ziglang/zig

- lib/std/mem/Allocator.zig
Reimplement `reallocBytes` after regression from #9394/#10112
Also adds an analogous `allocBytes` function.
@silversquirl / @mlugg: do these functions satisfy your requirements?
As the these functions don't return a slice with the alignment as part of the type I choose not to name them something like `reallocAdvancedWithRetAddrRuntimeAlignment` to seperate them from the other `alloc`/`realloc` functions.
closes #10348
> Allocator: `allocBytes` and `reallocBytes`

- lib/std/heap/general_purpose_allocator.zig
- src/stage1/codegen.cpp
- src/stage1/target.cpp
- src/stage1/target.hpp
Make `@returnAddress()` return for the BPF target, as the BPF target for the time being does not support probing for the return address. Stack traces for the general purpose allocator for the BPF target is also set to not be captured.
> stage1: deal with BPF not supporting @returnAddress()

- src/arch/aarch64/CodeGen.zig
- src/arch/aarch64/Emit.zig
- src/arch/aarch64/Mir.zig
This was implemented similarly to x86_64, by introducing a new MIR pseudo-instruction for pushing or popping multiple registers.
> stage2 AArch64: Implement saving callee-saved registers

- doc/docgen.zig
- lib/std/process.zig
- test/cli.zig
- test/compare_output.zig
I'm making this PR after receiving positive feedback regarding this from people on the Discord, including @SpexGuy and @N00byEdge. 
This changes the return type of `ArgIterator.next()` from `?(NextError![:0]u8)` to `NextError!?[:0]u8`. This change makes the `ArgIterator` much cleaner to use in `while` loops or `if` statements. For example:
```zig
while (it.next(allocator)) |arg_or_err| {
const arg = try arg_or_err;
```
Is now:
```zig
while (try it.next(allocator)) |arg| {
```
This is much better, as it storing an error union in a variable is usually a bad thing to do, and discourages handling the error immediately. Additionally, the convention in the std library is to use this order (`!?` as opposed to `?!`) -- I couldn't find any examples of the opposite order besides this one with grep.
> Change `ArgIterator.next()` return type

- lib/std/math/big/int.zig
- lib/std/math/big/int_test.zig
- lib/std/os.zig
- src/Air.zig
- src/AstGen.zig
- src/Liveness.zig
- src/Module.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/type.zig
- src/value.zig
- test/behavior/eval.zig
- test/behavior/eval_stage1.zig
- test/behavior/math.zig
- test/behavior/math_stage1.zig
This PR includes a bunch of things that are required for `page_allocator` to compile under stage 2. This includes the allocator itself as well as the allocation function:
```zig
const expect = std.testing.expect;
test "page allocator" {
const msg = "hello from heap memory\n";
const allocator = std.heap.page_allocator;
const mem = try allocator.alloc(u8, msg.len);
for (msg) |c, i| mem[i] = c;
asm volatile ("syscall"
:
: [number] "{rax}" (1),
[arg1] "{rdi}" (1),
[arg2] "{rsi}" (@ptrToInt(mem.ptr)),
[arg3] "{rdx}" (msg.len),
: "rcx", "r11", "memory"
);
}
```
(freeing does not work yet)
Error set related changes:
* Replaced the plain arrays used for the error values of `Module.ErrorSet` and Type `merged_error_set` with hash maps. This is to make error set subset …
> stage2: Make page_allocator work

- src/link/Elf.zig
Closes #6029 .
Should the `TextBlock` and `TextBlockList` be renamed to something like `DeclBlock` and `DeclBlockList` as they're no longer only in the `.text` section ?
I'd like to add tests to this PR, but I don't really know how. Should I use the `Case.addCompareObjectFile` method ?
I used the hello world example for testing :
```zig
pub export fn _start() noreturn {
print();
exit();
}
fn print() void {
asm volatile ("syscall"
:
: [number] "{rax}" (1),
[arg1] "{rdi}" (1),
[arg2] "{rsi}" (@ptrToInt("Hello, World!\n")),
[arg3] "{rdx}" (14)
: "rcx", "r11", "memory"
);
return;
}
fn exit() noreturn {
asm volatile ("syscall"
:
: [number] "{rax}" (231),
[arg1] "{rdi}" (0)
: "rcx", "r11", "memory"
);
unreachable;
}
```
Compiling this example without this PR produces this output when displaying …
> Constant data in rodata

- lib/std/elf.zig
Spotted a dead link while working on the compiler, thought it worthwhile to fix it so nobody has to go diving into the wayback maching :)
> Fix dead link

- lib/std/pdb.zig
I was debugging an unrelated issue with `procmon` and noticed that zig was doing this lookup to the filesystem a few thousand times. I doubt this has much performance impact in the grand scale of things, but removing that many calls into the system can't hurt, and it at least cleans up the `procmon` output.
> Only check the file's length once in `pdb.Msf.init`

- lib/std/testing.zig
before it started outputting the actual starting, not ending characters.
> fix expectStringEndsWith error output.

- src/arch/arm/CodeGen.zig
- test/stage2/arm.zig
This PR implements `is_null` and `is_non_null` for ptr-like optionals as well as `is_err` and `is_non_err` for error unions with zero-bit payloads.
The basic implementation of error unions brings stage2 ARM one step closer to `zig test`.
> stage2 ARM: basic implementation of optionals and error unions

- lib/std/wasm.zig
- src/link/Wasm.zig
- src/link/Wasm/Symbol.zig
The self-hosted linker will now emit names for all function, global and data segment symbols.
This increases the ability to debug wasm modules tremendously as tools like wasm2wat and browsers can use this information to generate named functions, globals etc, rather than placeholders such as `$f1`.
> Stage2: linker - Emit symbol names

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- src/arch/x86_64/PrintMir.zig
This is a pretty hefty PR which aims at cleaning up outright wrong lowerings that I've created when adding the MIR layer for `x86_64` a couple of weeks ago. Hopefully, with this PR landing, it will be easier and much clearer when anyone will want to add new codegen bits to the compiler.
The main changes worthy of mention include:
* every MIR callsite in the codegen code now follows Intel syntax `dst <- src`
* every MIR -> Isel selection function in `Emit.zig` is implemented via a lowering function specific to the desired instruction encoding - this is also where we will only ever use the `Encoder` struct, in the lowering functions (functions prefixed with `lower`) ~~(**still working on it**)~~
* every lowering function is now tested for correctness when emitting a single instruction in …
> stage2: rewrite MIR -> Isel layer for x86_64

- src/codegen/c.zig
- test/behavior.zig
* fix initialisation of void* fields of structs (initialises to NULL rather than {})
* don't generate fields where the type does not have codegen bits
* in airAlloc generate a void* local if the element type does not have codegen bits
> stage2: make tests/behaviour/void.zig work with c backend

- lib/std/mem.zig
> std: Skip `comptime` struct fields in `mem.zeroes()`

- src/arch/arm/CodeGen.zig
- src/codegen.zig
- test/stage2/arm.zig
Also upgrades `generateSymbol` in `codegen.zig` to generate arrays (most of the code is adapted from WASM codegen)
> stage2 ARM: implement slice_elem_val for types with size <= 4

- lib/std/fmt.zig
Fixed typo in deprecation error for `E` format specifier where it would instead complain about a specifier of `X`.
> Fixed typo in fmt.zig deprecation error message

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- src/arch/x86_64/PrintMir.zig
- test/stage2/x86_64.zig
* add separate tag for MI encoding - to request memory-immediate encoding at the MIR side, we are now required to use a new tag such as `mov_mem_imm` where the size of the memory pointer operand is encoded using the flags:
```zig
0b00 => .byte_ptr,
0b01 => .word_ptr,
0b10 => .dword_ptr,
0b11 => .qword_ptr,
```
* fix handling of `ah`, `bh`, `ch`, and `dh` registers (which are actually used as aliases to `dil`, etc. registers). Currenly, we treat them as aliases only meaning when we encounter `ah` we make sure to set the REX.W to promote the instruction to 64bits and use `dil` register instead - otherwise we might have mismatch between registers used in different parts of the codegen. In the future, we can and should use `ah`, etc. as upper 8bit halves of 16bit registers `ax`, etc.
* fix …
> stage2: more fixes to x86_64 codegen, mir and isel

- src/arch/arm/CodeGen.zig
- src/codegen.zig
- src/register_manager.zig
- test/stage2/arm.zig
Further progress towards `zig test`
> stage2 ARM: basic slice + basic struct support

- src/arch/x86_64/CodeGen.zig
- test/stage2/x86_64.zig
Implements:
* `isNull` and `isNonNull`
* `genSetReg` for `ptr_stack_offset`
* load address (pointer) to a stack variable in a register via
`lea` instruction
* store value on the stack via a pointer stored in a register via
`mov [reg], imm` instruction
* the lowerings naturally are handled automatically by Mir -> Isel
layer
* add initial (without safety) implementation of `.optional_payload`
* add matching stage2 test cases
> stage2: impl isNull/isNonNull, genSetReg for ptr_stack_offset, loading-storing via pointer (in register)

- src/stage1/codegen.cpp
- test/behavior/error_stage1.zig
Fixes #10468 
If I interpret src/Sema.zig correctly `@errorName` is not yet implemented in stage2.
> stage1: fix @errorName null termination

- lib/std/os/linux/io_uring.zig
Fixes the kernel version check in renameat/unlinkat/mkdirat/symlinkat/linkat.
I've tested the test binary on kernel 5.4 and 5.10; I haven't been able to build kernel 5.5 to 5.9 so I haven't tested those.
Fixes #10466
> io_uring: fix version check in tests

- lib/std/fmt.zig
- src/stage1/analyze.cpp
The current logic for parsing the format string in the format API is extremly inefficient and is a
big cause for the huge memory usage of the stage 1 compiler. This PR makes an attempt at improving
this by moving the logic for parsing the placeholders into its own function which the compiler can
then cache. This then causes the compiler to generate a lot less IR instructions, which improves
the memory usage by quite a bit. In theory, this is also an improvement for stage 2. As far as I
understand, then sematics of comptime arguments have not changed between the compilers, so stage 2
would produce a lot of IR instructions for the old format API as well.
related #6485 #9635 #9056
```
zig-master on  master
$ mkdir build
$ cd build
$ cmake .. -G Ninja -DZIG_PREFER_CLANG_CPP_DYLIB=on …
```
> fmt: Refactor parsing of placeholders into its own function

- src/Sema.zig
- test/behavior/type.zig
- test/behavior/type_info.zig
- test/behavior/type_info_stage1.zig
- test/behavior/type_stage1.zig
* Fixes a bug where comptime and inline functions would be called with generic poison arguments if the call appears in a non-evaluating context such as return types and depends on the type of another parameter.
* Implements `@Type` for pointers. One complication appears here with type info for sentinels, since those are of `anytype`. I temporarily hacked around that here by allowing coercions from `T` to `noreturn`, though i did not include that here since i felt it was kind of a hack. As a result, `@Type` for pointers without sentinels works, but only with type info created by `@typeInfo`.
* Moves a bunch of tests that now pass.
> stage 2 stuff

- lib/std/os/linux/io_uring.zig
This is an attempt to fix a bug I encountered while trying to reproduce #10462.
The following code can trivially trigger [this assert](https://github.com/ziglang/zig/blob/master/lib/std/os/linux/io_uring.zig#L304) on my machine:
```zig
const os = std.os;
const testing = std.testing;
var ring = try os.linux.IO_Uring.init(4, 0);
defer ring.deinit();
const path = "test_io_uring_write_read_fixed";
const file = try std.fs.cwd().createFile(path, .{ .read = true, .truncate = true });
defer file.close();
defer std.fs.cwd().deleteFile(path) catch {};
const fd = file.handle;
while (i < 10000000) : (i += 1) {
const sqe_write = try ring.write(0x45454545, fd, "foobar", 3);
sqe_write.flags |= os.linux.IOSQE_IO_LINK;
const …
```
> io_uring: improve IO_Uring.copy_cqe

- src/stage1/analyze.cpp
- test/stage1/c_abi/cfuncs.c
- test/stage1/c_abi/main.zig
See #10431 and [#9443](./9443) for context. Thus far this has been tested really only on Zig master on Linux x86_64, so I'm kinda relying on CI to highlight any potential breakage on other platforms.
Regarding tests, packed structs weren't tested at all in stage1 C ABI until this point, so I added relevant tests for both small and big packed structs, but C→Zig calls still don't support packed struct arguments so small struct cases wouldn't compile with a link to [#1481](./1481), so I left them commented out for now. If this isn't right, feel free to change or request changes as you see fit; this is my first time contributing *and* the first time I've dug through stage1 so I might be off base on this one.
For Github's sake: resolves #10431
> stage1: Fix LLVM C ABI type resolution for small packed structs

- lib/std/os/windows.zig
Can happen when e.g. trying to delete a file with the Read Only flag set
(was being triggered by the test added in #10486)
> Add CANNOT_DELETE as a possible error in os.windows.DeleteFile

- src/codegen/llvm.zig
- src/glibc.zig
- src/link.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/Wasm.zig
This commit fixes two problems:
* `zig build-obj` regressed from the cache-mode branch. It would crash
because it assumed that dirname on the emit bin path would not be
null. This assumption was invalid when outputting to the current
working directory - a pretty common use case for `zig build-obj`.
* When using the LLVM backend, `-fno-emit-bin` combined with any other
kind of emitting, such as `-femit-asm`, emitted nothing.
> linker: fix build-obj and -fno-emit-bin

- lib/std/wasm.zig
- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/arch/wasm/Mir.zig
- test/behavior.zig
Some refactoring has been done to implement initial sret arguments support.
This means that rather than returning a struct's stack pointer value, we now allocate enough stack space and provide a pointer to this as the first argument in a function call. The function types that Wasm requires support this as well, ensuring we pass the type checking.
Besides this, I implemented initial support for the extended opcode instructions that have been introduced in later versions of the wasm spec. This means that when the user enabled the `bulk-memory` feature, we will lower `memset` to wasm's `memory.fill` instruction, rather than lowering it to compiler_rt. When the feature is disabled, we lower the instructions manually. In the future, this use case will be a call to compiler_rt.
With those …
> Stage2: wasm - Pass more behavior tests

- doc/langref.html.in
I noticed this is missing and thought I should add it.
> Add missing package to the langref that's always available

- src/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/type.zig
- src/value.zig
- test/behavior.zig
- test/behavior/bit_shifting.zig
This required some llvm and struct+union work. Hope I did it right. Each commit contains reasoning for why this change was done
> Stage2 bit_shifting.zig passing

- src/Air.zig
- src/Liveness.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- test/behavior.zig
- test/behavior/error_llvm.zig
- test/behavior/error_stage1.zig
Implements `@errorName`. To this end i added a new air instruction, `error_name`, which is similar in semantics to `tag_name`. In the LLVM backend, `error_name` is implemented similar to the stage 1 compiler, by using an array of slices. Note that in the stage 2 compiler this comes with a number of caveats:
* In the stage 1 compiler, this table is directly emitted as an LLVM global array. In the stage 2 compiler, we only know the Module's complete global error set when all functions are analyzed. In order to avoid that, the error table is only generated right before `flushModule` is called, and `error_name` is generated by looking up a global pointer instead of an array. When generating the actual table, this global pointer is then updated with the address of the array. In theory this …
> stage2: @errorName sema+llvm

- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- test/behavior.zig
Implements the `@src` builtin. To this end i changed the Zir for `builtin_src` a bit so that it already contains the line and column, similar to `dbg_stmt`. This ensures that we do not need to load the source during Sema.
There is currently still a problem where `@src().file` doesn't return the full path.
> stage2: implement @src

- src/arch/wasm/CodeGen.zig
- test/behavior.zig
This gets all the array behavior tests passing.
Besides that, this also implements lowering struct constants which means `4560.zig` is passing once again.
> Stage2: wasm - implement arrays

- src/codegen.zig
- src/link/MachO.zig
- test/stage2/x86_64.zig
Put `Decl`s in different MachO sections.
Use `getDeclVAddrWithReloc` when targeting MachO backend rather than `getDeclVAddr` - this fn returns a zero vaddr and instead creates a relocation on the linker side which will get automatically updated whenever the target decl is moved in memory. This fn also records a rebase of the target pointer so that its value is correctly slid in presence of ASLR.
This commit enables `zig test` on x86_64-macos.
> stage2: enable zig test on x86_64-macos

- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/arch/wasm/Mir.zig
- test/behavior.zig
- test/behavior/cast.zig
- test/behavior/cast_int.zig
This implements the following:
- float_to_int and bitshifting to get `cast.zig` behavior tests passing.
- Optional comparison (`?u32 == u32`) to get `optionals.zig` passing.
- Basic 128 bit integer support for loading, storing and comparing.
(Equality comparison is currently implemented in the wasm backend itself, until compiler-rt is supported).
> Stage2: wasm - Implement optional equality, casts and more

- lib/std/hash_map.zig
Optimize `HashMap`.
- Add an `Metadata.isFree` helper method (not an optimization, just for clarity).
- Implement `Metadata.isTombstone` and `Metadata.isFree` with `@bitCast` then comparing to a constant. I assume `@bitCast`-then-compare is faster than the old method because it only involves one comparison, and doesn't require bitmasking.
- Summary of benchmark results (`gotta-go-fast`, run locally, compared to master):
- 3/4 of the hash map benchmarks used ~10% fewer cycles
- The last one (project Euler) shows 4% fewer cycles.
<details>
<summary>Benchmarks
- Measurements are from running the `gotta-go-fast` benchmarks locally on my laptop.
- `available`: Measures current master (a couple weeks out of date, but there haven't been any changes to hash_map in that time).
- …
> std: hash_map: optimize isFree/isTombstone

- lib/std/build.zig
- src/Compilation.zig
- src/link/Wasm.zig
- src/stage1.zig
- src/stage1/codegen.cpp
- src/stage1/stage2.h
- src/stage1/zig0.cpp
This exposes a function from stage2 to stage1 to append symbols to automatically export them.
Stage1 will only call this function when the target is wasm.
The linker will then only append `--export=<symbol>` for when the user has not done so manually and did not provide the `-rdynamic` flag also. This allows the user to still override the default behavior do they wish to.
I also went ahead and implemented the same behavior for the LLVM backend when using stage2, meaning we can remove all stage1 related code for this without losing the behavior when stage2 becomes the default compiler.
Closes #2910 
Closes #7133
> Stage2: wasm-linker - Only export symbols notated as such

- src/translate_c.zig
- test/run_translated_c.zig
- test/translate_c.zig
> translate-c: Handle typedef'ed void return type for functions.

- lib/std/Thread.zig
- lib/std/Thread/Condition.zig
Condition in 0.9 is broken. This fixes it and adds a test to hopefully not have that happen again.
> Fix a bug in std.Thread.Condition and add a basic Condition test.

- src/link/Wasm.zig
By placing the stack at the start of the memory section, we prevent the runtime from silently overwriting the static memory and instead trap on a stack overflow.
We do, however, allow users to overwrite this behavior by setting the `global-base` flag, which puts the stack at the end of the memory section and the static data at the base that was specified.
The reason a user would want to do this is when they need to put the static data at a specific address. Another benefit of doing so it has a side effect of lower binary size.
(Having the stack in front, means that accessing the memory after the stack has a bigger offset when loading/storing from memory. Bigger offsets mean it takes more bytes to represent the instruction).
Note: While we used to append this flag by default to wasm-ld, we …
> Stage2: wasm-linker - Place stack at the beginning of the linear memory

- lib/std/build.zig
Seems like the right solution, but who knows :shrug:
> Make prominent_compile_errors also work for test steps

- lib/std/bounded_array.zig
> Allow BoundArray to be default initialized

- src/translate_c.zig
- test/translate_c.zig
Fixes compiler attempting to use null value when translating macro define of float constant using scientific notation with no decimal point.
Fixes #10574.
> translate-c: Fix macro define of float constant using scientific notation

- lib/std/net.zig
Removes a hard coded null terminator and the associated assumeSentinel.  Replaced with the std.fmt.allocPrintZ which makes it clear what/why it's all happening.
> net: Use allocPrintZ to avoid needing assumeSentinel

- src/AstGen.zig
- src/Sema.zig
- src/Zir.zig
- src/codegen/c.zig
- src/print_zir.zig
- src/value.zig
- test/behavior/array.zig
- test/behavior/array_llvm.zig
- test/behavior/array_stage1.zig
- test/behavior/for.zig
Introduce `validate_array_init_comptime`, similar to
`validate_struct_init_comptime` introduced in
713d2a9b3883942491b40738245232680877cc66.
`zirValidateArrayInit` is improved to detect comptime array literals and
emit AIR accordingly. This code is very similar to the changes
introduced in that same commit for `zirValidateStructInit`.
The C backend needed some improvements to continue passing the same set
of tests:
* `resolveInst` for arrays now will add a local `static const` with the
array value and so then `elem_val` instructions reference that local.
It memoizes accesses using `value_map`, which is changed to use
`Air.Inst.Ref` as the key rather than `Air.Inst.Index`.
* This required a mechanism for writing to a "header" which is lines
that appear at the beginning of a function body, …
> stage2: detection of comptime array literals

- src/stage1/bigint.cpp
- test/behavior/floatop.zig
> stage1: fix bigint_init_bigfloat for single-limb negative floats

- lib/std/c.zig
- lib/std/c/darwin.zig
- lib/std/net.zig
- lib/std/net/test.zig
- lib/std/x/os/net.zig
Fixes https://github.com/ziglang/zig/issues/10521 and makes a couple of additional tests pass ~when linking libc~ for macOS.
> Use libc if_nametoindex for macOS when parsing IPs

- CMakeLists.txt
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Isel.zig
- src/arch/x86_64/Mir.zig
- test/stage2/x86_64.zig
* refactor handling of immediates in x86_64 backend
* rename Isel to Emit for x86_64
* implement signed compare
> stage2: rename Isel back to Emit, and fix immediate casts in Emit for x86 64

- lib/std/bounded_array.zig
This makes bounded array work more like how slicing works on normal array, where the mutability depends on the mutability of the thing you are slicing.
> Make slice function of BoundedArray return a slice with constness depending on the self pointer

- lib/std/multi_array_list.zig
Calling `insert` on a `std.MultiArrayList` currently fails with a compiler error due to using a `try` without the `!` annotation on the return type
This code:
```zig
this.list.insert(allocator, 0, listener);
```
Produces this error:
```zig
/Users/jarred/Build/zig/lib/std/multi_array_list.zig:192:13: error: expected type 'void', found '@typeInfo(@typeInfo(@TypeOf(std.multi_array_list.MultiArrayList(src.javascript.jsc.node.types.Listener).ensureUnusedCapacity)).Fn.return_type.?).ErrorUnion.error_set'
try self.ensureUnusedCapacity(gpa, 1);
```
Instead, it should produce this error:
```zig
./src/javascript/jsc/node/types.zig:955:33: error: error is ignored. consider using `try`, `catch`, or `if`
this.list.insert(allocator, 0, listener);
^
```
> Add missing `!void` in `std.MultiArrayList.insert`

- src/translate_c.zig
- test/translate_c.zig
* Fix incorrect result when the first digit after the decimal point is not 0-9 - eg `0x0.ap0`.
* Fix compiler panic when the number starts with `0X` with a capital `X` - eg `0X0p0`.
* Fix compiler panic when the number has a decimal point immediately after `0x` - eg `0x.0p0`.
Fixes #10581.
> translate-c: Fix issues translating macro define of hex float constant

- lib/std/c/linux.zig
Fixes ziglang#10543 on Linux.
I don't know whether this needs to be added for other operating systems as well.
> Fix os.rusage when linking with c library on Linux

- src/AstGen.zig
- test/behavior/misc.zig
Makes stage2 disallow underscores in int primitive type names (stage1 already disallowed underscores in int primitive type names).
Makes identifiers containing underscores not shadow int primitive types.
Fixes #10421.
> stage2: do not interpret identifier containing underscores (eg: u3_2) as int primitive type

- src/translate_c.zig
- test/translate_c.zig
Old:
unable to translate C expr: expected ')'
New:
unable to translate C expr: expected .RParen instead got .Ellipsis
Also, is `return m.fail(...);` supposed to be this instead?
```zig
try m.fail(...);
return error.ParseError;
```
I replaced two instances of `return m.fail(...);` in this pull request, but there are four more matches that I haven't changed.
> translate-c: improve error messages when expecting specific tokens

- lib/libc/include/generic-glibc/features.h
This was originally introduced in 4d48948b526337947ef59a83f7dbc81b70aa5723 but broken immediately afterwards in c8af00c66e8b6f62e4dd6ac4d86a3de03e9ea354.
In my use case, this fixes an undefined symbol when compiling libc++ with older versions of glibc (see #10614). libc++ checks for the existence of features using `__GLIBC_PREREQ`, which always passed since `__GNU_MINOR__` was hardcoded in the header.
I would also like to add a test for this, but I only found a single test that compiles a C++ file in `test/standalone/c_compiler`. Are you interested in more small tests which try to compile code with different versions of glibc?
Closes #10614 and if I am not mistaken the original change already closed #7508.
> glibc: fix passing of __GNU_MINOR__

- src/arch/x86_64/CodeGen.zig
- test/behavior/align.zig
- test/behavior/array.zig
* push the arguments in reverse order
* add logic for pushing args of any abi size to stack - very similar to `genSetStack` however uses `.rsp` as the base register
* increment and decrement `.rsp` if we called a function with args on the stack in `airCall`
* add logic for recovering args from the caller's stack in the callee
* add tweak to please Apple re stack alignment when calling extern functions - this is more like a temp hack than anything else as I think the mechanism we use for adjusting the stack when pushing function args onto the stack could/should be reused - i.e., we should just align the stack before each call and then reset the `.rsp` when we return from the callee rather than relying on the current hack
> stage2: fix passing arguments on the stack on x86_64

- src/link/MachO.zig
Fixes #9527 
Prior to this change, `__DATA,__bss` and `__DATA,__thread_bss` would get actually, physically written out to the output file, unnecessarily filling the output file with 0s.
This fix does not yet fully cover incremental side of the linker - in case we introduce a section in `__DATA` segment, we do not yet reorder the zerofills to be at the end of the segment (thus allowing us to conserve the filesize space), nor do we take into account that there is no need to grow zerofills in filesize when expanding the zerofill sections.
---
Quick verification using `bloaty` on the following Zig source:
```zig
$ cat hello.zig
var arr: [2000000]u8 = undefined;
arr[100] = 42;
std.log.info("All your codebase are belong to us!", .{});
}
$ zig …
```
> macho: do not write out ZEROFILL physically to file

- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/link/Wasm.zig
- src/link/Wasm/Atom.zig
- test/behavior/array.zig
- test/behavior/for.zig
Previously, the wasm backend would lower any type of constant to a stack value. For types such as structs, we'd then store it in the 'virtual' stack in the data section. This meant that lowering larger constants was done during runtime.
Not only was this inefficient, but it also meant that constants were not memoized, but regenerated on each reference. Making the binaries larger, and runtime slower.
After this PR, however, we now lower constants that are passed by reference (such as structs, arrays, etc) to bytes and store them in the `rodata` section. The linker generates a relocation for this constant and rewrites its actual address when we emit the final binary data. This means that now we re-use code (in `genTypedValue`), rather than implement the same logic twice. Constants are now …
> Stage2: wasm - Refactor lowering constants

- src/type.zig
Previously, optional slices returned the pointer size as abi size.
We now account for slices to calculate the correct size.
> Stage2: Fix abi size for optional slices

- src/Air.zig
- src/AstGen.zig
- src/Liveness.zig
- src/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/print_zir.zig
- src/type.zig
- test/behavior/array_llvm.zig
* AIR instruction vector_init gains the ability to init arrays and
tuples in addition to vectors. This will probably also gain the
ability to initialize structs and be renamed to `aggregate_init`.
* AstGen prefers to use an `anon_array_init` ZIR instruction for
local variables when the init expr is an array literal and there is
no type.
> stage2: implement tuples

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- src/arch/x86_64/PrintMir.zig
- src/link/Elf.zig
- src/link/MachO.zig
* Instead of using `push` and `pop` combo, we now re-use our stack allocation mechanism which means we don't have to worry about 16-byte stack adjustments on macOS as it is handled automatically for us. Another benefit is that we don't have to backpatch stack offsets when pulling args from the stack.
* By changing stack offset and ptr to stack offset from `u32` to `i32` in `MCValue`, we can use re-use most of the current functionality to read the arguments from the stack without the need to copy into the callee's locals.
* Fix an insufficient byte preallocation bug in `Emit.lowerToRm` lowering function.
> stage2: refactor how we preserve callee regs and how we pass args on the stack in x86_64 backend

- lib/std/build/RunStep.zig
I'm currently developing a application that returns non-error information using the exit code of the process, meaning using a `RunStep` causes `zig build` to treat all invocations as erroring.
This PR allows the `expected_exit_code` of `RunStep` to be set to `null` to signify that the exit code of the child should be ignored.
> build: RunStep can optionally ignore exit code of child process

- lib/std/array_hash_map.zig
- lib/std/multi_array_list.zig
Also fixes error with ArrayHashMap when both key and value are 0 sized.
Fixes #10618.
> MultiArrayList: Fix error when struct is 0 sized

- lib/std/fs/get_app_data_dir.zig
This is generally used to specify where to put user-specific data on linux, with the default being ~/.local/share as per the [xdg base dir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
> std/fs: Support `XDG_DATA_HOME`

- lib/std/os/windows.zig
The size of a `GUID` is not platform-dependent, it's always a fixed number of bits.  So I've updated `GUID` to use fixed bit integer types rather than platform-dependent C integer types.
Note that my guess is these C types were used because that's what the docs use, but the win32metadata project which feeds the new win32 API uses fixed-width integer types.
> use explicit integer bit widths for windows GUID

- lib/std/io/reader.zig
This is one way I see #9594 being solved. I hope I didn't get it too far off. I'm more than happy making any changes (and learn in the process)
I decided to start with `readUntilDelimiter` and `readUntilDelimiterOrEof` and submit this as draft to collect early feedbacks — which are more than welcome 🙂 I'll continue to the other `readUntilDelimiter*` functions.
Happy to propose my first contribution to Zig! 🎉 Thanks to @SpexGuy for suggesting me this issue.
> readUntilDelimiter*: read only if buffer not full

- build.zig
- lib/std/build.zig
- test/standalone/issue_794/build.zig
- test/standalone/issue_9812/build.zig
- test/standalone/link_interdependent_static_c_libs/build.zig
- test/standalone/link_static_lib_as_system_lib/build.zig
- test/standalone/objc/build.zig
- test/standalone/objcpp/build.zig
- test/standalone/static_c_lib/build.zig
- test/standalone/use_alias/build.zig
- test/tests.zig
An attempt to normalize some of the function names in build.zig.  I've elected to normalize `add*Dir` to `add*Path`.  Also I've replaced the "Lib" abbreviation with "Library" to make it more consistent with using "Include" rather than "Inc".
The PR does not remove the old names, only adds the new normalized ones to faciliate a transition period.
This PR is structured as a proposal where only the necessary changes have been submitted.  Follow up changes would be to substitute the new names with the old through the whole repository, and another change might include renaming the fields of the `Builder` type to correspond with the function names changes.
> Normalize some build function names

- lib/std/crypto/25519/scalar.zig
This operation is extremely useful for schemes using multiplicative blinding such as https://chris-wood.github.io/draft-wood-cfrg-eddsa-blinding/draft-wood-cfrg-eddsa-blinding.html
> std.crypto.25519.scalar: implement edwards25519 scalar field inversion

- src/arch/arm/CodeGen.zig
- src/arch/arm/Emit.zig
- src/arch/arm/Mir.zig
These were disabled during the MIR transition
> stage2 ARM: re-enable debug info for arguments

- src/arch/x86_64/PrintMir.zig
These MIR instruction were getting printed all on the same line.
before:
```
mov qword ptr [rbp + 4294967288], rcxmov qword ptr [rbp + 4294967280], rdi
```
after
```
mov qword ptr [rbp + 4294967288], rcx
mov qword ptr [rbp + 4294967280], rdi
```
> stage2: x64: fix printing of callee preserved regs instructions

- src/codegen/c.zig
- test/behavior.zig
This PR adds basic support for `union` to the C backend.
There are some differences vs. the union encoding in the LLVM backend:
- The payload/tag fields are not ordered based on their alignment
- Tagged unions with a 0-bit payload are not lowered directly to their tag type. 
Instead, they become a struct with an empty union as their payload field
Some additional fixes were needed to get `test/behavior/union.zig` to pass:
- Rendering `.elem_ptr` + `.enum_numbered` types
- (Not) rendering `void` function args
- Add `__` prefix to rendered identifiers, to avoid conflicts with reserved C keywords
This is also my first Zig PR, so I hope I haven't missed any important steps/guidelines.
Please let me know if anything needs fixing 👍
> stage2: Add `union` support to C backend

- lib/std/crypto.zig
> std.crypto.random: `Random`s are no longer passed by reference

- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/arch/wasm/Mir.zig
- test/behavior.zig
- test/behavior/alignof.zig
- test/behavior/bit_shifting.zig
- test/behavior/bugs/1277.zig
- test/behavior/bugs/1310.zig
- test/behavior/bugs/1381.zig
- test/behavior/bugs/1500.zig
- test/behavior/bugs/1735.zig
- test/behavior/bugs/2006.zig
- test/behavior/bugs/3112.zig
- test/behavior/bugs/3367.zig
- test/behavior/bugs/394.zig
- test/behavior/bugs/656.zig
- test/behavior/bugs/7250.zig
- test/behavior/generics_llvm.zig
- test/behavior/namespace_depends_on_compile_var.zig
- test/behavior/optional_llvm.zig
- test/behavior/union.zig
This PR implements unions for the wasm backend.
Besides unions, the following was done as well:
- genTypedValue for enums (needed for tagged unions and was previously always emitting 'undefined' as value).
- Directly use Type.abiSize() to determine load/store instruction rather than an own variant.
(Thanks to previous refactor PR this was now possible).
- Implement the `rem` instruction: Only had to be enabled and will allow better test runner features.
- Function calling through decl_ref.
Note that this moves all the behavior tests to the outer branch and each test case has been disabled individually for all non-passing backends.
> Stage2: wasm - Implement unions

- src/link.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/MachO/DebugSymbols.zig
Augment relocation tracking mechanism to de-duplicate potential
creation of base as well as composite types while unrolling
composite types in the linker - there is still potential for
further space optimisation by moving all type information into
a separate section `.debug_types` and providing references to
entries within that section whenever required (e.g., `ref4` form).
Currently, we duplicate type definitions on a per-decl basis.
Anyhow, with this patch, an example function signature of the following
type:
```zig
fn byPtrPtr(ptr_ptr_x: **u32, ptr_x: *u32) void {
ptr_ptr_x.* = ptr_x;
}
```
will generate the following `.debug_info` for formal parameters:
```
<1><1aa>: Abbrev Number: 3 (DW_TAG_subprogram)
<1ab>   DW_AT_low_pc      : 0x8000197
<1b3>   DW_AT_high_pc     : 0x2c
<1b7> …
```
> stage2: add implementation of pointer type in DWARF/ELF

- build.zig
- src/main.zig
This PR makes debug builds of the compiler use `GeneralPurposeAllocator` even when linking libc.
Without this change debug builds on targets that always link libc or when the compiler links libc for tracy would use `c_allocator` meaning the issues checked by `GeneralPurposeAllocator.deinit()` are not caught.
> stage2: always use GPA in debug builds

- lib/std/special/compiler_rt/os_version_check.zig
Before this commit, compiling an empty main with Stage 2 on macOS x86_64 results in
```
../stage2/bin/zig build-exe -ODebug -fLLVM empty_main.zig
error: sub-compilation of compiler_rt failed
[...]/zig/stage2/lib/zig/std/special/compiler_rt/os_version_check.zig:26:10: error: TODO: Sema.zirStructInit for runtime-known struct values
```
By assigning the value to a variable we can sidestep the issue for now.
> stage2: avoid inferred struct in os_version_check.zig

- lib/std/mem.zig
Closes #10670
This PR looks to make the `std.mem.sliceTo` documentation comment more readable by listing `an array` before, `a pointer to an array`.
> Update the documentation for std.mem.sliceTo for readability

- src/Compilation.zig
First step towards #10634.
Treating stub files as C++ allows to use zig c++ as a host
compiler for nvcc.
Treating cu files as C++ allow using zig c++ as a host compiler in
CMake. CMake calls the host compiler with -E on a cu file to identify
the compiler.
Using zig c++ to directly compile CUDA code is untested.
> zig cc: Treat cu files as C++ source files

- doc/langref.html.in
This PR adds a note to the language reference about implicit dereferencing of pointers to structs when accessing fields.
This PR is intended to resolve issue #10325
> Added documentation for implicit struct pointer dereferencing

- lib/std/array_list.zig
This is a common operation and matches the API on other stdlib collections like HashMap and MultiArrayList.
cc @SpexGuy, as discussed on Discord.
> Add ArrayList.clone

- lib/std/start.zig
This fixes the:
`root source file has no member called 'main'`
issue when defining:
`pub const io_mode = .evented;`
and using `wWinMain`, `--subsystem windows`, e.g.:
`pub fn wWinMain(instance: win.HINSTANCE, prevInstance: ?win.HINSTANCE, cmdLine: win.PWSTR, showCode: c_int) c_int`
`initEventLoopAndCallWinMain` was calling `callMainAsync` instead of the `WinMain`.
> Fix startup procedure for async WinMain

- doc/langref.html.in
the code example immediately following `@truncate`'s introduction is a demonstration of `@intCast`'s undefined behavior on oversized values. this misled myself and another person when trying to answer a question, so here's a clearer arrangement with links between `@truncate` and `@intCast`.
> docs: reorganize `@truncate` and `@intCast` for clarity

- lib/std/os/linux.zig
Before this change it was truncating the uid and gid to u16 on 32-bit targets.
> fchown: use the 32-bit uid/gid variant of the syscall on 32-bit linux targets.

- lib/std/elf.zig
- lib/std/mem.zig
- lib/std/tz.zig
- src/link/Elf.zig
- src/link/MachO/fat.zig
To match the renaming of `@bswap` to `@byteSwap` in https://github.com/ziglang/zig/commit/1fdb24827fb51351d5e31103069619668fae31c4.
> Rename mem.bswapAllFields to byteSwapAllFields

- lib/std/fmt.zig
- lib/std/fmt/errol.zig
This commit fixes an out of bounds write that can occur when formatting certain float values. The write messes up the stack and causes incorrect results, segfaults, or nothing at all, depending on the optimization mode used.
The `errol` function writes the digits of the float into `buffer` starting from index 1, leaving index 0 untouched, and returns `buffer[1..]` and the exponent. This is because `roundToPrecision` relies on index 0 being unused in case the rounding adds a digit (e.g rounding 999.99 to 1000.00). When this happens, pointer arithmetic is used [here](https://github.com/ziglang/zig/blob/0e6d2184cacf2dd1fad7508b2f9ae99d78763148/lib/std/fmt/errol.zig#L61-L65) to access index 0 and put the ones digit in the right place.
However, `errol3u` contains two special cases: `errolInt` …
> fmt: fix out-of-bounds array write in float printing

- lib/std/mem.zig
Find the index of the smallest/largest number in a slice, without traversing it twice.
closes #9891
> std.mem: add indexOfMin and indexOfMax

- doc/docgen.zig
- lib/std/Thread.zig
- lib/std/fs.zig
- lib/std/fs/file.zig
- lib/std/fs/test.zig
- lib/std/fs/watch.zig
- src/Cache.zig
- src/test.zig
Closes #10540, and is an alternate solution to #10541.
> fs: Use `OpenMode` enum instead of read/write flags.

- src/Autodoc.zig
this fixes this case:
```zig
const Foo = usize;
const Bar = u6;
```
@kristoff-it
I also cleaned up to not hardcode /home/kristoff
I can't test it in a browser since you didn't push the js.
> autodoc: generate WalkResults for ref types

- lib/std/os/windows.zig
I found that after switching from my custom Guid parser to the one in std that it increased zigwin32 build times substantially (from 40 seconds to over 10 minutes).  More information can be found in the benchmark PR I created here: https://github.com/ziglang/gotta-go-fast/pull/21 .  This PR ports my GUID parser to std so all projects can leverage the faster comptime performance.
I also added a `parseNoBraces` function (which `parse` calls into) that supports parsing guids that don't have surrounding braces.
> improve comptime windows GUID.parse performance

- lib/std/math/isnormal.zig
These cases had all the top bits set, so adding would cause an overflow, despite the high bits being immediately masked out.
I'm having trouble with fully building and testing my local copy of `zig`, so apologies if I've made basic errors, but I figured this was a simple enough fix that it more worth submitting an untested PR than opening an issue; I also tested outside of `std`.
> Fix overflow in std.math.isNormal when applied to -Inf or a negative NaN

- lib/std/process.zig
The buffer allocated by `argsAlloc()` was allocating more bytes than needed. Since the buffer size is recalculated from the actual arguments length in `argsFree()`, a slice with a different length was passed to `allocator.free()`, triggering an error when using `std.heap.GeneralPurposeAllocator` with a large enough argument payload (>2048 bytes on my setup).
The buffer `buf` contains N (= `slice_sizes.len`) slices followed by the N null-terminated arguments. The N null-terminated arguments are stored in the `contents` array list. Thus, `buf` size should be:
```zig
@sizeOf([]u8) * slice_sizes.len + contents_slice.len
```
Instead of:
```zig
@sizeOf([]u8) * slice_sizes.len + contents_slice.len + slice_sizes.len
```
> fix std.process.argsAlloc buffer size

- lib/std/fs.zig
complex and needed to define set in consumer functions
> std: define static error set for fs.Dir.copyFile

- lib/std/fs.zig
- lib/std/fs/test.zig
This fixes the use of multiple `Iterator`s in a row on a directory. Previously, on many platforms, using an `Iterator` on an already-iterated directory would give no entries.
Fixing this involved seeking to the beginning of the directory on the first call of `next()`.
cc: @nektro @squeek502 
fixes #10317
> std: Fix using `fs.Dir.Iterator` twice

- src/libcxx.zig
fixes https://github.com/ziglang/zig/issues/10719
compiler_rt already provides __muloti4 but libc++ is also providing it and when linking libc++ it causes a crash on my windows x86_64 machine.
> remove __muloti4 from libc++

- doc/docgen.zig
- lib/std/process.zig
- lib/std/unicode.zig
- src/main.zig
- test/cli.zig
- test/compare_output.zig
I hit the "quotes in an RSP file" issue when trying to compile gRPC using `zig cc`.
This modifies (and renames) `ArgIteratorWindows` in process.zig such that it works with arbitrary strings (or the contents of an RSP file).
In main.zig, this new `ArgIteratorGeneral` is used to address the "TODO" listed in `ClangArgIterator`. 
This change is meant to close out issue #4833
**Benefits:**
- It has the nice attribute of handling "RSP file" arguments in the same way it handles `cmd_line` arguments.
- High Performance, minimal allocations
- Fixed bug in previous `ArgIteratorWindows`, where final trailing backslashes in a command line were entirely dropped
- Added a test case for the above bug
- Harmonized the `ArgIteratorXxxx.initWithAllocator()` and `next()` interface across Windows/Posix/Wasi …
> More response file support

- src/stage1/ir.cpp
While trying to experiment with https://github.com/ziglang/zig/issues/2647#issuecomment-1024083146, I noticed that in `ir.cpp`, that the code of `is_tagged_union` is replicated in several locations, making it harder to read.
Although it is unlikely (at least for now) that I upstream the whole partial implementation of 2647 once I get it to work (which is also not that likely), I'll try to upstream all unrelated fixes and such that I encounter along the way.
> `ir.cpp`: use `is_tagged_union` to DRY

- src/arch/riscv64/CodeGen.zig
- src/arch/riscv64/bits.zig
Follow-up to #10701 for RISCV64
Also adds a simplification to `bits.zig` where `Register` and `RawRegister` are merged into one enum similar to the `bits.zig` for other architectures.
> stage2 RISCV64: Move to new regalloc freeze API

- lib/std/debug.zig
This commit fixes two related things:
1. If the loop goes all the way through the slice without a match, on
the last iteration `mid == symbols.len - 1` which causes
`&symbols[mid + 1]` to be out of bounds. Handle this by clamping
the value to the length of the slices.
2. If the address we're looking for is greater than the address of the
last symbol in the `symbols` slice, we now match it to that symbol. Previously,
we would miss this case since we only matched if the address was _in
between_ the address of two symbols.
Closes https://github.com/ziglang/zig/issues/10666.
> debug: fix edge cases in macOS debug symbol lookup

- src/AstGen.zig
- src/Module.zig
- src/Zir.zig
- src/arch/x86_64/Emit.zig
- src/link/Elf.zig
Clarify that `astgen.advanceSourceCursor` already increments absolute
values of the line and columns numbers; i.e., `GenZir.calcLine` is thus
not only obsolete but wrong by design.
Incidentally, this clean up allows for specifying the `FnDecl` line
numbers for DWARF use correctly as relative values with respect to
the start of the parent `Decl`. This `Decl` in turn has its line number
information specified relatively to its parent `Decl`, and so on, until
we reach the global scope.
Supersedes #10676
> astgen: clean up source line calculation and management

- lib/std/fmt/parse_hex_float.zig
- test/behavior/math.zig
Addressing #10737, corrected the rounding logic in float128 parsing. Using [golang logic](https://github.com/golang/go/blob/a5c0b190809436fd196a348f85eca0416f4de7fe/src/strconv/atof.go#L528) (original source as the comment says) no longer produces the off-by-one error.
> std: correct rounding in parse_hex_float.zig

- lib/std/array_hash_map.zig
- lib/std/builtin.zig
- lib/std/hash/auto_hash.zig
- lib/std/hash_map.zig
- src/InternArena.zig
- src/codegen/spirv/type.zig
- src/type.zig
- src/value.zig
which is the index of the key that already exists in the hash map.
This enables the use case of using `AutoArrayHashMap(void, void)` which
may seem surprising at first, but is actually pretty handy!
This commit includes a proof-of-concept of how I want to use it, with a
new InternArena abstraction for stage2 that provides a compact way to
store values (and types) in an "internment arena", thus making types
stored exactly once (per arena), representable with a single u32 as a
reference to a type within an InternArena, and comparable with a
simple u32 integer comparison. If both types are in the same
InternArena, you can check if they are equal by seeing if their index is
the same.
What's neat about `AutoArrayHashMap(void, void)` is that it allows us to
look up the indexes by key, *without …
> std: make ArrayHashMap eql function accept an additional param

- src/Sema.zig
- test/behavior/math.zig
This makes the `"compare undefined literal with comptime_int"` behavior test pass.
This focused on just fixing this one test, but in the process I found a lot of weird behavior around "undefined" with stage1 (and therefore was unsure what the expected behavior was in stage2). I'll open another issue about that. 
This is my first time making a Zig compiler PR so please let me know if I should run any other commands. The only commands I ran was `test-stage2` and then the stage2 behavior tests runner with `zig2 test ../test/behavior.zig ...`
> stage2: cmp between untyped undefines values results in undef bool

- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
- src/link/Elf.zig
- test/behavior.zig
- test/behavior/cast.zig
- test/behavior/struct.zig
* start moving to new regalloc freeze API
* handle `struct_field_ptr` for `register` mcv
* handle `struct_field_ptr` for `stack_offset` mcv
* pass more behaviour tests
UPDATE:
Additionally,
* pad out (non-packed) struct fields when lowering to bytes to be saved in the binary - prior to this change, fields would be saved at non-aligned addresses leading to wrong accesses
* add a matching test case to `behavior/struct.zig` tests
* fix offset to field calculation in `struct_field_ptr` on `x86_64`
> stage2: handle more MCValue types in `struct_field_ptr` in x86_64 and pad out nonpacked struct fields when lowering to bytes (all targets incl wasm32)

- lib/std/builtin.zig
- lib/std/crypto/benchmark.zig
- lib/std/enums.zig
- lib/std/json.zig
- lib/std/mem.zig
- lib/std/meta.zig
- lib/std/zig/Ast.zig
- lib/std/zig/parse.zig
- lib/std/zig/render.zig
- src/AstGen.zig
- src/stage1/all_types.hpp
- src/stage1/codegen.cpp
- src/stage1/ir.cpp
- test/behavior/struct_llvm.zig
- test/behavior/type_info.zig
- test/behavior/type_stage1.zig
- test/behavior/union_stage1.zig
- test/compile_errors.zig
> remove anytype fields from the language

- src/Sema.zig
- src/link/MachO.zig
- test/stage2/aarch64.zig
- test/stage2/x86_64.zig
Fixes #10765
Changes:
* sema: do not pass libc or libc++ to the linker as system libs on the linker line `-lc` and `-lc++` - they are handled separately via link options flags
* macho: handle bss like normal section in stage2 - this is just a temporary workaround until I work out how to manage non-physical sections between incremental updates
* update stage2 tests to use name-qualified import lib names for externs:
From:
```zig
extern fn write(...);
```
to
```zig
extern "c" fn write(...);
```
cc @schmee
> stage2: handle name-qualified imports in sema, add a zerofill sections workaround to incremental macho

- src/link/Elf.zig
- test/behavior.zig
- test/behavior/bugs/1486.zig
With special dedication to @joachimschmidt557 ;-)
This is the first commit in what probably will be a series of commits and rewrites of the ELF linker. For now, refactors how we handle different phdrs and shdrs with a caveat that, in incremental context, there is always a one-to-one mapping between the two, while in traditional context, we will have one-to-many (for better filesize results).
> elf: add basic handling of .data section

- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/arch/wasm/Mir.zig
- src/link/Wasm.zig
- test/behavior.zig
- test/behavior/array_llvm.zig
- test/behavior/bugs/1025.zig
- test/behavior/bugs/1741.zig
- test/behavior/bugs/1914.zig
- test/behavior/slice.zig
The virtual stack has been slightly refactored to account for the alignment of the local variables.
This means that a local variable such as
```zig
var x: u32 align(128) = 10;
```
Will now work correctly.
We do this by calculating the total stack size that will then be forward aligned by the alignment of the largest type.
For the curious reader, the full explanation can be read in the commit message of e35414bf5c356798f201be85303101f59220326c
Besides this change, it also implements `elem_ptr` and `vector_init` instructions which makes the remaining array and slice behavior tests passing.
> stage2: Wasm - Account for stack alignment

- src/Sema.zig
- test/behavior/math.zig
Catching the cmp in Sema stops it's being ordered against zero (which results in a hard crash). Also supported the logic of `(nan != nan) == true` is easier and less hacky compred to if it was to be handled lower down the chain. `float80` has been ommited as it does not seem to be supported that well in stage2 (crashes trying to access to `math.nan_f80`, no ability to `@bitCast` into `f80`).
> stage2: cmp between nans

- doc/langref.html.in
This PR includes @yurapyon's fixes from #6162 *without* the changes to address #5939, in addition to changes to address (most of) the questions raised in #1854.
This should close ##5345 and #5730 (most of the latter should already have been covered by #8630, but I've also explicitly included an example of an enum literal using the `@""` identifier syntax so that someone searching for `.@` will land in the correct place)
For #1854, the "EDITING" fixes are trivially included, "QUERIES" A/B/C/D have hopefully been addressed, E seems obsolete (`@sqrt` with an `f16 var` worked fine locally during my testing so I assume it doesn't need to be called out), F seems to have already been addressed in the current docs by an example which makes it clear IMO. With respect to the "OMISSIONS" regarding …
> Various documentation fixes

- lib/std/process.zig
- src/main.zig
Closes  #10787
Not sure whether we should accept single quotes for windows, I'm guessing not?
> std.process: add option to support single quotes to ArgIteratorGeneral

- lib/std/builtin.zig
- lib/std/target.zig
- lib/std/zig.zig
- src/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/link.zig
- src/link/NvPtx.zig
- src/stage1/all_types.hpp
- src/stage1/analyze.cpp
- src/stage1/codegen.cpp
- src/stage1/ir.cpp
Nvptx aka [NVidia Parallel Thread Execution](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html) is a high-level assembly for Nvidia GPUs.
This PR aims to allow Stage 2 to generate this format, and therefore enable GPU programming in Zig.
This is a follow up on issue #10064 , and contains work presented at last [Zig Rush](https://youtu.be/rvfsWm6TckA?t=5351)
To generate the .ptx file we leverage the Nvptx LLVM backend.
The main thing we need to do is to ask LLVM to produce the assembly instead of the binary.
That's why we have a custom Linker that just pass most function calls to LLVM. 
Only we intercept `flushModule` and modify the `Compilation` object to ask for assembly instead of binary.
In NVPTX functions that can be launched from the host (CPU) are named kernel and …
> Add Stage2 support for Nvptx target

- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/register_manager.zig
>  * Runtime crashes are better than bugs.
Previously, when the register manager ran out of registers, it would just return registers as if nothing went wrong, except that the registers which couldn't be allocated were `undefined`.
Also improves documentation for `freezeRegs` and `unfreezeRegs` with some comprehensive examples.
> stage2 regalloc: Introduce error.OutOfRegisters

- src/arch/x86_64/CodeGen.zig
For PIE targets, we defer getting an address of value until the linker
has allocated all atoms and performed the relocations. In codegen,
we represent this via `MCValue.linker_sym_index` value.
> x86_64: add distinct MCValue representing symbol index in the linker

- lib/std/math.zig
- lib/std/special/compiler_rt.zig
- lib/std/special/compiler_rt/addXf3.zig
- lib/std/special/compiler_rt/compareXf2.zig
- lib/std/special/compiler_rt/extendXfYf2.zig
- lib/std/special/compiler_rt/extend_f80.zig
- lib/std/special/compiler_rt/truncXfYf2.zig
- lib/std/special/compiler_rt/trunc_f80.zig
- src/stage1/codegen.cpp
No tests but I have fuzzed them against hw a bit, might not work correctly for big-endian, and forcing f80 to be 16 bytes on x86 also seems to have some issues.
> Add compiler-rt functions for f80

- lib/std/build.zig
- lib/std/special/build_runner.zig
- src/stage1/zig0.cpp
These options were removed in 5e63baae8 but some remainders were left in.
> CLI: remove remainders of --verbose-ast and --verbose-tokenize

- src/AstGen.zig
- test/behavior/basic.zig
An attempt to address https://github.com/ziglang/zig/issues/10816 by imitating what's already happening for [switch expressions](https://github.com/ziglang/zig/blob/master/src/AstGen.zig#L5936-L5959).
With this commit applied, `ast-check -t` now produces the output expected in the issue:
```
%0 = extended(struct_decl(parent, Auto, {
[41] export entry line(2) hash(7a2ff26191c0207ee25eab8aafc47359): %1 = block_inline({
%22 = func(ret_ty={
%2 = break_inline(%22, @Ref.void_type)
}, body={
%3 = dbg_stmt(2, 5)
%4 = alloc_mut(@Ref.bool_type) node_offset:4:5
%5 = store_node(%4, @Ref.bool_true) node_offset:4:22
%6 = dbg_stmt(3, 5)
%11 = block({
%8 = load(%4) node_offset:5:75
%9 = as_node(@Ref.bool_type, %8) node_offset:5:75
%10 = condbr(%9, {
%12 = int(32768)
%13 = as(@Ref.u16_type, %12)
%15 = …
```
> stage2: apply type coercion in if expressions

- src/Sema.zig
Fixes a memory leak when generating the instructions for a switch case's body.
As `prev_then_body` is being overwritten, we only free the last case, but never the previous instruction lists that were overwritten. This change ensures it will be freed before we overwrite it.
> Sema: Fix memory leak

- lib/std/math/big.zig
- lib/std/math/big/int.zig
- lib/std/math/big/int_test.zig
This adds a new path which avoids using compiler_rt generated div
udivmod instructions in the case that a divisor is less than half the
max usize value. Two half-limb divisions are performed instead which
ensures that non-emulated division instructions are actually used. This
does not improve the udivmod code which should still be reviewed
independently of this issue.
Notably this improves the performance of the toString implementation of
non-power-of-two bases considerably.
Division performance is improved ~1000% based on some coarse testing.
The following test code is used to provide a rough comparison between
the old vs. new method.
```zig
const Managed = std.math.big.int.Managed;
const allocator = std.heap.c_allocator;
fn fib(a: *Managed, n: usize) !void { …
```
> std/math: optimize division with divisors less than a half-limb

- build.zig
- lib/std/build.zig
- lib/std/build/RunStep.zig
- lib/std/child_process.zig
- lib/std/process.zig
- src/Compilation.zig
- src/ThreadPool.zig
- src/libc_installation.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/Wasm.zig
- src/main.zig
- src/mingw.zig
- src/test.zig
- test/tests.zig
In accordance with the requesting issue (#10750):
- `zig test` skips any tests that it cannot spawn, returning success
- `zig run` and `zig build` exit with failure, reporting the command the cannot be run
- `zig clang`, `zig ar`, etc. already punt directly to the appropriate clang/lld main(), even before this change
- Native `libc` Detection is not supported
Additionally, `exec()` and related Builder functions error at run-time, reporting the command that cannot be run
> Avoid depending on child process execution when not supported by host OS

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- src/arch/x86_64/PrintMir.zig
- src/link.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/MachO/Atom.zig
- src/link/Plan9.zig
- test/behavior/align.zig
- test/behavior/cast.zig
- test/behavior/struct.zig
- test/stage2/x86_64.zig
* link: add a virtual function `lowerUnnamedConsts`, similar to
`updateFunc` or `updateDecl` which needs to be implemented by the
linker backend in order to be used with the `CodeGen` code
* elf: implement `lowerUnnamedConsts` specialization where we
lower unnamed constants to `.rodata` section. We keep track of the
atoms encompassing the lowered unnamed consts in a global table
indexed by parent `Decl`. When the `Decl` is updated or destroyed,
we clear the unnamed consts referenced within the `Decl`.
* macho: implement `lowerUnnamedConsts` specialization where we
lower unnamed constants to `__TEXT,__const` section. We keep track of the
atoms encompassing the lowered unnamed consts in a global table
indexed by parent `Decl`. When the `Decl` is updated or destroyed,
we clear the unnamed …
> stage2: lower unnamed constants in Elf and MachO

- lib/std/mem.zig
- test/run_translated_c.zig
> std: Allow `mem.zeroes` to work at comptime with extern union

- lib/std/special/compiler_rt.zig
- lib/std/special/compiler_rt/addo.zig
- lib/std/special/compiler_rt/addodi4_test.zig
- lib/std/special/compiler_rt/addosi4_test.zig
- lib/std/special/compiler_rt/addoti4_test.zig
- lib/std/special/compiler_rt/mulo.zig
- approach by Hacker's Delight with wrapping addition
- ca. 1.10x perf over the standard approach on my laptop
- tests with all combinations of min,max with -1,0,+1 and combinations of
sequences +-1,2,4..,max
> compiler_rt: add addo

- src/Module.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/value.zig
* add new `Decl` subtype, `Decl.ExternFn` - `ExternFn` will contain a maybe-lib-name if it was defined with the `extern` keyword like so
```zig
extern "c" fn write(usize, usize, usize) usize;
```
`lib_name` will live as long as `ExternFn` decl does.
---
TODO
> stage2: store externs lib name as part of decl

- src/arch/arm/CodeGen.zig
- test/behavior/struct.zig
* implement `struct_field_ptr` when `MCValue == .stack_argument_offset`
* enable simple `struct` test for ARM
> stage2,arm: add lowering of unnamed consts

- lib/std/bit_set.zig
For large ranges, this is faster than having the caller call setValue() for
each index in the range. Masks wholly covered by the range can be set to
the new mask value in one go, and the two masks at either end that are
partially covered can each set the covered range of bits in one go.
> std.bit_set: add setRangeValue(Range, bool)

- lib/std/c/darwin.zig
- lib/std/c/darwin/aarch64.zig
- lib/std/c/darwin/x86_64.zig
- lib/std/debug.zig
Produces the following output on a M1 MacBook Pro, macOS Monterey 12.2:
```
$ cat segfault.zig
const a = @intToPtr(*u8, 123123).*;
std.debug.print("{d}", .{a});
}
$ ./build/zig build-exe segfault.zig && ./segfault
Segmentation fault at address 0x1e0f3
/Users/<USER>/repos/zig/segfault.zig:4:37: 0x104a6077c in main (segfault)
const a = @intToPtr(*u8, 123123).*;
^
/Users/<USER>/repos/zig/build/lib/zig/std/start.zig:551:22: 0x104a626cf in std.start.callMain (segfault)
root.main();
^
/Users/<USER>/repos/zig/build/lib/zig/std/start.zig:495:12: 0x104a60a83 in std.start.callMainWithArgs (segfault)
return @call(.{ .modifier = .always_inline }, callMain, .{});
^
/Users/<USER>/repos/zig/build/lib/zig/std/start.zig:460:12: 0x104a609af in std.start.main …
```
> debug: implement segfault handler for macOS aarch64

- lib/std/child_process.zig
This was found on a user's machine when calling "git" as a child process from msys.  Instead of getting `BROKEN_PIPE` on `GetOverlappedResult` like we currently expect, it would occur on `ReadFile` which we are currently ignoring, which would then cause collectOutputWindows to hang because the async operation was never started.
With this patch, `zig build` no longer hangs on their machine when collecting output from child processes.  This bug could also be causing intermittent "hangs" in the CI on windows.
> child_process: collectOutputWindows handle broken_pipe from ReadFile

- src/Air.zig
- src/Liveness.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/stage1/codegen.cpp
- src/value.zig
- test/behavior/floatop.zig
- test/behavior/floatop_stage1.zig
- test/behavior/math.zig
This is my first contribution to stage2 and hopefully it's not a complete mess, all feedback is appreciated!
Support for f128, comptime_float, and c_longdouble require improvements to compiler_rt and will implemented in a later PR. Some of the code in this commit could be made more generic, for instance `llvm.airSqrt` could probably be `llvm.airUnaryMath`, but let's cross that bridge when we get to it.
My tentative plan going forward is:
1. Implement a bunch more unary operators (`@floor`, `@ceil`, `@sin`, `@cos`) for `f{16,32,64}` to get a feel for how it's going to look with multiple operators implemented.
2. Try to understand how compiler_rt works, and make the necessary changes to support f128 for the operators implemented in Step 1.
3. Implement the remaining operators for all float …
> stage2: implement @sqrt for f{16,32,64}

- lib/std/special/test_runner.zig
- lib/std/start.zig
- src/arch/wasm/CodeGen.zig
- src/link/Wasm.zig
- src/link/Wasm/Symbol.zig
- test/stage2/wasm.zig
This updates the test runner for stage2 to emit to stdout with the passed, skipped and failed tests similar to the LLVM backend.
Another change to this is the start function, as it's now more in line with stage1's.
The stage2 test infrastructure for wasm/wasi has been updated to reflect this as well.
> stage2: wasm - update test runner

- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
- src/value.zig
- test/behavior/bugs/1025.zig
- test/behavior/bugs/1277.zig
- test/behavior/bugs/1310.zig
- test/behavior/bugs/1500.zig
* pass more x64 behavior tests
* return with a TODO error when lowering a decl with no runtime bits
* insert some debug logs for tracing recursive descent down the
type-value tree when lowering types
* print `Decl`'s name when print debugging `decl_ref` value
> stage2: tiny improvements all over the place

- src/arch/wasm/CodeGen.zig
Rather than using runtime to perform pointer arithmetic to set the stack offset as a pointer into a local, we now store the offset as a `WValue` from the bottom of the stack. This has the benefit of fewer instructions, fewer locals, and less performance impact when we allocate a value on the virtual stack.
The way this works is that rather than having each stack value have its own local, we re-use the local that represents the bottom of the stack. Then, whenever we do a `load` or `store` operation, we use the offset stored in the `WValue` as part of the instruction, as wasm allows providing an offset for the memory operations.
This is a continuation from #10780
> stage2: wasm - Store stack-offset as WValue

- lib/std/Thread.zig
- lib/std/Thread/RwLock.zig
Currently RwLock does not build.  This updates it to use static initialization like the other synchronization primitives.
> update RwLock to use static initialization

- src/arch/x86_64/CodeGen.zig
- test/behavior/basic.zig
Make sure we don't panic when running behavior tests on `x86_64-macos`.
> stage2: handle direct and got load for stack args on x86_64-macos

- src/arch/x86_64/abi.zig
- src/stage1/analyze.cpp
- test/stage1/c_abi/build.zig
- test/stage1/c_abi/cfuncs.c
- test/stage1/c_abi/main.zig
I have a more robust solution in mind for this problem in general:
https://github.com/ziglang/zig/blob/master/src/arch/x86_64/abi.zig
But this PR is intended to be a minimally invasive bug fix to address a regression from 0.8.1.
closes #10445
> stage1: fix x86 i128 C ABI for extern structs

- src/stage1/ir.cpp
- test/compile_errors.zig
@kristoff-it  mentioned that this error message could be improved.
Most often the code is missing a 'try'. The error message should reflect that.
before:
```
./src/main.zig:6:24: error: expected type '[]const u8', found '@typeInfo(@typeInfo(@TypeOf(getValue)).Fn.return_type.?).ErrorUnion.error_set![]const u8'
printValue(getValue());
```
after:
```
./src/main.zig:6:24: error: Can not convert error union to payload type. Missing 'try'?
Expected type '[]const u8', found '@typeInfo(@typeInfo(@TypeOf(getValue)).Fn.return_type.?).ErrorUnion.error_set![]const u8'
printValue(getValue());
```
code
```zig
var gpa = std.heap.GeneralPurposeAllocator(.{}){};
printValue(getValue());
}
fn printValue(str: []const u8) void {
std.debug.print("{s}", …
```
> stage 1: improve error message if error union is cast to payload

- src/arch/wasm/CodeGen.zig
- src/link/Wasm.zig
- test/behavior.zig
- test/behavior/bugs/2578.zig
- test/behavior/bugs/3007.zig
- test/behavior/cast_llvm.zig
- test/behavior/fn.zig
Implements the `field_ptr` value for pointer types when generating decls.
This also fixes and updates miscellaneous changes of which all details can be found in the commit messages.
> stage2: Wasm - implement field_ptr

- src/arch/aarch64/CodeGen.zig
- src/arch/aarch64/Emit.zig
- src/arch/aarch64/Mir.zig
- src/arch/arm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- src/arch/x86_64/PrintMir.zig
- src/codegen.zig
- src/link.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/Plan9.zig
- test/behavior.zig
- test/behavior/basic.zig
- test/behavior/slice.zig
* x64 + arm codegen: handle lowering of const slice pointers
* elf: store pointer relocations indexed by containing atom - in `getDeclVAddr` it may happen that the target `Decl` has not been allocated space in virtual memory. In this case, we store a relocation in the linker-global table which we will iterate over when flushing the module, and fill in any missing addresses in the final binary. Note that for optimisation, if the address was resolved at the time of a call to `getDeclVAddr`, we skip relocating this atom.
* macho: correctly lower slices including relocation and rebasing tracking
* x64 + aarch64 - expand `Mir` instructions requiring the knowledge of the containing atom to pass the symbol index into the linker's table from codegen via mir to the emitter, to then utilise it in …
> stage2: native backends: lower const slices

- src/arch/arm/CodeGen.zig
- test/behavior/basic.zig
- test/behavior/slice.zig
Follow-up to e1a535360fb9ed08fc48018571b9702ab12a5876 (#10862) for ARM
This also fixes some stack offset calculation bugs
cc @kubkon
> stage2 ARM: lower const slices

- src/link/MachO.zig
Due to differences in where the output gets emitted in stage1 and stage2,
we were putting the symlink next to the binary rather than in `zig-cache`
directory when building with stage2.
> macho: put linker symlink for cache invalidation in zig-cache

- lib/std/math.zig
Just a tiny little change to the implementation of `floorPowerOfTwo`, since I noticed it could be simplified
> stdlib: Simplify implementation of `std.math.floorPowerOfTwo`

- lib/std/Progress.zig
- lib/std/special/test_runner.zig
This is a fix for https://github.com/ziglang/zig/issues/10773
Now the progress always starts with 1. The counter is updated last, after every test related message has been printed.
> Fixed progress indicator for `zig test`

- lib/std/special/compiler_rt.zig
- lib/std/special/compiler_rt/floatfmodl.zig
- lib/std/special/compiler_rt/floatfmodl_test.zig
- src/stage1/ir.cpp
- src/value.zig
- test/behavior/math.zig
This contains code from #10827. Also as suggested by @matu3ba, added regression tests.
Presented example code in the closing issue now results in
```
[f16]  @rem(6.9e+00, 4.0e+00) = 2.8984375e+00
[f64]  @rem(6.9e+00, 4.0e+00) = 2.9000000000000004e+00
[f80]  @rem(6.9e+00, 4.0e+00) = -nan
[f128] @rem(6.9e+00, 4.0e+00) = 2.9e+00
[f16]  comptime @rem(6.9e+00, 4.0e+00) = 2.8984375e+00
[f64]  comptime @rem(6.9e+00, 4.0e+00) = 2.9000000000000004e+00
[f80]  comptime @rem(6.9e+00, 4.0e+00) = 2.9e+00
[f128] comptime @rem(6.9e+00, 4.0e+00) = 2.9e+00
```
Closes #10819.
> Implement f128 @rem

- lib/std/zig/Ast.zig
- lib/std/zig/parse.zig
- src/Module.zig
- src/main.zig
- test/compile_errors.zig
- test/stage2/cbe.zig
```zig
// a.zig
var a
}
// before
// a.zig:3:1: error: expected ';', found '}'
// }
// ^
// after
// a.zig:2:10: error: expected ';' after declaration
//     var a
//          ^
```
This should probably be applied to all expected_* errors but these seem like the biggest offenders.
> make some errors point to the end of the previous token

- lib/std/c.zig
- lib/std/c/darwin.zig
- lib/std/c/dragonfly.zig
- lib/std/c/freebsd.zig
- lib/std/c/linux.zig
- lib/std/c/netbsd.zig
- lib/std/c/openbsd.zig
- lib/std/c/solaris.zig
- lib/std/debug.zig
- lib/std/os.zig
- lib/std/os/linux.zig
- lib/std/os/windows.zig
- lib/std/os/windows/kernel32.zig
Before we are going to de-reference the frame-pointer check if the memory is mapped. Inspired by `libunwind`. For now this is just a draft, main thing that is not finished is the same behavior on non-POSIX systems (Windows). I'm open to input :+]
Closes: #10114.
> std: validate frame-pointer address in stack walking

- lib/std/special/test_runner.zig
In #10859 I moved the `test_node.end()` call after everything else has been logged. Now the `test_fn.name` is printed by `Progress` itself, making the additional log obsolete.
Before:
```
Test [3/4] test "Test should fail"... expected 10, found 15
Test [3/4] test "Test should fail"... test "Test should fail"... FAIL (TestExpectedEqual)
```
After:
```
Test [3/4] test "Test should fail"... expected 10, found 15
Test [3/4] test "Test should fail"... FAIL (TestExpectedEqual)
```
I'm sorry I didn't catch that in my first PR.
> test_runner.zig: Do not log test name twice

- lib/std/c/darwin.zig
- lib/std/c/freebsd.zig
- lib/std/c/haiku.zig
- lib/std/c/netbsd.zig
- lib/std/c/openbsd.zig
- lib/std/c/wasi.zig
- lib/std/fs.zig
- lib/std/fs/file.zig
- lib/std/fs/test.zig
- lib/std/os/wasi.zig
This PR implements a cross-platform metadata API, aiming to reduce unnecessary Unix-dependence of the Zig `std.fs` api. Presently, all OSes beside Windows are treated as Unix; I think that this is the best way to treat things by default, instead of explicitly listing each Posix-compliant OS.
Adds:
- File.setPermissions() : Sets permission of a file according to a `Permissions` struct (not available on WASI)
- File.Metadata : A cross-platform representation of file metadata
- Metadata.size() : Returns the size of a file
- Metadata.permissions() : Returns a `Permissions` struct, representing permissions on the file
- Metadata.kind() : Returns the `Kind` of the file
- Metadata.time() : Returns the time the file was accessed, modified, or created
- File.Permissions : A cross-platform …
> std: Implement cross-platform metadata API

- lib/std/json.zig
- lib/std/testing.zig
- lib/std/zig/c_translation.zig
- lib/std/zig/parser_test.zig
This is covered by an existing test which was already failing.
> std.json: fix compile error for comptime fields

- lib/std/os.zig
On Windows, `argv` is not populated by start code, and instead left as undefined. This is problematic, and can lead to incorrect programs compiling, but panicking when trying to access `argv`. This change causes these programs to produce a compile error on Windows instead, which is far preferable to a runtime panic.
related: #6600
cc: @enkore
> std.os: throw compile error for `argv` on Windows

- src/codegen/llvm.zig
- Use `llvm.getIntrinsic` instead of `llvm.getNamedFunction`
- Merge `airClzCtz` and `airPopCount` to reduce duplication and to match SEMA.
> stage2: refactor LLVM bitcount ops

- lib/std/c/darwin.zig
- lib/std/c/dragonfly.zig
- lib/std/c/freebsd.zig
- lib/std/c/haiku.zig
- lib/std/c/netbsd.zig
- lib/std/c/openbsd.zig
- lib/std/c/solaris.zig
- lib/std/fs.zig
- lib/std/os.zig
- lib/std/os/linux/arm-eabi.zig
- lib/std/os/linux/arm64.zig
- lib/std/os/linux/mips.zig
- lib/std/os/linux/powerpc.zig
- lib/std/os/linux/powerpc64.zig
- lib/std/os/linux/riscv64.zig
- lib/std/os/linux/sparc64.zig
- lib/std/os/test.zig
On Linux, locking fails with EAGAIN (vs. EACCES on other systems).
This commit also adds FcntlErrors for EDEADLK and ENOLCK.
> Adds Linux support for POSIX file locking with fcntl

- lib/std/Thread.zig
- lib/std/os/windows.zig
- lib/std/os/windows/kernel32.zig
- lib/std/os/windows/ntdll.zig
So, the current implementation of `Thread.getName` and `Thread.setName` on Win32 uses the `GetThreadDescription` and `SetThreadDescription` APIs respectively. The problem with this is **sort of** documented in the source:
https://github.com/ziglang/zig/blob/a3c9bfef301e0a4675fcea57356653334e07df45/lib/std/Thread.zig#L88-L93
However, it hard links to `kernel32.dll` and the function was not in there until **after** W10 1607, it was previously acquired by querying the symbol from `kernelbase.dll` at runtime. Putting loader code for a shared object in the standard library is pretty ugly though, and doesn't solve properly linking to it in cases where it's available. Thankfully as with a lot of things in Win32 you can ditch this terrible null-terminator-using API entirely, and just use `Nt*` …
> std.Thread.getName/setName: rework windows implementation

- src/arch/aarch64/CodeGen.zig
- src/arch/aarch64/Emit.zig
- src/arch/aarch64/Mir.zig
- test/behavior/basic.zig
- test/behavior/cast.zig
- test/behavior/struct.zig
* disable failing `aarch64-macos` behavior tests
* introduce `MCValue.got_load` and `MCValue.direct_load` - this matches the current design in `x86_64` backend and simplifies handling of PIE targets in `aarch64` backend
* add `lowerUnnamedConst` glue to codegen
> aarch64,macos: handle GOT and direct loads in codegen

- lib/std/fmt.zig
This is a very minor inconsistency in std.fmt.parseInt()
std.fmt.parseHexFloat allow both 0x and 0X as prefix, so in order to
keep things consistent. This commit modifies std.fmt.parseWithSign to
check for the prefix case insensitively in order to allow both upper
case and lower case prefix.
This change now allows: 0O, 0B and 0X as prefixes for parsing.
> fmt: allow uppercase prefix to be parsed in std.fmt.parseInt()

- lib/std/build.zig
- src/main.zig
- test/standalone.zig
- test/standalone/fail_full_report/build.zig
- test/standalone/fail_full_report/build2.zig
Address https://github.com/ziglang/zig/issues/3477
This provides a mechanism for builds to fully report an error to the user and prevent zig from piling on extra noise.
After I've played around with #9987 (build_runner calling "zig build") the need for this change becomes apparent in order to provide a way to cut down error messages/stack traces from recursive builds.
Note that this initial change introduces the ability for project `build.zig` files to use it, but doesn't modify the zig build system to leverage it internally.  If this mechanism is accepted, then we can go through the std build system to see where it should be used to reduce build error noise.
> reduce build error noise

- lib/std/math/fabs.zig
Replaces two magic numbers with the procedure used to generate them, in order to keep consistent with other implementations for f64 & f128.
> Replace magic numbers with clearer representation

- doc/langref.html.in
- lib/std/zig/Ast.zig
- lib/std/zig/parse.zig
- lib/std/zig/parser_test.zig
- lib/std/zig/tokenizer.zig
- src/Module.zig
- src/main.zig
- src/stage1/ir.cpp
- test/compile_errors.zig
- test/stage2/cbe.zig
Continuation to #10879.
Also included is better error message when casting tuple to slice/ptr to array discards const qualifier.
Closes  #416
Closes #5739
Closes  #10511
Closes  #10529
> further parser error improvements

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- test/behavior/array.zig
- test/behavior/slice.zig
If the function call is not extern and we are compiling in debug,
pass function params always on stack. This will improve debugging
capabilities since the params will not be volatile and possibly
clobbered by the procedure code.
> stage2,x64: pass all args on stack in debug and if not extern fn

- src/codegen/c.zig
- test/behavior/basic.zig
- test/behavior/undefined.zig
This PR adds basic multi-dimensional array support to the C backend.
The core of the change is lower pointers to 1D arrays as `[*c][N]T`, rather than `[*c]T`. This allows correct pointer arithmetic based on element pointers in 2D arrays
Higher-dimensional arrays are also supported (e.g. pointer to 2D array is lowered as `[*c][N][M]T`, etc.)
Also includes miscellaneous changes to:
- refactor CValue dereferencing logic
- fix up elem_ptr and field_ptr handling, including to undefined pointers
- add `renderTypecast` (renders in C typecast format, e.g. "int* [10]")
> stage2 CBE: Implement 2D array support

- lib/std/testing.zig
To prevent calling `@hasDecl` on an instance of a struct we need to check the `@TypeOf` the decl is actually `type`.
This PR closes #10908
> refAllDecls handle pub instances of structs

- lib/std/math/big/int.zig
- lib/std/math/big/int_test.zig
- src/Air.zig
- src/Liveness.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/value.zig
- test/behavior.zig
- test/behavior/bitreverse.zig
- test/behavior/byteswap.zig
Dependent on #10858
This implements `@bitReverse` and `@byteSwap` for Sema and the LLVM back-end. Vector support is not included as part of this PR.
To make sure the endian-specific logic was properly tested, I added `bitSwap` and `bitReverse` tests to `std.math.big.int`. These are essentially copied from the existing behavior tests, with a few additions for completeness.
> stage2 llvm: Implement `@bitReverse`, `@byteSwap` built-ins

- lib/std/array_list.zig
- src/Air.zig
- src/Compilation.zig
- src/Liveness.zig
- src/Module.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/arm/Emit.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
Prior to this PR, there were two places that AIR referenced ZIR:
* The arg instruction for the corresponding parameter name
* The asm instruction for most of the information
After this PR, all the information is duplicated into AIR (or found elsewhere, as in the case of parameter names). AIR is now independent from ZIR. See individual commit messages for more information.
closes #10784
Keep in mind going forward I want to explore #10761 which might further change the code touched in this patchset.
> AIR independence day

- src/arch/arm/CodeGen.zig
The new binOp lowering mechanism is already used in the AArch64 backend. I personally think it is a simplification of the previous register allocation mechanism for binary operations. The new mechanism also enables way more code reuse — previously, `add`, `mul`, `genMulConstant`, and `cmp` all had different register allocation stuff. Now it's all unified under binOp.
Also fixes bitwise negation on the way
> stage2 ARM: move to binOp lowering mechanism

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- test/behavior.zig
- test/behavior/int_div.zig
* add lowering for single operand `imul` and `idiv`
* implement `div_exact` for signed and unsigned integers
* add unsigned `div`
* implement the rest of builtins for integers: `div_trunc`, `div_floor`, `mod`, and `rem`
* pull out integer division tests into a standalone test unit
> stage2,x64: implement integer division

- lib/std/debug.zig
Without this check errors like the below are received for freestanding targets:
```
zig build run
/home/lee/src/github.com/leecannon/zig/lib/std/os.zig:91:23: error: container 'std.os.system' has no member called 'MSF'
pub const MSF = system.MSF;
^
/home/lee/src/github.com/leecannon/zig/lib/std/os.zig:235:25: error: container 'std.os.system' has no member called 'getErrno'
pub const errno = system.getErrno;
^
RGOS...The step exited with error code 1
error: the following build command failed with exit code 1:
/home/lee/src/github.com/leecannon/RGOS/zig-cache/o/b8b4c6bd414cf6b0763ae8a1db37ffdd/build /home/lee/src/github.com/leecannon/zig/build/zig /home/lee/src/github.com/leecannon/RGOS /home/lee/src/github.com/leecannon/RGOS/zig-cache /home/lee/.cache/zig run
```
> StackIterator should not try to check memory validity on freestanding

- src/arch/riscv64/Emit.zig
Found this while i was reading stage2 backends.
> stage2: fix typo in riscv64/Emit.zig

- src/main.zig
Some projects ([elfutils](https://sourceware.org/elfutils/) in my case) pass `-Wl,--soname` rather than `-Wl,-soname` to the C compiler. `--soname` appears to be supported by GNU ld but undocumented, so I've just updated the linker argument processing logic to handle `-soname` and `--soname` the same way.
There were also a couple of other linker args that weren't supported but didn't seem to negatively affect the final output:
* `-rpath-link`
* `--build-id`
* `--no-undefined`
* `--enable-new-dtags`
I may circle back and add support for those as well if there is interest.
> Support -Wl,--soname

- lib/std/zig/tokenizer.zig
> Update Tokenizer Dump Function

- ci/azure/pipelines.yml
The shasum generated for windows builds is showing as uppercase, this change makes it lowercase like all the other builds.
> Use lowercase in shasum for windows builds

- lib/std/builtin.zig
- src/Sema.zig
- src/codegen/llvm.zig
- test/cases.zig
- test/stage2/nvptx.zig
Follow up on #10189 , this enable GPU specific address spaces leveraging previous work from @Snektron in #9649.
Right now this is directly mapping to the LLVM address spaces, but with Snektron we didn't found good reason to deviate from this and we believe it should be compatible across different architectures.
Note: this is still experimental feature because Zig doesn't have any officially supported GPU target.
> enable Gpu address spaces

- src/Air.zig
- src/AstGen.zig
- src/Liveness.zig
- src/Sema.zig
- src/Zir.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/print_zir.zig
- test/behavior.zig
- test/behavior/struct.zig
~~No idea if this actually works since I can't get LLVM to work with stage2.~~ Keep forgetting I can use stage1 with `-fno-stage1`.
> stage2: support anon init through error unions and optionals

- src/codegen/c.zig
- test/behavior.zig
Codegen for `field_ptr` and `elem_ptr` resulted in invalid C programs with misplaced referencing/dereferencing operators. This is fixed by this pull request. As a result, a few more behavior tests are passing now.
Additionally, I changed the order of parameters in `renderDeclName` so it is consistent with the other `render` functions.
> stage2: C backend: fix codegen for field_ptr/elem_ptr values

- lib/std/array_list.zig
All errors from std.ArrayList are allocation errors. Mark them as such.
This is helpful when one wants to obtain a function pointer.
However, I was not able to get a "simple" signature: help would be appreciated
on how to type it:
```
$ zig test array_list.zig
./array_list.zig:1451:41: error: expected type 'fn(u8) std.mem.Allocator.Error!void', found '(bound fn(*ArrayListAligned(u8,null), u8) std.mem.Allocator.Error!void)'
const appendFn: appendProto = buffer.append;
^
```
> [std.ArrayList] return explicit errors

- lib/std/os/linux.zig
`fd` is an out parameter in the syscall
> Fixes std.os.linux.socketpair

- lib/std/build.zig
- src/Compilation.zig
- src/link.zig
- src/link/Wasm.zig
- src/main.zig
This implements WebAssembly LLVM argument `--shared-memory`.
> wasm: implement shared memory

- doc/langref.html.in
This PR adds a subsection to the Error Union Type section of the documentation to inform readers about common mistakes caused by errdefer scoping (e.g. allocated memory leaving the scope of an errdefer and being leaked) to hopefully save some people from shooting themselves in the foot. In commit e9c7987, I added a header to separate this from the errdefer subsection because I felt it was distinct enough, but it's completely optional imo
This PR is intended to resolve issue #7298
> Added documentation for common mistakes in errdefer scoping

- src/Module.zig
- src/Sema.zig
- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/link.zig
- src/link/Wasm.zig
- src/link/Wasm/Atom.zig
- src/link/Wasm/Symbol.zig
- src/link/Wasm/types.zig
This PR implements emitting a relocatable object file using `build-obj`.
We now emit relocations and metadata such as a symbol table and segment information when using build-obj.
COMDAT information (link once) and init functions (constructors) are currently not implemented yet.
For implementation details, refer to each individual commit.
The self-hosted wasm linker is now one step closer to being useful :)
> wasm-linker: Implement relocatable object files

- lib/std/special/compiler_rt.zig
- lib/std/special/compiler_rt/README.md
- lib/std/special/compiler_rt/extend_f80.zig
- lib/std/special/compiler_rt/trunc_f80.zig
- src/stage1/codegen.cpp
* goals
- zig as linker for object files generated by other compilers
- zig-specific runtime features for eventual standardisation
* changes
- missing routines are marked with `missing`
- structure inspired by libgcc docs, but improved order and wording
- rename misspelled functions
- reorder and rephrase compiler_rt.zig to reflect documentation
- potential decimal float or fixed-point arithmetic support:
* 'Decimal float library routines' ca. 120 functions
* 'Fixed-point fractional library routines' ca. 300 functions
thanks to @Vexu for multiple reviews and @scheibo for review
> compiler_rt: specify goals, organize README and compiler_rt.zig

- lib/std/special/test_runner.zig
- src/arch/x86_64/CodeGen.zig
- src/link/MachO.zig
Turns out, there were a couple of things that needed rectifying both in the codegen as well as in the linker itself. Here's a summary breakdown:
* synthesizing `__mh_execute_header` in the linker assumed it was always done first (before resolving any other symbol) - this is obviously not true in general incremental setting, and lead to incorrectly handled symbol aliasing where Zig's libstd export a dummy weak `__mh_execute_header` symbol, and then the linker tried to synthesize the correct one which lead to trapping. This is now rectified so that we correctly check if the symbol was already defined.
* another issue was that incorrect names for decls were used in the linker leading to false collisions - turns out we need to use the fully qualified decl name via `Decl.getFullyQualifiedName` …
> x64: print test runner results on macos

- lib/std/build.zig
- src/main.zig
These patches fix a major issue which prevents using Zig's build system from being viable in larger projects with lots of source files on Windows (and macOS + Linux, to a lesser degree.)
In [Mach engine](https://github.com/hexops/mach) we're seeing command line arguments to `zig build-lib` exceed the 32 KiB limit that Windows imposes in the `CreateProcess` API, due to the number of source files and compiler flags we need in order to build WebGPU/Dawn.
I've fixed this issue in three steps (best reviewed as individual commits):
1. Refactored `zig build-lib [args]` args handling to use an iterator, in anticipation of response file support.
2. Added response file support to `zig build-lib @args.rsp` (and `build-exe`, etc. friends) so you can pass them a text file of arguments instead.
3. …
> Do not fail to build if 'zig build-lib' etc. arguments exceed OS limits

- src/arch/aarch64/CodeGen.zig
- src/arch/aarch64/Emit.zig
- src/arch/aarch64/Mir.zig
- src/arch/aarch64/bits.zig
- test/behavior/align.zig
- test/behavior/basic.zig
- test/behavior/bugs/2006.zig
- test/behavior/cast.zig
- test/behavior/slice.zig
- test/behavior/struct.zig
This enables a handful of behavior tests previously disabled for `aarch64-macos`.
cc @kubkon
> stage2 AArch64: more support for PIE targets (Mach-O)

- src/link/Elf.zig
Matches the fixes introduced to MachO linker in #10976
> elf: use fully qualified decl names in the linker

- src/Sema.zig
- test/behavior/cast.zig
This makes the given test pass without causing any additional tests to fail.
This doesn't cause any existing behavior tests to fail, but I think there are still some more complex peer resolution cases that this isn't 100% correct for that future skipped behavior tests will keep ironing out. Still, this moves the needle forward.
> stage2: peer type resolution *[N]T and *[M]T to []const T

- lib/std/os/uefi/protocols/edid_override_protocol.zig
As of 6249a24, align() is not allowed on packed struct fields
and as such the align(4) was removed from the first field of
EdidOverrideProtocolAttributes. The endgame here is packed struct
backed by explicit integers, in this case a u32, but until that
is implemented put the align(4) on the pointer to avoid breaking
someone's UEFI code in a hard to debug way.
> std: work around current packed struct situation

- lib/std/c/darwin.zig
- lib/std/time.zig
`std.time.Instant` is an abstraction which helps represent elapsed time within a program. The name takes inspiration from Rust's [`std::time::Instant`](https://doc.rust-lang.org/std/time/struct.Instant.html).
The motive is to delegate `std.time.timestamp` and friends for *telling time* (e.g. dates) while `std.time.Timer/std.time.Instant` are for *measuring time* (e.g. elapsed durations). 
The difference between Instant and Timer is that the former isn't required to *necessarily* be monotonic nor be representable in wall clock time like nanoseconds. This API allows for slightly faster sampling by deferring time conversions to a separate function. It also makes it trivial for Timer to be built on-top of it, providing the monotonicity guarantee in userspace instead of relying on the OS or …
> time: introduce Instant

- src/arch/wasm/CodeGen.zig
- src/link/Wasm.zig
- src/link/Wasm/Atom.zig
Rather than ping-ponging between the linker and codegen to first create a symbol, then generate the code, and then update the atom with the code. This will now emit a simple call to the linker which will then create the symbol, atom, and initiate the codegen for the unnamed const. Similar to how the linker also drives the codegen for a decl. This means the single function can easily be re-used within the backend whenever a complex constant requires lowering that doesn't fit in a single local.
Besides this, it also fixes the alignment of an error union, where it was previously packed in memory without considering the alignment of each 'field'.
> stage2: wasm - Move responsibilities lowerUnnamedConst

- src/arch/aarch64/CodeGen.zig
- src/arch/aarch64/Emit.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/link/MachO.zig
- src/link/MachO/Atom.zig
- test/behavior/align.zig
- test/behavior/basic.zig
- test/behavior/struct.zig
- test/behavior/union.zig
* aarch64: fix alignment issues for consts with natural ABI alignment not matching that of the `ldr` instruction in `aarch64` - solved by preceding the `ldr` with an additional `add` instruction to form  the full address before dereferencing the pointer.
* macho: redo selection of segment/section for decls and consts based on combined type and value
* aarch64: check if type has runtime bits before allocating mem ptr
* x64+aarch64: check for pointer to zero-bit type when lowering decl - unless the pointer is a pointer to a function, if the pointee type has zero-bits, we need to return `MCValue.none` as the `Decl` has not been lowered to memory, and therefore, any GOT reference will be wrong.
> macho,x64,aarch64: misc fixes

- src/AstGen.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- test/behavior.zig
- test/behavior/bugs/4328.zig
- test/behavior/bugs/5474.zig
Arguments to `@TypeOf` need to be analyzed in their own block so that we don't end up with trash instructions in codegen. This also makes it easy to avoid issues with some instructions requiring a runtime block when we only care about their type.
> stage2: `@TypeOf` improvements

- src/Sema.zig
- test/behavior/error.zig
- test/behavior/type_info.zig
Subject self-explanatory. I added a few more tests here to be exhaustive. Left them skipped for native backends; they might pass but I'll let those folks clear them.
4 more passing tests.
> stage2: @TypeInfo for error sets

- lib/std/hash_map.zig
All errors from std.ArrayList are allocation errors. Mark them as
such. This is helpful when one wants to return explicit errors where
HashMap is used.
> std.HashMap: return explicit errors

- lib/std/Progress.zig
- lib/std/os/linux.zig
- lib/std/special/test_runner.zig
- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/type.zig
- test/behavior.zig
- test/behavior/basic.zig
Not sure how correct my fix is but the issue is that `zirCondbr` must not handle `error.ComptimeBreak` when a comptime known argument causes it to be inlined.
Current limitations:
* ~~only works for one argument likely due to behavior tested in `test/behavior/bugs/828.zig`~~
* the argument tuple cannot mix comptime and non comptime arguments since the comptime argument forces the entire tuple to be comptime only
> stage2: make formatted printing work

- src/Sema.zig
- test/behavior/type.zig
This PR implements `@Type` for Array, Optional, Float, and ErrorUnion.
I noticed that @Vexu already has an update to support the pointer sentinel in #11001 , so I haven't included that in these changes. The pointer sentinel changes will allow two more tests to pass, for a total of 7 additional ✅ tests
> stage2: Implement `@Type` for Array, Optional, Float, and ErrorUnion

- src/Sema.zig
- test/behavior/eval.zig
This PR implements a `comptime` result for certain comparisons between unsigned integers and comptime values.
For example:
```
( 0 <= (unsigned runtime value)) => true
(-1 <  (unsigned runtime value)) => true
((unsigned runtime value) < -15) => false
((unsigned runtime value) <  15) => (runtime comparison)
```
**Note:** Along the way, I noticed that `test/behavior/eval.zig` was failing when executed on its own. This seems to be caused by an unresolved union layout in zirTagName. I've added the fix to this PR, but unfortunately I wasn't able to add any tests, because I'm not sure how to reliably create a union with un-resolved layout for testing.
> stage2: Add comptime result for certain unsigned/comptime comparisons

- lib/std/Thread.zig
- lib/std/Thread/StaticResetEvent.zig
- lib/std/os.zig
I was doing a bit of Threading stuff in zig and was looking for a yield method in `std.Thread` and took me a couple of minutes to figure out it is in `std.os` under a different name. I think it is better for the function to be under the `Thread` namespace similar to how Rust and C++ provide it.
> std: rename `sched_yield` to `yield` and move it to `std.Thread`

- src/Module.zig
- src/Sema.zig
- src/type.zig
- test/behavior/type_info.zig
This also includes two other small fixes:
1. Instantiate void TypeInfo fields as `void`
2. Return an error in `type.comptimeOnly` when encountering unresolved comptime requirements
The problem behind (2) is that type.hasRuntimeBits() can hit an `unreachable` because "requires_comptime" is not resolved for some child structs.
Since we already approximate (i.e. return `true`, even though the type may end up comptime-only) when encountering unknown comptime requirements in other branches, this PR updates the function to approximate in all branches.
> stage2: Resolve alignment for union field in `@TypeInfo`

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/codegen.zig
- test/behavior/union.zig
* implement `set_union_tag`
* implement `get_union_tag` for stack offset
* implement lowering of union type to memory for Elf and MachO backends
* make `lowerUnnamedConst` a fallthrough condition in `genTypedValue` - we'll see how this fares
* fix storing values with ABI size greater than 8 bytes on the stack
* fix switch condition MIR gen code where we would use `test` opcode to compare against a possibly value of `0` immediate which would always yield equal which is wrong
* pass some basic union tests in behavior test suite
> stage2,x64: basic (un)tagged unions

- src/Sema.zig
- test/behavior/cast.zig
We were using the array type, not the element type. Also, we should do
the sentinel comparison after we verify that the element types of both
are compatible.
1 more passing test.
> stage2: sentinel compare during peer type resolution should use elem type

- src/Sema.zig
- src/type.zig
- test/behavior/cast.zig
- test/behavior/error.zig
I surprisingly could only find 1 test that passes thanks to this (no new failures). But I added a number of new cases to better cover error union/set peer resolution in various cases and these also pass in stage1.
One question: note the TODO in Sema L17404 I added. A generic poison is making its way through somehow if I don't guard against it. Is the way I'm guarding fine?
> stage2: peer resolve error sets and error unions 

- src/link/Wasm.zig
- src/link/Wasm/Atom.zig
- src/link/Wasm/Object.zig
- src/link/Wasm/Symbol.zig
- src/link/Wasm/types.zig
From now on, all strings in the linker will be interned. The benefits of interning, while using only Zig code and not linking any other object files are nearly non-existing as most symbol names are already unique for Zig code. However, it does save memory when using WASI functions as they all reference library names that will be interned. The benefits of this become clear when trying to link with other object files, as at such point you'll have multiple symbols containing the same name.
A nice side-effect of this change is it opens up the ability to provide a better data-oriented design for symbols. Since strings are now an offset into a string table, we could also potentially look into preserving this table throughout the entire pipeline. This would mean the linker could re-use those …
> stage2: wasm-linker - Implement string interning

- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
- test/behavior/align.zig
- test/behavior/alignof.zig
- test/behavior/array.zig
- test/behavior/basic.zig
- test/behavior/bitcast.zig
- test/behavior/bitreverse.zig
- test/behavior/bugs/1381.zig
- test/behavior/bugs/1735.zig
- test/behavior/bugs/4954.zig
- test/behavior/cast.zig
- test/behavior/defer.zig
- test/behavior/enum.zig
- test/behavior/error.zig
- test/behavior/fn.zig
- test/behavior/if.zig
- test/behavior/ir_block_deps.zig
- test/behavior/namespace_depends_on_compile_var.zig
- test/behavior/optional.zig
- test/behavior/struct.zig
- test/behavior/try.zig
- test/behavior/underscore.zig
- test/behavior/union.zig
- test/behavior/while.zig
* x64: implement `unwrap_errunion_payload` when `MCValue` is a register
* x64: implement `unwrap_errunion_err` when `MCValue` is a register
* codegen: fix padding calculation for error unions when lowering
* x64: do not track `rdi` register before `call` inst, but instead freeze it from further use until `call` has been realised
* x64: clean up `loadMemPtrIntoRegister` abstraction to accept a register instead of allocating inside
* implement `get_union_tag` when `MCValue` is a register
EDIT: 
Passing vs skipped tests summary when run locally on my MBA:
> x64: more codegen

- lib/std/buf_set.zig
This was introduced in d1a46548349a902c30057b3ba66ebad9bc25bdd2: when a
BufSet clones the keys, it used to assign the new pointers to the old
struct. Fix that by assigning the pointers to the correct, i.e. the new,
struct.
This caused double-free when using arena allocator for the new struct,
also in the test case.
> std.BufSet.clone: fix key ownership

- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
- src/link.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/Plan9.zig
- test/behavior/bugs/3046.zig
- test/behavior/struct.zig
This requires generating an addend for the target relocation as
the field pointer might point at a field inner to the container.
> codegen: lower field_ptr to memory across linking backends

- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
- test/behavior/basic.zig
- test/behavior/bugs/2889.zig
- test/behavior/bugs/3112.zig
- test/behavior/cast.zig
- test/behavior/enum.zig
- test/behavior/optional.zig
* codegen: lower optionals and floats across linking backends
* x64: rectify and missing optionals bits - `wrap_optional`, `optional_payload` and `isNull` helper
* x64: fix `int_cast` to properly clear out the destination register before copying the value over
* x64: fix incorrect calculation of spill stack location of the `rdi` register for backpatching the return value write locations
> x64: handle more optional types

- lib/std/bounded_array.zig
Makes it easier to mark explicit errors when using BoundedArray
downstream.
Per @jedisct1 confirmation, also removing `IndexOutOfBounds` in favor of `Overflow`, making it the only error this module can return.
> std.BoundedArray: return explicit errors

- src/Sema.zig
- src/value.zig
- test/behavior/type.zig
`@Type()` for error sets.
This also fixes a bug in @typeInfo for error sets where I wasn't wrapping the payload properly. This test also catches that.
Question: I create an `error_set_merged` since that only requires a name map. Should I be creating a full `error_set` decl for this? That requires a full `Module.ErrorSet`. I'm sure I can do that but wasn't sure what you wanted here.
> stage2: reify error sets

- src/Sema.zig
- src/codegen/llvm.zig
- src/type.zig
- test/behavior/optional.zig
- test/behavior/ptrcast.zig
Various changes to fix some small tests in `behavior/optional.zig` and `behavior/ptrcast.zig`
**Aside:** The last remaining test in ptrcast seems quite tricky: A field_ptr fails to be dereferenced because Sema.beginComptimePtrLoad assumes that it can recurse to a root decl_ref and ask for its type to get the parent struct/array type. However, this seems incorrect for reinterpreted memory, where a pointer intentionally disagrees about its target vs. the containing decl
> stage2: Improve `@ptrCast` support for sliced/optional operands

- src/Air.zig
- src/AstGen.zig
- src/Liveness.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/arch/wasm/Mir.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/link/C/zig.h
- src/print_air.zig
- src/type.zig
- test/behavior.zig
- test/behavior/wasm.zig
This implements the [@wasmMemorySize](https://ziglang.org/documentation/master/#wasmMemorySize) and [@wasmMemoryGrow](https://ziglang.org/documentation/master/#wasmMemoryGrow) builtins. Note that the implementation differs from stage1 whereas in stage2 it ensures the `index` argument is a comptime-known value. This is required, as the index is part of the instruction encoding, and therefore cannot be a runtime value. For stage1, this is only enforced by AstGen whereas in stage2 Sema also resolves it as a comptime value. I figured it wouldn't be worth the effort to correct this in stage1 when AstGen already enforces it there now as well. (This does however make this PR a breaking change).
Unfortunately, I have to perform quite some fixes within the self-hosted linker to ensure the LLVM …
> stage2: Implement wasm builtins

- src/arch/arm/CodeGen.zig
- test/behavior/align.zig
- test/behavior/cast.zig
- test/behavior/error.zig
- test/behavior/floatop.zig
- test/behavior/inttoptr.zig
- test/behavior/math.zig
- test/behavior/slice.zig
- test/behavior/switch.zig
The checks detecting such no-op branches (essentially instructions
that branch to the instruction immediately following the branch) were
tightened to catch more of these occurrences.
> stage2 ARM: generate less no-op branches

- test/behavior/pointers.zig
stage1 peer resolves the given test to `[*c]u8` but stage2 makes that a
const u8. I believe stage2 behavior is correct since the pointer itself
is const, but I'm not sure.
Please advise what the proper behavior here should be and I can make it so.
> stage2: test changed behavior of c pointer resolution from stage1

- src/arch/x86_64/Emit.zig
- src/codegen.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/MachO/DebugSymbols.zig
But also:
* migrate to named struct for slices - `lldb` kindly hinted me that we should name the structs with the typename, so we now get a slice recognise by its type, say `[]const u8` or whatnot
* when padding out compiled machine code section in MachO, write NOPs instead of `0x0` - while this is not strictly required, it un-breaks helper utilities for analysing MachO binaries such as MachOView.app which now properly displays the start and end of each atom with the compiled machine code section
* remove `anon_struct_type` abbrev type from DWARF as we don't actually need it any longer since slices and optionals are named struct where name is their actual type
* fix incorrect line and PC advancement in MachO DWARF - a left-over after one of my earlier cleanups
This is probably my last …
> link: debug info for non-pointer optionals

- doc/langref.html.in
The documentation omitted the primary parameter, making it difficult to
understand what this function actually does.
> correct `@frameSize()` params in documentation

- src/Sema.zig
A `manyptr_const_u8_sentinel_0` is a pointer type.
This makes the following work properly (as it does in stage1, too):
```zig
var zero_ptr: [*:0]const u8 = undefined;
var no_zero_ptr: [*]const u8 = zero_ptr;
```
Prior to this this would fail with an "expected type" error since
coercion failed.
No test, the "null terminated pointer" test is closer to passing with this but still has some other issues and I didn't feel it was worth making a dedicated test for this one small change since that test clearly will exercise it once it is passing.
> stage2: coerce [*:0]u8 to other valid pointer types

- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
When an union had a zero-sized payload type, we would lower the tag twice. This is fixed by exiting early when `payload_size` is 0.
With regards to error unions, we were only accounting for padding for the payload field. However, the errorset value can have a smaller alignment than the payload as well, i.e. `error!usize`. We fix this by also accounting for padding/alignment of the error set tag of an error union.
> stage2: Fix codegen for unions and error unions

- src/codegen/llvm.zig
- src/link/Wasm.zig
- test/behavior/struct.zig
- This fixes 2 entry points within the self-hosted wasm linker that would be called for the LLVM backend, whereas we should simply call into the LLVM backend to perform such action. i.e. not allocate a decl index when we have an LLVM object, and when flushing a module, we should be calling it on LLVM's object, rather than have the wasm linker perform the operation.
- Also, fixes were done for the wasm intrinsics `wasm.memory.size` and `wasm.memory.grow`.
- Lastly, this PR ensures that when an extern function is being resolved, we tell LLVM how to import such function.
Those fixes make all the behavior tests pass for the LLVM backend when targeting WebAssembly.
> stage2: LLVM - Wasm improvements/fixes

- lib/std/build.zig
- src/main.zig
This brings back #10950, which was reverted in 5ab5e2e6731a9f1198df6c53134545ccc6a6bbd3 because it [introduced a regression in `zig run`](https://github.com/ziglang/zig/pull/10950#issuecomment-1049481212) where the runtime arguments passed were incorrect (sorry for not catching that sooner!)
I've fixed the issue, and notably this was the only location where we directly relied on accessing arguments by index in this code still (all other locations use the iterator proper) and so we should be all good to go now.
cc @andrewrk sorry for the regression!
> Do not fail to build if 'zig build-lib' etc. arguments exceed OS limits (take 2)

- src/link/Wasm.zig
- src/link/Wasm/Atom.zig
- atoms may have relocations, so freeing them when we update the parent atom will cause segfaults.
- Not all declarations will live in symbol_atom as they may already been freed by `resetState`.
Fixes the test error caused by #11070
> stage2: wasm - fix incremental compilation

- src/AstGen.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- test/behavior/pointers.zig
Array types with sentinels were not being typed correctly in the translation from ZIR to Sema (comptime). This uses a new ZIR inst `array_init_sent` (and a ref equivalent) to represent array init expressions that terminate in a a sentinel value.
The sentinel value is the last value in the `MultiOp` payload. This makes it a bit more awkward to deal with (lots of "len - 1") but makes it so that the payload matches the fact that sentinels appear at the end of arrays. However, this is not a hill I want to die on so if we want to change it to index 0, I'm happy to do so.
This makes the following work properly:
try expect(@typeof([_:0]u8{}) == [0:0]u8);
Also see the new test added.
```zig
test "hello" {
const E = enum { A, B, C };
[_]u8{1};
[_:0]u8{1};
&[_:.A]E{1};
}
```
```
[158] test "hello" …
```
> stage2: sentinel-terminated array initialization

- src/Module.zig
- src/arch/arm/Emit.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/link.zig
- src/link/Dwarf.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/MachO/Atom.zig
- src/link/MachO/DebugSymbols.zig
It's DWARF spring cleaning time!
Let's consolidate all of DWARF functionality into a common module shared by the linker! For now, hook up Elf and MachO linkers to the new solution.
---
I have decided to make my life easier and introduced a common type `link.Dwarf.SrcFn` that is required if you wanna use `Dwarf.zig` functionality. I also did the same with `TextBlock` related debug_info data - encapsulated it as `link.Dwarf.DebugInfoAtom`. I don't think we need to support those types being overridable since they are useful only in the context of `Dwarf`, or at least that's my thinking here.
Additional requirement for any backend willing to use `Dwarf` is it needs to offer hooks for growing and moving debug sections - currently, this is orchestrated manually within `Dwarf` with no comptime …
> DWARF spring cleaning time!

- src/arch/arm/CodeGen.zig
- test/behavior/align.zig
- test/behavior/array.zig
- test/behavior/cast.zig
Also reduces `slice_elem_val` to `ptr_add`, simplifying the implementation
> stage2 ARM: implement ptr_add, ptr_sub for all element sizes

- lib/std/bit_set.zig
- lib/std/builtin.zig
- lib/std/enums.zig
- lib/std/hash/auto_hash.zig
- lib/std/io/fixed_buffer_stream.zig
- lib/std/io/reader.zig
- lib/std/io/writer.zig
- lib/std/json.zig
- lib/std/mem.zig
- lib/std/meta.zig
- lib/std/meta/trailer_flags.zig
- lib/std/zig/Ast.zig
- lib/std/zig/c_translation.zig
- src/AstGen.zig
- src/InternArena.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/stage1/ir.cpp
- src/type.zig
- src/value.zig
- test/behavior/bugs/1421.zig
- test/behavior/bugs/6456.zig
- test/behavior/tuple.zig
- test/behavior/type.zig
- test/behavior/type_info.zig
- test/compile_errors.zig
I started by trying to rename `TypeInfo` to `Type`, but I ended up needing to more changes to get that to work, so instead I just created a new `Type = TypeInfo` alias.  This way code can start transitioning to using `Type` now and we can do the same in Zig iteratively without making a huge change that constantly breaks with merge conflicts.
> deprecate TypeInfo in favor of Type

- src/translate_c.zig
- test/behavior/translate_c_macros.h
- test/behavior/translate_c_macros.zig
- test/run_translated_c.zig
> translate-c: use nested scope for comma operator in macros

- lib/std/json.zig
- lib/std/testing.zig
Hey all, this is my first time contributing to Zig so adjust your expectations accordingly heh.
I wanted to contribute and picked this issue [#9743](https://github.com/ziglang/zig/issues/9743) to fix.
My fix only partially fixes the issue, because there's the 2nd part where if you mark the struct field as a null terminating slice `u8[:0]` you get yelled at that the types don't match with what the function returns:
`./zig/build/lib/zig/std/json.zig:1874:58: error: expected type '[:0]u8', found '[]u8'` <- something like that 
I don't know enough about the language to tell exactly what the expectation is, and how to handle a polymorphic case like this. But I can fix that part in another PR.
I'd love some feedback on how to improve this!
> Make json parser return a null terminated string for []u8 types

- src/Sema.zig
- test/behavior/cast.zig
- test/behavior/pointers.zig
By the time zirElemVal is reached for a many pointer at comptime, a load has already happened, making sure the operand is already dereferenced. This fixes a comptime-only failure scenario with elemval.
This makes `mem.sliceTo` now work in comptime (found 3 tests that now pass, at least...) 🥳 
Here is a minimal test case in case you want to compare. No need to add this test case since other tests exercise this, but this was what I used during debugging:
```zig
test "A" {
comptime {
var a: [*]const u8 = &[_]u8{1,2,3};
try expect(a[1] == 2);
}
}
test "B" {
comptime {
var array_with_zero = [_:0]u8{ 'h', 'e', 'l', 'l', 'o' };
var zero_ptr: [*:0]const u8 = @ptrCast([*:0]const u8, &array_with_zero);
try expect(zero_ptr[5] == 0);
}
}
```
> stage2: elem vals of many pointers need not deref pointers

- src/Sema.zig
- test/behavior/pointers.zig
Two changes in here, both needed to get the tests passing in this PR.
At least 3 more passing tests!
1. For inferred allocs with values known at comptime _but not forced comptime_ (i.e. not in a `comptime {}` block), we were setting the incorrect type, causing cascading errors. We can now set the type to the bitcast type. The previous comment noted we can't do that due to constness, but @Vexu's recent `make_const_ptr` work fixes this.
2. A mistake from my prior PR on sentinel array initialization, I was not adding the sentinel to the end of the array value for comptime. Bonus: this solidifies that adding the sentinel as the final op in the `array_init_sent` ZIR is correct.
Tests used during debugging/development are below. First two are the inferred alloc commit, last one is the sentinel …
> stage2: correct comptime-known inferred alloc type, plus comptime array init sentinels

- doc/langref.html.in
- lib/std/dwarf.zig
- src/Compilation.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
- src/link.zig
- src/link/Dwarf.zig
- src/stage1/analyze.cpp
- src/type.zig
- src/zig_llvm.cpp
- src/zig_llvm.h
> stage2 LLVM debug info

- lib/std/zig/fmt.zig
check was only validating content, not handling the case when there was no content at all. `fmtId` on empty string should yield `@""`
fixes #11099
> std: fix false positive for `zig.isValidId` with empty string

- src/Module.zig
- src/Sema.zig
- src/type.zig
- src/value.zig
- test/behavior/cast.zig
- test/behavior/error.zig
- test/behavior/type_info.zig
- test/stage2/x86_64.zig
This implements type equality for merged error types. This is done through element-wise error set comparison. This is a bit odd since no other error type is structurally compared (see #11022) but it appears to be the same behavior that stage1 also expects based on tests.
Also took the opportunity to clean up the style of error set comparisons.
This gets 6 more error-specific tests passing!
> stage2: error set type equality, error and error union value equality

- src/Sema.zig
- test/behavior/array.zig
Matches behavior of stage1, makes `std.mem` tests move forward a bit more when paired with #11122
> stage2: Array len field should be a usize not comptime_int

- src/Sema.zig
- test/behavior/error.zig
This was a special case of the stage1 compiler that was exercised by the behavior tests.
> stage2: is_non_error always returns comptime true for empty error set

- lib/std/math.zig
Fixes integer overflow caused by cast from maxInt(u32) as an f32 to u32.
Fixes #11115
> std.math.lossyCast: fix integer overflow

- lib/std/child_process.zig
- Cli operations should be refactored, since the standard test runner
has an expected argument structure. This would also ensure that the
test cli is usable as tested library with checks for subprocess
error or success instead of "hacky shell script interfaces".
- Default paths generation based on tmpDir would also be useful.
- Anonymous pipes on windows are generated from named pipes
- Async IO does not work on anonymous pipes
- Remove finished TODO
> std: add test for child_process

- src/link/NvPtx.zig
- src/test.zig
- test/cases.zig
- test/stage2/nvptx.zig
Fixes #10968
Allow test cases to chose whether to link libc or not.
default behavior is to not link libc, except for `exeUsingLLVMBackend`
Ptx backend doesn't support linking, so we should not try to link libc.
Also the `link/nvptx.zig` error handling was wrong, so I simplified the code to remove the errdefer that could segfault.
Since there was a TODO in `test.zig` about linking libc, I also implemented it. @andrewrk Let me know if that still makes sense.
https://github.com/ziglang/zig/blob/f6aaab9406807305c2b48fcd742449c9e91f1851/src/test.zig#L1159-L1160
> fix nvptx test failure #10968

- test/behavior/bugs/6456.zig
- test/stage2/llvm.zig
In stage1, this behavior was allowed (by accident?) and also
accidentally exercised by the behavior test changed in this commit. In
discussion on Discord, Andrew decided this should not be allowed in
stage2 since there is currently on real world reason to allow this
strange edge case.
I've added the compiler test to solidify that this behavior should NOT
occur and updated the behavior test to the new valid semantics.
> stage2: add compiler test to ensure typed null doesn't coerce to any

- src/Air.zig
- src/AstGen.zig
- src/Liveness.zig
- src/Sema.zig
- src/Zir.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
- src/print_air.zig
- src/print_zir.zig
- src/zig_llvm.cpp
- src/zig_llvm.h
- test/behavior/align.zig
- test/behavior/bugs/2692.zig
- test/behavior/bugs/4954.zig
- test/behavior/bugs/5398.zig
- test/behavior/eval.zig
- test/behavior/floatop.zig
- test/behavior/fn.zig
- test/behavior/for.zig
- test/behavior/generics.zig
- test/behavior/slice.zig
- test/behavior/union.zig
- test/behavior/union_with_members.zig
Adds 2 new AIR instructions:
* dbg_var_ptr
* dbg_var_val
Sema no longer emits dbg_stmt AIR instructions when strip=true.
LLVM backend: fixed lowerPtrToVoid when calling ptrAlignment on
the element type is problematic.
LLVM backend: fixed alloca instructions improperly getting debug
location annotated, causing chaotic debug info behavior.
zig_llvm.cpp: fixed incorrect bindings for a function that should use
unsigned integers for line and column.
A bunch of C test cases regressed because the new dbg_var AIR
instructions caused their operands to be alive, exposing latent bugs.
Mostly it's just a problem that the C backend lowers mutable
and const slices to the same C type, so we need to represent that in the
C backend instead of printing two duplicate typedefs.
> stage2: add debug info for locals in the LLVM backend

- lib/std/c/linux.zig
The libc interface uses `stat` instead of `stat64` struct like in the kernel.
This fixes, among other things, `zig fmt` accidentally setting the formatted file's permission to 000.
> c/linux: Fix `stat` struct definition for SPARCv9

- lib/std/zig/parser_test.zig
- lib/std/zig/render.zig
This now checks for the presence of a comment before throwing everything on one line and dropping the comment from the switch case entirely, as mentioned in https://github.com/ziglang/zig/issues/11131
After verifying the issue being fixed, I tested for potential regressions by running it on `Sema.zig` and seeing if there was any formatting changes in the git diff. 
~~If there is a test suite (I was unable to find any sorry) for `zig fmt`, please let me know!~~
> zig-fmt: Resolve #11131 loss of comment on switch cases 

- src/Sema.zig
- test/behavior/type.zig
Similarly to structs, there appears to be no "empty union" shortcut type available so we have to generate a full decl for now. 
I also fixed another location (enum reification) where I wasn't using the value functions and was casting too much.
> stage2: reify unions

- src/Module.zig
- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
- src/zig_llvm.cpp
- src/zig_llvm.h
LLVM backend: generate `DIGlobalVariable`s for non-function globals and
rename linkage names when exporting functions and globals.
`zig_llvm.cpp`: add some wrappers to convert a handful of DI classes
into `DINode`s since `DIGlobalVariable` is not a `DIScope` like the others.
`zig_llvm.cpp`: add some wrappers to allow replacing the `LinkageName` of
`DISubprogram` and `DIGlobalVariable`.
`zig_llvm.cpp`: fix DI class mixup causing nonsense reinterpret_cast.
The end result is that GDB is now usable since you now no longer need
to manually cast every global nor fully qualify every export.
Closes #11097.
> stage2: add debug info for globals in the LLVM backend

- src/codegen.zig
- src/codegen/llvm.zig
- test/behavior.zig
- test/behavior/bugs/11165.zig
It is possible for the value length to be longer than the type because
we allow in-memory coercing of types such as `[5:0]u8` to `[5]u8`. In
such a case, the value length is 6 but the type length if 5.
The `.repeated` value type already got this right, so this is extending
similar logic out to `.aggregate` and `.bytes`. Both scenarios are
tested in behavior tests.
Fixes #11165
> stage2: codegen of arrays should use type length, not value length

- src/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/type.zig
- src/value.zig
- test/behavior.zig
- test/behavior/bugs/11139.zig
- test/behavior/cast.zig
- test/behavior/ptrcast.zig
This PR resolves the "tricky" situation noted in #11043. Also resolves #11139.
Parent pointer values (`.elem_ptr`, `.field_ptr`, `.eu_payload_ptr`, and `.union_payload_ptr`) don't have any way of recovering the type that they were constructed with. If you create a .field_ptr from the result of a bit-cast (e.g. `&@bitCast(T, ptr).foo`), it can't be lowered or dereferenced correctly, since we cannot recover `T`
This ended up being a pretty scruffy yak. Major changes:
- Add `container_ty`/`elem_ty` to parent pointer Values
- Implement `Type.hasWellDefinedLayout` and `Sema.typeHasWellDefinedLayout`, so that we can anticipate when bitcasting in Sema is legal
- Update Sema `pointerDeref` to bitcast if parent pointer type diverges from the backing decl type
- Update LLVM `lowerParentPtr` to …
> stage2: Track parent type for `.elem_ptr`, `.field_ptr`, and `.*_payload_ptr`

- lib/std/coff.zig
- lib/std/elf.zig
target.Arch already supports finding the correct encoding for either
target, so being able to do the inverse has use cases for when parsing
files of an unknown target (i.e. for zar).
> std: Add elf.EM, coff.MachineType to target.Arch

- src/Sema.zig
- test/behavior.zig
- test/behavior/bugs/11181.zig
We must resolve the type fully so that pointer children (i.e. slices)
are resolved. Additionally, we must resolve even if we can know the
value at comptime because the `alloc_inferred` ZIR always produces a
constant in the AIR.
Fixes #11181
> stage2: resolve type fully when resolving inferred allocs

- src/AstGen.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/type.zig
- test/behavior.zig
- test/behavior/bugs/11159.zig
- test/behavior/bugs/11162.zig
- test/behavior/bugs/11182.zig
This resolves https://github.com/ziglang/zig/issues/11159
Assorted fixes here:
1. Comptime fields should not affect whether a type has runtime bits
2. We were not correctly deleting the field stores after recognizing that an array initializer was a comptime-known value.
3. LLVM was not checking that the stored type had no runtime bits, and so would generate an invalid store.
This also adds several test cases for related bugs, just to check these in for later work. Initializing tuples with mixed comptime/runtime fields is unfortunately still broken (on both stage1 and stage2) - that will have to be tackled later, probably with https://github.com/ziglang/zig/issues/11162
> stage2: resolve panic on array-like tuple initialization

- src/Sema.zig
- test/behavior/type_info.zig
Prior to these, the return type was non-null but the value was generic
poison which wasn't usable in user-space. This sets the value to null.
This also adds a behavior test for this.
Co-authored-by: InKryption <inkryption07@gmail.com>
> stage2: TypeInfo for func with generic return type should set null

- CMakeLists.txt
- lib/std/build.zig
- lib/std/c/darwin.zig
- lib/std/child_process.zig
- lib/std/os.zig
- lib/std/os/posix_spawn.zig
Currently, the new API will only be available on macOS with the intention of adding more POSIX systems to it incrementally (such as Linux, etc.). A cool new feature is the ability for the `ChildProcess` have the ASLR disabled on request:
```zig
var child = ChildProcess.init(argv.items, arena);
child.disable_aslr = true;
try child.spawn();
return child.pid;
```
Changes:
* add `posix_spawn` wrappers in a separate container in `os/posix_spawn.zig`
* rewrite `ChildProcess.spawnPosix` using `posix_spawn` targeting macOS as `ChildProcess.spawnMacos`
* introduce a `posix_spawn` specific `std.c.waitpid` wrapper which does return an error in case the child process failed to exec - this is required for any process that was spawned using `posix_spawn` mechanism as, by definition, the errors returned …
> std: introduce posix_spawn as an alt to fork-exec

- src/Sema.zig
- src/value.zig
- test/behavior/pointers.zig
This fixes one of the major issues plaguing the `std.sort` comptime tests.
The high level issue is that at comptime, we need to know whether `elem_ptr` is
being used to subslice an array-like pointer or access a child value. High-level
example:
var x: [2][2]i32 = undefined;
var a = &x[0]; // elem_ptr, type *[2]i32
var y: [5]i32 = undefined;
var b = y[1..3]; // elem_ptr, type *[2]i32
`a` is pointing directly to the 0th element of `x`. But `b` is
subslicing the 1st and 2nd element of `y`. At runtime with a well
defined memory layout, this is an inconsequential detail. At comptime,
the values aren't laid out exactly in-memory so we need to know the
difference.
This becomes an issue specifically in this case:
var c: []i32 = a;
var d: []i32 = b;
When converting the `*[N]T` to `[]T` we need to …
> stage2: elem_ptr needs to know if slice or direct access

- src/codegen/c.zig
- test/behavior/array.zig
Far from perfect I'm sure, but enables printing of test stats which is useful, and makes a few new tests pass.
As a bonus, while doing a pass on existing tests that were being skipped for the C backend I found more that are now passing, not necessarily due to my changes here..
```
$ build/zig build --zig-lib-dir lib --prefix stage2 -Denable-llvm -Dconfig_h=build/config.h && stage2/bin/zig test -I test/ -lc -ofmt=c test/behavior.zig
694 passed; 339 skipped; 0 failed.
```
> CBE: better handling of sentineled slices/arrays

- src/Sema.zig
- src/codegen/llvm.zig
- test/behavior/muladd.zig
Little bit unsure of the LLVM part for the`libc` strat for vectors, but it seems to work.
Using `expectEquals` on vectors runs into the following error:
```
$ zig test test/behavior/muladd.zig -Itest -fLLVM
/Users/<USER>/repos/zig/stage2/lib/zig/std/fmt.zig:765:18: error: unreachable else prong; all cases already handled
else => |e| return e,
```
Not sure if the else-prong actually is unreachable or if there is a bug, but I'll take a look and see what I find.
> Implement `@mulAdd` for vectors

- src/value.zig
- test/behavior/math.zig
A simple one, exercised by some stdlib tests (bit sets). 
Might be more useful to fix `std.math.big.int` to not crash in this case, but this is probably something that should avoid all the BigInt machinery anyways (as the TODO below my changes implies...)
> stage2: bit_not on u0 is always 0

- lib/std/debug.zig
This fixes lack of stack traces on arm64 macOS which were regressed
and not getting generated at all after this addition to write
current stack traces. Prior to this, function `isValidMemory` would
sync two subsequent pages if the aligned (base) address was different
than the frame pointer. I fail to see what the logic for such assumption
here is as the manual of `msync` clearly states it will fail with error
if the passed in memory region length contains unmapped regions.
This was the very reason why there were no stack traces print on
arm64 macOS as the second page was unmapped thus incorrectly flagging
the frame pointer as invalid.
cc @m-radomski
> debug: msync only current page when validating frame pointer

- src/Sema.zig
- src/codegen/llvm.zig
- test/behavior/byteswap.zig
Made the behavior tests for this a little more primitive to exercise as little extra functionality as possible.
~I did a test for `Vector(2, u0)`, which works in stage1, but currently fails in stage2 with an index out of bounds in `Sema.zirValidateArrayInit`. I tried to fix it but it seems like it has rabbit hole potential, so I'll leave it for another PR. Full error below.~
<details>
```
$ zig test test/behavior/byteswap.zig -Itest -fLLVM
thread 6462457 panic: index out of bounds
Analyzing test/behavior/byteswap.zig: byteswap.zig:test.@byteSwap vectors u0
%1059 = dbg_stmt(5, 5)
%1067 = block({
%1060 = dbg_stmt(5, 9)
%1061 = decl_val("builtin") token_offset:113:9
%1062 = field_val(%1061, "zig_backend") node_offset:113:16
%1063 = enum_literal("stage2_wasm") token_offset:113:33
%1064 = …
```
> Implement `@byteSwap` for vectors

- src/main.zig
gcc and clang do not strip by default, so it seems like `zig cc` and `zig c++` should match that behavior. For reference, current behavior been around ever since `zig cc` and `zig c++` were first added: https://github.com/ziglang/zig/commit/ead50ea6657d31632f5661f788b035a66c344d13.
If there's concern about making this change directly, we could add a flag to explicitly disable stripping, since currently it looks like the only way to do that is to enable some level of debuginfo in this invocation of the compiler.
Closes #11194.
> Don't strip by default in cc or c++

- src/arch/wasm/CodeGen.zig
- test/behavior/basic.zig
This implements the `memcpy` instruction, as well as improves the inline memcpy function.
We feature-detect for the availability of wasm's built-in instruction `memory.copy`. When the feature 'bulk-memory' is not enabled, we perform the operation ourselves.
When the length is comptime-known, we perform an inline loop, whereas we emit a regular runtime loop into the binary when the length is runtime known.
The same changes were made to the inline memset function and instructions such as `airWrapErrUnionErr` now use this to set the entire payload to 'undefined'.
> stage2: wasm - Implement memcpy instruction

- src/arch/aarch64/CodeGen.zig
- src/register_manager.zig
Previously, tryAllocRegs did not take frozen registers into account
when checking if enough registers are available.
This should fix the CI issue encountered in #11203.
> stage2 regalloc: fix tryAllocRegs for specific situations

- src/AstGen.zig
- test/behavior.zig
- test/behavior/bugs/11213.zig
They aren't inline blocks by nature of being labeled.
I'm not sure I fully grokked `break_inline` properly in this case, so I'm not 100% confident in this fix. It fixes the previous issue and all previous behavior tests continue to pass.
Fixes #11213
> AstGen: labeled blocks should always complete with a normal break

- src/type.zig
Test fails on stage2 without this change, but logically it should
be equivalent. I wasn't able to reduce this to an isolated case
demonstrating any issues with the compiler. I'm going to keep seeking
that out, but in the mean time I felt it was probably worthwhile for the
auto_hash tests to pass since we use auto hash significantly in the
compiler so this should help it compile itself.
> std: change error union hashing to use if/else format

- CMakeLists.txt
- lib/std/zig/c_builtins.zig
I added these builtins used in the [CRuby header files](https://github.com/ruby/ruby/tree/master/include):
- `__has_builtin` - Always returns true because unimplemented builtins give an "undefined identifier" error before it can be called.
- `__builtin_assume`
- `__builtin_unreachable`
- `__builtin_constant_p` - With a C compiler, this returns a non-zero value (`true`) if the given expression is known to be constant at compile time. AFAICT it's not possible to check for this in Zig, so we just return `false` (zero).
- `__builtin_mul_overflow`
> translate-c: add missing builtins used by CRuby

- src/Sema.zig
Example scenario:
test {
const a: i32 = blk: {
if (false) break :blk 24;
};
_ = a;
}
Prior to this, this would panic the compiler with a source needed error.
This provides the source as `sema.src`. This is not ideal, since the
line it points to is pretty far from the true issue. (One block out)
But, this prevents the compiler from straight up crashing and follows a
pattern used by similar ZIR which don't provide a src loc.
> stage2: fix crash that could happen if `as` zir fails

- src/Air.zig
- src/AstGen.zig
- src/Liveness.zig
- src/Sema.zig
- src/Zir.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/print_zir.zig
- test/behavior/struct.zig
- test/behavior/while.zig
This add `dbg_block_{begin,end}` which control visibility of debug info variables:
```zig
{
var a: u32 = undefined;
a = 0;
}
{
var a: u32 = undefined;
a = 1;
@breakpoint();
// p a
// before: 0
// after: 1
}
}
```
Fixes #7239 for stage2.
> stage2: add debug info for payload captures + inline function parameters

- doc/langref.html.in
- lib/std/fmt.zig
- src/stage1/astgen.cpp
- test/compile_errors.zig
This pull request attempts to remedy some issues that prevent the changes in #11191 from being able to properly debug some types. The issues there were caused by the fact that type names for dependent types, those declared in a generic struct for example, get a name based solely on the namespace and the name of the struct, and not the parent type. This caused, for example, that there would not be unique names for different kinds of [ArrayHashMap.Data structs](https://github.com/ziglang/zig/blob/ad5770eba40e0cc425c7a1eab4d37c6f9788d670/lib/std/array_hash_map.zig#L500) for different instances of `ArrayHashMap`. All of them would simply be called `std.array_hash_map.Data`. Since the printers for the scripts in #11191 work based on regexes and looking up member function names, this breaks …
> stage1: make type names more unique

- src/Sema.zig
- test/behavior/align.zig
This updates WipAnonDecl to require an alignment provided by the caller, which is used for explicitly aligned comptime allocs. Previously we were creating a pointer to the decl with the requested alignment, but the decl itself was given default alignment.
> stage2: Correctly align decls for comptime allocs

- src/arch/wasm/CodeGen.zig
- src/codegen.zig
- test/behavior/array.zig
- test/behavior/slice.zig
- test/behavior/tuple.zig
- test/behavior/union.zig
This implements/improves a bunch to get all behavior tests for unions, arrays, tuples, and slices passing.
- Implements `union_init` instruction (`@unionInit`).
- Correctly lowers parent pointers for element and field pointers. (recursively).
- Update `generateSymbol` to ask for a type's container layout, rather than assert it's always a struct (when it could be a tuple).
- When comparing pointers and they'd live inside the stack, we would be emitting the stack pointer itself rather than appending the offset from the stack pointer where the value lived. This meant that comparing pointers would always be equal to true.
> stage2: wasm - union_init and passing tests

- src/codegen/c.zig
- src/link/C/zig.h
- test/behavior/int_div.zig
- test/behavior/math.zig
Also enables the newly-passing `math.zig` tests, while splitting off the half-precision floating point tests until https://github.com/ziglang/zig/pull/10771 is merged.
> CBE: implement mod, divFloor, divTrunc, and enable more passing tests

- src/Sema.zig
Sorry for the noisy diff, but it was really weird that each branch on `elem{Ptr,Val}` had a different argument order, so I normalized them. I also used the term `indexable` instead of `array` when it wasn't specifically referring to a `[N]` type.
Broke out indexing into empty errors since they could be checked with less resolved information. Also moved comptime index bound checks for arrays to run them before bubbling up `undefined`.
Added ` +1 (sentinel)` to the length printout for sentinel-terminated arrays/slices since it was really weird & inconsistent that `index X outside array of length X` would only sometimes be an error.
Made `elemPtr{Array,Slice}` allow an `undefined` array/slice since it's not actually dereffing any pointers at this point in time. Instead, any attempt to use …
> stage2: add safety checks for index out of bounds

- lib/std/special/c.zig
- lib/std/special/compiler_rt.zig
Greetings.
I noticed that msvc stage1 build is broken due to [this commit](https://github.com/ziglang/zig/commit/b2a1b4c085b93d508c51307f40444252b8cd4d52). The error messages is like:
```
zig1.obj : error LNK2019: unresolved external symbol ceill referenced in function std.mem.sliceAsBytes.8517 [E:\zig\build-debug\zig.vcxproj]
```
I figured that it's missing these set of methods in `compiler_rt.zig`. This PR should fix the build.
Cheers!
> add compiler_rt ceilf/ceil/ceill

- lib/std/build/OptionsStep.zig
Due to #11226 `OptionsStep` can generate invalid code as seen here: https://github.com/ziglang/zig/issues/11240
```zig
pub const @".@build.src.shared.ZigVersion" = enum {
master,
@"0.7.0",
@"0.7.1",
@"0.8.0",
@"0.8.1",
@"0.9.0",
};
pub const data_version: .@build.src.shared.ZigVersion = .@build.src.shared.ZigVersion.master;
pub const @"std.log.Level" = enum {
err,
warn,
info,
debug,
};
pub const log_level: std.log.Level = std.log.Level.info;
```
```zig
pub const ZigVersion = enum {
master,
@"0.7.0",
@"0.7.1",
@"0.8.0",
@"0.8.1",
@"0.9.0",
};
pub const data_version: ZigVersion = ZigVersion.master;
pub const Level = enum {
err,
warn,
info,
debug,
};
pub const log_level: Level = Level.info;
```
Closes #11240
> Fix OptionsStep with enums after #11226

- lib/std/special/docs/main.js
- src/Autodoc.zig
Okay, so this *should* be a minimal working setup to check the Autodocs javascript file for type errors.
The `analysis.d.ts` file is for declaring what the structure of the eventual `zigAnalysis` object will be, and currently needs to be hand edited and checked for consistency with the actual `DocData` struct. I did preemptively include a type comment for the generated file, although I'm not sure if that will be the best way to ensure consistency.
In order to install and use TypeScript, just go to the `lib/std/special/docs` folder and run
```sh
npm install
```
then
```sh
npm exec tsc
```
in order to get it to type check the `main.js` file.
If you want it in watch mode:
```sh
npm exec tsc -- --watch
```
Also fixed the problem causing strict mode to error.
Also also note that there has been …
> Optional TypeScript for Autodocs development

- src/arch/x86_64/CodeGen.zig
- test/behavior/basic.zig
- test/behavior/eval.zig
The code for `airPtrElemVal` is identical to `airPtrElemPtr` except for an extra `mov` at the end.
Also made `copyToTmpRegister` and `genSetReg` (for `direct_load`/`got_load`) use the correct register alias for the type passed in (this was leading to constants getting loaded with the wrong size, for e.g. an `f32` was getting loaded with `mov rbx, QWORD PTR ds:0xc0000a0`)
Since I was touching `behavior/basic.zig` anyway I checked to see if any more tests where passing.
> stage2: x86_64: implement `ptr_elem_val`

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- test/behavior/cast.zig
stage1 and LLVM backend both use the `vcvt` group of instructions for these operations. Those require AVX512, so I opted `fisttp`/`fld` instead.
the `@floatToInt` test from `test/behavior/cast.zig` now passes for x86_64 backend.
> stage2: x86_64: implement `@floatToInt` for `f32` and `f64`

- src/Air.zig
- src/Liveness.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/value.zig
- test/behavior/vector.zig
There was _a lot_ here, so I can't really go over it all line by line, but I did break up the commits into very neatly contained changes with some context in each commit message for the reader's benefit. At a high level:
* Add `cmp_vector` AIR instruction
* Make most `Value` functions auto-vectorize based on arguments
* Make a lot of Sema & LLVM backend vector-agnostic using auto-vectorizing
* Enable `test/behavior/vector.zig'
> stage2: implement most vector operations in Sema and LLVM backend

- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/arch/wasm/Mir.zig
- test/behavior/popcount.zig
Implements the `@popCount` builtin instruction which means `std.debug.print` now works in the wasm backend :)
> stage2: wasm - Implement popcount instruction

- src/Sema.zig
- test/behavior/cast.zig
- test/compile_errors.zig
This PR has two changes split by commit, respectively.
First, it introduces out of bounds checking for comptime slicing. I matched the error messages with stage1.
Second, **this one I'm unsure if we want to match stage1 behavior** is to make it so that the following is true:
```zig
test {
comptime {
var array = [0:0]u8{};
var src_slice: [:0]u8 = &array;
var slice = src_slice[0..0];
try testing.expect(@TypeOf(slice) == *[0]u8);
// try testing.expect(@TypeOf(slice) == *[0:0]u8); prior stage2 behavior
}
}
```
This is the stage1 behavior. The stage 2 behavior was to create a `*[0:0]u8`. 
What makes this weird is that arrays behave differently in stage1. For arrays, if the end of a slice equals the length and the source type has a sentinel, it adds the sentinel. Stage2 previously did this …
> stage2: slice bounds checks at comptime, slicing with sentinel matching stage1

- lib/std/build.zig
- src/Compilation.zig
- src/link.zig
- src/link/MachO.zig
- src/link/MachO/CodeSignature.zig
- src/main.zig
With this change, we can now bake in entitlements into the binary.
Additionally, I see this as the first step towards full code signature
support which includes baking in Apple issued certificates for
redistribution, etc.
> macho: extend CodeSignature to accept entitlements

- src/main.zig
since the native paths are expected to be linked by default adding them to the rpath is pointless.
> ignore target lib dirs when invoked with -feach-lib-rpath

- src/main.zig
Reverts ziglang/zig#10621
Introduced a regression when building stage2 on nixOS where the linker would fail to find relevant LLVM dynamic libraries as some search dirs were missing.
> Revert "ignore target lib dirs when invoked with -feach-lib-rpath"

- src/Compilation.zig
- src/Module.zig
- src/RangeSet.zig
- src/Sema.zig
- src/TypedValue.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/arm/Emit.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/codegen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/link.zig
- src/link/C.zig
- src/link/Dwarf.zig
- src/link/MachO.zig
- src/print_air.zig
- src/type.zig
- src/value.zig
- test/behavior.zig
- test/behavior/struct_contains_slice_of_itself.zig
- test/stage2/x86_64.zig
The main change here is adding `target: Target` to all the functions that deal with Type and Value so that the new Value tag `lazy_align` can be resolved when it is time.
I also added advanced versions of some Value methods so that they can take an optional *Sema, *Block, and LazySourceLocation, and perform resolution sometimes.
> stage2: lazy `@alignOf`

- lib/std/os/linux/arm-eabi.zig
- lib/std/os/linux/arm64.zig
- lib/std/os/linux/i386.zig
- lib/std/os/linux/powerpc.zig
- lib/std/os/linux/powerpc64.zig
- lib/std/os/linux/sparc64.zig
- lib/std/os/linux/x86_64.zig
> Fix ucontext_t

- src/codegen/c.zig
- test/behavior/error.zig
- test/behavior/ptrcast.zig
- test/behavior/union.zig
Various fixes/improvements to the C backend to improve error/union support.
This also fixes up our handling of decls, where some decls were not correctly marked alive. Also had to tweak a few of the @ptrCast tests so that they avoid memory accesses that are well-defined in Zig but UB in C.
> stage2 CBE: Improve support for unions and error sets

- lib/std/c.zig
Current `Thread.Semaphore` in standard library cannot be used across process.
Here's a simple example for using semaphore with current API:
```zig
const PROT = std.os.PROT;
const MAP = std.os.MAP;
const sem_t = std.c.sem_t;
// make sure child always prints first
var shm_addr = try std.os.mmap(null, @sizeOf(sem_t), PROT.READ | PROT.WRITE, MAP.SHARED | MAP.ANONYMOUS, 0, 0);
var semaphore = @ptrCast(*sem_t, &shm_addr[0]);
if (std.c.sem_init(semaphore, 1, 0) != 0) return error.SemaphoreFailed;
const pid = try std.os.fork();
if (pid == 0) {
std.debug.print("child\n", .{});
if (std.c.sem_post(semaphore) != 0) return error.SemaphoreFailed;
} else {
if (std.c.sem_wait(semaphore) != 0) return error.SemaphoreFailed; …
```
> Add sem_open sem_close C definition to standard library

- src/Sema.zig
- test/behavior/slice.zig
hundo p for `test/behavior/slice.zig`
> stage2: concat/mult of slices should yield a ptr to an array

- test/behavior/array.zig
- test/behavior/math.zig
I didn't realize before that there were vector tests outside of `vector.zig`. I also found an array ABI size test that seems to pass.
> stage2: enable some passing array & vector tests

- src/Sema.zig
- test/behavior/eval.zig
Resolves #11272 - `tokenizer` is 100% ✅ 
Sema.pointerDeref() assumes that elem_ptrs have been "flattened" when they were created. That is, an elem_ptr should never be the array_ptr of another elem_ptr if they share the same types.
Value.elemPtr does this already, but a couple of places in Sema were bypassing this logic.
> stage2: Properly "flatten" elem_ptrs before deref

- src/Sema.zig
- test/behavior/slice.zig
- test/compile_errors.zig
The runtime behavior allowed this in both stage1 and stage2, but stage1
fails at comptime with index out of bounds. This behavior should not fail,
comptime behavior should match runtime behavior. I implemented this
only in stage2.
> stage2: able to slice to sentinel index at comptime

- src/arch/x86_64/CodeGen.zig
- src/link/Dwarf.zig
- test/behavior/array.zig
- test/behavior/struct.zig
- test/behavior/tuple.zig
* dwarf: add debug info for tuples and anon structs
* x64: implement `aggregate_init` for structs
* x64: implement `aggregate_init` for arrays
* x64: fix `struct_field_val` for structs fitting in a register - masking has to go via a temp register to avoid accidentally extending it to 8 bytes, and we ought to account for signed ints by move-sign-extending the result
* pass more behaviour tests including tuples!
> stage2: add debug info for tuples (and anon structs), and implement aggregate_init for structs and arrays

- doc/langref.html.in
It includes:
- `<style>` content indentation fix, so that content collapsing works (at least in VSCode) regardless of the selected file format.
- small rephrasing as described in #11091.
> chore: doc fixes, closes 11091

- src/translate_c.zig
- src/translate_c/ast.zig
Removes translate-c usage of std.meta.Vector, which was deprecated in d42d31f72f
> translate-c: Use @Vector for vector expressions

- src/AstGen.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- src/type.zig
- src/value.zig
- test/behavior/call.zig
* AstGen: restore the param_type ZIR instruction and pass it to the
expression for function call arguments. This does not solve the
problem for generic function parameters, but it catches stage2 up to
stage1 which also does not solve the problem for generic function
parameters.
- Most of the enhancements in this commit will still be needed for a
more sophisticated further improvement to handle generic function
types.
- In Sema, handling of `as` coercion recognizes the `var_args_param`
Type Tag and passes the operand through doing no coercion.
- That was the last ZIR tag and we are now using all 256 ZIR tags.
* AstGen: array init and struct init expressions use the anon form even
when the result location has a type. Prevents the type system
incorrectly believing, for example, that a tuple …
> stage2: result location types for function call arguments

- src/arch/wasm/CodeGen.zig
- src/link/Wasm.zig
- test/behavior/basic.zig
- test/behavior/bitcast.zig
- test/behavior/bugs/4328.zig
- test/behavior/ptrcast.zig
- test/behavior/type_info.zig
Rather than creating an import for externs on `updateDecl`, we now generate them when they're referenced. e.g. when performing a function call on an extern function. This is required so using `@typeof(someExternFn())` will not emit the import into the binary (causing an incorrect function type index as it won't be fully analyzed).
> stage2: wasm - Only create imports when an extern is referenced

- src/Air.zig
- src/Liveness.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/print_air.zig
This partially implements #10248 but retains compatibility with the current signature and semantics of `@addWithOverflow` and similar builtins.
This paves the way for implementing these AIR instructions efficiently in self-hosted backends and should also help unblocking https://github.com/ziglang/zig/pull/11174.
> stage2: Change semantics of AIR arithmetic overflow instructions

- src/Module.zig
- src/Sema.zig
Greetings!
This commit implements the TODO above `Module.Namespace.Decl` that uses hash map context to save memory.
There's a few things that I'm not sure:
1. Should I use `mem.sliceTo(s, 0)` or `mem.span(s)` to convert `[*:0]const u8` to slice?
2. Is this the intended way to "Save Memory"? Or maybe it's about doing the string table buffer approach as in AstGen?
Cheers!
> `Namespace.decls` use context to save memory

- lib/std/fs.zig
Fixes #11178.
As per discussion on IRC, return error.Unexpected directly rather than calling `os.unexpectedErrno()` to avoid a stack trace in debugging mode. It may be an unexpected error, but it's known to happen and won't need further patching in Zig.
> std.fs: Handle EINVAL from linux.getdents64

- src/Sema.zig
- src/type.zig
I wasn't too sure about how to split up the check between `sema.zirBitcast` and `sema.bitCast`, so it's very possible that things need to move around a bit.
I added more detailed error messages for a couple of cases cause I think it will be very common for people to mix up `@bitCast` and `@ptrCast`. As far as I know the compiler error tests are not implemented yet for stage2 so sadly there's no tests in this PR. I'll happily add them once these tests are enabled for stage2.
One improvement I would like to make but couldn't figure out is to elide the entire call to `@bitCast` if the thing you're bitcasting already has the correct type. So in other words,
```zig
if (operand_ty == dest_ty) {
// What do I return here???
}
```
If anyone has any hints of what to do there please let me know!
> stage2: add type checking for @bitCast

- lib/std/child_process.zig
- lib/std/testing.zig
continuation of #11093 to simplify testing IPC
* use cases
- get path to temporary directory
- get the test arguments inside test block for reusage
- build executables from text within test blocks, ie to test IPC
* missing conventions
- how to name and debug test cases
- where do simple+repititve build commands for testing belong
> std.testing: add methods tmpDirPath, getTestArgs, buildExe

- src/stage1/codegen.cpp
- test/behavior/widening.zig
This PR is an attempt to fix #11317. It implements special case of `u0` in `gen_widen_or_shorten`.
> stage1: implement casting from u0

- lib/std/math/complex.zig
Added methods to the complex number structure:
1) negation - simply negate the real part, and negate the imaginary part.  This is needed for stringing together mathematical operations without invoking a complex multiply (which may be costly).
2) mulbyi - multiplies a complex number by i=sqrt(-1).  BUT, this is done without invoking a complex multiply (which may be costly with its 4 required operations).  Effectively, this "rotates" any number on the complex plane by 90 degrees.  The operation is found often (such as in FFT routines).  Can be common in inner loops.  
NOTE A: I think that the name "mulbyi" is not optimal, but other names I had considered (muli, rot90, imul, imult) all were a bit underwhelming.
NOTE B: It understood that one may create their own complex struct and implement …
> added 'negation' and 'mulitply by i' for complex numbers

- src/arch/wasm/CodeGen.zig
- test/behavior/math.zig
Implements the following instructions:
- `@addWithOverflow`
- `@subWithOverflow`
- `@shlWithOverflow`
- `@mulWithOverflow`
This already uses the new semantics from #10248 meaning we create a tuple that stores the result as well as the overflow bit.
> stage2: wasm - Implement overflow arithmetic

- src/Sema.zig
- test/behavior/eval.zig
- test/behavior/fn.zig
- test/behavior/for.zig
- test/behavior/int128.zig
- test/behavior/slice.zig
- test/compile_errors/stage2/slice_of_null_pointer.zig
I'll add a compiler error test once #11284 is figured out...
Note: this forces some behavior tests for the CBE to be disabled because it is failing at rendering `int_big_positive` correctly for the max int values that are generated during the safety checks.
> stage2: runtime safety checks for slicing a null C pointer and @intCast truncating bits

- lib/std/mem.zig
Closes #11323
Issue was that if an empty tuple was passed as the initialiser, `zeroInit` would return a zeroed struct. Correct behaviour is to return the struct with default field values, with the rest being zeroed. This PR fixes this behaviour and implements a test case to prevent future regressions.
> std.mem.zeroInit: Fix behaviour with empty initialiser

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- test/behavior/math.zig
Partially implements `add_with_overflow`, `sub_with_overflow` and `mul_with_overflow`. Things still missing:
* non-byte-sized integers need truncation added (AFAICT)
* multiplication currently doesn't handle byte-sized ints at all
All in all, this should unblock #11316 and in the meantime I will work on rectifying the above points.
> x64: implement add, sub and mul with overflow

- src/codegen/c.zig
- test/behavior/eval.zig
- test/behavior/fn.zig
- test/behavior/for.zig
- test/behavior/int128.zig
- test/behavior/slice.zig
Commit 052079c99455d01312d377d72fa1b8b5c0b22aad surfaced two issues with the generated C code:
- `renderInt128()` contained a seemingly unnecessary assertion to verify that the high 64 bits of the number were nonzero, dating back to 9bf1681990fe87a6b2e5fc644a89f1aece304579. I removed it.
- `renderValue()` didn't have any special handling for undefined structs, falling back to printing `{}` which generated invalid expressions such as `return {}` for functions returning structs, whereas `return (S){}` is the correct form. I changed it accordingly.
At the same time I'm reenabling the relevant tests.
> CBE: fix C output after PR #11302, reenable tests

- lib/std/crypto/aes/aesni.zig
- lib/std/crypto/aes/armcrypto.zig
- lib/std/crypto/chacha20.zig
- lib/std/crypto/ghash.zig
- lib/std/crypto/gimli.zig
- lib/std/crypto/salsa20.zig
- lib/std/crypto/utils.zig
- lib/std/fmt.zig
- lib/std/math.zig
- lib/std/simd.zig
- lib/std/special/compiler_rt/multi3.zig
- lib/std/target.zig
- test/behavior/floatop.zig
- test/behavior/math.zig
- test/behavior/type.zig
- test/behavior/type_info.zig
- test/runtime_safety.zig
followup to https://github.com/ziglang/zig/commit/7be340e3cc62285d77cbd13f19f4ff0a2a982e82
> std: replace other uses of `std.meta.Vector` with `@Vector`

- src/arch/aarch64/Emit.zig
- src/arch/arm/Emit.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/riscv64/Emit.zig
- src/arch/x86_64/Emit.zig
- src/codegen.zig
- src/link/Dwarf.zig
- src/link/Elf.zig
- src/link/MachO.zig
Avoids many pitfalls connected with premature/early return in case
there are errors with Decl, etc. This is effectively bringing back
the old design however in a much nicer packaging, where every
mechanism related to tracking Decl's debug info is now nicely
wrapped in a single struct (aka the `DeclState`). This includes
relocation table, type arena, etc. It is now the caller's
responsibility to deinit the state (so that no memory is leaked)
after `Decl` has been analysed (or errored out). The caller here
is typically a linker such as `Elf` or `MachO`.
cc @andrewrk redone fix of https://github.com/ziglang/zig/commit/e39c86399da565d3855d54b242bf7b5940e3924d
> dwarf: pass DeclState around instead of storing a temp global in Dwarf

- src/AstGen.zig
- src/Sema.zig
- src/codegen/c.zig
- test/behavior.zig
- test/behavior/asm.zig
Now the `"sized integer/float in asm input"` test case of `test/behavior/asm.zig` passes, which is admittedly not a big win, but it gets us an inch closer to having working asm expressions.
In order for these tests to run on stage2 I moved it out of the `if (builtin.zig_backend == .stage1)` block in `test/behavior.zig`, while adding the `SkipZigTest` clauses on most tests and for most backends. Please double check if I missed any :sweat_smile:
> CBE: improve support for asm inputs

- lib/std/dwarf.zig
This was causing freestanding builds to fail due to the use of `std.debug.print`
Unsure if this is the correct path to take (as potentially valuable output is lost) - happy to accept feedback and adjust as needed.
> Remove a std.debug.print from the dwarf.zig file

- src/AstGen.zig
- src/Zir.zig
- src/print_zir.zig
fix the line and column printed in Zir for calls to `@src()`
also fixes #11354
> stage2: fix print_zir for .builtin_src

- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/arch/wasm/Mir.zig
- test/behavior/floatop.zig
- test/behavior/math.zig
- test/behavior/maximum_minimum.zig
- test/behavior/muladd.zig
Implements the following builtins for the wasm backend for types with bitsize <= 64.
- `@maximum` 
- `@minimum`
- `@mulAdd`
- `@clz`
- `@ctz`
> stage2: wasm - Implement more builtins

- src/codegen/llvm.zig
- test/behavior/error.zig
I'm not sure if the order of the fields is important or not because this would likely be easier solved by swapping the order.
Closes #11340
`-Dskip-install-lib-files` is still required due to #11375.
> stage2 llvm: properly align error union payload

- doc/langref.html.in
> langref: rename incorrect expect to assert

- src/arch/arm/Emit.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- src/arch/x86_64/PrintMir.zig
- src/link/Dwarf.zig
Add support for emitting debug info for local variables within a subprogram.
This required moving bits responsible for populating the debug info back to
`CodeGen` from `Emit` as we require the operand to be resolved at callsite
plus we need to know its type. Without enforcing this, we could end up
with a `dead` mcv.
> dwarf: emit debug info for local variables on x86_64

- lib/std/Thread/Futex.zig
- lib/std/compress/deflate/compressor.zig
- lib/std/crypto/argon2.zig
- lib/std/crypto/scrypt.zig
- lib/std/math.zig
- lib/std/math/big/int.zig
- lib/std/mem/Allocator.zig
- lib/std/os.zig
- lib/std/os/uefi/pool_allocator.zig
- lib/std/os/uefi/tables/boot_services.zig
- lib/std/packed_int_array.zig
- lib/std/simd.zig
- lib/std/time.zig
- lib/std/x/net/tcp.zig
- lib/std/x/os/socket_posix.zig
- lib/std/zig/parser_test.zig
- lib/std/zig/render.zig
- lib/std/zig/string_literal.zig
- src/arch/wasm/Mir.zig
- src/arch/x86_64/Mir.zig
- src/link/Elf.zig
- src/link/MachO.zig
Fixes #11353 
The renderer treats comments and doc comments differently since doc comments are parsed into the Ast. This commit adds a check after getting the text for the doc comment and trims whitespace at the end before rendering.
> zig fmt: remove trailing whitespace on doc comments

- src/arch/wasm/CodeGen.zig
- src/arch/wasm/Emit.zig
- src/arch/wasm/Mir.zig
Rather than using blocks and control flow to check which operand is maximum or minimum, we use wasm's `select` instruction which returns us the operand based on the 3rd operand. (In this case, we can use the comparison between lhs and rhs to determine which operand to select). This saves us the need for control flow, as well as reduces the instruction count from 13 to 7 per `@maximum` or `@minimum` callsite.
> stage2: wasm - reduce instruction count for `@maximum` and `@minimum`

- lib/std/Thread/Condition.zig
I needed the equivalent of `std::condition_variable::wait_for`, but it's missing in std.
This PR adds an implementation, following the status quo of using std.os.CLOCK.REALTIME in the pthread case (i.e. Futex)
A follow-up patch moving futex/condition stuff to monotonic clocks where available seems like a good idea.
This would involve conditionally exposing more functions and constants through std.c and std.os.
For instance, Chromium picks `pthread_cond_timedwait_relative_np` on macOS and `clock_gettime(CLOCK_MONOTONIC...)` on BSD's.
Tested on Windows 11, macOS 12.2.1 and Linux (with/without libc)
> std: add Thread.Condition.timedWait

- doc/langref.html.in
5a53ab28 removed these as keywords, and the Primitive Values section
of the docs already exists to describe them.
> Remove primitive values from keyword reference

- lib/std/unicode.zig
I noticed that this function was repeating code that was already written before: https://github.com/ziglang/zig/blob/6ae8fe193bd5397b9fceea98ba684d9d870286cf/lib/std/unicode.zig#L71
> Reuse code in `Utf8Iterator.nextCodepoint`

- src/test.zig
Follow-up to #11417.
I went ahead and reverted the reported `update_index` to also be 0-indexed.
P.S. I took a look to move over any existing incremental tests, but I don't think we have any yet for stage2
> Use 0-indexing for incremental compile error tests

- lib/std/fs/test.zig
Follow up to https://github.com/ziglang/zig/pull/11413#issuecomment-1096056393 and https://github.com/ziglang/zig/pull/11416 (tangentially)
Looks like d3f87f8ac01039722197a13a12342fc747a90567 fixed the standard cases of dir renaming, but the edge cases (renaming onto an existing empty/non-empty directory) are still behaving differently than on non-Windows.
> Enable passing 'Dir.rename directories' fs test on Windows

- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
- src/link/Dwarf.zig
- src/link/MachO.zig
- src/link/MachO/DebugSymbols.zig
* x64: recursively mark decls as alive when lowering
* x64: generate debug info for local vars at hardcoded memory address (non-PIE)
* dwarf: generate debug info for arrays
* x64: deref memory address if referenced via GOT when computing the exprloc for a local variable stored in memory
* x64+macho: resolve debug info relocs for RIP-based addressing after symbols were allocated VM addresses - sometimes we will want to generate debug info for a constant that has been lowered to memory and not copied anywhere else. For this we will need to defer resolution on PIE platforms until all locals (including GOT entries) have been allocated.
cc @joachimschmidt557 @Luukdegram @andrewrk this fixes the compiler panic we discussed during the Zig Meetup in Milan.
> stage2: fix (recursively) marking decls as alive, and improve DWARF for local vars

- lib/std/priority_queue.zig
Fix to call siftDown on the removed index instead of always on index 0.
Updated test to a test that fails before and passes now.
PriorityDequeue does not have this issue.
> Fix bug in PriorityQueue::removeIndex()

- lib/std/math/float.zig
319555a6690a43de143698f13d6d107a7873dce0 introduced this change:
```diff
-    return if (T == f80) 1 << floatFractionalBits(T) else 0;
+    return if (floatMantissaDigits(T) == 64) 1 << 63 else 0;
```
However, this prevents an `f80` backed `c_longdouble` from getting the explicit integer part since it's not `== f80`. There's not a lot of test coverage for `c_longdouble` at the moment but I noticed this at a second glance so I thought I'd make a quick PR.
> std.math.float: fix f80-backed c_longdouble consts

- src/link/Wasm.zig
- src/link/Wasm/Atom.zig
- src/link/Wasm/Object.zig
- src/link/Wasm/types.zig
Previously, the data segments were being aligned twice. This caused us to over-align the segment and therefore allocate a much larger size for each segment than was required. This fix ensures we align and set the size just once, ensuring semantically correct binaries as well as smaller binaries.
> stage2: wasm-linker - Fix segment alignment/size

- lib/std/fs.zig
- lib/std/fs/test.zig
The call to `makeDir` for the top-level component of `sub_path`
can return `error.FileNotFound` if the directory represented by
`self` has been deleted.
Fixes #11397
> std.fs: prevent possible integer overflow in Dir.makePath

- lib/std/fmt.zig
- lib/std/unicode.zig
This is a possible improvement I found while working on an `std.unicode.Char` and `std.unicode.Codepoint` (https://github.com/r00ster91/zig/commit/02da6dc26e011bcebc25b899f275e5d2c6c8ca44) which, after some discussion, seemed better not to pull. Instead, it's only this.
There are already 2 places within `std` where code related to this is kind of duplicated and I thought this constant could be useful to general applications as well.
For reference here is what this looks like in other languages:
* https://doc.rust-lang.org/std/primitive.char.html#associatedconstant.REPLACEMENT_CHARACTER
* https://crystal-lang.org/api/Char.html#REPLACEMENT
The problem this solves is that you don't have to memorize or look up this constant yourself. I would understand if that alone doesn't justify adding …
> Add `std.unicode.replacement_character`

- src/Sema.zig
- src/type.zig
- test/compile_errors/stage2/struct_duplicate_field_name.zig
- test/compile_errors/stage2/union_access_of_inactive_field.zig
- test/compile_errors/stage2/union_duplicate_enum_field.zig
- test/compile_errors/stage2/union_duplicate_field_definition.zig
- test/compile_errors/stage2/union_enum_field_missing.zig
- test/compile_errors/stage2/union_extra_field.zig
- test/compile_errors/stage2/union_runtime_coercion_from_enum.zig
To match stage1. For the most part, the error messages are the same, but in some cases I've added some extra information or reformatted it to match how stage2 reports errors.
> stage2: add more union compile errors / improve error messages

- lib/std/math.zig
> std/math.zig: resolve missed optimization in rotates

- src/arch/arm/CodeGen.zig
- src/arch/arm/Emit.zig
- src/arch/arm/Mir.zig
This removes the questionable Air -> Mir dependency that existed
before. The x86_64 backend also performed this change.
cc @kubkon
> stage2 ARM: move genArgDbgInfo back to CodeGen

- CMakeLists.txt
- lib/std/std.zig
- lib/std/treap.zig
A [Treap](https://en.wikipedia.org/wiki/Treap) is a randomized binary search tree. The "randomized" part means that, after every update, the shape of the tree is dependent on the RNG's distribution but the height is highly probable to be `log n` where n = unique keys/nodes.
The reason for adding a Treap in the standard library over more common self-balancing binary search trees like [AVL](https://en.wikipedia.org/wiki/AVL_tree) and [RedBlack](https://en.wikipedia.org/wiki/Red%E2%80%93black_tree) is that the implementation is iterative, requires similar Node overhead, and (most importantly) is relatively much simpler.
The API supports getting the min/max nodes and getting "Entry"s by key lookup or from an existing/inserted node. Inserts, updates, and deletions are all done through an Entry …
> Introduce std.Treap

- lib/std/math/fabs.zig
- lib/std/math/isfinite.zig
- lib/std/math/isinf.zig
- lib/std/math/isnormal.zig
- Enables tests skipped due to #11391 being open, which was fixed by 319b5cbce5d4c43de8a6848ac5f5c8879ab9806e.
- Enables f80 testing on `fabs` which I did not add in cb019b80ac8ae8ffd7f7dd619c4da29a83668cde because that same issue was open.
> re-enable f80 tests on freebsd

- lib/std/special/compiler_rt/atomics.zig
Some SPARC CPUs (particularly old and/or embedded ones) only has atomic TAS instruction available (`ldstub`). This adds support for emitting that instruction in the spinlock.
> compiler_rt: atomics: Add TAS lock support for SPARC

- lib/std/start.zig
- lib/std/target.zig
- src/link.zig
- src/link/MachO.zig
- src/stage1/target.cpp
- src/type.zig
- test/behavior/cast.zig
Turns out, `c_longdouble` is not `f128` but rather `f64` on aarch64 Darwin:
> The long double type is a double precision IEEE754 binary floating-point type, which makes it identical to the double type. This behavior contrasts to the standard specification, in which a long double is a quad-precision, IEEE754 binary, floating-point type.
[Writing ARM64 Code for Apple Platforms](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms)
I am leaving this PR as draft until @andrewrk and myself work out how to handle premature exit from `link.makeExecutable` function for stage2. This premature exit means we don't move the final executable in place leading to a sigkill from the kernel as we have overwritten the contents of a file/inode that was already run and …
> stage2: fix behavior test failures on aarch64-macos (LLVM+native), and other minor fixes

- doc/langref.html.in
- lib/std/fs/path.zig
- lib/std/fs/test.zig
- lib/std/fs/wasi.zig
- lib/std/os.zig
- lib/std/os/test.zig
- lib/std/testing.zig
Dependent on #11021 .
Some more work is needed to align our CWD treatment on WASI with wasi-libc. This is particularly important for runtimes like wasmer, which inserts a special "/" Preopen by default and also strips leading slashes from other Preopens
Here's the idea behind these changes:
1. We store the CWD as a simple `[]const u8`. We lookup Preopens for every absolute or CWD-referenced file operation, based on the Preopen with the longest match (i.e. most specific path)
2. Preorders are normalized to POSIX absolute paths at init time, based on the `cwd_root` parameter of `initPreopensWasi`.  cwd_root is used _only_ for any Preopens that start with "." so that:
```
"./foo/bar" ~ canonicalizes to ~> "{cwd_root}/foo/bar"
"foo/bar"   ~ canonicalizes to ~> "/foo/bar"
"/foo/bar"  ~ …
```
> stdlib std.os: Update CWD emulation to match wasi-libc behavior

- lib/std/os/uefi.zig
the `@byteSwap` looks sus but it's actually how GUIDs are formatted
Also swaps to using fmtSliceHexLower over the deprecated {x}
> std.os.uefi: fix GUID formatting

- lib/std/array_hash_map.zig
4th argument was added in cf88cf2657d721c68055a284e8c498a18639f74c
> Update doc comment of ArrayHashMap to include 4th arg in eql fns

- src/main.zig
Example:
$ zig cc -o main.exe main.cpp -target x86_64-windows -Wl,--subsystem,windows
Closes #11389
> zig cc: support --subsystem linker flag

- lib/std/fs.zig
- src/Cache.zig
- src/introspect.zig
- src/main.zig
Dependent on #11053. Resolves #10716.
This PR adds support for locating the Zig executable and the library and global cache directories, based on looking in the fixed "/zig" and "/cache" directories. It also bypasses the file-locking in "src/Cache.zig" and initializes the WASI preopens on startup.
The expected directories can be provided on the command-line using `--mapdir`, as follows:
```
wasmtime --mapdir=/cwd::. --mapdir=/cache::"$HOME/.cache/zig" --mapdir=/zig::./stage2-wasm/ ./stage2-wasm/bin/zig.wasm
```
The reason for the fixed directories is that argv[0] on WASI is just the basename (any absolute/relative path information is deleted by the runtime) and there is no WASI-equivalent to procfs.
This is enough to get stage2 running without LLVM on WASI:
```bash
$ ./build/zig build …
```
> stage2: Add limited WASI support for selfExePath and globalCacheDir

- src/arch/wasm/CodeGen.zig
Found this (typo?) while working on another change.
> wasm: fix lowerDeclRefValue using wrong Decl

- lib/std/debug.zig
- src/arch/wasm/CodeGen.zig
- src/link/Wasm.zig
- src/stage1/codegen.cpp
- src/stage1/target.cpp
- src/target.zig
This adds support for DWARF information for the wasm target. This does, however, not add support for stack traces yet. This implements support for both stage1 and stage2 (LLVM-backend).
Closes #11330 
Fixes #11420 
Here's an example of what it would look like in Chrome:
I tried to find some information regarding targets that do not support any form of debug information, but couldn't find anything about that. So for now, I changed `hasDebugInfo` to always return true.
> Wasm: add support for debug information

- lib/std/os/uefi/protocols.zig
- lib/std/os/uefi/protocols/block_io_protocol.zig
Useful for anything which needs access to actual disk data directly, e.g. reading fs and gpt headers.
> std.os.uefi: Add `BlockIoProtocol`

- doc/langref.html.in
For those souls looking for a zig `size_t` equivalent, and not
lucky/educated enough (that was me yesterday) to know it's the same as
`uintptr_t`.
From a recent discussion on IRC.
> [doc update] add size_t

- lib/std/coff.zig
- lib/std/debug.zig
- lib/std/dwarf.zig
- lib/std/pdb.zig
- src/link/MachO/Object.zig
Fixes #4353
While not a complete rewrite as suggested in #4353, it does clean up the problems with resources in non-terminating scenarios, i.e., you can use the modules with your custom allocator, and properly deinit any allocated resources. Another by-product of this PR is the fact that the MachO linker no longer leaks memory courtesy of relying on `std.dwarf` module - this is a prereq for my work on the linker test harness which will by default target stage2 LLVM backend. Anyhow, I will most likely look into cleaning up the design of `std.dwarf` (if needed) when I get to working on translating DWARF info from relocatable object files into relocated sections part of the output dSYM bundle for stage2 (LLVM and native backends).
---
* dwarf: clean up allocations in `std.dwarf` module - …
> dwarf+debug: clean up resources mgmt

- lib/std/child_process.zig
This PR fixes the issue mentioned in issue #11470
> Fix child process spawn on macos hangs with stdin, stdout behavior set to pipe

- src/Cache.zig
- src/Compilation.zig
- src/Module.zig
- src/stage1.zig
Adapting the logic used for @import and @embedFile, we needed to ensure that the include files generated by the clang dependency file are added to the whole cache manifest in addition to the c-object specific ones.
Due to the fact that these are scheduled on worker threads - the whole cache needs to be locked with a mutex on access, a heavy handed solution but workable in the short term.
This resolves  #11063
> Fix C include files not being in `whole` cache

- lib/std/os/windows/kernel32.zig
Added one missing Windows API.
> std.os.windows.kernel32: add GetProcessTimes binding

- lib/std/Thread.zig
- lib/std/Thread/Condition.zig
- lib/std/Thread/Futex.zig
- lib/std/Thread/Mutex.zig
- lib/std/atomic/Atomic.zig
- lib/std/heap/general_purpose_allocator.zig
- lib/std/os/windows.zig
- Optimize Mutex and Condiiton implementations to use Futex based algorithms.
- More robust tests for Mutex and Condition.
- More documentation in general, but specifically about Condition semantics.
- Guarantee at most `u64` large sync primitives (if Futex is removed in the future, they can always be made [`usize` large](https://github.com/kprotty/usync)).
- Introduce `std.Thread.Futex.Deadline` for accurately waiting on a Futex in a loop with a relative timeout.
- currently used by Condition's futex impl.
- will be used by Semaphore and ResetEvent's futex impl.
> std.Thread: Mutex and Condition improvements

- lib/std/crypto/benchmark.zig
- lib/std/hash/benchmark.zig
Hi! 
I stumbled upon crypto and hash benchmarks in std lib and noticed they don't compile. This PR should've fixed it.
Test run results on my box:
```
wyhash
iterative:  8516 MiB/s [84b9fcc452c9983b]
small keys: 10375 MiB/s [c5c45b09b8000000]
fnv1a
iterative:  1072 MiB/s [1e3d9d378e4b7325]
small keys:  1319 MiB/s [a799f41e7c700000]
adler32
iterative:  2865 MiB/s [a302147400000000]
small keys:  2862 MiB/s [95923dd300000000]
crc32-slicing-by-8
iterative:  2832 MiB/s [ab94acd000000000]
small keys:  3456 MiB/s [9c2cae1900000000]
crc32-half-byte-lookup
iterative:   266 MiB/s [ab94acd000000000]
small keys:   279 MiB/s [9c2cae1900000000]
cityhash-32
small keys:  6425 MiB/s [a22f04f100000000]
cityhash-64
small keys: 16707 MiB/s [4efcdec62d500000]
murmur2-32
small keys:  5448 MiB/s …
```
> std: fix crypto and hash benchmark

- src/arch/wasm/CodeGen.zig
- src/arch/wasm/abi.zig
This implements an initial round of changes to support the C-ABI as specified by https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md.
The goal of these changes is to implement the base required to support linking with compiler-rt. As compiler-rt will be built by the LLVM backend by default, we must ensure the ABI's between the backends match. Above mentioned C-ABI matches that of clang to ensure we have maximum compatibility with other compilers as well.
There are definitely some rough edges with regards to branching (in the backend) and codegen that could be improved. But before doing that, I'd like to implement basic compiler-rt linking first, so I get a better view of how to structure the backend.
In the near future, I'd like to enable the C-ABI tests specified in …
> stage2: wasm - Initial C-ABI implementation

- lib/std/fmt.zig
- lib/std/math/signbit.zig
- lib/std/special/compiler_rt.zig
- lib/std/special/compiler_rt/README.md
- lib/std/special/compiler_rt/addXf3.zig
- lib/std/special/compiler_rt/addXf3_test.zig
- lib/std/special/compiler_rt/divdf3.zig
- lib/std/special/compiler_rt/divxf3.zig
- lib/std/special/compiler_rt/divxf3_test.zig
- lib/std/special/compiler_rt/fmodq.zig
- lib/std/special/compiler_rt/fmodq_test.zig
- lib/std/special/compiler_rt/fmodx.zig
- lib/std/special/compiler_rt/fmodx_test.zig
- lib/std/special/compiler_rt/mulXf3.zig
- lib/std/special/compiler_rt/mulXf3_test.zig
This change also includes several additional bugfixes:
- Rounding edge case with f80 sub-normals in `__mulXf3`
- Incorrect subtraction in `fmodq`
- Hex-float printing in `std.fmt` for f80
Here's the throughput of the new functions compared to their peers (MiB/s):
|     |    f32   |    f64   |    f80 (new)  |   f128   |
|-----|----------|----------|----------|----------|
|  __divXf3|   191.97 |   275.76 |   **296.48** |   248.81 |
|  fmodX |    20.82 |     5.60 |     **1.21** |     0.60 |
The `fmod` implementations are 10-300x slower here because they use a shift-and-subtract algorithm, which could be changed to use fast division like `__divXf3`
__divxf3 is based directly on the f128 version, including error margins, so there's some room to optimize this later by fine-tuning the number of …
> compiler_rt: Implement `__divxf3` and `fmodx`

- src/Sema.zig
- test/behavior/int128.zig
Shout-out to @mitchellh who laid out the groundwork for these intCast runtime safety checks. This is just a bit of algebra to combine the two compares.
> Sema: combine signed->unsigned and shrinkage runtime checks in intCast

- lib/std/meta.zig
- src/print_targets.zig
This function was one of the biggest zig functions in a debug build of
the compiler.
```
$ bloaty stage3-debug/bin/zig -d symbols --tsv -n 10000000 |
rg -v '(llvm|clang|std|lld|\(anonymous namespace\))::|\[section ' |
sort -h -k 3
...
translate_c.ast.renderNode                    86168   86219
main.buildOutputType                         177959  178004
InfoTable                                    184832  184870
AArch64SVEIntrinsicMap                       188544  188596
print_targets.cmdTargets__anon_4735          319156  319216
__static_initialization_and_destruction_0()  486666  489582
MatchTable1                                  621884  621997
OperandMatchTable                           1139622 1139861
MatchTable0                                 1899764 1900141
$ bloaty …
```
> Remove usage of inline for from print_targets.cmdTargets

- lib/std/child_process.zig
- lib/std/testing.zig
* remove need for manual string concatenation for building binaries in test blocks
* include small program snippet to show how to get binary path with subslicing
> std.testing: add writeZigFile for TmpDir

- src/codegen/c.zig
- test/behavior/struct.zig
These shouldn't count towards the total emitted, or the stray comma
separators would cause compilation errors.
> CBE: fix renderValue() for struct fields with no runtime bits

- lib/std/build.zig
- lib/std/build/RunStep.zig
- lib/std/child_process.zig
- lib/std/testing.zig
- src/Compilation.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/Wasm.zig
- src/main.zig
- src/mingw.zig
- test/tests.zig
Instead, just return ChildProcess directly. This structure does not
require a stable address, so we can put it on the stack just fine. If
someone wants it on the heap they should do.
```zig
const proc = try allocator.create(ChildProcess);
proc.* = ChildProcess.init(args, allocator);
```
> std: Do not allocate the result for ChildProcess.init

- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- test/compile_errors/stage2/comptime_unreachable.zig
- test/incremental/x86_64-linux/comptime_var.3.zig
- test/incremental/x86_64-macos/comptime_var.3.zig
This reduces the amount of `.extended` instructions from 212702 down to 6711 (in `zig fmt --ast-check src lib/std`).
> Stage2: fix comptime unreachable, adjust Zir.Extended

- lib/std/multi_array_list.zig
I keep on writing these behaviors by hand, so I thought it'd be nice if MultiArrayList just exposed them as part of the API.
> std.MultiArrayList: add functions `addOne`, `pop`, and `popOrNull`

- src/Sema.zig
- test/behavior/basic.zig
This allows the following code to now compile properly:
```zig
export fn _start() void {
_ = doTheTest("bar");
}
fn doTheTest(comptime s: [*:0]const u8) [*:0]const u8 {
return "foo" ++ s;
}
```
> Sema: Fix many-pointer array concatenation at comptime 

- src/codegen/c.zig
- test/behavior/sizeof_and_typeof.zig
Just like for `Struct` in 8238d4b33585a715c58ab559cd001dd3ea1db55b, in the case of `ErrorUnion` struct we need to return a compound literal `(T){...}` instead of just `{}`, which is invalid code when used in e.g. a `return` expression.
> CBE: handle returning `undefined` for ErrorUnion

- lib/std/mem/Allocator.zig
Correct `PanicFree` function name.
> Allocator: correct `PanicFree` function name

- lib/std/os/windows.zig
- lib/std/pdb.zig
- lib/std/special/test_runner.zig
- lib/std/start.zig
- src/Air.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparcv9/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
- src/print_air.zig
- test/behavior/struct.zig
- test/incremental/aarch64-macos/hello_world_with_updates.0.zig
- test/incremental/x86_64-linux/hello_world_with_updates.0.zig
- test/incremental/x86_64-macos/hello_world_with_updates.0.zig
The goal of this branch is to get this command to pass:
```
stage2/bin/zig build test-behavior
```
Status:
> progress towards stage2 behavior tests for all targets passing with the LLVM backend

- lib/std/debug.zig
Adding `unreachable` prevents the futex code from being inspected during
a single-threaded build. Without futex, first draft BYOS packages don't
need to implement `nanosleep` to get a single-threaded "hello world"
program working.
Use of `assert()` did not achieve the desired effect of avoiding futex
in a single-threaded build.
> std: Single-threaded `panicImpl` sleep is unreachable

- cmake/Findllvm.cmake
Alpine linux installs llvm to this path and currently patches zig's
cmake file in order to build zig from source.
https://git.alpinelinux.org/aports/tree/testing/zig/llvm-include.patch?id=0c3f7850bef38fb4c63fc6af5c14724e5311b0cc
> cmake: add /usr/lib/llvm13 to searched paths

- lib/std/zig/system/NativeTargetInfo.zig
- src/arch/sparcv9/CodeGen.zig
- src/arch/sparcv9/Emit.zig
- src/arch/sparcv9/Mir.zig
- src/arch/sparcv9/abi.zig
- src/arch/sparcv9/bits.zig
- test/cases/sparcv9-linux/hello_world.zig
This implements basic function calls/returns on SPARCv9, such that the basic implementation of `_start` from the stdlib works.
> stage2: sparcv9: Implement basic function calls and returns

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- test/behavior/math.zig
~~Blocked by #11574~~
Implements `@mulWithOverflow` for variable-sized integers in the range `1...64` signed and unsigned.
> stage2,x64: implement @mulWithOverflow for all 1...64 bit-widths cases

- build.zig
- ci/azure/macos_script
- ci/zinc/linux_test.sh
- lib/std/build.zig
- lib/std/os/linux/arm-eabi.zig
- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
- src/link/MachO.zig
- test/behavior/cast.zig
- test/tests.zig
We can't yet run the behavior tests with stage3, but at least we can run
them with stage2, and we can use the proper test matrix.
This commit also adds use_llvm and ofmt to the zig build system.
> CI: add non-LLVM backends to the test matrix

- src/arch/wasm/CodeGen.zig
- src/type.zig
- test/behavior/math.zig
- test/cases/binary_operands.13.zig
- test/cases/binary_operands.2.zig
This improves the `@mulWithOverflow` implementation and ensures it passes all tests when bitsize <= 32.
To also support integers with bitsize 64, we will need compiler-rt support as Wasm does not have the same capabilities like the native backends with regards to carry bits, etc.
This PR ensures the Wasm backend will comply with #11316
> stage2: wasm - Improve `@mulWithOverflow` implementation

- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/register_manager.zig
- test/behavior/align.zig
- test/behavior/byval_arg_var.zig
The main aim of this PR is to unblock #11316 for the mainstream native backends: `x86_64`, `arm` and `aarch64`. Yep, you understood it right, this PR ensures #11316 when rebased on top of this PR will pass all of the tests for the aforementioned native backends with integer overflow safety on in Sema.
A major step in ensuring the native backends are able to pull this off was revamping the register locking (freezing) mechanics. Prior to this PR, locking registers (so that we don't accidentally reallocate and thus spill registers that are important to the instruction at hand) would follow the standard Zig's lock-defer mechanics, however, we would not track scopes, making this possible:
```zig
outer: {
const reg = try self.register_manager.allocReg(null); …
```
> stage2: introduce new register locking mechanism, and fix x64, arm and aarch64 native backends for compliance with integer overflow safety PR

- doc/langref.html.in
bit_count was removed in #6246
> docs: T.bit_count -> @typeInfo(T).Int.bits

- lib/std/build/RunStep.zig
- src/Compilation.zig
- src/libcxx.zig
- test/standalone/c_compiler/build.zig
- test/standalone/c_compiler/test.c
- test/standalone/c_compiler/test.cpp
The PR contains two major changes:
1. C++ is compiled without threading support for single-threaded targets (was already partially implemented for WASM, now it's applied to all single-threaded targets).
2. RunStep has been extended to run artifacts with the external executors if enabled.
The reason for (1) is that the current functionality is a little bit confusing as C++ standard library is compiled with the threading support even if an artifact is explicitly flagged to use the single-threaded mode. I've discovered that during dealing with #6573. The original LLVM commit referenced there is being abandoned, and the only way to use C++ for ARM in Zig is using modified standard library, hence this PR.
There are few reason for (2), but none of them are critical, therefore the change could …
> Normalized C++ compilation options for single-threaded targets

- src/arch/x86_64/CodeGen.zig
- test/behavior/math.zig
In general, cleans up and adds missing bits for various instructions including:
* `shl`, `shl_exact`, `shr_exact`, `shr`, `shl_with_overflow`
* `add_with_overflow` and `sub_with_overflow`
* `not`
The rest of the changes are behavior test additions as well as converging different common code paths between different binary instructions on x64.
> x64: major cleanup of codepaths generating binary ops

- lib/std/os.zig
- lib/std/os/windows/ntdll.zig
Windows does Unicode-aware case-insensitive comparisons for environment variable names. Before, os.getenvW was only doing ASCII case-insensitivity. We can take advantage of [RtlEqualUnicodeString in NtDll](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlequalunicodestring) to get the proper Unicode case insensitivity (note that this is what [ReactOS uses for its environment variable case insensitivity](https://github.com/reactos/reactos/blob/3fa57b8ff7fcee47b8e2ed869aecaf4515603f3f/sdk/lib/rtl/env.c#L560)).
This should be a more complete fix for part of https://github.com/ziglang/zig/issues/4603, and an improvement on https://github.com/ziglang/zig/pull/4608.
Example with the following test code and the env var `СЛАВЬСЯ` (set as all uppercase, but the test code …
> os.getenvW: Fix case-insensitivity for Unicode env var names

- lib/std/http.zig
- lib/std/http/method.zig
- lib/std/http/status.zig
- lib/std/std.zig
starts again the `std.http` namespace and add definitions for the `Method` and `Status` primitives for use in further work and 3rd party libraries
additionally will be used by 910, 2007, 943
> std: add http definitions for Method and Status

- lib/std/rand.zig
- lib/std/rand/RomuTrio.zig
this is an implementation of [Romu-rng](https://www.romu-random.org/romupaper.pdf).
I tested this RNG in some research code of mine and it improves performance substantially without compromising results (while I noticed some biases with the smallest Xoroshiro).
There is some controversy regarding this RNG family (mostly theoretical arguments) but empirically this RNG is proven to be exceptionally good.
Francesco
------- added buffered benchmark --
```zig
on Mac M1 Air 2020
-------- TESTING BUF [64]u8
rng:        Romu192    time minimum 6.9940 ms;  time maximum 7.3120 ms;
rng:     Xoshiro256    time minimum 8.3250 ms;  time maximum 8.5200 ms;
rng:          Sfc64    time minimum 13.3090 ms;  time maximum 13.7180 ms;
rng:   Xoroshiro128    time minimum 12.6660 ms;  time maximum 12.7310 ms; …
```
> std: adding RomuTrio RNG to Zig

- lib/std/math.zig
- returns -1, 0 or 1
- supports vector types
- branchless
> std.math.sign: get the sign of a int, float or vector

- lib/std/os/linux.zig
the list parameter should be a multi-item pointer rather than a single-item
pointer. see: https://linux.die.net/man/2/setgroups
> setgroups() sets the supplementary group IDs for the calling process...
> the size argument specifies the number of supplementary group IDs in the buffer pointed to by list.
> std.os.linux: fix signature of setgroups

- src/main.zig
When I try to run `zig fmt . --exclude build` I get errors when the `build/` directory is missing which is annoying and it seems like it shouldn't complain about something its intending to ignore in the first place. (easier to open a PR than file an issue, though feel free to close!)
> zig fmt: make --exclude ignore missing dirs

- lib/std/rand.zig
- lib/std/rand/test.zig
Fixes some minor issues that were recently merged in #10428 (`Improve stdlib's random float generation`).
- Test: Fix bucket counting. Previously, the first hit was not counted.
This off-by-one error slightly increased the mean of `*_total_variance`, which decreased the acceptance rate for a particular random seed from 95% to 92.6%. (Irrelevant for test failure because the seed is fixed.)
- Improve comments
cc @mrakh, @daurnimator, @andrewrk
> Minor fixes for random float generation

- lib/init-exe/src/main.zig
As suggested in https://github.com/ziglang/zig/issues/9945#issuecomment-950114977 by @wizzard0.
Fixes #9945.
> init-exe: add note about log_level in ReleaseSmall and ReleaseFast build mode

- lib/std/os.zig
- lib/std/os/test.zig
Currently `std.os` doesn't expose the functions `timerfd_create`, `timerfd_settime` and `timerfd_gettime`, which are only available via their primitives methods in `std.os.linux`. I added their equivalent functions in `std.os` with a proper calling signature and error handling.  I also added a test to `os.test.zig` to check the correct behavior of those functions.
> std.os: add timerfd_create, timerfd_settime and timerfd_gettime

- lib/std/crypto/siphash.zig
This is a workaround for some stage1 bug in `@call` that happens only in certain cases in comptime evaluation. [LoLa](https://github.com/MasterQ32/LoLa) is broken on `0.10.0-dev.2054+3ed9ef3e6` due to this evaluation bug.
This is likely a regression in stage1, so this is only a workaround. The same "fix" is already applied somewhat lower in siphash.
> Fixes comptime 'error: cannot assign to constant' error in siphash.

- src/arch/sparc64/CodeGen.zig
- src/arch/sparc64/Emit.zig
- src/arch/sparc64/Mir.zig
- src/arch/sparc64/bits.zig
This implements basic test harness support for sparc64. 
So far, it manages to run an empty testcase:
```
$ cat s9test.zig
test {}
$ stage2/bin/zig test s9test.zig --test-cmd qemu-sparc64 --test-cmd-bin -target sparc64-linux
$
```
> stage2: sparc64: Make basic test harness run

- lib/compiler_rt.zig
- lib/std/builtin.zig
- lib/test_runner.zig
- src/Air.zig
- src/AstGen.zig
- src/Compilation.zig
- src/Liveness.zig
- src/Module.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/type.zig
~~Currently disabled on all targets because LLVM is being a dick and I'm too tired to fight it.~~
```sh-session
$ zig2 test test/behavior.zig -I test -fLLVM    -target aarch64-linux
LLVM Emit Object... 
inlinable function call in a function with debug info must have a !dbg location
call fastcc void @builtin.returnError(%builtin.StackTrace* %0) #13
inlinable function call in a function with debug info must have a !dbg location
call fastcc void @builtin.returnError(%builtin.StackTrace* %0) #13
inlinable function call in a function with debug info must have a !dbg location
call fastcc void @builtin.returnError(%builtin.StackTrace* %0) #13
inlinable function call in a function with debug info must have a !dbg location
call fastcc void @builtin.returnError(%builtin.StackTrace* %0) #13
```
Not …
> stage2: error return traces

- lib/test_runner.zig
This fixes the issue #11640 that I created yesterday. With this, running `zig test` on Windows console finally shows like this:
```
> zig test src/main.zig
All 138 tests passed.
```
> zig test: Add proper detection for Windows console

- src/arch/wasm/CodeGen.zig
- test/behavior/align.zig
- test/behavior/bugs/421.zig
- test/behavior/error.zig
- test/behavior/int128.zig
- test/behavior/math.zig
- test/behavior/popcount.zig
- test/behavior/struct.zig
- test/behavior/widening.zig
This implements 128-bit integers for all instructions, with the exception of those that require compiler-rt (such as multiplying, dividing, shifting). This PR also ensures it matches the C-ABI correctly with regards to lowering the arguments and returning a 128-bit integer. The next step is to implement compiler-rt support in the Wasm backend & linker.
> stage2: wasm - Implement 128-bit integers

- src/Sema.zig
- test/behavior/error.zig
I had an evening free, so I figured I'd get another one of these easy safety check PRs out. I also prettied up the existing comptime cast failure error message with a "declared here" note as well as added a new error for incompatible error set types with more fancy "declared here" notes. I tried to avoid resolving inferred error sets if possible in the logic, but it might make sense to just simplify all that if that isn't a concern.
> stage2: `@errSetCast` safety

- lib/std/math.zig
Provides inline aliases to functions originally in `std.math`. This is to keep backwards compatibility (makes #11532 not breaking anymore) and keep math code unified (eg no need to mix builtins with std.math).
> Add aliases to math builtins back into std.math

- src/Compilation.zig
- src/link.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/Wasm.zig
- src/main.zig
Warnings about non-implemented `-z nocopyreloc` are common when
compiling go code (including Go's tests themselves). Let's just
make it stop complaining.
> [Elf] add -z nocopyreloc

- lib/compiler_rt/fma.zig
- lib/std/math/atanh.zig
- lib/std/math/complex/cosh.zig
- lib/std/math/complex/proj.zig
- lib/std/math/complex/sinh.zig
- lib/std/math/complex/sqrt.zig
- lib/std/math/complex/tanh.zig
- lib/std/math/copysign.zig
- lib/std/math/isfinite.zig
- lib/std/math/isinf.zig
- lib/std/math/isnormal.zig
- lib/std/math/ldexp.zig
- lib/std/math/pow.zig
- lib/std/math/signbit.zig
Simplified the implementations of `signbit` and `copysign`, based on `fabs`, also removed the explicit type argument. Works on f80 now!
> std.math: simplify signbit and copysign

- lib/std/meta.zig
- lib/std/meta/trailer_flags.zig
- Include `TrailerFlags` in std tests.
Also fix a bug that was undetected because of the skipped tests.
- Previously, init() took a struct parameter, which gave the misleading impression that `TrailerFlags` was initialized with the struct's values. In fact, those values were unused.
Before:
```zig
var flags = Flags.init(.{
.a = 1234,
.b = "actually unused str",
});
```
After: (Edit: Now using @InKryption's suggestion)
```zig
var flags = Flags.init(.{
.a = true,
.b = true,
});
```
cc @Vexu, @andrewrk, @tadeokondrak
> Fix `std.meta.TrailerFlags`

- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
The previous implementation of calling conventions was hacky and broken.
This commit reworks lowerFnParamTy into iterateParamTypes which returns
enum tags indicating how to handle each parameter. This is then used in
the three places that matter:
* lowering a function type to llvm type
* converting function parameters to the canonical type representation
(with respect to isByRef).
* converting canonical type representation to function arguments at
callsites (again with respect to isByRef).
As a result, we are one step closer to the C ABI tests passing. Before
this commit, attempting to build them crashed the compiler. I isolated
the broken function and verified that it now is lowered correctly. I
will keep working on this one piece at a time until all the C ABI tests
pass, and then I will …
> LLVM: rework calling convention lowering

- src/stage1/ir.cpp
The following code produces a segfault in current master:
```
fn init() !u32 {
return 0;
}
const Foo = struct {
data: u32 = init(),
};
const state: Foo = .{};
_ = state;
}
```
This is caused by default assigning `data` with an error union value when it doesn't expect one - it segfaults when it tries to add a compiler note. I think because it's trying to evaluate the `init()` body as a constant expression but the compiler note expects it to be inside a function (?)
This change just avoids adding the compiler note in this case. The error still reads fine:
```
./zig-bounded-array-repro.zig:6:21: error: cannot convert error union to payload type. consider using `try`, `catch`, or `if`. expected type 'u32', found '@typeInfo(@typeInfo(@TypeOf(init)).Fn.return_type.?).ErrorUn …
```
> Fix segfault in error note

- lib/std/fmt.zig
just adding documentation where I needed to read the code. It was not clear from the types that bufPrint would return a slice of the bytes printed to.
> document bufPrint, and format now uses `writer` not `output`

- lib/docs/main.js
- src/Autodoc.zig
Currently handling the following code with some exceptions. 
Implementation are not fully finished there are some known issues and in some cases node still rendered as `@as` node.
```zig
const array_type: [4]u8 = undefined;
const ptr_type_simple: []u8 = undefined;
const ptr_type: [:0]u8 = undefined;
const array_init_anon = .{ 1, 2, 3 };
const array_type_and_array_init2 = [_]u8{ 1, 2, 3 };
const array_type_sentinel_and_array_init_sent = [_:0]u8{ 1, 2, 3 };
const ptr_type_simple_and_array_init_anon: [*]u8 = .{ 1, 2, 3 };
const ptr_type_and_array_init_anon: [*:0]u8 = .{ 1, 2, 3 };
const ptr_type_simple_and_array_type_and_array_init_anon: *[3]u8 = .{ 1, 2, 3 };
const ptr_type_simple_anon_init: []const u8 = .{ 1, 2, 3 };
const array_2d_anon = .{ .{ 1, 2, 3 }, .{ 2, 1, 3 }, .{ 2, 3, 1 } }; …
```
> Autodoc: handling sentinel

- src/Module.zig
- src/Sema.zig
- src/TypedValue.zig
- src/codegen.zig
- src/codegen/llvm.zig
- src/value.zig
- test/behavior/eval.zig
- test/cases/llvm/pointer_with_different_address_spaces.zig
This is a temporary addition to stage2 in order to match stage1 behavior,
however the end-game once the lang spec is settled will be to use a global
InternPool for comptime memoized objects, making this behavior consistent
across all types, not only string literals. Or, we might decide to not
guarantee string literals to have equal comptime pointers, in which case
this commit can be reverted.
> stage2: string literal interning

- lib/std/rand.zig
- lib/std/rand/RomuTrio.zig
Following on from #10755.
Going to see if tests pass, I think the test case was broken rather than the actual RNG implementations.
> std.rand: Add RomuTrio

- lib/std/debug.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/link/Dwarf.zig
- src/type.zig
- test/behavior/error.zig
- test/behavior/eval.zig
- test/cases/compile_errors/call method on bound fn referring to var instance.zig
* Sema: avoid unnecessary safety checks when an error set is empty.
* Sema: make zirErrorToInt handle comptime errors that are represented
as integers.
* Sema: make empty error sets properly integrate with
typeHasOnePossibleValue.
* Type: correct the ABI alignment and size of error unions which have
both zero-bit error set and zero-bit payload. The previous code did
not account for the fact that we still need to store a bit for
whether there is an error.
* LLVM: lower error unions possibly with the payload first or with the
error code first, depending on alignment. Previously it always put
the error code first and used a padding array.
* LLVM: lower functions which have an empty error set as the return
type the same as anyerror, so that they can be used where
fn()anyerror function …
> stage2: fixes for error union semantics

- lib/std/crypto/aes/soft.zig
“Byte-sized” continuation of #11612, making the `mul` function more intuitive and readable. 
_(Based on [FIPS-197 4.2.1](https://csrc.nist.gov/csrc/media/publications/fips/197/final/documents/fips-197.pdf))_
> std.crypto: simplify AES multiplication algorithm

- src/Sema.zig
- src/value.zig
- test/behavior/sizeof_and_typeof.zig
- test/behavior/struct.zig
- test/cases/compile_errors/dereference_anyopaque.zig
~~I'm not 100% sure about the second commit but it does make sense based on my understanding of the current intended semantics of packed structs.~~ And for the generic poison check, the second best alternative I could come up with was to add the check to `resolveInst` which would have been a much more intrusive change.
Closes #11709
Closes #11680
Closes #11550
Closes #11504
> Stage2 misc fixes

- src/arch/sparc64/CodeGen.zig
- src/arch/sparc64/Emit.zig
- src/arch/sparc64/Mir.zig
- src/arch/sparc64/abi.zig
- Add `cmp` and `mov` synthetic instructions for convenience
- Account for stack bias and reserved area when generating pointers to stack offsets
> stage2: sparc64: Small refactorings and stack pointer accounting fixes

- lib/std/crypto/25519/scalar.zig
Add the ability to generate a random, canonical curve25519 scalar, like we do for p256.
Also leverage the existing CompressedScalar type to represent these scalars.
> crypto/25519: add scalar.random(), use CompressedScalar type

- lib/std/os/linux.zig
all_mask is a value of type `sigset_t`, which is defined as an array type
`[N]u32`.  However, `all_mask` references `sigset_t.len`, but, the array type
does not have a `len` field.  Fix is to use `@typeInfo(sigset_t).Array.len`
instead.
> fix semantic error with std.os.linux.all_mask

- lib/std/c.zig
- lib/std/c/darwin.zig
- lib/std/c/linux.zig
This PR introduces functions from `dirent.h`, which exists on Unix-like systems including macOS and FreeBSD.
Along with the new functions, I simplified `std.c` by removing redundant code from `std/c/darwin.zig`.
> Add functions from `dirent.h` to std.c

- src/AstGen.zig
- src/Sema.zig
- test/behavior.zig
- test/behavior/basic.zig
- test/behavior/bugs/11179.zig
- test/cases/compile_errors/invalid_array_elem_ty.zig
- test/cases/compile_errors/runtime_indexing_comptime_array.zig
Closes #11135
Closes #11543
Closes #11632
Closes #11179
> more misc stage2 fixes

- src/clang.zig
- src/translate_c.zig
- src/zig_clang.cpp
- src/zig_clang.h
- test/translate_c.zig
This patch attempts to reserve the correct amount of space in a record containing a bitfield but does not implement bitfields. So this :
```c
struct my_struct {
unsigned a: 1;
unsigned b: 28;
};
```
becomes
```zig
pub const struct_my_struct = extern struct {
bitfield0: c_uint,
};
```
The motivation was working w/ DPDK, which has tons of bitfields in the hierarchy, and I didn't want to fix them up all by hand. This works.
There are likely more reasons not to accept this patch than to accept it. They include:
This only works if the C was intended to be compiled w/ clang.
Any generated zig code that reference the individual bitfields is now invalid.
likely x86 specific.
it's a hack.
If there is any interest in this PR, things that would need to be done:
make it opt in. Not sure how to get …
> translate-c: reserve space for bitfield.

- lib/docs/main.js
- src/Autodoc.zig
Working only when the slice is initialized with `_` or a known number representing the size.
I didn't found a way to get the sentinel in other cases, the `ptr_type` has a flag saying it has a sentinel but there's no reference for that sentinel in it's own structure like in some `array` initializers which I was able to grab from the last element of the array.
Following the zir generated there's a way to grab the sentinel before `ptr_type` but the `tags` like `str` or `int` were never called, I wasn't able to figure out how to get it from somewhere else or how to made they being called.
There are some minor changes in js to handle comptimeExprs.
The `anyopaque` (old [comptimeExpr]) has an [1] showing in from of itself.
```
Things I said above are not true anymore.
```
`Sentinel examples` …
> Autodoc: Anytype and Struct sentinels

- src/AstGen.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- test/behavior/basic.zig
- test/behavior/tuple.zig
> Stage2: improve AstGen for array init expressions

- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- src/type.zig
- test/behavior/align.zig
The main purpose of this commit is to prepare to implement support for
callconv(), align(), linksection(), and addrspace() annotations on
generic functions where the provided expression depends on comptime
parameters (making the function generic).
It's a rather involved change, so this commit only makes the necessary
changes to AstGen without regressing any behavior, and a follow-up
commit can finish the task by making the enhancements to Sema.
By my quick estimation, the new encoding for functions is a negligible
improvement - along the lines of 0.005% fewer total ZIR bytes on
average. Still, it's nice that this commit, while adding more
data into ZIR, actually ends up reducing the storage size thanks to a
slightly more sophisticated encoding.
Zir.Inst.ExtendedFunc is renamed to …
> stage2: add missing data to ZIR encoding of functions

- src/Liveness.zig
- src/codegen/llvm.zig
Generally, the load instruction may need to make a copy of an
isByRef=true value, such as in the case of the following code:
```zig
pub fn swap(comptime T: type, a: *T, b: *T) void {
const tmp = a.*;
a.* = b.*;
b.* = tmp;
}
```
However, it only needs to do so if there are any instructions which can
possibly write to memory. When calling functions with isByRef=true
parameters, the AIR code that is generated looks like loads followed
directly by call.
This allows for a peephole optimization when lowering loads: if the load
instruction operates on an isByRef=true type and dies before any side effects
occur, then we can safely lower the load as a no-op that returns its
operand.
This is one out of three changes I intend to make to address #11498.
However I will put these changes in separate …
> LLVM: elide some loads when lowering

- src/codegen/llvm.zig
This moves some logic from resolveLlvmFunction to updateFunc and takes
advantage of the iteration we already do that takes into account C ABI
lowering, making LLVM parameter attributes accurate for C ABI functions
as well as our own unspecified calling convention.
Related to #11498.
> LLVM: add readonly, nonnull, align attributes to pointer params

- lib/std/math/big/int.zig
- src/Sema.zig
- test/behavior/basic.zig
- test/behavior/bugs/1741.zig
~~This PR makes it so that const variables produce a `decl_ref_const_init` value which behaves similarly to `decl_ref_mut` but also allows runtime stores if needed by converting the comptime pointer into a set of runtime instructions. The alloc and the instructions are placed in a `resolve_const_alloc` block replacing the hacky `make_ptr_const` which detects if any runtime instructions were emitted for the initializer and then either converts the original alloc into a runtime instruction or a comptime value.~~
~~The mechanism is quite complex but it's the simplest I could think of capable of solving more complex situations with nested structs/arrays producing chained `field_ptr`/`ptr_elem_ptr` instructions:~~
```zig
pub export fn entry() void {
const T = struct { c: u8 };
const S = struct …
```
> Stage2: detect when initializer of const variable is comptime known

- src/link/tapi/Tokenizer.zig
- src/link/tapi/parse.zig
- src/link/tapi/parse/test.zig
- src/link/tapi/yaml.zig
gitrev kubkon/zig-yaml 8cf8dc3bb901fac8189f441392fc0989ad14cf71
Calculate line and col info indexed by token index. We can then
re-use this info to track current column number (aka indentation
level) of each "key:value" pair (map) or "- element" (list).
This significantly cleans up the code, and leads naturally to
handling of unindented lists in tbd files.
Fixes #11718
> tapi: sync with upstream

- lib/docs/main.js
- src/Autodoc.zig
Some unary and binary builtin functions are now implemented, there are much more to implement.
The structure to implement them it's better and cleaner, than binOp, delivering all the work to js.
Tag `merge_error_sets` are now implemented and apparently it's working and it's generating all the information
needed to show it in frontend.
The tags `array_cat` and `array_mul` are working in examples cases but it's get broken running in std.
So it's commented in the pr.
The next candidates tags I'm thinking in working on are:
`slice_start`
`slice_end`
`slice_sentinel`
`switch_block` I already started this one but it's get complicated 
`func_fancy`
And refactoring the `binOp` to match the struct of `builtinBin`.
All this implementations are not fully tested. Said that maybe there are some …
> Autodoc: some builtin functions and implemented merge_error_set and array_cat/mul tags

- test/standalone.zig
- tools/process_headers.zig
- tools/update-linux-headers.zig
I tried to update merge_anal_dumps.zig, but it looks abandoned since 2019, so IMHO it's too much work (a lot has changed since then) for too little gain. If you want, I can remove this file and/or include this commits to #11740.
Signed-off-by: BratishkaErik <bratishkaerik@getgoogleoff.me>
> tools: fix update-linux-headers.zig and process_headers.zig

- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/link/Dwarf.zig
- src/link/Elf.zig
Splits type relocs into two kinds: local and global:
* Global relocs use a global type resolver and calculate offset to the existing definition of a type abbreviation.
* Local relocs use offset in the abbrev section of the containing atom plus addend to generate a local relocation.
Refactor and enhance logging symtab in ELF linker.
> dwarf: fix incorrect type relocations for union payloads

- src/Air.zig
- src/AstGen.zig
- src/Liveness.zig
- src/Sema.zig
- src/Zir.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
- src/print_zir.zig
Implements #11772.
Note: master branch at time of writing is e498fb155051f548071da1a13098b8793f527275.
It did *not* close the bloat gap (#11498). File size stats after this change:
```
self-hosted binary size, LLVM backend, -Drelease, -Dstrip, LLVM disabled:
master:
stage3: 8370744 bytes
stage2: 6963432 bytes
this branch:
stage3: 8343144 bytes
stage2: 6939800 bytes
```
So it seems that this branch produces a slightly smaller executable (a delta of 25 KB) in both cases, but did not change the relative size difference.
However it did have a small improvement on how long it took to build in release mode with LLVM:
```
building self-hosted, LLVM backend, -Drelease, -Dstrip, LLVM disabled:
master: 
stage1 build stage2: 3m28.3s
stage2 build stage3: 3m16.4s
stage3 build stage3: 3m14.4s
this …
```
> introduce a "try" ZIR and AIR instruction

- src/Sema.zig
- src/link/Elf.zig
- src/link/MachO.zig
- test/behavior/bugs/1741.zig
Now the linkers call `decl.getAlignment(target)` instead of `decl.ty.abiAlignment(target)` to get the explicit alignment if specified (for example via `var x align(2) = ...`).
After changing the callsites I noticed that one code path in Sema wasn't setting the `Decl`'s explicit alignment to `0` (for those out of the loop, alignment of `0` means unspecified, use ABI alignment instead), and instead left it as `undefined` which would then incorrectly be picked up as specified explicit alignment of `0xaaaaaaaa` which is obviously incorrect. The code path in Sema I mention is in `instantiateGenericCall`, but I'm wondering if my patch to Sema is indeed fixing the issue or rather just the symptom, so would appreciate your input here @andrewrk.
> elf+macho: use explicit alignment on Decl if specified

- src/codegen/llvm.zig
- test/behavior/bugs/529.zig
Zig allows multiple extern functions with the same name, and the
backends have to handle this possibility.
For LLVM, we keep a sparse map of collisions, and then resolve them in
flushModule(). This introduces some technical debt that will have to be
resolved when adding incremental compilation support to the LLVM
backend.
> LLVM: handle extern function name collisions

- lib/std/c/netbsd.zig
- lib/std/c/openbsd.zig
- lib/std/c/solaris.zig
- lib/std/os/linux/arm-eabi.zig
- lib/std/os/linux/arm64.zig
- lib/std/os/linux/i386.zig
- lib/std/os/linux/io_uring.zig
- lib/std/os/linux/mips.zig
- lib/std/os/linux/powerpc.zig
- lib/std/os/linux/powerpc64.zig
- lib/std/os/linux/riscv64.zig
- lib/std/os/linux/sparc64.zig
- lib/std/os/linux/x86_64.zig
- lib/std/os/windows/ws2_32.zig
alongside the typical `msghdr` struct, Zig has added a `msghdr_const`
type that can be used with `sendmsg` which allows const data to
be provided.  I believe that data pointed to by the `iov` and `control`
fields in `msghdr` are also left unmodified, in which case they can
be marked `const`.
> add const to msghdr_const iov and control pointers

- src/Sema.zig
- src/codegen/llvm.zig
- src/type.zig
- test/behavior/packed-struct.zig
* Sema: handle overaligned packed struct field pointers
* LLVM: handle byte-aligned packed struct field pointers
We do not attempt this with big-endian targets yet because of nested
structs and floats. I need to double-check the desired behavior for big endian
targets before adding the necessary complications to this code. This will not
cause miscompilations; it only means the field pointer uses bit masking when it
might not be strictly necessary.
I intended to include the fix to behavior test 1120 in here as well but I ran out of time for today and I wanted to give these two commits a CI run while I sleep.
> stage2: better codegen for byte-aligned packed struct fields

- src/Compilation.zig
- src/link.zig
- src/link/Elf.zig
- src/main.zig
Note that the current documentation for the `-z noexecstack` is
incorrect. This indicates that an object *does not* require an
executable stack.
This is actually the default of LLD, and there has never been a way to
override this default by passing `-z execstack` to LLD.
This commit removes the redundant `-z noexecstack` option from
zig build-exe/build-lib/build-obj and ignores the option if passed
to zig cc for compatibility.
As far as I can tell, there is no reason for code to require an
executable stack. This option only exists because the stack was
originally executable by default and some programs came to depend
on that behavior. Instead, mprotect(2) may be used to make memory
pages executable.
> linker: remove `-z noexecstack` option

- build.zig
- ci/azure/build.zig
- lib/std/debug.zig
- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/arch/wasm/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/config.zig.in
- src/print_zir.zig
- src/test.zig
- test/behavior/bugs/920.zig
- test/cases/recursive_inline_function.1.zig
- test/stage2/cbe.zig
The actual fix here is:
```diff
-        try sema.emitBackwardBranch(&child_block, call_src);
+        try sema.emitBackwardBranch(block, call_src);
```
Here is some output from using std.debug.Trace on the LazySrcLoc that helped me track down where the problem was:
```
[nix-shell:~/dev/zig/build-release]$ stage2/bin/zig test test3.zig 
init:
/home/andy/dev/zig/src/Zir.zig:2441:45: 0x31b8ba5 in Zir.struct:2432:18.src (zig)
return LazySrcLoc.nodeOffset(self.src_node);
^
/home/andy/dev/zig/src/Sema.zig:5030:35: 0x339fde6 in Sema.zirCall (zig)
const call_src = inst_data.src();
^
/home/andy/dev/zig/src/Sema.zig:712:62: 0x322dbe7 in Sema.analyzeBodyInner (zig)
.call                         => try sema.zirCall(block, inst),
^
thread 18654 panic: index out of bounds …
```
> introduce std.debug.Trace and use it to debug a LazySrcLoc in stage2 that is set to a bogus value

- src/link.zig
Would cause panic when invoking `build-lib` with stage2 in the same dir where Zig source is located:
```
zig build-lib -static main.zig
```
> stage2: correctly work out dirname for ar

- src/ThreadPool.zig
This comptime gate is needed to make sure that purely single-threaded programs don't generate calls to the std.Thread API.
WASI targets successfully build again with this change 🚀
> ThreadPool: Make `join()` a no-op in single-threaded mode

- lib/std/debug.zig
- lib/std/mem.zig
- src/Sema.zig
- test/behavior/eval.zig
- test/behavior/translate_c_macros.zig
This comment is now deleted because the task is completed in this
commit:
```
// TODO: Update this to behave like `beginComptimePtrLoad` and properly check/use
// `container_ty` and `array_ty`, instead of trusting that the parent decl type
// matches the type used to derive the elem_ptr/field_ptr/etc.
//
// This is needed because the types will not match if the pointer we're mutating
// through is reinterpreting comptime memory.
```
The main strategy is to change the ComptimePtrMutationKit struct so that
instead of `val: *Value` it now returns a tagged union which can be one
of three possibilities:
* The pointer type matches the actual comptime Value so a direct
modification is possible. Before this commit, the implementation
incorrectly assumed this was always the case.
* In the case of …
> Sema: rework beginComptimePtrMutation

- lib/std/crypto/pcurves/common.zig
The saturated representation of the field size and the the precomputed value for the field inversion are constants.
So, compute them at comptime.
And the `zero` and `one` constants are already defined, so just reuse them by the way.
> crypto/pcurves: compute constants for inversion at comptime

- lib/std/math/big/int.zig
This patch lets `std.math.big.int.Managed.toString()` use the allocator provided to the method as the comment states, instead of the `Managed` allocator.
> std.math.big.int: update Managed.toString() to use provided allocator

- build.zig
- src/test.zig
Instead of always using std.testing.allocator, the test harness now follows
the same logic as self-hosted for choosing an allocator - that is - it
uses C allocator when linking libc, std.testing.allocator otherwise, and
respects `-Dforce-gpa` to override the decision. I did this because
I found GeneralPurposeAllocator to be prohibitively slow when doing
multi-threading, even in the context of a debug build.
There is now a second thread pool which is used to spawn each
test case. The stage2 tests are passed the first thread pool. If it were
only multi-threading the stage1 tests then we could use the same thread
pool for everything. However, the problem with this strategy with stage2
is that stage2 wants to spawn tasks and then call wait() on the main
thread. If we use the same thread pool …
> multi-thread `zig build test-cases`

- lib/std/crypto.zig
- lib/std/crypto/ecdsa.zig
ECDSA is the most commonly used signature scheme today, mainly for historical and compliance reasons. It is a necessary evil for many standard protocols such as TLS and JWT.
It is tricky to implement securely and has been the root cause of multiple security disasters, from the Playstation 3 hack to multiple critical issues in OpenSSL and Java.
This implementation combines lessons learned from the past with recent recommendations.
In Zig, the NIST curves that ECDSA is almost always instantiated with use formally verified field arithmetic, giving us peace of mind even on edge cases. And the API rejects neutral elements where it matters, and unconditionally checks for non-canonical encoding for scalars and group elements. This automatically eliminates common vulnerabilities such as …
> std/crypto: add support for ECDSA signatures

- src/main.zig
This passes -Wl,-no-pie linker arg. Golang uses that. From the `ld(1)`
man page:
Create a position dependent executable.  This is the default.
Not adding to the help text, because this is the default.
> [elf] understand -no-pie

- src/value.zig
- test/behavior/bitcast.zig
Stage 2 will panic when attempting to `@bitCast` a packed struct that has a float field in comptime. The problem was that when iterating over the struct's fields in `packedStructToInt`, `val.toFloat` was used instead of `field_val.toFloat`.
There is also a test case included in this PR.
> stage2: comptime @bitCast packed struct bug fix 

- src/Sema.zig
- test/behavior/vector.zig
added test case was failing with:
```
zig/test/behavior/vector.zig:181:25: error: expected @Vector(3, i32), found tuple{comptime comptime_int = 0, comptime comptime_int = 1, comptime comptime_int = 0}
for ([_]Vec3{ .{ 0, 1, 0 }, .{ 0, 0, 1 } }) |it| {
```
> stage2: coerce tuple to vector

- src/arch/wasm/CodeGen.zig
- test/behavior/saturating_arithmetic.zig
Implements `+|`, `-|` and `<<|` for both signed and unsigned integers <= 64 bits.
128 bit support will be for a future effort, as well as multiplication. Perhaps together with llvm backend as that currently does not support saturating multiplication for wasm (https://github.com/ziglang/zig/issues/9660).
> stage2: wasm - saturating arithmetic

- src/Compilation.zig
- src/link.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/Wasm.zig
- src/main.zig
Pass `-pagezero_size` to the MachO linker. This is the final
"unsupported linker arg" that I could chase that CGo uses. After this
and #11874 we may be able to fail on an "unsupported linker arg" instead
of emiting a warning.
Test case:
zig=/code/zig/build/zig
CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC="$zig cc -target x86_64-macos" CXX="$zig c++ -target x86_64-macos" go build -a -ldflags "-s -w" cgo.go
I compiled a trivial CGo program and executed it on an amd64 Darwin
host.
To be honest, I am not entirely sure what this is doing. This feels
right after reading what this argument does in LLVM sources, but I am by
no means qualified to make MachO pull requests. Will take feedback.
> [MachO] add -pagezero_size

- lib/std/os.zig
The NameTooLong check isn't taking the sentinel 0 into account which
would result in a buffer overflow on the stack.
> std.os.execvpe: fix buffer overlow

- lib/std/debug.zig
The for-loop in dump() would index out of bounds if `t.index` is greater
than size, because `end` is the maximum of `t.index` and `size` rather than the
minimum.
> fix ConfigurableTrace.dump OOB

- src/link/Wasm.zig
- src/link/Wasm/types.zig
Previously, all decls would be placed within the 'rodata' segment regardless of constness. With this change, we correctly put them into segments such as 'data' and 'bss'. The linker now also orders the segments in such a way to always place the bss segment last, which allows us to completely omit this segment in the case where the memory is exported and not imported from the runtime. This allows smaller binaries as the runtime itself will zero-initialize the memory for us.
> stage2: wasm-linker - Place decls in the correct segment and order segments

- src/Compilation.zig
> Pass -O0 rather than -Og to Clang for Debug builds

- src/stage1/zig0.cpp
As discussed in #11918, I just follow the short term solution, adding hard-coded cpu features for rv64.
I have tested locally in rv64 platform, now zig0 successfully produces a working compiler.
> zig0: handle baseline cpu features for rv64

- lib/std/debug.zig
- lib/std/heap/general_purpose_allocator.zig
- lib/std/testing.zig
- lib/std/testing/failing_allocator.zig
There are two parts to this:
---
Adds stack trace capturing to `std.testing.FailingAllocator` and makes `std.testing.checkAllAllocationFailures` print the stack trace of the induced allocation failure when memory leaks are detected (very helpful for debugging)
---
`checkAllAllocationFailures`: add possibility of SwallowedOutOfMemoryError (split from NondeterministicMemoryUsage)
Inducing failure but not getting OutOfMemory back is not as much of a problem as never inducing failure when it was expected to be induced, so treating them differently and allowing them to be handled differently by the caller is useful.
For example, the current implementation of `std.HashMapUnmanaged.getOrPutContextAdapted` always tries to grow and then recovers from OutOfMemory by attempting a lookup of an …
> Add stack trace capturing to `FailingAllocator` and use it to improve `checkAllAllocationFailures`

- lib/std/os/linux.zig
- lib/std/zig/parser_test.zig
- lib/std/zig/render.zig
This should fix #11802 
I'd be happy to hear any suggestions/improvements as I'm not really sure if this is the best way to go about it.
> zig fmt: fix idempotency with newlines surrounding doc comment

- lib/std/crypto/pcurves/p256.zig
- lib/std/crypto/pcurves/p384.zig
- lib/std/crypto/pcurves/tests/p256.zig
- lib/std/crypto/pcurves/tests/p384.zig
Unlike curve25519 where the scalar size is not large enough to fill the top nibble, this can definitely be the case for p256 and p384.
> std.crypto.{p256,p384}: process the top nibble in mulDoubleBasePublic

- lib/std/crypto/25519/scalar.zig
- lib/std/crypto/pcurves/p256/scalar.zig
- lib/std/crypto/pcurves/p384/scalar.zig
For 25519, it's very likely that applications would ever need the serialized representation. Expose the value as an integer as in other curves. Rename the internal representation from `field_size` to `field_order` for consistency.
Also fix a common typo in `scalar.sub()`.
> std/crypto/{25519,pcurves}: make the scalar field order public

- lib/std/mem.zig
Over the last couple of weeks weeks I needed to iterate over a
collection backwards at least twice. Do we want to have this in stdlib?
If yes, click "Merge" and start using today! Free shipping and returns
(before 1.0).
Why is this useful?
-------------------
I need this for building an error wrapper: errors are added in the
wrapper from "lowest" level to "highest" level, and then printed in
reverse order. Imagine `UpdateUsers` call, which needs to return
`error.InvalidInput` and a wrappable error context. In Go we would add a
context to the error when returning it:
// if update_user fails, add context on which user we are operating
if err := update_user(user); err != nil {
return fmt.Errorf("user id=%d: %w", user.id, err)
}
Since Zig cannot pass anything else than u16 with an error …
> mem: add splitBackwards

- lib/std/json.zig
- lib/std/json/write_stream.zig
Newline Delimited JSON ([ndjson](ndjson.org)) expect compact json without newline inside its content
Add None to StringfyOptions.indent and move newline writeByte inside StringfyOptions.outputIndent
> std.json: Support disabling indent

- lib/std/math/big/int.zig
- lib/std/math/big/int_test.zig
- lib/std/math/big/rational.zig
- src/RangeSet.zig
- src/Sema.zig
Many of the Managed methods accepted by-val parameters which could
reference Limb slices that became invalid memory after any
ensureCapacity calls. Now, Managed methods accept `*const Managed`
parameters so that if the function allows aliasing and the
ensure-capacity call resizes the Limb slice, it also affects the
aliased parameters, avoiding use-after-free bugs.
This is a breaking change that reduces the requirement for callsites to
manually make the ensure-capacity changes prior to calling many of the
Managed methods.
Closes #11897
> std.math.big.int: breaking API changes to prevent UAF

- lib/std/net/test.zig
- src/codegen/llvm.zig
- test/behavior/union.zig
The LLVM backend was calculating the amount of padding solely based
on the payload size. However, in the case where there is no union
tag, this fails to take into account alignment.
Closes #11857
> LLVM: fix lowering of untagged union types

- lib/std/event/group.zig
- lib/std/event/locked.zig
> Correct the init function to use initLocked() for initializing std.event.Lock.

- lib/std/crypto.zig
- lib/std/crypto/ecdsa.zig
- lib/std/crypto/hash_composition.zig
A hash function cascade was a common way to avoid length-extension attacks with traditional hash functions such as the SHA-2 family.
Add `std.crypto.hash.composition` to do exactly that using arbitrary hash functions, and pre-define the common SHA2-based ones.
With this, we can now sign and verify Bitcoin signatures in pure Zig.
> std.crypto.hash: allow creating hash functions from compositions

- lib/std/crypto.zig
- lib/std/crypto/xoodoo.zig
- lib/std/rand.zig
- lib/std/rand/Xoodoo.zig
Gimli was a game changer. A permutation that is large enough to be used in sponge-like constructions, yet small enough to be compact to implement and fast on a wide range of platforms.
And Gimli being part of the Zig standard library was awesome.
But since then, Gimli entered the NIST Lightweight Cryptography Competition, competing against other candidates sharing a similar set of properties.
Unfortunately, Gimli [didn't pass the 3rd round](https://csrc.nist.gov/Projects/lightweight-cryptography/finalists).
There are no practical attacks against Gimli when used correctly, but NIST's decision means that Gimli is unlikely to ever get any traction.
So, maybe the time has come to move Gimli from the standard library to another repository.
We shouldn't do it without providing an alternative, …
> crypto: add the Xoodoo permutation, prepare for Gimli deprecation

- lib/std/macho.zig
- src/link/MachO.zig
- src/link/MachO/CodeSignature.zig
This is a prelude to a more elaborate work which will implement
`-dead_strip` flag - garbage collection of unreachable atoms. Here,
when sorting sections, we also check that the section is actually
populated with some atoms, and if not, we exclude it from the final
linked image. This can happen when we do not import any symbols
from dynamic libraries in which case we will not be populating
the stubs sections or the GOT table, implying we can skip allocating
those sections. Furthermore, we also make a check that a segment
is actually occupied too, with the exception of `__TEXT` segment
which is non-optional given that it wraps the header and load commands
and thus is required by the `dyld` to perform dynamic linking, and
`__PAGEZERO` which is generally non-optional when the linked image
is …
> macho: implement pruning of unused segments and sections

- src/Sema.zig
- test/behavior.zig
- test/behavior/bugs/12003.zig
Closes #12003
The Type in the TypedValue was being overwritten by the `field_ty` before the call to `fieldValue`.
> stage2: Fix corrupted Type when de-referencing field pointer

- lib/std/os/linux.zig
The fstype argument to the mount system call can be null.  To see an
example run "strace -e trace=mount unshare -m":
```
mount("none", "/", NULL, MS_REC|MS_PRIVATE, NULL) = 0
...
```
> Mark fstype argument to mount as optional

- src/Sema.zig
Commit 3014a0d5f1dcbcfdcec3852ffd54f3c589fe3e83 added calling convention validation, but left out thumb and thumbeb from the archs that can use the ARM-specific calling conventions. This plus a8a7f15106abef7c647d4de572a04b77ce048dd6 made compilation fail for thumb targets.
> Sema: accept thumb and thumbeb with ARM calling conventions

- lib/std/log.zig
- test/standalone/issue_7030/main.zig
@InKryption and I came to the conclusion that it'd be much nicer if instead of doing nothing `std.log.debug` etc. gave an error if you use it on a freestanding target with no top level `log` function available.
The reason this `builtin.os.tag == .freestanding` branch was added is #6252 where the issue was that when they tried to use the GPA, it would also semantically analyze `std.log`'s stuff which in turn would cause errors because most likely you did not implement any of that I/O stuff. Of course it is silly to require the user to implement all that I/O stuff when you just want to allocate.
However I think that if you choose to use the GPA, an allocator that can log messages, you should accept that you will also have to deal with the burden of some of the GPA's functionality not being …
> `std.log`: give friendly error to freestanding users

- src/TypedValue.zig
- src/type.zig
With these changes, it's now possible to print the AIR (`--verbose-air`) for:
```zig
test {
const anon_st = .{ .foo = 1, .bar = 2 };
_ = &anon_st.bar;
const anon_t = .{ 1, 2 };
_ = &anon_t.@"0";
const str: []const u8 = &[_]u8{ 1, 2, 3 };
_ = &str.len;
}
```
This also changes it so that comptime fields are always printed, for both structs and tuples.
The printing of slices could use some improvement still, but this is a step in the right direction.
> stage2: Fix panic when printing AIR for tuple/anon struct types

- lib/std/crypto/25519/ed25519.zig
Key blinding allows public keys to be augmented with a secret scalar, making multiple signatures from the same signer unlinkable.
https://datatracker.ietf.org/doc/draft-irtf-cfrg-signature-key-blinding/
This is required by privacy-preserving applications such as Tor onion services and the PrivacyPass protocol.
> crypto.sign.ed25519: add support for blind key signatures

- lib/std/start.zig
Hi, I'm new to zig and I'm so fascinated with it that I just started looking for some quick issues to tackle as the first contribution for me.
- https://github.com/ziglang/zig/issues/3767 
I thought this issue should be a good start, soon realizing that apparently it is already resolved except that one outdated TODO comment remains there. In fact, grep gives me the following result:
```
❯ rg 'issues/265'
lib/std/start.zig
364:// TODO https://github.com/ziglang/zig/issues/265
```
And the function that follows this TODO comment, `posixCallMainAndExit`, seems to be already taking advantage of sentinel-terminated pointers (I suppose [this commit](https://github.com/ziglang/zig/commit/15d415e10b81a66fa3b887fb2a0c20bbcd614d94#diff-d6d2716d80bf9cc45a0051d3ffe1885c2e2af19165a7bb1a9f04c3a595ffffd2) …
> Remove outdated TODO comment in lib/std/start.zig

- lib/std/log.zig
Instead of having a distinct type for every string length, we can generalize it using `[]const u8` to return a string of any length.
> `std.log`: deduplicate `switch`

- src/Sema.zig
- src/type.zig
- test/behavior/tuple.zig
- test/cases/compile_errors/offsetOf-bad_field_name.zig
Adds support for initializing `.anon_struct` types. Resolves #12030.
During this change, I noticed some loose ends still open from #11162, so I've added skipped behavior tests covering the missing functionality. I also filed  #12049 since we don't currently have a way to add skipped compile error tests (AFAIK)
> stage2: Support initializing anonymous struct type

- CMakeLists.txt
Before:
`-- Found llvm: /usr/lib/llvm/14/lib64/libLLVM-14.so (Required is at least version "13")`
After:
`-- Found llvm: /usr/lib/llvm/14/lib64/libLLVM-14.so (Required is at least version "14")`
> CMakeLists.txt: set LLVM minimal version to 14

- src/stage1/codegen.cpp
Calling sprintf() is now triggering an error on Xcode 14.
Using snprintf() is generally not a bad idea anyway.
> stage1/codegen: replace sprintf() with snprintf()

- lib/compiler_rt/common.zig
- lib/compiler_rt/fixdfti.zig
- lib/compiler_rt/fixhfti.zig
- lib/compiler_rt/fixsfti.zig
- lib/compiler_rt/fixtfti.zig
- lib/compiler_rt/fixunsdfti.zig
- lib/compiler_rt/fixunshfti.zig
- lib/compiler_rt/fixunssfti.zig
- lib/compiler_rt/fixunstfti.zig
- lib/compiler_rt/fixunsxfti.zig
- lib/compiler_rt/fixxfti.zig
- lib/compiler_rt/floattidf.zig
- lib/compiler_rt/floattihf.zig
- lib/compiler_rt/floattisf.zig
- lib/compiler_rt/floattitf.zig
- lib/compiler_rt/floattixf.zig
- lib/compiler_rt/floatuntidf.zig
- lib/compiler_rt/floatuntihf.zig
- lib/compiler_rt/floatuntisf.zig
- lib/compiler_rt/floatuntitf.zig
- lib/compiler_rt/floatuntixf.zig
- lib/compiler_rt/modti3.zig
- lib/compiler_rt/multi3.zig
- lib/compiler_rt/udivmodti4.zig
- lib/compiler_rt/udivti3.zig
- lib/compiler_rt/umodti3.zig
- lib/std/fmt.zig
- src/codegen/llvm.zig
- src/stage1/codegen.cpp
- test/behavior/vector.zig
Resolves #12063
Starting with LLVM 14, the Libcalls to these functions are now lowered using a `Vector(2, u64)` instead of the standard ABI for i128 integers on Windows, so our compiler-rt implementation needs to be updated to expose the same ABI
Relevant LLVM revision: https://reviews.llvm.org/D110413
> compiler_rt: Update Windows ABI for float<->int conversion routines

- lib/std/fmt.zig
Those 6 sets of square brackets are just a typographical aid used in this doc-comment, and must not actually be written by the user in their own format string placeholders... except for in one case where they must
> std.fmt: clarify the description of placeholders in Format Strings

- lib/std/math.zig
Implements simple conversion functions for `degrees` and `radians`. 
A quick search brings up https://github.com/ziglang/zig/issues/9889
> Add std.math.degrees and std.math.radians

- src/Compilation.zig
- src/test.zig
- test/compile_errors.zig
Now we can finally write long multiline error messages and they'll look nice!
While working on #12021 I thought it'd be really nice if we could actually make multiline error messages look nice so I worked on this. In hindsight, maybe the newline after the semicolon there wasn't really needed but that's besides the point of this PR.
One argument against this might be that error messages should be concise and you should never need more than one line but I think that's just not really a helpful rule.
I mainly did this so that *users* (i.e. `"this is bad"`) rather than lang devs (i.e. `"struct 'x.x' has no member named 'main'"`) could write longer error messages.
So if I as a lib dev for example like to give my users long helpful error messages because that's my style, why not allow me to …
> Indent multiline error messages properly

- build.zig
- ci/azure/macos_script
- lib/std/build.zig
- lib/std/build/CheckObjectStep.zig
- src/link.zig
- src/link/Wasm.zig
- test/link.zig
- test/link/wasm/bss/build.zig
- test/link/wasm/bss/lib.zig
- test/link/wasm/segments/build.zig
- test/link/wasm/segments/lib.zig
- test/link/wasm/stack_pointer/build.zig
- test/link/wasm/stack_pointer/lib.zig
- test/link/wasm/type/build.zig
- test/link/wasm/type/lib.zig
- test/tests.zig
Implements the linker-tests framework for the self-hosted wasm linker.
This includes a few test cases, as well as small fixes within the self-hosted linker that were caught during the implementation of the tests.
Note: This adds the `-fno-LLD` and `-fLDD` options to `build.zig` to make sure the self-hosted linker is used, rather than wasm-ld when running the tests.
> wasm-linker: Implement linker tests

- lib/std/zig/Ast.zig
- lib/std/zig/parse.zig
- lib/std/zig/parser_test.zig
- src/Module.zig
- src/main.zig
```zig
// a.zig
struct Foo {
a: u32,
};
```
before:
```
a.zig:1:1: error: expected test, comptime, var decl, or container field, found 'struct'
struct Foo {
^
```
after:
```
a.zig:1:8: error: 'struct Foo' is invalid
struct Foo {
^
a.zig:1:8: note: to declare a container do 'const Foo = struct'
struct Foo {
^
```
> parser: add helpful error for C style container declarations

- src/codegen/llvm.zig
Resolves #12086
Consider this lowered union type:
```llvm
%Value = type { <{ i64, [8 x i8] }>, i1, [7 x i8] } ; 24 bytes, align(1)
%ErrorUnion = type { %Value, i16 } ; 26 bytes, align(2)
```
Stage 2 incorrectly assumes that LLVM's `sizeof(%Value)` is 32 bytes, but it's actually 26 because the alignment of Value was "deleted" by the use of a packed struct. Stage 2 can then end up generating a 32-byte `memcpy` that exceeds the bounds of the corresponding `alloca`.
AFAICT, there are two ways to go about fixing this:
1. Make sure our LLVM type lowering never depends on the LLVM type being correctly aligned, OR
2. Make sure that we keep the alignment of LLVM types in sync with the Zig types they represent
This PR takes approach (2), mostly for simplicity. AFAICT, we don't need a packed struct …
> stage2 LLVM: Use non-packed struct for unions and arrays

- lib/std/io/c_writer.zig
- lib/std/mem.zig
- lib/std/x/net/bpf.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/zig_llvm.cpp
See individual commits for more info.
```
stage2/bin/zig build test-std
```
> stage2 bug fixes

- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- test/behavior/struct.zig
Previously, struct types, alignment values, and initialization
expressions were all lowered into the same ZIR body, which caused false
positive "depends on itself" errors when the initialization expression
depended on the size of the struct.
This also uses ResultLoc.coerced_ty for struct field alignment and
initialization values. The resulting ZIR encoding ends up being roughly
the same, neither smaller nor larger than previously.
Closes #12029
cc @kristoff-it - this affects ZIR encoding for autodocs
> stage2: lower each struct field type, align, init separately

- src/arch/arm/CodeGen.zig
In these cases, the division and modulo boils down to simple left shift and truncation respectively. Supporting arbitrary integer constants (e.g. using the algorithm from Hacker's Delight) is future work.
This change almost makes printing in the test runner possible.
> stage2 ARM: add integer div+mod with constant power-of-twos

- lib/compiler_rt/common.zig
- lib/std/math/float.zig
- lib/std/math/isinf.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/type.zig
- src/value.zig
- test/behavior/math.zig
For calling convention ABI purposes, integer attributes and return
values need to have an LLVM attribute signext or zeroext added
sometimes. This commit implements that logic.
It also implements a proof-of-concept of moving the F16T type from
being a compiler_rt hack to being how the compiler lowers f16 in
functions that need to match certain calling conventions.
Closes #12054
> LLVM: implement signext/zeroext attributes

- lib/std/os.zig
I've observed HOSTUNREACH on multiple versions of Linux.  It happens when the subnet is routable, but the host is not present on the subnet.  sendto/sendmsg already map HOSTUNREACH to NetworkUnreachable, so this follows that convention.
> handle HOSTUNREACH for blocking and non-blocking connects

- CMakeLists.txt
- cmake/Findclang.cmake
- cmake/Findlld.cmake
- cmake/Findllvm.cmake
CMake has a surprising default behavior where looking up a library by multiple names gives the name order higher priority than the directory search order. This change add `NAMES_PER_DIR` to request the more sensible behavior: directory search order has higher priority than name order.
Previously, system-provided "llvm-config-14" would always be chosen over "llvm-config" in CMAKE_PREFIX_PATH.
Now, any matching name found in CMAKE_PREFIX_PATH wins over system-provided tools/libraries.
> CMake: Use `NAMES_PER_DIR` in all lookups

- src/Sema.zig
- src/print_zir.zig
- src/value.zig
- test/behavior/array.zig
- test/behavior/if.zig
Previously, the logic for analyzing coerce_result_ptr would generate
invalid bitcast instructions which did not include coercion logic, such
as optional wrapping, resulting in miscompilations.
Now, the logic of resolve_inferred_alloc goes back over all the
placeholders inserted by coerce_result_ptr, and replaces them with logic
doing the proper coercions.
Closes #12045
```zig
fn doTheTest() !void {
var cond: bool = true;
const pc_range = if (cond) PcRange{
.start = 15,
.end = 30,
} else null;
assert(pc_range != null);
}
const PcRange = struct {
start: u64,
end: u64,
};
```
Each prong of the if expression incorrectly bitcasts the optional to a non-optional and then fails to account for the null bit at all.
```
%4 = const_ty(*bool)
%7 = const_ty((inferred_alloc_const))
%13 = const_ty(*const …
```
> Sema: fix coerce_result_ptr in case of inferred result type

- lib/std/c/freebsd.zig
- lib/std/os.zig
The getFdPath function did not previously support FreeBSD.  This adds just enough functionality to get that done.  The inclusion of the kinfo_file struct does not contain all the members of a union that holds details about different file types as that was not necessary for getFdPath.  I put a place holder named kf_filler which occupies the space of the union and keeps the alignment for following structure members.
This is my first real attempt at writing zig code so if I have not done things using proper zig idioms, I welcome feedback.
> Add FreeBSD support to std.os.getFdPath

- doc/langref.html.in
Fixes #11219.
I reviewed that code snippet and the ones before it and decided the best way to explain it involved slightly more changes than suggested in the issue, so that's what I did.
I couldn't test what the rendered docs look like because I don't see how to generate them. `zig run doc/docgen.zig` fails to compile.
> doc/langref: clarify behavior of slicing with constant indexes

- ci/azure/pipelines.yml
The currently used image is getting deprecated and every user is advised
to switch to either macos-11 or macos-12. The link to upstream
issue/notification:
https://github.com/actions/virtual-environments/issues/5583
> ci: bump macOS image on Github Actions to macos-11

- src/main.zig
This flag adds support to manually export a symbol in Wasm, similarly to what we already have for Zig code.
Fixes #12126
> zig cc: support '--export' linker argument

- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
- src/type.zig
As @topolarity noticed, sometimes the LLVM backend lowers types in a way that do not have an LLVM ABI size that matches the Zig ABI size. This is essentially unwanted undefined behavior whenever it occurs.
This branch has a mechanism to detect when this occurs and log about it in a debug build of the compiler. I have it disabled in the very last commit because there are more instances to fix before turning it on. However this branch already fixes two instances, one in optional types and one in error unions. Both are fixed by adding padding bytes at the end.
Note that we never call `LLVMABISizeOfType` because this fails when lowering types that reference pointers of themselves. Rather than work around this, it is much simpler for Zig to compute the padding itself and add it …
> Audit LLVM ABI size

- src/Compilation.zig
This is really minor but the issue this fixes is that if you copy-paste the following output of `--show-builtin` into your `build.zig` for example then the formatter will format
```zig
pub const os = std.Target.Os{
.tag = .freestanding,
.version_range = .{ .none = {} }
};
```
to
```zig
pub const os = std.Target.Os{ .tag = .freestanding, .version_range = .{ .none = {} } };
```
which doesn't match the output.
With this comma, the output of `--show-builtin` will stay the way it is after a `zig fmt`.
> style: add missing comma

- lib/std/build.zig
- lib/std/fs.zig
- lib/std/fs/test.zig
- lib/std/os.zig
- lib/std/testing.zig
- src/main.zig
- src/test.zig
- tools/process_headers.zig
- tools/update-license-headers.zig
- tools/update-linux-headers.zig
- tools/update_glibc.zig
- tools/update_spirv_features.zig
`walk` and `iterate` are moved to a new type `IterableDir`. `Dir` receives a new `openIterableDir` function which returns an `IterableDir` and also an `intoIterable` function which converts the `Dir` into an `IterableDir` asserting that it was opened with `iterate = true`.
Closes #12007
> std.fs: split `Dir` into `IterableDir`

- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
- src/main.zig
- src/print_zir.zig
- test/compile_errors.zig
```zig
comptime {
var a: u8 = 255;
var b: u8 = 255;
_ = (a - 1) + (b - 1);
}
comptime {
var a: u8 = 255;
var b: u8 = 255;
_ = (a - 1) +
(b - 1);
}
comptime {
var a: u8 = 255;
var b: u8 = 255;
_ = (a - 1)
+ (b - 1);
}
comptime {
var a: u8 = 255;
var b: u8 = 255;
_ = (a - 1)
+
(b - 1);
}
```
```
$ zig2 test a.zig
a.zig:4:17: error: overflow of integer type 'u8' with value '508'
_ = (a - 1) + (b - 1);
~~~~~~~~^~~~~~~~~
a.zig:9:17: error: overflow of integer type 'u8' with value '508'
_ = (a - 1) +
~~~~~~~~^
a.zig:16:9: error: overflow of integer type 'u8' with value '508'
+ (b - 1);
^~~~~~~~~
a.zig:22:9: error: overflow of integer type 'u8' with value '508'
+
^
```
~~I didn't edit compile error tests yet since this is likely to touch most of them and I want to wait for #12117/comments.~~ …
> Stage2 point to error location using spans

- lib/std/testing.zig
Before, this would fail to compile:
```zig
fn testFn(alloc: std.mem.Allocator, arr: []const u8) !void {
_ = alloc;
_ = arr;
}
test "checkAll" {
var arr = [_]u8{ 1, 2, 3 };
try std.testing.checkAllAllocationFailures(std.testing.allocator, testFn, .{arr[0..]});
}
```
with the error `error: Unexpected type for extra argument at index 0: expected []const u8, found *[3]u8`
By removing this strict equality check, we allow the type checking to be done during the `@field(args, arg_i_str) = @field(extra_args, field.name);` instead, which then allows for things like type coercion to work, but still will give a compile error if the types are incorrect. So, after this change, the above succeeds (because `*[3]u8` can be coerced to `[]const u8`).
The new compile error when providing an incorrect type …
> Fix `checkAllAllocationFailures` being too strict when checking arg types

- lib/std/testing.zig
```zig
const Struct = struct {
pub const test_constant = @compileLog("referenced - 0");
pub const InternalStruct = struct {
pub const internal_constant = @compileLog("referenced - 1");
};
};
```
**`refAllDecls()`:**
```zig
test "normal" {
std.testing.refAllDecls(Struct);
}
```
```sh
| *"referenced - 0"
```
**`refAllDeclsRecursive()`:**
```zig
test "recursive" {
std.testing.refAllDeclsRecursive(Struct);
}
```
```sh
| *"referenced - 0"
| *"referenced - 1"
```
we used the same approach in **Mach ([1](https://github.com/hexops/mach-freetype/blob/9b8b9796d9a22f2a05e701da0cbcdcf4ae8fcccb/src/utils.zig#L23-L36), [2](https://github.com/hexops/mach/blob/f8f4dcf55fc0b7365abfa66304e1f781b5f4eb42/sysaudio/soundio/main.zig#L16-L29))**
which were very helpful and found many errors
> std.testing: add `refAllDeclsRecursive` function

- lib/std/os/linux/io_uring.zig
Kernel 5.18 changed how `IORING_OP_TIMEOUT`, `IORING_OP_TIMEOUT_REMOVE` and `IORING_OP_REMOVE_BUFFERS` work, breaking some tests.
There are more details in the commit messages.
Fixes #11900
> Fix io_uring tests

- src/codegen/llvm.zig
This is a possible workaround for
https://github.com/llvm/llvm-project/issues/56585
On my computer it makes stage3-release go from false positive
compilation errors on the behavior tests to "segmentation fault".
Is this forwards progress or backwards progress? I have no idea.
See #11450
> LLVM: lower optional types as byref=true

- lib/std/math/big/int.zig
- lib/std/math/big/int_test.zig
This pull request fixes a problem that the capacity of std.math.big.int.Managed is too large after calling `mul` and `sqr` methods.
An actual trouble caused with this problem is [hnakamur/expNnWindowed-become-slow](https://github.com/hnakamur/expNnWindowed-become-slow).
It tried to allocate a way more memory than needed, and it caused the program run very slowly.
This pull request fixes this problem.
> Fix std.math.big.int.Managed capacity after mul and sqr

- src/codegen/llvm.zig
- test/behavior/packed-struct.zig
This makes [Aro](https://github.com/Vexu/arocc) pass all tests with #11798 worked around and  #11867 applied.
> stage2 llvm: fix handling of pointer fields in packed structs

- lib/std/math/big/int.zig
Running this kind of calculation (adapted from iguanaTLS) resulted in OOM errors
```
// encrypted = signature ^ key.exponent MOD key.modulus
while (curr_exponent.toConst().orderAgainstScalar(0) == .gt) {
if (curr_exponent.isOdd()) {
try result.mul(&result, &curr_base);
try llmod(&result, modulus);
}
try curr_base.sqr(&curr_base);
try llmod(&curr_base, modulus);
try curr_exponent.shiftRight(&curr_exponent, 1);
}
```
Bounding the allocation size of the result of sqr() to twice the used size (instead of twice the allocated size) avoids this issue.
Other similar functions in this file do allocation sizing based on `Managed::len()`. I think all allocation in this file should be done like this, but this is this is the most likely place it goes wrong.
> std.math bound big.int.Managed::sqr() allocation more tightly

- ci/zinc/linux_test.sh
- lib/std/hash/auto_hash.zig
- test/cli.zig
- test/compare_output.zig
* Use a debug build of stage3 instead of a debug build of stage2 for
our self-hosted compiler test coverage.
* Move coverage from stage1 to stage3 for:
- building self-hosted without LLVM
- building self-hosted for 32-bit arm
- test-compiler-rt
- test-behavior
- test-std
- caveat: release mode is skipped because I observed a problem
locally.
- test-compare-output
- test-asm-link
- test-fmt
> CI: increase stage3 test coverage

- lib/std/priority_queue.zig
update() calls mem.indexOfScalar() which uses `==` for comparing items,
which fails when the operator is not supported.
As PirorityQueue needs a comparing function anyway we can use `.eq` results
to identify matching objects.
closes #9918
> PriorityQueue: use compareFn in update()

- lib/std/zig/system/NativePaths.zig
`/usr/local/include`, `/usr/local/lib` and `/Library/Frameworks`
have been deprecated since approximately macOS 11, and so to avoid
redundant and misinformed warning messages generated by the linker,
add those dirs only when natively targeting macOS 10.x.x or below.
cc @andrewrk
> macos: add /usr/local/* paths conditional on macOS major version

- lib/std/json.zig
- lib/std/json/test.zig
Numbers greater than about 2^53 are encoded as strings in JSON, looking like `{ "12345678901234567890" }` instead of `{ 12345678901234567890 }`. `std.json.parseInternal` previously errored out because of this. It now tolerates integers wrapped in quotes. I've written a simple test case for this.
This has the side effect that `std.json.parse` will also accept small integers wrapped in quotes, though I think this is acceptable.
> std.json: Fix parsing of large numbers

- lib/std/net.zig
> std.net.getAddressList: fix segfault on bad hostname

- doc/langref.html.in
The current phrasing is vague; it is unclear whether it is demonstrating an example of the type of permitted behavior, from which the rule set must be extrapolated, or it is stating that this restriction only applies to the relationship between integers and bare structs.
> langref: clarify permitted `@bitCast` usage.

- lib/std/mem/Allocator.zig
I added an `alignedCreate` function because all of the other allocating functions had some variation which took could specify alignment, but `create` strangely did not.
> Allocator: add alignedCreate

- src/stage1.zig
Stage1 converts library names to lowercase, which isn't good when they're not all lowercase. I suspect this was done because they're insensitively compared with a bunch of libc and libc++ names, but `is_libc_lib_name` and `is_libcpp_link_name` already do a case-insensitive comparison so all it does is mangle the string and break cases where it has uppercase characters (such as `libX11`, where I ran into it). This regression appears to have been introduced in 5fed42d.
closes #11682
> stage1: don't lowercaseify lib names

- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/codegen/llvm.zig
- src/print_zir.zig
- test/cases/compile_errors/noinline_fn_cc_inline.zig
Fixes #11767
```zig
test {
foo();
}
noinline fn foo() void {
//
}
```
```
[meg@nixos:~/dev/zig]$ ./zig-out/bin/zig ast-check -t test.zig 
%0 = extended(struct_decl(parent, Auto, {
test line(0) hash(53b4e586ab7c73d53a2fda7c58ad19aa): %1 = block_inline({
%9 = func_fancy(test, inferror, body={
%2 = dbg_block_begin())
%3 = dbg_stmt(2, 5)
%4 = decl_val("foo") token_offset:2:5 to :2:8
%5 = dbg_stmt(2, 8)
%7 = dbg_block_end())
%6 = call(nodiscard .auto, %4, []) node_offset:2:5 to :2:10
%8 = ret_tok(@Zir.Inst.Ref.void_value) token_offset:3:1 to :3:2
}) (lbrace=1:6,rbrace=3:1) node_offset:1:1 to :1:5
%10 = break_inline(%1, %9)
}) node_offset:1:1 to :1:5
[40] foo line(4) hash(f3339e121db838fc9d98c7412345a9c5): %11 = block_inline({
%13 = func_fancy(noinline, body={
%12 = …
```
> stage2: implement `noinline fn`

- doc/langref.html.in
- lib/std/build.zig
- lib/std/crypto/phc_encoding.zig
- lib/std/fmt.zig
- lib/std/x/os/net.zig
- src/Cache.zig
- src/Compilation.zig
- src/link/MachO.zig
- src/link/Wasm.zig
- src/link/Wasm/Object.zig
- src/main.zig
- src/register_manager.zig
- src/translate_c.zig
Replaces #11754 (cleaner commit history & avoids merge conflict stuff).
Closes #11753.
> std.fmt: require specifier for unwrapping ?T and E!T.

- lib/test_runner.zig
Without this fix the following fails due to the index of the args being changed by the test runner log function.
```zig
test {
std.log.warn("{[0]d}, 0x{[0]X}", .{123});
}
```
> Fix indexing in the test runner's log formatting

- lib/std/fs.zig
- lib/std/fs/test.zig
This is a fix for a regression caused by https://github.com/ziglang/zig/commit/61c5d8f8f19d4321a492cb8a1adc4d221024f7d9
Closes #12209
> std.fs: Fix Walker closing the initial directory when not fully iterated

- src/codegen/llvm.zig
when deciding whether to lower to x86_fp80 instructions, or softfloat
instructions.
Closes #10847
Closes #12090
> LLVM: notice the soft_float CPU feature

- ci/zinc/linux_test.sh
- lib/std/build.zig
- lib/std/build/CheckObjectStep.zig
- lib/std/build/EmulatableRunStep.zig
- lib/std/build/RunCompareStep.zig
- lib/std/build/RunStep.zig
- test/link.zig
- test/link/macho/dead_strip/build.zig
- test/link/macho/dylib/build.zig
- test/link/macho/entry/build.zig
- test/link/macho/needed_library/build.zig
- test/link/macho/objc/build.zig
- test/link/macho/pagezero/build.zig
- test/link/macho/search_strategy/build.zig
- test/link/macho/stack_size/build.zig
- test/link/macho/weak_library/build.zig
Implements a new step that can run and compare the output for foreign binaries that will be run through emulation when enabled (or directly on the host when non-foreign binary). When disabled, it will skip running the binary and produce a warning instead. Said warning can be hidden by either setting the option manually in `build.zig` on the step, or passing `-Dhide-foreign-warnings`. This option is automatically added when creating the step.
The main goal of this step is to help us test the various linkers and we want to run it for multiple targets. This is especially useful when cross-compiling for ELF and MachO as they support more than a single architecture. For this reason, a handy function was appended to `CheckObjectStep` called `runAndCompare` that will automatically create this …
> Implement EmulatableRunStep for linker tests

- lib/std/testing.zig
Same as #11766 but without the messed up history (thanks git).
> `std.testing`: make the caret indicator line more helpful

- lib/std/fs.zig
- lib/std/fs/test.zig
This is one way to fix #12211, see that issue for more details
`getdents` on Linux can return `ENOENT` if the directory referred to by the fd is deleted during iteration. Returning null when this happens makes sense because:
- `ENOENT` is specific to the Linux implementation of `getdents`
- On other platforms like FreeBSD, `getdents` returns `0` in this scenario, which is functionally equivalent to the `.NOENT => return null` handling on Linux
- In all the usage sites of `Iterator.next` throughout the standard library, translating `ENOENT` returned from `next` as null was the best way to handle it, so the use-case for handling the exact `ENOENT` scenario specifically may not exist to a relevant extent
Previously, ENOENT being returned would trigger `os.unexpectedErrno` (and the added test …
> std.fs: End iteration on Linux/WASI during Iterator.next when hitting `ENOENT`

- build.zig
- src/arch/wasm/CodeGen.zig
- src/arch/wasm/abi.zig
- src/codegen/llvm.zig
- test/stage1/c_abi/build_wasm.zig
- test/standalone.zig
- test/tests.zig
This utilizes the same logic as what the Wasm backend uses, similar to what was done for x86_64. All the C ABI tests are now passing and are enabled for Wasm specifically when stage2 is enabled.
> stage2: llvm - Implement C ABI when targetting wasm32

- src/Module.zig
- src/Sema.zig
- test/compile_errors.zig
> Sema: `analyzeInlineCallArg` needs a block for the arg and the param

- build.zig
- ci/azure/build.zig
- lib/std/SemanticVersion.zig
- lib/std/builtin.zig
- lib/std/crypto/phc_encoding.zig
- lib/std/crypto/scrypt.zig
- lib/std/mem.zig
- lib/std/net.zig
- lib/std/process.zig
- lib/std/zig/CrossTarget.zig
- lib/std/zig/render.zig
- src/Compilation.zig
- src/libc_installation.zig
- src/test.zig
- tools/update_spirv_features.zig
Continuation of #11696
`first` feels pretty nice to work with. It was a good idea.
> feat: add `first` method to `SplitIterator` and `SplitBackwardsIterator`

- lib/std/mem.zig
I just had a case where I wanted to reuse a `SplitIterator` but couldn't find a `reset` on it even though `TokenIterator` (a close relative to `SplitBackwardsIterator` and `SplitIterator`) has one. You could argue that what `reset` does is too trivial to have a method for it but for `SplitBackwardsIterator` the implementation is a bit less trivial and a bit more specific. And, again, `TokenIterator` has `reset` too.
Alternatively, I think we should remove `reset` from `TokenIterator`.
> feat: add `reset` to `SplitBackwardsIterator` and `SplitIterator`

- lib/std/zig/Ast.zig
- lib/std/zig/parse.zig
- lib/std/zig/parser_test.zig
- lib/std/zig/system/darwin.zig
- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- test/cases/compile_errors/bad_usage_of_call.zig
- test/cases/compile_errors/error_in_call_builtin_args.zig
- test/cases/compile_errors/export_with_empty_name_string.zig
- test/cases/compile_errors/invalid_identifiers.zig
- test/cases/compile_errors/stage1/obj/wrong_panic_signature_runtime_function.zig
- test/standalone/issue_9812/main.zig
Closes #12233
Closes #12230
Closes #8262
> Stage2 improve errors for builtin function options structs

- CMakeLists.txt
- build.zig
- cmake/Findclang.cmake
- cmake/Findlld.cmake
- cmake/Findllvm.cmake
- src/stage1/config.h.in
This commit reworks the LLVM/Clang/LLD discovery process for CMake.
`llvm-config` really wraps **two** sets of libraries that exist in parallel in an installation: shared and static. Building LLVM according to the wiki gives you only static libs. However, building with `-DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_LINK_LLVM_DYLIB=ON` means that your LLVM/Clang installation with have *both* sets of libraries (which is usually the case for system-provided LLVM/Clang).
In that case, llvm-config reports entirely different libraries and dependencies for `--link-static` versus `--link-shared`
This include several changes to handle this better:
1. Search for `llvm-config` from most preferred directory to least, skipping any candidate that is the wrong version or doesn't support the requested link mode …
> CMake: Improve usage of `llvm-config` (esp. for consistent static/shared linking)

- doc/langref.html.in
- lib/std/fmt.zig
- src/Sema.zig
- src/arch/sparc64/bits.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/link/MachO/Atom.zig
- src/link/MachO/Dylib.zig
- src/link/MachO/Object.zig
- src/link/MachO/fat.zig
- src/main.zig
- src/print_zir.zig
- src/translate_c.zig
This makes it so that if you try to do `std.debug.print("{x:10}", .{.hello})`, it errors because
trying to format an enum literal as hexadecimal makes no sense. Currently it compiles as-is.
Basically what you're supposed to do instead is, in that case, `"{:10}"` or `"{any:10}"`.
The ":10" part to align the thing of course still works.
This is supposed to catch mistakes like `"{b:10}", .{true}` where maybe the user assumed
"b" means "boolean" but it means "binary". Or maybe they assumed it would print `1` or whatever? It's ambiguous.
It just doesn't seem right to accept `"{u:10}", .{null}` (which currently prints as "null") when something like `"{s:10}", .{5}` isn't accepted either.
Silently ignoring such invalid specifiers can give the user the wrong expectations so we should explicitly …
> feat(std.fmt): reject more invalid type specifiers 

- src/Module.zig
closes #9537
Note that, for some reason, I couldn't get this error to trigger. I have ensured that the check I changed triggers when it should, though. Not sure what's preventing it from erroring for me.
> fix error message importing file starting with module root path

- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
- src/main.zig
after a certain package depth, it appears access to the `'std'` package is lost. with this fix building [nektro/aquila](https://github.com/nektro/aquila) reaches a new error
```
[nix-shell:~/other/dev/aquila]$ ~/other/dev/zig/zig-out/bin/zig build --prominent-compile-errors -fno-stage1
/home/meg/other/dev/aquila/.zigmod/deps/git/github.com/nektro/zig-zorm/src/sqlite3.zig:1:21: error: unable to open 'std': PackageNotFound
^
aquila...The step exited with error code 1
error: the build command failed with exit code 1
[nix-shell:~/other/dev/aquila]$ ~/other/dev/zig/zig-out/bin/zig build --prominent-compile-errors -fno-stage1
Semantic Analysis [2456] ensureTotalCapacityPrecise... thread 78535 panic: integer overflow
/home/meg/other/dev/zig/lib/std/mem.zig:3045:54: …
```
>  stage2: ensure builtin packages are always available

- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_catch.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_if_bool.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_if_error.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_if_optional.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_orelse.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_switch.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_while_bool.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_while_error.zig
- test/cases/compile_errors/comptime_continue_inside_runtime_while_optional.zig
AstGen contains a bunch of hacks that I haven't fixed yet since I don't expect this solution to pass on the first try.
> stage2: add error for comptime control flow in runtime block

- src/stage1/parser.hpp
Fixes: 2a990d696 ("stage1: rework tokenizer to match stage2")
Fixes: b6354ddd5 ("move AST rendering code to separate file")
Signed-off-by: Wei Fu <fuweid89@gmail.com>
> stage1: remove deadcode ast_print

- build.zig
Adds a warning if config.h could not be located:
```
$ ./stage2/bin/zig build -Dlog -Denable-llvm --zig-lib-dir lib --prefix $(pwd)/stage3 --search-prefix ~/local/llvm13-release
warning: config.h could not be located automatically. Consider providing it explicitly via "-Dconfig_h"
```
The search for "config.h" now also stops early if it sees a `.git` folder, so that we don't go beyond the repo root.
> build.zig: Warn if "config.h" cannot be located

- build.zig
- src/clang.zig
- src/link/Elf.zig
- src/main.zig
- src/zig_clang.cpp
- src/zig_clang.h
If we are integrating with system LLVM, build.zig attempts to statically link `libc++`.
As a result, LLVM ends up with a separate "copy" of the library. This causes POSIX `std::error_code`s generated by LLVM and Clang always compare unequal, since they refer to (duplicated) static variables.
This PR changes libc++ to be linked dynamically and adds a runtime check to verify that LLVM and Clang are using a single instance of libc++. I believe this resolves https://github.com/ziglang/zig/issues/11168 (cc @mitchellh)
I might have missed some important build system details, so feel free to take this change over if needed.
> Dynamically link `libc++` if integrating with system LLVM

- src/TypedValue.zig
- src/value.zig
Packed structs never have comptime fields, and a slice might actually be backed by a variable, which we need to catch before iterating its elements.
Resolves #12293, cc @sin-ack who reported a similar issue on Discord
> stage2: Fix AIR printing

- cmake/Findllvm.cmake
If you have multiple llvm-config executables in your path, and all of
them cause failures, then only the last failure will be printed. This
can cause confusion when the multiple llvm-config executables are from
different major LLVM versions, i.e. LLVM 13 and 14, which might mask an
error that happened on the LLVM 14 llvm-config with an unrelated error.
This commit makes it so that all errors are collected into a list and
printed all at once; this way, you can see how each llvm-config
executable failed to configure properly. Note that the failures still
won't be printed if a successful configuration is found.
> cmake: Print all LLVM config errors instead of just the last one

- lib/std/os.zig
- lib/std/os/linux.zig
From https://man7.org/linux/man-pages/man7/inotify.7.html
> **IN_MASK_CREATE** (since Linux 4.18)
>
> Watch pathname only if it does not already have a watch associated with it; the error EEXIST results if pathname is already being watched.
> Linux: Add `IN_MASK_CREATE` and corresponding error handling in `inotify_add_watch`

- src/arch/wasm/CodeGen.zig
> wasm: fix typo in CodeGen.zig

- lib/std/fs.zig
- lib/std/fs/test.zig
Follow up to #12226, implements the compromise detailed in https://github.com/ziglang/zig/issues/12211#issuecomment-1196011590
> std.fs: Split `Iterator.next` on Linux and WASI to allow for handling platform-specific errors

- lib/docs/index.html
- lib/docs/main.js
As discussed in Discord.
Before:
After:
> autodoc: Add borders to field docs to make it clear which field they are associated with

- lib/docs/main.js
Just a small thing I found I could do.
> autodoc: better short description algorithm

- lib/std/build/CheckObjectStep.zig
- lib/std/macho.zig
- src/link/Dwarf.zig
- src/link/MachO.zig
- src/link/MachO/Archive.zig
- src/link/MachO/Atom.zig
- src/link/MachO/CodeSignature.zig
- src/link/MachO/DebugSymbols.zig
- src/link/MachO/Dylib.zig
- src/link/MachO/Object.zig
- src/link/MachO/dead_strip.zig
- src/link/MachO/fat.zig
Syncs with gitrev https://github.com/kubkon/zld/commit/a2c32e972f8c5adfcda8ed2d99379ae868f59c24
In addition, also revamps how we create and track output sections - instead sorting the ordinals and updating every symbol within each section, we keep the sections in a sorted order from the get-go. The logic for selecting and creating an output section for some input section is also significantly simplified leading to cleaner and smaller code.
I want to point out here that I have made the first step towards a more cache-friendly linker via the use of multiarraylist to track sections with the associated metadata such as the output segment index, and last atom in the section.
> macho: sync with standalone zld repo, improve memory usage and linking speed

- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/llvm.zig
This PR as the TODOs in the code state replaces the fields param_names and anytype_args with functions which fetch the data from elsewhere.
> Replace param_names and anytype_args fields inside of Fn with functions

- lib/std/os/linux/syscalls.zig
New changes: memfd_secret implemented for RISC-V.
> Update Linux syscall list for 5.19

- lib/std/meta.zig
Makes std.meta.Tuple and std.meta.ArgsTuple generate a unique type instead of generating one per invocation.
> std.meta.Tuple memoization fix

- lib/std/mem.zig
`std.mem.zeroes(struct{handle: void})` Failed with the following error before:
```
/nix/store/l6v4359wc9xrxxmvvp3rynsb5s3d78xf-zig-0.9.1/lib/zig/std/mem.zig:270:42: error: missing field: 'handle'
if (@sizeOf(T) == 0) return T{};
^
```
> std.mem.zeroes: Zero sized structs with uninitialized members

- src/Sema.zig
- test/cases/safety/modrem by zero.zig
- test/cases/safety/modulus by zero.zig
- test/cases/safety/remainder division by zero.zig
Piggybacking on 40f8f0134f5da9baaefd0fdab529d5585fa46199, remainder
division, modulus, and `%` syntax no longer emit safety checks for a
comptime-known denominator.
> Sema: elide safety of modulus and remainder division sometimes

- lib/docs/main.js
This changes how the documentation viewer creates search result items. By building up the HTML for the search results, and adding them to the DOM in one operation, it improves the performance when rendering many search results.
**Measurements:**
Starting from a freshly loaded page, and searching "a" (returning ~10,000 results) it takes ~70ms, versus ~1.9s previously.
**Old:**
**New:**
Unfortunately after this task, the browser recalculates styles and does a layout, taking another ~600ms or so. I'm still looking into what's causing that, but for now this is a small code change with a big improvement.
> autodoc: only modify the DOM once to display the search results

- src/link/Dwarf.zig
Previously, `@sizeOf(usize)` was used, however, the pointer size of
the host may differ from the target when cross-compiling.
cc @kubkon
> stage2 DWARF: fix size and offset in slices

- src/AstGen.zig
- src/Autodoc.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- test/cases/compile_errors/reify_type_for_tagged_union_with_extra_union_field.zig
This avoids the issue in #12358 (and generally results in nicer names for reified types) but doesn't prevent it happening somewhere else.
> stage2: pass anon name strategy to reify

- src/Sema.zig
- test/cases/compile_errors/shlExact_shifts_out_1_bits.zig
I couldn't figure out if I was running the test case, I don't think I was.
Completes part of #12366, doesn't add a similar check for `shrExact` or `divExact`.
> stage2: add compile error for shlExact overflow

- src/link/MachO/Object.zig
When parsing dylibs (binary files as opposed to text-based stubs), every `__LINKEDIT` data section has to be aligned to a minimum of `@alignOf(u64)` as otherwise `dyld` will refuse to load it, which means we don't have to relax the requirements for dylib parsing.
Closes #12387
> macho: allow unaligned offsets in object files

- lib/std/builtin.zig
- lib/std/zig/Ast.zig
- lib/std/zig/parse.zig
- lib/std/zig/parser_test.zig
- src/AstGen.zig
- src/Autodoc.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/codegen/llvm.zig
- src/print_zir.zig
- src/stage1/all_types.hpp
- src/stage1/analyze.cpp
- src/stage1/ir.cpp
- src/stage1/parser.cpp
- src/type.zig
- src/value.zig
- test/behavior.zig
- test/behavior/math.zig
- test/behavior/packed_struct_explicit_backing_int.zig
- test/behavior/type_info.zig
- test/cases/compile_errors/packed_struct_backing_int_wrong.zig
Now the backing integer of a packed struct type may be explicitly
specified with e.g. `packed struct(u32) { ... }`.
I haven't touched `Sema.zig` this extensively before, so any code/style pointers there are certainly appreciated.
Related: #10113, #5049
> stage2: Implement explicit backing integers for packed structs

- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
- test/standalone.zig
> stage2 llvm: implement more C ABI

- lib/std/os.zig
- lib/std/os/windows.zig
- src/link.zig
- src/main.zig
I encountered this error today when testing the self-hosted compiler on
Windows.
> std: add error.LockViolation to windows.WriteFile

- lib/std/hash/auto_hash.zig
> fix error message when providing slice to `std.hash.autoHash`

- lib/std/c/darwin.zig
- lib/std/c/dragonfly.zig
- lib/std/c/freebsd.zig
- lib/std/c/netbsd.zig
- lib/std/c/openbsd.zig
- lib/std/c/solaris.zig
- lib/std/debug.zig
- lib/std/os.zig
- lib/std/os/linux.zig
- lib/std/os/test.zig
POSIX specifies that the sa_handler field of the sigaction struct may
be set to SIG_IGN or SIG_DFL. However, the current constants in the
standard library use the function pointer signature corresponding to
the sa_sigaction field instead.
This may not cause issues in practice because the fields usually occupy
the same memory in a union, but this isn't required by POSIX and there
may be systems we do not yet support that do this differently.
Fixing this also makes the Zig interface less confusing to use after
reading the man page.
I've also included a commit fixing one case where we pass undefined memory to the kernel :/
> std: fix definition of SIG_IGN, SIG_DFL, etc.

- ci/azure/pipelines.yml
- test/link.zig
- test/stack_traces.zig
- test/standalone.zig
- test/tests.zig
Issue #12380
Check the last status of `zig.exe` and exit if an error occurred.
The last code that I wrote wrongly assumed that [ErrorActionPreference](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#:~:text=errorActionPreference-,ErrorActionPreference,-(Optional)%20When%20not) would catch executable errors.
> ci: windows: stop when exe exits with an error

- src/Sema.zig
- test/cases/compile_errors/signed_integer_division.zig
- test/cases/compile_errors/stage1/obj/signed_integer_division.zig
stage1 error reads
error: division with 'i32' and 'comptime_int': signed integers must use @divTrunc, @divFloor, or @divExact
Fixes: #12339
---
Trying to compile the example in #12339 
```zig
var v1: i32 = -49;
var v2: i32 = v1/2;
std.log.info("Result: {}", .{v2});
}
```
we now get
```bash
$ stage2/bin/zig test 12339.zig
12339.zig:5:21: error: division with 'i32' and 'comptime_int': signed integers must use @divTrunc, @divFloor, or @divExact
var v2: i32 = v1/2;
~~^~
```
> Sema: error on signed integer division

- src/arch/x86_64/CodeGen.zig
- src/link/Dwarf.zig
- src/link/MachO/DebugSymbols.zig
Add handling for these additional `MCValue`s:
* `.immediate` - lower to `DW.OP.consts` or `DW.OP.constu` depending
on signedness followed by popping off the DWARF stack with
`DW.OP.stack_value`
* `.undef` - lower to `DW.OP.implicit_value`
* `.none` - lower to `DW.OP.lit0` followed by popping off the DWARF
stack with `DW.OP.stack_value`
For any remaining unhandled case, we generate `DW.OP.nop` in order
not to mess up remaining DWARF info.
Also, update `__DWARF` sections before and after writing out `__LINKEDIT` sections in dSYM bundle for MachO.
> x86: fix generating debug info for variables

- src/AstGen.zig
- test/behavior.zig
- test/behavior/bugs/12430.zig
Super smol fix.
Resolves #12430.
> stage2 astgen: Use `rl` semantics for `@Type`

- lib/std/fs.zig
- lib/std/fs/test.zig
https://github.com/ziglang/zig/blob/d2342370fe85491cb8216ccce9cc8fb5259376e2/lib/std/fs.zig#L860-L864
Before this commit, the modified test would fail with `FileNotFound` because the `entry.dir` would be for the entry itself rather than the containing dir of the entry. That is, if you were walking a tree of `a/b`, then (previously) the entry for `b` would incorrectly have an `entry.dir` for `b` rather than `a`.
> std.fs: Fix `WalkerEntry.dir` not always being the containing dir

- lib/docs/index.html
- lib/docs/main.js
For reference, here is Rust's page when you have no results: https://doc.rust-lang.org/std/collections/struct.HashSet.html?search=wdqqdw
As you can see, it offers you to make a search with DDG.
Even as mainly a DDG user myself, I think this is a little bit opinionated so I didn't add any explicit search engine link to search with. There are [other search engines](https://github.com/r00ster91/shifting#search_engines) too.
---
This indentation you can see is supposed to be a visual clue that those shortcuts are only available when having pressed <kbd>S</kbd> (or the search field is active).
> autodoc: better No Results Found page and other improvements

- src/Sema.zig
- test/behavior/floatop.zig
- test/cases/compile_errors/ambiguous_coercion_of_division_operands.zig
The following, from the documentation as of the time of writing, illustrates
the problem:
```zig
// Compile time coercion of float to int
test "implicit cast to comptime_int" {
var f: f32 = 54.0 / 5;
_ = f;
}
```
It is not clear how to unify the types of 54.0 and 5 to perform the
division. We can either
- cast 54.0 to comptime_int resulting in @as(comptime_int, 10), which is
casted to @as(f32, 10), or
- cast 5 to comptime_float resulting in @as(comptime_float, 10.8), which
is casted to @as(f32, 10.8)
Since the two resulting values are different, a compiler error is appropriate.
Fixes: #12364
---
I wasn't sure about exactly which types should be disallowed, so I only used the comptimes. 
Further, this also raises an error in the flipped case, which stage1 doesn't:
```zig
// Compile time …
```
> Sema: error on ambiguous coercion of comptime float and ints

- lib/std/zig/system/NativePaths.zig
> fix memory leak in NativePaths.zig

- lib/std/zig/system/NativeTargetInfo.zig
UPD: See https://github.com/ziglang/zig/pull/12151#pullrequestreview-1044192217
> std.zig.system.NativeTargetInfo: look for a shebang line in /usr/bin/env, if any

- src/link.zig
- src/link/MachO.zig
Fixes #12408 
Firstly, opening a file handle is not really needed since we won't even
use it, and secondly, this can cause AccessDenied errors on Windows
when trying to move a directory from zig-cache/tmp/ to zig-cache/o/
since, without POSIX semantics, it is illegal to move directories
with open handles to any of its resources.
> macho: do not open file handle when building static archive

- lib/std/build/OptionsStep.zig
I don't see a reason why this shouldn't be allowed.
> build: Allow comptime_int in OptionsStep.addOption

- lib/std/target.zig
- lib/std/zig.zig
- lib/std/zig/CrossTarget.zig
- lib/std/zig/system/NativeTargetInfo.zig
- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/link.zig
- src/link/C.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/NvPtx.zig
- src/link/Plan9.zig
- src/link/SpirV.zig
- src/link/Wasm.zig
- src/main.zig
- src/stage1/codegen.cpp
- src/test.zig
- src/type.zig
- test/behavior/align.zig
Continuation of #12127. After this branch, there are no more instances of disagreements between LLVM ABI size and Zig ABI size when building stage3. However, it did not solve #11450.
The remaining ABI size mismatches that happen during behavior tests are:
```
error(codegen): when lowering behavior.ptrcast.testReinterpretExternStructAsExternStruct.S2, Zig ABI size = 6 but LLVM ABI size = 8
error(codegen): when lowering behavior.ptrcast.test.lower reinterpreted comptime field ptr (with under-aligned fields).S, Zig ABI size = 6 but LLVM ABI size = 8
error(codegen): when lowering builtin.Type.Fn.Param, Zig ABI size = 2 but LLVM ABI size = 3
error(codegen): when lowering [2]builtin.Type.Fn.Param, Zig ABI size = 4 but LLVM ABI size = 6
```
> More ABI size and alignment fixes

- src/link/MachO.zig
This manifested in different `AccessDenied` errors on Windows when
trying to do an atomic file copying in the compiler/linker.
> macho: do not leave file descriptors open if unused

- lib/std/os.zig
Stage2 seems to be able to handle this now.
> Enable unexpectedErrno error tracing for stage2 LLVM

- lib/std/build.zig
- lib/std/build/RunStep.zig
- src/link/Wasm.zig
- src/link/Wasm/Archive.zig
- src/link/Wasm/Object.zig
- test/link.zig
- test/link/wasm/archive/build.zig
- test/link/wasm/archive/main.zig
This includes a fix to correctly parse the names of object files. Wasm archive files follow the same convention as GNU, meaning the name array in the header either consists of the name itself, or the character index within the long name table. This table is parsed right after the symbol table and then stored. We then retrieve the name correctly by starting from the index (found in the header), until the delimiter: an LF character (0x0a).
Previously, we would also read object files until the end of the file. This is incorrect in the case where it's part of an archive file, as follow-up object files can be contained within that same file. We now pass the object file size to the parser which will then read all of that in a single pass, and then use a FixedBufferStream as a reader.
> wasm-linker: Improve archive linking

- lib/std/valgrind/callgrind.zig
Fixes the error when using std.vallgrind.callgrind:
`error: expected type '[2]u8', found '*const [2:0]u8'`
> Fix string type

- doc/langref.html.in
Addresses #11103
This add's a small note detailing the two's compliment representation of signed integers. 
I'm a Zig newbie but hoping to help out in the docs before digging deeper. Couldn't get the docs to build by running `zig run doc/docgen.zig` with 
```
zig git:master
❯ zig version
0.10.0-dev.3504+85a3f9b05
```
Any existing documentation for building the docs? if not, I can add some if you can tell me what I'm obviously doing wrong here 👍
> Add signed integer repr documentation

- lib/test_runner.zig
Essentially #1923 means "caught" errors still show up in error return traces.
The correct fix would require the compiler to fix this, but that could affect performance.
For now, simply workaround this issue by clearing the return traces
between tests.
This means that "caught" errors in one test will not show up in the
error traces of other tests.
Consider the following code:
```zig
const testing = std.testing;
export fn add(a: i32, b: i32) i32 {
return a + b;
}
test "expect error" {
const func = struct {
fn oom() !void {
return error.OutOfMemory;
}
};
try testing.expectError(error.OutOfMemory, func.oom());
}
test "basic add functionality" {
try testing.expect(add(3, 7) == 11);
}
```
Here is the behavior before this change:
Here is the behavior afterwards: …
> Partial workaround for #1923, isolating error return traces between individual tests

- test/tests.zig
The meaning of this "skip_stage2" flag was intended to mean the
self-hosted backends, not the stage2 frontend. Sorry for the confusion.
closes #12541
> test harness: don't skip tests

- lib/std/debug.zig
This `pdb.Pdb.init` call can return `error.FileNotFound`, which was previously resulting in:
Unable to print stack trace: FileNotFound
which also aborts the stack trace printing (so any deeper stack traces are not printed).
It makes more sense to treat it as `MissingDebugInfo` which then gets printed as:
???:?:?: 0x7fffa8817033 in ??? (???)
and allows the stack trace to continue printing.
Note: locally, the error.FileNotFound was being triggered for me when looking for kernel32.pdb and ntdll.pdb
---
Test code:
```zig
test "trace" {
std.debug.dumpCurrentStackTrace(@returnAddress());
}
```
Before:
```
Test [1/1] test "trace"... C:\Users\Ryan\Programming\Zig\zig\lib\test_runner.zig:79:28: 0x7ff7f4feb064 in root).main (test.obj)
} else test_fn.func();
^ …
```
> Windows: Fix output when .pdb file is not found during stack trace

- lib/std/coff.zig
- lib/std/debug.zig
- src/link/Coff.zig
We now do not allocate memory for headers and other metadata unless
requested by the caller. Instead, we read-in the entire contents
of the image into memory and operate on pointers and casts wherever
possible. I have a left a TODO to hook up Windows' memory-mapped API
here in-place of standard `readToEndAlloc` which should be more memory
proof on memory constrained hosts.
This commit also supplements our `std.coff` with a lot missing basic
extern structs required to make our COFF linker.
> coff: improve default COFF/PE object parser

- lib/docs/main.js
- src/Autodoc.zig
Changes the way compileError keeps its argument, and the way it renders in the frontend.
> autodoc: show compileErrors correctly

- lib/docs/index.html
Follow up to https://github.com/ziglang/zig/pull/12305
Before:
After:
> autodoc: Fix border color around field docs in light mode

- lib/std/os.zig
This constant returns an invalid `socket_t` that can be used as a sentinel value.
> std.os: add INVALID_SOCKET

- lib/std/meta.zig
A helper function with a expiration date. Makes sharing code between stage1 and stage2 easier, as otherwise this function will be replicated everywhere
> Adds std.meta.FnPtr for easier stage1/stage2 compatibility

- lib/std/build/TranslateCStep.zig
Unbreaks projects using stage1 and manual TranslateC
> Enables std.build.TranslateCStep to use stage1/stage2 selectively. 

- src/AstGen.zig
- src/Sema.zig
- src/value.zig
- test/behavior/generics.zig
- test/behavior/tuple.zig
- test/cases/compile_errors/comptime_parameter_not_declared_as_such.zig
- test/cases/compile_errors/error_in_typeof_param.zig
- test/cases/compile_errors/slice_of_non_array_type.zig
Ideally the nested function type thing would only apply to function types inside generic function types but that would require moving the param block inside the function type instruction.
> Stage2 fixes

- src/Compilation.zig
When the entire purpose of this compilation is to perform a single zig
cc operation we could "tail call" clang by doing an execve, and any use 
of the caching system would actually be problematic since the user is 
presumably doing their own caching by using dep file flags.
Fixes #12317
> compilation: avoid pointless caching

- lib/std/c.zig
`pthread_key_create` is used in emutls implementation, which is used on OpenBSD.
> pthread_key_create: make it build with stage2

- lib/std/mem.zig
- `alignBackward` does round 'down', not 'up'
- removed 'nearest' in favor of 'next' as its more in line with 'previous'
- added '(or current)', because the input address will be the output address if its already aligned.
- added a period at the end of the lines I touched, because it is missing when the stdlib docs are generated
> docs: remove confusion about align[For|Back]ward

- src/Sema.zig
- test/behavior/typename.zig
- test/cases/compile_errors/export_function_with_comptime_parameter.zig
- test/cases/compile_errors/extern_function_with_comptime_parameter.zig
This fixes a bug exposed by cd1833044ab7505bc101c85f59889bd3ea3fac80 a function type would be converted to generic_poison even after instantiated due to containing comptime only types.
This could also be fixed by just checking `is_generic_instantiation` this way also provides better type names.
Closes #12625
With this ci.ziglang.org should pass again (or at least get further).
> Sema: ignore comptime params in partial func type check

- src/Compilation.zig
- src/link.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/mingw.zig
This commit enables `-u <symbol>` for ELF and `-include:<symbol>` for COFF linkers for use internally. This means we do not expose these flags to the users just yet, however, we make use of them internally whenever required. One such use case is forcing inclusion of `_tls_index` when linking for Windows with mingw and LTO and dead code stripping enabled. This ensures we add `_tls_index` to the symbol resolver as an undefined symbol and force the linker to include an atom that provides it marking it a dead-code-stripping root - meaning it will not be garbage collected by the linker no matter what.
This is my proposed alternative to #8674 which doesn't rely on scanning input source files by name when compiling mingw and putting in the cache. Instead, we tell the linker to force-include …
> add ability to pass force-undefined-symbols to the linker

- src/translate_c.zig
- test/standalone.zig
- test/standalone/issue_12471/main.zig
A self-defined macro is one of the form `#define FOO FOO`
Those types of macros have never been translated; this change will cause
any macros which refer to them to be translated as `@compileError` instead
of referring to a non-existent identifier.
Closes #12471
> translate-c: Don't add self-defined macros to global name table

- src/Sema.zig
- test/behavior.zig
- test/behavior/bugs/12486.zig
- test/cases/coercion-to-unused-union-and-struct.zig
We call `sema.resolveTypeFields` in order to get the fields of structs
and unions inserted into their data structures. If it isn't called, it
can happen that the fields of a type is queried before those fields are
inserted into (for instance) `Module.Union.fields`, which would result in
a wrong 'no field named' error.
Fixes: #12486
> Sema: ensure resolveTypeFields is called for optional and error union types

- lib/std/os.zig
- src/link.zig
From `copy_file_range(2)` errors:
ETXTBSY
Either fd_in or fd_out refers to an active swap file.
Same error will be used in the upcoming `ioctl_ficlonerange(2)`:
ETXTBSY
One of the files is a swap file.  Swap files cannot share storage.
> copy_file_range: fix zigification of TXTBSY

- lib/docs/main.js
This change stops autodoc from cutting off doc comments at the first full stop for a short description, and instead will cut off doc comments at first paragraph, or after 80 characters, whichever is sooner.
This prevents short summaries of multiple sentences from being cut early, and prevents examples without a second paragraph from creating noise.
> autodocs: improve first-line descriptions

- lib/docs/main.js
This change allows autodoc to render empty error sets (this previously caused a runtime error), and to correctly render multi-item error sets in the same style as `zig fmt`. 
Before:
- empty `[crashes]`
- single `error{Foo}`
- multi `error{Foo, Bar}`
After:
- empty `error{}`
- single `error{Foo}`
- multi `error{ Foo, Bar }`
> autodocs: improve error set rendering

- lib/std/c/openbsd.zig
`sc_fpstate` member of `struct sigcontext` is a [`struct fxsave64 *`](https://github.com/openbsd/src/blob/2207c4325726fdc5c4bcd0011af0fdf7d3dab137/sys/arch/amd64/include/signal.h#L83).
use `*anyopaque` to represent it.
avoid to defining `fxsave64` as it is a [packed struct with some arrays](https://github.com/openbsd/src/blob/2207c4325726fdc5c4bcd0011af0fdf7d3dab137/sys/arch/amd64/include/fpu.h#L17-L30) and zig doesn't compile with it (see #12547)
> openbsd: fix sigcontext struct and avoid defining fxsave64

- lib/std/c.zig
- lib/std/elf.zig
- lib/std/io/bit_reader.zig
- lib/std/io/bit_writer.zig
- lib/std/meta.zig
- lib/std/multi_array_list.zig
- src/Sema.zig
- test/behavior/union.zig
- test/cases/compile_errors/explain_why_fn_is_called_at_comptime.zig
- test/cases/compile_errors/non_comptime_param_in_comptime_function.zig
Closes #12333
This PR implements a compile error for when a function which return type is comptime only takes a parameter which might be a runtime parameter.
> Add compile error for runtime parameter in function returning a comptime only type.

- doc/langref.html.in
It was removed from the language.
> docs: Remove mention of type inference on anytype struct fields

- lib/std/rand.zig
- lib/std/rand/test.zig
The ~~`dice`~~ `weightedIndex` function picks from a list of weighted indices.  This is useful in situations where the developer needs to select from a range of options which are not equally weighted; this is common in simulations or algorithms like Wave Function Collapse.
~~A note on naming: I went with `dice` because that's what the algorithm is called in the [D standard library](https://dlang.org/library/std/random/dice.html).  Other good options would be `weightedIndex` and `pickIndex`.~~
This implementation should work with all primitive numeric types.
> Add Random.weightedIndex function

- src/type.zig
- test/behavior/cast.zig
- test/c_abi/cfuncs.c
- test/c_abi/main.zig
According to https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md the size of c's long double is 16 bytes for Wasm, rather than 8 bytes we previously used in the compiler. This ensures we not only pass the correct values but also create the correct function signature needed to pass the Wasm validator. e.i. When passing a `c_longdouble` to a function, we pass it as 2 separate `f64`'s.
This essentially fixes a bug where the compiler-rt function `roundl` was generating an incorrect function signature and causing a miscompilation when targeting Wasm.
This also adds an additional test case in c_abi tests.
> stage2: fix size of c_longdouble for Wasm target

- src/link/Wasm.zig
Regardless of the build mode (build-exe, build-lib), always set the default stack size to 1MB. Previously, this was only done when using build-exe, making the inconsistancy confusing. The user can still override this behavior by providing the `--stack <size>` flag.
Closes #3735.
> wasm-lld: set stack size to 1MB by default

- src/main.zig
fixes #12503
followup to https://github.com/ziglang/zig/commit/2759313263d58dba324788dbe346ed1506b239dc that only implemented for `zig build-{exe|lib}` and `zig cc`
> implement cache environment variables for `zig build`

- lib/std/coff.zig
I was quite confused when some executables were seemingly missing the COFF header magic number. It turns out that the `0x3C` COFF header offset was being read as a byte and not a `u32`, causing the header to sometimes be read incorrectly.
I'm also working with COFF for a project, so I added some missing constants I needed.
> coff: fix reading COFF header offset

- CMakeLists.txt
- lib/std/coff.zig
- lib/std/start.zig
- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Mir.zig
- src/link.zig
- src/link/Coff.zig
- src/link/Coff/Atom.zig
- src/link/Coff/Object.zig
- src/link/Coff/lld.zig
- src/link/MachO.zig
- src/link/MachO/DebugSymbols.zig
- src/link/strtab.zig
- test/cases/aarch64-macos/hello_world_with_updates.0.zig
- test/cases/x86_64-linux/hello_world_with_updates.0.zig
- test/cases/x86_64-macos/hello_world_with_updates.0.zig
tl;dr we can correctly link and execute a very crude and hacky program of the form:
```zig
pub export fn _start() noreturn {
exit();
}
fn exit() noreturn {
asm volatile ("syscall"
:
: [arg1] "{r10}" (0),
[arg2] "{rdx}" (0xc0000005),
[number] "{eax}" (0x2c),
);
unreachable;
}
```
This is clearly not a program you'd expect to every see for Windows as we call into a syscall directly, but nonetheless, it was minimal enough just to test some basic assumptions about the PE/COFF structure. Also, for interested, `0x2c` corresponds to `NtTerminateProcess` in latest Win10 (a word of warning, Microsoft changes those very regularly).
In order to simplify working on the incremental COFF linker, I have move all code that deals with LLD into `Coff/lld.zig` - this way, `Coff.zig` has manageable LOCs. …
> coff: initial rewrite of the COFF/PE linker

- lib/std/zig/c_translation.zig
- test/behavior/translate_c_macros.h
- test/behavior/translate_c_macros.zig
Closes #10793
Co-authored-by: Veikka Tuominen <git@vexu.eu>
> translate-c: promote large integer macros to unsigned long long if necessary

- lib/std/log.zig
Some recent change makes slice concatenation runtime (merge #12368), so the example needs to be explicitly made comptime.
> Using `comptime level.asText()` in log example

- doc/langref.html.in
saying `[]T` is a pointer is confusing because zig docs say there are two types of pointers (`*T` and `[*]T`). It is more clear to say that `[]T` is a slice type which contains a `[*]T` pointer and a length.
> `[]T` pointer confusion in docs.

- lib/std/os.zig
Happens if you do this:
```zig
var socket = try std.os.socket(
std.c.AF.LOCAL,
std.c.SOCK.STREAM,
0
);
const sockaddr = std.os.sockaddr.in{
.port = std.mem.bigToNative(u16, 7777),
.addr = @as(u32, 0),
};
try std.os.bind(socket, @ptrCast(*const std.os.sockaddr, &sockaddr), @sizeOf(@TypeOf(sockaddr)));
```
> Add AFNOSUPPORT error to bind

- lib/std/zig/parser_test.zig
- lib/std/zig/render.zig
Fix #12655 
It will remove the trailing comma at the end of inline assembly clobber.
For example, before format:
```zig
fn foo() void {
asm volatile (""
: [_] "" (-> type),
:
: "clobber"
);
asm volatile (""
:
: [_] "" (type),
: "clobber",
);
}
```
After format:
```zig
fn foo() void {
asm volatile (""
: [_] "" (-> type),
:
: "clobber"
);
asm volatile (""
:
: [_] "" (type),
: "clobber"
);
}
```
> Fix #12655: zig fmt remove trailing comma at the end of assembly clobber

- src/arch/aarch64/abi.zig
- src/codegen/llvm.zig
- test/c_abi/main.zig
- test/standalone.zig
... at least enough to pass all the current tests.
Should fix #12483
> stage2 llvm: implement aarch64 C ABI

- src/autodoc/render_source.zig
sorry that i forgot light theme in previous PR 
colors are taken from [*Documentation*](https://ziglang.org/documentation/master/) page
> autodoc: fix highlighted line in light mode

- src/translate_c.zig
- test/behavior/translate_c_macros.h
- test/behavior/translate_c_macros.zig
> translate-c: convert tabs to `\t` in object-like macro string literals

- lib/std/simd.zig
The element_bit_size will break if T is ~~unsigend~~ signed by how ceilPowerOfTwo works
@noiryuh made a good point there, u16 should be enough, I hope
> Change T to u16

- src/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/translate_c.zig
- test/behavior.zig
- test/behavior/bugs/12776.zig
- test/behavior/pointers.zig
- test/cases/compile_errors/closure_get_depends_on_failed_decl.zig
- test/cases/compile_errors/closure_get_in_param_ty_instantiate_incorrectly.zig
- test/cases/compile_errors/incorrect_type_to_memset_memcpy.zig
Previously if a decl failed its capture scope would be deallocated and
set to undefined which would then lead to invalid dereference in
`zirClosureGet`. To avoid this set the capture scope to a special
failed state and fail the current decl with dependency failure if
the failed state is encountered in `zirClosureGet`.
> Sema: fix UAF in zirClosureGet 

- lib/std/os/uefi/protocols/block_io_protocol.zig
Forgot to do this in the initial PR mb
> std.os.uefi: mark BlockIoProtocol and EfiBlockMedia as public

- doc/docgen.zig
- lib/std/build.zig
- lib/std/build/EmulatableRunStep.zig
- lib/std/zig/system/NativeTargetInfo.zig
- src/codegen/llvm.zig
- src/main.zig
- src/test.zig
Previously, this code would fail to detect glibc version because it
relied on libc.so.6 being a symlink which revealed the answer. On modern
distro versions, this is no longer the case.
This new strategy finds the path to libc.so.6 from `/usr/bin/env`, then
inspects the `.dynstr` section of libc.so.6, looking for symbols that
start with "GLIBC_2.". It then parses those as semantic versions and
takes the maximum value as the system-native glibc version.
-----
Before, native glibc and dynamic linker detection attempted to use the
executable's own binary if it was dynamically linked to answer both the
C ABI question and the dynamic linker question. However, this could be
problematic on a system that uses a RUNPATH for the compiler binary,
locking it to an older glibc version, while system …
> std.zig.system.NativeTargetInfo: improve glibc version and dynamic linker detection

- src/translate_c.zig
- test/behavior/translate_c_macros.zig
- test/behavior/translate_c_macros_not_utf8.h
Macro definitions are simply a slice of bytes, which may not be UTF-8 encoded. If they are not UTF-8 encoded, escape non-printable and non-ASCII characters as `\xNN`.
Fixes #12784
> translate-c: Escape non-ASCII characters that appear in macros

- src/type.zig
- test/behavior/typename.zig
- test/cases/compile_errors/comptime_param_coersion.zig
Given the source
```zig
fn f(_: i32, comptime _: i32) void {}
test {
_ = @as(*const fn (i32, i32) void, f);
}
```
this turns the compile error from
```
repro.zig:4:40: error: expected type '*const fn(i32, i32) void', found '*const fn(i32, i32) void'
_ = @as(*const fn (i32, i32) void, f);
^
repro.zig:4:40: note: pointer type child 'fn(i32, i32) void' cannot cast into pointer type child 'fn(i32, i32) void'
repro.zig:4:40: note: generic function cannot cast into a non-generic function
```
into
```
repro.zig:4:40: error: expected type '*const fn(i32, i32) void', found '*const fn(i32, comptime i32) void'
_ = @as(*const fn (i32, i32) void, f);
^
repro.zig:4:40: note: pointer type child 'fn(i32, comptime i32) void' cannot cast into pointer type child 'fn(i32, i32) void'
repro.zig:4:40: note: …
```
> type: print comptime on fn type params

- src/arch/arm/CodeGen.zig
- src/arch/arm/Emit.zig
- src/arch/arm/Mir.zig
- test/behavior/alignof.zig
- test/behavior/array.zig
- test/behavior/basic.zig
- test/behavior/bitcast.zig
- test/behavior/cast.zig
- test/behavior/comptime_memory.zig
- test/behavior/const_slice_child.zig
- test/behavior/enum.zig
- test/behavior/error.zig
- test/behavior/eval.zig
- test/behavior/field_parent_ptr.zig
- test/behavior/for.zig
- test/behavior/generics.zig
- test/behavior/merge_error_sets.zig
- test/behavior/pointers.zig
- test/behavior/ptrcast.zig
- test/behavior/sizeof_and_typeof.zig
- test/behavior/slice.zig
- test/behavior/struct.zig
- test/behavior/switch.zig
- test/behavior/this.zig
- test/behavior/try.zig
- test/behavior/union.zig
- test/behavior/usingnamespace.zig
- test/behavior/while.zig
The new `allocRegs` register allocation mechanism provides a simple, clean and extensible API for allocating input and output arguments for a certain operation. It replaces the old `binOp` mechanism.
Also includes several commits of general improvements and bug fixes.
> stage2 ARM: introduce allocRegs mechanism and other improvements

- lib/std/child_process.zig
- src/Compilation.zig
- src/glibc.zig
Before, Zig tried to use its own libc files (e.g. glibc) when there were no system libs being linked. This prevented building against native glibc on systems that have newer glibc than the ones Zig provides.
Closes #12797
> stage2: no condition on system libs to link native libc
