ziglang/zig

lib/std/linked_list.zig
Looking through the source and found these unused
=> chore: Remove unused constants in linked_list

doc/langref.html.in, src/AstGen.zig, src/Sema.zig, src/Zir.zig, src/print_zir.zig, test/behavior/defer.zig, test/cases/compile_errors/return_from_defer_expression.zig, test/cases/compile_errors/uncreachable_else_prong_err_set.zig, test/cases/returns_in_try.zig
Storing defers this way has the benefits that the defer doesn't get multiple times in AstGen, it takes up less space, and it Sema aware of defers allowing for 'unreachable else prong' on error sets in generic code.
The disadvantage is that it is a bit more complex and errdefers with now emit a placeholder instruction (but those are rare).
```
Sema.zig before:
Total ZIR bytes:    3.7794370651245117MiB
Instructions:       238996 (2.051319122314453MiB)
String Table Bytes: 89.2802734375KiB
Extra Data Items:   430144 (1.640869140625MiB)
Sema.zig after:
Total ZIR bytes:    3.3344192504882812MiB
Instructions:       211829 (1.8181428909301758MiB)
String Table Bytes: 89.2802734375KiB
Extra Data Items:   374611 (1.4290275573730469MiB)
```
=> stage2: change how defers are stored in Zir

src/link/Wasm.zig, src/link/Wasm/Archive.zig, src/link/Wasm/Atom.zig, src/link/Wasm/Object.zig, src/link/Wasm/Symbol.zig, src/link/Wasm/types.zig
Changes the behavior from writing to the file constantly, to first writing the entire binary's contents to a buffer before writing it to the file during `flush`. This reduces the number of system calls in exchange for an increase in temporary memory usage. Additionally, we now only write the magic bytes of the Wasm format when the entire `flush` was successful. This makes it easier to find errors as tools (such as wasm-objdump) will tell us the magic bytes are missing. Lastly, this gets rid of all the usage of `self` and replaces it with meaningful names instead.
=> wasm-linker: misc improvements & cleanups

lib/std/Thread.zig, lib/std/heap/general_purpose_allocator.zig, lib/std/math.zig, src/AstGen.zig, src/Autodoc.zig, src/Sema.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/link/Plan9.zig, src/print_air.zig, src/translate_c/ast.zig, src/type.zig, test/behavior/bugs/11165.zig, test/behavior/type.zig, test/behavior/type_info.zig, test/cases/compile_errors/non-comptime-parameter-used-as-array-size.zig, test/cases/compile_errors/pointless discard.zig, test/cases/type_of.0.zig, test/translate_c.zig
Example:
```zig
test {
var x: i32 = 1234;
x += 1;
_ = x;
}
```
```
test.zig:4:9: error: pointless discard of local variable
_ = x;
^
test.zig:3:5: note: used here
x += 1;
^
```
Related: #12803
----
* Needs a compile error test added
* I'm not sure why but this seemed to expose a latent bug:
```
thread 559744 panic: reached unreachable code
/home/andy/Downloads/zig/lib/std/debug.zig:281:14: 0xad82d8 in std.debug.assert (zig2)
^
/home/andy/Downloads/zig/src/type.zig:2508:23: 0xf71d26 in type.Type.hasRuntimeBitsAdvanced (zig2)
assert(union_obj.haveFieldTypes());
^
/home/andy/Downloads/zig/src/type.zig:3041:62: 0xd41d42 in type.Type.abiAlignmentAdvanced (zig2)
if (!(try field.ty.hasRuntimeBitsAdvanced(false, sema_kit))) continue;
^ …
```
=> introduce compile error for pointless discards

lib/std/unicode.zig
* comptime and runtime tests are based on tests for counting utf8 code points
=> std.unicode: add utf16 byte length and codepoints counting routines

doc/langref.html.in
Fixes https://github.com/ziglang/zig/issues/11579
=> docs: add missed docs for some language feature like `defer` and `errdefer`

src/print_env.zig
Add the native target triple to the zig env command output.
The target triple is formatted the same way as it is done in the
zig targets command.
=> src/print_env: print the native target

lib/std/c/freebsd.zig
Required for #1759.
I wrote a simple project that verified the sizes against the headers at compile time:
```zig
// Vendored from std/c/freebsd.zig.
// Change the first line to `@import("std");` to compile
const freebsd = @import("freebsd.zig");
const c = @cImport({
@cInclude("sys/types.h");
@cInclude("sys/socket.h");
@cInclude("sys/event.h");
@cInclude("sys/umtx.h");
@cInclude("sys/link_elf.h");
@cInclude("sys/fcntl.h");
@cInclude("sys/stat.h");
@cInclude("sys/timespec.h");
@cInclude("sys/dirent.h");
@cInclude("sys/socket.h");
@cInclude("sys/signal.h");
@cInclude("sys/ttycom.h");
@cInclude("sys/ucontext.h");
@cInclude("sys/stack.h");
@cInclude("sys/poll.h");
@cInclude("netinet/in.h");
@cInclude("sys/un.h");
@cInclude("netinet/if_ether.h"); …
```
=> Audit FreeBSD structs to match header files/ABI

lib/std/os.zig
by making the initial value for the variable `err` in the function `execvpeZ_expandArg0` of the file os.zig equal to `error.FileNotFound`. Closes #12816.
Explanation: The `execvpeZ_expandArg0` function was returning an undefined `err` because it never went into the while loop right after (because the PATH was empty) which I guess was causing the `invalid error code`. I fixed it by just making the `err` variable initially equal to `error.FileNotFound`. `error.FileNotFound` is returned for a PATH that is not empty where a command or executable could not be found.
=> fix ChildProcess crash when PATH is empty.

lib/std/c/linux.zig
These definitions no longer match the bionic source code.  Also, this line was a compilation error:
```
__reserved: [12]u8 = [_]u8{0} ** 2
```
=> fix android definition of pthread_rwlock_t

src/main.zig
If `-o` is not specified for `zig cc` for linking, it should emit the `a.out` (or equivalent) to the current directory. So then this:
$ zig cc test.c
Should result in `./a.out`.
If directory is omitted from `Compilation.EmitLoc`, it will default to the cache directory later in the compilation chain, which will result in `a.out` missing in the current directory.
If we specify the directory to `Compilation.EmitLoc`, it will be handled, allegedly, correctly.
Fixes #12858
=> zig cc: emit to a.out if outpath is unspecified

lib/std/os/linux.zig
https://linux.die.net/man/2/stat
`u32` does not satisfy trying to pass a `mode_t` on various architectures
=> std: fix os.linux.S function signatures to use mode_t

src/AstGen.zig, src/Autodoc.zig, src/Sema.zig, src/Zir.zig, src/print_zir.zig
cmpxchg_weak and cmpxchg_strong are not very common; demote them to extended operations to make some headroom.
This commit does not change any behavior, only memory layout of the compiler.
This takes us from 256/256 tags used to 254/256 tags used.
=> stage2: free up 2 ZIR tags

src/Sema.zig, test/cases/compile_errors/asm_at_compile_time.zig
=> Sema: `evalutate` → `evaluate` in error message

src/AstGen.zig, test/cases/compile_errors/missing_else_clause.zig
fix https://github.com/ziglang/zig/issues/12743
if not have else body, should be store void_value to the pointer explicitly.
=> AstGen: store void_value to ptr when else body is empty

lib/std/fs/path.zig
Seems like an accidentally unfinished sentence in here. I shortened it and added an example.
=> Fix docstring for std.fs.path.extension

doc/langref.html.in
The syntax for function pointers has changed and I noticed a couple places in the docs that weren't updated.
=> (Docs) New function pointer syntax

lib/std/fmt.zig
currently being ignored by `_ = options;`
thanks to Chuck in Zig discord
=> make `fmt.formatAsciiChar` respect `options` parameter

lib/std/c/darwin.zig
Added missing types defined in sys/_types.h and <machine>/_types.h.
=> add missing darwin types

src/Sema.zig, test/cases/compile_errors/unhandled_enum_value_in_switch_with_enum_declared_in_other_file.zig, test/compile_errors.zig
The enum we want to get the fields from might not be declared in the same file as the block we are analyzing, so we should get the AST from the decl's file instead.
Closes #12950.
=> sema: load the correct AST in addFieldErrNote

src/codegen/llvm.zig, src/stage1/codegen.cpp
I noticed (https://github.com/ziglang/zig/pull/12740#issuecomment-1257112045) that after the LLVM 15 update, the exception record (unwind info) was missing from the COFF info.
This seems to be caused by an incorrect attribute value for `uwtable`. Based on https://llvm.org/docs/LangRef.html it, the options are (0: off, 1: sync, 2: async). 
I'm not familiar enough with the difference between the sync/async, but it seems like async was the default previously and has the most detailed unwind info.
=> llvm: fix missing unwind info (wrong uwtable attribute value)

lib/std/build.zig
Having access to this function will make it possible for zls to get more include paths in its build runner.
=> make `runPkgConfig` pub

lib/compiler_rt/emutls.zig, lib/std/enums.zig
This is needed if the field type happens to be a pointer/slice, addresses #12957.
=> std.enums.EnumFieldStruct: add explicit cast for default_value

src/main.zig
My specific use case is that my editor (emacs) creates temporary broken symlinks while editing a file (seems like a locking mechanism?) which causes `zig fmt` to error.  Some testing shows that formatting a non-broken symlink overwrites the symlink, which seems a bit unsafe, so I chose to just ignore symlinks completely.
=> Avoid error trying to format broken symlinks

src/Sema.zig
=> Sema: avoid passing `.unneeded` to `safetyPanic`

lib/std/fs/file.zig
Stumbled onto this while investigating #12091. The comment seems mistaken, and the issue it links to is closed.
=> Remove outdated comment

doc/langref.html.in
The language reference for `unreachable` doesn't mention `ReleaseSmall`.
=> Docs: clarify unreachable for ReleaseSmall

src/Sema.zig, test/cases/compile_errors/assign_to_constant_variable.zig
resolves #12793
All operators mentioned in the issue ( `^=` `&=` `|=`  `/=` `%=` `<<=` `<<|=` `>>=` ) are now having correct error location. 
For example:
```zig
main.zig:3:10: error: cannot assign to constant
data ^= 1;
~~~~~^~~~
```
=> Shema: improve source location in errors

lib/std/builtin.zig
I don't think this was supposed to be public. Seems to be an exclusively internally-used function.
=> std.builtin: un-pub testVersionParse()

lib/std/testing.zig
~~I think this is confusing behavior. It should either just behave like the non-recursive equivalent `refAllDeclsRecursive` and be allowed to be used anywhere, or it should fail with a compile error if `!builtin.is_test`.
Either way, I expect both `refAllDecls` and `refAllDeclsRecursive` to behave the same in regards to where you can use those functions. So if `if (!builtin.is_test) return;` shouldn't be removed, I think it should be added to `refAllDeclsRecursive` as well (or alternatively both should fail with an error if `!builtin.is_test`).~~
See https://github.com/ziglang/zig/pull/13007#pullrequestreview-1124812982
Closes #12998 with a proper conclusion.
=> std.testing.refAllDeclsRecursive: silently return if !builtin.is_test

lib/std/child_process.zig
17b0166e moved getUserInfo from std.os to std.process but ChildProcess.setUserName never updated the pkg name.
=> std.ChildProcess: correct fn getUserInfo pkg in setUserName

src/Sema.zig, test/cases/compile_errors/packed_struct_field_alignment_unavailable_for_reify_type.zig
Fixes #13028.
Added a check to see if the alignment in each field is set to 0.
Now `@typeInfo` does not produce a segfault if the alignment is set to anything other than 0.
=> Sema: Fixed segfault arising from @TypeOf bug with packed struct field alignments

lib/std/os/windows.zig
Looking at https://learn.microsoft.com/en-us/windows/console/handlerroutine, it seems this should use `WINAPI` for 32-bit compatibility.
=> std.os.windows: fix HANDLER_ROUTINE callconv

src/Sema.zig, test/cases/compile_errors/function_type_coercion.zig
```
expected type 'fn() void', found 'fn(i32) void'
function with 0 parameters cannot cast into a function with 0 parameters
```
=>
```
expected type 'fn() void', found 'fn(i32) void'
function with 1 parameters cannot cast into a function with 0 parameters
```
=> Sema: fix function paramater count mismatch note

src/codegen/llvm.zig
Before this change, if I take a debug zig dynamically linked to release llvm 15.0.1 compiled with release stage3 zig, and run `build-obj` on this program:
```zig
export fn f() void {}
```
I get the following output:
```
LLVM Emit Object... 
function definition may only have a distinct !dbg attachment
ptr @f
thread 27187 panic: LLVM module verification failed
codegen/llvm.zig:773:17: 0x90c2eb in flushModule (zig)
link/Elf.zig:960:47: 0x922c7c in flushModule (zig)
link/Elf.zig:1250:29: 0x91763b in linkWithLLD (zig)
link/Elf.zig:946:32: 0x908378 in flush (zig)
/home/jacob/Source/zig/src/link.zig:655:68: 0x905795 in flush (zig)
.elf => return @fieldParentPtr(Elf, "base", base).flush(comp, prog_node),
^
/home/jacob/Source/zig/src/Compilation.zig:2440:24: 0xa75943 in flush (zig) …
```
=> stage2: fix C ABI for bool

src/Module.zig, src/Sema.zig, src/codegen/llvm.zig, test/standalone.zig, test/standalone/issue_13030/build.zig, test/standalone/issue_13030/main.zig
Fixes #13030 and #12933, but does not address https://github.com/ziglang/zig/issues/12933#issuecomment-1255658710, which I cannot reproduce locally.
~~I do not have much experience with stage2 internals yet, so if a reviewer could confirm that `ensureDeclAnalyzed` can be called from this context, since there are currently no other calls to it in `llvm.zig`.~~  A subsequent error makes it clear that this was, indeed, the wrong approach, so I worked out another solution that makes much more sense.
=> stage2: fix branches on undefined values

src/Compilation.zig
Pulls out the `-g` cc flag addition to the common area so that it is also applied to assembly files.
=> stage2: add support for assembly debug info

lib/std/os/wasi.zig
This implements the new addition to the API: `sock_accept`.
Reference WASI commit can be found in the commit message.
=> std: WASI - update to latest snapshot preview 1

src/Autodoc.zig, src/Compilation.zig, src/Module.zig
Before this commit:
```
$ zig test lib/std/fs/test.zig --main-pkg-path lib/std --zig-lib-dir lib
2170 passed; 37 skipped; 0 failed.
```
After this commit:
```
$ zig test lib/std/fs/test.zig --main-pkg-path lib/std --zig-lib-dir lib
All 45 tests passed.
```
This matches stage1 behavior:
```
$ zig test -fstage1 lib/std/fs/test.zig --main-pkg-path lib/std --zig-lib-dir lib
All 45 tests passed.
```
All tests are still run if `zig test` is run directly on `lib/std/std.zig`:
```
$ zig test lib/std/std.zig --main-pkg-path lib/std --zig-lib-dir lib
2170 passed; 37 skipped; 0 failed.
```
`zig build test-std` is unaffected by this change.
Closes #12926
---
Prior relevant commits for context:
- 3b60ab4872355f0b9a9c7d0794ca8b548ab99412
- ec95e00e28cb23f37dc097f71afd7090e947a1cd
=> Fix all std lib tests being run for any file within the std package

src/clang.zig, src/translate_c.zig, src/zig_clang.cpp, src/zig_clang.h, test/run_translated_c.zig, test/translate_c.zig
This is relevant to the fix and discussion in #12735 (and supersedes it).
@ifreund noticed that `align(1)` is missing from `translate-c` output. Hoewever that bug is present with both stage1 & stage2 and is technically independent from that other PR.
~~Until PR #12735 is applied (or some other fix to #12733), `packed struct` will only work with translate-c on stage1.~~
~~I'm hoping this will help work towards getting `packed struct` to support `extern` (but I don't really understand the details too much).~~
**EDIT**: Zig's notion of packed struct is an integer e C's notion of packed struct is essentially an `extern struct` with every field set to `align(1)` (as @ifreund already noticed below).
Since the last stable release (0.9.1), there was a **change in the language spec** related to …
=> translate-c: Translate clang packed struct C into Zig extern struct with align(1)

lib/std/build/CheckObjectStep.zig, src/link/Wasm.zig, test/link.zig, test/link/wasm/producers/build.zig, test/link/wasm/producers/lib.zig
Implements the `producers` custom section. This section contains meta data describing what tools were used to generate the binary as well as what the source language was. Other tools can use this information to apply certain transformations (such as name mangling for c++), or even optimizations.
For now, we always emit Zig as source language and as tool used to produce the binary. The next step would be to parse all linked object files and static archives and append their source languages and tools + SDK's also.
=> wasm-linker: generate 'producers' section

src/arch/wasm/Emit.zig, src/link/Wasm.zig, src/link/Wasm/Atom.zig, src/link/Wasm/Object.zig, src/link/Wasm/types.zig
Did an oopsie and interpret the specification incorrectly. We now parse and write `addens` for a relocation correctly, while still ensuring the final relocation value is a positive integer as addresses are always a positive number.
=> wasm-linker: convert relocation addend to i32

src/stage1/parse_f128.c
Before:
```c
[ 81%] Built target embedded_softfloat
[ 85%] Built target zigcpp
Consolidate compiler generated dependencies of target opt_c_util
[ 85%] Building C object CMakeFiles/opt_c_util.dir/src/stage1/parse_f128.c.o
/home/bratishkaerik/zig-upstream/src/stage1/parse_f128.c:986:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static inline float128_t makeInf128() {
^
void
/home/bratishkaerik/zig-upstream/src/stage1/parse_f128.c:993:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static inline float128_t makeNaN128() {
^
void
2 errors generated.
gmake[2]: *** [CMakeFiles/opt_c_util.dir/build.make:76: …
```
=> Fix building with Clang 16

lib/std/math.zig
regression introduced in #11432
resolves #12315 
I saw that `isPowerOfTwo` panics when provided `0`
https://github.com/ziglang/zig/blob/7f508480f49b78817bf67579a8810d4499cbbc13/lib/std/math.zig#L1072-L1075
Also, upon `T == u0` both the current and previous rotate implementations would have panicked anyways
https://github.com/ziglang/zig/blob/7f508480f49b78817bf67579a8810d4499cbbc13/lib/std/math.zig#L643
https://github.com/ziglang/zig/blob/5b8ac9821dd25c3e5282130b4d93d6c5b7debb08/lib/std/math.zig#L561
So I thought it might be a good idea to make passing `u0` a compile error.
=> Reimplement bitwise rotates of non-power-of-two integers

lib/compiler_rt.zig, lib/compiler_rt/divc3.zig, lib/compiler_rt/divc3_test.zig, lib/compiler_rt/divdc3.zig, lib/compiler_rt/divhc3.zig, lib/compiler_rt/divsc3.zig, lib/compiler_rt/divtc3.zig, lib/compiler_rt/divxc3.zig, lib/compiler_rt/extenddfxf2.zig, lib/compiler_rt/extendf.zig, lib/compiler_rt/extendf_test.zig, lib/compiler_rt/mulc3.zig, lib/compiler_rt/mulc3_test.zig, lib/compiler_rt/muldc3.zig, lib/compiler_rt/mulhc3.zig, lib/compiler_rt/mulsc3.zig, lib/compiler_rt/multc3.zig, lib/compiler_rt/mulxc3.zig, lib/std/math/ilogb.zig, lib/std/math/ldexp.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig, test/standalone/c_compiler/test.c
Resolves https://github.com/ziglang/zig/issues/9259
Due to the C ABI, these functions won't work on all targets until we have `c_complex_float`, et al. (see https://github.com/ziglang/zig/issues/8465)
At least this gives us an implementation until we can sort out the ABI 🙂
=> compiler-rt: Implement complex multiply/division

lib/std/Progress.zig
It seems we can simply lock the update mutex a little earlier.
Before:
```
~/Desktop/zig$ zig build -p stage3 -Dsanitize-thread --zig-lib-dir lib
~/Desktop/zig$ stage3/bin/zig run x.zig
AST Lowering [21] zig/number_literal.zig... LLVMSymbolizer: error reading file: No such file or directory
==================
WARNING: ThreadSanitizer: data race (pid=6670)
Read of size 8 at 0x7ffd5dd43000 by thread T2:
#0 memcpy <null> (zig+0x1ce7896)
```
After:
```
~/Desktop/zig$ zig build -p stage3 -Dsanitize-thread --zig-lib-dir lib
~/Desktop/zig$ stage3/bin/zig run x.zig
```
Fixes #13072
=> fix: resolve data race in std.Progress.maybeRefresh()

lib/std/os/linux/io_uring.zig
The function std.os.accept correctly allows for nullable arguments.  This change allows the same with io_uring's accept API, providing some symmetry with the std.os.accept API.
=> io_uring: allow for nullable arguments in accept

build.zig, lib/std/build.zig, src/Compilation.zig, src/main.zig, test/cli.zig, test/link/wasm/archive/build.zig, test/link/wasm/bss/build.zig, test/link/wasm/segments/build.zig, test/link/wasm/stack_pointer/build.zig, test/link/wasm/type/build.zig
Closes #6676
```
ali@linux ~/d/zig (o0)> build/zig2 build-exe z.zig -O ReleaseSmall
ali@linux ~/d/zig (o0)> ls -lha ./z ./z.o
-rwxr-xr-x 1 ali ali 8.5K Oct  4 17:52 ./z*
-rw-r--r-- 1 ali ali  12K Oct  4 17:52 ./z.o
ali@linux ~/d/zig (o0)> build/zig2 build-exe z.zig -O ReleaseSmall --strip
ali@linux ~/d/zig (o0)> ls -lha ./z ./z.o
-rwxr-xr-x 1 ali ali 8.5K Oct  4 17:52 ./z*
-rw-r--r-- 1 ali ali  12K Oct  4 17:52 ./z.o
ali@linux ~/d/zig (o0)> build/zig2 build-exe z.zig -O ReleaseSmall --no-strip
ali@linux ~/d/zig (o0)> ls -lha ./z ./z.o
-rwxr-xr-x 1 ali ali 426K Oct  4 17:53 ./z*
-rw-r--r-- 1 ali ali 729K Oct  4 17:53 ./z.o
ali@linux ~/d/zig (o0)> build/zig2 build-exe z.zig
ali@linux ~/d/zig (o0)> ls -lha ./z ./z.o
-rwxr-xr-x 1 ali ali 976K Oct  4 17:53 ./z*
-rw-r--r-- 1 ali ali 1.4M Oct  4 …
```
=> Compilation: strip debug info from ReleaseSmall by default

src/codegen/llvm.zig, test/behavior.zig, test/behavior/bugs/13128.zig
This little guy was affecting our self-hosted backends
Resolves #13128
=> stage2 LLVM: Use packed aggregate for union payload init

src/Sema.zig, test/behavior/export.zig
Implements exporting namespaced declarations. e.g. `@export(a.b, .{...});`
closes #12532
=> stage2: implement exporting using field access

lib/std/os/uefi/protocols/managed_network_protocol.zig, lib/std/os/uefi/protocols/simple_text_input_ex_protocol.zig, lib/std/os/uefi/tables/boot_services.zig
This is an attempt to make `std.os.uefi` work with self-hosted (stage2); it is currently broken.
With this PR, the following now works:
```zig
std.testing.refAllDeclsRecursive(std.os.uefi);
}
```
```
$ zig run x.zig --zig-lib-dir lib
$
```
However, it doesn't work with stage1:
```
$ zig run x.zig --zig-lib-dir lib -fstage1
./lib/std/os/uefi/protocols/simple_text_output_protocol.zig:7:38: error: struct 'std.os.uefi.protocols.simple_text_output_protocol.SimpleTextOutputProtocol' depends on itself
pub const SimpleTextOutputProtocol = extern struct {
^
./lib/std/os/uefi/tables/system_table.zig:27:5: note: while checking this field
con_out: ?*SimpleTextOutputProtocol,
^
./lib/std/os/uefi/protocols/loaded_image_protocol.zig:10:33: error: struct …
```
=> std.os.uefi: fix some mistakes

src/arch/wasm/CodeGen.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/llvm.zig, test/behavior.zig, test/behavior/bugs/13068.zig, test/behavior/slice.zig
Implements missing codegen for `.field_ptr` on a slice in various backends.
Fixes #13068
Extracted from #13093 since that quickly devolved into exclusively CBE fixes.
=> codegen: implement slice field pointer

lib/std/fs.zig, lib/std/fs/test.zig
From @andrewrk in https://github.com/ziglang/zig/pull/13070#issuecomment-1268046310:
> I'd like to fully exhaust the non-recursive, non-heap-allocating implementation options before resorting to this. Could you try a version that uses a fixed-size stack buffer (and resorts to redundant syscall operations in the case that the buffer is exhausted)?
>
> I think we should have only one implementation in the standard library. Hopefully it can accomplish all the characteristics we want:
>
> - Equivalent or better perf of rm -rf.
> - No possibility of stack overflow due to "user input" of a deeply nested file system tree
> - No allocator parameter required.
This PR implements this suggestion and (I think) accomplishes everything in the list. It is just as fast as the recursive implementation in …
=> `fs.Dir.deleteTree`: Optimize for non-deeply-nested directories

lib/std/build.zig, src/main.zig
build.zig:
- use `-I` instead of `-isystem` for `b.addSearchPrefix()`
main.zig:
- silently ignore superfluous search dirs
- warn when a dir is added to multiple searchlists
- consolidate "expected paramter after {s}" fatal error messages
- rename command-line switch `-dirafter` → `-idirafter`
closes #12888
=> improve header searchlist handling in build, main

lib/std/Progress.zig
I really had a lot of attempts at this and I think this might be the best one so far. I think there's still some things to improve but this is definitely a start.
Output now fits nicely on pretty much any terminal width (well, not if it's >256 though, but that limit can easily be bumped):
Here's another common issue that I think Andrew described in https://github.com/ziglang/zig/issues/12024#issuecomment-1176803566:
That issue seems to be fixed now; here's a compilation on a terminal with a very small width:
https://user-images.githubusercontent.com/35064754/178335637-3a187e07-9cc9-4cc5-9ac3-45bda66ebc95.mp4
It succeeds with nothing left on the terminal.
Closes #12024
=> `std.Progress`: fix inaccurate line truncation and use optimal max terminal width

lib/std/os.zig
At least on Linux, the sendto command can cause the INVAL error with 'user-side' error. I.e. not a clear bug in the code, but simply the address being send to not being in the right ip address range. There is no definite way to check for this issue before hand, so it should probably not turn to an unreachable and crash.
The user still has to deal with the enum and could make it unreachable if that is required on their side.
Here is an example to show the issue:
```
const os = std.os;
const net = std.net;
const address_all = net.Address.initIp4([_]u8{ 0, 0, 0, 0 }, 4040);
const address = net.Address.initIp4([_]u8{ 127, 0, 0, 1 }, 4040);
const address_target_ok = net.Address.initIp4([_]u8{ 127, 0, 0, 42 }, 4040);
const …
```
=> Return invalid argument in sendto instead of unreachable

lib/std/os/linux.zig, lib/std/os/linux/io_uring.zig
=> io_uring: ignore SOCK_NONEMPTY for reproducible tests

lib/std/Progress.zig
Just some follow-ups to #12079
Some things mentioned here could still be fixed in the future in some way.
Fixes #13150
=> fix(std.Progress): some follow-ups

src/codegen/llvm.zig, test/standalone.zig, test/standalone/emit_asm_and_bin/build.zig, test/standalone/emit_asm_and_bin/main.zig
I tried finding a better solution, but emitting is just too stateful in llvm, so I ended up just copying the logic from stage1.  For reference, if you ask clang for both outputs, then it emits the asm file first and then assembles that with the integrated or system assembler.
Fixes #12800
=> stage2: fix -femit-asm

lib/std/target.zig, src/type.zig, test/standalone.zig
This makes the following changes for i386:
long long and unsigned long long have 4 byte alignment on non-Windows
f64 (double) has 4-byte alignment on non-Windows
long double is 80 bits and has 4 byte alignment on mingw
long double on android is 64 bits, not 80: https://www.uclibc.org/docs/psABI-i386.pdf
Fixes #12453
Fixes #12987
=> i386 ABI: Fix some sizes and alignments

lib/std/os/windows.zig
The definition of HKEY__ as a struct with an unused int field is only the case in the Windows headers when `STRICT` is defined. From https://learn.microsoft.com/en-us/windows/win32/winprog/enabling-strict:
> When STRICT is defined, data type definitions change as follows:
>
> -  Specific handle types are defined to be mutually exclusive; for example, you will not be able to pass an HWND where an HDC type argument is required. Without STRICT, all handles are defined as HANDLE, so the compiler does not prevent you from using one type of handle where another type is expected.
Zig's `opaque {}` already gives this benefit to us, so the usage of a struct with an unused field is unnecessary, and it was causing HKEY to have an alignment of 4, which is a problem because there are HKEY constants …
=> std.os.windows: Change HKEY to *opaque {}

lib/std/fs.zig
closes #12970 
Due to the unavailability of `fchdir` in Windows, a call for setting the CWD needs to either call `chdirW` or `SetCurrentDirectory` with the path string (`[]const u16`). Unfortunately, Windows does not offer any functions for setting the current working directory via handle/fd, which is what `setAsCwd()` uses.
Since we are dealing with a Handle in Windows, a call for `GetFinalPathNameByHandle` is necessary for getting the file path first in order to call `SetCurrentDirectory`.
Another option is to have this condition inside `fchdir` instead. 
This was tested using the following code: 
```zig
const dir = try std.fs.cwd().openDir("C:\\", .{}); 
try dir.setAsCwd(); 
var buffer: [1024]u8 = undefined; 
const cwd = std.fs.cwd(); 
std.debug.print("@@@{s}@@@\n",.{try …
```
=> Added os check for std.fs.setAsCwd() to work on Windows

src/codegen/llvm.zig, test/behavior.zig, test/behavior/bugs/12972.zig
I tried auditing the other calls to `lowerValue`, and it seems like they all use types which can't (at least currently) be byval.
However, I'm not sure if they should also call `resolveValue` anyway for consistency/future-proofing.
Closes #12972
=> llvm: fix bug lowering aggregate_init with a byref sentinel

lib/std/builtin.zig, lib/std/os.zig, lib/std/target.zig, src/Module.zig, src/Sema.zig, src/link/NvPtx.zig, src/target.zig, test/cases.zig, test/stage2/nvptx.zig
Due to the progress on 0.10 a few things broke Nvptx backend.
Some of the changes I'm pushing here are outside of  `link/NvPtx.zig`, and are modifying  shared code.
Let me know if you can think of a better way to structure the changes. From least controversial to more controversial.
* link/NvPtx.zig -> I'm modifying in place the "Compilation" object. Now I restore the changes before returning. A bit hacky but it allows to reuse the rest of the LLVM backend code without modification there.
* Target.zig -> PTX only support debug information starting from PTX 7.5. Not sure how to test "ptx >= 7.5".
* Sema.zig -> allow to use Zig objects in exported .PtxKernel functions. This allow tight integration between CPU/GPU code and was approved by Andrew given that we can change it later if we …
=> Update Nvptx backend for Zig 0.10

src/codegen/llvm.zig, test/behavior.zig, test/behavior/bugs/12025.zig
When we want a runtime pointer to a zero-bit value we use an undef pointer, but what if we want a runtime pointer to a comptime-only value? Normally, if `T` is a comptime-only type such as `*const comptime_int`, then `*const T` would also be a comptime-only type, so anything referencing a comptime-only value is usually also comptime-only, and therefore not emitted to the executable.
However, what if instead we have a `*const anyopaque` pointing to a comptime-only value?  Certainly, `*const anyopaque` is a runtime type, and so we need some runtime value to store, even when it happens to be pointing to a comptime-only value.  In this case we want to do the same thing as we do when pointing to a zero-bit value, so we use `hasRuntimeBits` to handle both cases instead of ignoring comptime. …
=> llvm: fix lowering of runtime refs to comptime-only decls

src/Module.zig, test/standalone.zig, test/standalone/issue_12588/build.zig, test/standalone/issue_12588/main.zig
* `--verbose-llvm-ir` should trigger analysis and codegen
* `-femit-asm` etc should trigger codegen even with `-fno-emit-bin`
Closes #12588
=> Module: fix early exit conditions during compilation

doc/langref.html.in, src/codegen/llvm.zig
* When a field starts at some bit offset within a byte you need to load starting from that byte and shift, not starting from the next byte, so a rounded-down divide is required here, not a rounded-up one.
* Remove paragraph from doc that no longer relates to anything.
Closes #12363
=> llvm: fix lowering of non-byte-aligned field pointers

lib/std/ascii.zig
Supersedes #11629 
This should be a lot easier to review than #11629 because it does a lot less.
It mainly renames some functions and removes 3. It also adds a lot more tests.
See the commit descriptions for the reasons of all the deprecations and renamings.
They're all just deprecated so it will still work in 0.10 (if this gets into 0.10). After that they'll be removed.
You might also be interested in Rust's naming decisions: https://doc.rust-lang.org/std/primitive.char.html#method.is_ascii
=> std.ascii: rename functions and other improvements

lib/std/meta.zig
This PR adds a runtime function called isTag to std.meta; This function returns a `bool` that reflects if the enum or tagged union corresponds to the tag name, which is a comptime string.  Although using the actual tag enum value is generally preferable, in some cases (such as FFI) easy access to the string representation is desirable.
As indicated in the documentation, this function runs in constant time, regardless of the size of the enum/union or the length of the string representations of the tag name.
I can also provide tests against the compile-time checks if desired.
=> adds isTag function to std.meta

src/main.zig
handler removed in https://github.com/ziglang/zig/commit/5f97652da8881773b823a0730e5791816668528a
=> stage2: remove `--verbose-mir` from help menu

lib/std/os/linux/bpf.zig
- For ALU operations, src should be allowed to be an explicit Reg.
- Expose AluOp and JmpOp as public types. This makes code generation using BPF as a backend easier, as AluOp and JmpOp can be used directly as part of an IR
=> os.linux: some fixes to BPF module

lib/std/zig/system/NativePaths.zig
distro like guix doesn't use FHS, so it relies on envorinment variables (`C_INCLUDE_PATH`, `CPLUS_INCLUDE_PATH` and `LIBRARY_PATH`) to search for headers and libraries
=> std.zig: search include dir and lib dir from environment variables

lib/std/os.zig
For e.g. SO_BINDTODEVICE, ENODEV is a legit error code if the interface has disappeared. This PR adds a case for that.
=> fix setsockopt returning ENODEV

src/main.zig
For #10501. Basic use case:
```
stage3/bin/zig build-exe --name hello/a <source file>
```
Outputs to `hello/a`, or if `hello` doesn't exist, fails with `error: unable to open output directory 'hello': FileNotFound`
=> Properly handle --name with folder separators

lib/compiler_rt/emutls.zig
Commit f14cc75 accidentally added a const when grepping for assignments to `std.builtin.Type.StructField.default_value`, however when looking into it further, I noticed that even though this default_value field is emitted into the `.data` section, the value it points to is actually emitted into the `.rodata` section, so it seems correct to use const here.
Fixes https://github.com/ziglang/zig/pull/12975#issuecomment-1279956048
=> emutls: add const to default_value field

src/codegen/llvm.zig, src/type.zig, src/value.zig, tools/stage2_gdb_pretty_printers.py, tools/stage2_lldb_pretty_printers.py, tools/stage2_pretty_printers_common.py
Extracted the finished features from a local branch so that they aren't blocked by the other features.
* Fix untagged struct names in debug info for llvm.
* Factor out common stage2 pretty printer data.
* Add lldb version of stage2 pretty printers.
=> tools: add lldb stage2 pretty printers

src/AstGen.zig, src/Sema.zig, src/Zir.zig, src/print_zir.zig
It is not yet determined whether the Zig language will land on text-based string concatenation for inline assembly, as Zig 0.9.1 allows, and as this commit allows, or whether it will introduce a new assembly syntax more integrated with the rest of the language. Until this decision is made, this commit relaxes the restriction which was preventing inline assembly expressions from using comptime expressions for the assembly source code.
=> stage2: allow comptime expressions for inline asm

lib/c.zig, lib/compiler_rt.zig, lib/compiler_rt/bcmp.zig, lib/compiler_rt/memcmp.zig, lib/compiler_rt/memcpy.zig, lib/compiler_rt/memmove.zig, lib/compiler_rt/memset.zig, test/link/wasm/archive/build.zig
This moves functions that LLVM generates calls to, to the compiler_rt implementation itself, rather than c.zig.
This is a prerequisite for native backends to link with compiler-rt and also allows native backends to generate calls to `memcpy` and the like.
=> compiler_rt: Move mem implementations from c.zig

lib/std/Thread/RwLock.zig
=> Fix for #13163: DefaultRwLock accumulates write-waiters, eventually fails to write lock

lib/std/debug.zig
tracing down an `error: else prong required when switching on type 'anyerror'` error while using some `std.debug` functions and thought this might be a lead. generally better for the stdlib to not use `anyerror`
=> std.debug: define error set in DebugInfo.lookupModuleDl

src/value.zig, test/behavior/bitcast.zig
Hopefully this implementation is correct. I'll happily add some tests given some hints on how/where to add tests for comptime evaluation.
=> stage2: implement packedStuctToInt for more types

src/value.zig, test/behavior/generics.zig
* Support comparison between implicitly casted array pointer and slice.
* Support comparison between slices with different value tags.
Closes #12700
=> value: implement `Value.eqlAdvanced` on slices

lib/docs/main.js
related issue: #12759
Hi! I was looking for a way to familiarize myself a bit more with Zig, and having previously poked with autodoc a bit a month or two ago, I figured I'd grab this quick one-liner to carry forward `[src]` links on function declaration docs pages.
Here's the result:
Which links to this page:
---
I do have a couple questions concerning development on autodoc in general not specific to this PR, and happy to move these to issues/discussions if this isn't the appropriate spot for questions:
1. I'm struggling a bit to understand the development flow of `index.html` and `main.js`. From my reading of [the docs](https://github.com/ziglang/zig/wiki/How-to-contribute-to-Autodoc), I should be able to edit either of these files, run `zig build-obj -femit-docs <file>.zig`, and it …
=> Add [src] links to function decls in autodocs

src/main.zig
I did not fully wire it up in main.zig when I originally implemented `-z nocopyreloc` in #11679 (440f5249f1a). Finish it.
If we strictly follow the rules, we should bump the cache version, since the field was technically added only now. But since nobody complained thus far, I don't think many users care that much about it and we can omit it.
=> [elf] main.zig: add -z nocopyreloc

lib/std/fs.zig
Currenty copy_file_range always uses at least two syscalls:
1. As many as it needs to do the initial copy (always 1 during my
testing)
2. The last one is always when offset is the size of the file.
The second syscall is used to detect the terminating condition. However,
because we do a stat for other reasons, we know the size of the file,
and we can skip the syscall.
Sparse files: since copy_file_range expands holes of sparse files, I
conclude that this layer was not intended to work with sparse files. In
other words, this commit does not make it worse for sparse file society.
Test program
------------
const arg1 = std.mem.span(std.os.argv[1]);
const arg2 = std.mem.span(std.os.argv[2]);
try std.fs.cwd().copyFile(arg1, std.fs.cwd(), arg2, …
=> os.copy_file_range: save a syscall for most operations

lib/std/build/CheckObjectStep.zig, test/link/macho/dead_strip/build.zig, test/link/macho/dylib/build.zig, test/link/macho/entry/build.zig, test/link/macho/needed_library/build.zig, test/link/macho/search_strategy/build.zig, test/link/macho/stack_size/build.zig, test/link/macho/weak_library/build.zig
When creating an `EmulatableRunStep`, it now correctly depends on its own step rather than only the executable that was created. This means we do not need to add extra `dependOn` statements on both the emulatable step as well as the check object step. Thanks to @jacobly0 for finding this bug.
=> std: CheckObject - correctly depend on its own step when creating an EmulatableRunStep

src/Compilation.zig, src/test.zig
Probably at some point after the if statement was added, ttyconf.setColor was refactored to internally be a noop if ttyconf == .no_color, so this whole condition is now unnecessary, as far as I can tell.
=> Fix #12091: Error message with TERM=dumb is missing info

lib/std/crypto/benchmark.zig
Recently in my latest tests there has been an error with "testing.allocator".
```bash
error: Cannot use testing allocator outside of test block
@compileError("Cannot use testing allocator outside of test block");
```
cc: @jedisct1
=> crypto/benchmark - replace testing allocator

lib/std/os/uefi/tables/boot_services.zig
This makes possible to query the memory map size from EFI firmware without making any allocation beforehand. This makes possible to be precise about the size of the allocation which will own a copy of the memory map from the UEFI application.
=> UEFI: Querying memory map size with no allocation

lib/compiler_rt/common.zig, lib/compiler_rt/emutls.zig, lib/std/c/linux.zig
- Exports `__emutls_get_address` for android abi
- Defines `_pthread_key_t` on linux only for android abi
- Sets `want_eabi` to true for android abi
=> Support compiling for the android NDK

lib/std/builtin.zig, lib/std/debug.zig, lib/test_runner.zig, src/Air.zig, src/AstGen.zig, src/Liveness.zig, src/Module.zig, src/Sema.zig, src/Zir.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/print_air.zig, src/print_zir.zig, src/value.zig, test/behavior/bugs/12891.zig, test/behavior/error.zig, test/behavior/eval.zig, test/stack_traces.zig
This implements the (unapproved) error handling behavior described in https://github.com/ziglang/zig/issues/1923#issuecomment-1218495574.
The result is a basic ownership-style algorithm for errors. Barring any bugs (🤞), it should guarantee that error return frames follow a strict stack discipline, which we need to correctly accumulate them in a single stack-per-thread.
Error return traces "live" when:
- stored in a `const` variable
- handled in a `catch { ... }` or `else |err| { ... }` block
- propagated to caller via `return` or `try`
- passed to a function as an argument
Error return traces are killed when:
- stored in a mutable `var`
- leaving a `catch` or `else |err|` block with a non-error value
- the `const` variable associated with an error trace falls out of scope
- a function …
=> stage2: Pop error trace frames for handled errors (#1923)

lib/compiler_rt.zig
`cmp.zig` was accidently being referenced twice, rather than importing `memcmp.zig`.
=> compiler-rt: import memcmp.zig instead of importing cmp.zig twice

lib/compiler_rt/README.md
This documents status of routines and adds the next work item "Decimal float library routines", which are only recommended for binary data. Complete absence of tests is also documented. This does not document the various aliases, e.g. those for ARM.
Missing Integer library routines:
- __addvsi3
- __addvdi3
- __addvti3
- __addvdi3
- __addvti3
- __subvsi3
- __subvdi3
- __subvti3
- __subvdi3
- __subvti3
- __mulvsi3
- __mulvdi3
- __mulvti3
- __mulvdi3
- __mulvti3
Missing floating library routines:
- __powisf2
- __powidf2
- __powitf2
- __powixf2
Missing routines for symbol-level compatibility to gcc:
- __ashlsi3
- __ashrsi3
- __lshrsi3
=> update compiler_rt README and prettify it

CMakeLists.txt, src/stage1/config.h.in
CMake recognizes the CMAKE_PREFIX_PATH environment variable for some things, and also the CMAKE_PREFIX_PATH cache variable for other things. However, it does not relate these two things, i.e. if the environment variable is set, CMake does not populate the cache variable in a corresponding manner. Some package systems, such as Homebrew, set the environment variable but not the cache variable. Furthermore, the environment variable follows the system path separator, such as ':' on POSIX and ';' on Windows, but the cache variable follows CMake's array behavior, i.e. always ';' for a separator.
Closes #13242
=> CMake: detect use of CMAKE_PREFIX_PATH env var

src/link/MachO.zig, src/link/MachO/CodeSignature.zig, src/link/MachO/zld.zig
...when computing the adhoc code signature.
I tried testing this on the self-hosted compiler to find out if it's faster, but I got this:
```
MachO Flush... error(link): incomplete symbol table: expected symbol table of length 0x61020000
```
but when I tried master branch as a control group, I also got the same error. Here are the steps to reproduce:
```
$ make install
$ stage3/bin/zig build -p stage4-release -Dskip-install-lib-files -Drelease -Denable-llvm
$ stage4-release/bin/zig build -p stage4-macos -Dtarget=aarch64-macos --search-prefix ~/dev/bootstrap-zig/out/aarch64-macos-none-apple_a14 -Denable-llvm
error(link): incomplete symbol table: expected symbol table of length 0x61020000
error: MalformedArchive
```
=> link.MachO: multi-thread first round of sha256 hashing

build.zig, src/config.zig.in, src/link.zig
This option can be used to produce a C backend build of the self-hosted compiler, which only has the C backend enabled. Once the C backend is capable of self-hosting, this will be a way for us to replace our stage1 codebase with a C backend build of self-hosted, which we can then use for bootstrapping. See #5246 for more details.
Using this option right now results in a crash because the C backend is not yet passing all the behavior tests.
=> build: add `-Donly-c` option

src/link.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/MachO.zig, src/link/MachO/dead_strip.zig, src/link/MachO/zld.zig, src/link/NvPtx.zig, src/link/Plan9.zig, src/link/SpirV.zig, src/link/Wasm.zig
This makes it easier to understand how control flow should happen in various cases; already just by doing this it is revealed that UndefinedSymbol and UndefinedSymbolReference should be merged, and that MissingMainEntrypoint should be removed in favor of the ErrorFlags mechanism thath we already have for missing the main entrypoint.
The main motivation for this change, however, is preventing a compile error when there is conditional compilation inside linker implementations, causing the flush() error set to depend on compilation options. With this change, the error set is fixed, and, notably, the `-Donly-c` flag no longer has compilation errors due to this error set.
=> link: add an explicit error set for flush() and flushModule()

lib/std/fmt.zig
These ifs were missing a case for f80 which should have shifted by one, but we can just compute the correct value instead.  Also, we want the fractional bits to be a multiple of four, not the mantissa bits, since the mantissa could have a leading one which we want to be separated.
=> fmt: fix `f80` hex formatting

lib/std/build/CheckObjectStep.zig, src/link.zig, src/link/Wasm.zig, src/link/Wasm/types.zig, test/link.zig, test/link/wasm/basic-features/build.zig, test/link/wasm/basic-features/main.zig, test/link/wasm/infer-features/build.zig, test/link/wasm/infer-features/foo.c, test/link/wasm/infer-features/main.zig
Wasm object files and binaries can contain an optional section called the `target_features` section. This section describes features that are used, required, or disallowed. This PR implements the validation of each linked object file and its features to ensure the generated binary is compatible. For example, when object A uses the feature 'atomics' but object B disallows the feature 'atomics' it's a linker error. Only when the user has specified features or any of the linked object files do, will we emit this section. As it's optional, it's omitted when providing the `-fstrip` flag. When the user did not specify any features, we instead infer them from any of the linked object files. For the curious reader, more information can be found at: …
=> wasm-linker: feature compatibility validation

src/Compilation.zig, test/standalone.zig
I copy/pasted what was done in `std.build.LibExeObjStep.make()` for `zig build-exe` to create a .rsp file for `zig clang`.
Maybe it's good enough for now?
Let me know if I need to improve anything.
closes #12419
=> make a .rsp file for `zig clang`

src/libcxx.zig
This definition communicates to libcxxabi that the libc will provide the `__cxa_thread_atexit_impl` symbol. This is true for glibc but not true for other libcs, such as musl.
Fixes building zig with `-Dtracy`.
=> libcxx: only pass -DHAVE___CXA_THREAD_ATEXIT_IMPL for glibc

lib/std/crypto/25519/ed25519.zig, lib/std/crypto/25519/x25519.zig, lib/std/crypto/benchmark.zig
This is a breaking API change, to make the ed25519 API similiar to the one used for ECDSA, and for future signature systems.
The ed25519 API was difficult to extend. In particular, adding multiple encodings for keys would have been ugly.
Instead of raw bytes, keys are now represented as `PublicKey` and `SecretKey` types, and signatures as the `Signature` type.
This is consistent with the ECDSA API, and, overall, makes everything much cleaner.
Signature creation and non-batch verification also got a little bit faster with the removal of an unneeded serialization.
Blind key signatures now directly reuse the regular signature code instead of duplicating it just to use a different way to compute the prefix.
In addition, support for incremental signatures has been added. Very large messages …
=> Revamp the ed25519 API

src/Sema.zig, src/TypedValue.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/value.zig, test/behavior/bugs/13164.zig, test/behavior/vector.zig
Makes the inline version of #13279 pass
=> Sema: use `runtime_value` instead of creating allocs

lib/std/fs/wasi.zig, lib/std/x/net/bpf.zig, src/Sema.zig, test/behavior/packed-struct.zig, test/cases/compile_errors/stage2/tuple_ptr_to_mut_slice.zig
Closes #12821.
~~Also adds quick fix for seeming misuse of `pointerDecl`, should be audited at some point. This is just so that the CI passes.~~
Note: stage1 still does this.
Co-authored-by: topolarity [topolarity@tapscott.me](mailto:topolarity@tapscott.me)
=> Sema: Prevent coercion from tuple pointer to mutable slice

lib/compiler_rt/memcmp.zig
See the new test case - this fails in the previous implementation.
See #13303
https://godbolt.org/z/v4bM16drq
=> compiler_rt: fix memcmp wrong for some inputs

lib/std/crypto/ecdsa.zig
Similar to what was done for EdDSA, allow incremental creation and verification of ECDSA signatures.
Doing so for ECDSA is trivial, and can be useful for TLS as well as the future package manager.
=> std.crypto.sign.ecdsa: add support for incremental signatures

lib/std/zig/c_translation.zig, src/translate_c.zig, src/translate_c/ast.zig, test/behavior/translate_c_macros.h, test/behavior/translate_c_macros.zig
Perform C-style arithmetic conversions on operands to division operator in macros
Closes #13162
=> translate-c: Better support for division in macros

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig, lib/std/mem.zig, src/Sema.zig, src/codegen.zig, src/value.zig, test/behavior/bitcast.zig
Packed memory has a well-defined layout that doesn't require actually using a BigInt to read from. Let's use it :-)
Included changes:
- Adds `readPackedInt`, `writePackedInt` and friends to `std.mem`
- Adds support for casting to packed enums and vectors 
- (follow-up to #13124)
- Fixes bitcasting to/from vectors outside of a packed struct
- Adds a fast path for bitcasting <= u/i64
- Fixes bug when bitcasting f80 which would clear following fields
=> Introduce `std.mem.readPackedInt` and improve bitcasting of packed memory layouts

lib/std/crypto/sha2.zig
There's probably plenty of room to optimize these further in the future, but for the moment this gives ~5-6x improvement on x86-64, and ~10x on M1 AArch64 Macs.
These extensions are very new. Most Intel processors prior to 2020 do not support them. AMD has supported them since Ryzen.
P.S. @kubkon I haven't fixed the CPU features for LLVM in stage2 yet, but at least this gives you something to play with until that's sorted 🙂
=> crypto.sha2: Use intrinsics for SHA-256 on x86-64 and AArch64

ci/srht/freebsd_script, src/glibc.zig, src/print_targets.zig
Before, the code for building glibc stubs used a special case of the Cache API that did not add any file inputs, and did not use writeManifest(). This is not really how the Cache API is designed to work and it shows because there was a race condition.
This commit adds as an input file the abilists file that comes with Zig's installation, which has the added benefit of making glibc stub caching properly detect cache invalidation when the user decides to overwrite their abilists file. This harmonizes with the rest of how Zig works, which intentionally allows you to hack the installation files and have it behave properly with the cache system.
Finally, because of having any file inputs, the normal API flow of the Cache system can be used, eliminating the one place that used the Cache API in …
=> glibc: fix race condition when building stubs

lib/std/c/darwin.zig, lib/std/c/dragonfly.zig, lib/std/c/haiku.zig, lib/std/fs.zig, lib/std/fs/test.zig, lib/std/os/windows.zig
Before this PR, the added test would have failed on Windows with the error found in https://github.com/ziglang/zig/issues/8268.
Fixes #8268.
=> Windows: Fix Iterator name buffer size not handling all possible file name components

src/link/MachO/Object.zig, src/link/MachO/ZldAtom.zig, src/link/MachO/dead_strip.zig, src/link/MachO/zld.zig
Prior to this patch, we would unnecessarily spin in `markLive` routine when dead stripping due to inability to handle target atoms described by hard-coded offsets wrt to the source relocatable object file (i.e., `r_extern == 0` which normally occurs `X86_64_RELOC_UNSIGNED` and `X86_64_RELOC_SIGNED`). This is now fixed by caching sorted source symbols by address per object and finding the containing atom of this type of relocation, and marking it live.
With this patch, macOS users on `x86_64` can now experience comparable performance as `aarch64` users. Some numbers run against standalone `zld` linking `stage3`. The link time of `stage3` with dead stripping has now been reduced by 1 second making `zld` just 1.40x slower than `lld` and faster than `ld64`:
```
❯ hyperfine ./zld ./lld ./ld64 …
```
=> macho: fix performance regression for x86_64 and -dead_strip

lib/docs/main.js
related issue: https://github.com/ziglang/zig/issues/12759
This PR makes a couple changes, open to feedback!
1. Fixes the broken "double-links" that were introduced in https://github.com/ziglang/zig/pull/13120 (see also https://github.com/ziglang/zig/pull/13237, which we should close if this is merged)
2. Adds links to source code directly in to the function name rather than a separate `[src]` button on the right side of the page. I chose this because when you have a long function declaration, the `[src]` link takes up precious real estate, so hopefully this avoid some cases where you might get a `...` on your function declaration, which obscures the info I'm looking for.
3. Opens source links in new tabs (this is a better experience IMO)
Here is a page of the list of functions in a …
=> Better Autodoc Src File Links

lib/std/os.zig, lib/std/os/uefi.zig, lib/std/os/uefi/protocols.zig, lib/std/os/uefi/protocols/absolute_pointer_protocol.zig, lib/std/os/uefi/protocols/device_path_protocol.zig, lib/std/os/uefi/protocols/edid_override_protocol.zig, lib/std/os/uefi/protocols/hii.zig, lib/std/os/uefi/protocols/simple_network_protocol.zig, lib/std/os/uefi/protocols/simple_text_input_ex_protocol.zig, lib/std/os/uefi/tables.zig, lib/std/os/uefi/tables/boot_services.zig, lib/std/os/uefi/tables/runtime_services.zig
* device_path_protocol now uses extern structs with align(1) fields because
the transition to integer backed packed struct broke alignment
* added comptime asserts that device_path_protocol structs do not violate
alignment and size specifications
=> change uefi packed structs to new integer backed syntax

src/AstGen.zig, src/Sema.zig, test/behavior/basic.zig, test/behavior/bit_shifting.zig, test/behavior/bugs/6456.zig, test/behavior/optional.zig, test/behavior/pointers.zig, test/behavior/slice.zig, test/behavior/translate_c_macros.zig, test/behavior/typename.zig
This PR fixes a Zir issue where a value defined in an inner scope is accessed from an outer scope.  This does not cause issues with most of the backends since they do not do any scope verification, and asm and LLVM IR are flat.  However, with the C backend, this triggers C compile errors since the a local gets defined in an inner C scope, and the C compiler actually checks for proper scoping.  This could also have been fixed by declaring all locals at the top of the function, but it seems reasonable for Zir to respect proper scoping.
* Change the Zir generated by while expressions to respect scoping.
* Fix Sema crash when not breaking to the outermost inline block, which was revealed by the previous change.
* With these changes the C backend is passing 92% (1259/1374) of the behavior …
=> AstGen: avoid access to capture defined in an inner scope from a continue expression

src/Sema.zig, src/stage1/all_types.hpp, src/stage1/astgen.cpp, src/stage1/ir.cpp, test/behavior/eval.zig
Allows code like this to compile:
```zig
fn foo() bool {
const stdout = std.io.getStdOut().writer();
stdout.print("i = {}\n", .{i}) catch unreachable;
return true;
}
if (false and foo()) { // This works already today
@compileError("Condition should be comptime-false");
}
i += 1;
if (foo() and false) { // PR allows this condition to be comptime-known
@compileError("Condition should be comptime-false");
}
}
```
outputs:
```console
$ ./build/stage3/bin/zig run test.zig
i = 1
```
Note that side effects are still respected, but the result can be comptime-known despite them. This is the same way we handle, e.g. `x * 0` and `0 * x`.
Closes #6768.
=> Make `x and false` and `x or true` comptime-known

src/Sema.zig
Depending on how #13366 is resolved, this code should arguably have been rejected with a compile error in the first place.
Closes #13362.
=> stage2: Add explicit type to workaround #13366

lib/include/zig.h, lib/std/start.zig, lib/test_runner.zig, src/codegen/c.zig, test/behavior/atomics.zig, test/tests.zig
* Fix `_start` on aarch64.
* Add fallbacks for unsupported float types.
Fixes #13357
=> cbe: improve support for non-native float types

src/codegen/llvm.zig
=> stage2 llvm: Respect alignment for `.union_init`

src/codegen/llvm.zig, test/link.zig, test/link/wasm/extern-mangle/a.zig, test/link/wasm/extern-mangle/b.zig, test/link/wasm/extern-mangle/build.zig, test/link/wasm/extern-mangle/lib.zig
When Wasm extern functions contain the same name but have a different module name such as `extern "a"` vs `extern "b"` LLVM backend will currently resolve the two functions to the same symbol. By mangling the name of the symbol, we ensure the functions are resolved separately. We mangle the name by applying `<name>|<module>` where `module` is also known as the library name.
Closes #12880 
Sorry, this wasn't part of the 0.10.0 release, but this should at least make it available in 0.10.1
=> llvm: mangle extern function names for Wasm target

build.zig, lib/include/zig.h, lib/std/build.zig, lib/std/crypto/blake3.zig, lib/std/crypto/gimli.zig, lib/std/multi_array_list.zig, lib/std/target.zig, lib/std/zig/system/x86.zig, src/codegen/c.zig, test/behavior/basic.zig, test/behavior/bugs/11139.zig, test/behavior/bugs/1851.zig, test/behavior/bugs/7250.zig, test/behavior/cast.zig, test/behavior/fn.zig, test/behavior/if.zig, test/behavior/type.zig, test/tests.zig
=> cbe: enough fixes for `-Donly-c` to be able to produce an executable

src/type.zig
On platforms where `c_longdouble` is 128-bits, we probably want `f128` and `c_longdouble` to match.
I intended to make this change as part of #13257, but missed this piece.
Supersedes #13392.
=> stage2: Ensure f128 alignment matches c_longdouble alignment

lib/std/time.zig
Add the microTimestamp function to get the time since epoch in microseconds.  Complements the existing nanoTimestamp, milliTimestamp, and timestamp functions.
=> std.time: add microTimestamp()

lib/include/zig.h, src/codegen/c.zig, test/behavior/union.zig, test/stage2/cbe.zig
The bootstrapping steps I followed:
```sh
mkdir stage1
cp lib/include/zig.h stage1
zig build -p only-c -Donly-c -Dno-lib
cat only-c/bin/zig.c > stage1/zig1.c
zig build-obj -ofmt=c lib/compiler_rt.zig -femit-bin=stage1/compiler_rt.c
clang -Istage1 -fbracket-depth=512 stage1/compiler_rt.c stage1/zig1.c -o stage1/zig1 -Wl,-z,stack-size=0x10000000
cat > stage1/options.zig <<DONE
pub const mem_leak_frames: u32 = 4;
pub const skip_non_native: bool = false;
pub const have_llvm: bool = false;
pub const llvm_has_m68k: bool = false;
pub const llvm_has_csky: bool = false;
pub const llvm_has_arc: bool = false;
pub const force_gpa: bool = false;
pub const only_c: bool = false;
pub const version: [:0]const u8 = "0.11.0-dev.stage1";
pub const semver: @import("std").SemanticVersion = .{
.major = 0, …
```
=> cbe: enough fixes to bootstrap a compiler with a working c backend

lib/std/crypto/bcrypt.zig
std/crypto/benchmark.zig results:
* Intel i5
```
before: 3.144 s/ops
after: 1.922 s/ops
```
* Apple M1
```
before: 2.067 s/ops
after: 1.373 s/ops
```
=> std.crypto.pwhash.bcrypt: inline the Feistel network function

lib/std/fs/path.zig
This adds a function to `std.fs.path` returning the stem of the given path. I think this is a worthwhile addition in the long term. It's a pretty common function for a standard library. And I hope there isn't already some other really easy way to do this. I don't think there is.
I needed this today when I wanted to append a file name and change its file extension, like this:
```zig
thisDir() ++ "/" ++ stem(path) ++ ".ext",
```
See here for how other standard libraries do this:
* https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.stem
* https://crystal-lang.org/api/1.6.0/Path.html#stem%3AString-instance-method
* https://doc.rust-lang.org/std/path/struct.Path.html#method.file_stem
This also kind of goes in hand with the already existing `std.fs.path.extension()` above this.
=> std.fs.path: add stem()

src/Module.zig, src/Sema.zig
Empirically, this `AutoHashMapUnmanaged` &rightarrow; `AutoArrayHashMapUnmanaged` change fixes all non-determinism in `ReleaseFast` build artifacts.
```sh
1732720 4927ca68d53191842ffa265204c1782b1dcb18aa80955faa04342464b17371aeb63594e0316a59d0cafd23cba9f8f948a9c5834d9006cc79d8dd2e3393b436b8  build/zig1
57433840 9d88d1b4c33864f668a6497b8c0655d64fd06a6c80cd055a8d699f4bc2912914c140a14285182e726d9af49d296bd26971f63ffb005ac5bd398be7a5ba1cbf6b  build/zig2
11641624 b00c4af28c71d1e8b757e6e0dab3f35173f26db62c6916ede91364d00507b8abf1ce5d18a88e3c9dccffc2133f41d641fa4feba6ef832a76bb95997e63298e20  build/stage3/bin/zig
61163904 063d7dde32a9f0f141cff60359039fedc75bcee52b16507c91656e43bff774c0e028c564302ae73fa9bedf4c20cc792a2d91235e980a5d073b49b28b2580be18  det1/bin/zig
61163904 …
```
=> Sema: make `InferredErrorSet` deterministic

src/Sema.zig, test/behavior.zig, test/behavior/bugs/13435.zig
This commit mirrors 930f904aaa7d591d86a8c3216526711be95fcc17. This is my first time contributing to the stage2 compiler, so let me know if I'm misunderstanding anything.
Closes #13435
=> Sema: resolve lazy align in zirReify for union fields

lib/std/c/freebsd.zig, lib/std/os.zig, src/link.zig
=> std.os: take advantage of the freebsd's `copy_file_range`

src/link/MachO/Dylib.zig, src/link/tapi.zig, test/link.zig, test/link/macho/bugs/13056/build.zig, test/link/macho/bugs/13056/test.cpp
However, we will treat them as standard imports rather than refs to weak imports until I investigate more how it actually works underneath.
Fixes #13056 
cc @topolarity 
```
$ cat test.cpp                                                                                             
// test.cpp
#include <new>
#include <cstdio>
int main() {
int *x = new int;
*x = 5;
fprintf(stderr, "x: %d\n", *x);
delete x;
}
$ ../../zig/build/stage3/bin/zig c++ test.cpp $(xcrun --show-sdk-path)/usr/lib/libc++.tbd -nostdlib++ -nostdinc++ -I $(xcrun --show-sdk-path)/usr/include -I $(xcrun --show-sdk-path)/usr/include/c++/v1
$ ./a.out …
```
=> macho: parse weak imports in tbd descriptors

lib/std/crypto.zig, lib/std/crypto/salsa20.zig
...instead of hard-coding it to 20.
- This is consistent with the ChaCha implementation
- NaCl and libsodium, that this API is designed to interop with, also support 8 and 12 round variants. The 12 round variant, in particular, provides the same security level as the 20 round variant, but is obviously faster.
- scrypt currently uses its own non optimized version of Salsa, just because it use 8 rounds instead of 20. This will help remove code duplication.
No behavior nor public API changes. The Salsa20 and XSalsa20 still represent the 20-round variant.
=> crypto.salsa20: make the number of rounds a comptime parameter

lib/std/crypto/aes/aesni.zig, lib/std/crypto/aes/armcrypto.zig
At least on Apple Silicon, this is slightly faster than 8 blocks.
=> crypto.core.aes: process 6 block in parallel instead of 8 on aarch64

lib/std/crypto/ghash.zig
Aggregated reduction requires 5 additional multiplications (to precompute the powers of H), in order to save 2 multiplications per batch.
So, only use large batches when it's actually interesting to do so.
For the last blocks, reuse the precomputations in order to perform a single reduction.
Also, even in .ReleaseSmall, allow 2-block aggregation. The speedup is worth it, and the code increase is reasonable.
And in .ReleaseFast, bump the upper batch size up to 16.
Leverage comptime by the way instead of duplicating code.
std/crypto/benchmark.zig on Apple M1:
Zig 0.10.0: 2769 MiB/s
Before: 6014 MiB/s
After: 7334 MiB/s
=> std.crypto: make ghash faster, esp. for small messages

lib/std/os/linux/bpf/btf.zig
- the meaning of packed structs changed in zig 0.10. adjust accordingly. Use "extern struct" for the cases that directly map to C structs.
- Add new type info kinds, like enum64 and DeclTag
- change the Type enum to use the canonical names from libbpf. This is more predictable when comparing with external BPF documentation (than invented synonyms that need to be guessed)
cc @mattnite
=> Fixes to linux/bpf/btf.zig

lib/std/c/darwin.zig, lib/std/c/dragonfly.zig, lib/std/c/freebsd.zig, lib/std/c/haiku.zig, lib/std/c/netbsd.zig, lib/std/c/openbsd.zig, lib/std/c/solaris.zig, lib/std/os/linux.zig, lib/std/os/test.zig
This fix (proposed independently by @Vexu here (https://github.com/ziglang/zig/issues/13216#issuecomment-1282297305) and @marler8997 here (https://github.com/marler8997/ziglibc/pull/3#issuecomment-1294881409) allows one to pass `os.SIG.IGN` or other non-pointer aligned values for the `handler_fn` on word-aligned architectures like aarch64.
The PR is two separate commits simply because this is my first PR to zig and I wanted to make sure that the CI picks up the failing case first and will be fixed w/ the 2nd commit, IMO the PR can be squashed before merging.
I added the `align(1)` to all the `lib/std/c` implementations, even the ones like dragonfly that only (currently) target x86 for consistency but am happy to remove those changes if preferred.
Fixes #13216.
=> std.os: fix alignment of Sigaction.handler_fn

lib/std/crypto/ghash.zig
These constants were read as a block count in `initForBlockCount()` but at the same time, as a size in `update()`.
The unit could be blocks or bytes, but we should use the same one everywhere.
So, use blocks as intended.
Fixes #13506
=> crypto.ghash: define aggregate tresholds as blocks, not bytes

src/Sema.zig, src/value.zig
* Add `tagName` to `Value` which behaves like `@tagName`.
* Add `hashUncoerced` to `Value` as an alternative to hash when we want to produce the same hash for values that can coerce to each other.
* Hash `owner_decl` instead of `module_fn` in `Sema.instantiateGenericCall` since `Module.Decl.Index` is not affected by ASLR like `*Module.Fn` was, and also because `GenericCallAdapter.eql` was already doing this.
* Use `Value.hashUncoerced` in `Sema.instantiateGenericCall` because `GenericCallAdapter.eql` uses `Value.eqlAdvanced` to compare args, which ignores coersions.
* Add revealed missing cases to `Value.eqlAdvanced`.
Without these changes, we were breaking the hash contract for `monomorphed_funcs`, and were generating different hashes for values that compared equal.  This resulted in a …
=> Sema: avoid breaking hash contract when instantiating generic functions

src/RangeSet.zig, src/Sema.zig, src/codegen/llvm.zig, src/type.zig, src/value.zig, test/behavior.zig, test/behavior/bugs/12043.zig, test/behavior/bugs/13063.zig, test/behavior/bugs/13064.zig, test/behavior/bugs/13065.zig, test/behavior/bugs/13069.zig, test/behavior/vector.zig
- [Sema] Changes array initialization to scan for stores the same way struct init does
- [Sema/Value] Renames `compare` (and family) to `compareAll` (etc.), and fixes lots of places where the wrong predicate for vectors was used
- [Sema] If vector arithmetic yields a compile-time-known constant, make sure it's a vector
- ~~[Liveness] Add a peephole optimization for safety checks to Liveness, for copy/load elision~~
- [LLVM] Fix up load elision to account for "byref pass-through" consumers like `.array_elem_val`, etc. which do not make copies
P.S. As @Vexu pointed out to me, we still need a way to ensure that if, e.g., `foo.arr[x][y].z` performs a copy, it only copies the target object rather than all of foo. This is (usually) handled correctly already when the result is a non-by-ref type, …
=> stage2: Miscellaneous fixes to vector arithmetic and copy elision 

src/codegen/llvm.zig, test/behavior/asm.zig
These are supported using `%[ident:mod]` syntax.
This allows requesting, e.g., the "w" (32-bit) vs. "x" (64-bit) views of AArch64 registers.
See https://llvm.org/docs/LangRef.html#asm-template-argument-modifiers
=> stage2: Support modifiers in inline asm

doc/langref.html.in
Fixes #13449 
My take is there's no great place for this definition in the current doc structure. Each existing section is dedicated to a concrete topic which teaches you how to use Zig, but "container" is an abstraction used to group struct, enum, etc.
But I do think it should be defined if used, so I added an Appendix. Using the above thinking, I believe **Grammar** and **Zen** also belong here. It's somewhat arbitrary, though.
Alternatives:
- Just put a one-liner under "Container Level Variables", though this is not where the term is first used in the doc.
- Give it a top-level section, though I think that gives the term too much weight.
- Make a glossary instead of an appendix, though it might be lonely.
- Save it for the language spec.
=> langref: add appendix and explain 'container' terminology

lib/std/SemanticVersion.zig, lib/std/build/CheckObjectStep.zig, lib/std/builtin.zig, lib/std/debug.zig, lib/std/fmt.zig, lib/std/fs/wasi.zig, lib/std/heap/general_purpose_allocator.zig, lib/std/math/big/int.zig, lib/std/net.zig, lib/std/os/uefi.zig, lib/std/target.zig, lib/std/testing.zig, lib/std/wasm.zig, lib/std/x/net/bpf.zig, lib/std/x/net/ip.zig, lib/std/x/os/net.zig, lib/std/x/os/socket.zig, src/main.zig
- Renames `invalidFmtErr()` to `invalidFmtError()` (for consistency; Zig seems to use `Error` more than `Err`).
- Makes `invalidFmtError` public, as suggested by @Vexu in https://github.com/ziglang/zig/pull/13489.
- Uses `invalidFmtError` in place of `@compileError` when bailing due to bad format strings.
Goals are to:
- Reduce use of custom strings to give more consistent format errors.
- Give users info about the type of the value they formatted incorrectly to help them find and fix it.
- Make `invalidFmtError` the standard way of reporting bad format strings in Zig and for users.
```zig
const builtin = @import("builtin");
const Guid = std.os.uefi.Guid;
std.debug.print("{s}", .{builtin.zig_version});
const guid = Guid{
.time_low = …
```
=> Make invalidFmtError public and use in place of compileErrors for bad format strings

src/Module.zig, src/Sema.zig, src/type.zig, src/value.zig
These parameters are only ever needed when `std.builtin` is out of sync with the compiler in which case panicking is the only valid operation anyways. Removing them causes a domino effect of functions no longer needing a `src` and/or a `block` parameter resulting in handling compilation errors where they are actually meaningful becoming simpler.
=> Sema: remove `block` and `src` parameters from `getBuiltin`

lib/std/crypto/ghash.zig
In the process of 'remaining blocks',
the length of processed message can be from 1 to 79. The value of 'n-1' is ranged from 0 to 3.
So, st.hx[i] must be initialized at least from st.hx[0] to st.hx[3]
=> std.crypto.ghash: fix uninitialized polynomial use

lib/std/os/linux.zig
Added setitimer and getitimer syscalls. This is my first contribution to the project so let me know if I need to change anything.
=> std.os.linux: Add setitimer and getitimer syscalls

lib/std/build/RunStep.zig
This would only fail to compile when building *on* WASI.
=> std.build.RunStep: fix typo

src/DepTokenizer.zig
closes #13539
This patch comes as a result of seeing various instances of invalid pathnames of various libc dependencies on windows. 
This kind of path hinted at the underlying issue. Note trailing `:` as **part** of pathname!
```
/msys64/what/zig-cache\tmp\48ac4d78dd531abd-cxa_thread_atexit.obj:
```
And it was obtained via DepTokenizer from a `.d` dependency file such as:
```
C:/msys64/what/zig-cache\tmp\48ac4d78dd531abd-cxa_thread_atexit.obj: \
C:/msys64/opt/zig3/lib/zig/libc/mingw/crt/cxa_thread_atexit.c
```
- the first token should be a `.target` and all the way up to last `:` before EOL
- instead `.target` was parsed as `C` and `.prereq` was `/msys64/what/zig-cache\tmp\48ac4d78dd531abd-cxa_thread_atexit.obj:`
The solve is to allow `DRIVE:/PATH` just as `DRIVE:\PATH` is allowed; this …
=> zig-cache: support windows drive + fwd-slash paths

lib/std/zig.zig, src/link/NvPtx.zig
Something changed in the builder a bit before 0.10.0, and Nvptx.zig is currently outputing files directly at the top level of zig-cache.
This change make it outputs .ptx files inside zig-cache/o/<hash>/
Could we merge this for 0.10.1 ?
=> fix Nvptx backend outputing files at the top level of zig-cache

lib/std/os/linux.zig
perf_event_attr.type needs to take a runtime defined value to enable
dynamic PMU:s, such as kprobe and uprobe. This value can exceed
predefined values defined in the linux headers.
reference: perf_event_open(2) man page
=> stdlib: make linux.PERF.TYPE non-exhaustive

doc/langref.html.in
The packed struct example was mistakenly applying endianness where it shouldn't have been.  This wasn't being caught because we don't currently test the examples on Big-endian systems.
I updated the test to remove the endianness where it didn't apply, and added a new part of the test to demonstrate when it would apply.
=> packed struct fix example and clarify least to most significant ordering

lib/std/crypto/ghash.zig
Carryless multiplication was slow on older Intel CPUs, justifying the need for using Karatsuba multiplication.
This is not the case any more; using 4 multiplications to multiply two 128-bit numbers is actually faster than 3 multiplications + shifts and additions.
This is also true on aarch64.
Keep using Karatsuba only when targeting x86 (granted, this is a bit of a brutal shortcut, we should really list all the CPU models that had a slow clmul instruction).
Also remove useless agg_2 treshold and restore the ability to precompute only H and H^2 in ReleaseSmall.
Finally, avoid using u256. Using 128-bit registers is actually faster.
=> std.crypto.onetimeauth.ghash: faster GHASH on modern CPUs

src/Compilation.zig
This should fix https://github.com/ziglang/zig/issues/8531 and https://github.com/ziglang/zig/issues/13549, which should fixup the CI for https://github.com/ziglang/zig/pull/13562 (which exposed this error).
There were three issues here:
- On x86, the name is mangled to `__tls_index`
- As per this comment (https://github.com/ziglang/zig/issues/8531#issuecomment-1272637732), the logic needs to happen even if we aren't linking libc. `_tls_index` is provided by `start_windows_tls.zig` in this case
- Don't do this if we're single-threaded, because `start_windows_tls.zig` won't be included
=> windows: _tls_index linker error fixes

lib/std/crypto/ghash.zig
The software emulation of the carryless multiplication instruction was not updated to handle the `.hi_lo` case.
=> Fix ghash optimization for wasm32-wasi

test/c_abi/cfuncs.c, test/c_abi/main.zig
I think I found a failing C abi test for Zig.
I'm not using the latest build, and I'd like my approach to be confirmed first.
But if it holds, I can share a hundred of those from https://github.com/gwenzek/llvm-test-suite/
@topolarity which expressed interest for this area of work.
=> failing C ABI test with double

lib/std/build.zig, src/Compilation.zig, src/main.zig, test/standalone.zig, test/standalone/test_runner_path/build.zig, test/standalone/test_runner_path/test.zig, test/standalone/test_runner_path/test_runner.zig
This PR adds the ability to specify a custom test runner via a new `--test-runner` CLI option, or the `std.build.Builder.test_runner_path` field. There are a few aspects I'm uncertain about:
- A custom test runner probably does not want it's stdout to be consumed by the build runner so that the stdout of running `zig build test-with-special-runner` is the stdout of the custom test runner.
+ The stdout of `.test` kind `LibObjExeStep` is consumed by the build runner, but looking through the code, I wasn't sure that this was needed for `.test` kind steps.
+ This can be worked around by using a `.test_exe` kind `LibObjExeStep` and its run step, rather than a `.test` kind `LibObjExeStep`, in order for the stdout of the test to go to the stdout of the build runner, but I think it would be nicer …
=> Custom test runner

lib/std/rand.zig
Should address #13247; this doesn't make `enumValue` or `shuffle` consistent across architectures, but it does allow one to use the alternative function to specify an integer with a bit width independent of the architecture.
Also added some simple comptime checks to `enumValue`*, to take advantage of some possible invariants.
=> std.Random: add functions with explicit index type

lib/std/array_list.zig
While it is already mentioned on the `items` attributes of the structs, it is interesting to comment in every method potentially invalidating pointers to items that they may do so. My thoughts are that it's the moment you're calling these methods that it is interesting to know you may have an impact on items pointers (I've been bitten by this...).
Please discard if you don't think that's a good idea.
=> std.array_list: add a comment on every methods potentially invalidating pointers.

test/behavior/floatop.zig
No functional change. Separates various float operations behavior tests from the ones that test vectors.
=> extract C backend behavior tests with vectors

src/Compilation.zig, src/link/Coff/lld.zig, src/link/Elf.zig, src/link/Wasm.zig
This fixes https://github.com/ziglang/zig/issues/13432 and https://github.com/ziglang/zig/issues/13235
There was no check for linker errors after flushing, which meant that if the link failed the build would continue, trying to copy the non-existent artifact, and also write the manifest as if it had succeeded.
I added `Compilation.lockAndParseLldStderr` to consume the stderr result of the lld call, and accumulate it in `lld_errors`. These errors are then surfaced via the same mechanism the other compilation errors are.
=> linker: fail the compilation if there were linker errors

src/arch/x86_64/abi.zig, src/codegen/llvm.zig, test/c_abi/main.zig
follow up on https://github.com/ziglang/zig/pull/13376
(note I originally copy pasted the wrong part of the IR...)
For the `C_C_D = extern struct { v1: i8, v2: i8, v3: f64 }` struct
Clang generates the following IR:
```
; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @assert_C_C_D(i64 %0, double %1) #0 !dbg !10 {
%3 = alloca %struct.C_C_D, align 8
%4 = alloca i32, align 4
%5 = getelementptr inbounds { i64, double }, ptr %3, i32 0, i32 0
store i64 %0, ptr %5, align 8
%6 = getelementptr inbounds { i64, double }, ptr %3, i32 0, i32 1
store double %1, ptr %6, align 8
```
Zig:
```
%struct.C_C_D = type { i8, i8, [6 x i8], double }
; Function Attrs: nounwind
define dso_local i32 @zig_assert_C_C_D(i64 %0, i64 %1) #0 !dbg !32 {
Entry:
%2 = alloca i32, align 4
%3 = alloca …
```
=> fix x86_64 C ABI

src/link/Coff/lld.zig
Closes #7484.
Right now for UEFI targets an alignment of 32 is being used for no reason other than support a rare bytecode. As this is far from the standard case, removing this alignment and using the default one, as most toolchains do, should be the desired behavior.
=> uefi: Delete unneeded alignment and use default 4K

lib/std/valgrind.zig, src/codegen/llvm.zig, src/target.zig
Tested locally on my aarch64 machine.
=> std: valgrind client request support for aarch64

src/AstGen.zig, test/stack_traces.zig
Thanks to @squeek502 for the bug report!
Resolves #13618.
=> AstGen: Pop error trace for `continue`

src/value.zig
This patch fixes #13615 for me. I have based it on what we do in `fn hash(...)`, however, I wasn't sure if we should also hash the slices length given that we are doing partial hashes as this is `fn hashUncoerced(...)` so I would definitely appreciate a thorough review.
cc @jacobly0
=> value: account for undef value for ptr in slice in hashUncoerced

lib/std/crypto.zig, lib/std/crypto/aegis.zig, lib/std/crypto/benchmark.zig
The Pelican-based authentication function of the AEGIS construction can be used independently from authenticated encryption, as a faster and more secure alternative to GHASH/POLYVAL/Poly1305.
We already expose GHASH, POLYVAL and Poly1305 for use outside AES-GCM and ChaChaPoly, so there are no reasons not to expose the MAC from AEGIS as well.
Like other 128-bit hash functions, finding a collision only requires ~2^64 attempts or inputs, which may still be acceptable for many practical applications.
Benchmark (Apple M1):
siphash128-1-3:       3222 MiB/s
ghash:       8682 MiB/s
aegis-128l mac:      12544 MiB/s
Benchmark (Zen 2):
siphash128-1-3:       4732 MiB/s
ghash:       5563 MiB/s
aegis-128l mac:      19270 MiB/s
=> std.crypto.auth: add AEGIS MAC

ci/linux/build-aarch64.sh, ci/linux/build-x86_64-debug.sh, ci/linux/build-x86_64-release.sh, ci/macos/build-aarch64.sh, ci/macos/build-x86_64.sh, ci/windows/build.ps1, lib/std/fs/path.zig, lib/std/fs/test.zig, lib/std/fs/wasi.zig, src/Cache.zig, src/Compilation.zig, src/glibc.zig, src/libcxx.zig, src/main.zig, src/mingw.zig
Before, cache manifest files would have absolute file paths. This is problematic for two reasons:
* Absolute file paths are not portable. Some operating systems such as WASI have trouble with them. The files themselves are less portable; they cannot be migrated from one user's home directory to another's. And finally they can break due to file paths exceeding maximum path component size.
* They would prevent some advanced use cases of Zig, where the lib dir has a different path in a different invocation but is ultimately the same Zig version and lib directory as before.
This commit adds a new column that specifies the prefix directory for each file. 0 is an escape hatch and has the previous behavior. The other two prefixes introduced are zig lib directory, and the cache directory. This …
=> Cache: introduce prefixes to manifests

lib/std/builtin.zig, src/Sema.zig
The TODO comment in safetyPanic mentions introducing the concept of reference-counted decls. That sounds like Zig current semantics for normal declarations. By placing the panic messages in builtin there is no need for another concept in the compiler.
=> Get panic messages from builtin instead of creating anon decls

lib/std/Thread/Condition.zig
fixes #12877
Current implementation (before this fix) observes number of waiters when broadcast occurs and then makes that number of wakeups.
If we have multiple threads waiting for wakeup which immediately go into wait if wakeup is not for that thread (as described in the issue). The same thread can get multiple wakeups while some got none. That is not consistent with documented behavior for condition variable broadcast: `Unblocks all threads currently blocked in a call to wait() or timedWait() with a given Mutex.`.
This fix ensures that the thread waiting on futext is woken up on futex wake.
=> stdlib: fix condition variable broadcast FutexImpl

lib/std/crypto/25519/ed25519.zig
If the noise parameter was null, we didn't use any noise at all.
We unconditionally generated random noise (`noise2`) but didn't use it.
Spotted by @cryptocode, thanks!
=> std.crypto.ed25519 incremental signatures: hash the fallback noise

lib/libc/glibc/sysdeps/arm/arm-features.h
Problems with -target arm-linux-gnueabi
```bash
zig build-exe hello.c -target arm-linux-gnueabi --library c --verbose-cc --name hello-zig
...
In file included from /usr/local/Cellar/zig/0.9.1_1/lib/zig/libc/glibc/sysdeps/unix/sysv/linux/arm/sysdep.h:25:
In file included from /usr/local/Cellar/zig/0.9.1_1/lib/zig/libc/glibc/sysdeps/unix/arm/sysdep.h:19:
/usr/local/Cellar/zig/0.9.1_1/lib/zig/libc/glibc/sysdeps/arm/sysdep.h:25:11: fatal error: 'arm-features.h' file not found
...
```
Add file arm-features.h from the glibc source.
=> add arm-features.h from glibc source

lib/std/os.zig, lib/std/os/test.zig, lib/std/testing.zig
Test coverage was lacking for chdir() on WASI, allowing this to regress.
This change makes os.chdir() compile again, and improves the test logic to use our standard CWD support for WASI.
Resolves #13644. Thanks to @codefromthecrypt for the bug report 🙂
=> std.os: Fix `std.os.chdir` for WASI

src/Module.zig, src/Sema.zig
Reviving MR https://github.com/ziglang/zig/pull/11977
=> Use a slice for InstMap instead of std.HashMap

lib/std/crypto/25519/ed25519.zig, lib/std/crypto/25519/edwards25519.zig
Does what the name says: rejects generators of low-order groups.
`clearCofactor()` was previously used to do it, but for e.g. cofactored signature  verification, we don't need the result of an actual multiplication.
Only check that we didn't end up with a low-order point, which is a faster operation.
=> std.crypto.edwards25519: add a rejectLowOrder() function

build.zig, lib/std/fs/path.zig, src/Module.zig, src/introspect.zig, src/main.zig, src/test.zig
In general, we prefer compiler code to use relative paths based on open directory handles because this is the most portable. However, sometimes absolute paths are used, and sometimes relative paths are used that go up a directory.
The recent improvements in 81d2135ca6ebd71b8c121a19957c8fbf7f87125b regressed the use case when an absolute path is used for the zig lib directory mixed with a relative path used for the root source file. This could happen when, for example, running the standard library tests, like this:
stage3/bin/zig test ../lib/std/std.zig
This happened because the zig lib dir was inferred to be an absolute directory based on the zig executable directory, while the root source file was detected as a relative path. There was no common prefix and so it was not determined that …
=> CLI: more careful resolution of paths

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
Previously, this would set `len` to 1 but fail to initialize any limbs, because the while loop would loop 0 times.  There's probably a cleaner way to do this, but I just want it to work.  This bug is causing the C backend to emit `@as(f64, 0.0)` non-deterministically on 32-bit targets.
=> std.big.int.Mutable: fix `set(@as(DoubleLimb, 0))`

lib/std/Thread/Futex.zig
Fixes #13673
I found the correct type by [blaming](https://github.com/ziglang/zig/commit/62ff8871ed9c8c4e46d8acd1d227ed3fb802be7f#diff-efdc8ea1c18493314ed01d0dc85d35564a2f5282f15c1f66db91822861d704a1L724-R724).
=> std.Thread.Futex.PosixImpl.Address.from: fix `alignment` type

lib/std/os/windows.zig
Ran into this when using a program that uses `CreateFileMapping` and then from Zig trying to call `std.fs.Dir.createFile` with the mapped file's path. More info can be found here:
https://stackoverflow.com/questions/41844842/when-error-1224-error-user-mapped-file-occurs
Before:
```
error.Unexpected NTSTATUS=0xc0000243
C:\Users\Ryan\Programming\Zig\zig\lib\std\os\windows.zig:138:40: 0x7ff74e957466 in OpenFile (test.exe.obj)
else => return unexpectedStatus(rc),
^
```
After:
```
FAIL (AccessDenied)
C:\Users\Ryan\Programming\Zig\zig\lib\std\os\windows.zig:137:30: 0x7ff7f5b776ea in OpenFile (test.exe.obj)
.USER_MAPPED_FILE => return error.AccessDenied,
^
```
=> `os.windows.OpenFile`: Add `USER_MAPPED_FILE` as a possible error

src/codegen/llvm.zig
* ensure parameter debug info is in the subroutine di scope
* slit sub file path into basename and dirname
Closes #12257
Closes #12665
Might also resolve the following: #13224 and #13315 but I haven't been able to reproduce those.
=> llvm: improve emitted debug info

lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig, lib/std/os/windows/ntdll.zig, lib/std/target/aarch64.zig, lib/std/zig/system/NativeTargetInfo.zig, lib/std/zig/system/arm.zig, lib/std/zig/system/linux.zig, lib/std/zig/system/windows.zig
Detecting Armv8 CPU features using low-level mechanism such as pulling the feature set directly from system registers on requires exception level 1 (EL1) which, as a user-space app, we don't have access to. Therefore, we are limited by the info provided to us by each OS when it comes to detecting available CPU features at runtime.
On Windows, this is done via a `kernel32` function `IsProcessorFeaturePresent` (this is what LLVM does btw). However, instead of issuing a DLL call, why not reimplement the function ourselves? In this case, `IsProcessorFeaturePresent` is very simple to implement without issuing a single system DLL call since all of the required data is always mapped by the kernel at a fixed memory location and available as a read-only virtual page for user-space apps at location …
=> windows: add native CPU and features detection for Armv8 chips

build.zig, ci/windows/build.ps1, test/link.zig, test/tests.zig
Symlinks aren't available on Windows unless developer mode is enabled, or the user has a certain permission.
Running test-link before this change would result in this:
```
error: AccessDenied
C:\cygwin64\home\kcbanner\kit\zig\build-stage3-debug\lib\zig\std\os\windows.zig:220:32: 0x7ff765cd841f in DeviceIoControl (build.exe.obj)
.PRIVILEGE_NOT_HELD => return error.AccessDenied,
^
C:\cygwin64\home\kcbanner\kit\zig\build-stage3-debug\lib\zig\std\os\windows.zig:741:9: 0x7ff765cbaa6d in CreateSymbolicLink (build.exe.obj)
_ = try DeviceIoControl(symlink_handle, FSCTL_SET_REPARSE_POINT, buffer[0..buf_len], null);
^
C:\cygwin64\home\kcbanner\kit\zig\build-stage3-debug\lib\zig\std\fs.zig:1997:9: 0x7ff765cba207 in symLinkW (build.exe.obj)
return os.windows.CreateSymbolicLink(self.fd, …
```
=> Skip linker tests requiring symlinks on Windows

lib/std/zig/system/arm.zig, lib/std/zig/system/windows.zig
Hear me out, cause I think this is pretty cool and big kudos to folks from Microsoft for actually facilitating it!
Here's the thing: detecting CPU features on ARM requires reading and parsing bitfields from a set of special registers called system registers. All good except those system registers are not accessible by us user-space mortals - they require running in a higher, privileged HW state called Exception Level 1 (we normally run in EL0 for context). So we cannot just type out some inline asm to pull the contents of those registers as we are not running in the correct exception level. Increasing exception level is also not an option as it's not allowed (to the best of my knowledge). On Linux and macOS we are giving intermediate mechanism to pull those out via a user-space tool such …
=> Improve aarch64 feature detection based on the readouts from privileged system registers

ci/linux/build-x86_64-debug.sh, src/codegen/llvm.zig, test/behavior/while.zig
=> LLVM: fix canElideLoad behavior with loops

lib/std/heap.zig, lib/std/heap/PageAllocator.zig, lib/std/heap/WasmAllocator.zig, lib/std/heap/WasmPageAllocator.zig
This is a 160-line Allocator implementation that is simpler, faster, and more memory-efficient than GeneralPurposeAllocator. It similarly buckets allocations into size classes, however, unlike GPA, it additionally uses free lists, and does not track any metadata. The only extra information stored within each allocation is an intrusive free list node, so that the allocation can be added to the free list without possibility of failure. This allocator has zero external fragmentation, but a high amount of internal fragmentation. Large allocations are never split into multiple smaller allocations, and smaller allocations are never joined into a single larger allocation.
It is WebAssembly-only because it depends on single-threaded access to global variables to keep track of allocator state, it …
=> WebAssembly-only fast allocator

lib/build_runner.zig, lib/std/build.zig, src/Sema.zig, src/codegen/llvm.zig, src/main.zig
`@llvm.dbg.value` is absolutely useless, adding a temporary alloca
to store the constant in will make it actually show up in debuggers.
The effect on performance should be minimal since there is only one
store and it the change is not applied to ReleaseSafe builds.
```zig
fn foo(a: u32, b: []const u8, c: bool, d: enum { yes, no }) void {
_ = a; _ = b; _ = c; _ = d;
}
```
before:
```
Breakpoint 1, a.foo (a=<optimized out>, b=..., c=<optimized out>, d=<optimized out>) at a.zig:18
18          _ = d;
```
after:
```
Breakpoint 1, a.foo (a=1, b=..., c=false, d=yes) at a.zig:15
15          _ = a; _ = b; _ = c; _ = d;
(gdb) p b
$1 = {ptr = 0x20854f <a.main.anon_3888> "bar", len = 3}
```
=> Improve debuggability of programs built by the self hosted compiler

lib/std/testing.zig
Provides a nice improvement over the current output of `expectEqualSlices` when dealing with binary data (the status quo is that only the first line of the output shown below is printed [the `index 5 incorrect`, etc]).
Example when the lengths match:
Example when the lengths are different:
The coloring is controlled by `std.debug.detectTTYConfig` so it will be disabled when appropriate.
---
Some notes:
- Instead of making this a separate function, this style of printing could be used by `expectEqualSlices` when the type is `u8`. Unsure if that'd be better. There's this relevant TODO in `expectEqualSlices`, but I'm unsure if hexdumps like this would satisfy it or not:
https://github.com/ziglang/zig/blob/71038c42f554da86ee23c9c448d39e457d5818eb/lib/std/testing.zig#L285-L288
- It's possible …
=> std.testing: Add expectEqualBytes that outputs hexdumps with diffs highlighted in red

lib/std/testing.zig
Follow up to #13720.
`expectEqualBytes` will now truncate the hexdump of each input to a maximum window of 256 bytes, which makes it safe to use for arbitrarily large inputs. Therefore, it can be used in `expectEqualSlices` when the type is `u8`.
If the input needs to be truncated, then the printed section of each will start slightly before the first difference.
Here's an example of what it looks like when the inputs are truncated:
=> std.testing: Improve `expectEqualBytes` for large inputs and make `expectEqualSlices` use it

lib/std/fs.zig, lib/std/fs/test.zig
I hope the comment in the change explains well! I found this bug in https://github.com/tetratelabs/wazero/pull/865 where Rust and C pass for a large directory test while zig fails.
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
=> wasi: fixes IterableDir.nextWasi for large directory

src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/link/Dwarf.zig
I think it's high time we move all DWARF specific stuff such as opcodes and exprloc emitting to `Dwarf.zig` module and expose higher level helpers for use by any codegen that wants to emit DWARF debug info.
cc @joachimschmidt557, @Luukdegram, @koachan
=> dwarf: dedup generation of dwarf info for func args and vars in Dwarf module

ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/aarch64-macos.sh, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, ci/x86_64-macos.sh, ci/x86_64-windows.ps1
Notably this contains a fix to zig cc that enables the syntax `-Wl,-z,stack-size=0x10000`.
=> CI: update tarballs to 0.11.0-dev.448+e6e459e9e

lib/zig.h, src/codegen/c.zig, test/stage2/cbe.zig
In general the C backend should lower to human-maintainable C code
whenever possible. Directly using C types that one would use when
writing C code is one part of the strategy.
The concern with including stdint.h is C89 compatibility. Well, we can
just check the C std lib version before deciding to include that header.
bonus commit: use a 0 literal instead of `error.@"(no error)"`
This saves bytes and is easier to read too.
=> CBE: use bool, true, false, instead of `zig_` prefixes

src/codegen/c.zig, test/behavior/asm.zig, test/behavior/basic.zig, test/behavior/bitreverse.zig, test/behavior/byteswap.zig, test/behavior/math.zig, test/behavior/ptrcast.zig, test/behavior/struct.zig, test/behavior/vector.zig
Also fixes an aarch64-specific test so I don't keep accidentally enabling it.
=> cbe: use memcpy for underaligned loads and stores

src/codegen/c.zig
This change alone solves the bracket-depth issue when compiling zig1.c with Clang.
=> CBE: no braces when lowering block instruction

src/Sema.zig, test/cases/compile_errors/reify_enum_with_duplicate_field.zig, test/cases/compile_errors/reify_enum_with_duplicate_tag_value.zig
Fixes #13728
Fixes #13606
I also tried to add some source locations, but I'm not sure about those. For example:
Before:
```
y.zig:9:15: error: duplicate enum tag A
const x = @Type(std.builtin.Type{
^~~~~
```
After:
```
y.zig:9:15: error: duplicate enum field 'A'
const x = @Type(std.builtin.Type{
^~~~~
y.zig:9:15: note: other field here
```
Is this actually an improvement? Also, it doesn't show the same source line again below the note (maybe it's ok?). But I'm not sure how else we would improve the source location because are we supposed to point at the exact line where the value or field name is specified (e.g. `        .{ .name = "A", .value = 10 },`)? If not, the way I did it might be close to what's desired.
And looking at e.g. …
=> Sema: detect duplicate enum tag values

lib/std/compress/gzip.zig
- Add two length bounds of 1024 for the filename and comment fields.  The official gzip C sources use a bound of 1024 for the filename, so that number is chosen.
- Add two missing header fields 'extra' and 'operating_system'
- Change a couple local vars into const.
=> gzip: add missing header fields and bounds for header parsing

src/link/Dwarf.zig, src/link/Elf.zig, src/link/MachO.zig, src/link/Wasm.zig
We need to access it outside of `DeclState` too so why not reuse the helper anyway.
=> dwarf: reuse getDbgInfoAtom helper in all of Dwarf.zig

lib/std/bit_set.zig
I was surprised that `StaticBitSet` didn't implement `subsetOf`. Digging further I realized an entire set of pure functions could be added to `StaticBitSet`.
The following functions were added to both `IntegerBitSet` and `ArrayBitSet`:
```zig
fn eql(self: Self, other: Self) bool
fn subsetOf(self: Self, other: Self) bool
fn supersetOf(self: Self, other: Self) bool
fn complement(self: Self) Self
fn unionWith(self: Self, other: Self) Self
fn intersectWith(self: Self, other: Self) Self
fn xorWith(self: Self, other: Self) Self
fn differenceWith(self: Self, other: Self) Self
```
I am open to better function names.
`DynamicBitSet` remains unchanged as it is not possible to implement some of those functions without an allocator.
=> std: add pure functions to StaticBitSet

src/wasi_libc.zig
When the bulk_memory feature is enabled, wasi-libc will only use it if the number of bytes is >= `BULK_MEMORY_THRESHOLD`.
Set it to `32` as in the original `wasi-libc` Makefile.
=> wasi-libc: define BULK_MEMORY_THRESHOLD for the bulk_memory feature

src/Sema.zig
Before this commit, I observe a crash from this abiSize call because the element type is a struct that is not yet resolved. This is triggered by running the behavior tests with -ofmt=c -target x86_64-windows.
=> Sema: resolve elem type for non-default aligned ptrs

lib/std/crypto/aes.zig
Hardware-accelerated AES requires inline assembly code, which cannot work at comptime.
=> std.crypto.aes: use software implementation in comptime context

lib/std/crypto/aes.zig
This reverts commit d4adf4420071397d993bac629a9da27b33c67ca3.
Unfortunately, this is not the best place to check if functions are being used at comptime or not.
=> Revert "std.crypto.aes: use software implementation in comptime context"

src/Cache.zig, src/Compilation.zig, src/main.zig
This fixes https://github.com/ziglang/zig/issues/12718.
- C compilation flows didn't hold an exclusive lock on the cache manifest file when writing to it in all cases
- On windows, explicitly unlock the file lock before closing it
At first I though this was related to locks not being released, since the LockFileEx documenation mentions:
> If a process terminates with a portion of a file locked or closes a file that has outstanding locks, the locks are unlocked by the operating system. However, the time it takes for the operating system to unlock these locks depends upon available system resources. Therefore, it is recommended that your process explicitly unlock all files it has locked when it terminates. If this is not done, access to these files may be denied if the operating system has …
=> cache: Fix LockViolation during C compilation paths

lib/std/testing.zig
- In #13720, `expectEqualBytes` was added as a standalone function
- In #13723, `expectEqualSlices` was made to use `expectEqualBytes` when the type was u8
- In this commit, `expectEqualSlices` has fully absorbed `expectEqualBytes`, and `expectEqualBytes` itself has been removed
For `u8`, `expectEqualSlices` works as `expectEqualBytes` did before. For non-`u8` types, `expectEqualSlices` will now work similarly to `expectEqualBytes` (highlighting diffs in red), but will use a full line for each index and therefore will only print a maximum of 16 indexes.
This should address all the TODO comments that were in `expectEqualSlices`.
---
The most dramatic improvement is when the slice lengths differ. Here's an example with `u32` as the type:
Before:
```
Test [6/11] test_2... slice lengths …
```
=> std.testing: Fully absorb `expectEqualBytes` into `expectEqualSlices`

src/link/Dwarf.zig, src/link/Elf.zig, src/link/MachO.zig, src/link/MachO/DebugSymbols.zig, src/link/Wasm.zig
We now generate `include_directories` and `file_names` lists in `.debug_line` section which means we can finally debug the self-hosted native backend output across multiple Zig source files. In particular, we can finally debug output from running:
```
$ zig test behavior.zig -Itest -fno-LLVM --test-no-exec -femit-bin=test_bin
$ gdb test_bin
```
I have ensured that all 3 platforms Linux, macOS and Wasm benefit from the changes introduced in this PR. ~~Before merging it, I am thinking of adding some simple incremental DWARF test plugin to our incremental test harness. This is long overdue especially now that I have taken the time to refactor a lot of the DWARF linker code. For that reason, I will leave the PR in draft until I have a stab at the testing harness.~~ In order not to clutter …
=> dwarf: add support for multiple source files

lib/std/math.zig, lib/std/mem.zig
We currently have two `doNotOptimizeAway()` implementations, one in `std.math` and the other one in `std.mem`.
Maybe we should deprecate one. In the meantime, the `std.math` one now just calls the `std.mem` one.
In a comptime environment, just ignore the value. Previously, `std.mem.doNotOptimizeAway()` did not work at comptime.
If the value fits in a CPU register, just tell the compiler we need that value to be computed, without clobbering anything else.
Only clobber all possibly escaped memory on pointers or large arrays.
Add tests by the way since we didn't had any (we had, but only indirect ones).
=> Improve and remove duplicate doNotOptimizeAway() implementations

src/Compilation.zig, src/codegen/llvm.zig, src/link.zig, src/link/Coff/lld.zig, src/link/Dwarf.zig, src/link/Elf.zig, src/link/MachO/DebugSymbols.zig, src/link/Wasm.zig
This change brings back `stage1` behavior in that all debug info paths that are emitted in DWARF/PDB are always absolute. Note that the paths are resolved only when committing them into either a respective LLVM type (`llvm.DIFile`), or when emitting DWARF (as is the case with self-hosted backends).
This change will make stack traces and debugging experience more consistent in the sense that the presence of source lines in stack traces will not be dependent on the current working directory of the running process, making cases like https://github.com/ziglang/zig/issues/13831 non-existent (I am referring here to lack of source lines in submitted stack trace, not the actual linker bug which is unrelated).
Additional bonus is that we no longer need to mess with `lld-link`s output on Windows by …
=> debug info: resolve relative paths to source files into absolute paths

src/link/MachO/dead_strip.zig
They are implicitly marked live.
Fixes #13831
=> macho+zld: skip atomless synthetic globals in dead_strip

CMakeLists.txt
Few tweaks to CMakeLists.txt to allow zig1.c to successfully build with msvc and generate zig2.c
=> fix building wasm2c output with msvc

doc/langref.html.in
Several <em> elements where added inside a shell node in the Using--target-and--cflags section.  Remove them, since they are not supposed to be handled by codegen.
For the original commit, see
0c091feb5 (Improve HTML semantics and a11y of language reference).
Fixes #13846
=> langref: remove HTML code from a shell node

lib/std/bit_set.zig
Some typos I noticed in the doc comments.
=> Fix doc comments in std.StaticBitSet types

src/Compilation.zig
We definitely want a shared lock on a cache hit. Without this, we get a deadlock when Zig is asked to compile the same C source file multiple times as part of the same compilation.
This is a partial revert of 8ccb9a6ad327a4d7fbc321b33d4aa66a27a1f5ee.
cc @kcbanner
=> Compilation: revert asking for exclusive locks on cache hits

lib/std/SemanticVersion.zig, lib/std/ascii.zig, lib/std/fmt.zig, lib/std/net.zig, lib/std/zig/parse.zig, lib/std/zig/render.zig, lib/std/zig/tokenizer.zig, src/DepTokenizer.zig, src/translate_c.zig
I wrote this after #12448 got merged but decided to wait for 0.10.0 to be released before pulling it. Now I've decided to pull it a bit earlier since 0.10.0 is just about to be released, anyway (and in case someone else would accidentally start working on the same thing or something).
This should be merged **after** 0.10.0 and removes all deprecations, updates the codebase, does some other cleanups etc., and also removes the LUT (Look-Up Table): this was already discussed quite a bit in #11629 (see https://github.com/ziglang/zig/pull/11629#issuecomment-1213641429 etc.) and I've also discussed this with @topolarity in more detail after that, but basically the reason is that the LUT made us depend on cache performance. It also reduces binary size. See also the commit's description for more …
=> std.ascii: remove LUT and deprecations

lib/std/os.zig, lib/std/os/test.zig
isatty hasn't been tested explicitly, and there was a compilation error for WASI target.
```
lib/std/os.zig:3161:17: error: incompatible types: 'os.wasi.errno_t' and 'comptime_int'
if (err != 0) {
~~~~^~~~
```
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
=> wasi: fixes os.isatty on type mismatch

lib/std/debug.zig
This fixes a class of bugs on macOS where a segfault happening in a loaded dylib with no debug info would cause a panic in the panic handler instead of simply noting that the dylib has no valid debug info via `error.MissingDebugInfo`. An example could be code linking some system dylib and causing some routine to segfault on say invalid pointer value, which should normally cause Zig to print an incomplete stack trace anchored at the currently loaded image and backtrace all the way back to the Zig binary with valid debug info. Currently, in a situation like this we would trigger a panic within a panic.
=> Remove incorrect assertion in readMachODebugInfo panicking during panic

lib/docs/main.js
Removes error that blocks rendering of autodoc documentation.
=> autodoc: Removed BoundFn from indexTypeKinds in main.js

lib/std/array_list.zig
Calling `deinit` might still be required after using `toOwnedSlice` now.
See <https://github.com/ziglang/zig/commit/ceb0a632>.
=> std: Update ArrayList documentation

lib/std/enums.zig
Implements [multiset](https://en.wikipedia.org/wiki/Set_(abstract_data_type)#Multiset) (also known as bag) for enums.
`EnumMultiSet` can count up to `usize`.
`EnumMultiSet` is implemented by `BoundedEnumMultiSet`, which has a comptime count type.
`BoundedEnumMultiSet` is backed by `EnumArray`.
=> std: add EnumMultiSet

src/Module.zig, src/Sema.zig, test/cases/compile_errors/array_mult_with_number_type.zig
Fixes #13857
Works just like andrewrk described it:
```
test.zig:7:25: error: expected indexable; found 'f32'
return 3.141592 * self.r ** 2;
~~~~~~~~~^~~~~~~~
test.zig:7:34: note: this operator multiplies arrays; use std.math.pow for exponentiation
return 3.141592 * self.r ** 2;
^~
referenced by:
area: test.zig:38:30
main: test.zig:59:52
remaining reference traces hidden; use '-freference-trace' to see all reference traces
```
​
I couldn't find a way to get just the operator using `LazySrcLoc`, so I also added a new variant for that.
=> Add a helpful note when using `**` on number types.

lib/std/os/test.zig
Remove timerfd timeout and fix timerfd_settime flag. CI tests should not rely on timings to succeed.
=> std.os.linux: fix timerfd test

lib/std/zig/parser_test.zig, lib/std/zig/render.zig
TODO comments said to remove this
re: the second change: I'm slightly unsure here what was meant by "get rid of renderSpace()"; I guessed at the intent and it looks sensible to me but I would like someone more knowledgeable to confirm.
=> parser: remove c_void -> anyopaque rewrite

test/standalone.zig
=> Revert test workarounds for aarch64-windows

lib/std/rand/Pcg.zig
The PCG32 fill function seems to have been copy-pasted from code using u64, so requesting `n` bytes where `(n & 7) > 4` bytes would cause the last few bytes to be all 0.
=> std: fix bug in Pcg32 fill function

doc/langref.html.in
Split the original `defer.zig` doctest into 3 doctest:
1. Document the defer keyword
2. Document that the return statement is not allowed inside a defer expression
3. Document the errdefer keyword
Replace "method" with "expression" in the text `defer method`.
=> langref: improve the defer section

lib/std/os.zig, lib/std/os/test.zig
This helps prevent errors related to undefined pointers being passed through to some OS apis when slices have 0 length.
Tests have also been added to catch these cases.
=> Add 0-length buffer checks to os.read & os.write

src/Liveness.zig
Spun off from #13074
This is a crude pattern match for  try-like `.cond_br` blocks emitted by Sema's safety checks. It looks for:
```zig
%x = block(void, {
cond_br(..., {
br(%x, @Zir.Inst.Ref.void_value)
}, {
call(...)
})
})
```
This matches the signature of many of our safety checks which look like this:
```zig
%14 = ... ; generate check condition
%23!= block(void, {
%24!= cond_br(%14!, {
%13! %21!
%25!= br(%23, @Zir.Inst.Ref.void_value)
}, {
%22!= call(%21!, [%12, %13!])
})
})
```
The reasoning here is that control flow either diverges (the call must be `noreturn` to be at the end of the block) or continues directly to the following instructions in the block without modifying memory. This was inspired by https://github.com/ziglang/zig/issues/11772#issuecomment-1144203077
Resolves …
=> stage2: Teach Liveness that some safety checks do not observably modify memory

doc/langref.html.in
=> langref: incorrect use of the term "enum variant" in enums.zig

ci/aarch64-windows.ps1
This matches the scripts we use for our other self-hosted runners.
=> CI: override cache folders on aarch64-windows

test/behavior/math.zig
works on my machine in various configurations, so re-enabling here for the CI run
=> re-enable "signed zeros are represented properly" beahvior tests for f80 and c_longdouble

lib/std/priority_dequeue.zig, lib/std/priority_queue.zig
Previously the update() method would iterate over its capacity, which may contain uninitialized memory or already removed elements.
Noticed this while debugging today's solution of Advent of Code.
=> std: Fix update() method in PriorityQueue and PriorityDequeue

doc/langref.html.in
In the slices.zig doctest, the code `const all_together_slice = all_together[0..]` is incorrect, since the actual type is a pointer to an array, instead of a slice.
Use a runtime-know value to slice the array.
In the next "slice pointer" test, clarify that slicing a slice to produce a pointer to an array, requires comptime-know indexes, not just constant indexes.
=> langref: fix the slices.zig doctest

doc/langref.html.in
Currently, the test_fn_reflection.zig doctest has an example of .Fn.is_var_args.  This example can confuse the reader, since there is no documentation about variadic functions and is_var_args is mainly used in the compiler.
Remove the example with .Fn.is_var_args and add instead examples with .Fn.return_type and .Fn.is_generic.
=> langref: improve the test_fn_reflection.zig doctest

doc/langref.html.in
Add a missing ReleaseSmall when describing unreachable in the try section and the unreachable entry in the Keyword Reference section.
Additionally, transform Debug, ReleaseSafe, ReleaseFast and ReleaseSmall into links in the try section.
=> langref: add missing ReleaseSmall when describing unreachable

doc/langref.html.in
A self-closing tag for void elements like link is only required under XHTML 1.0.
See https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags.
=> langref: remove the trailing slash from the link element

lib/std/mem/Allocator.zig
* Remove recursive call using null alignment, since it's no longer relevant.
* Fix comment
=> Allocator.zig: minor fixes

doc/langref.html.in
Add a new subsection within the C section, documenting extern variadic functions.
=> langref: document extern variadic functions

doc/langref.html.in
closes #13870
I decided to remove the coercion test from this section, because that is also tested in both directions in the linked section specifically about union<->enum coercion.
=> Improve tagged union documentation

lib/std/Progress.zig, lib/std/debug.zig, lib/std/testing.zig, src/Compilation.zig
`ttyconf.setColor(stderr, .Dim)` just like `stderr.print("{s}", .{plain.msg})` can fail, so I don't see why we wouldn't handle the former just like the latter. It's an edge case. You can always still ignore the error in your specific case if you want to.
Apart from that it solves a bunch of related TODOs and it also removes a bunch of `unreachable`s in `std.Progress` which is supposed to be non-fallible because now I'm confident these `unreachable`s can be reached since the user can modify the `std.Progress.terminal` field. It can probably fail anyway. Better safe than sorry.
=> std.debug: handle some possible errors and resolve low-hanging TODOs

ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, lib/std/c/linux.zig, lib/std/fs.zig, lib/std/fs/file.zig, src/Module.zig
Hello.
This PR:
- changes `Dir.statFile` to use a single syscall (`fstatat`, called in the `os.fstatat` function)
- adds functions in `File.Stat` to initiate it from an `os.system.Stat` structure (given by `os.fstatat`)
- mainly keeps the `Dir.statFile` signature, except for errors that are now inherited from `os.fstatat`
- adds `Dir.fstatat` in order to avoid the conversion from `os.system.Stat` to `File.Stat`, which drops data such as `uid` and `gid`
Also, there is currently no test for this function in the standard library.
Tell me how to test `Dir.statFile` and I'll add it in the PR, if you want.
Thanks for your time!
=> Dir.statFile now uses fstatat (fewer syscalls)

lib/std/builtin.zig, lib/std/debug.zig, lib/std/testing.zig, src/main.zig
This fixes a regression introduced in #12298 where colors would never reset in a Windows console because the attributes would be queried on every `setColor` call, and then try to 'reset' the attributes to what it just queried (i.e. it was essentially doing a complicated no-op on `.Reset`).
This fixes the problem while (I think) keeping with the spirit of the changes in #12298--that is, `TTY.Config` is not specifically tied to stderr like it was before #12298. To that end, detectTTYConfig now takes a `File` and that's what gets used to query the initial attributes to reset to.
(for context, before #12298, the first `setColor` call is where the reset attributes would get queried and it would always use stderr to do it)
Before (the green of the `^` would carry over to the output of `zig …
=> std.debug.TTY: Fix colors not resetting on Windows

lib/std/compress/deflate/bits_utils.zig, lib/std/compress/deflate/compressor.zig, lib/std/compress/deflate/compressor_test.zig, lib/std/compress/deflate/decompressor.zig, lib/std/compress/deflate/deflate_fast.zig, lib/std/compress/deflate/deflate_fast_test.zig, lib/std/compress/deflate/dict_decoder.zig, lib/std/compress/deflate/huffman_bit_writer.zig, lib/std/compress/deflate/huffman_code.zig, lib/std/compress/deflate/token.zig, lib/std/compress/gzip.zig, lib/std/compress/zlib.zig
- Previously, some of the compress tests used `@src()` in combination with `dirname` and `openDirAbsolute` to read test files at runtime, which both excludes platforms that `openDirAbsolute` is not implemented for (WASI) and platforms that `SourceLocation.file` is not absolute (this was true for me locally on Windows and @mikdusan said they ran into it on BSDs). Instead of converting the tests to use `fs.cwd().openDir`, they have been converted to use `@embedFile` to avoid any potential problems with the runtime cwd.
- In order to use `@embedFile`, some of the `[]u8` parameters needed to be changed to `[]const u8`; none of them needed to be non-const anyway
- The tests now use `expectEqual` and `expectEqualSlices` where appropriate for better diagnostics
=> `std.compress`: Improve tests, remove reliance on openDirAbsolute

lib/std/leb128.zig
This is a trivial patch to re-enable tests that were disabled due to a LLVM 14 regression. The regression has been fixed in LLVM 15.
You can reproduce with:
`stage3/bin/zig test ../lib/std/leb128.zig --zig-lib-dir ../lib -target riscv64-linux-none`
Closes #12031.
=> std.leb128: Re-enable test for riscv64

src/link/Elf.zig
Given `main.go`:
package main
import  _ "os/user"
func main() {}
Compiling it to linux/arm64:
$ CGO_CFLAGS='-O0' GOOS=linux GOARCH=arm64 CGO_ENABLED=1 CC="zig cc -target aarch64-linux-gnu.2.28" go build main.go
Results in this error:
runtime/cgo(.text): unknown symbol memset in callarm64
runtime/cgo(.text): unknown symbol memset in callarm64
runtime/cgo(.text): relocation target memset not defined
In the midst of intermediate compilations files we can see this commmand:
ld.lld -o _cgo_.o <...> /tmp/go-build206961058/b043/_x009.o <...> ~/.cache/zig/.../libcompiler_rt.a <...> ~/.cache/.../libc.so.6
`_x009.o` needs memset:
$ readelf -Ws ./b043/_x009.o | grep memset
22: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND memset
Both `libcompiler_rt.a` and `libc.so.6` provide it:
$ readelf -Ws …
=> Elf: switch link order of libcompiler_rt and libc

test/behavior.zig, test/behavior/bugs/13366.zig
Closes #13366
My understanding is that now that stage1 is gone, the only thing preventing all the stage1 issues from being closed is the lack of tests to prove they are really fixed.
=> Add test for #13366

lib/std/zig/parser_test.zig, lib/std/zig/render.zig, src/codegen/llvm.zig, test/stack_traces.zig
=> zig fmt: fix extra whitespace with multiline strings

lib/std/enums.zig
**Context**
| Zig Version | 0.11.0-dev.618+096d3efae |
|-| - |
I am new to Zig, but not to C / C++. I am trying to to learn Zig via Advent of Code, and on day 9 came across this situation, I expected to work.  Very possible this is a beginner mistake, but also wanted to [do my part](https://github.com/ziglang/zig/blob/master/.github/CONTRIBUTING.md#start-a-project-using-zig) and file an issue.
**Reference Code**
```zig
const EnumSet = std.EnumSet;
test "EnumSet const iteration" {
const Direction = enum { up, down, left, right };
const diag = diag: {
var move: EnumSet(Direction) = .{};
move.insert(.right);
move.insert(.up);
break :diag move;
};
_ = diag.iterator();
//  ^ expected to be able to iterate a const EnumSet
}
```
**Expected Behavior**
I expected the …
=> std.IndexedSet.iterator: allow iteration on const EnumSet

lib/std/child_process.zig, lib/std/os/windows.zig
Note: This is probably best reviewed commit-by-commit, as they could each be a separate PR if I weren't making all the changes at one time.
---
If the command is specified as `something.exe`, the retry will now try:
```
C:\some\path\something.exe
C:\some\path\something.exe.COM
C:\some\path\something.exe.EXE
C:\some\path\something.exe.BAT
... etc ...
```
whereas before it would only try the versions with an added extension from `PATHEXT`, which would cause the retry to fail  on things that it should find.
---
Also, I reworked some stuff to drastically reduce the amount of allocations that occur in the `FileNotFound` recovery block when looking through `PATH`.
---
Finally, `CreateProcessW` can now return `error.InvalidExe` when appropriate, and `spawnWindows` has been made to handle it. …
=> `ChildProcess.spawnWindows`: `PATH` search fixes + optimizations

lib/compiler_rt/clzsi2_test.zig
On arm and thumb `test__clzsi2(0x00000000, 32)` crashes pretty badly:
```
Test [1/10] test.clzsi2... FAIL (TestExpectedEqual)
thread 50405 panic: reached unreachable code
Panicked during a panic. Aborting.
qemu: uncaught target signal 6 (Aborted) - core dumped
error: the following test command crashed:
```
We could still run this on the other CPUs.
=> compiler_rt: test clzsi2 with zero on CPUs where possible

lib/std/math.zig, src/Sema.zig, src/test.zig, src/value.zig, test/behavior.zig, test/behavior/int_comparison_elision.zig
Déjà vu.
Fixes #2146
This generates a constant true/false whenever possible when comparing integers, based purely on the type of one of the operands. One side must be a comptime int or constant, and the other side can be either undefined or a runtime value (but must be sized).
The implementation detail that's probably most worth validating is using `popCount()` for detecting when a constant is at the upper/lower bound of a sized type. A more obvious approach might be comparing the value to itself +/- 1 and seeing if the bitsize changes, as I did [on my scratch branch](https://github.com/hryx/zig/commit/7fce0ac867913f60411befc58f8b9e885d0dae5b#diff-23f8450a3403f774f20a81390ea9072846dc675ee17a679f715b26b22c86b591R28384-R28399). That could still be done using only stack allocation, but it …
=> Sema: elide integer comparisons with guaranteed outcomes

lib/std/zig/Ast.zig, lib/std/zig/parser_test.zig
The following code will crash the zig compiler. (this is the entire file)
```zig
foo()
```
=> fix potential integer underflow in std.zig.Ast.fullCall

lib/std/rand/Xoroshiro128.zig, lib/std/rand/Xoshiro256.zig, src/codegen/llvm.zig, test/behavior/struct.zig
* Handle a `null` return from `llvmFieldIndex`.
* Add a behavior test to test this code path.
* Reword this test name, which incorrectly described how pointers to zero-bit fields behave, and instead describe the actual test.
* Add `pub` to some rand functions.
These were all of the issues encountered while trying to test a new data structure.
=> llvm: fix null pointer use when lowering pointer to final zero-width field of a comptime value

src/Sema.zig, test/cases/compile_errors/ignored_comptime_value.zig
Check the return type of a comptime call prior to its evaluation.
Support all kinds of expressions may require big changes to data structure and sema.zig.
Fixes #12580
=> Call ensureResultUsed before comptime .call is evaluated.

lib/std/child_process.zig, lib/std/os.zig, lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig, test/standalone.zig, test/standalone/windows_spawn/build.zig, test/standalone/windows_spawn/hello.zig, test/standalone/windows_spawn/main.zig
Follow up to #13983.
First, the eye-popping benchmark:
```
Benchmark 1: winpathbench-perf.exe
Time (mean ± σ):     854.3 ms ±   6.0 ms    [User: 116.9 ms, System: 731.9 ms]
Range (min … max):   845.3 ms … 867.6 ms    10 runs
Benchmark 2: winpathbench-master.exe
Time (mean ± σ):      8.188 s ±  0.038 s    [User: 0.684 s, System: 7.479 s]
Range (min … max):    8.137 s …  8.254 s    10 runs
Benchmark 3: winpathbench.bat
Time (mean ± σ):     851.4 ms ±   4.9 ms    [User: 90.3 ms, System: 741.3 ms]
Range (min … max):   843.9 ms … 861.1 ms    10 runs
Summary
'winpathbench.bat' ran
1.00 ± 0.01 times faster than 'winpathbench-perf.exe'
9.62 ± 0.07 times faster than 'winpathbench-master.exe'
```
<details>
<summary>Benchmark code</summary>
Compiled with `-lc -OReleaseFast`:
```zig
const std = …
```
=> `spawnWindows`: Improve worst-case performance considerably + tests

doc/langref.html.in, lib/std/builtin.zig, src/Air.zig, src/AstGen.zig, src/BuiltinFn.zig, src/Liveness.zig, src/Sema.zig, src/Zir.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/link/MachO/load_commands.zig, src/print_air.zig, src/print_zir.zig, src/type.zig, test/behavior/sizeof_and_typeof.zig, test/behavior/var_args.zig, test/cases/compile_errors/invalid_capture_type.zig, test/cases/compile_errors/invalid_variadic_function.zig, test/cases/compile_errors/stage1/obj/invalid_maybe_type.zig
=> implement defining C variadic functions

test/behavior/error.zig, test/behavior/ptrcast.zig
See individual commit messages.
=> add behavior test coverage

lib/std/child_process.zig, test/standalone/windows_spawn/main.zig
Fixes a regression caused by https://github.com/ziglang/zig/pull/13983
From the added comment:
We still search the path if the cwd is absolute because of the "cwd set in ChildProcess is in effect when choosing the executable path to match posix semantics" behavior--we don't want to skip searching the PATH just because we were trying to set the cwd of the child process.
This is a straightforward bug fix. It will cause conflicts with #13993 but I'll resolve those once this is merged.
=> `spawnWindows`: Fix PATH searching when cwd is absolute

doc/langref.html.in
When reading a document with nested sections, it is not easy to discover the depth of the current section.
Add support for nested section numbers, from the h2 to the h4 heading, in the format "lv1. ", "lv1.lv2. ", "lv1.lv2.lv3. ".  The "Zig Version" and "Table of Content" sections are excluded.
The section numbers are implemented in CSS, with the CSS rules declared inside a @media rule.  Currently the @media rule targets all media.
=> langref: add section numbers

lib/std/mem.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/value.zig, test/behavior/bugs/3742.zig, test/behavior/struct.zig
This a second attempt at #13992.
* Handle a `null` return from `llvmFieldIndex`.
* Fix getting a pointer to the end of a zero-bit struct in the llvm and c backends.
* Add a behavior test to test these code paths.
* Reword this test name, which incorrectly described how pointers to zero-bit fields behave, and instead describe the actual test.
* Fix incorrect type being passed to `renderParentPtr` in the C backend.
* Disable uncovered test failure on aarch64-windows to verify it's the only remaining issue.
=> codegen: fix taking the address of a field in a zero-bit struct

lib/std/zig/Ast.zig, lib/std/zig/parser_test.zig
these were found while fuzzing zls.
this patch prevents underflow for the following file contents: `enum(u32)` and adds parsing test for it.
i've found another integer underflow for file contents: `*x`. but i'm not sure how to resolve it and added a skipped test for it with a TODO.
=> fix potential integer underflow in std.zig.Ast.fullContainerDecl

src/link/Wasm.zig, src/link/Wasm/Archive.zig, src/link/Wasm/Atom.zig, src/link/Wasm/Object.zig, src/link/Wasm/Symbol.zig
This PR adds the ability to use the in-house WebAssembly linker instead of `wasm-ld` by providing the `-fno-lld` flag. Although this flag was always available already, it would result in crashes as it wasn't properly set up yet for the linking path. This PR also adds many fixes for bugs that were found while testing the in-house linker on the behavior tests while using the LLVM backend. As the linker does not yet fully support all required features we use by default, the in-house linker is not yet the default linker when using the WebAssembly target. For now, we duplicate some of the logic between the linkers for faster iteration.
=> wasm-linker: allow usage of the in-house WebAssembly linker

lib/compiler_rt/emutls.zig
Zig had temporarily regressed in building for the Android NDK due to an uncatched error in `compiler_rt/emutls.zig` and due to the recent aa39644 commit, which caused `c.zig` to export `pthread_key_t` even though `c/linux.zig` exports it on Android.
These errors were not catched because building for the Android NDK isn't tested in the CI.
This pull request just fixes the aforementioned errors.
=> fix build for the Android NDK

lib/std/c/linux.zig
* pthread_key_t should also be available for non-android platforms
* Also change the type to c_uint because Linux pthreadtypes.h typedefs it as "unsigned int"
Partially addresses #13950
=> Fix missing pthread_key_t definition on linux

lib/std/fs.zig
Can occur when trying to open a directory for iteration but the 'List folder contents' permission of the directory is set to 'Deny'.
This was found because it was being triggered during PATH searching in ChildProcess.spawnWindows if a PATH entry did not have 'List folder contents' permission, so this fixes that as well (note: the behavior on hitting this during PATH searching is to treat it as the directory not existing and therefore it will fail to find any executables in a directory in the PATH without 'List folder contents' permission; this matches Windows `cmd.exe` behavior which also fails to find commands in directories that do not have 'List folder contents' permission).
=> `Dir.openDirAccessMaskW`: Add ACCESS_DENIED as a possible error

test/behavior.zig, test/behavior/bugs/11995.zig, test/behavior/bugs/12000.zig, test/behavior/bugs/12051.zig, test/behavior/bugs/12092.zig, test/behavior/bugs/12119.zig, test/behavior/bugs/12142.zig, test/behavior/bugs/12169.zig, test/behavior/bugs/12450.zig, test/behavior/bugs/13113.zig, test/cases/compile_errors/implicit_cast_const_array_to_mutable_slice.zig, test/cases/compile_errors/invalid_store_to_comptime_field.zig, test/cases/compile_errors/invalid_struct_field.zig
The current policy is that before an old stage1 issue can be closed, test coverage for it has to be added.
1. Go to https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+label%3Astage1
2. Close your eyes and click on an issue
3. Determine whether the code in the issue is supposed to compile-error or simply pass.
* If the code from the issue is supposed to just pass, maybe clean it up a bit and put the code in `test/behavior/bugs/github_issue_number.zig` and then reference that file in `test/behavior.zig` at the right spot (there's an order). Use `zig test x.zig` to check locally if it does actually pass.
[Example](https://github.com/ziglang/zig/blob/master/test/behavior/bugs/12486.zig) and [its reference in test/behavior.zig](https://github.com/ziglang/zig/blob/88b49ed00d6d2efb5b523 …
=> Close more old stage1 issues

lib/std/build/CheckObjectStep.zig, src/link/MachO.zig, src/link/MachO/zld.zig, test/link.zig, test/link/macho/strict_validation/build.zig, test/link/macho/strict_validation/main.zig
Otherwise, we were prematurely committing `__LINKEDIT` segment LC with outdated size (i.e., without code signature being taken into account). This would scaffold into strict validation failures by Apple tooling.
Add MachO strict validation smoke test to avoid this type of regression in the future.
Fixes #14045
=> macho+zld: write code signature padding before committing load commands

lib/std/crypto/hkdf.zig
=> HKDF allow expansion up to, and including <hash size> * 255 bytes

test/behavior/bitcast.zig, test/behavior/bugs/12169.zig
```
LLVM Emit Object... zig: llvm/include/llvm/ADT/APInt.h:840: void llvm::APInt::lshrInPlace(unsigned int): Assertion `ShiftAmt <= BitWidth && "Invalid shift amount"' failed.
Aborted
```
Tracked by #13782
=> behavior: disable tests that trigger an llvm 15 bug and assertion

src/Sema.zig, test/behavior/struct.zig
* Fix missing struct layout for llvm backend.
~~I'm not 100% convinced that this won't prevent valid code from compiling, but it passes behavior tests and I can't come up with anything.~~  After noticing how similar this code was to `resolveTypeFully`, I copied over the style from that function and am much more convinced of the correctness of this change.
Closes #14063
=> Fix #14063

build.zig, src/Sema.zig
I did not find many tests under the `test/` directory wrt `linksection` if anyone has directions on how they want this tested I'm definitely willing to put in the work breaking ground on some testing facilities.
In addition to the section name I changed the `compile` step to depend on stage3's install step. This way when building zig using cmake (I'm linking to LLVM because I'm primarily testing this on embedded targets) it'll be under `zig-out`, instead of having to find it in the build cache.
=> @export() with linksection option

lib/std/target.zig
Earlier in https://github.com/ziglang/zig/blob/cf822c6ddd7e56b248ab217d38907aad38935b2f/lib/std/zig.zig#L198 I saw we already specify a file extension there so at least for now this is probably better than before. It's probably the same file extension as there.
=> std.Target.ObjectFormat: specify dxcontainer file ext

src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, test/behavior/struct.zig
* Remove typed pointers and pointer bitcasts from `llvm.zig`.
* Add asserts and tests for the rest of #14063, which no longer crashes due to not needing to lower the pointee types of function parameters.
Closes #14063
=> llvm: remove unnecessary code for opaque pointers

src/arch/aarch64/CodeGen.zig, src/arch/aarch64/abi.zig, src/arch/aarch64/bits.zig, test/behavior/alignof.zig, test/behavior/basic.zig, test/behavior/bitcast.zig, test/behavior/byval_arg_var.zig, test/behavior/call.zig, test/behavior/error.zig, test/behavior/field_parent_ptr.zig, test/behavior/fn.zig, test/behavior/if.zig, test/behavior/math.zig, test/behavior/merge_error_sets.zig, test/behavior/null.zig, test/behavior/pointers.zig, test/behavior/ptrcast.zig, test/behavior/sizeof_and_typeof.zig, test/behavior/slice.zig, test/behavior/struct.zig, test/behavior/struct_contains_slice_of_itself.zig, test/behavior/type_info.zig, test/behavior/undefined.zig, test/behavior/underscore.zig, test/behavior/union.zig, test/behavior/void.zig, test/behavior/while.zig
- Unify set of callee-preserved registers on all targets (previously, `x19` was erroneously excluded in macOS)
- Implement `field_parent_ptr`
=> stage2 AArch64: small improvements

cmake/Findllvm.cmake
Pull request https://github.com/ziglang/zig/pull/12136 has greatly improved LLVM search logic for CMake (kudos to @topolarity !). HOWEVER, it caused following regression: https://bugs.gentoo.org/886569. So, when targets is missing for LLVM, it prints:
```
CMake Error at cmake/Findllvm.cmake:90 (continue):
A CONTINUE command was found outside of a proper FOREACH or WHILE loop
scope.
Call Stack (most recent call first):
cmake/Findllvm.cmake:93 (NEED_TARGET)
CMakeLists.txt:138 (find_package)
```
I thought that this function should be macro instead so that this body replaces all occurencies of  NEED_TARGET. HOWEVER 😄 , `continue()` does not work in macro: https://gitlab.kitware.com/cmake/cmake/-/issues/22052.
This PR moves "checking if llvm-config supports all what we need" in separate …
=> cmake: check llvm-config in separate function, fix cmake error

src/main.zig
Adds support for `-undefined error` in addition to `-undefined dynamic_lookup` added in #13991. 
`error` is the default behavior: fail of an undefined symbol is referenced. An explicit `-undefined error` is useful to reverse a previous `-undefined dynamic_lookup` on the command line (e.g.., in some set of base flags that are being appended to).
Fixes #14046
=> Add support for -undefined error

ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, test/cases/compile_errors/cImport_with_bogus_include.zig
These tarballs were built with `-DLLVM_ENABLE_ASSERTIONS=ON`.
=> CI: update x86_64 and aarch64 LLVM tarballs with assertions enabled

lib/std/io/buffered_reader.zig
See also commit 7287c7482a2c694c7c7f56b9f7c1744a7ae7905f where LinearFifo is removed from BufferedWriter
Basically, LinearFifo does extra work v. copying bytes and increasing an offset.
---
I wrote a clone of [runiq](https://github.com/whitfin/runiq), [zuniq](https://github.com/hwchen/zuniq), and was surprised `zuniq` was slower by quite a bit. On my test data set, runiq's read + filter + write had about the same time as just zuniq's read.
Just to give a broad idea of the speedup, here's some timings of before/after. (`patched` is the version run against the changes in this PR). I'm running ubuntu 20.04 on amd64 (ryzen).
```
zuniq on  main [+1] > just bench scratch/test-data.txt
zig build install -Drelease-fast -p zig-out
zig build install -Drelease-fast -p zig-out/patched --zig-lib-dir …
```
=> std: stop using LinearFifo in BufferedReader

src/target.zig
This will prevent unused argument warnings when compiling C objects targeting powerpc.
=> powerpc does not have a red zone

lib/std/debug.zig
Fixes #13020 by replacing tabs with spaces when printing a line.
The examples from #13020 now produce the expected behaviour:
`@panic`:
```
thread 28938 panic: 
/home/mint/Desktop/test.zig:2:2: 0x20b5f3 in main (test)
@panic("");
^
```
`@errorReturnTrace()`:
```
error: Trace: 
[...]
/home/mint/Desktop/test.zig:4:6: 0x20d759 in someFunction (test)
_ = try std.math.mul(u32, std.math.maxInt(u32), 2);
^
```
I would have added a test case for this, but that's impossible because the CI runs `zig fmt --check` on behaviour tests.
=> Fix caret location of `@panic` and `@errorReturnTrace()` when using tabs

lib/std/packed_int_array.zig
I have some code that needs to deserialize into a `std.PackedIntArray` and a `std.PackedIntSlice`, but that's currently not possible to do when you only have the type returned by either functions (at least, I can't see any obvious way to do so).
Just exposing the `Int` parameter is enough to let me deserialize properly though. I'd be able to write something like this:
```zig
// Assume Value is some std.PackedIntArray...
fn visitSeq(allocator: ?std.mem.Allocator, seq: anytype) !Value {
var array = Value.initAllTo(0);
if (array.len == 0) {
return array;
}
while (i < array.len) : (i += 1) {
if (try seq.nextElement(allocator, Value.Child)) |value| { // can't call this without PR.
array.set(i, value);
} else {
// End of sequence was reached early.
return error.InvalidLength; …
```
=> std: Expose Int parameter in std.PackedInt[Array,Slice]

lib/std/crypto/hkdf.zig
The HKDF extract function uses HMAC under the hood, but requiring applications to directly use HMAC functions reduces clarity and feels like the wrong abstraction.
So, in order to get the PRK length, add a `prk_length` constant that applications can use directly.
Also add an `extractInit()` function for cases where the keying material has to be provided as multiple chunks.
=> std.crypto.hkdf: add prk_length and extractInit()

lib/std/zig/parse.zig, tools/extract-grammar.zig
Move the parsing of Root from the parse function to the Parser.parseRoot method.
Add an empty line between each rule, for consistency with grammar.y.
Ensure that normal doc-comments are always on the top, for consistency.
Add extract-grammar.zig to the tools directory; it is used to extract the PEG grammar from parse.zig, so that it can be compared with grammar.y.
=> parser: ensure the documented grammar matches grammar.y

src/arch/x86_64/Emit.zig
Remove extra whitespace at the end of a line in Emit.zig, in regions where zig fmt is off.
=> x86_64: remove extra whitespace

lib/std/crypto/sha3.zig
In sponge-based constructions, the block size is not the same as the state size. For practical purposes, it's the same as the rate.
Size this is a constant for a given type, we don't need to keep a copy of that value in the state itself. Just use the constant directly. This saves some bytes and may even be slightly faster.
More importantly:
Fixes #14128
=> sha3: define block_length as the rate, not as the state size

lib/std/child_process.zig
Previously, the implementation would essentially check `startsWith` instead of `eql` (e.g. it would return true for `.exec` because it erroneously 'matched' `.exe`).
This bug had no real negative effects, the `windowsCreateProcessSupportsExtension` function is just used as an optimization to avoid evaluating extensions that we know we will fail to execute.
Follow up to #13993
=> ChildProcess: fix false positives in windowsCreateProcessSupportsExtension

lib/zig.h
GCC added `__has_builtin` in version 10 which is pretty recent. This patch makes zig.h support GCC 9.x and older, which fixes building Zig from source on many targets.
=> zig.h: support GCC compilers that lack __has_builtin

lib/std/meta.zig
This is simply a small convenience wrapper around `meta.fieldInfo(T, .field).type`. However, this operation is common enough that it makes sense to have its own function for.
Context: I've seen this question asked on Discord several times, with people often trying to do `@TypeOf(T.field)` or similar. The status quo solution of `std.meta.fieldInfo(T, .field).type` is just a little too clunky for my liking - it's actually a few characters less to do `@TypeOf(@as(T, undefined).field)`, which is definitely not nice. This function feels like a reasonable extra to include.
=> std: add meta.FieldType

lib/std/fs/path.zig
Since https://github.com/ziglang/zig/commit/d24aaf8847336e12b6571e13d57f6d112452d97d, `std.fs.path.resolve` doesn't make system calls anymore, thus made the function agnostic to actuall filesystem layout. As a result, relative path can no longer be resolved to absolute path (Not sure if they could before). Yet the behavior isn't specified in the documentation, causing https://github.com/ziglang/zig/issues/14010.
Related: https://github.com/ziglang/zig/issues/14010
=> docs: Clarify that `std.fs.path.resolve` doesn't resolve relative path to absolute path

doc/langref.html.in
Closes #13837
Have not been able to test since I don't know how to build the language reference. docgen.zig seems to generate only a massive code file, not an html page.
=> Document tuple syntax

lib/docs/index.html
`<S-s>` is not bound and shortcuts popup already use lowercase.
=> autodoc: show binding in lowercase

build.zig
This pads the install names area in final (stage3) zig executable on macos. The executable size grows by 4096 bytes, or roughly 0.002% .
closes #13388
=> stage3 macos: enable -headerpad_max_install_names

src/arch/aarch64/CodeGen.zig, test/behavior/basic.zig, test/behavior/error.zig
This enables us to use more efficient loading and storing for these small stack items
cc @kubkon
=> stage2 AArch64: bump up alignment of stack items fitting in regs

lib/std/heap/arena_allocator.zig
Implements a method to reset the arena allocator and provider a variant that allocates less in the next iteration of the arena use. This is especially useful for an application that allocates temporaries in a loop.
=> Implements std.ArenaAllocator.reset()

lib/std/builtin.zig, lib/std/target.zig, src/Sema.zig, src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/codegen/spirv.zig
I didn't test this on real hardware yet, but after looking at the LLVM IR it seems to be working.
```zig
var a: u16 addrspace(.data) = 11;
var b: u16 addrspace(.program) = 22;
var c: u16 addrspace(.data) = 0;
pub export fn _start1() callconv(.C) noreturn {
c = a + b;
while (true) {}
}
```
compiles to:
```llvm
@foo.a = internal unnamed_addr global i16 11, align 1
@foo.b = internal unnamed_addr addrspace(1) global i16 22, align 1
@foo.c = internal unnamed_addr global i16 0, align 1
; Function Attrs: minsize noredzone noreturn nounwind optsize
define dso_local void @_start1() addrspace(0) #0 {
Entry:
%0 = load i16, ptr @foo.a, align 1
%1 = load i16, ptr addrspace(1) @foo.b, align 1
%2 = add nuw i16 %0, %1
store i16 %2, ptr @foo.c, align 1
br label %Loop
Loop: …
```
=> Sema: implement AVR address spaces

doc/docgen.zig, src/Compilation.zig
Before, --color on would affect colored compile error printing but not affect terminal progress bar printing. It was intended for this option to affect both; now it does.
This causes a failure when building the language reference, which contains code for parsing terminal output and rendering HTML. Now it must be expanded to handle 'K' and 'D' codes to simulate a terminal cursor moving, and the CI will fail until that capability is added in a later commit of this branch.
I extracted this change from #13560 so that the idea is not lost but we can solve this issue separately.
=> stage2: make --color on affect progress bar too

lib/zig.h
The calls to `zig_float_from_repr` need to come after the float typedefs, otherwise it's a compile error:
```
zig\lib\zig.h(1780): error C2061: syntax error: identifier 'zig_float_from_repr_f16'
zig\lib\zig.h(1780): error C2059: syntax error: ';'
zig\lib\zig.h(1780): error C2059: syntax error: '<parameter-list>'
zig\lib\zig.h(1781): error C2061: syntax error: identifier 'zig_float_from_repr_f32'
zig\lib\zig.h(1781): error C2059: syntax error: ';'
zig\lib\zig.h(1781): error C2059: syntax error: '<parameter-list>'
zig\lib\zig.h(1782): error C2061: syntax error: identifier 'zig_float_from_repr_f64'
zig\lib\zig.h(1782): error C2059: syntax error: ';'
zig\lib\zig.h(1782): error C2059: syntax error: '<parameter-list>'
zig\lib\zig.h(1783): error C2061: syntax error: identifier …
```
=> cbe: revert movement of zig_float_from_repr to before float typedefs

src/Cache.zig, src/Compilation.zig
https://github.com/ziglang/zig/pull/13864 reverted some changes which were causing breakage if the same c file was compiled twice as part of the same compilation. This PR makes the fixes as suggested by this comment there: https://github.com/ziglang/zig/pull/13864#issuecomment-1345368976 
Changes:
- Add an assert that an exclusive lock is help to `writeManifest`, to catch this error when it happens.
- Only call `writeManifest` if an exclusive lock is held.
- Update tests to assert that a cache hit results in holding a shared lock, instead of writing the manifest
Reproduction steps for the `LockViolation`:
```
// build.zig
const Builder = std.build.Builder;
pub fn build(b: *Builder) void {
const target = b.standardTargetOptions(.{});
const mode = …
```
=> Fix another LockViolation case on Windows

lib/std/debug.zig, lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig, lib/std/os/windows/ntdll.zig
This PR implements `std.debug.walkStackWindows` as a replacement for `RtlCaptureStackBackTrace`. 
As part of debugging #12703 I was investigating why stack traces weren't appearing, and realized a simple test program that just panicked would not always print the stack trace.
Note that I'm using `zig2` here as I can't build stage3 due to #12703.
Example program:
```
fn bar() void {
@panic("test");
}
fn foo() void {
bar();
}
foo();
}
```
```
>zig2 build-exe panic.zig -target native-windows-msvc
>panic.exe
thread 24112 panic: test
>panic.exe
thread 6572 panic: test
c:\cygwin64\home\kcbanner\temp\zig_panic\panic.zig:2:5: 0x7ff7c6e31d7f in bar (panic.exe.obj)
@panic("test");
^
c:\cygwin64\home\kcbanner\temp\zig_panic\panic.zig:6:8: 0x7ff7c6e315ce in foo (panic.exe.obj) …
```
=> debug: replace RtlCaptureStackBackTrace (which was spuriously failing) with a new implementation which uses RtlVirtualUnwind instead

test/behavior.zig, test/behavior/bugs/8277.zig
Test `@sizeOf` reified unions with zero-size payload fields.
closes #8277
=> behavior: add test for #8277

lib/std/start.zig
Being able to disable the TLS initialization has two benefits:
* Most importantly it will make it possible to build Zig programs for Linux platforms that lack hardware TLS support (e.g. old ARM)
* It shaves off a bunch of bytes* for single-threaded programs that don't need TLS, which I assume is most of them not counting Dragonfly BSD and its strange syscall requirements. 
(*4608 bytes to 944 for an empty no-op program on x86-64)
~~Currently the draft simply adds an option to not initialize the TLS area. If one goes ahead and uses `threadlocal` variables anyway the program will likely crash on runtime, which is not that great.~~
Ideally the compiler would know if TLS variables are used anywhere and only add the TLS init stuff when actually needed (#2432); this option may be useful until …
=> Don't initialize thread-local storage for single-threaded builds

src/codegen/llvm.zig, test/behavior.zig, test/behavior/bugs/14198.zig
@bitCast from integer NaN representation to float NaN resulted in changed bits in float. This only happened with signaled NaN.
- added test for signaled NaN
- added tests for quiet NaN (for completeness)
closes #14198
=> llvm codegen: fix f16,f32,f64 nan bitcasts

lib/std/crypto/tlcsprng.zig, lib/std/debug.zig, lib/std/event/batch.zig, lib/std/event/loop.zig, lib/std/fs.zig, lib/std/fs/file.zig, lib/std/io.zig, lib/std/log.zig, lib/std/start.zig, lib/std/std.zig, lib/test_runner.zig, src/crash_report.zig, src/main.zig, test/behavior/pointers.zig, test/compare_output.zig, test/standalone/issue_7030/main.zig, test/standalone/issue_9693/main.zig
Putting all of the options in one namespace makes it easier to find what can be tweaked and results in fewer magical declarations in the root file.
=> std: collect all options under one namespace

lib/std/fs/path.zig
The resolvePosix and resolveWindows routines changed behaviour in an earlier commit so that the return value is not always an absolute path. That caused the relativePosix and relativeWindows to return a relative path that is not correct.
The change in behaviour mentioned above would cause a local cache-dir to be created in the wrong directory when --cache-dir was specified for a build.
Close #13936
=> Fix cache-dir specified on the command line

lib/zig.h
A followup to 5bd69c655d9e04102c8a64ced1215c9d69f4f03f .
For compatibility purposes clang defines __GNUC__. This broke logic where clang14 __has_builtin returns false but `|| defined(__GNUC__)` made it true.
CI did not catch this because it uses clang15. However, bootstrapping with latest apple compiler is clang14. We also want to support older clang.
=> zig.h: do not assume __GNUC__ is not clang

lib/std/build/LibExeObjStep.zig, src/Compilation.zig, src/link.zig, src/link/Elf.zig, src/main.zig
These linker flags are required to build static ELF binaries that can run under the Blink emulator.
See: https://github.com/jart/blink/issues/14
=> ELF linker: support common-page-size and max-page-size lld opts

lib/zig.h
I missed this edit in 176940b5045ff0c9b20f9951dca34b2a1bb7edc0 .
=> zig.h: do not assume __GNUC__ is not clang (#2)

lib/std/crypto/tls/Client.zig, lib/std/http.zig, lib/std/http/Client.zig
With this, I have successfully downloaded https://github.com/ziglang/zig/archive/refs/tags/0.10.0.tar.gz!
closes #14204
In order to add tests for this I need to implement an HTTP server in the standard library (#910) so that's probably the next thing I'll do.
Test drive script:
```zig
const http = std.http;
var arena_instance = std.heap.ArenaAllocator.init(std.heap.page_allocator);
const arena = arena_instance.allocator();
const gpa = arena;
const args = try std.process.argsAlloc(arena);
var client: http.Client = .{
.allocator = gpa,
};
try client.ca_bundle.rescan(gpa);
defer client.deinit(gpa);
const url = try std.Url.parse(args[1]);
var req = try client.request(url, .{}, .{});
const stdout = if (args.len >= 3)
try …
```
=> std.http.Client: support transfer-encoding: chunked

lib/std/debug.zig, lib/std/process.zig, src/main.zig
Fixes https://github.com/ziglang/zig/issues/14135
Due to the limitations of the functionality that WASI currently exposes, this isn't great from a performance perspective, but it probably doesn't matter that much and it's definitely better than just returning EnvVar not found.
=> Implement some more environment functions for WASI.

lib/std/Uri.zig, lib/std/Url.zig, lib/std/http/Client.zig, lib/std/std.zig
=> Ports zig-uri to stdlib.

src/codegen/llvm.zig
AVR has 16 bit pointers, which were not considered in this switch-case
=> Fixes bug in AVR codegen for llvm backend

lib/docs/index.html, lib/docs/main.js
This PR add dropdowns to function descriptions in the autodoc functions listing, allowing the user to see the full function description without leaving the page.
Also added _No documentation provided_ description for functions that aren't documented, as it makes the page layout more consistent.
Also fixed a bug in the markdown rendering code where half open code blocks weren't closed (that could happen if the text was sliced for the function description summary, or due to the source comment being malformed).
=> autodoc: allow function descriptions expansion

doc/langref.html.in
Previously the number of `<p>` and `</p>` where not the same.
Line 5588 has no closing tag and there is a lone tag on line 9414.
=> langref: fix unclosed and lonely tag

lib/std/os/test.zig
This test was failing for me, and the cause was my cwd had a lowercase drive letter:
Repro steps:
1. `cd c:\cygwin64\home\kcbanner\kit\zig\zig-test-tmp`
2. `zig build test-std -Dtest-filter="chdir smoke test"`
3. `try expect(mem.eql(u8, tmp_dir_path, new_cwd));` comparison fails
It ends up comparing `C:\cygwin64\home\kcbanner\kit\zig\zig-test-tmp` to `c:\cygwin64\home\kcbanner\kit\zig\zig-test-tmp`. 
Fixed by resolving the cwd as well to normalize the drive letter.
=> Fix "chdir smoke test" path comparison on Windows

lib/std/coff.zig, lib/std/debug.zig, lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig
These are some changes to reduce the amount of kernel32 calls, file reads,  and allocations required to render stack traces on windows.
The previous method would do the following for each address in the trace:
1. Two kernel32 calls to get the module list
2. For each module (until the one with the address in it is found)
1. kernel32 call to get the module info
2. If it's the correct module:
- kernel32 call to get it's filename
- Read the file from disk and parse Coff
Instead, now when the debug info is created, we make a call to `kernel32.CreateToolhelp32Snapshot` to snapshot the module list. The set of module sizes/base addrs is then copied. 
Then, the address -> module lookup changes to:
1. Iterate the cache to find the base addr of the module
2. Using the base address, use the Coff …
=> Windows debug info lookup improvements

lib/std/net.zig
Fixes #14244.
`linuxLookupName` does not correctly return loopback addresses when given localhost names, instead asking DNS first. RFC 6761 section 6.3 says that DNS should not be asked about localhost names.
Fully qualified localhost names also were not caught.
=> std.net: check for localhost names before asking DNS

lib/std/os/uefi/pool_allocator.zig
Closes #14191
This PR changes the interface to align with the new allocator interface. A bug was also fixed where the UEFIPoolAllocator was not allocating enough memory for the metadata and aligning of the pointer.
=> UEFI pool allocator changes and fixes

lib/libc/wasi/emmalloc/emmalloc.c
The symbol was introduced in LLD 15.0.7, as a way to know how much memory can be allocated:
https://github.com/llvm/llvm-project/commit/1095870e8ceddc5371f446f4e7c3473f89a461cd 
https://github.com/WebAssembly/wasi-libc/pull/377
=> wasi-libc: use __heap_end if available

lib/std/fmt/errol.zig
I noticed a program was segfaulting when formatting a number, which seemed weird. It only happens when you enable DAZ (denormals are zero) because errolSlow tries to use floating point math to format the number. If the number is a denormal this math will not work as expected, and the digit generating loop will run over the end of the buffer.
Issue demo: https://godbolt.org/z/Tn37a4d6K
=> Fix buffer overflow in fmt when DAZ is set

src/link.zig, src/link/Wasm.zig, src/link/Wasm/types.zig
This implements the remaining features left to allow the in-house linker to link with WASI-libc. This means we now support c constructors in the form of `__wasm_call_ctors` which will call each constructor based on its priority. It also creates symbols for `__heap_base` and `__heap_end` when any of the linked object files reference the symbol. Those symbols are then used to perform relocations so the runtime knows where the heap starts and ends. This is useful to know for allocators such as sbrk.
=> wasm-linker: implement linking with WASI-libc

build.zig, src/arch/x86_64/abi.zig, src/codegen/llvm.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig, test/tests.zig
Trying to match what clang outputs while keeping the classification system similar to the documentation is somewhat difficult. I don't know how it'll be with the self-hosted backend but maybe it'd be better to just do our own thing?
=> float related C ABI fixes

build.zig
https://github.com/ziglang/zig/commit/741445ce298df5136553802f2681ca8dc5ad596f started linking zig's libcpp on windows, but `libcxxabi` can't build under msvc.
Fixes: https://github.com/ziglang/zig/issues/11777
Related: https://github.com/ziglang/zig/issues/5312
=> build: avoid zig's libc++ on *-windows-msvc

src/type.zig, test/behavior/typename.zig
The zig grammar expects the alignment expression of a function prototype before the calling convention, but printing the type will show the calling convention first.
```zig
test {
// this shouldn't fail
try expectEqualStrings(
@typeName(fn () align(2) callconv(.C) void),
"fn() align(2) callconv(.C) void"
);
}
```
Also, there is no space between `fn` and the parameter decls even though `zig fmt` will put a space there. Don't know if this is intentional or should also be changed.
=> swap align and callconv in function typeName

lib/std/mem.zig
Fixes #14115
First commit is the minimum change to fix.
Second commit changes the implementation to initialize each field of the struct exactly once.
=> std: Handle field struct defaults in std.mem.zeroInit

lib/std/crypto/Certificate/Bundle.zig, lib/std/crypto/Certificate/Bundle/macos.zig, lib/std/io/reader.zig, src/Autodoc.zig, src/link/MachO/fat.zig
Closes #14169
References:
- https://github.com/libyal/dtformats/blob/main/documentation/MacOS%20keychain%20database%20file%20format.asciidoc
- https://github.com/n0fate/chainbreaker/blob/master/chainbreaker/schema.py
- https://gist.github.com/williballenthin/d6bf9f1553d9fa27e0cc6880a6d992b4
- https://repo.zenk-security.com/Forensic/Keychain%20Analysis%20with%20Mac%20OS%20X%20Memory%20Forensics.pdf
=> Find system-installed root SSL certificates on macOS

lib/std/os/linux/io_uring.zig, src/Module.zig, src/Sema.zig, src/codegen/llvm.zig, src/type.zig, test/behavior/struct.zig
This is a simple starting version of the optimization described in #168 where the fields are just sorted by order of descending alignment.
=> Sema: automatically optimize order of struct fields

lib/std/http/Client.zig, src/main.zig
After this change, the system will be inspected for root certificates only upon the first https request that actually occurs. This makes the compiler no longer do SSL certificate scanning when running `zig build` if no network requests are made.
=> std.http.Client: default to lazy root cert scanning

lib/std/crypto/Certificate.zig, lib/std/crypto/Certificate/Bundle.zig, lib/std/net.zig, lib/std/os/windows.zig, lib/std/os/windows/crypt32.zig
Closes #14170
Works as expected.
Any code reviews are pleased.
=> windows root certificate scanning

doc/langref.html.in
Add the new addrspace keyword in the Keyword Reference section, without documentation.
Move the linksection keyword in order to keep the keywords list sorted.
=> langref: add the new addrspace keyword

doc/langref.html.in
The current compiler ignores the UTF-8 BOM if it is at the start of the file, and disallows it anywhere else.  Document it in the Source Encoding section.
=> langref: document UTF-8 BOM handling

lib/std/zig/tokenizer.zig, src/AstGen.zig, src/Sema.zig, src/codegen/llvm.zig, test/behavior/packed-struct.zig, test/behavior/pointers.zig, test/behavior/switch.zig, test/behavior/type_info.zig, test/c_abi/main.zig, test/cases/compile_errors/invalid_store_to_comptime_field.zig, test/cases/f32_passed_to_variadic_fn.zig
@star-tek-mb if you can try building master with the Windows C ABI commit applied to see if it fixes the issues you're seeing.
=> Misc fixes

lib/std/c/netbsd.zig, lib/std/debug.zig, src/crash_report.zig
- test `lib/std/std.zig` passes
- stack traces work
=> netbsd: add mcontext_t for aarch64

doc/langref.html.in
In the Hello World section, replace the term "anonymous struct literal" with tuple, when documenting the second argument of stdout.print().
=> langref: use the term tuple in the Hello World section

lib/std/process.zig
I was testing this with wazero, which defaults to not propagate any env variables. This ensures we don't try to allocate zero length buffers when there are no results from either function.
=> wasm: avoids allocating zero length buffers for args or env

lib/std/os/windows/user32.zig
Fixes error with function pointers.
Code:
```zig
_ = try std.os.windows.user32.messageBoxW(null, std.unicode.utf8ToUtf16LeStringLiteral("hello"), std.unicode.utf8ToUtf16LeStringLiteral("world"), 0);
```
Before:
```
.local/zig/ver/zig-linux-x86_64-0.11.0-dev.1268+0e66df209/lib/std/os/windows/user32.zig:1585:48: error: unable to resolve comptime value
const function = selectSymbol(MessageBoxW, pfnMessageBoxW, .win2k);
^~~~~~~~~~~~~~
.local/zig/ver/zig-linux-x86_64-0.11.0-dev.1268+0e66df209/lib/std/os/windows/user32.zig:1585:48: note: argument to parameter with comptime-only type must be comptime-known
.local/zig/ver/zig-linux-x86_64-0.11.0-dev.1268+0e66df209/lib/std/os/windows/user32.zig:31:139: note: expression is evaluated at comptime because the generic function was instantiated with a …
```
=> stdlib: fix selectSymbol function pointers

lib/std/zig/system/NativePaths.zig
On MacOS, if we're using Nix to supply the frameworks Zig should add the frameworks paths. 
Instead we currently emit warning logs (which are a bit [noisy](https://gist.github.com/MarcoPolo/b52f6f79caefd8362bcc031c5c6b82a6)). And then potentially fail to build. Users can workaround this by manually parsing the `NIX_CFLAGS_COMPILE` and adding framework paths manually (basically what this PR does), but it would be great if we did the correct thing here.
=> Add framework paths from NIX_CFLAGS_COMPILE

lib/std/crypto/Certificate.zig
Closes #14177
The following testcase was included in the RFC spec, but not explicitly mentioned in the issue. I went ahead and implemented it.
> f*.com matches foo.com but not bar.com
Do we want to expand this to cases like `zig*ng.org` matching `ziglang.org`? I could not find any reference to it in the spec, but I imagine the above quote implying that `zig*ng.org` would need to pass as well.
=> Wildcard certs should only validate one level of sub domain

lib/std/c/windows.zig, lib/std/os.zig, lib/std/os/windows.zig, lib/std/os/windows/ntdll.zig
Recently discussed on Discord in zig-help, exactly what it says on the tin. I don't have a Windows machine on hand to confirm it works, but the logic is pretty simple and it compiles fine.
(Who designed the `VirtualProtect` API?! The protection constants are insane)
=> std: implement os.mprotect on Windows

src/codegen/llvm.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig, test/tests.zig
Experimental fix for https://github.com/ziglang/zig/issues/14355
=> llvm: passing byval structs as ptr byval(<ty>) intead of directly

lib/std/build/LibExeObjStep.zig
* no longer repeat -lc on the linker line redundantly
* when using linkLibrary() with a static library, it will now also put the static library's static library dependencies on the linker line, recursively.
* refactor out a common pattern to an addFlag function
* avoid putting static libs inside static libs
=> std.build.LibExeObjStep: better handle transitive deps

lib/std/c/freebsd.zig, lib/std/debug.zig, src/crash_report.zig
Following on from #14354.
Currently it is impossible to build zig3 due to a subprocess returning ENOTDIR, but zig2 executes fine at the moment.
What isn't disabled for test-std mostly passes, except for the copysign test. The offending line is
try expect(copysign(@as(T, 6.0), -math.nan(T)) == -6.0);
where T is f16. The return value is positive 6.0. I've confirmed this only happens for f16.
=> FreeBSD: add mcontext_t for aarch64

lib/std/compress.zig, lib/std/compress/gzip.zig
From [RFC 1952](https://tools.ietf.org/rfc/rfc1952.txt):
> If FHCRC is set, a CRC16 for the gzip header is present, immediately before the compressed data. The CRC16 consists of the two least significant bytes of the CRC32 for all bytes of the gzip header up to and not including the CRC16.
=> Implement gzip header CRC check

lib/std/build/InstallArtifactStep.zig
Rename the full_pdb_path variable to full_h_path, in the InstallArtifactStep.make method.
=> build: fix incorrect name in InstallArtifactStep

src/Compilation.zig, src/Module.zig, src/Package.zig, src/Sema.zig, src/main.zig, src/test.zig
Previously, if a source file was referenced from multiple packages, it just became owned by the first one AstGen happened to reach; this was a problem, because it could lead to inconsistent behaviour in the compiler based on a race condition. This could be fixed by just analyzing such files multiple times - however, it was pointed out by Andrew that it might make more sense to enforce files being part of at most a single package. Having a file in multiple packages would not only impact compile times (due to Sema having to run multiple times on potentially a lot of code) but is also a confusing anti-pattern which more often than not is a mistake on the part of the user.
This PR also changes how errors are formatted slightly. Previously, `entire_file` module errors were turned into `plain` …
=> AstGen: detect and error on files included in multiple packages

doc/docgen.zig, doc/langref.html.in
Update the genToc funtion to make the name required in the Code node, and add an additional optional field for the expected error, to use with test_err, test_safety and obj_err.
Update langref.html.in to ensure all code blocks have a name that
- is unique, so that a doctest can be identified by it
- is descriptive
For test, test_err and test_safefy, ensure that the doctest name starts with "test_", excluding doctests in the "Zig Test" section and doctests that are imported by other doctests.
Ensure that the indentation of code_begin and code_end blocks are consistent.
Fix a typo in pointer_arthemtic.
=> docgen: make the name required in the Code node

doc/langref.html.in
In commit 3542dbf0ea5 (langref: add section numbers) I accidentally added an extra closing curly bracket at the end of the style element.
Sorry for not validating the HTML file before creating the PR.
=> langref: remove extra curly bracket in the CSS

lib/std/debug.zig, lib/std/fs.zig, lib/std/net.zig, lib/std/os.zig, lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig, lib/std/pdb.zig, lib/std/zig/system/NativeTargetInfo.zig
This fixes a bug in std.net caused during the introduction of meta.assumeSentinel due to the unfortunate semantics of mem.span()
This leaves only 3 remaining uses of meta.assumeSentinel() in the standard library, each of which could be a simple @ptrCast([*:0]T, foo) instead. I think this function should likely be removed.
See also #14383, #14417
=> std: eliminate pointless meta.assumeSentinel() usage

lib/std/os/uefi/tables/boot_services.zig
https://uefi.org/specs/UEFI/2.10/07_Services_Boot_Services.html#efi-boot-services-getmemorymap
=> [UEFI] Delete unnecessary padding and fix number_of_pages type

lib/std/debug.zig
I believe the leaks here were fixed by https://github.com/ziglang/zig/pull/14247
Fixes https://github.com/ziglang/zig/issues/13963
=> debug: re-enable resource management test on x86_64 windows

lib/compiler_rt/divxf3.zig
I went to check what was wrong here, but the test is now passing on windows.
Closes https://github.com/ziglang/zig/issues/12603
=> compiler_rt: re-enable divxf3 test on windows/llvm

lib/std/fs.zig, lib/std/meta.zig, lib/std/os/linux/vdso.zig
All but 3 callsites of this function in the standard library and compiler were unnecessary and were removed in faf2fd18.
In this commit, the remaining 3 callsites are removed. One of them turned out to also be unnecessary and has been replaced by slicing directly with the length..
The 2 remaining callsites were in the very pointer-math heavy std/os/linux/vdso.zig code which should perhaps be refactored to better utilize slices. These 2 callsites are replaced with a plain @ptrCast([*:0]u8, ptr) though could likely use std.mem.sliceTo() if the surrounding code was refactored.
=> std: remove meta.assumeSentinel

lib/std/build/LibExeObjStep.zig
Currently when building a zig executable through build.zig with the red zone flag disabled, it gives an error:
```
error: unrecognized parameter: '-fno-red-zone'
```
This fixes it.
=> build: Fix red zone flag

lib/build_runner.zig, lib/std/build.zig, lib/std/build/InstallDirStep.zig, lib/std/build/InstallFileStep.zig, lib/std/build/LibExeObjStep.zig
This function is needed when a library exposes one of its own library dependency's headers as part of its own public API.
Also, improve error message when a file system error occurs during install file step.
Real world motivation: https://github.com/andrewrk/libgroove/commit/9566fce65b822c57f052e749820a38e739ab0ea9
=> zig build system: add LibExeObjStep.installLibraryHeaders

src/link/Elf.zig, src/link/MachO/DebugSymbols.zig
Otherwise, we were risking having strtab zero-sized and overlap with another section.
=> elf+macho: append null to DWARF strtab to avoid overlapping sects

doc/langref.html.in
In the "C Translation CLI" section, move the paragraph inside the p element.
The current HTML is valid, but, as an example, a paragraph outside a p element is not handled correctly by the browser Inspect tool.
=> langref: move paragraph inside the p element

doc/langref.html.in
Add more coercion examples to test_coerce_unions_enums.zig in the
"Type Coercion: unions and enums" section.
=> langref: improve test_coerce_unions_enums.zig

doc/langref.html.in
@Type is currently available for Functions.
=> langref: update the documentation of @Type

doc/langref.html.in
In the "Type Coercion" section, rename:
- Coercion Float to Int => Float to Int
- unions and enums => Unions and Enums
- tuples to arrays => Tuples to Arrays
=> langref: make "Type Coercion" subsections more consistent

src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/MachO.zig, src/link/Plan9.zig, src/link/Wasm.zig
* remove unused `externally_managed` prong for Decls' code - even if we did find a use for it, we would need to redesign it to account for relocations applied by the linker, i.e., make it mutable one way or another
* rename `Result.appended` to `Result.ok` as we do not really care how the linker/codegen handled it
=> self-hosted: cleanup codegen.Result

lib/test_runner.zig
This will allow users to have more informative outputs when they run in-Wasm unit tests:
```
$ zig test -target wasm32-wasi --test-cmd wasmtime --test-cmd run --test-cmd-bin --zig-lib-dir ../ziglang/lib test.zig
0 passed; 0 skipped; 2 failed.
test failureError: failed to run main module `/XXX/zig-cache/o/22440a85b93b9bbbacf5235da2ee1591/test.wasm`
Caused by:
0: failed to invoke command default
1: error while executing at wasm backtrace:
0:  0x2ab - <unknown>!os.abort
1:  0x17e - <unknown>!builtin.default_panic
2:  0x819 - <unknown>!test_runner.main
3:  0x79d - <unknown>!_start
note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information
2: wasm trap: wasm `unreachable` instruction executed
error: the following test command failed with exit code …
```
=> wasm: uses main instead of main2 for test runner

lib/std/os.zig
This was introduced in https://github.com/ziglang/zig/commit/b37acc4d6870a090c3501d81d3f647bc30220e4b as a workaround, but it shouldn't be needed anymore (all the runtimes should be able to handle exit(1) properly, and the `unreachable` is in any way inserted _after_  proc_exit). This makes the code aligned with other platforms.
=> wasi: remove unnecessary breakpoint() in abort

lib/std/json.zig, lib/std/json/test.zig
In `std.json` check the output and source lengths before doing `mem.copy`.
=> std.json: check output and source lengths in `std.json`

src/Module.zig, src/Sema.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/link.zig, src/link/Coff.zig, src/link/Coff/Atom.zig, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/Plan9.zig, src/link/Wasm.zig, src/link/Wasm/Atom.zig
TODO:
After this is done, I will move ownership of `Atom`/`TextBlock`/`DeclBlock` from `Module` into the backends, and instead, the `Module` will be handed out an index by the respective backend. Just to be clear, I will work on this in a separate patch.
=> self-hosted: remove allocateDeclIndexes from the linker API

lib/std/os.zig
Problem :  
Having a simple loop that does this -
sock = accept()
.. do stuff
std.os.sendfile(sock, ...)
It is possible for accept() to return a valid socket fd, but the socket can disconnect before the sendfile starts or completes.
Current handling of this in std.os is to call unreachable ... which in turns kills the server app.
Other code in the same file handles the .NOTCONN condition by returning a SocketNotConnected (for Recv errors) or BrokenPipe (for write errors where the connection dies)
This patch changes the handling of the .NOTCONN condition on std.os.sendfile() to return error.BrokenPipe rather than doing a panic / unreachable.
Testing:
Naiive test - run an app that does the simple loop, and hammer it with a flood of requests. Observe that it panics shortly into the flood. …
=> On std.os.sendfile, return error rather than unreachable on brokenPipe condition

lib/std/c.zig, lib/std/c/netbsd.zig
The system linker shows warning when `msync` is linked instead of `__msync13`:
"warning: reference to compatibility msync(); include <sys/mman.h> for correct reference"
closes #14422
=> netbsd: use versioned __msync13 from libc

lib/std/os/uefi/pool_allocator.zig
Needed a fixed integer type on the LHS and the RHS to be of the right width.
=> std.os.uefi: fix shift in pool allocator

lib/std/Thread.zig, lib/std/bounded_array.zig, lib/std/cstr.zig, lib/std/fs.zig, lib/std/io/fixed_buffer_stream.zig, lib/std/mem.zig, src/link/MachO/load_commands.zig, src/main.zig, test/behavior/basic.zig
These functions are currently footgunny when working with pointers to arrays and slices. They just return the stated length of the array/slice without iterating and looking for the first sentinel, even if the array/slice is a sentinel terminated type.
From looking at the quite small list of places in the standard library/compiler that this change breaks existing code, the new code looks to be more readable in all cases.
The usage of std.mem.span/len was totally unneeded in most of the cases affected by this breaking change.
We could remove these functions entirely in favor of other existing functions in std.mem such as std.mem.sliceTo(), but that would be a somewhat nasty breaking change as std.mem.span() is very widely used for converting sentinel terminated pointers to slices. It is …
=> std: restrict mem.span() and mem.len() to sentinel terminated pointers

lib/std/testing.zig
Close #12451
Deeply equal is defined as follows:
- Primitive types are deeply equal if they are equal using  `==` operator.
- Struct values are deeply equal if their corresponding fields are deeply equal.
- Container types(like Array/Slice/Vector) deeply equal when their corresponding elements are deeply equal.
- Pointer values are deeply equal if values they point to are deeply equal.
=> std: add expectEqualDeep

lib/std/zig/parser_test.zig, lib/std/zig/render.zig
running `zig fmt` on a file that ends with a multi line comment without a line break afterwards would previously trip an assertion or produce malformed output.
=> zig fmt: fix file ending in a multi line comment

lib/std/target.zig
This was working around a stage1 compiler bug.
=> std.Target: remove workaround

lib/std/os/uefi/pool_allocator.zig
god why do we need 2 damn pull requests just to get uefi pool allocator properly working on the new allocator update on 0.11.0
=> std.os.uefi: fix shift in pool allocator (again)

src/arch/wasm/CodeGen.zig, test/behavior/cast.zig, test/behavior/optional.zig
The following code snippet would previously fail when using the native webassembly backend.
```zig
fn foo() ?[]const u8 {
return null;
}
fn bar() ?[]const u8 {
return foo();
}
comptime {
_ = bar;
}
```
Running `stage4/bin/zig build-obj example.zig -target wasm32-freestanding` would produce:
```
thread 19645 panic: reached unreachable code
/home/techatrix/zig/src/arch/wasm/CodeGen.zig:282:25: 0x1b38a09 in buildOpcode (zig)
else => unreachable,
^
/home/techatrix/zig/src/arch/wasm/CodeGen.zig:2430:27: 0x1b44658 in load (zig)
.width = abi_size * 8,
^
/home/techatrix/zig/src/arch/wasm/CodeGen.zig:2381:47: 0x1a202a0 in airLoad (zig)
const stack_loaded = try func.load(operand, ty, 0);
...
```
If I'm not mistaken the issue was that `?[]const u8` should be passed as a reference just like `[]const …
=> wasm: correctly handle optional slices

src/mingw.zig
`__LIBMSVCRT__` is still used and is distinct from `__LIBMSVCRT_OS__`
See #13384.
=> mingw: repair msvcrt-os build flags

src/translate_c.zig, test/translate_c.zig
Fixes #14387 
Just seems like an earlier block needed copying down into the expression version:
https://github.com/ziglang/zig/blob/4c116841840bfa7f0068bef23984dd832da8a54d/src/translate_c.zig#L4504-L4507
=> translate-c: Fix types on assign expression bool

doc/langref.html.in
PR #10610 addressed most of the points from #1854.  This additional paragraph and examples covers the OMISSIONS section clarifying issues about indexing into non-ASCII strings (whether valid UTF-8 or not).  I think this finally closes #1854.
=> langref: add paragraph and examples about indexing non-ASCII strings

lib/libc/mingw/misc/strtoimax.c, lib/libc/mingw/misc/strtoumax.c, lib/libc/mingw/misc/wcstoimax.c, lib/libc/mingw/misc/wcstoumax.c
this patch is from upstream, to fix `-Wdeprecated-non-prototypes` issues.
K&R-style has apparently been deprecated since even C89, and C2x will be repurposing the syntax space. this warning triggers when the change would affect the meaning of the code.
Closes #13384.
=> mingw: stop using K&R-style function definitions

lib/std/fs/file.zig, lib/std/tar.zig, src/Package.zig
This enhances Zig to use [multihash](https://multiformats.io/multihash/) for the hash field in package manifests, closing #14284.
Additionally, it adds the executable bit and file paths to package hashes, closing #14308.
Unfortunately, due to the Windows equivalent of executable permissions being a bit tricky, there is follow-up work to be done.
What is done in this commit is the hash modifications. At the fetch layer, executable bits inside packages are ignored. In the hash
computation layer, executable bit is implemented for POSIX but not yet for Windows. This means that the hash will not break again in the future for packages that do not have any executable files, but it will break for packages that do.
Or, perhaps, I could make the decision that zig packages will unconditionally erase …
=> two package hash breaking enhancements

lib/compiler_rt/README.md
This commit makes the text more dense with sources, noes the outstanding audit and adds an explanation of the table before converting everything to markdown tables.
For the status a checkmark or cross in utf8 encoding are used and the input and output sizes of all operations are given inclusive comments for understanding of the routines.
This should document all compiler_rt integer and float routines, but does not include a documentation of existing ieee floating and math routines.
=> compiler_rt: make README visually nice and improve explanations

doc/langref.html.in
In the math builtin functions documentation, remove the link to issue https://github.com/ziglang/zig/issues/4026, since it was closed by https://github.com/ziglang/zig/pull/11532.
=> langref: remove link to closed issue #4026

src/Autodoc.zig
fixed variable type in the cases like
```
var x = Z{};
```
=> autodoc: Implemented struct_init_empty for walkInstruction 

lib/std/math/big.zig, lib/std/math/big/int.zig
Underlying fix should have been https://github.com/ziglang/zig/commit/d7b029995c8ac678598de39aa106076dca232902.
u128 limb sizes are still not fully tested as we are missing compiler-rt support (__divei4, __modei4 on x86_64). Should be no zig blockers so the assertion has been removed.
=> remove stage1 workaround for big int set

lib/compiler_rt/README.md
- In Integer Bit Operations, use zeros consistently and fix the incorrect function descriptions
- In ucmp, fix the incorrect signedness of the operands
- In Integer Arithmetic, document the signedness of the operands in div, udiv, mod, umod, udivmod and divmod as it is done in LLVM documentation
- In Float Conversion, replace "int_to_float" to "int to float" and "uint_to_float" to "uint to float"
=> compiler_rt: fix and improve documentation

lib/std/meta.zig
assumeSentinel was removed and replaced with a compileError, but it's not pub, so the error message indicates it's private rather than providing the compileError message.
=> mark deprecated assumeSentinel as pub

doc/langref.html.in, tools/update_cpu_features.zig
Commit 40f5e5dfc60e removed the `--single-threaded` option, but didn't update all mentions of it.
```console
$ zig version
0.11.0-dev.1568+c9b957c93
$ zig build-exe --help | grep single
-fsingle-threaded         Code assumes there is only one thread
-fno-single-threaded      Code may not assume there is only one thread
$ zig build-exe --single-threaded foo.zig
error: unrecognized parameter: '--single-threaded'
```
=> langref, tools: rename --single-threaded to -fsingle-threaded

src/Module.zig, test/standalone.zig, test/standalone/embed_generated_file/bootloader.zig, test/standalone/embed_generated_file/build.zig, test/standalone/embed_generated_file/main.zig
=> make `@embedFile` support module-mapped names the same way as `@import`

lib/std/Build.zig, lib/std/Build/CompileStep.zig, lib/std/Build/ConfigHeaderStep.zig, lib/std/Build/TranslateCStep.zig, lib/std/Build/WriteFileStep.zig
This is a fork of #14382 with my own take on the problem.
Breaking API change to std.Build.addConfigHeader. It now uses an options
struct.
Introduce std.Build.CompileStep.installConfigHeader which also accepts
an options struct. This is used to add a generated config file into the
set of installed header files for a particular compilation artifact.
std.Build.ConfigHeaderStep now additionally supports a "blank" style
where a header is generated from scratch. It no longer exposes
`output_dir`. Instead it exposes a FileSource via `output_file`.
It now additionally accepts an `include_path` option which affects the
include path of CompileStep when using the `#include` directive, as well
as affecting the default installation subdirectory for header
installation purposes.
The hash used for the …
=> std.Build: enhancements to ConfigHeaderStep

src/link/MachO/UnwindInfo.zig
There can be a maximum of 256 compact encodings per page in compact unwind info, and we were using `u8` to represent the count which is insufficient. This commit bumps it to `u9`.
Fixes https://github.com/ziglang/zig/issues/14584
=> macho: fix incorrect representation of encodings count per page

lib/std/Build.zig
This didn't come through in #14498.
=> std.Build.addAssembly: add missing .kind

lib/std/zig/tokenizer.zig
formatting the following file would previously fail:
```zig
@"
```
```
thread 35824 panic: reached unreachable code
/opt/zig/0.11.0-dev.1580+a5b34a61a/files/lib/std/debug.zig:281:14: 0x3318cc in assert (zls)
^
/opt/zig/0.11.0-dev.1580+a5b34a61a/files/lib/std/zig/render.zig:2453:18: 0x655e01 in renderIdentifier (zls)
assert(lexeme.len >= 3);
^
/opt/zig/0.11.0-dev.1580+a5b34a61a/files/lib/std/zig/render.zig:210:36: 0x64f961 in renderExpression (zls)
return renderIdentifier(ais, tree, token_index, space, .preserve_when_shadowing);
^
/opt/zig/0.11.0-dev.1580+a5b34a61a/files/lib/std/zig/render.zig:2343:32: 0x6cf270 in renderExpressionComma (zls)
return renderExpression(gpa, ais, tree, node, space);
^ …
```
=> don't tokenize an invalid string literal

lib/compiler_rt/README.md, lib/compiler_rt/int.zig, tools/gen_stubs.zig
- Copy and adjust __divmodsi4 tests for __divmoddi4 and __divmodti4.
- Assuming d = a/b does not overflow (MIN/-1) or uses div by 0, then tmp = (d * b) = (a/b * b) = a does not overflow. => Remove wraparound for remainder in applicable routines.
=> compiler_rt: __divmodti4 for libgcc symbol compatibility

lib/build_runner.zig
Often `zig build --help` gets run just to see what top level steps are available, but the output is very noisy for this use-case (I have to scroll my terminal when doing this in the Zig repo for instance). This PR adds the `-l` and `--list-steps` options that just print the `Steps:` section of the `--help` output.
Apologies if this should have first been opened as an issue first (or my brief search for an issue missed an existing one) but it was simple enough to implement that I didn't think it was necessary.
=> zig build: add -l, --list-steps option to build_runner.zig

lib/compiler_rt/README.md
This documents the currently implemented math functions in alphabetical order and sorts the remaining items.
=> compiler_rt: document math functions

src/main.zig
=> zig fmt: additionally format .zon files

lib/std/crypto.zig, lib/std/crypto/ascon.zig, lib/std/crypto/isap.zig, lib/std/rand.zig, lib/std/rand/Ascon.zig
Ascon has been selected as new standard for lightweight cryptography in the NIST Lightweight Cryptography competition.
Ascon won over Gimli and Xoodoo.
https://csrc.nist.gov/projects/lightweight-cryptography/finalists
The permutation is unlikely to change. However, NIST may tweak the constructions (XOF, hash, authenticated encryption) before standardizing them. For that reason, implementations of those are better maintained outside the standard library for now.
In fact, we already had an Ascon implementation in Zig: `std.crypto.aead.isap` is based on it. While the implementation was here, there was no public API to access it directly.
So:
- The Ascon permutation is now available as `std.crypto.core.Ascon`, with everything needed to use it in AEADs and other Ascon-based constructions
- The …
=> std.crypto: add the Ascon permutation

doc/langref.html.in
Some examples using {#syntax_block|zig|...#} either have a valid syntax or it is easy to make the syntax valid.  Update these example to use {#code_begin|syntax|...#}.
Remove extra whitespace in the error_union_parsing_u64.zig example.
Replace size_t with usize in the call_malloc_from_zig.zig example.
=> langref: make more examples testable

lib/std/Build.zig, src/Compilation.zig, src/main.zig
Closes #691. Adds `-ferror-tracing` and `-fno-error-tracing` to the compile options. 
Specifying `-ferror-tracing` enables error tracing in ReleaseFast mode.
Specifying `-fno-error-tracing` disables error tracing in Debug and ReleaseSafe modes.
Error tracing remains permanently disabled in ReleaseSmall mode.
Example (ReleaseFast, `-ferror-tracing`): 
```
$ zig build-exe src/main.zig -ferror-tracing -OReleaseFast
$ ./main
error: AckAnotherError
/home/adam/base/src/main.zig:4:5: 0x2031a8 in main (main)
return error.OhNoAnError;
^
/home/adam/base/src/main.zig:8:24: 0x2031b0 in main (main)
return foo() catch return error.AckAnotherError;
^
/home/adam/zig/lib/std/start.zig:616:37: 0x20316e in posixCallMainAndExit (main)
const result = root.main() catch |err| {
```
Example (Debug, …
=> Add -ferror-tracing and -fno-error-tracing compile options

lib/std/c.zig
Hello. I just needed `umask` to create unix sockets with the right permissions so I added a simple line in `std.c`.
Is this okay? Should I add something else?
=> Add std.c.umask.

src/link/MachO/zld.zig
This is just a simple/hacky feature to report the source of a linking error. I found this helpful in fixing-up some of my libs when recently switching from an x86_64 to aarch64 device, so thought it might be useful to others a well before zld has a fully featured error reporting system.
=> Zld: Report archive file with cpu arch mismatch

src/Compilation.zig, src/link.zig, src/link/Elf.zig, src/main.zig
Tested by: created a "hello world" C file and compiled with:
zig cc -v main.c -Wl,--sort-section=name -o main
... and verified the `--sort-section=name` is passed to ld.lld.
Refs https://github.com/zigchroot/zig-chroot/issues/1
=> [elf linker] add --sort-section

src/main.zig
From ld.lld(1):
--sort-common
This option is ignored for GNU compatibility.
Refs https://github.com/zigchroot/zig-chroot/issues/1
=> [linker] ignore --sort-common

src/main.zig
Currently `zig cc`, when confronted with a linker argument it does
not understand, skips the flag and emits a warning.
This has been causing headaches for people that build third-party
software (including me). Zig seemingly builds and links the final
executable, only to segfault when running it. Emiting a warning and
"successfully" compiling a binary breaks autoconf assumptions.
See https://github.com/zigchroot/zig-chroot/issues/1 for a recent
painful example.
If there are linker warnings when compiling software, the first thing we
have to do is add support for ones linker is complaining, and only then
go file issues. If zig "successfully" (i.e. status code = 0) compiles a
binary, there is instead a tendency to blaim "zig doing something
weird". (I am guilty of this.) In my experience, …
=> [all linkers] fail hard on unsupported flags

src/value.zig, test/behavior/comptime_memory.zig
This was put together to enable some code written for [MicroZig](https://github.com/ZigEmbeddedGroup/microzig).
Question: Do tagless unions have some sort of hidden tag for safety checks?
=> bitcast packed unions to integers

lib/std/Build/RunStep.zig
RunStep is supposed to auto-detect whether the intend is for side-effects or for producing an output file. The auto-detection logic was incorrect, and this commit fixes it.
I tested this manually locally. Automated testing will require a more significant investment in the test harness, which I will work on in a future enhancement.
closes #14666
=> std.Build.RunStep: fix default caching logic

doc/langref.html.in, lib/std/zig/Ast.zig, lib/std/zig/tokenizer.zig, src/AstGen.zig, test/compare_output.zig, test/compile_errors.zig
Taking guidance from: ziglang/zig-spec#38, carriage returns are now allowed preceding line-feeds when found in doc-comments or multiline strings. The CRLF is also only interpreted as a newline in this case. However - they are otherwise rejected when found in any other context except when used as plain whitespace.
This resolves #11414 and resolves #12674. It replaces #12692 which is a part of this PR.
Ideally the error reporting should be improved by #12449 sometime in the future, but I think I might take a look at that once this has been merged.
=> Correctly handle carriage return characters according to the spec

lib/std/Build/CompileStep.zig, lib/std/fs/test.zig, lib/std/fs/wasi.zig
While working on Wazero, we learned that Zig's behavior is for `cwd()` to always point at `fd=3`, i.e. the first given preopen. However, if multiple preopens are available, there is currently no predefined library function to look through all of them. 
For instance, consider the case when `/` and `/tmp` are both preopened, and `/` resolves to `a`, and `/tmp` resolves to `b`.
If you just naively invoke `std.fs.openIterableDir("/tmp/blah.txt", .{})` the file `blah.txt` will be looked under `a/tmp/blah.txt` instead of, `b/blah.txt`
Since `wasi-libc` seems to be doing [a prefix search where the longest match wins](https://github.com/WebAssembly/wasi-libc/blob/a02298043ff551ce1157bc2ee7ab74c3bffe7144/libc-bottom-half/sources/preopens.c#L189-L192), we'd like to propose an API to look up an …
=> wasi: add Preopens.findDir, update tests to preopen `/tmp'

src/Sema.zig, src/arch/wasm/CodeGen.zig, src/codegen.zig, src/value.zig, test/cases/compile_errors/bitCast_same_size_but_bit_count_mismatch.zig, test/cases/compile_errors/bitCast_with_different_sizes_inside_an_expression.zig
This is in direct contradiction to parts of #9646 and these two test cases https://github.com/ziglang/zig/blob/master/test/behavior/comptime_memory.zig#L319-L371.
As discussed in the self hosted compiler meetings the justification for this is change is that it seems like a lot of work for little value and making it an error also avoids the complications brought by comptime only types.
cc @SpexGuy 
Closes #11211
=> Implement `writeToMemory`/`readFromMemory` for pointers

lib/std/Build/EmulatableRunStep.zig, lib/std/Build/RunStep.zig, lib/std/os.zig, lib/std/start.zig, lib/std/std.zig, test/link/macho/dead_strip_dylibs/build.zig, test/src/compare_output.zig, test/standalone.zig, test/standalone/sigpipe/breakpipe.zig, test/standalone/sigpipe/build.zig
This PR modifies `start.zig` to tell the kernel to ignore SIGPIPE before
calling main.  This can be disabled by adding this to the root module:
```zig
pub const keep_sigpipe = true;
```
`SIGPIPE` is triggered when a process attempts to write to a broken pipe.
By default, SIGPIPE will terminate the process without giving the program
an opportunity to handle the situation.  Unlike a segfault, it doesn't
trigger the panic handler so all the developer sees is that the program
terminated with no indication as to why.
By telling the kernel to instead ignore SIGPIPE, writes to broken pipes
will return the EPIPE error (error.BrokenPipe) and the program can handle
them like any other error.
=> ignore SIGPIPE by default

lib/compiler_rt.zig, lib/compiler_rt/README.md
Justifications
- compiler_rt base routines are almost finished, so make 1:1 mapping of code and documentation.
- Make adjustments to code + documentation simpler to prevent technical or documentation debt.
=> compiler_rt: restructure compiler_rt.zig according to README.md

lib/docs/main.js
Both [original Markdown](https://daringfireball.net/projects/markdown/syntax#list) and [CommonMark](https://spec.commonmark.org/current/#lists) require at least one space or tab between the list marker and any following content.  Following this allows starting a line with a negative number or one with a decimal point.
I am unaware of the history but for some reason ordered lists are rendered as unordered.  The second patch adds support for `<ol>` rendering.
=> autodoc: fix markdown list rendering

src/main.zig
`lld` accepts both syntaxes, but we were rejecting (and, before 3f7e9ff597a3514bb1c4f1900027c40682ac9f13, ignoring) the former.
In particular, `cargo-zigbuild` was broken since Rust unconditionally [adds](https://github.com/rust-lang/rust/blame/7aa413d59206fd511137728df3d9e0fd377429bd/compiler/rustc_codegen_ssa/src/back/linker.rs#L761) `-znoexecstack` (not `-z noexecstack`) on non-Windows platforms.
=> Linker: -z<arg> should be equivalent to -z <arg>

lib/std/mem.zig
The parameter could be confused with a prefix or suffix, instead of a set of values.
=> trim(Left|Right): clarify that values_to_strip is a set

lib/std/child_process.zig
All the code for this function already exists, but only ChildProcess.exec was allowed to use the code.
=> Introduce ChildProcess.collectOutput

lib/std/sort.zig
Forcing the key to be of the same type as the sorted items used during
the search is a valid use case.
There, however, exists some cases where the key and the items are of
heterogeneous types, like searching for a code point in ordered ranges
of code points:
```zig
const CodePoint = u21;
const CodePointRange = [2]CodePoint;
const valid_ranges = &[_]CodePointRange{
// an ordered array of ranges
};
fn orderCodePointAndRange(
context: void,
code_point: CodePoint,
range: CodePointRange
) std.math.Order {
_ = context;
if (code_point < range[0]) {
return .lt;
}
if (code_point > range[1]) {
return .gt;
}
return .eq;
}
fn isValidCodePoint(code_point: CodePoint) bool {
return std.sort.binarySearch(
CodePointRange,
code_point,
valid_ranges,
void,
orderCodePointAndRange
) != null;
}
```
It is so …
=> Relax `std.sort.binarySearch` requirements

build.zig, lib/std/Build/WriteFileStep.zig
And additionally support writing files to source files. This means a custom build step in zig's own build.zig is no longer needed for copying zig.h because it is handled by WriteFileStep.
=> std.Build.WriteFileStep: integrate with cache system

lib/std/os/windows/advapi32.zig
The current api of `RegQueryValueExW` doesn't seem to allow to have null values as `lpReserved`, `lpType`, `lpData` and `lpcbData`. It however should by looking at the [win32 docs](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regqueryvalueexw):
=> fix RegQueryValueExW api

lib/zig.h, src/codegen/c.zig, src/codegen/c/type.zig, src/link/C.zig, src/target.zig, test/behavior/field_parent_ptr.zig, test/behavior/packed-struct.zig, test/behavior/pointers.zig, test/behavior/var_args.zig
* `@fieldParentPtr` of a union
* pointers to generic functions
* c varargs
* partial call attribute support
95% (1493/1569) on linux vs the llvm backend
=> CBE: fix more behavior tests

src/codegen/c.zig, src/codegen/c/type.zig, test/behavior/vector.zig
* use `CType` instead of `Type` for local reuse
* only-c compile now emits 27760 fewer locals
=> CBE: more `CType` improvements

src/AstGen.zig, test/cases/compile_errors/for_loop_break_value_ignored.zig, test/cases/compile_errors/while_loop_break_value_ignored.zig
If we use the `discard` result location any `break` with a value will be ignored and not checked for usage.
Closes https://github.com/ziglang/zig/issues/14684.
=> astgen: do not discard result location in for/while loops

src/Package.zig, src/main.zig
When there is a diamond dependency, reuse a *Module instead of creating a redundant one using the same build.zig file. Otherwise, the compile error "file exists in multiple modules" would occur.
cc @mlugg
=> packages: avoid creating multiple modules with same build.zig

lib/std/crypto.zig, lib/std/crypto/benchmark.zig, lib/std/crypto/keccak_p.zig, lib/std/crypto/sha3.zig
Make the Keccak permutation public, as it's useful for more than SHA-3 (kMAC, SHAKE, TurboSHAKE, TupleHash, etc).
Our Keccak implementation was accepting f as a comptime parameter, but always used 64-bit words and 200 byte states, so it actually didn't work with anything besides f=1600.
That has been fixed. The ability to use reduced-round versions was also added in order to support M14 and K12.
The state was constantly converted back and forth between bytes and words, even though only a part of the state is actually used for absorbing and squeezing bytes. It was changed to something similar to the other permutations we have, so we can avoid extra copies, and eventually add vectorized implementations.
In addition, the SHAKE extendable output function (XOF) was added (SHAKE128, SHAKE256). …
=> crypto.hash.sha3: make permutation generic and public, add SHAKE

lib/std/fs/file.zig
I was confused about this, so here are some doc comments to help myself and others understand in the future.
=> add doc comments to std.fs.File.default_mode

lib/std/c.zig, lib/std/fs.zig, lib/std/os.zig, lib/std/os/linux.zig, lib/std/os/test.zig
Also add `std.fs.has_executable_bit` for doing conditional compilation.
This adds the linux syscalls for chmod and fchmodat, as well as the extern libc function declarations.
Only `fchmodat` is added to `std.os`, and it is not yet added to std.fs.
=> std: add fchmodat

lib/std/child_process.zig, lib/std/process.zig, lib/std/std.zig
Previously, this API had pid, to be used on POSIX systems, and handle, to be used on Windows.
This commit unifies the API, defining an Id type that is either the pid or the HANDLE depending on the target OS.
This commit also prepares for the future by allowing one to import via `std.process.Child` which is the fully qualified namespace that I intend to migrate to in the future.
=> std.process.Child: remove pid and handle, add id

src/Sema.zig, src/target.zig
On AVR, functions need to be placed in the flash address space in order to generate correct fixups for function pointers (`R_AVR_16_PM` for fixups for flash addresses vs `R_AVR_16` for data fixups).
Fixes #14733.
=> LLVM: Place functions on AVR in flash addrspace

lib/std/Build/Cache.zig
https://github.com/ziglang/zig/pull/14762#pullrequestreview-1322648429
=> std.Build.Cache: remove 'test-filetimestamp.tmp' once timestamp returned

src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/MachO.zig, src/link/Plan9.zig, src/link/Wasm.zig, src/register_manager.zig, test/behavior/field_parent_ptr.zig
The implementations were either identical or subsets, so this has nicely deduped logic that should have been common to begin with. I envision more things being moved to `codegen.zig` in the near future.
@Luukdegram I haven't updated Wasm backend as it was doing its own thing already but feel free to plug into the common interface if you feel it makes sense.
=> codegen: move common logic for generating typed values from each native backend into codegen.zig

doc/langref.html.in
Fixes the out-of-date information about setting the build mode at https://ziglang.org/documentation/master/#Build-Mode
=> fix doc Build Mode

lib/std/os.zig, src/link.zig
In Linux when writing to various files in the virtual file system, for example /sys/fs/cgroup, if you write an invalid value to a file you'll get errno 16.
This change allows for these specific cases to be caught instead of being lumped together in `error.UnexpectedError`.
In a shell:
```
echo 3G > memory.memsw.limit_in_bytes
bash: echo: write error: Device or resource busy
```
Before this change:
```
unexpected errno: 16
/home/shadeops/opt/zig-master-llvm15/lib/zig/std/debug.zig:561:19: 0x22b9a7 in writeCurrentStackTrace__anon_6009 (write)
while (it.next()) |return_address| {
^
/home/shadeops/opt/zig-master-llvm15/lib/zig/std/debug.zig:157:80: 0x20cf63 in dumpCurrentStackTrace (write)
writeCurrentStackTrace(stderr, debug_info, detectTTYConfig(io.getStdErr()), start_addr) catch |err| {
^ …
```
=> std.os: Add DeviceBusy as a possible write error

lib/std/math/big/int.zig, lib/zig.h, src/Sema.zig, src/codegen/c.zig, src/codegen/c/type.zig, src/link/C.zig, src/type.zig, src/value.zig, test/behavior/bitcast.zig, test/behavior/bitreverse.zig, test/behavior/bugs/10147.zig, test/behavior/byteswap.zig, test/behavior/cast.zig, test/behavior/floatop.zig, test/behavior/math.zig, test/behavior/maximum_minimum.zig, test/behavior/muladd.zig, test/behavior/popcount.zig, test/behavior/select.zig, test/behavior/shuffle.zig, test/behavior/truncate.zig, test/behavior/vector.zig
C backend improvements.
* Add support for big integer literals.
* Add support for big integer and vector (oops wrong type :eyes:) operations:
* comparisons
* clz
* ctz
* popcount
* add
* sub
* Oops, add support for all of the other vector operations too.
* Pass 99% (1553/1571) of behavior tests relative to the llvm backend.
Closes #8817
=> CBE: add support for integers larger than 128 bits (and apparently vectors too)

src/AstGen.zig, test/behavior/builtin_functions_returning_void_or_noreturn.zig
So what's strange is that `@fence` and others already returned void just fine previously without these changes suggested by @Vexu in #14779. It was only really `@setAlignStack` and `@setFloatMode` that seem to have actually had this problem described in #14779 (IIRC they returned a value of type `u1`) and their return value is now fixed with this PR.
I wonder if the others were previously relying on UB? Anyway, seems safer and perhaps faster actually to just explicitly use `.void_value`.
=> AstGen: ensure certain builtin functions return void

src/codegen/llvm.zig, test/behavior/slice.zig
I would love to add a test for this, but since this is a memory bug they are super flaky and don't reliably reproduce the issue.
Closes #14715
Closes #14783
=> llvm: fix use after free with pointers to optional slices

lib/std/crypto/blake3.zig, lib/std/crypto/gimli.zig, lib/std/target.zig
Now that the C backend can codegen vectors, lets reenable them in the standard library.
=> std: reenable vectorized code with the C backend

lib/std/http/Client.zig, lib/std/os.zig, src/link.zig, src/main.zig
In Linux when interacting with the virtual file system when writing in invalid value to a file the OS will return errno 22 (INVAL).
Instead of triggering an unreachable, this change now returns a newly introduced `error.InvalidArgument`.
An example of where this can occur is with Cgroups, if you write a value to memory.memsw.limit_in_bytes that is smaller than memory.limit_in_bytes this will return an Invalid Argument.
Bash:
```
echo 1G > memory.memsw.limit_in_bytes
bash: echo: write error: Invalid argument
```
With this PR:
```
zig build run -- ./mem
Setting /sys/fs/cgroup/memory/ginkgo/ginkgo_135496/memory.memsw.limit_in_bytes to 1G
error: InvalidArgument
```
Other notes:
The reason that std.http.Client's ReadError list was updated despite this being added to the list of write errors is …
=> std.os: Allow write functions to return INVAL errors

lib/std/crypto/25519/field.zig
This helps with binary size when using, for example, tls.Client:
Before (function size = 155200 bytes):
```console
$ zig build-exe goog.zig -Dcpu=baseline
$ readelf -a goog -W |grep Fe.invert
1328: 000000000045b100 0x25e40 FUNC    LOCAL  DEFAULT    2 crypto.25519.field.Fe.invert
```
After (function size = 18088 bytes):
```console
$ zig build-exe goog.zig -Dcpu=baseline
$ readelf -a goog -W |grep Fe.invert
1329: 0000000000447fa0 18088 FUNC    LOCAL  DEFAULT    2 crypto.25519.field.Fe.invert
```
So, removes over 130kb from the function size.
=> crypto.25519.field: conditionally de-inline mul

lib/std/crypto/benchmark.zig, lib/std/crypto/keccak_p.zig, lib/std/crypto/sha3.zig
TurboSHAKE is a round-reduced version of SHAKE which is being standardized by CFRG.
It offers the same practical security as SHA3 and SHAKE. Its security builds up on the scrutiny that Keccak has received since its publication.
Unlike SHA3 (but not unlike SHAKE), the output can be of any size.
TurboSHAKE also offers higher performance - It is nearly twice as fast as SHAKE.
```
sha3-256:        571 MiB/s
sha3-512:        316 MiB/s
shake-128:        723 MiB/s
turboshake-128:       1334 MiB/s
```
Why it matters: TurboSHAKE is the fastest secure hash function we'll have in Zig when compiling for the `baseline` CPU.
Since we already had SHAKE, TurboSHAKE is a trivial addition, and it will immediately benefit from the further optimizations we'll do to Keccak.
=> std.crypto.hash.sha3: add TurboSHAKE

lib/std/fmt.zig
We already had `hexToBytes()`, but not the reverse operation.
This simplifies code that currently has to use formatters.
=> std.fmt: add bytesToHex() to encode bytes as hex digits

lib/compiler_rt/udivmodei4.zig, lib/zig.h, src/codegen/c.zig, test/behavior/int_div.zig
Unsigned integers are never less than zero, and so zig helpfully deleted the entire case. :grin:
Closes #14816
=> compiler_rt: fix rare case in udivei4

src/Module.zig, stage1/wasi.c
Multiple processes can sit waiting for the exclusive lock at the same time, so we want to recheck whether it needs to be updated whenever we get an exclusive lock.
This also fixes a race condition between one process truncating the cache file and another process reading it without atomic locking.
This could use some extra testing/review as I haven't done much testing yet.
=> Module: rewrite zir caching logic

src/link/Wasm.zig
Make our wasm linker emit the build ID,  a value that uniquely identifies a build.
It is intended to capture the "meaning" or inputs of the build, and is usually associated with debug info.
References:
- https://github.com/WebAssembly/tool-conventions/blob/main/BuildId.md
- https://github.com/WebAssembly/tool-conventions/issues/133
Support for this was also recently added to LLVM: https://github.com/llvm/llvm-project/commit/c7af9ae577bb04c5fe120fc07844a500818c8f47
=> wasm-linker: emit build_id section

lib/std/Thread.zig, lib/std/os.zig
Man page for posix lists EMFILE, man page for linux ENFILE. Also posix says "The mmap() function adds an extra reference to the file associated with the file descriptor fildes which is not removed by a subsequent close() on that file descriptor. This reference is removed when there are no more mappings to the file."
It sounds counter-intuitive, that a process limit but no system limit can be exceeeded.
As far as I understand, fildes is only used for file descriptor backed mmaps.
=> std.os: add missing mmap errors

CMakeLists.txt, build.zig
It is becoming increasingly common for distributions to want to enable PIE for all binaries and zig currently does not provide any way to do so aside from patching the build.zig.
=> build: add -Dpie option

ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh
This would have caught the problem we are seeing in #14799.
=> CI: more aggressively check zig1 bootstrapping

lib/std/crypto/sha3.zig
The TurboSHAKE paper just got published: https://eprint.iacr.org/2023/342.pdf
and unlike the previous K12 paper, suggests 0x1F instead of 0x01 as the default value for `D`.
=> TurboSHAKE: change default delimiter to 0x1F

src/Package.zig, src/main.zig
Closes #14279
This PR adds the ability to import dependencies from build.zig. We now create a tree of dependencies with the build_pkg as root. This allows for recursive dependencies importing from their own dependencies as well.
=> Add ability to import dependencies from build.zig

src/link/Wasm.zig, src/link/Wasm/Atom.zig, src/link/Wasm/Object.zig, src/link/Wasm/Symbol.zig
For data symbols, we will now store their virtual address. This means we do no longer have to calculate it each time a relocation asks for the address. 
This now also allows us directly store the virtual address of synthetic symbols without having to create an atom for them. This means we also don't need to have a "synthetic" segment any longer and do not emit the synthetic symbols such as __heap_end and __heap_base into the final binary.
This is a prerequisite for the implementation of shared memory and TLS I'm about to upstream.
=> wasm-linker: refactor virtual addresses

src/Sema.zig, test/standalone.zig, test/standalone/extern/build.zig, test/standalone/extern/exports.zig, test/standalone/extern/main.zig
* There was an edge case where the arena could be destroyed twice on error: once from the arena itself and once from the decl destruction.
* The type of the created decl was incorrect (it should have been the pointer child type), but it's not required anyway, so it's now just initialized to anyopaque (which more accurately reflects what's actually at that memory, since e.g. [*]T may correspond to nothing).
* A runtime bitcast of the pointer was performed, meaning `@extern` didn't work at comptime. This is unnecessary: the decl_ref can just be initialized with the correct pointer type.
=> Sema: @extern fixes

src/translate_c.zig, src/translate_c/ast.zig, test/translate_c.zig
Resolves: #14743
Depends on #14860 to work properly, but won't regress anything if merged sooner.
=> translate-c: translate extern unknown-length arrays using @extern

lib/std/crypto/aes/armcrypto.zig
Apple M1/M2 have an `EOR3` instruction that can XOR 2 operands with another one, and LLVM knows how to take advantage of it.
However, two `EOR`s can't be automatically combined into an `EOR3` if one of them is in an assembly block.
That simple change speeds up ciphers doing an AES round immediately followed by a XOR operation on Apple Silicon.
Before (Apple M1):
```
aegis-128l mac:      12534 MiB/s
aegis-256 mac:       6722 MiB/s
aegis-128l:      10634 MiB/s
aegis-256:       6133 MiB/s
aes128-gcm:       3890 MiB/s
aes256-gcm:       3122 MiB/s
aes128-ocb:       2832 MiB/s
aes256-ocb:       2057 MiB/s
```
After:
```
aegis-128l mac:      15667 MiB/s
aegis-256 mac:       8240 MiB/s
aegis-128l:      12656 MiB/s
aegis-256:       7214 MiB/s
aes128-gcm:       3976 MiB/s
aes256-gcm:       3202 …
```
=> crypto.aescrypto.encrypt: do not add the round key in an asm block

src/Sema.zig, test/behavior.zig, test/behavior/bugs/14854.zig
=> Sema: avoid panic on callconv(.C) generic return type

doc/langref.html.in
In 41 (Undefined Behavior) . 5 (Integer Overflow) . 3 (Builtin Overflow Functions), it is stated that
> These builtins return a bool of whether or not overflow occurred, as well as returning the overflowed bits:
> * @addWithOverflow
> * @subWithOverflow
> * @mulWithOverflow
> * @shlWithOverflow
but in their definition says that it returns a `tuple`/`struct`.
Example;
`@addWithOverflow(a: anytype, b: anytype) struct { @TypeOf(a, b), u1 }`
=> Resolve docs inconsistency with Overflow builtins

lib/std/crypto.zig, lib/std/crypto/aes/soft.zig
Our software AES implementation doesn't have any mitigations against side channels.
Go's generic implementation is not protected at all either, and even OpenSSL only has minimal mitigations.
Full mitigations against cache-based attacks (bitslicing, fixslicing) come at a huge performance cost, making AES-based primitives pretty much useless for many applications. They also don't offer any protection against other classes of side channel attacks.
In practice, partially protected, or even unprotected implementations are not as bad as it sounds. Exploiting these side channels requires an attacker that is able to submit many plaintexts/ciphertexts and perform accurate measurements. Noisy measurements can still be exploited, but require a significant amount of attempts. Wether this is …
=> Add configurable side channels mitigations; enable them on soft AES

lib/std/crypto.zig, lib/std/crypto/aes/soft.zig, lib/std/std.zig
Options have been moved to a single namespace.
Thank you Andrew for the reminder!
=> Move std.crypto.config options to std.options

src/Sema.zig, test/behavior/array.zig, test/behavior/comptime_memory.zig
See the added test case for an example of what this fixes.
Previously, if you had a pointer to multiple array elements and tried to write to it at comptime, it was incorrectly treated as a pointer to one specific array value, leading to an assertion down the line. If we try to mutate a value at an elem_ptr larger than the element type, we need to perform a modification to multiple array elements.
This solution isn't ideal, since it will result in storePtrVal serializing the whole array, modifying the relevant parts, and storing it back. Ideally, it would only take the required elements. However, this change would have been more complex, and this is a fairly rare operation (nobody ever ran into the bug before after all), so it doesn't matter all that much.
Resolves: #8304
Resolves: #10211 …
=> Sema: allow comptime mutation of multiple array elements

lib/std/http/Client.zig
Hi, thank you for working on HTTP client implementations as part of std. I'm trying to use it, but I faced one issue regarding an empty path. The current implementation doesn't allow missing trailing slashes for URLs, which should be acceptable. 
This PR fixes to accept regardless of the trailing slash, that is, both `http://example.com` and `http://example.com/`
https://gist.github.com/musaprg/b73aa918816989db7c15b7b75d214ca4#file-main-zig
environment:
- macOS 12.5 (Darwin 21.6.0 arm64)
- zig version 0.11.0-dev.1929+4ea2f441d
return 400 (bad_request)
<details><summary>execution result</summary>
```
parsed schema: http
parsed path:
parsed host: example.com
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" …
```
=> std.http: Use '/' for a empty path

lib/std/crypto/argon2.zig
=> Argon2: properly handle outputs > 64 bytes in blake2Long()

src/Sema.zig, test/cases/compile_errors/attempted_implicit_cast_from_T_to_long_array_ptr.zig
Casting `*T` to `*[1]T` should still work, but every other length will now be a compiler error instead of a potential OOB access.
=> Add error for bad cast from `*T` to `*[n]T`

lib/std/os.zig
Handle the EPERM error in the os.bind function, which can happen when binding AF_NETLINK sockets as non-root on Linux.
Return `error.AccessDenied` instead of `error.PermissionDenied`, as this seems to be the more common return convention for EPERM in os.zig.
=> std.os: handle EPERM errno for bind

src/Sema.zig, test/behavior/comptime_memory.zig
It doesn't matter if a pointer to a zero-bit (i.e. OPV) type is undefined or runtime-known; we still know the result of the dereference at comptime. Code may use this, for instance, when allocating zero-bit types: `@as(*void, undefined)` is entirely reasonable to use at runtime, since we know the pointer will never be accessed, thus it should be valid at comptime too.
=> Sema: allow dereferencing ill-defined pointers to zero-bit types at comptime

lib/std/bounded_array.zig, lib/std/std.zig
This is useful for creating byte buffers of actually-different-things.
Copied the argument order from `Allocator.alignedAlloc`
I noted that `ArrayListAligned` is going out of it's way to not set the
alignment at comptime when it is not specified. However, I was not able
to do that the same way here, and good people on IRC, @ifreund in
particular (thanks!) assured me that
```zig
[N]T align(@alignOf(T))
```
is equivalent to
```zig
[N]T
```
=> add BoundedArrayAligned

lib/std/crypto/tls.zig, lib/std/crypto/tls/Client.zig
Sends post-quantum secure hybrid key share X25519+Kyber768Draft00, deployed by [Cloudflare](https://blog.cloudflare.com/post-quantum-for-all/).
A few notes:
1. The method of hybridisation is as per this [IETF TLS WG draft](https://datatracker.ietf.org/doc/html/draft-ietf-tls-hybrid-design) version -06.
2. Kyber will probably change before final standardisation by NIST. When it does, we'll use a new TLS codepoint and update. The current version is [v3.02](https://pq-crystals.org/kyber/data/kyber-specification-round3-20210804.pdf) of the specification and version -00 of [this I-D](https://datatracker.ietf.org/doc/draft-cfrg-schwabe-kyber/).
3. The only other big deployment of post-quantum kex is CECPQ2 ([ref1](https://blog.cloudflare.com/the-tls-post-quantum-experiment/), …
=> tls: send post-quantum secure keyshare

lib/build_runner.zig, lib/std/Build.zig
This is useful for tests that want to `execve` zig directly. The string is already null-terminated, so this will just expose it as such, removing an extra allocation from the test.
Will be used in #14462
=> Build.zig_exe: make it sentinel-aware

lib/build_runner.zig, src/main.zig
This removes the remnant mentions of the `--prominent-compile-errors` flag from the cli help output. The flag is unavailable since merge of #14647.
=> delete `--prominent-compile-errors` from cli help output

src/link.zig, src/link/MachO.zig, src/link/MachO/zld.zig
Since #14647 landed in master, I started experiencing build failures on an M1 mac where it looked as if the output directory handle was getting closed before we could invalidate the kernel cache by moving the final binary in-place. The code responsible for this so far resided in `link.makeExecutable` but now I am of the opinion that it really is part of the MachO linker only. I have thus moved it and as expected it solved the problems for me.
For the record, here's an example error trace before this change:
```zig
zig build-exe zdb Debug native: error: thread 6148693 panic: reached unreachable code …
```
=> link: move macOS kernel inode cache invalidation to MachO linker

lib/std/Build.zig, lib/std/Build/OptionsStep.zig, test/standalone.zig, test/standalone/options/build.zig
* use the same hash function as the rest of the steps
* fix race condition due to a macOS oddity.
* fix race condition due to file truncation (rename into place instead)
* integrate with marking Step.result_cached. check if the file already exists with fs.access before doing anything else.
* use a directory so that the file basename can be "options.zig" instead of a hash digest.
* better error reporting in case of file system failures.
Fixes #15006
=> fix std.Build.OptionsStep

src/link/Wasm.zig, test/link/wasm/bss/build.zig, test/link/wasm/bss/lib2.zig
=> wasm-linker: fix storing atoms in the correct segment

lib/std/os/windows.zig
This function is unused, it doesn't provide much over a direct call to `NtQueryInformationFile`, and the current implementation contains a few footguns:
- The current wrapper treats all possible errors as unexpected, even likely ones like `BUFFER_OVERFLOW` (which is returned if the size of the out_buffer is too small to contain all the variable-length members of the requested info, which the user may not actually care about, see https://github.com/ziglang/zig/pull/14841/commits/6d74c0d1b41b52bca3d66092a48660f2ee4ae4f8)
- Each caller may need to handle errors differently, different errors might be possible depending on the `FILE_INFORMATION_CLASS`, etc, and making a wrapper that handles all of those different use-cases nicely seems like it'd be more trouble than it's worth …
=> Remove `std.os.windows.QueryInformationFile` (a wrapper of `NtQueryInformationFile`)

src/link/Elf.zig
If the shared library is a relative path, dirname will return null causing a segfault. In the case I debugged, the current directory was already in RPATH so just ignoring this case seems a reasonable fix. After this fix "make" and "make test" pass for mimalloc.
Closes #13766
=> Fix linker segfault adding rpath to sharedlib

build.zig, lib/std/c/darwin.zig, lib/std/macho.zig, lib/std/os.zig, src/link.zig, src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/MachO/Relocation.zig, src/main.zig
Depends on #14935 
Upstreams updated but still minimal PoC of hot-code swapping on macOS with the incremental MachO linker. In order to play with it without any `sudo` malarkey, it's required to build the compiler with the right entitlements: those for the debugger. At least for the time being, we won't do it by default as it elevates Zig to superpowers, so to try it out, you need to rebuild with `-Dentitlements=Info.plist` flag.
=> Upstream macOS hot-code swapping PoC

lib/std/simd.zig
std.simd.suggestVectorSizeForCpu didn't support Wasm SIMD
This PR adds Wasm SIMD support.
```shell
$ zig version
0.11.0-dev.1987+a2c6ecd6d
$ cat wasm-simd.zig 
const wasm_simd_model = std.Target.wasm.cpu.bleeding_edge;
const wasm_simd_cpu = comptime std.Target.Cpu.Model.toCpu(&wasm_simd_model, std.Target.Cpu.Arch.wasm32);
std.debug.print("vector size for u8(wasm) {?}\n", .{std.simd.suggestVectorSizeForCpu(u8, wasm_simd_cpu)});
}
$ zig run wasm-simd.zig 
vector size for u8(wasm) null
$ zig run --zig-lib-dir ~/ghq/github.com/ziglang/zig/lib wasm-simd.zig 
vector size for u8(wasm) 16
```
=> add wasm-simd support for suggestVectorSizeForCpu

build.zig, test/tests.zig
It is reasonable to pass `-Dskip-non-native` when unable to run foreign binaries, however there is no option for being able to run foreign static binaries but unable to run foreign dynamic binaries.  This can occur when qemu is installed but not cross glibc.
=> tests: add `-Dskip-cross-glibc` option

lib/std/json.zig, lib/std/json/test.zig
Adds support for parsing and stringifying between JSON arrays (which can contain multiple types) and Zig tuples.
This is my first PR to Zig itself, so any and all feedback is appreciated :)
=> std.json: support tuples

lib/std/fs/file.zig, lib/std/os.zig, lib/std/os/windows.zig, lib/std/os/windows/ntdll.zig
- Fixes the first few code units of the name being omitted (it was using `@sizeOf(FILE_NAME_INFO)` as the start of the name bytes, but that includes the length of the dummy `[1]u16` field and padding; instead the start should be the offset of the dummy `[1]u16` field). This effectively meant that it was only doing the `-pty` check, as the `m` in `msys-` was always being cut off.
- Replaces `kernel32.GetFileInformationByHandleEx` call with `ntdll.NtQueryInformationFile`
+ Contributes towards #1840
- Checks that the handle is a named pipe first (which is a much faster call than NtQueryInformationFile) before querying and checking the name (this was about a 10x speedup in my probably-not-so-good/take-it-with-a-grain-of-salt benchmarking)
```
Benchmark 1: iscyg-new.exe
Time (mean ± σ): …
```
=> `os.isCygwinPty`: Fix a bug, replace kernel32 call, and optimize

doc/langref.html.in
This should add all remaining missing return types to all builtin
functions.
For @clz, @ctz, and @popcount it uses anytype for the lack of a better
alternative. We already use this return type for other builtin functions in the langref
to indicate that the type is not always the same.
It is not possible to use anytype as the return type for regular
functions but builtin functions are special.
Alternatively, we could omit the return type from all builtin functions that don't always have the same return type, as an alternative to `anytype` which might mislead newbies to believe they can use that return type for their own functions too.
But if we omit it, it might look like a void return type.
See also: #14779
=> langref: add missing return types to builtin functions

src/AstGen.zig, src/Module.zig, src/Sema.zig, src/Zir.zig, src/print_zir.zig, test/cases/compile_errors/incompatible sub-byte fields.zig, test/cases/compile_errors/missing_else_clause.zig, test/cases/compile_errors/missing_result_type_for_phi_node.zig, test/cases/compile_errors/unused_value_in_switch_in_loop.zig
I wanted to experiment a bit and improve these error messages but I have no idea if this is the right way to go about it. If it's not, I'm happy to do it differently if I can get a nudge in the right direction, otherwise feel free to just close the PR :smile:
This turns `@"break"` data from a nice, self-containted 8 byte struct into something more like a `pl_node` with extra data. I haven't measured the performance impact since I wanted some feedback if this overall approach before investing too much time.
Examples of the improved error messages:
```zig
var x: bool = true;
const b = while (x) {
break 1;
} else "asdf";
_ = b;
```
Before:
```zig
fails.zig:85:15: error: incompatible types: 'comptime_int' and '*const [4:0]u8'
const b = for (a) |_| {
```
After:
```zig
fails.zig:7:15: error: …
```
=> Improve error messages for break type coercion

lib/std/crypto/hmac.zig
HMAC supports arbitrary key sizes, and there are no practical reasons to use more than 256 bit keys.
It still make sense to match the security level, though, especially since a distinction between the block size and the key size can be confusing.
Using `HMAC.key_size` instead of `HMAC.mac_size` caused our TLS implementation to compute wrong shared secrets when SHA-384 was used. So, fix it directly in `crypto.hmac` in order to prevent other misuses.
=> crypto.hmac: set the recommended key size to the block size

lib/std/crypto/aes.zig, lib/std/crypto/tls/Client.zig
On CPUs without AES support, ChaCha is always faster and safer than software AES.
Add `crypto.core.aes.has_hardware_support` to represent whether AES acceleration is available or not, and in `tls.Client`, favor AES-based ciphers only if hardware support is available.
This matches what BoringSSL is doing.
=> TLS: Favor ChaCha over AES-based ciphers on CPUs without AES support

lib/std/macho.zig, src/link/MachO.zig, src/link/MachO/DwarfInfo.zig, src/link/MachO/Object.zig, src/link/MachO/UnwindInfo.zig, src/link/MachO/ZldAtom.zig, src/link/MachO/dead_strip.zig, src/link/MachO/eh_frame.zig, src/link/MachO/load_commands.zig, src/link/MachO/thunks.zig, src/link/MachO/zld.zig
#14923 partially addressed - see comment below for more context.
Bug description extracted from one of the commit messages:
Previously, if we were looking for the very last symbol by address in some section, and the next symbol happened to also have the same address value but would reside in a different section, we would keep going finding the wrong symbol in the wrong section.
This mechanism turns out vital for correct linking of Go binaries where the runtime looks for specially crafted synthetic symbols which mark the beginning and end of each section. In this case, we had an unfortunate clash between the end of executable machine code section (`_runtime.etext`) and the beginning of read-only data (`_runtime.rodata`) which assumed the same address in the input relocatable object file.
=> macho: fix Go mislinking on aarch64-macos, and misc cleanup

lib/std/http/Client/Response.zig
Common headers in a response are:
Content-Encoding: gzip
Transfer-Encoding: chunked
We used to return `HttpHeadersInvalid` if a `Transfer-Encoding` header was received while the compression was already set.
However, Transfer-Encoding may not include compression. We should only return an error if we are setting a value that was already set.
Fixes compatibility with a bunch of websites.
=> http.Client: don't prematurely check transfer_{encoding,compression}

doc/langref.html.in
As I've been messing around I tried some things that I expected to work but didn't:
```
if (maybeAnError()) |goodVal| {
// happy path
} else {
// oops this syntax doesn't work
}
```
So I wanted to add a docs example showing how to have an else without `switch` since whatever the case the parser does expect you to capture a variable.
Also added an example of using a named block for setting a value from a catch block. Yes this is strictly redundant but I didn't immediately think/guess correctly how to use a block with a catch.
Note to self: build the docs with `zig build docs`.
=> Two more examples of possible syntax when dealing with errors

lib/std/child_process.zig, lib/std/process.zig
Notably the Darwin (XNU) kernel the maxrss field is number of bytes and not kilobytes (kibibytes) like other platforms (e.g. Linux, BSD).
This is my first PR, although very small in scope, feel welcome to give input.
Fixes #14957
=> std.process.Child: implement maxrss on Darwin

lib/std/fmt/parse_float.zig
Since removing the stage1 backend we no longer have a disagreement here.
=> enable more float-parsing tests

CMakeLists.txt, src/arch/aarch64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/link.zig, src/link/Coff.zig, src/link/Coff/ImportTable.zig, src/link/Coff/Relocation.zig, src/link/MachO.zig, src/link/Wasm.zig, test/tests.zig
Fixes #15075
The cool thing about Zig's handling of `extern`s (aka `extern "ntdll" fn SomeFunc(...)`) is that we can declaratively specify what DLLs we want to link against and what symbols link from there without having access to the said DLLs. Of course, if we make a mistake in naming the right DLL, we get a loader rather than a linker error, but I still find it amazing that we are able to do this.
=> coff: handle multiple DLLs

src/Sema.zig, src/codegen/c.zig, src/codegen/llvm.zig, test/behavior/slice.zig
While attempting to produce a non-zero alignment, we accidentally picked the one thing with a zero alignment instead.
Closes #15085
=> Sema: fix empty slice pointer value

src/codegen/llvm.zig
As bpf program has no global section for constant values (especially strings), so use llvm's builtins (like memcpy, memset, etc) will lead to compilation failure (something like this: A call to built-in function 'memcpy' is not supported.)
=> llvm/bpf: disable llvm builtins for bpf target

doc/langref.html.in, src/Air.zig, src/AstGen.zig, src/BuiltinFn.zig, src/Liveness.zig, src/Sema.zig, src/Zir.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/print_air.zig, src/print_zir.zig
* `@workItemId(comptime dimension: u32) u32` returns the index of the work item in a work group for a dimension.
* `@workGroupId(comptime dimension: u32) u32` returns the index of the work group in the kernel dispatch for a dimension.
* `@workGroupSize(comptime dimension: u32) u32` returns the size of the work group for a dimension.
These builtins are mainly useful for GPU backends. They are only implemented for the AMDGCN LLVM backend.
Also see my experiments which live at https://github.com/Snektron/zig-hip-test. The performance of a simple reduction is quite similar to that of HIP :).
```
info: zig: result = 576460752303423500, processed 1073741824 items in 3.92 ms (273.70 GItem/s, 1094.80 GB/s)
info: hip: result = 576460752303423500, processed 1073741824 items in 3.86 ms (277.85 …
```
=> GPU builtins

doc/docgen.zig, doc/langref.html.in
- Fix usage string `--skip-code-test` to `--skip-code-tests`.
- Added a token `{#additonal_option|-rdynamic#}` which introduce arbitrary flag to `build-exe/obj/lib` example.
- Fix wasm freestanding example, it now needs explicit export symbols to work.
This fixes #14818. The wasm freestanding shell now looks like this:
```shell
zig build-lib math.zig -target wasm32-freestanding -dynamic -rdynamic
```
Cheers!
=> docgen: add `additional_option` token; fix wasm-freestanding example

test/link/macho/bugs/13056/build.zig
Latest macOS 13.3 rolled out LLVM 15 and thus the way `nullptr_t` is defined within the `libc++`:
https://github.com/llvm/llvm-project/commit/157bbe6aea22e87c822f6cda3cd404b8f657dce4
This seems to require including `/usr/include` with `-isystem` directive rather than `-I`. Otherwise we get clang miscompilation issues due to missing `nullptr_t` declaration.
=> link-test: adjust test/link/bugs/macho/13056 to latest changes on macOS 13.3

src/Sema.zig, src/codegen/c.zig, src/codegen/llvm.zig, test/behavior/if.zig, test/behavior/union.zig
This lets us generate the store with knowledge of the type to be stored. Therefore, we can avoid generating garbage Air with stores through pointers to comptime-only types which backends cannot lower.
Closes #13410
Closes #15122
---
```
%31 = alloc(*u32)
...
%57 = bitcast(*comptime_int, %31)
%58!= store(%57!, @Zir.Inst.Ref.zero)
```
=>
```
%68 = constant(u32, 0)
...
%31 = alloc(*u32)
...
%54!= store(%31, %68!)
```
---
```
%43 = constant(@TypeOf(.enum_literal), .a)
...
%38 = alloc(*repro.U)
...
%45 = bitcast(*@TypeOf(.enum_literal), %38)
%46!= store(%45!, %43!)
```
=>
```
%95 = constant(repro.U, .{ .a = {} })
...
%38 = alloc(*repro.U)
...
%44!= store(%38, %95!)
```
=> Sema: defer stores to inferred allocs

lib/std/mem.zig
`std.mem.reverseIterator` currently only accepts slices but not pointers to arrays, making it slightly inconvenient to use since `std.mem.reverseIterator(&array)` will end up passing the argument as `*[N]T` and not `[]T`. This PR fixes it so that the function accepts both pointers to arrays and slices. (I didn't add support for passing arrays by value because I imagine it is almost never what you want and a likely source of bugs from typos such as forgetting the `&`.)
```zig
var it = std.mem.reverseIterator("Hello, World!"); // This did not compile previously.
while (it.next()) |c| {
std.debug.print("{c}", .{c});
}
std.debug.print("\n", .{});
```
I also added `nextPtr()` to enable iterating over the slice by reference. This brings the function close to parity with captures in `for` loops. …
=> std.mem.reverseIterator: misc improvements

lib/std/os/linux/x86.zig, lib/std/os/linux/x86_64.zig, lib/std/start.zig, src/Module.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/link.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/MachO.zig, src/print_air.zig, test/behavior/bugs/12776.zig, test/behavior/bugs/1442.zig, test/behavior/bugs/3007.zig, test/behavior/cast.zig, test/behavior/error.zig, test/behavior/eval.zig, test/behavior/inttoptr.zig, test/behavior/struct.zig, test/behavior/switch_prong_err_enum.zig, test/behavior/switch_prong_implicit_cast.zig, test/cases/aarch64-macos/hello_world_with_updates.0.zig, test/cases/x86_64-linux/hello_world_with_updates.0.zig, test/cases/x86_64-macos/hello_world_with_updates.0.zig, test/cases/x86_64-windows/hello_world_with_updates.0.zig, test/src/Cases.zig
This reaches the milestone of being able to run [Hello World](https://ziglang.org/documentation/master/#Hello-World) without modification.
```
$ cat hello.zig
const stdout = std.io.getStdOut().writer();
try stdout.print("Hello, {s}!\n", .{"world"});
}
$ zig run hello.zig -fno-LLVM
Hello, world!
=> x86_64: get enough things working to enable full `start.zig` logic

lib/std/c/linux.zig, lib/std/os.zig, lib/std/os/linux.zig
This PR adds support for the [`mincore` syscall](https://github.com/ziglang/zig/blob/ab44b454d0408a7968354f8889a2e57c02396153/lib/std/os/linux/syscalls.zig#L223)
[`mincore`](https://man7.org/linux/man-pages/man2/mincore.2.html) is available on some UNIX like operating systems and allows a user to determine if a page is resident in memory.
Notes:
- The `mincore` function signature in `std.os` could be made more idiomatic Zig by passing a slice instead of a ptr and len. However this implementation matches what was done for [`madvise`](https://github.com/ziglang/zig/blob/ab44b454d0408a7968354f8889a2e57c02396153/lib/std/os.zig#L7009-L7010). If we want the more idiomatic approach we can open a separate (breaking) PR which updates the various functions which currently pass both a ptr and len. …
=> std.os: add mincore syscall

lib/libc/glibc/README.md, lib/libc/glibc/io/fcntl.h, lib/libc/include/generic-glibc/fcntl.h, lib/libc/include/generic-glibc/resolv.h, test/link.zig, test/link/glibc_compat/build.zig, test/link/glibc_compat/main.c
- `fcntl` was renamed to `fcntl64` in glibc 2.28 (see #9485)
- `res_{,n}{search,query,querydomain}` became "their own" symbols since glibc 2.34: they were prefixed with `__` before.
This PR makes it possible to use `fcntl` with glibc 2.27 or older and the `res_*` functions with glibc 2.33 or older.
These patches will become redundant with universal-headers and can be dropped. But we have to do with what we have now.
Closes #9485
Related: 39083c31a550ed80f369f60d35791e98904b8096
=> glibc: add backwards compatibility for some symbols

src/arch/wasm/CodeGen.zig
This change would match the LLVM backend behavior and makes allocators work.
=> Make self-hosted wasm @returnAddress return 0

src/Liveness.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen/c.zig, src/print_air.zig, test/behavior/const_slice_child.zig, test/behavior/for.zig, test/behavior/slice.zig
Deaths of operands in loop bodies are special. Consider this code:
```zig
var x: u32 = 0;
for (something) {
foo(x);
bar();
}
```
Syntactically, `x` dies after the call to `foo`, and this is what Liveness emits today. However, for backends to treat it like this would be a bug, because further loop iterations may occur. Rather, backends are required to defer the death of `x` until after the end of the loop.
The C backend had its own logic to achieve this, but it was rather a mess. Moreover, since every backend (save for LLVM) needs this logic, it makes sense to include it in liveness analysis. Here, we add an extra data payload to `.loop`, with a list of operands which must die after the loop terminates.
Unfortunately, implementing this required adding a second pass to Liveness which …
=> Liveness: defer deaths of externally-scoped instructions in loop bodies

src/arch/wasm/CodeGen.zig, test/behavior/floatop.zig, test/behavior/muladd.zig, test/link/wasm/archive/build.zig
This implements the majority of floating-point operations on the native webassembly backend by either calling into compiler-rt or directly emitting instructions if available.
Prior to this, operations on `f16` were implemented using a round trip to `f32` (which is why I had to change the archive test).
=> wasm: implement float operations with compiler-rt

src/Compilation.zig, src/link.zig, src/link/Elf.zig, src/main.zig
Fixes: #15051
This passes `-wrap` through to the old.
Test
```
> cat wrap_example.c foo.c
#include <stdio.h>
extern int foo();
extern int __real_foo();
int __wrap_foo() {
printf("wrap foo\n");
return 0;
}
int __real_foo(){
printf("real foo\n");
return 0;
}
int main () {
printf("foo:");foo();
printf("wrapfoo:");__wrap_foo();
printf("realfoo:");__real_foo();
return 0;
}
#include <stdio.h>
int foo() {
printf("foo\n");
return 0;
}
> ./zig2 cc wrap_example.c foo.c  -Wl,-wrap,foo -o main
> ./main
foo:wrap foo
wrapfoo:wrap foo
realfoo:foo
```
=> add linker -wrap flag

lib/std/crypto/tls/Client.zig
=> tls.Client: don't read if we don't need more data

src/arch/wasm/CodeGen.zig, src/arch/wasm/Emit.zig, test/behavior/shuffle.zig, test/behavior/vector.zig
Thanks @jacobly0 for all the help with this :)
- `@shuffle` works
- Vector element accesses (mutable and constant) work (again)
cc @Luukdegram
=> Implement `@shuffle`, fix vector element accesses for WASM backend

lib/std/multi_array_list.zig, lib/std/zig/Parse.zig, src/translate_c/ast.zig
Support for tagged unions with no API changes. As per #14496.
I'm don't see why but this won't compile saying that this type definition is recursive:
```
lib/std/multi_array_list.zig:21:12: error: struct 'multi_array_list.MultiArrayList(array_hash_map.ArrayHashMapUnmanaged([]const u8,link.tapi.yaml.Value,array_hash_map.StringContext,true).Data)' depends on itself
return struct {
^~~~~~
lib/std/array_hash_map.zig:480:9: note: while checking this field
entries: DataList = .{},
^~~~~~~~~~~~~~~~~~~~~~~
lib/std/array_hash_map.zig:81:9: note: while checking this field
unmanaged: Unmanaged,
^~~~~~~~~~~~~~~~~~~~
src/link/tapi/yaml.zig:41:5: note: while checking this field
map: Map,
^~~~~~~~
lib/std/array_hash_map.zig:511:13: note: while checking this field
value: V,
^~~~~~~~
```
I'm happy to fix …
=> std.MultiArrayList: add support for tagged unions.

lib/std/math.zig, lib/std/math/log10.zig
A straight forward port of `int_log10` from the [Rust standard library](https://github.com/rust-lang/rust/blob/f63ccaf25f74151a5d8ce057904cd944074b01d2/library/core/src/num/int_log10.rs), including tests.
In theory, this makes it possible to  _accurately_ compute `log10` of any integer, from `u1` to `u65535`. However, due to a [compiler bug](https://github.com/ziglang/zig/issues/14816), currently it only gives accurate results up to `u136`.
Even with limitations, the proposed implementation it's an improvement because currently the compiler segfaults when trying to use integers bigger than `u128` and gives wrong results even when it works.
I've been learning Zig for 2 weeks, sorry for any mistakes or non idiomatic code.
=> std.math: port `int_log10` from Rust

src/target.zig
Support for the built-in libcrypt was removed in commit 6b7ddfba,
but the -lcrypt flag remained ignored, preventing linking against
external libcrypt.
Fixes #5990.
Signed-off-by: Piotr Sikora <piotr@aviatrix.com>
=> glibc: allow linking against external libcrypt.

src/Air.zig, src/Sema.zig
```
%0 = arg(bool, 0)
%2!= block(void, {
%3!= block(void, {
%4 = loop(noreturn, {
%8!= block(void, {
%11!= cond_br(%0!, {
%9!= br(%3, @Zir.Inst.Ref.void_value)
}, {
%10!= br(%8, @Zir.Inst.Ref.void_value)
})
})
%12!= br(%2, @Zir.Inst.Ref.void_value)
})
})
%13!= br(%2, @Zir.Inst.Ref.void_value)
})
%15!= ret(@Zir.Inst.Ref.void_value)
```
=>
```
%0 = arg(bool, 0)
%2!= block(void, {
%3!= block(void, {
%8!= block(void, {
%11!= cond_br(%0!, {
%9!= br(%3, @Zir.Inst.Ref.void_value)
}, {
%10!= br(%8, @Zir.Inst.Ref.void_value)
})
})
%12!= br(%2, @Zir.Inst.Ref.void_value)
})
%13!= br(%2, @Zir.Inst.Ref.void_value)
})
%15!= ret(@Zir.Inst.Ref.void_value)
```
=> Sema: delete non-looping loops

doc/docgen.zig, lib/std/Build.zig, lib/std/Build/CompileStep.zig, lib/std/Build/TranslateCStep.zig, src/main.zig, test/standalone/issue_13970/build.zig, test/standalone/test_runner_module_imports/build.zig, test/tests.zig
std.Build.CompileStep: remove output_dir
Build scripts must instead use the FileSource abstraction rather than
telling the compiler directly where to output files.
CLI: remove --enable-cache option
This use case is now handled instead by the --listen option.
closes #14951
closes #15025
closes #15072
=> remove --enable-cache option; std.Build.CompileStep: remove output_dir

CMakeLists.txt, build.zig
This is useful for packaging where you want the lib/ files but not langref in some completely non-standard location.
langref also prolongs the local install to access the stage 3 compiler without having to fish for hashes
=> build: add option to not build langref on install

lib/std/crypto.zig, lib/std/crypto/aegis.zig
The latest (`cfrg-aegis-aead-02`) revision of the draft allows AEGIS to output 256-bit authentication tags.
The computational overhead is negligible. However, with a 256-bit tag, finding a collision becomes impractical even when the key and associated data can be chosen by an adversary.
=> std.crypto.aegis: support 256-bit tags

lib/std/os/windows.zig, lib/std/os/windows/ntdll.zig, lib/std/process.zig
On Windows, there are two kinds of total physical memory. One obtained by `GetPhysicallyInstalledSystemMemory` which represends the real physical memory values retreived from the SMBIOS physical memory tables. While this value is the total actual memory installed in the system, it does not represent the max total memory that the system can have. Parts of the system memory are hardware reserved. It's also worth noting that `GetPhysicallyInstalledSystemMemory` can be a bit expensive compared to the total - reserved as it parses the SMBIOS tables until it finds the memory table (16) which i believe requires allocation.
In Linux, `std/process.zig` uses `/proc/meminfo` MemTotal. In the man page of proc, it states that: 
```
MemTotal %lu
Total usable RAM (i.e., physical RAM minus a few reserved …
```
=> windows: replace GetPhysicallyInstalledSystemMemory with ntdll

src/print_targets.zig
Fix "zig targets" panic with integer cast truncated bits
=> fix: print targets

build.zig, lib/compiler_rt/common.zig, lib/std/Build.zig, lib/std/Build/CompileStep.zig, lib/std/Build/RunStep.zig, lib/std/zig/Server.zig, test/behavior/atomics.zig, test/behavior/bugs/12680.zig, test/behavior/cast.zig, test/behavior/floatop.zig, test/behavior/math.zig, test/behavior/muladd.zig, test/behavior/vector.zig, test/behavior/widening.zig, test/tests.zig
* avoid skipping native tests
* actually run the C backend tests
With this I was able to make the C backend tests integrate cleanly with the build runner:
```
├─ run test behavior-native-Debug-libc-cbe 1567 passed 101 skipped 15ms MaxRSS:18M
│  └─ zig build-exe behavior-native-Debug-libc-cbe Debug native success 11s MaxRSS:647M
│     └─ zig test Debug native success 24s MaxRSS:181M
```
=> add CI test coverage for more target combinations

lib/std/start.zig, test/link/wasm/type/build.zig
The Wasm backend now supports all features required to use the full `start.zig` logic, rather than the simplified version.
=> wasm: no longer use simplified `start.zig` logic

test/tests.zig
Native targets are, by definition, not cross-compiling targets.
=> tests: fix skip_cross_glibc check

lib/std/dynamic_library.zig, test/standalone/load_dynamic_library/build.zig
Closes https://github.com/ziglang/zig/issues/15043, https://github.com/ziglang/zig/issues/13200, https://github.com/ziglang/zig/issues/13550, https://github.com/ziglang/zig/issues/13686.
=> DynLib.lookup: cast the pointer to the correct alignment

lib/std/http/Client.zig, lib/std/http/Server.zig
Hi,
Thank you so much for wonderful project! I fixed the HTTP server when chunked encoding.
Here is `server.zig`
```zig
var server = std.http.Server.init(std.heap.page_allocator, .{ .reuse_address = true });
defer server.deinit();
try server.listen(try std.net.Address.parseIp("127.0.0.1", 8080));
while (true) {
const res = try server.accept(.{ .dynamic = 8192 });
const thread = try std.Thread.spawn(.{}, handler, .{res});
thread.detach();
}
}
fn handler(res: *std.http.Server.Response) !void {
defer res.reset();
try res.wait();
std.debug.print("requested: {}\n", .{res.request});
// chunked transfer
res.headers.transfer_encoding = .chunked;
res.headers.connection = res.request.headers.connection;
try res.do();
_ = try res.write("Hello, …
```
=> HTTP client and server send "0\r\n\r\n" when chunked encoding

src/Compilation.zig, src/main.zig
Closes https://github.com/ziglang/zig/issues/15306.
In the case of no `main_pkg`, then `use_llvm` is false, which would cause the compilation to use the default caching mode (incremental). This was causing the cache to not be checked at all for the compilation.
Also fixed the argument to `--debug-log` being treated as a file argument when used with a release build. Discovered this one while testing this. This was causing the command to fail, instead of just printing a warning.
=> Fix purely C/C++ compilations not using CacheMode.whole

src/arch/x86_64/CodeGen.zig, test/behavior/bugs/12776.zig, test/behavior/bugs/1851.zig, test/behavior/enum.zig, test/behavior/struct.zig, test/tests.zig
These are the fixes needed to run the fully featured `test_runner.zig`, except for the tracking rewrite that depends on @mlugg's upcoming liveness changes.
Closes #15324
=> x86_64: liveness independent fixes

lib/std/Build/Cache.zig
This fixes `.INVAL => unreachable` being triggered by the cache system on macOS when multiple processes race to create the same compilation. The problem is that when two processes race to create a file, it sometimes returns ENOENT even though that error code is nonsensical for this situation.
Commit 2b0929929d67e222ca6a9523a3a594ed456c4a51 purportedly solved this, but it did not open the file with write permissions, leading to the EINVAL panic later on. This commit remedies the situation by introducing a loop and simply retrying when the ENOENT occurs.
=> Cache: fix multi-process race condition on macOS

src/link/Coff/lld.zig
Closes https://github.com/ziglang/zig/issues/14718.
When `allow_shlib_undefined` is true, then `-FORCE:UNRESOLVED` is set on the `lld`command line.
Note that the [docs](https://learn.microsoft.com/en-us/cpp/build/reference/force-force-file-output?view=msvc-170) for `/FORCE:UNRESOLVED` don't explicitly state that this rule only applies to shared libraries. However, in order for linking to succeed, an import library (`.lib`) for the library specified in the `extern` definition still needs to be available to the linker. Because of this, the behavior should be consistent - only allow unresolved symbols when linking against shared libraries.
Example of this working:
```zig
const target = b.standardTargetOptions(.{});
const optimize …
```
=> coff: support allow_shlib_undefined with lld

lib/std/zig/parser_test.zig, lib/std/zig/render.zig
Status quo canonical:
```zig
1 test {}
2
3 //
4
```
Now:
```zig
1 test {}
2
3 //
```
=> zig fmt: omit extra whitespace after last comment before EOF

lib/std/target/riscv.zig, tools/update_cpu_features.zig
=> std.target.riscv: fix baseline_rv32 missing feature "32bit"

lib/std/Thread/Condition.zig
- Hold the lock for a shorter amount of time
- Previously, when holding the lock while signaling, the other, resumed thread could potentially get suspended again immediately because the mutex was still locked.
- Fix comment
cc @kprotty
=> std.Thread.Condition: optimize example

lib/std/math/big/int.zig
This pull request removes the optional allocator argument from functions `divFloor` and `divTrunc`. As a result, the comments related to accepting an optional `allocator` are no longer applicable. The support for accepting an optional allocator was removed in #10017.
=> math.big.int: remove stale comments

lib/std/enums.zig, lib/std/fmt.zig, lib/std/mem.zig, lib/std/os/windows/user32.zig
ccf670c made using `return` from within a comptime block in a non-inline function illegal, since it is a use of runtime control flow in a comptime block. It is allowed if the function in question is `inline`, since no actual control flow occurs in this case. A few functions from std (notably `std.fmt.comptimePrint`) needed to be marked `inline` to support this change.
=> std: fix uses of comptime blocks in non-inline functions

lib/std/Uri.zig, lib/std/crypto/Certificate.zig, lib/std/crypto/Certificate/Bundle.zig, lib/std/crypto/Certificate/Bundle/macos.zig, lib/std/http.zig, lib/std/http/Client.zig, lib/std/http/Headers.zig, lib/std/http/Server.zig, lib/std/http/protocol.zig, src/Package.zig
std.http.Client now has a set of curated errors that are higher level than the raw socket errors.
std.http.Headers added, adapted from daurnimator's work on the now orphaned std.http.Headers.
* http/2 compatibility removed as it's not important for http/1
Fixes #15295
```zig
var client = std.http.Client{
.allocator = gpa,
// .proxy = .{
//     .protocol = .plain,
//     .host = "127.0.0.1",
//     .port = 8080, // optional, defaults to 80 (plain) or 443 (tls)
//     .auth = "Basic dXNlcm5hbWU6cGFzc3dvcmQ=", // optional
// },
};
defer client.deinit();
const uri = std.Uri.parse("https://example.com") catch unreachable;
var h = std.http.Headers{ .allocator = gpa };
defer h.deinit();
try h.append("Content-Type", "text/plain");
// The following headers are sent as defaults if not provided:
// …
```
=> std.http: curated error sets and custom Headers

src/Compilation.zig
The issue with just passing `-gcodeview` is that it's not part of the `OPT_g_Group` in `clang/Driver/Options.td`, so it doesn't trigger debug info to be generated.
```
// Clang.cpp#4124
if (const Arg *A = Args.getLastArg(options::OPT_g_Group)) {
DebugInfoKind = codegenoptions::DebugInfoConstructor;
```
Passing only `-g` is sufficient on MSVC, as there is logic in `Clang.cpp` which enables codeview if that is the default for the toolchain. Since the default for -gnu is not codeview, we have to pass `-gcodeview` in that case.
```
// Clang.cpp#4169
// If the user asked for debug info but did not explicitly specify -gcodeview
// or -gdwarf, ask the toolchain for the default format.
if (!EmitCodeView && !EmitDwarf &&
DebugInfoKind != codegenoptions::NoDebugInfo) {
switch …
```
=> Fix generating COFF debug info on -gnu

lib/std/http/Server.zig
Hi,
The following code has a build error.
```zig
var res: std.http.Server.Response = undefined;
var buf: [16]u8 = undefined;
_ = try res.read(&buf);
}
```
Here is the build error.
```
/Users/ryo/ws/zig/zig/build/stage3/lib/zig/std/http/Server.zig:535:93: error: expected type 'error{ConnectionResetByPeer,ConnectionTimedOut,DecompressionFailure,EndOfStream,HttpChunkInvalid,HttpHeadersExceededSizeLimit,OutOfMemory,UnexpectedReadFailure}', found type 'error{InvalidTrailers}'
res.request.parse(res.request.parser.header_bytes.items) catch return error.InvalidTrailers;
```
This PR fixes this.
zig version is:
0.11.0-dev.2680+a1aa55ebe
=> std.http: add missing InvalidTrailers to ReadError

src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/zig_llvm.cpp, src/zig_llvm.h
One use case is to genearte BTF information from global variable's metadata.
=> llvm: emit metadata for exported global variables

src/Sema.zig, test/behavior/array.zig, test/cases/compile_errors/len_access_on_array_many_ptr.zig
Also remove an incorrect piece of logic which allowed fetching the 'len' property on non-single-ptrs (e.g. many-ptrs) and add a corresponding compile error test case.
Resolves: #4765
=> Sema: allow ptr field access on pointer-to-array

src/Module.zig, src/Sema.zig
This fixes cases where a function called inline or at comptime is modified, but dependent decls are not correctly re-analyzed, because normal function dependencies don't require re-analysis. Example test case for `x86_64-linux`:
```zig
pub export fn _start() noreturn {
asm volatile ("syscall"
:
: [num] "{rax}" (60),
[arg] "{rdi}" (comptime foo()),
: "rcx", "r11", "memory"
);
unreachable;
}
pub fn foo() u8 {
return 1;
}
```
Changing the return value of `foo` and performing an update did not used to change the return code; now it does.
This change also stops us from trying to semantically analyze outdated anonymous decls. This fixes the current issue  mentioned in #15174, but just gives way to another.
=> Module: mark function body dependencies, don't re-analyze anonymous decls

lib/std/math.zig
I think it'd be cool if we could have a basic lerp function in the std.
=> std.math: add lerp

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
When a `big.Int.Mutable` had more than two limbs, it was possible for this function to change the `len` field without zeroing limbs in the active range. These uninitialized limbs would then be used in `truncate()` and could cause invalid results.
Thanks to @matu3ba for investigating and finding the source of the bug!
This allowed me to uncomment the disabled `popCount` tests. I added a new test specific to `bitNotWrap`, but since the simplest check is to compare against large integer types (u256+) I skipped backends that don't support them yet.
Closes #13571
=> std.math.big.int: Initialize limbs in addWrap

lib/compiler_rt/README.md
Document current status of exports and intended design being inspired by Integer Operations.
=> compiler_rt: README stubs for arbitrary precision big integer library routines

lib/std/fs/test.zig, lib/std/os/windows.zig
~~closes #15315~~
closes #5537
Using `FILE_DELETE_ON_CLOSE` can silently succeed without reporting any error on non-empty directory. One way to return an error is to add `NtSetInformationFile` which will cause `DeleteFile` to report `DIRECTORY_NOT_EMPTY`.
=> windows: use NtSetInformationFile in DeleteFile.

src/target.zig
Because UEFI applications are windows DLLs, `zig cc` correctly sets the target to <arch>-unknown-windows-msvc when compiling for UEFI. However, a UEFI application is not treated as a windows DLL when determining whether the target supports the -fPIC option.
=> Do not use -fPIC when compiling a UEFI application

lib/std/crypto.zig, lib/std/crypto/aegis.zig
When used as a MAC, 256-bit tags are recommended.
But in interactive protocols, 128 bits may be acceptable.
We already implement both versions, so it doesn't take much to expose the relevant types.
=> AEGIS MAC: add support for 128-bit tags

lib/std/Build/RunStep.zig
The return type of the captureStdOut function is incorrect. Replace *std.Build.GeneratedFile with std.Build.FileSource.
=> std.Build.RunStep: fix captureStdOut function return type

src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/link/Coff.zig, src/link/Coff/Relocation.zig, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/MachO/DebugSymbols.zig, src/link/MachO/Relocation.zig, src/link/MachO/ZldAtom.zig, src/link/MachO/eh_frame.zig, src/link/MachO/stubs.zig, src/link/MachO/thunks.zig, src/link/MachO/zld.zig, src/link/table_section.zig
Additionally for ELF we no longer waste a GOT entry index for atoms that do not require it. For MachO and Coff, we no longer use atoms to represent GOT section which will reduce memory usage. There are still caveats such as dirtying one GOT cell will trigger an update of the entire GOT table, however this can be optimised out as we go quite easily.
Finally, I have redone handling of threadlocals in MachO such that they no longer get a GOT cell, and they get their own helper for lowering into memory much like `updateLazySymbolAtom` and `updateDecl`.
=> link: make GOT (and other synthetic sections) handling common across linkers

src/Sema.zig, src/link/Plan9.zig
Fixes https://github.com/ziglang/zig/issues/15219.
The reported crash was a panic due to incorrect alignment. Upon inspection, the misaligned pointer (`hash_map` metadata pointer) had a value of `0x02`.
The story of how 0x02 ends up there is as follows:
```
[0x0]   zig!weak.memset.default._alloca + 0xd4   
[0x1]   zig!allocAdvancedWithRetAddr__anon_51974 + 0x261   
[0x2]   zig!alloc__anon_6263 + 0x56   
[0x3]   zig!resolveStructLayout + 0xbbf   
[0x4]   zig!resolveTypeLayout + 0xa3   
[0x5]   zig!typeAbiSize + 0x54   
[0x6]   zig!intFitsInType + 0x650   
[0x7]   zig!coerceExtra + 0x67b4   
[0x8]   zig!coerce + 0x6e   
[0x9]   zig!semaStructFields + 0x5241  < analyzing `S`
```
In order to determine the value of the `.lazy_size` payload of `size`, the struct layout has to be resolved. The …
=> sema: fix memory corruption caused by resolveStructLayout

lib/std/fs.zig
`deleteTree` needs to retry once the directory is reported to be not empty. Otherwise, `need_to_retry` is always going to be false thus making the retry a dead code.
=> `fs.Dir.deleteTree`: Fix DirNotEmpty condition

lib/std/tar.zig
closes #15222. these changes allow the .tgz from this issue to decompress and the test code to succeed.
[discussion on discord](https://discord.com/channels/605571803288698900/1094497811090919455).
NOTE: the change to [this line](https://github.com/ziglang/zig/blob/master/lib/std/tar.zig#L125) wasn't necessary to make this test pass, but `@random internet person` on discord indicated that it was an improvement. 
NOTE: using `dir.makePath()` is an improvement because `dir.makeDir()` fails if the directory already exists which happens if the same file is decompressed twice.
=> std.tar: make sub dirs + trim spaces

src/clang.zig, src/translate_c.zig, src/zig_clang.cpp, src/zig_clang.h, test/translate_c.zig
Closes https://github.com/ziglang/zig/issues/11481.
This PR adds support for this kind of array initialization: `static const char foo[] = {"bar"};`. This fixes a crash where the code assumed that an an array filler always existed.
Context:
- https://eel.is/c++draft/dcl.init.string
- https://clang.llvm.org/doxygen/_2home_2buildbot_2as-worker-4_2publish-doxygen-docs_2llvm-project_2clang_2lib_2StaticAnalyzer_2Core_2RegionStore_8cpp-example.html#a66
=> translate-c: support brace-enclosed string initializers (c++20 9.4.2.1)

src/Module.zig, src/arch/wasm/CodeGen.zig, src/link/Wasm.zig, test/behavior/cast.zig
Implements the air instructions `error_set_has_value` and `cmp_lt_errors_len`, which are runtime safety checks emitted during `@errorToInt` and `@errCast`
=> wasm: implement more runtime safety checks

src/Sema.zig, test/behavior/fn.zig
Currently, it is possible to use the method call syntax `obj.method(...)` when `method`'s first parameter is the same as `obj`'s type (`T`), a pointer (`*T` or `[*c]T`), optional (`?T`), or error union (`Error!T`). This change adds support for `?*T`.
This is particularly useful for bindings to libraries where deallocation functions (e.g. `free`, `unref`) allow null to be passed as the object: a mechanical translation using `[*c]T` would work with the previous method syntax, but would no longer work when manually refined to `?*T`.
=> Sema: allow method calls on optional pointers

lib/std/http/Client.zig, lib/std/http/Headers.zig
Before this change, if a request errored before getting its `response.headers` initialized, then it would attempt to `deinit` `response.headers` which would still be `undefined`. Since all locations that set `response.headers` within `Client` use the same code, it can just be done upfront in `request` instead.
Closes #15380 
(with this, I now get error: EndOfStream when trying to build `zls` instead of a panic)
---
Note also that before this change, this:
https://github.com/ziglang/zig/blob/21aa55d34e432b677f71cbb377aa89c8cdbd1483/lib/std/http/Client.zig#L1030
was a guaranteed panic if it ever actually ran (right now it's technically impossible for that `errdefer` to run though).
=> std.http: Always initialize `response.headers` in Client.request

lib/std/http/Server.zig, lib/std/http/protocol.zig
This fixes https://github.com/ziglang/zig/issues/15370
ref. https://www.rfc-editor.org/rfc/rfc9112#name-chunked-transfer-coding
=> std.http: fix server to handle a chunked transfer coding request

lib/std/fs.zig, lib/std/os/test.zig
=> std: fix windows resource leaks

lib/std/fs.zig
addition to #15450
`createFileW` does not account for when  `LockFile` fails. This can result in a file handle not being closed on failure Which can be seen on test such as `open file with exclusive nonblocking lock twice` here:
https://github.com/ziglang/zig/blob/d8bdfd8192fb43ca8f6abd223396a4073e369499/lib/std/fs/test.zig#L1030-L1050
this can also be observed by finding the file specified in the test in the `zig-cache` due to failure in cleanup.
=> std: further windows resource fix

lib/std/json.zig, lib/std/json/test.zig
Adds support for @Vector-types in `std.json.parse` std.json.  Currently std.json supports encoding @Vectors into JSON arrays but it cannot parse them.  This change adds support for reading JSON arrays (like `[0,1,2,3]`) into @Vectors.
closes #15314
=> std: @Vector support for std.json.parse

src/Sema.zig, test/cases/compile_errors/slice_to_anyopaque_pointer.zig
Fixes https://github.com/ziglang/zig/issues/14917. 
This change makes coercing a slice (directly, ie. without using `.ptr`) to an anyopaque pointer a compile error. Short discussion in Discord [here](https://discord.com/channels/605571803288698900/785499283368706060/1099927070466900008).
Instead of crashing there is now a compile error alerting the user that the coercion isn't possible:
```
src\main.zig:36:44: error: expected type '?*const anyopaque', found '[]const u8'
_ = pocketmod.pocketmod_init(&pmodctx, mod_data, mod_data.len, 44100);
^~~~~~~~
C:\cygwin64\home\kcbanner\temp\zig-embeddir\zig-cache\o\d9a8c17a208fb48bf628a30a3cafa090\cimport.zig:79:62: note: parameter type declared here
pub extern fn pocketmod_init(c: [*c]pocketmod_context, data: ?*const anyopaque, size: c_int, rate: …
```
=> sema: add compile error for coercing a slice to an anyopaque pointer

lib/std/http/Client.zig, lib/std/http/test.zig, src/Package.zig
Requires https://github.com/ziglang/zig/pull/15416
Fixes https://github.com/ziglang/zig/issues/15376
Fixes trailing headers being parsed for transfer information
Fixes use after free for resolved URIs
=> std.http: do -> wait, fix redirects and uaf

src/translate_c.zig, test/translate_c.zig
Fixes https://github.com/ziglang/zig/issues/15411.
If the C code had variables that were named the same as the prefixes used for name mangling, such as `tmp`, `ref`, or `cond_temp`, then the codegen would generate incorrect code in some cases. This was because these aliases were immediately visible to sub-expressions that actually needed to use the original name.
Example:
```
void test_transCreateNodeAssign() {
int n, tmp = 1;
if (n = tmp) {}
}
// Translated to:
pub export fn test_transCreateNodeAssign() void {
var n: c_int = undefined;
var tmp: c_int = 1;
_ = @TypeOf(tmp);
if ((blk: {
const tmp_1 = tmp_1;
n = tmp_1;
break :blk tmp_1;
}) != 0) {}
}
```
Note the incorrect assignment `const tmp_1 = tmp_1;`, which should be `const tmp_1 = tmp;`
Another example:
```
int …
```
=> translate-c: fix codegen when C source has variables named the same as mangling prefixes

src/value.zig, test/cases/comptime_aggregate_print.zig
Fixed https://github.com/ziglang/zig/issues/15255.
This fixes a crash when `@compileLog` is passed a slice backed by an aggregate field at comptime.
I'm not sure if this behavior (return a slice backed by a function-scoped variable at comptime) is intended to be supported, but it does work now that the crash is fixed.
=> Add support for .field_ptr in elemValueAdvanced

lib/std/http.zig
.header_fields_too_large -> .request_header_fields_too_large
https://www.rfc-editor.org/rfc/rfc6585#section-5
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431
=> std.http: fix name of Status field to better match RFC name

lib/compiler_rt/README.md, lib/compiler_rt/arm.zig
This commit documents the status of Run-time ABI 2022Q3 for ARM excluding C++ helper functions.
=> compiler_rt: document ARM status

lib/std/builtin.zig, lib/std/debug.zig, lib/std/os.zig, src/Module.zig
Thanks to @jacobly0's recent enhancements to the C backend, this stuff works now.
Example code:
```zig
foo();
}
fn foo() void {
@panic("crash");
}
```
With these changes, I was able to get the following output:
```
$ stage4/bin/zig run test.zig -ofmt=c -lc
thread 2170091 panic: crash
/home/andy/.cache/zig/o/94655884186a733d45f84ff29e3268a1/test.c:3808:2: 0x20e3f6 in test_foo__148 (/home/andy/.cache/zig/o/94655884186a733d45f84ff29e3268a1/test.c)
builtin_default_panic__192((anon__148_39){(uint8_t const *)((uint8_t const *)&test_foo__anon_2586__2586), (uintptr_t)5ul}, ((struct StackTrace__991 *)NULL), (anon__148_43){ .payload = (uintptr_t)0xaaaaaaaaaaaaaaaaul, .is_null = true });
^
/home/andy/.cache/zig/o/94655884186a733d45f84ff29e3268a1/test.c:3513:2: 0x20e308 in …
```
=> enable debugging infrastructure when using C backend

lib/std/fs/test.zig, test/standalone/windows_spawn/main.zig
On Windows, a directory that's set as the current working directory is not allowed to be removed. This can cause error on `deleteTree` if the CWD is set to the handle to be removed and will result in `error.FileBusy`. However, due to `tmp.cleanup()` ignoring the errors, the folder removal error will be ignored. (Possibly Related: #15465)
The only test that I found to be violating this is `windows_spawn` as it sets CWD to the tmp dir then tries to remove it. I added a test to verify this occurrence. 
Another option for solving is to always set the CWD to the parent in both `cleanup()` functions: 
https://github.com/ziglang/zig/blob/7285eedcd26b92afb03c313a167133103a78ded5/lib/std/testing.zig#L520-L525
I hate to take another guess, but this \* _might be_ \* be the last test causing the …
=> test: Fix windows_spawn tmp directory cleanup

lib/std/os/linux.zig
fix incorrect structure definition of `io_uring_probe` and `io_uring_restriction`. 
Change `u32[3]` to `[3]u32`. And according to [liburing](https://github.com/axboe/liburing/blob/4fed79510a189cc7997f6d04855ebf7fb66cc323/src/include/liburing/io_uring.h#L599-L605) the definition of `io_uring_probe` should have a c pointor to `io_uring_probe_op`.
In `liburing`:
```c
struct io_uring_probe {
__u8 last_op;	/* last opcode supported */
__u8 ops_len;	/* length of ops[] array below */
__u16 resv;
__u32 resv2[3];
struct io_uring_probe_op ops[];
};
```
=> fix bug: fix incorrect structure definition

lib/std/Thread/Condition.zig
Verified by running the changed tests in a loop at the same time as an uncached `zig build test` which uses 100% cpu for extended periods of time, and deadlocks without these changes within 10 seconds.
Since reliably reproducing this deadlock is so correlated with cpu usage, I think that this is the most likely cause for #14948 which only started happening with parallel builds.
=> std: prevent the possibility of deadlocks in some threaded tests

lib/test_runner.zig, src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Emit.zig, src/arch/x86_64/Encoding.zig, src/arch/x86_64/Lower.zig, src/arch/x86_64/Mir.zig, src/arch/x86_64/bits.zig, src/arch/x86_64/encoder.zig, src/arch/x86_64/encodings.zig, src/link/Coff.zig, src/link/Coff/Relocation.zig, src/link/MachO.zig, src/link/MachO/Relocation.zig, test/behavior/align.zig, test/behavior/basic.zig, test/behavior/bugs/12571.zig, test/behavior/bugs/12776.zig, test/behavior/bugs/13069.zig, test/behavior/bugs/1851.zig, test/behavior/eval.zig, test/behavior/fn.zig, test/behavior/math.zig, test/behavior/packed-struct.zig, test/behavior/pointers.zig, test/behavior/popcount.zig, test/behavior/union.zig, test/behavior/vector.zig, test/src/Cases.zig
This allows abstract references to the stack frame which enables:
* deferred frame layout until after the function has been processed
* frame compaction (sorting by alignment)
* being able to overalign the stack
* references that change based on an overaligned stack
* moving callee saved spills to the usual part (smaller code size)
* shared call frame (avoids stack adjustments before and after calls)
=> x86_64: add frame indices

src/Module.zig, src/Sema.zig, test/cases/decl_value_arena.zig
Fixes https://github.com/ziglang/zig/issues/15150.
This fixes a bug where resolveStructLayout was promoting from stale value_arena state which was then overwritten when another ArenaAllocator higher in the call stack saved its state back. This resulted in the memory for struct_obj.optmized_order overlapping existing allocations.
My initial fix in c7067ef wasn't sufficient, as it only checked if the struct being resolved had the same owner as the current sema instance. However, it's possible for resolveStructLayout to be called when the sema instance has a different owner, but the struct decl's value_arena is currently in use higher up in the callstack.
This change introduces ValueArena, which holds the arena state as well as tracks if an arena has already been promoted from it. This …
=> sema: Rework Decl.value_arena to fix another memory corruption issue

lib/std/builtin.zig, src/Sema.zig, src/type.zig, test/cases/compile_errors/bad_usage_of_call.zig
Fixes https://github.com/ziglang/zig/issues/15489
This also lays the groundwork for exposing whether or not a function is
noinline in std.builtin.Fn as an `is_noinline: bool` field if we ever want to do that.
=> Sema: emit error for always_inline call of noinline function

src/main.zig
Fixes https://github.com/ziglang/zig/issues/15499.
In https://github.com/ziglang/zig/pull/14771 I added support for `--no-dynamicbase`, but I removed the parsing of the `--dynamicbase` linker argument, since being enabled is the default. 
That broke any tooling that still passed `--dynamicbase` to the linker. This PR fixes that.
=> Parse --dynamicbase linker arg

lib/std/Build.zig
Closes #14822.
This PR implements the simple solution I mentioned in the linked issue by using a hashmap to detect when an attempt is made to add a top-level step with the same name as a pre-existing one. When this happens the build runner panics, with a message saying which step name caused a collision.
=> std.Build: detect and disallow top-level step name clashes

src/Sema.zig, test/cases/compile_errors/double_pointer_to_anyopaque_pointer.zig, test/cases/compile_errors/pointer_to_anyopaque_slice.zig
Before this change, the message for the new test case [test/cases/compile_errors/pointer_to_anyopaque_slice.zig](https://github.com/ziglang/zig/pull/15488/files#diff-8f3223e616ca12f5028ff69d0af6d802fcc545e71fe0d5750feb8b8f239742b4) looked like this:
```
test\cases\compile_errors\pointer_to_anyopaque_slice.zig:4:9: error: @bitCast size mismatch: destination type '[]anyopaque' has 128 bits but source type '*u32' has 64 bits
b = a;
^
```
This is the result of this suggestion: https://github.com/ziglang/zig/pull/15434#pullrequestreview-1397607212
=> sema: improve the error message when coercing to []anyopaque

lib/std/crypto/pbkdf2.zig
Hi there! I noticed an inaccuracy in the [docs for pbkdf2](https://ziglang.org/documentation/master/std/#A;std:crypto.pwhash.pbkdf2) (the namespace for [SHA256 et al](https://github.com/ziglang/zig/blob/e963793e37f93d84f1e5295d309ebe0c738b663d/lib/std/crypto/hmac.zig#L9-L14) has been updated to be behind `sha2`).
Thanks!
=> Fix PBKDF2 docstring comment

src/AstGen.zig, src/BuiltinFn.zig, src/Sema.zig, src/Zir.zig, src/arch/x86_64/CodeGen.zig, src/print_zir.zig, src/type.zig, test/behavior/maximum_minimum.zig
=> Implement multi-argument @min/@max and notice bounds

doc/langref.html.in
The use of `extern "..."` for specifying the library that has the definition was undocumented. Fixes #13906
=> langref: Documented `extern "..."` use

lib/std/log.zig
I ran into this compile error while working on a project that targets wasm32-freestanding and felt it was unnecessarily restrictive so I'm putting removing it up as a suggestion.
Programs that provide their own implementation of the subset of `os.system` features required for writing to stderr shouldn't need to also override the default logging function just to be allowed to use `std.log`.
Looking at why this was added in 6f17be063d37f5ecd9552479e65428a5c60d9152, it seems to be because a compile error is preferable over the previous runtime no-op. Removing this line replaces still results in a compile error, but the message is now
>error: struct 'os.system__struct_1234' has no member named 'fd_t'.
which is less informative but is the same error as you get when using other "print to …
=> std.log.defaultLog: remove freestanding compile error

lib/std/crypto/tls/Client.zig
Looks like the current implementation of `limitVecs` doesn't match its description.  Here's a program that demonstrates the bug:
```zig
fn getCapacity(vecs: []const std.os.iovec) usize {
var total: usize = 0;
for (vecs) |vec| {
total += vec.iov_len;
}
return total;
}
var bad_case = [_]std.os.iovec{ .{ .iov_len = 3, .iov_base = undefined } };
var vecs_current = limitVecsCurrent(&bad_case, 1);
std.log.info("capacity={}", .{getCapacity(vecs_current)});
var vecs_new = limitVecsCurrent(&bad_case, 1);
std.log.info("capacity={}", .{getCapacity(vecs_new)});
}
fn limitVecsCurrent(iovecs: []std.os.iovec, len: usize) []std.os.iovec {
var vec_i: usize = 0;
var bytes_left: usize = len;
while (true) {
if (bytes_left >= iovecs[vec_i].iov_len) { …
```
=> fix bug and simplify std.crypto.tls.Client.limitVecs

src/AstGen.zig, src/Sema.zig, src/Zir.zig, src/print_zir.zig
`isAlwaysVoid` was being called with the undefined tag added by `addOne`, causing non-deterministic behavior failures with release builds of the compiler.  Prevents the following random failure:
test/behavior/defer.zig:120:40: error: expected type 'error{One}', found 'void'
=> AstGen: fix branch on undefined

src/codegen/c.zig
Unfortunately, I need a `zig1.wasm` update that includes this fix in order for #15597 to be able to pass CI.  This is not an immediate blocker, but it be within a week.
=> cbe: fix typos

lib/std/zig/number_literal.zig, src/AstGen.zig, test/cases/compile_errors/number_literal_bad_exponent.zig
Closes #15480.
The linked issue is caused by the tokenizer not separating tokens between an 'e' and a '+' or '-', so a string like `0xab0e+3` would be tokenized as a single token, while AstGen asserts that the tokenizer doesn't do this. There are two fixes I can see - generate multiple tokens as is done for the string `1+3` or generate an error as it may be a footgun. ~This PR currently generates the addition tokens, so the above example would be tokenized in the same way as `0xab0e + 3` (i.e. as if there were spaces around `+`), but could be reworked to generate an error.~
When a hexadecimal number literal such as `0x12abe-4` is encountered, an error will be reported like this:
<pre><b>test.zig:1:18: </b><font color="#BF616A"><b>error:</b> </font><b>sign &apos;-&apos; cannot follow digit …
=> Fix parsing of hexadecimal literals

lib/std/zig/Ast.zig, lib/std/zig/parser_test.zig, lib/std/zig/render.zig
This can be used to escape the usual meaning of `_` to indicate a non-exhaustive enum and create an enum tag that is a literal underscore, so zig fmt should allow this syntax.
Before, zig fmt changes
const E = enum { @"_" };
to the semantically different
const E = enum { _ };
After, it remains the same.
=> fmt: avoid canonicalizing enum fields named `@"_"` to `_`

lib/std/fmt.zig, lib/std/hash_map.zig, lib/std/io/reader.zig, lib/std/math/big/int_test.zig, lib/std/math/big/rational.zig, lib/std/net/test.zig, lib/std/priority_dequeue.zig, lib/std/zig/parser_test.zig, src/Module.zig, test/behavior.zig, test/behavior/basic.zig, test/behavior/comptime_memory.zig, test/behavior/duplicated_test_names.zig, test/behavior/vector.zig, test/cases/compile_errors/invalid_duplicate_test_decl_name.zig
Closes #13599 and #14583.
This change prevents (named) test decls from sharing a name if they are in the same namespace. If two tests have the same name, an error is reported like so:
```
/path/to/main.zig:1:6: error: found test declaration with duplicate name: test.thingy
test "thingy" {}
^~~~~~~~
/path/to/main.zig:2:6: note: other test here
test "thingy" {}
^~~~~~~~
```
This change caught several tests in `lib/std` and `test/behavior` that were silently skipped due to the issues referenced above. I have resolved the tests with duplicated names (first two commits), though someone should check that I have done this suitably as I was unsure if some of them were needless duplication or not.
=> Disallow named test decls with duplicate names

lib/std/fmt/parse_float/common.zig, lib/std/fmt/parse_float/parse_float.zig
I experienced an error while writing some code:
```zig
var reset: u64 = try std.fmt.parseFloat(u64, resetStr);
```
Obviously, you can't parse a float into a u64, but the error message this gave confused me a little bit:
```zig
/home/jvyden/Documents/zig/build/stage4/lib/zig/std/fmt/parse_float/common.zig:89:17: error: reached unreachable code
else => unreachable,
^~~~~~~~~~~
/home/jvyden/Documents/zig/build/stage4/lib/zig/std/fmt/parse_float/common.zig:57:31: note: called from here
mantissa: mantissaType(T),
~~~~~~~~~~~~^~~
```
I tried to fix this with by changing the unreachable to a `@compileError`, but [tiehuis had a better suggestion](https://github.com/ziglang/zig/pull/15593#issuecomment-1537265319). The error now prints a stack trace when calling `parseFloat` directly:
```zig …
```
=> parse_float: Error when a float is attempted to be parsed into an invalid type

doc/langref.html.in
Hey there! Notice a 1-line typo in the language reference.
=> Fix langref typo

lib/std/crypto/tls/Client.zig
Looks like #15278 broke `finishRead2`, which relied on the old overlapping semantics. To reproduce, run the test program in #14573. Note that I'm unsure whether the other callsites of `@memcpy` in `Client.zig` rely on the old behavior, this is just the one that immediately broke the test program.
I'm also unable to reproduce #14573 after applying this patch and running the test program hundreds of times. It may have been fixed somewhere along the way.
=> tls: update finishRead2 for new @memcpy semantics

lib/build_runner.zig, lib/std/fmt.zig
=> Add std.fmt.parseIntSizeSuffix and use for --maxrss

lib/std/mem.zig
This introduces a parallel set of functions to the std.mem.indexOfAny functions. They simply invert the logic, yielding the first/last index which is *not* contained in the "values" slice.
Inverting this logic is useful when you are attempting to determine the initial span which contains only characters in a particular set. For example, finding the length of an integer literal could be done (somewhat naively) using indexOfNone.
This is my first attempt to contribute to Zig, so please let me know of any steps I accidentally skipped or mistakes I made.
=> Add std.mem.indexOfNone

lib/std/fmt.zig
https://www.nist.gov/pml/owm/metric-si-prefixes
https://www.npl.co.uk/si-prefix
https://www.nature.com/articles/d41586-022-03747-9
=> std.fmt.parseIntSizeSuffix: add R and Q

src/Module.zig, test/cases/compile_errors/issue_15572_break_on_inline_while.zig
Closes #15572.
The example in the issue now results in this:
```zig
main.zig:9:28: error: incompatible types: 'builtin.Type.EnumField' and 'void'
const section = inline for (@typeInfo(DwarfSection).Enum.fields) |section| {
~~~~~~~^~~
referenced by:
comptime_0: /Users/<USER>/repos/zig/lib/std/start.zig:63:50
remaining reference traces hidden; use '-freference-trace' to see all reference traces
```
=> module: return null if no candidate src

lib/zig.h, src/codegen/c.zig, src/codegen/llvm.zig, test/behavior/math.zig
Both `@mod` and `@divFloor` were computed incorrectly in the C backend, and `@mod` was computed incorrectly in the LLVM backend.  Also minor C backend cleanup.
Closes #15636
=> llvm/cbe: fix signed `@mod`/`@divFloor` computations

doc/langref.html.in, lib/docs/main.js, lib/std/Build/Cache/DepTokenizer.zig, lib/std/array_list.zig, lib/std/bounded_array.zig, lib/std/compress/deflate/decompressor.zig, lib/std/compress/deflate/huffman_bit_writer.zig, lib/std/hash/crc.zig, lib/std/hash/wyhash.zig, lib/std/json.zig, lib/std/math/big/int.zig, lib/std/net.zig, lib/std/os/windows.zig, lib/std/testing.zig, lib/std/unicode.zig, src/AstGen.zig, src/Autodoc.zig, src/Sema.zig, src/Zir.zig, src/link/Plan9/aout.zig, src/print_zir.zig, test/behavior/slice.zig
Closes #15482.
This PR implements a new ZIR instruction `slice_length` to facilitate optimizing lowering of the slice-by-length pattern `s[start..][0..len]`. 
This PR makes one change to the change to the language (discussion [here](https://github.com/ziglang/zig/pull/15519#issuecomment-1532352304)): you can now slice a multi-pointer using the slice-by-length syntax, i.e. `ptr[start..][0..len]`; previously, use of this pattern would cause a compile error due to slicing multi-pointers without a end being an error.
Taking the example function in the linked issue:
```zig
fn foo(s: []const i32, start: usize, len: usize) []const i32 {
return s[start..][0..len];
}
```
The core change this makes in the ZIR is:
```diff
- %16 = dbg_stmt(2, 13)
- %17 = slice_start(%15, %6) node_offset:2:12 to :2:22 …
```
=> Optimize lowering of `s[start..][0..len]`

lib/std/os.zig, lib/std/os/linux.zig
I'm unsure if there's a better or additional way to test this, but it's currently running happily running https://github.com/GrayHatter/hsh/blob/main/src/tty.zig#L101,L106
=> Add tc{set,get}pgrp to std.os.linux

lib/std/math/atan.zig
The constant must have been mistyped while being ported over from musl.
Bug found and rectified by WiserOrb.
Co-authored-by: WiserOrb <diego99.masotti@gmail.com>
=> std.math.atan: fix mistyped magic constant

src/codegen/llvm.zig
This change adds a simple pattern match for a short AIR sequence of 'struct_field_ptr -> load -> array_elem_val', and generates same LLVM IR as the sequence of 'struct_field_ptr -> ptr_elem_ptr -> load'.
Although this change will still generate CallInst of Memcpy, LLVM will successfully identify the CallInst as dead code and eliminate it, preventing unuseful memcpy of the array field.
Resolves https://github.com/ziglang/zig/issues/13938
=> Optimize access of array member in a structure.

doc/langref.html.in
- 768 -> 786
- The link seems to be correct
- The link-text points to a seemingly unrelated issue
=> Fix typo in langref

lib/docs/main.js
Unlike `keydown`, the `input` event is dispatched regardless of how the input value was changed - key press, keyboard paste, mouse paste, ...
Closes #15632.
=> autodoc: Start search on any search input event, not just keydown

CMakeLists.txt, build.zig
Depends on https://github.com/ziglang/release-cutter/pull/4
=> CMakeLists.txt and build.zig: remove deprecated options

src/Sema.zig, test/behavior/memcpy.zig, test/cases/compile_errors/incorrect_type_to_memset_memcpy.zig
Closes #15638, with parts being reused with attribution
=> `@mem{cpy,set}` fixes

lib/std/mem.zig
The current implementation of `zeroInit` will leave padding undefined which is not consistent with its comments:
> /// Initializes all fields of the struct with their default value, or zero values if no default value is present.
Let's fix it.
=> std.mem.zeroInit: zero all hidden padding for extern struct

lib/docs/main.js
Before this fix clicking on any module in under `Dependencies` did nothing and still rendered main module
=> autodoc: Fix rendering of imported modules

lib/std/crypto/aegis.zig
In an update whose size is not a multiple of the block size, we would end up calling `@memcpy()` with arguments of different sizes.
=> crypto.AegisMac: fix a regression from s/mem.copy/@memcpy/

src/main.zig
closes #7170
```
$ stage4/bin/zig cc -### -c hello.c
clang version 16.0.3 (git@github.com:llvm/llvm-project.git 6e5368c3967a68e6b5bd047c7ec606e4c7348c8d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /run/current-system/sw/bin
(in-process)
"/home/andy/Downloads/zig/build-release/stage4/bin/zig" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-emit-obj" "-mrelax-all" "-disable-free" "-clear-ast-before-backend" "-main-file-name" "hello.c" "-mrelocation-model" "pic" "-pic-level" "2" "-fhalf-no-semantic-interposition" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "x86-64" "-tune-cpu" "generic" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debug-info-kind=constructor" …
```
=> zig cc: implement `-###` (dry run)

build.zig, lib/std/Build.zig, lib/std/Build/Cache.zig, lib/std/Build/Step/Compile.zig, src/Compilation.zig, src/link.zig, src/link/Elf.zig, src/link/Wasm.zig, src/main.zig
The hash of the build-id of the wasm binaries will change, because we are hashing a bit less now.
Deprecates `-fbuild-id` and `-fno-build-id` in favor of `--build-id[=style]`.
Fixes #12777
=> stage2: implement `--build-id` styles

lib/std/sort.zig
Maybe I'm dumb and there is some hidden definition that all sorts need to be ascending, but I had to spend a couple minutes digging looking at the test cases to figure this out.
=> Document the sorting order in `std.sort`.

build.zig, src/Compilation.zig, src/main.zig, stage1/config.zig.in
When producing zig2.c, don't waste time emitting C code for subcommands that won't be used, such as `zig objcopy`.
This takes zig2.c down from 111M to 109M, and sidesteps some unfortunate warnings that are currently emitted by GCC.
The second commit renames `omit_pkg_fetching_code` to `only_core_functionality` to better reflect how it is used.
=> zig2.c: omit non-essential subcommands

lib/std/crypto/tls/Client.zig
* When there is buffered cleartext, return it without calling the underlying read function. This prevents buffer overflow due to space used up by cleartext.
* Avoid clearing the buffer when the buffered cleartext could not be completely given to the result read buffer, and there is some buffered ciphertext left.
* Instead of rounding up the amount of bytes to ask for to the nearest TLS record size, round down, with a minimum of 1. This prevents the code path from being taken which requires extra memory copies.
* Avoid calling `@memcpy` with overlapping arguments.
closes #15590
=> std.crypto.tls.Client.readvAdvanced: fix bugs

src/Module.zig, test/cases/compile_errors/invalid_duplicate_test_decl_name.zig
* Avoid redundant words ("found")
- All compile errors are found by the compiler
* Avoid unnecessary prepositions ("with")
- There is a grammatically correct alternate word order without the preposition.
=> Sema: simplify "duplicate test name" error message

src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Encoding.zig, src/arch/x86_64/Lower.zig, src/arch/x86_64/Mir.zig, src/arch/x86_64/encoder.zig, src/arch/x86_64/encodings.zig, src/codegen.zig, test/behavior/bitcast.zig, test/behavior/bugs/13128.zig, test/behavior/eval.zig, test/behavior/floatop.zig, test/behavior/math.zig, test/behavior/maximum_minimum.zig, test/behavior/saturating_arithmetic.zig, test/behavior/truncate.zig, test/behavior/vector.zig, test/behavior/widening.zig
* float `@min`/`@max`
* redo casts
* big cmp
* 128-bit atomics not on linux
* integer vector `@truncate`
* global vector padding
* saturating add/sub
* 91% (1463/1613) behavior tests natively vs llvm
* opening to unblock #15701
=> x86_64: behavior

lib/std/io/multi_writer.zig
Since #14819 this test failed with:
$ ../../../build/stage3/bin/zig test multi_writer.zig
multi_writer.zig:26:57: error: unable to evaluate comptime expression
var batch = std.event.Batch(Error!void, self.streams.len, .auto_async).init();
~~~~^~~~~~~~
referenced by:
Writer: multi_writer.zig:19:52
writer: multi_writer.zig:21:36
remaining reference traces hidden; use '-freference-trace' to see all reference traces
Thanks @jacobly0 for hints how to fix this on IRC.
=> multi-writer: test with a non-comptime stream

src/Sema.zig, src/Zir.zig, src/print_air.zig, src/type.zig
This was a special type tag used for hacky stuff in Semantic Analysis. Move the hacky stuff to use a dedicated `Air.Inst.Ref` instead.
This way, `var_args_param` is not involved in the type system or intern pool.
=> Sema: eliminate `Type.Tag.var_args_param`

lib/std/meta.zig
any comptime parameter sets `.is_generic` to be true but in many cases these will still be discrete types available in `.params`
=> std.meta: allow ArgsTuple to be used on functions with comptime parameters

lib/std/Thread/Mutex.zig, lib/std/crypto/siphash.zig, lib/std/hash/auto_hash.zig, lib/std/hash/wyhash.zig, src/AstGen.zig, src/Autodoc.zig, src/Module.zig, src/Sema.zig, src/TypedValue.zig, src/Zir.zig, src/print_air.zig, src/print_zir.zig, src/type.zig, src/value.zig, test/behavior/member_func.zig, test/cases/compile_errors/member_function_arg_mismatch.zig
This commit removes the `field_call_bind` and `field_call_bind_named` ZIR instructions, replacing them with a `field_call` instruction which does the bind and call in one.
`field_call_bind` is an unfortunate instruction. It's tied into one very specific usage pattern - its result can only be used as a callee. This means that it creates a value of a "pseudo-type" of sorts, `bound_fn` - this type used to exist in Zig, but now we just hide it from the user and have AstGen ensure it's only used in one way. This is quite silly - `Type` and `Value` should, as much as possible, reflect real Zig types and values.
It makes sense to instead encode the `a.b()` syntax as its own ZIR instruction, so that's what we do here. This commit introduces a new instruction, `field_call`. It's like `call`, but …
=> Zir: eliminate `field_call_bind` and `field_call_bind_named`

lib/test_runner.zig, src/arch/wasm/CodeGen.zig, test/behavior/int128.zig, test/behavior/math.zig, test/behavior/memset.zig, test/behavior/slice.zig
This implements the remaining instructions to enable the standard test runner rather than the simplified one.
=> wasm: enable standard test runner

lib/std/Build.zig, src/Package.zig
Very basic implementation. One key thing that this should probably be made to do at some point is validate that every argument passed to the `build` function which is used, has the same value on future calls to `dependency`.
=> Deduplicate uses of the same package across dependencies

lib/std/crypto/pcurves/p256/scalar.zig, lib/std/crypto/pcurves/p384/scalar.zig, lib/std/crypto/pcurves/secp256k1/scalar.zig, lib/std/crypto/pcurves/tests/p256.zig, lib/std/crypto/pcurves/tests/p384.zig, lib/std/crypto/pcurves/tests/secp256k1.zig
Just adding `Secp256k1.scalar.Scalar.isOdd` for convenience and a basic test to cover it
=> std.crypto: expose Fe isOdd & add basic parity tests for each pcurve
