lib/std/zig/Ast.zig
=> Ast: fix expected_block error message

src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/x86_64/CodeGen.zig, test/behavior/basic.zig, test/behavior/const_slice_child.zig, test/behavior/eval.zig, test/tests.zig
=> Bitcast fixes for self-hosted native backends

src/Package.zig
Fixes leaked file handles in https://github.com/ziglang/zig/issues/14699 and package problems with Windows.
=> Close files in hashFileFallible

lib/std/Build/CompileStep.zig, src/Package.zig
=> fix package hashes on Windows

lib/build_runner.zig, src/main.zig
=> Add --build-runner `zig build` option

lib/std/crypto/keccak_p.zig
Existing tests were only testing Keccak with f=1600, so add a test vector for a reduced size, from the XKCP test vectors.
=> crypto.KeccakF: compute rotations at comptime, add a test with f=800

lib/std/crypto/25519/field.zig
=> crypto.25519.field: de-inline _sq()

src/link/Wasm.zig
Give +x to the .wasm file if it is an executable and the OS is WASI. Some systems may be configured to execute such binaries directly. Even if that is not the case, it means we will get "exec format error" when trying to run it rather than "access denied", and then can react to that in the same way as trying to run an ELF file from a foreign CPU architecture.
This is part of the strategy to unify RunStep and EmulatableRunStep.
=> link: give executable bit to wasm executables sometimes

lib/std/zig/Ast.zig, test/behavior/tuple.zig
=> Ast: properly handle sentinel-terminated slices in tuple

lib/std/Build.zig
This was originally a typo, and it's causing confusion now, so I wanted to fix it before reviewing more complex PRs such as #14731.
=> std.Build.addModule: return the created module

src/AstGen.zig, test/cases/compile_errors/exporting_primitive_values.zig
=> AstGen: compile-error on primitive value export

src/Package.zig
Close #14777.
After some debugging, I found this bug is introduced in https://github.com/ziglang/zig/commit/db8217f9a080f7c645a6448640a9af65f3944818. 
It should only append dep to `build_roots_source` when `pkg_dir` exists.
=> fix package redeclaration when pkg_dir is not exists

lib/std/multi_array_list.zig, tools/lldb_pretty_printers.py
```
(lldb) frame variable list
(multi_array_list.MultiArrayList(repro.main__struct_3807)) list = len=3 capacity=8 {
[0] = (*y = 1, *x = 1, *z = '\x01')
[1] = (*y = 3, *x = 2, *z = '\x02')
[2] = (*y = 9, *x = 4, *z = '\x03')
}
(lldb) frame variable slice
(multi_array_list.MultiArrayList(repro.main__struct_3807).Slice) slice = len=3 capacity=8 {
[0] = (*y = 1, *x = 1, *z = '\x01')
[1] = (*y = 3, *x = 2, *z = '\x02')
[2] = (*y = 9, *x = 4, *z = '\x03')
}
```
=> tools: add lldb pretty printer for `std.MultiArrayList.Slice`

lib/std/os/windows/advapi32.zig
Adds [RegCloseKey](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regclosekey).
=> std.os.windows.advapi32: Add RegCloseKey

src/Sema.zig, test/cases/compile_errors/comptime_try_non_error.zig
=> Sema: check type of comptime try operand

test/cases/compile_errors/comptime_try_non_error.zig
=> Fix test case added in 6d7fb8f

src/Sema.zig, src/value.zig, test/cases/compile_errors/reify_type_with_undefined.zig
=> Sema: correctly detect use of undefined within slices in @Type

src/Module.zig
=> retry cache file creation

lib/std/array_list.zig
Also test and document that inserting at list.items.len is allowed.
=> std: Add ArrayList.insertAssumeCapacity()

src/Sema.zig, test/cases/compile_errors/method_call_with_first_arg_type_primitive.zig, test/cases/compile_errors/method_call_with_first_arg_type_wrong_container.zig
=> Sema: improve error message when calling non-member function as method

src/Sema.zig, test/behavior.zig, test/behavior/return_address.zig
See also #14938.
Resolves: #14931
=> Sema: make @returnAddress return 0 at comptime

lib/build_runner.zig
--sysroot was copy-pasted instead of --maxrss from above. Also, make it less likely in other places for this to be repeated.
I found this by accident when reviewing f51413d2cf0bd87079dace7f6481d2a361a19ea6
=> fix copy-paste errors

lib/std/Build/CheckObjectStep.zig, lib/std/Build/CompileStep.zig, test/link/macho/dylib/build.zig
=> build: fix adding rpaths on darwin, improve CheckObjectStep to allow matching FileSource paths

src/arch/x86_64/CodeGen.zig, src/arch/x86_64/abi.zig, src/register_manager.zig, test/behavior/array.zig, test/behavior/bugs/10970.zig, test/behavior/cast.zig, test/behavior/enum.zig, test/behavior/for.zig, test/behavior/if.zig, test/behavior/switch.zig, test/behavior/union.zig, tools/lldb_pretty_printers.py
* regress ~~two~~ ~~four~~ two behavior tests
* fix ~~three~~ ~~eight~~ nine behavior tests
I'll ***really*** take it!
=> x86_64: fix value tracking bugs

tools/zig_gdb_pretty_printers.py
The debug info for optionals was changed, and I cleaned up the formatting to fit PEP8 while I was in there
=> Update GDB pretty printers

lib/libc/include/any-macos-any/sys/timex.h
=> libc: add missing sys/timex.h to macOS libc headers

lib/docs/main.js, src/Autodoc.zig
fix rendering of fieldRef in exprName
=> autodoc: Add struct to tryResolveRefPath

src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/MachO/Relocation.zig
Don't special-case resolving of `dyld_stub_binder`.
=> macho: refactor adding GOT and stub entries

lib/std/fs/path.zig, lib/std/heap/arena_allocator.zig
... by fixing the underlying memory bugs, of course! :smile:
=> std: delete the new GPA errors triggered by CI

lib/std/c/darwin.zig
=> std: add os_log/signpost api (sort of linux's perf event equivalent)

lib/std/process.zig
=> Fix crash on some Windows machines

lib/std/debug.zig
Test case:
```zig
var t1 = try std.Thread.spawn(.{}, throwSegFault, .{});
defer t1.join();
var t2 = try std.Thread.spawn(.{}, throwPanic, .{});
defer t2.join();
}
fn throwSegFault() void {
const ptr = @intToPtr(*u8, 0x1);
ptr.* = 1;
}
fn throwPanic() void {
var x: u8 = 255;
x += 1;
}
```
Before it was inconsistent but usually:
```
$ ./test
Segmentation fault at address 0x1
thread 763743 panic: integer overflow
???:?:?: 0x20f214 in ??? (???)
Panicked during a panic. Aborting.
Aborted (core dumped)
```
After, it is consistently:
```
$ ./test
Segmentation fault at address 0x1
/home/andy/dev/zig/build-release/test.zig:15:5: 0x20e073 in throwSegFault (test)
ptr.* = 1;
^
/home/andy/dev/zig/lib/std/Thread.zig:406:13: 0x22e81a in callFn__anon_6280 …
```
=> std.debug: fix segfault/panic race condition

lib/std/os.zig
=> std.os.sendto: use ws2_32 on Windows

build.zig
=> Add `omit_pkg_fetching_code` option to test_cases

lib/libc/include/any-macos-any/getopt.h
=> macos: add missing getopt.h header

src/arch/x86_64/CodeGen.zig, src/codegen.zig, test/behavior/array.zig, test/behavior/atomics.zig, test/behavior/bugs/718.zig, test/behavior/bugs/7325.zig, test/behavior/pointers.zig
Not anymore, now that liveness is fixed.  This _almost_ turned into liveness stuff, but decided to get this liveness-independent stuff in first.
=> x86_64: fix various miscompilations

lib/std/crypto/ecdsa.zig, lib/std/crypto/pcurves/secp256k1.zig
=> secp256k1: Endormorphism.splitScalar() can return an error

src/main.zig
=> Fix `zig cc` flags for Wasm

src/Sema.zig, test/standalone.zig, test/standalone/strip_empty_loop/build.zig, test/standalone/strip_empty_loop/main.zig
I'm not a fan of tests that don't test anything, but how would you even test that an infinite loop does indeed infinite loop.
Closes #15284
=> Sema: fix empty infinite loops

src/arch/x86_64/CodeGen.zig, src/arch/x86_64/encoder.zig, src/link/tapi/parse.zig
* downstream fixes to memory bugs in the yaml parser
* clean up formatting functions in x86_64 encoder
=> Misc cleanups

lib/std/c/freebsd.zig
adding getentropy and cpuset_(get/set)affinity calls.
=> std: freebsd update proposal.

lib/std/debug.zig
Changes:
- Change the segfault handler to walk the stack via the method that is aware of unwind info (fixes x86_64 / aarch64 traces). Walking the stack using the rbp method isn't valid on non-x86 Windows.
- Enhance the output for frames where the debug info isn't available by printing the module name
This may also close https://github.com/ziglang/zig/issues/13114, but I can't verify that (don't have a linux testing setup atm).
Previously, the printing the stack would terminate early at the first frame where debug info wasn't available:
```
>zig-out\bin\main.exe
Illegal instruction at address 0x7ffab7751052
```
This is a common scenario when linking with a C library - since by default `-g` isn't set in Debug.
Now, info for all frames is printed, and it will include the name of the module …
=> Fix missing stack traces during segfaults on Windows, enhance output when debug info is missing

lib/std/os/linux/io_uring.zig
=> work around an intermittent io_uring test failure

lib/std/fs.zig
Docs that link back to the other similar functions.
=> std.fs: add linking docs to makeDir*

lib/std/Thread.zig
I noticed this comment saying the intent of the code's author was unclear.
`setName`:
`prctl` can set or get the name of the "calling thread", i.e. the thread that calls the function, hence we don't need to pass a thread id to it. In the first `if` statement they forgot an `is_gnu` because that function is actually a GNU extension which allows setting or getting any thread's name. If the thread is the calling thread, it also works and it'll just delegate to `prctl` internally, is what I read.
In the `else if` below `self.getHandle() == std.c.pthread_self()` means "are we the calling thread", and that's when you can call `prctl`.
Otherwise, it just does the `"/proc/self/task/{d}/comm"` thing in the `else` below.
`getName`:
It's similar except there was an additional `else if …
=> std.Thread: use dead code

lib/std/heap.zig, lib/std/heap/general_purpose_allocator.zig, lib/test_runner.zig, test/standalone/windows_spawn/main.zig
=> std: GPA deinit return an enum instead of a bool

doc/docgen.zig
=> docgen: fix exe_build_err code snippets

lib/docs/main.js, src/Autodoc.zig
special case inline cc in exprName
=> autodoc: Handle calling conventions better

lib/docs/main.js, src/Autodoc.zig
Each file is now saved with its package index in data.json
=> Autodoc: html files for sources scoped with respect to packages

lib/std/process.zig
To improve understandability of its purpose.
=> process: add args definition comment

doc/langref.html.in, lib/std/Build/Cache.zig, lib/std/RingBuffer.zig, lib/std/Uri.zig, lib/std/array_list.zig, lib/std/bit_set.zig, lib/std/builtin.zig, lib/std/compress/zstandard.zig, lib/std/compress/zstandard/decode/fse.zig, lib/std/debug.zig, lib/std/fmt.zig, lib/std/fs/path.zig, lib/std/macho.zig, lib/std/math.zig, lib/std/mem.zig, lib/std/os/linux/seccomp.zig, lib/std/rand.zig, src/Air.zig, src/Autodoc.zig, src/Sema.zig, src/link/NvPtx.zig, src/main.zig, test/cases/compile_errors/union_init_with_none_or_multiple_fields.zig, test/cases/compile_errors/variadic_arg_validation.zig
A batch of fixes to docs and text I amassed over time.
I wasn't sure when the right time would be to post this but I had my first merge conflict yesterday so maybe now is a time to push this.
=> Improvements to docs and text

lib/zig.h, src/Compilation.zig, src/Module.zig, src/codegen/c.zig, src/codegen/c/type.zig, src/link/C.zig, test/behavior/basic.zig
=> cbe: implement `@extern`

lib/docs/commonmark.js, lib/docs/index.html, lib/docs/main.js, src/Autodoc.zig
as part of the work to add search support for guides, the main decl search system has been revamped
=> Autodoc: new decl search system

src/Sema.zig, src/codegen/c.zig
This gives a ~3% decrease in LOC for the compiler with `-Donly-c`, and a ~12% decrease in LOC for behavior tests with `-OReleaseFast -fstrip`. Compilation speed unfortunately doesn't improve too much, but it's not nothing - behavior tests seem to build 2-5% faster from quick testing.
=> CBE: minor optimizations to output source

src/translate_c.zig
=> translate-c: deduplicate global declaration

src/Sema.zig, test/cases/compile_errors/indexing_non-tuple_struct.zig
=> Sema: disallow indexing non-tuple struct

src/arch/sparc64/CodeGen.zig, src/arch/sparc64/Emit.zig, src/arch/sparc64/Mir.zig, src/arch/sparc64/bits.zig, test/behavior/array.zig, test/behavior/bugs/12051.zig, test/behavior/bugs/12450.zig, test/behavior/comptime_memory.zig, test/behavior/packed-struct.zig, test/behavior/ptrcast.zig, test/behavior/tuple.zig, test/behavior/union.zig, test/behavior/var_args.zig, test/behavior/vector.zig
Wasn't able to do much this time since life's getting somewhat busier, but at least this gets the sparc64 selfhosted backend to not panic when building the behavior testsuite (though there's still a lot of TODO items to work on before it can fully build the suite).
Also, skipped more of the tests where we still does not have support for it yet.
=> stage2: sparc64: Yet another patchset for the selfhosted backend

CMakeLists.txt, build.zig
See https://github.com/ziglang/zig/issues/14240#issuecomment-1374642063
=> cmake: install zig to 'build_dir/stage3' during building

lib/std/net/test.zig
This PR adds a random generated prefix to the unix socket_path to guard against multiple tests/threads running the same test at the same time which should resolve issues like: 
https://github.com/ziglang/zig/actions/runs/4853495431/jobs/8651092179?pr=15428
=> Use random prefix for filename used by net/test.zig

lib/std/Build/Step/Run.zig
=> fix 'zig build test' crashing with no tests

lib/std/Build/Step/ConfigHeader.zig
=> std.Build: support #cmakedefine01 pattern

lib/std/Build/Cache.zig
When checking a cache entry with no input files for a hit, if `createFile` returned `error.WouldBlock` we would forget about the fact that the file has been created, and all future checks will assume that a cache hit has happened, even though one never has or does, leading to rare `FileNotFound` errors trying the access the protected files.
This fix works by writing an extra byte to the manifest file to distinguish hits and misses when there no input files to write.
This should fix various random CI failures such as the following:
```
zig build-exe address_space_pointer_access_chaining_pointer_to_optional_array Debug x86_64-macos: error: error: unable to open 'zig-local-cache/o/6e72b1ff281ef8a28f01e40136aacf4a': FileNotFound
zig build-exe …
```
=> Cache: fix race condition

src/Liveness.zig
`branch_deaths` was a relic from before I had a full understanding of AIR's control flow structure, and so was unnecessary. This change simplifies Liveness, fixes a bug exposed by #15235, and likely improves performance (due to cloning hashmaps less often).
=> Liveness: simplify logic

src/Package.zig
=> add application/tar+gzip unblocking sr.ht packages

lib/std/fmt.zig
Closes #15132, may need extra work but will amend any changes which are reviewed.
=> std: expose fmt methods and structs for parsing

src/Package.zig
Allows the package manager to download gitlab tarballs from urls such as `https://gitlab.com/<namespace>/<project>/-/archive/<sha>/<project>-<sha>.tar.gz`
Such http requests have headers `Content-Type=application/octet-stream` and `Content-Disposition='attachment; filename="<project>-<sha>.tar.gz"'`. The package manager doesn't yet support these headers. This patch doesn't attempt to properly parse the content-disposition header. Instead it does a minimal check for the presence of the strings 'attachment' and '.tar.gz'.
I've left the Content-Disposition header parsing to a follow up PR as I'm not sure where it should go.
=> Package: support gitlab tarball urls

src/codegen/spirv.zig, test/behavior/cast.zig, test/behavior/enum.zig, test/behavior/error.zig, test/behavior/maximum_minimum.zig, test/behavior/slice.zig, test/behavior/union.zig
not much. just `%1` more tests passing (`%32` -> `%33`). cc @Snektron
=> spirv: get more behavior tests passing

doc/docgen.zig
Work towards #2101. Starting with something not user-facing to not break everyone's builds. Well, not yet :smile:
=> docgen: Rename enum values to snake case

src/Sema.zig, test/cases/compile_errors/call_optional_function.zig
Current error message at such situation is uninformative. I added an note message with extra information.
=> Improve error message when trying to call optional

lib/std/crypto/poly1305.zig
These operations are constant-time on most, if not all currently supported architectures. However, even if they are not, this is not a big deal in the case on Poly1305, as the key is added at the end.
The final addition remains protected.
SalsaPoly and ChaChaPoly do encrypt-then-mac, so side channels would not leak anything about the plaintext anyway.
Apple Silicon (M1)
```
Before: 2048 MiB/s
After : 2823 MiB/s
```
AMD Ryzen 7
```
Before: 3165 MiB/s
After : 4774 MiB/s
```
=> Make Poly1305 faster by leveraging @addWithOverflow/@subWithOverflow

lib/std/builtin.zig, lib/std/crypto/aes/soft.zig, src/Sema.zig, src/codegen/llvm.zig, test/cases/safety/noreturn returned.zig
=> add runtime safety for noreturn function returning

src/Package.zig
Improves detection of "filename" / "filename*" parameter in the content-disposition header for package downloads.
* Checks parameter names case insensitive per the spec.
* Allows for multiple other parameters in the disposition header
* Supports the filename*=UTF-8'' parameter.
cc: @travisstaloch @LordMZTE
=> Improve content-disposition filename detection

lib/std/Build/Cache.zig, lib/std/Build/Step/InstallDir.zig, lib/std/crypto/Certificate/Bundle.zig, lib/std/event/loop.zig, lib/std/fmt.zig, lib/std/fs.zig, lib/std/fs/file.zig, lib/std/fs/test.zig, src/Module.zig, src/Package.zig, src/main.zig, test/src/Cases.zig, tools/process_headers.zig, tools/update-linux-headers.zig, tools/update_glibc.zig, tools/update_spirv_features.zig
=> std: Snake-case some public facing enums

lib/std/crypto/poly1305.zig
=> poly1305: properly cast the mask from u1 to u64

src/Sema.zig, test/behavior/maximum_minimum.zig
=> Sema: return comptime_int if all args to @min/@max are comptime_int

lib/std/c/darwin.zig, lib/std/c/freebsd.zig
=> std.os: fix uname usage.

lib/std/child_process.zig, lib/std/os/windows.zig, lib/std/os/windows/ntdll.zig, lib/std/os/windows/test.zig, src/arch/x86_64/CodeGen.zig, test/behavior/maximum_minimum.zig
Unblocks https://github.com/ziglang/zig/pull/15768
Closes https://github.com/ziglang/zig/issues/15904
=> x86_64: hotfix for crash during in-memory coercion of large type

src/AstGen.zig, test/behavior/defer.zig
=> AstGen: handle ref_table for errdefer captures

lib/std/io/reader.zig
Resolves https://github.com/ziglang/zig/issues/15528
=> std.io.reader.Reader: add `streamUntilDelimiter`

lib/libc/include/any-macos-any/netinet/in_systm.h, lib/libc/include/any-macos-any/netinet/ip.h, lib/libc/include/any-macos-any/netinet/udp.h, lib/libc/include/any-macos-any/sys/paths.h, lib/libc/include/any-macos-any/zconf.h, lib/libc/include/any-macos-any/zlib.h
=> macos+libc: add zlib.h,sys/paths.h,netinet/{ip.h,udp.h}

lib/docs/main.js
A temporary fix to #15856, waiting for better handling of calls in Autodoc
=> autodoc: Fix rendering of some values in main.js

lib/std/hash_map.zig
To avoid leaking slots, `fetchRemove` must increment `available` (when the "fetch" succeeds).
Without the `available += 1`, the added test `"std.hash_map repeat fetchRemove"` fails with
run test std-x86-linux-none-Debug: error: thread 432734 panic: integer overflow
.../zig/lib/std/hash_map.zig:1365:28: 0x6471d5 in getOrPutAssumeCapacityAdapted__anon_47495 (test)
self.available -= 1;
^
.../zig/lib/std/hash_map.zig:1308:62: 0x616950 in getOrPutAssumeCapacityContext (test)
const result = self.getOrPutAssumeCapacityAdapted(key, ctx);
^
Alternatively, `fetchRemove` could call `removeByIndex`, though that would entail calling `header()` twice instead of once.
=> std.hash_map: fetchRemove increment available

src/Sema.zig, test/cases/compile_errors/inttoptr_non_ptr_type.zig
=> Sema: emit error on @intToPtr with slice dest type

src/Sema.zig, test/behavior/vector.zig
=> Sema: resolve peer vector types before comparison

lib/std/os.zig
=> os.connect: mark ECONNABORTED as unreachable

lib/std/rand.zig, lib/std/rand/ziggurat.zig
=> publicize std.rand.ziggurat

src/Sema.zig, test/behavior/slice.zig
While adding a test for this, I noticed some other tests in the file which were accidentally not being run, and enabling those uncovered another bug, fixed by the second commit.
=> Fix comptime mutation of slice len

src/TypedValue.zig, src/codegen/c.zig
=> cbe: add missing cast for `@intToPtr` values

lib/std/mem.zig
=> std.mem: expose readPackedIntLittle and readPackedIntBig

lib/std/hash/wyhash.zig
Closes #16070.
---
Performance has no change and SMHasher sanity checks continue to pass.
=> wyhash: support comptime usage

src/Module.zig, test/behavior/asm.zig
=> Module: add support for multiple global asm blocks per decl

src/Sema.zig
=> Sema: fix type in a `@floatToInt` safety check

src/link/Wasm.zig
Unblocks #15285
Unblocks #16096
Unblocks #16098
=> wasm: fix decl alignment

src/codegen/c.zig
Can't repro, but definitely crashed a CI run.
=> cbe: key lifetime?

lib/std/priority_dequeue.zig
This makes it so `first_child_index` will not be accessed when it is equal to `self.len`. (i.e. `self.items[self.len]` will not happen) The access itself was "safe" (as in, `self.len < self.items.len`) because we were only calling `doSiftDown` in the case where there was a stale value at `self.items[self.len]`. However, it is still technically a bug, and can manifest by an unnecessary comparison of a value to a copy of itself.
=> [priority_dequeue] Fix out-of-bounds access

src/value.zig, test/behavior/comptime_memory.zig
=> Value: handle more legacy tags when writing extern struct to memory

lib/std/zig/system/NativeTargetInfo.zig
- supply ".0" as .Z component and satisfy semver X.Y.Z requirement
- previously only X.Y was supplied and semver parse failed
Thanks [bilaliscarioth](https://github.com/bilaliscarioth) for originally opening #16133 and testing out this fix.
=> openbsd: fix NativeTargetInfo semver

src/codegen/llvm.zig
DeclGen/FuncGen methods are for things that pertain to a particular declaration or function, while Object methods are for things that pertain to the entire LLVM Module. Many methods were in the wrong category, such as type and value lowering.
This is a prerequisite commit for a local branch I am working on, which needs to be able to call lowerValue() without the context of any particular function or declaration.
=> LLVM: move many DeclGen methods to Object

lib/std/pdb.zig, src/Module.zig, src/Sema.zig, test/behavior/struct.zig, test/behavior/union.zig
=> Sema: copy pointer alignment to union field pointers

lib/std/Build/Step/ConfigHeader.zig
=> std.Build: omit newline from last line

lib/std/c/tokenizer.zig, lib/std/comptime_string_map.zig, lib/std/enums.zig, lib/std/sort.zig, lib/std/sort/block.zig, src/arch/x86_64/Encoding.zig
=> std.sort.block: add safety check for lessThan return value

src/Sema.zig
All of this code is expected to get rewritten anyway.
Closes #16216
=> Sema: use tmp_hack_arena as a temporary solution for lifetime issues

lib/std/crypto/Certificate/Bundle.zig
- add support for freebsd, netbsd, dragonfly
- refactor rescanOpenBSD -> rescanBSD
- make os-specific rescan*() non-public
closes #16279
---
- tested on freebsd 13.2, openbsd 7.3, netbsd 9.3, dragonfly 6.4
=> tls certificates: support more BSDs

lib/std/heap/general_purpose_allocator.zig
=> std: fix doc comment of GPA deinit

test/behavior/bitcast.zig
This seems to have resolved itself now.
Tested on x86_64 using debug optimize mode.
Closes #9851
=> behavior: test @bitCast of packed struct of bools

lib/std/Build/Step/Run.zig
Adds two functions to `Step.Run`:
* `addPrefixedFileSourceArg(self: *Run, prefix: []const u8, file_source: FileSource)`
* `addPrefixedDirectorySourceArg(self: *Run, prefix: []const u8, dir_source: FileSource)`
A few examples where this is useful:
```
run.addPrefixedDirectorySourceArg("-L", dir_source);
```
```
run.addPrefixedDirectorySourceArg("-B", exe_step.getOutputDirectorySource());
```
```
run.addPrefixedDirectorySourceArg("-I", dir_source);
```
=> std: add prefixed versions of addFileSource and addDirectorySource to Step.Run

lib/std/crypto/tls/Client.zig
Support rsa_pss_rsae_sha384 and rsa_pss_rsae_sha512 in certificate verification.
This fixes tls connection to https://www.iana.org/domains/reserved for example.
Without this change, tls connection to such domains return error.TlsBadSignatureScheme.
=> std.crypto.tls.Client.zig: support rsa_pss_rsae_sha384 and rsa_pss_rsae_sha512

lib/std/math.zig, test/cases/compile_errors/unhandled_enum_value_in_switch_with_enum_declared_in_other_file.zig
This [speeds up algorithms like binary search](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AAvPMFJL6yAngGVG6AMKpaAVxYMQAJmkOAMngMmABy7gBGmMQgkgDspAAOqAqEtgzObh7e0onJNgIBQaEsEVGxFphWeQxCBEzEBOnunj7llak1dQQFIeGR0XEKtfWNmS2Dnd1FJf0AlBaorsTI7BxoDIMA1IPoGwCkAMwAIhsAAngsifUQu15e2zdeMwcAQrsaAIJrmyxMBAh7Ry2BHQADofn8Xm9PgJvpgWADjtswXDIR8vgQNkwFEp6gigaCsGFXMAQVicQRUe8ofFXGENuiNgB5YhYYh4xjuCCuR57GKvD4bQUbYAEUhQoUbWii8VCzAARzFHxlgppdKoDA2gQAbpECBBLFQQEyWZEZsbWbz%2Be8JRLiJgCIsNQoAO6EZD/fUVKhm3Z85U2iUgqUIg7YDYgkWK60Bm0g%2BUh/ZhuMK/0x8MihNJqVRtO%2Bw6UiV5qFF/ZWqEAekrGwA4ngdRqCM7UBsGL1iApSBs/ngFBsqK4GNZUhs7Q7iOsuwhMBsSBa/pgAJ6Yu0bV1/EeYBTxTDWLvNzBMd0z%2BfEEHU2l9jWzyIQJhGwwLggL7edsL3hiP5%2BYM3Mi2%2Bq0SngVAbLeCbHGEPp%2BgKMajo …
=> Change math.Order order

lib/std/Build/Step/Run.zig
Closes #16051. I hope this is the correct integration with the cache system.
=> Changed Step.Run's stdin to accept FileSource

lib/std/Build/Step/TranslateC.zig
I wasn't sure whether to expose the dependencies as a parameter, or create an `AddModuleOptions` struct parameter. I went with the former since if I made such a struct it would only contain the dependencies as a member anyway, and I'm not sure what the likelihood is that the struct would ever contain more than that.
Lines 85-88 in `createModule` essentially inlines `moduleDependenciesToArrayHashMap`, which is used in the `createModule` implementation in Build.zig, but is private so I could not reuse it. So a bit of code duplication there. But, I wasn't sure if there was a common place to move that to, and it is a fairly simple function so didn't feel too wrong.
=> std.Build: Add methods for creating modules from a TranslateC object.

src/AstGen.zig, src/Sema.zig, test/cases/compile_errors/union_init_with_non_type_as_first_param.zig
=> Fixes wrong error location for unionInit when first parameter is not a type

lib/std/linked_list.zig
add a function to invert a singly linked list.
=> feat(list_invert): SinglyLinkedList inversion.

lib/docs/index.html, lib/docs/main.js, lib/docs/ziglexer.js
I'm not sure the solution of passing additional parameter to `renderTokens` and `renderSingleToken` is the best thing we could do
=> autodoc: More exprName to ex refactoring

lib/docs/index.html, lib/docs/main.js, lib/docs/ziglexer.js, src/Autodoc.zig
This PR wires in the new tokenizer everywhere and deletes all the old ad-hoc pseudo-syntax rendering code.
=> Autodoc tokenizer

lib/std/crypto/sha1.zig
=> std.crypto: add finalResult and peek api for Sha1

src/codegen/c.zig, test/src/Cases.zig
fix a bug where an invalid empty enum would be emitted into the C source file if the global error set was empty.
=> cbe: fix bug where empty enum would be generated

lib/std/os/uefi/protocols/device_path_protocol.zig, lib/std/os/uefi/protocols/hii.zig, lib/std/os/uefi/protocols/managed_network_protocol.zig, lib/std/os/uefi/protocols/udp6_protocol.zig
follow up on #16403, sorry i missed these before!
=> more UEFI fixes

src/Sema.zig, src/type.zig, src/value.zig
Partially addresses #16494. There is still at least one more issue left when compiling bun with master branch.
=> fix recent compiler regressions found when compiling bun

.github/CODEOWNERS
Notify me to review `std.Thread` changes.
=> Update CODEOWNERS for std.Thread

src/Compilation.zig
6e4fff6ba62ae3e61a948c98fa8fea7e35732cc0 regressed the direct CLI interface of -femit-docs.
This commit fixes it and also hooks up to the progress bar.
=> Compilation: fix autodocs CLI

src/InternPool.zig, test/behavior/generics.zig
=> InternPool: fix handling of coerced function bodies

lib/std/priority_queue.zig
- Adds the overflow guard from https://github.com/ziglang/zig/pull/16127 to std.PriorityQueue.
- Simplified logic so that the algorithms only write the sifted item into heap memory once rather than log(`self.len`) times.
- Removes the copying of every item into the siftDown function's stack. This helps avoid a 2-3x slowdown (in my tests, obviously), particularly with complex structs. For the record I tried my tests with a variety of structs, integers, and with different amounts of code executed prior (to vary layout). I found that copying values to the stack can be marginally beneficial in some cases, but can lead to halving performance in other cases. I haven't looked at the assembly but I would guess it has to do with how many instructions are necessary to copy a value to the stack …
=> [priority_queue] Simplify sifting & fix edge case

lib/std/io/reader.zig
these changes address #16416 
Closes #16416 
- added typecast (that is guaranteed to be safe)
- added behavior test bug 16416 to test suite, all tests pass
Think i might actually be one of the only people who use this api but this should fix it now :')
=> Fix type mismatch in Reader.readIntoBoundedBytes (#16416)

src/link.zig
Removed Package import as it's not used in file
=> src.link | Remove unused import

src/main.zig, test/tests.zig
=> zig fmt: make `--exclude` work on files

lib/std/os/linux.zig
=> std.os.linux | Fix sendmmsg function | Issue #16513

lib/std/builtin.zig, lib/std/meta.zig, lib/std/testing.zig, src/Sema.zig, src/codegen/llvm/Builder.zig, src/translate_c.zig, test/behavior.zig, test/behavior/eval.zig, test/behavior/type_info.zig, test/behavior/type_info_only_pub_decls.zig
fixes #10731
Thanks @nektro for previous work in #14878
=> make `@typeInfo` not return private decls

lib/std/Progress.zig, src/Package.zig, src/main.zig
This is a fairly basic implementation, but it works quite nicely: I think it's definitely a UX improvement. I expect later improvements to this to be tied to improvements to `std.Progress`, so that we can show download rate, fractional filesizes, etc.
This PR adds a tiny new API to `std.Progress` to display a unit alongside the "amount completed".
Demo: https://asciinema.org/a/2ynN35dPpEaEqXbQIJXcoPjDy
Closes #16463
=> Display package download progress

src/AstGen.zig, src/Sema.zig, src/codegen/llvm/Builder.zig, test/behavior/tuple_declarations.zig, test/cases/compile_errors/reify_struct.zig
This feature wasn't really intended to be supported.
closes #16541
=> forbid packed and extern tuples

src/link/MachO/Dylib.zig, src/link/tapi/yaml.zig, test/link.zig, test/link/macho/tbdv3/a.c, test/link/macho/tbdv3/build.zig, test/link/macho/tbdv3/main.c
=> macho: fix parsing of TBDv3 dylib stubs

src/codegen/llvm.zig, test/llvm_targets.zig
=> llvm: fix data layout on ios

lib/std/dwarf.zig, lib/std/dwarf/call_frame.zig, lib/std/dwarf/expressions.zig
Initial numbers (`zig-before-worktree` is the commit before the merge of https://github.com/ziglang/zig/pull/15823):
```
Benchmark 1: zig build-exe hello.zig -fno-LLVM -fno-LLD --zig-lib-dir c:\cygwin64\home\kcbanner\kit\zig-before-worktree\lib -target x86_64-linux-gnu
Time (mean ± σ):     215.4 ms ±   7.6 ms    [User: 171.6 ms, System: 147.2 ms]
Range (min … max):   210.1 ms … 232.6 ms    13 runs
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
Benchmark 2: zig build-exe hello.zig -fno-LLVM -fno-LLD --zig-lib-dir c:\cygwin64\home\kcbanner\kit\zig\lib -target x86_64-linux-gnu
Time (mean ± σ):     440.2 ms ±   5.2 ms    [User: 465.3 ms, …
```
=> Reducing compile time regression introduced by the new DWARF unwinder

src/AstGen.zig, test/behavior/for.zig
=> AstGen: fix missing deferred ref

lib/std/coff.zig
Fixes illegal behavior. Invalid-length sections are now skipped in `Coff.getSectionByName`.
Works around #15238 breaking stack traces on Windows. In particular, this occured in `std.debug.readCoffDebugInfo` when looking for a DWARF debug info section named `".debug_info"`.
=> `std.coff`: check strtab lengths against `data` length

lib/std/zig/system/darwin.zig
=> macos: fix parsing of SDK version string into std.SemanticVersion

src/Sema.zig, src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, src/codegen/llvm/bindings.zig, test/behavior/tuple.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig, test/tests.zig
Closes #16242
Closes #16038
Closes #16288
=> Fix various C ABI issues

test/behavior.zig, test/behavior/packed-union.zig
=> behavior: add coverage for no longer reproducing issue

src/Air.zig, src/codegen/llvm.zig, test/behavior/asm.zig
=> llvm: support read-write output constraints in assembly

test/behavior/vector.zig
=> add behavior test for vector bitcast at comptime

src/codegen.zig
Fixes #16586 
The old code was iterating and generating symbols for fields in their declared order while getting offsets that might be in a different memory optimized order. This PR fixes this by iterating through fields and generating their symbols in the correct order.
=> self hosted: fix integer overflow in struct field padding calculation

build.zig, lib/std/target.zig, src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, src/codegen/llvm/bindings.zig, test/cases.zig, test/llvm_targets.zig, test/tests.zig
=> llvm: fix data layout calculation for experimental llvm targets

doc/langref.html.in, lib/std/fs.zig, lib/std/heap.zig, lib/std/heap/sbrk_allocator.zig, lib/std/os/plan9.zig, lib/std/os/plan9/errno.zig, lib/std/start.zig, src/arch/x86_64/Emit.zig, src/link/Plan9.zig
=> Plan 9: more standard library support

lib/std/hash/wyhash.zig
Update calls with input longer then one block must ensure that last sixteen bytes are available when final is called.
Fixes #16695
=> wyhash: keep tail bytes on iterative update

src/codegen/c.zig
=> cbe: don't emit traps in naked functions

lib/std/os/linux.zig
=> linux: add setsid

build.zig
When linking system llvm/clang/lld, add system libc++ to the searchlist. This is needed for certain distros (eg. chimera linux).
closes #16754
- tested on chimera-linux
- tested on archlinux
=> linux: search for system libc++

src/Sema.zig, test/behavior/array.zig, test/behavior/struct.zig, tools/lldb_pretty_printers.py
=> Sema: avoid deleting runtime side-effects in comptime initializers

src/Autodoc.zig
=> Autodoc: remove assumption that slice's lhs is always a declRef

lib/std/dwarf/abi.zig
=> std: fix compilation errors in dwarf/abi.zig when targeting iOS

lib/std/json/dynamic.zig, lib/std/json/dynamic_test.zig
Closes #16861
Using `alloc_if_needed` when parsing a `Value` allows receiving a token which points to the buffer of the underlying `Reader`. This token will no longer be valid after the `Reader`'s buffer is refilled, which will happen with large values. Using `alloc_always` avoids this issue by ensuring the returned tokens always own their data independently of the underlying buffer.
=> std.json: avoid stale pointers when parsing Value

src/Sema.zig, test/cases/compile_errors/ptr_coerced_to_slice.zig
=> Sema: disallow C pointer to slice coercion

lib/std/Build/Step.zig, lib/std/Build/Step/Run.zig, lib/std/zig/Server.zig, lib/test_runner.zig
=> Build: fail tests that log errors, like `zig test` does

src/AstGen.zig, src/Sema.zig, src/Zir.zig, src/print_zir.zig, test/behavior/memset.zig
=> compiler: provide result type for @memset value

src/codegen/c.zig, src/codegen/llvm.zig, test/behavior/prefetch.zig
=> llvm/cbe: support slice in `@prefetch`

lib/std/base64.zig
Fixes #16291
Improves performance by about 2x, which is better than the "plain" codec of libbase64.
```console
> poop ./repro-libbase64 ./repro-libbase64-plain ./repro-zig-std-old ./repro-zig-std-new
Benchmark 1 (376 runs): ./repro-libbase64
wall_time          13.1ms ± 2.30ms    10.2ms … 23.3ms          7 ( 2%)        0%
peak_rss           47.9MB ± 56.8KB    47.8MB … 48.0MB          0 ( 0%)        0%
cpu_cycles         36.7M  ± 5.21M     31.0M  … 62.2M           9 ( 2%)        0%
instructions       67.6M  ± 6.05      67.6M  … 67.6M          16 ( 4%)        0%
cache_references    588K  ± 8.96K      569K  …  647K           9 ( 2%)        0%
cache_misses        229K  ± 32.0K      183K  …  318K           0 ( …
```
=> Optimize std.base64.standard.Encoder.encode

src/Module.zig, src/Sema.zig, src/value.zig, test/behavior/cast.zig, test/behavior/undefined.zig
=> Sema: error when converting `undefined` int to float

lib/std/array_hash_map.zig
My use case is here: https://github.com/andrewrk/groovebasin/blob/c51ddbaec756f1dd1e689b32f53c586e5b99b075/src/server/db.zig#L88-L130
I'm assigning values to all of the keys and values in an ArrayHashMap, but not the computed+stored hashes. Calling `reIndex()` seems like it should recompute all the denormalized metadata to make this work, but it currently does not. It only rebuilds the `index_header`.
This PR updates `reIndex()` to also compute and store the hashes before rebuilding the `index_header`.
=> std.ArrayHashMap.reIndex also recomputes hashes

lib/docs/main.js, src/Autodoc.zig
Also add `^` (xor) binop and change float rendering to show float `1` as `1.0`
=> autodoc: Implement `@call`, `@unionInit`, `@mulAdd` support

lib/std/fs.zig
=> remove outdated error message in std.fs

lib/std/math/asinh.zig
=> std.math.asinh: fixed -0.0 evaluating to 0.0

src/Module.zig, src/Sema.zig
Here is a small diff of an idea to modify how capture scopes work in semantic analysis, which does these things:
* Uses 32-bit integers instead of pointers for compactness and serialization friendliness.
* Uses a separate hash map for runtime and comptime capture scopes, avoiding the 1-bit union tag.
* Uses a compact array representation instead of a tree of hash maps.
* Eliminates the only instance of ref-counting in the compiler, instead relying on garbage collection (not implemented yet but is the plan for almost all long-lived objects related to incremental compilation).
Because a code modification may need to access capture scope data, this makes capture scope data long-lived state. My goal is to get incremental compilation state serialization down to a single pwritev syscall, by …
=> compiler: rework capture scopes in-memory layout

lib/docs/main.js, src/Autodoc.zig
Implement unary ops handling.
Fix getType in main.js
Minor cleanup of builtin function handling.
=> autodoc: Implement builtin function rendering.

.github/workflows/ci.yaml, ci/aarch64-macos-debug.sh, ci/aarch64-macos-release.sh, ci/x86_64-macos-release.sh
Updates from LLVM release/17.x to 17.0.1
=> CI: update macos tarballs

src/Sema.zig
Closes #17231 
No idea what I'm doing here, but this seems to reveal even more memory leaks (see #17232).
=> sema: fix mem leaks in inferred error set handling

src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/Object.zig, src/link/Elf/Symbol.zig, src/link/Elf/ZigModule.zig, src/link/Elf/file.zig
=> elf: misc improvements, plus let's actually link against a parsed archive!

README.md
Could you update the wiki page(s) as well? Thanks.
EDIT: I updated the wiki (didn't know this was allowed for anyone to do...).
=> Update LLVM version in README from 16.x to 17.x

src/Compilation.zig, src/main.zig
This commit introduces `--debug-incremental` so that we can start playing around with incremental compilation while it is still being developed, and before it is enabled by default.
Currently it saves InternPool data, and has TODO comments for the remaining things. Deserialization is not implemented yet, which will require some post-processing such as to build a string map out of null-terminated string table bytes.
The saved compiler state is stored in a file called <root-name>.zcs alongside <root-name>.o, <root-name>.pdb, <root-name>.exe, etc. In case of using the zig build system, these files are all in a zig-cache directory.
For the self-hosted compiler, here is one data point on the performance penalty of saving this data:
```
Benchmark 1 (3 runs): zig build-exe ...
measurement …
```
=> Compilation: introduce saveState()

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
=> std.math.big.int.Const.order 0 == -0

lib/std/Build/Step/Run.zig
=> Step.Run: remove unnecessary assert

lib/std/Build/Step/InstallDir.zig
Resolves https://github.com/ziglang/zig/issues/16687
=> Add include_extensions to InstallDir Options

lib/std/array_list.zig
Continuation of [17312](https://github.com/ziglang/zig/pull/17312).
(Unmanaged)ArrayList.insert has the same inefficiency as the old insertSlice. With the new addManyAt, the solution is trivial. 
I also improved the test "growing memory preserves contents". In the previous implementation, if any changes were made to the ArrayList memory growth policy (function growMemory), the list could end up with enough capacity to not trigger a memory growth, defeating the purpose of the test. The new implementation more robustly triggers a memory growth.
=> Improve (Unmanaged)ArrayList.insert

lib/std/Build/Step/Compile.zig
Adds `std.Build.Step.Compile.addAfterIncludePath` in order to make it possible for `build.zig` scripts to add include paths using `-idirafter`.
Motivation: porting C project build scripts to the Zig build system. Include paths added using `-idirafter` are looked up last, after `-I` and `-isystem`, so `-idirafter` is sometimes used to provide a vendored fallback when system headers are preferred but can't be found.
=> std.Build: expose `-idirafter` to the build system

src/codegen/llvm.zig
=> llvm: remove extra copy of wrapped payloads

src/arch/wasm/CodeGen.zig, test/behavior/enum.zig
=> wasm - fix `@tagName` prong value serialization

lib/std/Build/Step/Run.zig, test/tests.zig
=> Step.Run: change `cwd` to `?Build.LazyPath`

src/Sema.zig, src/type.zig
The following pairs of functions have been combined using the "advanced" pattern used for other type queries:
* `Sema.fnHasRuntimeBits`, `Type.isFnOrHasRuntimeBits`
* `Sema.typeRequiresComptime`, `Type.comptimeOnly`
=> Sema,type: unify type query functions

lib/std/priority_dequeue.zig, lib/std/priority_queue.zig
=> Update docs of PriorityQueue.iterator() and PriorityDeque.iterator()

lib/std/http/protocol.zig, lib/std/mem.zig, lib/std/simd.zig, lib/std/unicode.zig, src/Sema.zig
=> Fix `@Vector` source locations being swapped

lib/std/heap/arena_allocator.zig
=> std.heap.ArenaAllocator: fix doc comment typo

lib/std/Build/Step/ConfigHeader.zig
* include path was using bad default for dependency lazy paths
* unhashed config options caused changes to not trigger a rebuild
=> Build: fix some issues with ConfigHeader step

lib/std/fs/test.zig, lib/std/os/windows.zig
=> std.fs: fix relative symbolic links on Windows

lib/std/compress/deflate/decompressor.zig
=> added reset value to decompressor

src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Encoding.zig, src/arch/x86_64/bits.zig, src/arch/x86_64/encoder.zig, test/tests.zig
* inline asm C++-style comments
* inline asm indirect call operands
* fix misleading immediate debug formatting
Closes #15328
=> x86_64: pass universal-libc tests

test/link/elf.zig
=> elf: fix flaky link tests

src/codegen/llvm/Builder.zig
=> Builder: fix incorrect type for 32-bit systems

lib/docs/main.js
=> autodoc: Display type kinds for containers

src/codegen/spirv.zig, src/codegen/spirv/Assembler.zig, src/codegen/spirv/Cache.zig, src/codegen/spirv/Module.zig, test/behavior/bugs/12000.zig, test/behavior/bugs/1735.zig, test/behavior/bugs/1914.zig, test/behavior/bugs/2006.zig, test/behavior/bugs/3007.zig, test/behavior/bugs/6947.zig, test/behavior/bugs/7325.zig, test/behavior/error.zig, test/behavior/eval.zig, test/behavior/generics.zig, test/behavior/null.zig, test/behavior/optional.zig, test/behavior/ptrcast.zig, test/behavior/struct.zig, test/behavior/struct_contains_null_ptr_itself.zig, test/behavior/struct_contains_slice_of_itself.zig, test/behavior/union.zig
This reverts commit 9f0359d78f9facc38418e32b0e8c1bf6f99f0d26 in an attempt to make the tests pass again. The CI failure from that merge should be unrelated to this commit.
=> spirv: recursive ptrs (2)

src/link/Elf.zig
Prior to this change, we would trip up when building natively on pretty much any Linux distro that's not NixOS with an error that would look something like this:
```
error: unexpected error: parsing object failed with error FileNotFound
note: while parsing /usr/lib/x86_64-linux-gnu/libutil.so
```
and a similar error for `pthread`, `m` and a couple more. The libraries indeed do not exist in the system lib dir under the searched name but rather with a number suffix (well, mostly, some I think might not even exist as a dynamic lib at all but I am getting ahead of myself). This baffled me as the standalone `zld` linker doesn't do any checks for dynamic libs with number suffixes in the name, and it works fine as a drop-in replacement on the affected OS, say, a Ubuntu. So what the heck is going …
=> elf: fix linking against system libc libs

lib/std/target.zig
- freebsd, openbsd, macos, ios, watchos, tvos
=> std.target: bump some OS max versions

doc/langref.html.in
somehow the concept of slices had less elaboration in its own dedicated section than in passing mentions of it elsewhere.
=> Doc: elaborate on Slice section

src/Sema.zig, test/behavior/switch.zig
=> Sema: do not assume switch item indices align with union field indices

src/print_zir.zig
=> print_zir: fix crash in writeRestoreErrRetIndex

lib/std/os/linux/io_uring.zig
Server networking application typically accept multiple connections. Multishot accept simplifies handling these situations. Applications submits once and receives CQE whenever a new connection request comes in.
Multishot is active until it is canceled or experience error. While active, and further notification are expected CQE completion will have IORING_CQE_F_MORE set in the flags. If this flag isn't set, the application must re-arm this request by submitting a new one.
Reference: [io_uring and networking in 2023](https://github.com/axboe/liburing/wiki/io_uring-and-networking-in-2023#multi-shot)
=> io_uring: add multishot accept operation

src/Sema.zig, test/cases/compile_errors/invalid_extern_function_call.zig
Closes https://github.com/ziglang/zig/issues/17893
=> Sema: emit error when pointer to extern function is called

src/InternPool.zig, src/arch/x86_64/CodeGen.zig, test/behavior/union.zig
=> x86_64: fix passing register-sized payload as non-reigster-sized union

src/Sema.zig, test/cases/compile_errors/array_init_not_supported_on_result_type.zig
=> Sema: fix source location for untyped array init with result type

src/link/MachO.zig, src/link/MachO/dead_strip.zig, test/link.zig, test/link/elf.zig, test/link/link.zig, test/link/macho.zig
=> macho: handle special section/segment boundary symbols

lib/compiler_rt.zig, lib/compiler_rt/ssp.zig, src/Compilation.zig, src/link/Coff/lld.zig, src/link/Elf.zig, src/target.zig, stage1/config.zig.in
Extracted from #17892.
Closes #7265.
=> move libssp into libcompiler_rt

src/Module.zig, src/Sema.zig, src/codegen/llvm/BitcodeReader.zig
```
$ ./zig build test-cases --summary all
Build Summary: 2188/2239 steps succeeded; 51 skipped
test-cases success
<...>
```
=> x86_64: pass `test-cases` with an x86_64 backend compiled compiler

src/codegen/llvm.zig, test/behavior/union.zig
=> llvm: workaround SROA misoptimizations in LLVM

src/Package/Fetch/git.zig
Addresses a comment in #17779 pointing out the inability to fetch the upstream BoringSSL sources over Git. The reason for this is because the Git server used in this case did not include the optional (but recommended) LF terminator for textual pkt-line data. This commit adjusts handling of textual pkt-line data so that it works both with and without the optional trailing LF.
---
Demonstration of now working functionality:
```
⬢[ian@toolbox ~]$ zig fetch git+https://boringssl.googlesource.com/boringssl#ad57528d2c978543106f9b115bd0eb658f3ebdd2
1220666ed5daabf399d327dd7202f5527596ee75c400a93d50785b7a5e181a336eef
```
=> Package.Fetch.git: handle optional pkt-line LF

lib/std/Build/Step/Compile.zig
this is the first time i've messed with the build system so apologies if i missed anything
=> expose `--error-limit` to build system

lib/std/math/big/int_test.zig, src/arch/x86_64/CodeGen.zig
=> x86_64: actually track state during `@divFloor` of `i128`

lib/std/meta.zig
The current implementation of meta.IntToEnum uses an inline loop over the fields of EnumTag, as show below:
```zig
pub fn intToEnum(comptime EnumTag: type, tag_int: anytype) IntToEnumError!EnumTag {
// ...omitted...
inline for (enum_info.fields) |f| {
const this_tag_value = @field(EnumTag, f.name);
if (tag_int == @intFromEnum(this_tag_value)) {
return this_tag_value;
}
}
return error.InvalidEnumTag;
}
```
Inlining this loop generates suboptimal code. I wrote an implementation that does without inlining the loop:
```zig
pub fn intToEnum(comptime EnumTag: type, tag_int: anytype) IntToEnumError!EnumTag {
// ...omitted...
// We don't directly iterate over the fields of EnumTag, as that
// would require an inline loop. Instead, we create an array of
// values that is comptime-known, but can be …
```
=> Faster implementation of intToEnum.

src/value.zig, test/cases/compile_errors/unable_to_evaluate_comptime_expr.zig
Closes https://github.com/ziglang/zig/issues/18038
=> value: update isDeclRef for anonymous declarations

lib/std/debug.zig
```zig
var addr: *u8 = @ptrFromInt(0xaaaaaaaaaaaaaaaa);
addr.* = 1;
}
```
On x86_64-linux:
Before:
```
$ zig run x.zig
Segmentation fault at address 0x0
/home/wooster/Desktop/zig/x.zig:5:5: 0x21d887 in main (x)
addr.* = 1;
^
/home/wooster/Desktop/zig-linux-x86_64/lib/std/start.zig:583:37: 0x21d847 in posixCallMainAndExit (x)
const result = root.main() catch |err| {
^
/home/wooster/Desktop/zig-linux-x86_64/lib/std/start.zig:251:5: 0x21d371 in _start (x)
asm volatile (switch (native_arch) {
^
???:?:?: 0x0 in ??? (???)
Aborted (core dumped)
```
After:
```
$ zig run x.zig --zig-lib-dir lib
General protection exception
/home/wooster/Desktop/zig/x.zig:5:5: 0x21d907 in main (x)
addr.* = 1;
^
/home/wooster/Desktop/zig/lib/std/start.zig:583:37: …
```
=> std.debug: detect general protection faults on x86_64-linux

src/arch/x86_64/Encoding.zig
Remove all comptime sorts, making it compile 3x faster.
=> x86_64: optimize compile time of `mnemonic_to_encodings_map`

src/Sema.zig
=> fix spelling in sema

src/Zir.zig, test/behavior.zig, test/behavior/type_info_mul_linksection_addrspace_decls.zig
=> Zir: add missing extra index for linksection_or_addspace

lib/std/zig/BuiltinFn.zig, src/AstGen.zig
Missing in https://github.com/ziglang/zig/pull/18096
cc: @Vexu
=> add field in BuiltinFn and rewrite check in AstGen

lib/std/Build/Step.zig
=> Use `@memcpy` in `Step.zig`

lib/std/Thread/Futex.zig, lib/std/debug.zig
=> bsd: debitrot atomic and debug

doc/build.zig.zon.md, lib/init/build.zig.zon, lib/std/zig/render.zig, src/Package/Fetch.zig, src/Package/Manifest.zig, src/main.zig
```
--save        Add the fetched package to build.zig.zon
--save=[name] Add the fetched package to build.zig.zon as name
```
=> `zig fetch`: add `--save` flag

src/Package/Fetch.zig
The logic here already caught the case when a dependency path tried to escape out of the zig cache directory using up directories. However, it did not catch the case when the relative path tried to reach into a different path within the zig-cache. For example, if it asked for "../../../blah" then it would be caught, but if it asked for "../blah" then it would try to resolve as "zig-cache/p/blah" and probably result in file-not-found, or perhaps resolve to a different package if someone inadvertently used a valid package hash instead of "blah".
Now it correctly gives a "dependency path outside project" error, however, still allows relative paths with up-dirs that were not fetched via URL.
=> package fetching: catch relative paths that resolve into cache dir

lib/std/debug.zig
Uses mem.indexOfScalar to speed line iteration instead of byte for byte. Also prints the whole line in a single write (or up to a page size at a time)
Also fixes a bug that the last line of a file could not be printed (EOF before a `\n`)
Closes #18099
=> std.debug: optimized printLineFromFileAnyOs

src/Module.zig, src/Sema.zig, test/cases/compile_errors/array_cat_invalid_elem.zig
=> Improve error location for array cat/mul

lib/std/debug.zig, src/Sema.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, test/behavior/bitcast.zig, test/behavior/packed-struct.zig, test/tests.zig
=> test: test with `-fstrip` and fix failures

src/Air.zig, src/Liveness.zig, src/Liveness/Verify.zig, src/Module.zig, src/Sema.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/print_air.zig
I need some indices for a thing...
=> Air: use typesafe `Air.Inst.Index`

lib/std/unicode.zig
=> std: make std.unicode.initComptime() a comptime-known function

lib/std/fmt.zig
previously when T was smaller than 8 bits, it was possible for base to overflow T (because base is a u8).  this patch prevents this by accumulating into a U rather than T which is at least 8 bits wide.
this is the best way i could think of to maintain performance.  this will only affect parsing of integers less than 8 bits by adding one additional cast at return.  additionally, this patch may be slightly slower to return an error for integers less than 8 bits which overflow because it will accumulate a few more digits before the overflow check at return.
* add tests which previously overflowed when they shouldn't have
closes #18157
NOTE: i'll post a perf comparison shortly.
=> fmt.parseWithSign(): prevent edge case overflows

doc/build.zig.zon.md, lib/init/build.zig.zon
Just a couple things I noticed
=> Grammar fixes

test/behavior/vector.zig
=> test: add coverage for index into comptime-known vector is comptime-known

lib/std/fs/test.zig
In theory this is part of https://github.com/ziglang/zig/issues/18335, but these tests already pass since deleteTree does not depend on `OpenDirOptions.no_follow` behavior for these test cases:
- `deleteTree` always tries to delete the initial path as a file first, which will succeed on symlinks because `deleteFile` doesn't follow symlinks
- `deleteTree` when iterating a directory will get the type of symlinks as .sym_link, not as .directory (even if the symlink points to a directory), meaning it will never try to open a symlink as a directory.
The intention here is to test/validate this part of the commit message of https://github.com/ziglang/zig/commit/e0b77a6b77614538d18b9f0b9e3e7e434ccee4ff:
> Ensure Dir.deleteTree does not dereference symlinks
>
> Otherwise, the behaviour can lead to …
=> fs: Add tests for deleteTree not following symlinks

lib/std/fmt.zig
- Clean up array formatting code. Remove buggy formatting of array pointers, deference pointer to reuse existing array formatting logic.
- Change default specifier for array pointers to be "{any}", to be consistent with slices.
- Allow using "{x}" and "{e}" for arrays and slices for all number types, including u8.
Fixes #18185
=> std.fmt: fix formatting of array pointers

lib/std/zig/Ast.zig, lib/std/zig/Parse.zig
Found some things to clean up while [porting `std.zig.Parse` to Rust](https://github.com/FnControlOption/zig-rs)
=> std.zig: Miscellaneous cleanup

lib/std/Build/Cache.zig, lib/std/Build/Step/Run.zig
=> std.Build.Step.Run: fix depfile support

src/Compilation.zig
Closes #18438
@xdBronch would you mind giving this a spin?
=> compiler: fix build runner not added to cache hash

src/codegen/llvm.zig, test/behavior/optional.zig
=> llvm: optional slices cannot be passed in parts when they allowzero

lib/std/math.zig
Add `approxEqAbs`/`approxEqRel` support for `comptime_float`
https://github.com/ziglang/zig/wiki/Contributing#directly-testing-the-standard-library-with-zig-test
```
stage4/bin/zig build test-std -Dskip-release -Dskip-non-native -Dtest-filter="approxEqAbs"
```
```
stage4/bin/zig test lib/std/std.zig --zig-lib-dir lib --main-mod-path lib/std -Dtest-filter="approxEqAbs"
```
=> Add `approxEqAbs` support for `comptime_float`

src/AstGen.zig, src/Autodoc.zig, src/Module.zig, src/Sema.zig, src/Zir.zig, src/print_zir.zig
=> add type safety to ZIR for null terminated strings

lib/std/start.zig, src/arch/aarch64/Emit.zig, src/arch/x86_64/Emit.zig, src/link/Dwarf.zig
=> stage2 AArch64: get empty file compiling again

src/codegen/llvm.zig, test/behavior.zig, test/behavior/extern.zig
=> LLVM: fix lowering of extern anyopaque

lib/std/c.zig, lib/std/os.zig
=> std: make c.versionCheck() a comptime-known function

src/Sema.zig, test/cases/compile_errors/asm_output_to_const.zig
=> sema: forbid asm output to const locals

lib/std/array_list.zig
=> std.ArrayList: Clarify that ensureTotalCapacity/ensureTotalCapacityPrecise will never shrink the array

src/link/Elf/SharedObject.zig
=> add `SHT_NOBITS` check

lib/std/Build/Step/Compile.zig, src/link/Elf.zig, src/link/Elf/Object.zig, src/link/Elf/ZigObject.zig, test/link/elf.zig
=> elf: report duplicate symbol definitions

src/Sema.zig, src/codegen/llvm.zig, test/behavior/extern.zig
=> Sema: fix `@extern` function decls

lib/std/array_list.zig
fixes #18413 
conflicts with #18361
Edit: to reduce the size, it may be prudent to mark functions causing illegal behavior as such, but not vice versa. I am looking for suggestions regarding this.
=> std.array_list: Document and reduce illegal behavior in ArrayLists

lib/std/Build/Step/Options.zig
=> Step.Options: Allow multiple options using the same enum type

lib/std/math/big/int.zig, lib/std/zig/render.zig
=> std: remove deprecated API and old zig fmt fixups

src/Sema.zig, test/behavior/cast.zig
=> return optional state to `zirPtrCastNoDest`

lib/std/array_list.zig
Context: https://github.com/ziglang/zig/issues/18413#issuecomment-1897510042
cc @andrewrk, @notcancername
=> ArrayList: remove unneeded overflow checks

lib/std/array_list.zig
Adds `replaceRangeAssumeCapacity` method. This feels like it's missing based on the other methods that are available in ArrayList.
Also refactor `orderedRemove` to just call out to `replaceRange`. Happy to revert this part if it's not the right vibe.
Are there any patterns for parametrizing tests in zig? Seems like it could help a lot here testing the 4 different types of ArrayLists.
=> Add replaceRangeAssumeCapacity method to ArrayList

lib/std/math/pow.zig
Potential fix for #18553, I hope this is useful! Any input, feedback, or suggestions would be much appreciated!
I have run `zig build test-std -Dskip-release -Dskip-non-native` for testing, but have run no other tests. This has also resolved the aforementioned issue for my personal use case.
=> std/math/pow: Fix #18553, isOddInteger: Return false if input greater than 1 << 53

lib/std/math/complex/abs.zig, lib/std/math/complex/sqrt.zig, lib/std/math/hypot.zig
related: https://github.com/ziglang/zig/pull/17840
=> std.math: make hypot infer type from argument

lib/std/crypto/Certificate/Bundle/macos.zig, lib/std/io.zig, lib/std/io/Reader.zig, src/link/MachO/fat.zig
=> std.io: replace readStructBig with readStructEndian

src/Compilation.zig
Fixes #18594
Posible fixes #18627
=> Fix wrong if condition for windows

lib/build_runner.zig, lib/std/process.zig
=> std.process: return u64 in totalSystemMemory

src/Compilation.zig
Previously, sorting dependencies would reorder the builtin dependency and cause `Package.Module.getBuiltinDependency` to stop working.
=> Compilation: preserve "builtin" as the first dependency

src/Sema.zig, test/cases/compile_errors/missing_field_in_struct_value_expression.zig
Possibly solves #18671, solves #18609
=> Sema: tuples have no names to be used for reporting errors in finishStructInit

src/AstGen.zig, src/Autodoc.zig, src/Compilation.zig, src/InternPool.zig, src/Module.zig, src/Sema.zig, src/Zir.zig, src/main.zig, src/print_zir.zig
See commit messages for details. I will provide performance data points shortly.
=> InternPool: introduce TrackedInst to prepare for incremental compilation

build.zig, src/link/MachO.zig, src/link/MachO/Archive.zig, src/link/MachO/Atom.zig, src/link/MachO/DwarfInfo.zig, src/link/MachO/Dylib.zig, src/link/MachO/InternalObject.zig, src/link/MachO/Object.zig, src/link/MachO/Symbol.zig, src/link/MachO/ZigObject.zig, src/link/MachO/relocatable.zig
Downstream kubkon/zld#105
Fixes #18675
cc @ominitay
=> macho: reduce heap allocations

ci/x86_64-macos-release.sh
Closes https://github.com/ziglang/zig/issues/15197
=> ci: x86_64-macos reproducibility

src/Sema.zig, src/codegen/llvm.zig, src/value.zig, test/behavior/comptime_memory.zig, test/behavior/error.zig, test/behavior/vector.zig
Should unblock #17634 at least on the part of the related issue.
Closes #17354
Closes #17761
Closes #17996
=> Fix some generic{Reader,Writer} related issues

src/Sema.zig, src/type.zig, src/value.zig, test/behavior/packed-struct.zig, test/behavior/packed-union.zig
Continuation of #18246
Closes #18244
Closes #18245
=> Fix some comptime packed struct issues

lib/std/Build/Step/Compile.zig
Closes #18628
This commit splits the arguments obtained from pkg-config into two groups, cflags and libs, and consistently applies the cflags to each individual module linking the library while applying the libs only once for each compilation.
---
Compilation command used in compiling the sample given in #18628 prior to this change:
```
/var/home/ian/src/zig/build/stage3/bin/zig build-exe -ODebug --dep mod1 --dep mod2 -Mroot=/var/home/ian/src/zig-multi-module-test/src/main.zig -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-6 -lglib-2.0 -Mmod1=/var/home/ian/src/zig-multi-module-test/src/mod1.zig -Mmod2=/var/home/ian/src/zig-multi-module-test/src/mod2.zig -lc --cache-dir /var/home/ian/src/zig-multi-module-test/zig-cache --global-cache-dir …
```
=> Apply cflags from pkg-config to all dependent modules

lib/std/os.zig
=> std.os: fix chdirZ to compile on Windows

src/link/MachO/Dylib.zig, src/link/MachO/Object.zig, src/link/MachO/ZigObject.zig, test/link/macho.zig
=> macho: improve weak-ref symbols handling

src/link/MachO/Dylib.zig, test/link/macho.zig
=> macho: fix parsing versions from TBDs if parsed as floats

lib/std/http/Client.zig, lib/std/http/Headers.zig
Also fixes a bug with proxy auth missing the prefix.
=> http: support basic access authentication

lib/std/crypto/25519/ed25519.zig, lib/std/crypto/Certificate.zig, lib/std/crypto/tls/Client.zig
Which were claimed to be supported during the handshake but were not actually implemented.
=> tls: support ed25519 signatures

lib/std/fs/test.zig
This allows for easier debugging without the need to print out the path type to stderr.
Example trace from an induced error:
```
C:\Users\Ryan\Programming\Zig\zig-tmp\lib\std\fs\test.zig:652:45: 0x14194e1 in impl (test.exe.obj)
return error.FakeInducedError;
^
C:\Users\Ryan\Programming\Zig\zig-tmp\lib\std\fs\test.zig:120:5: 0x14197ab in testWithPathTypeIfSupported__anon_54668 (test.exe.obj)
try test_func(&ctx);
^
C:\Users\Ryan\Programming\Zig\zig-tmp\lib\std\fs\test.zig:110:5: 0x14198ab in testWithAllSupportedPathTypes__anon_54664 (test.exe.obj)
try testWithPathTypeIfSupported(.absolute, test_func);
^
C:\Users\Ryan\Programming\Zig\zig-tmp\lib\std\fs\test.zig:650:5: 0x1419915 in test.Dir.statFile (test.exe.obj)
try testWithAllSupportedPathTypes(struct {
^
```
Context: …
=> fs tests: Make path type show up in stack traces of testWithAllSupportedPathTypes

src/Sema.zig, test/cases/compile_errors/union_enum_field_does_not_match_enum.zig, test/cases/compile_errors/union_extra_field.zig
=> Fix OOB when enum field out of order in different file

src/link/MachO/relocatable.zig
As reported by @jacobly0, the Apple system linker matches sections to segments by name and not by flags causing Zig's executable section ending up in a segment with incorrect permission flags.
=> macho: sanitize Zig sections segment names before emitting a relocatable

lib/std/crypto/Certificate/Bundle/macos.zig, lib/std/crypto/tls/Client.zig, src/Sema.zig, src/TypedValue.zig, src/codegen/llvm/Builder.zig
This fixes issues targetting both `x86_64-linux` and `x86_64-macos` with the self-hosted backend.
=> x86_64: fix errors compiling the compiler

lib/compiler_rt/os_version_check.zig
This change causes `__isPlatformVersionAtLeast` to no longer exist in compiler_rt when targetting a min os version earlier than 10.15, which is earlier than the default os version and so only affects builds that explicitly target an older version than Zig officially supports.
=> compiler_rt: avoid referencing symbol on versions where it doesn't exist

src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Encoding.zig, src/arch/x86_64/Mir.zig, src/arch/x86_64/encodings.zig
=> Add the `clflush` mnemonic

src/link/MachO.zig, src/link/MachO/Archive.zig, src/link/MachO/Atom.zig, src/link/MachO/Object.zig, src/link/MachO/file.zig
=> macho: store open file descriptors in a global array

test/behavior/abs.zig, test/behavior/basic.zig, test/behavior/bitcast.zig, test/behavior/bitreverse.zig, test/behavior/byteswap.zig, test/behavior/cast.zig, test/behavior/eval.zig, test/behavior/extern.zig, test/behavior/floatop.zig, test/behavior/fn.zig, test/behavior/import_c_keywords.zig, test/behavior/math.zig, test/behavior/muladd.zig, test/behavior/multiple_externs_with_conflicting_types.zig, test/behavior/packed-struct.zig, test/behavior/translate_c_macros.zig, test/behavior/tuple.zig, test/behavior/vector.zig, test/behavior/widening.zig
=> x86_64+macho: pass more behavior tests

src/link/MachO/relocatable.zig
=> macho: include compiler-rt in static lib if requested

CMakeLists.txt, src/link/Elf.zig, src/link/Elf/Archive.zig, src/link/Elf/Atom.zig, src/link/Elf/Object.zig, src/link/Elf/SharedObject.zig, src/link/Elf/ZigObject.zig, src/link/Elf/eh_frame.zig, src/link/Elf/file.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig, src/link/MachO/Archive.zig
Mirrors https://github.com/kubkon/zld/pull/109
=> elf: reduce memory pressure

build.zig
An example of this happening is during CI runs where it has a value such as `c++ -target x86_64-linux-musl -mcpu=baseline`.
=> build.zig: support multiple args in `cxx_compiler_arg1`

lib/std/zig/system/linux.zig
Partial fix for #18848
Will test later today.
=> Add CPU model detection for RISC-V systems

src/Sema.zig, test/cases/compile_errors/runtime_condition_comptime_type_in_destructure.zig
=> Sema: validate that runtime-known inferred alloc does not have comptime-only type

src/codegen/c.zig
Attempts to fix the current CI failures introduced by #18983.
=> cbe: make more use of `InternPool.Index.Slice`

src/codegen/llvm.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig
=> llvm: fix c abi for structs not passed in registers

src/Sema.zig, test/behavior/cast.zig
=> Fix peer type resolution for arrays of coercible elements

src/link/MachO.zig, src/link/MachO/DebugSymbols.zig, src/link/MachO/UnwindInfo.zig, src/link/MachO/dyld_info/bind.zig, src/link/MachO/load_commands.zig, src/link/MachO/relocatable.zig
=> MachO: fix `calcLoadCommandsSize` computation

ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/Object.zig, src/link/Elf/eh_frame.zig, src/link/Elf/relocation.zig, src/link/MachO/Atom.zig, src/link/MachO/Relocation.zig, src/link/MachO/synthetic.zig, src/link/MachO/thunks.zig, src/link/aarch64.zig, src/link/riscv.zig, test/link/elf.zig
=> elf: add basic aarch64 and riscv64 support

lib/std/c.zig
- restricted similar $INODE64 symbols to macos x86_64 only
- minor cleanup and updated comments
closes #11386
- used the following code sample to verify correctness:
```
{
var buf = std.mem.zeroes(std.c.Stat);
_ = std.c.stat("z0.zig", &buf);
std.log.debug(" stat: {}", .{buf});
}
{
var buf = std.mem.zeroes(std.c.Stat);
const fd = std.c.open("z0.zig", .{});
_ = std.c.fstat(fd, &buf);
std.log.debug("fstat: {}", .{buf});
}
}
```
=> std: fix macos x86_64 to link stat$INODE64

src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, src/codegen/llvm/bitcode_writer.zig
See https://github.com/ziglang/zig/pull/19031#issuecomment-1962740908
=> llvm: rework memory management in emit

src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/MachO/InternalObject.zig
=> macho: actually set SG_READ_ONLY on __DATA_CONST segment

lib/std/http/Client.zig, lib/std/http/test.zig
=> std.http.Client: fix UAF when handling redirects

src/Sema.zig, test/behavior/switch.zig, test/cases/compile_errors/switch_capture_incompatible_types.zig
Fixes https://github.com/ziglang/zig/issues/18660.
=> Sema: preserve field alignment in union pointer captures

lib/std/Target.zig, lib/std/os.zig
Also general cleanup of things that the compiler supports now.
=> posix: fix socket fd leak

lib/compiler/objcopy.zig, src/main.zig
=> move `zig objcopy` command to be lazily built

src/main.zig
Ref: https://man.archlinux.org/man/extra/lld/ld.lld.1.en#rpath
=> cli: add `--rpath` and `-R` linker arg aliases

lib/std/Build/Step/Compile.zig, src/Compilation.zig, src/link.zig, src/link/Coff/lld.zig, src/link/Elf.zig, src/link/Wasm.zig, src/main.zig
=> feat: add support for --enable-new-dtags and --disable-new-dtags

src/Sema.zig, test/behavior/switch.zig
=> Sema: reset block error return trace index between cases

CMakeLists.txt, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/LdScript.zig, src/link/Elf/Object.zig, src/link/Elf/Symbol.zig, src/link/Elf/eh_frame.zig, src/link/Elf/synthetic_sections.zig, src/link/Elf/thunks.zig, src/link/MachO/Atom.zig, src/link/MachO/synthetic.zig, src/link/MachO/thunks.zig, src/link/aarch64.zig, test/link/elf.zig
So far I have tested that linking `stage3` with `-fno-lld` works as expected. Having said that gotta add more tests!
=> elf: port aarch64 support from zld

lib/std/math.zig
I think of lerp() as a way to change coordinate systems, essentially remapping the input numberline onto a shifted+rescaled numberline. In my mind the full numberline is remapped, not just the 0-1 segment.
An example of how this is useful: in a game, you can write: `myPos = lerp(pos0, pos1, easeOutBack(u))`
for some `u` that changes from 0 to 1 over time.
(see https://easings.net/#easeOutBack)
This will animate `myPos` between `pos0` and `pos1`, overshooting the goal position `pos1` in a nicely-animated way.
`easeOutBack(float)->float` is a pure function that overshoots 1, and by combining it with `lerp()` we can remap coordinates in other coordinate systems, making them overshoot in the same way.
However, this overshooting is only possible because `easeOutBack(t)` sometimes exceeds the …
=> remove `math.lerp` bounds-check

doc/langref.html.in
Reviving #18043. I've addressed the feedback on that PR, and I think some documentation here is long overdue (even if imperfect), so I am going to set this to auto-merge, but feedback is still welcome.
=> langref: add basic documentation of RLS

lib/compiler_rt/emutls.zig, lib/std/Thread/Futex.zig, lib/std/Thread/RwLock.zig, lib/std/atomic.zig, lib/std/c.zig, lib/std/c/darwin.zig, lib/std/c/dragonfly.zig, lib/std/c/netbsd.zig, lib/std/fs/Dir.zig, src/Air.zig, src/arch/sparc64/CodeGen.zig
The usual trying to keep the BSDs capable of cmake-bootstrap and passing behavior and std test.
closes #19234
=> bsd: debitrot

lib/std/Build/Step/Options.zig
Add support for (normal, packed and extern) structs and non-exhaustive enums in build options.
Related to #3127.
=> Implementing structs and better enums in build options

lib/std/c.zig, lib/std/dynamic_library.zig, lib/std/os.zig
The cross-platform functions now use an error set that contains all possible errors on every platform.
Merges #18947
Supersedes #19040
=> std: adjust DynLib API

src/Compilation.zig, src/mingw.zig
fixes https://github.com/ziglang/zig/issues/18690
=> mingw: define _WIN32_WINNT when building CRT

lib/std/hash_map.zig
=> std.hash_map: fix pointer lock safety false positive

lib/std/fmt.zig, lib/std/fmt/format_float.zig
=> fix comptime float formatting

lib/docs/wasm/main.zig
=> autodoc: better indentation handling when rendering source code

src/Sema.zig, test/behavior/array.zig
=> Sema: fix crash accessing array of opv types

doc/langref.html.in
In sync with https://github.com/ziglang/zig-spec/pull/52
=> grammar: fix ASCII range typo

lib/std/json/stringify.zig, lib/std/json/stringify_test.zig
=> json.WriteStream.objectFieldRaw()

src/codegen/c.zig, src/codegen/llvm/Builder.zig, test/behavior/enum.zig
=> Builder: fix encoding big integers in bitcode

doc/build.zig.zon.md, lib/init/build.zig.zon
Also added the same description to doc/build.zig.zon.md
=> Document lazy dependency in init build.zig.zon

src/Compilation.zig
This was overlooked in #19458. Using the fully qualified name of each module usually makes sense, but there is one module where it does not, namely, the root module, since its name is `root`. The original Autodoc tar creation logic used `comp.root_name` for the root module back when it was the only module included in `sources.tar`, and that made sense. Now, we get the best of both worlds, using the proper root name for the root module while using the module name for the rest.
Thanks to @00JCIV00 for pointing this out!
=> Autodoc: fix root module name in sources.tar

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
closes #19601
Not sure if it is fastest way
=> std: fix big int llshr to respect aliasing

src/Sema.zig, test/cases/compile_errors/assign_to_constant_destructure.zig
=> fix runtime assignment to destructured constants

src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/LinkerDefined.zig, src/link/Elf/Object.zig, src/link/Elf/SharedObject.zig, src/link/Elf/Symbol.zig, src/link/Elf/ZigObject.zig, src/link/Elf/gc.zig, src/link/Elf/merge_section.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig, src/link/Elf/thunks.zig, src/link/MachO/Atom.zig, src/link/MachO/synthetic.zig, src/link/MachO/thunks.zig, src/link/aarch64.zig, test/link/elf.zig, test/link/link.zig
Handles `SHF_MERGE` and `SHF_MERGE | SHF_STRINGS` sections in the ELF linker.
=> link/elf: implement string merging

src/InternPool.zig, src/Module.zig, src/Sema.zig, src/arch/x86_64/CodeGen.zig, src/arch/x86_64/abi.zig, src/codegen/c/Type.zig, src/codegen/llvm.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig
=> x86_64: fix C abi for unions

src/Sema.zig, test/cases/compile_errors/slice_end_index_undefined.zig
=> Sema: error on slice `undefined` end index

src/codegen/llvm.zig, src/codegen/llvm/Builder.zig
This PR removes most constant expression from Builder in preparation for LLVM 18. These constant expression will either be removed in LLVM 18 or are planned to be removed at a later date (some discussion on the subject can be found on the [LLVM discourse](https://discourse.llvm.org/t/rfc-remove-most-constant-expressions/63179/28)). 
Most of the removed expression were unused anyway, the only major change to the backend is to how packed struct and union values are lowered. They are now lowered manually into a single integer instead of a constant expression. Constant expressions have also been converted to instructions in other places (which is what the LLVM auto upgrade system would have done anyway).
These are the remaining constant expressions in Builder:
```
trunc
ptrtoint
inttoptr …
```
=> LLVM: Remove deprecated or soon to be deprecated constant expressions

src/codegen/c.zig
As of Clang 18, calling memcpy() with a misaligned pointer [trips UBSAN](https://godbolt.org/z/KG6z64aYP), even if the length is zero. This unfortunately includes any call to `@memcpy` when source or destination are undefined and the length is zero.
This patch makes the C backend avoid calling memcpy when the length is zero, thereby avoiding undefined behavior.
A zig1.wasm update will be needed in the llvm18 branch to activate this code.
=> C backend: avoid memcpy when len=0

lib/std/Build/Step/CheckObject.zig
This function incorrectly assumed that module name subsections, function name subsections, and local name subsections are encoded the same, however according to
[the specification](https://webassembly.github.io/spec/core/appendix/custom.html) they are encoded differently.
This commit adds support for parsing module name subsections correctly, which started appearing after upgrading to LLVM 18.
=> std.Build.Step.CheckObject: fix parseDumpNames

lib/zig.h, src/codegen/c.zig
A zig1.wasm update will be needed in the llvm18 branch to activate this code.
=> cbe: fix ub with integer `@abs`

lib/compiler/build_runner.zig, lib/std/Thread/Pool.zig, src/Compilation.zig, src/Package/Fetch.zig, src/link/MachO/hasher.zig, src/main.zig
This function accepts a WaitGroup parameter and manages the reference counting therein. It also is infallible.
=> add std.Thread.Pool.spawnWg

lib/std/compress/flate/inflate.zig
Fixes: #19895 
Calling `.read` will result in panic when reading into an empty buffer. This happens, because `limit: usize` parameter in `.get` function have alternative meaning, for `limit=0`.
Note: I encountered this bug, when using tar iterator on top of gzip reader.
@ianic, while adding test for this bug, I found there are no simple tests for public facing functions of `Inflate` struct, maybe in future revision or maintenance they could be added with my test merged into them, thank you.
=> std.compress.flate: fix panic when reading into empty buffer

lib/std/child_process.zig
Add some basic documentation for the different ChildProcess.StdIo
behaviors and the fields they affect.
=> ChildProcess: document StdIo behaviors

lib/std/heap/PageAllocator.zig
There's no need to call `alignForward` before `VirtualAlloc`. From [MSDN](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc#:~:text=If%20the%20lpAddress%20parameter%20is%20NULL%2C%20this%20value%20is%20rounded%20up%20to%20the%20next%20page%20boundary):
```
If the lpAddress parameter is NULL, this value is rounded up to the next page boundary
```
=> Avoid unnecessary operation in PageAllocator.

lib/std/Build/Cache.zig, lib/std/Build/Step/Run.zig
Fixes regression introduced by #19826
Closes #19947
=> Build.Step.Run: fix cache management when there are side effects

lib/libcxx/src/atomic.cpp, lib/libcxx/src/chrono.cpp, lib/libcxxabi/src/cxa_guard_impl.h
=> update libcxx and libcxxabi to llvm 18.1.6

lib/std/bounded_array.zig
This PR implements `BoundedArray.addManyAsSlice`, for parity with `ArrayList.addManyAsSlice`.
I noticed this API was missing when switching a buffer from `ArrayList` to `BoundedArray` since a small fixed size buffer was enough for my use case, and avoided an allocation. I think it would be useful for these two containers to share the same methods where possible, so that users of the standard library can make this kind of switch easily.
The PR also has a doc comment fix for `BoundedArray.addManyAsArray`, since it returns a pointer to an array, not a slice.
Closes #19967.
=> std: implement BoundedArray.addManyAsSlice

lib/std/fmt.zig
this changes literally nothing except for my ability to sleep sound at night
=> use constant in formatType

doc/langref.html.in, lib/std/zig/AstGen.zig, src/Air.zig, src/Sema.zig, src/codegen/llvm.zig
=> llvm: fix `@wasmMemory{Size,Grow}` for wasm64

src/Compilation.zig
The diag file did not get deleted on the success path and the dep file did not get deleted on the failure path.
=> Compilation: better cleanup of temporary files

src/Compilation.zig
=> Compilation: fix regressed assembly diagnostics

test/src/Cases.zig
You don't know if it's possible to run a binary until you try. The build system already integrates with executors and has the `skip_foreign_checks` for exactly this use case.
=> test cases: try running foreign binaries

lib/std/Progress.zig
3a3d2187f986066859cfb793fb7ee1cae4dfea08 unintentionally broke some of the Windows console API implementation.
- The 'marker' character was no longer being written at all
- The ANSI escape codes for syncing were being written unconditionally
Unsure if this fixes the Wine behavior. Will test that in a second.
=> std.Progress: Fix Windows console API implementation

lib/std/Progress.zig
Reduce node_storage_buffer_len from 200 to 83. This makes messages over the pipe fit in a single packet (4096 bytes). There is now a comptime assert to ensure this. In practice this is plenty of storage because typical terminal heights are significantly less than 83 rows.
Handling of split reads is fixed; instead of using a global `remaining_read_trash_bytes`, the value is stored in the "saved metadata" for the IPC node.
Saved metadata is split into two arrays so that the "find" operation can quickly scan over fds for a match, looking at 332 bytes maximum, and only reading the memory for the other data upon match. More typical number of bytes read for this operation would be 0 (no child processes), 4 (1 child process), or 64 (16 child processes reporting progress).
Removed an align(4) …
=> std.Progress: IPC fixes

lib/std/Build/Step/Run.zig
The docs for setting stdio to "inherit" say:
https://github.com/ziglang/zig/blob/c564a16a01811c18113fe304dbc3e8255af9f172/lib/std/Build/Step/Run.zig#L101-L106
The implementation of this lock was missing but is now provided by this commit.
closes #18855 [[asciinema](https://asciinema.org/a/UshqIldyZcGWtWdRjWHO4fPIj)]
=> std.Build.Step.Run: global lock when child inherits stderr

src/main.zig
also lock stderr for good measure. it's generally a good idea to lock stderr when you are spawning and waiting for a child that inherits stderr.
closes #20148
=> zig run: finish progress node before executing child

lib/std/Progress.zig
closes #20161
problem introduced in e09963d8544c19812db20e520f09f6e5d9a57d64
=> std.Progress: fix line upper bound calculation

lib/std/posix.zig
=> Add ECONNREFUSED to sendto

doc/langref/test_basic_slices.zig, doc/langref/test_multidimensional_arrays.zig, doc/langref/test_union_method.zig
I have found myself repeatedly looking through the docs for each of these. I don't believe they are documented anywereh currently.
1. How to make an empty slice.
2. How to initialize a multidimensional array to zero.
3. How to assign a tagged union to a tag with no value.
=> Document a few non-obvious variable assignments

src/main.zig
=> Parse WASM linker flags as base 10, like clang

lib/std/Thread.zig
=> std: Extended type checks for Thread startFn return type

src/arch/riscv64/CodeGen.zig, src/arch/riscv64/Lower.zig, src/arch/riscv64/abi.zig, src/arch/riscv64/bits.zig
=> riscv: remove deprecated `Module` usages

src/link/MachO.zig
=> macho: support TSAN

lib/std/Build/Cache.zig, lib/std/debug.zig, src/Compilation.zig, src/InternPool.zig, src/Package/Module.zig, src/Sema.zig, src/Type.zig, src/Zcu.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/link/C.zig, src/link/Dwarf.zig, src/link/Wasm/ZigObject.zig, src/main.zig
I titled the PR after the primary commit, but there are some other independent commits before it as well. See commit messages for more information. In summary, this is progress towards compiler state serialization.
=> Zcu: extract serializable state from File

lib/std/os/linux/bpf.zig
sync map/prog/attach type with latest kernel.
=> bpf: sync with latest linux kernel

lib/std/debug.zig, lib/std/os/linux.zig, src/Zcu/PerThread.zig
=> debug: prevent segfaults on linux

lib/std/Thread.zig, lib/std/Thread/Pool.zig
=> fix: Update `spawn`'s `runFn` signature

lib/std/Build/Step/Run.zig
Just like how addPrefixedFileArg and addPrefixedDirectoryArg works, we can make it for artifacts.
=> Allow adding prefix to artifact arguments

lib/std/process.zig, lib/std/unicode.zig
Before this commit, the WTF-16 command line string would be converted to WTF-8 in `init`, and then a second buffer of the WTF-8 size + 1 would be allocated to store the parsed arguments. The converted WTF-8 command line would then be parsed and the relevant bytes would be copied into the argument buffer before being returned.
After this commit, only the WTF-8 size of the WTF-16 string is calculated (without conversion) which is then used to allocate the buffer for the parsed arguments. Parsing is then done on the WTF-16 slice directly, with the arguments being converted to WTF-8 on-the-fly.
This has a few (minor) benefits:
- Cuts the amount of memory allocated by ArgIteratorWindows in half (or better)
- Makes the total amount of memory allocated by ArgIteratorWindows predictable, since, …
=> ArgIteratorWindows: Reduce allocated memory by parsing the WTF-16 string directly

lib/std/array_list.zig
=> std.ArrayList.unusedCapacitySlice: Return unaligned slice

src/main.zig
=> Fix handling of `--save-exact=name` in fetch

lib/std/Progress.zig, lib/std/mem.zig, src/InternPool.zig, src/Zcu/PerThread.zig, src/main.zig, src/target.zig
Let's see what happens :sweat_smile:
See also #20635
=> InternPool: enable separate codegen/linking thread

lib/std/os/linux.zig
The current build runner is failing to compile on x86.
```
techatrix@nixos-desktop:~/repos/zls/ > zig-linux-x86-0.14.0-dev.364+8ab70f80c/zig build -freference-trace
zig-linux-x86-0.14.0-dev.364+8ab70f80c/lib/std/os/linux.zig:719:9: error: @bitCast size mismatch: destination type 'usize' has 32 bits but source type 'os.linux.fanotify.MarkMask' has 64 bits
@bitCast(mask),
^~~~~~~~~~~~~~
zig-linux-x86-0.14.0-dev.364+8ab70f80c/lib/std/os/linux.zig:4211:33: note: struct declared here
pub const MarkMask = packed struct(u64) {
~~~~~~~^~~~~~
referenced by:
fanotify_markZ: zig-linux-x86-0.14.0-dev.364+8ab70f80c/lib/std/posix.zig:4555:36
fanotify_mark: zig-linux-x86-0.14.0-dev.364+8ab70f80c/lib/std/posix.zig:4542:30
update: zig-linux-x86-0.14.0-dev.364+8ab70f80c/lib/std/Build/Watch.zig:174:52 …
```
=> fix fanotify_mark on 32-bit

lib/std/Target.zig, lib/std/elf.zig
See: https://github.com/loongson/la-abi-specs/blob/release/laelf.adoc
=> std: Add loongarch support for elf.

src/arch/wasm/CodeGen.zig, test/behavior/basic.zig, test/behavior/math.zig
Touched add/sub/shl/mul. Fixed bug in comparison. Also added/reworked tests for overflow ops.
Applied renaming of wrong switcheroo lsb/msb, that discussed in DM.
=> stage2-wasm: overflow ops improvement

doc/langref.html.in, doc/langref/test_single_item_pointer.zig
=> Add documentation for single-item pointer slice syntax

lib/std/builtin.zig
Inspired by the review in #16094. cc @wooster0?
=> std.builtin.panic(uefi): usability improvements

src/dev.zig, src/link/Elf.zig, src/link/Elf/Object.zig, src/link/Elf/relocatable.zig, src/link/riscv.zig
upstream of https://github.com/kubkon/zld/pull/151
cc @kubkon
=> elf: add riscv eflag collisions

src/codegen/llvm.zig
Before, this code:
```zig
@setRuntimeSafety(false);
var arr: [38]elf.Addr = undefined;
```
would emit a call to `memset()` in the output code in Debug mode, while in all the release modes, LLVM optimized the `memset()` out as expected. Emitting the call in Debug mode is problematic in some contexts, e.g. in `std.os.linux.start_pie` where we are not yet ready to correctly perform calls because relocations haven't been applied yet, or in the early stages of a dynamic linker, etc.
=> `llvm`: Don't emit safety memset() for stores of undef in Debug with safety off.

lib/init/src/root.zig
Just started reading the source code; hopefully, this will be the first of many PRs to come."
=> Fix typo in init files.

src/link/MachO.zig, src/link/MachO/InternalObject.zig, test/link/macho.zig
=> macho: fix typo in boundary symbols handling

lib/std/fs/Dir.zig, lib/std/posix.zig, lib/std/posix/test.zig, lib/std/unicode.zig
=> std: fix buffer overflows from improper WTF encoding

lib/std/Target.zig
See: https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html#c-lang-data-model
=> std: fix long double size for loongarch.

lib/std/atomic.zig
This should probably go in the release notes so people will know to audit their call sites.
I checked the call sites in the standard library; both look fine. That said, the inline assembly next to one [here](https://github.com/ziglang/zig/blob/7342017404db17c3caec82f18ae83292c62c0651/lib/std/Thread.zig#L823) looks very suspect because it's doing a memory read and in no way signaling that to LLVM. But that seems to be a pervasive issue with the inline assembly for wasm in this file. So that'll be a problem for another time.
=> `std.atomic`: Don't lie to the compiler about memory clobbers in spinLoopHint().

lib/std/zig/target.zig
https://lists.gnu.org/archive/html/info-gnu/2020-08/msg00002.html
=> std.zig.target: Add arc-linux-gnu.

tools/process_headers.zig
See also: https://github.com/ziglang/glibc-abi-tool/pull/9
=> `process_headers`: Add arc-linux-gnu.

lib/std/Target.zig, lib/std/mem.zig, lib/std/os/linux.zig, src/glibc.zig, src/musl.zig
Adopt some patches from https://github.com/yxd-ym/zig-bootstrap/pull/1 .
=> loongarch: various architecture specific fixes.

lib/std/builtin.zig, src/Sema.zig, test/behavior/src.zig
=> language: add module name field to `@src`

src/link/Coff.zig, src/link/Elf.zig, src/link/Elf/ZigObject.zig, src/link/MachO.zig, src/link/MachO/ZigObject.zig, src/link/Wasm/ZigObject.zig
=> link: handle pointers to extern symbols

lib/std/Target.zig
=> `std.Target`: Bump some minimum/maximum OS versions, and switch from SunOS to Solaris version numbers

lib/std/Target.zig
Sourced from LLVM/GCC backends and ABI documents.
=> `std.Target`: Some corrections and additions to stackAlignment().

test/tests.zig
These work for me locally now. Let's see if CI agrees.
Closes #3287.
=> `test`: Re-enable armv8-linux-gnueabihf tests.

lib/std/Build/Watch.zig
Using `--watch` I noticed a couple of issues with my initial attempt.
1) The index I used as 'completion key' was not stable over time, when directories are being added/removed the key no longer corresponds with the intended dir.
2) There exists a race condition in which we receive a completion notification for a directory that was removed.
My solution is to generate a key value and associate it with each Directory.
=> Watch.zig: fixes for windows implementation

lib/compiler/aro/aro/Compilation.zig, lib/std/time/epoch.zig
=> std.time.epoch: Fix comments referring to epoch as 1970-10-01

src/codegen/llvm.zig
=> llvm: disable instrumentation in naked functions

src/Air.zig, src/Air/types_resolved.zig, src/Compilation.zig, src/Liveness.zig, src/Liveness/Verify.zig, src/Sema.zig, src/Zcu/PerThread.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Emit.zig, src/arch/x86_64/Lower.zig, src/arch/x86_64/Mir.zig, src/arch/x86_64/bits.zig, src/arch/x86_64/encoder.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/link/C.zig, src/link/Coff.zig, src/link/Dwarf.zig, src/link/Elf/ZigObject.zig, src/link/MachO/ZigObject.zig, src/link/Plan9.zig, src/link/Wasm/ZigObject.zig, src/print_air.zig, test/src/Debugger.zig
=> Dwarf: inline calls progress

lib/std/zig/Zir.zig, src/Zcu.zig
This fixes a bug hit immediately by @andrewrk when he tried to use `--watch -fincremental` on the compiler :P
=> compiler: fix losing ZIR instructions in main_struct_inst fields

lib/std/Build/Step/TranslateC.zig, src/main.zig
Just a couple of bugfixes which unblock using `TranslateC` steps in the build system.
=> `std.Build.Step.TranslateC` fixes

ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, src/Type.zig, src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Emit.zig, src/arch/x86_64/Lower.zig, src/arch/x86_64/Mir.zig, src/link/Dwarf.zig, src/link/Elf/ZigObject.zig, test/src/Debugger.zig
Get the behavior tests executable passing `llvm-dwarfdump --verify` with no errors or warnings.
=> Dwarf: more cleanup

lib/std/valgrind.zig, lib/std/valgrind/cachegrind.zig, lib/std/valgrind/callgrind.zig, lib/std/valgrind/memcheck.zig
port [cachegrind.h](https://sourceware.org/git/?p=valgrind.git;a=blob;f=cachegrind/cachegrind.h;h=ddc10abe597f1346ea9b57f5849e2d0ac7b42523;hb=HEAD) to zig.
=> port cachegrind.h to zig

lib/std/os/linux/x86.zig
LLVM would run out of registers due to the `edi` usage. This happens because the compiler reserves a register to be used as the PIC register. Just extend what we're already doing for `ebp` to `edi` as well.
=> `std.os.linux`: Fix `syscall6()` when building for PIC/PIE.

lib/std/hash_map.zig
=> std.hash_map: fix error message in getAutoHashFn

src/Sema.zig, test/cases/compile_errors/error_set_decl_literal.zig
=> Sema: perform requested coercion when decl literal demoted to enum literal

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, src/arch/riscv64/CodeGen.zig, src/print_zir.zig, test/behavior/pointers.zig
=> compiler: provide correct result types to `+=` and `-=`

src/clang_options_data.zig, src/main.zig, tools/update_clang_options.zig
=> cc: Add support for -Wp,

src/Sema.zig, test/behavior/export_keyword.zig
=> Sema: mark export on owner nav when exporting function alias

lib/std/zig/AstGen.zig, test/cases/errdefer_discard.zig
=> fix: disallow discard as errdefer capture

lib/std/fs/test.zig, lib/std/os/windows.zig, lib/std/posix.zig, lib/std/zig/system.zig
=> std.os.windows.ReadFile: handle ERROR_LOCK_VIOLATION

lib/std/debug.zig
See commit message. Confirmed this builds but not tested as either my local QEMU setup broke or there is a larger regression somewhere else (I can't get it to boot).
=> std.debug: Fix defaultPanic() uefi build

ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Emit.zig, src/arch/x86_64/Lower.zig, src/arch/x86_64/Mir.zig, src/arch/x86_64/encoder.zig, src/link/Dwarf.zig, test/src/Debugger.zig, tools/lldb_pretty_printers.py
This implements dwarf lexical blocks.
=> Dwarf: progress

src/main.zig
=> zig fetch: update saved dependency with resolved URL

src/arch/aarch64/Mir.zig
=> fix some spelling (pseudo instead of psuedo)

src/codegen/spirv.zig, src/link/SpirV.zig, test/behavior/basic.zig, test/behavior/decl_literals.zig, test/behavior/eval.zig, test/behavior/inline_switch.zig, test/behavior/math.zig, test/behavior/pointers.zig, test/behavior/switch.zig
Makes the backend working again. I want to improve some things, but I figure that I might as well make that a separate PR.
=> spirv: fix some bitrot

src/Compilation.zig, src/InternPool.zig, src/Package/Module.zig, src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/main.zig, test/incremental/add_decl, test/incremental/fix_astgen_failure, test/incremental/remove_invalid_union_backing_enum
Fixes a few crashes, slightly improves the efficiency of gathering error bundles, and adds some test cases.
=> incremental compilation progress

doc/langref.html.in
=> langref: update builtin variadic functions

doc/langref.html.in
=> Remove `@setAlignStack` from the langref

src/Compilation.zig, src/Sema.zig
=> fix callconv resolution for varargs

lib/std/crypto/hkdf.zig, lib/std/crypto/sha3.zig
=> Allow HKDF based on Keccak hash functions

src/main.zig
=> CLI: don't warn on missing host-detected directories

lib/std/Target.zig, lib/std/builtin.zig, lib/std/gpu.zig, src/Sema.zig, src/codegen/spirv.zig, src/codegen/spirv/Module.zig, src/link/SpirV.zig, src/target.zig
=> spirv: push constants and small fixes

lib/std/os/windows.zig, lib/zig.h, stage1/zig.h
* Make them work for thumb and aarch64.
* Clean up `std.os.windows.teb()` a bit.
I also updated `stage1/zig.h` since the changes are backwards-compatible and are necessary due to the `std.os.windows` changes that call the newly-added functions.
=> `zig.h`: Improve portability of `zig_*_windows_teb()` helpers

lib/std/valgrind.zig, lib/std/valgrind/memcheck.zig, src/codegen/llvm.zig, src/target.zig
=> Add client request support for all architectures supported by Valgrind

build.zig, src/Sema.zig, src/link/Elf/SharedObject.zig, src/main.zig, test/behavior/slice.zig
This fixes `zig build -Denable-llvm -Duse-llvm=false` on my system.
=> fix llvm-enabled compiler builds with the self-hosted backend

lib/std/Build/Step/Run.zig
When using Build.Step.Run.captureStdOut with a program that prints more than 10 megabytes of output, the build process hangs.
This is because evalGeneric returns an error without reading child's stdin till the end, so we subsequently get stuck in `try child.wait()`.
To fix this, make sure to kill the child in case of an error!
Output before this change:
λ ./zig/zig build  -Dmultiversion=0.15.6 -Dconfig-release=0.15.7 -Dconfig-release-client-min=0.15.6
[3/8] steps
└─ run gh
^C
λ # an hour of debugging
Output after this change:
λ ./zig/zig build  -Dmultiversion=0.15.6 -Dconfig-release=0.15.7 -Dconfig-release-client-min=0.15.6
install
└─ install generated to ../tigerbeetle
└─ run build_mutliversion (tigerbeetle)
└─ run unzip
└─ run gh failure
error: unable to spawn gh: StdoutStreamTooLong …
=> build: don't hang when capturing Stdout of verbose Build.Step.Run

src/Sema.zig, test/behavior/cast.zig
fixes #22017 
the cast i added to the test feels a little gross but :man_shrugging: seems fine
=> Fix peer type resolution with allowzero pointers

src/link/Elf.zig, src/link/Elf/Object.zig, src/link/riscv.zig
=> link: use target to determine risc-v eflag validity

src/InternPool.zig
=> ip: cleanup `@constCast` usages

lib/std/c.zig
I just started using zig so I'm not sure how I would add a test for this ;)
Closes #22159.
=> Also export mach_timebase_info_data from darwin

lib/std/crypto/argon2.zig
=> argon2: bail out if m < 8p

test/standalone/build.zig, tools/fetch_them_macos_headers.zig, tools/gen_macos_headers_c.zig, tools/macos-headers.c
After this, I think https://github.com/ziglang/fetch-them-macos-headers can be archived.
=> Move fetch-them-macos-headers tools to ziglang/zig

lib/std/c/darwin.zig, lib/std/zig/system/darwin/macos.zig
source comes from: https://github.com/Homebrew/brew/blob/64edbe6b7905c47b113c1af9cb1a2009ed57a5c7/Library/Homebrew/extend/os/mac/hardware/cpu.rb#L132C14-L133
=> add m4 {pro,max} detection

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/InternPool.zig, src/link/Dwarf.zig
Fixes some of the bad stuff(tm) that the dwarf emitter was doing.
=> Dwarf: cleanup

tools/fetch_them_macos_headers.zig
=> Some cleanups and fixes for `fetch_them_macos_headers.zig`

src/InternPool.zig
This should fix the incremental test failures we've seen a few times today.
---
The `.empty` map in a shard is weird: it claims to have capacity 1, but you're not actually allowed to actually use that capacity. That's fine for the normal insertion algorithm, because it always resizes to a higher capacity when inserting the initial element. However, `rehashTrackedInsts` was not aware of this caveat, so sometimes tried to store to the single element of the `empty` map.
This system exists to avoid an extra branch in the main resizing logic (since `new_cap = old_cap * 2` only works if the capacity is never non-zero). However, it's fine for `rehashTrackedInsts` to have an extra branch to handle this case, since it's literally called once per update.
=> InternPool: fix segfault in `rehashTrackedInsts`

test/behavior/type.zig
follow up closing of #19985 by adding code from that issue to test/behavior/type.zig
=> add `@Type` behavior tests from #19985

lib/std/Target/Query.zig
This is an RLS footgun.
Resolves: #21834
=> std: fix undefined value in Target.Query

src/Sema.zig
Resolves: #22417
cc @jacobly0, feel free to pull this into your branch
=> Sema: fix incorrect type in `optional_payload` instruction

build.zig
Reverts the build script changes in b352595aa2ede0c2fd53094da4123aac031335ec  making the `zig build test-unit` available to run the unit tests for the compiler and no longer trying to make the compiler unit tests run the full target matrix.
Public service announcement: when working on the compiler you can use `zig build test-unit` after this to run the compiler unit tests only. It's fairly quick and painless.
=> build.zig: make unit tests not use the full matrix

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, src/Value.zig, src/Zcu/PerThread.zig, src/print_value.zig, src/print_zir.zig, test/cases/compile_errors/compile_log_a_pointer_to_an_opaque_value.zig, test/cases/compile_errors/comptime_var_referenced_at_runtime.zig, test/cases/compile_errors/comptime_var_referenced_by_decl.zig, test/cases/compile_errors/comptime_var_referenced_by_type.zig, test/cases/comptime_aggregate_print.zig
Depends on #22414 because I forgot to reset to master :)
=> compiler: improve "... contains reference to comptime var" errors

src/link/Dwarf.zig, test/behavior/generics.zig, test/behavior/sizeof_and_typeof.zig, test/behavior/type_info.zig, test/src/Debugger.zig
Solves, for the self-hosted backend, #41
=> Dwarf: emit debug info for extern globals

src/Sema.zig, test/cases/compile_errors/invalid_pointer_cast.zig
And add test coverage for the compile error in question.
=> Sema: fix UB in error reporting

src/Sema.zig, src/Zcu/PerThread.zig, test/behavior/union.zig, test/incremental/change_enum_tag_type
* Fix an incremental compilation bug where enum resolution failures did wacky things
* Fix Sema trying to initialize global union at comptime because pointer is comptime-known
=> incremental, Sema: minor fixes

lib/std/zig/system/x86.zig, src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Disassembler.zig, src/arch/x86_64/Encoding.zig, src/arch/x86_64/Lower.zig, src/arch/x86_64/Mir.zig, src/arch/x86_64/bits.zig, src/arch/x86_64/encoder.zig, src/arch/x86_64/encodings.zig
=> x86_64: add a bunch of instruction encodings

ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh
https://github.com/ziglang/zig/pull/22098#discussion_r1923120413
=> `ci`: Switch to Wasmtime v29.0.0.

lib/std/debug.zig, lib/std/mem/Allocator.zig, lib/std/zig.zig, src/Sema.zig, src/Zcu.zig, test/cases/compile_errors/invalid_switch_item.zig, test/cases/compile_errors/runtime_condition_in_inline_loop.zig
See commit messages.
Resolves: #22545
=> compiler: a few fixes

src/Compilation.zig, src/mingw.zig
and remove faulty assertion. When a prelink task fails, the completed_prelink_tasks counter will not decrement.
A future improvement will be needed to make the pipeline fully robust and handle failed prelink tasks, followed by updates in which those tasks succeed, and compilation proceeds like normal.
Currently if a prelink task fails, the Compilation will be left in a state unrecoverable by an incremental update.
=> Compilation pipeline: repeat failed prelink tasks

doc/langref.html.in
=> Add `zig std` to langref.html

doc/langref.html.in
=> langref: correct return type of comptime known bitcount ops

lib/std/http/Server.zig
Added a helper function to retrieve header values from http requests.
=> get a header value from http requests

lib/std/c.zig, lib/std/os/linux.zig, lib/std/posix.zig
https://pubs.opengroup.org/onlinepubs/009695299/functions/mkdir.html
https://man7.org/linux/man-pages/man2/mkdir.2.html
https://man.freebsd.org/cgi/man.cgi?query=mkdir&sektion=2&n=1
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/mkdir.2.html
https://keith.github.io/xcode-man-pages/mkdir.2.html
=> std: mkdir(2) mode uses mode_t

ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/aarch64-macos-debug.sh, ci/aarch64-macos-release.sh, ci/aarch64-windows.ps1, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, ci/x86_64-macos-release.sh, ci/x86_64-windows-debug.ps1, ci/x86_64-windows-release.ps1
Otherwise the disk just keeps getting filled up.
=> `ci`: Set `ZIG_GLOBAL_CACHE_DIR` and `ZIG_LOCAL_CACHE_DIR` earlier.

lib/std/process/Child.zig
=> std: don't leak a process in Child.run in case of an error

lib/std/zig/Zoir.zig, src/Builtin.zig, src/Compilation.zig, src/InternPool.zig, src/Package/Module.zig, src/Sema.zig, src/Sema/LowerZon.zig, src/Type.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/link.zig, src/link/Dwarf.zig, src/main.zig, src/print_zir.zig, test/cases/compile_errors/@import_zon_bad_import.zig, test/incremental/change_zon_file
what if you wanted zon to work better?
well you need imagine no longer
your dream is a reality.
* it actually notices changes now
* it caches ZOIR
* it works with incremental (and i even added a test)
* i did something sneaky with the whole cache manifest what i mean nothing don't look andrew
=> ZON and incremental bits

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Compilation.zig, src/InternPool.zig, src/Sema.zig, src/Zcu.zig, src/print_zir.zig, test/behavior/cast.zig, test/behavior/error.zig, test/behavior/eval.zig, test/behavior/fn.zig, test/behavior/generics.zig, test/behavior/slice.zig, test/behavior/type_info.zig, test/behavior/union.zig, test/cases/compile_errors/for_comptime_array_pointer.zig, test/cases/compile_errors/struct_depends_on_itself_via_non_initial_field.zig, test/cases/compile_errors/tagName_on_undef_enum_literal.zig, test/incremental/analysis_error_and_syntax_error
Wow, `-Duse-llvm=false` makes quickly iterating on a bunch of bugs super easy!
=> Fix a bunch of frontend bugs

src/arch/x86_64/CodeGen.zig, src/link/Dwarf.zig, src/link/Elf/ZigObject.zig
Fixes the backend portion of #22798
=> x86_64: fix backend assertion failures

src/codegen/c.zig
=> cbe: emit linksection for `@export`

lib/zig.h, test/behavior/math.zig
=> cbe: fix ub triggered by mulw overflowing the promoted type

lib/std/array_hash_map.zig
Only available in the "unmanaged" variant since the other one is deprecated.
=> std.ArrayHashMap: introduce setKey

lib/compiler_rt/memcpy.zig
When using the LLVM backend, array copies were lowered as calls to `llvm.memcpy.*` builtin which could cause recursive calls to memcpy to be generated (observed with `-target x86_64-linux -mcpu x86_64+avx512vl --debug-rt`).
By instead performing these small fixed-size copies with integers or vectors the LLVM backend does not generate calls to the LLVM memcpy builtin, so combined with `-fno-builtin` no recursive calls to `memcpy` should be generated.
I have tested the change via `stage3/bin/zig test ../test/behavior.zig --debug-rt --test-cmd [QEMU_EXE] --test-cmd-bin` and inspection of the LLVM IR generated by the LLVM backend for targets `arm-linux`, `aarch64-linux`, `x86_64-linux`, `riscv32-linux` and `riscv64-linux`. There should be no performance impact for these targets as the …
=> compiler-rt: fix memcpy generating recursive calls

lib/libc/musl/src/locale/iconv.c
https://www.openwall.com/lists/oss-security/2025/02/13/2
Closes #22883.
=> musl: Apply Rich Felker's CVE-2025-26519 mitigation patches.

lib/std/zon/stringify.zig
=> zon.stringify: Correctly serialize unions with void fields

lib/std/os/linux.zig
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/udp.h
=> linux: add UDP socket options

lib/std/zig/AstGen.zig, test/cases/compile_errors/extern_packed_on_opaque.zig
=> AstGen: make layout specifiers on opaque containers a compile error

lib/std/zig/system/NativePaths.zig
Added code to check for Homebrew paths on Mac.
=> std.zig.system.NativePaths: Add Homebrew paths

lib/std/heap/debug_allocator.zig
zig 0.14.0-dev.3271+bd237bced
The problem is getting this in a js console when running the dvui web-test:
```
web-test.wasm-02395a3e:0xfee3e Uncaught RuntimeError: unreachable
at web-test.wasm.debug.defaultPanic (web-test.wasm-02395a3e:0xfee3e)
at web-test.wasm.heap.debug_allocator.DebugAllocator(bin/.{ .stack_trace_frames = 0, .enable_memory_limit = false, .safety = true, .thread_safe = false, .MutexType = null, .never_unmap = false, .retain_metadata = false, .verbose_log = false, .backing_allocator_zeroes = true, .resize_stack_traces = false, .canary = 2246045967, .page_size = 131072 }).free (wasm://wasm/web-test.wasm-02395a3e)
at web-test.wasm.mem.Allocator.free__anon_17185 (web-test.wasm-02395a3e:0x14523b)
```
It's because the DebugAllocator chose the wrong page_size so the canary …
=> fix DebugAllocator.default_page_size

lib/std/posix.zig
https://github.com/ziglang/zig/pull/22461#issuecomment-2676411079
=> std.posix: Handle USER_MAPPED_FILE in windows ftruncate() impl

src/Zcu.zig
Resolves: #21569
Resolves: #22912
=> Zcu: correctly resolve references to test bodies

lib/std/os/uefi.zig, lib/std/time.zig
See commit messages. Tested manually (ref #22809).
=> Three time-related fixes for UEFI

test/link/elf.zig
https://github.com/ziglang/zig/issues/23125
=> `test`: Disable `test-elf-ld-script-path-error` for now.

src/codegen/llvm.zig
This should be a lot easier to maintain. It's also a small step towards eventually making the builder API parse the data layout string in order to answer layout questions that we need to ask during code generation.
=> `llvm`: Replace `DataLayoutBuilder` with a simple target -> string switch.

lib/std/mem/Allocator.zig
=> std.mem.Allocator.remap: fix incorrect doc comment

src/Sema.zig, test/behavior/this.zig
=> Sema: fix handling of `@This()` on opaques

lib/std/Thread.zig, lib/std/crypto/Certificate/Bundle.zig, lib/std/fs.zig, lib/std/fs/get_app_data_dir.zig, lib/std/os.zig, lib/std/process.zig, lib/std/zig/target.zig
Not nearly the entire downstream patchset but these are completely uncontroversial and known to work.
Depends on #23192.
=> std: Add support for SerenityOS in various places

lib/std/mem/Allocator.zig
See https://github.com/ziglang/zig/pull/23196#discussion_r1988165784
=> std.mem.Allocator.remap: fix incorrect doc comment (part 2)

lib/std/zig/c_translation.zig
=> std.zig.c_translation: fix function pointer casting

src/Sema.zig, test/behavior/array.zig
=> Sema: correctly handle empty by-ref initializers

lib/std/Target/spirv.zig, lib/std/gpu.zig, src/Sema.zig, src/codegen/spirv.zig, src/codegen/spirv/Assembler.zig, src/codegen/spirv/Module.zig, test/behavior.zig, test/behavior/bitcast.zig, test/behavior/cast_int.zig, test/behavior/export_keyword.zig, test/behavior/floatop.zig, test/behavior/globals.zig, test/behavior/packed-struct.zig, test/behavior/packed-union.zig, test/behavior/packed_struct_explicit_backing_int.zig, test/behavior/ptrcast.zig, test/behavior/ptrfromint.zig, test/behavior/sizeof_and_typeof.zig, test/behavior/struct.zig, test/behavior/union.zig, test/behavior/vector.zig, test/cases/compile_errors/illegal_operation_on_logical_ptr.zig, test/tests.zig
cc @Snektron @mlugg 
Resolves #23212
=> spirv: miscellaneous stuff #2

src/Zcu/PerThread.zig, src/codegen.zig, src/link.zig, src/link/Coff.zig, src/link/Dwarf.zig, src/link/Plan9.zig, src/register_manager.zig, test/behavior/packed-struct.zig
=> codegen: fix packed byte-aligned relocations

doc/langref.html.in, lib/compiler/aro_translate_c/ast.zig, lib/std/array_hash_map.zig, lib/std/multi_array_list.zig, lib/std/zig/llvm/Builder.zig, src/Compilation.zig, src/Sema.zig, src/arch/x86_64/Encoding.zig, src/link/Coff.zig, src/link/Elf/Atom.zig, src/link/MachO/Atom.zig, src/link/aarch64.zig, src/link/riscv.zig
contributes to https://github.com/ziglang/zig/issues/23352#issuecomment-2750449003
=> std.meta -> @FieldType

build.zig
* https://github.com/ziglang/zig/actions/runs/13824823318/job/38677744939?pr=23221#step:3:347
* https://github.com/ziglang/zig/actions/runs/14078929259/job/39427248526?pr=23353#step:3:349
Extracted from #23221, FYI @Rexicon226.
=> `build`: increase `test-std` max rss

lib/std/crypto/ecdsa.zig
=> crypto.ecdsa: fix EcdsaP384Sha3_384 constant name

lib/std/multi_array_list.zig
Resolves #23352
Adds eval branch quota for the comptime sort of fields, and test for a few struct field counts up to 200 fields.
=> Support structs with many fields in MultiArrayList

lib/std/zon/stringify.zig
=> zon: correctly serialize negative zeroes

src/Sema.zig, test/behavior/generics.zig
=> Sema: increment extra index even if return type is generic

test/behavior/struct.zig
=> x86_64: fix incorrect handling of unreusable operands

lib/libcxx/include/__configuration/availability.h
=> `libcxx`: Backport llvm/llvm-project#134278.

src/Compilation.zig
Zig will not include a bunch of compiler flags when providing `.ll` or `.bc` as source files. Here is a reproduction:
```
echo 'const std = @import("std");
std.debug.print("All your codebase are belong to us.", .{});
}' > main.zig
zig build-exe main.zig -femit-llvm-ir=main.ll -fno-emit-bin
zig build-exe main.ll -O ReleaseFast --verbose-cc
```
The last command will print the `zig clang` invocation which should now include the missing flags. 
Before:
```diff
zig clang main.ll --no-default-config -fno-caret-diagnostics -target x86_64-unknown-linux6.6.85-gnu2.39.0 -fno-PIC -gdwarf-4 -gdwarf32 -fno-lto -fhosted -mred-zone -fno-omit-frame-pointer -fno-stack-protector -fbuiltin -fno-function-sections -fno-data-sections -fasynchronous-unwind-tables -nostdinc
```
After: …
=> Include missing compiler flags when compiling LLVM IR source files

README.md
cc. @ricky8955555
Reported-by: Ricky8955555 <rkmiao@duck.com>
Signed-off-by: xtex <xtex@aosc.io>
=> doc: Bump LLVM version in README

lib/fuzzer/web/main.zig
The error was:
```
error: expected type '?mem.Alignment', found 'comptime_int'
```
Does this file have some kind of CI test to catch new errors in the future?
=> Fix compile error in Fuzzer web-ui

lib/std/crypto/ecdsa.zig
Some applications need to directly sign and verify hashes rather than a message.
=> crypto.ecdsa: add the ability to sign/verify prehashed messages

src/Compilation.zig, src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, test/incremental/change_exports, test/incremental/compile_error_then_log, test/incremental/compile_log, tools/incr-check.zig
See commit messages for details.
=> incremental: fixes

src/Sema.zig, test/behavior/align.zig
=> `Sema`: Fix some ptr alignment checks to handle a potential ISA tag bit.

lib/std/os/windows.zig, lib/std/posix.zig
Fix #23668 unexpected error 1453 on windows.
=> Fix Unexpected error for 1453 on Windows

lib/std/os/windows.zig
closes https://github.com/ziglang/zig/issues/23667
=> fix(windows): handle commitment limit error in CreateProcessW

src/translate_c.zig, test/cases/translate_c/macro_calling_convention.c
=> translate-c: fix callconv attribute in macro

lib/std/os/windows.zig
=> std: fix `error.Unexpected` on certain Windows file operations

src/glibc.zig
=> `glibc`: Fix stub libraries containing unwanted symbols.

lib/libcxx/include/__flat_map/flat_map.h, lib/libcxx/include/__flat_map/flat_multimap.h
=> `libcxx`: Backport llvm/llvm-project#137594.

lib/libtsan/sanitizer_common/sanitizer_linux.cpp, lib/libtsan/sanitizer_common/sanitizer_linux_libcdep.cpp, lib/libtsan/sanitizer_common/sanitizer_platform_limits_posix.cpp, lib/libtsan/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cpp, src/libs/libtsan.zig
https://github.com/llvm/llvm-project/pull/120036
=> `libtsan`: Backport llvm/llvm-project#120036.

lib/std/hash/wyhash.zig
=> std.hash.Wyhash: fix dangling stack pointer

tools/doctest.zig
Evaluate all child processes in the temporary directory, and use `std.fs.path.relative` to make every other path relative to that child cwd instead of our cwd.
Resolves: #22119
=> doctest: handle relative paths correctly

test/standalone/libfuzzer/build.zig, test/standalone/libfuzzer/main.zig
=> libfuzzer test: use proper cache dir logic

src/Zcu.zig
Bug introduced by d717c96, sorry!
=> Zcu: fix memory leak

CMakeLists.txt, lib/compiler/test_runner.zig, lib/std/builtin.zig, lib/std/debug.zig, lib/std/mem.zig, lib/std/os/linux.zig, lib/std/start.zig, lib/std/testing.zig, lib/ubsan_rt.zig, src/Zcu.zig, src/arch/powerpc/CodeGen.zig, src/codegen.zig, src/dev.zig, src/target.zig, test/cases/compile_errors/@import_zon_bad_type.zig, test/cases/compile_errors/anytype_param_requires_comptime.zig, test/cases/compile_errors/bogus_method_call_on_slice.zig, test/cases/compile_errors/coerce_anon_struct.zig, test/cases/compile_errors/redundant_try.zig
Nothing interesting here; literally just the bare minimum so I can work on this on and off in a branch without worrying about merge conflicts in the non-backend code.
=> compiler: Scaffold `stage2_powerpc` backend

src/Compilation.zig, src/Package/Module.zig, src/link/Elf.zig, src/main.zig
=> `link.Elf`: Don't require linking libc for dynamic linker path to take effect

lib/std/zig/llvm/ir.zig
=> llvm.ir: fix subrange version

lib/compiler/std-docs.zig
=> Fix `zig std` regression FTBFS

doc/langref/runtime_shrExact_overflow.zig, lib/libunwind/src/UnwindCursor.hpp, lib/std/Build/Step/CheckObject.zig, lib/std/bit_set.zig, lib/std/crypto/salsa20.zig, lib/std/os/linux/riscv32.zig, lib/std/os/linux/riscv64.zig, lib/std/simd.zig, lib/std/zig/system/linux.zig, src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/zig_llvm.cpp, src/zig_llvm.h, test/behavior/vector.zig, test/link/glibc_compat/build.zig, test/standalone/coff_dwarf/build.zig, test/standalone/stack_iterator/build.zig
Getting things in shape for CI on [Milk-V Jupiter](https://milkv.io/jupiter).
=> Native RISC-V bootstrap and test fixes

src/target.zig
https://github.com/ziglang/zig/issues/24341
=> compiler: Disable self-hosted x86_64 backend on NetBSD

lib/compiler_rt/clear_cache.zig
Unblocks https://github.com/ziglang/zig-bootstrap/issues/227#issuecomment-2993584357.
=> `compiler-rt`: Implement `__clear_cache()` for `mips-netbsd`

lib/std/Io/Reader.zig, lib/std/Io/Writer.zig, lib/std/debug.zig, lib/std/log.zig
=> buffering fixes

lib/std/Io/Reader.zig
Resolves: #24424
The benchmark in that PR is now *significantly* faster, even for the `take(10)` case.
Before:
```sh-session
$ ./repro fast
Time: 860ms
$ ./repro slow
Time: 1479ms
```
After:
```sh-session
$ ./repro fast
Time: 349ms
$ ./repro slow
Time: 358ms
```
The single `take` does still consistently *slightly* beat out the double `takeInt`. That makes sense; the second approach has to do a tiny bit more work (an extra check on the buffer length). However, the difference is ~2-5% instead of ~70%, and even the "slow" path is now 60% faster than the "fast" path *previously* was.
=> std.Io.Reader: encourage inlining hot buffer check

lib/std/zig/llvm/Builder.zig
this was enough to build some real projects from the printed IR
=> fix some llvm ir printer bugs

lib/std/Progress.zig
Closes https://github.com/ziglang/zig/issues/24491.
=> Progress: reset end when failing to flush stderr

lib/std/Io/Writer.zig
Here is one way to solve #24486.
=> std.io.Writer: remove requirement of a 2-byte buffer for extern unions

lib/std/Build/Step/Run.zig
https://github.com/ziglang/zig/pull/24151/files#r2217494741
=> `std.Build.Step.Run`: fix up 681d324c49e7cdc773cc891ea49ed69dd03c23c7

test/behavior/switch.zig
=> x86_64: fix some bugs

src/main.zig
=> Update `zig init` help with new `-m` arg

lib/std/Io.zig, lib/std/Io/DeprecatedReader.zig, lib/std/Io/test.zig
=> DeprecatedReader.Adapted: fix EndOfStream handling

lib/std/math.zig, lib/std/math/gamma.zig, lib/std/math/modf.zig, lib/std/math/pow.zig, lib/std/zon/parse.zig, src/Sema.zig, test/cases/compile_errors/int_to_float_coercion_loses_precision.zig
Solving a TODO which has gone untouched since the days of the bootstrap compiler! (TODO introduced in aecebf3)
Resolves: #21586
=> Sema: compile error on lossy int to float coercion

lib/std/crypto/ecdsa.zig
This confused me for a minute 😄
=> crypto: fix typo in ecdsa comment

lib/std/c.zig
=> std.c: fix utsname array sizes

lib/std/os/windows.zig
=> `std.os.windows`: map `RtlGenRandom()` failure to `error.SystemResources`

src/Package/Fetch/git.zig
Progress towards #24732
---
Examples from the linked issue now fetching correctly with this change:
```
ian@ian-laptop:~/src/zig/build$ stage4/bin/zig fetch git+https://gitlab.com/fjc/zigby.git#57d01bac78e1a152172d1daee4868593eb1c5156
zigby-0.2.0-AAAAABQFAAAmrS02aaQ-D_goZc5-vRrhI_TRWwdCMmjF
ian@ian-laptop:~/src/zig/build$ ~/opt/zig-0.14.1/zig fetch git+https://gitlab.com/fjc/zigby.git#57d01bac78e1a152172d1daee4868593eb1c5156
zigby-0.2.0-AAAAABQFAAAmrS02aaQ-D_goZc5-vRrhI_TRWwdCMmjF
ian@ian-laptop:~/src/zig/build$ stage4/bin/zig fetch git+https://github.com/ianprime0509/zig-xml
xml-0.1.0-ZTbP35VkAgAp2cDlvsPuL7SWVZWwPg-V99LmVRSHbCtL
ian@ian-laptop:~/src/zig/build$ ~/opt/zig-0.14.1/zig fetch git+https://github.com/ianprime0509/zig-xml
xml-0.1.0-ZTbP35VkAgAp2cDlvsPuL7SWVZWwPg-V99LmVRSHbCtL …
```
=> Fetch.git: fix FetchStream packet reading

lib/zig.h, src/codegen/c.zig, src/codegen/c/Type.zig, test/behavior/x86_64/binary.zig
=> cbe: emit `nonstring` attribute

lib/std/Io/Writer.zig, lib/std/compress/flate/Decompress.zig
=> std.Io.Writer: introduce rebase to the vtable

src/codegen/aarch64/Assemble.zig, src/codegen/aarch64/Disassemble.zig, src/codegen/aarch64/encoding.zig, src/codegen/aarch64/instructions.zon
=> aarch64: more assembler instructions

lib/std/os/linux/powerpc.zig, lib/std/os/linux/powerpc64.zig
https://git.musl-libc.org/cgit/musl/commit/?id=f6944eb3c4ce1c97dc39dc36d32390dc9f70b67b
=> `std.os.linux`: powerpc syscalls clobber `ctr` and `xer`

lib/std/mem/Allocator.zig
Here's a little util I take from project to project, that seems fundamental enough to be in `std`. It's useful when something expects an Allocator but you've already preallocated the needed memory.
I would have called it `Allocator.failing` (like `Writer.failing`), except that `testing.FailingAllocator` already exists and that would be confusing, so I followed the pattern in std.heap.
=> An allocator that always fails

lib/std/Build/Step/CheckObject.zig, lib/std/elf.zig, src/link/Elf/Object.zig, src/link/Elf/SharedObject.zig, src/link/Elf/ZigObject.zig, tools/gen_stubs.zig
https://groups.google.com/g/generic-abi/c/doY6WIIPqhU
=> ELF updates for gABI 4.3

lib/std/fs/File.zig
Follow-up to #25135
- introduce seekToUnbuffered which asserts no buffered data and does not have WriteFailed in the error set
- remove WriteFailed from SeekError
- make seekTo based on calling flush and then seekToUnbuffered
=> std.fs.File.Writer: break up seekTo

lib/std/http/Client.zig
=> std.http.Client.Connection: make host() public

lib/std/c.zig, lib/std/c/darwin.zig
=> std.c: adjust shm_open to be variadic on darwin

test/behavior/enum.zig
=> x86_64: improve support for large enums

lib/compiler/resinator/compile.zig, lib/compiler/resinator/preprocess.zig
Just a few minor things, the alignment fix is the only important thing.
=> resinator: Sync with upstream, fix an alignment problem

lib/std/http/test.zig
=> fix read of undefined in http tests
