ziglang/zig

- lib/std/crypto.zig
- lib/std/crypto/Certificate.zig
- lib/std/crypto/ff.zig
- lib/std/crypto/tls/Client.zig
A minimal set of simple, safe functions for Montgomery arithmetic, designed for cryptographic primitives.
Also update the current RSA cert validation to use it, getting rid of the FixedBuffer hack and the previous limitations.
Make the check of the RSA public key a little bit more strict by the way.
> std.crypto.ff - Alloc-free, constant-time field arithmetic for crypto

- lib/std/crypto/Certificate/Bundle.zig
Solves #15422 by ignoring certificates which cannot be parsed due to having an "unrecognized object id", in the same manner that expired certificates are currently ignored.
> Ignore certificates with unknown OID

- lib/std/crypto/chacha20.zig
- lib/std/rand/ChaCha.zig
Ryzen 7 7700, ChaCha20/8 stream, long outputs:
```
Generic: 3268 MiB/s
AVX2   : 6023 MiB/s
AVX512 : 8086 MiB/s
```
Apple M1 CPUs seem to also benefit from a 4-way implementation on micro-benchmarks, but only on full-round ChaCha, and I'm not sure we can generalize it to other aarch64 CPUs, or to real workloads.
~~So, enable this only on x86_64 for now.~~ verified to also improve performance on a Cortex A72, so enabling on aarch64, too.
Bump the rand.chacha buffer a tiny bit to take advantage of this. More than 8 blocks doesn't seem to make any measurable difference.
ChaChaPoly also gets a small performance boost from this, albeit Poly1305 remains the bottleneck.
```
Generic:  707 MiB/s
AVX2   :  981 MiB/s
AVX512 : 1202 MiB/s
```
> std.crypto.chacha: support larger vectors on AVX2 and AVX512 targets

- src/codegen/llvm.zig
> llvm: also generate metadata for extern global variables

- lib/std/crypto/tls.zig
The tls wg preferred a codepoint outside of the reserved range. This new codepoint has been assigned by IANA.
See
- https://datatracker.ietf.org/doc/draft-tls-westerbaan-xyber768d00-02/
- https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#table-tls-parameters-8
> crypto/tls: switch X25519Kyber768Draft00 to new codepoint

- lib/std/crypto/aes/aesni.zig
Define `optimal_parallel_blocks` for more CPUs.
> crypto.aes: define optimal_parallel_blocks for more CPUs

- lib/std/crypto/ghash_polyval.zig
```
Before:  91 MiB/s
After : 243 MiB/s
```
Some other platforms might benefit from this, but WebAssembly is the obvious one (simd128 doesn't make a difference).
> std.crypto: 2.5 times faster ghash and polyval on WebAssembly

- lib/std/Build.zig
- lib/std/Build/Step/WriteFile.zig
- test/src/Cases.zig
- test/src/CompareOutput.zig
- test/src/StackTrace.zig
- test/src/run_translated_c.zig
- test/src/translate_c.zig
- test/tests.zig
Prior to this change, to add a file to a `WriteFile` step and then use the written file elsewhere in your build script, you'd write the following code:
```zig
const path = "foo/bar.baz";
write_files.add(path, contents);
const file_source = write_files.getFileSource(path).?; // This line fails on Windows!
```
Aside from being a little verbose and doing some unecessary string comparisons, this fails on Windows: When the file is added to `WriteFiles`, it is passed to `dupePath` which replaces the path separators. Because the path separators were replaced, `getFileSource` fails to find an exact match.
There are a few ways we could resolve this issue:
Unfortunately this is not cross platform because there's no single path separator that all platforms recognize. Forward slash is close, but not …
> Fixes `WriteFile.getFileSource` failure on Windows

- lib/std/c/freebsd.zig
- lib/std/os/linux.zig
- lib/std/target.zig
- lib/std/zig/system/NativePaths.zig
- lib/std/zig/system/NativeTargetInfo.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/riscv64/abi.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen.zig
- src/codegen/c/type.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/glibc.zig
- src/link/Coff.zig
- src/link/Coff/lld.zig
- src/link/Dwarf.zig
- src/link/Elf.zig
- src/link/Elf/Atom.zig
- src/link/Plan9.zig
- src/mingw.zig
- src/musl.zig
- src/type.zig
- src/value.zig
* move `ptrBitWidth` from Arch to Target since it needs to know about the abi
* double isn't always 8 bits
* AVR uses 1-byte alignment for everything in GCC
These changes are needed to pass [Aro record layout tests](https://github.com/Vexu/arocc/tree/c6a3ecad7f7c79f39b61bf6841fc1b8f3a864dfc/test/records).
> std.Target adjustments

- lib/std/math/big/int.zig
- lib/std/math/big/int_test.zig
Implemented with reference to Modern Computer Arithmetic, Algorithm 1.13 \[[PDF](https://members.loria.fr/PZimmermann/mca/mca-cup-0.5.9.pdf)\]. https://members.loria.fr/PZimmermann/mca/pub226.html
The below optimization ideas are derived from Go's big package.
* Minimize initial loop value
* Reuse loop values
math/big/int.go: https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/math/big/int.go;l=1286
Motivation: I'm implementing cryptocurrency algorithms in Zig.
It is common to use 256-bit integer values in this domain. So it would be helpful if std.math.big.int supports common operations like square root.
> std.math.big.int: Add Sqrt

- lib/std/math/big/int.zig
I found typos while using std.math.big.int.
- `bytes` -> `buffer`
- Correct naming consistency between
1. fn argument and doc comment of `(read|write)PackedTwosComplement`
2. fn arguments of `(read|write)PackedTwosComplement` and `(read|write)TwosComplement`
From autodoc, we can see the naming inconsistencies.
[std:math.big.int.Mutable](https://ziglang.org/documentation/master/std/#A;std:math.big.int.Mutable)
[std:math.big.int.Const](https://ziglang.org/documentation/master/std/#A;std:math.big.int.Const)
> std.math.big.int: Fix typo

- lib/std/child_process.zig
- lib/std/os/windows.zig
- lib/std/os/windows/ntdll.zig
- lib/std/os/windows/test.zig
There are many different types of Windows paths, and there are a few different possible namespaces on top of that. Before this commit, NT namespaced paths were somewhat supported, and for Win32 paths (those without a namespace prefix), only relative and drive absolute paths were supported. After this commit, all of the following are supported:
- Device namespaced paths (`\\.\`)
- Verbatim paths (`\\?\`)
- NT-namespaced paths (`\??\`)
- Relative paths (`foo`)
- Drive-absolute paths (`C:\foo`)
- Drive-relative paths (`C:foo`)
- Rooted paths (`\foo`)
- UNC absolute paths (`\\server\share\foo`)
- Root local device paths (`\\.` or `\\?` exactly)
Plus:
- Any of the path types and namespace types can be mixed and matched together as appropriate.
- All of the `std.os.windows.*ToPrefixedFileW` …
> Windows: Support UNC, rooted, drive relative, and namespaced/device paths

- lib/std/dwarf.zig
This data changed quite significantly between DWARF 4 and 5. Some systems are shipping DWARF 5 libraries (Void Linux on musl libc seems to use it for crt1 etc), which meant when printing stack traces, a random compile unit might be incorrectly identified as containing an address, resulting in incorrect location information.
I was consistently experiencing this issue with compiler stack traces, and this change fixed it.
> std.dwarf: handle DWARF 5 compile unit DW_AT_ranges correctly

- src/Compilation.zig
- src/link.zig
- src/link/Coff/lld.zig
- src/link/Elf.zig
- src/link/MachO/zld.zig
- src/link/Wasm.zig
- src/main.zig
`-l :path/to/lib.so` behavior on gcc/clang is:
- the path is recorded as-is: no paths, exact filename (`libX.so.Y`).
- no rpaths.
The previous version removed the `:` and pretended it's a positional argument to the linker. That works in almost all cases, except in how rules_go[1] does things (the Bazel wrapper for Go).
Test case in #15743, output:
gcc rpath:
0x0000000000000001 (NEEDED)     Shared library: [libversioned.so.2]
0x000000000000001d (RUNPATH)    Library runpath: [$ORIGIN/x]
gcc plain:
0x0000000000000001 (NEEDED)     Shared library: [libversioned.so.2]
zig cc rpath:
0x0000000000000001 (NEEDED)     Shared library: [libversioned.so.2]
0x000000000000001d (RUNPATH)    Library runpath: [$ORIGIN/x]
zig cc plain:
0x0000000000000001 (NEEDED)     Shared library: [libversioned.so.2]
Fixes …
> zig ld: handle `--library :path/to/lib.so`

- lib/std/crypto/Certificate.zig
- lib/std/crypto/tls/Client.zig
Individual max buffer sizes are well known, now that arithmetic doesn't require allocations any more.
Also bump `main_cert_pub_key_buf`, so that e.g. `nodejs.org` public keys can fit.
> RSA: remove usage of allocators

- lib/std/fmt.zig
- lib/std/fmt/parse_float/decimal.zig
- lib/std/math/big/int.zig
- lib/std/math/scalbn.zig
- lib/std/zig/c_translation.zig
- src/main.zig
- src/translate_c.zig
- src/translate_c/ast.zig
This is for #15789. I chose 'base' because the std lib seemed closer to consistently using 'base' than 'radix'. I skipped a couple of occurrences of 'radix'  in `zig/c_translation.zig` because there it was part of the name of a type, which would be a breaking change. (There are other cases that would be breaking if we changed everything to radix)
> Use the word 'base' consistently instead of 'radix'

- src/arch/wasm/CodeGen.zig
- src/codegen.zig
- test/behavior/align.zig
- test/behavior/atomics.zig
- test/behavior/basic.zig
- test/behavior/bugs/12142.zig
- test/behavior/bugs/13113.zig
- test/behavior/bugs/13128.zig
- test/behavior/bugs/13664.zig
- test/behavior/bugs/1381.zig
- test/behavior/cast_int.zig
- test/behavior/empty_union.zig
- test/behavior/enum.zig
- test/behavior/error.zig
- test/behavior/eval.zig
- test/behavior/optional.zig
- test/behavior/ptrcast.zig
- test/behavior/return_address.zig
- test/behavior/type.zig
- test/behavior/union.zig
- test/behavior/union_with_members.zig
Fixes several miss-compilations or missing features of instructions to enable more behavior tests to pass. Each individual commit contains an explanation of the implementation and/or fix for the curious reader.
> wasm backend: implement/fix more behavior tests

- lib/std/crypto/benchmark.zig
- lib/std/crypto/siphash.zig
- lib/std/hash/benchmark.zig
- lib/std/hash/xxhash.zig
The benchmarks were reusing the same input buffer over and over again, giving a chance to the optimizer for computing the hash only once, and multiplying the output by the number of iterations.
After this, the results are *very* different (not in a good way, but at least, they are closer to reality).
Also add xxhash and siphash.
xxhash `hash()` function had a different API than all other std.hash function that forced the key to be 0. Make it consistent with other functions, especially since this is not a cryptographic hash function.
Remove some useless `pub` and declarations from siphash by the way.
> Fix std.hash benchmarks

- lib/std/crypto/tls.zig
- lib/std/crypto/tls/Client.zig
- lib/std/http/Client.zig
- lib/std/http/Server.zig
- lib/std/http/protocol.zig
- test/standalone/http.zig
Collapses BufferedConnection and StoredConnection into the existing Connection struct.
Adds errors for the different tls alerts so that an error return trace can point out which problem tls hit specifically.
Should fix #15710 and #15902
> std.http: fix infinite read loop, deduplicate connection code, add TlsAlert errors

- src/Package.zig
fixes an issue where multiple dependencies have a common module will crash on download because all_modules do not add the package unless it is cached ->
```
thread 15204 panic: reached unreachable code
C:\Git\zigcode\zig\lib\std\debug.zig:260:14: 0x7ff622d5e847 in assert (zig.exe.obj)
^
C:\Git\zigcode\zig\src\Package.zig:297:36: 0x7ff622f419bd in fetchAndAddDependencies (zig.exe.obj)
assert(other_sub == sub.mod);
^
C:\Git\zigcode\zig\src\main.zig:4412:67: 0x7ff622d905ae in cmdBuild (zig.exe.obj)
const fetch_result = build_pkg.fetchAndAddDependencies(
```
> fix missing insertion of module to all_modules on first download

- lib/std/Build/Step/Compile.zig
- lib/std/debug.zig
closes: #13405
Due to the change in default behavior of ReleaseSmall (#13067), debug info (pdb here) are stripped by default. However because `Compile.create` defaults to null, `producesPdbFile` will report true for
`lib/std/Build/Step/InstallArtifact.zig` 
https://github.com/ziglang/zig/blob/378264d404e71da878f9e6934c045ad64193877f/lib/std/Build/Step/InstallArtifact.zig#L33
Because of this, this only affects `zig build` and not `zig build-exe`. After this change, a simple program compiled with  `ReleaseSmall` will successfully compile and won't try to copy/produce the pdb file.
Of course, this still allows the user to choose not to strip the build and will produce a pdb file.
> Build: Fix bug causing ReleaseSmall to fail on Windows

- lib/std/c.zig
Windows defines `recv` and `recvfrom` to return a value of type `int`, rather than a pointer-sized signed integer, and so should use `c_int` rather than `isize` for their return types.
This would cause a bug where windows may return `-1` to indicate an error, but `std.os.recv` will not recognize it as an error, rather interpretting it as (and returning) `2^32 - 1`, indicating that `2^32 - 1` bytes were read into the buffer. I'm unsure if this is UB as it depends on whatever the top 32 bits of the `isize`  end up being, but this behaviour seemed reliable in debug builds.
Here are the docs for [recv](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-recv) and [recvfrom](https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-recvfrom), the headers …
> std.c: fix return type of recv/recvfrom on windows

- lib/std/hash/auto_hash.zig
- lib/std/hash/wyhash.zig
This updates to the new v4 version, so existing hashes will fail and this is not backwards compatible.
Be skeptical of the true value below as there are needed improvements to the benchmarking script. Use this as a relative performance indicator.
```
$ ./benchmark --filter wyhash --key-size 65535
wyhash
iterative: 15754 MiB/s [ac7dfbc737b3ee33]
small keys: 14744 MiB/s [c504fcf016bbda43]
```
```
$ ./benchmark --filter wyhash --key-size 65535
wyhash
iterative: 31050 MiB/s [a2ad8475e77f0a2a]
small keys: 28081 MiB/s [56f43308c6a8af3f]
```
---
Compared to the C reference we are slightly faster:
Our 16-48 byte keys however have worse performance however, which should be investigated but I wouldn't consider that a blocker.
---
Full measurements from my [smhasher …
> reimplement wyhash v4.1

- lib/std/fs.zig
The commit messages in a more readable format:
---
Allow recovering from `Walker.next` errors without continually hitting the same error
Before this commit, if Walker.next errored with e.g. `error.AccessDenied` and the caller did something like
```zig
var num_walked: u64 = 0;
while (true) {
const curr = walker.next() catch |err| switch (err) {
error.AccessDenied => continue,
else => |e| return e,
}
if (curr) |_| {
num_walked += 1;
} else {
break;
}
}
```
then the directory that errored with AccessDenied would be continually iterated in each `next` call and error every time with AccessDenied.
After this commit, the directory that errored will be popped off the stack before the error is returned, meaning that in the subsequent `next` call, it won't be retried and the Walker will continue …
> A few `IterableDir.Walker`/`Iterator` fixes

- src/AstGen.zig
- test/behavior/call.zig
This is kind of similar to 1a4b0d9. In this case, we need to handle ref_table when appending the body of param instructions.
Resolves: #15952
> AstGen: handle ref_table for params

- lib/std/os/plan9/x86_64.zig
We need to set rbp last because the arguments are stored on the stack. If we clobber rbp first, then we will get a segfault when trying to access the function arguments.
I believe I had already done this with the other syscall* functions, but not with syscall1, so this allows single argument syscalls like close to work.
> os/plan9: fix order of register setting in syscall1

- src/Sema.zig
- test/cases/compile_errors/muladd_int_vector.zig
Fixes #16013
The given test case now correctly outputs
```
error: expected vector of floats or float type, found '@Vector(1, u32)'
```
> Add a compiler error for `@mulAdd` with int vectors.

- lib/std/heap/arena_allocator.zig
- Previously, when the last buffer in `buffer_list` was retained after deleting all other buffers, `buffer_list` wasn't updated and pointed to a deleted buffer.
- Previously, when the user-provided a limit in `retain_with_limit` that was smaller than `@sizeOf(BufNode)`, `reset` would store a new `BufNode` in an allocation smaller than `BufNode`, leading to a buffer overrun.
cc @MasterQ32
> arena_allocator/reset: fix use after free, fix buffer overrun

- lib/std/mem.zig
Failing to forward free calls to the underlying allocator makes `ValidationAllocator` unusable for testing allocators while checking for leaks. This change allows allocators that wrap `std.testing.allocator` to be tested with `std.heap.testAllocator()` in test decls without reporting erroneous leaks.
> std.mem.ValidationAllocator: forward free() calls

- lib/std/Build/Step/CheckObject.zig
- test/link/macho/dead_strip/build.zig
- test/link/macho/dylib/build.zig
- test/link/macho/entry/build.zig
- test/link/macho/entry_in_dylib/build.zig
- test/link/macho/needed_library/build.zig
- test/link/macho/search_strategy/build.zig
- test/link/macho/stack_size/build.zig
- test/link/macho/strict_validation/build.zig
- test/link/macho/unwind_info/build.zig
- test/link/macho/weak_library/build.zig
Closes https://github.com/ziglang/zig/issues/14969
> Remove CheckObjectStep.runAndCompare

- lib/std/zig/system/NativePaths.zig
- src/Compilation.zig
resolves #13466
closes #15292 (alternative)
instead of adding all lib paths as an rpath implicitly when we are compiling for the Native OS, add NixOS lib paths to the rpath.
> Never implicitly add rpaths for each lib dir, add NixOS libdir to rpath

- lib/std/Build/Step/Run.zig
This flag allows run steps for foreign binaries to be skipped if the executor is not available.
There are two reasons I want this functionality:
- I have a project with multiple architectures targeted and want to enable qemu for running tests on foreign architectures, however not all architectures have a qemu binary available.
- Contributors should not be expected to have a wide selection of qemu binaries but any they do have should be utilized and the rest skipped.
> Allow run step to skip foreign binary execution if executor fails

- src/Sema.zig
- src/type.zig
- test/behavior/for.zig
- test/behavior/tuple.zig
- test/behavior/vector.zig
I promise I'm not trying to make a habit of implementing non-accepted proposals: I wrote this code as a fix for #14705, then while skimming the issue tracker for related bugs found that this implements #13852. In all honestly, I thought this was already an intended behavior, and I *think* that proposal should be fairly uncontroversial.
Resolves: #13852
Resolves: #14705
> Sema: allow indexing tuple and vector pointers

- src/Module.zig
- src/Sema.zig
- test/behavior/inttoptr.zig
Calling into coercion logic here is a little opaque, and more to the point wholly unnecessary. Instead, the (very short) logic is now implemented directly in Sema.
Resolves: #16033
> Sema: fix @intToPtr of zero value to optional pointer

- lib/std/target.zig
Since both consoles use standard x86_64 amd cpu, these should do the trick.
> target.zig adds ps4 and ps5 type sizes.

- lib/build_runner.zig
- src/main.zig
The motivating case for this is that currently when a test fails the CI log will include ~5k lines of listing steps that succeeded.
> zig build: add option to only print failed steps

- lib/std/os.zig
Missed this originally because I was only able to trigger it when SA_RESTART was missing from the sigaction handlers. I'm unconvinced this is actually a sane way for stdlib to behave (see #15664). But this does duplicate the existing behavior throughout os.zig which IMO should be prioritized here.
> add additional errno (INTR) to tcset,getpgrp calls

- src/arch/wasm/CodeGen.zig
- src/codegen.zig
- src/link/Wasm.zig
- test/behavior.zig
- test/behavior/bugs/1381.zig
- test/behavior/bugs/529.zig
This improves symbol resolution during incremental compilation mode where previously both externs and exports were not being resolved with existing global symbols. This PR ensures during `updateDeclExports` and `getOrPutImport` a symbol will be resolved if an existing symbol is found. The symbol resolution follows the same rules as the general symbol resolution for object files.
This also fixes 2 regressions caused by the `internpool` merge where a merge conflict resulted in undoing previous fixes.
> wasm/linker: symbol resolution improvements

- doc/langref.html.in
Previous commit has changed the filename from "introducing_zig_test.zig" to "testing_introduction.zig". Update the documentation to reflect the change.
> Change outdated filename in langref

- lib/std/Thread.zig
- lib/std/c/dragonfly.zig
- lib/std/c/freebsd.zig
- lib/std/c/openbsd.zig
- lib/std/fs.zig
- lib/std/os.zig
- lib/std/process.zig
with this PR:
- fixed getdents signature for freebsd, openbsd, dragonfly
- freebsd 13.2 passes `zig test lib/std/std.zig`
- openbsd builds stage3
tested on:
- freebsd 13.2, 13.1 (amd64)
- openbsd 7.3 (amd64)
- dragonfly 6.4
impact:
I don't foresee an impact on any tier1 platforms, each of the commits are special cased for the respective OS.
other note:
Unfortunately I do not have access to a solaris platform to test (and no luck with solaris x86 qemu guest), and `getdents` return type should be changed from `usize` → `c_int` .
> fix bad return types for BSDs getdents and debitrot openbsd

- doc/docgen.zig
- doc/langref.html.in
In order to fix #13280 I decided to simply remove line number from the shell output; personally I think they are not necessary.
In future I plan a refactoring as suggested in #13280.
I also found an unnoticed compiler error in one of the `docgen.zig` tests;  I think `docgen.zig` should be added in `test/standalone`.
> Fix issue 13280

- lib/compiler_rt/udivmod.zig
See https://reviews.llvm.org/D81809 for upstream description.
In summary this is ~10x improvement for small divisors and similar performance for equal divisors.
Closes #13523.
---
As a sanity, check, the below benchmark reinforces the visibly slow latency for small divisors:
```zig
const Timer = std.time.Timer;
var prng = std.rand.DefaultPrng.init(0);
const random = prng.random();
const loops = 20_000_000;
{
var timer = try Timer.start();
const start = timer.lap();
while (i < loops) : (i += 1) {
const a = random.int(u128);
const b = (random.int(u128) & 0xfff) + 1;
const s = a / b;
const r = a % b;
std.mem.doNotOptimizeAway(s);
std.mem.doNotOptimizeAway(r);
}
const end = timer.read();
const ns_per_iteration = …
```
> optimize udivmod

- lib/std/fs/test.zig
- lib/std/os/windows.zig
Justification: When a file is deleted on Windows, it may not be immediately removed from the directory. This can cause problems with future scans of that directory, which will see the partially deleted file. Under some workloads and system configurations, Windows files may appear to be deleted immediately.
This is the PR with requested fixup. Thanks to @SpexGuy for the original PR.
> std.windows: use posix semantics to delete files, if available

- CMakeLists.txt
- src/link/Elf.zig
Add enough support to enable building zig in netbsd's pkgsrc tree. PIE and RELRO are general requirements for their tree.
for PIE support, a cmake `ZIG_PIE` option is added which does two things:
1. builds `libzigcpp.a` with `-fPIC`
2. passes `-Dpie` to stage3 build args
for RELRO support, an old workaround's scope was too wide and is now narrowed to apply to dynamic libraries only. Side note, this unfortunately doesn't fix `ld.lld` to support RELRO dynamic libraries but the effect of this PR does allow zig to create PIE executables.
closes #14420
> netbsd: pkgsrc

- lib/std/http/Client.zig
- test/standalone/http.zig
Resolves #15965
Make to avoid releasing request's connection twice.
Change the `Request.connection` field optional. This field is null while the connection is released.
> std.http: Fix segfault while redirecting

- lib/std/math.zig
I would argue that the input of 0 can happen pretty often and mathematically it makes more sense to actually return false rather than assert that the input can't be 0. We're in `std.math`, not `std.fast`.
When trying to compile
```zig
export fn x() u0 {
return 0;
}
```
a debug crash happens only with a debug build of the compiler:
```
src/Sema.zig:23338:43: 0x9395c1 in explainWhyTypeIsNotExtern (zig)
.Int => if (!std.math.isPowerOfTwo(ty.intInfo(sema.mod.getTarget()).bits)) {
^
```
In the release build of the compiler it does compile-error as expected but takes the wrong compile error branch and thus still exhibits incorrect behavior because the `assert(v != 0)` is not there and so `isPowerOfTwo` returns true for 0. Cases like this exist elsewhere in the compiler too. Of course this is …
> std.math.isPowerOfTwo: return false for 0

- lib/std/fs/file.zig
- lib/std/os/windows.zig
This is a revival of #15282
Helps mitigate https://github.com/ziglang/zig/issues/15976 (and may be enough to warrant closing that issue if we're fine with the `.windows_api` `tty.Config` having slightly different behavior than `.escape_codes`, see the "Potential solutions" at the bottom of that issue)
---
From https://github.com/ziglang/zig/pull/15282#issuecomment-1556381417:
The new build runner means that on Windows the `SetConsoleTextAttribute` colors are not preserved when a test case fails. In combination with https://github.com/ziglang/zig/pull/13816 / https://github.com/ziglang/zig/pull/13723, this makes the output for `expectEqualSlices` much less useful.
With the changes in this PR, the colors *are* preserved (at least with Windows Terminal).
Before this PR:
After this PR:
> windows: detect ANSI support in more terminals

- lib/compiler_rt/divtc3.zig
- lib/compiler_rt/divtf3.zig
- lib/compiler_rt/fixtfti.zig
- lib/compiler_rt/fixunstfti.zig
- lib/compiler_rt/floattitf.zig
- lib/compiler_rt/floatuntitf.zig
- lib/compiler_rt/multc3.zig
- lib/compiler_rt/negtf2.zig
- lib/compiler_rt/powiXf2.zig
PPC targets can also use the functionality-equivalent standard routine, so unconditionally export the standard routine.
Fixup of #16054 merged in f043071cdfb956ff16b1441c9d01ce43eea9fb7b.
> compiler_rt: fixup exports of PPC routines

- test/src/Cases.zig
The runCases function incorrectly called the introspect.findZigLibDir function, causing a possible error, depending on the location of the local cache directory, since the current executable is check-case.
Use findZigLibDirFromSelfExe, passing the zig_exe_path argument.
The current CI scripts work correctly because ZIG_LOCAL_CACHE_DIR is set to "$(pwd)/zig-local-cache".
Fixes #15044
> test/src/Cases: fix incorrect code to find zig_lib_directory

- lib/std/json.zig
- lib/std/json/dynamic.zig
- lib/std/json/dynamic_test.zig
- lib/std/json/static.zig
- lib/std/json/static_test.zig
- lib/std/json/test.zig
- lib/std/json/write_stream.zig
- tools/gen_spirv_spec.zig
- tools/spirv/grammar.zig
- tools/update_clang_options.zig
- tools/update_cpu_features.zig
- tools/update_spirv_features.zig
This PR combines the dynamic `json.Parser` and the static `json.parse*()`. The bundled arena strategy from `ParseTree` is now available for all parsing via `json.parseFrom*()`. The old behavior is still available at `json.parseFrom*Leaky()` (name bikeshedding welcome on that one).
The `parseFree()` function is gone in favor of deinitting an arena instead. The main motivation for this was to allow customizable `jsonParse()` methods, and it was too hard to get customizable `jsonParseFree()` methods to work.
Uses of `parseFromSlice` or `parseFromTokenStream` (introduced in https://github.com/ziglang/zig/pull/15602 ) need to change.
1. If you're using your own arena allocator, call `parse*Leaky` instead.
2. Otherwise, the return value goes into a wrapper object that needs to be deinitted with …
> std: Support user-provided jsonParse method. Unify json.Parser and json.parse*

- lib/std/elf.zig
- src/objcopy.zig
This is 3 pull request combined:
- https://github.com/ziglang/zig/pull/15010 to get `zlib.compressStream`
- https://github.com/ziglang/zig/pull/14882 to get `zig objcopy` elf sections extraction
- https://github.com/ziglang/zig/pull/15011 to fix a failure in stage2 that gets exposed by using `deflate.compressor` in the compiler.
and one commit to actually implement the feature.
> objcopy: add support for --compress-debug-sections

- lib/std/fmt.zig
The error sets for a `FixedBufferStream.Writer` and the writer passed for `formatDuration` may be different, in particular when using `std.io.null_writer` the return type of `formatDuration` is `error{}!void` which previously caused a compile error. The fix is easy - we are guaranteed that none of the writes to the fixed buffer stream will fail, so we can just assert that there are no errors when writing to it.
> std.fmt: fix error set of formatDuration

- src/link/MachO/ZldAtom.zig
Fixes https://github.com/ziglang/zig/issues/15444
> macho: do not skip scanning relocs if the sym is non-extern

- src/InternPool.zig
- test/behavior/enum.zig
Fixes #16095
Previously the case of signed integers was ignored ignored as "out of range" for auto-numbered enums.
> Fix `@intFromEnum` and `@tagName` for auto-numbered enums with signed tag type

- src/type.zig
- test/behavior/fn.zig
- test/cases/compile_errors/function_parameter_is_opaque.zig
- test/cases/compile_errors/function_returning_opaque_type.zig
Opaque and `noreturn` make sense since they don't represent real values, but `null` and `undefined` are perfectly normal comptime-only values.
Closes #16088
> Type: remove arbitrary restrictions on param and return types

- src/Air.zig
- src/InternPool.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/arch/wasm/CodeGen.zig
- src/arch/wasm/abi.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/abi.zig
- src/codegen/c.zig
- src/codegen/c/type.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/link/Dwarf.zig
- src/type.zig
- src/value.zig
This is the current progress in my `InternPool` optimization branch.  Last I checked, it makes up for about half of the losses from `InternPool`.  Opening this now before it gets too out of date with master.
```
Benchmark 1 (122 runs): master/bin/zig build-exe --stack 33554432 src/main.zig --mod build_options::zig-cache/c/3fb6e89d536536de349edafc1438f486/options.zig --deps build_options -fno-emit-bin
measurement      mean ± σ               min … max                   outliers         delta
wall_time        4.924s ± 60.51ms       4.749s … 5.104s               5 ( 4%)        0%
peak_rss         428M ± 644K            426M … 429M                   0 ( 0%)        0%
cpu_cycles       24644932956 ± 40187532523641864552 … 25413638166     0 ( 0%)        0%
instructions     46260045656 ± 18645 …
```
> InternPool: various optimizations

- lib/std/http/Client.zig
The 'Content-Length' header was inspected by mistake, which makes it effectively impossible to use chunked Transfer-Encoding when using the http client.
Tested locally with a HTTP server - data is properly sent with POST method and the proper encoding declared, after the fix.
> http: fix getting Transfer-Encoding value

- src/objcopy.zig
Regular objcopy allows to copy empty sections this is an interface change. Please fix this.
> objcopy.zig allow outputting zero length sections

- lib/std/priority_dequeue.zig
LLVM has trouble compiling the old implementation, (presumably) because `leading_zeros` is thought to be a `u7` rather than a `u6`, which means `63 - clz` is not equivalent to `63 ^ clz`, which means it can't deduce that the final condition can simply be flipped. (I am assuming `usize` is a `u64` here for ease of understanding, but it's the same for any power of 2)
https://zig.godbolt.org/z/Pbj4P7ob3
The new version is slightly better too because `isMinLayer(maxInt(usize))` is now well-defined behavior.
> [priority_deque] simplify & optimize isMinLayer

- doc/docgen.zig
- lib/build_runner.zig
- lib/std/io/tty.zig
- test/src/StackTrace.zig
This PR adds `fn std.io.tty.detectConfigForce(File, bool) Config` which accepts an extra parameter to force coloring if the platform supports it. There are two code paths where `.no_color` will be returned: if the platform is wasi, or on windows if the `windows.kernel32.GetConsoleScreenBufferInfo()`  test fails - other options in this case could be to return an error, or `.escape_codes` (though this might be unexpected). If you want to force escape codes on wasi for some reason, you don't need to do TTY detection, just use `.escape_codes` directly.
> std.io.tty: cleanup detectConfig

- lib/std/sort.zig
(Firstly, I changed `n` to `b`, as that is less confusing. It's not a length, it's a right boundary.)
The invariant maintained is `cur < b`. In the worst case `2*cur + 1` results in a maximum of `2b`. Since `2b` is not guaranteed to be lower than `maxInt`, we have to add one overflow check to `siftDown` to make sure we avoid undefined behavior.
LLVM also seems to have a nicer time compiling this version of the function. It is about 2x faster in my tests (I think LLVM was stumped by the `child += @intFromBool` line), and adding/removing the overflow check has a negligible performance difference on my machine. Of course, we could check `2b <= maxInt` in the parent function, and dispatch to a version of the function without the overflow check in the common case, but that probably is not …
> [heapsort] Protect against integer overflow

- doc/langref.html.in
I am documenting this after struggling to figure out how to narrow error sets. I ended up finding the answer in the [Discord history](https://discord.com/channels/605571803288698900/1119291330410061935/1119291330410061935).
This is how the Error Set section looks like after the changes:
> Langref: Add example for catching only some errors and narrowing the error set

- src/codegen/llvm.zig
- src/codegen/llvm/bindings.zig
- src/zig_llvm.cpp
- src/zig_llvm.h
- test/cases/llvm/large_slices.zig
Fixes https://github.com/ziglang/zig/issues/16156.
The signature is `getOrCreateSubrange(int64_t  Lo, int64_t  Count)`, so this updates the bindings to match.
This fixes a crash in `lowerDebugTypeImpl` when analyzing slices that have a length of 2^32 or larger (up to `2^64 >> 3`, which still crashes, because above that the array size in bits overflows u64: https://github.com/ziglang/zig/issues/14627).
> llvm: fixup elem_count argument of ZigLLVMCreateDebugArrayType to be i64

- src/Sema.zig
- test/behavior/switch.zig
Fixes https://github.com/ziglang/zig/issues/16165
> sema: Fix overflow when analyzing an inline switch prong range that ends on the maximum value of the switched type

- src/Module.zig
- src/Sema.zig
Now that InternPool migration is finished, all values have types. So only the value parameter is required.
> sema.addConstant: remove type parameter

- lib/std/atomic/Atomic.zig
Removed an unnecessary "return switch" on the Atomic.store method
> Removed unnecessary return switch on void method

- lib/std/Build/Step/ConfigHeader.zig
- test/standalone.zig
- test/standalone/cmakedefine/build.zig
- test/standalone/cmakedefine/config.h.cmake
- test/standalone/cmakedefine/expected.h
Changes the implementation behind `cmakedefine` and `cmakedefine01` to match the actual cmake behavior.
Tested against https://github.com/Jan200101/cmakedefine-test, which can configure a test header against cmake, meson and zig.
The diff between the cmake and zig configured header with this PR
```patch
--- cmake_build/test.h  2023-06-14 22:55:53.531659521 +0200
+++ zig-cache/o/9dcd70028e62d4109280ca26a82c002c/config.h       2023-06-14 22:53:41.225032597 +0200
@@ -1,3 +1,4 @@
+/* This file was generated by ConfigHeader using the Zig Build System. */
// defined as "foo_content"
#define foo "foo_content"
@@ -46,3 +47,4 @@
// defined as 0, no value
#define nofoo 0
+
```
Currently only supports `@var@` substition and not `${var}`.
`@var@` substition is also implemented in a very messy way, …
> Correct cmakedefine implementation

- lib/std/zig/ErrorBundle.zig
Do `zig init-exe` and put something like
```zig
const x = [1]u8{
.{
`
},
};
```
in it and run `zig build`. You'll see:
```
zig build-exe x Debug native: error: the following command failed with 1 compilation errors:
/home/wooster/Desktop/zig-linux-x86_64/zig build-exe /home/wooster/Desktop/os/x/src/main.zig --cache-dir /home/wooster/Desktop/os/x/zig-cache --global-cache-dir /home/wooster/.cache/zig --name x --listen=-
Build Summary: 0/3 steps succeeded; 1 failed (disable with -fno-summary)
install transitive failure
└─ install x transitive failure
└─ zig build-exe x Debug native 1 errors
src/main.zig:2:11: error: expected expression, found 'invalid bytes'
.{
^
src/main.zig:3:13: note: invalid byte: '`'
`
thread 431336 panic: integer overflow …
```
> ErrorBundle: fix integer overflow printing caret

- src/Liveness.zig
I observed the llvm.memcpy elision to avoid the performance issue #12215 was no longer applied...
I reckon that's because there's an `unreach()` instruction after the call to panic , and the check introduced in  [25d3713b07a100d8fdb349317db97fd9d0c1e366] 
doesn't account for it.
so i've added some code to detect this case, and observed the debug performance is restored.
(caveat: I have no idea what I'm doing.. ^^ )
> fix array boundchecks performance regression (debug builds)

- lib/std/c/freebsd.zig
> std.c: freebsd fix typo for PROC.PROCCTL_MD_MIN constant.

- lib/std/c/darwin.zig
follow-up on ff59c45.
ref: https://github.com/ziglang/zig/blob/a5e15eced0e9cb00871966ede74eed9b3a07183c/lib/libc/include/any-macos-any/mach/host_info.h#L116
> std.c: fix host_basic_info definition for darwin.

- lib/std/fmt.zig
Fixes https://github.com/ziglang/zig/issues/10144 where calling fmt.parseInt() with explicitly set base incorrectly resulted in error.
> fix parseInt failing when a correct base is given

- lib/std/c/freebsd.zig
only variadic calls are prefixed with underscores.
ref: https://github.com/freebsd/freebsd-src/blob/59833b089e78463a561706fc03777249766aea01/sys/sys/capsicum.h#L326
> std.c: fix few capcisum api calls, following-up on 6ae19fa.

- src/main.zig
This PR addresses  #15549 :  ```zig cc -Wl,--version``` not understood by the linker
With this PR, ```zig cc``` and ```zig c++``` support ```-Wl,--version``` argument.
The expected output is to print
```
zig ld <build-version>
```
and exit.
> Support "--version" linker argument

- src/codegen/c.zig
- test/behavior/error.zig
Fixes https://github.com/ziglang/zig/issues/16186.
I believe this is the correct fix, based on the second part of this function (ie. the payload has runtime bits).
> cbe: fix crash caused by calling `mod.intValue` on `type_inferred_error_set`

- src/Compilation.zig
- src/main.zig
.res files are compiled Windows resource files that get linked into executables/libraries. The linker knows what to do with them, but previously you had to trick Zig into thinking it was an object file (by renaming it to have the .obj extension, for example).
After this commit, the following works:
zig build-exe main.zig resource.res
or, in build.zig:
exe.addObjectFile("resource.res");
Closes #6488 (first baby steps towards https://github.com/ziglang/zig/issues/3702)
---
Basic example of embedding an icon in a .exe so that it shows up in explorer:
> Recognize the .res extension and link it as if it were an object file

- src/wasi_libc.zig
`emmalloc.c` does a fair amount of type punning in order to access the size of memory regions and traverse them.
Unfortunately, that can lead to unwanted optimizations.
This simple test case currently triggers a memory fault:
```c
int main(void) {
char * volatile p = malloc(1);
p = realloc(p, 12);
p = malloc(1);
printf("%p\n", p);
}
```
Work around this by adding "-fno-strict-aliasing" when compiling that file.
> wasi-libc: compile emmalloc.c without strict aliasing

- lib/std/json.zig
Caught in https://github.com/ziglang/zig/pull/15981#issuecomment-1605097199 , I forgot to publish the new symbols in the top-level (mid-level?) json.zig so they can be accessed via `@import("std").json.<name>`.
> std: re-pub new json symbols in json.zig

- src/AstGen.zig
- test/cases/compile_errors/assign_local_bad_coercion.zig
- test/cases/compile_errors/break_void_result_location.zig
- test/cases/compile_errors/nested_error_set_mismatch.zig
- test/cases/compile_errors/union_init_with_none_or_multiple_fields.zig
Before:
assign_local_bad_coercion.zig:5:1: error: expected type 'u32', found 'u64'
export fn constEntry() u32 {
^~~~~~
assign_local_bad_coercion.zig:11:19: error: expected type 'u32', found 'u64'
var x: u32 = g();
~^~
After:
assign_local_bad_coercion.zig:6:21: error: expected type 'u32', found 'u64'
const x: u32 = g();
~^~
assign_local_bad_coercion.zig:11:19: error: expected type 'u32', found 'u64'
var x: u32 = g();
~^~
> AstGen: add source location to certain const initializers

- lib/std/c/freebsd.zig
following up on 4a0508e and 3dd0afe.
- kinfo_vmentry, removing kve_ prefix.
- kinfo_getproc, returns one entry at most.
> std.c: few freebsd's kinfo api fixes.

- doc/langref.html.in
- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- test/behavior/cast.zig
- test/cases/compile_errors/cast_without_result_type.zig
- test/cases/compile_errors/cast_without_result_type_due_to_generic_parameter.zig
- test/cases/compile_errors/nested_ptr_cast_bad_operand.zig
- test/cases/compile_errors/redundant_ptr_cast.zig
Two main things here:
* Add the ability for cast builtins to unwrap a layer of error union and/or optional from the result type. e.g. `@as(?MyEnum, @enumFromInt(123))` is now valid.
* Add a bunch of tests (both behavior and compile error).
> Follow-up to cast builtin result type inference

- src/Sema.zig
- src/value.zig
- test/behavior/comptime_memory.zig
Fixes crashes encountered while upgrading [capy](https://github.com/capy-ui/capy).
> Value: fix incorrect types returned from readFromMemory

- lib/std/array_hash_map.zig
I don't believe there's a requirement for this to take a pointer, as the underlying function doesn't. This should stop users from having to take a reference for no reason, and unify ArrayHashMap and ArrayHashMapUnmanaged's API.
> Change managed ArrayHashMap capacity method to take a non-pointer parameter

- build.zig
- lib/std/Build.zig
- lib/std/Build/Step/Compile.zig
- lib/std/Build/Step/InstallDir.zig
Closes #16187
I feel like this could benefit from a test, but I'm not sure how to get a `FileSource` directory in a platform-independent way to create a proper `standalone` test. I used the following "project" to test the behavior manually, but it depends on executing a shell script:
`build.zig`
```zig
pub fn build(b: *std.Build) !void {
const mkdir = b.addSystemCommand(&.{"./gendir"});
const src_dir = mkdir.addOutputFileArg("src");
b.installDirectory(.{
.source_dir = src_dir,
.install_dir = .prefix,
.install_subdir = "dest",
});
}
```
`gendir`
```shell
#!/bin/sh
set -e
mkdir "$1"
for i in `seq 9`; do
echo 'Hello, world!' >"$1/file$i"
done
```
If anyone has any advice on if/how to add a good test case for this, I would be happy to add one.
> Build: make `InstallDirStep` use a `FileSource`

- src/AstGen.zig
- test/behavior/array.zig
- test/cases/compile_errors/discarded_array_bad_elem_type.zig
> AstGen: fix result locations for elements of typed array init

- src/Sema.zig
- test/behavior/maximum_minimum.zig
> Sema: fix `@min`/`@max` type resolution with all runtime args

- lib/std/crypto/tls/Client.zig
Fixes this crash:
```
thread 429064 panic: index out of bounds: index 16406, len 15054
lib/std/crypto/tls/Client.zig:1064:38: 0x14078bb in readvAdvanced__anon_149933 (zig)
@memcpy(frag[first.len..][0..second_len], frag1[0..second_len]);
^
lib/std/crypto/tls/Client.zig:897:38: 0x14055f3 in readvAtLeast__anon_149932 (zig)
var amt = try c.readvAdvanced(stream, iovecs[vec_i..]);
^
lib/std/crypto/tls/Client.zig:858:24: 0x14053af in readAtLeast__anon_149931 (zig)
return readvAtLeast(c, stream, &iovecs, len);
^
```
Maybe related #15723
Reproduced from #15814
> crypto.tls.Client: fix occasional crash in `readvAdvanced`

- src/Air.zig
- src/Liveness.zig
- src/Liveness/Verify.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/print_air.zig
Previously, interned values were represented as AIR instructions using the `interned` tag. Now, the AIR ref directly encodes the InternPool index. The encoding works as follows:
* If the ref matches one of the static values, it corresponds to the same InternPool index.
* Otherwise, if the MSB is 0, the ref corresponds to an InternPool index.
* Otherwise, if the MSB is 1, the ref corresponds to an AIR instruction index (after removing the MSB).
Note that since most static InternPool indices are low values (the exceptions being `.none` and `.var_args_param_type`), the first rule is almost a nop.
> Air: store interned values in Air.Inst.Ref

- src/main.zig
gettext uses this version and, surely enough, it is supported by lld
> ld: support -version-script

- test/behavior/array.zig
Don't know when but it got fixed at some point. Here's test coverage.
Closes #15343
> behavior: test slicing array of zero-sized values

- lib/std/net.zig
- src/Sema.zig
- test/behavior/struct.zig
In
extern struct { x: u32, y: u16 }
we actually know that y's alignment is `@alignOf(u32)`, and not just `@alignOf(u16)`.
closes: #16134
> Sema: preserve extern struct field alignment

- lib/docs/index.html
- lib/docs/main.js
Closes #16081
The only preference implemented in this change is whether `/` can be used to focus the search bar (defaults to enabled for all browsers except Firefox), but others can be added later in a similar way. Preferences are stored in `localStorage` if available, but will still work for the current session if not.
> Autodoc: add preference for `/` search

- lib/std/crypto/sha2.zig
according to
https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=vpalignr&ig_expand=283,283,284,283,283&techs=AVX_ALL the vpalignr instruction requires AVX2 support
---
Context: I have an Intel J5005 CPU, which apparently supports .sha, but does not support .avx2 (or .avx). Without this patch, sha2 hashing crashes with "Illegal instruction" on this CPU:
```
~/src/zig/build % stage3/bin/zig test ../lib/std/std.zig --test-filter sha2               #910ad92e0e
Test [35/64] test.hmac sha256... Illegal instruction at address 0x33d25d
/home/lotheac/src/zig/lib/std/crypto/sha2.zig:260:56: 0x33d25d in round (test)
[w12_15] "x" (s_v[k + 3]),
^
/home/lotheac/src/zig/lib/std/crypto/sha2.zig:129:24: 0x31f8c6 in update (test)
d.round(b[off..][0..64]);
^ …
```
> std.crypto.hash.sha2: require avx2 on x86_64

- src/translate_c.zig
- src/translate_c/ast.zig
- test/translate_c.zig
Instead of converting a pointer to an int and then back to a pointer.
> translate-c: Use `@constCast` and `@volatileCast` to remove CV-qualifiers

- lib/std/builtin.zig
- lib/std/testing.zig
- src/codegen/spirv.zig
- test/behavior/c_char_signedness.zig
- test/behavior/call.zig
- test/behavior/comptime_memory.zig
- test/behavior/enum.zig
- test/behavior/maximum_minimum.zig
- test/behavior/ptrfromint.zig
This fixes a bunch of stuff that got broken.
- Fixes up some todos & errors from intern pool changes
- Enables a simplified panic handler, because we cannot print from spirv
- Disables prints in std.testing if the target does not support it.
- This still requires `.aggregate_init` to be implemented, so it does not really do anything for spir-v yet.
- Disables a bunch of new tests that fail (some of the reasons include the previous point).
> SPIR-V InternPool aftermath damage control

- lib/std/builtin.zig
- lib/std/os.zig
- src/codegen/llvm.zig
The panic handler expects that this value is represented with the generic address space, so cast the global to the generic addressspace before caching and returning the value.
Also attached is a commit that sets the default panic handler for amdhsa to one that does not crash.
> Some amdgcn fixes

- lib/std/c/haiku.zig
codePointer and subPath are not mandatory.
following up on 1084590
> std.c: fix haiku's find_path signature.

- lib/std/io/tty.zig
e05412669c8dde1230612de5af64fbc3fb0bc17e inadvertently changed the logic on Windows and made it so that supportsAnsiEscapeCodes was never checked. This fixes that regression while keeping the logic intact for other platforms.
Semi-related: https://github.com/ziglang/zig/pull/16080
cc @dweiller
> Fix `TTY.detectConfig` regression on windows

- lib/std/bounded_array.zig
This PR changes `BoundedArray`'s `len` field from a `usize` to a minimum-sized integer. If you're keeping a million of these in memory, their size can add up.
`BoundedArray(u8, 3)` used to take **16 bytes**, but now (with `len` stored as a `u2`) it only takes **4 bytes**.
Notes:
- `len` is the only type that changed. I left all the `usize` parameters alone, to not break existing code. A new test was added, and the old tests were not changed.
- The test is testing memory layout, which varies across targets, so I only let it run on x86_64. Not sure if that's the right approach?
- `@intCast` is sprinkled in. For each one, either the value had already checked before that point, or it's in an "assume" method.
- `appendNTimesAssumeCapacity` is an "assume" method, but it had an assert inside. Am …
> Smaller memory footprint for BoundedArray

- lib/std/math/big/int.zig
- lib/std/math/big/int_test.zig
- lib/std/math/big/rational.zig
- src/InternPool.zig
- src/Module.zig
- src/RangeSet.zig
- src/Sema.zig
- src/value.zig
All of the std except these few functions call it "eql" instead of "eq". This has previously tripped me up when I expected the equality check function to be called "eql" (just like all the rest of the std) instead of "eq".
The motivation is consistency.
If search "eq" on Autodoc, these functions stick out and it looks inconsistent.
I just noticed there are also a few functions spelling it out as "equal" (such as std.mem.allEqual). Maybe those functions should also spell it "eql" but that can be done in a future PR.
> std.math.big.int: better name for equal function

- lib/std/io/stream_source.zig
without this check zig assumes that UEFI has proper filesystem support which makes all of StreamSource non-functional when the other configs should work properly
> check for UEFI in io.StreamSource

- lib/std/Build/Step/Compile.zig
Commit c0b774fbc65e3e406a38d37b02fffda7c5d3df26 originally added this logic but it did not properly clear the C command line flags to empty when a previous positional argument had command line flags, because it never set the "previous" flag to true.
This fixes C compiler flags not being reset to empty when using the build system and a second positional argument has no arguments after a first positional argument has arguments.
Thanks to @squeek502 for finding this.
> std.Build.Step.Compile: fix clearing logic for empty cflags

- CMakeLists.txt
- lib/std/os/linux/thumb.zig
- lib/zig.h
- src/codegen/c.zig
- stage1/zig.h
* `CMakeLists.txt`: support the weird `uname -m` output.
* `CMakeLists.txt`: detect and use the C compiler's default arm mode.
* cbe: support gcc with both `f128` and `u128` emulated.
* std.os.linux.thumb: fix incorrectly passed asm inputs.
> bootstrap: support aarch64 in 32-bit mode

- lib/docs/main.js
- src/Autodoc.zig
- src/Zir.zig
Examples within the standard library where this change can be observed:
- `std.Thread.use_pthreads`
- `std.crypto.core.aes.has_hardware_support`
- `std.fs.need_async_thread`
In some of these, there seems to be a separate issue where `<match result>` is displayed for some fields, such as `target.os.tag`, which is part of a TODO in `tryResolveRefPath`.
Additionally, while I can't come up with any examples to the contrary, I'm slightly unsure about my assumption that the `Block` for the RHS of an `and` or `or` will always end in an `break_inline` or contain a single noreturn expression (such as `unreachable`) and hence walking the final instruction will reproduce the entire block. The approach taken for some other instructions that use a `Block` is to fall back on just rendering the source …
> Autodoc: implement boolean operations

- lib/std/mem/Allocator.zig
Take a look at the following code:
```zig
_ = allocator.create(u32) catch return;
_ = allocator.create(i32) catch return;
```
This is allocating two pieces of memory with the exact same size and alignment. Yet under the hood this generates two different functions, increasing the binary size and compile time. And now in the compiler there is 102 of these plus 125 calls to `alloc`.
Overall `800 kB` of zig's (debug) binary are wasted for allocator functions. That's `~2%` of the total size (measuring only zig functions).
In my own project it's even worse. Almost `10%` of the (debug) binary (excluding C functions) is filled with allocator functions.
Essentially I put all the common functionality from `allocAdvancedWithRetAddr` into a new function that is only generic over size and alignment: …
> Optimize `Allocator.allocAdvancedBla` to create less duplicate code for similar types.

- lib/std/http/Client.zig
- test/standalone/http.zig
This should solve the memory leak issue brought up in #16282.
> std.http: early return in pool release causing leaked connections

- lib/std/json/dynamic.zig
- lib/std/json/dynamic_test.zig
Calling `std.json.parseFromValue(std.json.Value, ...)` will yield the compile error below. Obviously it doesn't make sense to do this directly, but you can still encounter this indirectly through structs or generic code.
```
/opt/zig/0.11.0-dev.3932+17890f6b8/files/lib/std/json/static.zig:682:22: error: values of type 'anyopaque' must be comptime-known, but operand value is runtime-known
r.* = try internalParseFromValue(ptrInfo.child, allocator, source, options);
~^~
/opt/zig/0.11.0-dev.3932+17890f6b8/files/lib/std/json/static.zig:682:22: note: opaque type 'anyopaque' has undefined size
referenced by:
internalParseFromValue__anon_8402: /opt/zig/0.11.0-dev.3932+17890f6b8/files/lib/std/json/static.zig:635:53
internalParseFromValue__anon_7820: …
```
> add `jsonParseFromValue` to `std.json.Value`

- lib/std/json.zig
- lib/std/json/static.zig
- lib/std/json/static_test.zig
This PR addresses 2 issues with std.json:
1. The polymorphic parseByValue functions are inefficient for parsing json which are only partially polymorphic.
2. Parsing json with a streaming reader can cause use-after-free errors.
Imagine a json with this formatting:
```
{
"outer": {
"key1": {
// Large struct with known keys/values, including arrays and strings
},
"key2": {
// Same struct
},
// Many more unknown keys containing the same struct.
}
}
```
This json is partially polymorphic, because the "key1" keys aren't known at compile time. However, parsing this struct with the parseByValue method (parse the entire json into a Value, then reconstructing the inner structs) is inefficient, because it creates many more StringArrayHashMaps than needed. Ideally, we'd only want one …
> Add std.json.ParseOptions for more flexible json parsing

- lib/std/json.zig
- lib/std/json/hashmap.zig
- lib/std/json/hashmap_test.zig
- lib/std/json/static.zig
Inspired by @garrettlennoxbeck 's `JsonHashmap` here: https://github.com/garrettlennoxbeck/gotta_print_em_all/blob/7a2e79c10497c2a1f4cfad45bedb3eee628b8395/src/json.zig , this data structure can be used in the `parseFromSlice(T, ...)` system for objects that have arbitrary data keys rather than comptime known struct field names.
This PR also:
* exposes `innerParseFromValue` analogous to `innerParse` from https://github.com/ziglang/zig/pull/16312
* deletes unreachable "duplicate field" handling in `innerParseFromValue`.
* documents `parseFromValue`'s usage of the `options` object.
I ran into some of the same the trouble with `json.stringify` that @kristoff-it ran into here: https://github.com/ziglang/zig/blob/27a66191c271d2a8b1b6ebcbef0bbdeb8d389a38/src/Autodoc.zig#L948-L953
Potential …
> std.json: add generic hash map that parses/stringifies with arbitrary string keys

- src/type.zig
Fixes https://github.com/ziglang/zig/issues/16370.
> cbe: fix airIsNull to handle the `.ErrorSet` case when `optionalReprIsPayload` is false

- src/Sema.zig
- test/behavior/struct.zig
Closes #16148
Previously, the layout of a type used in a field in an anonymous struct was not guaranteed to be resolved, which triggered a failing assertion when trying to get the alignment of packed struct fields as part of executing `@typeInfo`.
This change fixes the resulting compiler crash for the example originally given in the linked issue, my additional reduced example (also added as a behavior test), and a larger project where I was running into this issue.
> Sema: resolve field type layout for anon struct type info

- lib/std/os/uefi.zig
- lib/std/os/uefi/protocols/absolute_pointer_protocol.zig
- lib/std/os/uefi/protocols/block_io_protocol.zig
- lib/std/os/uefi/protocols/edid_override_protocol.zig
- lib/std/os/uefi/protocols/file_protocol.zig
- lib/std/os/uefi/protocols/graphics_output_protocol.zig
- lib/std/os/uefi/protocols/hii_database_protocol.zig
- lib/std/os/uefi/protocols/hii_popup_protocol.zig
- lib/std/os/uefi/protocols/ip6_config_protocol.zig
- lib/std/os/uefi/protocols/ip6_protocol.zig
- lib/std/os/uefi/protocols/ip6_service_binding_protocol.zig
- lib/std/os/uefi/protocols/loaded_image_protocol.zig
- lib/std/os/uefi/protocols/managed_network_protocol.zig
- lib/std/os/uefi/protocols/managed_network_service_binding_protocol.zig
- lib/std/os/uefi/protocols/rng_protocol.zig
- lib/std/os/uefi/protocols/simple_file_system_protocol.zig
- lib/std/os/uefi/protocols/simple_network_protocol.zig
- lib/std/os/uefi/protocols/simple_pointer_protocol.zig
- lib/std/os/uefi/protocols/simple_text_input_ex_protocol.zig
- lib/std/os/uefi/protocols/simple_text_input_protocol.zig
- lib/std/os/uefi/protocols/simple_text_output_protocol.zig
- lib/std/os/uefi/protocols/udp6_protocol.zig
- lib/std/os/uefi/protocols/udp6_service_binding_protocol.zig
- lib/std/os/uefi/tables/boot_services.zig
- lib/std/os/uefi/tables/runtime_services.zig
- src/Sema.zig
- test/cases/compile_errors/invalid_variadic_function.zig
- test/cases/compile_errors/reify_type.Fn_with_is_var_args_true_and_non-C_callconv.zig
I tested this and this definitely compiles and these
changes were done programmatically but if there's still anything wrong
it shouldn't be hard to fix.
With this change it's going to be very easy to make further adjustments
to the calling conventions of all these external UEFI functions.
Closes #16309
> std.os.uefi: use std.os.uefi.cc instead of .C as calling convention

- lib/std/json/stringify.zig
- lib/std/json/stringify_test.zig
fixes #15859
This change wouldn't be necessary if #2971 was implemented, but until that happens, this will make using `std.json.stringify` on recursive structures easier to deal with.
> explicitly specify error set of `std.json.stringify`

- src/AstGen.zig
- test/cases/compile_errors/for_invalid_ranges.zig
Fixes #16311
The actual cause of #16311 is the `start_is_zero` special case:
```zig
const range_len = if (end_val == .none or start_is_zero)
end_val
else
try parent_gz.addPlNode(.sub, input, Zir.Inst.Bin{
.lhs = end_val,
.rhs = start_val,
});
```
It only happens if the range start is 0. In that case we would not perform any type checking. Only in the other cases coincidentally `.sub` performs type checking in Sema, but the errors are still rather poor:
```
$ zig test x.zig
x.zig:9:15: error: invalid operands to binary expression: 'Pointer' and 'Pointer'
for ("abc".."def") |val| {
~~~~~^~~~~~~
```
Note how it's the same as if I use `-`:
```
x.zig:9:11: error: invalid operands to binary expression: 'Pointer' and 'Pointer'
"abc" - "def";
~~~~~~^~~~~~~
```
Now after this PR, the errors are …
> AstGen: make sure `for` range start and end are usizes

- lib/std/multi_array_list.zig
I wasn't sure what naming convention to go by, so I picked `sortSpan`. Let me know if we should change that. I also add the ability to do unstable sorts, which is especially helpful at the moment given that we do not have a generic implementation of a stable sort.
> Add more sorting options to MultiArrayList

- src/codegen/llvm.zig
- test/standalone.zig
- test/standalone/zerolength_check/build.zig
- test/standalone/zerolength_check/src/main.zig
Originally, in WebAssembly, a zero-length `memory.copy` or `memory.fill` would [not result in a trap](https://github.com/WebAssembly/bulk-memory-operations/issues/97) for zero-length out-of-bounds operations. Unfortunately, that decision was reverted, and now any out-of-bounds memory operations regardless of length [will trap instead](https://github.com/WebAssembly/bulk-memory-operations/issues/124). [Attempts](https://github.com/WebAssembly/bulk-memory-operations/issues/145) were made to convince the committee to not trap on zero-length operations, but due to simplicity reasons, the status quo remains. 
The intended semantics of Zig is to not panic/UB for `@memcpy` and `@memset` when the length is 0. For this reason, this PR adds a safety check for the WebAssembly target to verify the …
> Emit check for memory intrinsics for WebAssembly

- src/Compilation.zig
- src/link/Coff/lld.zig
- src/link/Elf.zig
- src/link/Wasm.zig
- src/mingw.zig
closes https://github.com/ziglang/zig/issues/16379
and remove a leftover link to a closed issue.
> remove arbitrary stderr size limit when spawning a child process tool

- lib/std/os.zig
`std.os.sigprocmask` current accepts a `flags: u32`  parameter  which is passed to `system.sigprocmask`. However most implementations of `system` (either `std/c.zig` or `std/os/[platform].zig`) use a `c_int` for this argument. For example, when linking libc on linux, `std.c.sigprocmask` is used causing a compile error as `u32` cannot coerce to `c_int`.
This change is the minimal change that should make things work for all systems whose `sigprocmask` uses a 32 bit wide `flags` parameter - for any that don't, the current behaviour is already a compile error if they use a smaller type; this is a new compile error for a system that uses a flags parameter greater than 32bits wide.
> std.os.sigprocmask: @bitCast flags parameter

- src/Sema.zig
- test/cases/compile_errors/union_init_with_struct_as_first_param.zig
Found this while fixing #16383. The compiler crashes inside the unionFields function on line 2001 when the type given to the ```@unionInit``` builtin is not a union. https://github.com/ziglang/zig/blob/6bc9c4f716afbb15465f79f84f61221f394fa5b6/src/type.zig#L2000-L2004
This PR adds as check to ```zirUnionInit```which checks wether or not the given type is a union.
> Fixes crash when a struct is given as the first parameter to the unionInit builtin

- lib/std/array_list.zig
The 'at least' behavior of the Allocator interface was removed in #13666, so anything that used reallocAtLeast or the .at_least Exact behavior could still have doc comments that reference no-longer-true behavior.
Funnily enough, ArrayList is the only place that used this functionality (outside of allocator test cases), so its doc comments are the only things that need to be fixed. This was checked by resetting to deda6b514691c3a7ffc7931469886d0e7be2f67e (right before #13666 was merged) and searching for all instances of `reallocAtLeast` and `.at_least` (one of which would need to be used to get the `.at_least` behavior)
> docs: Fix outdated doc comments about allocating 'at least' the requested size

- lib/std/Build/Step/Compile.zig
- test/link.zig
- test/link/static_libs_from_object_files/build.zig
- test/link/static_libs_from_object_files/main.zig
I upgraded a build.zig for a c++ project, from zig 1.10 to master.
And got many errors of the form:
```
error: ld.lld: duplicate symbol: func()
note: defined at file.cpp:13 
note:            .../zig-cache/o/d2b46afbd2cd5d5c57e09b90cda4b76b/file_0.o in archive .../zig-cache/o/9f8d50303481988c02df2817264684bd/lib.a
note: defined at file.cpp:13 
note:            .../zig-cache/o/d2b46afbd2cd5d5c57e09b90cda4b76b/file_0.o
```
For context, the project is build by compiling a few static libraries, and then linking the libraries into an exe.
And instead of making each library directly from the source files (which exceeds the windows command line line, when cross compiling), batches of source files are instead compiled into a small number of object files, which are then combined into each library. …
> build: avoid repeating objects when linking a static library

- test/link/macho/dead_strip/build.zig
- test/link/macho/dylib/build.zig
- test/link/macho/entry/build.zig
- test/link/macho/entry_in_dylib/build.zig
- test/link/macho/needed_library/build.zig
- test/link/macho/search_strategy/build.zig
- test/link/macho/stack_size/build.zig
- test/link/macho/strict_validation/build.zig
- test/link/macho/unwind_info/build.zig
- test/link/macho/weak_library/build.zig
I noticed that when editing some of these tests, they weren't actually running their `CheckObject` steps. This change adds the missing `dependOn` calls.
> linker tests: add missing dependOn calls for CheckObject steps

- lib/std/Build/Step/CheckObject.zig
- lib/std/elf.zig
Dumping symtabs and relocs I will work out in a follow-up PR. For ELF it's a lot more interesting than other formats as depending on link context we can have more than 1 or even 2 symbol tables.
> std: add ELF parse'n'dump functionality to std.Build.Step.CheckObject

- lib/std/os/uefi/protocols/file_protocol.zig
previously complained about `[*]const u8` having alignment 1 and `[*:0]const u16` having alignment 2
> fix alignment error in uefi FileInfo protocol

- src/link/MachO/UnwindInfo.zig
If the last unwind info record was elided because it matched the preceding one, then the sentinel entry wouldn't take it into account. This change keeps track of the upper bound and use that instead of looking a the last added entry.
Question for @kubkon, are these records guaranteed to be sorted? ie. is `@max` needed?
For this code:
```
0000000000000380 <_frame1>:
380: 48 83 ec 28                   subq    $40, %rsp
... snip ...
41a: 66 0f 1f 44 00 00             nopw    (%rax,%rax)
0000000000000420 <_frame0>:
420: 48 83 ec 28                   subq    $40, %rsp
... snip ...
4bc: c3                            retq
Disassembly of section __TEXT,__cstring:
00000000000004bd <__cstring>:
4bd: 43 3a 5c 63 79                cmpb    121(%r11,%r12,2), %bl
4c2: 67 77 69                      ja …
```
> macho: fix __unwind_info sentinel entry not always being the upper bound

- lib/std/crypto/keccak_p.zig
- lib/std/crypto/sha3.zig
Just some very minor changes I'd noticed while using this:
- Semantic typo in KeccakF
- Typo in default delimiter for TurboShake256
- Recommendation to not use the same delimiter as K12 as per the paper
- Duplicate some useful docs as per doc comment guidance while this is already being changed
- Constrain security level and delimiter as per the paper
- Change URL ref to TurboSHAKE paper, now that it has its own
> std.crypto.sha3: Minor TurboSHAKE/Keccak fixes

- lib/std/linked_list.zig
`reverse` is the standard term for inverting the order of a collection, in the stdlib and in most other programming languages.
See: `std.mem.reverse`, `std.mem.reverseIterator`, [google searches](https://trends.google.com/trends/explore?date=all&q=%22reverse%20linked%20list%22,%22invert%20linked%20list%22&hl=en).
cc @Vexu, @pseudocc
> SinglyLinkedList: rename `invert` -> `reverse`

- doc/langref.html.in
- lib/std/crypto/chacha20.zig
0. Suggested the use of `std.crypto.utils.secureZero` under the docs for `@memset`, as an alternative that won't be optimized away for zeroing sensitive contents from memory;
1. Fixed copy-pasted segments on the documentation of ChaCha variants which stated the wrong number of rounds for certain variants;
That is all!
> Small documentation fixes on `std.crypto`

- lib/std/crypto/aes/soft.zig
- lib/std/crypto/md5.zig
- lib/std/crypto/sha1.zig
- lib/std/crypto/sha2.zig
And when we have the choice, favor little-endian because it's 2023.
Gives a slight performance improvement:
```
md5: 552 -> 555 MiB/s
sha1: 768 -> 786 MiB/s
sha512: 211 -> 217 MiB/s
```
> Replace hand-written endian-specific loads with std.mem.readInt*()

- lib/std/os.zig
The code removed does unnecessary copying in order to create a null-terminated pointer, just to pass it to libc getenv. It only does this for `small keys`, which are under 64 bytes in size.
Instead of going out of the way to add a null byte to a function that takes normal slices, this should just be handled by the loop below, which scans c.environ to find the variable's value
> getenv: remove unnecessary `small key` block

- src/Module.zig
- src/codegen/c.zig
Fixes a bootstrap bug hacked around in #16430
> cbe: fix pointers to aliases of extern values

- lib/std/Build/Step/CheckObject.zig
- lib/std/Build/Step/Compile.zig
- src/link/Wasm.zig
- src/link/Wasm/Atom.zig
- src/link/Wasm/Object.zig
- test/link/wasm/shared-memory/build.zig
- test/link/wasm/shared-memory/lib.zig
This fixes several bugs in the shared-memory implementation and adds TLS relocations which was the last component required to get the shared-memory linker feature fully working. 
With this PR, we can now use the self-hosted WebAssembly linker to link the threading example from: #16207 (i.e. appending `-fno-LLD` to the listed command).
> wasm-linker: finish shared-memory & TLS implementation

- lib/std/crypto/aegis.zig
It is assumed that generating a collision requires more than 2^156 ciphertext modifications. This is plenty enough for any practical purposes, but it hasn't been proven to be >= 2^256.
Be consistent and conservative here; just claim the same security as the other variants.
> Be more conservative in the description of Aegis256Mac

- lib/std/fmt/parse_float/convert_slow.zig
At the moment, the LLVM IR we generate for this fn is
```
define internal fastcc void @AstGen.numberLiteral ...  { Entry:
...
%16 = alloca %"fmt.parse_float.decimal.Decimal(f128)", align 8
...
```
That `Decimal` is huuuge! It stores
pub const max_digits = 11564;
digits: [max_digits]u8,
on the stack.
It comes from `convertSlow` function, which LLVM happily inlined, despite it being the cold path. Forbid inlining to not penalize callers with excessive stack usage.
Backstory: I was looking for needles memcpys in TigerBeetle, and came up with this copyhound.zig tool for doing just that:
https://github.com/tigerbeetle/tigerbeetle/blob/ee67e2ab95ed7ccf909be377dc613869738d48b4/src/copyhound.zig
Got curious, run it on the Zig's own code base, and looked at some of the worst offenders.
List of …
> reduce AstGen.numberLiteral stack usage

- lib/std/hash_map.zig
The only case where those should be written in camelCase is if they were function pointers, which they aren't.
> std.hash_map: Fix casing of keyPtr variables

- src/Compilation.zig
This is consistent with what clang and gcc are doing, because headers such as <cet.h> are specifically designed to be used in the context of assembly code.
Fixes #16449
> Include system headers path when targeting assembly_with_cpp

- src/Compilation.zig
Please refer to this issue https://github.com/ziglang/zig/issues/6573
This issue has been fixed in https://reviews.llvm.org/D118391, so we don't have a compiling error for arm-linux-musleabi in LLVM 16. So I am wondering if we unlock this limitation in zig, so we can start testing C++ for arm-linux-musleabi(hf) again.
> Unlock the SingleThread limitation for ARM

- lib/std/Build/Step/CheckObject.zig
- test/link/macho/dead_strip/build.zig
- test/link/macho/dead_strip_dylibs/build.zig
- test/link/macho/dylib/build.zig
- test/link/macho/entry/build.zig
- test/link/macho/entry_in_dylib/build.zig
- test/link/macho/headerpad/build.zig
- test/link/macho/linksection/build.zig
- test/link/macho/needed_framework/build.zig
- test/link/macho/needed_library/build.zig
- test/link/macho/pagezero/build.zig
- test/link/macho/search_strategy/build.zig
- test/link/macho/stack_size/build.zig
- test/link/macho/strict_validation/build.zig
- test/link/macho/unwind_info/build.zig
- test/link/macho/weak_framework/build.zig
- test/link/macho/weak_library/build.zig
- test/link/wasm/archive/build.zig
- test/link/wasm/basic-features/build.zig
- test/link/wasm/bss/build.zig
- test/link/wasm/export-data/build.zig
- test/link/wasm/export/build.zig
- test/link/wasm/extern-mangle/build.zig
- test/link/wasm/function-table/build.zig
- test/link/wasm/infer-features/build.zig
- test/link/wasm/producers/build.zig
- test/link/wasm/segments/build.zig
- test/link/wasm/stack_pointer/build.zig
- test/link/wasm/type/build.zig
Instead, we now have a looser helper called `checkContains(...)`
that will match on any occurrence similarly to `std.mem.indexOf()`.
While at it, I have cleaned up other combinators to make the entire
API more consistent, and so:
* `checkStart(phrase)` is now `checkStart()` followed by
`checkExact(phrase)`
* `checkNext(phrase)` if matching exactly is now `checkExact(phrase)`
* `checkNext(phrase)` if matching loosely is now `checkContains(phrase)`
* `checkNext(phrase)` if matching exactly with var extractors is now
`checkExtract(phrase)`
Finally, `ElfDumper` is now dumping contents of `.symtab` and `.dynsym`
symbol tables. I have also removed dumping of symtabs as optional - they
are now always dumped which cleaned up the implementation even more.
> std: dump .dynamic, .symtab, .dysym for ELF in `CheckObject`; remove wildcard matchers in favour of `checkContains` helper

- src/arch/wasm/CodeGen.zig
- test/behavior/cast_int.zig
When a signed integer's bitsize is not 32 or 64, but the given bitsize and wanted bitsize are either both represented by Wasm's i32 or i64, we must either sign extend or wrap the integer.
Fixes #16475
> wasm: correctly intcast signed integers

- src/codegen.zig
Both ways do the same thing but I think the compiler might have an easier time optimizing `appendNTimes` because it does less things/the path is shorter.
I have not done any benchmarking at runtime but have compared the instruction count of both ways a little here: https://zig.godbolt.org/z/vr193W9oj `b` (`appendNTimes`) is ~103 instructions while `a` (`writer().writeByteNTimes`) is ~117 instructions.
And looking at the implementation of `writeByteNTimes`, it only seems to buffer up 256 bytes before doing another `writeAll` which for `std.ArrayList` probably means another allocation, whereas when directly using `appendNTimes`, the entire exact additional capacity required is known from the start.
Either way, this would be more consistent anyway.
> codegen: `writer().writeByteNTimes` -> `appendNTimes`

- lib/std/zig/render.zig
Now `zig fmt` should do the job cleanly.
Previous commit that doesn't convert all of it: 283d65097
Reference: https://github.com/ziglang/zig/commit/be0c69957e7489423606023ad820599652a60e15
> fmt: convert @byteSwap

- build.zig
- ci/aarch64-linux-debug.sh
- ci/aarch64-linux-release.sh
- ci/aarch64-macos-debug.sh
- ci/aarch64-macos-release.sh
- ci/aarch64-windows.ps1
- ci/x86_64-linux-debug.sh
- ci/x86_64-linux-release.sh
- ci/x86_64-macos-release.sh
- ci/x86_64-windows-debug.ps1
- ci/x86_64-windows-release.ps1
- lib/std/Build/Step/Compile.zig
- src/Autodoc.zig
- src/Compilation.zig
- src/link.zig
- src/main.zig
* build.zig: introduce `-Dflat` option which makes the installation match what we want to ship for our download tarballs. This allows deleting a bunch of shell script logic from the CI.
- for example it puts the executable directly in prefix/zig rather than prefix/bin/zig and it additionally includes prefix/LICENSE.
* build.zig: by default also install std lib documentation to doc/std/
- this can be disabled by `-Dno-autodocs` similar to how there is already `-Dno-langref`.
* build.zig: add `std-docs` and `langref` steps which build and install the std lib autodocs and langref to prefix/doc/std and prefix/doc/langref.html, respectively.
* std.Build: implement proper handling of `-femit-docs` using the LazyPath system. This is a breaking change.
- this is a partial implementation of #16351 …
> move installation logic to the build script where it belongs

- lib/std/json/hashmap.zig
- lib/std/json/hashmap_test.zig
The ArrayHashMap Json parser added in #16366 does not propagate the `allocate` option added in #16312. This means that if a `Scanner` is used with `parseFromTokenSource*` function, use-after-free will occur with the keys, which will reference the Scanner's ephemeral buffer. This PR propagates this option, prevents keys from being freed if their allocation was intentional, and adds a test to demonstrate this behavior.
To see the issues the above behavior can cause, you can run the given test in `hashmap_test.zig` without applying the changes in `hashmap.zig`. The test will panic when attempting to access one of the keys, because the keys are now all `0xaa` after the scanner is invalidated, so no such key exists.
Please let me know if this solves the issue, or if this could cause other …
> Force key allocation in streaming json parsing

- lib/std/json/stringify.zig
Follow up to this comment: https://github.com/ziglang/zig/pull/16405#pullrequestreview-1541935139
This PR forces the safety checks mode to none in release fast and release small modes. I believe that with assertions being no-ops, this is pretty much equivalent to status quo, but with less memory.
> std.json.WriteStream: eliminate dead memory in optimized modes

- lib/std/heap.zig
- lib/std/json/static_test.zig
Updates `std.heap.FixedBufferAllocator` to skip ownership assertions at comptime. Adds a test that verifies this enables json parsing at comptime. Removes redundant (and ableist) language "sanity check" on an assertion.
I'm not totally clear on what the implications are of skipping the ownership assertions at comptime, but I think it's ok?
> std.json: support parsing json at comptime using FixedBufferAllocator

- lib/std/fs/test.zig
- lib/std/os/windows.zig
Using `FileDispositionInformationEx` (and therefore flags like `FILE_DISPOSITION_POSIX_SEMANTICS` and `FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE`) is only supported on NTFS, so the comptime Windows version range check is not enough to determine whether or not the `NtSetInformationFile` will succeed.
This commit makes `DeleteFile` always try using `FileDispositionInformationEx` first, but if `INVALID_PARAMETER` is received (which is the status that occurs when the filesystem doesn't support `FileDispositionInformationEx`), then it will fallback and try calling `NtSetInformationFile` with `FileDispositionInformation`.
This keeps NTFS as fast as it was before, since it will do at most 1 NtSetInformationFile call, but on non-NTFS filesystems (e.g. FAT32), DeleteFile will need to do 2 …
> windows.DeleteFile: Use FileDispositionInformationEx if possible, but fallback if not

- lib/std/http.zig
- lib/std/http/Server.zig
The `std.http.Server` test, "HTTP server handles a chunked transfer coding request", was out of sync with the Server implementation. Additionally we add Server to http.zig's tests so that the test will run when doing a `zig build test-std`.
If we rather not have this test run as part of the test-std that's totally cool, and we can amend this. However I think the test should still be updated to be functional as people use the tests as a form of documentation.
> Fix the http.Server test and add it to the set of tests in http.zig

- lib/std/zig/Parse.zig
Looks like the assert was copied from a few lines above without updating the target variable. This corrects that
> std.zig.Parse: Fix assert target

- lib/std/child_process.zig
- lib/std/os/windows.zig
This fixes a regression caused by https://github.com/ziglang/zig/pull/13993
As an optimization, the first call to `NtQueryDirectoryFile` would only ask for a single result and assume that if the result returned did not match the app_name exactly, then the unappended app_name did not exist. However, this relied on the assumption that the unappended app_name would always be returned first, but that only seems to be the case on NTFS. On FAT filesystems, the order of returned files can be different, which meant that it could assume the unappended file doesn't exist when it actually does.
This commit fixes that by fully iterating the wildcard matches via `NtQueryDirectoryFile` and taking note of any unappended/PATHEXT-appended filenames it finds. In practice, this strategy does not introduce a …
> child_process: Fix regression on Windows for FAT filesystems

- lib/std/os.zig
Partially addresses #16374 (see also #16492)
> os.renameatW: Handle OBJECT_NAME_COLLISION from NtSetInformationFile

- lib/std/os/windows.zig
This is possible when e.g. calling CreateSymbolicLink on a FAT32 filesystem.
---
In combination with #16492, #16498, and #16499, this is the last piece of the puzzle that will allow all the standard library tests to be run on a FAT32 filesystem without any failures.
```
E:\zigstd> zig test lib\std\std.zig --zig-lib-dir lib --main-pkg-path lib/std
2429 passed; 99 skipped; 0 failed.
```
> Handle `INVALID_DEVICE_REQUEST` in `std.os.windows.DeviceIoControl`

- build.zig
- lib/std/Build/Step/Compile.zig
- src/Compilation.zig
- src/main.zig
`-femit-analysis` used to do something with the old autodocs system. Now it does nothing.
As for `getOutputDocs`:
* Allow calling it multiple times.
* Rename it. Sorry, this is to coincide with https://github.com/ziglang/zig/issues/16353.
> CLI: delete dead option -femit-analysis and update -femit-docs buiild system API

- lib/std/crypto/Certificate.zig
This fixes #16515.
The original issue happens because the intermediate values in the vector lanes can overflow and incorrectly pass the checks. This fix widens the vector lanes such that overflow cannot happen in the intermediate results.
There's also a commit that changes the parameter type of `parseTimeDigits` so that it's more ergonomic to use and consistent with the parameter type of `parseYear4` (which accepts a pointer to array instead of a vector).
> std.crypto.Certificate: fix timedate parsing

- doc/langref.html.in
This behavior changed with https://github.com/ziglang/zig/issues/7147
> langref: update docs for ** and ++

- lib/std/os/linux/io_uring.zig
Fixes https://github.com/ziglang/zig/issues/14907
> io_uring: let the OS choose a free local port for all tests

- lib/std/mem/Allocator.zig
> add error when passing a non-single-item pointer to allocator.destroy

- lib/test_runner.zig
- test/standalone.zig
- test/standalone/child_process/build.zig
- test/standalone/child_process/child.zig
- test/standalone/child_process/main.zig
67d5bfef removed std.ChildProcess tests, suggesting to make them standalone instead. This commit does exactly that after the bug creating SIGPIPE in RealeaseFast is no more with LLVM 15.0.5.
Thanks to @x1ddos for the idea with the compile artifacts and PR improvements.
> test/standalone: reinstate std.ChildProcess tests

- lib/std/fmt/parse_float.zig
> re-enable test "fmt.parseFloat nan and inf" after llvm fix

- lib/std/zig/ErrorBundle.zig
This is another minor change but still makes a visual difference and will reduce the amount you have to scroll in your terminal by a little bit.
Reasoning:
1. The `for (0..src.data.reference_trace_len)` loop will run at least once due to the `src.data.reference_trace_len > 0` check above.
2. In all 3 branches of the `if` in that `for` it will print something.
3. The 3 strings of all of those prints already end in `\n`. Therefore, the extra `try stderr.writeByte('\n');` is unnecessary.
The extra newline looks like this by the way (it's the only empty line at the end):
```
$ zig test x.zig
x.zig:6:21: error: cast discards const qualifier
const x: []u8 = @ptrCast("a");
^~~~~~~~~~~~~
x.zig:6:21: note: use @constCast to discard const qualifier
referenced by:
test_0: x.zig:2:5
remaining …
```
> ErrorBundle: remove extra newline

- lib/std/c/darwin.zig
this makes them match decls in other OSes
the below test case fails on darwin, but succeeds on linux currently; merging this makes it pass on both.
```zig
const builtin = @import("builtin");
test {
try std.testing.expect(@hasDecl(std.os.SIG, "BLOCK"));
try std.testing.expect(@hasDecl(std.os.SIG, "UNBLOCK"));
try std.testing.expect(@hasDecl(std.os.SIG, "SETMASK"));
}
```
> darwin: drop underscore from SIG._{BLOCK,UNBLOCK,SETMASK}

- src/codegen/llvm.zig
- test/behavior/vector.zig
The special case to take advantage of llvm's intrinsic was generating invalid llvm ir:
```
Invalid bitcast
%60 = bitcast <2 x i2> %59 to i8, !dbg !3122
thread 145453 panic: LLVM module verification failed
```
> codegen/llvm: fix memset with vectors smaller than one byte

- src/Compilation.zig
- src/InternPool.zig
- src/main.zig
I found this useful when trying to optimize compile times (in https://github.com/ziglang/zig/pull/16538):
A section of example output:
```
allocBytesWithAlignment (4): 
allocBytesWithAlignment__anon_7903: ( InternPool.Key{ .int = InternPool.Key.Int{ .ty = InternPool.Index.u29_type, .storage = InternPool.Key.Int.Storage{ .u64 = 8 } } } )
allocBytesWithAlignment__anon_8077: ( InternPool.Key{ .int = InternPool.Key.Int{ .ty = InternPool.Index.u29_type, .storage = InternPool.Key.Int.Storage{ .u64 = 4 } } } )
allocBytesWithAlignment__anon_8481: ( InternPool.Key{ .int = InternPool.Key.Int{ .ty = InternPool.Index.u29_type, .storage = InternPool.Key.Int.Storage{ .u64 = 2 } } } )
allocBytesWithAlignment__anon_8483: ( InternPool.Key{ .int = InternPool.Key.Int{ .ty = InternPool.Index.u29_type, …
```
> Add --verbose-generic-instances to provide visibility on the number of generic function instantiations

- lib/std/Thread.zig
- lib/std/Thread/RwLock.zig
Adding RwLock to Thread.zig's list of tests resulted in a failure of `RwLock - smoke test` when running  `std-native-Debug-single`. This exposed an issue with `SingleThreadedRwLock.tryLockShared` where it would fail to count more than one shared lock.
This PR addresses the issue with tryLockShared, and ensures that RwLock's tests are run when testing the std-lib.
> std.Thread: Fix counting in SingleThreadedRwLock's tryLockShared

- src/link/MachO.zig
- src/link/MachO/Trie.zig
- src/link/MachO/zld.zig
- test/link.zig
- test/link/macho/bugs/16308/build.zig
- test/link/macho/bugs/16308/main.zig
> macho: create export trie root explicitly with Trie.init rather than implicitly on first Trie.put

- test/c_abi/cfuncs.c
- test/c_abi/main.zig
- test/tests.zig
This required disabling some failing tests. See #14908
> llvm: disable LTO on C ABI tests

- CMakeLists.txt
fix warning with cmake version 3.27.1
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
> build: update cmake_minimum_required to 3.5

- test/behavior.zig
- test/behavior/call_tail.zig
- test/behavior/defer.zig
- test/behavior/eval.zig
- test/behavior/packed-struct.zig
- test/behavior/ptrcast.zig
- test/behavior/switch.zig
- test/behavior/union.zig
closes #8487
closes #9703
closes #9871
closes #9912
closes #9914
closes #10196
closes #10591
> add behavior test coverage for stage1 issues

- src/codegen/llvm.zig
- test/c_abi/cfuncs.c
- test/c_abi/main.zig
These are needed for correctness. There's no reason to only add them for function pointers.
closes #16290
> LLVM: always add argument attributes to calls

- lib/std/child_process.zig
- lib/std/fs.zig
- lib/std/fs/file.zig
- lib/std/os.zig
- lib/std/os/windows.zig
- lib/std/zig/system/NativeTargetInfo.zig
When calling NtCreateFile with a UNC path, if either `\\server` or `\\server\share` are not found, then the statuses `BAD_NETWORK_PATH` or `BAD_NETWORK_NAME` are returned (respectively).
These statuses are not translated into `error.FileNotFound` because they convey more information than the typical FileNotFound error. For example, if you were trying to call `Dir.makePath` with an absolute UNC path like `\\MyServer\MyShare\a\b\c\d`, then knowing that `\\MyServer\MyShare` was not found allows for returning after trying to create the first directory instead of then trying to create `a\b\c`, `a\b`, etc. when it's already known that they will all fail in the same way.
---
The only other `NtCreateFile` call is in `ReadLink` but I made that translate `BAD_NETWORK_PATH`/`BAD_NETWORK_NAME` to …
> `windows.OpenFile`/`DeleteFile`: Add `NetworkNotFound` as a possible error

- src/AstGen.zig
- src/Sema.zig
- test/behavior/error.zig
This commit does two things which seem unrelated at first, but, together, solve a miscompilation, and potentially slightly speed up compiler perf, at the expense of making #2765 trickier to implement in the future.
Sema: avoid returning a false positive for whether an inferred error set is comptime-known to be empty.
AstGen: mark function calls as not being interested in a result location. This prevents the test case "ret_ptr doesn't cause own inferred error set to be resolved" from being regressed. If we want to accept and implement #2765 in the future, it will require solving this problem a different way, but the principle of YAGNI tells us to go ahead with this change.
Old ZIR looks like this:
%97 = ret_ptr()
%101 = store_node(%97, %100)
%102 = load(%97)
%103 = ret_is_non_err(%102)
New …
> frontend: make fn calls byval; fix false positive isNonErr

- lib/std/start.zig
At main startup, if the ELF auxiliary vector contains a stacksize value, use it as a hint for the minimum stacksize required by the executable.
1. Never lower the hard-limit. Once a hard-limit is lowered, then it can never be increased (including child processes).
2. If hint exceeds hard-limit then clamp hint to hard-limit.
3. If soft-limit exceeds hint then do nothing.
> linux: do not set stack size hard limit

- lib/std/Uri.zig
Zig's HTTP client breaks down when redirected to a URL with escaped query parameters. It seems to be doubly escaping them; this PR simply exempts the `%` character from being escaped in query parameters. I'm not sure if this will have unanticipated effects; we could also try a more complicated fix by looking ahead to see if the % in question is part of an escape sequence (and escaping it only if it's not).
> std.Uri: Don't double-escape escaped query parameters

- lib/std/fs.zig
- lib/std/fs/path.zig
- lib/std/os/windows.zig
Before this commit, there were three issues with the `makePath` implementation:
1. The component iteration did not 'collapse' consecutive path separators; instead, it would treat `a/b//c` as `a/b//c`, `a/b/`, `a/b`, and `a`.
2. Trailing path separators led to redundant `makeDir` calls, e.g. with the path `a/b/` (if `a` doesn't exist), it would try to create `a/b/`, then try `a/b`, then try `a`, then try `a/b`, and finally try `a/b/` again.
3. The iteration did not treat the root of a path specially, so on Windows it could attempt to make a directory with a path like `X:` for something like `X:\a\b\c` if the `X:\` drive doesn't exist. This didn't lead to any problems that I could find, but there's no reason to try to make a drive letter as a directory (or any other root path).
This commit …
> Add `fs.path.ComponentIterator` and use it in `Dir.makePath`

- lib/std/Build/Step/CheckObject.zig
- lib/std/debug.zig
- lib/std/dwarf.zig
- lib/std/dwarf/abi.zig
- src/Compilation.zig
- src/target.zig
- test/standalone.zig
- test/standalone/compiler_rt_panic/build.zig
- test/standalone/compiler_rt_panic/main.c
This partially solves https://github.com/ziglang/zig/issues/16474, but will not close it. 
Problem summary:
- `memcpy` came from compiler_rt, but had no unwind info
- Solved by setting `want_unwind_tables` on the compiler_rt sub-compilation if the main compilation had enabled `eh_frame_hdr`
- Debug symbols for compiler_rt were being stripped
- Solved by inheriting the `strip` flag from the parent compilation
- Enable `unwind_tables` by default on platforms that support DWARF unwinding
- This isn't strictly necessary (without this, we still get `.debug_frame` output). However, it's preferable to use `.eh_frame_hdr`/`.eh_frame` over `.debug_frame`, as lookups are improved (binary search table is built by the linker vs at runtime when we open the debug info). This also has the side effect of …
> Unwinding follow up: Don't strip compiler_rt symbols, enable unwind tables on supported platforms

- lib/std/zig/Ast.zig
- lib/std/zig/parser_test.zig
compiling the following source file will crash zig. (this is the entire file)
```zig
for (foo) |_| foo
```
or
```zig
while (foo) |_| foo
```
```
thread 74656 panic: integer overflow
/home/techatrix/Documents/zig/lib/std/zig/Ast.zig:2283:32: 0xcb6781 in fullForComponents (zig)
var tok_i = info.for_token - 1;
^
/home/techatrix/Documents/zig/lib/std/zig/Ast.zig:1948:34: 0xa8c45f in forSimple (zig)
return tree.fullForComponents(.{
^
/home/techatrix/Documents/zig/lib/std/zig/Ast.zig:2343:38: 0x8ba921 in fullFor (zig)
.for_simple => tree.forSimple(node),
^
/home/techatrix/Documents/zig/src/AstGen.zig:863:86: 0xccdcab in expr (zig)
.for_simple, .@"for" => return forExpr(gz, scope, ri.br(), node, tree.fullFor(node).?, false),
^
/home/techatrix/Documents/zig/src/AstGen.zig:1920:20: 0x10467f5 in …
```
> add bound check on for and while nodes

- doc/langref.html.in
`slice[i]` should assert `len > i`, not `len >= i + 1`.
I apologize for being nitpicky.
> Doc nitpick

- lib/std/start.zig
Removes the unused import tlcsprng
> std.start | Remove unused import

- lib/std/target.zig
Removes a comment referencing [#425](https://github.com/ziglang/zig/issues/425) which has been closed
> std.target | Remove comment referencing closed proposal

- lib/std/Build/Step/Run.zig
I can't reproduce this issue anymore after manually applying the diff.
Closes #14952
> Build: use optionals again

- src/main.zig
This mirrors the behavior of the progress indicator for the actual compilation. Not doing this was causing sporadic CI failures due to the (non-existent) fetches taking long enough to appear in stderr.
> package manager: don't show progress indicator on dumb terminals

- src/Sema.zig
- test/behavior/extern_struct_zero_size_fields.zig
- test/cases/compile_errors/exported_enum_without_explicit_integer_tag_type.zig
- test/cases/compile_errors/extern_struct_with_extern-compatible_but_inferred_integer_tag_type.zig
- test/cases/compile_errors/extern_struct_with_non-extern-compatible_integer_tag_type.zig
- test/cases/compile_errors/extern_variable_has_non_extern_type.zig
- test/cases/compile_errors/function_with_non-extern_non-packed_enum_parameter.zig
- test/cases/compile_errors/variadic_arg_validation.zig
Closes #16394. This change allows the following types to appear in extern structs:
* Zero-bit integers
* void
* zero-sized structs and packed structs
* enums with zero-bit backing integers
* arrays of any length with zero-size elements
> Allow zero-sized fields in extern structs

- lib/std/os/windows.zig
- lib/std/os/windows/ole32.zig
- src/windows_sdk.zig
The C++ version of this code used this logic, and it turns out it is able to find some setups that the current registry/Vs7 methods cannot.
For example, if only the "Build Tools for Visual Studio" are installed but not Visual Studio itself, then only the ISetupEnumInstances method seems to find it.
Follow up to #15657, fixes a regression caused by moving from the C++ version to the Zig version
---
Needs some testing for sure. I've only tested it on one setup with only the build tools installed so far.
Here's a build of `libc_only.exe` (detailed here: https://github.com/ziglang/zig/pull/15657#issuecomment-1556365709) if anyone wants to test their setup:
[libc_only-20230728.zip](https://github.com/ziglang/zig/files/12206448/libc_only-20230728.zip)
Otherwise, to test this, build this branch …
> windows_sdk.zig: Reinstate COM ISetupEnumInstances logic

- src/wasi_libc.zig
The referenced bug in LLD has been fixed:
https://reviews.llvm.org/D85567
> Remove obsolete comment in wasi_libc.zig

- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- test/behavior/packed-struct.zig
closes https://github.com/ziglang/zig/issues/16609
and partially addresses https://github.com/ziglang/zig/issues/15337
> packed struct fixes

- test/standalone/compiler_rt_panic/build.zig
Context: https://github.com/ziglang/zig/pull/16559#issuecomment-1657061004
> test: Fix missing _start symbol warning in the `compiler_rt_panic` test

- test/behavior/align.zig
The workaround in std.zig.Server remains because the C backend is not passing the new test.
see #14904
> add behavior test for sub-aligned field access

- lib/std/process.zig
> std.process.totalSystemMemory: return correct error type on FreeBSD

- lib/std/Build/Step/Compile.zig
- src/main.zig
Before:
-fLLVM, -fLLD, -fClang, -flibLLVM
-fno-LLVM, -fno-LLD, -fno-Clang, -fno-libLLVM
After:
-fllvm, -flld, -fclang, -flibllvm
-fno-llvm, -fno-lld, -fno-clang, -fno-libllvm
> CLI: stop special-casing LLVM, LLD, and Clang

- src/Sema.zig
- test/cases/compile_errors/call_from_naked_func.zig
- test/cases/compile_errors/return_from_naked_function.zig
- test/cases/compile_errors/unreachable_in_naked_func.zig
* pass a source location to all safety checks
* add notes about what is disallowed in naked functions
Turns
```
src/cpu/arch/x86/64/init.zig:483:17: error: runtime call not allowed in naked function
if (!has_error_code) {
^~~~~~~~~~~~~~~
```
into
```
src/cpu/arch/x86/64/init.zig:588:13: error: runtime safety check not allowed in naked function
unreachable;
^~~~~~~~~~~
src/cpu/arch/x86/64/init.zig:588:13: note: use @setRuntimeSafety to disable runtime safety
src/cpu/arch/x86/64/init.zig:588:13: note: the end of a naked function is implicitly unreachable
```
Closes #16651
> Sema: improve new error messages related to naked functions

- lib/std/Build/Step/Compile.zig
Without duping, users could get some unexpected behavior if they used a string with a lifetime that didn't persist throughout the full build, i.e. if it wasn't heap allocated, or if it was explicitly freed. All the other LazyPath APIs on Compile are duped.
> build: dupe library, rpath, and framework LazyPaths

- src/link/MachO/Object.zig
- src/link/MachO/UnwindInfo.zig
- src/link/MachO/ZldAtom.zig
- src/link/MachO/dead_strip.zig
- src/link/MachO/eh_frame.zig
- src/link/MachO/zld.zig
- test/link.zig
- test/link/macho/bugs/16628/a_arm64.s
- test/link/macho/bugs/16628/a_x64.s
- test/link/macho/bugs/16628/build.zig
- test/link/macho/bugs/16628/main.c
This solves the nuance case of compiling hand-crafted assembly files which do not feature `MH_SUBSECTIONS_VIA_SYMBOLS` flag resulting in input `Atom`s encompassing multiple symbols each with unique unwind information.
Closes #16628
> macho: track unwind/dwarf cfi records by symbol rather than atom

- src/libc_installation.zig
Reverts 4fa8cc736966544da381c90a6111158179fc550b. This check was added because it depended on C++ code, but after
77b96231a6bc195cc482d05599e8c20ee01645a6, this functionality no longer depends on C++ code.
This file is now independent from the rest of the compiler code and could be moved to the std.zig namespace if we wish.
cc @BratishkaErik :slightly_smiling_face:
> LibCInstallation: no longer depends on LLVM

- lib/std/target.zig
This was discussed in #16597. It makes sense for most of the functions in this file to be marked inline: many are simple helper functions so inlining is likely a strict win, and having the return values be comptime-known may improve userspace code in some cases by preventing it from unintentionally checking properties of the target at runtime.
This changeset is somewhat conservative: the functions marked inline are generally returning booleans or simple integers, and many are simple one-line checks.
> std.target: mark helper functions inline

- lib/std/Build/Step/Compile.zig
Found while updating https://github.com/fabioarnold/zig-gorillas/commit/cc7dc2c33fe2d1ee9e27d58d7cddc723a9e291e7
> Fix compile error in `addVcpkgPaths`

- lib/std/debug.zig
Before this commit, you could use readElfDebugInfo independently with one catch: the data is not freed since the deinitialization functions for ModuleDebugInfo are private. This change makes them public so the users of such function and similar can free the memory after the debug symbols have been used.
> debug: expose module debug info deinitialization

- CMakeLists.txt
This commit fixes CMake configuration error:
```
CMake Error at CMakeLists.txt:717 (elif):
Unknown CMake command "elif".
```
> cmake: Fix typo: elif → elseif

- src/Sema.zig
- test/cases/compile_errors/generic_method_call_invalid_coercion.zig
What does this code and/or comment mean anyway?  All I know is that it doesn't pass the test.
Closes #16601
> Sema: fix issues passing an invalid type to a generic method

- lib/std/testing.zig
When comparing slice elements, `std.meta.eql` is used which only compares pointer address and length to determine equality for pointer types. This previously led to confusing results where `expectEqualSlices` would appear to fail on seemingly equal slices (judging by the output of `expectEqualSlices`). For example:
```zig
try testing.expectEqualSlices(
[]const i64,
&[_][]const i64{ &[_]i64{ 1, 2, 3 }, &[_]i64{ 5, 5, 5 } },
&[_][]const i64{ &[_]i64{ 1, 2, 3 }, &[_]i64{ 5, 5, 5 } },
);
```
Previously, this would result in:
```
============ expected this output: =============  len: 2 (0x2)
[0]: { 1, 2, 3 }
[1]: { 5, 5, 5 }
============= instead found this: ==============  len: 2 (0x2)
[0]: { 1, 2, 3 }
[1]: { 5, 5, 5 }
================================================
```
After this commit, it …
> std.testing.expectEqualSlices: On failure, print address for pointer types

- src/codegen/llvm/Builder.zig
Seems that this was missed when migrating to the new builder.
This totally didnt break the example from the 0.11 release notes or anything.
> llvm: add const addrspace cast

- test/behavior/bugs/6305.zig
- test/behavior/cast.zig
- test/cases/compile_errors/comptime_dereference_slice_of_struct.zig
These were all bugs that caused the C++ implementation to crash or abort, but which are either valid Zig or properly handled errors in self-hosted.
I believe I captured the minimal reproductions accurately, but let me know if any of these is not the right type of test to satisfy closing the issues.
> Add test coverage for stage1 issues

- lib/std/json/stringify.zig
- lib/std/json/stringify_test.zig
std.json follows interoperability recommendations from RFC8259 to limit JSON number values to those that fit inside an f64.  However, since Zig supports arbitrarily large JSON numbers, this breaks roundtrip data congruence.
To appease both use cases, I've added an option `emit_big_numbers_quoted` to StringifyOptions.  It's disabled by default which preserves roundtrip but can be enabled to favor interoperability.
> std.json: fix roundtrip stringify for large integers

- lib/std/json/stringify.zig
- lib/std/json/stringify_test.zig
This improves upon #16239 and also enables stringifying raw enum literals.
> std.json: stringify enum literals

- src/codegen/llvm.zig
- src/codegen/llvm/Builder.zig
- src/codegen/llvm/bindings.zig
- src/value.zig
- src/zig_llvm.cpp
- src/zig_llvm.h
* finish converting intrinsics
* finish converting attributes
* finish converting instructions
* finish converting globals
* pass behavior tests with no dependence on the llvm api (`-fno-libllvm`)
> llvm: convert more things to use Builder

- src/Air.zig
- src/AstGen.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- src/type.zig
- test/behavior/array.zig
- test/behavior/call.zig
- test/behavior/struct.zig
- test/cases/compile_errors/anytype_param_requires_comptime.zig
- test/cases/compile_errors/error_in_typeof_param.zig
- test/cases/compile_errors/generic_method_call_with_invalid_param.zig
- test/cases/compile_errors/invalid_store_to_comptime_field.zig
- test/cases/compile_errors/splat_result_type_non_vector.zig
- test/cases/compile_errors/wrong_types_given_to_export.zig
- test/cases/compile_errors/zero-bit_generic_args_are_coerced_to_param_type.zig
- test/compile_errors.zig
See commit messages for details.
The final commit here has one small regression: the error return trace for `always_tail` calls isn't popped, so you could get a bogus line in your error return trace if a forced tail call returns an error and one of its parameters is an error set or union. The stars would really have to align to hit this in the wild, so it definitely seems like an acceptable regression for now since this PR otherwise fixes some real bugs.
The solution to that regression is probably to move the error tracing logic into `analyzeCall`, but that can be a future improvement.
> Fix RLS issues, fix crash on invalid result type for `@splat`, refactor some bits of generic instantiations

- lib/std/mem.zig
- src/Compilation.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/codegen/llvm/Builder.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/NvPtx.zig
- src/link/Wasm.zig
- src/type.zig
- test/behavior/optional.zig
With these changes, it is now possible to compile the llvm backend even without llvm linked.  There is a lot of work to make this generally useful, but it is already capable of performing `-fno-libllvm -fno-emit-bin -fstrip --verbose-llvm-ir=output.ll` without any external help.  Compiling the behavior tests to an ll file and then using llvm to finish the compilation separately produces a binary that passes all tests.
> llvm: enable the backend even when not linked to llvm

- lib/std/fs.zig
- lib/std/fs/test.zig
`.filter = .any` can be used here to remove an unnecessary extra OpenFile call when getting the path of a directory
The relevant test case was improved to explicitly test a directory path, but the functionality of `realpathW` is unchanged (the updated test would have passed before this commit as well).
> `fs.Dir.realpathW`: Reduce the number of OpenFile calls for directories

- lib/std/Build.zig
If I try to build a dependency with different arguments today, only one version of that dependency is built, when it should build every variant. Here's a simplified example, I've imported the `echo` dependency twice, but in each scenario I've specified the dependency with different optimization modes.
```zig
// build.zig
const dep_variant_1 = b.dependency("echo", .{
.optimize = .Debug,
});
const dep_variant_2 = b.dependency("echo", .{
.optimize = .ReleaseSafe,
});
```
I'll now write a program to print the value returned by `get_optimization()` in the `echo` static library of the `echo` dependency, and compile it twice, each using one of the dependency variants:
```zig
// build.zig continued...
const program_variant_1 = b.addExecutable(.{
.name = …
```
> Compare user input for multiple dependency build variants

- src/Sema.zig
- test/behavior/vector.zig
as explainded at https://llvm.org/docs/LangRef.html#vector-type :
"In general vector elements are laid out in memory in the same way as array types. Such an analogy works fine as long as the vector elements are byte sized. However, when the elements of the vector aren’t byte sized it gets a bit more complicated. One way to describe the layout is by describing what happens when a vector such as <N x iM> is bitcasted to an integer type with N*M bits, and then following the rules for storing such an integer to memory."
"When <N*M> isn’t evenly divisible by the byte size the exact memory layout is unspecified (just like it is for an integral type of the same size)."
closes https://github.com/ziglang/zig/issues/16588
> Sema: fix coerceArrayLike() for vectors with padding

- lib/std/http/Server.zig
The server tries to use the Content-Length header to get the transfer encoding instead of the Transfer-Encoding header, leading to a null dereference when using `Transfer-Encoding: chunked`
> std.http.Server: use correct header for Transfer-Encoding

- src/Module.zig
- src/Sema.zig
After ff37ccd, interned values are trivial to convert to Air refs, using `Air.internedToRef`. This made functions like `Sema.addConstant` effectively redundant. This commit removes `Sema.addConstant` and `Sema.addType`, replacing them with direct usages of `Air.internedToRef`.
Additionally, a new helper `Module.undefValue` is added, and the following functions are moved into Module:
* `Sema.addConstUndef` -> `Module.undefRef`
* `Sema.addUnsignedInt` -> `Module.intRef` (now also works for signed types)
The general pattern here is that any `Module.xyzValue` helper may also have a corresponding `Module.xyzRef` helper, which just wraps the call in `Air.internedToRef`.
> Sema: remove redundant addConstant functions

- src/AstGen.zig
- src/Zir.zig
- test/cases/compile_errors/invalid_coercion_in_aggregate_literal.zig
- test/cases/compile_errors/invalid_coercion_in_labeled_break.zig
- test/cases/compile_errors/invalid_if_expr_result_location_coercion.zig
- test/cases/compile_errors/invalid_switch_expr_result_location_coercion.zig
For every single creation of an `.as` instruction in `AstGen.zig`, I was able to find a corresponding error message with a horrible source location that resulted.  This PR comes close to replacing every single one with an `.as_node` instruction, and I would have gotten away with it too, if it weren't for you [meddling *break*s](https://github.com/ziglang/zig/blob/5e0107fbce8f33f84af232c3edc912a81615175f/src/Zir.zig#L2348)!
Closes #12509
```
test/cases/compile_errors/invalid_if_expr_result_location_coercion.zig:3:28: error: type 'u8' cannot represent integer value '256'
const result: u8 = if (cond) invalid else 0;
^~~~
test/cases/compile_errors/invalid_if_expr_result_location_coercion.zig:8:26: error: type 'u8' cannot represent integer value '256'
const invalid: u16 = 256;
^~~ …
```
> AstGen: create more `@as` with source locations

- README.md
The README contains a typo stating 'zig/lib/' and '../zig/lib/' as the lib search paths. This should be 'lib/zig' and '../lib/zig'.
> Fix incorrect lib search paths in README

- lib/std/Build/Step/ObjCopy.zig
- src/objcopy.zig
example usage:
```
if (!strip) {
b.installArtifact(exe);
} else {
const stripped_exe = b.addObjCopy(exe.getEmittedBin(), .{
.basename = exe.out_filename, // set the name for the debuglink
.compress_debug = true,
.strip = .debug_and_symbols,
.extract_to_separate_file = true,
});
b.getInstallStep().dependOn(&b.addInstallBinFile(stripped_exe.getOutput(), exe.out_filename).step);
b.getInstallStep().dependOn(&b.addInstallBinFile(stripped_exe.getOutputSeparatedDebug().?, b.fmt("{s}.debug", .{exe.out_filename})).step);
}
```
> build/ObjCopy: strip debug info to a separate elf file

- lib/std/child_process.zig
- lib/std/dynamic_library.zig
- lib/std/fs.zig
- lib/std/fs/test.zig
- lib/std/os.zig
- lib/std/os/windows.zig
- lib/std/os/windows/test.zig
Previously, a relative path like `..` would:
- Attempt to be normalized (i.e. remove . and .. without any path resolution), but would error with `TooManyParentDirs`
- This would make wToPrefixedFileW run it through `RtlGetFullPathName_U` to do the necessary path resolution, but `RtlGetFullPathName_U` always resolves relative paths relative to the CWD
Instead, when `error.TooManyParentDirs` occurs, we now look up the path of the passed in `dir` (if it's non-null) and append the relative path to it before giving it to `RtlGetFullPathName_U`. If `dir` is null, then we just give it `RtlGetFullPathName_U` directly and let it resolve it relative to the CWD.
Closes #16779
---
Before this PR, the added test would have failed with something like:
```
====== expected this output: ========= …
```
> Windows: Fix `TooManyParentDirs` handling for paths that shouldn't be cwd-relative

- src/libunwind.zig
Trying to cross compile zig for a target that needs libunwind can lead to a situation where zig tries to link libunwind without linking libcpp. Since libunwinds sources include the stdlib.h header this can lead to the __availability being also included but without  _LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS preprocessor directive being defined when cross compiling for targets like SerenityOS. See error description in https://github.com/SerenityOS/serenity/pull/20241 .
This PR ensures that libcpp is also linked as soon as libunwind is used.
> libunwind: Remove include for libcxx as its also done in upstream llvm repo

- lib/std/Build/Cache.zig
- lib/std/Build/Step/Run.zig
Closes #16040
Tested with a simple example program that outputs one target in the `.d` file, however I think we don't need to limit to a single target anymore. For example in the case of asset processors, as cited in the issue.
> std.Build: add support for deps .d file in Step.Run

- lib/std/Build.zig
- lib/std/Build/Step.zig
Not sure this is the best way to do it, but I faced a usecase where I needed more stack frames, and `first_ret_addr` is less practical.
Also unsure about the added output, but I think it's best to inform the user that stack traces _could_ be printed via a setting.
The number of stack frames being just a builder variable, it can change during build execution so no assumption that stack traces are present can be made. We could probably make it static in the program via the `@import("root")` mechanism but I don't know how to use it in a build context.
> std.Build: make number of collected stack frames configurable

- lib/std/dwarf/call_frame.zig
Thanks to @jacobly0 for finding this one!
main.zig:
```
pub fn main() void { @trap(); }
```
Before:
```
$ zig run main.zig -ofmt=c
Illegal instruction at address 0x21a694
/home/kcbanner/.cache/zig/o/f2420382f0eadd063c1653d1468fdd5d/main.c:6998:2: 0x21a694 in main_main__147 (/home/kcbanner/.cache/zig/o/f2420382f0eadd063c1653d1468fdd5d/main.c)
zig_trap();
^
Panicked during a panic. Aborting.
Aborted
```
After:
```
$ zig run main.zig -ofmt=c
Illegal instruction at address 0x21a674
/home/kcbanner/.cache/zig/o/f2420382f0eadd063c1653d1468fdd5d/main.c:6998:2: 0x21a674 in main_main__147 (/home/kcbanner/.cache/zig/o/f2420382f0eadd063c1653d1468fdd5d/main.c)
zig_trap();
^
/home/kcbanner/.cache/zig/o/f2420382f0eadd063c1653d1468fdd5d/main.c:6558:2: 0x218eb3 in start_posixCallMainAndExit__133 …
```
> dwarf: add missing length check in rowColumns

- src/Sema.zig
- test/cases/compile_errors/panic_has_source_location.zig
The panic handler decl_val was previously given a `unneeded` source location, which was then added to the reference trace, resulting in a crash if the source location was used in the reference trace. This commit makes two trivial changes:
* Don't add unneeded source locations to the ref table
* Pass a real source location when analyzing the panic handler
> Sema: provide source location when analyzing panic handler

- lib/std/json/scanner.zig
- lib/std/json/scanner_test.zig
- lib/std/unicode.zig
Before this PR, there were 524,288 codepoints that would get decoded improperly (starting with codepoint U+20000). After this PR, there will be 0.
Fixes #16828
Note: It's possible that the 'decode into a single u21' aspect of the JSON implementation could have been retained while fixing this, but I think the approach taken in this PR makes the code more understandable and there's no real reason the JSON stuff should have it's own version of UTF-16 decoding logic separate from `std.unicode`.
---
Exhaustively tested against the full unicode range with this code:
<details>
```zig
fn testCodepoint(input: []const u8, expected_utf8: []const u8) !void {
var stream = std.io.fixedBufferStream(input);
var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
defer …
```
> std.json: Fix decoding of UTF-16 surrogate pairs

- lib/std/coff.zig
- lib/std/debug.zig
- debug: support looking up debug symbols in both PDB and DWARF debug info, instead of only using DWARF if `.debug_info` is present
- coff: support reading from the image loaded by the loader or file data
Before these changes, if the `.debug_info` section was present in a COFF binary, then only the DWARF debug info present in the binary was used for symbol lookup. This is problematic if only some of the debug info is present in the DWARF sections, and the rest is in a PDB. 
Now, both DWARF and PDB debug information is used. PDB is preferred, and lookups fall back to checking the DWARF info if it's present.
I also made some fixes to the COFF parser - some functions assumed the backing data was from the memory-mapped image as loaded by the loader (and so virtual addreses were used), while …
> Windows: Support loading debug symbols from both the PDB file and embedded DWARF information

- src/translate_c.zig
- test/run_translated_c.zig
This addresses 2 issues revealed in #16838:
1. Don't treat zero-size/empty arrays as flexible members if they're not the last field in a struct
2. Don't crash if the flexible array member is a typedef type.
> Translate-c: better flexible array member handling

- src/link/MachO/Object.zig
- test/link.zig
- test/link/macho/reexports/a.zig
- test/link/macho/reexports/build.zig
- test/link/macho/reexports/main.c
This is in particular very important to the Zig language which allows exporting the same symbol under different names. For instance, it is possible to have a case such that:
```
...
4258 T _foo
4258 T _bar
...
```
In this case we need to keep track of both symbol names when resolving FDEs and unwind records.
Closes #16751
> macho: tie FDEs and unwind records to all symbol aliases, not just the first global

- lib/std/Build.zig
When using `std.Build.dependency` with target options, dependencies
would sometimes get targets which are equivalent but have distinct
names, e.g. `native` vs `native-native`. This is a somewhat broad issue,
and it's unclear how to fix it more generally - perhaps we should
special-case CrossTarget in options passing, or maybe targets should
have a canonical name which we guarantee to use everywhere aside from
raw user input.
However, this commit fixes the most egregious issue, which was an active
blocker to using the package manager for some users. This was caused by
the CPU changing from `native` to a specific descriptor (e.g.
`skylake+sgx`), which then changed the behavior of `zigTriple`.
Resolves: #16856
> std.Build: check for native CPU when serializing CrossTarget

- src/Autodoc.zig
The previous logic was using `root_src_directory` both in constructing the resolved path and as the root when opening the resolved path, which effectively duplicates those path components in the final path.
> Autodoc: fix guide path resolution

- lib/std/c/dragonfly.zig
- lib/std/c/netbsd.zig
- lib/std/debug.zig
- lib/std/dwarf/abi.zig
- lib/std/fs/test.zig
Advance the state of various BSDs ports on x86_64 to be able to build stage3 and pass `zig test lib/std/std.zig`:
- netbsd 9.3
- openbsd 7.3
- dragonfly 6.4
- freebsd 13.2 (wasn't broken but tested anyways)
> de-bitrot the BSDs

- lib/std/fs.zig
- lib/std/fs/test.zig
- lib/std/os.zig
- lib/std/os/test.zig
- lib/std/os/windows.zig
This PR changes many tests in `fs/test.zig` to use a helper that will run the test code for each path type that is supported on the target.
For example:
```zig
test "openDir" {
try testWithAllSupportedPathTypes(struct {
fn impl(ctx: *TestContext) !void {
const subdir_path = try ctx.transformPath("subdir");
try ctx.dir.makeDir(subdir_path);
for ([_][]const u8{ "", ".", ".." }) |sub_path| {
const dir_path = try fs.path.join(testing.allocator, &[_][]const u8{ subdir_path, sub_path });
defer testing.allocator.free(dir_path);
var dir = try ctx.dir.openDir(dir_path, .{});
defer dir.close();
}
}
}.impl);
}
```
- When targeting WASI, this will only run the function once with the `relative` path type
- On Linux, it will run twice with both the `relative` and `absolute` path type
- On Windows, it …
> `std.fs`: Improve tests and fix some bugs that were uncovered

- src/InternPool.zig
- src/Module.zig
- src/Sema.zig
- src/TypedValue.zig
- src/codegen/llvm.zig
- src/link/Dwarf.zig
- src/type.zig
- src/value.zig
The key changes in this commit are:
```diff
-        names: []const NullTerminatedString,
+        names: NullTerminatedString.Slice,
-        values: []const Index,
+        values: Index.Slice,
```
Which eliminates the slices from `InternPool.Key.EnumType` and replaces them with structs that contain `start` and `len` indexes. This makes the lifetime of `EnumType` change from expiring with updates to InternPool, to expiring when the InternPool is garbage-collected, which is currently never.
This is gearing up for a larger change I started working on locally which moves union types into InternPool.
As a bonus, I fixed some unnecessary instances of `@as`.
> InternPool: safer enum API

- lib/std/fs/test.zig
In theory, localhost could be mapped to a different address via the LMHOSTS file, so using 127.0.0.1 should remove that potential wrinkle and allow the drive-absolute -> UNC transformation to work on any(?) setup.
Also print the error name to ensure it gets printed in CI (aarch64-windows ReleaseSmall seemed not to print the error in the last intermittent UNC failure)
---
Follow up to https://github.com/ziglang/zig/pull/16847. This is probably pretty unlikely to address the failure observed here: https://github.com/ziglang/zig/pull/16847#issuecomment-1682909498 but I think this is overall a slight improvement and will make any future failures slightly more debuggable.
> fs tests: Use 127.0.0.1 instead of localhost as the server in UNC transformation

- build.zig
- lib/std/Build/Step/CheckObject.zig
- lib/std/Build/Step/Compile.zig
- lib/std/macho.zig
- src/main.zig
- test/standalone.zig
- test/standalone/ios/build.zig
- test/standalone/ios/main.m
- test/tests.zig
Prior to this change, we would unconditionally emit any system include path/framework path as `-iwithsysroot`/`-iframeworkwithsysroot` if the sysroot was set which can lead to unexpected build failures. Now, calls to `b.addSystemIncludePath` and `b.addFrameworkPath` will always emit search paths as `-isystem`/`-iframework`. As a result, it is now up to the user to correctly concat the search paths with the sysroot when and where desired.
If there is a need for emitting `-iwithsysroot`/`-iframeworkwithsysroot` I would advise adding explicit hooks such as `addSystemIncludePathWithSysroot` and `addFrameworkPathWithSysroot`.
While at it, disambiguate includes with sysroot in `ClangSearchSanitizer`. This noninvasive change improves warning messages for mixing up paths between `-iwithsysroot` …
> build: do not emit `-iwithsysroot`/`-iframeworkwithsysroot` implicitly

- lib/std/os.zig
- lib/std/os/windows.zig
- lib/std/zig/system/NativeTargetInfo.zig
From https://github.com/ziglang/zig/pull/16568:
> The only other `NtCreateFile` call is in `ReadLink` but I made that translate `BAD_NETWORK_PATH`/`BAD_NETWORK_NAME` to `error.FileNotFound`. I'm unsure about that decision.
This will make `ReadLink` match how the other filesystem functions were made to handle `BAD_NETWORK_PATH`/`BAD_NETWORK_NAME` in https://github.com/ziglang/zig/pull/16568. ReadLink was previously the odd one out, but that will no longer be the case.
> Add NetworkNotFound to ReadLinkError

- lib/std/fs.zig
- test/standalone.zig
- test/standalone/self_exe_symlink/build.zig
- test/standalone/self_exe_symlink/create-symlink.zig
- test/standalone/self_exe_symlink/main.zig
Before, selfExePath would be the path of the symlink on Windows instead of the path of what the symlink points to.
This deprecates fs.selfExePathW since it does not provide a separate use-case over selfExePath (before, the W version could return [:0]u16 directly)
Fixes https://github.com/ziglang/zig/issues/16670 (`zig.exe` being a symlink will now correctly find the lib dir relative to the symlink target rather than the location of the symlink itself).
---
Also adds a standalone test that tests that `fs.selfExePath` follows symlinks by comparing it to the path of the File returned from `fs.openSelfExe`
---
Before this PR, the added standalone test would fail with something like:
```
====== expected this output: =========
C:\Users\Ryan\Programming\Zig\zig\zig-cache\o\99cf2c7250d4d9eb9cd316b …
```
> `fs.selfExePath`: Make the Windows implementation follow symlinks

- lib/std/os.zig
Same as a190582b26a82f96da7488eff37e9676cdb937bc but for `os.realpathW` instead of `fs.Dir.realpathW`
> os.realpathW: Reduce the number of OpenFile calls for directories

- lib/std/Build/Cache.zig
This makes Cache.findPrefix/findPrefixResolved use `std.fs.path.relative` instead of `std.mem.startsWith` when checking if a file is within a prefix. This fixes multiple edge cases around prefix detection:
- If a prefix path ended with a path separator, then the first character of the 'sub_path' would get cut off because the previous implementation assumed it was a path separator. Example: prefix: `/foo/`, file_path: `/foo/abc.txt` would see that they both start with `/foo/` and then slice starting from one byte past the common prefix, ending up with `bc.txt` instead of the expected `abc.txt`
- If a prefix contained double path separators after any component, then the `startsWith` check would erroneously fail. Example: prefix: `/foo//bar`, file_path: `/foo/bar/abc.txt` would not see that …
> Cache: Fix findPrefix when paths are slightly out of the ordinary

- lib/std/math/big/int_test.zig
- lib/std/math/pow.zig
- src/AstGen.zig
- test/behavior/bitcast.zig
- test/cases/compile_errors/negative_zero_literal.zig
The intent here is ambiguous: this resolves to the comptime_int '0', but it's likely the user meant to use a floating-point literal.
Resolves: #16890
> AstGen: disallow '-0' integer literal

- lib/std/heap/general_purpose_allocator.zig
Created from a conversation with  @andrewrk on irc: Memory leaks when using ArrayList can be inconvenient to debug when the stack frame size is 4 because the entirety of the printed frame is within zig stdlib, and not in the users calling stack. Increasing this to 6 for Debug builds, gives 2 frames of user code. I increased the frame size for tests as well by the equivalent factor, but I'm unconvinced that's actually desirable.
> Update default stack frames for general_purpose_allocator.zig

- lib/compiler_rt/comparef.zig
- test/behavior/floatop.zig
Closes #16889
The previous comparison logic did not take the sign bit into account, resulting in lesser negative numbers comparing greater than greater negative numbers.
I'm not sure what the correct procedure for submitting compiler_rt bug fixes is, but I added some compiler_rt and behavior tests that fail under the old comparison code.
> compiler_rt: fix f80 comparisons

- lib/std/dwarf/call_frame.zig
- lib/std/meta.zig
- src/AstGen.zig
- src/InternPool.zig
- src/Module.zig
- src/Sema.zig
- src/TypedValue.zig
- src/Zir.zig
- src/arch/aarch64/abi.zig
- src/arch/arm/abi.zig
- src/arch/wasm/CodeGen.zig
- src/arch/wasm/abi.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/abi.zig
- src/codegen.zig
- src/codegen/c.zig
- src/codegen/c/type.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/link/Dwarf.zig
- src/type.zig
- src/value.zig
- test/behavior/union.zig
- test/cases/compile_errors/access_inactive_union_field_comptime.zig
- test/cases/compile_errors/dereference_anyopaque.zig
- test/cases/compile_errors/directly_embedding_opaque_type_in_struct_and_union.zig
- test/cases/compile_errors/non-const_variables_of_things_that_require_const_variables.zig
In short summary, this is a prerequisite to incremental compilation:
After this checklist, incremental compilation will be complete.
There are a couple concepts here worth understanding:
Key.UnionType - This type is available *before* resolving the union's fields. The enum tag type, number of fields, and field names, field types, and field alignments are not available with this.
InternPool.UnionType - This one can be obtained from the above type with `InternPool.loadUnionType` which asserts that the union's enum tag type has been resolved. This one has all the information available.
Additionally:
* ZIR: Turn an unused bit into `any_aligned_fields` flag to help semantic analysis know whether a union has explicit alignment on any fields (usually not).
* Sema: delete …
> compiler: move unions into InternPool

- src/arch/wasm/CodeGen.zig
- test/behavior/stage2_wasm_div.zig
Implement lowering code for `@mod` on integers in the stage2 wasm backend (`@mod` on floats remains unimplemented).
Fix invalid wasm being produced for `@divFloor` on signed integers by the stage2 wasm backend. wasm comparison instructions (e.g., less than) always output an `i32`, and `select` takes an `i32` as the condition, but the previous `@divFloor` implementation assumed that when comparing or selecting between `i64`, the output / condition would be an `i64`.
This pull request also renames `signAbsValue` in `wasm/CodeGen.zig` to `signExtendInt`, as I found the previous name misleading.
The new `@divFloor` implementation 0 extends its result when used on type `iN` where `N < 64, N != 32` - see https://github.com/ziglang/zig/pull/16807#issuecomment-1685243759.
> Implement `@mod` and fix bugs with `divFloor` for wasm

- lib/std/os/uefi/protocol.zig
- lib/std/os/uefi/protocol/hii_database.zig
- lib/std/os/uefi/protocol/hii_popup.zig
- lib/std/os/uefi/protocol/ip6.zig
- lib/std/os/uefi/protocol/managed_network.zig
- lib/std/os/uefi/protocol/udp6.zig
this is a very naive fix. all it does is get rid of errors that appear when running `std.testing.refAllDecls(std.uefi)`
> fix compile errors introduced by #16953

- src/Module.zig
- src/Sema.zig
Extracted from #16969 for easier inclusion in a bugfix release.
Closes #15124
---
```diff
repro.zig:24:5: error: bad
@compileError("bad");
^~~~~~~~~~~~~~~~~~~~
repro.zig:20:6: note: called from here
l();
~^~
repro.zig:16:6: note: called from here
k();
~^~
repro.zig:12:6: note: called from here
j();
~^~
repro.zig:9:9: note: called from here
fn h() i() {}
~^~
+referenced by:
+    g: repro.zig:6:5
+    f: repro.zig:2:5
+    comptime_0: repro.zig:28:5
```
---
```diff
lib/std/mem.zig:4143:9: error: expected []T or *[_]T, passed *u32
@compileError("expected []T or *[_]T, passed " ++ @typeName(Slice));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/std/mem.zig:4150:59: note: called from here
pub fn sliceAsBytes(slice: anytype) SliceAsBytesReturnType(@TypeOf(slice)) { …
```
> Sema: implement reference trace with called from here notes

- src/AstGen.zig
- src/Sema.zig
- test/behavior/cast.zig
- test/cases/compile_errors/invalid_float_casts.zig
The following cast builtins did not previously work on vectors, and have been made to:
* `@floatCast`
* `@ptrFromInt`
* `@intFromPtr`
* `@floatFromInt`
* `@intFromFloat`
* `@intFromBool`
Resolves: #16267
> Sema: allow cast builtins on vectors

- lib/std/linked_list.zig
- lib/std/std.zig
This fixes a mistake in PR #16996.
> std: Move `TailQueue` alias to correct namespace

- lib/std/zig/system/NativePaths.zig
- lib/std/zig/system/darwin.zig
- src/libc_installation.zig
- src/link/MachO/load_commands.zig
- test/link/macho/bugs/13056/build.zig
- test/standalone/ios/build.zig
`std.zig.system.darwin.getSdk` now pulls only the SDK path so we execute a child process only once and not twice as it was until now since we parse the SDK version directly from the pulled path. This is actually how `ld64` does it too.
Note that this behavior was regressed recently and our linker lost the ability to set the SDK version based on detected SDK via `xcrun` utility.
@andrewrk pointed out to me that perhaps we should embed the SDK version as part of the ABI of the triple much like we do for glibc versions which I have to admit I really like, but until I investigate this a lot more, this is a temporary solution that unregresses the status quo.
cc @floooh since last time you were affected by Zig failing to parse the SDK version properly.
> darwin: move inference of SDK version into the linker

- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
- test/cases/compile_errors/recursive_inline_fn.zig
Extracted bugfix into #16992
~~Only remove the references matching the notes.~~  I eventually figured out the correct way to generate the reference trace, and it ended up being extremely simple and not needing any of these massive changes (note the diffs below no longer have the superfluous reference traces they did before), but I still have other reasons for making them, so I don't really want to revert them all...
* 70e0d8170fe3de3e9be86813fc6baff013b352b4 cleanup `@as` invasion: a clear improvement that should get merged
* bdbe16c47a1a7bb7412bcfbf39c9f32d22a7e2cb use more enum literals: clearly an improvement, maybe stage1 couldn't handle these before?
* acd35a1aa75c78dc24859fa658f6d3e25e330b8a factor out `NeededComptimeReason`: this is literally only needed if you buy the next change, …
> Sema: refactor to use fewer catch expressions

- lib/std/fs.zig
- lib/std/fs/test.zig
`statFile` now only uses `os.fstatatWasi` when not linking libc, matching the pattern used throughout other `Dir` functions. This fixes the compilation error: `error: struct 'c.wasi.Stat' has no member named 'fromFilestat'` (which the added test would have failed with)
Unblocks https://github.com/ziglang/zig/pull/16878
> Fix `Dir.statFile` for WASI when linking libc

- lib/std/coff.zig
@kubkon Trivial change that fixes compile error.
> std.coff: Fixed compile error.

- src/link/Dwarf.zig
This un-breaks debug info generated by self-hosted native `x86_64` backend.
A wake-up call for me to finally add some DWARF tests into the mix.
> dwarf: fix copy-paste typo in variable lowering code for reg and stack

- src/link/Elf.zig
This avoids leaving undefined bytes in the output file in case a decl has been garbage collected before it's been committed into
the binary. Basically, we get rid of this nasty looking warning in various ELF tooling:
This should have minimal impact on performance since we have to write globals on every iteration anyway.
> elf: write all symbols in bulk in flush

- lib/std/os.zig
- lib/std/os/windows.zig
Usage of FILE_RENAME_IGNORE_READONLY_ATTRIBUTE or
FILE_DISPOSITION_IGNORE_READONLY_ATTRIBUTE for posix semantics require
win10_rs5 instead of win10_rs1 necessary for posix semantics. Keep it as simple
as possible, since it is reasonable to expect users being able to update
win10_rs5 or use non-posix semantics instead.
Closes #17049.
> std.os+windows: isAtLeast(.win10_rs5) in renameatW(), DeleteFile() for posix semantics

- lib/docs/main.js
- lib/docs/ziglexer.js
- src/Autodoc.zig
Rendering of `optionalPayload` assumes `a.?` syntax for now since other expressions using `optional_payload_*` are `if`, `orelse` and `while` which we don't analyse yet
> autodoc: Implement `a[b]`, `a.?`, and `a.*`

- lib/std/os/linux/io_uring.zig
Previous PR: #17060 
See thread on original PR. I also noticed a second syscall in this comment missing a `2`. cc: @daurnimator. Thanks!
> Make a Couple Syscall Comments Consistent

- lib/std/os/linux.zig
Closes https://github.com/ziglang/zig/issues/16975.
Before:
```
thread 4288 panic: panic
Panicked during a panic. Aborting.
Aborted
```
After:
```
thread 4135 panic: panic
/mnt/c/cygwin64/home/kcbanner/temp/16975/lib.zig:2:5: 0x2ae695 in panic (lib)
@panic("panic");
^
/mnt/c/cygwin64/home/kcbanner/temp/16975/exe.zig:4:10: 0x23a7e8 in main (exe)
panic();
^
/mnt/c/cygwin64/home/kcbanner/kit/zig/lib/std/start.zig:360:22: 0x23a0ac in posixCallMainAndExit (exe)
while (envp_optional[envp_count]) |_| : (envp_count += 1) {}
^
/mnt/c/cygwin64/home/kcbanner/kit/zig/lib/std/start.zig:243:5: 0x239c01 in _start (exe)
asm volatile (switch (native_arch) {
^
???:?:?:
```
The issue was caused by the version of `elf_aux_maybe` (linux.zig) in `lib` not being initialized by the startup code (since only the …
> linux: export getauxval when not compiling with libc

- src/clang.zig
- test/translate_c.zig
`zig translate-c` currently panics with a "switch on corrupt value" when encountering long double literals, such as when given the following input:
```c
extern const long double value = 1.0L;
```
The problem seems to have stemmed from the `APFloatBaseSemantics` enum in `clang.zig` being out of sync with LLVM 16's [`llvm::APFloatBase::Semantics`](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/include/llvm/ADT/APFloat.h#L151-L168) enum.
The added test cases fail on older zig compiler builds and result in panics.
> translate-c: fix panic when translating long double literals

- lib/std/net.zig
- lib/std/net/test.zig
This fixes the case where IPv6 address parsing incorrectly succeeded on input such as `1`, which now returns error.Incomplete. This is done by adding a check that if there is no abbreviation (i.e. the case where there is no `::` somewhere) then we must have written at least 14 of the 16 bytes in the IPv6 address result before the check (the last two bytes are handled after this check). This check is not needed for the case of abbreviation because this difference (14 - num of written bytes) determines how many zeroes are being abbreviated.
This PR fixes https://github.com/ziglang/zig/issues/17019.
> std.net: Fix IPv6 address parsing for single digit

- doc/langref.html.in
There were some keywords that were in the Grammar, but not in the Keyword List, namely: callconv and opaque.
Also some keywords in Grammar were not sorted in alphabetical order (that the Keyword List appeared to be in),
namely: linksection and nosuspend (or noinline).
I did all that in the browser, so I didn't test/ran anything.
But if something would be broken, I expect that it would be the link to opaque header.
Let me know if something is not ok.
> langref: keyword consistency (between keyword list and grammar)

- src/AstGen.zig
- test/cases/compile_errors/array_init_invalid_elem_count.zig
The struct equivalent already had this validation.
> AstGen: fix missing array type validation

- lib/std/mem/Allocator.zig
We should be able to filter OutOfMemory.
> mem: explicit dupe and dupeZ error on Allocator

- src/link/Wasm.zig
`getAtomPtr` returns a pointer to an element in an ArrayList which is followed by a call to `createAtom` that calls append on that ArrayList.
```
==23256== Memcheck, a memory error detector
==23256== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==23256== Using Valgrind-3.20.0 and LibVEX; rerun with -h for copyright info
==23256== Command: stage4/bin/zig build-exe example.zig -target wasm32-wasi -fno-llvm -fno-lld
==23256== 
compiler_rt... ==23256== Invalid read of size 8
==23256==    at 0x12B5287: link.Wasm.populateErrorNameTable (Wasm.zig:3037)
==23256==    by 0xEB5FEC: link.Wasm.flushModule (Wasm.zig:3364)
==23256==    by 0xBE5C26: link.Wasm.flush (Wasm.zig:3140)
==23256==    by 0x961C23: link.File.flush (link.zig:795)
==23256==    by 0x9612F5: Compilation.flush …
```
> wasm-linker: fix use of invalidated memory in populateErrorNameTable

- lib/std/tar.zig
Handles .extended_header type to parse PAX attributes and check if they override the path of the next file. Increases maximum file path length from 255 to ~1014~ `std.fs.MAX_PATH_BYTES`.
Fixes #15342
> std.tar: add support for file path in pax attributes

- lib/std/std.zig
This cleans up existing documentation, adds a bit more, and fixes some typos too.
I thought autodoc should probably just take over existing documentation from the top-level doc comment of the respective file that represents the namespace but those can sometimes be quite long so maybe it's better to do it like this. Though it could also just use only the first line. Anyway, that's for the future.
> std: clean up top-level namespaces documentation

- build.zig
- ci/aarch64-linux-debug.sh
- ci/aarch64-linux-release.sh
- ci/x86_64-linux-debug.sh
- ci/x86_64-linux-release.sh
We already have a zig build step for this: test-fmt.
* Rename the test-fmt step to check-fmt. test-fmt sounds like it runs tests for `zig fmt` itself (`lib/std/zig/render.zig`). It's also more similar to `zig fmt --check` and the `std.Build.FmtStep.Options` `check` field.
* Use the step instead of `zig fmt --check` in the CI scripts.
* ~~Also use it in CI scripts that didn't have this check before.~~ (decided not to do this anymore)
That, or should we have the check in only one of the scripts, like `ci/x86_64-linux-debug.sh`?
This includes the `tidy` check. Wouldn't it make sense to run these two checks only in one of the scripts?
I'm also not sure about the `--exclude ../build-{optimize_mode}` excludes found in the CI scripts but not in the `build.zig`. For now I decided to add them in …
> ci: use zig build check-fmt instead of zig fmt --check

- lib/docs/main.js
Closes #17013
The addition of the "other results" `hr` to the search results broke the previous code's assumption that the only elements in the search results were search results (`li` elements). This change fixes the linked issue along with some related navigation issues stemming from treating the `hr` as a search result (e.g. search for a term like "array list" and then navigate with the arrow keys to the "other results" divider: the previous code allows the divider to be "selected" as a result).
> Autodoc: fix search results navigation

- lib/docs/index.html
- lib/docs/main.js
Closes #17011
Closes #17012
This commit allows the logo to scale more freely to fit its container, and removes some extra margins so that the content scroll bar is flush with the right side of the viewport.
Before:
After:
> Autodoc: tweak page layout

- doc/langref.html.in
Better illustrate what happens to the block after inlining comptime conditionals.
closes #17106
> doc: inline comptime conditional block

- src/arch/wasm/CodeGen.zig
- test/behavior/bitcast.zig
- test/behavior/cast.zig
- test/behavior/floatop.zig
- test/behavior/math.zig
- test/behavior/maximum_minimum.zig
- test/behavior/muladd.zig
- test/behavior/widening.zig
follow up to #14668
This should cover the majority of float operations on `f80` and `f128` (excluding vectors).
I always tried to match the code generated by the llvm backend which was mostly compiler-rt calls.
Some of the possible conversions with `@floatFromInt` and `@intFromFloat` are not properly implemented yet, but I don't think that I regressed anything there.
71b15ea28eb308c3344bd097bd46115318e37f73 is technically not related to floats but it makes it possible to call `std.debug.print` on floats.
Update:
After taking a second look at my code, I've remembered that the optimization to float conversions referenced [here](https://github.com/ziglang/zig/pull/14668#discussion_r1111336436) could also be applied to `@floatFromInt` and `@intFromFloat`.
> wasm: implement more float operations on f80 and f128

- lib/std/json/dynamic.zig
- lib/std/json/dynamic_test.zig
`max_value_len` was not being used in the `jsonParse` function of `std.json.Value`
> json: respect max_value_len when parsing std.json.Value

- lib/std/math/cbrt.zig
Fixes #17112 
Changes the code checking for zero values to just return the value passed instead of 0 always. This is the same as the cbrt32 function, and the [musl libc implementation](https://git.musl-libc.org/cgit/musl/tree/src/math/cbrt.c).
> std.math.cbrt: fixed -0.0 evaluating to 0.0

- src/InternPool.zig
- src/Sema.zig
- src/TypedValue.zig
- src/codegen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/link/Dwarf.zig
- src/type.zig
- src/value.zig
Instead of using actual slices for InternPool.Key.AnonStructType, this commit changes to use Slice types instead, which store a long-lived index rather than a pointer.
This is a follow-up to 7ef1eb1c27754cb0349fdc10db1f02ff2dddd99b.
> InternPool: prevent anon struct UAF bugs with type safety

- lib/std/fs/test.zig
See https://github.com/ziglang/zig/issues/17134. I tried to disable the least amount of the test that would fix the flakiness without reducing the usefulness of the test too much. I didn't include an `aarch64` check since it's possible to hit this on `x86_64` as well (it just likely can't be hit in the specific x86_64 CI environment that is being used currently).
> Disable flaky part of Dir.rename directories test on Windows

- lib/std/mem.zig
We should be able to filter OutOfMemory.
Followup on pull-request #17090.
> mem: explicit Allocator.Error on concat and join

- src/link/Elf.zig
OK, so we still preallocate sections, but I figured that instead of trying to replicate how we do it for MachO, I'll try something different. Ladies and gents, with just a few changes, we can now attempt to link LLVM and clang emitted objects **without** invoking the incremental compiler and self-hosted `x86_64` backend. I am very excited how easy it was to do this, and even though we cannot yet link anything non-trivial emitted by LLVM (NB missing features will be added by me in the coming days/weeks), it opens Zig up for adding comprehensive linker tests that will stress test the linker without the need to involve the incremental compiler. This will be a huge win for us in the long run.
Some examples to back the poor description above:
1. `zig build-exe hello.zig -fno-llvm -fno-lld` …
> elf: enable Zig's ELF linker on non-incremental codepaths (LLVM, clang)

- lib/std/json.zig
- lib/std/json/fmt.zig
Adds std.json.fmt which returns a std.fmt Formatter that formats any given value using std.json.stringify.
> std.json: add fmt function

- lib/std/os.zig
- lib/std/os/test.zig
- lib/std/zig/system/NativePaths.zig
`std.process.getEnvMap` or `std.process.getEnvVarOwned` should be used instead, requiring allocation.
Fixes: #17117 
Thanks to @squeek502 for the pointer!
> std: add compile error when using `std.os.getenv` on the wasi target

- lib/std/comptime_string_map.zig
- lib/std/std.zig
This will allow users to construct e.g. a ComptimeStringMap that uses case-insensitive ASCII comparison.
Note: the previous ComptimeStringMap API is unchanged (i.e. this does not break any existing code).
(the motivating use case for this comes from https://github.com/ziglang/zig/pull/17069)
Prior art: https://github.com/ziglang/zig/pull/5520
> ComptimeStringMap: Add version that takes an equality function

- src/Compilation.zig
- src/main.zig
If `-includes` is passed to `zig libc`, it will print the detected libc include paths for the target and then exit
Examples on Linux:
```console
$ zig libc -includes
/usr/include
$ zig libc -includes -target native-native-musl
/home/ryan/Programming/zig/zig/lib/libc/include/x86_64-linux-musl
/home/ryan/Programming/zig/zig/lib/libc/include/generic-musl
/home/ryan/Programming/zig/zig/lib/libc/include/x86-linux-any
/home/ryan/Programming/zig/zig/lib/libc/include/any-linux-any
$ zig libc -includes -target x86_64-windows
/home/ryan/Programming/zig/zig/lib/libc/include/x86_64-windows-gnu
/home/ryan/Programming/zig/zig/lib/libc/include/generic-mingw
/home/ryan/Programming/zig/zig/lib/libc/include/x86_64-windows-any
/home/ryan/Programming/zig/zig/lib/libc/include/any-windows-any
$ zig libc …
```
> `zig libc`: Add -includes option

- lib/std/math.zig
- lib/std/math/log.zig
- lib/std/math/log_int.zig
This addresses #17142.
This patch leaves the `comptime_int` as is, i.e. *broken*. I haven't had the time to figure out where should I put the implementation for that.
Given that the code for `log_int` is extremely simple, it should be straightforward for someone with knowledge of the compiler to port the implementation to cover that case too.
~~Unfortunately, I'm not able to run the tests locally directly from the source tree. I tested the code as a separate module, not integrated in the rest of the standard library.~~
*Edit:* I managed to run the tests directly in the standard library source tree.
> std.math.log_int: implement integer logarithm without using float math

- src/AstGen.zig
- src/AstRlAnnotate.zig
- test/behavior/cast.zig
The `coerce_result_ptr` instruction is highly problematic and leads to unintentional memory reinterpretation in some cases. It is more correct to simply not forward result pointers through this builtin.
`coerce_result_ptr` is still used for struct and array initializations, where it can still cause issues. Eliminating this usage will be a future change.
Resolves: #16991
> AstGen: do not forward result pointers through @as

- lib/std/os/linux/bpf.zig
`Insn.st()` can be used with dynamic size just like `Insn.stx()`, which is relevant in a code generation context.
using `ImmOrReg` caused an error as its fields were ordered differently than `Source`.
> bpf: remove unhelpful "comptime" and fix union order

- lib/build_runner.zig
- lib/std/Build.zig
- lib/std/Build/Step/Options.zig
- src/Package.zig
- src/main.zig
Previously, the generated `@dependencies` module contained dependency metadata specified in a hierarchical manner using fully-qualified names. This exposes issues similar to the old `--pkg-begin`/`--pkg-end` options for modules: namely, shared dependencies cannot be reasonably modeled.
The new `@depedencies` module contains generated code like the following (where strings like "abc123" represent hashes):
```zig
pub const root_deps = [_]struct { []const u8, []const u8 }{
.{ "foo", "abc123" },
};
pub const packages = struct {
pub const abc123 = struct {
pub const build_root = "/home/mlugg/.cache/zig/blah/abc123";
pub const build_zig = @import("abc123");
pub const deps = [_]struct { []const u8, []const u8 }{
.{ "bar", "abc123" },
.{ "name", "ghi789" },
};
};
};
```
Each package contains a …
> package manager: write deps in a flat format, eliminating the FQN concept

- src/Sema.zig
- src/type.zig
- test/behavior/call.zig
This is supposed to be the case, similar to how pointers to generic functions are comptime-only (several pieces of logic already assumed this). These types being considered runtime was causing `dbg_var_val` AIR instructions to be wrongly emitted for such values, causing codegen backends to create a runtime reference to the inline function, which (at least on the LLVM backend) triggers an error.
Resolves: #38
> Sema: mark pointers to inline functions as comptime-only

- lib/std/c.zig
I have updated @MasterQ32's ZigAndroidTemplate to work with the latest version of Zig and we are exploring adding Android support to Mach https://github.com/hexops/mach/issues/17
`std.c.getcontext` is not used during the build, but if the `pub extern "c"` switch here is hit then it refers to a symbol that is not preset in Android's bionic libc. If the `std.os.linux.getcontext` switch is hit in contrast, then it cannot be built when targeting bionic libc - so it seems prudent to just disable this switch when targeting android for now.
This may not be the perfect long-term solution, but I have a golden rebuttal to that: before I was unable to compile Zig applications for Android, and now with this change I can:
> std: correct getcontext for Android bionic libc

- lib/std/http.zig
- lib/std/http/Client.zig
- lib/std/http/Headers.zig
- lib/std/http/Server.zig
- lib/std/http/protocol.zig
- test/standalone/http.zig
This PR provides a way for redirects to be handled with a payload when the redirect code indicates that the payload has been received and doesn't need to be re-transmitted such as with `see_other`, `moved_permanently`, or `found`. In such cases content headers are stripped, as they may confuse a server.
Privileged headers such as authentication are now stripped when redirecting off of the domain they were originally intended for (although to a subdomain is allowed).
CannotRedirect has been translated into a more informative RedirectRequiresResend error, indicating that the request is *still in a valid state*, but the request was left with the previous response (the redirection response), and the user will have to handle the redirection themselves to the Location provided in the response …
> std.http: handle Expect: 100-continue, improve redirect logic, add Client.fetch for simple requests

- lib/std/os.zig
The [_environ variable](https://learn.microsoft.com/en-us/cpp/c-runtime-library/environ-wenviron) that is populated when linking libc on Windows does not support Unicode keys/values (or, at least, the encoding is not necessarily UTF-8). So, for Unicode support, _wenviron would need to be used instead. However, this means that the keys/values would be encoded as UTF-16, so they would need to be converted to UTF-8 before being returned by `os.getenv`. This would require allocation, which is not part of the `os.getenv` API, so `os.getenv` is not implementable on Windows even when linking libc.
See https://github.com/ziglang/zig/pull/16464#issuecomment-1647337848 for a bit more detail.
Closes https://github.com/ziglang/zig/issues/8456. Alternative to https://github.com/ziglang/zig/pull/16464.
> Make `std.os.getenv` always a compile error on Windows

- src/codegen/llvm.zig
This is an optimization to avoid O(N) field index lookups. It's also nicer in terms of DRY; the only tradeoff is (insignificant) memory usage.
Performance data point for building the self-hosted compiler:
```
Benchmark 1 (3 runs): master/zig build-exe ...
wall_time          56.5s  ± 1.14s     55.2s  … 57.4s           0 ( 0%)        0%
peak_rss           4.10GB ±  883KB    4.10GB … 4.11GB          0 ( 0%)        0%
cpu_cycles          227G  ±  347M      227G  …  228G           0 ( 0%)        0%
instructions        315G  ± 76.4M      314G  …  315G           0 ( 0%)        0%
cache_references   13.2G  ±  154M     13.1G  … 13.3G           0 ( 0%)        0%
cache_misses       1.15G  ± 5.62M     1.14G  … 1.15G …
```
> LLVM: cache struct field indexes

- src/translate_c.zig
- test/run_translated_c.zig
- test/translate_c.zig
This introduces the concept of a "weak global name" into translate-c.
translate-c consists of two passes. The first is important, because it discovers all global names, which are used to prevent naming conflicts: whenever we see an identifier in the second pass, we can mangle it if it conflicts with any global or any other in-scope identifier.
Unfortunately, this is a bit tricky for structs, unions, and enums. In C, these types are not represented by normal identifers, but by separate tags - `struct foo` does not prevent an unrelated identifier `foo` existing. In general, we want to translate type names to user-friendly ones such as `struct_foo` and `foo` where possible, but we can't guarantee such names will not conflict with real variable names.
This is where weak global names come in. …
> translate-c: prevent variable names conflicting with type names

- lib/std/os.zig
From the Microsoft page:
[link](https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-connect#return-value)
> If no error occurs, connect returns zero. Otherwise, it returns SOCKET_ERROR, and a specific error code can be retrieved by calling [WSAGetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsagetlasterror).
> 
> On a blocking socket, the return value indicates success or failure of the connection attempt.
> 
> With a nonblocking socket, the connection attempt cannot be completed immediately. In this case, connect will return SOCKET_ERROR, and [WSAGetLastError](https://learn.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-wsagetlasterror) will return [WSAEWOULDBLOCK](https://learn.microsoft.com/en-us/windows/desktop/Win …
> std.os Return error.WouldBlock when ws2_32 connect returns .WSAEWOULDBLOCK

- lib/std/math.zig
saw a random comment in chat which eventually led to https://github.com/nektro/zig-color/commit/c586d8ba0ca57a50ef2ed5f951b2b4ee9c5361c5
making this patch to help the next person
> std: math.absInt: update docs to use fabs for floats

- src/translate_c.zig
- src/translate_c/ast.zig
- test/translate_c.zig
C99 introduced designated initializers for structs. Omitted fields are implicitly initialized to zero. Some C APIs are designed with this in mind. Defaulting to zero values for translated struct fields permits Zig code to comfortably use such an API.
Closes #8165
> translate-c: Struct fields default to zero value

- src/arch/x86_64/CodeGen.zig
- test/behavior/cast.zig
- test/behavior/int128.zig
Safety is not a global flag that should be enabled or disabled for all stores - it's lowered by the frontend directly into AIR instruction semantics. The flag for this is communicated via the `store` vs `store_safe` AIR instructions, and whether to write 0xaa bytes or not should be decided in `airStore` and passed down via function parameters.
This commit is a step backwards since it removes functionality but it aims our feet towards a better mountain to climb.
Correct place to restore functionality is here:
https://github.com/ziglang/zig/blob/5af5d87ad2227b6a7b5347c7217312ef8a83de12/src/arch/x86_64/CodeGen.zig#L5528C4-L5534
> x86 backend: don't read bogus safety flag

- doc/langref.html.in
Simplify wording and add some formatting in several locations.
Expand sentinel array tests to highlight (non-)handling of internal sentinels.
Fix format of symbol names in function pointers example.
Clarify wording a bit on the builin atomic* documentation.
Remove the (second) builtin compileLog example that demonstrated a lack of compileLog entries.
(Meta comment: This is my first Zig pull request.  I'm happy to split this up into smaller changes, or drop/update any of the content that you don't like.)
> langref: small fixes to wording and examples

- ci/x86_64-windows-debug.ps1
- ci/x86_64-windows-release.ps1
The new CI images provided by GitHub no longer provide ninja.exe, so this commit installs it explicitly, using the suggested method from GitHub.
See https://github.com/actions/runner-images/issues/8343 for more details.
> CI: install ninja on windows

- src/AstGen.zig
- src/Sema.zig
- test/cases/compile_errors/@export_with_undeclared_identifier.zig
This required a third `if (found_already == null)` in another place in AstGen.zig for this special case of `@export`.
Fixes #17188
> AstGen: fix `@export` with undeclared identifier crashing

- lib/std/c/emscripten.zig
- lib/std/os.zig
- lib/std/os/emscripten.zig
Inspired by [#10836](https://github.com/ziglang/zig/issues/10836), these additions allow Zig objects and libraries built with the `wasm32-emscripten` target to link libc and use the `std.os` interface. These files may then be linked into an [Emscripten](https://emscripten.org/) web app with `emcc`.
I realize that [#10836](https://github.com/ziglang/zig/issues/10836) is not approved, but I thought that I would at least put this out there. I have used Zig with Emscripten successfully via this patch in a few personal projects (e.g. [a work-in-progress websocket/tcp game server](https://github.com/permutationlock/thierd/tree/main) or [a toy test of threads](https://github.com/permutationlock/zig_emscripten_threads)).
I also realize that Emscripten has a lot of idiosyncracies, and I have only …
> Added basic support for wasm32-emscripten target

- src/Sema.zig
Previously, @memset at comptime performed N pointer stores. This is less efficient than just storing a whole array of values at once. The difference can be quite drastic when reinterpreting memory - a test case which is 40s on master branch now takes under a second on a debug compiler build.
Resolves: #17214
> Sema: optimize comptime @memset by setting all elements at once

- src/Sema.zig
- src/TypedValue.zig
- src/Zir.zig
- test/behavior/destructure.zig
- test/behavior/eval.zig
See commit message for details. Performance data points are below. Overall, it seems there's a slight performance regression, but it's insignificant. Interestingly, cache misses are consistently improved, probably because we're no longer having to traverse previous AIR (which could be arbitrarily large).
---
Analyze behavior tests:
```
Benchmark 1 (103 runs): /home/mlugg/zig/master/build/stage3/bin/zig test -Itest test/behavior.zig -fno-emit-bin --zig-lib-dir lib --global-cache-dir c1 --cache-dir c2
wall_time           586ms ± 11.3ms     570ms …  623ms          1 ( 1%)        0%
peak_rss            106MB ±  213KB     105MB …  106MB          1 ( 1%)        0%
cpu_cycles         2.00G  ± 34.9M     1.94G  … …
```
> Sema: refactor detection of comptime-known consts

- src/Compilation.zig
Follow up to https://github.com/ziglang/zig/pull/17069.
This TODO being left in/not addressed was a complete oversight.
Before, any 'retryable' error would hit:
```
error: thread 2920 panic: access of union field 'success' while field 'failure_retryable' is active
```
Now, it will be reported/handled properly (this is from an induced `FileNotFound` in `updateWin32Resource`):
```
C:\Users\Ryan\Programming\Zig\zig\test\standalone\windows_resources\res\zig.rc:1:1: error: FileNotFound
```
> Windows resources: Fix reportRetryableWin32ResourceError

- lib/std/testing.zig
add std.testing.Error with names of all possible errors found in std.testing's pub functions.
* use this new error set to allow expectEqualDeep() to support self-referential structs
* add a test to verify that this error set contains all possible errors - currently skipped due to compiler bug
> std.testing: expectEqualDeep() - support self-referential structs

- lib/std/Build/Step/TranslateC.zig
This simply adds the ability to use `Step.TranslateC` without linking libc, while leaving the default behavior (linking libc) the same.
Use case: `translate-c`-ing Linux kernel headers, where linking libc is not desirable. Previously, the way to do this would be to invoke `addSystemCommand()`, call `zig translate-c` directly, and install the result from `captureStdOut()`.
> Allow Step.TranslateC to not link libc

- lib/std/Build.zig
- lib/std/Build/Step/Compile.zig
- src/Package.zig
Partly closes #16643
~~This PR implements dependencyPath, and allows for fetching dependencies without a build.zig.~~
This PR adds support for non zig dependencies (dependencies without a build.zig). It adds a function ```path``` to the ```Dependency``` struct which returns a ```LazyPath``` to a path inside the dependency.
It does not currently fetch these dependencies lazily, it instead just uses the current way of fetching dependencies before running the build. Doing actual lazy fetching should probably be implemented separately together with lazy dependency fetching a zig dependencies. Right now it would require duplicating a lot of work from the existing dependency fetching.
I also created a proof of concept project based on Andrews [SDL](https://github.com/andrewrk/SDL) which …
> Add ability to construct a LazyPath out of any file from a dependency package

- src/Compilation.zig
- src/link.zig
- src/link/Coff/lld.zig
- src/resinator.zig
This prevents resinator from being included in zig1 and zig2.
> resinator: do not include in only_core_functionality builds

- lib/zig.h
- src/codegen/c.zig
implement codegen for:
- decl weak linkage
- decl aliases
- fn decl weak linkage
windows:
- `__declspec(selectany)` is not supported for functions
- skip weak linkage for functions
closes #17050
> cbe: support more symbol attributes

- src/zig_clang.cpp
Clang's `FullSourceLoc::getFileLoc()` contains an assert which causes a panic in `translate-c` if too many errors occur, this PR prevents that assert from causing an abort. 
Closes #17208
This is the output of `zig translate-c` before:
```
/usr/bin/zig translate-c -DCONFIG_X86_X32_ABI= -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1=1 -DCONFIG_AS_SHA256_NI=1 -DCC_USE_FENTRY=1 -DMODULE= -D__KERNEL__= -DKBUILD_BASENAME=gtrace -DKBUILD_MODNAME=gtrace -I/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1/include -I/usr/lib/modules/6.5.4-arch2-1/build/arch/x86/include/ -I/usr/lib/modules/6.5.4-arch2-1/build/arch/x86/include/generated/ …
```
> Prevent hitting a clang assert when dealing with FullSourceLoc

- src/type.zig
- test/behavior/struct.zig
This fixes a panic in `unionAbiSize` when a 0-length array of a union is used as a struct field: https://github.com/ziglang/zig/issues/17270
Because `resolveTypeLayout` does not resolve the `elem_ty` if `arrayLenIncludingSentinel` returns 0 for the array, the child union type is not guaranteed to have a resolved layout at this point.
Fixed this case by just returning 0 for the abi size (this was the reason the inner type wasn't resolved).
> type: handle the 0-length array case in abiSizeAdvanced

- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
- src/main.zig
- src/translate_c.zig
The main motivation for this change was that running `zig translate-c file.h --listen=-` did not respond with a error bundle message when translate-c failed but instead printed them to stderr
Here is a small script to send the needed messages to the zig compile server:
```bash
printf "\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" | zig translate-c file.h --listen=- # little endian
printf "\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" | zig translate-c file.h --listen=- # big endian
```
> translate-c: convert clang errors messages into `std.zig.ErrorBundle`

- src/Compilation.zig
- src/libcxx.zig
- src/mingw.zig
This PR enables the use case of cross-compiling for old versions of Windows. Currently, any dlls or exes built for Windows won't run on anything older than 8, since a new function, `GetSystemTimePreciseAsFileTime`, was added in windows 8, and which libcxx will depend on if it is built for Window 8 or above. 
Zig will currently build libcxx without specifying `_WIN32_WINNT`, which controls the target version, and so libcxx ends up targeting 8+.
This PR uses the target version information already present in libcxx.zig for the value of the `_WIN32_WINNT` define.
This the first time I've written any zig code, so it may not be idiomatic. 
Thanks.
> define `_WIN32_WINNT` for windows compilations based on target minver

- lib/std/http.zig
- lib/std/http/Client.zig
Some servers will respond with the identity encoding, meaning no encoding, especially when responding to range-get requests. Adding the identity encoding stops the header parser from failing when it encounters this.
> std.http: add identity to content encodings

- lib/std/Build/Step/Compile.zig
- src/link.zig
- src/link/Elf.zig
- src/main.zig
Adds `--compress-debug-sections=zstd` (supported by llvm 16, see https://www.phoronix.com/news/LLVM-Landing-Zstd-Debug-Section)
Only tested with `zig cc`, after the PR:
```bash
~ $ zig cc hello.c -g -O0 -Wl,--compress-debug-sections=zstd && ls -l a.out
-rwxr-xr-x 1 user user 4064 Aug 16 22:13 a.out
~ $ zig cc hello.c -g -O0 -Wl,--compress-debug-sections=zlib && ls -l a.out
-rwxr-xr-x 1 user user 4040 Aug 16 22:13 a.out
~ $ zig cc hello.c -g -O0 -Wl,--compress-debug-sections=none && ls -l a.out
-rwxr-xr-x 1 user user 3976 Aug 16 22:13 a.out
```
with file `hello.c`
```bash
extern int printf(const char *restrict fmt, ...);
int main(void) {
printf("Hello, world!\n");
return 0;
}
```
Closes https://github.com/ziglang/zig/issues/16858
> Add '--compress-debug-sections=zstd'

- src/link.zig
- src/link/Elf.zig
- src/link/Elf/Object.zig
- test/link.zig
- test/link/elf.zig
This now works:
```
$ cat hello.c
#include <stdio.h>
int main() {
printf("Hello!\n");
return 0;
}
$ zig build-exe hello.c -lc -target x86_64-linux-musl -fno-lld
$ ./hello
Hello!
```
> elf: link against musl libc, add ELF test harness, dynamically allocate misc SHF_ALLOC sections

- .github/CODEOWNERS
From, https://github.com/ziglang/zig/pull/17221#issuecomment-1736281498, the current strategy with resinator is option 1:
> Put Aro in src/, don't mark it as vendored, allow tight coupling with other compiler code, and periodically port code back and forth between the Zig source tree and the Aro source tree.
so it would be good if I were notified of any PRs that modify the files in `src/resinator`
EDIT: Nevermind, looks like CODEOWNERS only works for people with write access to the repo.
> The people you choose as code owners must have write permissions for the repository.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> Add myself as a code owner of /src/resinator/

- src/main.zig
- test/standalone/issue_5825/build.zig
Closes https://github.com/ziglang/zig/issues/16671
When compiling for `*-windows-msvc`, detect the msvc installation directory and add the lib dirs to the `lib_dirs`, so that system libs can be found. The linker would have found them by it's own logic of detecting and adding the msvc paths, but the frontend search was failing before that had a chance to run.
Previously, `version` and `ole32` were detected via the `mingw.libExists` logic, which was a false positive. Since mingw doesn't include `uuid.lib`, that was the only one that failed.
To illustrate the false positive, if only this part of the diff was applied:
```diff
-       if (target_info.target.os.tag == .windows) {
+       if (target_info.target.isMinGW()) {
```
The output would be:
```
error: unable to find Dynamic system …
```
> windows: fix not finding system libs when compiling for *-windows-msvc

- src/codegen/c.zig
- src/link/C.zig
When the compiler's state lives through multiple Compilation.update() calls, the C backend stores the rendered C source code for each decl code body and forward declarations.
With this commit, the state is still stored, but it is managed in one big array list in link/C.zig rather than many array lists, one for each decl. This means simpler serialization and deserialization.
> C backend: flatten out some of the long-lived state

- src/resinator/bmp.zig
- src/resinator/compile.zig
- src/resinator/errors.zig
- src/resinator/literals.zig
- src/resinator/res.zig
Also contains slight modifications of the 32-bit fixes from https://github.com/ziglang/zig/commit/80ae27bc844ce7fe18bc686ce4befa24ab0f86bb
Both 32-bit targets and big endian targets are now also tested in resinator's CI: https://github.com/squeek502/resinator/commit/92d4010629f9db3e8d6df8b038b814f135572567
> resinator: Update to latest, fix for big endian arch

- doc/langref.html.in
- lib/std/zig/Parse.zig
noticed this extra level of nesting in the Decl grammar that looks unnecssary.
> docs: remove unnecessary nesting in grammar

- lib/std/Uri.zig
- lib/std/http/Client.zig
- src/Package.zig
- test/standalone/http.zig
Addresses #17015 by introducing a new startWithOptions. The only option is currently is a flag to use the provided URI as is, without modification when passed to the server. Normally, this is not needed nor desired. However, some REST APIs may have requirements that cannot be satisfied with the default handling.
@truemedian - please take a look and lmk your thoughts. I tried to avoid exacerbating any escape/encoding terminology issues as well as required changes to existing code. The function suffix "withOptions" is also used elsewhere in stdlib.
> introduce options to http client to allow for raw uris

- doc/langref.html.in
- lib/std/zig/Parse.zig
Noticed this grammar rule could be simplified using a repeating sequence rather than recursion.
> simplify ContainerDeclarations grammar rule

- src/link/Elf.zig
- src/link/Elf/Atom.zig
- src/link/Elf/Object.zig
- src/link/Elf/ZigModule.zig
- src/link/Elf/file.zig
- src/link/Elf/synthetic_sections.zig
Extracted from https://github.com/ziglang/zig/pull/17288
For object-only linking, so clang and LLVM drivers, segments get automatically expanded when required. For self-hosted backends, we cannot expand the segments since we do not emit relocations that the linker can use to track movement of symbol references when shifting things in memory. Since we are lacking this in all self-hosted backends, if we hit this during immediate development, the linker will print a helpful error message like the following:
```
$ ./stage4/bin/zig build test-link                                                                                                                                                                                                      
test.link.zig build-exe test Debug x86_64-linux: …
```
> elf: grow segments in virtual memory if they exceed allocated capacity

- lib/std/enums.zig
Moves the check for empty fields before any access to those fields.
> Allow empty `enum` to be used in `EnumSet`/`EnumMap`

- lib/std/os/linux.zig
- lib/std/os/linux/syscalls.zig
- tools/generate_linux_syscalls.zig
The wrapper can be tested using this program I whipped up:
https://gist.github.com/The-King-of-Toasters/aee448f5975c50f735fd1946794574f7
> Update Linux syscalls for 5.5 and add a wrapper for `cachestat` 

- lib/std/Build/Step/ConfigHeader.zig
This MR adds an optional field in the blank Style to allow for overriding the default header guard that is generated from the output file path.
i.e. now you can do
```
b.addConfigHeader(.{
.style = .{ .blank = .{ .include_guard_override = "MY_PREFIXED_CONFIG_H" } },
.include_path = "config.h",
}, .{});
```
to get
```
/* This file was generated by ConfigHeader using the Zig Build System. */
#ifndef MY_PREFIXED_CONFIG_H
#define MY_PREFIXED_CONFIG_H
// ...
#endif /* MY_PREFIXED_CONFIG_H */
```
The motivation for this is the case when multiple dependencies generate the same `config.h` with the same include guard, which ends up causing problems when both headers are included in the same translation unit. With this option, there is an escape hatch to define an include guard with a name that is …
> std.Build.ConfigHeader: Override include guard for blank style

- lib/std/array_list.zig
There’s an inefficiency in insertSlice of std.ArrayList. This is the current implementation:
```zig
pub fn insertSlice(self: *Self, i: usize, items: []const T) Allocator.Error!void {
try self.ensureUnusedCapacity(items.len);
self.items.len += items.len;
mem.copyBackwards(T, self.items[i + items.len .. self.items.len], self.items[i .. self.items.len - items.len]);
@memcpy(self.items[i..][0..items.len], items);
}
```
The problem is that if ensureUnusedCapacity triggers a resize, it will copy all the elements to the new allocation. insertSlice will then copy a slice of these same items to the end of the allocation, to make space for the insertion. It’s better to copy everything to their final place at once.
This pull request introduces a new function to the public interface of ArrayList / …
> Fix inefficiency with ArrayList.insertSlice 

- src/link/Elf.zig
- src/link/Elf/Atom.zig
- src/link/Elf/Object.zig
- src/link/Elf/Symbol.zig
- src/link/Elf/ZigModule.zig
- test/link/elf.zig
- test/tests.zig
It's not exactly efficient as `.tbss` is actually never mapped at runtime unlike `.bss`. For that reason, typically linker overlaps `.tbss` with a succeeding alloc section, usually `.data`, in virtual memory, since we only care about the continuity of `.tdata` into `.tbss`. When the relocations are resolved, they are lowered into positive and negative offsets wrt to the TLS segment. I think given this knowledge there exists the potential for improving current implementation by quite a bit.
In other news, I have now also added a new test target to the test matrix:
```diff
+        .{
+            .target = .{
+                .cpu_arch = .x86_64,
+                .os_tag = .linux,
+                .abi = .musl,
+            },
+            .link_libc = true,
+            .use_lld = false, …
```
> elf: add basic TLS segment handling

- src/Compilation.zig
- src/codegen/c.zig
- src/link/C.zig
This logic to lower snippets of C code in a dependency order is no longer needed. Simplify the logic by deleting the mechanism.
> C backend: remove unneeded ordering mechanism

- lib/std/mem.zig
Closes #11634.
These are an order of magnitude quicker than the previous implementations:
A relative comparison of each, measuring scanning a 1G file.
```
Reading 1G (1.0000000009313226GiB)
std.mem.sliceTo: 281.232ms
vectorized.sliceTo: 24.769ms
strlen: 24.291ms
std.indexOfScalar: 229.016ms
vectorized.indexOfScalar: 24.685ms
memchr: 24.958ms
```
This has overlap with an existing PR https://github.com/ziglang/zig/pull/16646 which we started independently at similar times. Am looking to combine the ideas between the two as needed.
`indexOfSentinel` is currently only enabled for `x86`, `x86_64` and `aarch64` as these are machines I was able to test (`x86` disasm is identical enough to be comfortable). These rely on OS' paged memory and certain indexing properties which I would prefer to …
> std.mem: add vectorized indexOfScalarPos and indexOfSentinel

- lib/std/mem.zig
> std.mem.zeroes: Zero out entire `extern union`, including padding

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Lower.zig
- src/arch/x86_64/Mir.zig
- src/link/Elf/Atom.zig
As discussed offline, this is a proposed start to rewriting part of the x86_64 backend concerned with lowering VM addresses of symbols when targeting ELF. This change implements lowering of non-PIC GOT references, however it doesn't touch `MCValue.memory` which also needs to be tweaked to work based on symbol indexes passed by the linker rather than hard-coded VM addresses which may change if we are forced to shuffle things around in memory.
> x86_64+elf: emit relocations instead of hard-coding VM addresses

- lib/compiler_rt/common.zig
- src/Compilation.zig
- src/InternPool.zig
- src/Sema.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/abi.zig
- src/codegen/llvm.zig
- test/behavior/abs.zig
- test/behavior/asm.zig
- test/behavior/bitcast.zig
- test/behavior/bugs/12680.zig
- test/behavior/bugs/529.zig
- test/behavior/cast.zig
- test/behavior/defer.zig
- test/behavior/floatop.zig
- test/behavior/math.zig
- test/behavior/maximum_minimum.zig
- test/behavior/struct.zig
- test/behavior/union.zig
- test/behavior/vector.zig
* float operations:
- `@sin`
- `@cos`
- `@tan`
- `@exp`
- `@exp2`
- `@log`
- `@log2`
- `@log10`
- `@round`
- `==`
- `!=`
- `<`
- `<=`
- `>`
- `>=`
- `@floatCast`
- `@floatFromInt`
- `@intFromFloat`
- `@floor`
- `@ceil`
- `@trunc`
- `+`
- `-`
- `*`
- `/`
- `@sqrt`
Depends on #17288
> x86_64: support operations that are implemented in compiler_rt

- src/Sema.zig
- test/behavior/error.zig
- test/cases/safety/@errorCast error union casted to disjoint set.zig
Closes #17353
Closes #17355
#17354 passes analysis but crashes in codegen because `error_set_has_value` doesn't work with adhoc inferred error sets and I'm not quite sure how it should be fixed.
> Fix issues in `@errorCast` with error unions

- lib/std/valgrind/memcheck.zig
The `makeMem*()` functions crashed under valgrind in Debug and ReleaseSafe modes.
The reason being that `doMemCheckClientRequestExpr()` returns `0` when not running under Valgrind, and `maxInt(usize)` when running under Valgrind.
Thus, `@as(i1, @intCast(maxInt(usize)))` always fails and these functions crashed before returning.
That being said, what these functions used to return was quite unexpected: `0` on error and `-1` on success (=running under valgrind). That doesn't match any Zig nor C conventions.
But that return value doesn't seem to be very useful. Either we are running under Valgrind or we are not. There's no point in checking this for every single call. Applications are likely to always discard it.
So, just return a `void` instead.
Also avoid function comments that start with …
> valgrind.memcheck: fix makeMem*()

- CMakeLists.txt
- lib/std/fs.zig
- lib/std/tar.zig
- lib/std/zig/ErrorBundle.zig
- src/Package.zig
- src/Package/hash.zig
- src/git.zig
- src/main.zig
```
zig fetch [options] <url>
zig fetch [options] <path>
```
Fetches a package which is found at `<url>` or `<path>` into the global cache directory, printing the package hash to stdout.
Closes #16972
Related to #14280
Additionally, this branch:
* Adds uncompressed .tar support to package fetching
* Introduces symlink support to package fetching (closes #16678)
> introduce the `zig fetch` subcommand and symlink support in zig packages

- test/behavior/tuple.zig
Closes #16412
---
This bug appears to have been fixed at some point since I opened the issue. I didn't see a behavior test for an empty tuple type, so I figured it would be good to add one along with closing the issue.
> Add behavior test for empty tuple type

- lib/std/heap/general_purpose_allocator.zig
- lib/std/treap.zig
Before this PR, GeneralPurposeAllocator could run into incredibly degraded performance in scenarios where the bucket count for a particular size class grew to be large. For example, if exactly `slot_count` allocations of a single size class were performed and then all of them were freed except one, then the bucket for those allocations would have to be kept around indefinitely. If that pattern of allocation were done over and over, then the bucket list for that size class could grow incredibly large, and to find a particular bucket, the entire (doubly linked) list would have to be scanned linearly.
This allocation pattern has been seen in the wild: https://github.com/Vexu/arocc/issues/508#issuecomment-1738275688
In that case, the length of the bucket list for the `128` size class would …
> GeneralPurposeAllocator: Considerably improve worst case performance

- CMakeLists.txt
This allows both debug and release builds to link to it without forcing release builds to link to libssp
> Add `-fno-stack-protector` to flags when building libzigcpp

- lib/std/heap/general_purpose_allocator.zig
Follow up to #17383. This is a minor optimization that only matters when a small allocation is resized/free'd soon after it is allocated.
The only real difference I was able to observe with this was via a synthetic benchmark that allocates a full bucket and then frees all but one of the slots, over and over in a loop (see "Benchmark code" in https://github.com/ziglang/zig/pull/17383):
Debug build:
```
Benchmark 1 (9 runs): gpa-degen-master.exe
wall_time           575ms ± 5.19ms     569ms …  583ms          0 ( 0%)        0%
peak_rss           43.8MB ± 1.37KB    43.8MB … 43.8MB          1 (11%)        0%
Benchmark 2 (10 runs): gpa-degen-search-cur.exe
measurement          mean ± σ            min … max …
```
> GeneralPurposeAllocator.searchBucket: check current bucket before searching the list

- src/Compilation.zig
- src/InternPool.zig
- src/Module.zig
- src/Sema.zig
- src/TypedValue.zig
- src/arch/wasm/CodeGen.zig
- src/codegen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/link.zig
- src/link/C.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/Plan9.zig
- src/link/Wasm.zig
- src/value.zig
Instead of explicitly creating a `Module.Decl` object for each anonymous declaration, each `InternPool.Index` value is implicitly understood to be an unnamed constant declaration when encountered by backend code generation.
The memory management strategy for these anonymous decls then becomes to garbage collect them along with the rest of InternPool garbage.
In the interest of a smooth transition, this commit only implements this new scheme for string literals and leaves all the previous mechanisms in place.
self-hosted compiler perf delta:
```
Benchmark 1 (3 runs): before/zig build-exe ...
wall_time          50.7s  ±  394ms    50.3s  … 51.0s           0 ( 0%)        0%
peak_rss           3.92GB ±  945KB …
```
> compiler: start handling anonymous decls differently

- lib/std/os.zig
- lib/std/os/linux.zig
This PR adds [fanotify](https://man7.org/linux/man-pages/man7/fanotify.7.html) API to `std.os.linux` and relevant higher level functions to `std.os`. I've made the higher level functions analogous to inotify API. There are also `FAN_EVENT_NEXT` and `FAN_EVENT_OK` macros but I was unsure to include them. I believe it'd be best to implement them in `std.os` in the future (maybe with `inline`).
> linux: add fanotify API

- lib/docs/main.js
- src/Autodoc.zig
Fix issue with getting docs for src-less types in main.js
> autodoc: Add handling for array_cat, array_mul, struct_init_empty_result

- lib/std/os/linux.zig
- src/arch/aarch64/Emit.zig
- src/arch/arm/Emit.zig
- src/arch/riscv64/Emit.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Lower.zig
- src/arch/x86_64/abi.zig
- src/codegen.zig
- src/link/Dwarf.zig
- src/link/Plan9.zig
- test/behavior/abs.zig
- test/behavior/bitcast.zig
- test/behavior/bugs/11995.zig
- test/behavior/cast.zig
- test/behavior/floatop.zig
- test/behavior/math.zig
- test/behavior/maximum_minimum.zig
- test/behavior/packed-struct.zig
- test/behavior/widening.zig
* `callconv(.C)` functions for more parameter and return types
- `u128`
- `i128`
- `f80`
- `f128`
- `extern struct { x: f64, y: f64 }`
> x86_64: improve C abi support

- lib/std/math.zig
- lib/std/math/nextafter.zig
`nextAfter()` returns the next representable value after `x` in the direction of `y` and is a standard math library function ([C++](https://en.cppreference.com/w/cpp/numeric/math/nextafter), [Java](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#nextAfter-double-double-)). It is primarily useful for bitwise incrementing/decrementing floats.
This implementation supports runtime integers, runtime floats and `comptime_int`. `comptime_float` is not supported because NaNs/infinities are intentionally difficult to obtain and because I'm not sure if the fact that it's backed by `f128` is supposed to be an implementation detail. Either way, the user could just call the function with the floating-point type whose behavior they want at comptime and then cast the result to …
> std.math: add nextAfter

- lib/std/os.zig
- lib/std/os/linux.zig
filled_sigset is equivalent to sigfillset() as empty_sigset is equivalent to sigemptyset().
For Plan 9 I think something like that should do it
```zig
const usize_bits = @typeInfo(usize).Int.bits;
pub const filled_sigset = @as(sigset_t, 1 << (20 & (usize_bits - 1)) - 1);
```
The implementation is based on os.linux.sigaddset() and that 31 is the max correct signal possible based on os.linux.SIG as it is more portable than a magic number.
> std.os.linux: Add filled_sigset and pause()

- lib/std/Build/Step/Run.zig
- lib/std/zig/system/NativeTargetInfo.zig
- src/main.zig
- test/src/Cases.zig
- tools/docgen.zig
Until now, we would pass `candidate: NativeTargetInfo` which creates a copy of the `NativeTargetInfo.DynamicLinker` buffer. We would then return pointer to this buffer in `bad_dl: []const u8` which would goes out-of-scope the moment we leave this function frame yielding garbage. To fix this, we just need to remember to pass by const-pointer
`candidate: *const NativeTargetInfo`.
This resulted in cute test runner error messages such as this one:
```
test.link.run test: error: the host system is unable to execute binaries from the target
because the host dynamic linker is '/nix/store/b2hc0i92l22ir2kavnjn3z5z6mzabbvm-glibc-2.34-210/lib/ld-linux-x86-64.so.2',
while the target dynamic linker is 'SX'.
consider setting the dynamic linker or enabling skip_foreign_checks in the Run step
```
Note …
> std: fix memory bug in getExternalExecutor

- lib/std/unicode.zig
I noticed this function showing up while profiling. It's used in the std's JSON serializer.
I did some simple measurements, on a simple ASCII string, it was about 6x faster.  On a large Chinese lorem ipsum string, it was about 2.5x faster.
> Use Go's implementation for utf8ValidateSlice

- src/codegen/c.zig
This hashmap value used to be assigned much later during `flushModule`, which never happens if an error is returned by the backend, and attempting to the undefined values would cause a crash.
> cbe: fix crash on error

- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Encoding.zig
- src/arch/x86_64/Mir.zig
- src/arch/x86_64/abi.zig
- src/arch/x86_64/encodings.zig
- src/register_manager.zig
- test/behavior/abs.zig
- test/behavior/asm.zig
- test/behavior/cast.zig
- test/behavior/floatop.zig
- test/behavior/math.zig
- test/behavior/maximum_minimum.zig
- test/behavior/muladd.zig
- test/behavior/var_args.zig
- test/behavior/widening.zig
* movement of `f80` values
* negation of `f80`
* `@abs` of `f80`
* C var args ABI
* inline assembly features
* instruction prefixes
* mnemonic fixes
* labels
* memory operands
* read-write constraint modifier
* register and memory alternative constraint
* `@floor` of `f80`
* `@ceil` of `f80`
* `@trunc` of `f80`
* `@bitCast` of `f80`
* `@abs` of integer vectors
* binary operations of vectors
* `@divTrunc` of `f16`
* `@divFloor` of `f16`
* `@rem` of floats
* `@mulAdd` of floats
> x86_64: more `f80` support

- lib/std/fs/test.zig
Some cleanup to lib/std/fs/test.zig to make using `fs.path.join` less awkward.  Clean up the allocators used a bit (use the TestContext arena allocator where it simplifies test code), remove some extraneous typing (`&.` works for `&[_][]const u8` to initialize the paths argument to join), and use fs.path.join() instead of `++ fs.path.sep_str ++` where it simplifies the test.
> lib/std/fs/test.zig: cleanup

- src/arch/x86_64/CodeGen.zig
- test/behavior/eval.zig
```
$ zig build-lib lib/compiler_rt.zig -fno-llvm -fno-lld -OReleaseFast
error: TODOImplementWritingLibFiles
src/link/Elf.zig:1149:17: 0xd43afe in flush (zig)
.Lib => return error.TODOImplementWritingLibFiles,
^
src/link.zig:819:21: 0xa22bd1 in flush (zig)
.elf => return @fieldParentPtr(Elf, "base", base).flush(comp, prog_node),
^
src/Compilation.zig:2357:21: 0xa2249a in flush (zig)
else => |e| return e,
^
src/Compilation.zig:2311:9: 0xa60533 in update (zig)
try comp.flush(main_progress_node);
^
src/main.zig:4206:9: 0xa8d787 in updateModule (zig)
try comp.update(main_progress_node);
^
src/main.zig:3615:21: 0xab0cd0 in buildOutputType (zig)
else => |e| return e,
^
src/main.zig:271:9: 0x8c9d5a in mainArgs (zig)
return buildOutputType(gpa, arena, args, .{ .build = .Lib });
^ …
```
> x86_64: fix codegen errors when compiling compiler_rt

- doc/langref.html.in
- lib/std/zig/Parse.zig
`ContainerDeclarations` is an abstraction of `ContainerDeclaration*`. Removing this abstraction allows the `ContainerMembers` rule to contain more concrete information without having to look at the definition of `ContainerDeclarations` which arguably makes it easier to follow.
> Grammar: Use `ContainerDeclaration*` instead of `ContainerDeclarations`

- lib/std/cstr.zig
- lib/std/std.zig
- lib/std/zig/parser_test.zig
Followup to 0a868dacdd31b7d5c529a332da718683477a2505 .
> std.cstr: remove deprecated namespace

- src/Sema.zig
This broke with #16604 but went unnoticed due to lack of tests.
Closes #17444
> Sema: fix `dbg_inline` instructions not being emitted

- src/Package/Fetch.zig
Only for packages that come from the main package. Fetched packages still cannot depend on paths outside their package root.
> Package.Fetch: allow relative paths outside project root

- src/arch/wasm/CodeGen.zig
- src/codegen/llvm.zig
- test/behavior/cast_int.zig
- test/behavior/packed-struct.zig
- test/behavior/packed-union.zig
This is generalisation of @jacobly0 https://github.com/ziglang/zig/pull/16605 to support optional and unions.
llvm appears to assume padding bits are "properly set" when using `llvm.load i4`:
https://llvm.org/docs/LangRef.html#load-instruction
> "When loading a value of a type like i20 with a size that is not an integral number of bytes, the result is undefined if the value was not originally written using a store of the same type."
so llvm assumes the `and` is redundant  and doesn't generate code to mask out  the bits.
```llvm
%26 = getelementptr inbounds { i4, i8 }, ptr %3, i32 0, i32 0, !dbg !3141
%27 = load i4, ptr %26, align 1, !dbg !3141
%28 = lshr i4 %27, 1, !dbg !3142
%29 = and i4 %28, 7, !dbg !3142  <<< does nothing
%30 = trunc i4 %29 to i3, !dbg !3142
%31 = icmp eq i3 %30, -3, …
```
> codegen/llvm: truncate padding bits when loading a non-byte-sized value

- src/Package/Fetch.zig
Oops, the loop was checking the wrong variable! Added a unit test.
> Package.Fetch: fix inclusions not working for directories

- build.zig
- lib/std/Build/Step/Compile.zig
- test/link/common_symbols/build.zig
- test/link/common_symbols_alignment/build.zig
- test/link/macho/unwind_info/build.zig
- test/standalone/issue_11595/build.zig
- test/standalone/issue_12706/build.zig
> Step.Compile: add options struct for `addCSourceFiles`

- src/Package.zig
Fixes a package fetching regression on Windows. Closes #17477
> Package: Fix path separator not being escaped between root_dir and sub_path

- src/Compilation.zig
- src/link/Coff/lld.zig
- src/link/Elf.zig
- src/link/MachO/zld.zig
- src/link/Wasm.zig
- test/link/macho/bugs/16308/build.zig
Originally, this PR tried to switch compiler_rt from making a static library to making an object file. However, that change did not pan out, and what is left over is some minor related enhancements.
Mainly, the default backend is self-hosted when LLVM libraries are not available.
> Compilation: default to self-hosted backends when not using libllvm

- src/Package/Fetch.zig
This makes tmp_directory close before calling renameTmpIntoCache which fixes occurences of those AccessDenied errors that aren't synonymous with PathAlreadyExists on Windows
> Package.Fetch: wrap operations involving tmp_directory in a block

- lib/std/valgrind.zig
I haven't otherwise tested whether this actually makes everything *work* as I'm just learning how valgrind works in the first place, but in terms of the code I think this makes sense. Was probably just missed at some point when the other functions were refactored.
> Fix compilation failure in valgrind.zig

- lib/std/Progress.zig
I noticed that there was a missing "is" in the description of Progress, so I added one.
> Fix minor typo in the description of Progress

- src/Package/Fetch.zig
- src/Package/Manifest.zig
* Package.Fetch: fix empty path and "." not including all
* Package.Manifest: fix error message for paths
closes #17491
> path-related fixes for Package.Fetch and Package.Manifest

- lib/std/start.zig
MIPS and SPARC have delayed branches, that is, they will unconditionally run the next instruction following a branch.
Stuff a `nop` in that place to prevent our startup routine from executing stray instructions, which may result in odd program behavior.
> lib: Fix asm code in _start for arches with branch delay slot

- src/Compilation.zig
- src/main.zig
- src/resinator.zig
- src/resinator/cli.zig
- src/resinator/preprocess.zig
- src/resinator/utils.zig
Uses [resinator](https://github.com/squeek502/resinator) under-the-hood (see https://github.com/ziglang/zig/pull/17069)
Closes #9564
---
The `cmdRc` function basically works exactly the same as `main.zig` in [standalone `resinator`](https://github.com/squeek502/resinator), meaning it will have the same output that the standalone `resinator` does, e.g. warnings like this:
`zig rc` passes the [`win32-samples-rc-tests`](https://github.com/squeek502/win32-samples-rc-tests) with perfect results (matching standalone `resinator`):
```
Found RC compiler: resinator
Found RC compiler: zig
Processed 485 .rc files
---------------------------
resinator
---------------------------
485 .rc files processed without discrepancies
identical .res outputs:     460
expected compile errors:    25 …
```
> Add `zig rc` subcommand, a (cross-platform) drop-in replacement for rc.exe

- src/codegen/llvm.zig
The previous code incorrectly added `sub_path` twice.
Also for the compilation unit, it was passing empty string to realpath, resulting in the error handling codepath being used.
closes #17482
Related:
* #16571
> llvm: fix incorrect file paths in debug info

- lib/std/Build/Step/Compile.zig
Fixes #15767.
`FileSource.getPath` already calls `pathFromRoot`, so `appendModuleArgs` does not need to. Running it twice breaks the path resolution when the module's `source_file` is a relative path such as `../../src/main.zig`.
> build: fix module path resolution

- src/Sema.zig
- test/behavior/var_args.zig
When analyzing the `as` ZIR instruction, an assertion would trip if the result type was a var args function argument. The fix is simple: inline a little bit of the `resolveType` logic into `analyzeAs` to make it detect this situation - which it was already attempting to do.
Closes #16197
> Sema: fix crash when coercion dest is var args

- src/codegen/llvm.zig
- test/behavior/cast.zig
see #17381
upstream: https://github.com/llvm/llvm-project/issues/68068
> LLVM: work around `@floatFromInt` bug

- ci/x86_64-windows-debug.ps1
- ci/x86_64-windows-release.ps1
- test/standalone/c_compiler/build.zig
- test/standalone/load_dynamic_library/build.zig
- test/standalone/shared_library/build.zig
The previous tarball for x86_64-windows did not have LLVM assertions enabled.
Related:
* https://github.com/ziglang/zig/issues/16959
* https://github.com/ziglang/zig/issues/16960
* https://github.com/ziglang/zig/issues/16965
Closes #17237
> CI: update windows tarballs

- doc/langref.html.in
I was learning the Zig build system and noticed the `build.zig` examples presented in the documentation are out of date and do not compile on zig 0.11.0 through current master due to the deprecation of the `.run()` and `.install()` methods.
This PR copies the current `build.zig` files into the docs from master, allowing the documented versions to compile on the current version of zig. I left the comments in the executable example because I found them helpful. I removed the duplicate comments from the library example.
The same error exists on the rendered [0.11.0 docs](https://github.com/ziglang/www.ziglang.org/blob/master/content/documentation/0.11.0/index.html#L12923-L12983). I would be happy to open a PR there as well.
> docs: update build.zig examples from current stdlib

- src/translate_c.zig
- test/translate_c.zig
fix #17098 
If transStmt fails to translate the last statement inside a StmtExpr, zig will cash.
This PR fixes this.
> fix translate-c crash

- lib/std/base64.zig
Massively improves performance of encoding and decoding (~5+x faster for unencoded data >= 10 bytes long) via addition of fast loops at start of methods.
Does worsen memory usage of Decoder as now has to store a [4][256]u32 fast lookup array, but likely worthwhile for this performance increase - if wanting to provide a lower memory usage decoder, may be worth having a fast/slow variant.
Idea behind the fast lookup table is simply to store pre-shifted data as an int based on position in 4 byte block, then just need to bitwise OR each byte in block.
This fast lookup table is also currently being instantied for DecoderWithIgnore as this holds a Decoder despite not using the fast lookup - maybe worth separating these two to avoid this. I did attempt to improve ignore decoder using fast lookup …
> std.base64: Improve Encoder/Decoder performance

- lib/std/Build.zig
- lib/std/Build/Step/Compile.zig
- src/Compilation.zig
- src/main.zig
This is one option for addressing https://github.com/ziglang/zig/issues/17406 (it is option 3 in https://github.com/ziglang/zig/issues/17406#issuecomment-1752219196). See that issue for some more details.
An embedded manifest file is really just XML data embedded as a `RT_MANIFEST` resource (ID = 24). Typically, the Windows-only 'Manifest Tool' (`mt.exe`) is used to embed manifest files, and `mt.exe` also seems to perform some transformation of the manifest data before embedding, but in testing it doesn't seem like the transformations are necessary to get the intended result.
So, to handle embedding manifest files, Zig now takes the following approach:
- Generate a .rc file with the contents `1 24 "path-to-manifest.manifest"`
- Compile that generated .rc file into a .res file
- Link the …
> Add preliminary support for Windows `.manifest` files

- src/Compilation.zig
- src/Module.zig
- src/main.zig
- src/type.zig
- src/value.zig
I chose to use a CLI argument instead of a const in the root file since changing it would invalidate most functions in an incremental compilation.
Closes #786
> Make distinct error limit configurable

- src/link/MachO.zig
- src/main.zig
Pull request #16888 removed searching for libraries with no extensions when linking frameworks... this adds that feature back.
This fixes #17294.
> Fix some frameworks not linking macos

- src/arch/x86_64/CodeGen.zig
Added to #17556, this fixes a bug with text in [tetris](https://github.com/andrewrk/tetris) when compiled with the x86_64 backend:
My patch for reference:
```diff
diff --git a/build.zig b/build.zig
index 3500b0c..61213ab 100644
--- a/build.zig
+++ b/build.zig
@@ -6,6 +6,7 @@ pub fn build(b: *Build) void {
const optimize = b.standardOptimizeOption(.{});
const use_llvm = b.option(bool, "use-llvm", "use the LLVM backend");
+    const use_lld = b.option(bool, "use-lld", "use the LLD linker");
const exe = b.addExecutable(.{
.name = "tetris",
@@ -14,11 +15,15 @@ pub fn build(b: *Build) void {
});
exe.use_llvm = use_llvm;
-    exe.use_lld = use_llvm;
+    exe.use_lld = use_lld;
+    exe.single_threaded = true;
+    exe.pie = true;
exe.linkLibC();
exe.linkSystemLibrary("glfw"); …
```
> x86_64: fix C abi argument passing in memory

- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Lower.zig
- src/arch/x86_64/Mir.zig
- src/codegen.zig
- src/link/Dwarf.zig
- src/link/Elf.zig
- src/link/Elf/Atom.zig
- src/link/Elf/Object.zig
- src/link/Elf/SharedObject.zig
- src/link/Elf/Symbol.zig
- src/link/Elf/ZigModule.zig
- src/link/Elf/eh_frame.zig
- src/link/Elf/synthetic_sections.zig
- test/link/elf.zig
Instead of saying  what it can do, let me say what is missing:
> elf: port 99% of zld ELF linker to Zig proper

- lib/std/os/windows.zig
Without this flag, the subsequent call to `NtDeviceIoControlFile` can return `PENDING`.
> windows: fix ReadLink not using a synchronous file handle

- lib/std/fs.zig
- lib/std/mem.zig
- src/Package/Fetch.zig
- src/main.zig
> Package.Fetch: normalize path separators in symlinks

- src/Sema.zig
- test/behavior/pointers.zig
- test/cases/compile_errors/@intFromPtr_with_bad_type.zig
It would make a lot more sense if we prevented it from accepting pointers to comptime-only types.
> Sema: disallow @intFromPtr to accept comptime-only types

- src/Package/Fetch.zig
Resolves #14299.
I have tested this with `zig fetch` on a local `.tar.zst` archive, but I'm not aware of any code forges online that produce zstandard compressed archives. As I haven't been able to test against code forges I have not added any http content type recognition - should I just add `application/zstd` and/or `application/tar+zstd` or leave it until someone needs it in the future?
> package fetching: support .tar.zst archives

- lib/std/zig/Ast.zig
- lib/std/zig/render.zig
- src/translate_c/ast.zig
Currently, when parsing an ast in `.zon` mode, `renderToArrayList` fails in `rootdecls`:
```
thread 1219690 panic: index out of bounds: index 2863311530, len 7
/home/tobi/zig/0.12.0-dev.929+a126afa1c/files/lib/std/zig/Ast.zig:192:27: 0x2aa9da in rootDecls (zbuild)
return tree.extra_data[nodes_data[0].lhs..nodes_data[0].rhs];
^
/home/tobi/zig/0.12.0-dev.929+a126afa1c/files/lib/std/zig/render.zig:33:66: 0x25dba6 in renderTree (zbuild)
try renderMembers(buffer.allocator, ais, tree, tree.rootDecls());
^
/home/tobi/zig/0.12.0-dev.929+a126afa1c/files/lib/std/zig/Ast.zig:119:46: 0x23cd9f in renderToArrayList (zbuild)
return @import("./render.zig").renderTree(buffer, tree);
^
/home/tobi/repos/zbuild/src/build/ZBuild.zig:109:34: 0x23a859 in zon (zbuild)
try ast.renderToArrayList(&out_buf);
``` …
> Fix rendering ast in zon mode

- src/introspect.zig
- src/libc_installation.zig
- src/main.zig
- src/print_env.zig
- src/resinator/compile.zig
- src/resinator/preprocess.zig
Currently it is not very convenient to extract a single environment variable from `zig env`.
An example using the shell: `zig env | jq -r .lib_dir`.
Update print_env.zig so that, when args is not empty, print each environment variable associated with an argument.
An updated example: `zig env lib_dir`.
Unrecognized environment variables are ignored.
> zig env: add support for line based output

- src/Compilation.zig
* Default to off when strip=true
* Report an error when explicitly enabled but not supported for the target
> compiler: better default for valgrind

- src/Compilation.zig
Before this commit, the logic would fail with a "LTO not available" error if the user set `-fno-lto` which doesn't make sense. This commit corrects the logic to understand when the user is explicitly requesting to turn LTO off.
> compiler: fix LTO availability logic

- lib/std/Build.zig
So that if you pass `--search-prefix` to `zig build` it affects all packages in the dependency tree.
> std.Build: make dependencies inherit `--search-prefix`

- CMakeLists.txt
- src/link/Elf.zig
- src/link/Elf/Archive.zig
- src/link/Elf/LdScript.zig
- src/link/Elf/Object.zig
- src/link/Elf/SharedObject.zig
Oh, and parse GNU ld scripts as system lib indirection - I mean who even thought of that to make `libc.so` an ld script, seriously...
This ticks off two more check boxes from #17556:
> elf: link against libc installation

- src/codegen/llvm/Builder.zig
- src/link.zig
Without this change, I hit a crash in LLVM while cross-linking libcxx for arm with optimizations.  I didn't look too closely at what codepath in LLVM requires this, but the fact that I found one suggests the target should just always be initialized.
> link: initialize LLVM before calling the LLVM API

- doc/build.zig.zon.md
- src/Package/Manifest.zig
Solves #14475 -> Adds support for a new optional field "minimal_zig_version" in build.zig.zon.
> #14475 minimal_zig_version in build.zig.zon

- lib/std/Build/Step/Compile.zig
- src/Compilation.zig
- src/introspect.zig
- src/resinator/compile.zig
- src/resinator/errors.zig
- src/resinator/lex.zig
- src/resinator/literals.zig
- src/resinator/preprocess.zig
- src/resinator/source_mapping.zig
`src/` changes:
- Fix `ignore_include_env_var` not being set when preprocessing `.rc` files. Closes #17585
- Make using the `/p` or `/:no-preprocess` options for an `.rc` file an error when going through `zig build-exe`/`zig build`/etc
`src/resinator` changes:
- Revert the `INCLUDE` env var related changes in 09dea957ed74f87b7f5f88bc2c760f3f93d0165a since `INCLUDE` is now never read by anything except `zig rc`
- Added proper error handling when failing to open the CWD for the `.rc` compilation (an improvement on a change in 09dea957ed74f87b7f5f88bc2c760f3f93d0165a)
- Fixes for various bugs found when fuzz testing
- Made it use platform-specific delimiters when parsing `INCLUDE`
> resinator: Fix `INCLUDE` var handling and sync with upstream

- doc/langref.html.in
Update to match current outputs of init-exe and init-lib.
> langref: bring build.zig examples up to date

- lib/libc/include/generic-glibc/malloc.h
- lib/libc/include/generic-glibc/stdlib.h
Here's the glibc commit that adds reallocarray to glibc: https://sourceware.org/git/?p=glibc.git;a=commit;h=2e0bbbfbf95fc9e22692e93658a6fbdd2d4554da
The reallocarray symbol is declared in both stdlib.h and malloc.h.
Fix #17607
> glibc headers: reallocarray added to glibc in v2.26

- lib/std/hash_map.zig
Without this change, constructing a Context/Adapter for a `const` string table requires a `@constCast`.
> std.hash_map: add `const` attribute to StringIndexContext.bytes and StringIndexAdapter.bytes

- lib/build_runner.zig
- src/main.zig
> std.Build: add --seed argument to randomize step dependencies spawning

- src/link/Elf.zig
- src/link/Elf/Atom.zig
- src/link/Elf/synthetic_sections.zig
- test/link/elf.zig
and discover a QEMU bug while at it: #17619
> elf: actually check for dynamic executables

- src/InternPool.zig
There is this `common` prefix which was not getting passed in all union tags of pointer vals, presumably making InternPool slower for pointer values.
> InternPool: fix incomplete hash of pointer values

- lib/std/target.zig
Currently, Zig uses the oldest Debian release that is still under LTS for the default version minimum. This is now Debian 10 (Buster), with long-term support until 2024-06-30.
Debian Buster uses Linux 4.19 and glibc 2.28.
For the default version maximum, Zig uses the newest stable Linux version, which is currently 6.5.7.
Citations:
* https://www.debian.org/News/2019/20190706
* https://packages.debian.org/source/buster/glibc
* https://kernel.org/
Previous update commit: 1530203c804db7e5abd7d6eac05cfbe449d30aea
> std.Target: update default Linux cross-compiling version

- lib/std/os/linux/io_uring.zig
Implements splice functionality for sending data from an fd to another, with one fd a pipe.
Can for example be used to implement sendfile via an intermediate pipe.
man page: https://man7.org/linux/man-pages/man3/io_uring_prep_splice.3.html
liburing implementation: https://github.com/axboe/liburing/blob/master/src/include/liburing.h
> linux.io_uring: Implement splice functions

- lib/std/crypto/ff.zig
RSA exponents are typically 3 or 65537, and public.
For those, we don't need to use conditional moves on the exponent, and precomputing a lookup table is not worth it. So, save a few cpu cycles and memory for that common case.
For safety, make `powWithEncodedExponent()` constant-time by default, and introduce a `powWithEncodedPublicExponent()` function for exponents that are assumed to be public.
With `powWithEncodedPublicExponent()`, short (<= 36 bits) exponents will take the fast path.
> crypto.ff: faster exponentiation with short/public exponents

- lib/std/os.zig
supersedes #15592
closes #9688
> std.os: do nothing when calling fchdir with AT_FDCWD

- lib/std/rand.zig
This removes two fairly old asserts referencing some LLVM issue which I was not able to reproduce anymore.
There were two functions that needed updating, because they had hardcoded 32 and 64-bit ints, but thankfully these specific sizes aren't required for the algorithms in either case, so this is actually a negative LoC change.
---
Had a thought while working on this. In lieu of a proper proposal (which I am too lazy to make, so I will try and hijack this PR instead, sorry and feel free to skip this):
`std.rand.Random` is an awkward namespace.
It could instead be moved to `std.Random`, likewise all RNGs and free functions previously found in `std.rand` could be moved under this new `std.Random`.
`std.rand` would be deprecated and eventually removed entirely. This is very similar to the …
> std.rand: Support integers with >64 bits in more functions

- src/link/Dwarf.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/Wasm.zig
`Dwarf.zig` now allows selecting appropriate DWARF format at runtime via `Dwarf.Format = enum { dwarf32, dwarf64 }`. The actual format has no impact on the pointer size - DWARF64 format should only ever be selected for debug sections that exceed 4GB in file size, and even then it is not very well supported by the debuggers out there. For example, `lldb` still refuses to correctly load CUs in DWARF64 format. For that reason, I am changing generated DWARF targeting ELF to DWARF32. This makes it now possible to step through code with source line annotations in `lldb` on Linux. Please note that if we ever do exceed 4GB in file size for debug sections, it is now trivial to switch from DWARF32 to DWARF64. Finally, this significantly cleans up and unifies emitting DWARF between ELF and MachO.
Oh …
> dwarf: decouple DWARF format from target pointer size + misc fixes

- lib/std/Build.zig
- lib/std/Build/Step/RemoveDir.zig
The init() function initialize a struct on the stack. This can cause issues if the struct is used later, like this example:
```zig
// build.zig
var rmdir = std.Build.Step.RemoveDir.init(b, "tmp"); 
const tls = b.step("rmdir", "rmdir");
tls.dependOn(&rmdir.step);
}
```
Here the `rmdir` variable becomes invalid after the build() function returns, but is still used by `tls`.
This commit changes RemoveDir to use create() instead, allocating the struct on the heap rather than stack.
Also, it makes RemoveDir consistent with other build steps.
> std.Build: use create() instead of init() for Step.RemoveDir

- lib/std/math.zig
Fixes #15038.
The goal here is to guarantee lossyCast() is panic-free and always safe.
> Return zero for NaN-to-int lossy casts

- src/link/Elf.zig
On Ubuntu 22.04 (jammy), this code path was triggered when linking against system libc, and this patch makes it report nice linker errors rather than only printing `error: FileNotFound` to stderr.
> link.Elf: report file not found error

- lib/std/Build.zig
`Step.Compile.addAssemblyLazyPath` no longer exists, this issue is present in 0.11.0
> fix `std.Build.addAssembly`

- lib/std/fs.zig
- lib/std/fs/path.zig
- lib/std/fs/test.zig
Uses a single NtCreateFile syscall on windows, falling back if the parent directory does not exist.
Closes ziglang#12474. Thanks to @joedavis and @matu3ba.
> #12474: std.fs.Dir.makeOpenPath: optimize case, if path already exists

- src/libtsan.zig
> libtsan: do not set PIE

- src/codegen/spirv.zig
- src/codegen/spirv/Assembler.zig
- src/codegen/spirv/Cache.zig
- src/codegen/spirv/Module.zig
- test/behavior/bugs/12000.zig
- test/behavior/bugs/1735.zig
- test/behavior/bugs/1914.zig
- test/behavior/bugs/2006.zig
- test/behavior/bugs/3007.zig
- test/behavior/bugs/6947.zig
- test/behavior/bugs/7325.zig
- test/behavior/error.zig
- test/behavior/eval.zig
- test/behavior/generics.zig
- test/behavior/null.zig
- test/behavior/optional.zig
- test/behavior/ptrcast.zig
- test/behavior/struct.zig
- test/behavior/struct_contains_null_ptr_itself.zig
- test/behavior/struct_contains_slice_of_itself.zig
- test/behavior/union.zig
This rewrites the Cache for use with recursive pointers. The whole mechanism is a bit yucky, but there doesn't seem to be a good alternative.
> spirv: recursive pointers

- lib/std/unicode.zig
This changes optimized x86_64 from
```
20bbe0:	f3 0f 6f 07          	movdqu (%rdi),%xmm0
20bbe4:	66 0f 70 c8 ee       	pshufd $0xee,%xmm0,%xmm1
20bbe9:	66 0f eb c8          	por    %xmm0,%xmm1
20bbed:	66 48 0f 7e c9       	movq   %xmm1,%rcx
20bbf2:	48 85 c1             	test   %rax,%rcx
20bbf5:	75 17                	jne    20bc0e <std_utf8ValidateSlice+0x4e>
```
to
```
20bcd0:	f3 0f 6f 07          	movdqu (%rdi),%xmm0
20bcd4:	66 0f d7 c0          	pmovmskb %xmm0,%eax
20bcd8:	85 c0                	test   %eax,%eax
20bcda:	75 17                	jne    20bcf3 <new_utf8ValidateSlice+0x33>
```
While this isn't a complete wash performance-wise for some reason, I also have an ulterior motive of making it easier to codegen in the x86_64 backend. …
> std: slightly improve codegen of `std.unicode.utf8ValidateSlice`

- lib/std/RingBuffer.zig
- lib/std/compress/zstandard.zig
- lib/std/compress/zstandard/decode/block.zig
Metron benchmarks on M1 mac, testing time to write a slice to buffer then read it. Number corresponds to input size in bytes. RingBuffer capacity > 500.
- masterRead = read() function, which still exists following proposed changes
- newRead = readFirst()/readLast(), newly implemented.
- masterWrite = master writeSlice() function
- newWrite = modified writeSlice() function
Can see a slight loss in performance for small read/write sizes, mostly for the new read methods, however old read method still exists so not an issue. New write method is strictly an improvement. Huge improvements for large read/write sizes. Have not benchmarked writing data with a length greater than RingBuffer capacity but new writeSlice() method will be extremely efficient here as it skips data that will get …
>  std.RingBuffer: Implement mem.copy read/write 

- build.zig
- lib/std/Build.zig
- lib/std/Build/Step.zig
- lib/std/Build/Step/Compile.zig
- lib/std/Build/Step/Run.zig
- lib/std/child_process.zig
- lib/std/zig/system/darwin.zig
- src/libc_installation.zig
- src/main.zig
- test/standalone/windows_spawn/main.zig
- tools/docgen.zig
- tools/generate_linux_syscalls.zig
- tools/update_clang_options.zig
- tools/update_cpu_features.zig
Justification: exec, execv etc are unix concepts and portable version should be called differently.
Do no touch non-Zig code. Adjust error names as well, if associated. Closes #5853.
> child_process + Build: rename exec to run + all related code

- lib/std/Uri.zig
- lib/std/crypto/tls/Client.zig
- lib/std/http.zig
- lib/std/http/Client.zig
- lib/std/http/Headers.zig
- lib/std/http/Server.zig
- lib/std/http/protocol.zig
- lib/std/std.zig
- src/Package/Fetch.zig
- src/Package/Fetch/git.zig
- src/main.zig
- test/standalone/http.zig
Proxies are now separated, so HTTP and HTTPS requests can be diverted thru different proxies. Connection pool now accepts a `Allocator` instead of a `*Client` for allocations. Now passes around a `*Connection` instead of a `*ConnectionPool.Node`.
Writes are now buffered, and reads now use iovecs to reduce syscalls.
Adds `client.loadDefaultProxies` to loads proxy information from common
environment variables (http_proxy, HTTP_PROXY, https_proxy, HTTPS_PROXY,
all_proxy, ALL_PROXY).
- no_proxy and NO_PROXY are currently unsupported.
`std.Uri` has expanded formatting capabilities so to enable more control over what appears in the output.
`std.crypto.tls.Client.readv` was evidently not tested, it was missing a parameter.
Removed `http_connection_pool_size`, Added `http_disable_tls`
- …
> std.http: more proxy support, buffer writes, tls toggle

- doc/langref.html.in
- src/AstGen.zig
- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
- src/arch/wasm/CodeGen.zig
- src/codegen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/llvm/Builder.zig
- src/codegen/spirv.zig
- src/main.zig
- src/type.zig
- src/value.zig
First attempt #17532 was rebased from a pre-InternPool version so I didn't notice these changes with no `TODO revisit` comment.
Closes #786
Includes #17627
> Make distinct error limit configurable (attempt #2)

- lib/std/SemanticVersion.zig
- lib/std/zig/CrossTarget.zig
- lib/std/zig/system/NativeTargetInfo.zig
- lib/std/zig/system/darwin/macos.zig
In most cases "GLIBC_2.X" strings and `/lib/libc-2.x.so` files do not contain third (`patch`) field, which causes std.SemanticVersion.parse function to return error. To fix this, we reuse [now-public] std.zig.CrossTarget.parseVersion function, which accounts for this third field and makes it 0 in case it was not found. This new behaviour is similar to std.builtin.Version.parse, which was removed in https://github.com/ziglang/zig/commit/6e84f469904a24615a6721265a88ad8dcb4ed83a
Fixes regression from https://github.com/ziglang/zig/commit/6e84f469904a24615a6721265a88ad8dcb4ed83a and https://github.com/ziglang/zig/pull/13998 .
Related: https://github.com/ziglang/zig/issues/17626 . Results with `zig end`:
Before: `"target": "x86_64-linux.6.5.7...6.5.7-gnu.2.19",`
After: `"target": …
> std.zig.system.NativeTargetInfo: fix glibc version parsing

- src/Package/Fetch.zig
these short extensions are common in a lot of
places, and should be treated like their double
versions.
Example:
[Python Source code Releases](https://www.python.org/downloads/source/)
> add Fetch support for short compressed tar ext

- lib/std/mem.zig
- src/InternPool.zig
- src/Module.zig
- src/Sema.zig
- src/TypedValue.zig
- src/arch/wasm/CodeGen.zig
- src/codegen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/type.zig
- src/value.zig
See commit messages for details.
Depends on #17688.
> Remove `InternPool.Key.runtime_value`, clean up Sema value resolution functions

- lib/std/zig/Ast.zig
The rhs can be omitted eg `0..`
Working on an ast visitor and assuming the rhs was always valid created an infinite loop...
> Update comment on for_range in Ast

- src/Compilation.zig
- src/Sema.zig
- src/codegen/c.zig
- src/link/C.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/Wasm.zig
After this, down to only 4 uses of startAnonDecl() and 3 of them are for comptime value mutation.
```
$ grep -RI startAnonDecl src
src/Sema.zig:    pub fn startAnonDecl(block: *Block) !WipAnonDecl {
src/Sema.zig:    var anon_decl = try block.startAnonDecl(); // TODO: comptime value mutation without Decl
src/Sema.zig:        var anon_decl = try block.startAnonDecl(); // TODO: comptime value mutation without Decl
src/Sema.zig:        var anon_decl = try block.startAnonDecl(); // TODO: export value without Decl
src/Sema.zig:    var anon_decl = try block.startAnonDecl(); // TODO: comptime value mutation without Decl
```
> Sema: move remaining anon decls to new mechanism

- lib/std/Uri.zig
- lib/std/http/Client.zig
This adds scheme guessing when loading proxies, such that `HTTP_PROXY=127.0.0.1` and such are valid now and it behaves identically to `HTTP_PROXY=http://127.0.0.1`. Additionally fixed a typo that was causing loadDefaultProxies to never populate the https_proxy.
> std.http.Client: add proxy scheme guessing, fix typo

- lib/std/os/linux.zig
- lib/std/os/linux/io_uring.zig
Mainly updates linux.zig to match io_uring.h. Small improvement to make splice function more easily usable.
io_uring.zig can be updated to match the liburing.h diff [here](https://github.com/axboe/liburing/compare/liburing-2.1...master) if someone wants to put in the effort, an easy but tedious task (+ needs testing)
> std.linux: Update io_uring structs and consts for kernel 6.3.8 

- lib/std/io.zig
- lib/std/io/test.zig
add error.EndOfStream to readEnum() and isBytes() so that users can catch these errors.  this also prevents them from panicing with 'invalid error value' on EndOfStream.
test both methods.  before these changes the new test would panic.
closes #17733
> GenericReader error set fixes

- lib/std/zig/Ast.zig
The @"while" is still used if cont expr is missing but still has an else expr.
Edit: Sorry for all the noise, hopefully this is the last :)
> Update comment on ast while tag

- lib/std/zig/Ast.zig
Assert failed here while visiting zig's source ast... The slice end can be omitted
> Update slice_sentinel comment

- src/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
- src/link.zig
- src/link/C.zig
- src/link/Coff.zig
- src/link/Elf.zig
- src/link/MachO.zig
- src/link/NvPtx.zig
- src/link/Plan9.zig
- src/link/SpirV.zig
- src/link/Wasm.zig
- test/behavior/export.zig
The main motivating change here is to prevent the creation of a fake Decl object by the frontend in order to `@export()` a value.
Instead, `link.updateDeclExports` is renamed to `link.updateExports` and accepts a tagged union which can be either a Decl.Index or a InternPool.Index.
With this, the only remaining calls to startAnonDecl() are for comptime value mutation:
```
$ grep -RI startAnonDecl ../src
../src/Sema.zig:    pub fn startAnonDecl(block: *Block) !WipAnonDecl {
../src/Sema.zig:    var anon_decl = try block.startAnonDecl(); // TODO: comptime value mutation without Decl
../src/Sema.zig:        var anon_decl = try block.startAnonDecl(); // TODO: comptime value mutation without Decl
../src/Sema.zig:    var anon_decl = try block.startAnonDecl(); // TODO: comptime value mutation …
```
> link: support exporting constant values without a Decl

- src/Autodoc.zig
- src/Compilation.zig
- src/Module.zig
- src/Zir.zig
- src/main.zig
This field had the wrong type. It's not a `Zir.Inst.Index`, it's actually a `Zir.OptionalExtraIndex`. Also, the former is currently aliased to `u32` while the latter is a nonexhaustive enum that gives us more type checking.
This commit is preparation for making this field non-optional. Now it can be changed to `Zir.ExtraIndex` and then the compiler will point out all the places that the non-optional assumption is being violated.
> frontend: make Decl.zir_decl_index typed

- lib/std/mem.zig
- src/AstGen.zig
- src/Autodoc.zig
- src/InternPool.zig
- src/Module.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
This commit starts by making `Zir.Inst.Index` a nonexhaustive enum rather than a `u32` alias for type safety purposes, and the rest of the changes are needed to get everything compiling again.
As a bonus, break the standard library.
Depends on #17758.
> make Zir.Inst.Index typed

- lib/std/os/windows.zig
- lib/std/os/windows/kernel32.zig
This pull request addresses issues I have found with `std.os.windows` while using it.
- Added `PROC` type
- Added `HRESULT_CODE` macro
- Moved `wglCreateContext` from gdi32
- Moved `wglMakeCurrent` from gdi32
- Fixed `wglCreateContext` using incorrect types
- Fixed `wglMakeCurrent` using incorrect types
- Added zig wrapper for `wglCreateContext`
- Added zig wrapper for `wglMakeCurrent`
- Added `wglDeleteContext` + zig wrapper
- Added `wglGetProcAddress`
- Added `DwmFlush` + zig wrapper
- Added constants required for `PIXELFORMATDESCRIPTOR`
- Fixed `SetPixelFormat` using incorrect types
- Added zig wrapper for `SetPixelFormat` 
- Fixed `ChoosePixelFormat` using incorrect types
- Added zig wrapper for `ChoosePixelFormat`
- Added `DescribePixelFormat` + zig wrapper
- Moved `wglCreateContext` …
> std.os.windows additions and fixes

- src/InternPool.zig
- src/Module.zig
- src/Sema.zig
- src/type.zig
- test/behavior/union.zig
- test/cases/compile_errors/union_depends_on_pointer_alignment.zig
This is just the union alignment changes extracted from https://github.com/ziglang/zig/pull/17490. 
Changes:
- Add `resolveUnionAlignment`, to resolve a union's alignment only, without triggering layout resolution. 
- Update `resolveUnionLayout` to cache size, alignment, and padding. `abiSizeAdvanced` and `abiAlignmentAdvanced` now use this information instead of computing it each time.
> sema: add union alignment resolution

- CMakeLists.txt
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/codegen.zig
- src/link/Elf.zig
- src/link/Elf/Atom.zig
- src/link/Elf/Symbol.zig
- src/link/Elf/ZigObject.zig
- src/link/Elf/file.zig
`ZigObject` is effectively equivalent to the final stage of your typical compiler's pipeline when it emits a relocatable object file.
> elf: rename ZigModule to ZigObject and move all codegen hooks into it

- lib/std/unicode.zig
This takes the ASCII fast path added for UTF-8 validation in https://github.com/ziglang/zig/pull/17329 (plus the changes in https://github.com/ziglang/zig/pull/17659) and applies the same concept to both directions of UTF-8 <-> UTF-16 conversion.
I'm new to SIMD stuff so feedback on the implementation is appreciated.
<details>
<summary>Benchmark code</summary>
```zig
const ITERATIONS = 20_000;
try benchmark(
"short.ascii",
"it's over 9000!!",
16,
);
std.debug.print("\n", .{});
try benchmark(
"long.ascii",
"Lorem ipsum dolor sit amet, pri legere suscipit repudiare at, cu vix aliquip pertinacia quaerendum, in eam dicat cetero eripuit. Duo odio nonumy viderer at, et sea vidit dolor animal, has persius conceptam id. Vide idque copiosae ut qui, …
```
> std.unicode: Add ASCII fast path to UTF-16 <-> UTF-8 conversion functions

- lib/std/http/Client.zig
- lib/std/http/Server.zig
While learning `std.http` server and client, noticed some docs referenced nonexistent names. Traced it to a commit in #17407. Changed the docs to account for the renames.
> std.http: account for renames in docs

- lib/std/os/linux.zig
See [upstream](https://github.com/torvalds/linux/blob/8bc9e6515183935fa0cccaf67455c439afe4982b/include/uapi/linux/io_uring.h#L432)
> Fix regressing #17290 from #17734

- lib/test_runner.zig
- src/arch/wasm/CodeGen.zig
- test/behavior/bugs/1851.zig
- test/behavior/struct.zig
A bug was discovered by #17802, where in the Wasm backend it didn't correctly bitcast values between array and scalar types. This fixes that and re-enables the behavior tests as well as the default test-runner.
> wasm - fix bitcasting between arrays and scalar types

- lib/std/start.zig
Partial follow up to https://github.com/ziglang/zig/pull/17763#discussion_r1375249495 (cc @e4m2)
`nCmdShow` is a parameter of WinMain that "Controls how the window is to be shown."
From the added comment:
```zig
// This makes Zig mostly match the nCmdShow behavior of a C program with a WinMain symbol:
// - With STARTF_USESHOWWINDOW set in STARTUPINFO.dwFlags of the CreateProcess call:
//   - Compiled with subsystem:console -> nCmdShow is always SW_SHOWDEFAULT
//   - Compiled with subsystem:windows -> nCmdShow is STARTUPINFO.wShowWindow from
//     the parent CreateProcess call
// - With STARTF_USESHOWWINDOW unset:
//   - nCmdShow is always SW_SHOWDEFAULT
//
// TODO: Figure out how to check the subsystem and use it to match the above
//       behavior, or intentionally avoid matching the …
```
> start: Make nCmdShow better match how Windows sets it

- lib/std/os/windows/ntdll.zig
- lib/std/start.zig
Credit to @e4m2 for identifying which `ntdll` functions/PEB fields could be used to replace the `kernel32` functions (https://github.com/ziglang/zig/pull/17763#discussion_r1375249495). Progress towards https://github.com/ziglang/zig/issues/1840
Functionality is equivalent before and after:
Test code:
`winmain-zig.zig`:
```zig
pub fn wWinMain(
inst: std.os.windows.HINSTANCE,
prev: ?std.os.windows.HINSTANCE,
cmd_line: std.os.windows.LPWSTR,
cmd_show: i32,
) std.os.windows.INT {
std.debug.print("inst: {}\n", .{inst});
std.debug.print("prev: {?}\n", .{prev});
const cmd_line_slice = std.mem.span(cmd_line);
std.debug.print("cmd_line: {}\n", .{std.unicode.fmtUtf16le(cmd_line_slice)});
std.debug.print("cmd_show: {}\n", .{cmd_show});
return 0;
}
```
```
> …
```
> start.zig: Replace kernel32 usage with ntdll/PEB

- lib/std/zig/system/arm.zig
before this change if someone were to run apple silicon on e.g. Asahi linux zig would never search for apple chips and default to a generic cpu. the part numbers for the M1 and implementer number were found by reading `/proc/cpuinfo` on an M1 running asahi linux, the numbers for the M2 i found [here](https://lkml.kernel.org/kvm/9d00b09a-044b-55c6-9596-dd04d5b0ca19@huawei.com/T/) which i cannot confirm but the numbers fall in line with the M1 so i think its safe to trust.
i can do a follow up for the M3 if/when I can find the info I need and it's added to zigs list of targets
> add apple chips to arm CPU detection

- src/Sema.zig
> Sema: use correct error bit length when emitting error_set_has_value safety checks

- src/Compilation.zig
- src/Module.zig
- src/Sema.zig
This incremental compilation logic will need to be reworked so that it does not depend on buried pointers - that is, long-lived pointers that are owned by non-top-level objects such as Decl.
In the meantime, this fixes memory leaks since the memory management of these dependencies has bitrotted.
> frontend: rip out Decl dependencies

- lib/std/compress/zstandard/decode/block.zig
This reverts a change introduced in #17400 causing a bug when decompressing an RLE block into a ring buffer.
RLE blocks contain only a single byte of data to copy into the output, so attempting to copy a slice causes buffer overruns and incorrect decompression.
This bug only arises when using the allocating `decodeAlloc` (or lower-level APIs it uses).
Better testing coverage for zstandard could have caught this bug in CI, but several things would have to change. Currently the allocating APIs are not covered by stdlib tests, only the non-allocating top-level API is tests. In addition, the zstandard data that is decompressed for testing is two copies of the zstandard RFC (at different compressions levels). These both contain only a single frame with a single block of type 'compressed', so …
> zstandard: fix incorrect RLE decompression into ring buffer

- build.zig
- lib/build_runner.zig
- lib/std/bit_set.zig
- lib/std/zig/Ast.zig
- lib/std/zig/render.zig
- src/main.zig
- src/reduce.zig
- src/reduce/Walk.zig
- stage1/config.zig.in
This adds a new tool to the zig toolchain inspired by [llvm reduce](https://www.llvm.org/docs/CommandGuide/llvm-reduce.html). When I say "inspired" I mean that I find the interface impenetrable, the documentation misleading at best, and the overall experience barely accessible to even the most advanced programmers.
Anyway, this is a tool that helps you take a large test case, and in an automated fashion, delete the irrelevant bits from it until the only thing left is a minimal reproducer, perfect for filing a compiler bug report.
1. Walk the AST of the source file looking for independent reductions and collecting them all into an array list.
2. Randomize the list of transformations. A future enhancement will add priority weights to the sorting but for now they are completely shuffled.
3. …
> introduce `zig reduce` subcommand

- lib/std/array_hash_map.zig
- lib/std/zig/render.zig
- src/reduce.zig
- src/reduce/Walk.zig
Follow-up from  #17852. Still using #17618 as a motivating example, even though the bug has been solved.
With these changes, we arrive at the following reduction after 12 minutes:
```zig
const Compilation = struct {
const Compilation2 = @This();
const std2 = @import("std");
const Allocator = std2.mem.Allocator;
const data_structures = @import("data_structures.zig");
const BlockList = data_structures.BlockList;
const StringHashMap = data_structures.StringHashMap;
const StringArrayHashMap = data_structures.StringArrayHashMap;
base_allocator: Allocator,
build_directory: std2.fs.Dir,
pub fn init(allocator: Allocator) !*Compilation2 {
_ = allocator;
@trap();
}
pub const Module = struct {
main_package: *Package,
import_table: StringArrayHashMap(*File) = .{},
files: BlockList(File) = .{},
pub …
```
> zig reduce: support inlining `@import` and more

- doc/langref.html.in
- lib/std/Build/Step/Compile.zig
- lib/std/start.zig
- src/Compilation.zig
- src/link.zig
- src/link/Wasm.zig
- src/main.zig
- test/link/elf.zig
- test/link/macho/entry/build.zig
- test/link/macho/entry_in_dylib/build.zig
- test/link/wasm/archive/build.zig
- test/link/wasm/basic-features/build.zig
- test/link/wasm/bss/build.zig
- test/link/wasm/export-data/build.zig
- test/link/wasm/export/build.zig
- test/link/wasm/extern-mangle/build.zig
- test/link/wasm/function-table/build.zig
- test/link/wasm/infer-features/build.zig
- test/link/wasm/producers/build.zig
- test/link/wasm/segments/build.zig
- test/link/wasm/shared-memory/build.zig
- test/link/wasm/stack_pointer/build.zig
- test/link/wasm/type/build.zig
As discussed in https://github.com/ziglang/zig/pull/16949#issuecomment-1692779628 this changes the invocation when building for the WebAssembly target. Users who previously used `-dynamic` in combination with `build-lib` will now be required to use `build-exe` in combination with `-fno-entry`. This is the same behavior as found in other compilers such as Clang and Rust. `-fno-entry` will tell the linker there's no entry point available and therefore the built binary can be used, for instance, in a browser where no entry point is expected.
This change also now correctly passes the `--shared` and `--pie` linker flags to wasm-ld when enabled in the frontend. e.g. when the user used the combination of `build-lib -dynamic` or `build-exe -fPIE`.
Closes #16937 
Closes #16938 
Closes #11045
> wasm-linker: implement `-fno-entry` and correctly pass `--shared` and `--pie` when given

- src/Compilation.zig
- src/target.zig
The logic in 509be7cf1f10c5d329d2b0524f2af6bfcabd52de assumed that `use_llvm` meant that the LLVM backend would be used, however, use_llvm is false when there are no zig files to compile, which is the case for zig cc. This logic resulted in `-fsingle-threaded` which made libc++ fail to compile for C++ code that includes the threading abstractions (such as LLVM).
This is expected to fix the build-tarballs CI script that has been failing.
> frontend: fix -fsingle-threaded default detection logic

- src/Sema.zig
- test/behavior/destructure.zig
This was intended to work when destructuring was first implemented, and was just unintentionally missed out.
> Sema: allow destructuring vectors

- src/Sema.zig
- test/behavior/cast.zig
This code was previously tripping an assertion by not making this value used in the safety check a vector.
> Sema: emit @intCast safety check correctly for vectors

- src/AstGen.zig
- src/Autodoc.zig
- src/InternPool.zig
- src/Sema.zig
- src/arch/wasm/CodeGen.zig
- src/codegen/c.zig
- src/type.zig
- test/behavior/struct.zig
- test/behavior/union.zig
- test/cases/compile_errors/struct_depends_on_pointer_alignment.zig
This PR is based off of https://github.com/ziglang/zig/pull/17658.
The main goal of this PR was to resolve the circular dependency error you used to get when doing something like this:
```zig
const StructInner = extern struct {
outer: StructOuter = std.mem.zeroes(StructOuter),
};
const StructMiddle = extern struct {
outer: ?*StructInner,
inner: ?*StructOuter,
};
const StructOuter = extern struct {
middle: StructMiddle = std.mem.zeroes(StructMiddle),
};
test "circular dependency through pointer field of a struct" {
var outer: StructOuter = .{};
try expect(outer.middle.outer == null);
try expect(outer.middle.inner == null);
}
```
```
test\behavior\container_circular_dependency.zig:28:29: error: struct 'container_circular_dependency.StructMiddle' depends on itself
const StructMiddle = extern …
```
> sema: analyze struct field bodies in a second pass, to allow them to use the layout of the struct itself

- lib/std/math/big/int.zig
- lib/std/math/big/int_test.zig
fixes #17858
when the a value takes 0 bits, it will always be 0, by extension the square root will always be 0.
i also added a negative check that returns an `error.` because the current error is very misleading:
```
/home/dr/zig/lib/std/debug.zig:342:14: 0x222c22 in assert (test)
^
/home/dr/zig/lib/std/math/big/int.zig:1524:15: 0x2293ef in div (test)
assert(!y.eqlZero()); // division by zero
> Fix sqrt(0) panic in managed math

- doc/langref.html.in
- src/Sema.zig
- test/behavior/slice.zig
> sema: allow slicing [*]T without end

- lib/std/crypto/25519/curve25519.zig
The low-level `Curve25519.fromEdwards25519()` function assumed that the X/Y coordinates were not scaled (Z=1).
But this is not guaranteed to be the case.
In most real-world applications, the coordinates are freshly decoded, either directly or via the X25519.fromEd25519() function, so this is not an issue.
However, since we offer the ability to do that conversion after arbitrary computations, the assertion was not correct.
> Curve25519.fromEdwards25519(): don't assume normalized coordinates

- src/arch/x86_64/CodeGen.zig
- src/link/MachO/uuid.zig
With `./zig` being a compiler compiled with the x86_64 backend with #17931 applied:
```
$ ./zig build test-universal-libc --summary all
Build Summary: 39/43 steps succeeded; 4 skipped; 85/85 tests passed
test-universal-libc success
<...>
$ ./zig build test-c-abi --summary all
Build Summary: 88/91 steps succeeded; 3 skipped; 1594/2223 tests passed; 629 skipped
test-c-abi success
<...>
$ ./zig build test-compiler-rt --summary all
Build Summary: 34/37 steps succeeded; 3 skipped; 3664/3825 tests passed; 161 skipped
test-compiler-rt success
<...>
$ ./zig build test-behavior --summary all
Build Summary: 82/88 steps succeeded; 6 skipped; 63980/68269 tests passed; 4289 skipped
test-behavior success
<...>
$ ./zig build test-std --summary all
Build Summary: 83/90 steps succeeded; 7 skipped; …
```
> x86_64: pass more tests with an x86_64 backend compiled compiler

- lib/std/os/linux/io_uring.zig
Unsupported tests are now skipped on kernel 5.4:
```
uname -a
Linux d20 5.4.0-166-generic 
zig test lib/std/std.zig --zig-lib-dir lib --main-mod-path lib/std 2>&1 | cat
...
709/2616 test.nop... OK
710/2616 test.readv... OK
711/2616 test.writev/fsync/readv... OK
712/2616 test.write/read... SKIP
713/2616 test.splice/read... SKIP
714/2616 test.write_fixed/read_fixed... OK
715/2616 test.openat... SKIP
716/2616 test.close... SKIP
717/2616 test.accept/connect/send/recv... SKIP
718/2616 test.sendmsg/recvmsg... OK
719/2616 test.timeout (after a relative time)... SKIP
720/2616 test.timeout (after a number of completions)... OK
721/2616 test.timeout_remove... SKIP
722/2616 test.accept/connect/recv/link_timeout... SKIP
723/2616 test.fallocate... SKIP
724/2616 test.statx... SKIP
725/2616 …
```
> Fix io_uring tests on kernel 5.4

- src/link/Wasm.zig
- src/link/Wasm/Symbol.zig
Previously the symbol tag field would remain `undefined` until it was set during `flush`. However, the symbol's tag would be observed earlier than where it was being set. We now set it to the explicit tag `undefined` so this can be caught during debug. The symbol tag of a decl will now also be set right after `updateDecl` and `updateFunc`.
> wasm-linker: ensure symbol tag is set for decls

- lib/std/zig/Ast.zig
This changes ast.tokenLocation to scan for the first line before looking for the token. This avoids a lot of pointless adding on the loc.column. The speedup depends on the size of the file. For small files this can be slower but the time difference negligible, for normal sized files it is about 70% faster and can have meaningful time savings.  
```
[default] (warn): test/compile_errors.zig
[default] (warn):   old:  9.313ms
[default] (warn):   new:  3.004ms
[default] (warn):   diff: -6.309ms -67.75% faster
[default] (warn): test/c_abi/main.zig
[default] (warn):   old: 996.415ms
[default] (warn):   new: 305.051ms
[default] (warn):   diff: -691.364ms -69.39% faster
[default] (warn): test/llvm_targets.zig
[default] (warn):   old: 47.332ms
[default] (warn):   new:  8.905ms
[default] (warn): …
```
> Speed up ast.tokenLocation

- src/Sema.zig
- test/behavior/struct.zig
b3462b7 caused a regression in a third-party project, since it forced resolution of field initializers for any field call 'foo.bar()', despite this only being necessary when 'bar' is a comptime field.
See https://github.com/ziglang/zig/pull/17692#issuecomment-1802096734.
> Sema: do not force resolution of struct field inits when calling function pointer field

- src/Sema.zig
LLVM does this for us for `SysV` but not for `Win64`.  But even on `SysV`, we weren't providing signedness attributes, so it was still subtly wrong.
> Sema: implement vararg integer promotions

- src/AstGen.zig
- src/Autodoc.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
There are two optimizations here, which work together to avoid a pathological case.
The first optimization is that AstGen now records the result type of an array multiplication expression where possible. This type is not used according to the language specification, but instead as an optimization. In the expression '.{x} ** 1000', if we know that the result must be an array, then it is much more efficient to coerce the LHS to an array with length 1 before doing the multiplication. Otherwise, we end up with a 1000-element tuple which we must coerce to an array by individually extracting each field.
Secondly, the previous logic would repeatedly extract element/field values from the LHS when initializing the result. This is unnecessary: each element must only be extracted once, and the …
> Sema: optimize runtime array_mul

- lib/std/zig/render.zig
- src/reduce.zig
- src/reduce/Walk.zig
Apply the following sequence of transformations to `if` and `while` expressions. The conditions are checked in order and only the first matching transformation is applied.
1. If the `else` expression is missing or an empty block, replace the condition with `if (true)` if it is not already.
2. If the `then` block is empty, replace the condition with `if (false)` if it is not already.
3. If the condition is `if (true)`, replace the `if` expression with the contents of the `then` expression.
4. If the condition is `if (false)`, replace the `if` expression with the contents of the `else` expression.
For example, the following snippet might reduce in this sequence:
```zig
const x = 10;
if (x == 10) {
@compileError("Oh no!");
} else {
var y: usize = 11;
_ = y;
}
}
``` …
> zig-reduce: Add reductions for `if` and `while`

- src/Sema.zig
Currently there is invalid behavior in cases such as following
```zig
const x = packed struct{ f: u8, };
@compileLog(@as(x, @bitCast(@as(u8, undefined))));
```
```
Compile Log Output:
@as(example.main.x, .{.f = 170})
```
this patch add one more check to comptime-known 'undefiefd':
```
Compile Log Output:
@as(example.main.x, undefined)
```
> Sema: preserve 'undefined' in @bitCast

- lib/std/elf.zig
- src/link/Elf.zig
- src/link/Elf/Atom.zig
- src/link/Elf/LinkerDefined.zig
- src/link/Elf/Object.zig
- src/link/Elf/SharedObject.zig
- src/link/Elf/Symbol.zig
- src/link/Elf/ZigObject.zig
- src/link/Elf/eh_frame.zig
- src/link/Elf/file.zig
- src/link/Elf/synthetic_sections.zig
- test/link/elf.zig
> elf: the dreaded `-r` mode

- src/Compilation.zig
- src/codegen/llvm/BitcodeReader.zig
- stage1/wasi.c
```
zig build-exe repro Debug native: error: the following command failed with 2 compilation errors:
zig build-exe repro/repro.c --cache-dir repro/zig-cache --global-cache-dir ~/.cache/zig --name repro --listen=- 
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install repro transitive failure
└─ zig build-exe repro Debug native 2 errors
repro/repro.c:6:17: error: invalid operands to binary expression ('float' and 'float')
float z = x & y;
~~^~~
repro/repro.c:7:7: error: passing 'float' to parameter of incompatible type 'void *'
f(z);
^
repro/repro.c:1:14: note: passing argument to parameter 'x' here
void f(void *x) {}
^
```
compared with the original clang diagnostics
```
repro/repro.c:6:17: error: invalid operands to binary …
```
> Compilation: forward clang diagnostics to error bundles

- lib/std/compress/zstandard.zig
- lib/std/compress/zstandard/decode/block.zig
Fixes #17867.
This change fixes some division-by-zero bugs introduced by the optimized ring buffer read/write functions in d8c067966.
There are edge cases where decompression can use a length zero ring buffer as the size of the ring buffer used is exactly the the window size specified by a Zstandard frame, and this can be zero. Switching away from loops to mem copies means that we need to ensure ring buffers do not have length zero ring when attempting to read/write from them.
> zstandard: fix division by zero when using RingBuffer

- src/type.zig
- test/behavior/sizeof_and_typeof.zig
Fixes https://github.com/ziglang/zig/issues/17665
> sema: pass sema through if available for the array_type case in bitSizeAdvanced

- lib/std/leb128.zig
- src/arch/x86_64/CodeGen.zig
- src/arch/x86_64/Emit.zig
- src/arch/x86_64/Lower.zig
- src/arch/x86_64/Mir.zig
- src/link/Dwarf.zig
```
$ ./zig run repro.zig
panic: crash
Unwind error at address `exe:0x80364c0` (error.MissingFDE), trace may be incomplete
repro.zig:2:5: 0x8000cf3 in main (repro.zig)
@panic("crash");
^
lib/std/start.zig:575:22: 0x8000697 in posixCallMainAndExit (repro.zig)
root.main();
^
lib/std/start.zig:253:5: 0x800001a in _start (repro.zig)
asm volatile (switch (native_arch) {
^
Aborted (core dumped)
```
Closes #17811
> Dwarf: improve x86_64 backend debug info

- src/Sema.zig
- test/standalone.zig
- test/standalone/strip_struct_init/build.zig
- test/standalone/strip_struct_init/main.zig
Fixes https://github.com/ziglang/zig/issues/15469
Where would be the best place to introduce these tests using -fstrip for this?
```
fn Func(comptime Type: type) type {
return struct { value: Type };
}
inline fn func(value: anytype) Func(@TypeOf(value)) {
return .{ .value = value };
}
export fn entry() void {
_ = func(type);
}
test {
const S = struct { field: u32 };
comptime var arr: [1]S = undefined;
arr[0] = .{ .field = 0 };
}
test {
const S = struct { u32 };
comptime var arr: [1]S = undefined;
arr[0] = .{0};
}
```
> sema: fixup underflows during struct / ptr array init when using -fstrip

- src/Compilation.zig
- src/InternPool.zig
- src/Module.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
The motivating problem here was a memory leak in the hash maps of Module.Namespace.
The commit deletes more of the legacy incremental compilation implementation. It had things like use of orderedRemove and trying to do too much OOP-style creation and deletion of objects.
Instead, this commit iterates over all the namespaces on Module deinit and calls deinit on the hash map fields. This logic is much simpler to reason about.
Similarly, change global inline assembly to an array hash map since iterating over the values is a primary use of it, and clean up the remaining values on Module deinit, solving another memory leak.
After this there are no more memory leaks remaining when using the x86 backend in a libc-less compiler.
> rework memory management of Module.Namespace hash maps

- src/Compilation.zig
but allow for { .exe, .o, .a }.
closes #17928
- tested this does not regress #17575
> compilation: forbid PIE for dynamic libraries

- README.md
- bootstrap.c
- ci/x86_64-linux-debug.sh
- ci/x86_64-linux-release.sh
The idea here is that the zig2 executable is perhaps the more useful deliverable until we implement our own optimization passes. This will allow system packages to provide Zig, and use it to compile Zig projects, all without LLVM!
> adjust building from source without LLVM process

- src/Sema.zig
- test/behavior/string_literals.zig
Fixes #18007
Issue was caused by `fieldVal` access the pointer's sentinel, instead of the value's.
thanks @mlugg :D
> Fix sentinel in string literals

- lib/std/tar.zig
tbh I don't even know if this is the right behavior, but it fixes unpacking tar archives from https://sourceforge.net/projects/sdl2gfx/files/
> std.tar: trim also spaces from the beginning of file size

- lib/std/unicode.zig
Fixes a compile error when the target is mips, since `std.simd.interlace` does not work correctly on mips and raises a compile error if it is used.
https://github.com/ziglang/zig/blob/2ac0ba03a60a133e7ffbab9ad6aaf3b54f6c747b/lib/std/simd.zig#L131-L136
Follow up to https://github.com/ziglang/zig/pull/17797
> std.unicode: Disable utf8 -> utf16 ASCII fast path on mips

- src/clang.zig
- src/translate_c.zig
- src/zig_clang.cpp
- src/zig_clang.h
- test/translate_c.zig
Closes #17720
80/128-bit `long double` literals are converted to quadruple precision before formatting, just like how 64-bit and smaller values are converted to double precision.
Decimal formatting for `f128` is not yet implemented (#1181) and I don't have the know-how necessary to fix that. I still think it would be useful to translate these `long double` literals instead of demoting them to extern, even if the representation isn't as friendly to humans as it could be.
The way I've implemented formatting for now is to try and round-trip the `f128` value by
1. casting it to `f64`,
2. serializing it to the decimal format,
3. parsing the serialized string as a `f128`, and finally
4. checking if the parsed value is exactly the same as the original `f128`.
If we could successfully roundtrip …
> translate-c: translate 80/128-bit long double literals

- doc/build.zig.zon.md
The order of `dependencies` and `minimum_zig_version` was misleading.
> Reorder fields in `build.zig.zon.md`

- src/aro_translate_c.zig
- src/translate_c.zig
- src/translate_c/common.zig
- test/behavior/translate_c_macros.h
- test/behavior/translate_c_macros.zig
Should close #17327 
This adds a `blank_macros` set to Scope.Root, used to keep track of macros with no content (in the form `#define blank `, or any macro derived from macros of such macros). Then, when these macros are encountered in casts/expressions, they are skipped instead of concatenated with the rest of the cast/expression. This PR also includes a behavior test.
Here is a *.h to compare the new behavior:
```
[jrz@jrz scratch]$ cat test.h
#define useful_attr 
typedef float useful_type;
#define useful_enum 0
#define useful_thing_0 ((float)0)
#define useful_thing_1 ((useful_type)0)
#define useful_thing_2 ((useful_attr float)0)
#define useful_thing_3 ((useful_attr useful_type)0)
#define useful_thing_4 ((float)useful_enum)
#define useful_thing_5 ((useful_type)useful_enum)
#define …
```
> Skip blank macros when translating defines

- lib/std/os/windows/ws2_32.zig
Added missing timeval struct.
os/windows/ws2_32.zig had a reference to the timeval struct being in os/windows.zig, where it wasn't implemented. Since the struct is defined in Microsoft winsock(2).h headers, decided to implement it in os/windows/ws2_32.zig.
> add missing timeval struct

- lib/std/Uri.zig
Fixes: https://github.com/ziglang/zig/issues/17869
The issue suggested `error.unexpectedCharacter`, but `error.InvalidFormat` felt more fitting since these are expected characters, just in the wrong order.
This is a pretty tactical change, no hard feelings if we prefer a different approach.
> std.Uri: fix parsing edge case panic

- deps/aro/aro/Compilation.zig
- deps/aro/aro/Driver/GCCDetector.zig
- deps/aro/aro/Parser.zig
- deps/aro/aro/text_literal.zig
- lib/std/array_list.zig
- lib/std/crypto/ff.zig
- lib/std/fs.zig
- src/resinator/parse.zig
- tools/gen_spirv_spec.zig
Here are 8 places where I found that the use of BoundedArray was better served by doing something else instead.
In fact, this is all the uses of BoundedArray in the standard library and compiler codebase. I am tempted to remove the API entirely since it in practice leads to less than ideal code, however, I think there is nothing fundamentally wrong with the idea of abstracting over an array and a length, so I think it can remain in the standard library for now.
> std: use BoundedArray less

- lib/std/os/windows.zig
This inline assembly has no side effects.
> std.os.windows: remove volatile from inline asm

- lib/std/debug.zig
Also remove the TODO--it was added in fd067fbe8b14c445ed764da15fff5163156126df, but the current code no longer used that workaround, so this TODO didn't seem relevant anymore.
Follow up to #16743 (see https://github.com/ziglang/zig/pull/16743#discussion_r1402802261).
> Remove unnecessary branch on absolute path

- lib/compiler_rt/ceil.zig
- lib/compiler_rt/cos.zig
- lib/compiler_rt/exp.zig
- lib/compiler_rt/exp2.zig
- lib/compiler_rt/floor.zig
- lib/compiler_rt/round.zig
- lib/compiler_rt/sin.zig
- lib/compiler_rt/sincos.zig
- lib/compiler_rt/tan.zig
- lib/compiler_rt/trunc.zig
- lib/std/math.zig
- lib/std/math/asinh.zig
- lib/std/math/atan.zig
- lib/std/math/atanh.zig
- lib/std/math/expm1.zig
- lib/std/math/log1p.zig
- lib/std/math/tanh.zig
Addresses #18004, and a follow up to #13790.
1) Stop using ``math.doNotOptimizeAway`` in favor of ``mem.doNotOptimizeAway``.
2) Make ``math.doNotOptimizeAway`` a ``@compileError("Deprecated: ...");``
> Deprecate math.doNotOptimizeAway, use mem.doNotOptimizeAway

- src/Compilation.zig
- src/codegen/spirv.zig
- src/codegen/spirv/Module.zig
- src/codegen/spirv/Section.zig
- src/link.zig
- src/main.zig
- test/behavior/align.zig
- test/behavior/basic.zig
- test/behavior/slice.zig
- test/behavior/struct.zig
- test/behavior/union.zig
This PR contains some important groundwork for code generation for shaders: the ability to generate structured control flow. This basically entails that every construct must be either in the form of `if (x) { a(); } else { b(); }`, or in the form of `while (true) { a(); if (x) break; b(); if (y) break; c(); }`. It is a required feature for shaders. For more information on the requirements on such code, see the [SPIR-V Manual, 2.11, "Structured Control Flow"](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_structured_control_flow). For an introduction to structured control flow and why this is a requirement at all, see [TheMaister's excellent blog](https://themaister.net/blog/2022/04/24/my-personal-hell-of-translating-dxil-to-spir-v-part-5/). 
Luckily, AIR gets us must of …
> spirv: structured codegen

- src/translate_c/ast.zig
- test/cases/translate_c/static empty struct.c
- test/src/Cases.zig
Closes #18093 
`test.h`:
```
struct empty_struct {};
static inline void foo() {
static struct empty_struct bar = {};
}
```
`zig translate-c test.h` relevant output:
```
pub const struct_empty_struct = extern struct {};
pub fn foo() callconv(.C) void {
const bar = struct {
var static: struct_empty_struct = struct_empty_struct{};
};
_ = &bar;
}
```
> Use struct_init_one for no-initializer struct

- lib/std/Build.zig
I'm currently seeing a segfault when using a `source_file` string that has been allocated on the head, and using a defer statement to free the allocated string. e.g:
```zig
const modZig = std.fmt.allocPrint(allocator, "path/to/mod.zig", .{}) catch unreachable;
defer allocator.free(modZig); // Removing this statement prevents a segfault
const mod = b.addModule("mod", .{ .source_file = .{ .path = modZig } });
```
This results in the following error when building:
```
Segmentation fault at address 0x7fcec5b51000                                                                                                                   
/home/dacm/.local/lib/zig/std/fs/path.zig:287:33: 0x31f3db in isAbsolutePosix (build)
return path.len > 0 and path[0] == sep_posix;
^ …
```
> fix: Prevent segfault when using b.addModule()

- lib/std/zig/system/NativeTargetInfo.zig
The cast seems to no longer be necessary after changes in interactions between `u64` and `usize`.
> std.zig.system: remove explicit `usize` cast

- deps/aro/aro/Type.zig
- deps/aro/backend/Ir.zig
- doc/langref.html.in
- lib/std/debug.zig
- lib/std/mem.zig
- lib/std/os/windows/test.zig
- src/link/MachO/uuid.zig
- src/resinator/cli.zig
- src/resinator/compile.zig
- src/resinator/lang.zig
- src/resinator/source_mapping.zig
- test/behavior/for.zig
- test/behavior/ptrcast.zig
- test/behavior/threadlocal.zig
- tools/update-license-headers.zig
My reasoning for making this PR is 2 reasons.
1. This should have been simply removed/`@compileError` the first time, and now there is just no point in keeping it around.
2. In my opinion this creates a bad practice function alias. By aliasing `copyForward`, we are creating possible bugs that are not caught and corrupt data due to overlap. The pointer overlap detection of `@memcpy` is more important than I believe given credit to. So it leads to the thought that all uses of `std.mem.copy` (after it was aliased/depricated), were made out of ignorance of the dangerous it could pose to the codebase. If the writer wanted to ensure overlap, they would have / should use `copyForward`, and if they did *not* want overlap, they need to use `@memcpy`.
> Remove all usages of `std.mem.copy` and remove `std.mem.set`

- lib/std/crypto/tls.zig
- lib/std/crypto/tls/Client.zig
Following the recommendations from [1], the AEGIS specification and the TLS registry [2] were updated to recommend SHA512 for the traffic secrets.
[1] https://eprint.iacr.org/2023/913.pdf
[2] https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4
> TLS: The 0x1306 TLS identifier was updated to TLS_AEGIS_256_SHA512

- doc/langref.html.in
This fixes what appears to be an incorrect reference to a string literal in the example code snippet. The current version makes reference to a `"foo"` string literal, when in the snippet it's actually a `"hello"` string literal.
```zig
fn foo(s: []u8) void {
_ = s;
}
test "string literal to mutable slice" {
foo("hello");
}
```
> langref: fix incorrect reference to string literal

- src/link/Elf.zig
- src/link/Elf/Archive.zig
- src/link/Elf/LdScript.zig
- src/link/Elf/Object.zig
- src/link/Elf/SharedObject.zig
- src/link/Elf/ZigObject.zig
- src/link/Elf/file.zig
- test/link/elf.zig
Fixes #18205
Although it fixes the above issue, it's just the beginning of proper error handling in the linker. I will be adding better error catching and reporting incrementally as it's quite an involved task.
This PR also addresses a latent bug in writing a static library when one source is incrementally compiled Zig source - an example of this could be generating `libcompiler_rt.a` without LLVM. The bug would incorrectly calculate the total size of the incrementally compiled Zig source and thus it would fail to correctly re-encode it in the output archive file.
> elf: report errors for some detected malformed object contents

- lib/std/os/linux.zig
the name field is represented as trailing data after the struct so it can be confusing how to get it
> add getName helper to inotify_event

- lib/std/zig/parser_test.zig
- lib/std/zig/render.zig
Fixes #15650 
The problem is that the `renderExtraNewlineToken` works on the container member and its doc_comment(if any) individually, rendering two newlines instead of one. 
If the member has a doc_comment, the newline logic should be handled in its own rendering logic, just like for regular comments.
> fmt: Skip extra newline if doc_comment exists

- lib/std/enums.zig
Add `getPtrConstAssertContains(...)` for compatibility with a `const` `std.EnumMap`
Currently, `getPtrAssertContains(...)` exists but only works with mutable `var` instance. The new `getPtrConstAssertContains(...)` method aligns with the existing `getPtr(...)`/`getPtrConst(...)` methods.
> Add `getPtrConstAssertContains(...)` for compatibility with a `const` `std.EnumMap`

- lib/std/os/linux/io_uring.zig
The last versions of linux allow to create rings up to [IORING_MAX_ENTRIES](https://github.com/torvalds/linux/blob/c527f5606aa545233a4d2c6d5c636ed82b8633ef/io_uring/io_uring.c#L3907), to allow this I updated the `entries` arg to an _u16_
> IO_Uring: allow sqe entries up to 32768

- lib/std/Build/Step/CheckObject.zig
- test/link/elf.zig
- test/link/macho/dead_strip_dylibs/build.zig
- test/link/macho/dylib/build.zig
- test/link/macho/entry/build.zig
- test/link/macho/entry_in_dylib/build.zig
- test/link/macho/headerpad/build.zig
- test/link/macho/needed_framework/build.zig
- test/link/macho/needed_library/build.zig
- test/link/macho/pagezero/build.zig
- test/link/macho/search_strategy/build.zig
- test/link/macho/stack_size/build.zig
- test/link/macho/strict_validation/build.zig
- test/link/macho/unwind_info/build.zig
- test/link/macho/weak_framework/build.zig
- test/link/macho/weak_library/build.zig
- test/link/wasm/archive/build.zig
- test/link/wasm/basic-features/build.zig
- test/link/wasm/bss/build.zig
- test/link/wasm/export-data/build.zig
- test/link/wasm/export/build.zig
- test/link/wasm/extern-mangle/build.zig
- test/link/wasm/function-table/build.zig
- test/link/wasm/infer-features/build.zig
- test/link/wasm/producers/build.zig
- test/link/wasm/segments/build.zig
- test/link/wasm/stack_pointer/build.zig
- test/link/wasm/type/build.zig
- test/standalone/ios/build.zig
Doing
```zig
const check = exe.checkObject();
check.checkInSymtab();
//...
```
will now only dump the symbol table avoiding a possible false positive where a tested statement ends up being true because it was found in any of the following sections of the parsed object file. For example, prior to this change, this would succeed even though `_bar` is actually not present in MachO indirect symtab but it is present in the exports info of dyld info section:
```zig
const check = exe.checkObject();
check.checkInIndirectSymtab();
check.checkContains("_bar");
```
The change is breaking since `checkStart` is no longer public. Instead, it has been renamed to `checkInHeaders`.
> lib/std/Build/CheckObject: introduce scoped checks

- src/Compilation.zig
- src/Sema.zig
- src/link.zig
This option is not needed since the link_libc flag can be set directly when creating compiler_rt.
This fixes a problem where an immutable flag was being mutated in Sema.
> Compilation: remove parent_compilation_link_libc

- lib/std/Build/Step/Compile.zig
I suspect it might take some time before a fix to #17969 gets merged. I need to disable the formatted messages for debug builds for a severely stack-constrained embedded target, so I thought maybe it would be okay to expose these flags to the build system for a while until the new panic handler design is made available.
> Expose `-f(no-)formatted-panics` to the build system

- lib/std/net.zig
- lib/std/net/test.zig
Inferred errors in switch statements prevented IP address parsing at comptime.
Adding explicit error sets fixes it.
Also added a test that checks that:
a) You can parse valid IP address at comptime
b) You can handle error on your end for invalid IP addresses (as opposed to seeing compilation error regarding switch statement)
Closes #18276
> std.net: add explicit error sets for IP parsing

- CMakeLists.txt
- build.zig
- ci/aarch64-linux-debug.sh
- ci/aarch64-linux-release.sh
- ci/aarch64-macos-debug.sh
- ci/aarch64-macos-release.sh
- ci/aarch64-windows.ps1
- ci/x86_64-linux-debug.sh
- ci/x86_64-linux-release.sh
- ci/x86_64-macos-release.sh
- ci/x86_64-windows-debug.ps1
- ci/x86_64-windows-release.ps1
For computing the zig version number, pass --abbrev=9 rather than requiring the user to set their git configuration in order to make zig versions match the standard.
> build: pass --abbrev to git rather than relying on global config

- bootstrap.c
Minor change to add support for FreeBSD in the bootstrap.c file. This makes it easier to build Zig on FreeBSD from source.
> Add FreeBSD to bootstrap.c to make building from source easier in FreeBSD 14

- lib/std/fs/File.zig
ctime is last file status/metadata change, not creation time.
https://linux.die.net/man/2/fstat
```
time_t    st_ctime;   /* time of last status change */
```
Note that this mistake was not made in the `File.metadata`/`File.Metadata` implementation, which allows getting the actual creation time.
Closes #18290, see that issue for a more detailed writeup of the problems addressed here.
---
- There are no uses of the `ctime` field within Zig itself, so nothing internal was relying on this mistake. It still might make sense to rename the field to alert users that their usage of the field could have been buggy, though.
- `Stat` not containing creation time when it's available in `FILE_BASIC_INFORMATION` on Windows feels a bit strange, and there's definitely overlap between `stat`/`metadata` …
> Fix `Stat.ctime` docs, and correct its value on Windows

- lib/std/fs/File.zig
- lib/std/fs/test.zig
- lib/std/os/windows.zig
Requires an extra NtQueryInformationFile call when FILE_ATTRIBUTE_REPARSE_POINT is set to determine if it's actually a symlink or some other kind of reparse point (https://learn.microsoft.com/en-us/windows/win32/fileio/reparse-point-tags). This is something that `File.Metadata.kind` was already doing, so the same technique is used in `stat`.
Also, replace the std.os.windows.DeviceIoControl call in `metadata` with NtQueryInformationFile (NtQueryInformationFile is what gets called during kernel32.GetFileInformationByHandleEx with FileAttributeTagInfo, verified using NtTrace).
Addresses the last bit of https://github.com/ziglang/zig/issues/18290 that #18323 doesn't.
> `File.stat`: Support detection of `Kind.sym_link` on Windows

- lib/std/os/windows.zig
- lib/std/os/windows/kernel32.zig
https://github.com/ziglang/zig/blob/dd189a354bf1c77b1996725902c7f29526cc22a4/lib/libc/include/any-windows-any/processthreadsapi.h#L258
> `[in, optional] lpApplicationName` The lpApplicationName parameter can be NULL.
> `[in, out, optional] lpCommandLine` The lpCommandLine parameter can be NULL.
> `[in, optional] lpCurrentDirectory` If this parameter is NULL, the new process will have the same current drive and directory as the calling process.
https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw
> Correct `CreateProcessW` parameter types

- lib/std/crypto/kyber_d00.zig
On some architectures, including AMD Zen CPUs, dividing a secret by a constant denominator may not be a constant-time operation.
And most Kyber implementations, including ours, could leak the hamming weight of the shared secret because of this. See:
https://kyberslash.cr.yp.to
Multiplications aren't guaranteed to be constant-time either, but at least on the CPUs we support, they are.
> std.crypto.kem.kyber: mitigate KyberSlash

- lib/std/hash_map.zig
This is obvious in retrospect, but it tripped me up for a bit as a beginner.
> std.hash_map: clarify error when Context is missing pub hash/eql

- src/Sema.zig
- src/link/C.zig
- test/behavior/memcpy.zig
```
%9 = slice_ptr(*const [3]u8, <[]const u8, "src">)
```
&downarrow;
```
%9 = slice_ptr([*]const u8, <[]const u8, "src">)
%10 = bitcast(*const [3]u8, %9!)
```
Closes #18345
> Sema: ensure `slice_ptr` produces the correct type

- lib/std/child_process.zig
- lib/std/process.zig
The first commit adds `ArgIteratorWindows`, which faithfully replicates the quoting and escaping behavior observed in `CommandLineToArgvW` and should make Zig applications play better with processes that abuse these quirks. `ArgIterator` is updated to use this implementation on Windows.
The new implementation used `ArgIteratorGeneral` as a base but the new rules were written by me, from scratch, by following public documentation and manually observing the behavior of `CommandLineToArgvW` on Windows 10; they weren't ported from a different project or based on disassembly.
I left `ArgIteratorGeneral` as is, but since it is now only used for response files it might make sense to rename it `ArgIteratorResponseFile` and remove the Windows-specific wide string `init` overload.
The second commit …
> More accurate argv parsing/serialization on Windows

- lib/std/os/uefi.zig
- lib/std/time.zig
Adds some extra logic and things to make time work with UEFI. It may not be optimal but should do its job.
> std: add support for getting the time in UEFI

- src/Sema.zig
The first instruction in the block was never checked resulting in `struct_is_comptime` being incorrectly cleared if there are no instructions before the first field of the comptime struct.
EDIT: Can a test check this kind of bugs? I haven't written one as I haven't found how to.
Fixes #17119
---
Normal behavior with `-fno-strip`:
```
block.instructions.items = {
%Air.Inst.Index(2) = dbg_block_begin,
%Air.Inst.Index(3) = dbg_stmt,
%Air.Inst.Index(4) = store_safe,
%Air.Inst.Index(5) = store_safe,
}
```
store_inst=Index(5) -> `continue` at line 4823 -> store_inst=Index(4) -> `continue :field` at 4842, `struct_is_comptime` check passes
Incorrect behavior with `-fstrip` / `-O ReleaseSmall`:
```
block.instructions.items = {
%Air.Inst.Index(1) = store_safe,
%Air.Inst.Index(2) = store_safe,
}
``` …
> Sema: fix merging store instructions from a comptime struct value with `-fstrip`

- lib/std/fmt.zig
I got a bit tripped up by this and filed a duplicate issue--I probably wouldn't have if the docs linked to #1181, so I've updated them to do that.
> Update formatFloat* docs to reflect limitation w/ large floats

- lib/std/Thread.zig
possibly meant how instead of now
> doc: possible typo at `std.Thread.spawn` comment

- src/Compilation.zig
- src/Module.zig
- src/Package/Module.zig
- src/Sema.zig
- src/codegen/llvm.zig
Searching for "iterator" is a surprisingly efficient method for finding sus code. :grinning:
Justifications for `HashMap` &rightarrow; `ArrayHashMap` changes:
- `Compilation.CObject.Diag.Bundle.*_names`: These may already be inserted in order, so could potentially be turned into `ArrayList`s with some additional checks.
- `Module.embed_table`: Needs to be iterated while queuing work.
- `Package.Module.Deps`: Needs to be cloned often, which is just iteration in a trenchcoat, and less data to copy around while sorting (and, in fact, could now be sorted in-place, with no extra allocations, if mutation could be allowed).
- `Sema.unresolved_inferred_allocs`: Needs to be iterated to find unused allocs.
> Compilation: cleanup hashmap usage

- ci/x86_64-windows-debug.ps1
- ci/x86_64-windows-release.ps1
- lib/std/math.zig
- lib/zig.h
- src/codegen/c.zig
- src/link/C.zig
- test/behavior/bugs/12680.zig
Fixes https://github.com/ziglang/zig/issues/17817, and re-enables the MSVC CBE tests.
It's possible for some of the names generated by the macros in zig.h to collide with compiler intrinsics. This change introduces a system for avoiding these collisions, while still allowing the colliding name to be exported.
To avoid compile errors, the colliding names are redefined as `zig_intrin_<name>` in zig.h. If the symbol is exported, then a `zig_export` is generated mapping the mangled name back to the original.
The specific problem that sparked this change was the unfortunate combination of `zig_libc_name_f80(name) __##name##x` with the input `fma`, resulting in `__fmax`, which seems to be a new intrinsic in recent versions of cl.exe. If more of these intrinsic collisions come up in the future, …
> cbe: add a system for avoiding collisions with C compiler intrinsics

- lib/std/unicode.zig
Updated Utf8View example to format the single codepoint UTF-8 slice with {s}
> Fix Utf8View example to compile.

- lib/std/comptime_string_map.zig
this allows getting the index of `str` into `kvs`. this is useful because `kvs[index].key` will be a comptime stable string and `str` might not always be, so if you want it to persist pulling the string out of the CSM is better.
> std.ComptimeStringMap: allow getting kv index

- lib/std/enums.zig
Current implementation fails to handle the following enum
```zig
const E = enum {
X,
pub const X = 1;
}
```
because `@field(type, name)` prefers declarations over enum fields.
> Fix std.enums.values

- src/Sema.zig
- test/behavior/tuple.zig
closes #18400
im not entirely sure how youre meant to know when backends should skip a test since i dont even know how to run tests with some of them so i just chose the ones that most of the other surrounding tests skipped
> add missing resolveStructFieldInits

- lib/std/debug.zig
- lib/std/http.zig
- lib/std/json/static_test.zig
- lib/std/math/float.zig
- lib/std/mem.zig
- lib/std/multi_array_list.zig
- lib/std/testing.zig
- test/behavior/cast.zig
- test/behavior/packed-struct.zig
- test/behavior/type.zig
- test/c_abi/main.zig
This PR is an attempt of improving the ergonomics of passing literals to `std.testing.expectEqual` by changing the type of its second parameter to `anytype` and coercing both arguments to a common type `@TypeOf(expected, actual)`.
```diff
-pub fn expectEqual(expected: anytype, actual: @TypeOf(expected)) !void
+pub inline fn expectEqual(expected: anytype, actual: anytype) !void
```
The function is made `inline` to help ensure that certain coercions that can't happen at runtime happen at comptime, for example, from a value of the union's underlying enum type to an instance of the union itself.
This PR offers a partial solution to the problem described in the body of #4437. I invite everyone to provide feedback and suggest alternative solutions, and the core Zig team is encouraged to close …
> Update `std.testing.expectEqual` and friends to use peer type resolution

- lib/std/Build/Module.zig
When depending on a module that depends on a static library, there was a missing step dependency on the static library, which caused a compile error due to missing header file.
This fixes the problem by adding the proper step dependencies.
Reviewing this code, I'm starting to wonder if it might be simpler to have Module instances create dummy Step objects to better model dependencies and dependees, rather than trying to maintain this graph without an actual node. That would be an improvement for a future commit.
I thought about how best to test this, since it depends on the fetching code of `zig build` and therefore is ineligible for becoming a new test/standalone/* case. I thought about combining efforts with another idea I've been kicking around for a while now and created [a new …
> build system: fix missing step dependencies on lib

- src/Module.zig
Fixes edge cases where the `startsWith` that was used previously would return a false positive on a resolved path like `foo.zig` when the resolved root was `foo`. Before this commit, such a path would be treated as a sub path of 'foo' with a resolved sub file path of 'zig' (and the `.` would be assumed to be a path separator). After this commit, `foo.zig` will be correctly treated as outside of the root of `foo`.
Closes #18355
With this setup:
```zig
// foo.zig
pub fn foo() void {}
```
```zig
// foo/bar.zig
const foo = @import("../foo.zig");
foo.foo();
}
```
Before:
```
> zig build-exe foo/bar.zig
foo\bar.zig:1:21: error: unable to load 'foo\zig': FileNotFound
const foo = @import("../foo.zig");
^~~~~~~~~~~~
```
After:
```
> zig build-exe foo/bar.zig
foo\bar.zig:1:21: …
```
> Use `std.fs.path.relative` for `@import` and `@embedFile` sub paths

- lib/compiler_rt/common.zig
This fixes undefined reference to `__gnu_h2f_ieee` and `__gnu_f2h_ieee` on use of the `std.fmt` functions for example when building with: `-target x86_64-freestanding-none -mcpu x86_64_v3-avx-avx2-f16c-fma-fxsr-mmx+soft_float-sse-sse2-sse3-sse4_1-sse4_2-ssse3-vzeroupper-x87-xsave -rdynamic`
Example code:
```zig
var buffer: [1024 * 1024]u8 = undefined;
var alloc = std.heap.FixedBufferAllocator.init(buffer[0..buffer.len]);
pub export fn _start() void {
const str = std.fmt.allocPrint(alloc.allocator(), "Hello", .{}) catch unreachable;
defer alloc.allocator().free(str);
}
```
Thanks @matu3ba 
Related: #13333
> Enable gnu_f16_abi on x86_64

- lib/std/mem.zig
this unnecessarily slowed down sliceTo and the logic was already present for the other branches
> speed up sliceTo when end == sentinel on many-pointers

- src/Sema.zig
- test/behavior/type.zig
- test/cases/compile_errors/reify_type_for_tagged_union_with_no_enum_fields.zig
- test/cases/compile_errors/reify_type_for_tagged_union_with_no_union_fields.zig
Brought to attention in this post on Ziggit: https://ziggit.dev/t/union-fields-are-empty/2718
```zig
const MyUnion = @Type(.{
.Union = .{
.layout = .Auto,
.tag_type = enum {},
.fields = &.{
.{ .name = "a", .type = u32, .alignment = @alignOf(u32) },
.{ .name = "b", .type = u32, .alignment = @alignOf(u32) },
},
.decls = &.{},
},
});
const u: MyUnion = undefined;
_ = u;
}
```
On master this compiles into a 0-bit union with no fields. Changing the tag type to `enum { a }` results in a compile error complaining about a missing `b` enum field, so this seems like an oversight.
> sema: Prevent reifying non-empty union with empty tag type

- lib/std/comptime_string_map.zig
Add tests for empty initialization, and some more corner cases (empty key, very long key, duplicate keys).
Fixes #18212
> std.CompTimeStringMap*: support empty initialization list

- lib/std/fs/Dir.zig
- lib/std/fs/test.zig
This PR:
- Cherry-picks some relevant tests added by @rootbeer in #17499 (only those that don't require the changes in that PR or #16878)
- Documents and tests the platform-specific behavior around when `..` components are resolved in the `sub_path` of `Dir.makePath` (closes #18452)
> Add more `Dir.makePath` tests and document how `..` is handled in sub_path

- lib/std/Build.zig
- src/Compilation.zig
Fixes #18210 and makes it possible to use floating-point types in Zig on RISC-V. Tested with my Orion firmware for RISC-V which is using Phantom UI for its built in GUI. Was able to use f32 without any issues.
> Compilation: pass code model to buildOutputFromZig

- doc/langref.html.in
- Fixes issue #14347
- Also clarifies substitution in the format string
- Also makes some small updates to wording in Hello World section
> langref: Remove use of comptime in Hello World section

- src/link/MachO/uuid.zig
This mirrors a similar change in llvm to make builds reproducible regardless of the build host's CPU count.
See:
https://github.com/llvm/llvm-project/issues/63961
https://github.com/llvm/llvm-project/commit/359f170f5f712ee714193b46bad45a45656b2c59
Fixes #18068
> Use a fixed chunk size when calculating MachO UUID

- lib/std/fs/Dir.zig
- lib/std/fs/test.zig
std.fs.dir.makePath silently fails if one of the items in the path already exists. For example:
cwd.makePath("foo/bar/baz")
Silently failing is OK if "bar" is already a directory or a symlink that resolves to a directory - this is the intended use of makePath (like mkdir -p). But if bar is a file then the subdirectory baz cannot be created - the end result is that makePath doesn't do anything and never creates the directory baz which should be a detectable error.
The existing code had a TODO comment that did not specifically cover this error, but the solution for this silent failure also accomplishes the TODO task - the code now stats "foo" and returns an appropriate error if necessary. The new code also handles potential race condition if "bar" is deleted/permissions changed/etc in …
> fix std.fs.Dir.makePath silent failure

- lib/std/Build/Step/Compile.zig
Noticed this discrepancy between linker scripts and version scripts while working on #18486.
> Build: Use `LazyPath` for version scripts

- lib/std/debug.zig
- lib/std/testing.zig
Recently, when I've been working with structures of data that are not directly in RAM but rather laid out in bytes somewhere else, it was always very useful to print out maybe the next 50 bytes or the previous 50 bytes or so to see what's ahead or before me. I usually do this with a quick
`std.debug.print("{any}\n", .{bytes});` or something but the output is not as nice obviously.
That reminded me to this hexdump-like printing code that we already have in `std.testing` and use for `std.testing.expectEqualSlices` thanks to @squeek502.
We can reuse it for a general-purpose `std.debug.hexdump` function which should be an excellent debugging tool when you want to know what or where the bytes are.
```zig
var bytes: [5 * 1000 * 1000]u8 = …
```
> general-use std.debug.hexdump for printing hexdumps

- lib/std/mem.zig
- lib/std/os/linux.zig
The current stdlib implementation is not as good as it can be for `u8`, which is the most commonly used one by far. @kprotty and I have taken the task of vectorizing and accelerating this function by orders of magnitude. The idea here is to split this api into 2 different functions. The normal `eql` function, which works on anything, and the much more optimized `eqlBytes`, which specifically optimizes bytes. `eql` calls `eqlBytes` if `T` is `u8`.
For any other integers, we still use a much faster xor accumulator design, see benchmarks below.
The benchmarks are run in as good of a script as I was able to make, including using cpu counters, pinning the process to 1 core, and clearing caches between different function runs. Warmups happen for each function, as well as at least 1000 runs.
The …
> Heavily Optimized `std.mem.eql` with SIMD

- lib/std/Build/Step/Compile.zig
- src/Compilation.zig
They were being resolved relative to the wrong owner.
closes #18460
Tested via https://github.com/ziglang/contrib-testing/commit/b10e253b4b07bcb56a34940226ac2fe331cede56
> std.Build.Step.Compile: fix link object paths

- src/Package/Fetch.zig
Currently, when fetching dependencies, `src/Package/Fetch.zig` uses case-insensitive equality on the entire value of the Content-Type header to determine MIME type. However, Content-Type headers may include additional directives after the MIME type, most commonly `charset=utf-8`, delimited by a semicolon.
For example, this issue arises when trying to fetch SQLite sources from the official mirrors:
```
joel@Joels-MBP:~/Projects/zig-sqlite$ zig build
/Users/joel/Projects/zig-sqlite/build.zig.zon:7:20: error: unrecognized 'Content-Type' header: 'application/x-gzip; charset=utf-8'
.url = "https://www.sqlite.org/2023/sqlite-autoconf-3440200.tar.gz",
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Fixes #16963
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Typ …
> Fix Content-Type header parsing when fetching dependencies

- doc/langref.html.in
- src/AstGen.zig
- src/Sema.zig
- src/Zir.zig
- src/print_zir.zig
- test/behavior/switch_on_captured_error.zig
- test/cases/compile_errors/switch_expression-duplicate_error_prong.zig
- test/cases/compile_errors/switch_expression-duplicate_error_prong_when_else_present.zig
- test/cases/compile_errors/switch_expression-missing_error_prong.zig
- test/cases/compile_errors/switch_expression-multiple_else_prongs.zig
- test/cases/compile_errors/switch_expression-unreachable_else_prong_error.zig
- test/cases/compile_errors/switch_on_error_union_discard.zig
- test/cases/compile_errors/switch_on_error_with_1_field_with_no_prongs.zig
- test/cases/inherit_want_safety.zig
Closes #11957 and as well as the related issues #16770 and #11812.
There are a few things left to do before merging:
> Special-case switching on error union capture

- lib/std/Build/Step/Compile.zig
- src/Compilation.zig
- src/link.zig
- src/link/Coff/lld.zig
- src/link/Elf.zig
- src/link/MachO/zld.zig
- src/link/Wasm.zig
- src/main.zig
- test/link/elf.zig
Closes #16855 (main issue)
Closes #17326 (abandoned PR)
Closes #18255 (forked PR)
Adds support for the `--(no-)undefined-version` option, which permits/forbids references to undefined symbols in version scripts. The default is `--no-undefined-version`.
I squashed the commit history and added linker tests (with `use_lld = true` for now), as was requested by https://github.com/ziglang/zig/pull/17326#issuecomment-1741776476
> Add support for `--(no-)undefined-version`

- lib/std/dynamic_library.zig
- lib/std/math.zig
- lib/std/math/gamma.zig
Partially addresses #7212 and #8313 by adding these 2 useful functions available even in libc but not currently in zig standard library.
Implementation is based on [musl libc](https://git.musl-libc.org/cgit/musl/tree/src/math/tgamma.c) like many other functions in std.math.
I did some totally not scientific testing for `f64`, average relative error seems to be around `2 * 10^-15` while peak relative error is `1 * 10^-14` on the function's domain.
> Add std.math.gamma and lgamma

- lib/std/Target/arm.zig
- tools/update_cpu_features.zig
Closes #17374
Updates `update_cpu_features.zig` to support omitting deps and adds overrides for incorrect ARM Cortex-M series CPU definitions, most of them optional features that should not be enabled by default.
Based on the official [Arm Cortex-M Processor Comparison Table](https://developer.arm.com/documentation/102787/0300/?lang=en). Specifically the following highlighted features were incorrect:
I then re-ran `update_cpu_features.zig` using a `llvm-tblgen` built from https://github.com/llvm/llvm-project/commit/8f4dd44097c9ae25dd203d5ac87f3b48f854bba8, the exact same revision as the last time CPU features were updated (3ed40b114020ff774279a5af993851d74da64b52).
> Don't enable optional ARM Cortex-M series CPU features by default

- lib/std/crypto/ghash_polyval.zig
- lib/std/http/protocol.zig
- lib/std/mem.zig
- lib/std/simd.zig
- lib/std/unicode.zig
Closes #18296.
The first commit fixes the segfault in `mem.indexOfSentinel`.
The second renames `suggestVectorSize` to `suggestVectorLength` and makes the former a compile error. The function returns the vector *length* (as in, the number of elements), not the size in bytes of the entire vector or the bit size of individual elements. This distinction is important and some usages of the function in the stdlib operated under these incorrect assumptions.
I combed through nearby local variables and updated the names of them where the distinction was relevant.
Let me know if you would rather have the bug fix and the updated function names be two separate change sets.
> Rename `simd.suggestVectorSize` to clarify intent and fix related segfault

- deps/aro/aro/Compilation.zig
- lib/std/heap.zig
>  std.heap: add runtime safety for calling `stackFallback(N).get` multiple times

- lib/build_runner.zig
- lib/std/Build/Step.zig
- lib/std/Build/Step/Run.zig
* Specifically recognize stderr as a different concept than an error message in Step results.
* Display it differently when only stderr occurs but the build proceeds successfully.
closes #18473
> zig build: handle stderr more elegantly

- lib/std/Uri.zig
> Fixed verbatim copy of trailing '%' in unescapeStr

- lib/docs/index.html
This is to address a small glitch in the std docs styles, where the bottom section gets cutoff on the mobile viewport. Also on the desktop, at the regular or narrow viewport, the scroll bar indicator overflows the bottom of the page.
**Regular desktop at wide viewport--**
**Regular desktop at wide viewport with corrections--**
**Regular desktop at narrow viewport--**
**Regular desktop at narrow viewport with correcctions--**
**Mobile screen vertical--**
**Mobile screen vertical with corretions--**
**Mobile screen horizontal is not affected by the glitch--**
I tried to find the most basic way to patch this without interfering with the layout. Thankfully I was able to patch the styles directly, in just 2 places. The first will remove the bottom padding from the .docs container. This …
> Update styles in std docs to correct display glitch

- lib/std/io.zig
Avoids hitting `thread 1463 panic: invalid error code` in a professional project.
> std.io.GenericReader: add missing error annotations

- lib/std/math.zig
- lib/std/math/log.zig
- lib/std/math/log_int.zig
small follow up on #17143 , which will allow to close #17142
The `log_int` function should also be called at compile time. To allow this, I made the compile time check a little more permissive.
@matu3ba can you please review this one, since you accepted the previous one ? Thanks.
> fix #17142, wrong comptime log_int computation

- lib/std/Uri.zig
This should solve #18291.
This required adapting resolvePosix for Uri into its own function. This also has the benefit of never returning relative paths, which used to be possible.
> std.Uri: fix implementation of resolve with trailing slashes

- lib/std/http/Client.zig
- lib/std/http/Headers.zig
- lib/std/http/Server.zig
- test/standalone/http.zig
This adds the missing documentation for most of the previously undocumented functions, alongside a few example usages in certain scenarios.
This also removes the allocator parameter from Server and Server.init as it had no use and there are no plans to have a use for in the in near future.
> std.http: add missing documentation and a few examples

- tools/docgen.zig
Fix crash when trying to build zig using zig-boostrap on Windows if `\r\n` line endings present in `langref.html`
Ref https://github.com/ziglang/zig-bootstrap/issues/162
> Don't crash or CR/LF line endings in docgen

- lib/std/Build/Step/Compile.zig
I only just now got to updating one of my projects and noticed that this option was nowhere to be found. Looks like c20ad51c621ba18d2c90cc96d1b550831dc5d7a3 inadvertently removed it.
Formatted panics still appear to be a compilation option and not a module option, so they still belong in `Step.Compile`.
Related: #18287
> Expose `-f(no-)formatted-panics` to the build system (again)

- doc/langref.html.in
Small fix by removing the &-Operator in front of the string literals. The expected type is `[]const u8`.
> langref: Fix example for Generic Data Structures

- src/libcxx.zig
> libcxx:  only pass -DHAVE___CXA_THREAD_ATEXIT_IMPL for glibc >=2.18

- test/src/Cases.zig
relate commit: 
[child_process + Build: rename exec to run + all related code](https://github.com/ziglang/zig/commit/fd2239bde9e2051a32fb25c50c732a40d4afccd0)
> Fix minor error: std.ChildProcess.exec() already rename to run()

- lib/std/c.zig
- lib/std/os.zig
- lib/std/os/linux.zig
- lib/std/os/linux/syscalls.zig
- lib/std/os/test.zig
- src/link/Wasm.zig
> Add `fchmodat` fallback on Linux when `flags` is nonzero.

- lib/std/math.zig
This function is frequently used for wrapping things like angle ranges, would be a strange omission to have clamp and not this since they complement each other.
```zig
fn mouseMove(dx: i32, dy: i32) void {
yaw   += sensitivity(dx);
pitch += sensitivity(dy);
yaw   = wrap(yaw, 180);
pitch = clamp(pitch, -90, 90);
}
> std.math: add `wrap` function

- lib/std/mem.zig
This adds support for byteswapping the elements in an array. This is useful when reading something like an ICC profile for example as it deals in big endian and many machines are in little endian.
> mem: add byteswap array support

- lib/std/math/complex/acos.zig
- lib/std/math/complex/acosh.zig
- lib/std/math/complex/asin.zig
- lib/std/math/complex/asinh.zig
- lib/std/math/complex/atan.zig
- lib/std/math/complex/atanh.zig
- lib/std/math/complex/conj.zig
- lib/std/math/complex/cos.zig
- lib/std/math/complex/cosh.zig
- lib/std/math/complex/exp.zig
- lib/std/math/complex/ldexp.zig
- lib/std/math/complex/log.zig
- lib/std/math/complex/proj.zig
- lib/std/math/complex/sin.zig
- lib/std/math/complex/sinh.zig
- lib/std/math/complex/sqrt.zig
- lib/std/math/complex/tan.zig
- lib/std/math/complex/tanh.zig
See https://github.com/ziglang/zig/pull/17840#discussion_r1383863142
This also fixes some inconsistencies before where some function's return result reuses the argument's original type, yet implicitly it is always constructing from the `Complex(T)` type, meaning that it will be an error if the input was some bastard duck possessing the same field name.
> std.math.complex: use Peer Type Resolution for ducktyped functions

- lib/std/math/complex/pow.zig
related to https://github.com/ziglang/zig/pull/17901 but split into its own pull request since the interface is changed
>  std.math.complex: make complex.pow infer type from argument

- lib/std/os/linux/io_uring.zig
This ads zero copy send.`send_zc` tries to avoid making intermediate copies of data. Kernel will notify application when data is sent and one more time when buffer is not needed by the kernel any more. Available since kernel 6.0.
Also adds operation on direct file descriptors (fixed or registered files). Direct descriptors exist only within the ring itself, but can be used for any request within that ring. Should remove file descriptors handling overhead. Available since kernel 5.19.
Tested on multiple kernels: 5.4.0, 5.8.0, 5.11.0, 5.13.0, 5.15.0, 5.19.0, 6.2.0, 6.5.0.
> io_uring: add send_zc and *_direct operations

- src/Sema.zig
- test/behavior/align.zig
- test/behavior/alignof.zig
- test/behavior/array.zig
- test/behavior/async_fn.zig
- test/behavior/basic.zig
- test/behavior/bitcast.zig
- test/behavior/call.zig
- test/behavior/cast.zig
- test/behavior/enum.zig
- test/behavior/error.zig
- test/behavior/eval.zig
- test/behavior/fn.zig
- test/behavior/math.zig
- test/behavior/optional.zig
- test/behavior/pointers.zig
- test/behavior/sizeof_and_typeof.zig
- test/behavior/slice.zig
- test/behavior/struct.zig
- test/behavior/switch.zig
- test/behavior/truncate.zig
- test/behavior/type_info.zig
- test/behavior/union.zig
- test/behavior/vector.zig
Fixes an OOM bug introduced in #17944 when constructing error messages. All usages of `comptime expect` in `test/behavior` are also replaced with `comptime assert`. In addition a behaviour test for slicing multi-pointers was checking the types of some irrelevant slices - these type checks have been fixed up.
> 17944 followup

- lib/std/tar.zig
- src/Package/Fetch.zig
Fossil SCM can generate `tar.gz` compressed source tree archives at any given artifiact, which aligns well with zig build dependency fetching system.
Problem is that fossil serves these archives with mime type `application/x-compressed`. While it's too generic, zig should accept it nonetheless, but fall back to filename parsing to determine source archive type.
Other problem is that fossil generates tar archives where directory headers don't have trailing slash which causes issues with the way how `std/tar.zig` parses archive paths.
> Adds support for Fossil SCM source tree archives as zig build dependencies

- lib/std/os/linux.zig
- lib/std/os/linux/syscalls.zig
This release adds the rest of the futex2[^1] syscalls, along with shadow stack[^2] support for more architectures.
- Add syscall bindings/structures for the `futex2` family. The documentation is taken from the syscall definitions.
- Add documnentation for the `cachestat` bindings and structures. Taken from work I did in Cosmopolitian libc.
- Add binding for `map_shadow_stack`. No documentation for this one, since the kernel devs didn't bother to do it ¯\\_(ツ)_/¯.
[^1]: https://lwn.net/Articles/940944/
[^2]: https://lwn.net/Articles/926649/
> Linux: Update syscall bits for 6.7

- src/AstGen.zig
- test/cases/compile_errors/error_set_cannot_capture_by_reference.zig
- test/cases/compile_errors/switch_on_error_union_discard.zig
- test/cases/compile_errors/switch_on_error_with_capture_by_reference.zig
- test/cases/compile_errors/switch_on_error_with_non_trivial_switch_operand.zig
fixes #18583
The old code that tried to detect the "switch on error" was just looking at the token relative to the payload to find what is the switch operand. This is incorrect when the switch operand is an expression like in `catch |err| switch (err + 1) {}`.
> fix ast gen failure to catch incorrect by ref error captures

- src/AstGen.zig
- test/cases/compile_errors/capture_by_ref_if.zig
- test/cases/compile_errors/capture_by_ref_if_err_switch.zig
- test/cases/compile_errors/capture_by_ref_switch.zig
- test/cases/compile_errors/capture_by_ref_while.zig
fixes #18579
i've verified that after this change, the following error ranges are correct and point at the identifiers instead of the asterisks
```zig
switch (undefined) {
.a => |*ident| {},
//      ^^^^^ unused capture
}
if (undefined) |*foo| {} else |err| {}
//               ^^^ unused capture
while (undefined) |*foo| {} else |err| {}
//                  ^^^ unused capture
```
> ast-gen: use correct token_src for switch, if and while exprs

- doc/langref.html.in
The language reference only mentions `== null` but forgets about `!= null` which also appears to be valid.
> Add missing != null operator to langref

- doc/langref.html.in
When reading the docs I noticed that the paragraph about what `extern` is was placed way below the code example that used it.
This PR moves that paragraph just below that code example, so that it makes sense.
> Move the extern paragraph to a more logical place

- lib/std/crypto/tls/Client.zig
Client for tls was using a function that wasn't declared on the interface for it. The issue wasn't apparent because net stream implemented that function.
I changed it to keep the interface promise of what's required to be compatible with the tls client functionality.
> tls client interface consistency fix

- lib/std/crypto/tls.zig
- lib/std/crypto/tls/Client.zig
Per last paragraph of RFC 8446, Section 5.2, the length of the inner content of an encrypted record must not exceed 2^14 + 1, while that of the whole encrypted record must not exceed 2^14 + 256.
Fix #17600 and #15626.
> Fix TLS record overflow by limiting inner record length to 2^14

- src/codegen/llvm.zig
> llvm: remove extra copy of wrapped payloads

- lib/std/child_process.zig
- lib/std/os/windows.zig
closes #15506 
the `\\Device\\Null` Handle requires write access in case a child program wants to write to it. An example using bash is found in the linked issue.
this is not limited to bash, it also applies to cmd batch files and any application that wants to access the ignored stdout/stderr/stdin. A bit modified code from the original: 
<details>
<summary>Example</summary>
```zig
const fmt = std.fmt;
const heap = std.heap;
const Allocator = std.mem.Allocator;
const Child = std.process.Child;
var arena = heap.ArenaAllocator.init(heap.page_allocator);
defer arena.deinit();
const allocator = arena.allocator();
var buf: [16]u8 = undefined;
for (0..255) |i| {
const cmd = try fmt.bufPrint(&buf, ".\\script.bat {}", .{i});
const argv = &.{ …
```
> child_process: Add write and inheritable access to the null handle

- lib/std/debug.zig
- lib/std/heap.zig
These changes enable me to use `GeneralPurposeAllocator` with my "Bring Your Own OS" package. The previous checks for a freestanding target have been expanded to `@hasDecl` checks.
- `root.os.heap.page_allocator` is used if it exists.
- `debug.isValidMemory` only calls `os.msync` if it's supported.
> byos: Ease `GeneralPurposeAllocator` integration

- src/Sema.zig
- test/cases/compile_errors/add_on_undefined_value.zig
- test/cases/compile_errors/add_sat_on_undefined_value.zig
- test/cases/compile_errors/add_wrap_on_undefined_value.zig
- test/cases/compile_errors/mult_on_undefined_value.zig
- test/cases/compile_errors/mult_sat_on_undefined_value.zig
- test/cases/compile_errors/mult_wrap_on_undefined_value.zig
- test/cases/compile_errors/sub_on_undefined_value.zig
- test/cases/compile_errors/sub_sat_on_undefined_value.zig
- test/cases/compile_errors/sub_wrap_on_undefined_value.zig
Previously `@as(i64, undefined) +% 1` would produce `@as(@TypeOf(undefined), undefined)` which now gives `@as(i64, undefined)`.
Previously `@as(i64, undefined) +| 1` would hit an assertion which now gives `@as(i64, undefined)`.
> sema: fix safe integer arithmetic operations on undefined values

- src/Sema.zig
- test/cases/compile_errors/switch_on_non_err_union.zig
> add type check to `zirSwitchBlockErrUnion`

- lib/std/Uri.zig
- src/Package/Fetch.zig
This is because `std.fmt` doesn't pass `:` to `format` as it functions as a delimiter for format specifiers
Fetch: print scheme when suggesting adding a ref to git URIs
> std.Uri: change specifier for printing with scheme to semicolon `;`

- lib/std/fs/test.zig
Refactor tests around makePath and symlinks.
> std.fs: tests for makePath and symlinks

- lib/std/http/Client.zig
- lib/std/http/protocol.zig
Fixes #18367. Handles the edge case of a response with no transfer-encoding and no content-length needing to be read until the connection is closed. I also took the chance to fix no content responses to follow the spec word for word.
This problem does not apply to std.http.Server as a request message missing transfer-encoding is to be interpreted as a zero length body.
> std.http.Client: read response messages with no length until eof

- lib/std/dwarf/abi.zig
define openbsd specific elements in std/dwarf/abi.zig regBytes()
work from Jasper Lievisse Adriaanse, with register values from sys/signal.h and https://github.com/ARM-software/abi-aa/blob/main/aadwarf64/aadwarf64.rst#dwarf-register-names
> openbsd: add proper support for aarch64

- src/AstGen.zig
- src/Sema.zig
- test/stack_traces.zig
> astgen: fix error return trace on error union switch

- doc/langref.html.in
- Document how to do a while loop with both an optional capture and a continue expression
- Add links to end of Optionals section to improve discoverability of optional capture behaviour in if and while statements.
Based on my own experience having difficulty finding these things.
> Minor improvements to the Optionals documentation

- src/libcxx.zig
Fixes #15486. Credit for fixing the patch goes to @rootbeer. I will report whether I can build clang with it against arbitrary old glibc
> libcxx: fix C++ builds with glibc <2.16 without aligned_alloc

- src/Compilation.zig
- src/link.zig
- src/main.zig
see https://releases.llvm.org/17.0.1/tools/clang/docs/UsersManual.html#generating-a-pch-file
syntax examples:
`zig cc -x c-header test.h -o test.pch`
`zig cc -include-pch test.pch main.c`
`zig c++ -x c++-header test.h -o test.pch`
`zig c++ -include-pch test.pch main.cpp`
compiling `mold` now works:
`CC="zig cc" CXX="zig c++" ASM="zig cc" cmake .. -G Ninja && ninja`
closes https://github.com/ziglang/zig/issues/18343
extracted from https://github.com/ziglang/zig/pull/17956 as a first step.
> zig cc: expose clang precompiled C header support

- lib/std/Build/Step/Compile.zig
- src/Compilation.zig
- src/main.zig
Some people are creating Zig modules in the build system that have C source files, but no Zig root source file, and then exposing this as a module. Before this patch, this would result in an unhelpful error from Zig's CLI because the build system would create an invalid CLI invocation.
Now, it is handled more smoothly, although users probably still need to alter their strategy for this use case to be satisfied.
With this patch, one can provide a module that only has C source files and then add it to another project's compilation and have those link objects correctly participate in the compilation. However, some users seem to expect the module API to support exposing arbitrary sets of C headers. There is already a solution for that, which is to create a static library. Note that it was …
> build system: better handle modules that do not have a zig root source file

- src/Sema.zig
- src/type.zig
- src/value.zig
- test/behavior/sizeof_and_typeof.zig
During semantic analysis the value may be an unresolved lazy value which makes using `toUnsignedInt` invalid.
Add assertions to detect similar issues in the future.
Closes #18624
> Sema: replace uses of `toUnsignedInt` with `toUnsignedIntAdvanced`

- lib/std/net.zig
The following test fails since NonCanonical is not handled
```
test "foo" {
std.net.Ip4Address.resolveIp("1.1.1.1", 0) catch unreachable;
}
/usr/lib/zig/std/net.zig:240:60: error: switch must handle all possibilities
if (parse(name, port)) |ip4| return ip4 else |err| switch (err) {
^~~~~~
/usr/lib/zig/std/net.zig:240:60: note: unhandled error value: 'error.NonCanonical' referenced by:
test.foo: src/dhcp.zig:383:23
```
> Handle all errors on std.net.Ipv4address.resolveIP

- lib/std/Build/Step/ConfigHeader.zig
- test/standalone/cmakedefine/config.h.cmake
- test/standalone/cmakedefine/expected.h
Iterative passes should start at the end of the previous substitution. Previous implementation was "off-by-one" and referred to the start of the variable name (after the prefix character) and mangled neighboring variables.
Also extended test cases to cover this use case.
Closes #18633
> std.Build.Step.ConfigHeader (cmake): fix offset calculation for multiple substitutions on a single line

- doc/langref.html.in
This creates a section in the language reference about doctests, which is currently referenced by Autodoc in a tooltip when displaying a doctest.
Some advice relevant to writing doctests is included, based on the discussion on #16472.
> langref: add information about doctests

- lib/std/Thread/Pool.zig
Free the allocated threads in the initialization of a thread pool only with pool.join instead of additionally calling allocator.free causing free to be called twice.
Resolves #18643
> std.Thread.Pool.init: free memory only once on error

- src/Module.zig
- src/Sema.zig
- test/cases/compile_errors/comptime_err_ret_trace.zig
- test/cases/compile_errors/error_in_comptime_call_in_container_level_initializer.zig
```zig
fn inner() !void {
return error.SomethingBadHappened;
}
fn outer() !void {
return inner();
}
comptime {
outer() catch unreachable;
}
// :10:19: error: caught unexpected error 'SomethingBadHappened'
//     outer() catch unreachable;
//                   ^~~~~~~~~~~
// :2:18: note: error returned here
//     return error.SomethingBadHappened;
//                  ^~~~~~~~~~~~~~~~~~~~
// :6:5: note: error returned here
//     return inner();
//     ^~~~~~~~~~~~~~
```
Closes #1295
> Sema: implement comptime error return traces

- src/objcopy.zig
The issue this change proposes to address is specifically the ofmt=hex. Based on the checks prior to calling hex_writer.writeSegment() it is not difficult assume the original intention was to iterate through segments instead of through each section. Fixes #18545.
> objcopy: ofmt=hex iterates through segments instead of sections

- lib/std/fmt.zig
- lib/std/meta.zig
When formatting a pointer to user type, currently it needs to be dereferenced first, then call `formatType` on the child type.
This fixes the problem by checking for "format" function on not only the type itself, but also the struct it points to.
Fixes #15335.
Supersedes #16367.
> std.fmt: fix unecessary deref on user-defined format function

- src/Liveness.zig
Liveness mistakenly assumes that if the operand is not in the parameters of a function call it is being written to, resulting in pointless memcpies.
New IR from the test case in #17580 - no memcpy:
```
; Function Attrs: nounwind uwtable
define internal fastcc i1 @bad.Foo.method(ptr nonnull readonly align 1 %0, i64 %1) unnamed_addr #0 {
%3 = getelementptr inbounds %bad.Foo, ptr %0, i32 0, i32 0
%4 = call fastcc i64 @bad.Foo.noop(i64 %1)
%5 = getelementptr inbounds [100 x i1], ptr %3, i64 0, i64 %4
%6 = load i1, ptr %5, align 1
ret i1 %6
}
```
Difference in performance from the test case in #15685:
```
❯ zig run test.zig
error: Time: 49296208 Sum: 536854528
❯ zig-dev run test.zig
error: Time: 764281 Sum: 536854528
```
Fixes #17580, #15685
> Don't assume a write if an operand is not in function parameters

- lib/std/zig/system/NativePaths.zig
`NIX_LDFLAGS` typically contains just `-rpath` and `-L`, which we already handle. However, at least one setup hook in Nixpkgs [0] adds a linkage directive to it. To prevent library paths from being missed (as I've observed myself with `NIX_LDFLAGS` being `-liconv ...`, making it so that *all* paths are missed), let's just skip over them.
[0]: https://github.com/NixOS/nixpkgs/blob/08f615eb1b3c5cf7481996f29c6092c7c891b15b/pkgs/development/libraries/libiconv/setup-hook.sh
> std.zig.system.NativePaths: ignore linkage directives in `NIX_LDFLAGS`

- src/link/Elf/Object.zig
Without this, the linker would overflow on large inputs compiled with `-fdata-sections`. An immediate example would be linking stage4 compiled with LLVM (and linked with Zig's ELF linker).
> elf:  merge all mergeable string rodata sections into one

- lib/std/os/wasi.zig
Branch was renamed: master -> main
Preview 1 was moved to legacy
> std.os.wasi | Fix comment links

- lib/std/Build/Step/TranslateC.zig
- test/src/Cases.zig
- test/src/run_translated_c.zig
- test/src/translate_c.zig
fixes the following snippet since Module.source_file was renamed, and aligns `Step.TranslateC.Options`
```zig
const zig_source = b.addTranslateC(.{
.root_source_file=.{.path="source.h"},
.target=target,
.optimize=optimize,
});
const zig_mod = zig_source.addModule("source");
```
> align naming and fix module creation from TranslateC

- test/behavior/globals.zig
Wanna make sure https://github.com/ziglang/zig/pull/18641#issuecomment-1907279096 doesn't get left behind for the next attempt.
> test: add behavior coverage for global setter in function liveness

- src/link/MachO.zig
Fixes #17130 
@slimsag @menduz I would appreciate if you double check this indeed fixes your issue. I did verify locally but want to make sure I didn't have to check out a specific version of `mach-glfw` project or something.
@andrewrk a couple of comments regarding having lib and framework search dirs available in `Compilation`:
1. ~~I have added dumping those dirs when `--verbose-link` is passed which I find invaluable for debugging any path-related linker issues. That said, I would like to discuss this with you if perhaps we could handle this in the frontend if possible; the point here being having the entire linker line invocation available for dumping when required.~~ EDIT: Turns out I forgot that we already do that for ELF linker. Still, my point stands.
2. I think with these …
> macho: fix logic for parsing dependent dylibs aka re-exports

- lib/std/zig/Parse.zig
- lib/std/zig/parser_test.zig
Currently, `zig fmt` deletes `comptime` keyword from code like this:
```zig
if (true) {} else comptime foo();
```
This is also true for `else` after `while` and `for`. The problem lies not in rendering, but in parsing the Zig source file.
This wrong behaviour was introduced in #17156, file: `Parse.zig`. @mlugg
I added a test in `parser_test.zig`, it currently fails on the master branch.
Closes #18656.
> parser: fix "else" followed by "comptime"

- lib/std/crypto/tlcsprng.zig
- lib/std/meta.zig
- lib/std/std.zig
> std: remove meta.globalOption

- src/Sema.zig
- test/cases/compile_errors/enum_backed_by_comptime_int_must_be_casted_from_comptime_value.zig
While investigating #17570, I encountered that such code will crash the compiler:
```zig
export fn entry() void {
const Tag = enum(comptime_int) { a, b };
var v: u32 = 0;
_ = &v;
_ = @as(Tag, @enumFromInt(v));
}
```
This is a bug in `Sema.zig`, during the evaluation of `@enumFromInt`, the case when the enum tag type is `comptime_int` is not handled. This seems to have been present since 0.10.0.
I added a test case under `test/cases/compile_errors`.
> Sema: fix crash when casting runtime value to enum with comptime int tag type

- lib/std/Thread.zig
The current implementation of POSIX threads contains an off-by-one error, causing arguments that are exactly 1 byte in size to result in a segmentation fault.
Fixes #17774.
> std.Thread: fix off-by-one in PosixThreadImpl

- src/codegen/llvm.zig
- test/behavior/basic.zig
> llvm: revert bad array access optimization

- src/link/Dwarf.zig
- src/link/MachO.zig
- src/link/MachO/DebugSymbols.zig
- src/link/MachO/Dylib.zig
- src/link/MachO/InternalObject.zig
- src/link/MachO/Object.zig
- src/link/MachO/ZigObject.zig
- src/link/MachO/file.zig
- src/link/MachO/load_commands.zig
`ZigObject` only - combining debug info from multiple object files into a single dSYM bundle is still a TODO.
Fixes #18666
> macho: reinstate DWARF in self-hosted x86_64-macho

- src/Air.zig
- src/Liveness.zig
- src/Liveness/Verify.zig
- src/Sema.zig
- src/arch/aarch64/CodeGen.zig
- src/arch/arm/CodeGen.zig
- src/arch/riscv64/CodeGen.zig
- src/arch/sparc64/CodeGen.zig
- src/arch/wasm/CodeGen.zig
- src/arch/x86_64/CodeGen.zig
- src/codegen/c.zig
- src/codegen/llvm.zig
- src/codegen/spirv.zig
- src/print_air.zig
- test/behavior/undefined.zig
> llvm: ensure returned undef is 0xaa bytes when runtime safety is enabled

- lib/std/os/linux/io_uring.zig
The return value of submit() does not actually accurately report the amount of submitted sqes, when using sq_poll. ([see])(https://github.com/axboe/liburing/issues/88)
One can also see this in the zig implementation of liburing in sq_flush() / sq_ready. The kernel sq poll thread may modify the sq.head value "before" the atomic load in sq_ready, which e.g. could result in a return value of 0 after a successful submission of a single sqe.
In my opinion this is a pretty big footgun, when using sq polling in general and especially when preparing more then one sqe before a call to submit. The later case is arguably not actually usable, as the only thing that one does know if submit successfully returns is that one or more requests made it successfully. In this case it is e.g. both possible …
> Added comment about misleading return value of submit(), when used with sq_poll

- src/Sema.zig
- test/behavior/union.zig
Closes https://github.com/ziglang/zig/issues/18732.
During `validateUnionInit` in `Sema.zig`, when trying to determine if a union is comptime known, the `store` AIR instruction is being searched for. However, it will not be emitted if storing is done of zero sized type.
Because the `set_union_tag` AIR instruction is compile-time known, it will be saved in the comptime alloc map, but the `resolveComptimeKnownAllocValue` function has logic for a simple case which will be hit because we have only one store for this union (its tag), but there will be a type mismatch causing the assertion described in the issue, I linked.
There are 2 solutions:
- Convert the `assert` to an if statement, branching out of the simple case.
- Change `validateUnionInit` to handle the case when `store` instruction …
> Sema: fix union init with zero size field
