lib/std/Build/Step/TranslateC.zig
It was failing to compile since the definition of Build.Module changed
=> std.Build.Step.TranslateC: fix use of outdated Module in createModule

src/translate_c.zig, test/cases/translate_c/empty union initializer list.c, test/cases/translate_c/static empty struct.c
resolve #12658
Empty union initializer list is allowed since C23, but gcc and clang allow it to compile in non pedantic code as zero initialized.
Added a condition in transInitListExprRecord to call transZeroInitExpr when the number of initialization expressions is zero.
Also added as a test case for translate_c the example from the bug report.
=> Use mem.zeroes for empty union initializer list

src/arch/x86_64/Emit.zig, src/link/MachO/Atom.zig, src/link/MachO/ZigObject.zig
=> macho: misc fixes and improvements

lib/std/fifo.zig, lib/std/heap.zig, lib/std/heap/general_purpose_allocator.zig, lib/std/io/peek_stream.zig, lib/std/os/uefi/tables.zig, lib/std/os/uefi/tables/boot_services.zig, lib/std/os/uefi/tables/runtime_services.zig
This eliminates some simple usages of `usingnamespace` in the standard library. This construct may in future be removed from the language, and is generally an inappropriate way to formulate code. It is also problematic for incremental compilation, which may not initially support projects using it.
I wasn't entirely sure what the appropriate namespacing for the types in `std.os.uefi.tables` would be, so I ofted to preserve the current namespacing, meaning this is not a breaking change. It's possible some of the moved types should instead be namespaced under `BootServices` etc, but this can be a future enhancement.
=> std: eliminate some uses of `usingnamespace`

src/Sema.zig, test/cases/compile_errors/for_loop_error_union.zig
fixes #18745
supersedes #18759, no action for 2 days.
=> Add error hint when looping over `ErrorUnion`

lib/std/fmt.zig, lib/std/meta.zig
Fixes `hasMethod` which was introduced in #18636 
It should return false for pointers to more than one item.
=> std.fmt: fix formatting slices of structs with custom formatting

lib/std/wasm.zig
Looks like the doc comment was initially copied from the `SimdOpcode`, fixes the typo
=> fix typo in wasm atomic opcodes doc comment

src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/MachO/Relocation.zig, src/link/MachO/Symbol.zig, src/link/MachO/UnwindInfo.zig, src/link/MachO/ZigObject.zig, src/link/MachO/eh_frame.zig, src/link/MachO/relocatable.zig, src/link/MachO/thunks.zig, test/link/link.zig, test/link/macho.zig
Implements `zig build-obj hello.zig -fno-llvm -fstrip`.
Closes #18668 
Emitting DWARF sections is still a TODO.
=> macho: emit relocatable with self-hosted x86_64 backend

lib/std/Build/Cache.zig, stage1/wasi.c
I haven't been able to reproduce the `StreamTooLong` issue to verify, but based on when it was reported, and when I introduced the code this PR fixes, I suspect this may be the fix.
Extracted from #18792
Fixes potentially #16149
=> Cache: fix logic for retrying cache hits

src/link/MachO/Dylib.zig
Turns out that around 10.13/10.14 macOS release version, Apple changed the target tags in tbd files from `macosx` to `macos`. In order to be compliant and therefore actually support linking on older platforms against `libSystem.tbd`, we add `<cpu_arch>-macosx` to target strings.
=> macho: add <cpu_arch>-macosx to target strings as a fallback target

lib/std/zig.zig, src/AstGen.zig, src/Autodoc.zig, src/Compilation.zig, src/InternPool.zig, src/Module.zig, src/Sema.zig, src/Zir.zig, src/main.zig, src/print_zir.zig, src/type.zig
That PR starts work on implementing the frontend portion of incremental compilation. It introduces dependency tracking and invalidation, and modifies the semantic analysis work loop in `Compilation.performAllTheWork` to also analyze outdated decls and functions.
For now, this behavior is locked behind `--debug-incremental`. This is because incremental dependencies are rather large - around 60MiB for the whole compiler with my current representation - and it doesn't make sense for users to pay this cost in memory usage and CPU cycles when they can't actually use incremental compilation yet.
An `InternPool.Depender` is something which undergoes semantic analysis: so a `Decl`, or a runtime function (represented by an `InternPool.Index` to a `func_decl` or `func_instance`). During semantic …
=> Begin re-implementing incremental compilation

src/Sema.zig, test/cases/compile_errors/int_from_enum_undefined.zig
fixes #18767
+ makes running `@intFromEnum` on undefined return undefined
+ makes running `@intFromEnum` on empty enums (that are exhaustive) an error.
~~should we reconsider empty enums in general? they have no actual value representation, and so i'm confused why we have them.~~
=> Make `@intFromEnum` an error for empty enums

src/main.zig
Some declarations, like zig subcommands and usage strings, are unnecessary marked as public, even thought they are only referenced by main.zig.
I'm not sure why these declarations are marked public.  The compiler builds correctly after this change.
`usage_build` is unused, since the usage text has been moved to `lib/build_runner`.
However I decided to not remove it in this commit.  IMHO it should be used to document the options required by all build runners.
=> compiler: remove unnecessary pub declarations in main.zig

src/link/Coff.zig, src/link/Elf/ZigObject.zig, src/link/MachO/ZigObject.zig, src/link/Plan9.zig, src/link/Wasm.zig
This unblocks backend errors after #18814.
=> link: report function failures in `FuncAnalysis`

lib/std/sort.zig
This continues the work started in https://github.com/ziglang/zig/pull/15440 by @CraigglesO. The first commit is a squash of that PR, with attribution retained, and the second commit contains my own changes. From the message of that commit:
The old definitions had some problems:
- In `lowerBound`, the `lhs` (left hand side) argument was passed on the right hand side.
- In `upperBound`, the `greaterThan` function needed to return `greaterThanOrEqual` for the function work, so either the name or the implementation is incorrect.
To fix both problems, define the functions in terms of a `lessThan` function that returns `lhs < rhs`.
The is more consistent with the rest of `sort.zig` and it's also how C++ implements lower/upperBound (1)(2).
(1) …
=> Add upperBound, lowerBound, and equalRange 

src/link/MachO.zig, src/link/MachO/Archive.zig, src/link/MachO/Object.zig, src/link/MachO/ZigObject.zig, src/link/MachO/file.zig, src/link/MachO/relocatable.zig
This removes any fallback to `llvm-ar` for all MachO codepaths.
Closes #18667
=> macho: implement our own archiver

test/link/macho.zig
Fixes #18018
This fix is requires to make the build runner even compile when building Zig on architectures like RISC-V.
=> test.link.macho: fix for non-x86 and arm architectures

.gitattributes
Fixes git autocrlf issues with .zon files on Windows
Without this change I was hitting line ending mismatches for https://github.com/ziglang/zig/blob/master/lib/init/build.zig.zon locally since git checked it out as CRLF and then `zig fmt` changed it to LF.
=> Mark .zon as eol=lf

stage1/wasm2c.c
I have just built Zig from source for the first time. I have done it with `-Wall -Werror` by accident (had `CFLAGS` env variable set) and found that there are two unused variables in `wasm2c.c`. I thought that fixing that might be a good way to start contributing to the project.
=> remove unused local variables

src/Sema.zig, test/cases/compile_errors/store_to_comptime_var_through_call.zig
This fixes the second part of  #18502
=> Sema: catch runtime stores to comptime variables through calls

lib/std/log.zig
The default logging function used to have no buffer. So a single log statement could result in many individual write syscalls each writing only a couple of bytes.
After this change the logging function now has a 4kb buffer. Only log statements longer than 4kb now do multiple write syscalls.
4kb is the default bufferedWriter size and was choosen arbitrarily.
The downside of this is that the log function now allocates 4kb more stack space but I think that is an acceptable trade-off.
example:
```zig
std.log.info("Hello {s}!", .{"World"});
}
```
strace before:
```
...
write(2, "info: Hello ", 12info: Hello )            = 12
write(2, "World", 5World)                    = 5
write(2, "!\n", 2!
)                      = 2
...
```
strace after:
``` …
```
=> Buffer the logging function

ci/x86_64-macos-release.sh, lib/std/builtin.zig, src/Compilation.zig, src/link/Dwarf.zig, src/link/MachO.zig, src/link/MachO/DebugSymbols.zig, src/link/MachO/ZigObject.zig, src/link/MachO/relocatable.zig, test/link/macho.zig
builtin: enable panic handler on self-hosted MachO
Compilation: toggle compiler-rt and zig-libc capabilities for MachO
It is now possible to bootstrap a usable non-LLVM Zig on x86_64-macos.
Please note that emitted DWARF in a relocatable is itself non-relocatable (like for ELF) and this will need to be addressed separately.
Closes #18794
=> macho: emit DWARF for ZigObject relocatable

src/arch/wasm/CodeGen.zig
=> wasm: correctly lower packed structs in arguments

lib/std/os/linux.zig, lib/std/os/linux/io_uring.zig
This implements the IORING_OP_WAITID operation. It is the equivalent of a waitid(2) syscall and can be used to be notified about child process state changes.
Available since kernel 6.7
liburing reference:
- https://github.com/axboe/liburing/blob/master/src/include/liburing/io_uring.h#L252-L258
- https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L1157-L1167
=> io_uring: add waitid operation

src/Sema.zig, src/type.zig, test/cases/compile_errors/directly_embedding_opaque_type_in_struct_and_union.zig, test/cases/compile_errors/illegal_comparison_of_types.zig, test/cases/compile_errors/int_from_enum_undefined.zig, test/cases/compile_errors/invalid_deref_on_switch_target.zig, test/cases/compile_errors/invalid_inline_else_type.zig, test/cases/compile_errors/invalid_multiple_dereferences.zig, test/cases/compile_errors/non-const_variables_of_things_that_require_const_variables.zig
This ensures that the note is added in more places and that `errMsg` needs to be used in fewer places.
=> Sema: add declared here notes in `fail`

lib/std/os/linux/io_uring.zig
Implemented the fetching of a batch of cqes from the ringbuffer, as either one or two memcopies, as suggested in the todo comment.
Also removed unnecessary function argument.
=> Memcpy optimization in copy_cqes_ready

lib/std/child_process.zig, lib/std/fs/Dir.zig, lib/std/fs/File.zig, lib/std/os.zig, lib/std/os/windows.zig, lib/std/zig/system.zig
Encountered in a recent CI run on an aarch64-windows dev kit.
Pretty sure I disabled the virus scanner but it looks like it turned itself back on with a Windows Update.
=> std.os.windows.OpenFile: add missing error

lib/std/c/linux.zig, lib/std/os.zig
Export the T struct and winsize struct for targets which have it defined
in std.c. The T struct defines libc constants for ioctl syscalls.
Exporting these as part of `os.zig` allows callers to access these fields in a portable way, preventing the need to call into each std.c implementation to get the constants or winsize struct definition.
=> std.os: export T struct and winsize struct

lib/std/c/dragonfly.zig, lib/std/c/emscripten.zig, lib/std/c/freebsd.zig, lib/std/c/netbsd.zig, lib/std/c/openbsd.zig, lib/std/c/solaris.zig, lib/std/fs/Dir.zig
Minor changes as per 7680c5330cb mostly about pipe2() flags.
closes #18927
=> bsd: debitrot type-safe std.c.O

lib/std/Build.zig
Also address clobbering diagnostics field with an assert and
doc comment to use the Target.Query.parse function themselves.
Fixes #18876
=> std.Build: fix wrong variable used in `parseTargetQuery`

src/codegen/llvm.zig, test/behavior/struct.zig
This change allows recursing over types that are currently being resolved fully with a second pass of forward resolution.
Closes #16414
=> llvm: fix lowering of recursive debug info

lib/std/c.zig, lib/std/c/dragonfly.zig, lib/std/c/freebsd.zig, lib/std/c/netbsd.zig, lib/std/c/openbsd.zig
- macos uses 64-bits for the flag types.
- also add/fix `std.c.TCSA` for the BSDs
- code example in #18942 now works for macos and BSDs
closes https://github.com/ziglang/zig/issues/18942
=> std.os.termios: fix tc flag types for macos

lib/std/os.zig, lib/std/os/windows.zig, src/link.zig
Thanks to @matklad for finding this additional NTSTATUS possibility when calling GetFinalPathNameByHandle.
Follow-up issue:
* #18953
=> std.os.windows: add error.UnrecognizedVolume

src/Sema.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/link/Dwarf.zig, src/type.zig, test/cbe.zig
This should avoid the random pointer invalidation crashes.
Closes #18954
=> InternPool: make more use of `NullTerminatedString.Slice`

src/AstGen.zig, src/Autodoc.zig, src/Module.zig, src/Sema.zig, src/Zir.zig, src/print_zir.zig, test/cases/compile_errors/non_constant_expression_in_array_size.zig
This PR doesn't have a single direction, sorry - it was just a chain of me noticing things to improve. The changes fall into two broad categories.
The first is the elimination of `Sema.src`. This field was a failed experiment, complicating the frontend and making unwarranted assumptions about the existence of source-location-providing instructions. Eliminating this did require adding source nodes to a handful of ZIR instructions and changing a few encodings. This slightly increased ZIR bytes, but that is mitigated by...
The second thing is a series of optimizations in `AstGen` to minimize the size of generated ZIR. The logic for eliding consecutive `dbg_stmt` instructions has been fixed, since it didn't previously work in some cases. In addition, the `ret_type` instruction no longer …
=> A loose collection of random enhancements

src/link/C.zig
Previously, `zig build-exe foo.zig -ofmt=c` emits `foo.c` with `755` mode. This PR lets `createFile()` use default `.mode` and `foo.c` is emitted with `644` mode (assuming typical umask of 022).
Closes #13407
=> cbe: do not set execute bits on emitted file

lib/std/dwarf.zig, lib/std/dwarf/TAG.zig, lib/std/dwarf/expressions.zig, lib/std/io/fixed_buffer_stream.zig, src/link/Dwarf.zig
This code is run when printing a stack trace in a debug executable, so it has to be fast even without compiler optimizations.
Adding a `@panic` to the top of `main` and running an x86_64 backend compiled compiler goes from `1m32.773s` to `0m3.232s`.
=> dwarf: optimize dwarf parsing for speed

lib/std/os.zig
- update root.os.system override to require "system" field
- this allows easier overriding of `os.heap.page_allocator` in a users `main.zig`, which I'm currently using to fix allocations with Emscripten
- https://github.com/ziglang/zig/pull/18999
=> update root.os.system override to require "system" field, this allows easier overriding of os.heap.page_allocator

lib/std/io.zig, lib/std/io/buffered_tee.zig, src/Package/Fetch/git.zig
While analyzing #18967 I came to the idea of this kind of stream, Ian named it BufferedTee. The main idea is to allow consumer to put back to the stream some bytes it has already read, allowing it to lookahead few bytes and letter change it's mind and not consume them. Other consumers of the same stream should not be affected by this. BufferedTee is holding other consumers some number of bytes behind 'main' consumer allowing it to put back that number of bytes.
I feel that except helping with this particular case there can be other cases using lookahead approach which can found this type of stream useful. That is the reason behind this PR.
> BufferedTee provides reader interface to the consumer. Data read by consumer is also written to the output. Output is hold lookahead_size bytes …
=> propose adding BufferedTee to the std.io

lib/std/tar.zig
First was treating header mode field (8 bytes) same way as size field (12 bytes). We had to get invalid tar header to exploit that. 
Second was integer overflow also exploited by invalid tar header.
Fixed, and we now have tests for those cases.
Thanks @squeek502 for also [pointing](https://discord.com/channels/605571803288698900/906306963942543370/1210457032990269490) to this.
=> std:tar fix two crashes found by fuzzing

lib/std/fs.zig
Currently when building with emscripten, file access functions will fail because PATH_MAX isn't defined so we set Emscripten to use std/os/emscripten.zig's PATH_MAX (currently 4096).
ie.
```sh
C:\zig\current\lib\std\fs.zig:53:9: error: PATH_MAX not implemented for emscripten
@compileError("PATH_MAX not implemented for " ++ @tagName(builtin.os.tag)),
```
=> emscripten: set PATH_MAX to emscripten.os.PATH_MAX

lib/std/os.zig
**Description**
Not actually sure if we want this change for Emscripten, but have documented in this PR the results in console when you make it. With @trap for emscripten, it seems to hit an unreachable state issue.
**Code used to test this change**
```zig
if (true) @panic("my panic test");
}
```
**Before in Chrome DevTools console (short)**
- map-editor.js:4692 panic: my panic test
- map-editor.js:4692 Aborted(native code called abort())
- map-editor.js:20 Uncaught RuntimeError: Aborted(native code called abort())
**After in Chrome DevTools console (short)**
- map-editor.js:4687 panic: my panic test
- Uncaught RuntimeError: unreachable
**Before in Chrome DevTools console (long)**
- map-editor.js:4692 panic: my panic test
- err @ map-editor.js:4692
- …
=> emscripten: use @trap instead of system.abort for emscripten

lib/std/debug.zig
**Description**
This change follows `wasi` and stops trying to use DwarfInfo for emscripten builds
It stops the following compilation error from happening:
```
C:\zig\current\lib\std\debug.zig:726:23: error: no field or member function named 'getDwarfInfoForAddress' in 'dwarf.DwarfInfo'
if (try module.getDwarfInfoForAddress(unwind_state.debug_info.allocator, unwind_state.dwarf_context.pc)) |di| {
~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
C:\zig\current\lib\std\dwarf.zig:663:23: note: struct declared here pub const DwarfInfo = struct {
^~~~~~
referenced by:
next_internal: C:\zig\current\lib\std\debug.zig:737:29
next: C:\zig\current\lib\std\debug.zig:654:31
remaining reference traces hidden; use '-freference-trace' to see all reference traces
C:\zig\current\lib\std\debug.zig:970:31: error: no field or …
```
=> emscripten: fix compilation issues with getSymbolAtAddress and getDwarfInfoForAddress

lib/std/http/test.zig, lib/std/os.zig, lib/std/os/windows.zig, lib/std/zig/system.zig
Technically breaking since it removes NetNameDeleted from `std.os.read`. This error is now folded into ConnectionResetByPeer.
Fixes the CI failure observed in master branch:
```
test
+- test-std
+- run test std-x86_64-windows.win10_fe...win10_fe-gnu-znver3-Debug stderr
error.Unexpected: GetLastError(64): The specified network name is no longer available.
D:\a\zig\zig\lib\std\os\windows.zig:539:49: 0x1080157 in WriteFile (test.exe.obj)
else => |err| return unexpectedError(err),
^
D:\a\zig\zig\lib\std\os.zig:1265:33: 0x10956ce in write (test.exe.obj)
return windows.WriteFile(fd, bytes, null);
^
D:\a\zig\zig\lib\std\os.zig:1349:21: 0x15b050f in writev (test.exe.obj)
return write(fd, first.iov_base[0..first.iov_len]);
^
D:\a\zig\zig\lib\std\net.zig:1876:25: 0x18e9d93 in writev (test.exe.obj) …
```
=> std: map NETNAME_DELETED to error.ConnectionResetByPeer

lib/std/Build/Module.zig, lib/std/Build/Step/Compile.zig
cc @jacobly0 
Makes it possible to prepend a LazyPath that might have been derived from a `zig-cache` dep, and prepend it to a list of files.
I was adding `libgit2` as a dep to my project by downloading the tar ball from Github archive and since, (submodules bad) I used the build system. This leaves me with a `LazyPath` to the location in `zig-cache`, and a large list of files I need to add to the exe with the same flags. Since `addCSourceFiles` takes a "hardcoded" list of relative paths, I had no way to access things inside the `zig-cache`
=> change `addCSourceFiles` to use `LazyPath` instead `Dependency`

build.zig, test/tests.zig
This was added as a workaround for a bug that has since been fixed.
=> Revert "tests: add -Dskip-cross-glibc option"

lib/std/os/test.zig
- skip only RLIMIT_STACK test on macos
closes #18395
=> std: re-enable most of setrlimit test on macos

lib/std/heap.zig
std.heap.c_allocator was already doing this, however, std.heap.raw_c_allocator, which asserts no allocations more than 16 bytes aligned, was not.
The zig compiler uses std.heap.raw_c_allocator, so it is affected by this.
Using this example program:
```zig
const gpa = std.heap.raw_c_allocator;
//var general_purpose_allocator: std.heap.GeneralPurposeAllocator(.{}) = .{};
//const gpa = general_purpose_allocator.allocator();
const stdout = std.io.getStdOut().writer();
var slice = try gpa.alloc(u8, 1);
for (2..100000) |i| {
if (gpa.resize(slice, i)) {
slice = slice.ptr[0..i];
try stdout.print("{d} - resized\n", .{i});
} else {
try stdout.print("{d} - reallocated\n", .{i});
const new_slice = try gpa.alloc(u8, i);
gpa.free(slice);
slice = …
```
=> std.heap.raw_c_allocator: use malloc_size for resize

src/codegen/llvm.zig, src/codegen/llvm/Builder.zig
Follow up to #19031 
This PR reworks the debug location system in the LLVM Builder so that we don't always emit debug locations twice.
=> Rework LLVM debug locations to not emit them twice

src/Package/Fetch.zig
Regressed in ed4ccea7bae99c1baa634716941f308d9f922985. The early exit path was only supposed to happen in case of --system mode.
=> package management: fix regression of printing expected hash

lib/std/fmt/parse_float.zig, lib/std/fmt/parse_float/decimal.zig, lib/std/fmt/parse_float/parse_float.zig
Found while fuzzing. Previously `1.1897314953572317650857593266280070162E4932` was parsed as `+inf`, which caused issues for round-trip serialization of floats. Only f128 had issues, but have added other tests for all floating point large normals.
The max_exponent for f128 was wrong, it is subtly different in the decimal code-path as it is based on where the decimal digit should go. This needs to be 2 greater than the max exponent (e.g. 308 or 4932) to work correctly (greater by 1, then we use a >= comparision).
In addition, I've removed the redundant `optimize` constant which was only use for testing the slow path locally.
=> fix large f128 values being incorrectly parsed as inf

lib/std/debug.zig
**Description**
Following the pattern with Wasi for the time-being and considering the memory valid.
**Crash that can occur without this change**
**Potential future improvement**
*Please note: I'm very new to Emscripten / C-isms in general, so if anything I say below doesn't make sense, then it probably doesn't.*
Emscripten provides functions that give you the stacks range in memory here, if StackIterator is only iterating over stack addresses, we could valid the range with these:
https://github.com/emscripten-core/emscripten/blob/5441b40acb9a751ae03b61fd1c85949971826b64/system/include/emscripten/stack.h
Also it's my understanding that we could see if dynamic heap allocations are out of bounds by making sure they're below the sbrk value (I only just became aware of what sbrk is yesterday, …
=> emscripten: fix crash when calling StackIterator.isValidMemory with emscripten

lib/std/http/Client.zig, lib/std/http/HeaderIterator.zig, lib/std/http/Server.zig, lib/std/http/test.zig, lib/std/mem.zig
The header value could be empty. I believe this was meant to check if the header name is empty.
=> http: check for empty header name instead of value

src/Sema.zig, src/codegen/llvm.zig, src/codegen/llvm/Builder.zig
This avoids llvm module verification errors when the strip option is different across modules.
=> llvm: implement per-module stripping

src/AstGen.zig
Running `zig ast-check -t` on this code crashes for me on `master` branch:
```zig
pub fn foo() void {}
```
with this error (full stack trace below):
```
thread 6563100 panic: index out of bounds: index 10, len 8
/Users/user/repos/zig/lib/std/zig/Ast.zig:478:30: 0x1102f8be0 in firstToken (zig)
while (true) switch (tags[n]) {
```
As far as I can tell it was introduced in https://github.com/ziglang/zig/commit/434537213e406191959818f573b24ca45c1b0e45. `ast-check -t` works for me with this fix but I'm not sure if this has other implications, cc @mlugg 🙏 
<details>
```
thread 6563100 panic: index out of bounds: index 10, len 8
/Users/user/repos/zig/lib/std/zig/Ast.zig:478:30: 0x1102f8be0 in firstToken (zig)
while (true) switch (tags[n]) {
^ …
```
=> AstGen: fix OoB crash on `ast-check -t`

src/codegen/llvm/Builder.zig, src/codegen/llvm/bitcode_writer.zig, src/codegen/llvm/ir.zig
This PR reduces the size of emitted bitcode by both reducing the size of the `DebugLoc` record and using block info blocks to avoid emitting duplicate `DEFINE_ABBREV` records.
Below are bitcode sizes when compiling master in debug mode:
```
build.bc: 13M
c.bc: 12K 
compiler_rt.bc: 1.1M
zig.bc: 142M
```
```
build.bc: 15M
c.bc: 15K 
compiler_rt.bc: 960K
zig.bc: 145M
```
```
build.bc: 14M
c.bc: 15K 
compiler_rt.bc: 829K
zig.bc: 132M
```
```
build.bc: 12M
c.bc: 14K 
compiler_rt.bc: 669K
zig.bc: 118M
```
=> LLVM reduce size of emitted bitcode

lib/std/compress/flate.zig, lib/std/compress/flate/deflate.zig, src/link/Wasm.zig, test/tests.zig
to match the other operating systems. 16 MiB
closes #18885
=> change default WASI stack size

lib/std/http/Server.zig, lib/std/http/test.zig
Previously this would trip an assertion failure:
```
Test [41/58] http.test.test.stream read/write... thread 220203 panic: reached unreachable code
/home/andy/dev/zig/lib/std/debug.zig:403:14: 0x147c10d in assert (test)
^
/home/andy/dev/zig/lib/std/http/Server.zig:587:27: 0x16a14c8 in read_chunked (test)
assert(s.state == .receiving_body);
^
/home/andy/dev/zig/lib/std/io/Reader.zig:10:23: 0x150bdcb in read (test)
return self.readFn(self.context, buffer);
^
/home/andy/dev/zig/lib/std/http/test.zig:910:42: 0x156a921 in run (test)
const n = try reader.read(&buf);
^
/home/andy/dev/zig/lib/std/Thread.zig:427:13: 0x155466a in callFn__anon_22868 (test)
@call(.auto, f, args) catch |err| {
^
/home/andy/dev/zig/lib/std/Thread.zig:1199:30: 0x1525bd7 in …
```
=> std.http.Server: fix use case of streaming both reading and writing

src/Sema.zig, test/behavior/generics.zig
Closes https://github.com/ziglang/zig/issues/17086.
Closes https://github.com/ziglang/zig/issues/18433.
Closes https://github.com/ziglang/zig/issues/19015.
The problem in these issues can be reduced to:
```zig
pub fn Struct(comptime T: type) type {
return struct {
pub fn foo(comptime x: usize) struct { T } {
_ = x;
unreachable;
}
};
}
test "foo" {
const S = Struct(f64);
_ = S.foo(1);
}
```
The generic call `S.foo()` was evaluated with the capture scope of the owner decl (i.e the `test` block), when it needs to use the capture scope of the function declaration.
=> Sema: evaluate generic instantiations in fn decls capture scope

src/Sema.zig, test/cases/compile_errors/switch_on_undefined_union.zig
Before this fix, passing an undefined union value to `Sema.switchCond` returned an undefined value of the union type, not the tag type, since `Value.unionTag` forwards undefined values unchanged. This leads us into the `.Union` branch in `Sema.zirSwitchBlock` which is unreachable, now we take the `.Enum` branch instead.
Closes https://github.com/ziglang/zig/issues/18297.
=> Sema: fix compile error for switching on undefined union

src/Sema.zig, test/cases/compile_errors/union_calling_inactive_field_as_fn.zig
Reuse `unionFieldPtr` here to ensure that all the safety checks are included.
Closes https://github.com/ziglang/zig/issues/18546.
Closes https://github.com/ziglang/zig/issues/18625.
=> Sema: check for inactive union field when calling fn at comptime

src/Sema.zig, src/type.zig, test/behavior/tuple.zig
- Add default values to the list of comptime-known elements in `zirValidatePtrArrayInit`
- In `structFieldValueComptime`, only assert `haveFieldInits` if we enter the`fieldIsComptime` branch (otherwise they are not needed).
Closes https://github.com/ziglang/zig/issues/17349.
=> Sema: fix tuple default values

lib/std/Uri.zig, lib/std/http/Client.zig, lib/std/http/Server.zig, lib/std/http/test.zig
* Support different keep alive defaults with different http versions.
* Fix incorrect usage of `copyBackwards`, which copies in a backwards direction allowing data to be moved forward in a buffer, not backwards in a buffer.
=> http: fix fetching a github release

src/arch/wasm/abi.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig
The wasm backend ABI classification for vectors is currently surprising. It only works for int types and classifies based on the size of element type which is not in line with how the self-hosted wasm backend represents vectors in [`determineSimdStoreStrategy`](https://github.com/ziglang/zig/blob/63de8a59891f2c342d1a51b808cf04a895ba54d6/src/arch/wasm/CodeGen.zig#L1793-L1803).
~~With this change, the ABI use a v128 when the size is 128 and use a reference to memory instead otherwise. This works for non integer vectors (bool, float, and pointers).~~
~~This change means that instead of unrolling vectors as parameters, they are passed as reference (for the llvm backend since they were passed as reference already in the self-hosted backend):~~
```zig
const T = i32;
const V = @Vector(5, T);
pub …
```
=> wasm: allow non-int vectors

lib/std/compress/zstandard.zig
The increase in stack size for wasm32 targets in commit d51aa9748f allows the streaming decompressor to be tested on wasm32-wasi.
=> std.compress.zstd: enable tests for wasm32

lib/std/testing.zig
closes #19099
The choice to depend on `testing.expectEqualStrings()` was arbitrary and I only chose it because I'm familiar with it.
=> testing.expectFmt() - reuse expectEqualStrings()

lib/std/child_process.zig, lib/std/fs.zig, lib/std/fs/Dir.zig, lib/std/os.zig, lib/std/zig/system.zig
`InvalidHandle` in `OpenError` is no longer a possible error on any platform. In the past it was able to be returned in `openOptionsFromFlagsWasi`, but the implementation was changed in 7680c5330cbc9141b9a5444e30c512b6068ab50d to make it no longer possible.
`InvalidHandle` in `RealPathError` was a holdover from before d5312d53a066092ba9efd687e25b29a87eb6290c, which (re)made realpath a compile error on WASI. However, InvalidHandle was also a possible error in the FreeBSD fallback implementation added in 537624734c4db9e0cdbdc0ebce57375d17172a70. This commit changes the FreeBSD fallback implementation to return FileNotFound instead of InvalidHandle which matches how EBADF is handled in all the other `realpath` implementations (including the FreeBSD non-fallback implementation).
Closes #19084
=> Eliminate `error.InvalidHandle` from OpenError and RealPathError

lib/std/compress/flate.zig
They were disabled because insufficient stack size. 
That is [changed](https://github.com/ziglang/zig/commit/d51aa9748f9e4e3616328a207a8047ff37d81f8b) now.
=> compress: activate flate tests in wasm32

lib/std/compress/flate/CircularBuffer.zig
I noticed that the new inflate implementation was slower when it comes to repeating data, like for example a bunch of zeroes.
This is relevant for things like images and voxel data, where we often see long runs of repeating data.
To improve this I used memcopies of iteratively doubling size for repeating data like this.
This is a fairly common approach and was also present in the old inflate implementation.
<details>
<summary>Code</summary>
```zig
pub fn deflate(allocator: std.mem.Allocator, data: []const u8) ![]u8 {
var result = std.ArrayList(u8).init(allocator);
var comp = try std.compress.flate.compressor(result.writer(), .{});
_ = try comp.write(data);
try comp.finish();
return try result.toOwnedSlice();
}
pub fn inflateTo(buf: []u8, data: []const u8) …
```
=> Improve inflate performance for repetitive data

src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, src/codegen/llvm/bitcode_writer.zig
This PR contains some miscellaneous improvements to the LLVM backend
* Implement more efficient blob writing by taking advantage of the forced alignment in the bitcode format
* Separate out strtab strings from normal Builder strings allowing for a smaller bitcode STRTAB block
* Don't create lexical blocks when encountering an `dbg_inline_begin` as LLVM handles subprograms fine.
* ~Emit a metadata index record allowing LLVM to lazily load metadata~
```
Benchmark 1 (3 runs): 0.12.0-dev.3055+085bde688 (ReleaseSafe)
wall_time          80.3s  ±  542ms    79.9s  … 80.9s           0 ( 0%)        0%
peak_rss           4.94GB ±  705KB    4.94GB … 4.94GB          0 ( 0%)        0%
cpu_cycles          357G  ±  667M …
```
=> LLVM: Miscellaneous improvements to Builder

lib/std/tar.zig, lib/std/tar/test.zig
In the iterator function which is the low-level API, don't depend on
`std.fs.MAX_PATH_BYTES` because this is not defined on all operating
systems, such as freestanding.
However in such environments it still makes sense to be able to extract
from a tar file.
Breaks the low-level iterator() API but not the high level pipeToFileSystem() API.
cc @ianic for review
=> std.tar: avoid dependency on file system

src/Compilation.zig, src/link/Wasm.zig
Fixes false positive cache hit.
=> add missing export symbol names to whole mode wasm cache hash

lib/std/tar.zig, lib/std/tar/test.zig
Fix regression made by previous PR #19081
Fixes #19124
=> std.tar: fix unconditional error return

src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, src/codegen/llvm/ir.zig
Fixes  #19131
The field values were emitted in the wrong integer format making LLVM parse the wrong values.
=> LLVM: Fix debug info for enum field values

src/link/MachO.zig, src/link/MachO/Object.zig
In `ld -r` mode, the linker will emit `N_GSYM` for any defined external symbols as well as private externals. In the former case, the thing is easy since `N_EXT` bit will be set in the nlist's type. In the latter however we will encounter a local symbol with `N_PEXT` bit set (non-extern, but was private external) which we also need to include when resolving symbol stabs.
The major change in the logic for parsing symbol stabs per input object file is that we no longer try to force-resolve a `N_GSYM` as a global symbol. This was a mistake since every symbol stab always describes a symbol defined within the parsed input object file. We then work out if we should forward `N_GSYM` in the output symtab after we have resolved all symbols, but never before - intel we lack when initially parsing …
=> macho: correctly find N_GSYM symbols when parsing symbol stabs

lib/std/Build/Cache.zig, lib/std/Build/Step/ObjCopy.zig
According to this man page: https://man7.org/linux/man-pages/man1/objcopy.1.html, only-section in objcopy supports copying multiple sections, this PR adapt current build system to support it.
>--only-section=sectionpattern
>     Copy only the indicated sections from the input file to the
>     output file.  This option may be given more than once.  Note
>     that using this option inappropriately may make the output
>     file unusable.  Wildcard characters are accepted in
>     sectionpattern.
>
>     If the first character of sectionpattern is the exclamation
>     point (!) then matching sections will not be copied, even if
>     earlier use of --only-section on the same command line would
>     otherwise copy it.  For example:
>
>               --only-section=.text.* …
=> objcopy: support multiple only sections

lib/std/fs/Dir.zig, lib/std/fs/test.zig, lib/std/tar/test.zig
Follow up to https://github.com/ziglang/zig/pull/19126, fixes the Windows bug that was uncovered and re-enables the failing test.
=> Fix symLink's handling of `/` path separators on Windows

lib/std/zig/AstGen.zig, src/Autodoc.zig, src/Module.zig, src/Sema.zig, src/codegen/llvm.zig
Two things here:
* A couple of optimizations in `AstGen`, most notably elision of a bunch of unnecessary `block` instructions. This results in a big drop in ZIR bytes.
* Cleanups to the main loop of `Sema` to improve simplicitly and readability.
According to my quick testing, these changes have minimal performance impact, but it's a benefit where it exists, e.g.:
```
Benchmark 1 (30 runs): /home/mlugg/zig/master/stage4-fast/bin/zig test -fno-emit-bin test/behavior.zig
wall_time           688ms ± 9.42ms     669ms …  711ms          0 ( 0%)        0%
peak_rss            104MB ±  160KB     104MB …  104MB          0 ( 0%)        0%
cpu_cycles         2.28G  ± 32.5M     2.22G  … 2.37G           0 ( 0%)        0% …
```
=> Major ZIR size optimizations & small cleanups in Sema

lib/std/http/Client.zig, lib/std/http/HeaderIterator.zig, lib/std/http/Server.zig, lib/std/http/test.zig
HTTP fields are defined as `field-line = field-name ":" OWS field-value OWS`. The whitespace following `:` is optional, and whitespace following the value is optional. This fixes std.http to not assume all headers are sent as `"Field: Value"`.
Additionally fixes up the trailer boundary check in the headers iterator, as checking for CRLF CRLF (the end of head fields) is much more sound than checking that name and value are 0 length. Also adds an assert that name.len is greater than zero.
=> std.http: fix http field parsing

src/Air.zig, src/Liveness.zig, src/Liveness/Verify.zig, src/Sema.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/print_air.zig, test/behavior/switch.zig
This prevents the possibility of not emitting a `.dbg_inline_end` instruction and reduces the allocation requirements of the backends.
Closes #19093
=> Air: replace `.dbg_inline_*` with `.dbg_inline_block`

src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/zig_llvm.cpp, src/zig_llvm.h
This PR should ensure that zig doesn't finish compiling with LLVM warnings about broken debug info and instead fail.
=> LLVM: Fail to emit if LLVM encounters broken debug info

src/mingw.zig
Fixes a mismatch where the manifests would be written to the local cache dir, but the .def/.lib files themselves would be written to the global cache dir. This meant that if you cleared your global cache, your local cache would still think that the .lib files existed in the cache and it'd lead to 'No such file or directory' errors at linktime.
This local/global cache mismatch was introduced in the stage1 -> stage2 transition of this code.
---
This is something I've run into many times but never looked into the root cause until now.
Note: The `mingw.zig` code now matches what's done in `glibc.zig`:
https://github.com/ziglang/zig/blob/90c1a2c41aafb1e35e075fb7d0bdcf04c00db913/src/glibc.zig#L676-L684
=> Use the global cache dir for the manifests of generated mingw `.lib`s

lib/std/os/linux.zig
The functions `renameat` and `statx` accept `[*]const u8` values for path names, which may lead to undefined behavior at run time. For example, given a path to a file, I may want to inspect (every component of) the parent directory before operating on that file per CERT C rec. [FIO15]. I decide to use statx(2) to avoid copying irrelevant data:
```zig
const debug = std.debug;
const fs = std.fs;
const mem = std.mem;
const linux = std.os.linux;
const dir_name = fs.path.dirnamePosix("/usr/bin/vi").?;
debug.assert(mem.eql(u8, dir_name, "/usr/bin"));
var statx_buf: linux.Statx = undefined;
debug.assert(linux.getErrno(linux.statx(
linux.AT.FDCWD,
dir_name.ptr,
linux.AT.SYMLINK_NOFOLLOW,
linux.STATX_TYPE | linux.STATX_MODE,
&statx_buf,
)) == …
```
=> std.os.linux: enforce null-terminated path arguments

doc/langref.html.in, lib/std/zig/Ast.zig, lib/std/zig/Parse.zig
Previously, the following matched both `ContainerField` alternatives:
* `IDENTIFIER`
* `IDENTIFIER` `COLON` `TypeExpr`
=> grammar: remove gratuitous ambiguity

lib/std/compress/flate.zig, lib/std/compress/flate/bit_reader.zig, lib/std/compress/flate/container.zig, lib/std/compress/flate/inflate.zig, lib/std/compress/gzip.zig, lib/std/compress/zlib.zig
Inflate is internally using 8 byte bit buffer. We don't know in advance how many
bytes is compressed data block long. Once we reach end of block there may be
some bytes left in that internal buffer. That result that we move underlying
reader few bytes ahead of end of compressed data block. That is problem when
compressed block is followed by another data which need to be consumed.
We run into this problem in [zig package manager](https://github.com/ziglang/zig/issues/18967) when unpacking git
packfile and than again in [zigimg](https://github.com/zigimg/zigimg/pull/164) project.
**This PR ensures that zlib decompressor never overshoots.** Zlib is now using 4
byte internal buffer. At the end of deflate stream we can overshoot for at most
4 bytes. After deflate stream, in zlib, there is 4 …
=> compress.zlib: don't overshoot underlying reader

build.zig, test/cases/run_translated_c/compound_assignments_with_implicit_casts.c, test/cases/run_translated_c/explicit_cast_bool_from_float.c, test/src/Cases.zig, test/tests.zig
This PR adds several fixes and improvements for the Zig compiler test harness.
1. -Dskip-translate-c option added for skipping the translate-c tests.
2. translate-c and run-translated-c tests in test/cases/* have been added to the `test-translate-c` and `test-run-translated-c` steps. Closes #18224.
3. Custom name added to the CheckFile step for the translate-c tests to better communicate which test failed.
4. Test manifest key validation added to return an error if a manifest contains an invalid key.
=> test manifest key checking and other fixes

src/Sema.zig, test/behavior/extern.zig
Follow-up to #18554.
This fixes a bug where, at least with the LLVM backend, `@extern` calls which had the same name as a normal `extern` in the same Zcu would result in the `@extern` incorrectly suffixing the identifier `.2`. Usually, the LLVM backend has a system to change the generated globals to "collapse" them all together, but it only works if `updateDecl` is called!
=> Sema: perform codegen for anon decl created by `@extern`

src/Package/Fetch/git.zig
My first zlib implementation broke git fetch because it introduce [lookahead](https://github.com/ziglang/zig/issues/18967). That resulted in workarounds [1](https://github.com/ziglang/zig/commit/80f3ef6e14a1213d1c3b31d515870afb43cc9379) [2](https://github.com/ziglang/zig/commit/d00faa2407cdeaa058da62f2d95f64f9e7ed6a09).
After [removing](https://github.com/ziglang/zig/pull/19163) lookahead in zlib decompressor this fixes are no longer necessary.
cc @ianprime0509 for review
=> package: remove git fetch zlib lookahead fix

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
Fixes #19235.
The current `math.big.int.llsignedand(r, a, a_positive, b, b_positive)` implementation is not complete when `a` is positive and `b` is negative, resulting in the result not having higher bytes when `b.len < a.len`.
This is likely due to the wrong evaluation as written in this comment: 
https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/math/big/int.zig#L3990-L3992
Context:
https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a45cbee609d3b/lib/std/math/big/int.zig#L3974-L3977
It should be `a & ~(0 - 0) = a & ~0 = a`, so we should actually continue collecting `a[b.len..a.len]` into the higher part of the result.
From this little mistake, we had the wrong assumption that:
https://github.com/ziglang/zig/blob/4ba4f94c93d5eb1945f1b2c8c53a …
=> math.big.int: fix incorrect `bitAnd` behaviour

lib/std/crypto.zig, lib/std/crypto/ml_kem.zig
ML-KEM is the Kyber post-quantum secure key encapsulation mechanism, as being standardized by NIST: https://csrc.nist.gov/pubs/fips/203/ipd
Too bad, they decided to rename it; the "Kyber" name was so much better!
This implements the current draft (NIST FIPS-203), which is already being deployed even though the specification is not finalized.
=> std.crypto: add support for ML-KEM

lib/std/crypto/ml_kem.zig
Don't use camelCase for variable names, especially just for that one.
=> ml_kem.zig: inLen -> in_len

lib/std/crypto/aegis.zig, lib/std/crypto/aes_gcm.zig
These systems write the number of *bits* of their inputs as a u64.
However if `@sizeOf(usize) == 4`, an input message or associated data whose size is > 512 MiB could overflow.
On 64-bit systems, it is safe to assume that no machine has more than 2 EiB of memory.
=> {aegis,aes_gcm}: fix overflow with huge inputs on 32-bit systems

lib/std/os/emscripten.zig
These were missing in https://github.com/ziglang/zig/pull/18994
=> Fix emscripten exports

lib/std/compress/xz/block.zig
In the example from the issue https://github.com/ziglang/zig/issues/19052 to_read holds 213_315_584
uncompressed bytes. Calling read with small output results in many
shifts of that big buffer.
This removes the need to shift to_read after each read.
The example from the issue which took almost 3 hours now finishes in less than a second. 
Fixes: #19052
=> compress.xz: fix slow running read loop

lib/docs/main.js
It is currently impossible to bring up the help dialog on certain non-English keyboard layouts. On my Swedish keyboard, neither pressing the key with the `?` glyph nor the key physically located where the `/?` key is on a US/UK keyboard works, with or without holding down `Shift`.
`which` is deprecated and web standards recommend using `key` for matching on locale-specific character produced and `code` for matching on the locale-independent physical key being pressed (see <https://www.w3.org/TR/uievents-key/> and <https://w3c.github.io/uievents-code/> if you care about the details).
=> autodoc: Use `code` for keyboard events

lib/std/os/windows.zig
It's been seen on Windows 11 (22H2) Build 22621.3155 that NtCreateFile will return the OBJECT_NAME_INVALID error code with certain path names. The path name we saw this with started with `C:Users` (rather than `C:\Users`) and also contained a `$` character.  This PR updates our OpenFile wrapper to propagate this error code as `error.BadPathName` instead of making it `unreachable`.
> NOTE: not all versions of windows will return this error code, some will return `OBJECT_PATH_NOT_FOUND` instead
see https://github.com/marler8997/zigup/issues/114#issuecomment-1994420791
=> std.os.windows: handle OBJECT_NAME_INVALID in OpenFile

lib/std/dwarf.zig
`std.dwarf.EntryHeader.read` requires an `std.dwarf.FixedBufferReader`, which is non-public and therefore cannot be initialized. This makes said struct public. Also fixes a compile error as the field `is_64` no longer exists.
=> std: Make FixedBufferReader public and fix compile-error

src/main.zig
Context: user provides `-` to read from stdin instead of a file.
Before: it would create a file in $ZIG_LOCAL_CACHE_DIR/tmp/ for each invocation and leave it there.
After: it hashes the file contents and renames the file to the hash.
Result: repeated invocations of `zig cc` do not cause so much trash to be created.
=> reduce garbage for repeated `zig cc -` calls

lib/std/zig/AstGen.zig, src/InternPool.zig, src/Module.zig, src/Sema.zig, test/cases/compile_errors/comptime_decl_name_conflict_resolved.zig, test/cases/compile_errors/invalid_duplicate_test_decl_name.zig
We're deep in the weeds now. As of this PR trivial updates are blocked on linker progress (or CBE/LLVM backend progress), but I can still make progress in the meantime.
Before I make more steps towards incremental, I need to have a stern talking-to with `Zcu.Decl` (see [my proposed refactor](https://gist.github.com/mlugg/d0dcb0025dbfd7145b66d0ada6060024)) - but I think we're very close to something usable on the frontend.
=> compiler: more progress on incremental

lib/std/c/dragonfly.zig, lib/std/c/netbsd.zig, lib/std/c/openbsd.zig
- based on system API value IF_NAMESIZE
- unblocks `zig test lib/std/std.zig`
=> bsd: add missing os.IFNAMESIZE

lib/std/coff.zig, lib/std/debug.zig, src/link/Coff/lld.zig
Moves towards reproducible builds on Windows and makes stack traces independent of cwd and zig-cache.
Helps #12729, but doesn't solve paths in the PDB.
=> coff: only store PDB basename

src/link/MachO/synthetic.zig, test/link/macho.zig
=> macho: fix a sad typo in calculating the address of a TLV pointer

lib/std/math.zig
fixes #12315
If I remember correctly, in the actual codegen the runtime check gets optimized away but as far as I'm aware I did forget to use this keyword because I mistakenly thought that `isPowerOfTwo` would be hoisted to `comptime`. 
Even though this does fix #12315, I think it'd be cool if someone were to look at  https://github.com/ziglang/zig/issues/12315#issuecomment-1986830027 because I think the bug that caused the regression itself isn't resolved in the slightest.
=> fix(math): eval isPowerOfTwo at comptime in rotl/rotr

lib/std/math.zig
and make `degreesToRadians` and `radiansToDegrees` use the precomputed comptime float that potentially has marginally better post-rounding precision.
This also enables them to operate on a vector of floats, rather than just being a clunky way of multiplying conversion factors.
```zig
const rad = std.math.degreesToRadians;
const latitudes: @Vector(13, f32) = .{-90, -75, -60, -45, -30, -15, 0, 15, 30, 45, 60, 75, 90};
const xs, const ys = .{
@cos(rad(latitudes)),
@sin(rad(latitudes)),
};
for(xs,ys)|x,y|{
plot(x,y);
}
```
=> make `math.degreesToRadians` and `math.radiansToDegrees` infer type from argument

test/behavior/vector.zig
tested manually with qemu
Cc: https://github.com/ziglang/zig/issues/4951
=> test: reenable some behavior vector tests

lib/std/Build/Step/Run.zig
Before this fix, the stderr FIFO was advanced by the length of the trimmed message, thus the next error log contained the tail of that message.
Bug can be reproduced with a few failing tests run by std.Build, e.g. for this `build.zig`
```zig
const Build = @import("std").Build;
pub fn build(b: *Build) void {
b.step("test", "Run tests").dependOn(&b.addRunArtifact(b.addTest(.{
.root_source_file = .{ .path = "test.zig" },
.target = b.standardTargetOptions(.{}),
.optimize = b.standardOptimizeOption(.{}),
})).step);
}
```
where `test.zig` has 3 failing tests (reproducible with just 2 on 0.11):
```zig
const expect = @import("std").testing.expect;
test { try expect(false); }
test { try expect(false); }
test { try expect(false); }
```
`)\n` at the end of `test_1`'s log is repeated on that of …
=> Fix stuttering stderr in Zig test log

lib/std/os/linux.zig, lib/std/os/linux/IoUring.zig, lib/std/os/linux/io_uring_sqe.zig
Ring mapped buffers are newer implementation of provided buffers, supported since kernel 5.19.
Best described by Jens Axboe in [io_uring and networking in 2023](https://github.com/axboe/liburing/wiki/io_uring-and-networking-in-2023#provided-buffers).  
Newer implementation requires less management, after initial setup, and should be more [efficient](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c7fb19428d67dd0a2a78a4f237af01d39c78dc5a).
This commit implements low level io_uring_buf_ring functions as mostly direct translation from liburing:
* io_uring_setup_buf_ring
* io_uring_free_buf_ring
* io_uring_buf_ring_init
* io_uring_buf_ring_mask
* io_uring_buf_ring_add
* io_uring_buf_ring_advance
Using this functions is little work-some. Application need first to …
=> io_uring: ring mapped buffers

src/link/MachO/Archive.zig
https://developer.apple.com/documentation/kernel/fat_arch/1558631-size
According to apple's documentation, the size in the fat_arch structure is just the size of a single binary file, if it is to be compared with the read pointer, the offset needs to be added.
fixed: https://github.com/ziglang/zig/issues/19154
=> macos: archive size fix

src/mingw.zig
Closes https://github.com/ziglang/zig/issues/19284
As of 9f2cb920c055bc990cc9d593b8dc9eaa450d07b9 configuring the global cache directory to a relative path causes errors of the following form when cross compiling to `windows-gnu`.
```
error: unable to generate DLL import .lib file for kernel32: FileNotFound
```
The issue occurred because the `def_final_path` included the global cache path as a prefix and later on the `def_final_file` was created using that path with the global cache directory handle.
=> Fix "unable to generate DLL import .lib file"

lib/std/Thread.zig, lib/std/child_process.zig, lib/std/debug.zig, lib/std/fs.zig, lib/std/os/windows.zig, lib/std/os/windows/ntdll.zig, lib/std/os/windows/test.zig, lib/std/zig/system/windows.zig
=> Windows: Replace CreatePipe with ntdll implementation

lib/std/fmt/ryu128.zig
closes #19314
All original tests have passed. Given example with new output:
```
info: 0 == 0 == 0
info: 1 == 1 == 1
info: 2 == 2 == 2
info: 3 == 3 == 3
info: 4 == 4 == 4
info: 5 != 5 != 5
info: 6 != 6 != 6
info: 7 != 7 != 7
info: 8 != 8 != 8
info: 9 != 9 != 9
```
=> std.fmt: fix incorrect rounding on 0 precision of a decimal

src/codegen/llvm.zig, test/cases/union_unresolved_layout.zig
Fixes  #18518
I think the bug is actually in the llvm backend and not the frontend as the union type actually isn't used at runtime, only the field type is referenced and thus the union does not get a layout. The fix implemented here just emits an empty namespace as a debug type for unions without layout. I don't think this fix should have any real consequences on the debugability of programs as there won't ever be values with that debug type.
=> LLVM lowerDebugType: Lower union types without a layout into an empty namespace 

lib/compiler/reduce/Walk.zig, lib/docs/wasm/Walk.zig, lib/std/zig/Ast.zig, lib/std/zig/AstGen.zig, lib/std/zig/AstRlAnnotate.zig, lib/std/zig/parser_test.zig, lib/std/zig/render.zig, test/behavior/destructure.zig
A preceding `comptime` keyword was being ignored if the first destructure variable was an expression.
=> Ast: fix comptime destructure

src/codegen/c.zig
This fixes an issue with boostrapping the compiler using MSVC. There is a CircularBuffer with an array of length 65536 initialized to undefined, and because the undefined path of `renderValue` was using `StringLiteral` to render this, the resulting zig2.c would fail to compile using MSVC.
The solution was to move the already-existing array initializer path (used in the non-undefined path) into StringLiteral, and make StringLiteral aware of the total length so it could decide between which style of initialization to use. We prefer to use string literals if we can, as this results in the least amount of emitted C source.
Since this affects the bootstrap, I'll need a contributor to run `zig build update-zig1` on this branch.
=> cbe: rework StringLiteral to decide between string literal or array initializator syntax

src/codegen/llvm/Builder.zig, test/behavior/floatop.zig, test/cases/float_mode_optimized_reduce.zig
Fixes #19331
In addition to fixing #19331, this PR also fixes using fast math on individual instructions in the LLVM backend, all the fast math flags where emitted as disabled before.
=> Fix setFloatMode in LLVM backend

src/arch/wasm/CodeGen.zig, test/behavior/byteswap.zig
Hope this is good!
Tested locally and it seemed okay. Happy to implement a bunch more cases (like 40/48/56-bit byteswap) if there's interest.
Note that I did not use `wrapOperand` as I believe that always using the unsigned shift operators is correct. I believe it coincidentally worked for other cases where the signed and unsigned shift behavior would've been the same.
=> wasm: support 64bit byteSwap, use fewer locals in 32/64bit impls, enable behavior tests

doc/langref.html.in
This was renamed back in https://github.com/ziglang/zig/commit/d5312d53a066092ba9efd687e25b29a87eb6290c.
=> langref: Rename std.fs.wasi.{PreopenList => Preopens}

lib/std/os/linux.zig, lib/std/posix.zig
This was a mistake from day one. This is the wrong abstraction layer to do this in.
My alternate plan for this is to make all I/O operations require an IO interface parameter, similar to how allocations require an Allocator interface parameter today.
I tried to do something more ambitious in this branch but it turned into too deep of a rabbit hole, so I aborted mission and this is what is left.
=> std: don't do BYOS at the POSIX API layer

.github/CODEOWNERS
The resinator files were moved during #19174
=> Fix CODEOWNERS path to resinator source files

lib/std/os/windows/ws2_32.zig
Fix for:
`error: struct 'os.windows.ws2_32.POLL' has no member named 'IN'`
```
var pfd = [1]os.posix.pollfd{posix.pollfd{
.fd = socket,
.events = posix.POLL.IN,
.revents = undefined,
}};
os.posix.poll(&pfd, 0);
```
See:
https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsapoll
=> std.os.windows: add POLL.IN and POLL.OUT

CMakeLists.txt, lib/std/fmt.zig, lib/std/fmt/format_float.zig
Symmetry with parse_float and to hide the implementation from the user. Additionally, we expose the entire namespace and provide some aliases so everything is available to a user.
Closes #19366
=> rename ryu128 -> format_float

src/mingw.zig
see https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-crt/lib-common/ucrt.mri
it's unlikely that ucrtbase would be broken in the future, but this is the "proper" way of doing things that every other toolchain uses
=> mingw: link to api sets instead of ucrtbase

lib/std/Thread.zig
This is a revival of #18258 , that unbreaks compilation of threaded code targeting WASI.
When no allocator is set, it also changes the confusing `OutOfMemory` error to a dedicated error.
=> Unbreak support for WASI threads

lib/std/fmt.zig
These are the fundamental units so they can't have decimal places.
=> std.fmt.fmtIntSize{Bin,Dec}: Don't add .0... to bytes

lib/std/Build/Cache.zig
Closes https://github.com/ziglang/zig/issues/19408
Original plan was to open a different PR but i needed this patch locally to test and realized if i hit submit on any others the builds would be broken without this included so im send this first. cherry picked from jacobly's other branch.
=> Build.Cache: fix UAF during `unhit`

src/codegen/llvm.zig
This issue was causing debug information to sometimes not function correctly for some local variables, with debuggers simply reporting that the variable does not exist. What was happening was that after an AIR body - and thus debug lexical scope - begins, but before any `dbg_stmt` within it, the `scope` on `self.wip.debug_location` refers to the parent scope, but the `scope` field on the `DILocalVariable` metadata passed to `@llvm.dbg.declare` points, correctly, to the nested scope. I haven't looked into precisely what happens here, but in short, it would appear that LLVM Doesn't Like It (tm).
The fix is simple: when we change `self.scope` at the start or end of an AIR body, also modify the scope on `self.wip.debug_location`. This is correct as we always want the debug info for an …
=> llvm: update current debug location scope when entering debug scope

lib/docs/wasm/markdown.zig, lib/docs/wasm/markdown/Document.zig, lib/docs/wasm/markdown/Parser.zig, lib/docs/wasm/markdown/renderer.zig
Closes #19265
There are two commits in this PR: the first one implements the "traditional" Markdown autolink syntax, using `<>` to delimit the link, and the second one extends the parser to also recognize a more restricted form of links directly in plain text without any delimiters.
Both forms of autolinks are currently represented in the standard library documentation. Here are some examples:
- Using `<>` (these are a minority):
- `#std.Uri`
- `#std.fmt.parse_float.convert_slow.convertSlow`
- `#std.fmt.parse_float.convert_eisel_lemire.convertEiselLemire`
- Plain text:
- `#std.ascii` (the subject of the linked issue)
- `#std.unicode.fmtUtf8`
- `#std.mem.page_size`
=> Autodoc: hyperlink URLs in text

lib/std/Target.zig, lib/std/enums.zig, lib/std/fmt.zig, lib/std/meta.zig, lib/std/unicode.zig, lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Air.zig, src/Compilation.zig, src/InternPool.zig, src/Module.zig, src/Sema.zig, src/TypedValue.zig, src/Value.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/Encoding.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/link/Elf/LdScript.zig, src/print_zir.zig, test/behavior/align.zig, test/behavior/comptime_memory.zig, test/behavior/eval.zig, test/behavior/extern.zig, test/cases/compile_errors/comptime_var_referenced_at_runtime.zig, test/cases/compile_errors/comptime_var_referenced_by_decl.zig, test/cases/comptime_aggregate_print.zig
This commit changes how we represent comptime-mutable memory (`comptime var`) in the compiler in order to implement the intended behavior that references to such memory can only exist at comptime.
It does *not* clean up the representation of mutable values, improve the representation of comptime-known pointers, or fix the many bugs in the comptime pointer access code. These will be future enhancements.
Comptime memory lives for the duration of a single Sema, and is not permitted to escape that one analysis, either by becoming runtime-known or by becoming comptime-known to other analyses. These restrictions mean that we can represent comptime allocations not via Decl, but with state local to Sema - specifically, the new `Sema.comptime_allocs` field. All comptime-mutable allocations, as …
=> compiler: implement analysis-local comptime-mutable memory

lib/std/Build/Step/Fmt.zig
This MR ensures the strings used in the Step.Fmt belong to the builder, which prevents a use-after-free footgun in certain cases.
e.g.
```zig
const paths = [_][]const u8{b.build_root.path orelse "."};
const fmt = b.addFmt(.{ .paths = &paths });
b.step("fmt", "Test all files for correct formatting").dependOn(&fmt.step);
}
```
=> std.Build: dupe provided paths for Step.Fmt.create()

lib/libc/include/generic-glibc/features.h
Moving `__GLIBC__` to the top is needed so that commits https://github.com/ziglang/zig/commit/f9c9ae84c6c0773ab8dc710cae3ce9024ca1e91c  and https://github.com/ziglang/zig/commit/0afead56516c13c007b99d4b252db064080e2679 actually work.
=> Improve old glibc versions

lib/std/Build/Module.zig
=> make `addCSourceFiles` assert `options.files` are relative

src/translate_c.zig, test/cases/translate_c/macro_function_string_concat.c
Closes #19355 .
I promoted the code handling string concatenations from parseCPrimaryExpr to parseCPostfixExpr, making its precedence higher than postfix expressions (including functions). This solves the problem.
I've added a corresponding test, and all tests are passed.
=> translate-c: handle string concatenation of function calls

lib/std/c/haiku.zig, lib/std/io.zig, lib/std/zig/LibCInstallation.zig, lib/std/zig/system.zig
Followup fix for the third bullet from #19406
```
~> ./zig build-obj hello.zig
warning: Encountered error: FileNotFound, falling back to default ABI and dynamic linker.
~> cc -o hello hello.o
~> ./hello
Hello, world!
```
Related #17123
Related #18828
=> haiku: fix poll definitions

src/codegen.zig, src/link/Dwarf.zig
Fixes #19391 
~~Also, as an added bonus, we now write out relocation placeholders as a series of Zig undefined bytes `0xaa` which should help us in tracking down missed relocations down the line. Example:~~
=> link: fix undefined memory being written out in dwarf and codegen

lib/compiler/std-docs.zig, src/Compilation.zig
Closes #19403
There are two commits in this PR: the first one updates the logic of `-femit-docs` to include all modules in the compilation in the output `sources.tar` (and while I was at it, fixes #19403), and the second one applies the same effect to `zig std` by including the builtin module in its custom generated `sources.tar`.
There is also this comment on #17334 which is related to this change: https://github.com/ziglang/zig/issues/17334#issuecomment-2010992633 This PR fixes the first limitation mentioned, and the solution to the second limitation is that the root module of the compilation is the first one to appear in `sources.tar`, which I think is the most intuitive behavior. I don't know whether this change fully resolves (GitHub don't auto-close the issue please) #17334 or …
=> Autodoc: include all modules in output

src/Sema.zig, test/behavior/error.zig, test/cases/compile_errors/@errorCast_with_bad_type.zig
Closes #18177 .
Made minor changes to `@errorCast`'s type checks to allow casting error sets to error unions. Corresponding tests were added.
=> allow @errorcast to cast error sets to error unions

src/Sema.zig, test/behavior/array.zig
Salvaging the useful parts of #19347
=> Allow `.ptr` on pointer to array with ref result location

lib/std/os/linux/IoUring.zig
Fixes #19451 which describes io_uring regression introduced in #18757.
First commit adds failing test from the issue which fails with `panic: @memcpy arguments have non-equal lengths`.
```
1/1 IoUring.test.failing test for issue 19451... thread 248254 panic: @memcpy arguments have non-equal lengths
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.3496+a2df84d0f/lib/std/os/linux/IoUring.zig:289:45: 0x103d50a in copy_cqes_ready (test)
@memcpy(cqes[0..count], self.cq.cqes[head..tail]);
^
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.3496+a2df84d0f/lib/std/os/linux/IoUring.zig:276:36: 0x103d1c4 in copy_cqes (test)
return self.copy_cqes_ready(cqes);
^
/usr/local/zig/zig-linux-x86_64-0.12.0-dev.3496+a2df84d0f/lib/compiler/IoUring.zig:4251:40: 0x103df00 in test.failing test for issue 19451 (test) …
```
=> io_uring: fix regression

src/codegen/spirv.zig, src/link/SpirV.zig, src/link/SpirV/BinaryModule.zig, src/link/SpirV/deduplicate.zig, test/behavior/destructure.zig, test/behavior/math.zig
This linker pass deduplicates types and constants which are the same. It works by hashing and comparing the type/constant/annotation trees (of which a node is called an "entity"), and checking if all the members are the same.
To hash a type or compare two types, their trees are recursively walked and each node is hashed or compared. This is not done with anything smart for now, because we need to mind to handle recursive types in a way that yields the same hash for different types that have the same recursive structure. Recursive types are handled by storing all pointers in an ArrayHashMap, and if the pointer is already there (and so this is a recursive type), the _index_ is hashed or compared instead of recursively processing it. For two equal types, these recursive pointers will have …
=> spirv: deduplication pass

lib/std/array_list.zig
This fixes a few issues with the `ArrayList` / `ArrayListUnmanaged` tests for `replaceRange` and `replaceRangeAssumeCapacity`:
- Breaks the tests up so that each test scope is only testing one test case at a time.
- Deliberately does not share constants across tests, as that makes the tests harder to read. 
- By defining values within the test case, the reader can read the test in a straight line from beginning to end without having to jump around the file to understand what values have been assigned to various variables.
- Fixes a memory leak that existed in the previous test implementation (and switches to `testing.allocator` to catch memory leaks)
- Fixes ordering of test assertions so that the `expected` and `actual` parameters are passed in the correct order
- The previous …
=> std.ArrayList: Refactor replaceRange tests

lib/std/tar.zig, src/Package/Fetch.zig
Instead of striping leading root folder while unpacking tar, tar archive is unpacked as is into temporary directory. Then we check result and decide whether to skip root folder. That allows us to handle archives which don't have that leading root folder. 
This if follow up of PR #19090.
Fixes #17779
=> package manager: handle archives without leading root folder

lib/compiler/libc.zig, lib/std/Target/Query.zig, lib/std/zig/LibCInstallation.zig, lib/std/zig/system/darwin.zig, src/link/MachO.zig, src/link/MachO/Dylib.zig
- Map target os=`ios` and abi=`macabi` to macho.PLATFORM.MACCATALYST.
This allows for matches against tbdv4 targets, eg. `x86_64-maccatalyst`.
- When parsing old tbdv3 files with `zippered` platform, we append
[`ARCH-macos`, `ARCH-maccatalyst`] to list of "tbd" targets. This
enables linking for standard targets like `ARCH-macos-none` and
MacCatalyst targets `ARCH-ios-macabi`.
closes #19110
=> macos: add zippered support

lib/compiler/std-docs.zig
Having a fixed port number means you can just F5 in your existing tab when you relaunch the executable. That's far better for iterative development of the server.
```
Usage: zig std [options]
Options:
-h, --help                Print this help and exit
-p [port], --port [port]  Port to listen on. Default is 0, meaning an ephemeral port chosen by the system.
--[no-]open-browser       Force enabling or disabling opening a browser tab to the served website.
By default, enabled unless a port is specified.
```
=> zig std accepts --port and --no-open-browser

src/Package/Fetch.zig
Based on file content. Detects elf magic header or shebang line.
Executable bit is ignored in hash calculation, as it was before this. So packages hashes are not changed.
Reference: https://github.com/ziglang/zig/issues/17463#issuecomment-1984798880
Fixes: #17463
Test is [here](https://github.com/ianic/zig-fetch-test/blob/7c4600d7bb263f9b72fe3d0b70071f42be89e25c/src/main.zig#L307).
=> package manager: set executable bit

src/Package/Fetch.zig
Closes #19557
Closes #19561
Previously, `build.zig` was not being detected correctly by `computeHash` for packages where there is a containing root directory.
Tested on:
- https://github.com/kubkon/zld (#19561)
- https://codeberg.org/kiesel-js/kiesel/ (#19557)
=> Fix first-time package fetches

src/Sema.zig, test/behavior/array.zig
Fixes #18924
Makes `&.{ a, b, c }` coerce to `[*]const T`/`[*:x]const T`:
```zig
const expectEqual = std.testing.expectEqual;
const Foo = struct { bar: [*]const i32 };
test "ref to anon array init coerced to many-ptr" {
const foo: Foo = .{ .bar = &.{ 1, -2 } };
try expectEqual(1, foo.bar[0]);
try expectEqual(-2, foo.bar[1]);
}
fn checkSentinelManyPtr(values: [*:0]const i32) !void {
try expectEqual(3, values[0]);
try expectEqual(-4, values[1]);
try expectEqual(0, values[2]);
}
test "ref to anon array init coerced to sentinel many-ptr" {
try checkSentinelManyPtr(&.{ 3, -4 });
}
```
=> Sema: support coercing ref to anonymous array init to many-pointer

lib/compiler/build_runner.zig, lib/std/Build.zig, lib/std/math/nextafter.zig, src/Sema.zig, test/behavior/fn.zig
Closes #18987
Follow-up to #18778 (which added lazy dependencies) and the discussion in #18808 that followed
This adds `b.lazyImport`, which (in the context of a build script) is to `@import` what `b.lazyDependency` is to `b.dependency` and can be used to import a lazy dependency's build.zig struct.
It enables the use case where a package wants to lazily depend on an `@import`-style dependency and not fetch it until it is first needed, for example when building for a specific target.
```zig
// build.zig of lazy dependency 'foo'
pub fn build(_: *std.Build) void {}
pub const bytes = "Hello!";
```
```zig
// build.zig of consumer
const wf = b.addWriteFiles();
// the non-lazy way, which won't work for …
```
=> std.Build: add `lazyImport` (`@import` for lazy dependencies)

lib/std/Build.zig
Given a struct that corresponds to the build.zig of a dependency, `b.dependencyFromBuildZig` returns that same dependency. In other words, if you have already a `@import`ed a depdency's build.zig, you can use this function to obtain the corresponding `Dependency`:
```zig
// in consumer build.zig
const foo_dep = b.dependencyFromBuildZig(@import("foo"), .{});
```
---
This function is also important for packages that expose functions from their build.zig files that need to use their corresponding `Dependency` (for example, for package-relative paths, or for running system commands and returning the output as lazy paths). This would be accomplished through:
```zig
// in dependency build.zig
pub fn getImportantFile(b: *std.Build) std.Build.LazyPath {
const this_dep = …
```
=> std.Build: add `dependencyFromBuildZig`

lib/compiler/aro_translate_c/ast.zig, lib/compiler/test_runner.zig, lib/std/Build/Step/Options.zig, lib/std/zig.zig, lib/std/zig/render.zig, src/Builtin.zig, src/InternPool.zig, src/main.zig, src/print_zir.zig, tools/gen_spirv_spec.zig, tools/generate_linux_syscalls.zig, tools/update_cpu_features.zig, tools/update_spirv_features.zig
This updates `std.zig.fmtId` to support conditionally `@""` escaping primitives and the reserved `_` identifier via format specifiers:
- `{}`: escape invalid identifiers, identifiers that shadow primitives and the reserved `_` identifier.
- `{p}`: same as `{}`, but don't escape identifiers that shadow primitives.
- `{_}`: same as `{}`, but don't escape the reserved `_` identifier.
- `{p_}` or `{_p}`: only escape invalid identifiers.
In other words, the default empty `{}` specifier is as conservative as possible and you add `p` and/or `_` to add primitives/`_` to the set of identifiers that can be rendered unescaped.
Any other format specifier is a compile error.
Correctly formatted and escaped code generation. Status quo `fmtId` is problematic because it doesn't escape primitives, which …
=> `std.zig.fmtId`: conditionally escape primitives/`_` (breaking)

lib/docs/wasm/markdown.zig, lib/docs/wasm/markdown/Parser.zig
Previously, indentation was not being handled correctly in some cases, causing examples such as `std.json.WriteStream` to be rendered with improper list nesting.
Additionally, some more test cases have been added to ensure indentation (or lack of indentation) is handled correctly in some other constructs.
---
Thanks to @thejoshwolfe for pointing this out. Here are a couple screenshots showing how the motivating example looks before and after:
=> Autodoc: fix Markdown indented lists

lib/std/Build/Module.zig
Commit 0b7123f41d66bdda4da29d59623299d47b29aefb regressed the `include_path` option of ConfigHeader which is intended to set the path, including subdirectories, that C code would pass to an include directive.
For example if it passes
.include_path = "config/config.h",
Then the C code should be able to have
#include "config/config.h"
This regressed https://github.com/andrewrk/nasm/ because the build-exe command ends up being:
`-I /home/andy/dev/nasm/zig-cache/o/3e761af6a001bf60071c3f2b8c1a92c1/config`
However the desired path does not include the directory at the end:
```
andy@bark ~> find /home/andy/dev/nasm/zig-cache/o/3e761af6a001bf60071c3f2b8c1a92c1/ -type f
/home/andy/dev/nasm/zig-cache/o/3e761af6a001bf60071c3f2b8c1a92c1/config/config.h
```
``` …
```
=> std.Build: fix regression in Step.ConfigHeader

lib/std/crypto/Certificate.zig
Was causing `error.TlsInitializationFailed` on some connections, such as the musicbrainz.org API.
Related:
* #17213
=> std.crypto.Certificate: support 3072 bits RSA certificate

lib/std/Uri.zig, lib/std/http/Client.zig, lib/std/http/test.zig, lib/std/io.zig, src/Package/Fetch.zig, src/Package/Fetch/git.zig, src/link/SpirV.zig
This allows `std.Uri.resolve_inplace` to properly preserve the fact that `new` is already escaped but `base` may not be.  I originally tried just moving `raw_uri` around, but it made uri resolution unmanagably complicated, so I instead added per-component information to `Uri` which allows extra allocations to be avoided when constructing uris with components from different sources, and in some cases, deferring the work all the way to when the uri is printed, where an allocator may not even be needed.
Closes #19587
=> Uri: propagate per-component encoding

lib/std/Build.zig, lib/std/Build/Step/Compile.zig, lib/std/Build/Step/ConfigHeader.zig, test/standalone/test_runner_module_imports/build.zig, test/standalone/test_runner_path/build.zig
This adds the `*std.Build` owner to LazyPath so that lazy paths returned from a dependency can be used in the application without friction or footguns.
This is technically a breaking change due to `test_runner` taking a LazyPath rather than a string but it does not do the massive breaking change yet. The breakage can happen during the 0.13.0 release cycle.
closes #19313
```zig
.root_source_file = .{ .path = "src/main.zig" },
```
:arrow_down: 
```zig
.root_source_file = b.path("src/main.zig"),
```
```zig
.root_source_file = LazyPath.relative("src/main.zig"),
```
:arrow_down: 
```zig
.root_source_file = b.path("src/main.zig"),
```
```zig
.test_runner = "path/to/test_runner.zig",
```
:arrow_down: 
```zig
.test_runner = b.path("path/to/test_runner.zig"),
```
=> introduce std.Build.path; deprecate LazyPath.relative

lib/docs/wasm/markdown/Parser.zig
Function description was tokenized incorrectly and it resulted in replacement character in [std.math.big.int.Managed.sqrt](https://ziglang.org/documentation/master/std/#std.math.big.int.Managed.sqrt) description.
=> autodoc: fix tokenizer

lib/std/debug.zig
Don't know why UEFI wasn't excluded but freestanding is, probably an oversight since I want to have detailed debug info on my panic function on my Headstart bootloader.
=> Fix stack iterator on UEFI

doc/langref.html.in
As proposed in GH-10113 and implemented in GH-12379.
=> Document packed struct's backing int declaration

src/Package/Fetch.zig
Follow up of: #19500
[discussion](https://github.com/ziglang/zig/pull/19500#discussion_r1558238138)
=> fetch: combine unpack error validation in a single function

lib/std/debug.zig
Why was this passing null? These values are available and useful.
```
thread 464075 panic: sub_path is expected to be relative to the build root, but was this absolute path: '/home/andy/dev/zig/zig-cache/tmp/4284db75167f415d/fmt6.zig'
/home/andy/dev/zig/lib/std/debug.zig:434:22: 0x1231726 in panicExtra__anon_17736 (build)
std.builtin.panic(msg, trace, ret_addr);
^
/home/andy/dev/zig/lib/std/debug.zig:409:15: 0x11e6d79 in panic__anon_16238 (build)
panicExtra(null, null, format, args);
^
/home/andy/dev/zig/lib/std/Build.zig:1641:24: 0x118b74d in path (build)
std.debug.panic("sub_path is expected to be relative to the build root, but was this absolute path: '{s}'", .{
^
/home/andy/dev/zig/test/tests.zig:882:45: 0x119c0bc in addCliTests (build)
const check6 = b.addCheckFile(b.path(fmt6_path), …
```
=> std.debug.panic: pass the args

src/translate_c.zig, test/cases/translate_c/strlit_as_bool.c
this is a follow up to #19610 with fix suggested by @Vexu in https://github.com/ziglang/zig/issues/14642#issuecomment-2048999384
=> translate-c: allow str literals in bool expressions

lib/std/posix/test.zig, src/codegen/c.zig, src/codegen/c/Type.zig, test/behavior/abs.zig, test/behavior/call.zig, test/behavior/call_tail.zig, test/behavior/cast.zig, test/behavior/export_builtin.zig, test/behavior/extern.zig, test/behavior/fn.zig, test/behavior/globals.zig, test/behavior/optional.zig, test/behavior/packed-struct.zig, test/behavior/undefined.zig, test/behavior/union.zig, test/behavior/vector.zig, test/tests.zig
Also reduce ctype pool string memory usage, remove self assignments, and enable more warnings.
=> cbe: fix optional codegen

lib/std/Uri.zig, lib/std/http/Client.zig
This branch contains two competing implementations that both result in avoiding ":443" in the HTTP host header for zig's package fetching.
The first commit implements it by making `std.http.Client` pass the port to the server based on user input. This makes the host http header have the port if and only if the URI provided by the API user included it.
The second commit implements it a different way by making the host http header have the port if and only if it differs
from the defaults based on the protocol.
I think I like the first commit more actually, because it's simpler yet more flexible. What do you think, @jacobly0?
Closes #19624
=> std.http.Client: omit port in http host header sometimes

lib/std/crypto/benchmark.zig, lib/std/crypto/pcurves/p256/p256_64.zig, lib/std/crypto/pcurves/p256/p256_scalar_64.zig, lib/std/crypto/pcurves/p384/p384_64.zig, lib/std/crypto/pcurves/p384/p384_scalar_64.zig, lib/std/crypto/pcurves/secp256k1/secp256k1_64.zig, lib/std/crypto/pcurves/secp256k1/secp256k1_scalar_64.zig
signature/s:
```
Algorithm        Before     After
---------------+---------+-------
ecdsa-p256        3707       4396
ecdsa-p384        1067       1332
ecdsa-secp256k1   4490       5147
```
Add ECDSA to the benchmark by the way.
=> std.crypto.pcurves.*: simpler, smaller, faster u64 addition with carry

lib/std/fs/Dir.zig
Also fix the namespace having a redundant component.
Technically breaking but unlikely in practice.
=> std.fs.Dir.Walker: maintain a null byte in path names

lib/std/Build/Step/ConfigHeader.zig
Following in the steps of https://github.com/ziglang/zig/pull/19642
=> std.Build.Step.ConfigHeader: better error message

lib/std/Build/Step/CheckObject.zig
Allows us to emulate `readelf -p .rodata.str1.1`.
Here's how I use it in `zld` tests already:
```zig
const check = obj.checkObject();
check.dumpSection(".rodata.str1.1");
check.checkExact("Hello \x00World \x00");
test_step.dependOn(&check.step);
```
=> lib/std/Build/Step/CheckObject: dump section as string

lib/std/once.zig
* fix UB when Thread.spawn fails, and we try to join uninitialized threads (through new `thread_count` variable).
* make sure that the tests pins down synchronization guarantees: in the main thread, we can observe `1` simply due to synchronization from `Thread.join()`. To make sure that once uses Acq/Rel, and not just relaxed, we should also additionally check that each thread observes 1, regardless of whether it was the one to call once.
=> std: improve std.once tests

lib/std/process.zig, test/standalone/build.zig.zon, test/standalone/windows_argv/README.md, test/standalone/windows_argv/build.zig, test/standalone/windows_argv/fuzz.zig, test/standalone/windows_argv/lib.h, test/standalone/windows_argv/lib.zig, test/standalone/windows_argv/verify.c
On Windows, the command line arguments of a program are a single WTF-16 encoded string and it's up to the program to split it into an array of strings. In C/C++, the entry point of the C runtime takes care of splitting the command line and passing argc/argv to the main function.
https://github.com/ziglang/zig/pull/18309 (cc @castholm) updated ArgIteratorWindows to match the behavior of CommandLineToArgvW, but it turns out that CommandLineToArgvW's behavior does not match the behavior of the C runtime post-2008. In 2008, the C runtime argv splitting [changed how it handles consecutive double quotes](https://daviddeley.com/autohotkey/parameters/parameters.htm#WINCRULESDOC) within a quoted argument (it's now considered an escaped quote, e.g. `"foo""bar"` post-2008 would get parsed into …
=> ArgIteratorWindows: Match post-2008 C runtime rather than `CommandLineToArgvW`

lib/std/Target.zig, lib/std/Target/Query.zig, lib/std/zig/system.zig, src/Builtin.zig
Proposed implementation of #19581
=> Target: add wasi os version

src/arch/x86_64/CodeGen.zig
Crash occured while spilling this value:
https://github.com/ziglang/zig/blob/a2b834e8c7152f70d71c71107db40b9182909647/lib/std/crypto/tls/Client.zig#L860
=> x86_64: fix miscompilation regression in package fetching code

lib/std/zig/system/linux.zig
When building zig natively from source on an RK3588 SoC board, the generated stage3 compiler will use unsupported 'sha256h.4s' instructions due to mis-identified CPU features. This happens when trying to compile a new project generated with "zig init"
```
$ ~/devel/zig/build/stage3/bin/zig build
thread 919 panic: Illegal instruction at address 0x1fdc0c4 /home/dliviu/devel/zig/lib/std/crypto/sha2.zig:223:29: 0x1fdc0c4 in round (zig)
asm volatile (
^
/home/dliviu/devel/zig/lib/std/crypto/sha2.zig:168:20: 0x1fdca87 in final (zig)
d.round(&d.buf);
^
/home/dliviu/devel/zig/lib/std/crypto/sha2.zig:180:20: 0x1c8bb33 in finalResult (zig)
d.final(&result);
^
/mnt/home/dliviu/devel/zig/src/Package/Fetch.zig:754:49: 0x1a3a8eb in relativePathDigest (zig)
return …
```
=> std.zig.system.linux: Use arm.zig detection for AArch64 CPU features

src/Sema.zig, src/Value.zig, src/print_value.zig
Certain types (notably, `std.ComptimeStringMap`) were resulting in excessively long type names when instantiated, which in turn resulted in excessively long symbol names. These are problematic for two reasons:
* Symbol names are sometimes read by humans -- they ought to be readable.
* Some other applications (looking at you, xcode) trip on very long symbol names.
To work around this for now, we cap the depth of value printing at 1, as opposed to the normal 3. This doesn't guarantee anything -- there could still be, for instance, an incredibly long aggregate -- but it works around the issue in practice for the time being.
=> Sema: cap depth of value printing in type names

lib/compiler/build_runner.zig, lib/std/Build.zig, lib/std/Build/Step/Compile.zig, lib/std/Build/Step/Options.zig, lib/std/Target/Query.zig, src/main.zig
This is a partial revert of 105db13536b4dc2affe130cb8d2eee6c97c89bcd.
As we learned from Chimera Linux packaging, these options are not actually helpful since the distribution package manager may very well want to cross-compile the packages that it is building.
So, let's not overcomplicate things. There are already the options `-Dtarget`, `-Dcpu`, and `-Ddynamic-linker` created by [standardTargetOptions](https://ziglang.org/documentation/master/std/#std.Build.standardTargetOptions).
These options are generally provided when the project generates machine code artifacts, however, there may be a project that does no such thing, in which case it makes sense for these options to be missing. The Zig Build System is a general-purpose build system, after all.
cc @ifreund
=> std.Build: revert --host-target, --host-cpu, --host-dynamic-linker

CMakeLists.txt
This allows building Zig with the correct dynamic linker in environments where the auto detection mechanism fails, like in Nix dev shells.
This PR is a fixed version of #19631.
=> cmake: Support setting the dynamic linker

lib/std/Build.zig, test/standalone/build.zig.zon, test/standalone/dependencyFromBuildZig/build.zig, test/standalone/dependencyFromBuildZig/build.zig.zon, test/standalone/dependencyFromBuildZig/other/add.zig, test/standalone/dependencyFromBuildZig/other/build.zig, test/standalone/dependencyFromBuildZig/other/build.zig.zon
Closes https://github.com/ziglang/zig/issues/19683
=> std: fix and add test for Build.dependencyFromBuildZig

lib/std/c/wasi.zig, lib/std/fs/Dir.zig, lib/std/posix.zig
Also removes the LOCK namespace from std.c.wasi because wasi libc does not have flock.
closes #19336
related to #19352
```
[nix-shell:~/dev/zig/build-release]$ stage4/bin/zig build-exe test.zig -lc -target wasm32-wasi 
[nix-shell:~/dev/zig/build-release]$ wasmtime --dir /tmp --dir . ./test.wasm 
error: FileNotFound
Unable to dump stack trace: not implemented for Wasm
```
=> std.fs.Dir.openFile: use wasi libc API when -lc

lib/std/macho.zig
The Mach-O header flags gained two new members at some point, and these are missing in the Zig std library. This PR adds these.
The macOS libc header is already up-to-date: https://github.com/ziglang/zig/blob/130fb5cb0fb9039e79450c9db58d6590c5bee3b3/lib/libc/include/any-macos-any/mach-o/loader.h#L232-L241
=> Add missing Mach-O header flags to std

lib/std/crypto/sha2.zig
Reference: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf § 5.3.6.1
cc @jedisct1
=> define std.crypto.sha2.Sha512224

lib/std/Thread/Pool.zig
`@alignCast` was required for args with greater alignment than that of a pointer.
=> std: fix Thread.Pool.spawn

lib/std/fs/Dir.zig
Same as #19680 but for directories.
=> std.fs.Dir.openDir: use wasi libc API when -lc

lib/std/crypto/ecdsa.zig
The `length_min`/`length_max` convention is used everywhere else in `std.crypto.*`, so try to be consistent.
=> Rename der_encoded_max_length to der_encoded_length_max

README.md
The README, in the section "Building from Source without LLVM", lists some missing features of `zig2` built without LLVM.
A few links in this list refer to closed issues, and 0.12.0 release notes confirm that at least a couple of these are in fact now available features.
=> update list of missing features in no-LLVM built zig2

lib/std/os/linux.zig, lib/std/os/linux/bpf.zig, lib/std/posix.zig
`unexpectedErrno` comes from `posix`, not `os`.
=> Fix reboot unexpected error

src/link/Elf.zig, src/link/Elf/Atom.zig
Linux isn't the only OS that `mmap`s segments.
=> Elf: fix unaligned segments on non-linux

lib/std/Thread.zig
Properly call the entrypoint when it doesn't return an optional error, and use the per-thread copy of the arguments list.
=> Fix WASI threads, again

lib/std/meta.zig
Ran into this `unreachable` while developing and the reason wasn't immediately obvious.
This compile error should make it obvious.
=> std.meta: give TagPayloadByName unreachable a better @compileError message

lib/std/Build/Step/Compile.zig, lib/std/Build/Step/InstallArtifact.zig
Windows does not support RPATH and only searches for DLLs in a small number of predetermined paths by default, with one of them being the directory from which the application loaded.
Currently, if you build an executable and a DLL, link them and install them with the default settings, the exe will go in `bin/` and the DLL in `lib/`, which makes the exe unable to find the DLL at runtime without manually adding `lib/` to the `PATH` environment variable.
Installing both executables and DLLs to `bin/` by default helps ensure that the executable can find any DLL artifacts it has linked to. DLL import libraries are still installed to `lib/`.
[These defaults match CMake's behavior](https://cmake.org/cmake/help/latest/command/install.html#artifact-kind) (emphasis mine):
> ARCHIVE
> Target …
=> std.Build: Install Windows DLLs to `<prefix>/bin/` by default

lib/std/zig/system.zig
* Adjust buffer length a bit.
* Fix detecting if file is a script. Logic below was unreachable, because 99% of scripts failed "At least 255 bytes long" check and were detected as ELF files. It should be "At least 4" instead (minimum value of "ELF magic length" and "smallest possible interpreter path length").
* Fix parsing interpreter path, when text after shebang:
1. does not have newline,
2. has leading spaces and tabs,
3. separates interpreter and arguments by tab or NUL.
* Remove empty error set from `defaultAbiAndDynamicLinker`.
Fixes https://github.com/ziglang/zig/issues/19712
=> std.zig.system: fix ELF file search

lib/std/fmt.zig
Changed uses of `std.testing.expect` to `std.testing.expectEqual`, `std.testing.expectError`, and `std.testing.expectEqualStrings` where appropriate
=> std.fmt: Update tests

lib/std/Thread/RwLock.zig
I just spend a few hours tracing a deadlock in my code, until I discovered that my mental model of the RwLock was wrong.
So I decided to clarify the behavior in the doc-comment.
=> Clarify the blocking behavior of `RwLock.lockShared()`.

lib/std/os/windows.zig
A volume can be mounted as a NTFS path, e.g. as C:\Mnt\Foo. In that case, IOCTL_MOUNTMGR_QUERY_POINTS gives us a mount point with a symlink value something like `\??\Volume{383da0b0-717f-41b6-8c36-00500992b58d}`. In order to get the `C:\Mnt\Foo` path, we can query the mountmgr again using IOCTL_MOUNTMGR_QUERY_DOS_VOLUME_PATH.
Fixes #19731
---
Zig installed to a VHD mounted as a path:
Before:
```
> zig test test.zig
error: unable to find zig self exe path: FileNotFound
```
After:
```
> zig test test.zig
All 1 tests passed.
```
---
Note: It's also possible for a volume to be mounted to multiple paths. This PR will currently always just return the first one--unsure how something like `GetVolumePathNameW` compares, need to test that.
=> windows.GetFinalPathNameByHandle: Support volumes mounted as paths

lib/std/child_process.zig, lib/std/os/windows/kernel32.zig, lib/std/unicode.zig, test/standalone/build.zig.zon, test/standalone/windows_bat_args/build.zig, test/standalone/windows_bat_args/echo-args.zig, test/standalone/windows_bat_args/fuzz.zig, test/standalone/windows_bat_args/test.zig
> Note: This first part is mostly a rephrasing of https://flatt.tech/research/posts/batbadbut-you-cant-securely-execute-commands-on-windows/
> See that article for more details
On Windows, it is possible to execute `.bat`/`.cmd` scripts via CreateProcessW. When this happens, `CreateProcessW` will (under-the-hood) spawn a `cmd.exe` process with the path to the script and the args like so:
cmd.exe /c script.bat arg1 arg2
This is a problem because:
- `cmd.exe` has its own, separate, parsing/escaping rules for arguments
- Environment variables in arguments will be expanded before the `cmd.exe` parsing rules are applied
Together, this means that (1) maliciously constructed arguments can lead to arbitrary command execution via the APIs in `std.process.Child` and (2) escaping according to the …
=> std.process.Child: Mitigate arbitrary command execution vulnerability on Windows (BatBadBut)

src/link/Elf/Archive.zig, src/link/Elf/Object.zig, src/link/MachO/Archive.zig, src/link/MachO/Object.zig
If the object file is in an archive, then its size should be obtained from the archive header, rather than reading the entire archive size.
fixed: https://github.com/ziglang/zig/issues/19718
=> fix: object size error in archive

lib/compiler/objcopy.zig, lib/std/crypto/tls/Client.zig, lib/std/fs/File.zig, lib/std/fs/test.zig, lib/std/http/Client.zig, lib/std/http/Server.zig, lib/std/net.zig, lib/std/os/linux.zig, lib/std/os/linux/IoUring.zig, lib/std/os/linux/io_uring_sqe.zig, lib/std/posix.zig, lib/std/posix/test.zig, lib/std/zig/Server.zig, src/Compilation.zig, src/Module.zig, src/link/C.zig, src/link/Dwarf.zig, src/link/Elf/ZigObject.zig, src/link/Elf/synthetic_sections.zig, src/link/Plan9.zig, src/link/Wasm.zig
~~Also uses the opportunity to apply this change to windows' WSABUF.~~
This removes the posix-y field names in favor of more concise names.
=> std.posix.iovec: use .base and .len instead of .iov_base and .iov_len

src/link/Elf.zig
The ELF specification (generic ABI) states that ``loadable process segments must have congruent
values for p_vaddr and p_offset, modulo the page size''. Linux refuses to load binaries that
don't meet this requirement (execve() fails with EINVAL).
Ensures that output binaries always satisfy this condition by forcing page-alignment even for
freestanding targets.
(Related : #19750)
=> Fix ELF alignment for freestanding targets

lib/std/crypto/sha2.zig
Some cleanup I made during changes in #19308 before #19697. This is no longer necessary for that branch, but it does allow arbitrary SHA512 digests and improves readability.
Changes the following types:
- `Sha512224` -> `Sha512_224 = Sha512Truncated(224)`
- `Sha512256` -> `Sha512_256 = Sha512Truncated(256)`
- `Sha512T256` -> deleted (not in spec, not sure original intent)
=> std.crypto.hash.sha2: cleanup add add more docs

src/Sema.zig, src/codegen/llvm.zig
Closes #11661
Closes #4998
This PR adds the missing `byval` parameter attribute in the LLVM IR, and adds some safety checks to the function signature using [clang's documentation](https://clang.llvm.org/docs/AttributeReference.html#interrupt-x86) as a reference. I've also tested these changes on a hobby OS project.
This is my first time working with the LLVM codegen, and I'm not quite sure that I've done things correctly (especially error handling). Pointers from anyone more familiar with the codebase is appreciated!
=> Fix `Interrupt` callconv LLVM code generation

test/link/glibc_compat/glibc_runtime_check.zig
This is causing the 0.12 release to fail to pass tests on archlinux where glibc is 2.39.
```
-- Install configuration: "None"
test
+- test-link
+- link_test_cases
+- link_test_cases.glibc_compat
+- run native-linux-gnu.2.38 failure
thread 98682 panic: reached unreachable code
/build/zig/src/zig-0.12.0/testinstall/usr/lib/zig/std/debug.zig:403:14: 0x103125c in assert (native-linux-gnu.2.38)
^
/build/zig/src/zig-0.12.0/test/link/glibc_compat/glibc_runtime_check.zig:94:11: 0x10313d0 in checkStrlcpy_v2_38 (native-linux-gnu.2.38)
assert(used == 15);
^
/build/zig/src/zig-0.12.0/test/link/glibc_compat/glibc_runtime_check.zig:87:31: 0x1031408 in checkStrlcpy (native-linux-gnu.2.38)
try checkStrlcpy_v2_38();
^ …
```
=> test/link/glibc_compat: fix incorrect strlcpy result

lib/std/debug.zig, lib/std/hash/benchmark.zig, lib/std/hash/crc.zig, lib/std/hash/crc/impl.zig, lib/std/hash/crc/test.zig, tools/crc/catalog.txt, tools/update_crc_catalog.zig
This removes the two original implementations in favour of the single generic one based on the Algorithm type. Previously we had three, very similar implementations which was somewhat confusing when knowing what one should actually be used.
The previous polynomials all have equivalent variants available when using the Algorithm type.
---
The Koopman polynomial did not have an exact equivalent so one has been added to the catalog.txt file. This does mean we have patched this file but this will be clear if updated in future and tests will catch this.
This is a breaking change for direct users of the old polynomial api. Specifically when using a custom or non-standard polynomial (the `Crc32` alias will continue to work). There are clear compile errors indicating what is required in order to …
=> std.hash.crc: simplify api

src/link/Elf.zig
1. find local/pkg headers & libs
2. avoid ldd error on executables too:
$ ldd -v main_4segs
.../main_4segs: wrong number of segments (4 != 2)
.../main_4segs: invalid ELF class 2; expected 1
related issue https://github.com/ziglang/zig/issues/9109 and PR https://github.com/ziglang/zig/pull/9131
=> NetBSD 10.0 fixes

src/Sema.zig
Attempt to fix #19455
Example to reproduce:
```
fn splat(comptime n: comptime_int, value: anytype) @Vector(n, @TypeOf(value)) {
return @splat(value);
}
test {
_ = splat(0, @as(u8, 0));
}
```
=> Sema: Don't generate runtime instructions on zirSplat if dest_ty doesn't have runtime bits

src/codegen/llvm.zig, test/behavior/union.zig
=> LLVM: Fix panic when using tagged union backed by enum with negative values

lib/std/Build/Module.zig, lib/std/Build/Step/Compile.zig, test/standalone/windows_resources/build.zig, test/standalone/windows_resources/res/zig.rc
Adds an `include_paths` field to RcSourceFile that takes a slice of LazyPaths. The paths are resolved and subsequently appended to the -rcflags as `/I <resolved path>`.
This fixes an accidental regression from https://github.com/ziglang/zig/pull/19174. Before that PR, all Win32 resource compilation would inherit the CC flags (via `addCCArgs`), which included things like include directories. After that PR, though, that is no longer the case.
However, this commit intentionally does not restore the previous behavior (inheriting the C include paths). Instead, each .rc file will need to have its include paths specified directly and the include paths only apply to one particular resource script. This allows more fine-grained control and has less potentially surprising behavior (at the cost of …
=> Build system: Allow specifying Win32 resource include paths using LazyPath

lib/std/static_string_map.zig
closes #19803 by changing quota from (30 * N) to (10 * N * log2(N)) where
N = kvs_list.len
* adds reported adversarial test case
* update doc comment of getLongestPrefix()
EDITED
=> std.StaticStringMap: bump eval branch quota

lib/std/Build/Step/Compile.zig, lib/std/crypto/sha3.zig, lib/std/fs.zig, lib/std/json.zig, lib/std/json/stringify.zig, lib/std/math.zig, lib/std/meta.zig, lib/std/simd.zig
All of these compile errors have been around since before the 0.12.0 release.
=> Delete compile errors for deprecated decls

lib/compiler/build_runner.zig, lib/compiler/reduce.zig, lib/compiler/resinator/main.zig, lib/std/Build/Cache.zig, lib/std/Build/Step/Compile.zig, lib/std/Build/Step/ConfigHeader.zig, lib/std/Build/Step/Options.zig, lib/std/Build/Step/Run.zig, lib/std/Build/Step/WriteFile.zig, lib/std/debug.zig, lib/std/fs/Dir.zig, lib/std/fs/test.zig, lib/std/posix/test.zig, src/Compilation.zig, src/glibc.zig, src/main.zig, test/src/Cases.zig, test/standalone/windows_bat_args/fuzz.zig, test/standalone/windows_bat_args/test.zig, test/standalone/windows_spawn/main.zig, test/tests.zig, tools/process_headers.zig, tools/update-linux-headers.zig
`writeFile` was deprecated in favor of `writeFile2` in f645022d16361865e24582d28f1e62312fbc73bb. This commit renames `writeFile2` to `writeFile` and makes `writeFile2` a compile error.
=> Rename `Dir.writeFile2` -> `Dir.writeFile` and update all callsites

lib/std/io.zig, lib/std/io/Writer.zig, lib/std/mem.zig, lib/std/std.zig, lib/std/zip.zig, lib/std/zip/test.zig, src/Package/Fetch.zig
fixes #17408
Comments Addressed
Improvements:
* more tests around bad zip files
* deflate64 (requires std library work to enhance our current deflate implementation to support deflate64)
* improve std.zip.Diagnostics with nice error messages like std.tar
* implement more extensions like "override the file name from the Info-ZIP Unicode Path Extra Field (0x7075)" or preserving unix file permissions
=> add std.zip and support zip files in build.zig.zon

lib/std/process.zig, src/main.zig
On some systems, this raises the limit before seeing `ProcessFdQuotaExceeded` errors. On other systems, this does nothing.
=> introduce std.process.raiseFileDescriptorLimit

lib/std/zig/Zir.zig, src/Air.zig, src/InternPool.zig, src/Sema.zig, src/codegen/c/Type.zig, src/codegen/llvm.zig
This was a "fake" type used to handle C varargs parameters, much like generic poison. In fact, it is treated identically to generic poison in all cases other than one (the final coercion of a call argument), which is trivially special-cased. Thus, it makes sense to remove this special tag and instead use `generic_poison_type` in its place. This fixes several bugs in Sema related to missing handling of this tag.
Resolves: #19781
=> InternPool: eliminate `var_args_param_type`

lib/std/fs/Dir.zig
This fixes a race condition when two threads/processes try to `makeOpenPath` the same path simultaneously.
Expected to fix:
```
error: unable to write 'C:\Users\user\AppData\Local\zig\b\88252ac14d3f2f75467674e5a1aa8367\builtin.zig': Unexpected
```
Reproducer:
```zig
var threads: [2]std.Thread = undefined;
try std.fs.cwd.deleteTree("a");
for (&threads) |*thread| thread.* = try std.Thread.spawn(.{ .allocator = std.heap.page_allocator }, run, .{});
for (threads) |thread| thread.join();
}
fn run() !void {
var dir = try std.fs.cwd().makeOpenPath("a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u/v/w/x/y/z", .{});
dir.close();
}
```
=> fs: handle `OBJECT_NAME_COLLISION` in `makeOpenPath`

CMakeLists.txt
Not sure why this exists in the first place, but disabling it reduces the required dependencies of a CI runner.
=> cmake: make static curses configurable

lib/compiler/aro/aro/Type.zig, lib/compiler/aro_translate_c.zig, test/cases/translate_c/circular_struct_definitions.c, test/cases/translate_c/double_define_struct.c, test/cases/translate_c/field_access_is_grouped_if_necessary.c, test/cases/translate_c/global_struct_whose_default_name_conflicts_with_global_is_mangled.c, test/cases/translate_c/large_packed_struct.c, test/cases/translate_c/packed_union_nested_unpacked.c, test/cases/translate_c/packed_union_simple.c, test/cases/translate_c/pointer_to_struct_demoted_opaque_due_to_bit_fields.c, test/cases/translate_c/qualified_struct_and_enum.c, test/cases/translate_c/qualified_struct_and_enum_msvc.c, test/cases/translate_c/scoped_record.c, test/cases/translate_c/simple_struct.c, test/cases/translate_c/simple_union.c, test/cases/translate_c/struct_in_struct_init_to_zero.c, test/cases/translate_c/struct_with_aligned_fields.c, test/cases/translate_c/struct_with_invalid_field_alignment.c, test/cases/translate_c/type_referenced_struct.c, test/cases/translate_c/union_initializer.c, test/cases/translate_c/union_struct_forward_decl.c, test/cases/translate_c/unnamed_fields_have_predictable_names.c, test/cases/translate_c/zero_width_field_alignment.c, test/cases/translate_c/zig_keywords_in_c_code.c, test/translate_c.zig
Edit: Ready for review. See below for a summary of changes.
---
This PR adds support for translating C record types. The PR is still very much a work in progress, so it's probably not worth reviewing now. The only tests that have been added are `simple_struct.c` and `simple_union.c`. 
Tasks to complete before it's ready:
=> aro translate-c: support for record type translation

lib/std/os/linux/IoUring.zig
`entries` can be up to `32768`, so the result does not fit into the 16bits given by peer type resolution.
@ianic, can you take a look?
=> fix integer overflow in IoUring buffer ring size calculation

src/codegen/llvm.zig
Fixes #15095
Somebody who knows these compiler internals should verify my logic here, but the conditional here does not make sense to me. Consider the following piece of code `example.zig`:
```zig
var globl: i32 = 0;
var hello: i32 = 1;
hello += 1;
globl += 124;
}
```
`globl` is the variable that debuggers cannot find. On master this is the relevant LLVM IR:
```llvm
@example.globl = internal unnamed_addr global i32 0, align 4
```
With my fix this becomes:
```llvm
@example.globl = internal unnamed_addr global i32 0, align 4, !dbg !13
```
Note the `!dbg` that was speculated to be the cause in the issue as well. I've verified that this fix allows debuggers to see non-exported global variables, but I'm still confused as to why this check ever existed.
=> llvm: always include debug information for global variables

lib/std/os/windows.zig
According to WinAPI docs, `TCHAR` and their corresponding string typedefs are aliases for either 8-bit `CHAR` or 16-bit `WCHAR` based on a global compilation switch `UNICODE` in the macro, which also globally changes whether -A or -W functions are used.
In Zig we explicitly choose which version of the functions to use and their corresponding types. This means that references to those macro-dependent types are fundamentally incompatible, and they are rightly absent from `std.os.windows`.
However, their absence per se does not convey the intent of a forbidding _exclusion_, instead it can potentially be misinterpreted as an overlooked _omission_, especially considering that looking through the MSDN documentation and all their typedefs can be overwhelming unless one already has sufficient …
=> std.os.windows: add compileError warning against `TCHAR` & their corresponding string/pointer types

src/Package/Fetch.zig, src/main.zig
When adding a dependency using `zig fetch --save` I usually just want the latest thing on the `master`/`main` branch. However, when running `zig fetch --save git+https://github/abc/def#master` this gets saved verbatim in `build.zig.zon`:
```zig
.@"def" = .{
.url = "git+https://github.com/abc/def#master",
.hash = "...",
},
```
Now, when compiling this in the future, the branch may point to another commit, leading to a hash-mismatch.
> Context for the discussion below
<details>
<summary>Old Proposal</summary>
This PR adds the new flag `--resolve-commit` to `zig fetch` which instead saves whatever commit the refspec points at instead:
```zig
.@"def" = .{
.url = "git+https://github.com/abc/def#123403399058fd83f7fbb597f3f8304007ff6a3c",
.hash = "...",
},
```
I'm open to other names for this …
=> `zig fetch`: resolve branch/tag names to commit SHA

lib/std/os/wasi.zig, lib/std/std.zig
Fixes #19665
It seems possible that the last two asserts should now be uncommented as well. I don't know enough about why they were commented in the first place.
=> Do not run asserts for WASI alignment when not targeting WASI

lib/std/zig/AstGen.zig, test/behavior.zig, test/behavior/switch_on_captured_error.zig
=> astgen: fix result info for catch switch_block_err_union

lib/std/Build/Step/Run.zig
=> std.Build.Step.Run: add missing call to writeManifest

src/Package/Fetch.zig, src/main.zig
Resolves the issues raised by @andrewrk in the original PR https://github.com/ziglang/zig/pull/19349 (reverted):
- reduced nesting/indentation
- use new flags `--save-exact=[name]`
- use `std.Uri.Component.format`
=> Follow-up: `zig fetch`: resolve branch/tag names to commit SHA

lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig
Fixes #19946
CreateEventExW reference:
https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventexw
=> [std] Fixed bug missing optional for lpName param on CreateEventExW

lib/std/zig/WindowsSdk.zig
Information about installed MSVC instances are stored in `state.json` files within a `Packages/_Instances` directory. The default location for this is `%PROGRAMDATA%\Microsoft\VisualStudio\Packages\_Instances`. However, it is possible for the Packages directory to be put somewhere else. In that case, the registry value `HKLM\SOFTWARE\Microsoft\VisualStudio\Setup\CachePath` is set and contains the path to the Packages directory.
Previously, WindowsSdk did not check that registry value. After this commit, the registry value `HKLM\SOFTWARE\Microsoft\VisualStudio\Setup\CachePath` is checked first, which matches what ISetupEnumInstances does (according to a Procmon log).
Some more context: https://ziggit.dev/t/how-to-correctly-compile-static-libraries-on-windows/4232/23
---
Also fixes …
=> WindowsSdk: Fix finding the _Instances directory when it's not in the default location

lib/std/os/linux.zig
=> fix: incorrect field sizes in std.os.linux.ifmap

lib/compiler/aro_translate_c.zig
Adds a few minor improvements that didn't make it into #19227. Namely:
1. Don't calculate `head_field_alignment` if it isn't used (ie. if there aren't any alignment attributes).
2. Doc comment added for `alignmentForField()` explaining why it's needed. Also removed specific references to `u29` since it seems that Zig's alignment range may change in the future.
=> Minor follow-up improvements to PR #19227 for aro translate-c

lib/std/heap/general_purpose_allocator.zig
Fixes #19978
I wrote the following program to test different allocation sizes
```zig
const page_size = std.mem.page_size;
var gpa = std.heap.GeneralPurposeAllocator(.{
.safety = true,
.never_unmap = true,
.retain_metadata = true,
}){};
defer std.debug.assert(gpa.deinit() == .ok);
const allocator = gpa.allocator();
var size_class: usize = 1;
while (size_class <= page_size) {
std.debug.print("allocating {}\n", .{size_class * 8});
const alloc = try allocator.alloc(u8, size_class);
allocator.free(alloc);
allocator.free(alloc);
size_class *= 2;
}
}
```
=> gpa: Fix GeneralPurposeAllocator double free stack traces

lib/std/Target.zig, lib/std/zig/LibCDirs.zig, src/codegen/llvm.zig, src/target.zig
Should match how Clang/LLVM handle it but I haven't tested it.
Closes #20009
=> Target: add OpenHarmonyOS ABI

cmake/Findllvm.cmake
Left a comment in #12136, asking why we decided to unset `LLVM_CONFIG_EXE`.
=> cmake/llvm: Don't unset LLVM_CONFIG_EXE

src/Sema.zig, test/cases/compile_errors/discarding_error_value.zig, test/cases/compile_errors/expected_optional_type_got_container.zig, test/cases/compile_errors/for_loop_body_expression_ignored.zig, test/cases/compile_errors/generic_instantiation_failure.zig, test/cases/compile_errors/ignored_assert-err-ok_return_value.zig, test/cases/compile_errors/ignored_comptime_statement_value.zig, test/cases/compile_errors/ignored_comptime_value.zig, test/cases/compile_errors/ignored_deferred_function_call.zig, test/cases/compile_errors/ignored_deferred_statement_value.zig, test/cases/compile_errors/ignored_expression_in_while_continuation.zig, test/cases/compile_errors/ignored_return_value.zig, test/cases/compile_errors/ignored_statement_value.zig, test/cases/compile_errors/method_call_on_error_union.zig, test/cases/compile_errors/while_expected_optional_got_error_union.zig, test/cases/compile_errors/while_loop_body_expression_ignored.zig
=>  Sema: improvements to error messages related to the handling of (error) values

lib/compiler/std-docs.zig
```
$ zig std 
http://127.0.0.1:59993/
error: FileNotFound
```
0.12.0 will output an error on macOS, it should be `open`.
- https://superuser.com/questions/911735/how-do-i-use-xdg-open-from-xdg-utils-on-mac-osx
Also, this PR make `/debug` endpoint works, previously it will return 404...
=> std-docs: use `open` for macOS.

test/link/build.zig, test/link/link.zig, test/link/macho.zig
Fixes regression introduced by https://github.com/ziglang/zig/commit/5d5e89aa8d5a454bce2c93555d3bc7c7ae1aa162
Turns out since landing that PR we haven't run any tests requiring symlinks or any Apple SDK on a macOS host. Not great.
=> test/link: actually run tests requiring symlinks on non-Win

src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/MachO/InternalObject.zig, src/link/MachO/Object.zig, src/link/MachO/Relocation.zig, src/link/MachO/Symbol.zig, src/link/MachO/ZigObject.zig, src/link/MachO/relocatable.zig, test/link/macho.zig
This PR only covers deduping literals between input relocatable object files - `ZigObject` is left as a TODO once we actually start emitting constants into their respective literal sections.
=> link/macho: implement logic for merging literals

lib/std/process/Child.zig
This is @mlugg's commit from #20059 rebased to work on master branch + #20049.
The added comment explains the issue here relatively well. The new
progress API made this bug obvious because it became visibly clear that
certain Compile steps were seemingly "hanging" until other steps
completed. As it turned out, these child processes had raced to spawn,
and hence one had inherited the other's stdio pipes, meaning the `poll`
call in `std.Build.Step.evalZigProcess` was not identifying the child
stdout as closed until an unrelated process terminated.
=> std.process.Child: prevent racing children from inheriting one another's pipes

lib/std/hash_map.zig
- Pass self via value instead of reference in numerous places throughout `HashMapUnmanged` and `HashMap` (orignally proposed in #19770)
- Replaced some instances of `@intFromPtr` and `@ptrFromInt`  with `@ptrCast` and `@alignCast`, and pointer arithmetic where appropriate
With this, the only remaining instance of pointer-int conversion in hash_map.zig is in `HashMapUnmanaged.removeByPtr`, which easily be able to be eliminated once pointer subtraction is supported.
=> hash_map.zig: Pass `self` by value and less pointer-int conversion

lib/std/sort.zig
The line that calculates the midpoint in the upperBound function didn't take into account overflows from large arrays like in other binary search functions.
=> std: Avoid overflowing in the midpoint calculation in upperBound

lib/init/build.zig.zon
Clarify the usage of .paths in build.zig.zon. Follow the recommendation
of the comments to explicitly list paths by explicitly listing the paths
in the init project.
=> init: clarify .paths usage in build.zig.zon

lib/compiler/fmt.zig, lib/std/debug.zig, lib/std/fs/test.zig, lib/std/posix/test.zig, lib/std/testing.zig, src/Package/Fetch.zig, src/main.zig, test/src/Cases.zig, tools/doctest.zig
=> rename zig-cache to .zig-cache

lib/std/math.zig
math.zig imported the "math/float.zig" file multiple time, making the code unnecessarily more verbose.
=> std/math: import "math/float.zig" only once

lib/std/debug.zig
The default behavior for unmatched targets is to define getcontext as an extern function. Make android be an unmatched target rather than compileError.
closes #20117
=> Remove compileError when targetting android and using libc

lib/std/Progress.zig
This changes the terminal display to keep the cursor at the top left of the progress display, so that unlocked stderr writes, perhaps by child processes, don't get eaten by the clear.
[before](https://asciinema.org/a/mDCxRpdRd2A8UHQDzwO1VH8zJ) vs [after](https://asciinema.org/a/5GlmvN5ciu1CwkTPolSOhSpr0)
=> std.Progress: keep the cursor at the beginning

lib/std/math.zig
It kind of already did support them, as both `@min` and `@max` support vectors, just needed different handling in the assert
=> std.math.clamp: Support Vectors

lib/std/Progress.zig
The \r\n is necessary to get the progress tree to work properly in the old console when ENABLE_VIRTUAL_TERMINAL_PROCESSING and DISABLE_NEWLINE_AUTO_RETURN are set.
The line_upper_bound_len fix addresses part of #20161
=> Progress: Emit \r\n on Windows, include new line bytes in line_upper_bound_len

lib/compiler/build_runner.zig, lib/std/io/tty.zig, lib/std/zig.zig, src/main.zig, test/src/StackTrace.zig, tools/doctest.zig
Detecting the [`NO_COLOR`](https://no-color.org/) environment variable and disabling color output if set is a standard practice respected by most CLI tools.
When it comes to the inverse task of forcing color output even when not writing to a terminal, there exist two standards, [`CLICOLOR_FORCE`](https://bixense.com/clicolors/) and [`FORCE_COLOR`](https://force-color.org/). Neither of these two standards come even close to being as ubiquitous as `NO_COLOR`, but they both have some precedence and are respected by a handful of CLI tools.
Prior to e45d24c0de29eb6668e56ea927e15505674833a6, Zig used the `ZIG_DEBUG_COLOR` env variable to force color output, but that commit changed it to `YES_COLOR`. 
`YES_COLOR` seemingly has next to no precedent in existing software ([a search for …
=> Replace the `YES_COLOR` env variable with `CLICOLOR_FORCE`

lib/std/meta.zig
Closes https://github.com/ziglang/zig/issues/17592
=> std.meta.hasUniqueRepresentation: better support packed structs

lib/std/Progress.zig, lib/std/fs/File.zig, lib/std/io/tty.zig
On Windows, the console mode flag `ENABLE_VIRTUAL_TERMINAL_PROCESSING` determines whether or not ANSI escape codes are parsed/acted on. On the newer Windows Terminal, this flag is set by default, but on the older Windows Console, it is not set by default, but *can* be enabled (since Windows 10 RS1 from June 2016).
The new `File.getOrEnableAnsiEscapeSupport` function will get the current status of ANSI escape code support, but will also attempt to enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING` on Windows if necessary which will provide better/more consistent results for things like `std.Progress` and `std.io.tty`.
This type of change was not done previously due to a mistaken assumption (on my part) that the console mode would persist after the run of a program. However, it turns out that the …
=> Add `File.getOrEnableAnsiEscapeSupport` and use it

lib/std/crypto/keccak_p.zig
We support Keccak[f=200] just fine, so allow it.
=> sha3.keccak: allow Keccak[f=200]

lib/std/Target.zig, src/codegen/llvm.zig, src/codegen/llvm/bindings.zig
Still can't build hello world because LLVM didn't implement `fp_to_fp16`.
```
LLVM ERROR: Cannot select: t68: i64 = fp_to_fp16 t2
t2: f32,ch = CopyFromReg t0, Register:f32 %11
t1: f32 = Register %11
In function: __fixhfsi
```
=> LLVM backend: loongarch64 support

lib/std/fs/Dir.zig, lib/std/fs/test.zig
- Fixes a regression introduced in https://github.com/ziglang/zig/commit/67455c5e70e86dbb7805ff9a415f1b13b14f36da (cc @jacobly0). The `errdefer` cannot run since its not possible for an error to occur past that point, and we don't want it to run on the last handle, so we move the closing back down to where it was before https://github.com/ziglang/zig/commit/67455c5e70e86dbb7805ff9a415f1b13b14f36da.
- Fixes leaking a directory handle in "makepath existing directories" test in `fs/test.zig`
Should fix the cause of https://github.com/ziglang/zig/issues/20079 but does not close it, since `DELETE_PENDING` should still be handled in `makeOpenDirAccessMaskW`
=> Fix handle leaks in `Dir.makeOpenPathAccessMaskW` and a `fs` test

lib/compiler/aro_translate_c.zig, lib/compiler/aro_translate_c/ast.zig, src/translate_c.zig, test/cases/translate_c/macro_referencing_var.c, test/translate_c.zig
This PR changes how macros deemed to use runtime identifiers are generated. The current behavior generates decls that throw a compiler error upon being referenced:
`test.h`
```c
extern float foo;
#define FOO_TWICE foo * 2.0f
#define FOO_NEGATIVE -foo
#define BAR 10.0f
#define BAR_TWICE BAR * 2.0f
```
`zig translate-c test.h`
```zig
pub extern var foo: f32;
pub const FOO_TWICE = foo * @as(f32, 2.0);
pub const FOO_NEGATIVE = -foo;
pub const BAR = @as(f32, 10.0);
pub const BAR_TWICE = BAR * @as(f32, 2.0);
```
Referencing `FOO_TWICE` or `FOO_NEGATIVE` in your code will lead to a compile error:
`main.zig`
```zig
const c = @cImport(@cInclude("test.h"));
export const foo: f32 = 10;
_ = c.FOO_TWICE;
}
```
``` …
```
=> Translate Macros That Use Runtime Identifiers To Inline Functions

src/link/Elf.zig
```sh
$ zig build-exe main.zig -target armeb-freestanding --verbose-link
ld.lld --error-limit=0 --entry _start -z stack-size=16777216 --image-base=65536 -znow -m armebelf_linux_eabi -Bstatic -o main main.o /home/mike/project/zig/work/main/zig-cache/o/51a4a9fec86fe30c9e4f35333430c0a0/libc.a --as-needed /home/mike/project/zig/work/main/zig-cache/o/f0ca07dea4b8c61005af6a4a6b771faa/libcompiler_rt.a --allow-shlib-undefined
error: ld.lld: unknown emulation: armebelf_linux_eabi
```
```sh
$ zig build-exe main.zig -target aarch64_be-freestanding --verbose-link
ld.lld --error-limit=0 --entry _start -z stack-size=16777216 --image-base=16777216 -znow -m aarch64_be_linux -static -o main main.o /home/mike/project/zig/work/main/zig-cache/o/b17128ff5fbcce92dd6be944ba510aa5/libc.a --as-needed …
```
=> ld.lld: fix -m option for big-endian arm/aarch64

lib/std/fs/File.zig
See https://github.com/ziglang/zig/issues/20188 for details
Follow up to #20172. Fixes #20188
=> File.getOrEnableAnsiEscapeSupport: Do not attempt to set DISABLE_NEWLINE_AUTO_RETURN

lib/std/Build/Step/ObjCopy.zig
The actual `zig objcopy` does not accept keeping multiple sections. If you pass multiple `-j .section` arguments to `zig objcopy`, it will only respect the last one passed.
Originally I changed `zig objcopy` to accept multiple sections and then concatenate them instead of returning after outputting the first section (see emitElf) but I realized concatenating probably doesn't make sense.
=> objcopy build step: don't accept multiple sections

lib/std/heap/general_purpose_allocator.zig
Fixes #19977
This makes the following test not crash
```zig
test "retain metadata and never unmap" {
var gpa = std.heap.GeneralPurposeAllocator(.{
.safety = true,
.never_unmap = true,
.retain_metadata = true,
}){};
defer std.debug.assert(gpa.deinit() == .ok);
const allocator = gpa.allocator();
const alloc = try allocator.alloc(u8, 8);
allocator.free(alloc);
const alloc2 = try allocator.alloc(u8, 8);
allocator.free(alloc2);
}
```
The `getMin/getMax` -> remove pattern could be encapsulated in a function `popMin/popMax` that return the removed key.
=> Fix GeneralPurposeAllocator crash when deallocating metadata

lib/std/Build.zig
This add supports for `[]enum`, which are treated as `[]const []const u8`.
Example:
```zig
const Foo = enum {
Foo,
Bar,
};
const foo: []Foo = b.option([]Foo, "foo", "foo") orelse unrechable;
```
Can be used as:
```
zig build -Dfoo=Foo 
zig build -Dfoo=Bar
zig build -Dfoo=Foo -Dfoo=Bar
=> Add support for []enum in Build.option

lib/std/Build.zig, lib/std/Build/Step/Run.zig
=> std.Build: remove deprecated b.host in favor of b.graph.host

src/libcxx.zig, test/standalone/build.zig.zon, test/standalone/libcxx/build.zig, test/standalone/libcxx/mt.zig, test/standalone/libcxx/mt_doit.cpp, test/standalone/libcxx/st.zig, test/standalone/libcxx/st_doit.cpp
* Skip building libcxx mt-only source files when single-threaded.
* This change is required for llvm18 libcxx.
* Add standalone test to link a trivial:
- mt-executable with libcxx
- st-executable with libcxx
```
zig build-exe main.zig -lc++ -fsingle-threaded
```
=> libcxx: fix building when -fsingle-threaded

lib/std/os/linux/IoUring.zig
We are posting two submissions (zero copy send and receive) and then reading two completions. There is no guarantee that those completions will be in the order of submissions.
This test was expecting fist send completion then receive. Fix is allowing them to come the other way too.
Fixes: #20212
=> io_uring: don't assume completions order

lib/std/zig/WindowsSdk.zig
The current code wrongly assumes that versions[0] will always exist after the iterateAndFilterByVersion call.
Seen in the wild here: https://ziggit.dev/t/segmentation-fault-at-address-0x4-using-c-library/4468/29
=> WindowsSdk: Fix index-of-out-bounds when no versions are found in the sdk lib dir

doc/langref.html.in, lib/docs/index.html
closes https://github.com/ziglang/zig/issues/20144
=> autodoc: fix misaligned table header when alignment is default

lib/libc/glibc/README.md, lib/std/zig/target.zig, test/link/glibc_compat/build.zig, test/link/glibc_compat/glibc_runtime_check.c
Add `glibc_runtime_check.c`: a simple test case that exercises glibc functions that might smoke out linking problems with Zig's C compiler.  The build.zig compiles it against a variety of glibc versions.
Also mark the `aarch64` glibc minimum version as 2.17 (the `aarch64_be` target was already marked).  This is necessary because earlier versions of glibc do not support the aarch64 architecture.
Also document and test glibc v2.2.5 (from 2002) as the oldest working glibc target for C binaries.  (Earlier versions fail with a raft of missing symbols.)
=> test/link/glibc_compat: Add C test case for glibc versions

lib/std/os/linux/start_pie.zig
`Elf*_Rela` relocations store their argument in `r_addend`, including for `R_*_RELATIVE` relocations.  Unlike `Elf*_Rel` relocations, they are not applied as a delta to the destination virtual address.  Instead, they are computed from `base_address + r_addend` directly.
This is a very small fixup to make this follow the spec.  For supporting evidence for this change, see the glibc source code below that handles this type of relocation on x86_64:
https://github.com/bminor/glibc/blob/master/sysdeps/x86_64/dl-machine.h#L258
And on musl:
https://github.com/kraj/musl/blob/9f1842d38a02f9a213d3405ee0f767a1db385823/ldso/dynlink.c#L483
It is unlikely anyone would have even noticed this because the linker generally initializes these areas to 0, which ends up having the same effect.
=> Fix slight deviation from spec in handling Elf*_Rela relative relocations

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, src/print_zir.zig
These instructions are not emitted by AstGen. They also would have no effect even if they did appear in ZIR: the Sema handling for these instructions creates a Decl which the name strategy is applied to, and proceeds to never use it. This pointless CPU heater is now gone, saving 2 ZIR tags in the process.
=> Zir: remove legacy `error_set_decl` variants

lib/std/Build.zig, src/codegen/spirv.zig, src/codegen/spirv/Module.zig, src/link/SpirV.zig, test/behavior/abs.zig, test/behavior/array.zig, test/behavior/byval_arg_var.zig, test/behavior/cast.zig, test/behavior/enum.zig, test/behavior/error.zig, test/behavior/floatop.zig, test/behavior/hasdecl.zig, test/behavior/math.zig, test/behavior/optional.zig, test/behavior/packed-struct.zig, test/behavior/packed-union.zig, test/behavior/select.zig, test/behavior/shuffle.zig, test/behavior/slice.zig, test/behavior/string_literals.zig, test/behavior/typename.zig, test/behavior/union.zig, test/behavior/vector.zig
This adds a new abstraction for building low-level spirv operations, intended to make implementations of air instructions easier to read and write. These functions work with scalars and vectors of any size, and transparently selects the best way to lower them: if a particular operation cannot be vectorized, either because of the operation doesn't allow it outr because there is no native representation of the vector size, it's unrolled into separate separate operations. 
To reduce the amount of vector packing/unpacking operations between low-level operations, there is now a new `Temporary` type. This is intended as a representation for intermediate values during an operation, and may hold values in separate forms depending on the type and previous operations. For example, it can represent …
=> spirv: vectors v3

lib/std/Progress.zig, tools/update_cpu_features.zig
A node may be freed during the execution of this loop, causing there to
be a parent reference to a nonexistent node. Without this assignment,
this would lead to the map entry containing stale data. By assigning
none, the child node with the bad parent pointer will be harmlessly
omitted from the tree.
Closes #20262
=> std.Progress: fix race assertion failure

doc/langref.html.in, lib/std/zig/AstGen.zig, src/Package/Manifest.zig
The surrogate code points U+D800 to U+DFFF are valid code points but are not Unicode scalar values. This commit makes the error message more accurately reflect what is actually allowed in `\u` escape sequences.
From https://www.unicode.org/versions/Unicode15.0.0/ch03.pdf:
> D71 High-surrogate code point: A Unicode code point in the range U+D800 to U+DBFF.
> D73 Low-surrogate code point: A Unicode code point in the range U+DC00 to U+DFFF.
>
> 3.9 Unicode Encoding Forms
> D76 Unicode scalar value: Any Unicode code point except high-surrogate and low-surrogate code points.
Related: #20270
=> More precise error message for unencodable `\u` escapes

lib/std/Progress.zig, lib/std/Thread/Mutex.zig, lib/std/Thread/Mutex/Recursive.zig, lib/std/debug.zig
This patch adds `std.Thread.Mutex.Recursive` which is a recursive mutex implementation (cc @kprotty for review).
Next, it changes the mutex used by `std.debug.lockStdErr()` to be a recursive mutex, and obtains the lock when panicking.
The previously used `panic_mutex` is no longer needed.
=> make stderr mutex recursive and lock it when panicking

lib/std/posix.zig
Before this commit, the DIRECTORY_NOT_EMPTY/FILE_IS_A_DIRECTORY/NOT_A_DIRECTORY statuses were assumed only to be possible when using `FILE_RENAME_INFORMATION_EX` and `FILE_RENAME_POSIX_SEMANTICS`, but that has empirically been shown to be false; a networked samba share can return the DIRECTORY_NOT_EMPTY status from `FILE_RENAME_INFORMATION` (which doesn't support `FILE_RENAME_POSIX_SEMANTICS`).
`FILE_IS_A_DIRECTORY` and `NOT_A_DIRECTORY` were not proven to be possible (from my testing, `OBJECT_NAME_COLLISION` is returned when trying to name a file onto a directory or vice versa), but they were also moved to the outer switch just in case.
Fixes #19785
=> posix.renameW: Handle DIRECTORY_NOT_EMPTY more generally

lib/std/os/linux.zig
The syscall gives immediate compile error in zig 0.12. This PR fix that.
=> Fix futex2_waitv syscall

src/arch/wasm/CodeGen.zig, test/behavior/enum.zig
Seems, when big ints handling was added, code related to enums was not touched.
I re-enable assertion in `lowerConstant`, which was hitted by the `behavior/enum.zig` test.
=> stage2-wasm: enum bigint <= 128 bits

src/translate_c.zig, test/cases/run_translated_c/compound_assignments_with_pointer_arithmetic.c
The right-hand side was incorrectly cast to a pointer, since only signed ints were being interpreted correctly as pointer arithmetic.
Fixes #20285.
=> translate-c: fix translation of "ptr += uint"

lib/std/fmt/parse_float.zig, lib/std/fmt/parse_float/FloatStream.zig, lib/std/fmt/parse_float/decimal.zig, lib/std/fmt/parse_float/parse.zig
There were two primary issues at play here:
1. The hex float prefix was not handled correctly when the stream was reset for the fallback parsing path, which occured when the mantissa was longer max mantissa digits.
2. The implied exponent was not adjusted for hex-floats in this branch.
Additionally, some of the float parsing routines have been condensed, making use of comptime.
closes #20275.
=> std.float.parseFloat: fix large hex-float parsing

src/Sema.zig, src/codegen/spirv.zig, src/codegen/spirv/Module.zig
This should probably have been done a while ago :)
It turns out that OpenCL returns `usize` for all of these. For now I've inserted a cast, but perhaps its better to change the signature, at least for `@workGroupId()`. The others can't realistically be larger than u32. Usually platforms limits these to 1024, in fact, so I don't think there is an issue there.
=> spirv: add support for GPU builtins

lib/compiler_rt.zig, lib/compiler_rt/bitreverse.zig, lib/compiler_rt/bitreversedi2_test.zig, lib/compiler_rt/bitreversesi2_test.zig, lib/compiler_rt/bitreverseti2_test.zig, src/arch/wasm/CodeGen.zig, test/behavior/bitreverse.zig
Implementation for `@bitReverse` for stage2 wasm backend. I enabled and successfully ran a behaviour test for `@bitReverse`, also I added one runtime test for testing integers between 64 and 128 bits in size.
The idea for lowering is primarily based on how llvm lowers this operation in ReleaseSmall. The algorithm takes `log2(integer bits size)` steps, in which adjacent strides of bits (1, 2, 4, 8, 16, 32 until necessary) are swapped.
This is my first experience with self hosted wasm backend. I did try to follow common patterns in surrounding code, but I found there are 2 prevailing styles across `CodeGen.zig`, so I may have over engineered some parts of my code.
=> stage2-wasm: bit_reverse

lib/std/start.zig
This reverts commit d7daf7c203f583ed440efc68df6ee690ee8f8f32.
This is no longer needed with the LLVM 18 upgrade, and it was breaking PIE.
Closes #20306.
=> Revert "start: workaround for LLVM 17 regression" to fix #20306.

lib/std/Build.zig, lib/std/Build/Step.zig, lib/std/Build/Step/Fail.zig
Closes #15373.
Note that I didn't add the proposed `fail(step: *Step, comptime format: []const u8, args: anytype) *Step` to `std.Build.Step` as it seemed a bit non-idiomatic for `std.Build`. The same can be achieved with `step.dependOn(&b.addFail(b.fmt("...", .{...})).step)`. I can certainly add it if we really want it, though.
=> std.Build: Add Step.Fail and addFail() function.

src/codegen/llvm.zig
This is not supported by llvm.
=> llvm: avoid debug info for naked function arguments

lib/std/Target.zig
Just happened to notice that these haven't been updated in a while.
Sourced from:
* https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/sdkddkver.h
* https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions#Personal_computer_versions
=> std.Target: Update known Windows 10/11 versions and build numbers.

build.zig, ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, lib/std/Build/Step.zig, lib/std/Build/Step/Fmt.zig, lib/std/Progress.zig, lib/std/process/Child.zig
Example of a zig fmt failure with this branch:
```console
[nix-shell:~/dev/zig/build-release]$ stage3/bin/zig build test-fmt
test-fmt
└─ zig fmt --check failure
error: /home/andy/dev/zig/src/main.zig: non-conforming formatting
error: the following command exited with error code 1:
/home/andy/dev/zig/build-release/stage3/bin/zig fmt --check /home/andy/dev/zig/lib /home/andy/dev/zig/src /home/andy/dev/zig/test /home/andy/dev/zig/tools /home/andy/dev/zig/build.zig /home/andy/dev/zig/build.zig.zon --exclude /home/andy/dev/zig/test/cases 
Build Summary: 0/2 steps succeeded; 1 failed (disable with --summary none)
test-fmt transitive failure
└─ zig fmt --check failure
error: the following build command failed with exit code 1:
/home/andy/dev/zig/.zig-cache/o/3ac7a20af5c73e65a83d2e9b65218673/build …
```
=> enhance `std.Build.Step.Fmt` and use it more

build.zig, ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh
Eliminates a TODO from the CI scripts; makes it easier to check validity of html when working on the langref locally.
Checking autodocs is disabled because tidy gives a false positive:
```
line 304 column 9 - Warning: moved <style> tag to <head>! fix-style-tags: no to avoid.
```
I noticed that `--show-warnings no` still incorrectly causes exit code 1. I was unable to find an alternative to tidy.
=> add -Denable-tidy flag and use it in the CI

stage1/FuncGen.h
Using zig cc to compile and run wasm2c on zig1.wasm triggers what appears to be a sanitizer crash, i.e.
```sh
$ zig cc -o wasm2c stage1/wasm2c.c 
$ ./wasm2c stage1/zig1.wasm zig.c
Illegal instruction (core dumped)
```
The `FuncGen` struct field `reuse` (an array pointer) is initialized to null and at some point is resized to a length of zero, which triggers this code to execute:
```c
memcpy(&self->reuse[self->reuse_i], &self->reuse[reuse_top], sizeof(uint32_t) * reuse_n);
```
Given the current values, this equates to:
```c
memcpy(&(NULL)[0], &(NULL)[0], 0);
```
Taking the address of the first element of a null pointer doesn't trigger any actual runtime problem, since the pointer won't be dereferenced because were passing 0 as the length to memcpy, however, it seems that the C spec …
=> wasm2c: avoid indexing null pointer triggering undefined behavior

lib/std/meta.zig, lib/std/testing.zig
closes #20342 , previously failing test code is included.
=> fix `std.testing.expectEqual`, `std.meta.eql` for `comptime`-only unions

lib/std/c/linux.zig, lib/std/posix.zig
Using std.os.linux directly in e.g. std.posix.timerfd_create() causes the function to compile but silently fail at runtime when targeting any OS other than Linux.
To catch errors like this at compile time, std.os.linux must only be directly accessed within std.posix where there has been a comptime check that the target os is in fact Linux.
=> std.posix: remove unchecked std.os.linux usage

src/Compilation/Config.zig, src/main.zig
=> add error message for `-fno-llvm` `-flld`

lib/compiler/build_runner.zig
The error message for the --summary command line option did not list 'new' as a valid choice, potentially confusing users.
This commit updates the error hint to accurately reflect all available options.
=> build runner: add missing 'new' option to --summary error hint

lib/std/sort.zig
Stability of std sort was undertested before this change. Add a fuzz
test for more confidence.
Specifically, we used to have a single example test that used an array
of eight elements. That ends up exercising only a tiny fraction of
sorting logic, as it hits a hard-coded sorting network due to small
size.
EDIT: I've run this test for a million iterations locally, so it seems like there aren't actual problem with sort stability!
=> std: fuzz test sort stability

lib/std/os/linux/IoUring.zig
In my first [try](https://github.com/ziglang/zig/pull/20224) to fix 20212 I didn't reproduce bug on required kernel (6.9.2) and wrongly concluded that first two completions have different order on newer kernel.
On my current kernel (6.5.0) order of completions is: send1, recv, send2. On 6.9.2 order is send1, send2, recv. This fix allows second two completions to arrive in any order.
Tested on both kernels.
Fixes: #20212
=> io_uring: don't assume completions order (2)

lib/zig.h, stage1/zig.h
Noticed this today while reviewing some some f32 stuff in zig.h.
=> Fix `ypedef` -> `typedef` in zig.h

src/target.zig
=> Enables dynamic linking for `.os_tag == .other` again

lib/std/Build.zig, lib/std/process/Child.zig
While here, I also improved it to not misreport OOM from std.fs.realpathAlloc() as a generic failure to find the program, but instead panic like the rest of the build system does for OOM.
This is the fix I proposed in #20314.
=> std.Build.findProgram(): Try with and without the executable extension.

lib/std/Build/Step/CheckObject.zig, lib/std/compress/xz.zig, lib/std/compress/xz/block.zig, lib/std/dwarf.zig, lib/std/dwarf/call_frame.zig, lib/std/dwarf/expressions.zig, lib/std/leb128.zig, src/arch/wasm/CodeGen.zig, src/arch/wasm/Emit.zig, src/link/Dwarf.zig, src/link/MachO/Dylib.zig, src/link/MachO/dwarf.zig, src/link/MachO/dyld_info/Rebase.zig, src/link/MachO/dyld_info/Trie.zig, src/link/MachO/dyld_info/bind.zig, src/link/MachO/eh_frame.zig, src/link/Wasm.zig, src/link/Wasm/Object.zig
From Zig's style guide, names like `readULEB128` and `writeILEB128` should be cased as `readUleb128` and `writeIleb128`, respectively.
=> Rename *[UI]LEB128 functions to *[UI]leb128

lib/std/crypto/chacha20.zig
Thanks to @r4gus for reporting this.
Fixes #20398
=> std.crypto.chacha: fix typo in XChaChaIETF.stream()

lib/std/zig/target.zig
This doesn't actually exist; Windows on Arm only runs on little endian. MinGW also doesn't work for these targets at all.
=> std.zig.target: Remove `armeb-windows-gnu` and `aarch64_be-windows-gnu`.

lib/std/mem.zig
Closes https://github.com/ziglang/zig/issues/20401
=> std.mem.zeroes: make usage of .EnumLiteral a compile error

src/arch/wasm/CodeGen.zig, test/behavior/abs.zig
On my quest to compile `compiler_rt` by self hosted wasm backend. `@abs` for 128 bit integers needs to be implemented.
This pull request also contains two additional changes:
- Fixes `fn wrapOperand` for `128 bit` integers
- While doing above I found it inconvenient, the fact that `addImm32` accepts `i32`, but `addImm64` - `u64`. I changed it to `u32`, which undoubtedly increased consistency across `CodeGen.zig`
=> stage2-wasm: abs 128 bit

doc/langref.html.in
Just finished reading the Zig Test section at [ziglang.org/documentation](https://ziglang.org/documentation/master/#Zig-Test) and noticed the `lib/test_runner.zig` source code location mentioned in the document has [changed](https://github.com/ziglang/zig/commit/dfe430e9f488536c6ce4be23473f60aa5e89ab5a#diff-fdcfae9450245421af2f3ea783b1c4a34613908f790048fc31f7372aab451bc3), so I submitted this fix.
=> langref: update Zig Test section

lib/std/Build/Step/Compile.zig, test/standalone/build.zig.zon, test/standalone/dep_duplicate_module/build.zig, test/standalone/dep_duplicate_module/lib.zig, test/standalone/dep_duplicate_module/main.zig, test/standalone/dep_duplicate_module/mod.zig
The existing implementation adds the same module multiple times in the following case:
1. Module `app` depends on the static library `lib` and the module `mod`.
```zig
// file: app/build.zig.zon
.{
.name = "app",
.version = "0.0.0",
.dependencies = .{
.lib = .{ .path = "../lib", },
.mod = .{ .path = "../mod", },
},
.paths = .{ "" },
}
```
2. Static library `lib` depends on the module `mod` too.
```zig
// file: lib/build.zig.zon
.{
.name = "lib",
.version = "0.0.0",
.dependencies = .{
.mod = .{ .path = "../mod", },
},
.paths = .{ "" },
}
```
The build fails with 
```
error: error: unable to add module 'mod': already exists as 'mod.zig'
```
This PR fixed the above problem. 
According to my limited understanding of the convoluted Zig build system, the proposed fix should not break any other …
=> Fix adding module arguments for Step.Compile

.github/workflows/ci.yaml
Apple has already dropped support for macOS 11.
GitHub Actions is dropping macOS 11 support now.
The Zig project is also dropping macOS 11 support now.
=> CI: update macOS runner to 12

lib/compiler/aro/aro/Parser.zig, lib/std/ascii.zig, lib/std/net.zig, lib/std/zig/tokenizer.zig
"ASCII" should be treated as a normal word according to [the style guide](https://ziglang.org/documentation/0.13.0/#Names), and thus `isASCII` should be cased as `isAscii`.
This keeps `isASCII` as a deprecated alias for `isAscii` to ease the transition for users.
=> Rename isASCII to isAscii

src/arch/wasm/CodeGen.zig, src/arch/wasm/Emit.zig, src/arch/wasm/abi.zig, test/behavior/math.zig
See commit names for additional changes.
~~When migrating sign extension strategy, I encountered some Heisenbug related to bitcasting, ultimately I was able to pass all behavior tests, except one test (inside `int_cast.zig`), while this test seems to be related to strategy migration, it actually not (see code comment).~~ Fixed.
While I think migration was successful, there are places across `Codegen.zig` where wrapping is redundant. I also found a dozen bugs (ex: how `@mulWithOverflow` handles non-native ints), which I did not fix intentionally. This is the next PRs problem, because of the amount of tests I need to add for them.
Related #20404.
=> stage2-wasm: store signed integers with extended sign bit + minor changes

lib/std/zig/AstGen.zig, lib/std/zig/number_literal.zig, test/cases/compile_errors/invalid_number_literals.zig
This fixes those sequences of characters crashing.
Fixes #20385
=> Make 0e.0 and 0xp0 not crash

lib/libc/include/generic-glibc/stdlib.h
Hide the arc4random* prototypes when building against glibc targets before v2.36.
For context, here's the glibc v2.36 announcment noting the addition of arc4random, arc4random_buf and arc4random_uniform:
https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=8420a65cd06874ee09518366b8fba746a557212a;hb=6f4e0fcfa2d2b0915816a3a3a1d48b4763a7dee2
Tested with the testcase from the bug report.  I get a compile-time error when building against older glibc (instead of a linker error), and no errors (as before) when compiling against v2.36 or later.  And the glibc_compat regression tests pass.
Fix #20426
=> glibc headers: arc4random* functions added in glibc 2.36

lib/std/c/freebsd.zig
The eventfd system call and dup3 library function have been available since FreeBSD 13 and 10 respectively, and are thus available in all [FreeBSD releases not deemed EOL](<https://endoflife.date/freebsd>)
The lack of these were discovered when porting a terminal emulator to FreeBSD. It would be nice to have them included in Zig's stdlib.
Man pages:
[eventfd, FreeBSD 13](<https://man.freebsd.org/cgi/man.cgi?query=eventfd&apropos=0&sektion=2&manpath=FreeBSD+13.0-RELEASE&arch=default&format=html>)
[dup3, FreeBSD 10](<https://man.freebsd.org/cgi/man.cgi?query=dup3&apropos=0&sektion=0&manpath=FreeBSD+10.0-RELEASE&arch=default&format=html>)
=> [std.c] Add eventfd and dup3 functions to FreeBSD

lib/compiler/aro/aro/Driver.zig, lib/std/fs.zig, lib/std/fs/Dir.zig, lib/std/fs/test.zig, lib/std/zig/WindowsSdk.zig
`MAX_PATH_BYTES` was renamed to `max_path_bytes`. `MAX_NAME_BYTES` should get the same treatment. This keeps `MAX_NAME_BYTES` as an alias for `max_name_bytes` to ease the transition.
=> Rename MAX_NAME_BYTES to max_name_bytes

lib/std/valgrind.zig
"SIMD" should be treated as a normal word and thus `nonSIMDCall0` should be cased as `nonSimdCall0`.
=> Rename nonSIMDCall* to nonSimdCall*

lib/std/json/dynamic.zig, lib/std/json/dynamic_test.zig, lib/std/json/test.zig
This test would previously pass successfully even though it shouldn't:
```zig
test {
const parsed_value = try std.json.parseFromSlice(std.json.Value, std.testing.allocator,
\\{
\\  "foo": 1,
\\  "foo": 2
\\}
, .{ .duplicate_field_behavior = .@"error" });
defer parsed_value.deinit();
try std.testing.expectEqual(2, parsed_value.value.object.get("foo").?.integer);
}
```
=> json: respect duplicate_field_behavior in std.json.Value.jsonParse

src/Compilation.zig
=> Compilation: pass libc include directories when compiling assembly_with_cpp

src/codegen/llvm/Builder.zig
The trail_len was being multiplied by the size of the type before.
Pointed out by @jacobly0 here: https://github.com/ziglang/zig/pull/19031#discussion_r1664093634
=> LLVM Builder: Pass correct argument to ensureUnusedMetadataCapacity

lib/std/tar.zig, src/Package/Fetch.zig
This was the only kind of error which was raised in pipeToFileSystem and not added to Diagnostics.
Shell tar silently ignores paths which are stripped out when used with `--strip-components` switch. This enables that same behavior, errors will be collected in diagnostics but caller is free to ignore that type of errors.
Enables use case where caller knows structure of the tar file and want to extract only some deeply nested folders ignoring upper files/folders.
Fixes: #17620 by giving caller options:
- not provide diagnostic and get errors
- provide diagnostics and analyze errors
- provide diagnostics and ignore errors
=> std.tar: add strip components error to diagnostics

test/behavior/string_literals.zig
Happened to notice that the failing test case from #15944 passes now, so this has been fixed sometime in the last year. Closes #15944
=> Add behavior test: including the sentinel when dereferencing a string literal

lib/std/Build/Module.zig, lib/std/Build/Step/WriteFile.zig, test/src/Cases.zig, test/src/CompareOutput.zig, test/src/RunTranslatedC.zig, test/src/StackTrace.zig, test/src/TranslateC.zig, test/standalone/build.zig.zon, test/standalone/dep_lazypath/build.zig, test/standalone/dep_lazypath/inc/foo.h, test/standalone/dep_lazypath/inctest.zig, test/tests.zig
Adds a missing call to addLazyPathDependenciesOnly in std.Build.Module.addCSourceFiles.  Also fixes an issue in std.Build.Step.WriteFile where it wasn't updating all the GeneratedFile instances for every directory.  To fix the second issue, I removed all the GeneratedFile instances and now all files/directories reference the steps main GeneratedFile via sub paths.
=> build: fix WriteFile and addCSourceFiles not adding LazyPath deps

src/Compilation.zig, src/libtsan.zig, src/link/Elf.zig, src/link/MachO.zig, src/link/MachO/load_commands.zig
After careful investigation it turns out that on macOS we need to inject a dylib in order to properly instrument an image. I suspect this might actually be the case for all sanitizers but for now let us focus on one and let it be TSAN since it will be needed now more than ever once I upstream parallelized MachO linker.
Some requirements posed by LLVM's TSAN we need to adhere to/work around:
* https://github.com/llvm/llvm-project/issues/97627 - to work around this one, we simply force the headerpad size to be nonzero when building the TSAN dylib in zig's global cache
* TSAN lib expects `libclang_rt.tsan_osx_dynamic.dylib` as the dylib name and looks for it when spinning up so we will conform by setting the name of the TSAN dylib to just that: …
=> actually support TSAN on macOS

lib/std/Target.zig
=> std.Target: Use arch8 as the baseline CPU model for s390x.

lib/std/c.zig
```zig
_ = std.c.setlocale(.ALL, null); // Get locale
_ = std.c.setlocale(.ALL, "en_GB.UTF-8"); // Set locale
```
=> std.c: Add setlocale()

cmake/Findllvm.cmake
Line `link_directories("${CMAKE_PREFIX_PATH}/lib")` was evaluated as `link_directories("/lib")` in the default case of `CMAKE_PREFIX_PATH` being empty.
This caused cmake to add `-L/lib -Wl,-rpath,/lib` to the zig2 build flags.
This could result in errors on systems where libraries set via `CMAKE_LIBRARY_PATH` had conflicting versions in `/lib`:
- `-L/lib` could cause linking zig2 to fail
- `-Wl,-rpath,/lib` adds `/lib` as the first entry of the zig2 `RPATH`. This could cause running zig2 (to build zig3) to fail.
In case of conflicting lib dirs, cmake emitted this warning, which is now fixed:
```
Cannot generate a safe runtime search path for target zig2 because files in
some directories may conflict with libraries in implicit directories:
runtime library [libclang-cpp.so.18.1] in …
```
=> cmake/findllvm: fix incorrect lib dir setup for zig2

lib/std/crypto/argon2.zig, lib/std/crypto/bcrypt.zig, lib/std/crypto/scrypt.zig
These parameters according to the [OWASP cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html).
See also: #20503
=> std.crypto.pwhash: Add recommended parameters

lib/std/Build/Cache/Path.zig, lib/std/Build/Step/TranslateC.zig, lib/std/array_hash_map.zig, lib/std/coff.zig
Fixes a few of the errors mentioned in #20505
=> Fix a few compilation errors

lib/compiler/build_runner.zig
```
mkdir aaa
cd aaa
zig init
zig build --prefix
```
before:
```
thread 33711 panic: index out of bounds: index 9, len 9
/home/paulo/.local/lib/zig/lib/compiler/build_runner.zig:1211:110: 0x10f2e55 in nextArgOrFatal (build)
std.debug.print("expected argument after '{s}'\n  access the help menu with 'zig build -h'\n", .{args[idx.*]});
^
/home/paulo/.local/lib/zig/lib/compiler/build_runner.zig:131:48: 0x10edd41 in main (build)
install_prefix = nextArgOrFatal(args, &arg_idx);
^
...
error: the following build command crashed:
...
```
after:
```
expected argument after '--prefix'
access the help menu with 'zig build -h'
error: the following build command failed with exit code 1:
...
```
=> build_runner: fix oob access

lib/docs/main.js, lib/docs/wasm/Decl.zig, lib/docs/wasm/Walk.zig, lib/docs/wasm/main.zig
The old heuristic of checking only for the number of fields has the downside of classifying all opaque types, such as `std.c.FILE`, as "namespaces" rather than "types".
Before:
After:
=> Autodoc: only group structs under "namespaces"

lib/std/crypto/Certificate.zig
Comparing host name with dns name from certificate should be case insensitive.
I found a few domains (from the [cloudflare](https://radar.cloudflare.com/domains) list of top domains) for which tls.Client fails to connect. Error is:
```zig
error: TlsInitializationFailed
/home/ianic/Code/zig/lib/std/crypto/Certificate.zig:336:9: 0x126cddf in verifyHostName (http_get_std)
return error.CertificateHostMismatch;
^
/home/ianic/Code/zig/lib/std/crypto/tls/Client.zig:534:37: 0x1220f7f in init__anon_10280 (http_get_std)
try subject.verifyHostName(host);
^
/home/ianic/Code/zig/lib/std/http/Client.zig:1357:99: 0x1161f2b in connectTcp (http_get_std)
conn.data.tls_client.* = std.crypto.tls.Client.init(stream, client.ca_bundle, host) catch return error.TlsInitializationFailed;
^ …
```
=> crypto.Certificate: case insensitive host name check

lib/std/Build/Cache/Path.zig, lib/std/fs.zig, lib/std/fs/Dir.zig, lib/std/posix.zig, lib/std/testing.zig
https://ziglang.org/documentation/master/#Avoid-Redundant-Names-in-Fully-Qualified-Namespaces
As a follow-up to https://github.com/ziglang/zig/pull/20526#discussion_r1669307108
=> std.fs.Dir: Rename OpenDirOptions to OpenOptions

lib/std/Progress.zig
This removes the undefined behavior, but not the actual races.
Closes #20477
=> Progress: suppress tsan races

src/InternPool.zig, src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig
This fixes 2/5 of the remaining races before Sema and codegen/linking can be on separate threads.
=> InternPool: implement thread-safe allocated lists

lib/std/Progress.zig
Let's at least do aligned usize loads/stores where possible.
Follow up to  #20544
=> std.Progress: slightly better atomic memcpy

lib/std/posix.zig
`std.posix.poll` implementation incorrectly depends on `libc` on Windows, despite `std.os.windows.poll` existing. Issue similar to #9971, and resolved similar to #15225.
=> Use `std.os.windows.poll` for `std.posix.poll` implementation rather than `libc` dependency

lib/std/debug.zig, lib/std/dwarf.zig, lib/std/dwarf/call_frame.zig, lib/std/dwarf/expressions.zig
https://github.com/ziglang/zig/pull/20561 added `StackIterator.MemoryAccessor`, which is used to verify loads during FP-based unwinding.
This change updates the DWARF unwinder to use `MemoryAccessor` as well.
=> dwarf: use StackIterator.MemoryAccessor to check memory accesses

lib/compiler_rt/stack_probe.zig
@kubkon mentioned that `compiler_rt` symbols should have weak linkage, but that wasn't the case for `__chkstk_ms` which was causing conflicts during linking in some circumstances (specifically with linking object files from Rust sources). This PR switches `__chkstk_ms` to have weak linkage.
https://github.com/ziglang/zig/issues/15107
=> Update `__chkstk_ms` to have weak linkage

src/Air.zig, src/Compilation.zig, src/InternPool.zig, src/Sema.zig, src/Type.zig, src/Value.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/link/Coff.zig, src/link/Dwarf.zig, src/link/Elf/ZigObject.zig, src/link/MachO/ZigObject.zig, src/link/Plan9.zig, src/link/SpirV.zig, src/link/Wasm/ZigObject.zig, src/print_air.zig, src/print_value.zig
=> InternPool: fix more races blocking a separate codegen/linker thread

lib/std/crypto/tls/Client.zig
When calculating how much ciphertext from the stream can fit into user and internal buffers we should also take into account ciphertext data which are already in internal buffer.
Fixes: #15226
Tested with [this](https://github.com/ziglang/zig/issues/15226#issuecomment-2218809140). Using client with different read buffers until I, hopefully, understood what is happening.
Not relevant to the fix, but this [part](https://github.com/ziglang/zig/blob/95d9292a7a09ed883e65510ec054619747315c48/lib/std/crypto/tls/Client.zig#L988-L991) is still mystery to me. Why we don't use free_size in buf_cap calculation. Seems like rudiment from previous implementation without iovec.
=> tls.Client: fix out of bounds panic

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
Closes #17662.
To replicate two's-complement right shift behavior, we need to correct our sign-magnitude representation by one when right shifting out bits from a negative number.
=> Fix right shift on negative BigInts

lib/std/Target.zig, lib/std/coff.zig
See: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#machine-types
=> std: Add loongarch support for coff.

build.zig, lib/compiler/build_runner.zig, lib/compiler/objcopy.zig, lib/std/Build.zig, lib/std/Build/Cache.zig, lib/std/Build/Cache/Path.zig, lib/std/Build/Step.zig, lib/std/Build/Step/CheckFile.zig, lib/std/Build/Step/CheckObject.zig, lib/std/Build/Step/ConfigHeader.zig, lib/std/Build/Step/InstallDir.zig, lib/std/Build/Step/InstallFile.zig, lib/std/Build/Step/ObjCopy.zig, lib/std/Build/Step/Options.zig, lib/std/Build/Step/RemoveDir.zig, lib/std/Build/Step/Run.zig, lib/std/Build/Step/UpdateSourceFiles.zig, lib/std/Build/Step/WriteFile.zig, lib/std/Build/Watch.zig, lib/std/os/linux.zig, lib/std/posix.zig, lib/std/zig/Server.zig, src/Compilation.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/main.zig, test/tests.zig
```
--watch                      Continuously rebuild when source files are modified
--debounce <ms>              Delay before rebuilding after changed file detected
```
Uses the build system's perfect knowledge of all file system inputs to the pipeline to keep the build runner alive after completion, watching the minimal number of directories in order to trigger re-running only the dirty steps from the graph.
Default debounce time is 50ms but this is configurable. It helps prevent wasted rebuilds when source files are changed in rapid succession, for example when saving with vim it does not do an atomic rename into place but actually deletes the destination file before writing it again, causing a brief period of invalid state, which would cause a build failure without debouncing (it …
=> introduce file system watching features to the zig build system

src/main.zig
Resolves #20553 
It's a breaking change since now `zig build --debug-log smth -- arg` and `zig build -- arg --debug-log smth` have different meaning
=> Args including and after `--` get passed to build runner directly

src/Compilation.zig
oops, the src_path field of CObject is not relative to the module owner's root directory.
=> frontend: report correct paths for C objects

src/Sema.zig, src/Zcu.zig
This was causing failures in bootstrapping:
```
zig2.c(262301): error C2719: 'unnamed-parameter': formal parameter with requested alignment of 128 won't be aligned
```
=> zcu: fixup incorrect pass-by-value of Zcu

lib/std/Build/Step/Compile.zig, lib/zig.h, src/main.zig, stage1/zig.h
Commit messages have additional details.
- Fixup the atomic load implementation to only read memory, not write to it. This fixes a crash in `zig2` when compiling the compiler, during an atomic load from read-only memory.
- Pass the build graph's --zig-lib-dir along to child processes. This fixes zig2 not being able to find the installation directory. I believe in https://github.com/ziglang/zig/commit/a3c20dffaed77727494d34f7b4b03c0d10771270 this behaviour regressed.
Thanks to @jacobly0 for the help with the atomics!
=> Fixes for bootrapping with MSVC

lib/compiler/build_runner.zig, lib/std/Build.zig, lib/std/Build/Step.zig, lib/std/Build/Step/CheckFile.zig, lib/std/Build/Step/CheckObject.zig, lib/std/Build/Step/Compile.zig, lib/std/Build/Step/ConfigHeader.zig, lib/std/Build/Step/Fail.zig, lib/std/Build/Step/Fmt.zig, lib/std/Build/Step/InstallArtifact.zig, lib/std/Build/Step/InstallDir.zig, lib/std/Build/Step/InstallFile.zig, lib/std/Build/Step/ObjCopy.zig, lib/std/Build/Step/Options.zig, lib/std/Build/Step/RemoveDir.zig, lib/std/Build/Step/Run.zig, lib/std/Build/Step/TranslateC.zig, lib/std/Build/Step/UpdateSourceFiles.zig, lib/std/Build/Step/WriteFile.zig, lib/std/Progress.zig, lib/std/zig/Server.zig, src/Compilation.zig, src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/main.zig, test/standalone/cmakedefine/build.zig
```
$ zig build --watch -fincremental
Build Summary: 5/5 steps succeeded
install success
├─ install abc success
│  └─ zig build-lib abc Debug native success 183ms
└─ install abc success
└─ zig build-exe abc Debug native success 195ms
watching 67 directories, 2 processes
```
Closes #20600
---
This gets the build system fully ready for incremental compilation. The next step is to finish incremental compilation features in the frontend, as you can see from using the results of this PR:
```
andy@bark ~/t/abc [SIGINT]> ~/dev/zig/build-release/stage4/bin/zig build --watch -fincremental
Build Summary: 5/5 steps succeeded
install success
├─ install abc success
│  └─ zig build-lib abc Debug native success 1s
└─ install abc success
└─ zig build-exe abc Debug native success 1s
install
└─ install abc …
```
=> make zig compiler processes live across rebuilds

lib/std/zig/Ast.zig, lib/std/zig/AstGen.zig, lib/std/zig/tokenizer.zig, test/cases/compile_errors/invalid_unicode_escape.zig, test/compile_errors.zig
Fixes many error messages corresponding to invalid bytes displaying the wrong byte. Additionaly improves handling of UTF-8 in some places.
Fixes #13809
Fixes #17437
=> Fix invalid bytes error messages and improve utf-8 handling in tokenizer

lib/std/os/windows/kernel32.zig, lib/std/process.zig
Follow up to some comments made in #20592 (cc @T-727 and @castholm)
The main changes here are:
- More efficient method of ensuring well-formed WTF-8 output in `ArgIteratorWindows`
- Removal of `GetCommandLineW` call (and removal of the `std.os.windows.kernel32.GetCommandLineW` binding since it's no longer used anywhere)
- `[*:0]const u16` -> `[]const u16` in `ArgIteratorWindows.init` and therefore a removal of a `sliceTo` call
Details for each are in the commit messages, but here's some additional benchmarking info:
> [!NOTE]
> Don't take these benchmarks too seriously, they are not even close to emulating real-world scenarios, especially since they test generated command lines with (way) more than the maximum number of code units allowed by `CreateProcess` (32,766 technically due to the …
=> `ArgIteratorWindows`: Cleanup and some optimizations

lib/std/start.zig
Improves callMain in start.zig by switching on the main function's return type instead of doing a novemdecillion comparisons on the return type info.
=> Refactor callMain function in start.zig

lib/init/build.zig.zon
=> init: add a missing comment in build.zig.zon

lib/std/Thread.zig, lib/std/Thread/Condition.zig, lib/std/crypto/Certificate/Bundle.zig, lib/std/debug.zig, lib/std/io.zig, lib/std/os.zig, lib/std/os/windows.zig, lib/std/posix.zig, lib/std/process/Child.zig
Instead of calling the dynamically loaded kernel32.GetLastError, we can extract it from the TEB. As shown by [Wine](https://github.com/wine-mirror/wine/blob/34b1606019982b71818780bc84b76460f650af31/include/winternl.h#L439), the last error lives at offset 0x34 of the TEB in 32-bit Windows and at offset 0x68 in 64-bit Windows.
=> Better implementation of GetLastError.

doc/langref.html.in, doc/langref/test_pointer_arithmetic.zig, src/InternPool.zig, src/Sema.zig, src/Value.zig, test/behavior/pointers.zig, test/cases/compile_errors/invalid_pointer_arithmetic.zig
Fixes #1738
I don't know if this should introduce a dedicated AIR instruction instead of emitting two `int_from_ptr` and a `sub_wrap`. This is also missing safety just like the existing pointer arithmetic but maybe that can be done as part of #1918? Otherwise, if those two things aren't a blocking issue I think this is more or less complete. It seems to work at least.
I also put an emphasis on introducing a clear distinction between "pointer-integer arithmetic" and "pointer subtraction" (pointer-pointer arithmetic) because both of those are "pointer arithmetic" so "pointer arithmetic" on its own becomes ambiguous.
=> support pointer subtraction

lib/std/zig/Zir.zig, src/Air.zig, src/Compilation.zig, src/InternPool.zig, src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/main.zig
Moves `updateZirRefs` to be single-threaded for simplicity's sake. This makes it O(M) instead of O(N*M) where N is tracked insts and M is number of changed source files.
Also fix wrong union field access for declarations.
----
Next incremental compilation problem after this appears to be in the ELF linker:
```
error: thread 145898 panic: attempt to use null value
/home/andy/dev/zig/src/link/Elf/ZigObject.zig:702:89: 0x66e20c4 in lowerAnonDecl (zig)
const existing_alignment = elf_file.symbol(metadata.symbol_index).atom(elf_file).?.alignment;
^
/home/andy/dev/zig/src/link/Elf.zig:558:47: 0x66e27e6 in lowerAnonDecl (zig)
return self.zigObjectPtr().?.lowerAnonDecl(self, pt, decl_val, explicit_alignment, src_loc);
^
/home/andy/dev/zig/src/link.zig:656:85: 0x66e8300 in lowerAnonDecl (zig) …
```
=> frontend: fix updateZirRefs

src/Sema.zig, src/Type.zig, src/Value.zig, src/Zcu/PerThread.zig, src/arch/x86_64/CodeGen.zig, src/codegen.zig, src/codegen/spirv.zig, src/print_air.zig, src/print_value.zig
This eliminates one statically-reachable recursion loop between code generation backends and Sema. This is beneficial for optimizers (although I do not measure any performance improvement for this change), and for profilers.
Resolves: #15899
=> Type,Value: mark `ResolveStrat` parameter of type queries as `comptime`

lib/compiler/aro_translate_c.zig, lib/compiler/aro_translate_c/ast.zig, src/translate_c.zig, test/cases/run_translated_c/extern_typedef_variables_in_functions.c
- Added special handling for translating C extern variables declared within scoped blocks:
The following:
``` C
static int func(void)
{
typedef int test_type_t;
extern const test_type_t ev;
return ev + 2;
}
```
Used to translate to:
``` Zig
extern const ev: test_type_t;
pub fn func() callconv(.C) c_int {
const test_type_t = c_int;
_ = &test_type_t;
return ev + @as(c_int, 2);
}
```
Creating compile errors as `test_type_t` is not in global scope.
It now translates to:
``` Zig
pub fn func() callconv(.C) c_int {
const test_type_t = c_int;
_ = &test_type_t;
const ExternLocal_ev = struct {
extern const ev: test_type_t;
};
_ = &ExternLocal_ev;
return ExternLocal_ev.ev + @as(c_int, 2);
}
```
Extern variables declared at the global scope are unaffected.
- Added …
=> Properly Translate C Extern Variables Declared Within Scoped Blocks

src/Sema.zig, src/Zcu/PerThread.zig
this was meant to be two commits but i accidentally pushed one straight to master, oh well
=> Zcu: updateZirRefs typo

build.zig
Allows to enable Valgrind integrations in release builds, sometimes useful in combination with tooling.
=> build.zig: expose valgrind flag

lib/std/fmt.zig
Hi guys,
In this changelist I'm suggesting to improve upon the existing Format Options parsing to make it a little more flexible, closer actually to the defaults that C programmers are used to and that most languages implement. To me, it follows the following principles from the Zen:
* _Incremental improvements_,
* _Edge cases matter_,
* _Minimize energy spent on coding style_,
* _Together we serve end users_.
Padding with `0` is very common for hexadecimal output: in many languages `04x` left-pads with zeroes, but in Zig `{x:04}` left-pads with blanks. However for most fill characters like zero, adding an alignment specifier is actually not necessary (it's only necessary for `1`-`9` and `.`)
The new behaviour is non-breaking (e.g current unit tests pass) and feels more natural and closer …
=> format: do not force user to provide an alignment field when it's not necessary

src/arch/wasm/CodeGen.zig
While working on backend, I did not like the fact that `finishAir` cannot digest `.stack` values, this results in `CodeGen.zig` frequently (and sometimes unnecessary) calling `toLocal` to convert them into locals.
Also `fn typeToValtype` was geared towards `callconv(.C)` which is strange and not documented, I changed it to `.auto`, because it is mostly used in this context. Note: this change is required for `finishAir` commit to work properly.
You can find additional thoughts and consideration inside commit messages.
=> stage2-wasm: finishAir enhancement

lib/std/debug.zig, lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig
To facilitate https://github.com/ziglang/zig/issues/1840, this commit slims `std.windows.kernel32` to only have the functions needed by the standard library. Since this will break projects that relied on these, I offer these solutions:
- Make an argument as to why certain functions should be added back in. Note that they may just be wrappers around `ntdll` APIs, which would go against https://github.com/ziglang/zig/issues/1840.
If necessary I'll add them back in *and* make wrappers in `std.windows` for it.
- Maintain your own list of APIs. This is the option taken by bun, where they wrap functions with tracing.
- Use `zigwin32`.
I've also added `TODO` comments that specify which functions can be reimplemented using `ntdll` APIs in the future.
Other changes:
- Group functions into groups …
=> Windows: Rework kernel32 apis 

lib/std/mem.zig
I was working on some serialization code, and noticed that the `.Float` and `.Bool` cases weren't handled in `byteSwapAllFields`. I moved the scalar cases into `byteSwap` and call them from `byteSwapAllFields`.
=> mem: handle Float and Bool cases in byteSwapAllFields

CMakeLists.txt, bootstrap.c, build.zig, src/Compilation.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/codegen.zig, src/codegen/llvm.zig, src/dev.zig, src/link.zig, src/link/Coff/lld.zig, src/link/Elf.zig, src/link/Wasm.zig, src/main.zig, src/mingw.zig, stage1/config.zig.in
This allows specifying a development environment for reducing compile times while building the compiler, each targeted at developing a specific part of the compiler.  The legacy options `build_options.only_c` and `build_options.only_core_functionality` have been replaced with the new system.  This system allows easily specifying new optional features and new environments independently.
```
$ time zig build -Dno-lib -Duse-llvm=false -Ddev=full
real	0m9.462s
user	0m13.092s
sys	0m1.371s
$ time zig build -Dno-lib -Duse-llvm=false -Ddev=x86_64-linux
real	0m5.578s
user	0m7.295s
sys	0m0.860s
$ zig-out/bin/zig build
thread 292207 panic: Development environment x86_64-linux does not support feature build_command
```
=> dev: introduce dev environments that enable compiler feature sets

src/Compilation.zig, src/Zcu.zig, src/codegen/llvm.zig, src/dev.zig, src/link.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/NvPtx.zig, src/link/Wasm.zig
I didn't notice there were `*LlvmObject` fields and other sus things in the linkers.
```
$ zig build -Dno-lib -Duse-llvm=false -Ddev=full
real	0m9.431s
user	0m13.153s
sys	0m1.196s
$ zig build -Dno-lib -Duse-llvm=false -Ddev=x86_64-linux
real	0m4.635s
user	0m6.017s
sys	0m0.740s
```
=> dev: fix llvm backend checks

lib/std/Build.zig, lib/std/Build/Step/Options.zig, lib/std/Build/Step/Run.zig, lib/std/fmt.zig, lib/std/process.zig, lib/std/zig.zig, lib/std/zig/Server.zig, src/Compilation.zig, src/Package/Fetch.zig, src/Package/Manifest.zig, src/link.zig, src/main.zig, test/incremental/hello, tools/incr-check.zig
This is a tiny component of an overall testing strategy. This provides the ability to have compact test cases that can be run with a single command which are then tested in isolation, aiding reproducibility. For example, I have included one test case along with this tool:
```
#target=x86_64-linux
#update=initial version
#file=main.zig
try std.io.getStdOut().writeAll("good morning\n");
}
#expect_stdout="good morning\n"
#update=change the string
#file=main.zig
try std.io.getStdOut().writeAll("おはようございます\n");
}
#expect_stdout="おはようございます\n"
```
You can run it like this:
```
$ stage3/bin/zig run ../tools/incr-check.zig -- stage4/bin/zig ../test/incremental/hello 
error: update 'change the string' …
```
=> introduce a new tool for testing incremental compilation

src/Air.zig, src/Sema.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/link/SpirV/lower_invocation_globals.zig, src/link/Wasm.zig, src/link/Wasm/Atom.zig, src/link/Wasm/Object.zig, src/link/Wasm/Symbol.zig, src/link/Wasm/ZigObject.zig
I've been reading some parts of the source code, because I wanted to know if CPython can be compiled with `zig cc -Wall -Werror -Wextra -fsanitize=undefined` (`address` did not work for some reason). And I found a typo in the source. Then I executed `codespell` and here are the results :)
What a ride! 😆
=> Fix typos in code comments in `src/`

src/Sema.zig, test/cases/compile_errors/call_from_double_ptr.zig
Fixes the error message and adds a note when an attempt is made to invoke a method on a double pointer. Consider the following code:
```zig
const S = struct {
fn b() void {}
};
export fn entry(a: **S) void {
_ = a.b();
}
```
Before:
```shell
install
└─ install test_zig
└─ zig build-exe test_zig Debug native 2 errors
src/main.zig:6:10: error: no field or member function named 'b' in '*main.S'
_ = a.b();
~^~
```
After:
```shell
install
└─ install test_zig
└─ zig build-exe test_zig Debug native 2 errors
src/main.zig:6:10: error: no field or member function named 'b' in '*main.S'
_ = a.b();
~^~
src/main.zig:6:10: note: method invocation only supports up to one level of implicit pointer dereferencing
src/main.zig:6:10: note: use '.*' to dereference pointer
```
<details>
<Summary>Original …
=> fix: Add error notes for method calls on double pointers

src/Sema.zig, test/cases/compile_errors/invalid_array_assignment_with_valid_elems.zig
Prevents a misleading error note from being printed when an attempt is made to assign one array to another with coercible (but different!) element types. Taking the example from the #19541:
```zig
test {
const a = [_]u16{ 1, 2, 3 };
const b: [3]i32 = a;
try std.testing.expectEqual([_]i32{ 1, 2, 3 }, b);
}
```
Any `u16` value could indeed be represented by an `i32`, however the compiler's notes indicate otherwise:
Before:
```shell
❯ zig build test
test
└─ run test
└─ zig test Debug native 1 errors
src/main.zig:21:23: error: expected type '[3]i32', found '[3]u16'
const b: [3]i32 = a;
^
src/main.zig:21:23: note: array element type 'u16' cannot cast into array element type 'i32'
src/main.zig:21:23: note: signed 32-bit int cannot represent all possible unsigned …
```
=> fix: remove misleading error note for failed array assignments

lib/std/debug.zig, src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, src/codegen/llvm/ir.zig, test/cases/llvm/debug_types.zig
Zig previously put the debug entries for types, functions and variables at top-level into the file scope. This meant that most of these declarations could be accessed from a debugger expression only by their fully qualified names, which in turn are hard to use because C-style debuggers try to interpret the `.`s in them as member access. Getting around that in GDB required you to enclose the FQN in single-quotes (which has really bad discoverability) and was, as far as I can tell, impossible in LLDB.
This PR nests that data so that it can also be accessed from C++ debuggers with the regular `::` namespace operator. LLDB still handles variables badly and sometimes takes two tries for other declarations, but hopefully I can get a patch for that upstream.
All of that not only improves the …
=> llvm: Nest debug info correctly

src/InternPool.zig, test/behavior/extern.zig
=> ip: use `getExternFunc` in `getCoerced`

lib/std/mem.zig
I noticed that std.mem.reverse wasn't getting optimized to use SIMD while optimizing a program a while ago, and decided to make my own faster implementation. After refining it a bit this is my best effort at making it as efficient and readable as possible. For benchmarks see [this repo](https://github.com/jonathanHallstrom/array_reversing/). Any feedback is very welcome
=> std.mem.reverse: Improve performance

lib/std/crypto/tls/Client.zig
On decryption tls client should remove zero byte padding after the content type field. This padding is rarely used, the only site (from the list of top domains) that I found using it is `tutanota.com`.
From [RFC](https://datatracker.ietf.org/doc/html/rfc8446#section-5.4):
> All encrypted TLS records can be padded.
> Padding is a string of zero-valued bytes appended to the ContentType
field before encryption.
> the receiving implementation scans the field from the end toward the
beginning until it finds a non-zero octet. This non-zero octet is the content type of the message.
Currently we can't connect to that site:
```
$ zig run main.zig -- tutanota.com
error: TlsInitializationFailed
/usr/local/zig/zig-linux-x86_64-0.14.0-dev.208+854e86c56/lib/std/crypto/tls/Client.zig:476:45: 0x121fbed …
```
=> tls.Client: implement record padding

lib/compiler/aro_translate_c/ast.zig, lib/std/zig/Ast.zig, lib/std/zig/Parse.zig, lib/std/zig/parser_test.zig, lib/std/zig/render.zig, test/cases/compile_errors/disallow_coercion_from_non-null-terminated_pointer_to_null-terminated_pointer.zig, test/cases/compile_errors/incompatible_sentinels.zig, test/cases/compile_errors/issue_4207_coerce_from_non-terminated-slice_to_terminated-pointer.zig, test/cases/compile_errors/using_an_unknown_len_ptr_type_instead_of_array.zig
Fixes #19440
Rework of #20323 
As suggested in my original PR, I dug into the parser for this issue and believe I have diagnosed the issue. With the following input...
```zig
test {
_ = .{}[*0];
}
```
...the brackets would first be parsed as an `.array_access` on `.{}`, and then *reused* [here](https://github.com/ziglang/zig/blob/04e08ea883f94d2de7a91daee72ccc9613a18a43/lib/std/zig/Parse.zig#L3529) to allow `[*0]` to be parsed as a `.ptr_type_aligned`. This "sharing" of  the left bracket then caused the odd behavior with zig fmt. I added a check in the parsing code to disambiguate the `.ptr_type_aligned` and `.ptr_type` cases, and also updated `Ast.firstToken()` to reflect this change.
=> fix(fmt): pointer type syntax to index (take 2)

test/standalone/build.zig.zon, test/standalone/run_output_caching/build.zig, test/standalone/run_output_caching/main.zig
Supersedes #19194 since the underlying issue has already been fixed by #19826.
This just adds a standalone test that executes run steps with and without `std.Build.Step.Run.has_side_effects` and tests whether or not caching has occurred. If this kind of test is undesired, I can adjust it to only check for the existence of the output file since that should be enough to reproduce the issue. I though that a test that checks for caching could be useful :shrug:
closes #18281
=> test: check output file caching of run steps with side-effects

lib/std/Build/Step/Compile.zig
`PKG_CONFIG` environment variable is used to override path to
pkg-config executable, for example when it's name is prepended by
target triple for cross-compilation purposes:
```
PKG_CONFIG=/usr/bin/aarch64-unknown-linux-gnu-pkgconf zig build
```
=> zig build: respect PKG_CONFIG environment variable

lib/std/os/linux.zig
`std.os.linux.sched_setaffinity()` does not compile on x86_64, `std.os.errno` is missing:
```zig
const set = std.mem.zeroes(std.os.linux.cpu_set_t);
try std.os.linux.sched_setaffinity(0, &set);
}
```
```sh
$ ~/zig-linux-x86_64-0.14.0-dev.91+a154d8da8/zig run main.zig
/home/leki/zig-linux-x86_64-0.14.0-dev.91+a154d8da8/lib/std/os/linux.zig:1894:19: error: root struct of file 'os' has no member named 'errno'
switch (std.os.errno(rc)) {
~~~~~~^~~~~~
/home/leki/zig-linux-x86_64-0.14.0-dev.91+a154d8da8/lib/std/os.zig:1:1: note: struct declared here
//! This file contains thin wrappers around OS-specific APIs, with these
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
main: main.zig:5:21
callMain: …
```
=> std.os.linux: sched_setaffinity fix

doc/langref.html.in
Attempts to resolve https://github.com/ziglang/zig/issues/19123
This is my first time contributing, open to any and all feedback!
The changes to the docs look like this (the sentence beginning "Integers captured..." was added):
I tested it by running `zig build langref` and opening `zig-out/doc/langref.html` in Firefox. I also tested the link to non-exhaustive enum and it does jump to it.
=> improve @enumFromInt doc

test/standalone/run_output_caching/build.zig
how was this not caught in CI?
change happened here: abf895595189eb45df8c97f4029c58976815b450
=> test: update `make` functions to use `MakeOptions`

lib/std/start.zig
This is problematic for PIE. There's nothing but luck preventing the accesses to this global variable from requiring relocations. I've observed this being an issue on MIPS and PowerPC personally, but others may be affected.
=> `start`: Avoid going through the argc_argv_ptr global variable

test/behavior/optional.zig
This test is flaky in some way or may have been affected by #20718. I'll have it fixed by the next RISC-V backend upstream. I believe it's the reason for the master branch CI failures.
=> riscv: disable failing test

lib/std/c.zig, lib/std/os/linux.zig, lib/std/posix.zig, lib/std/process/Child.zig
std.process.Child is a nice abstraction, and it could be nicer if it can set the process group ID, which is useful if we want to kill that process and all its descendants.
Please let me know if backward compatibility in Child.kill's signature should be broken, or a `killpg` function should be added instead.
Slightly relevant: should Child.kill let caller choose the signal?
=> Allow setting PGID in std.process.Child.spawn

lib/std/crypto/chacha20.zig
=> Fix function definition: ChaCha20With64BitNonce counter is u64

lib/std/start.zig
I should note that I haven't tested any of these as there are various other blocking issues for these ports to work. But the commits are fairly straightforward adaptations of this musl code:
* https://git.musl-libc.org/cgit/musl/tree/arch/loongarch64/crt_arch.h
* https://git.musl-libc.org/cgit/musl/tree/arch/m68k/crt_arch.h
* https://git.musl-libc.org/cgit/musl/tree/arch/s390x/crt_arch.h
=> `start`: Add startup code for loongarch64, m68k, and s390x

lib/docs/index.html
=> autodoc: Preserve whitespace in inline code spans

lib/compiler/build_runner.zig, lib/compiler/test_runner.zig, lib/std/Build.zig, lib/std/Build/Step/Run.zig, lib/std/Random/ziggurat.zig, lib/std/hash_map.zig, lib/std/heap/arena_allocator.zig, lib/std/math/big/rational.zig, lib/std/os/linux/IoUring.zig, lib/std/priority_dequeue.zig, lib/std/sort.zig, lib/std/testing.zig, src/main.zig
=> add std.testing.random_seed

lib/std/posix.zig, test/standalone/stack_iterator/build.zig, test/standalone/stack_iterator/unwind_freestanding.zig
PR https://github.com/ziglang/zig/pull/20679 ("std.c reorganization") switched feature-detection code to use `T != void` checks in place of `@hasDecl`.  However, the default std.posix.system struct (used by freestanding targets) is empty, so compile-time feature detection against symbols in there (specifically `std.posix.system.ucontext_t` in this case), fail at compile time.
This PR adds a void ucontext_t into the std.posix.system default.  While I'm confident this fixes the particular problem, it may not be the right approach (it seems like this struct will eventually have to be padded out with a lot of void symbols).  I'm not sure if deeper fixes to std.debug are in order, or something else entirely.
This PR also adds pseudo-"freestanding" variation of the existing StackIterator …
=> Default std.posix.system.ucontext_t is void

lib/std/Progress.zig, lib/std/debug.zig, lib/std/posix.zig, lib/std/posix/test.zig, lib/std/start.zig, src/crash_report.zig
See commit messages for justification.
Closes #20704.
=> `std.posix`: Make `sigaction()` infallible

lib/std/Build/Step/Run.zig
https://github.com/bytecodealliance/wasmtime/issues/7384
=> `std.Build.Step.Run`: Fix invocation syntax for Wasmtime 14+.

lib/std/crypto/bcrypt.zig, lib/std/crypto/poly1305.zig
Some of these issues were mentioned in #20505
=> Fix compilation issues in crypto.bcrypt and poly1305

lib/compiler_rt/ceil.zig, lib/compiler_rt/common.zig, lib/compiler_rt/cos.zig, lib/compiler_rt/exp.zig, lib/compiler_rt/exp2.zig, lib/compiler_rt/floor.zig, lib/compiler_rt/round.zig, lib/compiler_rt/sin.zig, lib/compiler_rt/sincos.zig, lib/compiler_rt/tan.zig, lib/compiler_rt/trunc.zig, lib/compiler_rt/udivmodei4.zig, src/arch/wasm/CodeGen.zig, test/behavior/saturating_arithmetic.zig
I disabled one test, which was also disabled on `stage2_c`. Handling big ints > 128 bits, is not the first priority for wasm backend right now.
Next step is to be able to generate an archive file to test the possibility of non depending on LLVM for compiler_rt.
=> stage2-wasm: pass compiler_rt test suite

lib/std/Thread.zig, lib/std/debug.zig
PR [19271](https://github.com/ziglang/zig/pull/19271) added some static function implementations from kernel32, but some parts of the library still used the dynamically loaded versions.
=> Replace some dynamic functions with static ones.

lib/std/start.zig
Nothing bitness-specific about this startup code.
=> `start`: Handle loongarch32 together with loongarch64.

lib/std/os/linux/start_pie.zig
As with #20733, this is untested, but straightforwardly adapted from musl:
* https://git.musl-libc.org/cgit/musl/tree/arch/loongarch64/crt_arch.h
* https://git.musl-libc.org/cgit/musl/tree/arch/m68k/crt_arch.h
* https://git.musl-libc.org/cgit/musl/tree/arch/s390x/crt_arch.h
=> `std.os.linux.start_pie`: Implement `getDynamicSymbol()` for loongarch64, m68k, and s390x

lib/std/coff.zig
Sources:
* https://learn.microsoft.com/en-us/windows/win32/sysinfo/image-file-machine-constants
* https://github.com/wine-mirror/wine/blob/88a28aa5757ae74d9997b470d70216f10974247f/include/winnt.h#L2720-L2758
=> `std.coff`: Add missing entries to MachineType.

src/zig_llvm.cpp
The `TargetOptions` default constructor initializes all `bool`s to `false`, yet clang defaults to setting this option to `true`.  Since recent glibc versions on linux do not appear to support this being set to `false`, just changing the default for now unless a use case for making it configurable is found.
=> llvm: force `TargetOptions.UseInitArray` to `true`

src/main.zig
When all compiler inputs are invalid paths, there could be errors yet no valid file system inputs.
Closes #20713
=> main: avoid sending an empty file system inputs message

lib/std/Build/Cache.zig, src/Compilation.zig, src/main.zig
Partially addresses #9188.
Closes #20782.
=> build compiler_rt and fuzzer in parallel; fix false positive cache hits

lib/std/math.zig, lib/std/simd.zig, test/behavior/vector.zig
Closes #12012
As already commented in https://github.com/ziglang/zig/issues/12012#issuecomment-2246375845 this tests are no longer regressed and can be re-enabled.
=> aarch64: reenable tests that are no longer regressed

lib/std/start.zig
=> `start`: Harden against program interpreters that don't adhere fully to the ABI

lib/compiler/build_runner.zig, lib/compiler/test_runner.zig, lib/fuzzer.zig, lib/std/Build.zig, lib/std/Build/Fuzz.zig, lib/std/Build/Step/Compile.zig, lib/std/Build/Step/Run.zig, lib/std/io/test.zig, lib/std/testing.zig, lib/std/zig/Client.zig, lib/std/zig/Server.zig, src/Compilation.zig, src/codegen/llvm.zig, src/link/Elf.zig, src/main.zig
Adds a `--fuzz` CLI option to the build runner. When this is used it rebuilds any unit test binaries which contained at least one fuzz test with `-ffuzz` and then tells it to start fuzzing, which does in-process fuzzing.
Adds `std.testing.fuzzInput`, which is how unit tests mark themselves as fuzz tests.
This contains only a rudimentary implementation of fuzzer logic, really just some early, early experiments, but already it makes this test case fail in 65 milliseconds on my machine:
```zig
test "fuzz example" {
const input_bytes = std.testing.fuzzInput(.{});
try std.testing.expect(!std.mem.eql(u8, "canyoufindme", input_bytes));
}
```
```
andy@bark ~/t/abc [1]> ~/dev/zig/build-release/stage4/bin/zig build test --fuzz --debug-rt
test
└─ run test failure …
```
=> integrate fuzz testing into the build system

src/main.zig
Looks like an accidental effect introduced in #20750.
Had me questioning reality for a bit before I realized what was going on:
```
❯ zig run generate_linux_syscalls.zig -- $(which zig) /home/alexrp/Source/linux
error: NotDir
/home/alexrp/Source/zig/lib/std/posix.zig:1783:24: 0x108024f in openatZ (generate_linux_syscalls)
.NOTDIR => return error.NotDir,
^
/home/alexrp/Source/zig/lib/std/fs/Dir.zig:1565:21: 0x1090736 in openDirFlagsZ (generate_linux_syscalls)
else => |e| return e,
^
/home/alexrp/Source/zig/lib/std/fs/Dir.zig:1529:5: 0x107fef2 in openDirZ (generate_linux_syscalls)
return self.openDirFlagsZ(sub_path_c, symlink_flags);
^
/home/alexrp/Source/zig/lib/std/fs/Dir.zig:1473:5: 0x104cace in openDir (generate_linux_syscalls)
return self.openDirZ(&sub_path_c, args);
^ …
```
=> `main`: Don't pass `--seed` for `zig run`.

lib/std/zig/target.zig
This was the only missing "proper" architecture, I think. This function also needs to be updated to handle N32 on MIPS and x32 on x86-64, but that's a problem for another day (we don't have musl-specific `std.Target.Abi` tags for these).
=> `std.zig.target`: Handle m68k in muslArchName().

lib/zig.h, stage1/zig.h
Fixes missing definition errors hit in bootstrapping with MSVC.
These should have been in https://github.com/ziglang/zig/pull/20620, but I missed the pointer versions as they weren't used yet.
=> zig.h: fixup msvc pointer atomic load definitions

src/Compilation.zig
Makes adding `--debug-rt` correctly invalidate the cache for compiler_rt and libfuzzer.
=> frontend: add missed cache hash on --debug-rt

lib/std/os/linux.zig
=> std.os.linux: Fix default value for perf_event_attr.clockid field.

lib/compiler/aro_translate_c.zig, src/translate_c.zig, test/cases/run_translated_c/extern_typedef_variables_in_functions.c
=> translate-c: Use mangled name for local extern in condition/loop

src/Compilation.zig, src/link.zig, src/link/Coff.zig, src/link/Coff/lld.zig, src/link/Elf.zig, src/link/Wasm.zig, src/main.zig
Enable it by default when building Zig code in release modes.
This contributes to #9432, but does not fully close it, as we still need to add support for this in the self-hosted linker.
I tested this manually by building a DLL twice without the patch and verifying that they differed in the PE header, then built a DLL twice after the patch and verified that they were 100% identical.
=> link: Accept `-Brepro` linker option and pass it to LLD.

lib/std/os/uefi/protocol.zig, lib/std/os/uefi/protocol/serial_io.zig
the purpose of this PR is to introduce the Serial IO Protocol interface as described in the [UEFI Specification](https://uefi.org/specs/UEFI/2.10/12_Protocols_Console_Support.html?highlight=const%20efi_guid#serial-i-o-protocol)
closes #16713 
tested by running `zig test lib/std/std.zig --zig-lib-dir lib`
=> feat(std.os.uefi.protocol): add Serial IO

src/link/Coff.zig
Just keep things simple and zero the timestamp. It's not obvious that there's any real benefit to adding complexity and harming performance by computing a hash of the whole file for the timestamp value.
See:
* https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#general-concepts
* https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#debug-type
In the future, we should at least add an empty `IMAGE_DEBUG_TYPE_REPRO` entry to the debug data directory for this case, but I didn't want to do too much surgery right now since it's early days for COFF support in the self-hosted linker.
=> `link.Coff`: Basic support for `/Brepro` in the self-hosted linker.

lib/compiler/aro/aro/Attribute.zig, lib/compiler/aro/aro/Compilation.zig, lib/compiler/aro/aro/target.zig, lib/compiler_rt/clear_cache.zig, lib/compiler_rt/common.zig, lib/std/Target.zig, lib/std/Thread.zig, lib/std/atomic.zig, lib/std/c.zig, lib/std/zig/LibCDirs.zig, lib/std/zig/system/darwin/macos.zig, lib/std/zig/system/linux.zig, lib/std/zig/system/windows.zig, src/Sema.zig, src/Type.zig, src/Zcu.zig, src/codegen/llvm.zig, src/mingw.zig, src/target.zig, test/behavior/align.zig, test/behavior/atomics.zig, test/behavior/vector.zig, test/llvm_targets.zig
This is a misfeature that we inherited from LLVM:
* https://reviews.llvm.org/D61259
* https://reviews.llvm.org/D61939
(`aarch64_32` and `arm64_32` are equivalent.)
I truly have no idea why this triple passed review in LLVM. It is, to date, the *only* tag in the architecture component that is not, in fact, an architecture. In reality, it is just an ILP32 ABI for AArch64 (*not* AArch32).
The triples that use `aarch64_32` look like `aarch64_32-apple-watchos`. Yes, that triple is exactly what you think; it has no ABI component. They really, seriously did this.
Since only Apple could come up with silliness like this, it should come as no surprise that no one else uses `aarch64_32`. Later on, a GNU ILP32 ABI for AArch64 was developed, and partial support was added to LLVM:
* …
=> `std.Target.Cpu.Arch`: Remove the `aarch64_32` tag.

lib/std/Build/Step/Compile.zig, lib/std/fs.zig, lib/std/fs/Dir.zig
Deprecates std.fs.atomicSymLink and removes the allocator requirement from the new std.fs.Dir.atomicSymLink. Replaces the two usages of this within std.
I did not include the TODOs from the original code that were based off of `switch (err) { ..., else => return err }` not having correct inference that cases handled in `...` are impossible in the error union return type because these are not specified in many places but I can add them back if wanted.
Tested locally on Windows.
=> std.fs.Dir: Refactor atomicSymLink from std.fs

lib/std/mem.zig
Fixes #20409 
Apologies, I messed up the branch on my previous pull request (#20440).
=> std.mem.readVarInt: fix for 8-bits and below (Reloaded)

lib/compiler/build_runner.zig, lib/std/Build/Watch.zig, lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig
Closes #20598.
~This initial implementation has the limit of 64 directories due to the usage of WaitForMultipleObjects. If merged, a follow up issue should be created to track overcoming that limitation.~
Using IO completion ports instead of WaitForMultipleObjects, I am able to observe more than 64 directories at once.
BTW First time contributing, not very experienced with contributing on GitHub in general, but I love Zig. And I saw this issue and thought it would be a good learning opportunity for me.
=> Build Runner: Initial Implementation for File System Watching on Windows

lib/std/c.zig, lib/std/meta.zig, lib/std/os/uefi/protocol/serial_io.zig, lib/std/packed_int_array.zig
Comments throughout the codebase start with a space. This commit corrects comments that do not adhere to this norm.
=> chore: correct non-standard comments.

lib/std/posix.zig
Contributes to #15607
~~Although the case is not handled in `openatWasi` (as I could not get a
working wasi environment to test the change) I have added a FIXME
addressing it and linking to the issue.~~
Edit: Handled case in openatWasi too
=> std.posix: handle INVAL in openZ, openatZ and openatWasi

src/Compilation.zig
We advertise reproducible builds for release modes, so let's help users achieve that in C/C++ code. Users can still override this manually if they really want.
=> `compiler`: Enable -Werror=date-time for C/C++ code in release builds

src/musl.zig
* https://git.musl-libc.org/cgit/musl/tree/configure#n358
* https://clang.llvm.org/docs/UsersManual.html#cmdoption-fexcess-precision
* https://clang.llvm.org/docs/UsersManual.html#cmdoption-f-no-rounding-math
=> `musl`: Align `CFLAGS` with upstream

lib/std/start.zig
These are required for the changes in #20823 to actually work.
=> `start`: A handful of MIPS fixes

lib/c.zig
Accidentally deleted #20809 earlier. :facepalm:
=> `c`: Handle armeb and thumbeb in clone().

lib/compiler/aro_translate_c.zig, test/cases/translate_c/_Static_assert.c
Note: this only ignores `_Static_assert` during translation, which matches the behavior of clang-based `translate-c`. The `_Static_assert` conditions are validated during parsing and any failures result in an error.
Previously we were not rendering errors and exiting with a non-zero status. I wasn't sure how to add a test for this to the existing translate-c tests but I tested manually with:
`./stage3/bin/zig run -fno-clang -fno-llvm -fno-lld --dep aro -Mroot=../lib/compiler/aro_translate_c.zig -Maro=../lib/compiler/aro/aro.zig -- ~/test.c`
test.c contents:
```c
_Static_assert(1 == 2, "Bad comparison");
```
Output:
```
/Users/ehaas/test.c:1:1: error: static assertion failed "Bad comparison"
_Static_assert(1 == 2, "Bad comparison");
^
```
=> Aro translate c: Render error diagnostics properly and ignore _Static_assert decls during translation

lib/std/os/windows/kernel32.zig
In https://github.com/ziglang/zig/pull/19641 (cc @The-King-of-Toasters), this binding changed from `[*]u16` to `LPWSTR` which made it a sentinel-terminated pointer. This introduced a compile error in the `std.os.windows.GetModuleFileNameW` wrapper since it takes a `[*]u16` pointer. This commit changes the binding back to what it was before instead of introducing a breaking change to `std.os.windows.GetModuleFileNameW`
Related: https://github.com/ziglang/zig/issues/20858
---
Note: Neither `std.os.windows.kernel32.GetModuleFileNameW` nor `std.os.windows.GetModuleFileNameW` is used by Zig internally (instead, `std.os.windows.kernel32.GetModuleFileNameExW` is used in `std.debug`). So an alternate fix here might be to just delete the binding and the wrapper in `std.os.windows`.
=> Fix compile error due to GetModuleFileNameW binding change

doc/langref/test_pointer_coerce_const_optional.zig
This test was originally introduced in 5f38d6e2e97829ed74f06a96b5d07a2c68516063, where it looked like this:
```zig
test "cast *[1][*]const u8 to [*]const ?[*]const u8" {
const window_name = [1][*]const u8{c"window name"};
const x: [*]const ?[*]const u8 = &window_name;
assert(mem.eql(u8, std.cstr.toSliceConst(x[0].?), "window name"));
}
```
Over the years, this has become more and more obfuscated, to the point that the verbosity of the `expect` call overshadows the point of the example. This commit intends to update this test to match the spirit of the original version of the test, while shedding the obfuscation.
=> langref: Make pointer_coerce_const_optional test less obfuscated

lib/std/start.zig
Tested by observing `__sanitizer_cov_8bit_counters_init` and `__sanitizer_cov_pcs_init` being called in a libc-less build.
=> start code: implement __init_array_start, __init_array_end

src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/LinkerDefined.zig, src/link/Elf/Object.zig, src/link/Elf/SharedObject.zig, src/link/Elf/Symbol.zig, src/link/Elf/ZigObject.zig, src/link/Elf/eh_frame.zig, src/link/Elf/file.zig, src/link/Elf/gc.zig, src/link/Elf/merge_section.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig, src/link/Elf/thunks.zig, src/link/MachO/InternalObject.zig, src/link/MachO/ZigObject.zig, test/link/elf.zig
Moves ownership of all resources into owning objects except symbols - this will come in a subsequent PR.
=> elf: clean up resource ownership in the linker

lib/std/Target.zig
See: https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html#_program_interpreter_path
=> std: set standard dynamic linker path for loongarch64 on linux.

lib/compiler/aro_translate_c.zig, test/cases/translate_c/atomic types.c, test/cases/translate_c/empty declaration.c, test/cases/translate_c/function prototype with parenthesis.c, test/cases/translate_c/noreturn attribute.c, test/cases/translate_c/simple function prototypes.c, test/cases/translate_c/struct prototype used in func.c, test/translate_c.zig
This PR attempts to make aro-translate-c more useful by removing some common panics and improving type translation. See individual commits for details; a quick summary:
- Statement translation is not supported, so emit function definitions as extern prototypes instead of crashing
- Global variable declarations are not supported, so emit `@compileError` for them instead.
- Add support for pointer and array types
- Add basic support for typedef translation
- Improve record translation - most record types should be translatable now (bitfields, `_Atomic` fields, and flexible array members currently not supported)
- Translate enum types
- Move some tests to the manifest format instead of `test/translate_c.zig`
=> aro-translate-c improvements

lib/std/math/complex/abs.zig, lib/std/math/complex/acos.zig, lib/std/math/complex/acosh.zig, lib/std/math/complex/arg.zig, lib/std/math/complex/asin.zig, lib/std/math/complex/asinh.zig, lib/std/math/complex/atan.zig, lib/std/math/complex/atanh.zig, lib/std/math/complex/conj.zig, lib/std/math/complex/cos.zig, lib/std/math/complex/cosh.zig, lib/std/math/complex/log.zig, lib/std/math/complex/pow.zig, lib/std/math/complex/proj.zig, lib/std/math/complex/sin.zig, lib/std/math/complex/sinh.zig, lib/std/math/complex/sqrt.zig, lib/std/math/complex/tan.zig, lib/std/math/complex/tanh.zig
Fixes a few translation errors in the initial port and adds some fixes since changed upstream.
See #19476.
---
I have tested this predominantly using a simple fuzzing setup, comparing the results of zig vs musl (which is the primary source). Code for this can be seen at the bottom of this PR.
```
zig build-exe main.zig complex.c -target x86_64-linux-musl -lc --zig-lib-dir ../lib -O ReleaseSafe
```
For values in the range [0, 1) I'e fuzzed ~1 billion results with all matching to a small epsilon.
For larger values there are a few differences noted below, however this encompasses only ~5% of values max and generally the difference is small.
There are some known failures still present. These are not introduced by this PR and likely have been present for quite a while.
The primary reason from …
=> std.math.complex fixes

lib/std/crypto/ml_kem.zig, lib/std/macho.zig, lib/std/unicode.zig, lib/std/zig/Ast.zig, lib/std/zig/AstGen.zig, lib/std/zig/parser_test.zig, lib/std/zig/string_literal.zig, lib/std/zig/system/darwin/macos.zig, lib/std/zig/system/linux.zig, lib/std/zig/tokenizer.zig, src/Package/Manifest.zig, src/link/tapi/yaml/test.zig, test/cases/compile_errors/empty_char_lit.zig, test/cases/compile_errors/invalid_legacy_unicode_escape.zig, test/cases/compile_errors/invalid_unicode_escape.zig, test/cases/compile_errors/normal_string_with_newline.zig, test/compile_errors.zig, test/run_translated_c.zig, test/translate_c.zig
I pointed a fuzzer at the tokenizer and it crashed immediately. Upon inspection, I was dissatisfied with the implementation. This commit removes several mechanisms:
* Removes the "invalid byte" compile error note.
* Dramatically simplifies tokenizer recovery by making recovery always occur at newlines, and never otherwise.
* Removes UTF-8 validation.
* Moves some character validation logic to `std.zig.parseCharLiteral`.
Removing UTF-8 validation is a regression of #663, however, the existing implementation was already buggy. When adding this functionality back, it must be fuzz-tested while checking the property that it matches an independent Unicode validation implementation on the same file. While we're at it, fuzzing should check the other properties of that proposal, such as no ASCII …
=> std.zig.tokenizer: simplification and spec conformance

lib/std/start.zig, src/arch/riscv64/CodeGen.zig, src/arch/riscv64/Emit.zig, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/relocation.zig
=> riscv: fix-up non `.got.zig` symbol relocations

lib/std/start.zig
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-elf.adoc#calculation-symbols
=> start: Initialize `gp` to `__global_pointer$` on riscv.

lib/std/os/linux/start_pie.zig
Requires #20822 to actually work.
=> `std.os.linux.start_pie`: Add mips and powerpc support

lib/std/Target.zig
Similar situation to #20451:
```console
❯ zig cc test.c -target hexagon-linux-none
error: unknown target CPU 'generic'
note: valid target CPU values are: hexagonv5, hexagonv55, hexagonv60, hexagonv62, hexagonv65, hexagonv66, hexagonv67, hexagonv67t, hexagonv68, hexagonv69, hexagonv71, hexagonv71t, hexagonv73
```
Clang uses `hexagonv60` by default: https://github.com/llvm/llvm-project/blob/25f9415713f9f57760a5322876906dc11385ef8e/clang/lib/Driver/ToolChains/Hexagon.cpp#L800-L806
=> `std.Target`: Use hexagonv60 as the baseline CPU model for hexagon.

lib/std/elf.zig, lib/std/os/linux.zig
Closes #20743.
Source: https://github.com/torvalds/linux/blob/7a3fad30fd8b4b5e370906b3c554f64026f56c2f/include/uapi/linux/audit.h#L377-L443
=> `std.os.linux.AUDIT`: Rewrite ARCH in terms of std.elf.EM.

lib/std/Thread.zig, lib/std/os/linux/tls.zig, lib/std/start.zig
I don't normally like to propose refactors like this, but I think it's warranted here. I like to think I'm pretty good at understanding obscure ABI stuff, but I really struggled with this particular module initially. It's not helped by the fact that there's a lot of incorrect/incomplete information floating around on the internet. So, I renamed things to (hopefully) be more clear, added more in-depth (and correct) documentation, and replaced some pointer manipulation with a struct.
Once I understood the module, it became clearer that there was something off-looking about the layout computation for the modified Variant I. I verified that it was indeed broken by testing on PPC64, and also fixed that.
Finally, I ported the module to all the architectures I've been doing porting work for:
* …
=> `std.os.linux.tls`: Refactor, improve documentation, fix a bug, and port to more architectures

ci/aarch64-linux-release.sh, ci/aarch64-windows.ps1, ci/x86_64-windows-release.ps1
=> `ci`: Add stage3/4 diff to Linux (aarch64) and windows (aarch64, x86_64) release scripts.

tools/gen_stubs.zig
To use musl support of loongarch64.
=> loongarch: add loongarch64 to gen_stubs.zig

lib/std/Target.zig, tools/process_headers.zig
It is impossible to even build projects like glibc when targeting a generic SPARC v8 CPU; LEON3 is effectively considered the baseline for `sparc-linux-gnu` now, particularly due to it supporting a CASA instruction similar to the one in SPARC v9. However, it's slightly incompatible with SPARC v9 due to having a different ASI tag, so resulting binaries would not be portable to regular SPARC CPUs. So, as the least bad option, make v9 the baseline for sparc32.
https://sourceware.org/git/?p=glibc.git;a=blob;f=scripts/build-many-glibcs.py;h=8bfe29876d8a137be7622a1a00c8566829a1365d;hb=HEAD#l460
=> `std.Target`: Bump baseline CPU for sparc32 to v9; add `sparcv9-linux-gnu` to `process_headers.zig`

test/standalone/build.zig, tools/generate_c_size_and_align_checks.zig
Requested by @alexrp 
Prints _Static_asserts for the size and alignment of all the basic built-in C types.
The output can be run through a compiler for the specified target to verify that Zig's values are the same as those used by a C compiler for the target.
Example output for `x86_64-linux-gnu`:
```c
_Static_assert(sizeof(char) == 1, "");
_Static_assert(_Alignof(char) == 1, "");
_Static_assert(sizeof(short) == 2, "");
_Static_assert(_Alignof(short) == 2, "");
_Static_assert(sizeof(unsigned short) == 2, "");
_Static_assert(_Alignof(unsigned short) == 2, "");
_Static_assert(sizeof(int) == 4, "");
_Static_assert(_Alignof(int) == 4, "");
_Static_assert(sizeof(unsigned int) == 4, "");
_Static_assert(_Alignof(unsigned int) == 4, "");
_Static_assert(sizeof(long) == 8, ""); …
```
=> tools: Add tool for checking size and alignment of C types

src/musl.zig
This is what upstream's configure does: https://git.musl-libc.org/cgit/musl/tree/configure#n537
Previously, we only disabled warnings in some musl compilations, with `rcrt1.o` notably being one for which we didn't. This resulted in a warning in `dlstart.c` which is included in `rcrt1.c`. So let's just be consistent and disable warnings for all musl code.
Closes #13385.
=> `musl`: Disable warnings in all compilations.

CMakeLists.txt
Adds ZIG_EXTRA_BUILD_ARGS which provides a way to add additional stage3 args.
For example:  `-DZIG_EXTRA_BUILD_ARGS="--maxrss;34359738368"`
=> cmake: add ZIG_EXTRA_BUILD_ARGS option

lib/std/Target.zig
Sourced from GCC backends and some manual testing with clang.
=> `std.Target`: Some corrections and additions to charSignedness().

src/Type.zig
This may not be the totally correct fix, but I'm hoping this gets the ball rolling towards finding the correct fix. I'm also unsure what the source of truth is for these alignment values.
---
During the LLVM 18 upgrade, two changes were made that changed `@alignOf(u64)` from 8 to 4 for the x86-windows target:
- `Type.maxIntAlignment` was made to return 16 for x86 (200e06b). Before that commit, `maxIntAlignment` was 8 for windows/uefi and 4 for everything else
- `Type.intAbiAlignment` was made to return 4 for 33...64 (7e1cba7 + e89d6fc). Before those commits, `intAbiAlignment` would return 8, since the maxIntAlignment for x86-windows was 8 (and for other targets, the `maxIntAlignment` of 4 would clamp the `intAbiAlignment` to 4)
However, `src/codegen/llvm.zig` has its own alignment …
=> Make `Type.intAbiAlignment` match the LLVM alignment for x86-windows target

lib/std/crypto/ecdsa.zig, lib/std/os/linux.zig
Dude to the `std.crypto.ecdsa.KeyPair.create` taking and optional of seed, even if the seed is generated, cross-compiling to the environments without standard random source (eg. wasm) (`std.crypto.random.bytes`) will fail to compile.
This PR changes the API of the problematic function and moves the random seed generation to a new utility function.
The simplest workaround is copying the ECDSA file to my project and making the changes (to enjoy microscopic crypto wasm binary).
=> Ecdsa cross compilation fix + api change

src/main.zig
The "-v" argument is the same as "--version", but the linker should not exit after the version is printed.
CMake passes this argument during ABI info detection, and currently zig cc fails because this flag is not supported.
Fixes #20493
=> zig ld: handle -v linker arg

lib/std/c.zig, lib/std/os/linux.zig, lib/std/os/linux/test.zig
The std lib is missing getppid, this patch adds it.
=> Add getppid to std.c and std.os.linux.

lib/std/c.zig, lib/std/os/linux.zig, lib/std/posix.zig, lib/std/posix/test.zig
The signature is documented as:
```
int link(const char *, const char *);
```
(see https://man7.org/linux/man-pages/man2/link.2.html or https://man.netbsd.org/link.2)
And its not some Linux extension, the [syscall implementation](https://github.com/torvalds/linux/blob/21b136cc63d2a9ddd60d4699552b69c214b32964/fs/namei.c#L4794-L4797) only expects two arguments too.
It probably *should* have a flags parameter, but its too late now.
I am a bit surprised that linking glibc or musl against Zig code that invokes a 'link' with three parameters doesn't fail (at least, I couldn't get any local test cases to trigger a compile or link error).  But the extra argument should be harmless anyway.
The test case in `std/posix/test.zig` is currently disabled, but if I manually enable it, it works with this …
=> POSIX link() syscall only takes two arguments (no flags)

src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/riscv64/Emit.zig, src/arch/sparc64/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Emit.zig, src/arch/x86_64/Lower.zig, src/codegen.zig, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/LinkerDefined.zig, src/link/Elf/Object.zig, src/link/Elf/SharedObject.zig, src/link/Elf/Symbol.zig, src/link/Elf/ZigObject.zig, src/link/Elf/eh_frame.zig, src/link/Elf/file.zig, src/link/Elf/gc.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig, src/link/Elf/thunks.zig
This will make parallelisation of parsing stages actually possible as well as it should clean up incremental. This change also makes working with symbol indexes in the backends easier I believe,
=> elf: move ownership of symbols into owning objects

lib/std/json/scanner.zig, lib/std/json/scanner_test.zig
=> std.json: fix partial strings getting dropped when multi-byte codepoints span input buffers

lib/std/Target/arm.zig, lib/std/Target/riscv.zig, tools/update_cpu_features.zig
- Before this PR, the name `v9_5a` in `Target/arm.zig` was being used for two different features, and one was overwriting the other in the `all_features` array.
- `arrowlake_s` is an alias for `arrowlake-s`
- RISCV unaligned-scalar-mem was added in LLVM 18.1.6
=> update_cpu_features: Fixes and updates

tools/generate_c_size_and_align_checks.zig
Groups the assertions together properly.
=> `generate_c_size_and_align_checks`: Remove extraneous newline

lib/compiler/fmt.zig, lib/std/posix.zig, lib/std/zig/system.zig, src/link.zig
When reading from a `timerfd` on `CLOCK_REALTIME` or `CLOCK_REALTIME_ALARM` with `TFD_TIMER_CANCEL_ON_SET` and `TFD_TIMER_ABSTIME` flags set, the syscall will return `ECANCELED`.
See: https://man7.org/linux/man-pages/man2/timerfd_create.2.html
=> std.posix: read on timerfd can return error.Canceled

lib/std/debug/Dwarf.zig, test/standalone/stack_iterator/build.zig
*    fix the ".debuglink" case
*    and add support for the debuginfod cache (usefull for os libraries like libc.so.6)
a possible follow-up improvement would be to download the debuginfo automatically, but I'm not sure if it's a good idea when requesting a callstack from the process itself (which is probably already in panic)..
=> std.debug.Dwarf: improve loading debug symbol from separate files

lib/std/hash_map.zig
**Note: this resurrects the recently closed #17890.**
---
This allows a highly fragmented HashMap to have tombstones removed as the values are all rehashed.
It would be nice to make this ``rehash()`` automatically, but that currently presents a challenge where it doesn't work with adapted contexts since the keys are not preserved in the map for re-hashing and the hash value is not stored currently, and the non-adapted contexts require a bit of additional book-keeping to check before calling rehash().
This is a partial fix for #17851, but requires the user to call ``rehash()`` periodically to get the benefit.
=> std.hash_map: adding a rehash() method

src/Compilation.zig, src/main.zig
Some projects, such as Cap'n Proto, use .c++ as their filenames. Without this, compiling them fails because zig c++ will fall back to using the linker.
=> Compilation: Mark .c++ files as having C++ extension

lib/fuzzer.zig, lib/fuzzer/wasm/main.zig, lib/std/Build/Fuzz/WebServer.zig, lib/std/Build/Fuzz/abi.zig, tools/dump-cov.zig
* Upgrade from u8 to usize element types.
- WebAssembly assumes u64. It should probably try to be target-aware
instead.
* Move the covered PC bits to after the header so it goes on the same
page with the other rapidly changing memory (the header stats).
depends on the semantics of accepted proposal #19755
closes #20994
=> fuzzing: more optimized and correct management of 8-bit PC counters

tools/generate_linux_syscalls.zig
This PR aims to fix the formatting issues of the generated `syscalls.zig` by running `generate_linux_syscalls.zig` by removing trailing new line added at the end of the file in the last generated enum
=> Fix formatting issues of the generated `syscalls.zig`

lib/std/os/linux.zig
Wanted to make sure that these types/values are correct for the architectures we currently have `std.os.linux` arch bits for (arm, mips, powerpc, riscv, sparc, x86). Decided it would be easier to just retranslate them all, especially since some seemed to have been manually expanded rather than using our ioctl construction helpers.
For some of these, I deliberately chose not to try to merge multiple architectures. This is especially important for `T`; it quickly becomes an unmaintainable mess that way. Better to reflect what the actual UAPI headers do in this case.
Also added a few missing types (`termios2`, `serial_rs485`, etc).
=> `std.os.linux`: Retranslate and port some ioctl-related types and values.

doc/langref.html.in, lib/std/crypto.zig, lib/std/crypto/aegis.zig, lib/std/crypto/aes_gcm.zig, lib/std/crypto/aes_ocb.zig, lib/std/crypto/ascon.zig, lib/std/crypto/bcrypt.zig, lib/std/crypto/chacha20.zig, lib/std/crypto/ff.zig, lib/std/crypto/ghash_polyval.zig, lib/std/crypto/isap.zig, lib/std/crypto/keccak_p.zig, lib/std/crypto/ml_kem.zig, lib/std/crypto/pcurves/common.zig, lib/std/crypto/poly1305.zig, lib/std/crypto/salsa20.zig, lib/std/crypto/timing_safe.zig, lib/std/crypto/tlcsprng.zig
std.crypto has quite a few instances of breaking [naming conventions](https://ziglang.org/documentation/0.13.0/#Avoid-Redundancy-in-Names). This is the beginning of an effort to address that.
Deprecates `std.crypto.utils`.
=> std.crypto: better names for everything in utils

lib/std/os/linux/start_pie.zig
Some helpful resources:
* https://maskray.me/blog/2021-10-31-relative-relocations-and-relr
* https://dram.page/p/relative-relocs-explained
=> `std.os.linux.start_pie`: Add support for the new RELR relocation format.

doc/langref.html.in
fixes issue #20898
Updates documentation to correctly reference 'long double' as equivalent ANSI C type for Zig 'f80'.
=> fix C type corresponding to f80

lib/std/os/linux.zig
```
[...]/std/os/linux.zig:6558:51: error: backing integer type 'c_uint' has bit size 32 but the struct fields have a total bit size of 33
pub const tc_lflag_t = if (is_mips) packed struct(tcflag_t) {
^~~~~~~~
```
cc @alexrp
=> std.os.linux: Fix definition of tc_lflag_t on MIPS

src/codegen/llvm.zig
https://github.com/llvm/llvm-project/blob/efc6b50d2d93fa571572ee3ef1d4565c09ad1610/llvm/lib/Target/Sparc/SparcISelLowering.cpp#L561-L562
=> `llvm`: Disable lowering to f128 on sparc32.

src/codegen/llvm.zig
https://github.com/llvm/llvm-project/issues/50374
Not seeing any indication that this will be fixed anytime soon, so let's just not lower to `f16` for now.
=> `llvm`: Disable lowering to f16 on s390x.

lib/std/Thread.zig
https://git.musl-libc.org/cgit/musl/commit/?id=ce3688eca920aa77549323f84e21f33522397115
=> `std.Thread`: Explain apparently pointless mips instruction in freeAndExit().

lib/std/Thread.zig
Wrong source/destination register order.
=> `std.Thread`: Fix freeAndExit() assembly for powerpc.

lib/std/Thread.zig
These just seem to have been copy/pasted from mips32.
=> `std.Thread`: Fix freeAndExit() syscall numbers for mips64.

lib/std/os/linux/loongarch64.zig
to make it work for `zig-bootstrap` for `loongarch64-linux-musl`
=> loongarch: add missing getcontext

src/Sema.zig, src/codegen/llvm.zig, src/codegen/llvm/Builder.zig
This adds implementations for `@workItemId`, `@workGroupId`, and `@workGroupSize` for nvptx and nvptx64 in the LLVM backend.
=> nvptx: add implementations for GPU builtins

lib/std/Build/Fuzz/WebServer.zig, lib/std/debug/Coverage.zig, lib/std/debug/Dwarf.zig, lib/std/debug/Info.zig, lib/std/debug/SelfInfo.zig, src/zig_llvm.cpp, tools/dump-cov.zig
See individual commit messages.
Closes #20990
The motivating example looks a lot better in ReleaseSafe mode:
But it looks worse in debug mode for some reason:
However, I verified that our LLVM IR looks good, and our debug info logic matches GDB exactly. So, I think it's two steps forward, one step back. Remaining issues are tracked by:
* #20992
* #20989
=> fix several debug info bugs

doc/langref.html.in, doc/langref/test_round_builtin.zig, lib/std/math.zig
Questions regarding the behavior of this have shown up in the IRC channel more than once, and I think the current wording is misleading. I also added a test, which I think demonstrates the described behavior fairly unambiguously.
=> langref: clarify functionality of the round builtin

lib/std/os/linux.zig
With Linux 6.10 the syscall `mseal` was introduced. This PR adds the wrapper to it.
=> std.os.linux: add `mseal` syscall

lib/std/mem.zig
Also move example comments into tests.
=> std.mem.writeVarPackedInt: handle write_size == 0

lib/std/start.zig
=> start: fix passing comptime-only value to inline asm

lib/std/os/linux/tls.zig
Got this error when trying to build a simple zig program for loongarch target
```
$ ~/opt/zig/bin/zig build-exe hello.zig -target loongarch64-linux-gnu
error: <inline asm>:1:3: unrecognized instruction mnemonic, did you mean: move?
mv tp, $a0
^
```
For loongarch there is no `mv` instruction mnemonic, change it to something else.
=> loongarch: fix asm to set thread pointer

lib/std/start.zig, src/codegen/llvm.zig
I had the operator precedence wrong.
For csky, there are currently some LLVM issues blocking full compilation, so that mistake slipped through rather unsurprisingly. For riscv, I first added the `gp` initialization code unconditionally and tested it, but then I added the condition to exclude that code in self-hosted and neglected to actually test it with LLVM afterwards. The result was that it worked fine with the self-hosted backend, but not so with LLVM (which we have no CI coverage for due to #18872).
=> `start`: Avoid string concatenation in inline asm.

src/Sema.zig, test/cases/compile_errors/stack_usage_in_naked_function.zig
=> add an error for stack allocations in naked functions

cmake/Findclang.cmake
This fixes the failure to find CLANG_LIBRARIES on debian, which packages the relevant .so file at these paths:
libclang-cpp18: /usr/lib/llvm-18/lib/libclang-cpp.so.18.1
libclang-cpp18: /usr/lib/x86_64-linux-gnu/libclang-cpp.so.18.1
libclang-cpp18: /usr/lib/x86_64-linux-gnu/libclang-cpp.so.18
(The latter two paths are symlinks to the first.)
Without the patch, cmake fails with this error:
-- Could NOT find clang (missing: CLANG_LIBRARIES) (Required is at least version "18")
=> cmake: CLANG_LIBRARIES: find libclang-cpp.so.18.1

lib/std/bounded_array.zig, lib/std/zig/Zir.zig, src/Compilation.zig, src/InternPool.zig, src/Sema.zig, src/Type.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/crash_report.zig, src/link/Dwarf.zig, src/main.zig, test/incremental/add_decl, test/incremental/add_decl_namespaced, test/incremental/delete_comptime_decls, test/incremental/unreferenced_error, tools/incr-check.zig
> Say you build quick? Baby I know,
> That's that incremental
-Sabrina Carpenter 2024
---
We're getting close now, folks!
This PR makes progress towards incremental compilation. Various bugs and regressions have been fixed. The `incr-check` tool is expanded with some more options, such as passing through `-fno-emit-bin` to the compiler. With this option, the existing incremental compilation test, and the 3 added by this commit, all succeed. I don't know whether the right things are going to codegen, but some hacky CBE testing indicates... maybe?
The biggest blocker right now is linker work from @kubkon -- it's currently hard for me to know for sure whether the full pipeline is actually working correctly. Once one of the self-hosted linkers (presumably ELF) can perform basic incremental …
=> Incremental compilation progress

ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/aarch64-macos-debug.sh, ci/aarch64-macos-release.sh, ci/aarch64-windows.ps1, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, ci/x86_64-macos-release.sh, ci/x86_64-windows-debug.ps1, ci/x86_64-windows-release.ps1
This reverts commit 55cc9dda66a24ed2a86a358533ecf5840d47b3d7.
Checking if this resolves the `x86_64-linux-*` timeouts.
=> Revert "ci: Enable -Dtest-slow-targets."

lib/std/debug/Dwarf.zig, lib/std/fs/get_app_data_dir.zig, src/introspect.zig
Closes #21132
According to the XDG Base Directory specification
(https://specifications.freedesktop.org/basedir-spec/latest/#variables), empty values for these environment variables should be treated the same as if they are unset. Specifically, for the instances changed in this commit,
> $XDG_DATA_HOME defines the base directory relative to which
> user-specific data files should be stored. If $XDG_DATA_HOME is either
> not set **or empty**, a default equal to $HOME/.local/share should be
> used.
and
> $XDG_CACHE_HOME defines the base directory relative to which
> user-specific non-essential data files should be stored. If
> $XDG_CACHE_HOME is either not set **or empty**, a default equal to
> $HOME/.cache should be used.
(emphasis mine)
In addition to the case mentioned in the linked …
=> Fix handling of empty XDG environment variables

lib/compiler/aro/aro/Builtins/Builtin.zig, lib/compiler/aro/aro/Parser.zig, lib/std/crypto/aes/soft.zig, lib/std/crypto/blake2.zig, lib/std/crypto/pcurves/p384.zig, lib/std/enums.zig, lib/std/hash/xxhash.zig, lib/std/math.zig, lib/std/math/hypot.zig, lib/std/math/nextafter.zig, lib/std/unicode.zig, lib/std/zig/AstGen.zig, src/InternPool.zig, src/Sema.zig, src/register_manager.zig, test/incremental/delete_comptime_decls, test/incremental/modify_inline_fn, test/incremental/move_src
Two main things:
* Handle eval branch quota properly when memoizing calls. This is actually a bugfix to **non-** incremental, which brings it in line with incremental. **This bugfix is a breaking change.**
* Incorporate extra information into AstGen source hashes; most notably, the line and column of `@src()` calls. This solidifies the language change implemented by #17688; see commit message for details.
I added a new incremental compilation test for the `@src()` stuff; it passes with the C backend.
@Vexu, this PR (first commit) required correcting some eval branch quotas in Aro. One of the changes I made was to `aro/Builtins/Builtin.zig`, which is a generated file, but the file used to generate it isn't included downstream. Upstream Aro should make whatever the actual required change …
=> incremental: more progress

lib/std/dwarf.zig, src/link/Dwarf.zig
* reduce iteration cost by not tracking unused entries
* avoid emitting unused abbrevs to `.debug_abbrev`
* get the compiler executable passing `llvm-dwarfdump --verify`
* make it possible to skip `.debug_line` padding much more quickly
=> Dwarf: cleanup emitted debug info

lib/std/json/stringify.zig, lib/std/json/stringify_test.zig
An implementation of the functionality requested in https://github.com/ziglang/zig/pull/20962 .
=> std.json.WriteStream supports streaming long values directly to the underlying stream

lib/std/crypto.zig, lib/std/crypto/ml_kem.zig
NIST has published the final specification of ML-KEM, which adds domain separation to the seed used to create the inner secret key.
Deprecate `ml_kem_01` in favor of `ml_kem` .
=> Update ML-KEM to the final specification

lib/libc/glibc/sysdeps/unix/sysv/linux/alpha/xstatver.h, lib/libc/glibc/sysdeps/unix/sysv/linux/arm/xstatver.h, lib/libc/glibc/sysdeps/unix/sysv/linux/hppa/xstatver.h, lib/libc/glibc/sysdeps/unix/sysv/linux/microblaze/xstatver.h, lib/libc/glibc/sysdeps/unix/sysv/linux/sh/xstatver.h
Specifically for alpha, arm, hppa, microblaze, and sh.
Closes #20054.
=> `glibc`: Add missing xstatver.h for some linux architectures.

src/glibc.zig
For some platforms, the math-related flags are ignored and produce warnings. There's nothing we can do about that, so just silence them.
This started showing up after #20909. For example, for `mips64-linux-gnuabi64.2.32`:
```
warning: overriding currently unsupported rounding mode on this target [-Wunsupported-floating-point-opt]
```
The warning is confusingly worded; it's just informing us that [it's disabling rounding math despite us passing `-frounding-math`](https://github.com/llvm/llvm-project/blob/69f76c782b554a004078af6909c19a11e3846415/clang/lib/Frontend/CompilerInstance.cpp#L130-L134). So it's the same as if we hadn't passed `-frounding-math` in the first place.
=> `glibc`: Pass `-Qunused-arguments` when building `libc_nonshared.a`.

lib/std/c.zig
Hello zig developers !
After, building zig at the latest branch (0.14.0-dev.1248+997c4bd52), i find it out that 
getcontext is undefined on openbsd too.
Here a short patch, for fix the issue !
=> Update c.zig, openbsd don't have getcontext

lib/std/os/linux.zig, lib/std/os/linux/bpf/btf.zig, lib/std/os/linux/test.zig
Fixes for the `std.os.linux` compilation errors reported in #21094
=> std.os.linux: Fix bunch of compilation errors

lib/libc/glibc/csu/init.c, src/glibc.zig
This is necessary to inform the real, non-stub glibc that a program built with Zig is using a modern `FILE` structure, i.e. glibc 2.1+. This is particularly important on lesser-used architectures where the legacy code is poorly tested; for example, glibc 2.40 introduced a regression for the legacy case in the libio cleanup code, causing all Zig-compiled MIPS binaries to crash on exit.
=> `glibc`: Define `_IO_stdin_used` in start code and reference it in stub asm.

lib/compiler/std-docs.zig, lib/std/Build/Fuzz/WebServer.zig, lib/std/Build/Step.zig
regressed in dffc8c44f9a01aa05ea364ffdc71509d15bc2601 since there is no test coverage for the `zig std` command yet.
closes #21180
=> fix autodocs regression FTBFS

lib/std/Build.zig
Ensures that all runned command are visible when using `--verbose` flag, for example `pkg-config` from Step.Compile or `git describe` from build.zig.
=> std.Build: call `handleVerbose2` in `runAllowFail`

lib/std/Target/Query.zig
The `zigTriple()` implementation simply returns `gnu` when a glibc version is provided but a more specific ABI isn't.
https://github.com/ziglang/zig/blob/bb70501060a8bfff25818cf1d80491d724f8a634/lib/std/Target/Query.zig#L433-L445
I do realize I sound like a broken record at this point, but this is another problem we have because [we conflate libc and ABI](https://github.com/ziglang/zig/issues/20690).
Note: I think this test has been broken for a long time, but it was not failing in CI because you need to be testing for a target like `arm-linux-gnueabi`, `mips64-linux-gnuabi64`, etc, and AFAIK the CI machines do not have non-native glibcs installed (which is a bit of a shame IMO, but I digress).
=> std.Target.Query: Fix `parse` test on ABIs like `gnueabi`, `gnuabi64`, etc.

lib/std/fs/test.zig
https://github.com/ziglang/zig/issues/20747
Wasmtime developers have acknowledged that this is a regression on their end. I propose that we disable this test temporarily so that new contributors using a recent Wasmtime version don't hit this and get confused (e.g. https://github.com/ziglang/zig/pull/20511#issuecomment-2277214500).
=> std.fs: Disable `file operations on directories` test on WASI with wasi-libc.

lib/std/dynamic_library.zig
Implements the base that should usually work that is
- Check LD_LIBRARY_PATH if the binary is no setuid setgid binary
- Check /lib, /usr/lib, in that order
The missing parts are:
- DT_RPATH and DT_RUNPATH handling from the calling executable
- Reading /etc/ld.so.cache
For more details check man page of dlopen(3)
=> ElfDynLib: resolve lib from system paths

src/Zcu/PerThread.zig, test/incremental/remove_enum_field
I don't recall why I put these checks here -- they aren't correct. We can freely recreate a type even if its fields have changed, because we are going to re-do all type resolution.
The only conditions for recreations are (a) the ZIR index must not be lost and (b) the number of captures must be the same. These conditions are permissible because if either is violated, we can guarantee that analysis of a valid `zirStructDecl` (etc) will never reference this type (since the ZIR index has just been tracked, and the captures have just been created based on the ZIR).
Adds a corresponding test case.
Resolves: #21185
=> incremental: fix adding/removing aggregate fields

lib/std/coff.zig, lib/std/elf.zig, src/link/Elf.zig, src/link/Elf/Object.zig, src/link/Elf/SharedObject.zig, src/link/Elf/relocatable.zig, src/link/MachO.zig, src/link/MachO/Dylib.zig, src/link/MachO/Object.zig, src/link/MachO/relocatable.zig, test/link/elf.zig
These are fundamentally incapable of producing accurate information for reasons I've laid out in #20771. Since our only use of these functions is to check that object files have the correct machine type, and since #21020 made `std.Target.to{Coff,Elf}Machine()` more accurate, just switch these checks over to that and compare the machine type tags instead.
Closes #20771.
=> `std.{coff,elf}`: Remove the `{MachineType,EM}.toTargetCpuArch()` functions.

src/translate_c.zig, test/cases/translate_c/void_pointer_subtraction.c
Pointer subtraction on `void *` or function pointers is UB by the C spec, but is permitted by GCC and Clang as an extension. So, avoid crashing translate-c in such cases, and follow the extension behavior -- there's nothing else that could really be intended.
=> translate-c: support GCC/Clang pointer subtraction extension

.github/workflows/ci.yaml
Sets minimal required number of permissions in GitHub Actions. Docs: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
By default it is set to: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
It allows much more than needed by default.
`zig` only needs `contents: read`, so the repo contents can be read and tested.
We have this set in CPython as a part of our security: https://github.com/python/cpython/blob/fe85a8291d9aa11c9ce9e207c39ea0a0c35f9625/.github/workflows/build.yml#L14-L15
=> Only set `contents: read` permission in GitHub Actions

lib/compiler/test_runner.zig, lib/fuzzer.zig, lib/std/Build/Fuzz/WebServer.zig, lib/std/Build/Step/Compile.zig, src/Air.zig, src/Sema.zig, src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, src/print_air.zig
Follow-up to #21075.
Closes #20992 by moving code coverage instrumentation to the LLVM backend explicitly, leaving LLVM's sancov pass to only do TraceCmp.
cc @kristoff-it - implications for https://github.com/kristoff-it/zig-afl-kit/ are that you can remove these:
```c
void __sanitizer_cov_trace_pc_indir () {}
void __sanitizer_cov_8bit_counters_init () {}
void __sanitizer_cov_pcs_init () {}
```
Although leaving them in is harmless. And meanwhile you should see a speedup in iterations per second since it no longer has redundant instrumentation. Unfortunately you have to leave `__sancov_lowest_stack` for now due to https://github.com/llvm/llvm-project/pull/106464.
This is after it reaches the panic line:
The extra green dots on the panic line are the "else" clauses from each if statement. …
=> exclude unreachable code paths from having coverage instrumentation

src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/zig_llvm.cpp, src/zig_llvm.h
Passing it by value means that bringup on new architectures is harder for no real benefit. Passing it by pointer allows to get the compiler running without needing to figure out the C calling convention details first. This manifested in practice on LoongArch, for example.
See: https://github.com/ziglang/zig-bootstrap/issues/166#issuecomment-2313778111
The intent here is *not* to sweep the problem under the rug; I have plans to go through and improve our C calling convention conformance across the board. This just makes initial porting easier.
cc @yxd-ym please test this and see if it gets you unblocked.
=> `llvm`: Pass `EmitOptions` to libzigcpp by pointer.

lib/compiler_rt/arm.zig, lib/compiler_rt/stack_probe.zig, lib/std/builtin.zig, lib/std/debug.zig, lib/std/os/windows.zig, lib/std/zig/WindowsSdk.zig, lib/std/zig/target.zig, src/link/Coff.zig, src/mingw.zig
Can compile and link a Zig hello world now, but not much else due to some relocations that LLVM's `ARMWinCOFFObjectWriter` apparently can't handle. I also can't actually run the resulting binary as I don't have a Windows on Arm system. But it's at least a step in the right direction.
=> Change `arm-windows-gnu` to `thumb-windows-gnu`, plus some initial port work

lib/std/zig/Server.zig, src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/target.zig, src/zig_llvm.cpp, src/zig_llvm.h
* Set the correct PIC level for MIPS.
* Work around https://github.com/ziglang/zig/issues/21215 until https://github.com/llvm/llvm-project/pull/106231 trickles down.
* Revert the workaround for https://github.com/ziglang/zig/issues/14904.
This makes `zig build test-modules -fqemu --glibc-runtimes <...> -Dtest-slow-targets -Dtest-target-filter=mips-linux.4.19...6.10.3-gnueabi -Dtest-target-filter=mipsel-linux.4.19...6.10.3-gnueabi` mostly work, save for an `fchmodat` test failure that I still need to investigate.
=> Fix MIPS PIC level and work around an LLVM bug for `mips(el)-linux-gnueabi(hf)`

lib/std/c.zig
OpenBSD definition:
https://github.com/openbsd/src/blob/95d5c33/include/pwd.h#L80-L91
From `MacOSX.sdk/usr/include/pwd.h`:
```c
struct passwd {
char	*pw_name;		/* user name */
char	*pw_passwd;		/* encrypted password */
uid_t	pw_uid;			/* user uid */
gid_t	pw_gid;			/* user gid */
__darwin_time_t pw_change;		/* password change time */
char	*pw_class;		/* user access class */
char	*pw_gecos;		/* Honeywell login info */
char	*pw_dir;		/* home directory */
char	*pw_shell;		/* default shell */
__darwin_time_t pw_expire;		/* account expiration */
};
```
NetBSD definition:
https://github.com/NetBSD/src/blob/51abf16/include/pwd.h#L107-L118
On FreeBSD, `passwd` also has an internal `pw_fields` field:
https://github.com/freebsd/freebsd-src/blob/6e75812/include/pwd.h#L111-L123
Ditto for DragonFly: …
=> std.c.passwd: support macOS and NetBSD

lib/std/Build/Step.zig, lib/std/builtin.zig, lib/std/debug.zig
Noticed someone on Discord mention that ``std.debug.writeStackTrace`` doesn't use an allocator, so I removed it.
=> std.debug: remove allocator from std.debug.writeStackTrace()

build.zig
See: https://elixir.bootlin.com/llvm/llvmorg-18.1.8/source/llvm/lib/Target/LoongArch/LoongArchTargetMachine.cpp#L74
LLVM 18 only supports
- small
- medium
- large
code model on loongarch64.
And it seems to remain the same in LLVM 19.
See: https://elixir.bootlin.com/llvm/llvmorg-19.1.0-rc3/source/llvm/lib/Target/LoongArch/LoongArchTargetMachine.cpp#L83
I have tried different values, but medium seems to be the only one supported for both `loongarch64-linux-gnu` and `loongarch64-linux-musl` to have a debuggable `loongarch64` zig built.
Also see: https://github.com/ziglang/zig-bootstrap/issues/164#issuecomment-2290639730
=> loongarch: use medium code model for zig loongarch64 binary

lib/std/posix.zig
Zig's wrapper functions over `mmap` and `munmap` abstract over the system pages' lengths: `std.posix.mmap` returns (if successful) a slice of the exact requested length (rather than error, or rounded up to a multiple of the page size). `std.posix.munmap` accepts the slice produced by `std.posix.mmap` - so the length here too isn't page aligned.
`std.posix.mprotect` should also adhere to the abstraction, and accept any slice produced by `std.posix.mmap`, without need to fiddle with the data.
the change is simply to remove the assertion, as it seems like Linux, Plan9, and Windows' `VirtualProtect` all cope with lengths which aren't a multiple of a page (as I understand it, all other OSs require using the libc function, which also allows for lengths not divisible by the page size). …
=> `std.posix.mprotect` remove memory length assertion

lib/libc/include/generic-glibc/bits/string_fortified.h
=> lib: guard definition of `strl{cat,cpy}` against glibc version when _FORTIFY_SOURCE is enabled

lib/std/c.zig
=> std.c: fix pthread_mutex_t size for x86_64-linux-gnu

lib/std/debug.zig
Very simply add the format specifier to the print statement. Since debug.print is hard coded I couldn't come up with a reasonable way to add a test, and since this function is simple enough I doubt it's useful.
fixes one part of #21094
=> std: make debug.dumpStackPointerAddr compile

src/Sema.zig, test/cases/compile_errors/compile_time_struct_field.zig
Rework of #20791
Modifies `zirStructInit` to pass an array of `?usize`s to `finishStructInit`, mapping each initialized field's index in the struct declaration to the index in the initialization expression. Having the correct index then prevents the current out of bounds access behavior. I provided some additional detail for the bug in the original PR's description.
Closes #20629
=> fix(Sema): patch segfault in `finishStructInit` take 2

lib/compiler_rt/comparef.zig, lib/compiler_rt/extendf.zig, lib/compiler_rt/extendxftf2.zig, lib/compiler_rt/subxf3.zig, lib/compiler_rt/truncf.zig, lib/compiler_rt/trunctfxf2.zig, lib/std/math.zig, lib/std/math/nextafter.zig
The motivation behind this is to make these functions follow the naming convention for functions. I can change them back to be just regular functions if that is what is wanted and can change them to makeF80 and breakf80 or something else if wanted also.
=> std.math: rename make_f80 to F80.toFloat and break_f80 to F80.fromFloat 

lib/std/array_hash_map.zig, lib/std/array_list.zig, lib/std/hash_map.zig, lib/std/heap/general_purpose_allocator.zig, lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, src/arch/riscv64/CodeGen.zig, src/print_zir.zig, test/behavior.zig, test/behavior/cast_int.zig, test/behavior/decl_literals.zig, test/behavior/struct.zig, test/behavior/try.zig, test/behavior/while.zig, test/cases/compile_errors/cast_enum_literal_to_enum_but_it_doesnt_match.zig, test/cases/compile_errors/comptime_arg_to_generic_fn_callee_error.zig
Pretty straightforward -- see commit messages. I also added "default initialization" decls to `ArrayListUnmanaged`, `HashMapUnmanaged`, `ArrayHashMapUnmanaged`, and `GeneralPurposeAllocator`.
I am not yet using these in the compiler or standard library to avoid a need for a zig1.wasm update.
Zig 0.14.0 extends the "enum literal" syntax (`.foo`) to provide a new feature, known as "decl literals". Now, an enum literal `.foo` doesn't necessarily refer to an enum variant, but, using \[Result Location Semantics\]\(langref link\), can also refer to any declaration on the target type. For instance, consider the following example:
```zig
const S = struct {
x: u32,
const default: S = .{ .x = 123 };
};
test "decl literal" {
const val: S = .default;
try std.testing.expectEqual(123, val.x);
}
const …
```
=> compiler: implement decl literals

lib/std/fmt.zig
Before, this function would always format 0 as "0B" regardless of the float precision option. This commit makes it consistent with everything else, and replaces a reachable `unreachable` with a panic instead. (It is reachable with high precision values).
=> make formatSizeImpl's zero case respect options

lib/std/crypto/ml_kem.zig
=> `std.crypto.ml_kem`: Reduce test iteration counts from 100 to 10.

src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, src/codegen/llvm/bindings.zig, src/target.zig, src/zig_llvm.cpp, src/zig_llvm.h
Closes #21238
This PR also now sets the module flag behaviors to match what LLVM and clang does, before it set everything to warning
=> LLVM: Set module flags through Builder instead of LLVM API bindings

lib/std/zig/BuiltinFn.zig, test/behavior/defer.zig
Consequently, `AstGen.ret()` now passes the error code to `.defer_error_code`. Previously, the error union value was passed.
closes #20371
=> AstGen: update @errorCast to maybe eval to err

src/glibc.zig, src/link/Elf.zig
Closes #20919.
```console
❯ zig4 cc system.c -target x86_64-linux-gnu.2.33
❯ ldd a.out
linux-vdso.so.1 (0x00007ffc0ba83000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x0000795644147000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000795643e00000)
/lib64/ld-linux-x86-64.so.2 (0x0000795644181000)
❯ zig4 cc system.c -target x86_64-linux-gnu.2.34
❯ ldd a.out
linux-vdso.so.1 (0x00007ffd4eb0f000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000075bec1200000)
/lib64/ld-linux-x86-64.so.2 (0x000075bec14ba000)
```
See: https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html (note: this includes librt too, despite it not being mentioned)
=> `glibc`: Avoid building and linking stub libraries that were emptied in 2.34

lib/std/Target.zig, lib/std/elf.zig
Based on:
* `include/elf/common.h` in binutils
* `include/uapi/linux/elf-em.h` in Linux
* https://www.sco.com/developers/gabi/latest/ch4.eheader.html
I opted to use the tag naming of binutils because it seems to be by far the most complete and authoritative source at this point in time.
=> `std.elf`: Bring the `EM` enum up to date.

lib/std/base64.zig
Hello,
The current base64 interface only allows encoding to slices, making it impractical (although not impossible) to use when encoding dynamically to a document (such as a json string, as an example).
This PR adds the `encodeWriter` API to `Base64Encoder`, relying on the destination having the `writeAll` interface of `Writer`. As it is possible to encode base64 data by chunks of 3 bytes, it progressively encodes the source data in the stream without unnecessary heap allocations.
=> stdlib : base64 encode to writer

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
Closes #21311
The sign of the result `r` needs to be initialized before the correction `r.addScalar(r.toConst(), -1)`, or the intended end result could be off by 2 (depending on the original sign of `r`).
=> std.math.big.int: fix shiftRight sign handling

src/Package/Fetch.zig
Closes #21314
This allows the package manger to download tar.gz bitbucket urls.
I've verified that this works for the url in the linked issue.
=> package-manager: add application/x-tar-gz mime type

lib/libc/glibc/sysdeps/s390/s390-32/start-2.33.S, lib/libc/glibc/sysdeps/s390/s390-32/start.S, lib/libc/glibc/sysdeps/s390/s390-64/crti.S, lib/libc/glibc/sysdeps/s390/s390-64/start-2.33.S, lib/libc/glibc/sysdeps/s390/s390-64/start.S
This should be reverted with LLVM 20. PRs that add the missing functionality:
* https://github.com/llvm/llvm-project/pull/107032
* https://github.com/llvm/llvm-project/pull/107038
With this patch plus #21037 and #21195, this now works:
```console
❯ zig4 cc main.c -target s390x-linux-gnu
❯ qemu-s390x -L /opt/glibc/s390x-linux-gnu ./a.out
hello world
```
Next step is adding the `std.os.linux` arch bits and Zig should have ~full support for s390x.
=> `glibc`: Patch to work around missing features in LLVM's s390x assembler.

src/target.zig, test/behavior/union.zig, test/behavior/vector.zig, test/tests.zig
See commit messages and comments.
The main motivators for this change are to make it so that you can actually build binaries for `powerpc64-linux-none`, and to make it so we have CI coverage for big-endian PPC64.
=> Force ELFv2 for PPC64 and add `powerpc64-linux-(none,musl)` to CI

lib/libc/glibc/sysdeps/arc/bits/endianness.h, lib/libc/glibc/sysdeps/arc/entry.h, lib/libc/glibc/sysdeps/arc/start-2.33.S, lib/libc/glibc/sysdeps/arc/start.S, lib/libc/glibc/sysdeps/csky/abiv2/start-2.33.S, lib/libc/glibc/sysdeps/csky/abiv2/start.S, lib/libc/glibc/sysdeps/csky/bits/endianness.h, src/glibc.zig
* Fix the `-frounding-math` warning for real this time.
* Fix the `lgammal` duplicate symbol issue.
* Add arc and csky start files for glibc 2.40 and <= 2.33.
* Set asm and include paths for all targets supported by `std.zig.target`.
Closes #14118.
Closes #20376.
Closes #21076.
=> `glibc`: Some bug fixes, plus arc and csky start files

lib/std/start.zig, src/Compilation.zig, src/musl.zig
Now we can actually build both Zig and (musl) C programs for these.
I'll probably find time to get the test suite passing and added to CI after LLVM 19.
=> Some fixes for `thumb-linux-*` support

lib/std/dynamic_library.zig, lib/std/os/linux.zig, lib/std/os/linux/riscv32.zig, lib/std/posix/test.zig, lib/std/time.zig, src/codegen/llvm.zig
With this, the full test suite passes with LLVM 19 for `riscv32-linux-(none,musl,gnu)`. I won't enable it in CI until we've done the LLVM upgrade though.
=> More `riscv32-linux` port work

lib/std/Thread.zig, lib/std/os/linux/sparc64.zig
Assemblers suck. :neutral_face:
=> `std`: Fix assembler comment syntax for sparc.

test/behavior/vector.zig
=> `test`: Re-enable `vector shift operators` and `vector reduce operation`

src/arch/mips/abi.zig, src/codegen/llvm.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig
This greatly improves ABI compatibility for mips and mipsel.
```
❯ ./stage4/bin/zig test -lc test/c_abi/main.zig test/c_abi/cfuncs.c -target mips-linux -mcpu mips32r2+soft_float --test-cmd qemu-mips --test-cmd-bin 2>&1 | grep passed
49 passed; 15 skipped; 0 failed.
❯ ./stage4/bin/zig test -lc test/c_abi/main.zig test/c_abi/cfuncs.c -target mips-linux -mcpu mips32r2+soft_float --test-cmd qemu-mips --test-cmd-bin -O ReleaseFast 2>&1 | grep passed
49 passed; 15 skipped; 0 failed.
❯ ./stage4/bin/zig test -lc test/c_abi/main.zig test/c_abi/cfuncs.c -target mipsel-linux -mcpu mips32r2+soft_float --test-cmd qemu-mipsel --test-cmd-bin 2>&1 | grep passed
49 passed; 15 skipped; 0 failed.
❯ ./stage4/bin/zig test -lc test/c_abi/main.zig test/c_abi/cfuncs.c -target mipsel-linux -mcpu …
```
=> mips: Fix C ABI compatibility

src/Zcu/PerThread.zig
When `ensureCauAnalyzed` fails, it adds the anal_unit to the transitive failures, so we don't need to do anything here. The errors will be handled after this function returns.
fixes #21352
=> comp: `populateTestFunctions` shouldn't bubble up `AnalysisFail`

lib/std/zig/AstGen.zig, test/cases/compile_errors/capture_by_ref_discard.zig
closes #21356
is it normal to make helper functions for repeated errors like this? its small but it feels wrong having the same thing pasted so many times
=> add error for discarding if/while pointer capture

ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh, lib/std/hash_map.zig, lib/std/multi_array_list.zig, src/InternPool.zig, src/arch/aarch64/CodeGen.zig, src/arch/aarch64/Emit.zig, src/arch/arm/CodeGen.zig, src/arch/arm/Emit.zig, src/arch/riscv64/CodeGen.zig, src/arch/riscv64/Emit.zig, src/arch/sparc64/CodeGen.zig, src/arch/sparc64/Emit.zig, src/arch/wasm/CodeGen.zig, src/arch/wasm/Emit.zig, src/arch/x86_64/CodeGen.zig, src/arch/x86_64/Emit.zig, src/codegen.zig, src/link.zig, src/link/Coff.zig, src/link/Dwarf.zig, src/link/Elf/ZigObject.zig, src/link/MachO/ZigObject.zig, src/link/Plan9.zig, src/link/Wasm/ZigObject.zig, test/src/Debugger.zig
This reaches (more than) feature parity with the `zig` and `zig.std` categories of `tools/lldb_pretty_printers.py`.
=> Dwarf: implement more decls

doc/langref/test_tagged_union.zig
Going through the reference, I wonder if it's better to leave off the explicit type since we can use literals and the example is calling out coercing. I think this is more like what a programmer would do in real code, and it looks better. Tested.
=> remove explicit ComplexTypeTag from switch

test/behavior/align.zig, test/behavior/atomics.zig, test/behavior/basic.zig, test/behavior/bitcast.zig, test/behavior/call.zig, test/behavior/floatop.zig, test/behavior/math.zig, test/behavior/shuffle.zig, test/behavior/threadlocal.zig, test/behavior/vector.zig
Closes #10627.
Closes #12013.
Closes #18034.
These pass for me on Linux at least; let's see what macOS and Windows say.
=> `test`: Re-enable a bunch of behavior tests with LLVM.

lib/std/zig/AstGen.zig, test/behavior/switch.zig
`break`ing from something which isn't a loop should always be opt-in. This was a bug in #21257.
=> AstGen: do not allow unlabeled `break` to exit a labeled switch

src/Package/Fetch.zig
For instance, the official download site for libvterm uses this MIME type for tar.gz tarballs.
=> Package.Fetch: add another non-standard Content-Type

lib/std/start.zig
0ecc6332b4eb1ced547ffa38f57471134aaa4d13 improved things for thumb2, but thumb1 has a much smaller permissible instruction set. This commit makes that work.
=> `start`: Rewrite arm code to work for thumb1 too.

lib/std/ascii.zig
[Godbolt link](https://godbolt.org/z/sET64sr1Y)
Remove some extended instructions.
=> `std.ascii`: make `toLower` `toUpper` branchless

src/Sema.zig, src/arch/riscv64/CodeGen.zig, test/behavior/cast.zig, test/behavior/decl_literals.zig, test/behavior/optional.zig, test/behavior/struct.zig, test/behavior/union.zig
closes #21387
also added test coverage for optionals
=> make decl literals work with single item pointers

src/Sema.zig, test/behavior/try.zig
=> Sema: give `try` operand `error{}` result type in non-errorable functions

src/Sema.zig, test/behavior/maximum_minimum.zig
=> Sema: don't emit instruction when casting `@min`/`@max` result to OPV type

lib/std/Build.zig
This is an enhancement to the build system. There's no corresponding issue -- @andrewrk, I'll therefore wait for your approval on this one.
It seems reasonable and useful for packages to be allowed to expose arbitrary `LazyPath`s to dependants; for instance, an output file/dir from a `Step.Run`. I ran into this when helping @sphaerophoria make a package which exposes a bunch of Qt stuff by calling into CMake rather than porting the build system to Zig. You can also imagine situations in pure-Zig-land where this would be helpful; for instance, perhaps a package wants to expose a file containing some kind of generated JSON/ZON data (generated by a Zig program).
(Also, use decl literals for a couple of inits :D)
=> std.Build: allow packages to expose arbitrary LazyPaths by name

src/Sema.zig, src/Zcu/PerThread.zig, src/link/Dwarf.zig
Reverts a workaround in `src/link/Dwarf.zig`.
cc @jacobly0
=> compiler: always resolve field inits, remove unncecessary eager resolution

src/Sema.zig, src/Type.zig, src/Value.zig, test/behavior/math.zig, test/cases/compile_errors/comparing_against_undefined_produces_undefined_value.zig
I can't find a corresponding issue for this -- if anyone knows of any, note them down here and I'll close them with this PR.
=> Sema: return undefined on comparison of runtime value against undefined

lib/std/bit_set.zig
Which resulted in a confusing statement [in the documentation](https://ziglang.org/documentation/master/std/#std.bit_set.DynamicBitSet)
=> :memo: Comment (and docs) did not correspond to the actual code

README.md
Quick one-liner to bump README LLVM version now that llvm19 branch is merged.
=> doc: Bump LLVM version in README

lib/std/sort.zig
The current implementation of `equalRange` just calls `lowerRange` and `upperRange`, but a lot of the work done by these two functions can be shared. Specifically, each iteration gives information about whether the lower bound or the upper bound can be tightened. This leads to fewer iterations and, since there is one comparison per iteration, fewer comparisons.
Implementation adapted from [GCC](https://github.com/gcc-mirror/gcc/blob/519ec1cfe9d2c6a1d06709c52cb103508d2c42a7/libstdc%2B%2B-v3/include/bits/stl_algo.h#L2063).
This sample demonstrates the difference between the current implementation and mine:
```zig
fn S(comptime T: type) type {
return struct {
needle: T,
count: *usize,
pub fn order(context: @This(), item: T) std.math.Order {
context.count.* += 1;
return std.math.order(item, …
```
=> `std.equalRange`: Compute lower and upper bounds simultaneously

src/Sema.zig, test/cases/compile_errors/destructure_error_union.zig
Adds a helpful error note when an attempt is made to destructure an error union.
Before:
```shell
src/main.zig:6:31: error: type '@typeInfo(@typeInfo(@TypeOf(main.foo)).@"fn".return_type.?).error_union.error_set!main.foo__struct_1598' cannot be destructured
const bar, const baz = foo();
~~~^~
src/main.zig:6:26: note: result destructured here
const bar, const baz = foo();
~~~~~~~~~~~~~~~~~~~~~^~~~~~~
```
After:
```shell
src/main.zig:6:31: error: type '@typeInfo(@typeInfo(@TypeOf(main.foo)).@"fn".return_type.?).error_union.error_set!main.foo__struct_1598' cannot be destructured
const bar, const baz = foo();
~~~^~
src/main.zig:6:26: note: result destructured here
const bar, const baz = foo();
~~~~~~~~~~~~~~~~~~~~~^~~~~~~
src/main.zig:6:31: note: consider using 'try', 'catch', or 'if'
``` …
=> fix: Add error note when attempt is made to destructure error union

lib/libunwind/src/gcc_personality_v0.c, src/libunwind.zig
Notably, this fixes libunwind compilation for `thumb-windows-gnu`.
=> `libunwind`: Update `gcc_personality_v0.c` to LLVM 19.1.0.

lib/std/io/buffered_reader.zig
The current implementation of buffered_reader always reads from the unbuffered reader into the internal buffer, and then dumps the data onto the destination. This is inefficient, as sometimes it's possible to read directly into the destination. The current strategy generates more memory copies and unbuffered reads than necessary. This PR implements a 3-step algorithm to buffered_reader to resolve these problems.
=> Improve efficiency of buffered_reader.

lib/libc/glibc/sysdeps/mips/mips32/crtn.S, lib/libc/glibc/sysdeps/mips/mips64/n32/crtn.S, lib/libc/glibc/sysdeps/mips/mips64/n64/crtn.S, lib/libc/glibc/sysdeps/unix/mips/sysdep.h, lib/libc/musl/crt/mips/crtn.s, lib/libc/musl/crt/mips64/crtn.s
See: https://github.com/ziglang/zig/issues/21315
I [sent the musl patch upstream](https://www.openwall.com/lists/musl/2024/09/18/2). I won't bother upstreaming the glibc parts because I seriously doubt they'll accept it. In any case, this can of course be reverted when the LLVM assembler bug is fixed.
=> `libc`: Work around LLVM's misassembly of `j <reg>` on mips r6.

lib/zig.h
* Fill in the assembly for all (hardware) architectures that we support.
* For `zig_trap()`, match what GCC/Clang emit for `__builtin_trap()`, but deviate where necessary to produce `SIGILL`.
* For `zig_breakpoint()`, match what Clang emits for `__builtin_debugtrap()`.
* Remove the fallback paths as they were broken anyway and gave cryptic/unhelpful compile errors.
=> `zig.h`: Improve portability of `zig_trap()` and `zig_breakpoint()`.

lib/compiler_rt/common.zig, lib/compiler_rt/fixdfdi.zig, lib/compiler_rt/fixsfdi.zig, lib/compiler_rt/fixunsdfdi.zig, lib/compiler_rt/fixunssfdi.zig, lib/compiler_rt/floatdidf.zig, lib/compiler_rt/floatdisf.zig, lib/compiler_rt/floatundidf.zig, lib/compiler_rt/floatundisf.zig
These are necessary in addition to the usual ones. LLVM emits calls to both sets, for whatever reason.
With this and #21472, we can bootstrap for `thumb-windows-gnu`. (Whether the resulting binary works is a whole other question though...)
=> `compiler-rt`: Export extra soft float libcall names for `thumb-windows-gnu`.

lib/std/crypto/tls.zig, lib/std/crypto/tls/Client.zig
X25519MLKEM768 replaces X25519Kyber768Draft00 now that NIST has released ML-KEM.
IANA has assigned the codepoint 0x11ec:
https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8
Chrome and Firefox are planning to enable this in October.
=> Add post-quantum key agreement X25519MLKEM768

lib/std/process/Child.zig
memcpy requires non-overlapping arguments.
fifo.realign() handles this case correctly and tries to provide an optimized implementation.
This probably wasn't hit in practice, as, in a typical usage, fifo's head is not advanced.
=> fix IB in fifoToOwnedArrayList

lib/std/os/uefi/pool_allocator.zig
Fixes #21446
Both UefiPoolAllocator and UefiRawPoolAllocator were passing the value of `log2_ptr_align` directly to
`mem.alignAllocLen` which expects a alignment value.
I have removed these calls entirely because the value was thrown away regardless, and the alignment given is always valid (not that either resize could do anything about it).
=> uefi: erroneous alignment check in pool_allocator

src/Package/Manifest.zig, src/main.zig
=> fetch: Keep .lazy = true

lib/std/c/darwin.zig
addresses part of #21094
switch was missing else
this test now passes:
```zig
test {
_ = &std.c.THREAD_STATE_NONE;
}
```
=> fix THREAD_STATE_NONE on darwin

src/arch/mips/abi.zig
This fixes crashing std and compiler_rt tests.
ABI tests cannot be enabled for this because clang doesn't support `__int128` on mips(el).
=> mips: use byval for all integer types

lib/std/Build/Module.zig, lib/std/Build/Step/TranslateC.zig
`addIncludeDir` takes a string slice, and does not support LazyPath and other include dir params. To match with `Build.Module` and `Build.Step.Compile`, i've adapted the following definitions to TranslateC
- `addAfterIncludePath`
- `addSystemIncludePath`
- `addIncludePath` (changed from "dir" to "path" to match other apis)
- `addConfigHeader`
- `addSystemFrameworkPath`
- `addFrameworkPath`
possible solution for #20649, though motivated by my need to use addIncludePath but it taking a slice.
i haven't thoroughly tested these besides `addIncludePath` in my own project. i am assuming translate-c supports the same set of flags that `build-*` supports, and that the existing code for passing the flags works.
=> `std.Build.TranslateC`: replace `addIncludeDir` with variants with LazyPath/library names

lib/std/start.zig
If wanted stack size is `0` (effectively asking the system to use some sane default), the following `if` wont be true:
https://github.com/ziglang/zig/blob/085cc54aadb327b9910be2c72b31ea046e7e8f52/lib/std/start.zig#L550
so we wont `setrlimit()` and therefore dont need to `getrlimit()`
For the following test, the wanted stack size is set via `--stack 0`
Before:
```
$ zig build-exe hello.zig -O ReleaseFast -fsingle-threaded --stack 0
$ strace ./hello
execve("./hello", ["./hello"], 0x7ffe9784a320 /* 34 vars */) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x1001550, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x1001560}, NULL, 8) = 0
write(1, "Hello, World!\n", 14Hello, World!
)         = 14
exit(0) …
```
=> std.start: dont query stack limit for wanted stack size 0

lib/std/os/linux.zig
This is a breaking change which updates the `rtattr.type` from `IFLA` to `union { IFLA, IFA }`. `IFLA` is for the `RTM_*LINK` messages and `IFA` is for the `RTM_*ADDR` messages.
The declaration of IFA is based on linux-6.11(actually no updates after 5.18).
I am recently exploring the linux netlink api, and find that current definition of `std.os.linux.rtattr`  declares the `type` as `IFLA`, but actually it can also be `IFA`. For more, please refer to `man 7 rtnetlink`.
When the message type is `RTM_GETLINK` for instance, the `rtattr.type` is `IFLA`, when it is `RTM_GETADDR`, the `rtattr.type` should he `IFA` instead.
Part of my side project code here:
```zig
var msg_iter = try req.get(.RTM_GETADDR);
defer msg_iter.deinit();
while (try msg_iter.next()) |msg| {
if (msg.header.type != …
```
=> std.os.linux: extend rtattr.type to support IFA_*

lib/compiler/aro/aro/Compilation.zig, lib/compiler/aro/aro/target.zig, lib/compiler_rt/common.zig, lib/compiler_rt/emutls.zig, lib/std/Target.zig, lib/std/Target/Query.zig, lib/std/c.zig, lib/std/zig/LibCDirs.zig, src/codegen/llvm.zig, src/target.zig
`Abi.android` on its own is not enough to know whether soft float or hard float should be used. In the C world, `androideabi` is typically used for the soft float case, so let's go with that.
Note that Android doesn't have a hard float ABI for 32-bit Arm, so no `androideabihf`.
Closes #21488.
=> `std.Target`: Introduce `Abi.androideabi` to distinguish the soft float case.

test/tests.zig
Follow-up to #21261 actually enabling the tests.
=> `test`: Add `riscv32-linux-(none,musl,gnu)` triples for module tests.

lib/compiler/fmt.zig, lib/std/posix.zig, lib/std/zig/system.zig
This error occurs if the process to be read from or written to no longer exists.
Fixes #19875
=> std.posix: Added error message 'ProcessNotFound' for reading and writing in a Linux process

src/main.zig
gcc and clang both handle this flag with and without a space so it seems reasonable to replicate that
=> handle -x language flag without spaces

lib/std/zig/AstGen.zig, test/cases/compile_errors/minmax_missing_args.zig
The error message for too-few arguments provided to the builtin `@min` and `@max` functions currently has a hardcoded 0 as the provided number of arguments.
Using the example from #21549 
```zig
comptime { _ = @min(1); }
comptime { _ = @max(1); }
```
Before:
```shell
src/main.zig:1:16: error: expected at least 2 arguments, found 0
comptime { _ = @min(1); }
^~~~~~~
src/main.zig:2:16: error: expected at least 2 arguments, found 0
comptime { _ = @max(1); }
^~~~~~~
```
After:
```shell
src/main.zig:1:16: error: expected at least 2 arguments, found 1
comptime { _ = @min(1); }
^~~~~~~
src/main.zig:2:16: error: expected at least 2 arguments, found 1
comptime { _ = @max(1); }
^~~~~~~
```
Closes #21549
=> fix: print correct number of provided arguments in `@min`/ `@max` error message

lib/compiler_rt/aulldiv.zig, lib/compiler_rt/aullrem.zig, lib/std/Target.zig, lib/std/c.zig, lib/std/os/windows/tls.zig, lib/std/zig/LibCDirs.zig, lib/std/zig/LibCInstallation.zig, src/Compilation.zig, src/clang.zig, src/libcxx.zig, src/link/C.zig, src/link/Coff/lld.zig, src/main.zig, src/target.zig
https://llvm.org/docs/HowToBuildWindowsItaniumPrograms.html
This is a weird middle ground between `*-windows-gnu` and `*-windows-msvc`. It uses the C++ ABI of the former while using the C ABI and system libraries of the latter.
This PR just adds handling in all the obvious places. I wouldn't be surprised if there's still more work to do.
=> Initial port work for `*-windows-itanium` support.

lib/std/math/float.zig, lib/std/math/isnan.zig, test/behavior/bitcast.zig
This still leaves the `isSignalNan` test disabled for arm, aarch64, and powerpc, as well as the C backend, so #14366 should remain open.
=> Re-enable some tests that were disabled due to #14366

lib/std/c.zig
`std.os.linux.dev_t` for mips32 is `u64`, but glibc uses `u32`. The C header also doesn't actually use `dev_t` for these fields anyway.
Long term, I want to pull these basic types out of `std.os.linux`; they're a libc concept and are not always the same between glibc and musl.
Closes #21276.
=> `std.c`: Fix `Stat` struct layout for mips/mipsel with glibc.

lib/std/c.zig, lib/std/debug.zig, lib/std/os/linux.zig, lib/std/os/linux/tls.zig, lib/std/posix/test.zig, src/codegen/llvm.zig, test/tests.zig
Depends on #21037 to produce working `s390x-linux-gnu` binaries; `s390x-linux-none` and `s390x-linux-musl` work regardless.
ref: #21402
=> Get module tests passing for `s390x-linux` and add it to CI

doc/langref.html.in, lib/std/heap.zig, lib/std/mem.zig, lib/std/meta.zig, lib/std/tar.zig, lib/std/tar/writer.zig
All have been deprecated for over a year, so 0.10 release and older.
|deprecate date|Symbol                                  |
|-------------:|:---------------------------------------|
|oct 2020      |std.meta.refAllDecls                    |
|nov 2020      |std.meta.IntType                        |
|nov 2021      |std.heap.ThreadSafeFixedBufferAllocator |
|jan 2023      |std.meta.assumeSentinel                 |
|jun 2023      |std.mem.alignForwardGeneric             |
|jun 2023      |std.mem.alignBackwardGeneric            |
=> Remove old deprecated symbols in std

lib/std/Target.zig, lib/std/Target/propeller.zig, lib/std/builtin.zig, lib/std/elf.zig, src/Sema.zig, src/Type.zig, src/Zcu.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/target.zig
These cpu architectures allow targeting the Parallax Propeller 1 and Propeller 2, which are both very special microcontrollers with 512 registers and 8 cpu cores.
Resolves #21559
=> Adds new cpu architectures propeller1 and propeller2.

lib/compiler/build_runner.zig, lib/std/Build.zig
The dependency cache is shared amongst all Build objects. This is currently done by allocating a single instance and storing a reference to it in each Build object.  However, the Graph object already exists to host shared state so by moving it there we reuse the same pattern for shared state and avoid an extra object on the heap.
Allows Build.Graph to initialize dependency_cache with a default value.
=> Put dependency cache in graph

doc/langref.html.in, lib/std/Thread/Futex.zig, lib/std/Thread/ResetEvent.zig, lib/std/Thread/WaitGroup.zig, lib/std/atomic.zig, lib/std/zig/AstGen.zig, lib/std/zig/AstRlAnnotate.zig, lib/std/zig/BuiltinFn.zig, lib/std/zig/Zir.zig, lib/zig.h, src/Air.zig, src/Air/types_resolved.zig, src/Liveness.zig, src/Liveness/Verify.zig, src/Sema.zig, src/arch/aarch64/CodeGen.zig, src/arch/arm/CodeGen.zig, src/arch/riscv64/CodeGen.zig, src/arch/sparc64/CodeGen.zig, src/arch/wasm/CodeGen.zig, src/arch/x86_64/CodeGen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/print_air.zig, src/print_zir.zig, test/behavior/atomics.zig, test/behavior/builtin_functions_returning_void_or_noreturn.zig, test/cases/compile_errors/atomic_orderings_of_fence_Acquire_or_stricter.zig
closes #11650
In Zig 0.14, `@fence` has been removed. `@fence` was provided to be consistent with the C11 memory model, however, it complicates semantics by modifying the memory orderings of all [previous](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence#Atomic-fence_synchronization) and [future](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence#Fence-atomic_synchronization) atomic operations. This creates unforeseen constraints that are [hard to model in a sanitizer](https://github.com/google/sanitizers/issues/1415). Fences can be substituted by either upgrading atomic memory orderings or adding new atomic operations.
The most common use cases for `@fence` can be replaced by utilizing stronger memory orderings or by introducing a new atomic variable.
The most …
=> remove `@fence`

lib/std/c.zig
=> `std.c`: Make `dlopen()` accept null for the `path` parameter.

lib/compiler/objcopy.zig, lib/std/Build/Step/ObjCopy.zig
Adds support for --add-section, --set-section-alignment and --set-section-flags to both the zig objcopy CLI and std.Build.Step.ObjCopy.
Example usage to make a copy of ls with a copy of itself inside a the new section ".abc":
`zig objcopy ./ls ./ls_out --add-section ".abc=./ls" --set-section-alignment ".abc=256" --set-section-flags ".abc=data,readonly"`
Closes #19009
=> zig objcopy: support --add-section

lib/compiler/objcopy.zig
Fix suggested by @cclin0816. I couldn't see any obvious reason why this would be wrong.
Closes #20019.
=> `objcopy`: Use `p_paddr` from `PT_LOAD` even if zero.

src/codegen/llvm.zig
Addresses this problem: https://github.com/ziglang/zig-bootstrap/issues/102#issuecomment-2303243603
=> `llvm`: Implement sub-architecture translation in `targetTriple()`.

lib/std/c/darwin.zig
Fixes the typo in `lib/std/c/darwin.zig`.
Part of https://github.com/ziglang/zig/issues/21094
=> std: fix typo in darwin segset_t

lib/std/meta.zig
I'm using `std.meta.DeclEnum` with a struct that may be empty, current implementation fails with:
```
error: overflow of integer type 'usize' with value '-1'
.tag_type = std.math.IntFittingRange(0, fieldInfos.len - 1),
```
=> Prevent failure with empty struct in `std.meta.DeclEnum`

lib/std/Target.zig, lib/std/zig/system.zig
I went and collected all the known dynamic linker paths from GCC, Clang, and a few other places online, and then rewrote this function. Also moved some OS prongs for which I concluded with a reasonable degree of confidence that the OS doesn't have a standard dynamic linker path.
Recommend reviewing this one by just looking at the new implementation rather than the diff.
(Almost all of the ABI-related TODOs I'm adding here can be addressed by #20690.)
=> `std.Target`: Rewrite DynamicLinker.standard() and fill in some missing details.

build.zig, lib/std/io.zig, test/incremental/add_decl, test/incremental/add_decl_namespaced, test/incremental/delete_comptime_decls, test/incremental/hello, test/incremental/modify_inline_fn, test/incremental/move_src, test/incremental/remove_enum_field, test/incremental/type_becomes_comptime_only, test/incremental/unreferenced_error, test/tests.zig, tools/incr-check.zig
This does exactly what the title says. `zig build test` now includes `zig build test-incremental`, which runs `incr-check` over every case in `test/incremental/` (we expect exit code 0 from `incr-check`). In addition, `incr-check` undergoes several enhancements:
* Progress output now includes the target being tested
* External executors are used for emitted binaries which cannot be executed natively
* (If no executor exists, execution of the binary is silently skipped)
* The temporary directory created by `incr-check` is removed by default (both on success and on error); it can be retained for debugging purposes with the `--preserve-tmp` flag
All of the incremental test cases now include the `x86_64-windows-cbe` target too, just for a little more coverage -- see the corresponding commit …
=> incr-check enhancements, and CI for incremental test cases

lib/std/os/linux/powerpc64.zig, lib/std/start.zig
With this PR **and** a few steps not included in this PR, stage3 compiler builds on an alpine ppc64le VM with system tools (gcc compiler and binutils linker).
---
1. The following extra patch is required to get to stage3 but is **not** part of this PR.
1. build stage2 with `-Os` option because apparently system assembler cannot handle a larger unoptimized object. Not part of PR because this is a hack to get around a system limitation. Possibly in the future our c-backend will be able to split .c output and that would be one way to solve this issue.
2. need a `update-stage1` for some zig master commits that have accumulated since last update
3. hack zig to understand page size is 64K. Not part of PR because #20511 will fix it.
<details>
<summary>diff</summary>
```diff
diff --git …
```
=> ppc64: get further along into system bootstrap

lib/std/Build.zig
Also adds support for `[]const LazyPath` in a similar vein, and refactors a few other bits of code.
The main purpose of this addition is to enable passing `LazyPath`s from depender to dependency, ie say you generate a directory via some `Run` step, and you want to pass that as an argument to your dependency, which will use it as, say a search path for an executable, static resources, or what have you.
I've wanted/needed this on a few occasions. It can sort of be hacked in by exposing the functionality via `@import("dep-name")`, but it would be great to have this as a native capability.
=> Build: Add `option(LazyPath, ...)` support

lib/std/fs/Dir.zig, lib/std/os/wasi.zig
Fixes #14324
No testing performed. Original issue says "you can see this plainly in the source" -- agreed.
=> Create/open file on WASI targets should have POLL_FD_READWRITE rights

lib/std/Target.zig
This matches avr-gcc's ABI.
Note that this makes us diverge from Clang 19's AVR ABI. But we already did that in other ways for AVR, so I don't consider that a significant issue. (Right now, we're in a weird middle-ground where we don't fully match Clang *or* avr-gcc.) I'm [working on](https://github.com/llvm/llvm-project/pull/111290) getting Clang to match avr-gcc as well, which should hopefully make it into Clang 20.
Also worth noting:
https://github.com/ziglang/zig/blob/d5c9d8529534745c9feae6b67cdc01d53f11a0d9/src/Type.zig#L1639-L1641
=> `std.Target`: Fix `cTypePreferredAlignment()` to always return 1 for avr.

src/link/Elf.zig
Sourced from binutils/bfd (`ELF_MAXPAGESIZE`).
[LLD differs on some of these](https://github.com/search?q=repo%3Allvm%2Fllvm-project+path%3Alld%2FELF+defaultMaxPageSize&type=code), and [mold differs further](https://github.com/search?q=repo%3Arui314%2Fmold%20path%3Aelf%20page_size&type=code). I don't really know what to make of that. Following binutils seems safest...?
=> `link.Elf`: Fix page size calculation for more architectures.

src/Sema.zig, test/cases/compile_errors/comptime_var_referenced_at_runtime.zig, test/cases/compile_errors/comptime_var_referenced_by_decl.zig
Just a few missing calls to `validateRuntimeValue`, plus missing handling for the `variable` case when checking whether a declaration's resolved value references comptime-mutable memory.
=> Sema: add a few missing runtime value validations

src/arch/wasm/CodeGen.zig, test/behavior/math.zig
Enabled some additional tests in `math.zig`, that were already passing.
=> stage2-wasm: airRem + airMod for floats

test/standalone/empty_env/build.zig
Closes #3168
The problem seems to be ConEmu setting environment variables before executing the test process (the test passes when run in Windows CMD). These variables can differ depending on user configuration too. This PR skips the test if the host environment has the [`ConEmuHWND`](https://conemu.github.io/en/ConEmuEnvironment.html) variable set; i.e. we're running inside a ConEmu terminal session.
=> skip `standalone/empty_env` test in ConEmu terminal sessions

lib/std/Build/Step/Compile.zig, src/Compilation.zig, src/link.zig, src/link/C.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/Elf/Archive.zig, src/link/Elf/LdScript.zig, src/link/Elf/Object.zig, src/link/Elf/SharedObject.zig, src/link/Elf/relocatable.zig, src/link/MachO.zig, src/link/MachO/load_commands.zig, src/link/NvPtx.zig, src/link/Plan9.zig, src/link/SpirV.zig, src/link/Wasm.zig, test/link/elf.zig
The goal is to minimize as much as possible how much logic is inside flush(). So let's start by moving out obvious stuff.
* No longer create 2 unnecessary tables for rpaths
* No longer create unnecessary array list for positionals
* No longer make unnecessary file system reads for object files
=> link.Elf: reduce flush logic (rpaths, isObject fs reads)

src/link/Elf/Atom.zig, src/link/Elf/Object.zig
The initAtoms function now only uses the `elf_file` parameter for reporting linker error messages, making it easier to see that the function has no data dependencies other than the Object struct itself, making it easier to parallelize or otherwise move that logic around.
Also removed an indirect call via `addExtra` since we already know the atom's file is the current Object instance. All calls to `Atom.addExtra` should be audited for similar reasons.
Also removed unjustified use of `inline fn`.
=> link.Elf.Object.initAtoms: reduce state access and indirection

src/link/MachO.zig, src/link/MachO/Atom.zig, src/link/MachO/InternalObject.zig, test/link/macho.zig
=> link.MachO: fix reporting undefined implicit symbols and fix a typo in InternalObject.addObjcMethnameSection method

src/link/Dwarf.zig, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/AtomList.zig, src/link/Elf/Object.zig, src/link/Elf/Symbol.zig, src/link/Elf/ZigObject.zig, src/link/Elf/file.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig
In order to track if we need to reparse paths and objects (including relocatables, archives and shared objects) I've decided to add the paths, files, and some flags to local cache but I haven't used the frontend mechanism to achieve this, well not yet anyhow since I wasn't sure how to best go about it. I would appreciate input on this especially from @andrewrk and @mlugg. Next in order to detect if we are running the link from scratch (i.e., if we should invalidate the cache) I'm committing a random uuid-like value for the linker run. Again, this is very much a PoC so any feedback and suggestions are more than welcome.
Now onto progress report. I hear from @mlugg that apparently with this patch incremental works enough to do some basic incremental updates on Andrew's tetris clone. I have …
=> elf: more incremental progress

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, src/print_zir.zig, test/behavior/array.zig, test/cases/compile_errors/splat_bad_result_type.zig, test/cases/compile_errors/splat_result_type_non_vector.zig
=> Sema: implement @splat for arrays

lib/std/os/linux.zig
Fixes a "write to reserved register r7" compile error for `thumbeb-linux-*`.
=> `std.os.linux`: Use the Thumb-specific syscall helpers for thumbeb too.

lib/libc/musl/crt/arm/crti.s
See upstream patch: https://www.openwall.com/lists/musl/2024/10/10/4
=> `musl`: Align `_init`/`_fini` symbols correctly on arm.

lib/std/builtin.zig
This is specified in LLVM. It is the same as riscv64.
=> Add loongarch valist support

lib/std/os/linux/IoUring.zig
InvalidVersion might get thrown by skipKernelLessThan, due to some kernel versions not being SemVer compliant.
Which result in a bunch of InvalidVersion errors during unit tests:
```
error: 'os.linux.IoUring.test.accept/connect/send_zc/recv' failed: /home/jiboo/Projects/zig-fork/lib/std/SemanticVersion.zig:117:73: 0x1be34e3 in parse (test)
for (id) |c| if (!std.ascii.isAlphanumeric(c) and c != '-') return error.InvalidVersion;
^
/home/jiboo/Projects/zig-fork/lib/std/os/linux/IoUring.zig:3506:5: 0x2bc9aea in test.accept/connect/send_zc/recv (test)
try skipKernelLessThan(.{ .major = 6, .minor = 0, .patch = 0 });
^
```
Here's the result of my `uname -r`: `6.8.9-300.fc40.x86_64` the underscore makes this non compliant, I'm don't believe I've changed anything and I'm on a vanilla Fedora 40 …
=> IoUring: fix an issue in tests where InvalidVersion might get thrown

CMakeLists.txt
`check_pie_supported` only uses the `OUTPUT_VARIABLE` to to signify errors if PIE is actually supported is signaled by `CMAKE_<lang>_LINK_PIE_SUPPORTED`.
Checking if `OUTPUT_VARIABLE` is empty is not enough either since the check is bypassed if its results are cached but the output variable is not cached.
=> cmake: correct PIE support detection, add error output for debugging

CMakeLists.txt, lib/std/multi_array_list.zig, src/link/Elf.zig, src/link/Elf/LinkerDefined.zig, src/link/Elf/Merge.zig, src/link/Elf/Object.zig, src/link/Elf/Symbol.zig, src/link/Elf/ZigObject.zig, src/link/Elf/eh_frame.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig
And some bonus commits; see commit messages for more details.
Based on #21654.
=> link.Elf: fix phdr_gnu_stack_index not included in sortPhdrs

src/Compilation.zig, src/link.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/Elf/Atom.zig, src/link/Elf/Object.zig, src/link/Elf/eh_frame.zig, src/link/Elf/relocatable.zig, src/link/MachO.zig, src/link/MachO/Archive.zig, src/link/MachO/Atom.zig, src/link/MachO/ZigObject.zig, src/link/MachO/relocatable.zig, src/link/Wasm.zig, src/link/Wasm/Object.zig
By organizing linker diagnostics into this struct, it becomes possible to share more code between linker backends, and more importantly it becomes possible to pass only the Diag struct to some functions, rather than passing the entire linker state object in. This makes data dependencies more obvious, making it easier to rearrange code and to multithread.
Also fix MachO code abusing an atomic variable. Not only was it using the wrong atomic operation, it is unnecessary additional state since the state is already being protected by a mutex.
This is only one commit, based on #21666.
=> link: consolidate diagnostics

build.zig, ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh
This PR requires the `superhtml` tool to be installed on the CI machine, I'm not sure how to approach that.
=> Replace tidy with superhtml as HTML validator

src/link/MachO/Object.zig
Some compilers such as Go reference the end of a section (addr + size) which cannot be contained in any non-zero atom (since then this atom would exceed section boundaries). In order to facilitate this behaviour, we create a dummy zero-sized atom at section end (addr + size).
Closes #20243
=> macho: create dummy atom of size 0 marking the end of a section

lib/compiler/objcopy.zig, lib/std/Build/Cache.zig, lib/std/dynamic_library.zig, lib/std/elf.zig, lib/std/os/linux/vdso.zig, src/Compilation.zig, src/link.zig, src/link/Elf.zig, src/link/Elf/Archive.zig, src/link/Elf/Atom.zig, src/link/Elf/LdScript.zig, src/link/Elf/Object.zig, src/link/Elf/SharedObject.zig, src/link/Elf/Symbol.zig, src/link/Elf/ZigObject.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig, src/link/MachO.zig, src/link/MachO/Archive.zig, src/link/MachO/relocatable.zig
Make shared_objects a StringArrayHashMap so that deduping does not need to happen in flush. That deduping code also was using an O(N^2) algorithm, which is not allowed in this codebase. There is another violation of this rule in resolveSymbols but this commit does not address it.
This required reworking shared object parsing, breaking it into independent components so that we could access soname earlier.
Shared object parsing had a few problems that I noticed and fixed in this commit:
* Many instances of incorrect use of align(1).
* `shnum * @sizeOf(elf.Elf64_Shdr)` can overflow based on user data.
* `@divExact` can cause illegal behavior based on user data.
* Strange versyms logic that wasn't present in mold nor lld. The logic was not commented and there is no git blame information in …
=> link.Elf: eliminate an O(N^2) algorithm in flush()

lib/std/Target/Query.zig
=> std.Target.Query: fix compilation error

doc/langref.html.in, doc/langref/test_packed_struct_equality.zig, src/Type.zig, src/arch/riscv64/CodeGen.zig, src/codegen/llvm.zig, test/behavior/packed-struct.zig, test/cases/compile_errors/packed_struct_comparison.zig
=> implement packed struct equality

src/glibc.zig
This prevents LLVM from...cleverly...merging all of the global variable stub symbols that we emit under certain circumstances. This was observed in practice when using zig-bootstrap for `arm(eb)-linux-gnueabi(hf)`. zig-bootstrap'd compilers for those targets will now run.
Additionally, align stub symbols to the target word size. Ideally we'd like to use whatever alignment glibc actually ends up using in the real `libc.so.6`. But we don't really have a way of getting at that information at the moment, and it's not present in the abilist files. I haven't yet seen a symbol that wasn't word-aligned, though, so I think this should be good enough for 99% of symbols, if not actually 100%.
=> `glibc`: Emit some fill data for stub symbols, thus giving each a unique address.

lib/std/compress/zstandard/decode/block.zig, lib/std/compress/zstandard/decode/huffman.zig, lib/std/compress/zstandard/readers.zig, lib/std/io/bit_reader.zig, lib/std/io/bit_writer.zig, lib/std/io/test.zig
bit_reader and bit_writer have accumulated cruft from several Zig versions worth of semantics changes. I have rewritten them with the intention of enhancing readability, but have also made some additional modifications:
- Added a `readBitsTuple` method that returns the bits and bit count instead of taking an out pointer.
- Removed the ability to treat them as standard readers and writers, which I have no evidence was ever used and was of dubious utility.
- Modified the out pointer for bit counts, as well as the input bit count parameters, to be `u16` instead of `usize`.
=> Rewrite bit_reader and bit_writer to take advantage of current zig semantics and enhance readability

lib/compiler_rt/clear_cache.zig, lib/std/Target.zig, lib/std/Thread.zig, src/codegen/llvm.zig, test/llvm_targets.zig
* Adds loongarch32 handling where sensible.
* Fixes the LLVM data layout string to include `-n32:64` for loongarch64 and `-n32` for loongarch32.
* I also went ahead and extended the `f16` workaround in the LLVM backend to LoongArch. I resisted doing this previously since the `f16` issues were supposed to be fixed with LLVM 19. But since [that turned out not to be the case](https://github.com/ziglang/zig-bootstrap/commit/37b6c3d88ce12335d508975f02c364eb98842a9d), let's just work around it until LLVM 20 so porting effort can move along in other areas.
=> Some miscellaneous LoongArch port work

lib/compiler_rt/common.zig, src/codegen/llvm.zig, src/target.zig, test/tests.zig
Note that I'm not adding ILP32F/LP64F (hard `f32`, soft `f64`) to the test matrix. They work, but they're used extremely rarely, so I don't think it's worth wasting valuable CI resources on them. For perspective, glibc doesn't support them, and musl [needs a patch](https://www.openwall.com/lists/musl/2024/06/29/1) for them to work, so I doubt anyone cares much.
=> Fix some RISC-V ABI issues and add ILP32/LP64 (soft float) to module tests
