lib/std/Target.zig
This builds on 221bd829bcb4318be941a93029b9c12d8317845d with more research I did since for `test/llvm_targets.zig`.
=> `std.Target`: Make `Abi.default()` more smarter.

ci/aarch64-linux-debug.sh, ci/aarch64-linux-release.sh, ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh
This switches CI to a newer build of [qemu-static](https://github.com/ziglang/qemu-static) which notably includes [a patch](https://github.com/ziglang/qemu-static/commit/0f837ad708bbb47204d5ea33cc4df3b1a6fbcf69) for [this bug affecting aarch64_be](https://gitlab.com/qemu-project/qemu/-/issues/2580).
=> ci: Update to QEMU 9.1.0 in x86_64-linux scripts

doc/langref.html.in, lib/std/zig/AstGen.zig, lib/std/zig/AstRlAnnotate.zig, lib/std/zig/BuiltinFn.zig, test/behavior/struct.zig, test/behavior/union.zig, test/cases/compile_errors/invalid_field_type_usage.zig
Resolves: #21702
Zig 0.14.0 introduces the `@FieldType` builtin. This serves the same purpose as the `std.meta.FieldType` function: given a type and the name of one of its fields, it returns the type of that field.
```zig
const assert = @import("std").debug.assert;
test "struct @FieldType" {
const S = struct { a: u32, b: f64 };
comptime assert(@FieldType(S, "a") == u32);
comptime assert(@FieldType(S, "b") == f32);
}
test "union @FieldType" {
const U = union { a: u32, b: f64 };
comptime assert(@FieldType(U, "a") == u32);
comptime assert(@FieldType(U, "b") == f32);
}
test "tagged union @FieldType" {
const U = union(enum) { a: u32, b: f64 };
comptime assert(@FieldType(U, "a") == u32);
comptime assert(@FieldType(U, "b") == f32);
}
=> compiler: implement `@FieldType`

lib/std/debug/Dwarf/abi.zig
Needed for creating libraries that run both on physical Apple Watches and the watchOS simulator.
---
[Example Makefile](https://github.com/marionauta/zig-watchos-makefile/blob/main/Makefile)
While trying to build Zig code to run on the Apple Watch, Xcode requires the libraries to be in the following formats:
1. amd64 (aarch64) & x86_64 for the watchOS simulator.
2. amd64 (aarch64) & amd64_32 (aarch64_32) for a physical watchOS device.
This PR adds the `.watchos` os tag to the `.aarch64` architecture, mirroring both iOS and macOS. Runs with no problems.
Notes:
1. There we no changes needed for `x86_64`.
2. The `aarch64_32` architecture is exclusive to the Apple Watch and not supported by Zig, so I didn't add it. You can see in the linked `Makefile` that I first compiled Zig to LLVM …
=> `watchos`: add os to `aarch64` architecture

src/link/Coff.zig, test/standalone/c_compiler/build.zig, test/standalone/coff_dwarf/build.zig, test/standalone/load_dynamic_library/build.zig, test/standalone/shared_library/build.zig
Closes https://github.com/ziglang/zig/issues/16965
Closes https://github.com/ziglang/zig/issues/16959
Closes https://github.com/ziglang/zig/issues/16960
Closes https://github.com/ziglang/zig/issues/18427
As part of investigating a CI failure on aarch64-windows for https://github.com/ziglang/zig/pull/21758, I noticed that all the shared library tests were being skipped on either windows or aarch64-windows. I did some testing in an aarch64-windows VM, and noticed that the error happening here was a "Bad Image" error coming from the dll.
The way I figured this out was by removing each of the optional arguments from the linker line to see if I could get a different result. As it turned out, removing the -BASE:268435456 argument for the shared library caused the bug to go away. It turns out …
=> coff: fix incorrect default `image_base` values and re-enable shared library tests on Windows

test/behavior/align.zig, test/behavior/basic.zig, test/behavior/cast.zig, test/behavior/generics.zig, test/behavior/shuffle.zig
Closes https://github.com/ziglang/zig/issues/13679
Closes https://github.com/ziglang/zig/issues/19825
Closes https://github.com/ziglang/zig/issues/19824
Since I was set up to test on aarch64-windows as part of https://github.com/ziglang/zig/pull/21767, I checked other tests  that were being skipped. I've re-enabled these now that they pass.
=> tests: re-enable tests that now pass on aarch64-windows

lib/std/builtin.zig, src/InternPool.zig, src/Sema.zig, src/Value.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/codegen/llvm.zig, src/codegen/llvm/Builder.zig, test/cases/compile_errors/builtin_extern_in_comptime_scope.zig, test/standalone/extern/build.zig, test/standalone/extern/main.zig, test/standalone/extern/shared.c
Closes https://github.com/ziglang/zig/issues/15903
Closes https://github.com/ziglang/zig/issues/21749
This change adds `is_dll_import: bool` to the options to `@extern`. This has the effect of setting the LLVM DLL Storage Class of the global to `dllimport`, which then generates the correct code to load from such a symbol at runtime - by prepending `__imp_` to the symbol name and loading from that symbol instead. 
This is necessary for the `msvc` ABI, as the "auto imports" features that make this work on `-gnu` are MinGW specific and don't exist there (see https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fauto-import).
As part of this change I also added an error note that explains why you can't place an `@extern` that uses either `is_thread_local` or …
=> Add `is_dll_import` to @extern, to support `__declspec(dllimport)` with the MSVC ABI

lib/std/Progress.zig, src/link/MachO.zig, src/link/MachO/relocatable.zig
thread-sanitizer reports data races here when running test-link. I tried
only removing the ones that triggered races, but after 10 back and
forths with the compiler and tsan, I got impatient and removed all of
them.
next time, let's be sure the test suite runs tsan-clean before merging
any changes that add parallelism.
after this commit, `zig build test-link` completes without any tsan
warnings.
closes #21778
=> link.MachO: remove buggy multi-threading

src/Sema.zig, test/cases/compile_errors/ret_coercion_error_in_generic_fn_called_from_non_fn_scope.zig
=> Sema: fix check for whether current AnalUnit is a test function

lib/std/os/uefi.zig
Much like in #21615 there seems to be nothing in CI that covers substantial parts of `std.os.uefi` and it will keep regressing unless that's addressed.
=> std.os.uefi: Fix calling convention build error

lib/compiler/build_runner.zig, lib/std/Build/Watch.zig
=> Build Runner: Implement File System Watching for kqueue

lib/std/os/linux.zig
`fgetxattr` now doesn't accidentally call `lgetxattr`, which fixes #21785. Also tweaked the argument types, so file descriptors can be passed as they normally would be for other syscalls, and `*setxattr` values have the same type as `*getxattr`.
=> Fix up Linux xattr syscalls

src/link/Elf.zig
fixes e567abb339e1edaf5a3c86fe632522a3b8005275 "rework linker inputs" 
closes https://github.com/ziglang/zig/issues/21801
=> link/Elf.zig: ensure capacity before appending linker args.

src/Sema.zig, test/cases/compile_errors/if_condition_is_bool_not_int.zig
Also, start using labeled switch statements when dispatching maybe-runtime instructions like condbr to comptime-only variants like condbr_inline.
This can't be merged until we get a zig1.wasm update due to #21385.
Resolves: #21405
=> Sema: add missing coercion to `bool` for `condbr_inline`

lib/std/zig/BuiltinFn.zig
This field isn't used anymore and was related to old RLS.
cc @mlugg
=> remove unused `needs_mem_loc` field

lib/std/builtin.zig, src/codegen/llvm.zig
closes #20671
closes #21805 
anyone know of other issues this closes?
adds support for:
- `riscv64_interrupt`
- `riscv32_interrupt`
- `mips_interrupt`
- `mips64_interrupt`
- `arm_interrupt`
- `csky_interrupt`
=> implement new interrupt calling conventions in the llvm backend

stage1/wasi.c, stage1/wasm2c.c
I took a slightly unconventional approach to detecting endianness here. We have no compiler/platform-specific preprocessor checks in the stage1 C code today, and I think that's a property worth maintaining.
With this patch, I'm able to successfully run `s390x-linux-gnu-gcc ../stage1/wasm2c.c -o zig-wasm2c && qemu-s390x ./zig-wasm2c ../stage1/zig1.wasm zig1.c && s390x-linux-gnu-gcc -std=c99 -Os zig1.c ../stage1/wasi.c -o zig1 && qemu-s390x ../lib zig1 build-exe -ofmt=c -lc -OReleaseSmall ... -femit-bin=zig2.c`.
=> `wasm2c`: Add big endian support.

lib/std/Thread.zig
seems to work fine now, at least locally, without the cast
=> fix todo in thread.zig

CMakeLists.txt
This reverts commit 3dd6456c0f8d50801d366062bcf5894bb5d9e7ac.
We didn't end up using this after all.
=> Revert "cmake: Add a `ZIG2_NO_RTLIB` option for building zig2 without compiler-rt."

lib/std/start.zig, src/Sema.zig, src/Zcu.zig, src/codegen/spirv.zig, src/link/Dwarf.zig, src/link/SpirV.zig, src/link/SpirV/lower_invocation_globals.zig, src/target.zig, test/cases/compile_errors/explicit_error_set_cast_known_at_comptime_violates_error_sets.zig, test/cases/compile_errors/implicit_cast_of_error_set_not_a_subset.zig, test/cases/compile_errors/int_to_err_non_global_invalid_number.zig, test/cases/compile_errors/spirv_merge_logical_pointers.zig, test/cases/spirv_mergable_pointers.zig, test/src/Cases.zig
This PR adds some more Vulkan stuff, including but not limited to generating testing entrypoints for Vulkan. I've also updated the [zig spir-v test executor](https://github.com/Snektron/zig-spirv-test-executor) to support executing these types of tests - they work in a similar way as the OpenCL testing stuff. Additional changes:
* Use `builtin.stage2_spirv64` instead of `builtin.cpu.arch` in start.zig. The latter tries to lower `builtin.cpu` at runtime (longstanding Zig bug), and that structure is currently not yet supported under the Vulkan OS.
* Avoid the usual start.zig exporting mechanism with vulkan, only automatically export `pub fn main`.
* Fix up calling conventions with Vulkan. `spirv_kernel` now emits GLCompute (Vulkan compute shader) instead of Kernel (OpenCL kernel).
* Make …
=> spirv: vulkan setup

src/link/Elf/Object.zig, src/link/Elf/eh_frame.zig, src/link/Elf/relocatable.zig, test/link/elf.zig
According to a comment in mold, this is the expected (and desired) condition by the linkers, except for some architectures (RISCV and Loongarch) where this condition does not have to upheld.
If you follow the changes in this patch and in particular doc comments I have linked the comment/code in mold that explains and implements this.
I have also modified `testEhFrameRelocatable` test to now test both cases such that `zig ld -r a.o b.o -o c.o` and `zig ld -r b.o a.o -o d.o`. In both cases, `c.o` and `d.o` should produce valid object files which was not the case before this patch.
=> link/Elf: ensure we always sort all relocations by r_offset in -r mode

lib/std/fmt.zig
I was playing around with `std.fmt.Parser` and got hit by a compile error when it was not used in comptime.
Fixes #20500, which I noticed as I was creating this PR.
=> Fix compile error in std.fmt.Parser.peek()

src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/link.zig, src/mingw.zig, src/zig_llvm.cpp, src/zig_llvm.h
LLVM recently introduced new `Triple::ArchType` members in 19.1.3 which broke our static assertions in `zig_llvm.cpp`. When implementing a fix for that, I realized that we don't even need a lot of the stuff we have in `zig_llvm.(cpp,h)` anymore. This PR trims the interface down considerably, and also fixes a few issues I noticed in the affected code.
=> Reduce our exposure to LLVM API breakage

src/link.zig, src/link/Elf.zig, src/link/Wasm.zig, src/link/Wasm/Archive.zig, src/link/Wasm/Object.zig, src/link/Wasm/ZigObject.zig
Primarily, this moves linker input parsing from flush() into the linker
task queue, which is executed simultaneously with the frontend.
I also made it avoid redundantly opening the same archive file N times
for each object file inside. Furthermore, hard code fixed buffer stream
rather than using a generic stream type.
Finally, I fixed the error handling of the Wasm.Archive.parse function.
Please pay attention to this pattern of returning a struct rather than
accepting a mutable struct as an argument. This ensures function-level
atomicity and makes resource management straightforward.
Deletes the file and path fields from Archive and Object.
Removed a well-meaning but ultimately misguided suggestion about how to
think about ZigObject since thinking about it that way has led to
problematic …
=> link.File.Wasm: parse inputs in compilation pipeline

lib/std/fs/File.zig
On Linux, File.metadata calls the statx syscall directly. As such, the return value is the error code. Previously, it handled the error with `posix.errno`, which when libc is linked, treats the return value as a value set to -1 if there is an error with the error code in errno. If libc wasn't linked, it would be handled correctly.
In the Linux with libc linked case, this would cause the error result to always be treated as success (err val != -1), even when an error occurred.
The other use of `linux.statx` in File zig checked with `linux.E.init` which doesn't have the errno path with libc, so updated this case to do the same.
=> std.fs.File: Fix metadata error check on Linux

src/link/Wasm.zig, src/link/Wasm/Archive.zig
Don't use the reader interface
Avoid unnecessary heap allocations
At first I started working on incorporating the Archive fields into the Wasm data model, however, I realized a better strategy: simply omit Archive data from the serialized linker state. Those files can be trivially reparsed on next compiler process start. If they haven't changed, great. Otherwise if they have, the prelink phase needs to be restarted anyway.
=> link.File.Wasm.Archive: simplify

lib/std/Target/arm.zig, src/codegen/llvm.zig, tools/update_cpu_features.zig
Like d1d95294fd657f771657ea671a6984b860347fb0, this is more Apple nonsense where they abused the arch component of the triple to encode what's really an ABI.
Handling this correctly in Zig's target triple model would take quite a bit of work. Fortunately, the last Armv7-based Apple Watch was released in 2017 and these targets are now considered legacy. By the time Zig hits 1.0, they will be a distant memory. So just remove them.
=> `std.Target`: Remove armv7k/armv7s

src/link/Coff.zig
The `-lldmingw` option affects a lot of logic throughout LLD. We need to pass it for `*-windows-gnu` even when we're not actually linking MinGW since we're still using the MinGW ABI with all that that entails. (One particular problem we would run into is missing handling of `stdcall`-decorated symbols for 32-bit x86.) Also, various other LLD options are sensitive to this option, so it's best to pass it as early as possible.
Closes #11817.
=> `link.Coff`: Pass `-lldmingw` to LLD earlier and regardless of `-lc`.

src/codegen/llvm.zig
The former prevents recognizing code patterns and turning them into libcalls, which is what we want for compiler-rt. The latter is meant to be used on call sites to prevent them from being turned into intrinsics.
Context: https://github.com/ziglang/zig/issues/21833
=> `llvm`: Use `no-builtins` attribute instead of `nobuiltin`.

test/tests.zig
This reverts commit 4049be90de6a557c1ab522363fddbb71d3ccdb18.
See: https://github.com/ziglang/zig/issues/21911
I'll experiment some more with #21910 and try to reland this commit later.
=> Revert "test: Add aarch64_be-linux-(none,gnu,musl) to module tests."

build.zig
I've been consistently observing numbers in the 7659786240 ballpark when building with these settings:
```
e:\dev\zig-windows-x86_64-0.14.0-dev.2034+56996a280\zig.exe build %* ^
-p build-stage4-release ^
--search-prefix e:\dev\zig-bootstrap\out-win\x86_64-windows-gnu-native ^
--zig-lib-dir c:\cygwin64\home\kcbanner\kit\zig\lib ^
-Dstatic-llvm ^
-Doptimize=ReleaseSafe ^
-Dlog=true ^
-Dstrip=false ^
-Duse-zig-libcxx ^
-Dno-langref ^
-Dtarget=x86_64-windows-gnu
```
=> build: increase max_rss to 7.8G

lib/fuzzer.zig
seems to have regressed with the removal of anonymous structs
=> fix type of std_options

lib/std/Target/Query.zig, lib/std/zig.zig
adds arch error message. Matches format of invalid cpu and object format messages.
example: 
```
$ zig build-exe -target baz-macos main.zig
info: available architectures:
amdgcn
arc
arm
armeb
thumb
thumbeb
aarch64
aarch64_be
avr
bpfel
bpfeb
csky
hexagon
kalimba
lanai
loongarch32
loongarch64
m68k
mips
mipsel
mips64
mips64el
msp430
nvptx
nvptx64
powerpc
powerpcle
powerpc64
powerpc64le
propeller1
propeller2
riscv32
riscv64
s390x
sparc
sparc64
spirv
spirv32
spirv64
spu_2
ve
wasm32
wasm64
x86
x86_64
xcore
xtensa
native
error: unknown architecture: 'baz'
```
=> Provide a detailed message for invalid arch in target triple

lib/std/Random.zig
Fixing a compile error in `std.Random.enumValueWithIndex` when handling enums with a single value, reproducible with the following code snippet:
```zig
const SingleValueEnum = enum {
one,
};
pub fn main() void
{
var prng = std.Random.DefaultPrng.init(0);
const random = prng.random().enumValue(SingleValueEnum);
_ = random;
}
```
Error message:
```
/opt/compiler-explorer/zig-0.13.0/lib/std/Random.zig:89:35: error: function called at runtime cannot return value at comptime
```
Obviously randomizing a value for a single-value enum is a silly use case, but the compile error is unexpected regardless. I think the `comptime` keyword here was trying to express that the `if` should be evaluated at `comptime`, but I think
1. The correct way to write this is `if (comptime …
=> Fix compile error in `std.Random.enumValueWithIndex`

lib/std/crypto/25519/ed25519.zig, lib/std/crypto/Certificate.zig, lib/std/crypto/ecdsa.zig, lib/std/crypto/tls.zig, lib/std/crypto/tls/Client.zig, lib/std/http/Client.zig, lib/std/http/protocol.zig, lib/std/std.zig
Tested with ziglang/contrib-testing@ec35cfdbb8296b1cde82a7ef5e7e4462c649feaa.
=> std.crypto.tls: implement TLSv1.2

src/Sema.zig, test/cases/compile_errors/bogus_compile_var.zig, test/cases/compile_errors/missing_main_fn_in_executable.zig, test/cases/hello_world_with_updates.0.zig
~~I think omitting the .zig file extension here is bad for several reasons,
but one is that if you have a directory with two empty files called "x.zig" and
"x.zig.zig" and then compile x.zig.zig, it says this:~~
```
~/lib/std/start.zig:604:46: error: root struct of file 'x.zig' has no member named 'main'
const ReturnType = @typeinfo(@typeof(root.main)).@"fn".return_type.?;
~~~~^~~~~
x.zig.zig:1:1: note: struct declared here
^
```
~~It talks about x.zig in the message, but then x.zig.zig in the note below.
That, even though it never talks about the actual x.zig which is in the same
directory. This is confusing.~~
~~This is just the file name and I considered making this the full path to the file
but I think for this the testing infrastructure for compile errors has to be
improved because …
=>  Sema: fix wording in error message 

lib/std/Target.zig, lib/std/builtin.zig, src/Sema.zig, src/codegen/spirv.zig, src/codegen/spirv/Assembler.zig, src/link/SpirV.zig, src/link/SpirV/deduplicate.zig, src/target.zig
This branch contains some fixes and improvements to help compile Andrew's DAW shaders converted to Zig (see https://codeberg.org/Snektron/daw/src/branch/main/shaders/ui.zig).
- Forbid more pointer arithmetic.
- Properly resolve type inputs in assembly. The frontend doesn't reject it yet so we might as well.
- Properly handle globals declared from inline assembly
- Make the default 'generic' address space for Vulkan be Function. We still need to change this properly, but at least things work now.
- Add the storabe_buffer address space
- Emit ArrayStride for many-item pointers
- Don't emit OpTypeForwardPointer for debug annotations
- Require variable pointers for now. Its important to note that these are not physical pointers, and we cannot do many things with them. We need variable …
=> spirv: miscellaneous vulkan + zig stuff

lib/std/crypto/ascon.zig
Initial public draft NIST SP 800-232 specifies Ascon constants up to 16 rounds for future extensions. So, add these new constants.
=> crypto.ascon: support up to 16 rounds, and update links

lib/compiler/fmt.zig
`zig fmt` would silently fail for paths that didn't exist. This caused me significant confusion when I was trying to format a file but I had a typo in the name - the command looked like it succeeded in the terminal, but the file wasn't changing.
The problem was due to using the warn log level for the error - in `.ReleaseSafe` and `.ReleaseFast` build modes `.warn` messages aren't printed. I think it's fair to use the error level since `FileNotFound` errors like this cause `zig fmt` to produce a nonzero exit code.
=> Fix silent zig fmt errors

lib/std/Thread/Pool.zig
Function passed to `thread_pool` causes build failure when the return type is `!void`
Fixed with the help of @Cloudef 
code:
```zig
const ThreadPool = std.Thread.Pool;
var pool: ThreadPool = undefined;
var gpa = std.heap.GeneralPurposeAllocator(.{}){};
const allocator = gpa.allocator();
defer {
_ = gpa.deinit();
}
const values: [10]i32 = .{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
try pool.init(.{ .allocator = allocator, .n_jobs = 4 });
defer pool.deinit();
for (values) |v| {
try pool.spawn(addOneAndPrint, .{v});
}
}
fn addOneAndPrint(i: i32) !void {
std.debug.print("{d}\n", .{i + 1});
}
```
Default behavior in 0.12/0.13:
```
run
└─ run t_pool
└─ zig build-exe t_pool Debug native 1 errors
/Users/ippsav/zig/lib/std/Thread/Pool.zig:93:13: error: …
```
=> Enable thread_pool function to throw errors

lib/std/os/linux.zig, lib/std/posix.zig
Adds a packed struct for SIOCGIFFLAGS and SIOCSIFFLAGS
Addresses #21890
Quick checked this with the following code.
```
const sock = try std.posix.socket(std.posix.AF.INET, std.posix.SOCK.STREAM, 0);
const ifname = "wlp0s20f3";
var ifr: std.posix.ifreq = std.mem.zeroInit(std.posix.ifreq, .{});
@memcpy(ifr.ifrn.name[0..ifname.len], ifname);
ifr.ifrn.name[ifname.len] = 0;
try std.posix.ioctl_SIOCGIFINDEX(sock, &ifr);
const rval = std.posix.errno(std.os.linux.ioctl(sock, std.os.linux.SIOCGIFFLAGS, @intFromPtr(&ifr)));
if (rval != .SUCCESS) {
return error.FlagsGetFailed;
}
std.debug.print("Flags set:\n", .{});
if (ifr.ifru.flags.UP) {
std.debug.print("UP\n", .{});
}
if (ifr.ifru.flags.BROADCAST) {
std.debug.print("BROADCAST\n", .{});
}
if …
```
=> Flags for SIOC{G,S}IFFLAGS

lib/std/c/darwin.zig
This change fixes two issues:
1. The Zig definition of `std.c.EXC.MASK` had the mask flags starting at bit 0, but the header it's copying has this:
```c
#define EXC_BAD_ACCESS          1
...
/*
* Masks for exception definitions, above
* bit zero is unused, therefore 1 word = 31 exception types
*/
#define EXC_MASK_BAD_ACCESS             (1 << EXC_BAD_ACCESS)
```
2. the structure wasn't padded to 32 bits
Obviously the mask isn't used anywhere is zig, because it would've caused a packed structure padding compile error. On the chance that it is used in the future, either by the compiler, or as an api provided by std, I figured I'd save future poor souls from mysterious bugs caused by the mask flags bits being off by one bit.
=> Fix std.c.EXC.MASK struct to match definition in mach/exception_types.h

src/fmt.zig, src/main.zig
This command being JITed leads to a substantially worse first-time user experience, since you have to wait for upwards of 20 seconds for `fmt.zig` to build. This is especially bad when your editor is configured to run `zig fmt` on save and does so in a blocking manner. As such, it makes sense from a usability perspective to not JIT this particular command.
=> compiler: un-jit `zig fmt`

src/Package/Fetch.zig
Closes #21771
If the same dependency is first discovered as lazy and then later as eager, the existing entry needs to be updated to eager in order for `b.dependency()` to work.
Tested against the repro in the linked issue. With a master build of Zig it adds an `available` decl to the generated `dependencies.zig`, which makes the build system consider it lazy. With this fix the decl is absent and the dependency is correctly considered eager.
```diff
diff --git a/.zig-cache/o/0ac409a893112d8a0dadad72e466f606/dependencies.zig b/.zig-cache/o/abff17167087eb0d6564dda2732ee274/dependencies.zig
index 96c1b91..a39ff09 100644
--- a/.zig-cache/o/0ac409a893112d8a0dadad72e466f606/dependencies.zig
+++ b/.zig-cache/o/abff17167087eb0d6564dda2732ee274/dependencies.zig
@@ -1,6 +1,5 @@
pub const packages = …
```
=> Take eagerness into account when deduplicating dependencies

lib/std/c.zig
The `pthread_key_t` type is currently defined as `void` on Darwin, making the `pthread_key_*` functions fail to compile. This defines it as a `c_ulong`.
=> Add missing `pthread_key_t` definition for Darwin

src/Compilation/Config.zig
Closes #19478 
As in the linked issue:
hello.zig
```
std.debug.print("Hello, ziguana\n", .{});
}
```
Compilation and debug info
```
/home/bhetz -> zig build-obj -gdwarf64 -ODebug -target x86_64-linux hello.zig 
/home/bhetz -> objdump --dwarf=info hello.o | head -n 10
hello.o:     file format elf64-x86-64
Contents of the .debug_info section:
Compilation Unit @ offset 0:
Length:        0x3c779 (64-bit)
Version:       4
Abbrev Offset: 0
Pointer Size:  8
/home/bhetz -> zig build-obj -gdwarf32 -ODebug -target x86-linux hello.zig 
/home/bhetz -> objdump --dwarf=info hello.o | head -n 10
hello.o:     file format elf32-i386
Contents of the .debug_info section:
Compilation Unit @ offset 0:
Length:        0x2c404 (32-bit)
Version:       4
Abbrev …
```
=> Use options debug format if it is provided

src/dev.zig, src/link/Elf/ZigObject.zig, test/incremental/add_decl, test/incremental/fix_astgen_failure, test/incremental/function_becomes_inline, test/incremental/recursive_function_becomes_non_recursive
`zig build test-incremental` now passes with an llvm backend compiled `zig`, but not a self-hosted backend compiled `zig`.
Followup #21961
=> link: fix failing incremental test cases

src/Compilation/Config.zig
See: https://github.com/llvm/llvm-project/pull/116537
=> `Compilation`: Disable LTO for mips n32.

lib/libunwind/include/__libunwind_config.h
See: https://github.com/llvm/llvm-project/pull/116608
This addresses:
* https://github.com/ziglang/zig-bootstrap/issues/20#issuecomment-2480917999
* https://github.com/ziglang/zig-bootstrap/issues/199
=> `libunwind`: Fix compilation for the x32 ABI.

src/Compilation/Config.zig
Extension of 3a6a8b8aa540413d099a6f41a0d8f882f22acb45 (#22006) to all similar ABIs. The LLD issue affects them all.
=> `Compilation`: Disable LTO for all ILP32-on-LP64 ABIs.

lib/std/c/darwin.zig
Fixes most of the compiler errors in #21094 regarding darwin. Changed the functions to return/take *os_log_t instead of os_log_t as it seems that os_log_t is an alias for a pointer in apples docs.
=> fixes some compiler errors for darwin in #21094

src/Compilation/Config.zig
Let's see how this fares in CI. Hopefully things have improved since 2021.
=> `Compilation`: Re-enable LTO for RISC-V.

lib/std/crypto/keccak_p.zig
Now, squeeze() behaves like absorb()
Namely,
```
squeeze(x[0..t]);
squeeze(x[t..n)); with t <= n
```
becomes equivalent to `squeeze(x[0..n])`.
Fixes #22019
=> crypto.keccak.State: don't unconditionally permute after a squeeze()

lib/std/debug/MemoryAccessor.zig
=> `std.debug`: Gracefully handle `process_vm_readv()` `EPERM` in `MemoryAccessor.read()`.

lib/std/crypto/bcrypt.zig
They way OpenSSH does key derivation to protect keys using a password is not the standard PBKDF2, but something funky, picking key material non-linearly.
=> std.crypto.bcrypt: implement the actual OpenSSH KDF

lib/std/debug.zig, lib/std/hash_map.zig
- Adds a function which asserts that a SatetyLock's state is locked when runtime_safety is on.
- Changes the state enum when runtime_safety is off to be `unknown`.
- Add a simple usage test.
In my code, I have several constructs with methods that are, roughly:
- Begin
- Add item
- End
Where begin reserves resources, add item adds a pending value, and end sends the queued items.  As adding items is only valid between begin and end calls, I want an assert construct in my code.  I started writing my own, realized there's probably one in the standard library, and found SafetyLock.  However SafetyLock is currently only used in cases where a special state makes some calls invalid, and is not used anywhere that a special state makes calls valid.  Therefor, I propose adding a method …
=> Proposal: add assertLocked to std.debug.SafetyLock

lib/compiler_rt/count0bits.zig
=> `compiler-rt`: Fix `R_ARM_ABS32` relocation error in `__clzsi2_thumb1()`.

src/Sema.zig, test/cases/compile_errors/align_zero.zig, test/cases/compile_errors/function_alignment_on_unsupported_target.zig
Zig previously accepted `align(0)` in certain positions while rejecting it in others. Where it was accepted, it was taken to mean the default ABI alignment; in other words, it was strictly redundant.
This release makes `align(0)` an error everywhere in the language, thus leaving the design space for this alignment value open. (One possibility being explored here is that `align(0)` could allow the compiler to do bit packing in auto-layout structs.)
=> compiler: Disallow `align(0)` everywhere in the language.

lib/libc/musl/arch/i386/crt_arch.h, lib/libc/musl/arch/x86_64/crt_arch.h, lib/libc/musl/libc.S, lib/libc/musl/src/signal/riscv32/restore.s, lib/libc/musl/src/signal/riscv64/restore.s, lib/libc/musl/src/thread/s390x/__tls_get_offset.s, src/Compilation.zig, src/musl.zig, tools/gen_stubs.zig
Resurrection of #20943. See commit messages for details.
=> `gen_stubs`: No compiler-rt hacks, more compact output, and more arch support

ci/x86_64-linux-debug.sh, ci/x86_64-linux-release.sh
Notably includes a fix for Linux VDSO support on `armeb`.
=> `ci`: Update to QEMU 9.2.0-rc1 in `x86_64-linux` scripts

lib/std/meta.zig
Implementation of `std.meta.eql` updated to reflect the changes made by #21678. This is a breaking change as floats contained within `packed struct`s are now compared bitwise (this might be a reason to reject this pull request).
=> `std.meta.eql`: use `==` directly when comparing `packed struct`s

lib/std/fmt.zig
And make the initialization less error prone by removing a default for `iter`, which is required for a functional parser.
=> Remove unused `buf` field from `std.fmt.Parser`

lib/std/posix.zig
This PR adds explicitly handling of NXIO (errono(6)) to `std.posix.openatZ` to avoid verbose output when this error occurs.
related to: #18240
=> treat errno(6) (NXIO) as expected error in openatZ

lib/std/mem/Allocator.zig
It wasn't immediately clear from the implementation whether passing zero-length memory to free() was undefined behavior or intentionally supported. Since ArrayList and other core data structures rely on this behavior working correctly, this should be explicitly documented as part of the public API contract.
https://github.com/ziglang/zig/blob/53d7a7b3c023f0c26ae7ecc070645096d9adb3dd/lib/std/array_list.zig#L52-L59
cc @squeek502
=> Allocator.free: document zero-length behavior

lib/std/hash.zig
It turns out that Zig's default bit mixer is _very_ biased, and after a lot of googling it turns out that selecting a better solution is _hard_... 
I wrote a custom statistical analysis taylored for bit mixers in order to select the best one at each size (u64/u32/u16), compared a lot of mixers, and packaged the best ones in this PR.
TESTING CODE [here](https://github.com/francescoalemanno/bit_mixers_analysis)
=> add improved std.hash.int - deprecate std.hash.uint32

lib/std/math/isnan.zig
https://github.com/ziglang/zig/issues/14366
=> `std.math`: Disable `isSignalNan` test on mips32.

lib/std/Build/Step/Run.zig
We have deduced that it seems the sporadic BrokenPipe failures happening on the CI runners (e.g.
https://github.com/ziglang/zig/actions/runs/12035916948/job/33555963190) are likely caused by the test runner's stdin pipe abnormally closing, likely due to the process crashing. Here, we introduce error handling for this case, so that if these writes fail, the step is marked as failed correctly, and we still collect the child's stderr to report. This won't fix the CI issues, but it should promote them to proper error messages including child stderr, which -- at least in theory -- should allow us to ultimately track down where the errors come from.
Note that this change is desirable regardless of bugs in the test runner or similar, since the child process could terminate abnormally for any …
=> std.Build: gracefully handle child stdin closing when running tests

lib/std/Thread/Futex.zig
=> `std.Thread.Futex`: Mark inline asm volatile in `WasmImpl`.

build.zig, lib/std/Build/Cache.zig, lib/std/Target.zig, lib/std/Target/Query.zig, lib/std/c.zig, lib/std/os/linux/pie.zig, lib/std/zig/system.zig, lib/std/zig/target.zig, src/Builtin.zig, src/Compilation.zig, src/codegen/llvm.zig, src/glibc.zig, src/libcxx.zig, src/link/Elf.zig, test/cases/inherit_want_safety.zig, test/cases/no_compile_panic_for_unchecked_arith.zig, test/cases/pic_freestanding.zig, test/cases/pic_linux.zig, test/cases/pie_freestanding.zig, test/cases/pie_linux.zig, test/cases/spirv_mergable_pointers.zig, test/link/glibc_compat/build.zig, test/link/glibc_compat/glibc_runtime_check.zig, test/nvptx.zig, test/src/Cases.zig, test/src/Debugger.zig, test/src/TranslateC.zig, test/tests.zig
=> Add PIC/PIE tests and fix some bugs + some improvements to the test harness

lib/std/array_hash_map.zig
`std.ArrayHashMap` is now deprecated and aliased to `std.ArrayHashMapWithAllocator`.
To upgrade, switch to `ArrayHashMapUnmanaged` which will entail updating callsites to pass an allocator to methods that need one. After Zig 0.14.0 is released, `std.ArrayHashMapWithAllocator` will be removed and `std.ArrayHashMapUnmanaged` will be a deprecated alias of `ArrayHashMap`. After Zig 0.15.0 is released, the deprecated alias `ArrayHashMapUnmanaged` will be removed.
This move comes from unanimous agreement among veteran Zig users who have converged on the "unmanaged" container variants. They act as better building blocks, avoiding storing the same data redundantly, and the presence/absence of the allocator parameter dovetails nicely with the reserve capacity / reserved insertion pattern.
=> std.ArrayHashMap: add `reinit` method and other housekeeping, including the move towards "unmanaged" containers

src/Sema.zig, test/behavior/eval.zig
previously doing `++` or `**` with array-pointers, that being either `*[N]T ++ *[N]T` or `*[N]T ++ [N]T` the result value would be `*[N]T`. this violates Zig's principle of not allowing mutable references to temporary values. this PR changes these cases to return `*const [N]T`.
a bonus improvement is changing `*[N]T ++ *[N]T` to emit two `memcpy` AIR instructions instead of manually aggregating.
```diff
-%36 = alloc(*[4]u32)
-%37 = ptr_elem_ptr(*u32, %36, @Air.Inst.Ref.zero_usize)
-%38 = ptr_elem_ptr(*u32, %17!, @Air.Inst.Ref.zero_usize)
-%39 = load(u32, %38!)
-%40!= store(%37!, %39!)
-%41 = ptr_elem_ptr(*u32, %36, @Air.Inst.Ref.one_usize)
-%42 = ptr_elem_ptr(*u32, %27, @Air.Inst.Ref.zero_usize)
-%43 = load(u32, %42!)
-%44!= store(%41!, %43!)
-%45 = ptr_elem_ptr(*u32, %36, <usize, 2>) …
```
=> change `++` and `**` to not return mutable pointers

lib/std/ascii.zig
Instead of using a loop, using a switch statement might be better in the following scenario:
Before:
```zig
pub fn isWhitespace(c: u8) bool {
return for (whitespace) |other| {
if (c == other)
break true;
} else false;
}
```
After:
```zig
pub fn isWhitespace(c: u8) bool {
return switch (c) {
' ', '\t'...'\r' => true,
else => false,
};
}
```
https://godbolt.org/z/TWfnvdnbf
=> Updated ascii.zig's isWhitespace function to use switch instead of for loop.

lib/std/debug.zig, lib/std/debug/MemoryAccessor.zig, test/standalone/stack_iterator/build.zig, test/standalone/stack_iterator/unwind_freestanding.zig
Make `std.debug.StackIterator` compile on the `other` OS target, and port the "unwind_freestanding" test case to the `other` OS target.
Inspired by #20833 which reported the original problem and pin-pointed the issue.
[Edited summary and PR a couple times.]
=> debug.zig: Make it build with 'other' target OS

lib/std/mem.zig
=> std.mem.eql: make comparisons for zero-sized and non-sized types work

lib/std/os/linux.zig, test/tests.zig
This only builds the module tests since there's no `qemu-x32`.
=> `test`: Add `x86_64-linux-(gnux32,muslx32)` to module tests.

src/Compilation.zig
These are produced by `rustc`: https://rustc-dev-guide.rust-lang.org/backend/libs-and-metadata.html#rlib
Closes #21819.
=> `Compilation`: Consider `*.rlib` files to be static libraries.

lib/std/Target.zig
=> `std.Target`: Fix `charSignedness()` for hexagon.

lib/std/zig/target.zig, src/main.zig, src/target.zig
=> compiler: Classify various compiler-rt and libunwind names accurately and satisfy them

lib/zig.h
I recommend reviewing each commit individually.
Closes #22114. There's still more work to do in `bootstrap.c` for non-GCC/Clang compilers, but I'll do that in #22054.
=> Some portability improvements and cleanups in `zig.h`

build.zig
This issue applies to both loongarch32 and loongarch64.
=> `build.zig`: Also set code model for loongarch32.

lib/std/zig/LibCInstallation.zig, lib/std/zig/WindowsSdk.zig, test/standalone/windows_argv/build.zig
This makes e.g. cross-compiling for `x86-windows-msvc` on an `x86_64-windows-msvc` system work properly.
Closes #11926.
=> `std.zig.WindowsSdk`: Support cross-arch SDK lookups.

src/Package/Module.zig
Frame pointers make both debugging and profiling work better, and [the overhead is reportedly 1% or less for typical programs](https://www.brendangregg.com/blog/2024-03-17/the-return-of-the-frame-pointers.html). I think the pros outweigh the cons here. People who *really* care about that 1% can simply use the `-fomit-frame-pointer` option to reclaim it. For `ReleaseSmall`, though, it makes sense to omit frame pointers by default for the sake of code size, as we already strip the binary in this case anyway.
Closes #22161.
=> compiler: Only omit frame pointers by default for `ReleaseSmall`

src/Sema.zig, test/cases/compile_errors/untagged_union_integer_conversion.zig
It currently prints as:
```
:3:18: error: untagged union 'Zcu.LazySrcLoc{ .base_node_inst = InternPool.TrackedInst.Index(104), .offset = Zcu.LazySrcLoc.Offset{ .node_offset = Zcu.LazySrcLoc.Offset.TracedOffset{ .x = -2, .trace = (value tracing disabled) } } }' cannot be converted to integer
````
=> Sema: fix use of Zcu.LazySrcLoc in error message

src/Compilation.zig, src/target.zig
Also update the list of targets with red zone support.
=> `Compilation`: Don't rely on Clang defaults for options that are user-facing.

lib/std/zig/target.zig, src/main.zig
=> `std.zig.target`: Teach `isLibCLibName()` about emulated wasi-libc libraries

lib/std/Target.zig, lib/std/builtin.zig
NetBSD has long since migrated to the EABI and doesn't officially support the OABI anymore. The ABI selection logic in LLVM only actually picks OABI for NetBSD as a last resort if the EABI isn't selected. That fallback is likely to be removed in the future. So just remove this support in Zig entirely.
While here, I also removed some leftover 32-bit Arm and 32-bit x86 code for Apple targets, which are long dead and unsupported by Zig.
=> `std.Target`: Remove our broken support for the ancient and obsolete Arm OABI

src/Builtin.zig
This commit simply tweaks the generated `builtin.zig` source code to be more consistent and in line with current conventions.
=> Builtin: clean up formatting of generated code

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/InternPool.zig, src/Sema.zig, src/codegen/c.zig, test/behavior/fn.zig
Both of these instructions were previously under a special case in `rvalue` which resulted in every reference to such an instruction adding a new `ref` instruction. This had the effect that, for instance, `&a != &a` for parameters. Deduplicating these `ref` instructions was problematic for different reasons.
For `alloc_inferred`, the problem was that it's not valid to `ref` the alloc until the allocation has been resolved (`resolve_inferred_alloc`), but `AstGen.appendBodyWithFixups` would place the `ref` directly after the `alloc_inferred`. This is solved by bringing `resolve_inferred_alloc` in line with `make_ptr_const` by having it *return* the final pointer, rather than modifying `sema.inst_map` of the original `alloc_inferred`. That way, the `ref` refers to the …
=> AstGen: correctly deduplicate `ref` of `param` and `alloc_inferred`

lib/std/multi_array_list.zig, lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Compilation.zig, src/InternPool.zig, src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/main.zig, src/print_zir.zig, test/cases/compile_errors/access_invalid_typeInfo_decl.zig, test/cases/compile_errors/astgen_sema_errors_combined.zig, test/cases/compile_errors/colliding_invalid_top_level_functions.zig, test/cases/compile_errors/constant_inside_comptime_function_has_compile_error.zig, test/cases/compile_errors/invalid_compare_string.zig, test/cases/compile_errors/invalid_decltest.zig, test/cases/compile_errors/misspelled_type_with_pointer_only_reference.zig, test/cases/compile_errors/noreturn_builtins_divert_control_flow.zig, test/cases/function_redeclaration.zig, test/cases/unused_vars.zig
Zig's compilation model is inherently multi-pass: `AstGen` emits errors which do not depend on semantic analysis (such errors have the property of being emitted even for unreferenced code), while `Sema` performs semantic analysis and triggers the corresponding errors. Today, the Zig compiler has the property that the existence of any `AstGen` errors in a file cause that file to be considered "failed", such that semantic analysis can never occur on any code within that file. This has two unfortunate consequences:
* The existence of AstGen errors, even "trivial" ones such as "unused local variable", can cause analysis errors which are related to this file to not be shown, even if they clearly could be. This makes for a worse UX.
* If an incremental update introduces AstGen errors, all prior …
=> compiler: allow semantic analysis of files with AstGen errors

src/Compilation.zig
The rust compile emits ``.rmeta`` files that are required in order to compile Rust programs.  More information can be found here: https://rustc-dev-guide.rust-lang.org/backend/libs-and-metadata.html#rmeta
Zig currently rejects these files as an "unknown file extension."  This fix allows for ``.rmeta`` files.
Fixes https://github.com/ziglang/zig/issues/22168.
=> Fix unknown file extension with .rmeta

lib/std/Build/Cache.zig, lib/std/Build/Step.zig, lib/std/posix.zig, src/Compilation.zig, src/Zcu/PerThread.zig, src/link.zig
Previous commits
2b0929929d67e222ca6a9523a3a594ed456c4a51
4ea2f441df36cec61e1017f4d795d4037326c98c
had this text:
> There are no dir components, so you would think that this was
> unreachable, however we have observed on macOS two processes racing to
> do openat() with O_CREAT manifest in ENOENT.
This is indeed true, as verified by the snippet of code in a below comment on this PR description. However, ENOENT is also possible to be returned when a handle refers to a deleted directory. Thus, the previous workaround that unconditionally retried the file system operation is not sufficient. This patch changes the workaround to retry with `O_EXCL`, disambiguating which error condition has occurred.
This patch also adds an explicit error set to `std.Build.Cache.hit` as well as changing the …
=> std.Build.Cache.hit: more discipline in error handling

lib/std/array_hash_map.zig
In cf88cf2657d721c68055a284e8c498a18639f74c the eql function provided in the context of `ArrayHashMap` was changed to also include the key index, but this wasn't properly updated in the documentation.
Since a flat `usize` is unintuitive, I've tried to explain the function of the parameter as best I can based on the original commit.
Finally, I didn't do an extensive search if this eql definition is incorrectly stated anywhere outside of these 2 spots. But I somewhat doubt an file outside of `array_hash_map` would
solves #19990
=> std.ArrayHashMap fix `eql` documentation

lib/std/Random.zig
a quick TODO resolved with this shiny new builtin
=> use `@branchHint` in `std.Random.float`

lib/std/zig/Ast.zig
The root node is encoded differently depending whether it is a .zig or .zon file.
```zig
//! Abstract Syntax Tree for Zig source code.
//! For Zig syntax, the root node is at nodes[0] and contains the list of
//! sub-nodes.
//! For Zon syntax, the root node is at nodes[0] and contains lhs as the node
//! index of the main expression.
```
The Zig compiler codebase never calls rootDecls on .zon files but I do :)
=> fix std.zig.Ast.rootDecls on .zon mode Ast

src/Sema.zig, test/behavior/defer.zig
fixes #22174
there's another `ensureSpaceForInstructions` call inside of `analyzeBodyInner`, but it shouldn't incur any cost since it checks if the map already has room for the indices.
=> ensure `InstMap` capacity before remapping error code

lib/compiler_rt/arm.zig, lib/std/fmt.zig, lib/std/simd.zig, test/behavior/vector.zig, test/tests.zig
With #22035 merged, we should hopefully no longer see the random unwind failures that occurred after #21894, so let's try this again.
=> Add `armeb-linux-*`, `thumbeb-linux-*`, and `aarch64_be-linux-*` to CI

src/Sema.zig, test/cases/compile_errors/store_comptime_only_type_to_runtime_pointer.zig
Also fix a bug which allowed storing `undefined` to pointers to opaques. You shouldn't be able to create any opaque values, even `undefined` ones!
cc @Rexicon226; let me know if you need clarification on any of the diff.
Resolves: #22175
=> Sema: disallow runtime stores to pointers with comptime-only element types

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/link/Dwarf.zig, src/print_zir.zig
This code was left over from the legacy Autodoc implementation. No component of the compiler pipeline actually requires doc comments, so it is a waste of time and space to store them in ZIR.
=> compiler: remove doc comments from Zir

lib/compiler/build_runner.zig, lib/std/c/darwin.zig, src/DarwinPosixSpawn.zig, src/Sema.zig, src/clang.zig, src/link/Coff.zig, src/translate_c.zig, test/cases/compile_errors/implicit_cast_between_C_pointer_and_Zig_pointer-bad_const-align-child.zig, test/cases/compile_errors/implicit_casting_C_pointers_which_would_mess_up_null_semantics.zig, test/cases/compile_errors/invalid_pointer_coercions.zig, test/cases/compile_errors/use_implicit_casts_to_assign_null_to_non-nullable_pointer.zig
The error messages here aren't amazing yet, but this is an improvement on status quo, because the current behavior allows false negative compile errors, so effectively miscompiles.
Resolves: #15874
=> Sema: disallow unsafe in-memory coercions

lib/std/dwarf/AT.zig, lib/std/dwarf/TAG.zig, src/InternPool.zig, src/Type.zig, src/link/Dwarf.zig, tools/lldb_pretty_printers.py
```zig
fn Foo(comptime T: type) type {
return struct {
x: T,
const Bar = struct { x: u32 };
};
}
var foo1: Foo(u32) = .{ .x = 1 };
var foo2: Foo(bool) = .{ .x = false };
_ = .{ &foo1, &foo2, @TypeOf(foo1).Bar, @TypeOf(foo2).Bar };
@breakpoint();
}
```
```
(lldb) p @TypeOf(foo1)
(type) struct {}
(lldb) p @TypeOf(foo2)
(type) struct {
Bar = struct {}
}
```
&downarrow;
```
(lldb) p @TypeOf(foo1)
(type) struct {
Bar = struct {}
}
(lldb) p @TypeOf(foo2)
(type) struct {
Bar = repro.repro.Foo(u32).Bar
}
```
Also, start porting stage2 pretty printers to self-hosted debug info and thread-safe internpool changes.
=> Dwarf: preserve deduped struct navs

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/InternPool.zig, src/Sema.zig, src/Value.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/print_zir.zig, test/behavior/align.zig, test/behavior/fn.zig, test/behavior/type_info.zig, test/cases/compile_errors/comptime_only_global_align_section_addrspace.zig, test/cases/compile_errors/invalid_variadic_function.zig, test/link/macho.zig
even if you thought this feature was useful it really doesn't seem worth 500 damn lines of compiler logic :)
Resolves: #22261
---
This PR also implements a breaking change to disallow `align`/`linksection`/`addrspace` annotations on globals with comptime-only types. This includes function aliases, but not function declarations.
=> compiler: disallow `callconv` etc from depending on function parameters

src/Package/Module.zig
On x86 and x86_64 keeping the frame pointer usually reduces binary size, even for simple programs:
```
~$ cat x.zig
@import("std").debug.print("hello", .{});
}
~$ zig build-exe x.zig -target x86_64-linux -OReleaseSmall -fno-omit-frame-pointer && wc -c x
5168 x
~$ zig build-exe x.zig -target x86_64-linux -OReleaseSmall -fomit-frame-pointer && wc -c x
5216 x
```
```
~$ cat x.zig
@import("std").debug.print("hello", .{});
}
~$ zig build-exe x.zig -target x86-linux -OReleaseSmall -fno-omit-frame-pointer && wc -c x
3400 x
~$ zig build-exe x.zig -target x86-linux -OReleaseSmall -fomit-frame-pointer && wc -c x
3556 x
```
A bigger benchmark is the Zig compiler:
With no changes to anything on master branch:
```
$ zig build -Dno-lib -Dno-langref …
```
=> Module: keep frame pointer in ReleaseSmall on x86

doc/build.zig.zon.md, lib/init/build.zig.zon
There's been some proliferation of dependency URLs that reference mutable data such as links to git branches that can change.  This has resulted in broken projects, i.e.
* https://github.com/RohanVashisht1234/raylib_rain_train/blob/9eef9de94c511f2eb4fe5db1d6abd574ee245c9b/build.zig.zon
* https://github.com/rcmagic/ZigFightingGame/commit/4b64353e9c69de0fa2eb87fa9c3a3da76a8a3e7b
There's also disagreement about whether it's fine for URL's to point to git branches, i.e.
https://github.com/Not-Nik/raylib-zig/pull/130
This updates the docs to clarify that urls should reference immutable data.
=> doc: clarify build.zig.zon urls should point to immutable data

lib/std/os/linux.zig
looking at `man getgroups` and `info getgroups` this is given as an example:
```c
// Here's how to use ‘getgroups’ to read all the supplementary group
// IDs:
gid_t *
read_all_groups (void)
{
int ngroups = getgroups (0, NULL);
gid_t *groups
= (gid_t *) xmalloc (ngroups * sizeof (gid_t));
int val = getgroups (ngroups, groups);
if (val < 0)
{
free (groups);
return NULL;
}
return groups;
}
```
getgroups(0, NULL) is used to get the count of groups so that the correct count can be used to allocate a list of gid_t. However this is not possible with the function signature `getgroups(size: usize, list: *gid_t) usize` where "list" is supposedly a pointer to the beginning of a list of unknown length.
equivalent example in Zig after the change:
```zig
// get the group count
const ngroups: usize = …
```
=> fix: allow std.os.linux.getgroups to accept null

lib/compiler_rt/rem_pio2_large.zig
Adds a `@branchHint` to a 1 in 12 branch of the pi/2 remainder calculation.
=> Add branch hint to unlikely branch of `rem_pio2_large`

lib/std/dwarf/AT.zig, src/Compilation.zig, src/InternPool.zig, src/Type.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/link.zig, src/link/C.zig, src/link/Coff.zig, src/link/Dwarf.zig, src/link/Elf/ZigObject.zig, src/link/MachO/ZigObject.zig, src/link/Plan9.zig, src/link/Wasm/ZigObject.zig, tools/lldb_pretty_printers.py
Use `.unwrapped` to view intern pool index payloads.
```
(lldb) v val
(root.Value) val = {
.ip_index = @enumFromInt(156) repro2.Foo
}
(lldb) v val.ip_index.unwrapped
(root.InternPool.Index.Unwrapped) .unwrapped = {
.tag = .type_struct
.payload = {
.name = @enumFromInt(6597) "repro2.Foo"
.cau = @enumFromInt(313) {
.zir_index = @enumFromInt(314)
.namespace = @enumFromInt(8)
.owner = (.kind = .type, .index = 156)
}
.zir_index = @enumFromInt(314)
.namespace = @enumFromInt(8)
.fields_len = 1
.flags = {
.any_captures = false
.is_extern = false
.known_non_opv = true
.requires_comptime = .no
.assumed_runtime_bits = false
.assumed_pointer_aligned = false
.any_comptime_fields = false
.any_default_inits = false
.any_aligned_fields = false
.alignment = .@"8"
.alignment_wip = false
.field_types_wip = …
```
=> lldb: add more stage2 pretty printers

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Compilation.zig, src/InternPool.zig, src/Sema.zig, src/Sema/comptime_ptr_access.zig, src/Type.zig, src/Value.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/arch/wasm/CodeGen.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/link.zig, src/link/C.zig, src/link/Coff.zig, src/link/Dwarf.zig, src/link/Elf/ZigObject.zig, src/link/MachO/ZigObject.zig, src/link/Plan9.zig, src/link/Wasm/ZigObject.zig, src/print_zir.zig, test/behavior/globals.zig, test/cases/compile_errors/address_of_threadlocal_not_comptime_known.zig, test/cases/compile_errors/self_reference_missing_const.zig, test/cases/compile_errors/type_variables_must_be_constant.zig, test/cases/compile_errors/use_invalid_number_literal_as_array_index.zig
This PR performs 2 significant refactors, and then implements #131.
See commit messages for details.
The performance impact of this PR is variable, but here are two important tests:
```
Benchmark 1 (8 runs): /home/mlugg/zig/master/stage4-fast/bin/zig build-exe --stack 33554432 -fno-sanitize-thread -ODebug --dep aro --dep aro_translate_c --dep build_options -Mroot=src/main.zig -Maro=lib/compiler/aro/aro.zig --dep aro -Maro_translate_c=lib/compiler/aro_translate_c.zig -Mbuild_options=.zig-cache/c/c5119ba8c2bb22ea36039c62cc1b2325/options.zig -fno-llvm -fno-lld --cache-dir .zig-cache --global-cache-dir /home/mlugg/.cache/zig --name zig --zig-lib-dir lib
wall_time          12.9s  ± 40.0ms    12.8s  … 13.0s …
```
=> compiler: analyze type and value of global declarations separately

src/Value.zig, test/behavior/switch_loop.zig
=> Value: implement `orderAgainstZeroInner` for errors

lib/std/zig/AstGen.zig, test/behavior/slice.zig, test/cases/safety/slice by length sentinel mismatch on lhs.zig, test/cases/safety/slice by length sentinel mismatch on rhs.zig
I initially just wanted to simplify the code that handles the slicing syntax in AstGen.zig but then found two bugs related to the special [Slicing By Length](https://ziglang.org/download/0.11.0/release-notes.html#Slicing-By-Length) syntax:
This example will incorrectly trigger slicing by length even though no end index has been provided. It will crash the compiler.
```zig
test {
var foo = "";
_ = foo[0..][0.. :0];
}
```
In this example, the provided sentinel expression is never analyzed and no sentinel mismatch safety check is reported.
```zig
test {
var foo: [2:0]u8 = .{ 1, 2 };
_ = foo[0.. :1][0..2];
}
```
The [PR](https://github.com/ziglang/zig/pull/15519) that added the slicing by length special case has explicitly mentioned support for `s[start..:sentinel][0..len]` and …
=> fix incorrect slicing by length detection cases

lib/std/os/linux.zig
I think these arguments can accept null.
=> linux: make ptid and ctid in clone() optional

src/link/Elf.zig
Found this while trying to package ghostty and found that libghostty had had no build-id despite `--build-id=sha1` being explicitly passed.
This PR makes it so that `build-id` is also set for shared libraries.
=> link/Elf.zig: set build-id for dynamic libraries.

src/Sema.zig, test/cases/compile_errors/coerce_array_to_different_size.zig
The change in `Sema.coerceExtra` is just to avoid an unhelpful error message, covered by the added test case.
Resolves: #22373
=> Sema: fix invalid coercion `*[n:x]T` -> `*[m]T` for `n != m`

lib/std/zig/Zir.zig, src/Compilation.zig, src/Zcu.zig, test/incremental/fix_many_errors
Fixes a few bugs with incremental compilation. The first tripped an assert in some cases (although didn't actually affect ReleaseFast compilers in practice AFAICT), while the second was a much more significant bug. The bug in question was that while collecting error bundles, we corrupted the state of `Zcu.failed_analysis` on the false assumption that we would never use it again. That meant that when future incremental updates tried to remove elements from the map (because the corresponding `AnalUnit` was undergoing re-analysis), the error wasn't found by the lookup, causing it to persist forever.
@andrewrk, this bug absolutely explains why we have consistently been having issues with incremental compilation when trying to use `-Dno-bin -fincremental --watch` for e.g. big compiler …
=> incremental: bugfixes

lib/std/zig/LibCInstallation.zig
Fix windows libc lib paths when compiling to `x86-windows-msvc` from a `x86_64-windows` machine. The changes simply consider the cpu arch of the target instead of the host machine. This is what I get when outputting libc for target `x86-native-msvc` before this fix:
```
include_dir=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt
sys_include_dir=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include
crt_dir=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64
msvc_lib_dir=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\Lib\x86
kernel32_lib_dir=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64
gcc_dir=
```
As you can see the path for `crt_dir` and `kernel32_lib_dir` ends with x64 …
=> fix: windows libc lib paths for x86-windows-msvc

lib/compiler_rt/count0bits.zig
Originally the code loaded the (first 4 bytes of the) lookup table into r3 instead of the address of the lookup table, resulting in the memory address 02020100 (the lookup table bytes, in little endian) being dereferenced instead of the address of the lookup table.
=> compiler_rt: fix __clzsi2_thumb1 (incorrect lookup table usage)

src/Sema.zig, test/behavior/eval.zig
=> Sema: correctly label `block_comptime` for restoring error return trace index

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, test/cases/compile_errors/for.zig
The old lowering was kind of neat, but it unintentionally allowed the syntax `for (123) |_| { ... }`, and there wasn't really a way to fix that. So, instead, we include both the start and the end of the range in the `for_len` instruction (each operand to `for` now has *two* entries in this multi-op instruction). This slightly increases the size of ZIR for loops of predominantly indexables, but the difference is small enough that it's not worth complicating ZIR to try and fix it.
=> Zir: split up start and end of range in `for_len`

lib/std/mem.zig
Remove misleading `This never fails.` statement and add explicit clarification 
that first() will panic if called after iteration has already begun.
Fixes #22338
=> Improve `first()` documentation for split iterators

src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/codegen/llvm.zig
Rather than `Zcu.BuiltinDecl.Memoized` being a struct with fields, it can instead just be an array, indexed by the enum. This allows runtime indexing, avoiding a few now-unnecessary `inline` switch cases.
=> compiler: slightly simplify builtin decl memoization

src/Compilation.zig, src/Compilation/Config.zig, src/codegen/llvm.zig, src/libunwind.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/Wasm.zig, src/main.zig
This PR fixes this issue: https://github.com/ziglang/zig/issues/21947.  I have tested compiling the Godot Game Engine with this PR: https://github.com/godotengine/godot
It compiles much faster and does not consume all of my memory! :)
This is vital for us to be able to add first class support for cross platform compilation in our godot-src project: https://github.com/lange-studios/godot-src
NOTE:
I am unsure of how to trigger the code path in ``main.zig`` in lines 1383 - 1396.  If someone could give me instructions on how to trigger that code path or test themselves to confirm that code change works, that would be greatly appreciated!
Thanks again for the awesome Zig!  U all rock! :)
=> Fix Thin LTO not working

src/codegen.zig, test/standalone/build.zig.zon, test/standalone/empty_global_error_set/build.zig, test/standalone/empty_global_error_set/main.zig
The final offset was clobbering the first error name, which is revealed by an out of bounds when the global error set is empty.
Closes #22362
=> x86_64: fix `@errorName` data

src/Compilation.zig
Embedding manifests into .exes as covered in #17406 and #17448 totally works, but is currently using the wrong resource ID when embedding into .dlls. This change ensures that shared libs that embed manifests use the correct resource ID. See this docs page for an overview of the various kinds of resource IDs for manifests and their usage: https://learn.microsoft.com/en-us/windows/win32/sbscs/using-side-by-side-assemblies-as-a-resource
FYI @squeek502 
Below is a simple repro that has a `lib.c` built as a DLL and a `main.c` built as an .exe. `lib.c` is using an API (`TaskDialogIndirect`) that requires use of a manifest file with a specific dependency declaration (apparently done for back compat reasons). 
```c
// lib.c
#include <windows.h>
#include <commctrl.h>
void display_dialog(void)
{ …
```
=> fix win32 manifest ID for DLLs

lib/std/fmt.zig, lib/std/simd.zig, lib/std/zig/system.zig, test/behavior/align.zig, test/behavior/vector.zig
=> Some QEMU fixes + disable some tests for `thumbeb` in addition to `armeb`

src/target.zig
I ran into a build error on the wasm target where compiling C files with `-Werror` can fails the build with a warning `error: argument unused during compilation: '-mred-zone'`. These changes remove wasm from the redzone target list. I'm not sure why wasm was added to the list to begin with in #22190, so maybe this is the wrong change, but based on the repro it seems correct. 
It's possible that the red zone option is always present but not configurable for wasm targets but I'm not sure where to look up this info. In that case I'm not sure what the best change would be since the target would technically have a red zone, but zig shouldn't emit flags for it.
```c
// main.c
int get_magic(void)
{
return 1337;
}
```
```zig
//build.zig
pub fn build(b: *std.Build) void …
```
=> remove wasm from redzone targets list

lib/std/zig/system.zig
fixes the dynamic linker path resolution to take the added and subtracted features into consideration
i.e:
`zig build-exe -target riscv64-linux -mcpu generic_rv64+d` 
goes from the incorrect `/lib/ld-linux-riscv64-lp64.so.1` -> `/lib/ld-linux-riscv64-lp64d.so.1`
=> Target: update the extra features before resolving the dynamic linker

test/tests.zig
The relocation range issues will happen eventually as we add more code to the standard library and test suites, so we may as well just deal with this now. @MasonRemaley ran into this in #20271, for example.
=> test: Enable long calls for all `thumb`/`thumbeb` module tests.

lib/std/zig/system.zig
An ad-hoc fix hopefully fixing my issue. But I haven't tested it.
=> `-fwine` should allow x64 non-Windows OSes to run x86-windows apps

lib/std/atomic.zig
The Golang internals referenced have since changed to specify a size of 64 bytes, not 32. RISC-V profiles for application processors since RVA22 [have mandated 64-byte cache lines](https://github.com/riscv/riscv-profiles/blob/main/src/profiles.adoc#612-rva22u64-mandatory-extensions) via the `Zic64b` extension. There aren't any other extensions defined to indicate differently-sized cache lines, indicating the RISC-V ecosystem has effectively settled on 64 bytes.
=> std.atomic: change cache line size for RISC-V from 32 to 64 bytes

test/behavior/generics.zig, test/behavior/sizeof_and_typeof.zig, test/behavior/type_info.zig
Relax the behavior tests so that the following language rule can be implemented without breaking the behavior tests:
The reference to `foo` here creates an external dependency on symbol `foo` even if not called.
```zig
extern fn foo() callconv(.c) void;
comptime {
_ = foo;
}
```
Acceptance testing for this language rule is not implemented yet.
=> behavior: referencing an extern means depending on it

lib/libc/mingw/crt/intrincs/RtlSecureZeroMemory.c, src/mingw.zig
=> `mingw`: Add upstream `RtlSecureZeroMemory` implementation.

src/Type.zig, test/cases/compile_errors/dereference_bad_pointer_via_array_mul.zig
`Type.hasWellDefinedLayout` was in disagreement with pointer loading logic about auto-layout structs with zero fields, `struct {}`. For consistency, these types should not have a well-defined layout.
This is technically a breaking change.
=> Type: `struct {}` does not have a well-defined layout

lib/std/fs/Dir.zig
the actual parameter name is `sub_path` which is also referenced in other comments describing the fuction.
=> std.fs.Dir: update doc comment to match function signature

lib/std/Build/Step/Compile.zig
A libc file that was generated wouldn't add the step dependencies before, so you had to set them manually
=> Fix setLibCFile doesn't add step dependencies

lib/std/zip.zig, lib/std/zip/test.zig
This PR adds support for handling ZIP64 format in local file headers, when a zip file contains entries where the compressed or uncompressed size fields are set to 0xFFFFFFFF, and the extra field contains ZIP64 extended information tag (0x0001)
The code now:
- Reads the actual sizes from the ZIP64 extra field data
- Validates these sizes against the entry's compressed and uncompressed sizes
Zip file format spec.: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
This change allows proper extraction of ZIP files that use ZIP64 format in their local file headers, fixing issue #22329
=> std.zip: Add ZIP64 support for local file header extra field

lib/std/math/big/int.zig
closes #22498
Greped for similar types of mistakes in codebase but it seems to be the only one of kind. 
Would be usefull to create a tool to find them. Like https://github.com/ziglang/zig/issues/21660 but for markdown errors instead of typos.
=> autodocs: reflow comment to prevent it from been put in blockquote

src/target.zig
The blocker for enabling this feature was my need to debug the emitted assembly without debug info and having to manually inspect memory to determine struct contents.  However, we now have debug info!
(lldb) v -L foo bar
0x00007fffffffda20: (repro.repro.Foo) foo = {
0x00007fffffffda24:   .x = 12
0x00007fffffffda20:   .y = 34
}
0x00007fffffffda28: (repro.repro.Bar) bar = {
0x00007fffffffda28:   .x = 56
0x00007fffffffda2c:   .y = 78
}
Updates #21530
=> x86_64: enable struct field reordering

lib/compiler_rt/memcpy.zig, lib/std/zig/system.zig
This was accidentally broken in #22434. See https://github.com/ziglang/zig/pull/22513#issuecomment-2599684094 for an explanation.
cc @andrewrk @Rexicon226
=> `std.zig.system`: Move CPU feature hacks after ABI detection.

lib/std/Thread.zig
=> `std.Thread`: Fix `wasi_thread_start()` export to use a pointer.

src/libunwind.zig
See: https://github.com/llvm/llvm-project/pull/121819
This fixes LTO for libunwind, so also re-enable support for that.
=> `libunwind`: Build C files with `-fexceptions`.

src/codegen/llvm.zig
On x86_64, the `@divFloor` change is a strict improvement, and the `@mod` change adds one zero latency instruction.  In return, once we upgrade to LLVM 20, when the optimizer discovers one of these operations has a power-of-two constant rhs, it will be able to optimize the entire operation into an `ashr` or `and`, respectively.
#I   CPL   CPT
old `@divFloor` |  8 | 15 | .143 |
new `@divFloor` |  7 | 15 | .148 |
old `@mod`      |  9 | 17 | .134 | (rip llvm
new `@mod`      | 10 | 17 | .138 |  scheduler)
=> llvm: convert `@divFloor` and `@mod` to forms llvm will recognize

src/Sema.zig, src/Type.zig, test/behavior/optional.zig, test/cases/compile_errors/branch_in_comptime_only_scope_uses_condbr_inline.zig
We can still potentially determine a comptime result based on the type, even if the pointer is runtime-known.
Also, we previously used load -> is non null instead of AIR `is_non_null_ptr` if the pointer is comptime-known, but that's a bad heuristic. Instead, we should check for the pointer to be comptime-known, *and* for the load to be comptime-known, and only in that case should we call `Sema.analyzeIsNonNull`.
Resolves: #22556
=> Sema: fix `is_non_null_ptr` handling for runtime-known pointers

lib/std/Build.zig, lib/std/Build/Step/Compile.zig, lib/std/Build/Step/Run.zig, lib/std/process/Child.zig, test/standalone/test_runner_module_imports/build.zig, test/standalone/test_runner_path/build.zig
There were two bugs here; thanks to @Rexicon226 for helping figure this out.
The first commit here is a breaking `std.Build` change for anyone who is overriding the test runner (probably... not many people).
=> (Hopefully) fix `error.BrokenPipe` failures

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Air.zig, src/Air/types_resolved.zig, src/InternPool.zig, src/Sema.zig, src/Type.zig, src/Value.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/arch/wasm/CodeGen.zig, src/codegen.zig, src/codegen/c.zig, src/codegen/c/Type.zig, src/codegen/llvm.zig, src/codegen/spirv.zig, src/print_value.zig, src/print_zir.zig, test/behavior/fn.zig, test/cases/compile_errors/anytype_param_requires_comptime.zig, test/cases/compile_errors/bogus_method_call_on_slice.zig, test/cases/compile_errors/coerce_anon_struct.zig, test/cases/compile_errors/non-comptime-parameter-used-as-array-size.zig
The original motivation here was to fix regressions caused by #22414. However, while working on this, I ended up discussing a language simplification with Andrew, which changes things a little from how they worked before #22414.
The main user-facing change here is that any reference to a prior function parameter, even if potentially comptime-known at the usage site or even not analyzed, now makes a function generic. This applies even if the parameter being referenced is not a `comptime` parameter, since it could still be populated when performing an inline call. This is a breaking language change.
The detection of this is done in AstGen; when evaluating a parameter type or return type, we track whether it referenced any prior parameter, and if so, we mark this type as being "generic" in …
=> compiler: simplify generic functions, fix issues with inline calls

lib/std/Build/Step/Compile.zig, lib/std/process.zig
Fixes
```zig
_ = &std.process.changeCurDirC;
_ = &std.Build.Step.Compile.dependsOnSystemLibrary;
```
from #20505.
Looks like `chdirC` was renamed `chdirZ` but that wasn't reflected in the `std.process` alias. I'm not sure if this alias is even needed, I couldn't find any references to `changeCurDir` in std.
For `dependsOnSystemLibrary`, it looks like because of the way it finds dependency libraries, `compile` can't be a `*const Compile`. And since `Module::link_libc` returns a `?bool` with `null` meaning "doesn't matter", I used best judgement and assigned it to false based on how `is_linking_libc` is being used.
=> Fix compiler errors in std.process and std.Build.Step.Compile

lib/std/posix.zig
=> std.posix: Fix errno 13 when writing to file

lib/std/fs/path.zig, lib/std/zig/system.zig
Should help systems that have main `env` binary in different location than hardcoded `/usr/bin/env` **during build** (not neccessarily always), like Nix/Guix, Termux, Gentoo Prefix etc.
Theoretically should close following issues, but it needs more testing from affected users:
https://github.com/ziglang/zig/issues/12156
https://github.com/ziglang/zig/issues/14146
https://github.com/ziglang/zig/issues/14577
https://github.com/ziglang/zig/issues/15898
Source for logic: https://github.com/ziglang/zig/issues/14146#issuecomment-2308984936
=> std.zig.system: use both PATH and hardcoded locations to find `env`

lib/std/debug.zig
It was impossible to use format on any ConfigurableTrace which is not configured exactly like std.debug.Trace. And produced really sus results like so
This works perfectly fine.
```zig
const builtin = @import("builtin");
const Trace = std.debug.ConfigurableTrace(2, 4, true);
if (@hasDecl(Trace, "format")) {
std.debug.print("{}\n", .{Trace.init});
}
}
```
```sh
> zig run main.zig
```
Now if I change any number in ConfigurableTrace for example 4 -> 5
```zig
const builtin = @import("builtin");
const Trace = std.debug.ConfigurableTrace(2, 5, true);
if (@hasDecl(Trace, "format")) {
std.debug.print("{}\n", .{Trace.init});
}
}
```
```sh
> zig run main.zig …
```
=> std.debug: fix format on ConfigurableTrace

src/Package/Fetch.zig
When trying to execute a binary fetched from a package I ran into this issue: https://github.com/ziglang/zig/issues/21044:
> the expected behavior from the package manager is to ignore permissions from the zip file and set the execute bit based on ELF header and shebang line alone (see https://github.com/ziglang/zig/issues/17463)
Since this has been implemented for ELF already this change adds support for Mach-O.
=> Package fetch: add executable detection for Mach-O file headers

lib/std/compress/lzma.zig, lib/std/compress/lzma/test.zig
Replaces memcpy with mem.copyForwards to prevent overlap panic.
```zig
thread 18216 panic: @memcpy arguments alias
C:\Program Files\Zig\lib\std\compress\lzma.zig:80:53: 0x18c72d in read (lzma.exe.obj)
@memcpy(input[0 .. input.len - n], input[n..]);
```
The lzma tests never triggered the bug, I assume the inputs are too small so readAllAlloc never calls .read() for less than half of the buffer length, so if needed I attach some compressed input that does (let me know if I should get a minimal input that reproduces the issue and add a test).
```zig
test "lzma big file" {
const allocator = std.testing.allocator;
const compressed_file = try std.fs.cwd().openFile("compressed.txt", .{});
defer compressed_file.close();
var decompressor = try std.compress.lzma.decompress(allocator, …
```
=> Fix memcpy alias bug in std.compress.lzma

lib/init/build.zig, lib/std/Build.zig, test/behavior/x86_64/build.zig, test/link/common_symbols/build.zig, test/link/common_symbols_alignment/build.zig, test/link/interdependent_static_c_libs/build.zig, test/link/link.zig, test/link/static_libs_from_object_files/build.zig, test/src/Cases.zig, test/standalone/coff_dwarf/build.zig, test/standalone/dep_duplicate_module/build.zig, test/standalone/extern/build.zig, test/standalone/global_linkage/build.zig, test/standalone/install_headers/build.zig, test/standalone/load_dynamic_library/build.zig, test/standalone/shared_library/build.zig, test/standalone/stack_iterator/build.zig, test/standalone/static_c_lib/build.zig, test/standalone/windows_argv/build.zig
Extracted as own PR as mentioned in https://github.com/ziglang/zig/pull/20388#issuecomment-2380867994 .
Acts as a replacement for `addSharedLibrary` and `addStaticLibrary`, but
linking mode can be changed more easily in build.zig, for example:
In library:
```zig
const linkage = b.option(std.builtin.LinkMode, "linkage", "Link mode for a foo_bar library") orelse .static; // or other default
const lib = b.addLibrary(.{
.linkage = linkage,
.name = "foo_bar",
.root_module = mod,
});
```
In consumer:
```zig
const dep_foo_bar = b.dependency("foo_bar", .{
.optimize = optimize,
.linkage = .dynamic // or leave for default static
});
mod.linkLibrary(dep_foor_bar.artifact("foo_bar"));
```
It also matches nicely with `linkLibrary` name.
=> std.Build: add `addLibrary` function

lib/std/c.zig, lib/std/c/darwin.zig
This perhaps fixes #17260.
It adds constants for the TCP sockopt from darwin/bsd/netinet/tcp.h:
https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/netinet/tcp.h#L208
=> adding std.c.TCP.NODELAY for macos

lib/std/posix.zig
On Linux, set REUSEPORT option on an unix socket returns a EOPNOTSUPP error.
See https://github.com/torvalds/linux/commit/5b0af621c3f6ef9261cf6067812f2fd9943acb4b
=> std.posix.setsockopt: EOPNOTSUPP can be returned

build.zig, lib/std/Target.zig, lib/std/Target/wasm.zig, src/Compilation.zig, src/arch/wasm/CodeGen.zig, src/link/Wasm.zig, stage1/wasm2c.c, tools/update_cpu_features.zig
See #21818 and commit messages.
(#21818 should remain open after this to track aligning `lime1` exactly with the spec when we upgrade to LLVM 20.)
=> `std.Target`: Use `lime1` as wasm baseline model and `mvp` as generic model

lib/libc/musl/src/thread/s390x/__tls_get_offset.s
See these mailing list threads:
* https://www.openwall.com/lists/musl/2024/11/23/3
* https://www.openwall.com/lists/musl/2025/01/24/1
This supplants cc73d7ad749df8d53da442faa2e7af5d69357b33.
=> `musl`: Manually inline `__tls_get_addr` into s390x `__tls_get_offset`.

build.zig, lib/std/Build.zig
It's just as much part of an `std.Target` value as arch, OS, ABI, CPU, and dynamic linker, so it seems odd not to have it be part of the standard target options.
=> `std.Build`: Make `ofmt` part of `standardTargetOptions()`.

lib/std/fs/path.zig, src/Compilation.zig, src/InternPool.zig, src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, test/incremental/add_decl, test/incremental/add_decl_namespaced, test/incremental/change_embed_file, test/incremental/change_enum_tag_type, test/incremental/compile_error_then_log, test/incremental/delete_comptime_decls, test/incremental/fix_astgen_failure, test/incremental/fix_many_errors, test/incremental/remove_enum_field, test/incremental/remove_invalid_union_backing_enum, test/incremental/temporary_parse_error, test/incremental/unreferenced_error, tools/incr-check.zig
Uses of `@embedFile` register dependencies on the corresponding `Zcu.EmbedFile`. At the start of every update, we iterate all embedded files and update them if necessary, and invalidate the dependencies if they changed.
In order to properly integrate with the lazy analysis model, failed embed files are now reported by the `AnalUnit` which actually used `@embedFile`; the filesystem error is stored in the `Zcu.EmbedFile`.
An incremental test is added covering incremental updates to embedded files, and I have verified locally that dependency invalidation is working correctly.
EDIT: why not, this branch now also contains a nice lil incr-check enhancement: we now *actually* check that the compile errors match what's expected!
=> incremental: handle `@embedFile`

lib/std/os/windows.zig
The current implementation of the `LDR_DATA_TABLE_ENTRY` struct is using reserved fields for `InLoadOrderMemoryLinks`, `InInitializationOrderLinks`, and `BaseDllName` among a few other fields, but they are not as relevant. I've updated those fields in this PR, but I'm happy to discuss or look into this further if a more verbose struct definition would be applicable here.
Additionally, the complete `LDR_DATA_TABLE_ENTRY` struct definition can be found at the following links for Vista and W10, respectively:
https://www.nirsoft.net/kernel_struct/vista/LDR_DATA_TABLE_ENTRY.html
https://www.vergiliusproject.com/kernels/x64/windows-10/1909/_LDR_DATA_TABLE_ENTRY
=> Update LDR_DATA_TABLE_ENTRY struct

lib/std/zig/system/darwin.zig
=> std: do not call xcode-select or xcrun by absolute path in darwin sdk detection

lib/compiler_rt/memcpy.zig
Fixing some issues with #18912.
cc @jacobly0, the memmove issue should be resolved by #22606.
=> compiler-rt memcpy followup

lib/std/net.zig, lib/std/net/test.zig
On Linux, set REUSEPORT option on an unix socket returns a EOPNOTSUPP error.
See https://github.com/torvalds/linux/commit/5b0af621c3f6ef9261cf6067812f2fd9943acb4b
=> std.net.listen: no REUSEPORT with unix socket

lib/std/os/linux.zig, lib/std/os/linux/test.zig
This PR introduces the following changes:
- Implementation of the `sigdelset` function, which allows removing a signal from a signal set (sigset_t).
- Expansion of unit tests to include signal removal use cases (`sigdelset`).
=> Add Support for `sigdelset` in `std.os.linux`

lib/std/fmt.zig
Add a check for vector max depth in formatType.
Resolves #22376
=> std.fmt.formatType: check max depth for vector type in formatType

src/Sema.zig, test/cases/compile_errors/invalid_destructure_error_union.zig
Followup to #21491, based on [this comment ](https://github.com/ziglang/zig/pull/21491#issuecomment-2371768955).
Previously, the following note was added whenever an attempt was made to destructure an error union:
`note: consider using 'try', 'catch', or 'if'`
With these changes, the note is added only if the underlying payload type can be destructured.
=> fix: Only suggest try on destructure of error union if payload type can be destructured

doc/langref.html.in
My second attempted contribution! Feedback welcome.
Intended to resolve https://github.com/ziglang/zig/issues/21535
I traced the relevant lines to: 
https://github.com/ziglang/zig/blob/085cc54aadb327b9910be2c72b31ea046e7e8f52/src/Sema.zig#L2978
```zig
return ip.getOrPutStringFmt(gpa, pt.tid, "{}__{s}_{d}", .{
block.type_name_ctx.fmt(ip), anon_prefix, @intFromEnum(type_index),
}, .no_embedded_nulls);
```
and the relevant lines in the langref (changed in this PR).
I figured a change to Sema like that would be pretty breaking so I assumed y'all would want the change in the langref and not a change to Sema, if the change is desired in Sema, I could put the dot in the format string, otherwise I woudn't know what to do since that block name comes from deep inside intern pool stuff.
Should I be …
=> fix typo in @typeName langref

doc/langref.html.in
This PR hopefully addresses the documentation issue pointed out in #14231, which is: tuples (e.g. `.{}`) are used in the [Hello World docs example](https://ziglang.org/documentation/master/#Hello-World) (usually the first thing a newcomer sees) without explaining what they are or mentioning what they're called.
To keep the Hello World section short, I opted to only mention the "Tuple" in the "See also" right underneath the Hello World example. Also, in the Tuples section, I mentioned that `.{}` is an empty tuple and linked to the Hello World example that uses it.
=> link to Tuples section in Hello World docs, and give an example of an empty tuple

CMakeLists.txt
Avoid hard coding the path of zig2 relative to PROJECT_BINARY_DIR, which is instead located in PROJECT_BINARY_DIR/\<config\> for the Ninja Multi-Config generator(`-G"Ninja Multi-Config"`).
=> Fix incompatibility with multi-config cmake generator

doc/langref.html.in
for a few releases now the textual description of cmpxchg has been incorrect; the code example has been correct; null is returned if the exchange successfully happens, not if it failed due to mismatch.
=> langref: fixes incorrect description of cmpxchg functions

lib/std/c/darwin.zig
Turns out this was already fixed in #21964.
I have no idea why GitHub showed an incorrect diff in #21273, or how applying the diff to master was even possible, but here we are.
=> Revert d714cf33405486d9aa707e9aee8f103a011d06e9 (#21273)

lib/std/zig.zig, src/main.zig
Modifies EnvVar.isSet() to assume empty strings are unset. This is required for correctly parsing NO_COLOR values, and ifreund suggested that all variables should follow this behavior.
Closes #22380.
=> Classify empty environment variables as unset

lib/std/heap/memory_pool.zig
I wanted an easy way to ``preheat()`` a MemoryPool that was already initialized.
So I split out ``initPreheated()`` to have a ``preheat(size)`` function that it calls, and can be used anytime you want to preheat the pool.
=> std.heap.memory_pool: make preheat() usable after init()

lib/std/compress/flate/Lookup.zig, lib/std/zip.zig
When I was looking at [`lib/std/compress/flate/Lookup.zig`](https://ziglang.org/documentation/master/std/#std.compress.flate.Lookup) and [`lib/std/zip.zig`](https://ziglang.org/documentation/master/std/#std.zip) in <https://ziglang.org/documentation/master/std/>, I noticed that the doc comments at the start of them were not visible.
I think it would be better if these doc comments is top-level doc comments rather than doc comments. Because it is at the start of the source file. Also, given the context, I don't think these are doc comments for `const std = @import("std");` and `const builtin = @import("builtin");`. This makes these doc comments visible.
However, the last paragraph of doc comments in `lib/std/zip.zig` replaces doc comments with normal comments. This is because I thought …
=> Fix invisible doccomments at the start of source files to make them visible

doc/langref.html.in, doc/langref/destructuring_arrays.zig, doc/langref/destructuring_block.zig, doc/langref/destructuring_mixed.zig, doc/langref/destructuring_return_value.zig, doc/langref/destructuring_to_existing.zig, doc/langref/destructuring_vectors.zig
=> langref: Document destructuring

CMakeLists.txt
in cmake `option()` defaults the argument to a boolean type, changing it into a cache variable retains the same behavior while making sure the correct type is used.
This is mostly useful for tooling around cmake that doesn't allow type changes without a complete reconfiguration.
=> cmake: use cache entry for extra build args to get the type correct

src/Sema.zig, src/Type.zig, src/Value.zig, test/cases/compile_errors/memcpy_alias.zig, test/cases/compile_errors/memcpy_bad_type.zig
* The langspec definition of `@memcpy` has been changed so that the source and destination element types must be in-memory coercible, allowing all such calls to be raw copying operations, not actually applying any coercions.
* Implement aliasing check for comptime `@memcpy`; a compile error will now be emitted if the arguments alias.
* Implement more efficient comptime `@memcpy` by loading and storing a whole array at once, similar to how `@memset` is implemented.
This is a breaking change because while the old coercion behavior triggered a Sema TODO at runtime, it did actually work at comptime.
=> Sema: `@memcpy` changes

lib/std/c.zig, lib/std/os/linux.zig, lib/std/posix.zig
Fixes #22194 
For optional pointer with WASI, passes 0 for atim and mtim and sets flags for ATIM_NOW and MTIM_NOW to true in futimens.
=> std: add optional times pointer for futimes, futimens, utimes, utimensat

lib/std/testing.zig
Fixes: #19454
In L128 of testing.zig, patterned to others like it (e.g., L755). Also added the original test from issue (as "expectEqual null").
Also moved 2 tests because those are also `expectEqual` tests.
=> std.testing.expectEqual: {any} in print and move tests

src/main.zig
`zig cc main.c -o /dev/null` emit `a.out`, `zig cc -E main.c` emit `main.o`, this pr modifies the linking and preprocessing generation logic to be more consistent with clang's behavior.
When using `clang -E main.c` or `clang -E main.c -o -` outputs directly to standard output, if using `clang -E main.c -o a` it outputs to a file.
Fix the following issues:
fixed: https://github.com/ziglang/zig/issues/20739
fixed: https://github.com/ziglang/zig/issues/20689
fixed: https://github.com/ziglang/zig/issues/20359
fixed: https://github.com/ziglang/zig/issues/20709
=> fix(cc): preprocessor doesn't emit bin

lib/std/c.zig
cc @alexrp 
https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/recv.2.html#//apple_ref/doc/man/2/recv
https://developer.apple.com/documentation/kernel/msghdr/1499171-msg_iovlen
https://github.com/ziglang/zig/blob/master/lib/libc/include/any-macos-any/sys/socket.h#L564
=> std.c: add `msghdr` and `msghdr_const` definitions for macos

lib/std/zig/target.zig
These are system DLLs, most of which MinGW provides `.def` files for. It just so happens that MinGW also has some static libraries by the same name which link in some GUID definitions.
The remaining non-MinGW library names represent libraries that are always statically linked, so if those are requested by the user, it makes sense to error if libc is not linked. A future enhancement could be to compile those independent of `mingw32.lib`, however.
Closes #22560.
=> `std.zig.target`: Remove some library names from `isLibCLibName()` for MinGW

lib/std/os/windows.zig, lib/std/posix.zig
- effects FreeBSD memfd and Windows DeleteFile
- regression: e5d5a8bc4ea6b27dc3540ad4800a1231ff50b33d
---
- PR tested on FreeBSD 14.1 and 12.4
- issue manifested on master, on FreeBSD 14.1:
```sh
$ zig test lib/std/std.zig
lib/std/posix.zig:6825:17: error: memfd_create is unavailable on FreeBSD < 13.0
@compileError("memfd_create is unavailable on FreeBSD < 13.0");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> std: fix comptime SemanticVersion expr regression

lib/compiler/build_runner.zig, lib/std/Build.zig, lib/std/Build/Fuzz.zig, lib/std/zig.zig
Currently `-freference-trace` only works when running from a terminal.
This is annoying if you're running in another environment or if you redirect the output.
But `-freference-trace` also works fine without the color, so just changing how the build runner is interpreting this option.
main.zig:
```
f();
}
pub fn f() void {
std.debug.print("Hello ", .{"world"});
}
```
console: 
```
> zig run main.zig
~/zig-macos-aarch64-0.14.0-dev.2851+b074fb7dd/lib/std/fmt.zig:206:18: error: unused argument in 'Hello '
1 => @compileError("unused argument in '" ++ fmt ++ "'"),
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
print__anon_5159: ~/zig-macos-aarch64-0.14.0-dev.2851+b074fb7dd/lib/std/io/Writer.zig:24:26
print__anon_2883: …
```
=> -freference-trace can work without colors

lib/std/Build/Module.zig, lib/std/Build/Step/Compile.zig
Closes #20655
The `addCSourceFile` functions gain an optional `language` field which defaults to the current behavior (find the language by the file extension of each input).
This does not add support for any new languages beyond what `addCSourceFile` already supports: the C languages and assembly.
=> Add option to specify language of CSourceFiles

src/main.zig
Fixes #19400
Before:
```
$ zig build --help
error: AccessDenied
```
Now:
```
$ zig build --help
error: unable to open or create the global Zig cache at '/not/real': AccessDenied.
If this location is not writable then consider specifying an alternative with the ZIG_GLOBAL_CACHE_DIR environment variable or the --global-cache-dir option.
```
=> Better `zig build` error message when the global cache dir is unusable

src/main.zig
=> link: ensure --whole-archive is passed down to linker for -l arguments

src/main.zig
This extracts the main change in #20384 without all the other fluff.
Closes #19613.
Per the code comment, I don't think there's any compelling reason to actually implement the functionality for these flags in 2024. But swallowing them unblocks a real use case for `zig cc`.
=> compiler: Accept and ignore `--(enable,disable)-auto-image-base` linker options.

lib/std/fs/File.zig
I don't think we need to alloc 1024 bytes if we are going to read only few bytes. e.g.: `file.readToEndAlloc(ally, 10)`
BTW maybe we can add a assertion `size_hint <= max_bytes` if `size_hint` is not null.
=> std.fs.File: limit initial_cap according to max_bytes in readToEndAllocOptions

lib/std/posix.zig
I noticed that ``std.posix.setsockopt`` exists but not ``std.posix.getsockopt``. 
I tried to add it, but I'm not sure if the anyopaque / optlen approach is a good one.
https://linux.die.net/man/3/getsockopt
=> std.posix: adding getsockopt

lib/std/os/linux.zig
Adding the ``recvmmsg()`` syscall.
There are a couple of items to consider before this is ready:
1) should ``timeout`` be a ``?*timespec`` because it can be called with ``null``?
2) the return value from ``recvmmsg()`` is an ``int``, i'm not sure if this is wrong to return a ``usize``, and it would need to be passed to ``E.init(r)`` for errno purposes.
3) I noticed ``recvmsg`` has ``if (native_arch == .x86) { return socketcall(...); }``, perhaps we want that also for ``recvmmsg``? But ``sendmmsg`` doesn't use ``socketcall``?
=> std.os.linux: adding recvmmsg()

lib/std/debug.zig, lib/std/debug/MemoryAccessor.zig
- patch authored by Jacob Young
- tested on alpine-aarch64, 3.21.0, qemu-system 9.2.0
- issue manifested on Alpine Linux aarch64 under qemu-system where zig2 fails during bootstrap: `error.ProcessFdQuotaExceeded`
Fixes #21701
=> debug: fix MemoryAccessor file leak

src/Sema.zig, src/Type.zig, test/behavior/memcpy.zig
=> Sema: skip aliasing check and runtime operation for `@memcpy` of zero-bit type

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, src/print_zir.zig, test/behavior/try.zig, test/cases/compile_errors/redundant_try.zig
This commit effectively reverts 9e683f0, and hence un-accepts #19777. While nice in theory, this proposal turned out to have a few problems.
Firstly, supplying a result type implicitly coerces the operand to this type -- that's the main point of result types! But for `try`, this is actually a bad idea; we want a redundant `try` to be a compile error, not to silently coerce the non-error value to an error union. In practice, this didn't always happen, because the implementation was buggy anyway; but when it did, it was really quite silly. For instance, `try try ... try .{ ... }` was an accepted expression, with the inner initializer being initially coerced to `E!E!...E!T`.
Secondly, the result type inference here didn't play nicely with `return`. If you write `return try`, the operand …
=> compiler: do not propagate result type to `try` operand

lib/std/priority_queue.zig
The `ensureTotalCapacityPrecise`, `clearRetainingCapacity` and `clearAndFree` functions from the ArrayList API are also useful for a PriorityQueue.
=> std.priority_queue: add useful functions from ArrayList API

build.zig, lib/std/Target.zig
- llvm requires libexecinfo which has conflicting symbols with libc++abi
- workaround is to link c++abi dynamically
---
- cleanup a few other bsd prongs - unchanged behaviour
- tested on x86_64, OpenBSD 7.6, 7.1, FreeBSD 14.2, NetBSD 10.1, DragonflyBSD 6.4, macOS 15.3
=> openbsd: fix stage3 link

lib/std/Random.zig, lib/std/mem/Allocator.zig, lib/std/process/Child.zig
This is an alternative to https://github.com/ziglang/zig/pull/21760 (it's the 1st option in that PR's description):
> Codify that comparing ptr is always illegal/unsafe, and remove all existing comparisons.
(suggested for exploration here: https://github.com/ziglang/zig/pull/21760#issuecomment-2625965026)
However, I personally think this is probably not the best solution to https://github.com/ziglang/zig/issues/21756 / https://github.com/ziglang/zig/issues/17704, for a few reasons:
- A doc comment is about the best we can currently do to help unsuspecting users to avoid comparing these fields and invoking (currently unchecked, see https://github.com/ziglang/zig/issues/211) illegal behavior
- Unless I'm thinking about it wrong, in the future it seems likely that this illegal behavior would …
=> Document that the `ptr` field of Allocator/Random should not be compared and remove existing comparison

lib/std/zig/Ast.zig, lib/std/zig/AstGen.zig, test/cases/compile_errors/normal_string_with_newline.zig, test/cases/compile_errors/tab_inside_comment.zig, test/cases/compile_errors/tab_inside_doc_comment.zig, test/cases/compile_errors/tab_inside_multiline_string.zig, test/cases/compile_errors/tab_inside_string.zig, test/compile_errors.zig
This change provides a correct error message when an invalid byte is found inside of a multiline string line, comments, and doc comments. 
<Details>
<Summary>Inside multiline strings</Summary>
Taking the example from #20900:
```zig
const foo =
\\const S = struct {
\\<TAB>// hello
\\}
;
```
Before:
```shell
src/main.zig:4:1: error: expected ';' after statement
\\ // hello
^
```
After:
```shell
src/main.zig:4:5: error: expected 'a string literal', found invalid bytes
\\ // hello
^~~~~~~~~~~
src/main.zig:4:7: note: invalid byte: '\t'
\\ // hello
^~~~~~~~~~~
```
</Details>
<Details>
<Summary>Doc comments</Summary>
```zig
/// Some <TAB>comment
```
Before:
```shell
src/main.zig:1:1: error: expected type expression, found 'invalid token'
/// Some  comment
^~~~~~~~~~~~~~~~~
```
After:
```shell …
```
=> fix: Correct error message for invalid bytes in multiline strings and comments

lib/std/compress.zig
This seems like a simple typo.  The values are immediately used in a struct as types, so there's no reason to use anytype here, afaik.
=> fix typo of anytype to type

src/Zcu/PerThread.zig
Unfortunately, I can't easily add a test for this, because the repro depends on some details of DWARF layout; but I've confirmed that it fixes a bug repro on another branch.
=> incremental: codegen types which are recreated

lib/std/io/tty.zig, lib/std/process.zig, lib/std/zig.zig, src/main.zig
An alternative to #22757, adding ``hasNonEmptyEnvVar()`` and using for NO_COLOR support.
Fixes #22756.
=> std.process: adding hasNonEmptyEnvVar() functions

lib/std/crypto/phc_encoding.zig
The spec is ambiguous, and it's too late to change it.
So the most reasonable thing to do in order to avoid generating strings that could be parsed differently by other implementations is to forbid parameters named "v" at compile-time.
See https://github.com/P-H-C/phc-string-format/issues/8
=> crypto/phc-encoding: forbid parameters named 'v'

doc/langref.html.in
The previous language using subsets was really just stating a couple of the properties of the union of a group of sets, and with a minor error at that.
=> langref/errorset: Replace subset description with union

src/link/Dwarf.zig
This ensure capacity call does not match the number of appendAssumeCapacity() calls that follow it. Fix this.
This was discovered due to hitting the assertion failure in appendAssumeCapacity() while building river.
I'm not sure how to isolate a minimal reproducer for a test.
=> Dwarf: fix cross_section_relocs capacity

lib/std/os/uefi/protocol/file.zig
`getEndPos` always returns 0 due to logic error.
=> fix getEndPos in uefi.protocol.file

lib/libc/include/generic-glibc/bits/spawn_ext.h, lib/libc/include/generic-glibc/bits/statx-generic.h, lib/libc/include/generic-glibc/sys/mount.h, lib/libc/include/generic-glibc/sys/pidfd.h, lib/libc/include/generic-glibc/unistd.h
Guard the declaration of:
* `close_range` (introduced in 2.34)
* `statx` (introduced in 2.28)
* `fsopen`, `fsmount`, `move_mount`, `fsconfig`, `fspick`, `open_tree`, `mount_setattr` (introduced in 2.36)
* `pidfd_open`, `pidfd_getfd`, `pidfd_send_signal` (introduced in `2.36)
* `pidfd_getpid` (introduced in 2.39)
This fixes building util-linux` while targeting glibc `2.17` (or any version prior to 2.39)
=> glibc: guard more function declarations

lib/libc/include/generic-glibc/bits/mman-shared.h
They were introduced in glibc 2.27
=> generic glibc: guard memfd_create & mlock2 declarations

lib/std/multi_array_list.zig
pulled out of https://github.com/ziglang/zig/pull/19424
=> std.MultiArrayList: popOrNull() -> pop() [v2]

lib/std/Build/Cache.zig, lib/std/array_hash_map.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/codegen/c.zig, src/link/Coff.zig
pulled out of https://github.com/ziglang/zig/pull/19424
=> std.ArrayHashMap: popOrNul() -> pop() [v2]

lib/std/os/uefi/pool_allocator.zig
Related #22806
Makes the UEFI allocators compile now
=> std.os.uefi: fix allocators compiling

lib/std/crypto/Certificate/Bundle/macos.zig
This adds `/Library/Keychains/System.keychain` as a keychain to look for trusted CA certficates.  Fixes #22700
=> Read System.keychain as well as SystemRootCertificates.keychain for MacOS CA Bundle

lib/std/heap/SmpAllocator.zig
I tested various combinations, and generally found bigger batches of frees to
work better.
Freelist length accounting in alloc had a negative impact, especially with the
integer type bumped up to u16, so I even tried changing the system to be based
on counting slabs rather than total allocations.
It all ended up being worse perf than the simple thing when used with the
compiler however. Also, I realized that even with the simple free logic, it's
capable of reclaiming the freelist memory because allocations can win the race.
The freelist length accounting definitely reduces peak_rss in the asymmetric
example, however, I haven't found it to matter for the real wold use case of
the Zig compiler.
from [Carmen's Playground](https://github.com/andrewrk/CarmensPlayground)
```
Benchmark 1 (6 …
```
=> std.heap.SmpAllocator: back to simple free implementation

lib/std/Target.zig, lib/std/debug.zig, lib/std/os/uefi.zig, lib/std/os/uefi/device_path.zig, lib/std/os/uefi/pool_allocator.zig, lib/std/os/uefi/protocol/block_io.zig, lib/std/os/uefi/protocol/device_path.zig, lib/std/os/uefi/protocol/file.zig, lib/std/os/uefi/protocol/graphics_output.zig, lib/std/os/uefi/protocol/hii_popup.zig, lib/std/os/uefi/protocol/ip6.zig, lib/std/os/uefi/protocol/ip6_config.zig, lib/std/os/uefi/protocol/managed_network.zig, lib/std/os/uefi/protocol/serial_io.zig, lib/std/os/uefi/protocol/simple_network.zig, lib/std/os/uefi/protocol/udp6.zig, lib/std/os/uefi/status.zig, lib/std/os/uefi/tables.zig, lib/std/os/uefi/tables/boot_services.zig, lib/std/os/uefi/tables/runtime_services.zig, lib/std/os/uefi/tables/system_table.zig, lib/std/posix.zig, lib/std/time.zig
Tested locally against the Kiesel UEFI build, unsure if _everything_ builds though (ref #22809).
=> std.os.uefi: Various tweaks

lib/std/c.zig, lib/std/fs/Dir.zig, lib/std/fs/test.zig, lib/std/os/wasi.zig, lib/std/posix.zig, lib/std/posix/test.zig
Zig's copy of the `SYMLINK_{NO,}FOLLOW` constants from wasi-musl was wrong, as were the `IFIFO` and `IFSOCK` file type flags.  Fix these up, and add comments pointing to exactly where they come from (as wasi-musl has lots of unused, different definitions of these constants).
Add tests for the Zig convention that WASM preopen 3 is the current working directory.   This is true for WASM with or without libc.
Enable several fs and posix tests that are now passing (not necessarily because of this change) on wasm targets.
Fixes #20890.
=> wasi: fix wasm-wasi-musl SYMLINK_{NO,}FOLLOW constants and enable tests

lib/std/c.zig
The size field is not supposed to be signed. See: https://man.openbsd.org/sigaltstack.2
=> std.c: Fix definition of stack_t on OpenBSD

lib/std/mem.zig
Passing a `needle` with a length greater than the `haystack`'s length caused an integer overflow (illigal behavior). This behavior is not documented in the docs and is inconsistent with std.mem.indexOfPosLinear, where the check is present.
=> std.mem: add missing check to lastIndexOfLinear

lib/compiler/resinator/main.zig
Fixup for some of the changes in https://github.com/ziglang/zig/pull/22522
Noticed this while working on https://github.com/ziglang/zig/pull/22813, but these fixes should be made regardless of what happens with that PR.
=> resinator: Fix some error message integration

lib/std/fmt.zig
Lets look at a little example program:
```zig
std.debug.print("{{a: {d}, b: 0x{x}, c: {s}}}\n", .{ 0, 0xabc, "foo" });
}
```
When I compile this with `zig build-exe test.zig -O ReleaseSmall -femit-bin=master` the output of `strings master` includes `{{a: {d}, b: 0x{x}, c: {s}}}`.
I was wondering why the placeholders were included in the binary, since they are evaluated at compile time. This PR changes that.
After this PR the output of `strings branch` includes `{a: `, `, b: 0x`, `, c: ` and `}` instead.
Binary size changes:
```
$ du -b master branch
6320    master
6240    branch
```
`strace` changes:
```diff
@@ -1,16 +1,14 @@
-execve("./master", ["./master"], 0x7ffca0e79590 /* 52 vars */) = 0
+execve("./branch", ["./branch"], 0x7ffc85107730 …
```
=> std.fmt: remove placeholders from binary

src/codegen/c.zig, test/behavior/call.zig
=> cbe: fix crash rendering argument names in lazy functions

lib/compiler_rt/memcpy.zig
when compiled in debug mode (--debug-rt)
before:
```
andy@bark ~/s/z/build-release (master)> stage3/bin/zig test ../test/behavior.zig --debug-rt
error: the following test command crashed:
/home/andy/src/zig/.zig-cache/o/d67352db25a508f21ac48aa4a6e52b3e/test --seed=0xa5e06631
```
after:
```
andy@bark ~/s/z/build-release (fix-debug-memcpy)> stage3/bin/zig test ../test/behavior.zig --debug-rt
...
1910 passed; 100 skipped; 0 failed.
```
----
This code seems broken to me either way. It's the memcpy implementation, you can't copy arbitrary unaligned lengths of bytes, even if they are power of two.
This code needs to be reworked to not be recursive. This patch has only the quality of a temporary bandage.
=> compiler_rt memcpy: avoid infinite recursion

src/link/Elf/Atom.zig, src/link/riscv.zig
Just extracting this commit by @Rexicon226 from #22235 since we'll want this change regardless of that PR.
=> `link.Elf`: Implement `{SET,SUB}_ULEB128` relocations for RISC-V

lib/compiler/test_runner.zig, lib/fuzzer.zig, lib/init/src/main.zig, lib/std/testing.zig, lib/std/zig/tokenizer.zig, src/zig_llvm.cpp
breaking change to the fuzz testing API; it now passes a type-safe context parameter to the fuzz function.
libfuzzer is reworked to select inputs from the entire corpus.
I tested that it's roughly as good as it was before in that it can find the panics in the simple examples, as well as achieve decent coverage on the tokenizer fuzz test.
however I think the next step here will be figuring out why so many points of interest are missing from the tokenizer in both Debug and ReleaseSafe modes.
does not quite close #20803 yet since there are some more important things to be done, such as opening the previous corpus, continuing fuzzing after finding bugs, storing the length of the inputs, etc.
the main change here is that fuzz input corpus is stored at `.zig-cache/f/{s}/{d}`, where {s} is the …
=> fuzzer: write inputs to shared memory before running

lib/std/array_hash_map.zig
I have a hunch that this will be a better default. Will post perf data points shortly.
=> std.ArrayHashMap: base linear_scan_max on cache line size

lib/std/fmt.zig
Difference:
```
$ cat x.zig
pub const std_options = std.Options{ .keep_sigpipe = true };
std.io.getStdOut().writer().print("{d}\n", .{@intFromPtr(std.os.argv.ptr)}) catch {};
}
$ zig build-exe x.zig -OReleaseSmall -fsingle-threaded -fno-unwind-tables && wc -c x
2576 x
$ zig build-exe x.zig -OReleaseSmall -fsingle-threaded -fno-unwind-tables --zig-lib-dir ../zig/lib && wc -c x
2424 x
```
=> std.fmt.digits2: optimize for ReleaseSmall

lib/std/array_list.zig, lib/std/json/scanner_test.zig, lib/std/json/static_test.zig, lib/std/multi_array_list.zig, lib/std/zig/string_literal.zig
also std.MultiArrayList
build zig with itself (ReleaseFast, no libc)
```
Benchmark 1 (3 runs): master/bin/zig build-exe ...
wall_time          12.7s  ±  106ms    12.6s  … 12.8s           0 ( 0%)        0%
peak_rss            983MB ± 25.8MB     956MB … 1.01GB          0 ( 0%)        0%
cpu_cycles         93.7G  ± 63.0M     93.6G  … 93.7G           0 ( 0%)        0%
instructions        197G  ± 2.72M      197G  …  197G           0 ( 0%)        0%
cache_references   5.69G  ± 12.6M     5.67G  … 5.70G           0 ( 0%)        0%
cache_misses        413M  ± 2.31M      411M  …  415M           0 ( 0%)        0%
branch_misses       491M  ±  306K      491M  …  492M           0 ( 0%)        0%
Benchmark 2 (3 runs): …
```
=> std.ArrayList: initial capacity based on cache line size

lib/std/os/windows/kernel32.zig, lib/std/os/windows/ntdll.zig, lib/std/posix.zig, lib/std/time.zig
Closes #22460
`std.windows.SharedUserData.SystemTime` is basically what `GetSystemTimeAsFileTime` used and `NtQuerySystemTimePrecise` which was mentioned in a comment doesn't exist. ~~so unfortunately the kernel32 dependency in this case can't be removed~~
=> std.time: more precise `nanoTimestamp` in windows

lib/libc/include/generic-glibc/fts.h
This PR prevents the 64bits variants of the `fts_*` API from being declared before glibc 2.23.
It also prevents the 64bits time variants from being declared when targeting glibc versions <2.34
=> glibc: don't redirect fts to fts64 before glibc 2.23

lib/zig.h
As opposed to "GNU C" (`zig_gnuc`) which includes Clang.
This addresses #22890 but does not fix it until a `zig1.wasm` update.
=> `zig.h`: Add new `zig_gcc` macro to indicate GCC.

lib/std/net.zig
The check is not needed, since we are already checking for the os at line 847 and returning at 916 when the check succeeds. Therefore, at 926, we know the os is not windows.
Closes #22882
=> remove unneeded native_os check

lib/compiler_rt/common.zig
Until #21630 is addressed.
Closes #22893.
=> `compiler-rt`: Use Windows Arm ABI routines for UEFI for now.

lib/std/testing.zig
With a simple test like this:
```zig
const MyStruct = struct {
foo: u32,
bar: union {
a: u16,
b: f32,
},
};
const testing = @import("std").testing;
test {
const x: MyStruct = .{
.foo = 1,
.bar = .{ .a = 9 },
};
const y: MyStruct = .{
.foo = 2,
.bar = .{ .b = 1.5 },
};
try testing.expectEqual(x, y);
}
```
Prior to this change, the compile error would look like:
```
$ zig test ./test.zig
/.../zig/lib/std/testing.zig:150:17: error: Unable to compare untagged union values
@compileError("Unable to compare untagged union values");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
After this change, the compile error includes the name of the type containing the untagged union:
```
$ zig test ./test.zig
/.../zig/lib/std/testing.zig:150:17: error: Unable to compare untagged union values …
```
=> std.testing: improve compile error on untagged union equality

src/Sema.zig, test/cases/compile_errors/invalid_variadic_function.zig
As calling convention may not be specified explicitly in the source, so use va_arg's location instead.
=> Sema: make source location in checkCallConvSupportsVarArgs more meaningful

lib/std/heap.zig, lib/std/heap/sbrk_allocator.zig
This fixes the sbrk allocator build failures tracked by #22806, and adds a test to `std` that ensures the allocator continues to compile in the future.
There were two failures I needed to fix to get this working:
1. The `Allocator.VTable` was missing `remap`. I declared the function using the same implementation as the arena allocator.
2. Function signatures switched from `u8` to `mem.Alignment`. I switched over, and started calling `toByteUnits()` to perform the same conversion as before.
I validated this change by running std tests with `zig test lib/std/std.zig --zig-lib-dir lib`.
I confirmed that they fail with the newly added test, and then pass after the code change.
=> Fix build failure in sbrk allocator, caused by #20511

lib/std/crypto/aegis.zig
In the MAC finalization function, concatenated tags at odd positions were not absorbed into the correct lane.
Spotted by a Tigerbeetle regression test and reported by Rafael Batiati (@batiati) — Thanks!
=> crypto.auth.Aegis128X*Mac: properly absorb tags in the first lane

lib/std/crypto/Certificate/Bundle/macos.zig
In the original PR that implemented `rescanMac` (https://github.com/ziglang/zig/pull/14325), it included a list of references for the keychain format. Multiple of those references include the checks that are added in this commit, and empirically this fixes the loading of a real keychain file that was previously failing (it had both a record with offset 0 and a record with cert_size 0).
To give more detail: when not skipping a record with offset zero, it would attempt to read the base of the table as a `X509CertHeader`, but the base of the table is actually a `TableHeader`. It would then take this misinterpreted `X509CertHeader` and read N bytes that follow it (where N is equal to the misinterpreted `cert_size`), and then try to parse those bytes as a DER cert. These bytes are just some …
=> Skip empty/invalid records/certs in MacOS keychain files

lib/std/meta.zig
A very simple change to reflect the new [std.builtin.Type](https://ziglang.org/documentation/master/std/#std.builtin.Type) format
=> docs: update old reference from builtin.Type.Struct to builtin.Type.@"struct"

lib/std/crypto/bcrypt.zig, lib/std/crypto/benchmark.zig
This removes the need for having both `bcrypt()` and `bcryptWithTruncation()` in the public API.
And whether truncation happens or not becomes even more explicit.
=> crypto.pwhash.bcrypt: make silently_truncate_password a member of Params

lib/std/posix.zig, lib/std/posix/test.zig
Four tests in lib/std/posix/test.zig were disabled because they created fixed-name files in the current working directory, and this caused problems if tests were running in parallel with other build's tests.
This PR fixes those tests to all use `std.testing.tmpDir` to create unique temporary names and directories.
Also clean the tests up to more consistently use `defer` to clean up, or to just rely on tmpDir cleanup to remove individual files.
Working on these tests revealed a bunch of stale WASI code paths in posix.zig, fixed by replacing stale `wast.AT.FDCWD` references with just `AT.FDCWD`.
Fixes #14968.
=> lib/std/posix/test.zig: enable disabled tests using CWD

lib/std/crypto/timing_safe.zig
It turns out that Valgrind can be a very useful tool to check that secrets are not leaked via side channels involving lookups or conditional jumps.
Valgrind tracks uninitialized data, and memcheck reports operations involving uninitialized values. By permanently or temporarily telling Valgrind that a memory region containing secrets is uninitialized, we can detect common side-channel vulnerabilities.
For example, the following code snippets would immediately report that the result is not computed in constant time:
```zig
classify(&key);
const len = std.mem.indexOfScalar(u8, &key, 0);
```
```zig
classify(&key);
const idx = key[0];
x += idx;
```
```zig
var x: [4]u8 = undefined;
std.crypto.random.bytes(&x);
classify(&x);
if (std.mem.eql(u8, "test", &x)) return;
```
This is not fool-proof, …
=> std.crypto: add the ability to explicitly tag a value as secret

test/src/Debugger.zig
On my machine, the defaults are 5 seconds (LLDB) and 2 seconds (GDB). These are too low on the CI machines during high load, and the CI system itself already enforces a timeout on jobs anyway, so just disable the timeout altogether.
=> `test`: Disable packet timeout for debugger tests.

lib/std/crypto/Certificate/Bundle/macos.zig
Something random I noticed while investigating https://github.com/ziglang/zig/issues/22870
---
readAtLeast is greedy and will read the entire length of the buffer if it can. However, reading past the end of the cert in this case is useless, so reading the full length of the buffer just puts an increasingly large (due to the growth algorithm of ArrayList) collection of wasted bytes after each cert in cb.bytes.
In practical terms, this ends up saving potentially millions of bytes of wasted reads/allocations. In my testing, after reading the keychain files on my machine, cb.bytes ends up with these capacities:
- Before this PR: cb.bytes.capacity = 32720747
- After this PR: cb.bytes.capacity = 251937
That's a decrease of 99.2%
Additionally, swaps to readNoEof since it should be an error to …
=> rescanMac: Avoid overallocating/overreading by millions of bytes

lib/fuzzer.zig, src/Compilation.zig, src/codegen/llvm.zig
- allow `-fsanitize-coverage-trace-pc-guard` to be used on its own without enabling the fuzzer. (note that previouly, while the flag was only active when fuzzing, the fuzzer itself doesn't use it, and the code will not link as is.)
- add stub functions in the fuzzer to link with instrumented C code (previously fuzzed tests failed to link if they were calling into C): while the zig compile unit uses a custom `EmitOptions.Coverage` with features disabled, the C code is built calling into the clang driver with "-fsanitize=fuzzer-no-link" that automatically enables the default features. (see https://github.com/llvm/llvm-project/blob/de06978ebcff5f75913067b019d2d522d0be0872/clang/lib/Driver/SanitizerArgs.cpp#L587)
- emit `-fsanitize-coverage=trace-pc-guard` instead of `-Xclang …
=> fix `-fsanitize-coverage-trace-pc-guard` and fuzzer support for C compile units

lib/std/posix.zig
`EACCES` is returned if the file mode bit (i.e., user/group/other rwx bits) disallow access (mapped to `error.AccessDenied`).  `EPERM` is returned if something else denies access (immutable bit, SELinux, capabilities, etc) and is mapped to `error.PermissionDenied`.  This somewhat subtle distinction in errors is part of POSIX, and can happen in practice on Linux or MacOS.
This PR is effectively an update/simplification of (abandoned) PR #19193.  See #16782 for deeper problems with the AccessDenied/PermissionDenied duopoly in Zig.
Tested locally with an immutable file.
Fixes #22733 and #19162.
=> posix: access/accessZ/faccessat/faccessatZ can return AccessDenied or PermissionDenied

lib/std/time.zig
For the `Timer` decltest in particular, the `margin` check is not going to help if the kernel just decides not to schedule the thread for a while after we call `timer.reset()`.
Failure observed here: https://github.com/ziglang/zig/actions/runs/13443634035/job/37563803341?pr=22909
=> `std.time`: Make tests less flaky.

lib/std/crypto/25519/ed25519.zig
When runtime safety is turned on, `Ed25519.fromSecretKey()` can currently hit an assertion if the format of the secret key is invalid.
Return an error instead, so that applications can recover.
=> crypto.Ed25519.KeyPair: return an error rather than assert

lib/std/atomic.zig
This fixes potential issues and unintended coercions in other areas, such as std.ArrayList.
Previously:
```
const Foo = struct { buf: [68536]u8 = undefined };
var gpa = std.heap.GeneralPurposeAllocator(.{}){};
var v = std.ArrayList(Foo).init(gpa.allocator());
v.append(undefined) catch unreachable;
}
```
would yield
```
/home/kiedtl/zig14/lib/std/array_list.zig:1220:81: error: type 'u16' cannot represent integer value '68536'
const init_capacity = @as(comptime_int, @max(1, std.atomic.cache_line / @sizeOf(T)));
^~~~~~~~~~
referenced by:
growCapacity: /home/kiedtl/zig14/lib/std/array_list.zig:1227:35
ensureTotalCapacity: /home/kiedtl/zig14/lib/std/array_list.zig:449:89
8 reference(s) hidden; use '-freference-trace=10' to see all references
``` …
=> std.atomic: make cache_line const a comptime_int

src/Sema.zig, src/Type.zig, src/target.zig, test/behavior/align.zig
As seen on e.g. Arm/Thumb.
Fixes #22888.
=> `Sema`: Fix fnptr alignment safety checks to account for potential ISA tag.

lib/std/Build/Step/Compile.zig, src/Compilation.zig, src/link.zig, src/link/MachO.zig, src/link/MachO/InternalObject.zig, src/link/MachO/Object.zig, src/link/MachO/ZigObject.zig, src/link/MachO/synthetic.zig, src/main.zig, test/link/macho.zig
This can also be extended to ELF later as it means roughly the same thing there.
This addresses the main issue in #21721 but as I don't have a macOS machine to do further testing on, I can't confirm whether `zig cc` is able to pass the entire cgo test suite after this commit. It can, however, cross-compile a basic program that uses cgo to `x86_64-macos-none` which previously failed due to lack of `-x` support. Unlike previously, the resulting symbol table does not contain local symbols (such as C `static` functions).
I believe this satisfies the [related donor bounty](https://ziglang.org/news/second-donor-bounty), though it's not clear to me if the bounty also requires getting the whole cgo test suite passing; if yes, someone else will have to take it from here.
=> `link.MachO`: Add support for the `-x` flag (discard local symbols).

lib/docs/index.html, lib/docs/main.js, lib/docs/wasm/Walk.zig, lib/docs/wasm/main.zig
This PR aims to improve error handling and reporting in Autodoc, to help address potentially confusing scenarios such as the one described here: https://ziggit.dev/t/file-has-unexpected-syntax-error-when-building-documentation/8387
There are several changes included:
- Any parse errors in source files are reported to the user, and the AST is replaced with that of an empty file to avoid the rest of Autodoc bugging out when trying to handle an incomplete/invalid AST.
- The "file must contain trailing newline" check is converted from an assertion to a reported and handled error.
- The JS log function is enhanced to accept the log level so it can use `console.error`, `console.warn`, etc. instead of `console.log` (this brings several benefits, including colors in the browser console and stack …
=> Autodoc: improve error reporting

lib/docs/wasm/Decl.zig, lib/docs/wasm/main.zig
This change adds additional information to Autodoc for types such as ArrayList, StaticStringMap, BoundedArray, and more, by inspecting the contents of the function and surfacing information from the type returned by the function, if possible.
The [current documentation](https://ziglang.org/documentation/master/std/#std.array_list.ArrayList) for `ArrayList` displays a doc comment, as well as function parameters and source code.
Important information is missing from the docs, such as the presence of the `items` field, and functions for adding/removing/etc. People have to read the source code to know that `ArrayList` is really an alias for `ArrayListAligned`, and go to the documentation there to see the available functions. The `items` field doesn't show up on the …
=> Autodoc: Improve documentation for common types declared as type functions

lib/std/hash.zig, lib/std/hash/RapidHash.zig, lib/std/hash/benchmark.zig, lib/std/hash/rapidhash.zig
This is the a zig implementation of the rapidhash successor to wyhash.
It's an improvement on small key performance and quality. Especially now that wyhash is no longer being maintained.
=> Add rapidhash

lib/std/dynamic_library.zig, lib/std/elf.zig
See ["Loading `libvulkan.so.1` on Linux with `std.ElfDynLib`"](https://ziggit.dev/t/loading-libvulkan-so-1-on-linux-with-std-elfdynlib/8480) topic on Ziggit for some related commentary.
=> std.DynLib: add support for DT_GNU_HASH sections in elf files

src/link.zig, test/link/elf.zig
Currently zig fails to build while linking the system LLVM/C++ libraries
on my Chimera Linux system due to the fact that libc++.so is a linker
script with the following contents:
INPUT(libc++.so.1 -lc++abi -lunwind)
Prior to this commit, zig would try to convert "ambiguous names" in
linker scripts such as libc++.so.1 in this example into -lfoo style
flags. This fails in this case due to the so version number as zig
checks for exactly the .so suffix.
Furthermore, I do not think that this conversion is semantically correct
since converting libfoo.so to -lfoo could theoretically end up resulting
in libfoo.a getting linked which seems wrong when a different file is
specified in the linker script.
With this patch, this attempted conversion is removed. Instead, zig
always first checks if the …
=> link: fix ambiguous names in linker scripts

src/arch/wasm/CodeGen.zig, test/behavior/switch.zig, test/behavior/switch_loop.zig
=> stage2-wasm: implement AIR handling for labeled switch/continue

src/codegen/llvm.zig, src/codegen/llvm/Builder.zig
This is a correctness issue: When `-fno-builtin` is used, we must assume that we could be compiling the `memcpy`/`memset` implementations, so generating calls to them is problematic.
```
Benchmark 1 (3 runs): ./release/bin/zig build -Doptimize=ReleaseFast -Dno-lib -Denable-llvm=false -Duse-llvm=false
wall_time          12.5s  ± 69.2ms    12.4s  … 12.5s           0 ( 0%)        0%
peak_rss           1.13GB ± 5.96MB    1.13GB … 1.14GB          0 ( 0%)        0%
cpu_cycles         98.3G  ±  105M     98.2G  … 98.4G           0 ( 0%)        0%
instructions        270G  ±  147M      270G  …  270G           0 ( 0%)        0%
cache_references    227M  ±  204K      227M  …  227M           0 ( 0%)        0% …
```
=> `llvm`: Use inline variants of `memcpy`/`memset` intrinsics when using `-fno-builtin`

test/compile_errors.zig, test/nvptx.zig, test/src/Cases.zig
We now run incremental tests with `tools/incr-check.zig` (with the actual cases being in `test/incremental/`).
=> cases: remove old incremental case system

lib/compiler/resinator/cli.zig, lib/compiler/resinator/cvtres.zig, lib/compiler/resinator/main.zig
This is a fully optional PR that addresses a use case that will only be temporarily supported, since all `resinator` code and the `zig rc` subcommand is likely to be removed when Windows resource compilation becomes a build system thing (see https://github.com/ziglang/zig/pull/22522 for context).
Is what's described below worth the temporary addition of an extra thousand+ lines of code?
Note: This only touches files within `lib/compiler/resinator`
---
In #22522 I said:
> RC="zig rc" will now work in combination with zig cc and CMake. Here's an example of cross-compiling a simple Windows GUI CMake project
>
> ```
> $ RC="zig rc" CC="zig cc --target=x86_64-windows-gnu" cmake .. -DCMAKE_SYSTEM_NAME=Windows -G Ninja
> ```
However, I didn't realize at the time that this only works because of …
=> `zig rc`: Add COFF object file creation for CMake cross-compilation use case

src/Type.zig, test/behavior/eval.zig
=> Type: resolve union tag type before checking for runtime bits

lib/std/crypto/tlcsprng.zig
=> std.crypto.tlcsprng: Fix hardcoded use of defaultRandomSeed()

src/Type.zig, src/Value.zig, src/link/Dwarf.zig, test/behavior/optional.zig
=> Dwarf: fix lowering of comptime-only optional pointer `null` values

lib/std/net.zig, lib/std/net/test.zig
Fixes a bug in Ip6Address.format where improper zero-run handling led to incorrect IPv6 compression.
This PR fixes https://github.com/ziglang/zig/issues/22440.
=> std.net: Fix IPv6 address format compression for long zero runs

lib/std/Build/Step/ConfigHeader.zig
The current public interface of `std.Build.Step.ConfigHeader` only allows configuration values to be added at comptime using `addValues()`. This pull request adds a new public functon `addValue` that enables configuration values to be added during build graph construction, i.e. while the `build()` function runs.
This change allows values to be determined by checks that cannot be performed at comptime, such as inspection of system features or build dependencies.
=> std.Build: Allow ConfigHeader values to be added outside of comptime

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
=> std.math.big.int: Support strings up to base 36

lib/std/Build/Step/ConfigHeader.zig
Autoconf configuration header templates often use `#undef` directives as substitution hooks, which we already support via `ConfigHeader.Style.autoconf`. However, many projects, particularly those using Gnulib, additionally rely on `@FOO@`-style [output variables](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.72/autoconf.html#index-AC_005fSUBST-1) for header configuration. While some of these cases can be handled using `Style.cmake`, this fails when the template happens to contain strings like `${FOO}`.
For example, the [Gnulib](https://savannah.gnu.org/projects/gnulib) header template `lib/unistd.in.h` uses `@FOO@`-style substitutions, but also happens to contain the string `${LOGNAME-$USER}` in a code comment. This is misinterpreted as a substitution hook by …
=> std.Build.Step.ConfigHeader: Add support for Autoconf-style `@FOO@` variables

src/codegen/llvm.zig
It appears to just be a 1:1 copy of riscv64, including the super weird sign extension quirk for `u32`.
Contributes to #21671.
=> `llvm`: Fix C ABI integer promotion for loongarch64.

lib/std/zig/AstGen.zig, lib/std/zig/AstRlAnnotate.zig, lib/std/zig/BuiltinFn.zig, lib/std/zig/Zir.zig, lib/zig.h, src/InternPool.zig, src/Sema.zig, src/codegen/c.zig, src/codegen/llvm.zig, src/print_zir.zig
This implements #22110, and in a way that also satisfies the use case for #21833. If accepted, this would therefore supersede #21900.
I won't add any usage of this builtin to compiler-rt and std yet as this will require a `zig1.wasm` update.
Closes #21833.
Closes #22110.
=> compiler: Implement `@disableIntrinsics()` builtin function.

lib/std/Thread.zig, lib/std/debug/Dwarf.zig, lib/std/posix.zig
This patch adds `MappingAlreadyExists` to the `MMapError` error set and ensures that `mmap` correctly handles `EEXIST`, which can only be returned when using the `MAP_FIXED_NOREPLACE` flag.
1. **Updated `MMapError` in `std.posix`**  
- Added `MappingAlreadyExists` to the error set.  
- Matched `E.EXIST` to this new error in the `mmap` function.  
2. **Updated `loadPath` in `std.debug.Dwarf.zig`**  
- Replaced `try` with `catch` on the `mmap` call site to explicitly mark `MappingAlreadyExists` as `unreachable` while still propagating all other errors up the call stack.  
3. **Updated `spawn` in `std.Thread.zig`**  
- Marked `MappingAlreadyExists` as `unreachable` in the `catch` block, along with other `mmap` errors that are also unreachable.  
- The two places in the standard library that …
=> stdlib: handle EEXIST in mmap with FIXED_NOREPLACE. Fixes #21475

lib/std/mem.zig
This reverts commit 5b8af7a2a9140fd0533961b62addc61f57b33343.
Closes #16951.
=> Revert "skip regressed LLVM 17 std lib test on powerpc"

src/link/MachO/UnwindInfo.zig
Closes #23010.
Relevant LLD code (thanks @Rexicon226): https://github.com/llvm/llvm-project/blob/e67cd152cf4d0344efba19985b005dae15e6bde0/lld/MachO/UnwindInfoSection.cpp#L361-L368
=> `link.MachO.UnwindInfo`: Handle `u24` overflow for CU records pointing to DWARF.

lib/std/zig/AstGen.zig, test/cases/compile_errors/file_level_tuple_with_decls.zig
Instead of just reporting this on token 0, report it on the first tuple-like field.
=> AstGen: improve 'file cannot be a tuple' source location

lib/compiler/build_runner.zig
@andrewrk here is a cleaner PR.
Addresses #22523 by dead-coding Fuzz.Start() on non-64-bit platforms.
**Replaces**: [PR 23008](https://github.com/ziglang/zig/pull/23008)
**Reason**: omitting the unnecessary changes I'd proposed to Fuzz/WebServer.zig.
=> lib/compiler/build_runner: only build Fuzz on 64-bit platforms

doc/langref.html.in, doc/langref/test_deprecated_builtin.zig, lib/compiler/build_runner.zig, lib/std/Build.zig, lib/std/Build/Module.zig, lib/std/Build/Step/Options.zig, lib/std/zig/AstGen.zig, lib/std/zig/AstRlAnnotate.zig, lib/std/zig/BuiltinFn.zig, lib/std/zig/Zir.zig, src/Compilation.zig, src/Package/Module.zig, src/Sema.zig, src/main.zig, src/print_zir.zig, test/cases/compile_errors/deprecated.zig, test/compile_errors.zig, test/tests.zig
Implements #22822 
The part I'm most unsure about this implementation relates to how the build system represents `-fallow-deprecated` and `-fno-allow-deprecated` internally and how then this is reflected in the CLI invocation of `build-exe` and related subcommands.
=> Implement `@deprecated`

CMakeLists.txt, lib/std/zig.zig, lib/std/zig/llvm.zig, lib/std/zig/llvm/BitcodeReader.zig, lib/std/zig/llvm/Builder.zig, lib/std/zig/llvm/bitcode_writer.zig, lib/std/zig/llvm/ir.zig, src/Compilation.zig, src/InternPool.zig, src/codegen/llvm.zig
Mainly for the benefit of [projects like Roc](https://gist.github.com/rtfeldman/77fb430ee57b42f5f2ca973a3992532f).
=> Move the compiler's LLVM bitcode builder to `std.zig.llvm`.

test/behavior/bit_shifting.zig
Simliarly to shl_with_overflow, we first SHL/SAL the integer, then SHR/SAR it back to compare if overflow happens.
If overflow happened, set result to the upper limit to make it saturating.
Theoretically, if the left shifting instruction is lowered as a single SHL/SAL opcode, and the left operand fits into a register (so no truncation is needed), the CF flag can be used to check for overflow. However the optimization is not implemented right now (for my laziness).
Bug: #17645
=> x86_64: Implement integer saturating left shifting codegen

lib/std/crypto/pcurves/common.zig
The Bernstein-Yang inversion code was meant to be used only with the fields we currently use for the NIST curves.
But people copied that code and were confused that it didn't work as expected with other field sizes.
It doesn't cost anything to make it work with other field sizes, that may support in the future. So let's do it.
This also reduces the diff with the example zig code in fiat crypto.
Suggested by @Rexicon226 -- Thank you!
=> crypto.pcurves.common: generalize invert()

lib/std/heap.zig
If `root.std_options.page_size_min` is not `null` accessing `std.heap.page_size_min` results in the error described in #15108.
```zig
pub const std_options: std.Options = .{
.page_size_min = 4096,
};
comptime {
@compileLog(std.heap.page_size_min);
}
```
```
$ zig build-obj test.zig
/home/user/zig/0.14.0-dev.3445+6c3cbb0c8/files/lib/std/heap.zig:45:89: error: expected optional type, found 'usize'
pub const page_size_min: usize = std.options.page_size_min orelse page_size_min_default orelse
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```
This was introduced in #22488.
See also: [Discord `zig-help` link](https://discord.com/channels/605571803288698900/1345765450323070986)
=> Mitigation of #15108 in `std.heap.page_size_min`

src/target.zig
The command line flag is only supported in Clang 20: https://github.com/ziglang/zig/issues/23056
This gets rid of some warnings when using zig cc.
=> compiler: Don't consider powerpc to have red zone support yet.

lib/std/dynamic_library.zig
After commit 6ef2384 usage of DynLib on 32-bit archs is broken, as type for temporary _chain_ptr_ on GnuHashSection32.fromPtr should be [\*]elf.gnu_hash.ChainEntry to match the _chain_ field on the structure when returning. GnuHashSection64 is fine.
On GnuHashSection32:
https://github.com/ziglang/zig/blob/6ef2384c07ef6817f134ffc61e34bcea6e87df92/lib/std/dynamic_library.zig#L400
On GnuHashSection64:
https://github.com/ziglang/zig/blob/6ef2384c07ef6817f134ffc61e34bcea6e87df92/lib/std/dynamic_library.zig#L427
Repro:
```zig
const _my_func = *const fn () callconv(.C) c_int;
var libx = try std.DynLib.open("/usr/lib/libx.so.1");
defer libx.close();
const my_func = libx.lookup(_my_func, "my_func").?;
_ = my_func();
}
```
Fails on …
=> std.DynLib: fix proper type of chain_ptr on GnuHashSection32

src/Zcu/PerThread.zig, test/incremental/make_decl_pub
We could have more fine-grained dependencies here, but I think this is fine for now.
=> incremental: invalidate namespace dependencies when a name changes visibility

src/main.zig
=> init: Substitute invalid package names with `foo`

lib/std/zig/llvm/bitcode_writer.zig
The bitcode format always uses little endian words. Prior to this commit, a bitcode file produced on e.g. aarch64_be or s390x would fail to be loaded by LLVM.
=> `std.zig.llvm.bitcode_writer`: Fix word byte order on big endian systems.

doc/langref.html.in, doc/langref/test_splat_builtin.zig
Updates the `@splat()` docs to specify that it can now be used on arrays.
Test case is also updated.
=> langref: update splat section

lib/std/enums.zig
The sentinel is guaranteed by `@tagName` or `std.builtin.Type.EnumField`, and its presence can be useful.
Bun has had a function identical to this PR's new version of `tagName`, and we rely on the sentinel in some places -- I tried replacing all our uses of it with the patched `std.enums.tagName` and it worked fine.
=> std.enums.tagName: preserve sentinel in return value

lib/std/Build/Step/InstallArtifact.zig
this appears to have been a problem since 43f73af3595c3174b8e67e9f2792c3774f2192e9
closes #23120
=> fix InstallArtifact opening empty string

src/Compilation.zig
Clang's integrated Arm assembler doesn't understand `-mabi` yet, so this results in "unused command line argument" warnings when building musl code and glibc stubs, for example.
=> `zig cc`: Don't pass `-mabi` for assembly files when targeting arm.

lib/std/Build/Cache.zig
The build Cache test pass on Wasi now.
Fixes #5437
=> lib/std/Build/Cache.zig: remove .wasi SkipZigTest checks

src/Compilation.zig
=> `Compilation`: Fix `-fno-rtlib-defaultlib` unused argument warning in ReleaseSafe.

build.zig
Sometimes Zig is built not from a git repository (e.g. from tarball), but inside another git repository (e.g. distro package repository). Make sure that the version check tries to parse a tag of Zig, and not of a parent directory.
=> build: Don't check parent directories for git tag

lib/std/crypto/Certificate.zig, lib/std/os/uefi.zig, lib/std/time/epoch.zig
Changes `getDaysInMonth` to accept the year as an argument instead of `YearLeapKind`. I also deleted `YearLeapKind` since it was only being used for `getDaysInMonth` but I can bring it back if wanted.
=> std.time.epoch: change getDaysInMonth to accept the year as an argument

src/Sema.zig, test/cases/compile_errors/union_field_ordered_differently_than_enum.zig
Fixes #23059
The "note: enum field here" now references the field in the base union type rather than crashing.
=> Sema: handle generated tag enums in union field order check

lib/std/array_list.zig, lib/std/multi_array_list.zig
Since https://github.com/ziglang/zig/commit/e374483d67592907522141546450e89e4d2f5d1e, all functions of `std.ArrayHashMap` uses `gpa` for the allocator parameter name.
Some functions in `std.ArrayList` and `std.MultiArrayList` were already but not all of them, this PR uses `gpa` as the allocator parameter for all their functions.
=> std/containers: improve consistency using gpa parameter name for allocator

lib/std/fs/test.zig, lib/std/io/test.zig, lib/std/posix/test.zig
* use `tmp.dir.realpathAlloc()` to get full path into tmpDir instances
* use `testing.allocator` to remove Arena allocator setups
* Trust `TmpDir.cleanup()` to clean up contained files and sub-trees
* Remove some unnecessary absolute paths (enabling WASI to run the tests)
* Drop some no-longer necessary `[_][]const u8` casts
* Add scopes to reduce `var` usage in favor of `const`
* Move platform-specific (e.g., WASI+libc) logic into the core of a test (instead of skipping the whole test) to improve coverage
=> std/lib: {fs,io,posix} test clean up

lib/compiler/aro/aro/target.zig, lib/std/Target.zig, lib/std/zig/system.zig
Fixes https://github.com/ziglang/zig/issues/23146
=> std: Abi.default: only require an os tag

lib/std/os/uefi/status.zig
the `EfiMain` function in `start.zig` expects the user's `main` fn to return a `std.os.uefi.Status`, but users are likely to rely on `std.os.uefi.Status.Error` for error handling (via `.err()`). this pr adds a function to perform such conversion
for example:
```zig
const uefi = @import("std").os.uefi;
pub fn main() uefi.Status {
// before this PR
doThing() catch |err| return switch (err) {
uefi.Status.Error.Aborted => .aborted,
// ...
};
// after this PR
doThing() catch |err| return Status.fromError(err);
return .success;
}
fn doThing() uefi.Status.Error!void {
try uefi.system_table.con_out.?.outputString("hello, world!\r\n").err();
}
```
=> lib/std/os/uefi/status.zig: add error to enum conversion fn

src/Sema.zig, src/Value.zig, test/behavior/floatop.zig
Closes https://github.com/ziglang/zig/issues/21932
- Value: fix comparison of NaN in compareHeteroAdvanaced
- Sema: fix equality comparison of signed zeroes and NaN in compareScalar
- tests: add test coverage for vector float comparisons
=> Fix float vector comparisons with signed zero and NaN, add test coverage

test/tests.zig
I think the underlying issue was the same as https://github.com/ziglang/zig/issues/13258 and that has been worked-around in LLVM 19 (see https://github.com/llvm/llvm-project/issues/58557).
Fixes #15325
=> Enable compiler-rt tests for wasm32-wasi

src/Package/Fetch.zig
This is a follow-up to #21555, which makes the detection work for M1 (and later) Macs.
Also see my investigation here: https://github.com/ziglang/zig/issues/21044#issuecomment-2711510643
=> Fetch: enhance Mach-O executable detection for modern Macs

lib/std/c.zig, lib/std/c/serenity.zig
The [current patches](https://github.com/SerenityOS/serenity/tree/222acc9d389bc6b490d4c39539761b043a4bfcb0/Ports/zig/patches) we have for the SerenityOS Zig port are based on 0.12.0-dev, targeting `std.c` when it was still relying on `usingnamespace`, and using a [script to pull constant values from headers](https://github.com/SerenityOS/serenity/blob/222acc9d389bc6b490d4c39539761b043a4bfcb0/Ports/zig/scripts/generate-serenity-constants.zig) at build time - so I went through the entirety of `c.zig` and did it from scratch. Adding `std.c` support back is one of the main things missing from https://github.com/SerenityOS/serenity/pull/25775, [as mentioned](https://zsf.zulipchat.com/#narrow/channel/454446-ecosystem/topic/0.2E14.20packaging/near/504404376) I've decided to upstream them now and …
=> std.c: Add definitions for SerenityOS

src/link/Dwarf.zig, test/behavior/select.zig
=> x86_64: fix crashes with symbols

lib/std/c.zig
c.f. https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/bits/sysconf.h
std.heap.DebugAllocator & std.heap.page_allocator breaks on android platform due to the mis-configured SC names.
=> std.c: fix sysconf names (std.c._SC) for android api

src/Compilation.zig, src/Zcu.zig
On updates with failed files, we should refrain from doing any semantic analysis, or even touching codegen/link. That way, incremental compilation state is untouched for when the user fixes the AstGen errors.
Resolves: #23205
=> Zcu: rename `skip_analysis_errors` to `skip_analysis_this_update` and respect it

lib/compiler/aro_translate_c/ast.zig, lib/compiler/reduce.zig, lib/compiler/reduce/Walk.zig, lib/docs/wasm/Decl.zig, lib/docs/wasm/Walk.zig, lib/docs/wasm/html_render.zig, lib/docs/wasm/main.zig, lib/std/zig/Ast.zig, lib/std/zig/AstGen.zig, lib/std/zig/AstRlAnnotate.zig, lib/std/zig/ErrorBundle.zig, lib/std/zig/Parse.zig, lib/std/zig/Zir.zig, lib/std/zig/Zoir.zig, lib/std/zig/ZonGen.zig, lib/std/zig/render.zig, lib/std/zon/parse.zig, src/Package/Fetch.zig, src/Package/Manifest.zig, src/Sema.zig, src/Type.zig, src/Zcu.zig, src/Zcu/PerThread.zig, src/main.zig, src/print_zir.zig, test/cases/translate_c/continue_from_while.c
This PR introduces named/distinct integer types to `std.zig.Ast`, improving type safety and aligning it more closely with other compiler data structures like ZIR.
At it's core, the changes can be summarized by the following:
<details>
<summary>Before</summary>
```zig
// Most fields and declarations have been redacted for simplicity.
source: [:0]const u8,
tokens: TokenList.Slice,
nodes: NodeList.Slice,
extra_data: []Node.Index,
pub const TokenIndex = u32;
pub const Node = struct {
tag: Tag,
main_token: TokenIndex,
data: Data,
pub const Index = u32;
pub const Tag = enum {...};
pub const Data = struct {
lhs: Index,
rhs: Index,
};
};
```
</details>
<details>
<summary>After</summary>
```zig
// Most fields and declarations have been redacted for simplicity.
source: [:0]const u8,
tokens: …
```
=> improve type safety of std.zig.Ast

lib/libc/glibc/sysdeps/nptl/bits/thread-shared-types.h, lib/libc/glibc/sysdeps/nptl/pthread.h, lib/libc/include/generic-glibc/bits/thread-shared-types.h, lib/libc/include/generic-glibc/pthread.h
@alexrp Opened a detailed description over on [glibc's bugzilla](https://sourceware.org/bugzilla/show_bug.cgi?id=32786).  I'll just copy that in as I believe it summarizes this fix as well:
> glibc 2.41 changed the definition of `__pthread_cond_s` to remove the `__g_refs` field. This is fine for programs that are compiled against <=2.40, but for programs compiled against 2.41 and run against <=2.40, rather than an upfront symbol version error, you can get some rather nasty concurrency bugs because of uninitialized memory in `__pthread_cond_s`.
> 
> This happens because `PTHREAD_COND_INITIALIZER` in the 2.41 headers no longer zeroes the removed `__g_refs` field. So when the program is run against a <=2.40 libc that expects a larger `__pthread_cond_s`, it ends up accessing uninitialized …
=> Fix uninitialized memory in __pthread_cond_s for glibc versions less than 2.41

lib/std/http/Client.zig
This fixes #21032 by ignoring proxy environment variables that are empty.
It seemed much better to ignore the empty variables then return an error as it seems like that would more often be annoying and unwanted.
=> lib/std/http/Client.zig: Ignore empty proxy environment variables

lib/std/Build/Watch.zig
The code did one useless thing and two wrong things:
- ref counting was basically a noop
- last_dir_fd was chosen from the wrong index and also under the wrong condition
This caused regular crashes on macOS which are now gone.
=> std.Build.Watch: fix kqueue implementation

lib/std/posix.zig, src/fmt.zig
I was having an unknown error code when trying to use `std.posix.write` on a unix datagram socket on macOS, while the same code was perfectly working on Linux: investigating, I found that the default max buffer size writeable on macOS is way smaller than on Linux.
This PR catches the `MSGSIZE` write error on `std.posix.write` to get a more instructive stacktrace. (I reused the name and comment from the `std.posix.send`  implementation)
This change could be debatable if you think that `std.posix.send` should've been used instead of `std.posix.write` here, which I agree with, and `MSGSIZE` would've been properly caught in the `std.posix.send` implementation.
I'd argue that since `write` can technically write on an unixgram sockets, I don't see a good reason to ignore this error code while …
=> posix/write: catch MSGSIZE error

src/Compilation.zig, src/link/Coff.zig, src/mingw.zig
LLD expects the library file name (minus extension) to be exactly `libmingw32`. By calling it `mingw32` previously, we prevented it from being detected as being in LLD's list of libraries that are excluded from the MinGW-specific auto-export mechanism.
https://github.com/llvm/llvm-project/blob/b9d27ac252265839354fffeacaa8f39377ed7424/lld/COFF/MinGW.cpp#L30-L56
As a result, a DLL built for `*-windows-gnu` with Zig would export a bunch of internal MinGW symbols. This sometimes worked out fine, but it could break at link or run time when linking an EXE with a DLL, where both are targeting `*-windows-gnu` and thus linking separate copies of `mingw32.lib`. In #23204, this manifested as the linker getting confused about `_gnu_exception_handler()` because it was incorrectly exported by the DLL …
=> `mingw`: Rename `mingw32.lib` to `libmingw32.lib`.

lib/std/builtin.zig, src/codegen/llvm.zig, src/main.zig
Closes #22517.
There's room for improvement here; in particular, we should actually validate the given GCC code model against the target, as some of the niche ones (e.g. `medany`) only work for a subset of targets.
=> `compiler`: Support more GCC code models and fix the mapping to LLVM code models.

src/codegen/spirv/Assembler.zig
cc @Snektron @alichraghi , this enables support for descriptor indexing.
=> spirv: Assemble OpTypeRuntimeArray.

lib/compiler/resinator/cli.zig, lib/compiler/resinator/main.zig
(would appreciate this being included in 0.14.1)
---
When determining the type of RC compiler, meson passes `/?` or `--version` and then reads from `stdout` [looking for particular string(s) anywhere in the output](https://github.com/mesonbuild/meson/blob/d17df82efa5dd0b60b9b2a25f8a5e2f34477af6a/mesonbuild/modules/windows.py#L88-L93).
So, by adding the string "Microsoft Resource Compiler" to the `/?` output, meson will recognize `zig rc` as rc.exe and give it the correct options, which works fine since `zig rc` is drop-in CLI compatible with rc.exe.
This allows using `zig rc` with meson for (cross-)compiling, by either:
- Setting `WINDRES="zig rc"` or putting `windres = ['zig', 'rc']` in the cross-file
+ This will work like rc.exe, so it will output .res files. This will only link …
=> Trick the meson build system into thinking `zig rc` is `rc.exe`

src/link.zig
The old logic only decremented `remaining_prelink_tasks` if `bin_file` was not `null`. This meant that on `-fno-emit-bin` builds with registered prelink tasks (e.g. C source files), we exited from `Compilation.performAllTheWorkInner` early, assuming a prelink error.
Instead, when `bin_file` is `null`, we still decrement `remaining_prelink_tasks`; we just don't do any actual work.
Resolves: #22682
=> link: mark prelink tasks as procesed under `-fno-emit-bin`

lib/std/debug.zig, src/codegen/llvm.zig, src/target.zig
Emscripten currently implements `emscripten_return_address()` by calling out into JavaScript and parsing a stack trace, which introduces significant overhead that we would prefer to avoid in release builds.
This is especially problematic for allocators because the generic parts of `std.mem.Allocator` make frequent use of `@returnAddress`, even though very few allocator implementations even observe the return address, which makes allocators nigh unusable for performance-critical applications like games if the compiler is unable to devirtualize the allocator calls.
To demonstrate just how detrimental this overhead is, below is a quick test application that does 10k pointless `FixedBufferAllocator` allocations in a loop:
<details><summary>Test app</summary>
Save as `build.zig`, …
=> Lower `@returnAddress` to a constant 0 in Emscripten release builds because it is slow

test/behavior/packed-struct.zig
Fixes #20113. Fixes #20581. Fixes #22790.
AND instructions in packedStore clobbers EFLAGS.
Tested with the repro from #20113 and #20581.
```
xtex@xtex1 ~/s/z/zig (master)> build-host/out/zig run repro.zig -fno-llvm
ret: repro.Data{ .rd = 1, .rl = true }, true, true
xtex@xtex1 ~/s/z/zig (master)> zig version
0.15.0-dev.56+d0911786c
xtex@xtex1 ~/s/z/zig (master)> zig run repro.zig -fno-llvm
ret: repro.Data{ .rd = 1, .rl = false }, false, true
xtex@xtex1 ~/s/z/zig (master)> zig run repro.zig -fllvm
ret: repro.Data{ .rd = 1, .rl = true }, true, true
```
Behavior test: `1951 passed; 143 skipped; 0 failed.`
=> x86_64: fix packedStore miscomp by spilling EFLAGS

src/Sema.zig, test/behavior/fn.zig
While it is not allowed for a function coercion to change whether a function is generic, it *is* okay to make existing concrete parameters of a generic function also generic, or vice versa. Either of these cases implies that the result is a generic function, so comptime type checks will happen when the function is ultimately called.
Resolves: #21099
=> Sema: fix in-memory coercion of functions introducing new generic parameters

src/codegen/llvm.zig
The "musl" part of the Zig target triples `wasm32-wasi-musl` and `wasm32-emscripten-musl` refers to the libc, not really the ABI.
For WASM, most LLVM-based tooling uses `wasm32-wasi`, which is normalized into `wasm32-unknown-wasi`, with an implicit `-unknown` and without `-musl`. Similarly, Emscripten uses `wasm32-unknown-emscripten` without `-musl` ([`emcc` is actually very strict and rejects anything but the canonical triple](https://github.com/emscripten-core/emscripten/blob/95518ae96eca9b9eb1224ddb4a94f06820b0b2a8/emcc.py#L1395)).
Because Zig normalizes the triple `wasm32-emscripten` to `wasm32-emscripten-musl`, which is subsequently transformed into the LLVM triple `wasm32-unknown-emscripten-musl`, and because `emcc` and most Emscripten tooling expects …
=> Use `-unknown` when converting WASI/Emscripten target triples into LLVM triples

lib/std/meta.zig
Users should be using @FieldType() instead.
=> deprecate O(n) union field type helpers in std.meta

lib/std/fmt.zig
Fixes #23315. Added a test case to prevent future regressions.
=> fix(std/fmt.zig): fix overflow in fmtDurationSigned

lib/std/base64.zig
There are multiple implementations of Base64,[^1] but [`std.base64`](https://ziglang.org/documentation/0.14.0/std/#std.base64) appears to be based on [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648), so we clarify that it is based on RFC 4648.
[^1]: <https://en.wikipedia.org/w/index.php?title=Base64&oldid=1280060083#Variants_summary_table>
=> docs(std.base64): Add references to RFC 4648

lib/std/Build/Cache/DepTokenizer.zig
=> DepTokenizer: allow space between target and colon

lib/std/math.zig, lib/std/math/lcm.zig
Fixes #22660
Then maybe in the future the individual lcm implementations (like in crypto) can use a single one from the math library?
=> Add least common multiple (LCM) to math

lib/std/bit_set.zig
pairs well as the opposite to `.findFirstSet()`
discovered api mismatch in https://github.com/nektro/zig-UrlValues/commit/e7a258f24ff0d760c6bfdb107b575ecead0a4e6b
=> std: add bit_set.findLastSet()

lib/std/heap/arena_allocator.zig
This PR updates the documentation comment to fit with my understanding of how freeing in the arena allocator implemented by `arena_allocator.zig` works - memory allocated with an arena allocator can be freed individually as long as it is the last thing that was allocated. Please correct my understanding if this is not how it works since I am new to zig. My understanding is as follows:
- [The function which creates the allocator object for `arena_allocator.zig`](https://ziglang.org/documentation/master/std/#std.heap.arena_allocator.ArenaAllocator.allocator) sets the `vtable.free` property of the struct to [the `ArenaAllocator.free` function](https://ziglang.org/documentation/master/std/#std.heap.arena_allocator.ArenaAllocator.free)
- The `ArenaAllocator.free` function frees the memory if …
=> Update the documentation comment in arena_allocator.zig to be more accurate

lib/std/c.zig
1. https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/bits/getentropy.h
2. https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/stdlib.h
=> std.c: android bionic C supports arc4random_buf and getentropy

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig, src/Value.zig, test/behavior/for.zig
closes #23309
bigint functions are allowed to take non-normalized inputs (such as negative zero), however they can't return it. in this case, the operation `subWrap(0, 0)` (computing the length of the range) would result in `-0`, which would create a new internpool value. the simplest fix for this that I can think of is just a special casing both `a` and `b` being zero, similar to how it's done when one of the sides is zero.
=> big.int: return normalized results from `{add,sub}Carry`

lib/std/debug.zig
Abstracts the logic to `std.debug.dumpHexInternal`, which takes a writer and TTY config. That way, unit tests can be written for the function.
Fixes #20048
=> Fix std.debug.dumpHex address offsets

lib/std/fs/test.zig, lib/std/posix.zig
Add a test for std.fs.File's `setEndPos` (which is a simple wrapper around `std.posix.ftruncate`) to exercise some success and failure paths.
Explicitly check that the `ftruncate` length isn't negative when interpreted as a signed value.  This avoids having to decode overloaded `EINVAL` errors.
Add errno handling to Windows path to map INVALID_PARAMETER to FileTooBig.
Fixes #22960
=> lib/std/posix: test ftruncate via std.fs.File.setEndPos()

test/standalone/windows_bat_args/test.zig
Previously: https://github.com/ziglang/zig/pull/19698
Context:
- https://blog.rust-lang.org/2024/09/04/cve-2024-43402.html
- https://github.com/rust-lang/rust/pull/129962
Note that the Rust test case for this checks that it executes the batch file successfully with the proper mitigation in place, while the Zig test case expects a FileNotFound error. This is because of a PATHEXT optimization that Zig does, and that Rust doesn't do because Rust doesn't do PATHEXT appending (it only appends .exe specifically, see https://github.com/ziglang/zig/pull/13993#issuecomment-1356778290). See the added comment for more details.
=> Add test to ensure the BatBadBut mitigation handles trailing `.` and space safely

src/Zcu.zig
Oops, a little typo from yours truly! No test for this one, because we don't have any way of testing the reference trace.
=> Zcu: include named tests in resolved references

lib/std/os/linux.zig, lib/std/os/linux/IoUring.zig, lib/std/os/linux/io_uring_sqe.zig
io_uring is in active development and each new kernel brings some new features. This is an update to the most important changes from kernels 6.11 and 6.12.
**[Bind/listen](https://github.com/axboe/liburing/wiki/What's-new-with-io_uring-in-6.11-and-6.12#add-support-for-bindlisten) support**
IoUring.bind and IoUring.listen functions are added. For listening sockets is it common to set some socket options, so I added generic IoUring.cmd_sock but also posix like IoUring.setsokopt and IoUring.getsockopt.
**Probing capabilities**
When app has to run on different kernels it is handy to check if some [operation](https://github.com/ianic/zig/blob/fdb63447f5eecbb79c12d018edd21a72fdcb642c/lib/std/os/linux.zig#L5752) is supported on the running kernel. 
Example:
```
const probe = try …
```
=> io_uring: Update to kernel changes in 6.11 and 6.12

doc/langref/test_multidimensional_arrays.zig
Use a rectangular matrix instead of a square one to distinguish rows and
columns more clearly. Extend the example with row access.
Closes #9690
=> Clarify the multidimensional array docs example

lib/std/Build/Step/Run.zig
This change fixes false-positive cache hits for run steps that get run with different sets of environment variables due the the environment map being excluded from the cache hash.
I assume the exclusion of the `env_map` field from the cache hash of a `Step.Run` was an oversight as it is important for use cases where environment variables are used to control program behaviour (I encountered this issue when using AFLPlusPlus where environment variables are used to enable different instrumentation options). If it was intentional I can open an issue to discuss changing this behaviour.
The implementation in this PR sorts the environment variables by the variable name to ensure that any reordering does not cause a cache miss. I have not implemented special-case logic for windows to normalise …
=> zig build: add env_map entries to hash for Step.Run

lib/compiler/build_runner.zig, src/Package/Fetch.zig, src/main.zig
`--fetch` flag now has additional optional parameter, which specifies how lazy dependencies should be fetched:
* `needed` — lazy dependencies are fetched only if they are required for current build configuration to work. Default and works same as old `--fetch` flag.
* `all` — lazy dependencies are always fetched. If `--system` flag is used after that, it's guaranteed that **any** build configuration will not require additional download of dependencies during build. Helpful for distro packagers and CI systems: https://github.com/ziglang/zig/issues/14597#issuecomment-1426827495
If none is passed, behaviour is same as if `needed` was passed.
=> zig build: allow to choose "lazy mode" for fetching process

lib/std/os/linux.zig
Fixes #21522
@rohlem's suggestion in #21522 to move the relevant comptime block into the container namespace used to define getauxval *seems* to work fine.
```
$ cat hello_world.zig
pub const std_options = std.Options{ .keep_sigpipe = true };
std.io.getStdOut().writeAll("hello world\n") catch {};
}
$ zig build-exe hello_world.zig -OReleaseSmall -fsingle-threaded && wc -c hello_world
2016 hello_world
$ zig build-exe hello_world.zig -OReleaseSmall -fsingle-threaded --zig-lib-dir lib && wc -c hello_world
1944 hello_world
$
```
Before: 2016 bytes. After: 1944 bytes.
Might still not address *all* cases but I guess a new more specific issue can be opened for that.
=> linux: omit getauxval from binary if not needed

lib/std/Build/Step/Compile.zig
Right now, `pkg-config` can output `-Wl,-rpath,…` which is ignored by the parser.
On NixOS, `rpath` is an important concept for linking system libraries, especially when they are not the "native" library (x86 on x86_64).
This patch should fix this by configuring the Zig linker such that it respects these `rpath` requirements
=> Add support for rpath with pkg-config

lib/std/Target.zig, lib/std/posix.zig
As of zig-0.14.0, `std.posix.mmap`(which invokes `std.c.mmap`) returns `MAP_FAILED` with error code of `EINVAL` for androideabi, while `std.c.mmap64` works fine.
Actually, android bionic C has support for `_FILE_OFFSET_BITS`, enabling `lfs64_abi` for android fixes the above issue. 
c.f.
1. https://android.googlesource.com/platform/bionic/+/HEAD/docs/32-bit-abi.md
2. https://github.com/android/ndk/issues/468
=> std.posix: update LFS64 interfaces for android bionic C

lib/std/c.zig, lib/std/posix.zig, lib/std/posix/test.zig
This PR adds the `getuid()` and `geteuid()` functions from `unistd.h` that are to the best of my knowledge available on all POSIX-compliant systems.
=> std.posix: add getuid()/geteuid()

lib/std/os/linux/tls.zig
Proposed fix as supplied by @alexrp in #23377
Closes #23377.
=> check result of mmap() call to handle a large base_addr value correctly

src/Zcu/PerThread.zig, test/behavior/generics.zig
=> Zcu: resolve layout of analyzed declaration type

src/Sema.zig, test/behavior/memcpy.zig
If the `src_ty` is a `[:0]const u8`, the single pointer would try to inherit the sentinel, which is invalid. I've fixed it to move the sentinel to the child type, if there is one, and then clear the sentinel from the pointer info we're inheriting.
=> Sema: convert slice sentinel to single pointer correctly

src/Sema.zig, test/behavior/ptrcast.zig
This is actually completely well-defined. The resulting slice always has 0 elements. The only disallowed case is casting *to* a slice of a zero-bit type, because in that case, you cna't figure out how many destination elements to use (and there's *no* valid destination length if the source slice corresponds to more than 0 bits).
=> Sema: allow `@ptrCast` slice of zero-bit type to slice of non-zero-bit type

lib/std/os/uefi.zig, lib/std/start.zig
As mentioned in https://github.com/ziglang/zig/pull/23214#pullrequestreview-2730502337, it'd be nice to support returning `uefi.Status.Error!void` from your main function out of the box :)
this PR updates the `EfiMain` implementation in `lib/std/start.zig` to support such main definitions.
=> lib/std/start: allow return uefi error union in main

lib/std/zon/parse.zig
Some schemas can't be represented by Zig types.
For example, as #22775 points out, `build.zig.zon`'s schema can't be represented by a Zig type since it uses field names as map keys:
```zig
.{
.name = "foo",
.dependencies = .{
.these = .{
// ...
},
.fields = .{
// ...
},
.could_be_named_anything = .{
// ...
},
},
.paths = .{""},
}
```
This will be addressed for importing zon at comptime by #22907.
It's possible to handle this case at runtime by dropping down to [`std.zig.Zoir`](https://ziglang.org/documentation/master/std/#std.zig.Zoir), but this is cumbersome--especially if *most* of your type conforms to a Zig type, but a few fields don't.
This PR makes it possible to, for example, parse the `build.zig.zon` above at runtime using the following schema:
```zig
struct {
name: []const u8, …
```
=> Allow parsing into `Zoir.Node.Index` (it's easier to parse build.zig.zon at runtime now)

lib/std/heap/debug_allocator.zig
Hey Ziguanas 0/
Ran into this one while at work and it drove me crazy for a good couple hours until a coworker and I realized it was a bug in the DebugAllocator rather than in our own code!
Here's a repro; the first test will not error when it should, and the second will segfault:
```zig
const size_class_0_slot_count = 1308;
test "Head erasure" {
var debug_allocator: std.heap.DebugAllocator(.{}) = .init;
defer _ = debug_allocator.deinit();
const allocator = debug_allocator.allocator();
// Current bucket linked list: [null]
for (0..size_class_0_slot_count) |_| {
_ = try allocator.create(u8);
}
// Current bucket linked list: [null <- bucket_0]
const new_bucket = try allocator.create(u8);
// Current bucket linked list: [null <- bucket_0 <- bucket_1] …
```
=> DebugAllocator: Fix bucket removal logic causing segfault/leak

lib/std/os/linux.zig, lib/std/posix.zig
I believe the order of first two u32 is wrong.
See also: https://github.com/bminor/musl/blob/master/src/signal/sigfillset.c
=> std.os.linux: remove app_mask and block&unblock pair in raise

lib/std/zig/system.zig
3872778 will be the controversial part here. It attempts to fix #23411 by simply removing the use of `wine64`. I'm not actually sure that any distros still use (or did ever use?) this executable name, but I definitely welcome evidence to the contrary.
Closes #23411.
=> `std.zig.system`: Some fixes for `getExternalExecutor()`

cmake/Findlld.cmake
Homebrew now provides lld in a separate formula; it was part of llvm formula.
Closes #23457
=> Change the lld path on macos homebrew

lib/std/net.zig, lib/std/net/test.zig
This implements the `if_nametoindex` function for windows.
I noticed zig threw a compile error when trying to compile the zigdig example code for windows.
If I read the code correctly, and looking at issue #20530, this seems also hinder all IP resolution on windows, even though `if_nametoindex` is only called in the ipv4 codepath.
I pieced this code together from looking at the darwin implementation and the old std.x namespace, which also contained an implementation for windows.
This seems to pass all test, except for this one https://github.com/ziglang/zig/blob/d5db02728ce3ff3ba74a3e3f9050c3ea9ed34752/lib/std/net/test.zig#L79. As far as I understand, the `error.Overflow` case should be handled before `if_nametoindex` is even called. If someone can help me fix this case, I'd be happy for …
=> Implement `if_nametoindex` for windows

lib/std/os/uefi/protocol/file.zig
#23214 has a few glitches, this is a PR fixing one of them :)
there were 3 issues with `File` as pointed out by #23436:
in the spec, the `OpenMode` argument can only be `read`, `read|write`, or `read|write|execute`. However, currently the interface only allows `read`, `write`, and `execute`. This PR addresses this problem:
- defined an auxiliary type `OpenMode.Bits` which provides a bitfield representing those values from the spec
- `OpenMode`'s enum tags are renamed to `read`, `read_write`, and `read_write_create` for better clarity
- `OpenMode`'s enum values are implemented by bitcasting `OpenMode.Bits` values
The file info buffer should be larger than `@sizeOf(Info.*)`, because `Info.*` types have an attached null-terminated string at the end.
This method now requires the user to pass …
=> std.os.uefi.protocol.File: fix some typed definitions

lib/std/os/linux.zig
ETH definitions https://github.com/torvalds/linux/blob/master/include/uapi/linux/if_ether.h
This closes #23428 .
=> std.os.linux: add constants for ETH

src/Air/types_resolved.zig, src/link/Dwarf.zig, test/behavior/type.zig
=> Dwarf: handle undefined type values

src/codegen/llvm.zig
@Techatrix and I were attempting to instrument some code for coverage with LLVM and found that the unilateral application of the `nosanitize_coverage` attribute to all functions when `fuzz` is off blocked us completely.
We're trying to obtain coverage info, and it seems that the `fuzz` flag doesn't really make sense for our usecase, so we propose this change.
Now `@disableInstrumentation` always works, and the only difference between a `fuzz` and `no-fuzz` build is the `optforfuzzing` fn attr.
=> Remove overzealous LLVM anti-instrumentation attributes

src/zig_clang.h
Fixes failing tarball builds for `x86-linux` and `x86-windows`.
The MSVC special case here is very sus, but that's a problem for another day.
=> `zig_clang`: Fix size of `ZigClangAPValue` for Clang 20.

src/Sema/arith.zig
Maintainter 'mlugg' wanted to fix that typo, 4 weeks without changes, might be forgotten.
```
https://github.com/ziglang/zig/pull/23177#discussion_r1997957095
```
=> Sema/arith.zig: fixing typo from "lhs" to "rhs"

build.zig, src/Package/Module.zig
LLVM 21 will change the default, but we're making the change now to make building Zig for loongarch64 less painful.
https://github.com/llvm/llvm-project/pull/132173
=> compiler: Switch default code model for loongarch64 to medium.

lib/std/os/linux.zig, lib/std/os/linux/loongarch64.zig, lib/std/os/linux/test.zig, lib/std/posix/test.zig, test/behavior/prefetch.zig, test/tests.zig
This enables module tests for `loongarch64-linux`, including the behavior tests, but notably disables the std tests still. They're broken in lots of different ways and I have no way of debugging them because `qemu-loongarch64` + GDB/LLDB debugging *still* does not work. Additionally, the [cfarm machines](https://portal.cfarm.net/machines/list) provided by Loongson can't access GitHub for the reason you might expect, and I'm not going to spend time on working around that.
This is about as much porting work as I'm willing to do until the LoongArch folks get their tooling in shape or provide usable hardware.
ref #21646
=> Some `loongarch64-linux` porting work

lib/std/c.zig, lib/std/os/linux.zig, lib/std/os/linux/arm.zig, lib/std/os/linux/hexagon.zig, lib/std/os/linux/m68k.zig, lib/std/os/linux/mips.zig, lib/std/os/linux/mips64.zig, lib/std/os/linux/powerpc.zig, lib/std/os/linux/riscv32.zig, lib/std/os/linux/tls.zig, lib/std/os/linux/x86.zig, lib/std/posix.zig, lib/std/start.zig
This pr provides initial support for m68k-linux within std. 
Following https://github.com/ziglang/zig/issues/19510#issuecomment-2722895789, i can build object files, but there is still no support for m68k within lld. Therefore, I can't link programs to test with qemu.
https://github.com/ziglang/zig/issues/23089 
https://github.com/ziglang/zig/issues/22189
=> std: add arch bits for m68k-linux

src/codegen/llvm.zig
Solves
```
LLVM ERROR: Global variable '__sancov_gen_.0' has an invalid section specifier '__sancov_cntrs': mach-o section specifier requires a segment and section separated by a comma.
```
described in https://github.com/ziglang/zig/issues/20986.
So
```zig
// hello.zig
export fn aaa(a: [*]u8) void {}
```
with `zig build-obj -ffuzz hello.zig` now compiles on Mac! :)
=> Fix mach-o naming for sancov sections

lib/std/Build/Step/Compile.zig, lib/std/zig.zig, src/Compilation.zig, src/Compilation/Config.zig, src/codegen/llvm.zig, test/standalone/c_compiler/build.zig, test/tests.zig
I've noticed that the `Compile` step still uses a boolean for the LTO option, even though the command-line option for ThinLTO [`-flto=thin`] has been added months prior.
This change allows directly passing the option to select ThinLTO to the underlying `zig build-[kind]` command.
Things to consider before finally merging:
* Due to the difference in semantics, `want_lto` should probably be renamed to `lto` or similar.
* This change duplicates the `LtoMode` enum from `Compilation.Config`. This enum should be put in a shared location. But where exactly?
* Side note: it appears that `Compilation.CreateOptions.want_lto` is vestigial (i.e. never used anywhere). This field should probably be removed from the struct altogether.
=> Step.Compile: use LtoMode enum for lto option

CMakeLists.txt, build.zig
This is needed since LLVM 20, particularly for Windows.
=> build: Set `LLVM_BUILD_STATIC`/`CLANG_BUILD_STATIC` when linking statically.

src/clang.zig, src/zig_clang.cpp, src/zig_clang.h
Also add a `static_assert` to catch future alignment mismatches on this type.
=> `zig_clang`: Fix `ZigClangAPValue` being underaligned vs `clang::APValue`.

src/Sema/arith.zig
This is a complementary PR to #23487 (I had only found one typo before).
Now I've looked at the whole `arith.zig` file, trying to find other potential problems.
Discussion about these changes:
https://github.com/ziglang/zig/pull/23177#discussion_r1997957095
=> Sema/arith.zig: Fixing more typos from #23177.

lib/std/os/linux.zig
Linux kernel syscalls expect to be given the number of bits of sigset that they're built for, not the full 1024-bit sigsets that glibc supports.
I audited the other syscalls in here that use `sigset_t` and they're all using `NSIG / 8`.
Fixes #12715
=> linux.zig: epoll_wait: pass kernel sigset size

lib/std/os/linux.zig, lib/std/os/linux/test.zig
The code was using `u32` and `usize` interchangably, which doesn't work on 64-bit systems.  This: `pub const sigset_t = [1024 / 32]u32;` is not consistent with this: `const shift = @as(u5, @intCast(s & (usize_bits - 1)));`
However, normal signal numbers are less than 31, so the bad math doesn't matter much.  Also, despite support for 1024 signals in the set, only setting signals between 1 and `NSIG` (which is mostly 65, but sometimes 128) is defined.  The existing tests only exercised signal numbers in the first 31 bits so they didn't trigger the overflow.
The C library `sigaddset` will return `EINVAL` if given an out of bounds signal number.  I made the Zig code just silently ignore any out of bounds signal numbers.
I moved all the `sigset` related declarations to be adjacent in the …
=> Fix sigaddset/sigdelset bit-fiddling math

lib/libcxx/include/istream
https://github.com/llvm/llvm-project/pull/134874
=> `libcxx`: Backport llvm/llvm-project#134874.

src/Value.zig, test/behavior/globals.zig
Fixes https://github.com/ziglang/zig/issues/23161.
Before this fix, `"function pointer field call on global extern struct, conditional on global"` reproduces the above.
This resolution feels like it should be conditional on something - since it seems to only be required when the call itself is conditional on a global - let me know if this resolution should be done elsewhere.
=> Value: ensure that extern structs have their layout resolved in ptrField

lib/std/posix.zig, lib/std/posix/test.zig
Addresses the issue described in https://github.com/ziglang/zig/issues/22917.
Possibly interferes with @andrewrk work on https://github.com/ziglang/zig/tree/main branch.
Original implementation https://github.com/ziglang/zig/blob/aa3db7cc15/lib/std/posix.zig#L2004 for each environment variable iterates until the end of its name (until `=`), and only then compares entire name to `key`.
Since some of the environment variables could be quite long (i.e. `GHOSTTY_SHELL_INTEGRATION_NO_SUDO=1`), these sizes add up.
Simply - in order to find a `key` in `environ`, it has to iterate over cumulative sizes of each env variable name before it.
Proposed implementation functionally does what `strncmp` would do: stops iterating and moves to the next variable on first character mismatch with `key`.
See …
=> std.posix.getenv: early-return comparison

lib/std/os/windows.zig, lib/std/process.zig, test/standalone/build.zig.zon, test/standalone/env_vars/build.zig, test/standalone/env_vars/main.zig
Inspired by https://github.com/ziglang/zig/pull/23265, I thought I'd try applying the same strategy to the Windows implementation. The strategy itself didn't end up having the same benefit, but optimizations were still found while exploring it.
Also adds a standalone test to make sure the functionality remains the same.
---
Both sliceTo and indexOfScalarPos use SIMD when available to speed up the search. On my x86_64 machine, this leads to getenvW being around 2-3x faster overall.
Additionally, any future improvements to sliceTo/indexOfScalarPos will benefit getenvW.
---
<details>
<summary>Benchmark code</summary>
```zig
var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
defer arena.deinit();
const allocator = …
```
=> Windows: Faster `getenvW` and a standalone environment variable test

src/arch/wasm/CodeGen.zig, test/behavior/array.zig, test/behavior/bitcast.zig, test/behavior/call.zig, test/behavior/cast.zig, test/behavior/cast_int.zig, test/behavior/defer.zig, test/behavior/error.zig, test/behavior/field_parent_ptr.zig, test/behavior/floatop.zig, test/behavior/int128.zig, test/behavior/math.zig, test/behavior/optional.zig, test/behavior/packed-struct.zig, test/behavior/packed_struct_explicit_backing_int.zig, test/behavior/struct.zig, test/behavior/switch_on_captured_error.zig, test/behavior/tuple.zig, test/behavior/undefined.zig
My goal was to skim through behaviour tests and identify all that will not require big refactoring for passing them.
Next step for wasm codegen is > 128 int handling.
See commit names for descriptions.
=> stage2-wasm: multiple fixes

build.zig, lib/compiler/build_runner.zig, lib/std/Build.zig, lib/std/Build/Step/Compile.zig, src/main.zig
adds a `build-id` option to the build runner and a `build_id` property to `std.Build`.
the value of `std.Build.build_id` is used when `std.Build.Step.Compile.build_id` has not been explicitly specified.
This is useful for distro packagers and anyone who wants to specify a build-id for a whole project unless explicitly specified in the build logic itself.
=> std.Build: add build-id option

src/libunwind.zig
The define was changed in commit 729899f7b6bf6aff65988d895d7a639391a67608 in upstream llvm. This fixes #23543.
As in the related issue, before readelf produces the output
```
Symbol table '.dynsym' contains 68 entries:
Num:    Value          Size Type    Bind   Vis      Ndx Name
0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
1: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
2: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND memset@GLIBC_2.2.5 (2)
3: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __tls_get_addr@GLIBC_2.3 (3)
4: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  UND stderr@GLIBC_2.2.5 (2)
5: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND fwrite@GLIBC_2.2.5 (2)
// glibc symbols ...
29: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND …
```
=> src/libunwind.zig: Fix symbol visibility macro define

lib/std/Target.zig, lib/std/os/linux.zig
Also fix #16606 which requires Linux 5.8+.
=> `std.Target`: Bump minimum Linux kernel and glibc versions according to Debian LTS

lib/std/Build/Step.zig
Should fix some of the timeouts that appeared in CI since #23549. This apparently only worked by coincidence until now.
=> `std.Build.Step`: Don't capture a stack trace if `!std.debug.sys_can_stack_trace`

lib/std/os/linux.zig, lib/std/os/linux/test.zig, lib/std/process.zig
Looking for memory information I found this function std.process.totalSystemMemoryLinux()
Which currently parses out the human readable /proc/meminfo for use in totalSystemMemory()'s .linux case.
I knew there was a syscall for this so I found and ported the related struct
https://github.com/torvalds/linux/blob/master/include/uapi/linux/sysinfo.h
It's Linux only, but I think its useful in the std.process context.
This PR would add sysinfo_t and sysinfo(*sysinfo_t) to std.os.linux
Also replaces std.process.totalSystemMemory()'s .linux case to use the new function.
=> std.process: linux.sysinfo for totalSystemMemory

src/Compilation.zig
This is a mitigation of #23216 meant only for 0.14.x.
Patch by @Rexicon226: https://github.com/ziglang/zig/issues/23216#issuecomment-2783472009
I'll send a separate PR with the proper fix for master, which will allow `zig build-exe -fsanitize-c=trap` and `zig cc -fsanitize-trap=undefined`. We can't backport that because it will require `std.Build` API changes.
=> [0.14.x] `Compilation`: Use trapping UBSan if `-fno-ubsan-rt` is passed.

lib/std/enums.zig
Recently there is a tendency to remove stuff from std.meta. And std.enums.nameCast seems like a missed function since it's in a different namespace.
More specific reasons:
`@field(Enum, @tagName(tag))`
^ is just shorter to write compared to
`std.meta.nameCast(Enum, tag)`
nameCast's only advantage is that it can be used interchangeably with strings. But a search through common codebases (zig, bun, tigerbeetle, ...) only tigerbeetle uses it 3 times and only in non-generic way e.g. exclusively with strings or with tags.
It's also pretty buggy and allows usage with bizarre parameters such as `std.meta.nameCast(type, Enum)`.
=> Deprecate std.enums.nameCast.

lib/std/os/windows.zig, test/standalone/windows_spawn/main.zig
Fixes https://github.com/ziglang/zig/issues/19023
CreateProcessW currently returns error.Unexpected when the lpCurrentDirectory value is a directory that does not exist. 
With this PR, CreateProcessW returns error.FileNotFound in those cases.
Directory not existing and directory invalid cannot be distinguished. CreateProcessW returns [ERROR_DIRECTORY - 267 (0x10B) - The directory name is invalid.] in both cases.
Can be tested with the following test. 
```
test "test CreateProcessW with invalid path" {
const allocator = std.testing.allocator;
const application_name = try std.unicode.utf8ToUtf16LeAllocZ(allocator, "c:\\windows\\explorer.exe");
defer allocator.free(application_name);
const command_line = try std.unicode.utf8ToUtf16LeAllocZ(allocator, "");
defer allocator.free(command_line); …
```
=> Return FileNotFound when CreateProcessW is called with a missing path

doc/langref.html.in, doc/langref/packed_struct_mmio.zig
intended to close
<https://github.com/ziglang/zig/issues/14384>
<https://github.com/ziglang/zig/issues/20647>
Questions:
~1. I don't know what to do about this TODO:~
~>   TODO update these docs with a recommendation on how to use packed structs with MMIO~
~>   (the use case for volatile packed structs) once this issue is resolved.~
~>   Don't worry, there will be a good solution for this use case in zig.~
2. Does something different happen if the backing integer is specified as unsigned vs signed?
Looks like this:
=> langref: improve packed struct memory layout description

lib/std/math/big/int.zig, lib/std/math/big/int_test.zig
There was a bug in `llshl` where, if `a` and `r` were the same size, `llshl` would write to `r[a.len]` which is out of bounds. Since runtime safety was disabled, it was not caught by out of bounds check.
This PR rewrites `llshl` (and `llshr` so they both look similar) to fix the bug, and removes the runtime safety override. It also updates the tests in `int_test.zig` (change `expect(a == b)` to `expectEqual(b, a)`, ...) and add tests to `llshl` and `llshr` (and an overlapping check to 2 other functions).
I have not benchmarked the new functions for performance improvement, but a quick test seemed to show a speed-up. Also, the new functions now produce simd shift instructions, so I think they should be quicker ([godbolt link](https://godbolt.org/z/dx5Ezozjz)).
Some doubts I have about my …
=> std.math.big.int: fix a bug in `llshl` and update test syntax

CMakeLists.txt
=> cmake: support static linking against libxml2

test/tests.zig
Skips `std` tests for now: #2256
=> `test`: Add `powerpc-linux-gnueabi(hf)` to the module test matrix.

src/Compilation.zig, src/Package/Module.zig, src/target.zig
=> Module: ignore `xnack` and `sramecc` features on some gpu models

lib/std/Build.zig, lib/std/Build/Module.zig, lib/std/Build/Step/Compile.zig, lib/std/Build/Step/InstallArtifact.zig, src/main.zig, test/standalone/build.zig.zon, test/standalone/test_obj_link_run/build.zig, test/standalone/test_obj_link_run/src/main.zig
This is fairly straightforward; the actual compiler changes are limited to the CLI, since `Compilation` already supports this combination.
A new `std.Build` API is introduced to allow representing this. By passing the `emit_object` option to `std.Build.addTest`, you get a `Step.Compile` which emits an object file; you can then use that as you would any other object, such as either installing it for external use, or linking it into another step.
A standalone test is added to cover the build system API. It builds a test into an object, and links it into a final executable, which it then runs.
Using this build system mechanism prevents the build system from noticing that you're running a `zig test`, so the build runner and test runner do not communicate over stdio. However, that's okay, …
=> compiler: allow emitting tests to an object file

lib/std/testing/FailingAllocator.zig
Something random I noticed.
Note: The decltests for files-as-a-struct don't show up in autodoc currently (example: [FixedBufferAllocator decltest](https://github.com/ziglang/zig/blob/86d354618450d97b4a53735c0b222fcee655f7e8/lib/std/heap/FixedBufferAllocator.zig#L161) and [docs](https://ziglang.org/documentation/0.14.0/std/#std.heap.FixedBufferAllocator)). Will file a new issue if I can't find a relevant one (EDIT: https://github.com/ziglang/zig/issues/23614).
=> FailingAllocator: remove outdated doc comments, move doc comment example to decltest

lib/std/fs/Dir.zig
This reduces the stack usage by 96 KB by calculating the WTF-8 length and then checking the `out_buffer` length rather than converting into an intermediate buffer on the stack. This is one step towards fixing #23643.
=> std.fs.Dir: Reduce stack usage of realpathW

lib/std/c.zig
Fixes #23622. The integer types used for these fields before would not work on some platforms.
=> std.c: use arch's ino_t and off_t for dirent

lib/compiler/aro/aro/target.zig, lib/std/Target.zig, lib/std/zig/LibCDirs.zig, src/codegen/llvm.zig
* This has not seen meaningful development for about a decade.
* The Linux kernel port was never upstreamed.
* The glibc port was never upstreamed.
* GCC 15.1 recently deprecated support it.
It may still make sense to support an ILP32 ABI on AArch64 more broadly (which we already have the `Abi.ilp32` tag for), but, to the extent that it even existed in any "official" sense, the *GNU* ILP32 ABI is certainly dead.
=> `std.Target`: Remove `Abi.gnuilp32`.

lib/std/Target.zig
https://github.com/ziglang/zig/issues/21738#issuecomment-2822411842
=> `std.Target`: Bump minimum glibc to 2.34 for arches migrating to 64-bit time

lib/std/Build/Cache.zig, lib/std/Build/Step.zig, src/Compilation.zig
Aside from adding comments to document the logic in `Cache.Manifest.hit` better, this commit fixes two serious bugs.
The first, spotted by Andrew, is that when upgrading from a shared to an exclusive lock on the manifest file, we do not seek it back to the start. This is a simple fix.
The second is more subtle, and has to do with the computation of file digests. Broadly speaking, the goal of the main loop in `hit` is to iterate the files listed in the manifest file, and check if they've changed, based on stat and a file hash. While doing this, the `bin_digest` field of `std.Build.Cache.File`, which is initially `undefined`, is populated for all files, either straight from the manifest (if the stat matches) or recomputed from the file on-disk. This file digest is then used to update …
=> std.Build.Cache: fix several bugs

src/Compilation.zig
When running `build-lib` for a simulator target, I encountered `error: unknown argument: '-m-simulatorios-version-min=12.0.0'`. Once the arguments are transposed, things build as expected.
=> compiler: Fix `-m<os>-version-min=...` ordering

lib/std/ascii.zig
```diff
-/// /// Deprecated: use `isAscii`
+/// Deprecated: use `isAscii`
```
=> docs(std.ascii): Remove redundant three slashes

lib/compiler/aro/aro/Driver/GCCDetector.zig, lib/compiler/aro/aro/Toolchain.zig, lib/compiler/aro/aro/target.zig, lib/compiler/aro/aro/toolchains/Linux.zig, lib/std/Target.zig, src/codegen/llvm.zig, src/link/Elf.zig, test/llvm_targets.zig
The last Intel Quark MCU was released in 2015. Quark was announced to be EOL in 2019, and stopped shipping entirely in 2022.
The OS tag was only meaningful for Intel's weird fork of Linux 3.8.7 with a special ABI that differs from the regular i386 System V ABI; beyond that, the CPU itself is just a plain old P54C (i586). We of course keep support for the CPU itself, just not Intel's Linux fork (which is unmaintained, and thus will never be supported by us due to being so old).
=> `std.Target`: Remove `Os.Tag.elfiamcu`.

src/Sema.zig, test/behavior/memcpy.zig
before:
```
a.zig:5:13: error: type '[*c]u8' does not support field access
@memcpy(@as([*c]u8, &buf), src);
^~~~~~~~~~~~~~~~~
```
=> Sema: fix memcpy with C pointers

CMakeLists.txt, src/codegen/llvm.zig, src/dev.zig, src/link.zig, src/link/Goff.zig, src/link/Xcoff.zig, test/llvm_targets.zig
This allows emitting object files for `s390x-zos` (GOFF) and `powerpc(64)-aix` (XCOFF).
Note that GOFF emission in LLVM is still being worked on upstream for LLVM 21; the resulting object files are useless right now. Also, `-fstrip` is required, or LLVM will `SIGSEGV` during DWARF emission.
=> `link`: Stub out GOFF/XCOFF linker code based on LLVM

src/wasi_libc.zig
=> `wasi-libc`: Fix paths to `psignal.c` and `strsignal.c`.

src/Sema.zig, test/behavior/pointers.zig, test/cases/compile_errors/runtime_index_into_comptime_only_many_ptr.zig
* Indexing zero-bit types should not produce AIR indexing instructions
* Getting a runtime-known element pointer from a many-pointer should check that the many-pointer is not comptime-only
Resolves: #23405
=> Sema: fix a few indexing bugs

lib/compiler_rt/sqrt.zig, lib/std/os/linux/sparc64.zig, test/behavior/var_args.zig, test/behavior/vector.zig
`test-std` crashes QEMU with an internal error, but all other module tests pass for `sparc64-linux-none`. Note that this requires LLD changes that I'll be upstreaming soon; SPARC won't be part of the test matrix until LLVM 21 at least.
=> Some `sparc64-linux` stuff

lib/fuzzer.zig
This PR will fix linux fuzzer.
Currently it looks for the symbols `__end___sancov_cntrs ` but this weak symbol is not defined on linux, hence fuzzing on linux is broken right now as it resolves to 0
The correct symbol to look for is `__stop__sancov_cntrs`.
More details in my comment in https://github.com/ziglang/zig/pull/23621#issuecomment-2835484481
=> Use correcct symbol for the end of pc counters section on Linux

lib/std/os/linux.zig
- mount syscall allow `source` to be null
=> fix mount api

src/arch/wasm/CodeGen.zig, src/arch/wasm/abi.zig, src/codegen/llvm.zig, src/link/Wasm.zig, test/c_abi/cfuncs.c, test/c_abi/main.zig
I changed logic in `wasm/abi.zig`. Still there is some conflict of interest between llvm and self-hosted backend, better design will appear when abi tests will be tested with self-hosted.
Resolves: #23304
Resolves: #23305
=> wasm-c-abi: llvm fix struct handling + reorganize

src/codegen/llvm.zig
GCC uses the `%=` syntax to generate a unique number for each `asm` statement (see [on gcc's docs](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Special-format-strings)). LLVM uses `${:uid}` to do the same.
This PR adds the syntax, since it is not currently possible to use `%=` or `${:uid}` in zig's inline assembly. Also, it is currently impossible to use `${:comment}` or `${:private}` described [here on llvm's docs](https://releases.llvm.org/10.0.0/docs/LangRef.html#inline-assembler-expressions), and this PR does **not** change that.
I am unsure if this change requires tests, and how to even test it.
=> inline assembly: enable GCC's `%=` syntax

lib/std/Target.zig, lib/std/builtin.zig, src/Zcu.zig, src/codegen/llvm.zig, src/target.zig, test/cases/compile_errors/@import_zon_bad_type.zig, test/cases/compile_errors/anytype_param_requires_comptime.zig, test/cases/compile_errors/bogus_method_call_on_slice.zig, test/cases/compile_errors/coerce_anon_struct.zig, test/cases/compile_errors/redundant_try.zig
No CPU features for now; I'll do those separately as part of a larger branch I'm working on.
FYI @tensorush (https://github.com/ziglang/zig/issues/23560#issuecomment-2845589283)
=> `std.Target`: Add `Cpu.Arch.or1k` and basic target info.

lib/std/Progress.zig
There were several bugs with the synchronization here; most notably an ABA problem which was causing #21663. I fixed that and some other issues, and took the opportunity to get rid of the `.seq_cst` orderings from this file. I'm at least relatively sure my new orderings are correct.
Thanks to @achan1989 for noticing the ABA problem here and putting up an initial fix. This PR supersedes #23662, but I've marked you as a co-author here!
Resolves: #21663
=> std.Progress: fix many bugs

src/Sema/comptime_ptr_access.zig, src/Type.zig, test/behavior/comptime_memory.zig
* When storing a zero-bit type, we should short-circuit almost immediately. Zero-bit stores do not need to do any work.
* The bit size computation for arrays is incorrect; the `abiSize` will already be appropriately aligned, but the logic to do so here incorrectly assumes that zero-bit types have an alignment of 0. They don't; their alignment is 1.
Resolves: #21202
Resolves: #21508
Resolves: #23307
=> compiler: fix comptime memory store bugs

src/Sema.zig, src/codegen/c.zig, test/behavior/tuple.zig, test/cases/compile_errors/runtime_store_to_comptime_field.zig
=> Sema: fix pointers to comptime fields of comptime-known aggregate pointers

src/Compilation/Config.zig, src/main.zig, src/target.zig
This is generally ill-advised, but can be useful in some niche situations where the caveats don't apply. It might also be useful when providing a `libc.txt` that points to Eyra.
FYI @polarathene
=> compiler: Allow linking native glibc statically

src/main.zig
I don't know if it's possible to make a test case for this since it requires files from the windows SDK.
But 
* with this change
* and with the sdk downloaded using  https://github.com/mstorsjo/msvc-wine scripts
I was able to build a working `x86_64-windows-msvc` executable from a linux host.
(for reference, here is the zig  `libc.txt` file used: 
```ini
include_dir=/opt/msvc/kits/10/Include/10.0.22621.0/ucrt
sys_include_dir=/opt/msvc/VC/Tools/MSVC/14.43.34808/include/
crt_dir=/opt/msvc/kits/10/Lib/10.0.22621.0/ucrt/x64
msvc_lib_dir=/opt/msvc/VC/Tools/MSVC/14.43.34808/lib/x64
kernel32_lib_dir=/opt/msvc/kits/10/Lib/10.0.22621.0/um/x64
gcc_dir=
```
=> fix system library lookup when cross-compiling to windows-msvc

lib/std/os/linux.zig, src/link/MachO.zig, test/standalone/build.zig.zon, test/standalone/libfuzzer/build.zig, test/standalone/libfuzzer/main.zig
Running this test without #23721 (fails on linux, see https://github.com/ziglang/zig/actions/runs/14738198828)
```
1/3 main.test_0...OK
2/3 main.test.equality...OK
3/3 main.test.arithmetic...OK
All 3 tests passed.
Segmentation fault at address 0x119d008
/home/ci/actions-runner4/_work/zig/zig/build-release/../lib/std/hash/wyhash.zig:127:66: 0x116512c in fuzzer_init (fuzzer)
self.state[i] = mix(a ^ secret[i + 1], b ^ self.state[i]);
^
/home/ci/actions-runner4/_work/zig/zig/test/standalone/libfuzzer/main.zig:18:16: 0x1134d42 in main (main)
fuzzer_init(FuzzerSlice.fromSlice(""));
^
/home/ci/actions-runner4/_work/zig/zig/build-release/../lib/std/start.zig:671:37: 0x1134cb0 in posixCallMainAndExit (main)
const result = root.main() catch |err| {
^ …
```
=> add standalone test for libfuzzer initialization

lib/std/crypto/pcurves/p256.zig, lib/std/crypto/pcurves/p384.zig, lib/std/crypto/pcurves/secp256k1.zig
Implemented `neg()` method for `AffineCoordinates` struct of p256, p384 and secp256k1 curves.
Rust implementation reference: https://docs.rs/primeorder/0.13.6/src/primeorder/affine.rs.html#433
Contributes to #20505.
=> std: fix compile errors in `std.crypto.ecc`

lib/std/os/linux/IoUring.zig
This PR adds `register_file_alloc_range` to `IoUring`. This method is equivalent to [io_uring_register_file_alloc_range](https://man7.org/linux/man-pages/man3/io_uring_register_file_alloc_range.3.html) in liburing.
=> io_uring: add register_file_alloc_range

lib/std/os.zig
=> std.os: handle ENOENT for fcntl on macos

src/Compilation.zig
If clang encountered bad imports, the depfile will not be generated. It doesn't make sense to warn the user in this case. In fact, `FileNotFound` is never worth warning about here; it just means that the file we were deleting to save space isn't there in the first place! If the missing file actually affected the compilation (e.g. another process raced to delete it for some reason) we would already error in the normal code path which reads these files, so we can safely omit the warning in the `FileNotFound` case always, only warning when the file might still exist.
To see what this fixes, create the following file...
```c
#include <nonexist>
```
...and run `zig build-obj` on it. Before this commit, you will get a redundant warning; after this commit, that warning is gone.
=> Compilation: don't warn about failure to delete missing C depfile

lib/std/os/linux.zig
As an aside, the [man page](https://man7.org/linux/man-pages/man2/socketcall.2.html) for `socketcall` seems to suggest that its use should be phased out in favour of more specific syscalls. Additionally, [comments](https://github.com/torvalds/linux/blob/9c69f88849045499e8ad114e5e13dbb3c85f4443/include/linux/syscalls.h#L1169-L1170) in the kernel source code explicitly label `socketcall` as "obsolete" See [these](https://git.musl-libc.org/cgit/musl/log/?qt=grep&q=socketcall) commits for an example of this approach being taken in musl. It does seem to complicate the implementations a bit. As you can see in musl, they have code to handle falling back to the `socketcall` approach when the new syscalls are unavailable. However, as Zig only supports Linux versions >= 5.10, most if not all of …
=> Fix implementation of std.os.linux.accept on x86

lib/c.zig, lib/c/strings.zig, lib/libc/musl/src/string/bzero.c, src/musl.zig, src/wasi_libc.zig
I implemented this according to [this comment](https://github.com/ziglang/zig/issues/2879#issuecomment-2797310223).
Should contribute to closing #2879 .
First contribution so I start with an easy one (I hope).
=> Introduce common `bzero` libc implementation.

lib/compiler/build_runner.zig, lib/std/Build.zig, lib/std/Build/Step/Run.zig, lib/std/Target.zig, lib/std/fs/test.zig, lib/std/hash/xxhash.zig, lib/std/os/linux/test.zig, lib/std/posix/test.zig, lib/std/zig/target.zig, test/behavior/basic.zig, test/tests.zig
* `--glibc-runtimes` is now called `--libc-runtimes` as it now also works for dynamic musl. (`--glibc-runtimes` is still accepted for compatibility, but it won't show up in `--help`.) I've written a wiki page with copy-pastable scripts for building glibc and musl for (almost) all supported targets: https://github.com/ziglang/zig/wiki/Building-multiple-libcs-for-testing
* Dynamically-linked variants of all musl targets have been added to the module test matrix. Some are commented out because they're crashing/hanging, however. Most are gated by `-Dtest-extra-targets` mainly because we only have so much CI time to work with. `x86_64-linux-musl` and `aarch64-linux-musl` are not gated because they're the most common platforms that dynamic musl will be used on, so we'll want to have some bare …
=> Rename `--glibc-runtimes` to `--libc-runtimes` and make it work with musl; add more targets to the module test matrix

lib/compiler/resinator/compile.zig, lib/docs/wasm/markdown/Parser.zig, lib/std/crypto/tls/Client.zig, lib/std/elf.zig, lib/std/fmt.zig, lib/std/http/Client.zig, lib/std/mem.zig, lib/std/tar.zig, lib/std/zig/LibCInstallation.zig, lib/std/zig/Parse.zig, lib/std/zig/render.zig, lib/std/zig/system.zig, lib/std/zig/system/darwin.zig, lib/std/zig/system/linux.zig, src/link.zig, src/link/MachO/Archive.zig, src/link/Wasm/Archive.zig, test/src/Cases.zig, test/standalone/simple/guess_number/main.zig, tools/docgen.zig, tools/doctest.zig, tools/incr-check.zig
Rename `trimLeft` to `trimStart`, and `trimRight` to `trimEnd`. `trimLeft` and `trimRight` functions remain as deprecated aliases for these new names.
Due to this change, these functions will do exactly what their names suggest in right-to-left scripts, just like in left-to-right scripts and non-string slices.
The new function names I suggested are inspired by JavaScript,[^1][^2] C#,[^3][^4] and Rust.[^5][^6]
Closes #23664
[^1]: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimStart>
[^2]: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimEnd>
[^3]: <https://learn.microsoft.com/en-us/dotnet/api/system.string.trimstart>
[^4]: <https://learn.microsoft.com/en-us/dotnet/api/system.string.trimend>
[^5]: …
=> chore(std.mem): Rename `trimLeft` and `trimRight` to `trimStart` and `trimEnd`

lib/compiler/resinator/cli.zig, lib/compiler/resinator/res.zig, lib/std/Build/Step/CheckObject.zig, lib/std/enums.zig, lib/std/json/static.zig, lib/std/meta.zig, src/Package/Fetch/git.zig, src/Value.zig, test/behavior/enum.zig
Also use an optional as the return type instead of an error code because it was kind of pointless.
=> std.meta.intToEnum -> std.enums.fromInt

lib/std/enums.zig, lib/std/io.zig, lib/std/meta.zig
This was a temporary workaround intended to be removed after zig1.wasm was updated.
I saw someone about to cargo cult this now useless `++ ""` into their own code, so I think we should finally revert it.
This reverts commit c8fa767f083e610840cef688b709783c5ad66acc.
=> Revert "Work around stage1 not yet returning null-terminated `@typeInfo` strings"

lib/compiler/reduce.zig
=> `reduce`: Fix build due to `std.mem.Alignment` changes.

lib/std/zig/Ast.zig, lib/std/zig/AstGen.zig, test/cases/compile_errors/Issue_6823_dont_allow_._to_be_followed_by_.zig, test/cases/compile_errors/missing_parameter_name.zig
1. Error messages never contain periods or grave accents. Get rid of the periods and use apostrophes instead in probably the only two error messages that had them.
2. Change T to Type. It looks like something taken from languages like Rust that by convention use single letters for type parameter names. Zig doesn't need that.
=> make error messages prettier

lib/compiler/build_runner.zig, src/Compilation.zig, src/Sema.zig, src/Sema/comptime_ptr_access.zig, src/Zcu.zig, test/cases/compile_errors/add_overflow_in_function_evaluation.zig, test/cases/compile_errors/closure_get_depends_on_failed_decl.zig, test/cases/compile_errors/compile_time_division_by_zero.zig, test/cases/compile_errors/comptime_try_non_error.zig, test/cases/compile_errors/comptime_var_referenced_by_type.zig, test/cases/compile_errors/constant_inside_comptime_function_has_compile_error.zig, test/cases/compile_errors/error_in_comptime_call_in_container_level_initializer.zig, test/cases/compile_errors/generic_function_instantiation_inherits_parent_branch_quota.zig, test/cases/compile_errors/generic_instantiation_failure_in_generic_function_return_type.zig, test/cases/compile_errors/missing_main_fn_in_executable.zig, test/cases/compile_errors/missing_struct_field_in_fn_called_at_comptime.zig, test/cases/compile_errors/mul_overflow_in_function_evaluation.zig, test/cases/compile_errors/negation_overflow_in_function_evaluation.zig, test/cases/compile_errors/non-comptime-parameter-used-as-array-size.zig, test/cases/compile_errors/private_main_fn.zig, test/cases/compile_errors/recursive_inline_fn.zig, test/cases/compile_errors/referring_to_a_struct_that_is_invalid.zig, test/cases/compile_errors/ret_coercion_error_in_generic_fn_called_from_non_fn_scope.zig, test/cases/compile_errors/runtime_operation_in_comptime_scope.zig, test/cases/compile_errors/sema_src_used_after_inline_call.zig, test/cases/compile_errors/stack_usage_in_naked_function.zig, test/cases/compile_errors/store_to_comptime_var_through_call.zig, test/cases/compile_errors/sub_overflow_in_function_evaluation.zig, test/cases/compile_errors/unreachable_executed_at_comptime.zig
* Ensure we always show the first (and only the first) reference trace when `-freference-trace` is not passed
* Previously, an *arbitrary* error had the trace, because we added it to the first error Sema hit but later sorted the errors
* The old logic also did not support incremental compilation, where there might be unused entries in `failed_analysis`
* Include inline calls in the reference trace
* Inline calls "above" the current `AnalUnit` still appear as notes, but inline calls "below" the current `AnalUnit` now appear in the reference trace
* This makes it easier to track the full chain of references, particularly when comptime calls are involved since they often nest deeply
* These frames appear in the reference trace with `[inlined]` appended to the function name
* Improve "called …
=> compiler: reference trace fixes

src/Sema.zig, test/behavior/maximum_minimum.zig
I only wanted to fix a bug originally, but this logic was kind of a rat's nest. But now... okay, it still *is*, but it's now a slightly more navigable nest, with cute little signs occasionally, painted by adorable rats desparately trying to follow the specification.
Hopefully #3806 comes along at some point to simplify this logic a little.
Resolves: #23139
=> Sema: rewrite `analyzeMinMax`

src/libs/netbsd.zig
@mlugg does this look correct?
=> compiler: Fix build break due to #23836 being merged before #23913

lib/std/zig/target.zig
Leftover from 76d525f74a33e20dfa4c9e84b27ce8ad84529cac.
=> `std.zig.target`: Remove `thumb-freebsd-eabihf`.

lib/std/Build/Step/Run.zig, test/standalone/options/build.zig, test/tests.zig
Right now, if you override the build root with `--build-root`, then `Run` steps can fail to execute because of incorrect path handling in the compiler: `std.process.Child` gets a cwd-relative path, but also has its cwd set to the build root. The latter behavior is really weird; it doesn't match my expectations, nor does it match how we spawn child `zig` processes. So, this commit makes the child process inherit the build runner's cwd, as `LazyPath.getPath2` *expects* it to.
After investigating, this behavior dates all the way back to 2017; it was introduced in 4543413. So, there isn't any clear/documented reason for this; it should be safe to revert, since under the modern `LazyPath` system it is strictly a bug AFAICT.
=> std.Build.Step.Run: inherit build runner cwd

src/Package/Module.zig
37a9a4e accidentally turned paths `b/[hash]/` into `b[hash]/` in the global cache. This doesn't technically break anything, but it pollutes the global cache directory. Sorry about that one!
=> Module: name builtin module root directory correctly

lib/std/c.zig
OpenBSD -current grew EVFILT_USER. See commit message [1] and and
current sys/event.h [2]
Also EVFILT_DEVICE was missing.
Closes #23930
[1]: https://marc.info/?l=openbsd-cvs&m=174686993115485&w=2
[2]: https://codeberg.org/OpenBSD/src/src/branch/master/sys/sys/event.h
=> Add EVFILT_USER and friends for OpenBSD

lib/std/Build.zig
The doc comment here agreed with the implementation, but not with *any* `Step` which populates a `GeneratedFile`, where they are treated as cwd-relative. This is the obvious correct choice, because these paths usually come from joining onto a cache root, and those are cwd-relative if not absolute.
This was a pre-existing bug, but #23836 caused it to trigger more often, because the compiler now commonly passes the local cache directory to the build runner process as a relative path where it was previously an absolute path.
Resolves: #23954
=> std.Build: resolved generated paths are cwd-relative

src/Compilation.zig, src/libs/mingw.zig
By using the debug UCRT, we get access to functions like `_CrtDbgReport`.
Closes #23983.
=> `mingw`: Link to `ucrtbased.dll` instead of API set DLLs in Debug mode.

.github/workflows/ci.yaml
We don't seem to be getting non-deterministic hangs since 4f3b59f, and e28b402 cut the run times significantly on top of that. Runs now seem to take around 1-2 hours, so the default timeout should be plenty.
=> `ci`: Revert `aarch64-linux` timeout to GitHub's default 6 hours.

src/Compilation.zig, src/libs/mingw.zig
This reverts commit 4641e9556d1343e95e4676e2f1e3024173db9962.
See discussion on #24052.
=> Revert "mingw: Link to ucrtbased.dll instead of API set DLLs in Debug mode."

lib/std/os/windows.zig, lib/std/os/windows/kernel32.zig
These functions have been unused for a long time (since cfffb9c5e96eeeae43cd724e2d02ec8c2b7714e0; the PEB is used for this stuff now), and the GetEnvironmentVariableW wrapper's parameter types don't make much sense to boot.
Contributes towards:
- https://github.com/ziglang/zig/issues/4426
- https://github.com/ziglang/zig/issues/1840
=> windows: Delete obsolete environment variable kernel32 wrappers and bindings

CMakeLists.txt, lib/compiler/build_runner.zig, lib/std/Build/Step.zig
We have no control over memory usage on arbitrary systems in the wild. But we would still like to get the warnings so we can adjust the values based on observations in the official ZSF CI.
Closes #23254.
Closes #23638.
=> `std.Build`: Demote errors for exceeding `max_rss` to warnings.

src/Air/Legalize.zig, src/Type.zig, test/behavior.zig, test/behavior/align.zig, test/behavior/bitcast.zig, test/behavior/cast.zig, test/behavior/struct.zig, test/behavior/union.zig
Closes #22915
Implements, for the x86_64 backend, #19755
=> Legalize: handle packed semantics

src/Compilation.zig, src/link/Coff.zig
Linking it by default means that we produce binaries that, effectively, only run on systems which have the Windows SDK installed because `ucrtbased.dll` is not redistributable, and the Windows SDK is what actually installs `ucrtbased.dll` into `%SYSTEM32%`. The resulting binaries also can't run under Wine because Wine does not provide `ucrtbased.dll`.
It is also inconsistent with our behavior for `*-windows-gnu` where we always link `ucrtbase.dll`. See #23983, #24019, and #24053 for more details.
So just use `ucrtbase.dll` regardless of mode. With this change, we can also drop the implicit definition of the `_DEBUG` macro in `zig cc`, which has in some cases been problematic for users.
Users who want to opt into the old behavior can do so, both for `*-windows-msvc` and `*-windows-gnu`, by …
=> compiler: Don't link `ucrtbased.dll` when targeting `*-windows-msvc` in Debug mode

src/Compilation.zig, src/Compilation/Config.zig, src/main.zig, src/target.zig
To my knowledge, the only platform that actually *requires* PIE is Android, and that is *only* when building a dynamically-linked executable. Fuchsia, OpenBSD, and macOS all strongly encourage using PIE by default, but it isn't technically required. So for the latter platforms, we enable it by default but don't enforce it.
Also, importantly, if we're building an object file or a static library, and the user hasn't explicitly told us whether to build PIE or non-PIE code (and the target doesn't require PIE), we should *not* default to PIE. Doing so produces code that cannot be linked into non-PIE output. In other words, building an object file or a static library as PIE is an optimization only to be done when the user knows that it'll end up in a PIE executable in the end.
Closes #21837.
=> compiler: Rework PIE option logic.

lib/libcxx/include/__locale_dir/locale_base_api.h, lib/libcxx/include/__locale_dir/support/bsd_like.h, lib/libcxx/include/__locale_dir/support/freebsd.h, lib/libcxx/include/__locale_dir/support/netbsd.h
=> `libcxx`: Fix locale-related compilation errors on NetBSD.

src/link.zig, src/link/Elf.zig, src/link/Elf/Object.zig, src/link/Elf/file.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig
Note that `openLoadArchive` already has linker script support.
With this change I get a failure parsing a real archive in the self hosted elf linker, rather than the previous behavior of getting an error while trying to parse a pseudo archive that is actually a load script.
Also support non-comdat groups, whatever those are.
=> link: support static archives that are linker scripts

lib/std/zig/AstGen.zig, test/cases/type_names.zig
Representing this with a `GenZir` field is incredibly bug-prone. Instead, just pass this data directly to the relevant expression in the very few places which actually provide a name strategy.
Resolves: #22798
=> AstGen: fix name strategy bugs

test/cases/type_names.zig
A different merge must have changed these numbers before this PR was merged, leading to CI failures.
=> cases: fix type names

doc/langref.html.in
Context: 
* https://lobste.rs/s/oei5fj/jepsen_tigerbeetle_0_16_11#c_gkrsdf
* https://lobste.rs/s/oei5fj/jepsen_tigerbeetle_0_16_11#c_c8znsc
I am also not suprer happy about the clause that immediately follows. I
_believe_ what we want to say here is that, simultaneously:
* undefined is guaranteed to be matrerialized in in all safe modes.
A Zig implementation that elides `ptr.* = undefined` in ReleaseSafe
mode would be a non-conforming implementation.
* A Zig program that relies on undefined being materialized is buggy.
But I don't think it's the time to engage this level of language-lawering!
=> langref: undefined _is_ materialized in all safe modes

src/link/Dwarf.zig, test/cases/type_names.zig, test/incremental/change_struct_same_fields
Someone mentioned that the self-hosted binary sizes were getting slightly ridiculous, and one glance at the section size distribution showed that something was, in fact, *incredibly* wrong.  This PR adds back the missing padding to fix the section sizes that were not actually supposed to be the largest sections in the binary.
`master $ zig build -Duse-llvm=false -Ddev=x86_64-linux`: 1.3G
`master $ zig build -Duse-llvm=false`: 886M
`branch $ zig build -Duse-llvm=false`: 396M
`branch $ zig build -Duse-llvm=false -Ddev=x86_64-linux`: 222M
=> Dwarf: restore missing non-entry padding to fix output binary size issues

lib/std/fmt/parse_float.zig, lib/std/fmt/parse_float/convert_hex.zig
=> std.fmt.parseFloat: fix hex-float negative inf

lib/compiler/build_runner.zig, lib/std/Build/Watch.zig, lib/std/c.zig, lib/std/c/haiku.zig, lib/std/crypto/Certificate/Bundle.zig, lib/std/fs/Dir.zig
various low-hanging fruit, builds usable stage3
see https://github.com/ziglang/zig/issues/7691#issuecomment-2923883574
=> Haiku fixes

doc/langref.html.in, lib/std/zig/AstGen.zig, src/Sema.zig, src/Value.zig, test/behavior/vector.zig
Allow binary not, binary and, binary or, binary xor, and boolean not operators on vectors of bool and add corresponding tests.
Also update the lang ref to clarify use of operators on vectors.
This closes #24093.
=> Allow more operators on bool vectors 

lib/std/zig/Parse.zig, lib/std/zig/parser_test.zig
this could cause usages of `error_value` to go past the end of the token list due to the assumption that `main_token + 2` existed
=> bail when failing to parse `error`

lib/init/build.zig, lib/init/build.zig.zon, lib/init/src/main.zig, lib/init/src/root.zig, src/main.zig
And also rename `advancedPrint` to `bufferedPrint` in the zig init templates.
These are left overs from my previous changes to zig init.
The new templating system removes LITNAME because the new restrictions on package names make it redundant with NAME, and the use of underscores for marking templated identifiers lets us template variable names while still keeping zig fmt happy.
=> zig init: simplify templating logic

src/Zcu/PerThread.zig, src/link.zig, src/link/Queue.zig
I messed up atomic orderings on this variable because they changed in a local refactor at some point. We need to always release on the store and acquire on the loads so that a linker thread observing `.ready` sees the stored MIR.
=> compiler: fix races in link queue

lib/compiler_rt/sin.zig, lib/compiler_rt/sincos.zig, lib/compiler_rt/tan.zig
closes #24184
According to the comment, this line of the current `sin` function evaluates `x + 0x1p120` and raises an `INEXACT` exception if `x` is not zero.
It also evaluates `x / 0x1p120` and raises an `UNDERFLOW` exception if `x` is a non-normalized number.
```zig
// raise inexact if x != 0 and underflow if subnormal
if (common.want_float_exceptions) mem.doNotOptimizeAway(if (ix < 0x00100000) x / 0x1p120 else x + 0x1p120);
```
This is the disassembly results of the `sin` function test built in #24184.
```sh
$ llvm-objdump -S -l -d ./zig-out/bin/sin
[omitted]
; /workspaces/zig/lib/compiler_rt/sin.zig:101
;             if (common.want_float_exceptions) mem.doNotOptimizeAway(if (ix < 0x00100000) x / 0x1p120 else x + 0x1p120);
1075300: f144011f     	cmp	x8, #0x100, lsl #12     // =0x100000 …
```
=> libc: Prevent FCSEL instruction from being used to avoid raising an unintended exception

lib/compiler_rt.zig
=> `compiler-rt`: Export `_fltused` for UEFI.

src/Compilation.zig, test/standalone/build.zig.zon, test/standalone/entry_point/build.zig, test/standalone/entry_point/check_differ.zig, test/standalone/entry_point/main.zig
I unintentionally closed #23891 while pruning branches; this is the exact same diff.
Resolves: #23869
=> Compilation: add missing link file options to cache manifest

CMakeLists.txt
Cmake by default adds the `/RTC1` compiler flag for debug builds. However, this causes C code that conforms to the C standard and has well-defined behavior to trap. Here I've updated CMAKE to use the more lenient `/RTCs` by default which removes the uninitialized variable checks but keeps the stack error checks.
=> windows: MSVC: disable extra dubious Microsoft runtime checks

CMakeLists.txt
In debug builds, this change updates all cmake targets to statically link to the "Universal C Runtime Library" (ucrt) by default. This adds about 1 to 2 megabytes but also removes th runtime dependency on `ucrtbased.dll`, which is only available on machines that have installed the Windows SDK (and added the ucrtbased.dll parent directory to the system `PATH` environment variable).
=> windows: msvc: avoid depending on ucrtbased.dll by statically linking to ucrt in debug mode

lib/std/Thread.zig, lib/std/Thread/Futex.zig, lib/std/os/linux.zig, lib/std/os/linux/test.zig
linux: futex v1 API cleanup
* Use Ziggish `packed struct` for flags arguments.  Old: `linux.FUTEX.WAIT` vs new: `.{ .cmd = .WAIT, .private = false }`.
* rename `futex_wait` and `futex_wake` which didn't actually specify wait/wake, as `futex_3arg` and `futex_4arg` (as its the number of parameters that is different, the actual `op` is the second parameter).
* provide the full six-arg flavor of the syscall (for some of the advanced ops), and add packed structs for the flag-ish parameters.
* Use a `packed union` to support the 4th parameter which is sometimes a `timespec` pointer, and sometimes a 32-bit value.
* Add tests that make sure the structure layout is correct and that the basic argument passing is working (no actual futexes are contended).
linux: futex v2 API cleanup
* `futex2_waitv` …
=> Linux futex (v1 and v2) API fixes, tests and Ziggification

lib/compiler_rt/fmax.zig, lib/compiler_rt/fmin.zig
Closes #24214
This PR enables `fmax` and `fmin` to differentiate between `0.0` and `-0.0`, making it compatible with musl.
Maybe we can remove the musl `fmin` and `fmax` that are not processor specific and that would be another PR.
=> compiler_rt: enable `fmax` and `fmin` to distinguish between `0.0` and `-0.0`

test/behavior/slice.zig
=> x86_64: fix pair live-out tracking

lib/std/Build/Watch.zig
I hope it's okay to take over the inactive pull request https://github.com/ziglang/zig/pull/20672. The patch is very similar but I've taken into account the review comments: since indices correspond between the 'public' `DirTable` and 'private' (to the Linux implementation) `HandleTable` I've stashed the mount point information in there. However, the Windows implementation is quite similar and shares `markAllFilesDirty` so I had to add a small edge case, not sure what you'll think of it.
I've been using Zig for the past two weeks so apologies if I'm not following conventions. I've tested my change by following the [wiki](https://github.com/ziglang/zig/wiki/Contributing#editing-source-code) and since I'm on NixOS I'm hitting this problem immediately (same error message as #20670).
Fixes …
=> std.Build.Watch: key fanotify file descriptors by mount id

lib/std/os/linux/powerpc.zig, lib/std/os/linux/powerpc64.zig
Fixes #24230.
On powerpc64le Linux, the [registers used for passing syscall parameters](https://www.kernel.org/doc/html/v6.15/arch/powerpc/syscall64-abi.html#register-preservation-rules) (r3–r8, as well as r0 for the syscall number) are volatile, or caller-saved. However, Zig's syscall wrappers for this architecture do not include all such registers in the list of clobbers, leading the compiler to assume these registers will maintain their values after the syscall completes.
In practice, this resulted in a segfault when allocating memory with `std.heap.SmpAllocator`, which calls `std.os.linux.sched_getaffinity`. The third parameter to `sched_getaffinity` is a pointer to a `cpu_set_t` and is stored in register r5. After the syscall, the code attempts to access data in the `cpu_set_t`, but …
=> Fix illegal behavior from syscalls on powerpc64le

lib/libc/include/generic-glibc/sys/random.h, lib/libc/include/generic-glibc/sys/single_threaded.h, lib/libc/include/generic-glibc/threads.h, lib/libc/include/generic-glibc/unistd.h
this makes it possible to build the following libraries with `-target x86_64-linux-gnu.2.17` :
- gettext
- zstd
- curl
which all previously failed.
closes https://github.com/ziglang/zig/issues/24233
=> add glibc versioning for a number of headers

lib/compiler/test_runner.zig, test/behavior/align.zig, test/behavior/atomics.zig, test/behavior/bitcast.zig, test/behavior/cast.zig, test/behavior/cast_int.zig, test/behavior/enum.zig, test/behavior/error.zig, test/behavior/generics.zig, test/behavior/math.zig, test/behavior/optional.zig, test/behavior/packed-struct.zig, test/behavior/packed-union.zig, test/behavior/popcount.zig, test/behavior/src.zig, test/behavior/struct.zig, test/behavior/threadlocal.zig, test/behavior/union.zig
Previously tests for stage2 RISC-V 64 backend are never failing. This PR fixes it and skips all currently failing rv64 behavior tests.
=> compiler: test runner: fix tests never fails on crippled architectures

src/link/Lld.zig
This new error (`error.UnsupportedCoffArchitecture`) mirrors the error returned from the Elf struct (`error.UnsupportedElfArchitecture`):
https://github.com/ziglang/zig/blob/0adcfd60f4fcfd01c74a6477cbcef187ce06f533/src/link/Lld.zig#L112
Before:
```
$ zig build-exe -target riscv64-windows-gnu main.zig
thread 543087 panic: reached unreachable code
```
After:
```
$ zig build-exe -target riscv64-windows-gnu main.zig
error: unable to create compilation: UnsupportedCoffArchitecture
```
Closes #24287
=> Replace `unreachable` with error return for non-standard Windows targets

lib/compiler/resinator/main.zig, src/Compilation.zig
Previously, resinator would use the host arch as the target arch when looking for windows-gnu include directories. However, Zig only thinks it can provide a libc for targets specified in the `std.zig.target.available_libcs` array, which only includes a few for windows-gnu. Therefore, when cross-compiling from a host architecture that doesn't have a windows-gnu target in the available_libcs list, resinator would fail to detect the MinGW include directories.
Now, the custom option `/:target` is passed to `zig rc` which is intended for the COFF object file target, but can be re-used for the include directory target as well. For the include directory target, resinator will convert the MachineType to the relevant arch, or fail if there is no  equivalent arch/no support for detecting the …
=> zig rc: Fix include directory detection when cross-compiling from certain host archs

lib/std/posix.zig
=> std.posix.getsockopt: set option length correctly

build.zig, src/Compilation.zig, src/Sema.zig, src/libs/mingw.zig, src/main.zig, test/standalone/simple/build.zig, test/standalone/windows_argv/build.zig, test/standalone/windows_bat_args/build.zig, test/standalone/windows_spawn/build.zig, test/tests.zig
Closes #23971.
When encountering a declaration such as
```zig
pub extern "ws2_32" fn closesocket(s: SOCKET) callconv(.winapi) i32;
```
the Zig compiler will no longer automatically add the import library for `ws2_32.dll` as a link input. Users will now need to manually link `ws2_32` either by passing `-lws2_32` on the command line, or by calling `b.linkSystemLibrary("ws2_32")` in a build script (conditioned on `target.os.tag == .windows`).
This change was made because the old behavior obscured which DLLs a Windows binary actually depends on. Zig favors explicitness, and users are required to specify link dependencies explicitly for all other targets, making the old Windows behavior inconsistent. Finally, semantic analysis of Zig code having the ability to introduce new link inputs in the …
=> Sema: Stop adding Windows implib link inputs for `extern "..."` syntax.

src/Compilation.zig, src/libs/wasi_libc.zig, src/link/Lld.zig, src/main.zig
This matches what we do for small helper libraries like this in MinGW-w64. It simplifies the compiler a bit, and also means the build system doesn't have to treat these library names specially.
Closes #24325.
=> `wasi`: Build emulated libraries into `libc.a`

lib/compiler_rt/emutls.zig, src/codegen/llvm.zig, src/codegen/llvm/bindings.zig, src/main.zig, src/target.zig, src/zig_llvm.cpp, src/zig_llvm.h
=> `llvm`: Use emulated TLS when appropriate for the target

src/codegen/llvm.zig
Reverts #17963 (workaround for #16392). The LLVM bug appears to have since been fixed.
Closes #16392.
=> `llvm`: Revert #17963 (workaround for #16392)

lib/std/zon/parse.zig
https://github.com/ziglang/zig/issues/23922#issuecomment-3054296672
=> `std`: Disable `std.zon parse float` on dynamic `x86-linux-musl`

lib/compiler/build_runner.zig
=> build runner: fix --verbose-llvm-bc= not properly accepting value

lib/std/heap.zig, lib/std/heap/arena_allocator.zig, lib/std/log.zig, lib/std/mem/Allocator.zig
it was kind of wild to not do this before. sorry!
bonus commit: refactor some places to use `Alignment.of` helper
=> std.log: adjust default level for ReleaseSmall to include info + bonus cleanup

src/link/Elf/Object.zig
Apparently raw LLVM IR Bitcode files ("Bitstreams") may appear in
archives with LTO enabled. I observed this in the wild on
Chimera Linux.
I'm not yet sure if it's in scope for Zig to support these special
archives, but we should at least give a correct error message.
=> link.Elf: check files in archives for ELF magic

lib/std/Io/Writer.zig
For the `.fixed` Writer, we pass Slice, which already points to the original array. Because of this it doesn't need to be flushed, but if it is, `w.end` will never become 0 and the while loop will not break since the `fixedDrain` function never decrements or resets `w.end`
You can reproduce it with a simple test:
```
var buffer: [1]u8 = undefined;
var writer: std.io.Writer = .fixed(&buffer);
try writer.writeByte(10);
try writer.flush();
try testing.expectEqual(10, buffer[0]);
```
As a solution I specified `noopFlush` as a strategy instead of `defaultFlush`.
=> Writergate: .fixed flush never breaks out of the loop

lib/std/fs/File.zig, lib/std/posix.zig
=> std.posix.send: should expect ConnectionRefused

test/tests.zig
https://github.com/ziglang/zig/issues/24405
=> test: disable non-native loongarch64 behavior and std tests

lib/std/c.zig, lib/std/posix.zig
The interface and errors for this seem to be very universal and generic. Note Linux already has this defined as a syscall as well.
=> Add setsid to std.(c|posix)

.github/workflows/ci.yaml, ci/riscv64-linux-release.sh, ci/riscv64-linux-releasesafe.sh
The idea is to have 2 runners per machine, since a lot of time is spent building stage3 and stage4, both of which are largely single-core affairs. This will make the test steps take longer, however, so the timeouts have been bumped a bit, and max RSS for the test step has been lowered from 64G to 32G to prevent OOM. Finally, we now only run a single ReleaseSafe job on PRs; Debug and Release jobs are limited to pushes.
=> `ci`: make changes to `riscv64-linux` to try to avoid timeouts

src/main.zig
=> `zig std`: link `ws2_32.dll` on windows

test/standalone/build.zig, test/standalone/build.zig.zon, tools/dump-cov.zig
I discovered that this tool doesn't compile with the current compiler.
Should I add some CI coverage for Zig programs in `tools/` to ensure they remain working?
=> update dump-cov for alignment and writergate changes

lib/std/Build/Step/ConfigHeader.zig
Fixes #16208 by adding the style's `LazyFile` (when it has one) to the step as a dependency.
Tested by building the example code in https://github.com/ziglang/zig/issues/16208#issuecomment-1606740868
=> std.Build.Step.ConfigHeader: add the lazy file styled input as a dependency

lib/std/Io/Reader.zig, lib/std/testing.zig, lib/std/zig.zig
closes #24443
bonus: update OneByteReader usage to std.testing.Reader
=> std.Io.Reader: fix readSliceShort with smaller buffer than Reader

lib/compiler_rt/exp.zig, lib/compiler_rt/exp2.zig, lib/compiler_rt/log.zig, lib/compiler_rt/log10.zig, lib/compiler_rt/log2.zig, lib/std/math/expm1.zig, lib/std/math/log1p.zig
Simplified version of https://github.com/ziglang/zig/pull/16808.
- Create tests for all exp/log functions under `lib/std/math/` and `lib/compiler_rt/`
- Sanity tests, taken from [libc-test](https://wiki.musl-libc.org/libc-test.html) (e.g. [exp.h](http://nsz.repo.hu/git/?p=libc-test;a=blob;f=src/math/sanity/exp.h;h=7cbdfcae8770955be175e824e92e535fabae4430;hb=HEAD))
- Special cases (inf, nan, 0, ...)
- Boundary cases (last value before inf, first subnormal, ...)
- Remove existing tests to avoid duplication (these new tests provide more complete coverage)
- Bugfixes uncovered by improved testing:
- `exp2_32()` flushing to zero too soon
- `expm1_32()` giving incorrect results for a certain range of small negative inputs
- `ln64()` giving incorrect results for positive subnormal inputs
--- …
=> Math tests simplified (exp and log functions) with bugfixes

lib/std/os/uefi/protocol/file.zig
Hi.
This is a PR of mine to try and fix `getInfo()` method in the stdlib in file `lib/std/os/uefi/protocol/file.zig`.
My fix was based on the message from the compiler that can be read in the issue #24480 . Since I am new to Zig, I have no clue if this is the actual fix or just some kind of "band-aid". Feel free to mention better ways of improving this.
Thanks!
=> std.os.uefi.protocol.file: use @alignCast in getInfo() method to fix #24480

src/codegen/llvm.zig
=> llvm: workaround crashes in llvm loop optimizations

src/main.zig
Seems to have been accidentally missed in #24488
=> Fix main.zig

src/Sema.zig
=> Sema: fix missed simplifications of OPVs

test/tests.zig
=> `test`: enable `arm-freebsd-eabihf` std tests

src/arch/wasm/CodeGen.zig, test/behavior/try.zig, test/src/Cases.zig, test/tests.zig
@andrewrk I can pop revert, if needed.
@mlugg I decided to keep `.is_(non_)err_ptr` and etc as there is some symmetry with `.is_(non_)null_ptr`.
=> stage2-wasm: implement try_ptr + is_(non_)err_ptr

src/Compilation.zig
Closes #24565
Tested via `zig build-obj path/to/std.zig -fno-emit-bin -femit-docs`.
=> Autodoc: fix sources.tar generation

lib/compiler/std-docs.zig
Analogous to #24576 for `-femit-docs`
Without this change, I get "panic: unable to unpack tar: EndOfStream" when the documentation is displayed, but it works with this change applied.
=> zig std: fix sources.tar generation

src/codegen/aarch64.zig, src/codegen/aarch64/Assemble.zig, src/codegen/aarch64/Select.zig, src/codegen/aarch64/encoding.zig, src/codegen/aarch64/instructions.zon, test/behavior/basic.zig, test/behavior/cast.zig, test/behavior/pointers.zig
Not all C compilers natively support 128 bit integer types, and the CBE currently lowers switches as C switch statements. This means that MSVC (or any compiler where `zig_has_int128` is 0) cannot compile zig2.c if it contains any switches on (i|u)128.
Of course, it would be ideal if the CBE could lower these switches differently. In this case however, the switches in question don't require the full 128-bit range.
=> aarch64: avoid switching on > 64 bit values, to facilitiate bootstrapping with C compilers without 128 bit integers

lib/compiler/build_runner.zig, lib/std/Progress.zig
Turns out there's escape codes for sending progress status to the terminal: https://conemu.github.io/en/AnsiEscapeCodes.html#ConEmu_specific_OSC
As far as I'm aware only Windows Terminal and Ghostty support these. I didn't get access to either one yet for testing so this PR is going in blind.
```zig
const testing = std.testing;
const assert = std.debug.assert;
const main_progress_node = std.Progress.start(.{
.estimated_total_items = stuff.len,
.initial_delay_ns = 0,
});
defer main_progress_node.end();
for (&stuff) |name| {
const node = main_progress_node.start(name, 0);
defer node.end();
std.Thread.sleep(100 * std.time.ns_per_ms);
}
}
const stuff = [_][]const u8{
"frobnicating",
"confabulating",
"prognosticating",
"retabulating", …
```
=> std.Progress: support progress bar escape codes

src/Sema.zig, test/behavior/ptrcast.zig
=> Sema: exclude sentinel from source array length in pointer cast to slice

doc/langref/build.zig, doc/langref/build_c.zig, doc/langref/build_object.zig, lib/std/Build/Step/Compile.zig, test/link/elf.zig, test/link/link.zig, test/link/macho.zig, test/link/wasm/extern/build.zig, test/src/Cases.zig, test/src/RunTranslatedC.zig, test/standalone/c_embed_path/build.zig, test/standalone/extern/build.zig, test/standalone/issue_794/build.zig, test/standalone/stack_iterator/build.zig, test/tests.zig
Not only are `Step.Compile` methods like `linkLibC()` redundant because `Module` exposes the same APIs, it also might not be immediately obvious to users that these methods modify the underlying root module, which can be a footgun and lead to unintended results if the module is exported to package consumers or shared by multiple compile steps. For example, I personally almost ran in to this:
```zig
// module exported to package consumers, doesn't require libc
const mod = b.addModule("mymodule", .{
.root_source_file = b.path("main.zig"),
.optimize = optimize,
});
// some unit tests require libc
const tests = b.addTest(.{ .root_module = mod });
tests.linkLibC(); // uh-oh! now the exported module requires libc!
const run_tests = b.addRunArtifact(tests);
const test_step = …
```
=> std.Build: Deprecate `Step.Compile` APIs that mutate the root module

lib/std/zig.zig
Changes fmtId to return the FormatId type directly, and renames the FormatId.render function to FormatId.format, so it can be used in a format expression directly.
Why? Since `render` is private, you can't create functions that wrap `fmtId` or `fmtIdFlags`, since you can't name the return type of those functions outside of std itself.
The current setup _might_ be intentional? In which case I can live with it, but I figured I'd try making a small contribution to upstream zig :)
=> std.zig: fmtId returns a FormatId directly

src/main.zig, src/print_env.zig
The `zig env` command does not respect the `ZIG_LIB_DIR` environment variable which seems to be unintentional as the similar `ZIG_GLOBAL_CACHE_DIR` variable is being handled as expected. 
With the recent addition of `Compilation.Directories`, I also went ahead and made `zig env` runnable on wasi to make some progress on #20665. Here is how the output `wasmtime run --dir=lib::/lib --dir=cache::/cache build/stage4-wasi/bin/zig.wasm env` looks like:
```json
{
"zig_exe": "zig.wasm",
"lib_dir": "/lib",
"std_dir": "/lib/std",
"global_cache_dir": "/cache",
"version": "0.15.0-dev.650+4f3b59f70",
"target": "wasm32-wasi.0.1...0.2.2-musl",
"env": {
"ZIG_GLOBAL_CACHE_DIR": null,
"ZIG_LOCAL_CACHE_DIR": null,
"ZIG_LIB_DIR": null,
"ZIG_LIBC": null,
"ZIG_BUILD_RUNNER": null,
"ZIG_VERBOSE_LINK": null, …
```
=> update `zig env` to respect `ZIG_LIB_DIR` and support wasi

doc/langref.html.in, src/Zcu.zig, src/codegen/llvm.zig, test/behavior/atomics.zig, test/cases/compile_errors/atomics_with_invalid_type.zig
This PR fixes the lowering of packed structs with non-power-of-two backing integers in the LLVM backend; previously LLVM would throw the error "`atomic memory access' operand must have a power-of-two size`". Additionally, error sets are now caught when used in atomic instructions. Furthermore, I clarified the langref on which types are allowed in atomic builtins.
=> atomic fixes and clarification

src/Sema.zig, test/behavior/slice.zig, test/cases/compile_errors/slice_of_many-item_pointer_preserves_sentinel.zig
This is a rebasing/reopening of the previously closed PR #18033 due to the accepted issue #22345 which addresses the same concerns as #18019 which the original PR was meant to resolve.
The 3 removed lines in the behaviour tests are needed due to the interaction of #22345 with #22344 which pointed out that they should likely not have ever been legal, however behaviour tests run against #22344 would not catch these lines because the way #22344 fixed the issue with incorrect sentinels in the first slicing operation did so by lowering this pattern to a `slice_sentinel`/`slice_end` ZIR node pair instead of adding explicit sentinel checks for by-length slices; see #22371. Since these lines in the behaviour test were slicing a many-item pointer, the `slice_sentinel` was then allowed by the …
=> disallow slicing many-item pointer with different sentinel (rev. 2)

src/Package/Fetch.zig, src/Package/Fetch/git.zig
fsync blocks until the contents have been actually written to disk, which would be useful if we didn't want to report success until having achieved durability. But the OS will ensure coherency; i.e. if one process writes stuff without calling fsync, then another process reads that stuff, the writes will be seen even if they didn't get flushed to disk yet.
Since this code deals with ephemeral cache data, it's not worth trying to achieve this kind of durability guarantee. This is consistent with all the other tooling on the system.
Certainly, if we wanted to change our stance on this, it would not be something that affects only the git fetching logic.
=> fetch: remove calls to fsync

lib/std/c.zig, lib/std/c/openbsd.zig
also add the layout of `struct passwd` for DragonflyBSD and FreeBSD:
- https://github.com/DragonFlyBSD/DragonFlyBSD/blob/c267aac0072dae6cf4ae874605f3f0659a2fc820/include/pwd.h#L112
- https://cgit.freebsd.org/src/tree/include/pwd.h?id=d66f9c86fa3fd8d8f0a56ea96b03ca11f2fac1fb#n114
=> enable pwd.h functions for other OSes

lib/compiler/build_runner.zig, lib/std/Build/Watch.zig, lib/std/Build/Watch/FsEvents.zig
On macOS, instead of using the broken kqueue implementation, use the File System Events API in the Core Services framework to implement `std.Build.Watch`. This API is a bit different to others, because it is based on recursive watches, and it also requires using Apple's "dispatch queue" mechanism instead of just being a simple blocking call. The implementation is mostly contained within its own file, as `std.Build.Watch.FsEvents`, and is designed to not be too tightly coupled to `std.Build` so that in the future it can potentially be refactored into a more general-purpose filesystem watching tool.
Basic testing from myself, and tests from a few affected users, have confirmed this as working, resolving the longstanding issue that `zig build --watch` often does not work correctly on macOS. …
=> std.Build.Watch: add macOS implementation based on FSEventStream

lib/std/Build/Step/Compile.zig
Previously, this only applied when using `-fincremental --watch`, but `--webui` makes the build runner stay alive just like `--watch` does, so the same logic applies here. Without this, attempting to perform incremental updates with `--webui` performs full rebuilds. (I did test that before merging the PR, but at that time I was passing `--watch` too -- which has since been disallowed -- so I missed that it doesn't work as expected without that option!)
=> std.Build: keep compiler alive under `-fincremental --webui`

src/Zcu.zig
The support was already there but somebody forgot to allow to use the calling conventions spirv_fragment and spirv_vertex when having opengl as os tag.
=> OpenGL SPIR-V support

lib/std/Target.zig, src/target.zig
Emulated TLS depends on libc pthread functions.
Closes #24589.
=> `std.Target`: require libc for Android API levels prior to 29

lib/std/compress/flate/Decompress.zig, src/Package/Fetch/git.zig
Closes #24686
As a bonus, this commit also makes the `git.zig` "testing `main`" compile again.
---
Tested on both examples provided in #24686:
```
ian@ian-laptop:~/src/zig/build$ stage4/bin/zig fetch git+https://github.com/Not-Nik/raylib-zig.git#a6e9ce520f056200bc8aaecb6ca3c35ffe84cccd
raylib_zig-5.6.0-dev-KE8REBMwBQD5YduSugg8Iimkyc-G6Daz6OBEjUI94xCz
ian@ian-laptop:~/src/zig/build$ stage4/bin/zig fetch git+https://github.com/blocksds/maxmod.git#v1.8.0-blocks
N-V-__8AAOW1DgDA2yLdI8SMucr-YkH1Y-1JfUI_CR49OBbI
```
=> std.compress.flate.Decompress: return correct size for unbuffered decompression

lib/std/Target/Query.zig
```zig
const query = try std.Target.Query.parse(.{
.arch_os_abi = "x86-windows.xp...win8-msvc",
});
const text = try query.zigTriple(std.heap.smp_allocator);
defer std.heap.smp_allocator.free(text);
std.debug.print("{s}\n", .{text});
}
```
Output:
- 0.14.1: `x86-windows.xp...win8-msvc`
- 0.15.0-dev.1380+e98aeeb73: `x86-windows83951616..100794368-msvc`
=> std.Target.Query: fix `WindowsVersion` format in `zigTriple()`

lib/std/compress/flate/Decompress.zig
`n` is wanted number of bits to toss
`buffered_n` is actual number of bytes in `next_int`
Fixes: #24695
=> flate zlib fix end of block reading

lib/docs/main.js
After the sources tarball is loaded, check the search input for a value. If present, this means the user typed something into it during load - we should use that value for the initial search state instead of always respecting what the hash's search value is.
Future considerations:
- since no event handlers are registered until the tarball loads, we don't get `s` or `?` shortcuts. it would be straightforward to shuffle things around to get these working, but I figured I'd keep this PR short.
- calling `handleNavigation(null ... )` after tarball load forces a scroll to the top - I kept this behavior unchanged, but it does result in users losing their place via a refresh.
Fixes #21458
=> autodoc: Use the search input's value on load

lib/std/os/linux.zig
closes #24471
Please double-check the implementation of `MCL`. I interpreted results of searching the linux source tree:
https://github.com/search?q=repo%3Atorvalds%2Flinux+MCL_ONFAULT&type=code
I found the flags by referencing `man mlock`: https://man7.org/linux/man-pages/man2/mlock.2.html
* on WSL2 on windows
Create file `mlock-test.zig`:
```zig
test "mlock syscalls" {
const allocator = std.testing.allocator;
const my_memory_area: []u8 = try allocator.alloc(u8, 2048);
defer allocator.free(my_memory_area);
const mlock_result = std.os.linux.mlock(my_memory_area.ptr, my_memory_area.len);
std.log.warn("mlock errno: {}", .{std.posix.errno(mlock_result)});
try std.testing.expect(mlock_result == 0);
const munlock_result = std.os.linux.munlock(my_memory_area.ptr, …
```
=> #24471: add mlock syscalls in std.os.linux

lib/std/Io/Reader.zig, lib/std/fs/File.zig
addresses #24695, as well as just being a better, simpler implementation for these functions now that readVec is back in the vtable.
=> std.Io.Reader: use readVec for fill functions

lib/build-web/fuzz.zig, lib/compiler_rt/memcpy.zig, lib/compiler_rt/memmove.zig, lib/std/Io.zig, lib/std/Io/Reader.zig, lib/std/array_hash_map.zig, lib/std/crypto/codecs/asn1/der/Encoder.zig, lib/std/crypto/timing_safe.zig, lib/std/debug.zig, lib/std/debug/SelfInfo.zig, lib/std/hash_map.zig, lib/std/heap.zig, lib/std/heap/SmpAllocator.zig, lib/std/heap/debug_allocator.zig, lib/std/http/Server.zig, lib/std/os/uefi/tables.zig, lib/std/os/uefi/tables/runtime_services.zig, lib/std/os/windows.zig, lib/std/pie.zig, lib/std/zig/Ast/Render.zig, lib/std/zig/c_translation.zig, lib/ubsan_rt.zig, src/InternPool.zig, src/Package/Fetch.zig, src/translate_c.zig, test/behavior/array.zig, test/behavior/comptime_memory.zig, test/behavior/extern.zig, test/cases/compile_errors/nested_ptr_cast_bad_operand.zig, test/translate_c.zig
Closes #24106
Searches for surrounding tokens tagged with `.builtin` when a `.builtin_...` node whose main token ends in `"Cast"` is encountered and picks which one to render first according to the field order in `CastKind`. In case of a redundant casting operation (e.g. `@ptrCast(@volatileCast(@ptrCast(...)))`) no reordering is done for the entire nested chain.
The canonical ordering is the one proposed by mlugg:
```zig
@ptrCast(@alignCast(@addrSpaceCast(@constCast(@volatileCast(something)))))
```
It can be changed by simply rearranging the fields of `CastKind` (and adjusting the rendering order in `translate_c.removeCVQualifiers` for `@constCast()`/`@volatileCast()` and related tests).
The first commit is the actual implementation,the second commit is the new ordering applied to …
=> zig fmt: canonicalize nested cast builtin order

lib/std/compress/flate/Decompress.zig
After #24704 32-bit platform build passes with usize Bits instead of u64. There are two tests which are testing invalid inputs and raise different error in 32 than on 64 bit platform now.
=> flate change bit reader Bits to usize

lib/std/zip.zig
Previously, when extracting a ZIP file, `isBadFilename()`, which is designed to reject `../` patterns to prevent directory traversal, was called before normalizing backslashes to forward slashes.
This allowed path traversal sequences like `..\\..\\..\\etc\\passwd` which pass validation but are then converted to `../../../etc/passwd` for file extraction.
=> std/zip.zig: perform backslash-to-forward-slash before isBadFilename()

lib/std/fs/File.zig, lib/std/posix.zig
Fix usages of `std.c.versionCheck`, where `.linux` os tag should also be checked against android libc version. 
closes #24460
=> Fix some libc version checks

lib/std/Io/Reader.zig
Running tar.pipeToFileSystem compressed_mingw_includes.tar file from #24732 finishes in infinite loop calling defaultReadVec with: r.seek = 1024
r.end = 1024
r.buffer.len = 1024
first.len = 512
that combination calls vtable.stream with 0 capacity writer and loops forever.
Comment is to use whichever has larger capacity, and this fix reflects that.
=> Io.Reader fix defaultReadVec

lib/std/zig/LibCDirs.zig, src/Compilation.zig, src/Package/Module.zig, src/Sema.zig, src/Zcu.zig, src/libs/freebsd.zig, src/libs/glibc.zig, src/libs/libcxx.zig, src/libs/libtsan.zig, src/libs/libunwind.zig, src/libs/mingw.zig, src/libs/musl.zig, src/libs/netbsd.zig, src/libs/wasi_libc.zig, src/link.zig, src/main.zig
The functions `Compilation.create` and `Compilation.update` previously returned inferred error sets, which had built up a lot of crap over time. This meant that certain error conditions -- particularly certain filesystem errors -- were not being reported properly (at best the CLI would just print the error name). This was also a problem in sub-compilations, where at times only the error name -- which might just be something like `LinkFailed` -- would be visible.
This commit makes the error handling here more disciplined by introducing concrete error sets to these functions (and a few more as a consequence). These error sets are small: errors in `update` are almost all reported via compile errors, and errors in `create` are reported through a new `Compilation.CreateDiagnostic` type, a …
=> Compilation: improve error reporting

src/Sema.zig, src/Type.zig
The "completed" count in the "Semantic Analysis" progress node had regressed since 0.14.0: the number got crazy big very fast, even on simple cases. For instance, an empty `pub fn main` got to ~59,000 where on 0.14 it only reached ~4,000. This was happening because I was unintentionally introducing a node every time type resolution was *requested*, even if (as is usually the case) it turned out to already be done. The fix is simply to start the progress node a little later, once we know we are actually doing semantic analysis. This brings the number for that empty test case down to ~5,000, which makes perfect sense. It won't exactly match 0.14, because the standard library has changed, and also because the compiler's progress output does have some *intentional* changes.
=> Sema: fix unreasonable progress node numbers

lib/std/c.zig, lib/std/c/serenity.zig
See: https://github.com/SerenityOS/serenity/commit/59911d8da3da36aefd2d4902a0fdfc21e1f6f8ac
=> std.c: Remove serenity's internet_checksum() function

src/fmt.zig
- Closes #24795
Tested locally:
```
❯ cat foo.zig
}
[lillis@cachyos-x8664] ~/projects/foo
❯ cat foo.zig | /home/lillis/projects/zig/build/stage4/bin/zig fmt --stdin --check
[lillis@cachyos-x8664] ~/projects/foo
❯ echo $?                                                                                                                                                   ⏎
1
[lillis@cachyos-x8664] ~/projects/foo
❯ zig fmt foo.zig
foo.zig
[lillis@cachyos-x8664] ~/projects/foo
❯ cat foo.zig | /home/lillis/projects/zig/build/stage4/bin/zig fmt --stdin --check
[lillis@cachyos-x8664] ~/projects/foo
❯ echo $?
0
```
=> fix(fmt): return correct exit code for `zig fmt --stdin --check`

lib/std/fs/File.zig
The former detects when it is appropriate to switch to streaming mode.
closes #24798
=> std.fs.File: prefer getSize over getEndPos

lib/std/array_hash_map.zig, lib/std/array_list.zig, lib/std/multi_array_list.zig
This algorithm is non-trivial and makes sense for any data structure that acts as an array list, so I thought it would make sense as a method.
I have a real world case for this in a music player application (deleting queue items).
Adds the method to:
* ArrayList
* ArrayHashMap
* MultiArrayList
=> std: introduce orderedRemoveMany

src/codegen/llvm.zig
(probably) closes https://github.com/ziglang/zig/issues/11312
*Probably* because I haven't tested all backends, only C, llvm and self-hosted x86_64.
The described, unoptimized behaviour only occurred in the llvm backend, and there I fixed it by explicitly marking branches where the integer to be converted wouldn't fit as unreachable.
=> optimize `@intCast` in ReleaseFast mode

lib/libtsan/sanitizer_common/sanitizer_common_interceptors_ioctl.inc, lib/libtsan/sanitizer_common/sanitizer_platform_limits_posix.cpp, lib/libtsan/sanitizer_common/sanitizer_platform_limits_posix.h, src/link/Elf/synthetic_sections.zig, test/standalone/build.zig.zon, test/standalone/tsan/build.zig, test/standalone/tsan/main.zig
https://github.com/llvm/llvm-project/pull/137403
makes tsan build again for glibc after #24640
=> tsan: remove interceptors for termio

lib/std/Target.zig
According to https://apilevels.com, 88.5% of Android users are on 29+. Older API levels require libc as of https://github.com/ziglang/zig/pull/24629, which has confused some users. Seems reasonable to bump the default so most people won't be confused by this.
=> `std.Target`: bump default android API level from 24 to 29

lib/docs/wasm/Walk.zig, lib/std/Build/Step/ConfigHeader.zig, lib/std/Io/Writer.zig, lib/std/compress/flate/Decompress.zig, lib/std/debug.zig, lib/std/http/test.zig, lib/std/json.zig, lib/std/json/Stringify.zig, lib/std/tar/Writer.zig, lib/std/tar/test.zig, lib/std/zig/Ast/Render.zig, lib/std/zig/AstGen.zig, lib/std/zig/ErrorBundle.zig, lib/std/zig/ZonGen.zig, lib/std/zon/stringify.zig, src/Compilation.zig, src/Package/Fetch.zig, src/Sema.zig, src/codegen/c.zig, src/fmt.zig, src/link/C.zig, src/link/Dwarf.zig, src/link/Elf.zig, src/link/SpirV.zig, src/main.zig
This "get" is useless noise and was copied from FixedBufferWriter. Since this API has not yet landed in a release, now is a good time to make the breaking change to fix this.
=> std.io.Writer.Allocating: rename getWritten() to written()

lib/std/zig/AstGen.zig, lib/std/zig/Zir.zig, src/Sema.zig, src/print_zir.zig, test/behavior/array.zig
=> sema: strip `@splat` operand result type before checking it

lib/std/zig/parser_test.zig
addendum to #24199, formally tests that the canonicalization actually works as intended
=> zig fmt: add tests for cast builtin canonicalization

lib/std/fs/File.zig
This should be enough to unblock people for now. We'll revisit the way these things are organized with the upcoming std.Io interface.
fixes #24685
=> std.fs.File.Reader: fix freestanding build failures

src/Type.zig, test/cases/compile_errors/error_set_display.zig, test/cases/compile_errors/invalid_pointer_coercions.zig, test/src/Debugger.zig
This PR alters the error set printing logic to sort its members' names before displaying them. This patch is just @mlugg's code from https://github.com/ziglang/zig/issues/21829#issuecomment-3175203876 (thanks so much for the help!) with one small tweak, along with an added test case. 
- Closes #21829
=> fix: print error set members in a consistent order

lib/std/math.zig
A missed `@splat` in the implementations of `std.math.rotl` and `std.math.rotr` caused a compilation error when calling them with `@Vector(_, u0)` - it is now fixed.
=> Fix std.math.rot(l|r) for vectors of u0-s

lib/std/Build/Step.zig
As well as the exact byte count, include a human-readable value so it's clearer what the error is actually telling you. The exact byte count might not be worth keeping, but I decided I would in case it's useful in any scenario.
New errors look like:
```
memory usage peaked at 40.65GB (40650104832 bytes), exceeding the declared upper bound of 7.80GB (7800000000 bytes)
```
=> std.Build: improve error for peak RSS exceeding declared value

lib/std/math/modf.zig
Whatever the compiler bug that prevented the usage of `@trunc()` on `@Vector()` types was, I don't think it exists anymore.
Tested with `stage4/bin/zig build test-std -Dskip-non-native` on x86_64 linux.
=> re-enable std.math.modf vector tests

lib/std/Io/Writer.zig
I know it's supposed to fail, but probably just at runtime.
=> [std] fix compile error in std.Io.Writer.failing

src/Compilation.zig
On macOS, when using the LLVM backend, the output binary retains a reference to this object file's debug info (as opposed to self-hosted backends which instead emit a dSYM bundle). As such, we need to retain this object file in such cases. This object does unfortunately "leak", in that it won't be reused and will just sit in the cache forever (or until GC'd in the future). But that's no worse than the cache behavior prior to the rework that caused this, and it will become less of a problem over time as the self-hosted backend gains usability for debug builds and eventually becomes the default.
Resolves: #24369
=> Compilation: retain ZCU object when emitting unstripped Mach-O binary

lib/std/Io.zig, lib/std/Io/Reader.zig, lib/std/crypto/tls/Client.zig, lib/std/http.zig, lib/std/http/Client.zig, lib/std/http/Server.zig, src/Package/Fetch.zig
* std.Io.Reader: fix confused semantics of rebase. Before it was
ambiguous whether it was supposed to be based on end or seek. Now it
is clearly based on seek, with an added assertion for clarity.
* std.crypto.tls.Client: fix panic due to not enough buffer size
available. Also, avoid unnecessary rebasing.
* std.http.Reader: introduce max_head_len to limit HTTP header length.
This prevents crash in underlying reader which may require a minimum
buffer length.
* std.http.Client: choose better buffer sizes for streams and TLS
client. Crucially, the buffer shared by HTTP reader and TLS client
needs to be big enough for all http headers *and* the max TLS record
size. Bump HTTP header size default from 4K to 8K.
fixes #24872
I have noticed however that there are still fetch problems, perhaps …
=> std: more reliable HTTP and TLS networking

lib/std/Build/Step/Run.zig, lib/std/Io/Writer.zig
Writer.sendFileAll() asserts non-zero buffer capacity in the case that the fallback is hit.
Closes #24552
=> Build.Step.Run: fix missing stdin buffer and flush

lib/compiler/std-docs.zig, lib/std/http.zig, lib/std/http/Client.zig, lib/std/http/Server.zig
http.BodyWriter: handle EOF in chunkedSendFile, simplify
With these changes, the `zig std` command now works again and doesn't trigger assertion failures or mess up the chunked transfer encoding.
Closes #24760
Closes #24859
=> http.BodyWriter: handle EOF in chunkedSendFile, simplify

lib/std/Io/Writer.zig
```zig
std.debug.print("{X}", .{@as(f32, 123)});
// old: 0x1.ecp6
// new: 0x1.ECp6
```
The 'p' being lower case is in line with the 'e' being lower case in the 'E' format specifier.
```zig
std.debug.print("{E}", .{@as(f32, 123)}); // 1.23e2
```
=> std.Io.Writer: fix upper case hex float formatting

lib/std/fs/File.zig, lib/std/net.zig
Closes #24911
This fixes the HTTPS/TLS and package manager problems on Windows. Tested against the repro in the linked issue as well as by `zig build --fetch`ing https://github.com/castholm/zig-examples/tree/master/breakout with an empty global package cache.
=> Fix bugs in Windows readVec implementations

lib/std/c.zig
I just tried to use ptrace on macOS (which is already a miserable experience!) and noticed that `darwin.PT` isn't exposed anywhere. I'm guessing it was missed in #20679.
=> expose darwin.PT in std.c

lib/std/c.zig, lib/std/posix.zig
Linux already gained the relevant syscalls and consts in #24473
The basic mlock() and munlock() are fairly universal across the *nix world with a consistent interface, but are missing on wasi and windows.
The mlockall() and munlockall() calls are not as widely supported as the basic ones.  Notable non-implementers include darwin, haiku, and serenity (and of course wasi and windows again).
mlock2() is Linux-only, as are its MLOCK flags.
=> Add mlock syscalls to std.c and std.posix

lib/std/os/uefi/protocol/service_binding.zig
=> std.os.uefi: Fix typo that causes compile time error #22809"

lib/std/json/static.zig
Fixes #24728 
The `innerParseFromValue` still had the old way of comparing with `maxInt` and `minInt` that was updated in this commit: [`64bf8bb` (#24632)](https://github.com/ziglang/zig/pull/24632/commits/64bf8bb146099b51d74635a1f116a913e442bcf4)
=> std: remove lossy int to float coercion on json parse

lib/std/http/Client.zig
When using ``http.Client.fetch`` with a payload, the http requests did not work because the client forgot to flush.
This fixes it.
I was hoping we could use ``req.sendBodyComplete(payload)`` but got a type error since payload is ``[]const u8`` and that function expects ``[]u8``.
=> http.Client: don't forget to flush

lib/std/math/powi.zig
Without this change, the docs are formatted s.t. the text "Edge case rules ordered by precedence:" is appended onto the prior line of text "Underflow: Absolute value of result smaller than 1", instead of getting its own line.
See issue in docs:
- current docs state: https://ziglang.org/documentation/master/std/#std.math.powi
- original issue docs state: https://ziglang.org/documentation/0.14.1/std/#std.math.powi
=> Update powi.zig to fix docstring formatting

lib/init/build.zig
fix typo in comment about executable module in generated build.zig
I removed repeated "business" word in the comment in [build.zig](https://github.com/ziglang/zig/blob/master/lib/init/build.zig#L46-L47).
=> docs: fix typo in comment by removing repeated 'business' word

lib/std/mem/Allocator.zig
Remove confusing phrase "byte size". Clarify we mean number of items.
=> lib: Reword documentation for realloc to clarify size

src/main.zig
The `test-obj` subcommand, introduced in 927f233, was missing from the help output
=> Add `test-obj` to the help message

lib/std/zig/system.zig
Targeting v9 on sparc32 doesn't by itself imply "v8+" mode (64-bit instructions in 32-bit code).
=> `std.zig.system`: fix check for sparc "v8+" in `getExternalExecutor()`

lib/std/zon/parse.zig
Adds the following functions to `std.zon.parse`:
* `fromSliceFlat`
* `fromZoirFlat`
* `fromZoirNodeFlat`
These are identical to the existing functions with "flat" stripped from the name, but they assert at compile time that the result type doesn't contain a pointer and therefore doesn't need to be freed. As such, the latter two functions do not require an allocator as an argument. (`fromSlice` still does as it needs to allocate the `Ast` and `Zoir`.)
I'm open to alternative suggestions for the names. I think "flat" as in "flat in memory" is pretty reasonable, though it could be misinterpreted as to do with nesting. I would have simply named them `noAlloc`, but this is confusing since `fromSliceFlat` does in fact create (temporary) allocations.
Replaces #22835, CC @NicoElbers (thanks for …
=> Adds non allocating alternatives to ZON parse functions

lib/std/os/linux.zig
This make `fs.Dir.access` has more compatibility as the zig version 0.14.
With this change the `zig build --search-prefix` command would work again like the zig 0.14 version when used on Ubuntu20.04, kernel version 5.4.
Partly Align with [go](https://github.com/golang/go/blob/44c5956bf7454ca178c596eb87578ea61d6c9dee/src/syscall/syscall_linux.go#L155) and musl-libc preference.
No intent to fix issue #24860, as this only try to add more compatibility but no emulation.
=> os.linux: faccessat syscall wrapper  prefer to faccessat when flags is zero

lib/std/process.zig
Hi, I just started learing zig. I was trying to fetch total system memory on macOS and noticed that `totalSystemMemory` does not support it.
This PR adds it.
I believe there are a few issues with `totalSystemMemory` for `.freebsd` and `std.posix.sysctlbynameZ`, but I do not know what the correct approach to take here
1. `totalSystemMemory` for `.freebsd` returns `usize` instead of `u64`, I believe this should be fixed
2. `totalSystemMemory` for `.freebsd` does not handle all the errors from `std.posix.sysctlbynameZ`.
3. Last but not least, `std.posix.sysctlbynameZ` never returns `NameTooLong`. So either we should change the return type, or, as @andrewrk did in https://github.com/ziglang/zig/commit/3640303ce1585f266f94e2c815287cb590478e0d we should add [`name_len` …
=> add Darwin family systems handling for totalSystemMemory

src/Compilation.zig
It does nothing but generate a warning for these.
=> `zig cc`: don't pass `-mcmodel` for assembly files

lib/std/Build/Step/TranslateC.zig
Closes #24958
Let me know if this should also pass on `--global-cache-dir`. I'm not familiar enough with the caching system to be sure but my initial impression was that it isn't necessary.
=> std.Build.Step.TranslateC forward --cache-dir argument

lib/std/Build/WebServer.zig
Just a typo: I wasn't actually using the duped message, so the message I sent could be freed in this interval.
Thanks to @scottredig for noticing this and flagging it up to me.
=> std.Build.WebServer: fix race

lib/std/c.zig
Note the previous "28" here for openbsd was some kind of copy error long ago.  That's the value of KERN.SOMAXCONN, which is an entirely different thing.
=> std.c: add correct SOMAXCONN for BSDs

lib/std/debug.zig, test/standalone/stack_iterator/unwind.zig
We can't call `@frameAddress()` and then immediately `return`! That invalidates the frame. This *usually* isn't a problem, because the stack walk `next` call will *probably* have a stack frame and it will *probably* be at the exact same address, but neither of those is a guarantee. On powerpc, presumably some unfortunate inlining was going on, so this frame was indeed invalidated when we started walking frames.
We need to explicitly pass `@frameAddress` into any function which will return before we actually walk the stack. Pretty simple patch.
Resolves: #24970
=> std.debug: remove `@frameAddress()` "UAF"

src/codegen/llvm.zig, test/behavior/struct.zig
closes #25067
```llvm
; Function Attrs: noredzone nounwind uwtable
define internal fastcc void @test.gimme(ptr noalias sret(%test.S) nonnull %0, ptr align 1 nonnull %1) unnamed_addr #0 {
2:
call void @llvm.memcpy.p0.p0.i64(ptr align 4 %0, ptr align 4 %1, i64 4, i1 false)
ret void
}
```
:arrow_down: 
```llvm
; Function Attrs: noredzone nounwind uwtable
define internal fastcc void @test.gimme(ptr noalias sret(%test.S) nonnull %0, ptr align 1 nonnull %1) unnamed_addr #0 {
2:
%3 = alloca %test.S, align 4
call void @llvm.memcpy.p0.p0.i64(ptr align 4 %3, ptr align 1 %1, i64 4, i1 false)
call void @llvm.memcpy.p0.p0.i64(ptr align 4 %0, ptr align 4 %3, i64 4, i1 false)
ret void
}
```
It's not ideal, but it's correct.
=> LLVM backend:fix align 1 sret parameter load returned

lib/std/Io/Reader.zig
This reverts commit 530cc2c1111699d9d02ad9ebef94efa6b99f5205.
The compiler bug has been fixed.
=> Revert "std.Io.Reader: work around llvm backend bug"

lib/std/c.zig
While porting zig 0.15.1 to OpenBSD I discovered that these values are missing so I populated them from sys/sys/socket.h.  This was the only diff needed to get this compiling. Still untested, but it compiles.
=> Populate MSG struct for OpenBSD. Fixes compilation on 0.15.1

lib/std/http/Client.zig
The following example populates the `Authorization` header with `user:user` instead of `user:password`, due to a typo.
```zig
const allocator = std.heap.page_allocator;
var client = std.http.Client{ .allocator = allocator };
defer client.deinit();
var response = std.io.Writer.Allocating.init(allocator);
defer response.deinit();
const stat = try client.fetch(.{
.method = .POST,
.location = .{
.url = "http://user:password@127.0.0.1",
},
.headers = .{ .content_type = .{ .override = "application/json" } },
.response_writer = &response.writer,
.payload = "{}",
});
std.log.info("OK: status={s}, response={s}", .{ @tagName(stat.status), response.written() });
}
```
=> Fix regression: std.http.Client basic authorization sending user:user instead of user:password when passed in URI

lib/std/compress/lzma2.zig
While porting my project to zig, I found that when extracting large xz file, it fails with below stack trace, after some digging, I found out the looping logic in `appendLz` function append to the `ArrayList` while looping over it, which caused use after free, after my change to use `ensureTotalCapacity` before looping. the `ArrayList` memory is not modified while looping. Detailed analyze:
1. The std.ArrayList.append function may need to reallocate the underlying buffer if it runs out of capacity.
2. When a reallocation occurs, the memory location of the buffer's items changes, and the old memory is freed.
3. However, the loop continues to read from self.buf.items[offset]. The slice self.buf.items was implicitly captured at the start of the operation and now points to the old, freed …
=> lzma2: fix array list looping logic in appendLz

lib/std/compress/lzma2.zig
closes: https://github.com/ziglang/zig/issues/25121
lzma2 Decoder already checks if decoding is finished or not inside the process function, `range_decoder`finish does not mean the decoder has finished, also need to check `ld.rep[0] == 0xFFFF_FFFF`, which was already done inside the proccess function. This fix delete the redundant `isFinish()` check for `range_decoder`.
=> lzma2: fix premature finish

lib/std/c.zig
The getresuid(2) & getresgid(2) calls are available on a bunch of systems, including: glibc/Linux, musl/Linux, OpenBSD, FreeBSD, and even POSIX.1-2024.
=> std.c: add getresuid & getresgid

lib/std/debug.zig, test/tests.zig
Observed to ~randomly crash during FP-based unwinding.
The path forward here will be DWARF-based unwinding.
=> `std.debug`: disable stack traces on loongarch

lib/std/fs/File.zig, lib/std/fs/test.zig
Fixes #25080.
The `std.fs.File.Writer`'s `seekTo` now flushes to ensure buffered data is written appropriately.
A consequence is that `seekTo` now must also be able to respond with any error that occurred during the flush. In the style of `std.fs.File.Reader` I introduced `Writer.SeekError` which keeps the original `File.SeekError` but also includes `std.Io.Writer.Error`. 
Expanding the possible errors introduced an issue with `moveToReader`. The possible errors for the `seek_err` of a writer is no longer compatible with the reader. The writer set includes additional members not present in the reader set. There would seem to be three possible solutions.
1. Do not expand the possible seek errors for the writer and have a flush failure return an existing member, say `UnexpectedError`. 
2. …
=> fix: std.fs.File.Writer.seekTo does not flush

lib/std/c.zig, lib/std/c/dragonfly.zig, lib/std/c/solaris.zig, lib/std/os/linux.zig
Previously we had a single definition of std.c.cmsghdr for all libc-linking platforms which aliased from the Solaris definition, a superfluous matching one in std.os.dragonfly, and no others.
The existing definition from std.c didn't actually work for Linux, as Linux's "len" field is usize in the kernel's definition.
Emscripten follows the Linux model of course (but uses the binary-compatible musl definition, which has an endian-sensitive padding scheme to make the len type "socklen_t" even though the kernel uses a usize, which is fair).
This unifies and documents all the known *nix-ish cases (I'm not sure if wasi or windows really has cmsghdr support? Could be added later, void for now), such that c.cmsghdr and posix.system.cmsghdr should work correctly for all the known cases here, libc …
=> Fix cmsghdr struct for the *nixes

lib/std/zig/llvm/BitcodeReader.zig
Call start/endBlock before/after `parseBlockInfoBlock` in order to not use the current block context, which is wrong and leads to e.g. incorrect abbrevlen being used.
Fixes #24998
=> BitcodeReader: parse blockinfo inside block

lib/std/fmt.zig, lib/std/simd.zig, test/behavior/vector.zig
#4486 and #22060 seem to be fixed by LLVM. I have run all relevant tests using qemu, it would be great if someone else could also confirm (since I don't think we have armeb/thumbeb CI).
closes #4486
closes #22060
=> Reenable failing vector tests

lib/std/http/Client.zig
unused since 5ce8e9325b7aa15cbcc77221fc7075b6c46619cc
=> remove ResponseStorage

doc/langref.html.in, doc/langref/test_vector.zig, lib/std/debug.zig, lib/std/mem.zig, src/Sema.zig, test/behavior/cast.zig, test/behavior/union.zig, test/behavior/vector.zig, test/cases/compile_errors/in_memory_coerce_vector_to_array.zig
closes #25172
If you were using `@ptrCast` to convert between array memory and vector memory, use coercion instead.
If you were coercing from `anyerror![4]i32` to `anyerror!@Vector(4, i32)` or similar, you need to unwrap the error first.
=> frontend: vectors and arrays no longer support in-memory coercion

lib/std/Io/Writer.zig, src/link/Coff.zig, src/link/Elf.zig, src/link/Elf/eh_frame.zig, src/link/Elf/relocatable.zig, src/link/Elf/synthetic_sections.zig, src/link/MachO.zig, src/link/MachO/DebugSymbols.zig, src/link/MachO/UnwindInfo.zig, src/link/MachO/relocatable.zig, src/link/SpirV.zig
missing `extern` on a struct.
but also all these instances that call pwriteAll with a `@ptrCast` are endianness bugs.
this should be changed to use File.Writer and call writeSliceEndian instead.
this commit fixes one immediate problem but does not fix everything.
=> fix linker writing undefined memory to output file

doc/langref/destructuring_block.zig
The output for example 'Destructuring Tuples' was `min = 0max = 9` on a single line, now minimum and maximum are each on their own line.
=> langref: added missing newlines to destructuring tuples example

src/Sema.zig, src/Zcu.zig, src/Zcu/PerThread.zig, test/cases/export_from_body_of_coerced_fn.zig
This bug was manifesting for a user as a nasty link error because they were calling their application's main entry point as a coerced function, which essentially broke reference tracking for the entire ZCU, causing exported symbols to silently not get exported.
I've been a little unsure about how coerced functions should interact with the unit graph before, but the solution is actually really obvious now: they shouldn't! `Sema` is now responsible for unwrapping possibly-coerced functions *before* queuing analysis or marking unit references. This makes the reference graph optimal (there are no redundant edges representing coerced versions of the same function) and simplifies logic elsewhere at the expense of just a few lines in Sema.
The test is a test case rather than a behavior test to …
=> frontend: fix reference tracking through coerced function bodies

lib/std/crypto/25519/ed25519.zig
In ed25519.zig, we checked if a test succeeds, in which case we returned an error. This was confusing, and Andrew pointed out that Zig weights branches against errors by default.
=> Avoid logic where we return success in case of an error

lib/std/crypto.zig, lib/std/crypto/ascon.zig, lib/std/crypto/benchmark.zig
Ascon is the family of cryptographic constructions standardized by NIST for lightweight cryptography.
The Zig standard library already included the Ascon permutation itself, but higher-level constructions built on top of it were intentionally postponed until NIST released the final specification.
That specification has now been published as NIST SP 800-232: https://csrc.nist.gov/pubs/sp/800/232/final
With this publication, we can now confidently include these constructions in the standard library.
Also unbreak the benchmarks after the `deprecatedWriter()` removal.
=> std.crypto: add Ascon-AEAD, Ascon-Hash, Ascon-CHash

lib/std/c.zig, lib/std/c/darwin.zig, lib/std/c/dragonfly.zig, lib/std/c/freebsd.zig, lib/std/c/netbsd.zig, lib/std/c/openbsd.zig, lib/std/os/linux.zig, lib/std/posix.zig
Resolves #24982
First commit fixes a bug introduced by myself in #24921 by adding a missing `@enumFromInt` to the `std.posix.ptrace` `.darwin` prong. Also the `else` prong didn't really make sense there and wouldn't compile anyway as it was so I added explicit ptrace support for BSDs and compile errors for everything else.
Sources:
https://man7.org/linux/man-pages/man2/ptrace.2.html
https://man.dragonflybsd.org/?command=ptrace&section=2
https://man.freebsd.org/cgi/man.cgi?query=ptrace
https://man.netbsd.org/ptrace.2
https://man.openbsd.org/ptrace.2
https://github.com/SerenityOS/serenity/blob/502caef9a40bccc7459f9835f2174a601106299a/Userland/Libraries/LibC/sys/ptrace.h
https://docs.oracle.com/cd/E36784_01/html/E36874/ptrace-3c.html
https://smartos.org/man/3C/ptrace
(specifically the part …
=> std.*.ptrace: support more platforms and features more correctly

src/Type.zig, test/behavior/union.zig
=> fix handling of comptime-only union fields in `Type.getUnionLayout`

lib/std/fmt.zig, lib/std/fs.zig, lib/std/meta.zig, lib/std/os.zig, lib/std/posix.zig, lib/std/process/Child.zig
I noticed ``std.fmt.allocPrintSentinel`` and migrated ``bufPrintZ`` to ``bufPrintSentinel`` to match.
=> std.fmt: migrate bufPrintZ to bufPrintSentinel

lib/compiler/reduce.zig, lib/std/Random/benchmark.zig, lib/std/crypto/benchmark.zig, lib/std/hash/benchmark.zig, lib/std/log.zig, lib/std/unicode/throughput_test.zig
I tried to use `zig reduce` but it bitrot a bit since it used old `GenericWriter`. I went and updated it and some other tools to use new Writer.
Also Adler32 API changed so I also updated lib/std/hash/benchmark.zig to handle it properly just so I can test my changes with Writer.
=> Fix tools by removing usages of deprecatedWriter.

lib/std/c.zig
Contributes to #24997 
There might be other issues, but at the very least, this defines the ``MSG`` struct for dragonfly.
Based on
https://gitweb.dragonflybsd.org/?p=dragonfly.git;a=blob_plain;f=sys/sys/socket.h;hb=HEAD
=> std.c: add MSG support for dragonfly

test/behavior/fn.zig, test/tests.zig
This clarifies that it is legal to return an invalid pointer from a function, provided that such pointer is not dereferenced. It is the missing behavior test coverage for #5725.
This matches current status quo of the language. Any change to this should be a proposal that argues for different (breaking!) semantics.
Related:
* #3180
=> add behavior test: returning undefined pointer from function

lib/std/Io/Reader.zig
If `r.end` is updated in the `stream` implementation, then it's possible that `r.end += ...` will behave unexpectedly. What seems to happen is that it reverts back to its value before the function call and then the increment happens. Here's a reproduction (adapted from [here](https://ziggit.dev/t/im-too-dumb-for-zigs-new-io-interface/11645/76)):
```zig
test "fill when stream modifies `end` and returns 0" {
var buf: [3]u8 = undefined;
var zero_reader = infiniteZeroes(&buf);
_ = try zero_reader.fill(1);
try std.testing.expectEqual(buf.len, zero_reader.end);
}
pub fn infiniteZeroes(buf: []u8) std.Io.Reader {
return .{
.vtable = &.{
.stream = stream,
},
.buffer = buf,
.end = 0,
.seek = 0,
};
}
fn stream(r: *std.Io.Reader, _: *std.Io.Writer, _: std.Io.Limit) std.Io.Reader.StreamError!usize { …
```
=> Reader.defaultReadVec: Workaround bad `r.end += r.vtable.stream()` behavior

src/codegen/aarch64/Assemble.zig
Elements are computed at comptime, so don't declare them as "var".
=> aarch64 backend / zonCast: don't return a pointer to a stack element

lib/std/pie.zig, test/cases/pie_linux.zig
If the compiler happens to pick `ret = r0`, then this will assemble to `ag r0, 0` which is obviously not what we want. Using `a` instead of `r` will ensure that we get an appropriate address register, i.e. `r1` through `r15`.
Re-enable `pie_linux` for `s390x-linux` which was disabled in ed7ff0b693037078f451a7c6c1124611060f4892.
=> `std.pie`: fix register constraint in `getDynamicSymbol()` for s390x

lib/std/process/Child.zig
In a library, the two `builtin.link_libc` and `builtin.output_mode == .Exe` checks could both be false. Thus, you would get a compile error even if you specified an `env_map` at runtime. This change turns the compile error into a runtime panic and updates the documentation to reflect the runtime requirement.
I tested this locally with the following library/executable setup:
```
zig init -m
```
```zig
// build.zig
const target = b.standardTargetOptions(.{});
const optimize = b.standardOptimizeOption(.{});
const echo = b.addLibrary(.{
.name = "echo",
.root_module = b.createModule(.{
.root_source_file = b.path("echo.zig"),
.optimize = optimize,
.link_libc = false, // just to be sure
}),
}); …
```
=> std: fix spawning processes from libraries with env map

build.zig, test/libc.zig, test/src/Libc.zig, test/tests.zig
You can run the [libc-test](https://wiki.musl-libc.org/libc-test) cases with:
```
zig build test-libc -Dlibc-test-path=/path/to/libc-test
```
`/path/to/libc-test` is the path to a clone of `git://nsz.repo.hu:49100/repo/libc-test` ([repo website](http://nsz.repo.hu/git/?p=libc-test)).
I originally wanted to include windows targets, but I decided against it, because too many test cases seemed linux dependent. I instead suggest integrating [test cases of mingw](https://github.com/mstorsjo/llvm-mingw) into the build system in a follow-up PR.
The [test suite of wasi-libc](https://github.com/WebAssembly/wasi-libc/tree/008d705c9d16dc9057bb6efc220fb539f1fb7fb5/test) contains tests from libc-test (included in this PR) and other tests (maybe in a follow-up PR).
libc-test also includes math tests, …
=> Integrate libc-test cases into the build system

test/libc.zig
It's flaky in that systems with a high FD limit will get an unexpected `ENOMEM` error from `daemon()`, failing the test.
=> `libc-test`: disable `daemon-failure.c`

lib/std/mem.zig, src/main.zig
1. Introduce cut functions: `cut`, `cutPrefix`, `cutSuffix`, `cutScalar`, `cutLast`, `cutLastScalar`
2. Moving towards our function naming convention of having one word per concept and constructing function names out of concatenated concepts.
In `std.mem` the concepts are:
* "find" - return index of substring
* "pos" - starting index parameter
* "last" - search from the end
* "linear" - simple for loop rather than fancy algo
* "scalar" - substring is a single element
=> std.mem: introduce cut functions; rename "index of" to "find"

lib/compiler/build_runner.zig, lib/compiler/test_runner.zig, lib/fuzzer.zig, lib/std/Build/Fuzz.zig, lib/std/Build/Step/Run.zig, lib/std/Build/WebServer.zig, lib/std/Build/abi.zig, lib/std/zig/Client.zig, lib/std/zig/Server.zig, src/Compilation.zig, test/standalone/libfuzzer/main.zig
Adds the limit option to `--fuzz`. the limit expresses a number of iterations that *each fuzz test* will perform at maximum before exiting. The limit argument supports also 'K', 'M', and 'G' suffixes (e.g. '10K').
Does not imply `--webui` (like unlimited fuzzing does) and prints a fuzzing report at the end.
Closes #22900 but does not implement the time based limit, as after internal discussions we concluded to be problematic to both implement and use correctly.
=> fuzzing: implement limited fuzzing

lib/libc/musl/src/fenv/loongarch64/fenv-sf.c, src/libs/musl.zig
https://www.openwall.com/lists/musl/2025/09/27/1
closes #25367
=> `musl`: add missing fenv C dummy functions for `loongarch64-linux-muslsf`

src/Package/Fetch.zig
Before, this had a subtle ordering bug where duplicate deps that are specified as both lazy and eager in different parts of the dependency tree end up not getting fetched depending on the order they're fetched in. I modified it to resubmit lazy deps that were promoted to eager for fetching so that it will be around for the builds that expect it to be eager downstream of this.
This should fix https://github.com/ziglang/zig/issues/23120
=> Fix zig build lazy -> eager promotion while fetching dependencies.

src/translate_c.zig, test/cases/translate_c/tenary_in_macro.c, test/translate_c.zig
https://github.com/ziglang/zig/pull/24664 cherrypicked for 0.15.x
=> translate_c: fix ternary operator output in C macros

lib/std/debug.zig
This just needs to do the same thing as `powerpc64le`. Note that the saved LR is at the same position in both ELF v1 and v2.
=> `std.debug`: fix FP-based unwinding on `powerpc64`

lib/std/debug.zig
The ABIs make this safe and reliable due to their backchain requirements.
=> `std.debug`: consider FP-based unwinding on hexagon and powerpc safe

lib/std/crypto/25519/ed25519.zig
closes #25444
https://github.com/novifinancial/ed25519-speccheck/blob/65519336fda78a3d016e947df6d82848aca0c9da/cases.txt#L25
seems to me like it was just an accidental typo when copying it over, letters are shifted by one
=> correct ed25519 test case

lib/std/c/freebsd.zig
[see this Ziggit thread](https://ziggit.dev/t/core-dump-on-freebsd-when-using-streamremaining/12333?u=rpkak)
What I think happens here is that `streamRemaining` uses `sendFile`, which tries to use `copy_file_range` but fails because the output is not seekable.
https://github.com/ziglang/zig/blob/07c3f9ef8e0a5a557dce70322334b0d1b49fe154/lib/std/os/freebsd.zig#L36-L50
Because `copy_file_range` returns `usize` (this is changed by this PR), `rc` is not `-1`, but `0xffffffffffffffff` on error. This is returned as success because `errno(rc)` compares `rc` with `-1`. `sendFile` changes `w.pos` to `0xffffffffffffffff` and the next time `streamRemaining` calls `sendFile`, `@intCast(file_reader.pos)` panics.
This is untested by me because I don't use freebsd, but the OP of the [Ziggit …
=> Change the return type of copy_file_range to isize on freebsd

src/libs/libcxx.zig
closes https://github.com/ziglang/zig/issues/25455
=> `libcxx`: stop defining `_LIBCPP_ENABLE_CXX17_REMOVED_UNEXPECTED_FUNCTIONS`

src/Compilation.zig, src/InternPool.zig, src/Value.zig, src/Zcu.zig, src/Zcu/PerThread.zig
Building the compiler with `-Ddev=cbe`:
```
Benchmark 1 (58 runs): master/bin/zig build-exe ...
wall_time          2.09s  ± 7.58ms    2.07s  … 2.12s           2 ( 3%)        0%
peak_rss            609MB ± 5.82MB     589MB …  619MB          1 ( 2%)        0%
cpu_cycles         22.0G  ± 60.0M     21.9G  … 22.1G           0 ( 0%)        0%
instructions       47.6G  ± 5.30M     47.6G  … 47.6G           2 ( 3%)        0%
cache_references   2.15G  ± 10.5M     2.12G  … 2.17G           0 ( 0%)        0%
cache_misses        106M  ± 1.61M      103M  …  110M           0 ( 0%)        0%
branch_misses       114M  ±  605K      113M  …  116M           1 ( 2%)        0%
Benchmark 2 (58 runs): 25384/bin/zig build-exe ... …
```
=> InternPool: use sequential string indices instead of byte offsets

lib/std/debug.zig, lib/std/debug/SelfInfo/Elf.zig
The DWARF code can't handle these yet.
ref https://github.com/ziglang/zig/issues/25447
=> `std.debug.SelfInfo.Elf`: disable unwinding on mips n32 and x86 x32

lib/std/Target.zig, src/target.zig, test/tests.zig
* ELF v1 on powerpc64 is only barely kept on life support in a couple of Linux distros. I don't anticipate that this will last much longer.
* Most of the Linux world has moved to powerpc64le which requires ELF v2.
* Some Linux distros have even started supporting powerpc64 with ELF v2.
* The BSD world has long since moved to ELF v2.
* We have no actual linking support for ELF v1.
* ELF v1 had confused DWARF register mappings which is becoming a problem in our DWARF code in std.debug.
It's clear that ELF v1 is on its way out, and we never fully supported it anyway. So let's not waste any time or energy on it going forward.
closes #5927
=> drop support for powerpc64 ELF v1

lib/std/mem.zig
`findScalarPos` might do repetitive work, even if using simd. For example, when searching the string `/abcde/fghijk/lm` for the character `/`, a 16-byte wide search would yield `1000001000000100` but would only count the first `1` and re-search the remaining of the string.
When testing locally, the difference was quite significative:
```
count scalar
5737 iterations       522.83us per iterations
0 bytes per iteration
worst: 2370us median: 512us   stddev: 107.64us
count v2
38333 iterations      78.03us per iterations
0 bytes per iteration
worst: 713us  median: 76us    stddev: 10.62us
count scalar v2
99565 iterations      29.80us per iterations
0 bytes per iteration
worst: 41us   median: 29us    stddev: 1.04us
```
Note that `count v2` is a simpler string search, similar to the remaining …
=> perf: Refactor countScalar to benefit from simd

lib/std/Io/Reader/Limited.zig
Fixes #25093
`Reader.Limited.stream` was incorrectly relying on the underlying stream to report `error.EndOfStream` when reading 0 bytes. This worked by chance in existing unit tests -- they have fixed size sources and use `Reader.fixed()` with its underlying `endingStream`, which happens to return `error.EndOfStream` on *any* read.
But this behaviour is incorrect; `Reader.Limited` shouldn't perform any reads once its limit is reached. Fix this, and add a test with an infinite source stream.
=> Fix infinite loop in Reader.Limited

src/Sema.zig, test/behavior/tuple.zig
=> don't make anonymous tuple fields referencing `comptime var`s `comptime`

lib/std/Build.zig
=> std.Build: duplicate sub_path for LazyPath's dependency variant
