ziglang/zig

src/stage1/analyze.cpp
src/stage1/codegen.cpp
src/stage1/ir.cpp
src/translate_c.zig
test/stage1/behavior/error.zig
test/translate_c.zig

some fixes

---

lib/std/io/reader.zig

The current API does not allow the user to distinguish between EOF and
an empty line. Reader.readUntilDelimiterOrEof() gets this API right so
update readUntilDelimiterOrEofAlloc() to match it. Returning an optional
here additionally makes calling this in a loop much cleaner.
Remove readUntilDelimiterOrEofArrayList() as it no longer needed to
implement readUntilDelimiterOrEof() and has the same API issues
described without a clear way to fix them.
Closes #7581

std: fix Reader.readUntilDelimiterOrEofAlloc() API

---

lib/std/os/bits/freebsd.zig

std: Add more standard type definitions for FreeBSD

---

src/stage1/util.hpp

This should fix #7614 or part of it.

stage1: Remove stray brace in rarely-tested code path

---

src/codegen.zig
src/codegen/arm.zig
test/stage2/arm.zig

Add conditional branching to the stage2 ARM backend.
TODO:

stage2 ARM: add conditional branches

---

src/stage1/os.cpp

See https://github.com/ziglang/zig/issues/7614#issuecomment-752939981.

Fix ssize_t definition

---

src/codegen.zig
src/codegen/aarch64.zig

As always, this will initially be a draft pull request.
cc @kubkon

stage2 AArch64: logicalShiftedRegister

---

src/codegen.zig

This fixes two issues related to address offset calculation.

stage2 ARM: fix 2 bugs

---

lib/std/fs/watch.zig
lib/std/os/bits/freebsd.zig
lib/std/os/windows.zig
lib/std/os/windows/bits.zig
lib/std/os/windows/kernel32.zig

Current progress: 
Closes #5304

The std.fs.Watch rewrite PR

---

src/stage1/ir.cpp

stage1: Resolve alignment earlier in @alignCast

---

lib/std/os/bits/windows.zig
lib/std/os/windows.zig

This fixes a regression with poll() on windows.

define nfds_t for windows

---

lib/std/os.zig

I've observed this errno occurring on Linux.

add missing ECONNRESET from getsockoptError

---

src/Module.zig
src/codegen.zig
src/link/Coff.zig
src/link/Elf.zig
src/link/MachO.zig
src/link/Wasm.zig

This commit lays the groundwork in preparation for implementing
handling of extern functions in various backends.

stage2: lay the groundwork in prep for extern fn

---

src/link/MachO.zig
src/link/MachO/CodeSignature.zig

It turns out I was wrong and we can set the page size to the actual
page size used by the target architecture when dividing the binary
into chunks and calculating a hash of each chunk for embedding within
the adhoc code signature. This shaves of a considerable amount of bytes
since we divide the code signature section by at least 2x.
I've also unified the `write` interface of `CodeSignature` struct to
follow that used in every other bit of `MachO`; namely, the functions
now accept a writer instead of a buffer, therefore, there is no need
to manually track where to write each struct field anymore.

macho: use target architecture page size in code signature calculation

---

src/codegen.zig
src/codegen/aarch64.zig

This also adds some extra type safety to `LdrArgs` in `codegen/aarch64.zig`.
cc @kubkon

stage2 AArch64: add very basic return values

---

src/codegen.zig
src/codegen/arm.zig

We need to add a type argument to `genSetReg` in order to actually use `ldrh` (I'm working on that already), but after this PR, `strh` can already be used to store variables of type `u16` to the stack.

stage2 ARM: add extra load/store instructions

---

src/codegen.zig
src/link/MachO.zig
src/link/MachO/imports.zig

Now, we don't erroneously write to the string table on every
write of global and undef symbols.

macho: refactor undef symbol handling

---

src/codegen.zig
src/codegen/aarch64.zig

Fixes the offsets of `str` instructions created by `genSetStack`. This PR also implements reserving stack space for functions.
cc @kubkon

Stage2 AArch64: Fix genSetStack

---

lib/std/c.zig
lib/std/c/dragonfly.zig
lib/std/c/freebsd.zig
lib/std/c/linux.zig
lib/std/c/netbsd.zig
lib/std/c/openbsd.zig
lib/std/os.zig

Use both F_SETFD and F_SETFL depending on what flag we're setting.
Closes #7760

std: Fixed pipe2 fallback

---

src/codegen.zig

This is low-hanging fruit, but I might as well just implement it now (even though loops are not implemented yet).

stage2 AArch64: implement jump

---

lib/std/os/windows.zig

windows: make sure to handle PATH_NOT_FOUND when deleting files

---

src/stage1/softfloat.hpp

On big-endian hosts, zig_f128_isNaN() takes the high and low halves
from the wrong element, resulting in buggy NaN detection behavior.
This fixes it.

stage1: Fix f128 NaN check on sparc64

---

lib/std/mem.zig

Hi, I triggered integer overflow when calling joinZ with an empty slices.
```zig
const str = try joinZ(testing.allocator, ",", &[_][]const u8{});
```
This should fix the problem.

Fix integer overflow when calling joinZ with empty slices

---

lib/std/meta.zig

@Srekel was running into some missing cases in `std.meta.sizeof`, specifically for string literals.  I filled in some more cases for it.  Since we don't actually have enough information at this level to correctly figure out how C's sizeof would behave in all cases, it has to guess a bit.  But until translate-c is smart enough to do this correctly without deferring to a helper, we will always have this problem.  Zig's type system just can't encode these things in the way that is needed to exactly match C.

Fill out more cases for std.meta.sizeof

---

lib/std/fmt.zig

Improve error messages in std.fmt

---

lib/std/build.zig

Seems like a good idea for consistency.

std: Add "_FromWriteFileStep" for all the remaining LibExeObjStep types

---

lib/std/json.zig

std.json support for comptime fields

---

lib/std/multi_array_list.zig
lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig

This is a PR against the branch of #7920.
I'm not quite finished with this, I intend to complete the porting of array and struct initialization today. Opening an early draft though to hopefully stave off duplicated effort if others are also working on this.

zig fmt: help finish the rework

---

lib/std/zig/ast.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig

More progress for #7920.
I'll continue working on zig fmt and add more incremental commits to this branch if it has not yet been merged.

zig fmt: array types

---

src/codegen.zig

Previously, this would reuse an operand even if `reuseOperand` returned false for both operands.
`genArmBinOpCode` was also changed to be more Three-address code oriented in the process.

stage2 ARM: fix register allocation in genArmBinOp

---

src/Compilation.zig

macos: fix cond to enable ZIG_SYSTEM_LINKER_HACK

---

lib/std/os/bits/linux/arm-eabi.zig
lib/std/os/bits/linux/arm64.zig
lib/std/os/bits/linux/i386.zig
lib/std/os/bits/linux/mips.zig
lib/std/os/bits/linux/powerpc64.zig
lib/std/os/bits/linux/riscv64.zig
lib/std/os/bits/linux/sparc64.zig
lib/std/os/bits/linux/x86_64.zig

Add epoll_pwait2 Linux syscall

---

lib/std/event/loop.zig

I frequently hit this race condition with evented networking on linux.
Thread 1: suspends coroutine, adds fd to epoll
Thread 2: resumes coroutine, need_to_delete is still false, linuxRemoveFd does not get called
Thread 1: sets need_to_delete to true, but fd stays in epoll, and the following call to linuxWaitFd will fail
This simple fix is to invert the logic for need_to_delete.

fix race condition in linuxWaitFd

---

lib/std/os/uefi.zig

* At some point `format` stopped compiling—fix this. Also rename `out_stream` parameter to `writer`.
* Add an `eql` method.

std.os.uefi.Guid fixes

---

src/codegen.zig

This adds a new argument `ty: Type` to the `genSetReg` function in `codegen.zig`. This is necessary in order to generate the appropriate code for storing `u8`, `u16` or `u32` in ARM-registers for example.

stage2 codegen: Add Type argument to genSetReg

---

lib/std/buf_set.zig
lib/std/build.zig
lib/std/hash_map.zig
lib/std/json.zig
lib/std/json/write_stream.zig
lib/std/priority_queue.zig
src/link/Elf.zig
src/link/MachO/DebugSymbols.zig
src/liveness.zig
src/translate_c.zig
tools/update_glibc.zig

Should assigning `void` to `_` be a compile error? obviously this is a mistake people make...

HashMap.put returns !void, not a !bool

---

lib/std/crypto/benchmark.zig

Use the s formatter to format strings.

std/crypto/benchmark: update format strings

---

lib/std/fs/path.zig

Similar to mem.join and mem.joinZ.

std: Add std.fs.path.joinZ

---

lib/std/zig/parse.zig
lib/std/zig/parser_test.zig

parser: fix infinite loop on missing comma in param list

---

test/stage1/behavior/vector.zig

- consolidate into single code block
See #8130
See #8131

disable failing behavior tests with llvm 12

---

lib/std/c/tokenizer.zig
lib/std/multi_array_list.zig
test/run_translated_c.zig

fix c tokenizer giving invalid integer literals

---

lib/std/multi_array_list.zig

Previously calling `ensureCapacity` on empty list would not free the previously allocated bytes.

Std: fix memory leak in MultiArrayList

---

lib/std/zig/ast.zig
lib/std/zig/parser_test.zig

zig fmt: fix lastToken() for container_decl_arg

---

doc/docgen.zig

I'm looking into adding a feature to docgen.zig (see https://github.com/ziglang/zig/pull/8080 ), and the code tests are the overwhelming majority of the runtime of this program. In order to make developing unrelated features more convenient, I added a `--skip-code-tests` optional parameter to the CLI.
The CLI ergonomics are atrocious compared to python argparse, but I'm not really introducing any regression in this PR.

add a --skip-code-tests option to docgen.zig

---

lib/std/elf.zig
src/link/Elf.zig

move to std.elf and also add test

stage2 Elf linker: fill in bswapAllFields

---

src/glibc.zig
src/link/Elf.zig

Refer to the individual commit messages.
See also #4927.

Two fixes for MIPS targets

---

src/codegen.zig
src/ir.zig
src/zir.zig
src/zir_sema.zig

Code generation for the wrapping instructions is not implemented yet.

stage2 tzir: Add wrapping integer arithmetic instructions

---

lib/std/multi_array_list.zig

std: Handle empty MultiArrayList in items()

---

lib/std/Thread.zig
lib/std/c.zig
lib/std/io/c_writer.zig
lib/std/os.zig

while here, adjust std.os.unexpectedErrno()

make std.c.getErrno() return same type as _errno() aka c_int

---

lib/std/os/linux/io_uring.zig

liburing commit: https://github.com/axboe/liburing/commit/1bafb3ce5f5eeb11cd982c7540f6aa74e3f381d4
As stated in the liburing commit message, this fixes a regression,
reverting code that was added specutively to avoid a syscall in some
cases.

std/linux: sync io_uring library with liburing

---

src/link/MachO.zig

lld: handle error instead of abort

---

doc/docgen.zig

Really slow as usual but now looks slightly better.

docgen: Use Progress API

---

lib/std/os.zig

std: make all errors in os.zig public

---

lib/std/meta.zig
src/translate_c.zig

Together with #8126, this should fix #4479.

translate-c: improve std.meta.cast

---

lib/std/fs/path.zig

Add tests for at least triggering the build.

std: Fix std.fs.path.joinZ

---

src/translate_c.zig
test/run_translated_c.zig
test/translate_c.zig

translate-c: preserve zero fractional part in float literals

---

src/astgen.zig

this was pretty low hanging fruit

zir-memory-layout: astgen: literals and *, &

---

src/Compilation.zig

Some runaways after recent `std.fmt` module updates.

Fix digest format specifier after std.fmt updates

---

src/Sema.zig
src/astgen.zig

I'm unsure about the `LazySrcLoc` of `analyzeBlockBody`. I just set it to `.{ .node_offset = 0 }` for the time being.

astgen: implement typeof

---

src/astgen.zig
test/stage2/llvm.zig

this big boi test passes (expect for one line: `var val3_var = opt_val orelse 30;`, which i think has something to do with `.alloc_inferred_mut`):
https://github.com/ziglang/zig/blob/749c3f014ba36a6dc824419f835790f9c181aad3/test/stage2/llvm.zig#L140-L181

astgen: implement orelse

---

src/Module.zig
src/astgen.zig
test/stage2/llvm.zig

This gets us down to only one failing test for the LLVM backend, which is the for loops test.

astgen: implement breaking from a block

---

lib/std/zig/system/x86.zig

std: Detect AMD Zen3 CPU family

---

ci/azure/windows_msvc_install

Hopefully, fixes our latest Win CI failures.

azure: run pacman with -Sy

---

lib/std/array_hash_map.zig

The following test fails with an out-of-bounds exception. The exception is triggered when an array hash map's capacity is expanded multiple times, subsequently followed by a pop(). The subsequent pop() attempts to access the map's entries slice which is shrunk by pop() calling entries.pop(). The fix is to delay the decrement of the entries slice length to be at the end of pop().
```zig
test "pop" {
var map = AutoArrayHashMap(i32, i32).init(std.testing.allocator);
defer map.deinit();
// Insert just enough entries so that the map expands. Afterwards,
// pop all entries out of the map.
var i: i32 = 0;
while (i < 9) : (i += 1) {
testing.expect((try map.fetchPut(i, i)) == null);
}
while (i > 0) : (i -= 1) {
const pop = map.pop();
testing.expect(pop.key == i - 1 and pop.value == i - 1);
}
}
``` …

array_hash_map: decrement entries slice len after popping from entries in pop() to prevent oob

---

src/Sema.zig
test/stage2/cbe.zig

Lets go! (The optional one was already commented out)

stage2: cbe: restore all previously passing tests!

---

src/stage1/analyze.cpp

put llvm_type for an fnframe in the correct addrspace

---

src/codegen.zig
src/codegen/aarch64.zig

stage2 AArch64: Add ldrh and ldrb instructions

---

lib/std/c/netbsd.zig
lib/std/os/bits/netbsd.zig

- netbsd 9.1 amd64
- no testing done but basic stuff works

netbsd: minor fixes to allow stage1 to build

---

lib/std/meta.zig

translate-c: fix meta.cast to ?*c_void

---

src/codegen/aarch64.zig
src/link/MachO.zig
src/link/MachO/Zld.zig

stage2 AArch64: Add conditional branch instructions

---

lib/std/testing.zig

No functional changes (hopefully)

Minor std.testing fixes

---

lib/std/os/linux/tls.zig
lib/std/special/c.zig
lib/std/special/compiler_rt.zig
test/stage1/behavior/bugs/920.zig
test/stage1/behavior/cast.zig

Complements #8483 
cc @fengb 
Do you have a real PPC machine to run the test suite on? I find it weird that `920.zig` is accumulating so much error in between the calculations.

Improve Improve PowerPC support

---

lib/std/special/docs/main.js

std docs: @This() in generic types

---

src/register_manager.zig

This is the first step towards generating correct register spilling code when all registers are allocated and more than one register is required.

stage2 register manager: Add functions for allocating multiple registers

---

src/Compilation.zig

stage2: add support for zig cc assembler -mcpu option

---

lib/std/fmt.zig

Sorry for not thinking of this case. 
/cc @LemonBoy

std: fix potential bug in parseInt

---

lib/std/atomic/bool.zig
lib/std/atomic/int.zig

As `@atomicLoad` takes const pointers

std.atomic.Bool/Int.load should take const pointer to Self

---

doc/langref.html.in
lib/std/event/rwlock.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig
src/stage1/ir.cpp
src/stage1/parser.cpp
test/compile_errors.zig
test/runtime_safety.zig
test/stage1/behavior/async_fn.zig

stage1: Require a block after suspend

---

lib/std/crypto/25519/ed25519.zig
lib/std/crypto/25519/edwards25519.zig

This makes single signature verification about 60% faster.
Also check that R is not the identity point.

ed25519: use double-base multiplication for signature verification

---

lib/std/os/linux/bpf/btf.zig

fix import path

---

lib/std/Thread.zig

std: Fix thread creation with field-less context type

---

ci/drone/linux_script_test
lib/std/meta.zig
src/stage1/analyze.cpp
src/stage1/analyze.hpp
src/stage1/ir.cpp
src/stage1/target.cpp
src/stage1/target.hpp
src/translate_c.zig
src/translate_c/ast.zig
test/compile_errors.zig
test/stage1/behavior/type_info.zig
test/translate_c.zig

Refer to the single commits for more details.
Not sure how much of this is also needed in the stage2 compiler.
Fixes #8537

Function pointer alignment

---

lib/std/mem.zig

When two 'needle' values are adjacent in the 'input' slice, the size is not
counted correctly. The 2nd 'needle' value is not matched because the index is
incremented by one after changing the index to account for the first value.
The impact is that the size returned is incorrect, which could cause UB when this
size is used as the size of the output buffer passed to std.mem.replace.

#8454 Fix for std.mem.replacementSize adjacent matches bug.

---

lib/std/crypto/utils.zig

A little function to complement the existing `crypto.utils.timingSafeEql()` function with a way to compare large numbers serialized as arrays.
This is useful to compare nonces and to check that group elements are in canonical form.
Absence of side channels remains a best effort, reusing the common pattern we use elsewhere.

Add std.crypto.utils.timingSafeCompare

---

lib/std/zig/system/linux.zig

Untested but should work well on both 32 and 64 bit systems.

stage1: Implement CPU host detection for PowerPC targets

---

doc/langref.html.in

Update doc after 5079d11b213a02e9d9465f3371d0833021cfc636 .

Doc: zig-cache/bin -> zig-out/bin

---

lib/std/array_list.zig

Do not impose the internal alignment requirements to the user-supplied
parameters.
Closes #8647

std: Accept unaligned slice in several ArrayListAligned ops

---

lib/std/fmt.zig

The results have been cross-checked with LLVM's APFloat implementation
by randomly sampling the f32/f64 space, while the f16 one was completely
checked given the small size.

std: Implement hex float printing

---

src/translate_c.zig
test/run_translated_c.zig

@Vexu can you verify this is correct?
This should fix #8707.

translate-c: fix typedefs with multiple names

---

lib/std/os/bits/openbsd.zig
lib/std/target.zig
lib/std/zig/system.zig

- netbsd, dragonly: use sysctlbyname
- openbsd: use sysctl
- updated default semver ranges

bsd: detect os version

---

src/Compilation.zig

stage2: make failure to find native libc verbose

---

lib/std/os.zig

encountered this error code on my NixOS machine

add missing EBADF error code for openat

---

ci/azure/linux_script

- apply patch for qemu-user syscall do_sendrecvmsg_locked
- see #8750

ci linux: bump qemu-5.2.0.1

---

src/Compilation.zig

We do need to link the system libc if linking system libraries as
they may potentially be compiled against e.g. a newer glibc version
than zig can provide. However if not linking system libraries, using
the zig provided libc is more reliable as it does not depend on any
quirks of the host system or being able to invoke the system cc to
find include dirs.

stage2: only default to linking system libc if linking system libs

---

lib/std/crypto/tlcsprng.zig

Some TLCSPRNG fixes

---

lib/std/mem.zig

Currently, `indexOfPos` and `lastIndexOf` are broken when the Boyer-Moore-Horspool algorithm is used for types larger than a byte. In this case, `haystack` and `needle` are first cast from slices of `T` to slices of `u8` before a BMH search is run. This is fine, but returned indices are not adjusted from byte positions back to element positions. Further, matches are not checked for alignment with the original elements, so false positives can occur. For example, one a little-endian machine:
```
// make large enough to trigger BMH algorithm
const haystack = [1]u16{0} ** 50 ++ [_]u16 { 0xbbaa, 0xccbb, 0xddcc, 0xeedd, 0xffee, 0x00ff };
const needle0 = [_]u16{ 0xbbaa, 0xccbb, 0xddcc, 0xeedd, 0xffee };
assert(mem.indexOfPos(u16, &haystack, 0, &needle0) == 100); // oops, not 50 because byte …
```

fix Boyer-Moore-Horspool algorithm in indexOfPos and lastIndexOf when element type is larger than a byte

---

src/AstGen.zig
test/stage2/test.zig

stage2: astgen error for return or try in defer block

---

lib/std/zig/parse.zig

The "permanent" data allocated by `Parser` during parsing is done through the two large, shared `ArrayList` instances, `nodes` and `extra_data`. This certainly reduces the number of separate allocations as compared to naively allocating nodes one at time. Unfortunately, parsing functions also need to collect variable-length lists of nodes. This cannot be done directly into `extra_data` because of the nesting of calls to other parsing functions that may need to do the same, breaking contiguity. Exhaustively, `parseContainerMembers` collects members, `parseBlock` collects statements, `parseCurlySuffixExpr` and `parsePrimaryTypeExpr` collect initializers, `parseSuffixExpr` collects suffix operator parameters, `expectAsmExpr` collects input and output items, `parseSwitchProng` collects case …

Use shared scratch buffer to avoid allocating and freeing many small lists in parse.zig

---

lib/std/os.zig

A follow up to the change that made the setrlimit error silent when trying to set the stack size to 16 MB (see https://github.com/ziglang/zig/commit/33a779c7f65b9eb5115253bfe1cf4f4ea86336af).
This supplementary change is necessary in order for Zig to catch the error and continue.

handle LimitToBig error on setrlimit

---

src/translate_c.zig
src/translate_c/ast.zig
test/translate_c.zig

Translate-c: support designated initializers in macros

---

src/link/MachO/Archive.zig
src/link/MachO/Object.zig
src/link/MachO/Zld.zig
src/link/MachO/reloc.zig

zld: fix the linker for 32bit comp targets

---

doc/langref.html.in

docs: minor spelling fix

---

doc/langref.html.in

Perhaps we should hold off on merging this until just before 0.8.0 in case there are further changes.

langref: sync grammar with zig-spec repo

---

lib/std/zig/parser_test.zig
lib/std/zig/render.zig

fmt: fix #8974

---

lib/std/crypto/utils.zig

This is useful to increment nonces and for scalar reduction.
It will avoid code duplication in crypto/25519 and crypto/pcurves/*

std.crypto: timing-safe functions to add&subtract serialized integers

---

src/stage1/codegen.cpp

Make sure to propagate the target-specific attributes to internal
functions too.
Closes #8965
Completely untested, @leecannon can you check if this PR works for you?

stage1: Apply the same set of fn attributes everywhere

---

lib/std/build.zig

I prefer the use of nullable types over setting the field to undefined and hoping that nothing else will try to read its value.
Closes #9013
Closes #8928
Closes #7991

build: Avoid using undefined variables

---

lib/std/fmt.zig

Skip the useless type name and the numeric field names.

std: Better formatting of tuple types

---

lib/std/build.zig

See #8963 for reasoning behind this.

Add linkLibCpp helper to LibExeObjStep

---

lib/std/math/sqrt.zig

I found a bug in the implementation of std.math.sqrt_int.
The implementation assumed the number of bits of the type was even.
I added some tests and fixed the bug.
I also added a shortcut for small number of bits to prevent edge cases.

std.math.sqrt_int: fixed odd size integers types

---

src/codegen.zig

Now `codegen.zig` only hosts targets which have registers (at least until `codegen.zig` will be refactored and split into separate files for different targets).

stage2 codegen: Remove hacks for discontinued SPU II backend

---

lib/std/fmt.zig
test/behavior/shuffle.zig
test/behavior/vector.zig

Re-enable multiple wasm32 vector tests

---

src/main.zig

Print path on libc/libc-path fatal error

---

src/link/MachO/Object.zig
src/link/MachO/Symbol.zig
src/link/MachO/Zld.zig
test/standalone.zig
test/standalone/link_common_symbols/a.c
test/standalone/link_common_symbols/b.c
test/standalone/link_common_symbols/build.zig
test/standalone/link_common_symbols/main.zig

Closes https://github.com/ziglang/zig/issues/8945
Short and sweet: this PR adds support for synthesising tentative definitions to `zig ld`.

zig ld: add common (tentative) symbols support

---

lib/std/math/tanh.zig

It turns out the code was not ported correctly from C and produced wrong
results for negative input values. As a bonus fix the NaN codepath by
adding yet another missing piece of code.
Spotted in #9047

std: Fix tanh for negative inputs

---

src/translate_c.zig
test/run_translated_c.zig
test/translate_c.zig

translate-c: fix enums that require c_uint type

---

lib/std/build.zig
lib/std/build/TranslateCStep.zig
test/src/compare_output.zig
test/tests.zig

Should have included this as a part of #7959 but whatever.

std.build: don't default to static linkage

---

lib/std/child_process.zig
lib/std/os/bits/darwin.zig
lib/std/os/bits/dragonfly.zig
lib/std/os/bits/freebsd.zig
lib/std/os/bits/haiku.zig
lib/std/os/bits/linux.zig
lib/std/os/bits/netbsd.zig
lib/std/os/bits/openbsd.zig

Child Process Exit Code

---

src/Sema.zig

This enables both operations at comptime and runtime (but it's not implemented in any codegen backend yet afaik)

stage2 Sema: enable float multiplication and division

---

test/standalone.zig
tools/gen_spirv_spec.zig
tools/process_headers.zig
tools/update_cpu_features.zig
tools/update_spirv_features.zig

Many tools were broken after the recent hash-table refactorings, fix
them and ensure they won't silently break again.

tools: Unbreak many tools

---

lib/std/build.zig
lib/std/special/build_runner.zig

closes #9017
supersedes #9018 
allows specifying full paths of where to install binaries, libraries and headers and so on
ifreund had suggested using a similar approach as meson and detecting what lib directory is available but since the default output directory is local I left that out

specify the output lib, exe and include paths with flags

---

src/Compilation.zig

Previously, Zig did not properly communicate the target CPU features for
RISC-V to clang assembler, because Clang has a different way to pass CPU
features for C code and for assembly code. This commit makes Zig pass a
RISC-V -march flag in order to communicate CPU features to Clang when
compiling assembly files.

fix RISC-V assembly CPU features

---

src/main.zig

This PR improves the linker args parsing for `zig cc`.

zig cc improvements

---

src/Compilation.zig

fix oob during riscv64 feature processing

---

src/main.zig

fmt: make --ast-check work with --stdin

---

lib/std/os.zig

* Avoid emitting the copy_file_range symbol at all to prevent link-time
errors.
* Fix a bug in the check logic, the has_copy_file_range_syscall was
set to the wrong value in case of ENOSYS
* If link_libc is true don't fall-back to the raw syscall approach,
there's no policy about what to do in this case but let's follow what
the other impls do.
Fixes #9146
Please review the logic with care, it's easy to get it wrong.

std: Make copy_file_range checks run at compile-time

---

src/Sema.zig
src/codegen.zig
src/type.zig
src/value.zig
test/stage2/test.zig

I am not sure how to test this and the `int_u64` checking feels a little weird, can anyone think of any better way to represent a Value pointer?

stage2 Sema: implement @intToPtr

---

src/AstGen.zig

I re-opened this because I had to rebase it onto stage1-astcheck and github was being weird.
Closes #9206

astgen: error on struct field with no type

---

lib/std/json.zig

Json parsing currently returns UnexpectedToken when setting an int/comptime int field if a json number has a decimal or exponent attached. Thus it cannot handle numbers represented as 10.0 or 4.2e2, even though these numbers are perfectly happy to be ints.
I've left the is_integer check as this is a useful performance optimization, but in the case that a decimal or e value occurs (which is actually what is_integer is telling us), I parse the number instead as an f128 value, round the value and compare the result. If they're identical, we can then convert to the destination int/comptime int type. If not, we have an attempt to coerce an actual decimal number to float and can return an error as before.
I've selected error.InvalidNumber for the error as this was used elsewhere already and it …

allow json scientific notation to coerce to integers

---

doc/docgen.zig
doc/langref.html.in

translate-c: Add documentation for `zig translate-c`

---

src/AstGen.zig
test/behavior/union.zig

Closes #9233
Should I add a regression test in test/stage2/test.zig

stage2: fix unreachable in union(enum) with anytype payload

---

lib/std/fmt.zig

When working with durations it often makes sense to use signed integers
and allow negative durations, and there is currently no nice way to
format these in std.fmt. This patch adds a simple wrapper for the
existing fmtDurtion to fit this need.

std/fmt: add fmtDurationSigned

---

src/stage1/all_types.hpp
src/stage1/analyze.cpp
src/stage1/astgen.cpp
src/stage1/codegen.cpp
src/stage1/ir.cpp
src/stage1/ir_print.cpp

This commit intends to have no functional changes. The only purpose
is to delete the struct IrInst, which is the common base struct that
both IrInstSrc (ZIR) and IrInstGen (AIR) instructions embed.
This untangles stage1 ZIR and AIR memory layout, paving the way for a
following commit to reduce memory usage.

stage1: eliminate the IrInst base struct

---

doc/langref.html.in

Link to the GPA now that it's on upstream

---

test/cases.zig
test/stage2/plan9.zig

They generate an object file, but do not execute yet,
since we don't have something to execute them with.
Hopefully once I add arm support soon, I can add arm in the test case too!

plan9 codegen, add tests

---

lib/std/start.zig
src/codegen.zig
src/link/Plan9.zig
test/stage2/plan9.zig

Awaiting testing from someone with a rpi (I might be able to use qemu to test).

stage2 plan9: add aarch64 support

---

lib/std/os/linux/io_uring.zig

Implement io_uring submission queue entry preparation methods for epoll_ctl, poll_add, and poll_remove.
Poll masks are designated as 32-bit little-endian integers as specified in liburing's definitions. Refer to the patch series here for more information: https://www.spinics.net/lists/io-uring/msg02853.html
Updated io_uring_prep_rw to take in an unsigned 64-bit address instead of an anytype. io_uring_sqe by default assumes that the address specified in a submission queue entry is an unsigned 64-bit integer.
cc @ifreund @jorangreef

io_uring: add sqe prep methods for epoll_ctl, poll_add, and poll_remove

---

src/AstGen.zig
test/cases.zig
test/compile_errors.zig

stage2 astgen: error for return outside of function scope

---

src/codegen.zig
src/link/Elf.zig
src/link/Plan9.zig

The incrementalness is now roughly the same as the c backend
rather than the spirv backend before.
Also include a cleanup in codegen.zig

plan9 linker: make more incremental

---

lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig

parser: require block in suspend expression

---

src/link/Plan9.zig

* exports get rendered properly in symbol table
* global offset table is at the start of data section
instead of after symtab
* various null use fixes

[stage2-air]: plan9 linker: fix after testing

---

src/codegen/c.zig

The diff looks a bit weird as I deleted airUnOp as it is not used after this.

[stage2-air]: cbe: fix not (it is a ty_op, not un_op)

---

src/print_air.zig

Implements debug printing AIR for the following instructions:
- bin_op
- un_op
- block
- struct_field_ptr
- br
- condbr
- switch_br
Also updates constant to write the actual Type, rather than the enum tag of the `Ref`.

[stage 2 - AIR] Debug info - Implement more instructions

---

src/AstGen.zig
src/Compilation.zig
src/Zir.zig

- Changed ZIR encoding of `import` metadata from having instruction
indexes to storing token indexes.

Fixed wrong "unable to load" error for non-existing import files

---

lib/std/hash/auto_hash.zig
lib/std/meta/trait.zig

Correct hasUniqueRepresentation for vectors

---

src/AstGen.zig
test/cases.zig

astgen: errors for shadowing in captures

---

src/stage1/codegen.cpp

make progress towards https://github.com/ziglang/zig-bootstrap/issues/52

stage1: add c_longdouble mapping for s390x

---

lib/std/fs/path.zig

Had an issue with `resolveInstallPrefix()` in `std/build.zig` when `--prefix-exe-dir` was passed with an absolute path as an argument. When given an absolute path `resolveInstallPrefix()` would ultimately try and join an empty string with the given absolute path, and it was adding a file separator between them. So for me it would join `""` and `"c:\Users\Austin"` to `"\c:\Users\Austin"`, an invalid path. Now `std.fs.path.join()` will skip over any empty strings given as arguments while still adding separators between non-empty strings where necessary.

Skip empty strings in std.fs.path.join function

---

src/codegen.zig

Mostly copied and adapted from `codegen/llvm.zig`.

stage2 codegen: genTypedValue for error unions and error sets

---

src/codegen.zig
test/stage2/arm.zig

Copied and adapted from `codegen/wasm.zig`

stage2 codegen: Implement genTypedValue for enums

---

src/link/MachO.zig
test/standalone.zig
test/standalone/objc/Foo.h
test/standalone/objc/Foo.m
test/standalone/objc/build.zig
test/standalone/objc/test.m

Add standalone Objective-C enabled on macOS only

---

lib/std/array_hash_map.zig

which internally calls `ArrayHashMap.pop`, however, returns `?KV`
instead and performs the bounds checking automatically.
This function correponds to `ArrayList.popOrNull` and is meant
to fill the gap for situations where we want the quick lookup offered
by the hash map with elegant ability to iterate and pop of the
container with automatic bound checking that plugs in well with
a `while`-loop such as
```zig
var map = std.ArrayHashMap(K, V).init(allocator);
map.deinit();
while (map.popOrNull()) |entry| {
// ... do something
}
assert(map.count() == 0);
```

libstd: add ArrayHashMap.popOrNull function

---

src/Compilation.zig

include builtin & std packages in all defined packages

---

lib/std/mem.zig

Update mem.split/mem.tokenize doc comments

---

src/Air.zig
src/Liveness.zig
src/Sema.zig
src/codegen.zig
src/codegen/c.zig
src/codegen/llvm.zig
src/codegen/llvm/bindings.zig
src/print_air.zig
test/stage2/cbe.zig
test/stage2/llvm.zig

This implements it in the llvm and c backends.
x86_64 will have to be a little more work.

stage2: implement shr and shl

---

src/codegen.zig
src/codegen/arm.zig
test/stage2/arm.zig

Follow-up PR to #9587 as promised in https://github.com/ziglang/zig/pull/9587#discussion_r692431680

stage2 ARM: implement bitshifts

---

lib/std/build.zig

resolves https://github.com/ziglang/zig/issues/9308, though I'm not sure if this is the right way to achieve it. I need comments from @andrewrk @kubkon. Thank you!

build: allow specifying -mexec-model flag.

---

test/behavior.zig
test/behavior/comptime_memory.zig

This PR adds tests for the behavior described in #9646.  When these tests pass, that issue can be closed.

Add comptime memory tests

---

src/codegen/llvm.zig
src/codegen/llvm/bindings.zig

stage2: only initialize the llvm backend for the target we are building

---

doc/langref.html.in

fix language reference typo

---

lib/libc/mingw/math/arm-common/log2.c
lib/libc/mingw/math/arm-common/pow.c
lib/libc/mingw/math/bsd_private_base.h
lib/libc/mingw/misc/initenv.c
lib/std/special/compiler_rt.zig
lib/std/special/compiler_rt/stack_probe.zig
src/mingw.zig
test/tests.zig

fix issue #9519 by adding some missing stuff from mingw and compiler_rt to support windows aarch64.

implement building via cgo for windows/arm64 (aarch64-windows-gnu)

---

lib/std/c/netbsd.zig
lib/std/event/loop.zig
test/standalone.zig
test/standalone/issue_9693/main.zig

std: update event loop for recent usingnamespace changes

---

lib/libc/mingw/math/arm-common/scalbn.c
src/mingw.zig
src/windows_sdk.cpp

These are changes I made in order to build zig with the zig-bootstrap project for `aarch64-windows-gnu`

changes to build zig-bootstrap aarch64-windows

---

src/link/Plan9.zig

plan9 linker: fix for 32 bit

---

lib/std/special/compiler_rt/stack_probe.zig

This is a follow up on changes to support `aarch64-windows`.  A previous change added the missing `__chkstk` symbol, but that symbol wasn't hooked up properly in `stack_probe.zig`, which resulted in the implementation just being an `unreachable`.  Now it's hooked up properly and it's been tested through a dll that was compiled for and then executed on a Hololens 2 platform.  
Note, the `__chkstk` function is executed during `alloca` which is called during `DllMainCRTStartup` in the mingw-w64 implementation.

fix __chkstk on aarch64

---

src/Module.zig

stage2 Module: fix for 32 bit

---

lib/std/leb128.zig

I'm working on [a WebAssembly interpreter in zig](https://github.com/malcolmstill/foxwren). WebAssembly uses LEB128 encoding throughout its specification.
The WebAssembly spec requires signed LEB128 to be encoded up to a maximum number of bytes (max 5 bytes for i32, max 10 bytes for i64) and that "unused" bits are all 0 if the number is positive and all 1 if the number is negative. The Zig LEB128 implementation already enforces the max number of bytes and does check the unused bytes https://github.com/ziglang/zig/blob/master/lib/std/leb128.zig#L70-L79.
However, the WebAssembly test suite has a number of tests that were failing validation (expecting the wasm module to fail validation, but when running the tests, those examples were actually passing validation):
- …

readILEB128: Check remaining bits on last byte of negative number even if we don't overflow

---

lib/std/crypto/benchmark.zig
lib/std/crypto/blake3.zig
lib/std/hash/benchmark.zig

Update `hash` & `crypto` benchmarks run comment and Rename blake3 arguments name

Update `hash` & `crypto` benchmarks run comment

---

src/AstGen.zig
src/Compilation.zig
src/Module.zig
src/Sema.zig
src/print_zir.zig
src/type.zig
test/behavior.zig
test/behavior/sizeof_and_typeof.zig
test/behavior/sizeof_and_typeof_stage1.zig
test/behavior/translate_c_macros.zig
test/behavior/translate_c_macros_stage1.zig

~I have no idea if any of this works since I can't build stage2 with LLVM.~ Still can't build stage2 with LLVM but `-fno-stage1` will work for now.

stage2: implement cImport

---

src/Module.zig
src/codegen.zig
src/link/Plan9.zig
src/link/Plan9/aout.zig

plan9: emit debug info

---

lib/std/os/linux/io_uring.zig

This PR implements the equivalent of:
* [io_uring_prep_read_fixed](https://github.com/axboe/liburing/blob/98db8e883c0fedcfbf74ba7922821ff3be0e7c98/src/include/liburing.h#L310-L316)
* [io_uring_prep_write_fixed](https://github.com/axboe/liburing/blob/98db8e883c0fedcfbf74ba7922821ff3be0e7c98/src/include/liburing.h#L325-L331)
* [io_uring_register_buffers](https://github.com/axboe/liburing/blob/98db8e883c0fedcfbf74ba7922821ff3be0e7c98/src/include/liburing.h#L127-L128)
* [io_uring_unregister_buffers](https://github.com/axboe/liburing/blob/98db8e883c0fedcfbf74ba7922821ff3be0e7c98/src/include/liburing.h#L136)

io_uring: implement read_fixed/write_fixed

---

lib/std/x/os/net.zig

On certain systems (Solaris), resolving the scope id from an interface
name can only be done on AF_INET-domain sockets. While we're here,
simplify the test while we're here, since there's only one address.
Also note that the loopback interface name is not stable across OSs.
BSDs and Solaris use `lo0` whilst Linux uses `l0`.

Resolve scope IDs using AF_INET sockets

---

src/Sema.zig
src/print_zir.zig
test/behavior/array.zig

No tests from array_stage1.zig because apparently 
```
const a = [_]u64{a, b};
```
does not actually use array_init.
Works!!! (this uses array_init)
Could I use this as a test for now?

stage2: array stuff

---

src/Compilation.zig
src/Module.zig
src/Sema.zig
src/codegen.zig
src/codegen/c.zig
src/codegen/llvm.zig
src/codegen/spirv.zig
src/codegen/wasm.zig
src/crash_report.zig
src/link/Plan9.zig
src/main.zig
src/print_zir.zig
src/type.zig
src/value.zig

This fixes `std.target.Target.Cpu.Feature.feature_set_fns`, which may unlock other tests.

Stage 2: A bunch of cleaning up

---

lib/std/math.zig

add phi constant

---

src/main.zig

zig test: Add a --test-no-exec flag.

---

lib/std/heap/general_purpose_allocator.zig

Fixes #9995. The memory limit accounting in `GeneralPurposeAllocator` is broken for large allocations. The initial allocation will count the actual size returned by the backing allocator, but later resizes count only the requested size. If `resize` is being used with a non-zero `len_align` (as when calling `reallocAtLeast`), the backing allocator is likely to not bother actually shrinking the allocation. A large alloc followed by multiple shrinking reallocs will likely cause an underflow in `total_requested_bytes`:
```zig
var gpa = std.heap.GeneralPurposeAllocator(.{ .enable_memory_limit = true }){};
// assume page size is 4096, so large alloc
var buf = try gpa.allocator.alloc(u8, 4096);
// now gpa.total_requested_bytes == 4096
buf = try gpa.allocator.reallocAtLeast(buf, 1);
// now …
```

GeneralPurposeAllocator: fix memory limit accounting for large allocations

---

lib/std/c/linux.zig

fix termios not working when linking libc

---

src/AstGen.zig

<details>
<summary>tldr</summary>
| type | average improvement |
| --- | --- |
| debug no cache | ~549ms |
| debug cached | ~1.7ms |
| release no cache |  ~196ms |
| release cached | ~0.1ms |
</details>
While working on #10068 I happened to notice a sizeable number of short term allocations in this function.
I collected data regarding the number of arguments in call expressions by compiling a file with only an empty main function with no local or global cache and stashing the data from `AstGen.callExpr` which resulted in:
| Length | Count | Percentage |
| --- | --- | --- |
| 1 | 19480 | 45.80% |
| 2 | 7962 | 18.72% |
| 0 | 7140 | 16.79% |
| 3 | 4152 | 9.76% |
| 4 | 2042 | 4.80% |
| 5 | 1036 | 2.44% |
| 6 | 332 | 0.78% |
| 7 | 213 | 0.50% |
| 10 | 158 | 0.37% |
| 11 | 5 | 0.01% |
| 9 | 5 | …

stage2: optimize AstGen.callExpr

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig

This PR introduces a new algorithm for lowering branches in MIR (which reference another MIR instruction as the target) to real branches (which include a code offset).

stage2 AArch64: implement unconditional branches

---

src/AstGen.zig

This is a large set of changes to reduce temporary allocations in `AstGen.zig` that I've been sitting on for a few days because I wasn't sure they were worth the disruption. However, inspired by the improvement in #10069, I thought I should see what other people think. They start off simple but especially the last one may be too much of a burden to maintain for the minor gains in performance. I've tried to split the commits up to make it easier to pick and choose, but there's still a lot to wade through.
For the first commit, the main observation is that some functions that make temporary ArrayLists of `Zir.Inst.Ref` know the length of those lists ahead of time and do nothing with the lists other than copying them to `astgen.extra` as trailing payload data. The temporary allocations can …

stage2: Reduce temporary allocations in AstGen

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
src/arch/aarch64/bits.zig
test/stage2/aarch64.zig

This also includes a simple test case for conditional branches. While working on this, I noticed loading and storing values from stack are broken at the moment, but I will fix that in a separate follow-up PR.
cc @kubkon

stage2 AArch64: Implement conditional branches

---

lib/std/os/linux/io_uring.zig

Add method from liburing to queue (but not submit) a SQE to update the user data of an existing poll operation.
cc @ifreund @jorangreef

io_uring: add poll_update

---

lib/std/crypto.zig
lib/std/crypto/argon2.zig
lib/std/crypto/benchmark.zig

This PR adds [Argon2](https://en.wikipedia.org/wiki/Argon2) key derivation function. Widely used for password hashing.
/cc @jedisct1

std/crypto: add argon2 kdf

---

lib/std/os/linux/io_uring.zig

This pull request adds IO_Uring.cancel method and io_uring_prep_cancel function

std.os.linux: Add cancel and io_uring_prep_cancel

---

lib/std/crypto/scrypt.zig

update docs
add fast kdf test
fix inconsistent kdf error
refactor
/cc @jedisct1

std/crypto: scrypt update

---

lib/std/json.zig

The stack has been adjusted so that instead of pushing to index 0 in the
integer we push to the current end/index of the underlying integer. This
means we don't require a shift for every limb after each push/pop and
instead only require a mask/or and add/sub on a single element of the array.
Fixes #5959.

std/json: use bit-stack for nesting instead of large LLVM integer type

---

lib/std/os/linux/io_uring.zig

Implements updating the registered file descriptors (see [this manpage](https://manpages.debian.org/unstable/liburing-dev/io_uring_register.2.en.html#IORING_REGISTER_FILES_UPDATE)). It's equivalent to [io_uring_register_files_update](https://github.com/axboe/liburing/blob/master/src/include/liburing.h#L151-L152) from liburing.
This time I tried to take into account older kernels in the test: as far as I understand sparse entry in the file descriptors array was introduced in 5.5 (see [this comment](https://github.com/ziglang/zig/blob/008b0ec5e58fc7e31f3b989868a7d1ea4df3f41d/lib/std/os/linux/io_uring.zig#L1242-L1243), and according to the manpage `IORING_REGISTER_FILES_UPDATE` was added in 5.5 as well.
The test relies on the fact that `register_files` with a sparse entry will fail on …

io_uring: implement register_files_update

---

lib/std/c/openbsd.zig

From https://github.com/openbsd/src/blob/master/sys/sys/termios.h

Add OpenBSD termios constants to `std.c.openbsd`

---

lib/std/zig/c_translation.zig
src/translate_c.zig
src/translate_c/ast.zig
test/run_translated_c.zig
test/translate_c.zig

translate-c: Allow negative denominator in remainder (%) operator

---

src/translate_c.zig
test/run_translated_c.zig

translate-c: coerce boolean results to c_int when negated

---

lib/std/os/uefi/tables/runtime_services.zig

based off definitions in https://uefi.org/sites/default/files/resources/UEFI%20Spec%202_6.pdf

feat(uefi): add virtual addressing helpers

---

lib/std/os/linux/io_uring.zig

Add method from liburing for [io_uring support for linked timeouts \[LWN.net\]](https://lwn.net/Articles/803932/)
Test code is ported from https://github.com/axboe/liburing/blob/b7159e46bc002c7a174e184d94cfa61552f92e69/test/link-timeout.c#L539-L628

os/linux/io_uring: add link_timeout

---

src/link/MachO.zig
src/link/MachO/Atom.zig

macho: fix regression in handling SIGNED_X relocs on x86_64

---

lib/std/os/linux/io_uring.zig

The old test "timeout_link_chain1" was ported from liburing test_timeout_link_chain1
https://github.com/axboe/liburing/blob/509873c4454012c5810c728695c21911c82acdc4/test/link-timeout.c#L539-L628
However it turns out that both fails with EBADF (-9) on Linux kernel 5.4.
The this new test skips properly on Linux kernel 5.4
and passes on Linux kernel 5.11.

Fix test for io_uring link_timeout (fixes #10247)

---

lib/std/mem/Allocator.zig

As noted by @N00byEdge the intent is for `vtable`'s lifetime to be global not to be tied to the stack of `Allocator.init`.
This PR moves `vtable` into the `gen` struct to clarify its intended lifetime.
Unfortunately this does require renaming the functions in `gen` or there is an ambiguous reference.

allocator: Move vtable into gen struct

---

lib/std/bit_set.zig

fixes #9944 
`./result/bin/zig test lib/std/std.zig --zig-lib-dir lib --main-pkg-path lib/std` tests passed.

9944: make allocator the first argument (excl. self)

---

src/tracy.zig

As `TracyAllocator` is not in the stdlib and is only conditionally compiled in stage2 I missed it in some of the later allocgate commits.

stage2: fix TracyAllocator bugs

---

src/link/MachO/Atom.zig

macho: handle non-extern UNSIGNED relocs on arm64

---

src/link/MachO.zig

This adds LC_FUNCTION_STARTS info into the binary providing enhanced debugging support in case of an unexpected runtime crash.

macho: write out LC_FUNCTION_START data

---

src/Compilation.zig

While investigating slow build times with [a large project](https://github.com/hexops/mach/issues/124), I found that the compiler was reading from disk nearly every C source file in my project when rebuilding despite no changes having been made to any of my sources. This accounted for several seconds of time (approx. 20-30% of running `zig build` without any changes to the sources.)
The cause of this was that comparisons of file mtimes would _always_ fail (the mtime of the file on disk was always newer than that stored in the cache manifest), and so the cache logic would always fall back to byte-for-byte file content comparisons with what is on disk vs. in the cache-reading every C source file in my project from disk during each rebuild. Because file contents were the same, a cache hit …

Fix compilation cache updating bug leading to slow builds

---

src/link/Plan9.zig

plan9 linker: fix off by 1 error

---

src/arch/arm/CodeGen.zig

This _almost_ implements storing to global variables, but more support in the linking backends is needed as global variables are currently assigned to the read-only `.text` section (e.g. for ELF).

stage2 ARM: Refactor airStore

---

lib/std/c/openbsd.zig

Add the constants used to interact with BSD Authentication
https://blog.lambda.cx/posts/how-bsd-authentication-works/

Add BSD Authentication constants

---

src/arch/arm/CodeGen.zig
src/codegen.zig

Another small step towards `zig test`

stage2 ARM: Implement airLoad for slices

---

src/stage1/ir.cpp
test/behavior/slice_stage1.zig

stage1: fix access of slice sentinel at comptime

---

test/stage2/x86_64.zig

The test case works now.
Closes #7187

stage2 x86_64: add regression test for #7187

---

src/AstGen.zig

Some errors do not need to halt ast check eagerly. In those cases, it's a better developer experience to show more errors upfront rather than wait for previous errors to be fixed before showing more.
This applies to the following errors:
- `"unused for loop label"`
- `"unused while loop label"`
- `enum declarations must have at least one tag`
- `non-exhaustive enum missing integer tag type` (is this one safe?)
- `'comptime const' is redundant; instead wrap the initialization expression with 'comptime'`
- `"unused {s}"`
- `unused block label`
- `redundant nosuspend block`
- `unreachable code` (there is a case to be made that reporting errors in unreachable code is unnecessary)
| Before (37) | After (69) |
:-------------------------:|:-------------------------:

Report more errors upfront when possible

---

src/arch/arm/CodeGen.zig
src/codegen.zig
test/stage2/arm.zig

stage2 ARM: zig test working

---

src/arch/arm/CodeGen.zig
test/behavior.zig
test/stage2/arm.zig

This gets a bunch more behavior tests passing.

stage2 ARM: implement wrap_errunion_err for empty payloads

---

src/link/Plan9.zig

This allows the `acid` debugger on
plan9 to be used to debug a zig source
file without patching `acid`!
The patch adds a second `z` symbol. This z
symbol has a value of 0, which means that it
pops the history stack. We put a very large
number for the value of the second symbol because
it has to be at least as large as the linecount of
the file. The debuginfo format is meant to be used
with c files, where the stack would look something
like this:
```
->  Line: 0x1 (1)  Name: 0x1/0x2/0x3/0xe/0x13/0x1b (/sys/src/libc/port/malloc.c)
->  Line: 0x2 (2)  Name: 0x1/0x6/0x7/0x8 (/amd64/include/u.h)
->  Line: 0x4f (79)  Name:  ()
->  Line: 0x50 (80)  Name: 0x1/0x2/0x7/0x9 (/sys/include/libc.h)
->  Line: 0x358 (856)  Name:  ()
->  Line: 0x359 (857)  Name: 0x1/0x2/0x7/0x1c (/sys/include/pool.h)
-> …
```

plan9: fix .z symbol in debuginfo

---

src/Sema.zig
src/type.zig
test/behavior.zig

Time to get familiar with stage 2 semantic analysis. Found this low-hanging fruit to get me started :)

stage2: Implement validating switch on errors

---

lib/std/hash.zig
lib/std/special/compiler_rt/int.zig
lib/std/special/compiler_rt/multi3.zig
lib/std/special/compiler_rt/negsi2_test.zig
lib/std/special/compiler_rt/paritydi2_test.zig
lib/std/special/compiler_rt/paritysi2_test.zig
lib/std/special/compiler_rt/parityti2_test.zig
lib/std/special/compiler_rt/popcountdi2_test.zig
lib/std/special/compiler_rt/popcountsi2_test.zig
lib/std/special/compiler_rt/popcountti2_test.zig
lib/std/special/compiler_rt/truncXfYf2_test.zig
lib/std/special/compiler_rt/udivmod.zig
lib/std/time.zig
lib/std/valgrind.zig
lib/std/zig/system/darwin.zig
src/Compilation.zig
src/main.zig
src/mingw.zig
src/tracy.zig
src/translate_c.zig
test/behavior/cast.zig
test/behavior/enum_stage1.zig
test/behavior/import.zig
test/behavior/int128.zig
test/behavior/ref_var_in_if_after_if_2nd_switch_prong.zig
test/behavior/reflection.zig
test/behavior/translate_c_macros.zig
test/behavior/translate_c_macros_stage1.zig
test/behavior/widening.zig
test/standalone/install_raw_hex/build.zig

found with https://github.com/nektro/ziglint and manually updated

lint: duplicate import

---

src/link.zig

handle `error.PathAlreadyExists` in `renameTmpIntoCache`

---

lib/std/zig/Ast.zig

super confusing reading through the source to finally realize `Tree` was `@This()`.

std: fix zig.Ast being called Tree internally

---

src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
src/arch/aarch64/bits.zig

stage2 AArch64: split ldr/str into {ldr,str}_register and _immediate

---

src/arch/arm/CodeGen.zig

As we copy function parameters to the stack anyways for debugging purposes, this makes things easier.

stage2 ARM: store all function parameters to stack for unspecified cc

---

src/arch/arm/CodeGen.zig
test/behavior.zig

stage2 ARM: implement load for stack_offset + stack_argument_offset

---

lib/std/json.zig

Previously only `std.json.stringify` was available which accepts a Writer. This PR adds an alternative that accepts an Allocator for a shorthand to return the stringification results in dynamically allocated memory.

std: add json.stringifyAlloc

---

lib/std/c.zig

https://man7.org/linux/man-pages/man3/shm_open.3.html

std.c: add shm_open and shm_unlink

---

lib/std/c/darwin.zig
lib/std/debug.zig
src/crash_report.zig

Fixes part of https://github.com/ziglang/zig/issues/10609. It is still not implemented for ARM, but in a few weeks I will have access to an M1 MacBook and can hopefully continue from there.

Implement segfault handler for macOS x86_64

---

lib/std/builtin.zig
src/Air.zig
src/Liveness.zig
src/Sema.zig
src/arch/aarch64/CodeGen.zig
src/arch/arm/CodeGen.zig
src/arch/riscv64/CodeGen.zig
src/arch/wasm/CodeGen.zig
src/arch/x86_64/CodeGen.zig
src/codegen/c.zig
src/codegen/llvm.zig
src/link/C/zig.h
src/print_air.zig
test/behavior.zig
test/behavior/atomics.zig

This reverts commit f423b5949b8722d4b290f57c3d06d015e39217b0,
re-instating commit d48e4245b68bf25c7f41804a5012ac157a5ee546.

stage2: implement `@prefetch`

---

lib/std/meta.zig

counterpart to `std.meta.FieldEnum` but for declarations

std: add meta.DeclEnum

---

src/stage1/all_types.hpp
src/stage1/analyze.cpp
src/stage1/ir.cpp
test/compile_errors.zig

It's generally noise. The parts where it is useful will need to be
redone to not be annoying for the general case.

stage1: remove the "referenced here" error note

---

lib/std/io/buffered_writer.zig

Looking at the BufferedWriter assembly generated, one can see that is
has to do a lot of work, just to copy over some bytes and increase an
offset. This is because the LiniarFifo is a much more general construct
than what BufferedWriter needs and the optimizer cannot prove that we
don't need to do this extra work.
Here are some benchmarks:
``` zig
const fmt = std.fmt;
const heap = std.heap;
const io = std.io;
const process = std.process;
var arena = heap.ArenaAllocator.init(heap.page_allocator);
defer arena.deinit();
const args = try process.argsAlloc(arena.allocator());
const start = try fmt.parseUnsigned(usize, args[1], 10);
const end = try fmt.parseUnsigned(usize, args[2], 10);
var writer = …
```

Stop using LiniarFifo in BufferedWriter

---

lib/std/special/compiler_rt.zig
lib/std/zig/Ast.zig
src/AstGen.zig
src/Module.zig
src/Sema.zig
src/Zir.zig
src/print_zir.zig
test/behavior/cast_llvm.zig
test/behavior/inttoptr.zig

Doc comments zir

---

lib/std/hash_map.zig

HashMap.remove performs an index lookup, which is unnecessary if you've already looked up the key in the hash map (for example, to remove it conditional on the stored value). It would be useful to have a method to remove an item with a known index without performing an additional index lookup.
The method takes a pointer to a key rather than a pointer to a value to support cases where the value is zero sized.

HashMap: add removeByPtr

---

src/arch/x86_64/CodeGen.zig
src/arch/x86_64/Emit.zig

* implement cond_br when MCValue is a stack offset
* implement passing compare flags and immediate on stack

stage2: populate debug info for args passed on stack

---

src/arch/x86_64/CodeGen.zig

Some bugs in other parts of the compiler lead to some of the truncate tests not working properly.
Specifically:
1. comparing signed integers of non power-of-two sizes
2. using `u0` or `i0` seems to crash the stage2 compiler
But ignoring those, all the other tests that needed `airTrunc` in both `test/behavior/basic.zig` and `test/behavior/truncate.zig`
now pass.

stage2: x64: implement airTrunc

---

src/link/Elf.zig

Implements slice types including `[]const u8` for passing as
formal parameters in DWARF. Breaking on a function accepting
a slice in `gdb` will now yield the same behavior as stage1 and/or
LLVM backend:
```zig
fn sumArrayLens(a: []const u32, b: []const u8) usize {
return a.len + b.len;
}
```
Both `a` and `b` can now be inspected in the debugger:
```
Breakpoint 1, sumArrayLens (a=..., b=...) at arr.zig:59
(gdb) p a
$1 = {ptr = 0x7fffffff685c, len = 5}
(gdb) p b
$2 = {ptr = 0x7fffffff683d "\252\252\252\\h\377\377\377\177", len = 3}
(gdb)
```

elf: implement slice types in debug info

---

src/register_manager.zig

The freeze/unfreeze API replaces the exceptions API for hopefully preventing bugs in codegen code using the RegisterManager. The exceptions API is still available for backwards compatibility and will be removed once all backends transition to the new freeze/unfreeze API.
This topic was discussed in the [stage2 meeting on 2022-01-13](https://github.com/ziglang/zig/wiki/Self-Hosted-Compiler-Meetings#2022-01-13).

stage2 regalloc: Add freezeRegs/unfreezeRegs API

---

lib/std/debug.zig

add std.debug.todo

---

src/register_manager.zig

Specifically, `allocRegs` would in some cases forget to mark a register as allocated, leading to registers not being pushed and popped from the stack in the function prologues/epilogues.

stage2 regalloc: Fix bug where regs were not marked as allocated

---

lib/std/zig/parser_test.zig
lib/std/zig/render.zig

Closes https://github.com/ziglang/zig/issues/10443.

fmt: handle doc comments on struct members

---

lib/std/target.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig

Spotted a few TODOs, thought it best to act on them now 0.9.0 is released.

std housekeeping

---

src/Autodoc.zig

Port of https://github.com/ziglang/zig/blob/aca665cebd2b6ec9ec3db669cf5446ee45bbb5d0/src/stage1/codegen.cpp#L10290-L10320

autdoc: install artifacts

---

lib/std/Thread/Condition.zig
lib/std/Thread/Semaphore.zig

Add tests for std.Thread.Condition and std.Thread.Semaphore

---

src/arch/aarch64/CodeGen.zig

Follow-up to #10701 for AArch64

stage2 AArch64: Move to new regalloc freeze API

---

src/arch/arm/CodeGen.zig

stage2 ARM: Move to new regalloc freeze API

---

src/arch/arm/CodeGen.zig

Just a small thing which is implemented in x86_64 but wasn't implemented in ARM yet.

stage2 ARM: implement ptr_stack_offset function parameters

---

lib/std/builtin.zig
lib/std/crypto.zig
lib/std/meta.zig
lib/std/target.zig
lib/std/testing.zig
src/stage1/all_types.hpp
src/stage1/analyze.cpp
src/stage1/ir.cpp
src/translate_c.zig
test/behavior.zig
test/behavior/export_self_referential_type_info.zig
test/behavior/type_info.zig
test/compile_errors.zig

stage1: remove the `data` field from `TypeInfo.Declaration`

---

doc/langref.html.in

Correct `f80` docs

---

src/arch/x86_64/CodeGen.zig

The test `test/behavior/bugs/1486.zig` almost passes after this, but fails due to a (mutable) global getting put in `.rodata`.
(the assembly output looked good, but as an experiment I tried making `.rodata` also writable and that made the test pass)

stage2 x64: implement storing values to MCValue.memory

---

src/arch/aarch64/CodeGen.zig
src/arch/arm/CodeGen.zig
src/arch/riscv64/CodeGen.zig
src/arch/x86_64/CodeGen.zig
src/register_manager.zig

stage2: migrate x64 to freeze regalloc API, and remove the concept of register exceptions

---

src/arch/x86_64/CodeGen.zig

Follow-up to #10767
cc @mparadinha

x64: implement storing to MCValue.memory for PIE targets

---

src/arch/arm/CodeGen.zig
src/arch/arm/bits.zig

In these cases, the AIR inst can be lowered to only one ldr instruction.
Also fixes shifts in arm.bits.Offset

stage2 ARM: optimize airSliceElemVal for elem_size 1 or 4

---

lib/std/special/compiler_rt/mulo.zig

- use usize to decide if register size is big enough to store
multiplication result or if division is necessary
- multiplication routine with check of integer bounds
- wrapping multipliation and division routine from Hacker's Delight

compiler_rt: optimize mulo

---

lib/std/build.zig
lib/std/build/TranslateCStep.zig

The methods (and comments) are copy-pasted from `std.build.LibExeObjStep`, but
the string construction code is moved out into `std.build.constructCMacro`,
to allow reusing it elsewhere.
(Not sure if the name `constructCMacroArg` or `-DefArg` would be better?
In particular, it's really just `<name>=<value>`, without the `-D` prefix.
Maybe a fmt.bufPrint would be cleaner? But I thought I'd rather not overthink it
and leave the code as it was, whatever the reason.)
It's already working for me locally, so should hopefully be ready if it looks good.

std.build.TranslateCStep: add C macro support

---

lib/std/build.zig

#5514 was [closed with the request](https://github.com/ziglang/zig/pull/5514#issuecomment-667710208) to try using `setOutputDir` on tests to give them a predictable output path; this is a four-line fix [to remove tests as a special case](https://github.com/ziglang/zig/pull/5514#issuecomment-909069151) so we can try it.

std: allow tests to use cache and setOutputDir

---

src/arch/arm/CodeGen.zig

As promised for https://github.com/ziglang/zig/pull/10779#discussion_r799365501
cc @kubkon

stage2 ARM: clarify usage of unfreezeRegs in airSliceElemVal

---

src/arch/arm/CodeGen.zig

Previously, in these cases, we would emit the ldr instruction even
though ldrb oder ldrh are the correct instructions.

stage2 ARM: fix load and store for abi_size < 4

---

lib/std/special/compiler_rt.zig
lib/std/special/compiler_rt/addo.zig
lib/std/special/compiler_rt/subo.zig
lib/std/special/compiler_rt/subodi4_test.zig
lib/std/special/compiler_rt/subosi4_test.zig
lib/std/special/compiler_rt/suboti4_test.zig

- approach by Hacker's Delight with wrapping subtraction
- performance expected to be similar to addo
- tests with all relevant combinations of min,max with -1,0,+1 and all
combinations of sequences +-1,2,4..,max

compiler_rt: add subo

---

src/arch/arm/CodeGen.zig
test/behavior/align.zig
test/behavior/bugs/1277.zig
test/behavior/bugs/1310.zig
test/behavior/bugs/2006.zig
test/behavior/cast.zig
test/behavior/struct.zig

Also implements more of `airStructFieldVal`

stage2 ARM: genTypedValue for all integer types

---

src/link/Elf.zig
test/behavior.zig
test/behavior/basic.zig
test/behavior/bugs/2006.zig
test/behavior/bugs/3367.zig

Enable more behavior tests on both x64 and arm

stage2: handle void type in Elf DWARF gen

---

lib/std/special/c.zig
src/Sema.zig
src/codegen.zig
src/link/Elf.zig
test/behavior/bugs/1914.zig

stage2: handle decl ref to void types

---

src/link/Elf.zig

We need to pad out the file to the required maximum size equal the
final section's offset plus the section's size. We only need to
this when populating initial metadata and only when section header
was updated.

elf: pad out file to the required size when init data

---

lib/std/zig/Ast.zig
lib/std/zig/parse.zig
lib/std/zig/render.zig
src/AstGen.zig
src/Module.zig
src/Zir.zig
src/print_zir.zig
test/behavior.zig
test/behavior/decltest.zig

Implements parsing and zir of https://github.com/ziglang/zig/issues/7923 in stage2

stage2: Decltests

---

lib/std/os/linux.zig

On 64bit platform, we shouldn't split `offset` argument because the register is big enough to hold it.
Linux kernel also expects this assumption.

Fix preadv/pwritev bug on 64bit platform

---

src/register_manager.zig

The information whether a register is allocated to an instruction is
already encoded in the `free_registers` "bitmap". Duplicating that
information in the `registers` map is unnecessary and may lead to
performance degradations.

stage2 regalloc: track Inst instead of ?Inst in register mapping

---

src/Sema.zig

Two TODOs down, a few more to go 😄

stage2: improve compiler error message for bad union init

---

src/link/MachO.zig
src/link/MachO/DebugSymbols.zig

* update number of type abbrevs to match Elf linker
* update `DebugSymbols` to write symbol and string tables
at the end to match the `MachO` linker
* TODO: update segment vm addresses when growing segments in
the binary
* TODO: store DWARF relocations in linker's interned arena

macho: re-enable creating dSYM bundle

---

src/stage1/bigint.cpp
test/behavior/saturating_arithmetic.zig

- also simplifies code
- adding a few more tests
closes #10870

stage1: fix comptime saturation subtraction

---

src/link/MachO.zig
src/link/MachO/DebugSymbols.zig

* move DWARF in file if LINKEDIT spilled in dSYM
* update VM addresses for all segments
* introduce `copyFileRangeOverlappedAll` instead of `File.copyRangeAll` since we make lots of overlapping writes in MachO linker
EDIT: this makes it possible to step through the code in `lldb` with source lines preview on macOS

macho: handle binary updates in dSYM companion file

---

src/arch/aarch64/CodeGen.zig

Previously, the invocations used movk instead of movz

stage2 AArch64: Simplify and correct invocations of genInlineMemcpy

---

src/stage1/codegen.cpp

Non-Arm CPUs use `u16` as the parameter to `__extendhfxf2` and the return value of `__truncxfhf2`, so insert appropriate bitcasts in `gen_soft_f80_widen_or_shorten`.
Otherwise, LLVM might crash because the functions are called in a different way than its compiler-rt definition.
This fixes stage1 build on SPARCv9, and possibly other non-x86, non-Arm CPUs.
Closes #10872.

stage1: use u16 for __truncxfhf2/__extendhfxf2 on non-Arm CPUs

---

lib/std/zig/c_translation.zig
src/clang.zig
src/translate_c.zig
src/zig_clang.cpp
src/zig_clang.h
test/behavior/translate_c_macros.h
test/behavior/translate_c_macros.zig
test/run_translated_c.zig

translate-c: Add support for cast-to-union

---

src/AstGen.zig
src/Sema.zig
test/behavior.zig
test/behavior/bugs/10970.zig

AstGen: also eliminate store_to_block_ptr intsts from sub blocks

---

lib/std/Thread.zig

fix typo on Thread's getHandle docs

---

src/arch/arm/CodeGen.zig
src/arch/arm/Emit.zig
src/arch/arm/Mir.zig
src/arch/arm/bits.zig
test/behavior/basic.zig
test/behavior/truncate.zig

`*` only to integers with <= 32 bits

stage2 ARM: implement truncate*

---

src/Module.zig
src/Sema.zig
src/codegen/llvm.zig
src/type.zig
test/behavior.zig

* resolve error sets before merging them
* implement tupleFieldPtr
* make ret_ptr behave like alloc with zero sized types in llvm backend

stage2: various fixes to get one test passing

---

src/arch/arm/CodeGen.zig
src/arch/arm/Mir.zig
src/arch/arm/bits.zig
test/behavior/align.zig
test/behavior/array.zig
test/behavior/basic.zig
test/behavior/bitcast.zig
test/behavior/bitreverse.zig
test/behavior/bugs/3367.zig
test/behavior/bugs/3586.zig
test/behavior/bugs/4560.zig
test/behavior/bugs/704.zig
test/behavior/cast.zig
test/behavior/defer.zig
test/behavior/enum.zig
test/behavior/error.zig
test/behavior/fn.zig
test/behavior/for.zig
test/behavior/generics.zig
test/behavior/if.zig
test/behavior/slice.zig
test/behavior/struct.zig
test/behavior/this.zig
test/behavior/try.zig
test/behavior/type_info.zig
test/behavior/undefined.zig
test/behavior/union.zig
test/behavior/usingnamespace.zig
test/behavior/void.zig
test/behavior/while.zig

also `Mir.Inst.Data` is now 8 bytes as it should be

stage2 ARM: pass more behavior tests

---

lib/std/buf_set.zig

Following how ArrayList and HashMap does things. This is useful when one
wants to, ahem, clone the BufSet.

std.BufSet: add clone and cloneWithAllocator

---

src/arch/x86_64/CodeGen.zig
src/codegen.zig
test/behavior/array.zig

* x64: handle storing from-to non-stack memory
502 tests passing on x64! :tada:

codegen: handle elem_ptr when lowering to memory

---

src/Sema.zig
test/behavior/cast.zig

Logic errors I introduced in prior PRs, tests now pass.

stage2: fix a couple issues with peer resolution and const casting arrays

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
src/arch/aarch64/bits.zig
test/behavior/align.zig
test/behavior/array.zig
test/behavior/bitcast.zig
test/behavior/bugs/3367.zig
test/behavior/bugs/3586.zig
test/behavior/bugs/704.zig
test/behavior/cast.zig
test/behavior/defer.zig
test/behavior/enum.zig
test/behavior/error.zig
test/behavior/floatop.zig
test/behavior/fn.zig
test/behavior/for.zig
test/behavior/generics.zig
test/behavior/if.zig
test/behavior/inttoptr.zig
test/behavior/math.zig
test/behavior/null.zig
test/behavior/slice.zig
test/behavior/struct.zig
test/behavior/switch.zig
test/behavior/this.zig
test/behavior/truncate.zig
test/behavior/try.zig
test/behavior/usingnamespace.zig
test/behavior/while.zig

Includes:
* https://github.com/ziglang/zig/pull/11055 but for AArch64
* more slice support
* bitwise negation

stage2 AArch64: various improvements

---

src/AstGen.zig
src/Module.zig
src/Sema.zig
test/behavior.zig
test/behavior/basic.zig
test/behavior/bugs/11100.zig

Sema: handle noreturn result in condbr_inline

---

lib/std/array_hash_map.zig
lib/std/multi_array_list.zig
lib/std/sort.zig

This also adds `std.sort.sortContext` and
`std.sort.insertionSortContext` which are more advanced methods that
allow overriding the `swap` method. The former calls the latter for now
because reworking the main sort implementation is a big task that can be
done later without any changes to the API.

std: add sort method to ArrayHashMap and MultiArrayList

---

src/arch/x86_64/CodeGen.zig

stage2 x86_64: Fix assertion in getResolvedInstValue

---

src/Sema.zig
test/behavior/type.zig

I wasn't 100% sure I used all the correct allocators all over the place, so please take a close look there.

stage2: zirReify for enums

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
src/arch/aarch64/bits.zig
test/behavior/align.zig
test/behavior/array.zig
test/behavior/bitcast.zig
test/behavior/bugs/5474.zig
test/behavior/math.zig
test/behavior/sizeof_and_typeof.zig
test/behavior/slice.zig
test/behavior/struct.zig
test/behavior/var_args.zig

stage2 AArch64: misc improvements

---

doc/langref.html.in
lib/std/math/round.zig
lib/std/meta.zig
lib/std/multi_array_list.zig
lib/std/special/c.zig
src/Sema.zig
src/codegen/llvm.zig
src/type.zig
src/value.zig
test/behavior/cast.zig
test/behavior/floatop.zig
test/behavior/math.zig
test/cases.zig

See individual commit messages for more information.

stage2 float fixes

---

src/arch/arm/CodeGen.zig
src/arch/arm/Emit.zig
src/arch/arm/Mir.zig
test/behavior/array.zig
test/behavior/bitcast.zig
test/behavior/bugs/11181.zig
test/behavior/bugs/1421.zig
test/behavior/bugs/2692.zig
test/behavior/bugs/5474.zig
test/behavior/bugs/828.zig
test/behavior/cast.zig
test/behavior/fn.zig
test/behavior/math.zig
test/behavior/optional.zig
test/behavior/ptrcast.zig
test/behavior/sizeof_and_typeof.zig
test/behavior/slice.zig
test/behavior/struct.zig
test/behavior/struct_contains_null_ptr_itself.zig
test/behavior/type.zig
test/behavior/type_info.zig
test/behavior/var_args.zig
test/behavior/void.zig

This get some more behavior tests passing.

stage2 ARM: misc improvements

---

test/behavior/error.zig
test/behavior/for.zig
test/behavior/generics.zig
test/behavior/math.zig
test/behavior/merge_error_sets.zig
test/behavior/namespace_depends_on_compile_var.zig
test/behavior/null.zig
test/behavior/pointers.zig
test/behavior/ptrcast.zig
test/behavior/slice.zig
test/behavior/type_info.zig
test/behavior/var_args.zig

If my math is right, this means we're at about 64% passing :sunglasses:

CBE: enable more tests that are currently passing

---

src/arch/arm/CodeGen.zig
test/behavior/align.zig
test/behavior/array.zig
test/behavior/basic.zig
test/behavior/optional.zig
test/behavior/struct.zig

also implements slice_elem_ptr, ptr_elem_ptr

stage2 ARM: remove MCValue.embedded_in_code

---

src/codegen/c.zig
test/behavior.zig
test/behavior/bugs/3779.zig
test/behavior/tuple.zig

Very simplistic but it seems to get the job done, at least good enough for `test/behavior/tuple.zig` to pass. Let me know of any comments.

CBE: add support for tuples

---

src/Sema.zig
test/behavior/bitreverse.zig

Also, a small refactoring attempt. Feel free to throw that commit away if it's not the way to go!

stage2: implement `@bitReverse` for vectors

---

lib/std/debug.zig
lib/std/os.zig
lib/std/os/test.zig
src/crash_report.zig

Fixes #8357
I couldn't really test it locally, both because I don't have a system with a failing `sigaction`.

fix sigaction double panic

---

src/arch/riscv64/CodeGen.zig
src/arch/riscv64/Emit.zig
src/arch/riscv64/Mir.zig

I also implemented some more basic codegen while I was at it

stage2 RISCV64: remove MCValue.embedded_in_code

---

lib/std/fmt.zig
lib/std/os/linux.zig
src/codegen/llvm.zig
test/behavior.zig
test/behavior/bugs/11227.zig
test/behavior/bugs/1277.zig

stage2 llvm: fix lowerDeclRefValue for function aliases

---

test/behavior/slice.zig

This is from discussions from #11249. The stage2 behavior is correct and
is strictly more accurate, so we'd prefer to keep it. In that case, I
modified the behavior tests to have the conditional between
stage1/stage2 and get this test passing.
I didn't do the `S.doTheTest()` pattern because the comptime vs runtime types are slightly different, though functionally the same.

stage2: slice behavior test passes, just has diff behavior from stage1

---

src/arch/arm/CodeGen.zig
test/behavior/optional.zig

* more error union support
* `@maximum`, `@minimum`
* cmp for optional pointers
Next large milestone is `switch`.

stage2 ARM: move closer to test runner output working

---

src/Sema.zig

I don't know if there is a way to add automated tests for these, I just manually tested comparing stage1 to stage2.

stage2: runtime safety checks for slicing

---

src/Sema.zig
src/Zir.zig
src/type.zig
test/behavior/switch.zig
test/behavior/type.zig
test/behavior/union.zig

`zig2 build --help` is still blocked by (at least) #11297, #11293, #11306 and `TODO: get max errors in compilation` but this gets us a little closer.

stage2 fixes on the way to `zig2 build --help` working

---

src/arch/x86_64/CodeGen.zig

mirrors the changes in the ARM, AArch64, and RISCV64 backends
cc @kubkon

stage2 x86_64: remove MCValue.embedded_in_code

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
test/behavior/optional.zig

also mirrors some other miscellaneous improvements from ARM

stage2 AArch64: remove MCValue.embedded_in_code

---

src/Air.zig
src/Liveness.zig
src/Sema.zig
src/arch/aarch64/CodeGen.zig
src/arch/arm/CodeGen.zig
src/arch/riscv64/CodeGen.zig
src/arch/wasm/CodeGen.zig
src/arch/x86_64/CodeGen.zig
src/codegen/c.zig
src/codegen/llvm.zig
src/print_air.zig
test/behavior/select.zig

@andrewrk I noticed that `airShuffle` does a bit of coercion to allow arrays as input, does that apply here as well?

stage2: implement `@select`

---

src/Sema.zig
src/codegen/llvm.zig

With Value handling comptime vectorization, we can start simplifying Sema.

stage2: simplify mul_add

---

src/arch/aarch64/Emit.zig
src/arch/arm/Emit.zig
src/arch/riscv64/CodeGen.zig
src/arch/riscv64/Emit.zig
src/arch/x86_64/CodeGen.zig
src/arch/x86_64/Emit.zig
src/codegen.zig
src/link.zig
src/link/Dwarf.zig
src/link/Elf.zig
src/link/MachO.zig
src/link/MachO/Atom.zig
src/link/MachO/DebugSymbols.zig

dwarf: add debug info for error sets and error unions

---

build.zig
src/Sema.zig
src/value.zig

stage2: check arg count before types

---

src/Air.zig
src/Sema.zig
src/arch/aarch64/CodeGen.zig
src/arch/arm/CodeGen.zig
src/arch/riscv64/CodeGen.zig
src/arch/x86_64/CodeGen.zig
src/codegen/llvm.zig

With this `zig2 build -Dskip-install-lib-files` works (on my machine) (most of the time).
`-Dskip-install-lib-files`  due to #11340.

stage2: handle assembly input names

---

lib/std/testing.zig
lib/std/zig/parser_test.zig

Adds a function that allows checking for memory leaks (and other problems) caused by allocation failures by taking advantage of the FailingAllocator and inducing failure at every allocation point within the provided `test_fn` (based on the strategy employed in the Zig parser tests, which can now use this function).
Below is the function's giant doc comment in a more readable form:
---
Exhaustively check that allocation failures within `test_fn` are handled without
introducing memory leaks. If used with the `testing.allocator` as the `backing_allocator`,
it will also be able to detect double frees, etc (when runtime safety is enabled).
The provided `test_fn` must have a `std.mem.Allocator` as its first argument,
and must have a return type of `!void`. Any extra arguments of `test_fn` can …

Add `std.testing.checkAllAllocationFailures`

---

lib/std/crypto/25519/curve25519.zig

This is the x25519 counterpart to `edwards25519.clearCofactor()` that we already had.
It is useful to check for low-order points in protocols where it matters and where clamping cannot work, such as PAKEs.

crypto/x25519: implement clearCofactor()

---

lib/std/event/wait_group.zig

In 008b0ec5e58fc7e31f3b989868a7d1ea4df3f41d the `std.Thread.Mutex` API was changed from `acquire`/`release` to `lock`/`unlock`. `std.event.Lock` still uses `acquire`/`release`.
`std.event.WaitGroup` is using `std.Thread.Mutex`, though, not `std.event.Lock`, and it was not updated to use `lock`/`unlock`, and so compilation failed prior to this change.
Signed-off-by: Stephen Gutekanst <stephen@hexops.com>

std.event.WaitGroup: fix compilation (acquire->lock, release->unlock)

---

src/link.zig

This should mitigate <https://github.com/ziglang/zig/issues/8362> on Windows.
I previously have another PR trying to fix it in `renameatW` <https://github.com/ziglang/zig/pull/11413>. I figured if that change is a bit risky then this one should be a good enough workaround for now. As comment suggested `renameTmpIntoCache` logic is temporary and I think it's ok to add platform workaround in here?
I've locally tested this a bit and it seems to work for me. I'll locally test this with <https://github.com/ziglang/zig/pull/11365> and see if it fixes zig build related issues on Windows.
Thanks in advance!

fix `link.renameTmpIntoCache` on windows when dest dir exists.

---

lib/std/build.zig

Currently transitive system library dependencies are always linked using
linkSystemLibrary() and therefore pkg-config even if they were
originally specified with linkSystemLibraryName() instead. This causes
problems in practice for projects needing total control over exactly
what library is linked, such as the mach game engine.
This is fixed by keeping track of whether libraries are to be linked
with pkg-config or not and holding off on actually running pkg-config
until after transitive dependency resolution in LibExeObjStep.make().
This also fixes a separate issue with the pkg-config handling that could
cause partial application of pkg-config flags if the first part of the
pkg-config output parses correctly but there is an error later on. This
error isn't always fatal as we fall back to …

std.build: Fix transitive linkSystemLibraryName() dependencies

---

src/test.zig

Compile error test cases can now be given as a sequence of files: `foo.1.zig, foo.2.zig, foo.3.zig, etc...`
As recommended in #11288, "foo.zig" may not co-exist with "foo.X.zig", and no numbers may be skipped in the test sequence. This implementation also has a couple of slight differences:
- Test indices are 1-indexed
- A suffix of ".X.zig" is used instead of "_X.zig"
1-indexing was chosen so that it will match update progress number "[x/N]" reported in the log. I've also updated a few other places where we report the update number, to make sure it is consistently 1-indexed.
If you'd prefer to make this 0-indexed or to use the original `_` suffix, let me know and I'm happy to update the changes :+1:

Add file support for incremental compile error tests

---

lib/std/fs/test.zig

Realized this case wasn't explicitly tested in the current test code when writing https://github.com/ziglang/zig/pull/11413#issuecomment-1095571208.
Also split the "Dir.rename directories" test into 3 tests:
- General rename of a directory
- Rename of a directory onto an existing empty directory
- Rename of a directory onto an existing non-empty directory
The only actually new case here is the "rename onto an existing empty directory", but splitting the tests this way made them much more understandable.

std/fs/test.zig: Add test for renaming a dir onto an empty dir

---

lib/std/bounded_array.zig

After working with some other data types like std.ArrayList, it seems like std.BoundedArray should have also have a writer interface. It's a simple change and it makes the APIs feel more consistent IMO.

std/bounded_array.zig: Add Writer interface

---

src/link/Elf.zig

* support `--strip` option - when the user passes `--strip` option on the command line, we do not emit any debug info by skipping initializing the internal `Dwarf` module.
* check symtab section header's size when writing globals - without this, it may happen we write the globals without extending the symtab section header's size. This can potentially lead to clobbering some data in the file, or simply omitting the globals from the symtab when displaying with support tooling such as `readelf`.

elf: support `--strip` option and set symtab size when writing globals

---

lib/std/c.zig
lib/std/c/tokenizer.zig
lib/std/special/c.zig
src/AstGen.zig
src/clang.zig
src/codegen/llvm.zig
src/codegen/llvm/bindings.zig
src/translate_c.zig
src/translate_c/ast.zig
src/zig_clang.cpp
src/zig_clang.h
test/behavior/optional.zig

```sh-session
$ zig build -Denable-llvm
$ zig2 build -p build-stage3
$ cat a.zig
const stderr = std.io.getStdErr();
stderr.writeAll("Hello, world!\n") catch {};
}
$ build-stage3/bin/zig run a.zig
Hello, world!
```
LLVM backend needs some adjustments still.
Closes #11375

Make self hosted compiler capable of building itself

---

lib/std/array_hash_map.zig

array hash map: fix getOrPutAdapted on Managed array hash map

---

lib/std/Thread/Futex.zig
lib/std/atomic.zig
lib/std/c/dragonfly.zig
lib/std/c/freebsd.zig
lib/std/c/openbsd.zig

- Use the native futex apis available on BSD systems
- Optimizes the userspace pthread implementation of futex
- Introduces `std.atomic.cache_line` for avoiding false sharing
- More comments on stuff

std.Thread.Futex improvements

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
src/arch/aarch64/bits.zig
test/behavior/basic.zig
test/behavior/math.zig
test/behavior/truncate.zig

A first step towards getting arithmetic overflow instructions working on AArch64.

stage2 AArch64: truncation support

---

lib/std/mem.zig

Adds a concatZ to match joinZ et al, useful when dealing with C apis expecting null termination.

std.mem: add concatWithSentinel

---

src/codegen/c.zig
test/behavior/array.zig
test/behavior/fn.zig

Hi, I've done my best to fix #11368, but there are a few things I'm uncertain about:
- how do I add test cases for the C backend? I have a test case and verified manually that this fixes it, but just adding it in `test/behavior/bugs` didn't actually seem to compile the C output.
- is there a better way to tell if we're in a function argument? I just passed in an enum to `renderValue`, but that adds a lot of noise to the rest of the code.
Thanks and sorry for my ignorance.

C backend: Fix array declarations

---

src/stage1/all_types.hpp
src/stage1/analyze.cpp
src/stage1/codegen.cpp
src/stage1/ir.cpp
test/behavior.zig
test/behavior/packed-struct.zig
test/behavior/struct.zig

I added all the test cases I found across various issues like: #2627, #10104 and #3133. This is my first contribution to zig and it took me a month to figure this much and fix it all so if I messed it up I want to know, just please be gentle :)

stage1: Fix packed structs (#2627, #10104)

---

src/Sema.zig
src/TypedValue.zig
src/value.zig
test/behavior/slice.zig

Stage2: fix slice field modification at comptime

---

lib/std/segmented_list.zig

Currently, the SegmentedList only has an `iterator` function, which requires the list to be available through a mutable pointer. Sometimes the user may only have a constant pointer to the list, so I added in a second variant, `constIterator` which creates an equivalent iterator, returning constant pointers to list elements instead of mutable ones.
Usage of `constIterator` is equivalent to `iterator`, and in fact both those iterators now share most of their implementations through an internal generic struct instantiated into `SegmentedList(T).Iterator` and `SegmentedList(T).ConstIterator`.

std.SegmentedList: add constIterator

---

src/arch/x86_64/CodeGen.zig

Handle spilling of CF flags set with an overflow call.
Add saving stack offset to memory.

x64: handle CF flags spilling in overflow calls

---

lib/std/builtin.zig
src/codegen/llvm.zig
src/stage1/all_types.hpp
src/stage1/analyze.cpp
src/stage1/codegen.cpp
src/stage1/ir.cpp

Add Win64 calling convention

---

lib/compiler_rt.zig
lib/compiler_rt/ceil.zig
lib/compiler_rt/cos.zig
lib/compiler_rt/exp.zig
lib/compiler_rt/exp2.zig
lib/compiler_rt/fabs.zig
lib/compiler_rt/floor.zig
lib/compiler_rt/fma.zig
lib/compiler_rt/fmax.zig
lib/compiler_rt/fmin.zig
lib/compiler_rt/fmod.zig
lib/compiler_rt/log.zig
lib/compiler_rt/log10.zig
lib/compiler_rt/log2.zig
lib/compiler_rt/round.zig
lib/compiler_rt/sin.zig
lib/compiler_rt/sincos.zig
lib/compiler_rt/sqrt.zig
lib/compiler_rt/tan.zig
lib/compiler_rt/trunc.zig
src/Sema.zig
src/stage1/ir.cpp
test/behavior/cast.zig

compiler-rt: avoid symbol collisions with Windows libc

---

lib/std/build.zig
test/standalone.zig
test/standalone/issue_11595/build.zig
test/standalone/issue_11595/main.zig
test/standalone/issue_11595/test.c

stdlib: escape backslashes and double quotes in Builder response file

---

lib/std/os/linux/io_uring.zig

Fixes #11382. Tested on ArchLinux 5.17.5-arch1-1.

io_uring cancel test must tolerate CQ reordering

---

src/test.zig

While calling `next` an error can occur while parsing the file.
However, we don't set the filename that is currently being processed, until `next` is completed successfully.
This means that for invalid test names, the wrong filename was displayed in the panic message.
The fix is to retrieve the correct filename when an error occurs and then set the filename appropriately.

stage2: Improve test harness error handling

---

lib/std/Thread.zig
lib/std/heap.zig
src/Air.zig
src/Liveness.zig
src/Sema.zig
src/arch/aarch64/CodeGen.zig
src/arch/arm/CodeGen.zig
src/arch/riscv64/CodeGen.zig
src/arch/sparc64/CodeGen.zig
src/arch/wasm/CodeGen.zig
src/arch/x86_64/CodeGen.zig
src/codegen/c.zig
src/codegen/llvm.zig
src/print_air.zig
src/value.zig
test/behavior/align.zig
test/behavior/basic.zig
test/behavior/cast.zig
test/behavior/eval.zig
test/behavior/pointers.zig

See individual commit messages for more information.

stage2: bug fixes towards more behavior tests passing

---

src/link/Wasm.zig

wasm-linker: add -mwasm64 linker parameter for wasm64 target

---

src/AstGen.zig
src/Sema.zig
src/TypedValue.zig
src/Zir.zig
src/print_zir.zig
src/type.zig
src/value.zig
test/behavior/call.zig
test/behavior/cast.zig
test/behavior/sizeof_and_typeof.zig

See individual commit messages

stage2 bug fixes aimed towards more behavior tests passing

---

src/arch/arm/CodeGen.zig

`MCValue.cpsr_flags` replaces `MCValue.compare_flags_{signed,unsigned}`. This simplifies a lot of stuff and enables an `MCValue` to represent only the overflow bits in the CPU (previously, it was only possible to represent a register + the overflow bits combined).

stage2 ARM: Introduce MCValue.cpsr_flags

---

src/arch/arm/CodeGen.zig
src/arch/arm/Emit.zig
test/behavior/underscore.zig
test/cases/recursive_fibonacci.zig

Some handling of register_c_flag/register_v_flag was incorrect.

stage2 ARM: fix recursive fibonacci

---

src/arch/aarch64/abi.zig
src/arch/arm/abi.zig
src/arch/riscv64/abi.zig
src/arch/sparc64/abi.zig
src/arch/x86_64/abi.zig
src/register_manager.zig

Blocker #11680 has been closed :tada:

regalloc: use StaticBitSet internally

---

lib/std/priority_queue.zig

When the replacement node is smaller than its parent, we need to sift
up instead of sifting down.

std.PriorityQueue: fix missing siftUp in remove

---

lib/std/os/linux/io_uring.zig

This implements [automatic buffer selection](https://lwn.net/Articles/815491/) for `io_uring`.
The current api of `read` and `recv` is not great when using automatic buffer selection, we have to write relatively ugly code like this:
```zig
var slice: []u8 = "";
slice.len = 128;
var sqe = try ring.read(0xdfdfdfdf, fd, slice[0..], 0);
sqe.flags |= linux.IOSQE_BUFFER_SELECT;
sqe.buf_index = group_id;
```
because `read` takes a slice and gives its `ptr` and `len` to the kernel via [these fields](https://github.com/ziglang/zig/blob/master/lib/std/os/linux.zig#L3503-L3504).
This is the reason why I added `read_raw` and `recv_raw` which take a `?[*]u8` and a separate length, so we can write code like this instead:
```zig
var sqe = try ring.read_raw(0xdfdfdfdf, fd, null, buffer_len, 0);
sqe.flags …
```

io_uring: implement automatic buffer selection

---

lib/std/fmt/parse_float.zig
lib/std/fmt/parse_float/parse_float.zig

I inspected the code for #11713 but only found some minor issues, that we may want to fix.

Boyscout parse float

---

doc/langref.html.in

Fix grammatical error

---

src/arch/aarch64/CodeGen.zig
test/behavior/align.zig
test/behavior/array.zig
test/behavior/basic.zig
test/behavior/bitcast.zig
test/behavior/bitreverse.zig
test/behavior/bugs/11165.zig
test/behavior/bugs/11181.zig
test/behavior/bugs/11213.zig
test/behavior/bugs/1421.zig
test/behavior/bugs/394.zig
test/behavior/bugs/4560.zig
test/behavior/bugs/7187.zig
test/behavior/byteswap.zig
test/behavior/cast.zig
test/behavior/comptime_memory.zig
test/behavior/error.zig
test/behavior/eval.zig
test/behavior/fn.zig
test/behavior/fn_delegation.zig
test/behavior/generics.zig
test/behavior/optional.zig
test/behavior/pointers.zig
test/behavior/sizeof_and_typeof.zig
test/behavior/slice.zig
test/behavior/struct.zig
test/behavior/type.zig
test/behavior/type_info.zig
test/behavior/union.zig
test/behavior/void.zig

stage2 AArch64: complete genTypedValue

---

lib/std/os.zig

* Document deviation from Linux man page, which is identical to musl.
Man page wants always enabled user-provided abort handlers.
Worst case logic bug, which this can introduce:
+ user disables SIGABRT handler to prevent tear down to last safe
state
+ abort() gets called and enables user-provided SIGABRT handler
+ SIGABRT tears down to supposed last safe state instead of crash
+ Application, instead of crashing, continues
* Pid 1 within containers needs special handling.
- fatal signals are not transmitted without privileges,
so use exit as fallback
* Fix some signaling bits
* Add checks in Debug and ReleaseSafe for wrong sigprocmask

std.os: ported signal handling in abort() from musl

---

lib/std/io/bit_reader.zig
lib/std/io/stream_source.zig
lib/std/math/big/rational.zig
lib/std/net.zig
lib/std/net/test.zig
lib/std/priority_queue.zig
lib/std/simd.zig
src/AstGen.zig
src/Sema.zig
src/codegen/llvm.zig
test/behavior/error.zig

This gets `zig2 build test-std` to a point where it builds and runs successfully, but fails 39 tests.
Stage1 `2139 passed; 33 skipped; 0 failed.` vs stage2 `2016 passed; 51 skipped; 39 failed.`
Closes #11798

`zig2 build test-std` finale

---

lib/std/math/log2.zig

Since `@clz` is undefined for `comptime_int` and Zig does not provide `@fls` (find-last-set), `log2` for comptime integers needs to be computed algorithmically.
This change replaces the existing implementation with a basic binary search
The benefit is that the added tests no longer hit the default backward branch quota of 1000 :+1:

std.math: Add O(log N) implementation of `log2(x)` for `comptime_int`

---

src/arch/aarch64/CodeGen.zig

Follows 9747303d16dfca61316a292d1e05ac901191e3a3 for AArch64

stage2 AArch64: introduce MCValue.condition_flags

---

src/AstGen.zig
src/Sema.zig
src/Zir.zig
src/test.zig
src/type.zig
test/behavior.zig
test/behavior/bugs/6781.zig
test/behavior/defer.zig
test/behavior/eval.zig
test/cases/compile_errors/incompatible sub-byte fields.zig

See individual commit messages for more information.

stage2: enhancements aimed at more behavior tests passing

---

src/arch/wasm/CodeGen.zig

Implements the following instructions:
- `@byteSwap` (<= 32 bit)
- `@divTrunc`
- `@divFloor`
- `@divExact`
- `@ceil`
- `@floor`
- `div_float`
This also implements division for signed integers.
Once the PR for compiler-rt support is ready, the above mentioned instructions will enable `f16` and a lot of the tests will be enabled also.

stage2: wasm - float/signed division & more

---

lib/std/bit_set.zig
lib/std/tz.zig
src/Sema.zig
src/value.zig
test/behavior/array.zig

Stage2: fixes for bugs found while looking for miscompilations

---

lib/std/debug.zig

Before this commit, the passed in length would always be given to the `RtlCaptureStackBackTrace` call. Now we always give the length of the actual buffer we're using (the `addr_buf_stack` size of 32 or the passed in length if it's larger than 32; this matches what the doc comment says the function was meant to be doing as well).
This was causing empty stack traces for things like the GeneralPurposeAllocator leak checking.
Fixes #6687
---
Test code:
```zig
test "leak" {
var alloc = try std.testing.allocator.alloc(u8, 8);
_ = alloc;
}
```
Before:
```
Test [1/1] test "leak"... [gpa] (err): memory address 0x1af1a1f0000 leaked:
All 1 tests passed.
1 errors were logged.
1 tests leaked memory.
```
After:
```
Test [1/1] test "leak"... [gpa] (err): memory address …
```

Fix stack traces with non-null `first_address` on Windows

---

lib/std/crypto/25519/field.zig
lib/std/os/linux/arm64.zig
lib/std/os/linux/i386.zig
lib/std/os/linux/mips.zig
lib/std/os/linux/powerpc.zig
lib/std/os/linux/powerpc64.zig
lib/std/os/linux/riscv64.zig
lib/std/os/linux/sparc64.zig
lib/std/x/os/net.zig
src/Module.zig
src/codegen/llvm.zig
src/stage1/codegen.cpp
src/target.zig

See individual commit messages.

stage2 fixes towards standard library tests passing

---

lib/std/mem.zig

Peeking is a useful operation on tokenizers.
I'm unsure whether this would make sense for `SplitIterator(T)` as well. Any opinions?

std.mem: add peek() to TokenIterator(T)

---

lib/std/crypto/ecdsa.zig

The `Ecdsa.PublicKey` type is not a direct alias for a curve element.
So, use the inner field containing the curve element for serialization.
Add some serialization/deserialization tests by the way.
Reported by @except -- Thanks!

crypto.sign.ecdsa: fix toCompressedSec1()/toUcompressedSec1()

---

src/AstGen.zig
test/cases/variable_shadowing.10.zig

Fixes #11939.
Also added a test case for this to prevent regression.

AstGen: fix catch payoad checking for shadowing

---

src/Sema.zig
src/stage1/ir.cpp
test/cases/recursive_inline_function.1.zig

Sema: Add a note on @evalBranchQuota() when branch limit exceeded

---

src/stage1/ir.cpp
test/behavior.zig
test/behavior/bugs/12033.zig

stage1: Fix seg-fault when slicing string literal with sentinel

---

lib/std/build.zig

Replaced warn messages to use std.log.[info|warn|err] instead of std.debug.print.

use std.log for logging

---

src/stage1/analyze.cpp

stage1: fix typo in analyze.cpp

---

src/codegen/llvm.zig

I wanted to try an alternative workaround that affects the in-memory representation, since a store is where the mis-optimization occurs (https://godbolt.org/z/Ehbxz7471)
At least on my machine, this appears to resolve #11450

stage2 LLVM: Change optional non-null field to i8

---

lib/std/zig/system/NativeTargetInfo.zig

Since we know the offset, we may as well read starting there. Still expects
rpath to fit in 4096 bytes; that might be worth fixing in the future.
Fixes issue #12112

Read dynstr starting at rpath offset

---

lib/std/fmt.zig

I'm new to this. Am I going about it the right way, not changing the API of fmtIntSizeDec and fmtIntSizeBin themselves? I'm confused about the API, is this how it's meant to be used?
```zig
const fmt = std.fmt;
const debug = std.debug;
const io = std.io;
var stdout = io.getStdOut().writer();
try fmt.fmtIntSizeBin(10000).format("", fmt.FormatOptions{.width = 12, .alignment = .Center}, stdout);
// debug.print("{s}", .{result});
}
```
(It currently prints `9.765625    KiB     `. I assume the intended behavior would be to put no space inbetween the number and `KiB` and center the concanetation?)
Edit: nevermind my question about the API. I think I figured out how it's meant to be used, I didn't realize the format placeholders had that much …

Fix #9184: Support fmtIntSizeDec/fmtIntSizeBin FormatOptions

---

lib/std/simd.zig

The idea behind this is using the register capabilities in safe amounts,
there is still some consideration to be done.
+ Fixed compile error using std.Target.<arch>.featureSetHas
+ X86 MMX and "3DNOW" 64 bits register usage considered for vector size
+ Added ARM Neon recommened usage of 128 bits (The size of the register)
+ Added AARCH64 Neon and SVE for 128 bits. SVE could use in theory up to
2048 bits, but found only evidence of functional 512 bits on a super
computer, decided on using 128 bits as a safety
+ Added Altivec recommendation of using the 128 bits long register
+ Using MIPS msa 2x64bits capabilities, usage of 64 bits registers for MDMX
systems, need testing on how using bigger values affect performance
+ Using V extension on RISC-V, which is extendable via instructions, …

SIMD size suggestions: suggestions code now compiles, added more architectures

---

src/Sema.zig
src/codegen/c.zig
src/codegen/llvm.zig
test/behavior/error.zig
test/behavior/eval.zig
test/cases/compile_errors/array_init_invalid_elem_count.zig
test/cases/compile_errors/dereferencing_invalid_payload_ptr_at_comptime.zig

Sema: fix loading and storing of optional pointers represented as pointers

---

doc/langref.html.in

This PR documents Pointer Arithmetic.
Closes #10995

docs: Pointer Arithmetic

---

lib/std/os/linux.zig

Add a bunch of new flags and register opcodes, taken from [liburing](https://github.com/axboe/liburing/blob/c2d1207cc310d41c0f5fe23ce36a13ffa84189d6/src/include/liburing.h).

add more io_uring flags

---

lib/std/json.zig

Expose 2 functions from std.json.  These functions take a slice of bytes
and forward them to a given writer as a JSON encoded string.
The use case I have for this is in a custom JsonStringWriter.  This writer
takes data and automatically encodes it as JSON string characters and
forwards it to an underlying writer.  I use this JsonStringWriter in
combination with std.fmt.format to go directly from a format string/arg
pair to JSON.  This way I don't have to format my string into a separate
buffer first and encode it afterwards, which avoids the need to create
a temporary buffer to hold the unencoded but formatted string.

std.json: expose encodeJsonString and encodeJsonStringChars

---

src/Sema.zig
test/cases/compile_errors/import_of_missing_package.zig

report better error for package not found in stage2

---

lib/std/testing.zig
test/cli.zig
test/compare_output.zig
test/standalone/empty_env/main.zig
test/standalone/load_dynamic_library/main.zig

std: compile error on invalid testing allocator usage

---

doc/langref.html.in
lib/std/build.zig
lib/std/crypto/phc_encoding.zig
lib/std/fmt.zig
lib/std/x/os/net.zig
src/Cache.zig
src/Compilation.zig
src/link/MachO.zig
src/link/MachO/Atom.zig
src/link/Wasm.zig
src/link/Wasm/Object.zig
src/main.zig
src/register_manager.zig
src/translate_c.zig

#12160 with fixups from #12203
Closes #11753

std.fmt: require specifier for unwrapping ?T and E!T

---

lib/std/zig/c_translation.zig
src/translate_c.zig
src/translate_c/ast.zig
test/behavior/translate_c_macros.h
test/behavior/translate_c_macros.zig
test/run_translated_c.zig
test/translate_c.zig

translate-c: take address of functions before passing them to @ptrToInt

---

ci/zinc/linux_test.sh
src/AstGen.zig
src/codegen/llvm.zig
src/codegen/llvm/bindings.zig
test/behavior/fn.zig
test/behavior/packed-struct.zig
test/behavior/union.zig
test/run_translated_c.zig

Contains 3 bug fixes and 2 disabled tests, extracted into #12263 and #12264.

CI: test-run-translated-c with stage3

---

src/translate_c.zig
src/translate_c/ast.zig
test/run_translated_c.zig

translate-c: use correct number of initializers for vectors

---

src/codegen/llvm.zig

This change provides a basic implementation of #2349 for stage2.
There's still quite a lot of work before this logic is as complete as [what's in Clang](https://github.com/llvm/llvm-project/blob/b3645353041818f61e2580635409ddb81ff5a272/clang/lib/CodeGen/CGStmt.cpp#L2304-L2795), especially considering that we don't account for any target-specific constraints at all. Before we round things out though, we should probably wait until there's a clearer picture for constraints in Zig's dedicated ASM syntax
As a bonus, this also fixes a bug with how we were handling `_` identifiers in stage 2.

stage2 LLVM: Pass inline assembly outputs directly when not targeting memory

---

src/Sema.zig
test/behavior/type.zig

Sema: fix reify Fn alignment and args

---

lib/std/builtin.zig
src/Sema.zig
test/cases/compile_errors/reify_type_for_tagged_union_with_extra_union_field.zig
test/cases/safety/array slice sentinel mismatch non-scalar.zig
test/cases/safety/array slice sentinel mismatch vector.zig

Sema: add safety for sentinel slice

---

lib/std/crypto/25519/ed25519.zig

The next revision of the specification is going to include a context string in the way blinded scalars are computed.
See:
https://github.com/cfrg/draft-irtf-cfrg-signature-key-blinding/issues/30#issuecomment-1180516152
https://github.com/cfrg/draft-irtf-cfrg-signature-key-blinding/pull/37

crypto.sign.ed25519: include a context string in blind key signatures

---

lib/std/enums.zig

This PR makes directEnumArrayLen public
closes #8875

std.enums: make directEnumArrayLen public

---

lib/docs/main.js

autodoc: Run through prettier formatter with default settings

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
src/arch/aarch64/bits.zig

Should unblock https://github.com/ziglang/zig/pull/12228 from the AArch64 side

stage2 AArch64: fixes for removing builtin.stage2_arch

---

lib/std/builtin.zig
src/AstGen.zig
src/Sema.zig
test/stack_traces.zig

See individual commit messages for more information.

several improvements to error return tracing in the self-hosted compiler

---

src/Sema.zig
test/behavior/eval.zig

Sema: fix expansion of repeated value

---

lib/std/zig/tokenizer.zig

fix: disallow newline in char literal

---

src/Sema.zig
test/cases/compile_errors/compile_time_null_ptr_cast.zig
test/cases/compile_errors/compile_time_undef_ptr_cast.zig

stage2: add compile error for compile-time ptrCast from null to non-optional pointer

---

lib/std/array_list.zig
src/link/MachO.zig
src/link/MachO/Atom.zig
src/link/MachO/Object.zig

link.MachO: use accurate alignment attribute on pointers

---

src/arch/wasm/CodeGen.zig

This introduces 2 new features:
- By default leave values on the stack for shared functionality (such as `binOp`), which means we allocate less locals as we can re-use operands directly when it's on the top of the stack. If the result needs to be re-used multiple times, we can force it into a local using `toLocal`. 
- Free locals and allow them for reuse. This means that when a temporary local was created, we can manually free it so it can be reused at a later stage, also reducing the total amount of locals we're allocating.
The next step is to hook this into liveness analysis. Although I've started implementing that locally, there are some hurdles to overcome that will benefit the other backends also. More on this in one of the next compiler meetings.
Some stats:
Instructions size on …

stage2: wasm - reuse (temporary) locals

---

lib/std/hash/auto_hash.zig

I applied the change suggested in #12423. I also noticed that the switch seemed redundant since it just passes through the strat in either case, so I collapsed it to the else branch.

Fix #12423: auto_hash not hashing arrays of slices uniquely

---

src/Sema.zig
test/cases/compile_errors/exact division failure.zig
test/cases/compile_errors/float exact division failure.zig
test/cases/compile_errors/shrExact_shifts_out_1_bits.zig

add compile errors for comptime `@shrExact` and `@divExact` failures

---

lib/std/zig/tokenizer.zig

Just a few minor things that have been bothering me a little the few times I wanted to make some changes in this file.

tokenizer: cleanups

---

src/translate_c.zig
test/translate_c.zig

Fixes https://github.com/ziglang/zig/pull/12443#issuecomment-1220316053

fix(translate-c): fix off-by-one for leading zeroes

---

lib/std/io/reader.zig

* Add readIntoBoundedBytes
* Add readBoundedBytes
I keep re-implementing these functions in variations of "util.zig" files, and it would be nice if they were instead just part of the API.

std.io.Reader: bounded array functions

---

test/behavior/void.zig

stage2: Reference to void constants

---

lib/std/coff.zig
test/run_translated_c.zig

coff: do not pull in std.log into coff.zig definitions

---

test/behavior/packed-struct.zig

Closes #3091
Sorry I naively deleted the previous repo, so I opened again the PR. Requested changes by @kubkon done :)

Add behavior test coverage for nested packed struct field access

---

lib/std/Thread.zig

See issue #12690

---

src/link/Coff.zig
src/link/Coff/Atom.zig

This means we can request ASLR on by default as other COFF linkers
do. Currently, we write the base relocations in bulk, however,
given that there is a mechanism for padding in place in PE/COFF
I believe there might be room for making it an incremental operation
(write base relocation whenever we add/update a pointer that would
require it).

coff: write base relocations for the dynamic linker

---

src/Sema.zig
src/main.zig

Fix panic when the dependency is missing in #12694.

fix panic when the dependency is missing

---

src/autodoc/render_source.zig

autodoc: highlight target line

---

lib/std/zig/parser_test.zig
lib/std/zig/render.zig

Is there a test suite for zig-fmt?

Fix #12617: zig fmt removing module comments

---

src/Module.zig

Currently, `zig build-exe -fno-emit-bin --verbose-air src/main.zig`
results in no output at all. With this refactor, it dumps AIR
and then exits without invoking LLVM, as expected

build-exe: allow combination of -fno-emit-bin and --verbose-air

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/x86_64/CodeGen.zig
src/arch/x86_64/Emit.zig
src/link/Coff.zig
src/link/Coff/Atom.zig
src/link/MachO.zig
src/link/MachO/Atom.zig
src/link/MachO/DebugSymbols.zig
src/link/MachO/dead_strip.zig

See each commit description for details.

Self-hosted backends and linkers refactor: x86_64 + aarch64 + macho + coff

---

build.zig
lib/std/process.zig
lib/std/testing.zig
lib/test_runner.zig
src/main.zig
src/test.zig

Move std.testing.zig_exe_path into build options

---

src/main.zig

* search upwards, if no build.zig is found
* if this fails or any error occurs, fallback to global zig-cache
Closes #11672

place zig-cache directory next to build.zig

---

src/arch/sparc64/CodeGen.zig
src/arch/sparc64/Mir.zig
src/arch/sparc64/bits.zig
test/behavior/error.zig
test/behavior/math.zig
test/behavior/packed-struct.zig
test/behavior/struct.zig

The usual batch of Air lowerings and other sparc64 backend-related changes.
Didn't manage to do much this time but at least I managed to cut out a lot of `airBinOp`-related lowerings.

stage2: sparc64: Another batch of Air lowerings, bugfixes, etc.

---

lib/std/array_list.zig

std.ArrayList.ensureTotalCapacity: check for integer overflow

---

lib/std/array_hash_map.zig
lib/std/array_list.zig
lib/std/base64.zig
lib/std/build.zig
lib/std/builtin.zig
lib/std/crypto/25519/edwards25519.zig
lib/std/fmt.zig
lib/std/hash_map.zig
lib/std/log.zig
lib/std/math.zig
lib/std/math/complex.zig
lib/std/mem.zig
lib/std/multi_array_list.zig
lib/std/priority_dequeue.zig
lib/std/priority_queue.zig
src/Autodoc.zig

std: remove deprecated API for the upcoming release

---

lib/build_runner.zig
lib/std/build.zig
src/AstGen.zig
src/Compilation.zig
src/Module.zig
src/Sema.zig
src/Zir.zig
src/main.zig
src/print_zir.zig
src/test.zig
src/value.zig
test/behavior.zig
test/behavior/bugs/12786.zig
test/behavior/bugs/12794.zig
test/behavior/bugs/12801-1.zig
test/behavior/bugs/12801-2.zig
test/behavior/eval.zig
test/behavior/generics.zig
test/cases/compile_errors/comptime_continue_to_outer_inline_loop.zig
test/cases/compile_errors/comptime_store_in_comptime_switch_in_runtime_if.zig
test/cases/compile_errors/top_level_decl_dependency_loop.zig

Second attempt at #11533 with feedback from previous review and self hosted compiler meeting.

stage2: add referenced by trace to compile errors attempt #2 (+ some fixes)

---

lib/std/macho.zig
src/arch/aarch64/Emit.zig
src/arch/x86_64/Emit.zig
src/link/Coff.zig
src/link/Dwarf.zig
src/link/Elf.zig
src/link/MachO.zig
src/link/MachO/Atom.zig
src/link/MachO/DebugSymbols.zig
src/link/MachO/Object.zig
src/link/MachO/Relocation.zig
src/link/MachO/dead_strip.zig
src/link/MachO/zld.zig

Turns out, I was wrong in collapsing incremental with full/one-shot linking contexts. While this deduplicated some code paths, it merged the contexts too much making it very hard to experiment on the incremental linker in isolation which is a big drawback since the incremental codepath is largely unfinished and bound to change wildly in the next couple of months. Therefore, with this PR I have started the process of separating the contexts enough to be able to experiment on either context in isolation without worrying about the other one.
With that out of the way, I am pleased to announce that the rewritten incremental MachO linker now is indeed incrementally allocating space in the final binary, committing `Decl` code as it's generated by the codegen, and storing only static and dynamic …

macho: rewrite incremental linker, and init splitting of linking contexts

---

src/arch/arm/CodeGen.zig
src/arch/arm/Emit.zig
src/arch/arm/Mir.zig

- fix rewrite of `sp` subtraction in prologue
- fix debug info for arguments passed in registers (e.g. C calling convention)

stage2 ARM: minor fixes

---

doc/langref.html.in

Decided to proof-read the langref today.

Fix minor langref typos

---

src/Sema.zig
test/cases/compile_errors/stage2/reified_enum_field_value_overflow.zig

Closes #12908.
Note: stage1 still does this.

Sema: check that reified enum field values fit tag type

---

lib/std/meta.zig

This is a minor gripe I've had with `FieldEnum` a couple times - this change just makes things a little more consistent, and allows functions like the following to be a little nicer:
```zig
fn getUnionField(x: U, comptime f: std.meta.FieldEnum(U)) ?std.meta.fieldInfo(U, f).field_type {
if (x != f) return null;
return @field(x, @tagName(f));
}
```
Whereas before, `x != f` would be a compile error due to it not being the correct enum, requiring extra casts.

std/meta: make FieldEnum(T) == Tag(T) for tagged unions

---

src/codegen/llvm.zig
test/c_abi/cfuncs.c
test/c_abi/main.zig

Thanks @davidgm94 for the bug report - This was very quick to find by peeking at the IR from your test.
Closes #12982

stage2: Fix multiple_llvm_int parameter passing

---

src/Sema.zig
test/cases/compile_errors/enum_value_already_taken.zig

Closes https://github.com/ziglang/zig/issues/12805

stage2: detect duplicate enum values

---

lib/std/build/CheckObjectStep.zig
lib/std/build/OptionsStep.zig

Fix `Step.cast` for `OptionsStep` and `CheckObjectStep`

Fix `Step.cast` for `OptionsStep` and `CheckObjectStep`

---

src/Sema.zig
test/behavior.zig
test/behavior/bugs/12644.zig

Closes https://github.com/ziglang/zig/issues/12644

Sema: fix resolveInferredErrorSet panic when generic inline function

---

lib/std/math.zig

`comptime_float` is also a "float type".

std.math: allow comptime_float for radiansToDegrees and degreesToRadians

---

doc/langref.html.in

docs(langref): fix outdated example

---

doc/langref.html.in
lib/std/zig/Ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig
src/AstGen.zig
src/Module.zig
src/Sema.zig
src/Zir.zig
src/arch/x86_64/Emit.zig
src/print_zir.zig
src/stage1/all_types.hpp
src/stage1/astgen.cpp
src/stage1/parser.cpp
test/behavior.zig
test/behavior/inline_switch.zig
test/cases/compile_errors/inline_underscore_prong.zig
test/cases/compile_errors/invalid_inline_else_type.zig
test/cases/compile_errors/invalid_tag_capture.zig
test/cases/compile_errors/tag_capture_on_non_inline_prong.zig

I haven't implemented `inline else` yet but otherwise this should be ready for initial comments/reviews.
Closes #7224

Implement inline switch cases

---

src/Module.zig
src/main.zig

This was an accidental misuse of the Cache API which intends to call
resolve on all file paths going into it. This one callsite was failing
to do that; fixed now.
Fixes relative file paths from making it into the global cache manifest.
See #13050

stage2: resolve file before putting them into cache

---

src/Sema.zig
test/cases/compile_errors/slice_of_pointer_must_include_end_value.zig

Sema: fix error location when casting pointer to slice

---

lib/std/compress/deflate.zig
lib/std/compress/deflate/compressor.zig

Make CompressorOptions public

---

src/stage1.zig

This is one way to fix #10506. See https://github.com/ziglang/zig/issues/10506#issuecomment-1274184313 for a complete explanation of the problem. Note that this only affects stage1 and stage2/stage3 builds that are compiled with stage1 enabled.
The easiest reproduction of the problem is just to pass a path with non-ASCII characters to `zig cc`, e.g. `zig cc -o hello.exe Кириллица\hello.c`
Before:
```
>zig cc -o hello.exe Кириллица\hello.c
?????????\hello.c:1:1: error: unable to build C object: BadPathName
```
And after this PR, it will work successfully:
```
>zig cc -o hello.exe Кириллица\hello.c
>.\hello.exe
hello
```
Closes #10506 if merged.

Windows: Fix stage1.zig's main failing to receive non-ASCII args

---

lib/std/c/darwin.zig
lib/std/os/posix_spawn.zig

std.c: fix incorrect return types

---

lib/std/event/loop.zig

Enables event loop for all darwin platforms.

enable event loop for ios, tvos, and watchos

---

lib/std/segmented_list.zig

std.SegmentedList: fix compilation error

---

lib/std/fs.zig
lib/std/fs/test.zig

Fix compile error in Dir.deleteTreeMinStackSize and add test

---

lib/std/meta.zig

Transform `if (optional) |payload| payload else` into `optional orelse`

Simplify code in std.meta.isTag

---

lib/std/os.zig

std.os: handle error.UnreachableAddress in send()

---

lib/std/os/linux.zig

From issue #10181. @cweagans can you evaluate if I'm doing this the right way? I found which ioctl it is from reading musl source.

add tcdrain on linux

---

lib/std/debug.zig

close https://github.com/ziglang/zig/issues/13186

fix `panic: integer overflow` in dumpStackTraceFromBase

---

src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
src/arch/aarch64/bits.zig

Follow-up to https://github.com/ziglang/zig/pull/12799 for AArch64

stage2 AArch64: move to new allocRegs mechanism

---

src/link/MachO/DwarfInfo.zig

macho: handle majority of DW_FORM_ values for DWARF4 in the linker

---

lib/std/crypto/bcrypt.zig

Now that std.base64 supports everything bcrypt needs to encode its parameters, we don't need to include another implementation.

crypto/bcrypt: don't reimplement base64, just use a custom alphabet

---

lib/std/crypto/ecdsa.zig

This commit adds EcdsaP384Sha256.
Some certifictes(below certs are in /etc/ssl/certs/ca-certificates.crt on Ubuntu 22.04) use EcdsaP384Sha256 to sign itself.
- Subject: C=GR, L=Athens, O=Hellenic Academic and Research Institutions Cert. Authority, CN=Hellenic Academic and Research Institutions ECC RootCA 2015
- Subject: C=US, ST=Texas, L=Houston, O=SSL Corporation, CN=SSL.com EV Root Certification Authority ECC
- Subject: C=US, ST=Texas, L=Houston, O=SSL Corporation, CN=SSL.com Root Certification Authority ECC
Ecdsa.Signature assumes that digest_length is larger than Curve.scalar.encoded_length. However, Sha256's digest_length is 32 bytes and P-384's scalar.encoded_length is 48 bytes. This commit is implemented to accept such smaller digest_length signature algorithm.
In verify(), hash …

std.crypto.sign.ecdsa: add EcdsaP384Sha256

---

lib/std/os.zig
lib/std/os/linux.zig

Add reboot syscall

---

lib/std/ascii.zig
lib/std/mem.zig

* Port Boyer-Moore-Horspool algorithm and relevant tests from std.mem.indexOfPos
* Remove TODO doc comment
* Fix/provide doc comments

Enhance std.ascii.indexOfIgnoreCase with Boyer-Moore-Horspool algorithm

---

src/Compilation.zig
src/arch/x86_64/CodeGen.zig
src/link.zig
src/link/Plan9.zig
test/cases/plan9/exit.zig
test/cases/plan9/hello_world_with_updates.0.zig
test/cases/plan9/hello_world_with_updates.1.zig

This adds
* unnamed decl support
* relocation support
Hello world now works again

Plan9: Fix The Backend

---

lib/std/mem/Allocator.zig

fix https://github.com/ziglang/zig/issues/12294
It's a small fix, I think there should not be need to add tests

Allocator: fix len_align calc in large type size case

---

lib/std/crypto/25519/ed25519.zig

Ed25519.KeyPair.fromSecretKey() didn't compile after the API changes

---

src/main.zig

Fixes regression introduced in https://github.com/ziglang/zig/commit/0b47e69b7c0aedbc142400305cda86ef58b41656
cc @mikdusan

cli: set sysroot when --sysroot option was passed

---

lib/test_runner.zig
src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
test/behavior/switch.zig

Includes implementations for more AIR instructions as well as a few bug fixes

stage2 aarch64: enable printing test results in the test runner

---

lib/std/zig/c_translation.zig
src/translate_c.zig
src/translate_c/ast.zig
test/behavior/translate_c_macros.h
test/behavior/translate_c_macros.zig
test/translate_c.zig

Should fix #13346
Needs testing -- running out of RAM on my machine for this...

Translate-C Remainder Macro Fix

---

lib/std/io.zig
src/arch/aarch64/CodeGen.zig
src/arch/aarch64/Emit.zig
src/arch/aarch64/Mir.zig
src/link/Coff.zig

We were working on this today during my stream, and while we didn't manage to get it into a successfully linking state, we were really close! I have since fixed the remaining bits, and voila:
```
PS C:\Users\kubko\dev\examples\incremental> cat exit.zig
assert(true);
}
fn assert(ok: bool) void {
if (!ok) unreachable;
}
PS C:\Users\kubko\dev\examples\incremental> ../../zig/stage3/bin/zig.exe build-exe exit.zig -fno-LLVM -fno-emit-implib -fno-unwind-tables
PS C:\Users\kubko\dev\examples\incremental> ./exit.exe
PS C:\Users\kubko\dev\examples\incremental> echo $LASTEXITCODE
0
```

aarch64,coff: lift-off!

---

src/link/MachO/zld.zig
test/link.zig
test/link/macho/bugs/13457/build.zig
test/link/macho/bugs/13457/main.zig

macho: do not zero-out file if there are no nonzerofill sects 

---

src/codegen/llvm.zig
test/behavior/union.zig

llvm: implement packed unions

---

lib/std/math.zig

Finished what was missing in #10281.
I wrote this using `@select(.., i>0, 1, 0)` instead of the proposed `@intTofloat(.., @bitCast(.., i > 0))`.
Since this implementation also works for ints, I decided to merge them.
To ensure that this doesn't introduce performance regressions in the integer version, I checked using godbolt and [both versions indeed generate the same assembly](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYgATKVpMGoAF55gpJfWQE8Ayo3QBhVLQCuLBiADMAVlInABk8BkwAOU8AI0xifQB2UgAHVAVCewZXDy9fAJS0uwEQsMiWGLi9ROtMWwyhAiZiAizPb38rTBtChnrGgmKI6NiEqwamlpz2hTH%2B0MGy4cqASitUd2Jkdg40BmmAamn0PYBSHwARPYABPBYUpohjvT1Dx70l04AhY40AQW%2BfpLuKJ7Hb7ABqNUkeBO5yuENsJAg0j2eB8b0%2B/3%2BgOBDFQoVocz2VAYBwsDAA8rR0BAKHtjABPAj0p …

Implement `std.math.sign` for float vectors.

---

lib/std/c.zig

Implements [`pthread_sigmask`](https://man7.org/linux/man-pages/man3/pthread_sigmask.3.html).

pthread_sigmask

---

lib/zig.h
src/codegen/c.zig

Fixes some C warnings and errors on gcc 11.3.0.

C backend: unblock progress on #13560

---

lib/std/math/big/int.zig
lib/std/math/big/int_test.zig

This is an implementation of `popCount()` for `big.int.Const` that requires no copying or allocation.
The motivation for this was to improve #13552 so that it doesn't have to copy the maximum possible bigint value in order to use `popCount()`, significantly lowering the stack size required.
There may be an established or more efficient algorithm, I just used my imagination here.
The result is a usize, unlike the `Mutable` implementation where the result is another bigint. This will never be an issue in practice because if a bigint has a higher bit count than can be represented by usize, it already can't be held in memory.
I updated the bigint test to check 0, 1, and various positive/negative numbers, including those whose bit counts cross the border of multiples of `Limb`. This revealed …

std.math.big.int: implement popCount() for Const

---

src/Sema.zig
src/value.zig
test/behavior/bugs/12891.zig

relate https://github.com/ziglang/zig/pull/12901

Sema: optimizing compare comptime float with int

---

src/codegen/c.zig

This reduces the size of the output file by quite a bit:
```
$ master/bin/zig test test/behavior.zig -Itest -ofmt=c -femit-bin=test.old.c
$ branch/bin/zig test test/behavior.zig -Itest -ofmt=c -femit-bin=test.c
$ ls -l test.*
test.c:     10180670 bytes
test.old.c: 12682809 bytes
```

c backend: Output string literals for array init of bytes

---

lib/std/os/windows.zig

os: windows: fix unhandled error

---

src/arch/arm/CodeGen.zig

adapted from AArch64 backend
- remove redundant `new` from `binOpRegisterNew` name
- fix mul_with_overflow

stage2 ARM: misc fixes

---

src/Module.zig
src/Sema.zig
src/codegen/llvm.zig
src/codegen/llvm/bindings.zig
src/main.zig
src/print_air.zig
src/print_zir.zig
src/type.zig
src/value.zig
src/zig_llvm.cpp
src/zig_llvm.h
test/behavior/basic.zig
test/behavior/cast.zig
test/behavior/type_info.zig
test/c_abi/cfuncs.c
test/c_abi/main.zig
test/cases/compile_errors/array_init_invalid_elem_count.zig
test/cases/compile_errors/global_variable_stored_in_global_const.zig
test/cases/compile_errors/inttoptr_non_ptr_type.zig
test/cases/compile_errors/missing_struct_field_in_fn_called_at_comptime.zig

Stage2 bug fixes

---

lib/zig.h
src/codegen/c.zig
src/codegen/llvm.zig
src/target.zig
test/behavior/vector.zig

92% -> 93% behavior tests passing
related:  #13633

C backend: start implementing vectors

---

lib/std/zig/parse.zig

If a parse node is reserved but never set the node remains uninitialized and can crash tools doing a linear scan of the nodes (like ZLS) when switching on the tag.

Bug fix: Prevent uninitialized parse nodes

---

lib/std/os/linux/bpf.zig

Returning a bool allows to conveniently use it as the condition of a while loop.
Also remove restriction that ST cannot be double-word. While imm is only 32-bit, this value is extended into a 64-bit memory location.

linux.bpf: expose map_get_next_key

---

src/arch/wasm/CodeGen.zig
src/arch/wasm/abi.zig
src/codegen.zig
src/link/Wasm.zig
test/behavior/bitcast.zig
test/behavior/bugs/12776.zig
test/behavior/bugs/9584.zig
test/behavior/enum.zig
test/behavior/packed-struct.zig
test/behavior/struct.zig

Implements packed structs in the Wasm backend where the backing integer is smaller or equal to 64 bits.

stage2: Wasm - Implement packed structs

---

lib/zig.h
src/codegen/c.zig
test/stage2/cbe.zig

CBE: eliminate zig_void

---

lib/zig.h
src/codegen/c.zig
src/link/C.zig
test/behavior/align.zig
test/behavior/basic.zig
test/behavior/bugs/12680.zig
test/behavior/bugs/3112.zig
test/behavior/bugs/529.zig
test/behavior/optional.zig
test/behavior/struct.zig

cbe: pass more behavior tests

---

lib/std/meta.zig

Empty structs would previously result in a compilation error.

std: add a special case for empty structs in meta.FieldEnum.

---

build.sh
lib/std/array_hash_map.zig
lib/std/hash_map.zig
src/arch/wasm/CodeGen.zig
src/codegen/c.zig
src/codegen/llvm.zig
src/link/C.zig
test.sh
test/behavior/math.zig
test/behavior/vector.zig

This is #13764 opened against master to run the CI checks.

C backend: reuse locals but respect loops to pass behavior tests

---

src/codegen/c.zig

I reverted this broken change in the other functions but forgot this one.

CBE: revert broken change that got missed

---

lib/std/atomic/queue.zig

Fixes `std.atomic.Queue.unget()`, adds doc comment, and adds additional unit tests for `unget`. 
This change fixes a bug. In the previous version `unget` would clear out the queue rather than placing the node at the beginning of it.

std.atomic.Queue: fix unget implementation and add doc

---

lib/std/bit_set.zig

Follow up to https://github.com/ziglang/zig/pull/13770, now all bit_sets implement `eql`.

std: added eql to DynamicBitSet and DynamicBitSetUnmanaged

---

lib/std/comptime_string_map.zig
lib/std/meta.zig

This is now possible due to #13627.

std.ComptimeStringMap: use tuple types

---

stage1/FuncGen.h
stage1/wasm2c.c

This didn't work out as well as I had hoped, but it still has code cleanup and C compiler compatibility wins.
* Reduce stack usage of an -O0 build of zig1 by 33%.
* Avoid compiler builtin calls.

wasm2c: reuse locals

---

doc/langref.html.in

langref: update anonymous struct naming

---

lib/zig.h

* Fixes a bunch of builtin fallbacks.
* Implements `clz`, `ctz`, and `popcount` builtin fallbacks.

zig.h: fix and add builtin fallbacks

---

doc/docgen.zig

Remove unneeded `else unreachable` in docgen.zig

---

src/codegen/c.zig

These bugs were triggered in the C backend by aarch64-specific code in `os/windows.zig`.  Intentionally not updating `zig1.wasm` yet because of upcoming changes and since aarch64-windows is not tested on master yet.

CBE: fix compiling for aarch64-windows

---

lib/std/enums.zig

Follow up to https://github.com/ziglang/zig/pull/13770
This aligns the interface of `StaticBitSet` and `EnumSet` where it makes sense.

std: added pure fns to EnumSet

---

src/tracy.zig

Update `TracyAllocator` to work with the changes to the Allocator interface.

update TracyAllocator for new Allocator changes

---

lib/std/bit_set.zig
lib/std/enums.zig

Follow up to https://github.com/ziglang/zig/pull/13783 and https://github.com/ziglang/zig/pull/13834
While reviewing the common Set interface, I realized `subsetOf`/`supersetOf` were missing on `DynamicBitSet` and `EnumMultiset`.

std: add missing subsetOf/supersetOf to DynamicBitSet and EnumMultiset

---

lib/std/mem.zig

`std.mem.split` is very useful when there is a known delimiter, but there is no easy way to split a buffer every N items.
Manually implementing this for every 3 items looks like:
```zig
const buffer = "abcdefg";
const size  = 3;
while (size < buffer.len) : (i += size) {
const end = @min(i + size, buffer.len);
const slice = buffer[i..end];
...slice is "abc", "def", "g"
}
```
`std.mem.window` simplifies that to:
```zig
const buffer = "abcdefg";
var it = std.mem.window(u8, buffer, 3, 3);
while (it.next()) |slice| {
...slice is "abc", "def", "g"
}
```
But there's more! This isn't named `splitEvery` as `std.mem.window` is more powerful. It takes in both a `size` and `advance` parameter. When they are equal, it is the same as `splitEvery`.
By choosing an `advance` smaller than …

std: add std.mem.window

---

lib/std/zig.zig

source: https://github.com/microsoft/DirectXShaderCompiler/blob/main/docs/DXIL.rst

std: add object format extension for dxcontainer

---

src/glibc.zig

In glibc.zig, there were a few instances where the zig lib dir path name incorrectly made its way into the cache namespace for various build artifacts, resulting in unnecessary rebuilds of glibc.
Closes #13619

glibc: avoid poisoning the cache namespace with zig lib dir

---

lib/std/array_list.zig

#13666 introduced a footgun when using `toOwnedSlice` with `errdefer array_list.deinit()`, since `toOwnedSlice` could retain capacity if `resize` failed, meaning it would leak without `deinit` being called. This meant that the only correct way to use `toOwnedSlice` was with `defer` instead of `errdefer` to ensure that the ArrayList would get cleaned up.
Now, toOwnedSlice will now behave similarly to how it did before #13666, in that it will always clear the ArrayList's capacity if the resize/realloc succeeds.
This also reverts commit 05890a12f532ba9d58904a14381ec174b9efe473, which was contingent on the modified toOwnedSlice behavior.
Closes #13946
---
With this fix, running the std lib tests with `std.testing.allocator` wrapped in the `NoResizeAllocator` from #13946 runs without any …

`ArrayList.toOwnedSlice`: Fix potential for leaks when using errdefer

---

lib/std/builtin.zig
lib/std/math/sqrt.zig
src/type.zig

std: make builtin.Type.{Int,Float}.bits a u16 instead of comptime_int

---

src/codegen.zig
src/codegen/llvm.zig
test/behavior.zig
test/behavior/lower_strlit_to_vector.zig

closes #13897
notes: 
* i'm sure that the test will need a name change. wasn't sure if it belongs in test/behavior or elsewhere.

codegen - allow lowering a str_lit to vector

---

lib/std/c.zig

Add missing definition for pthread_key_t
Closes #13950

c.zig: Add definition for pthread_key_t

---

test/behavior.zig
test/behavior/bugs/12571.zig

Add test for #12571

---

lib/std/std.zig

Make std.tz namespace accessible

---

src/codegen/c.zig
test/behavior/math.zig

CBE: fix bitwise not

---

src/Sema.zig
src/codegen/c.zig
test/behavior/array.zig

* Implement feature for concatenating arrays and tuples.
* Fix false positive undefined behavior error.
* Fix partially undefined string literals in the C backend.
Closes #14041
Closes #14037

Implement array and tuple concatenation feature

---

src/Sema.zig
test/behavior/struct.zig

* Add missing cases in `resolveLazyValue`.
* Fix typo in Sema.
Closes #14032

Fix #14032

---

doc/langref.html.in

langref: more explicitly document how enum overriding works

---

lib/std/build/CheckObjectStep.zig
src/link/MachO.zig
src/link/MachO/zld.zig
test/link/macho/strict_validation/build.zig
test/link/macho/uuid/build.zig

macho: ensure LINKEDIT layout follows Apple strict validation rules

---

test/behavior/array.zig
test/behavior/bugs/12571.zig
test/behavior/error.zig
test/behavior/fn.zig
test/behavior/ptrcast.zig

This closes some old stage1 bugs by adding behavior test coverage.

add more behavior test coverage 

---

src/link.zig
src/link/Coff.zig
src/link/MachO.zig
src/link/Plan9.zig
test/cases/plan9/hello_world_with_updates.1.zig

* Fix linker memory leaks found while running `zig build test-cases`.
* Add missing target to test manifest.

link: fix memory leaks

---

src/arch/aarch64/CodeGen.zig
test/behavior/error.zig
test/behavior/if.zig
test/behavior/switch.zig
test/behavior/try.zig
test/behavior/while.zig

Passes a few more behavior tests

stage2 AArch64: implement errUnion{Err,Payload} for registers

---

lib/std/process.zig

Fixes #14120 (I hope)
I'm new to zig and I made this fix semi-blindly. Happy to take suggestions about different alternatives or if there are problems.

Fix bug in WASI envmap handling.

---

ci/aarch64-linux-release.sh
ci/aarch64-macos.sh
ci/x86_64-linux-release.sh
ci/x86_64-macos.sh

Found with https://github.com/perillo/check-whitespace/.

ci: remove extra whitespace

---

src/Air.zig
src/AstGen.zig
src/Module.zig
src/Sema.zig
src/arch/aarch64/CodeGen.zig
src/arch/arm/CodeGen.zig
src/arch/riscv64/CodeGen.zig
src/arch/sparc64/CodeGen.zig
src/arch/wasm/CodeGen.zig
src/arch/x86_64/CodeGen.zig
src/codegen/llvm.zig
src/link/SpirV.zig
src/print_air.zig

Debug info fixes

---

lib/std/log.zig

There has been a few times where I have wanted to know if a specific log level and scope combination is enabled.
This PR adds:
```zig
/// Determine if a specific log message level and scope combination are enabled for logging.
pub fn logEnabled(comptime message_level: Level, comptime scope: @Type(.EnumLiteral)) bool {
....
}
/// Determine if a specific log message level using the default log scope is enabled for logging.
pub fn defaultLogEnabled(comptime message_level: Level) bool {
....
}
```

std.log: add functionality to check if a specific log level and scope are enabled

---

lib/std/math.zig

This commit adds support to absInt for integer vectors.

math: implement absInt for integer vectors

---

src/link/Wasm.zig
src/link/Wasm/Atom.zig
src/link/Wasm/Symbol.zig
test/link.zig
test/link/wasm/bss/build.zig
test/link/wasm/export-data/build.zig
test/link/wasm/export-data/lib.zig
test/link/wasm/export/build.zig
test/link/wasm/export/main.zig
test/link/wasm/function-table/build.zig
test/link/wasm/function-table/lib.zig

This improves both the incremental -and traditional in-house WebAssembly linker and ensures their feature-level match.
See the individual commit messages for a more detailed description per change.

wasm-linker: various fixes & improvements

---

src/Module.zig
src/Sema.zig
test/cases/compile_errors/error_in_comptime_call_in_container_level_initializer.zig
test/cases/compile_errors/generic_instantiation_failure.zig
test/cases/compile_errors/generic_instantiation_failure_in_generic_function_return_type.zig

I'm not sure how correct this is (especially note the added TODO) so a thorough review is needed.

Sema: do not immediately destroy failed generic instantiation

---

lib/std/heap.zig
lib/std/heap/memory_pool.zig

This is a fast memory pool implementation that can be used to rapidly allocate objects of the same type. It even outperforms the null hypothesis of just leaking the memory using a `std.heap.ArenaAllocator`.

Adds std.heap.MemoryPool

---

test/standalone.zig
tools/extract-grammar.zig
tools/gen_stubs.zig

No LLVM assertions were triggered for me.
Closes #12015
Closes #12022
Closes #12223

tools: build all tools in ci to prevent bitrot

---

build.zig

Currently llvm-linkage mode (static vs dynamic) decides linkage mode for system libstdc++/libc++ .
A previous commit only tested static mode for *BSD and netbsd was reported to not work in dynamic mode.
We now special-case freebsd, openbsd, netbsd and dragonfly for dynamic linking too.

stage3 bsd: support dynamic libstdc++/libc++

---

lib/std/zig/Ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
src/AstGen.zig
src/Module.zig
src/Sema.zig
src/Zir.zig
src/print_zir.zig
src/value.zig
test/behavior/defer.zig
test/behavior/type_info.zig
test/cases/compile_errors/nested_generic_function_param_type_mismatch.zig
test/cases/compile_errors/tuple_declarations.zig

compile error improvements and bug fixes

---

lib/std/Thread.zig

Should fix #14236
I've tested a fair bit with wine, both 32-bit and 64-bit and stuff, and so far, whatever has not worked previously doesn't work now either (and vice versa), so it seems to work fine so far.

std.Thread: make Id smaller where possible

---

lib/std/array_list.zig

Add ArrayList{Unmanaged}.fromOwnedSliceSentinel and ArrayListUnmanged.fromOwnedSlice

---

lib/std/macho.zig

We do not need more for the purpose of parsing and synthesising unwind info by the linker. If we ever decide to generate unwind info for Zig by the compiler, we can re-add packed struct defs again.

macho: port arm64 and x86_64 compact unwind defs verbatim

---

src/arch/arm/CodeGen.zig
test/behavior/pointers.zig

Also disables one behavior test which was failing

stage2 ARM: add basic debug info for locals

---

lib/std/crypto/Certificate.zig

std.crypto.Certificate: support P256 sigantures in x509 certificates

---

lib/std/os.zig
lib/std/os/windows.zig
lib/std/zig/system/NativeTargetInfo.zig
src/link.zig
src/main.zig

std.os.windows: add possible error NETNAME_DELETED of ReadFile

---

src/arch/aarch64/CodeGen.zig

This enhances the debugging experience as upon encountering a breakpoint in a function, all arguments passed as registers have already been moved to the stack, ready to be inspected by the debugger.

stage2 AArch64: move copy-register-arg-to-stack code to fn prologue

---

src/codegen/c.zig

The AIR for handling undefined arrays looks like:
```
%9 = constant([20]u8, undefined)
...
%7 = alloc(*[20]u8)
%11!= store(%7, %9!)
```
Before this change, the CBE would emit:
```
// Result of resolveInst on the RHS of the store
static zig_u8 const t1[zig_as_u64(20)] = "\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252\252";
...
zig_u8 t0[zig_as_u64(20)];
...
memset(&t0, zig_as_u8(0xaa), sizeof(zig_u8 [zig_as_u64(20)]));
```
`t1` is never actually used here, since `airStore` knows to render the store as a memset of undefined.
The array constants are now only resolved when they are not undefined, elminating all these string literals from the output.
This reduces `zig2.c` from 126.86MB to 116.71MB. `-fproc-stat-report` reports:
| File         | Total time | User …

CBE: Don't emit unused undefined array literals (optimization)

---

lib/std/build/LibExeObjStep.zig

Closes https://github.com/ziglang/zig/issues/14470

Fix producesPdbFile to account for ofmt .c

---

src/link/MachO/Dylib.zig
src/link/MachO/Object.zig
src/link/MachO/UnwindInfo.zig
src/link/MachO/ZldAtom.zig
src/link/MachO/dead_strip.zig
src/link/MachO/eh_frame.zig
src/link/MachO/zld.zig

macho+zld: fix misc alignment issues when parsing object files in archives

---

test/link/macho/uuid/build.zig

link-tests: do not hardcode UUID when testing the build with/out DI

---

src/translate_c.zig
test/translate_c.zig

Closes https://github.com/ziglang/zig/issues/14560.

translate_c: fix typedeffed pointer subtraction

---

src/Compilation.zig
test/standalone.zig
test/standalone/issue_13970/build.zig
test/standalone/issue_13970/src/main.zig
test/standalone/issue_13970/src/package.zig
test/standalone/test_runner_module_imports/build.zig
test/standalone/test_runner_module_imports/module1/main.zig
test/standalone/test_runner_module_imports/module2/main.zig
test/standalone/test_runner_module_imports/src/main.zig
test/standalone/test_runner_module_imports/test_runner/main.zig

Fixes #13970.
This fix makes test runners resolve package paths relative to the directory the test runner is in. This means it is not possible to import a file from outside the file tree root at the directory containing the test runner. It is not possible to change the directory that imports are made relative to (like for the main package with `main_pkg_path`).
This PR also allows custom test runners to import modules by copying the package table from `main_pkg` to `root_pkg` when using a custom test runner.

fix custom test runner file import path resolution

---

lib/std/json.zig
lib/std/json/test.zig

Some std.json fixes

---

src/Compilation.zig

When the following is specified
```
$ zig build-obj -fcompiler-rt example.zig
```
the resulting relocatable object file will have the compiler-rt unconditionally embedded inside.
```
$ nm example.o
...
0000000012345678 W __truncsfhf2
...
```
Fixes #14099

comp: reinstate -fcompiler-rt when used with build-obj as output

---

src/main.zig

Refs https://github.com/zigchroot/zig-chroot/issues/1

[linker] add --no-undefined, -z undefs
