ziglang/zig

doc/langref.md

Mostly rearranging the previous spec and adding new content.

Start working on lang spec

---

src/all_types.hpp
src/analyze.cpp
src/codegen.cpp
test/run_tests.cpp

rename BuiltinFnIdValueCount to BuiltinFnIdMemberCount
rename value_count to member_count

rename value_count to member_count

---

std/math.zig
std/std.zig

This PR enables printing of f64. Note that `9000000000000000000.0` is around the largest number that can be printed at the moment.

float printing mostly works

---

README.md

Add Email list

---

src/codegen.cpp

Fix for C pointer generator

---

std/os/index.zig

This just exposes the underlying os exit function.
I haven't tested this on a windows machine explicitly, but I've tested the truncation conversion logic for the status code assuming c_uint is smaller and larger than 32 bits (don't think the larger case should come up in usual practice, though).

Add exit function

---

src/tokenizer.cpp
test/compile_errors.zig

Improve invalid character error messages

---

src/c_tokenizer.cpp
src/c_tokenizer.hpp
src/ir.cpp
src/translate_c.cpp
test/translate_c.zig

Added support for exporting of C field expressions

---

std/fmt/index.zig

This is my first contribution to zig, I hope you find it useful. Feel free to change or reject as you wish.

Added format for floating point numbers. {.x} where x is the number of decimals.

---

std/linked_list.zig

Define intrusive linked lists as a special case of basic linked lists.

Intrusive linked lists

---

std/special/build_file_template.zig

Api changed in 7b57454cc11371b71097967656e19f0a1736d733.

Fix build template to match build runner changes

---

src/main.cpp
std/special/build_runner.zig

Resolves https://github.com/zig-lang/zig/issues/748

improve behavior of `zig build`

---

std/array_list.zig

at - Get the item at the n-th index.
insert - Insert and item into the middle of the list, resizing and copying
existing elements if needed.
insertSlice - Insert a slice into the middle of the list, resizing and
copying existing elements if needed.

Add ArrayList functions

---

std/unicode.zig

An initial implementation for a utf-8 view of a byte slice. A buffer alternative may be useful down the track, analogous to `&str` and `String` in Rust. I don't need this just yet, though.
I've created a new `Rune` type to indicate a unicode codepoint (or scalar value which it looks like the decoding is based on) as well. Are we happy with this name?
The module structure probably needs to be decided. How do we want to structure `unicode` and `utf8`? Do we want to include other decoding/encoding in the future (`utf-16` for windows apis) or not and if so how will this fit in? My current view was simply that `utf8.StringView` is more explanatory than `unicode.StringView` which doesn't give any detail to the underlying storage.

Add utf8 string view

---

src/translate_c.cpp
test/translate_c.zig

Generalized code that handled if statements on none boolean expressions, and made use of it in for and while translation as well. I also implement boolean not.

Translate C now handles bools better

---

doc/langref.html.in

The "old bug" is cause my last pr #839 . I'm fixing it now.

Remove unnecessary rule and re-fix an old bug

---

std/buf_map.zig

fix use-after-free in BufMap.set()

---

src/analyze.cpp
test/cases/null.zig

Allows us to create and use optional types.

Enabled optional types of zero bit types with no LLVM DI type.

---

doc/langref.html.in
src/all_types.hpp
src/codegen.cpp
src/ir.cpp
src/ir_print.cpp
std/fmt/errol/index.zig
std/math/big/int.zig
std/special/compiler_rt/comparetf2.zig
test/cases/bool.zig

also add missing docs
See #1061

remove bool to int syntax. add @boolToInt

---

doc/langref.html.in
src/all_types.hpp
src/codegen.cpp
src/ir.cpp
src/ir_print.cpp
std/cstr.zig
std/heap.zig
std/json.zig
std/macho.zig
std/mem.zig
std/net.zig
std/os/child_process.zig
std/os/index.zig
std/os/windows/util.zig
test/cases/align.zig
test/cases/cast.zig
test/cases/enum.zig
test/cases/error.zig
test/cases/misc.zig
test/cases/struct.zig
test/cases/type_info.zig
test/cases/union.zig
test/compile_errors.zig
test/runtime_safety.zig

remove "cast harder" casting syntax; add new casting builtins

---

src/bigint.cpp
test/behavior.zig
test/cases/bugs/1111.zig

Fix bigint -1 increment operation

---

src/analyze.cpp
test/compile_errors.zig

fix compiler crash for invalid enum

---

std/math/copysign.zig
std/math/fabs.zig
std/math/floor.zig
std/math/index.zig
std/math/inf.zig
std/math/isfinite.zig
std/math/isinf.zig
std/math/isnan.zig
std/math/isnormal.zig
std/math/nan.zig
std/math/signbit.zig
std/math/sqrt.zig
std/special/builtin.zig
std/special/compiler_rt/extendXfYf2_test.zig

There is still more work to be done but it's a start.

improve std.math f16 support

---

CMakeLists.txt
build.zig
src-self-hosted/errmsg.zig
src-self-hosted/introspect.zig
src-self-hosted/main.zig
src-self-hosted/module.zig
src-self-hosted/test.zig
src/main.cpp
std/atomic/index.zig
std/atomic/int.zig
std/build.zig

* introduce std.atomic.Int
* add src-self-hosted/test.zig which is tested by the main test suite
- it fully utilizes the multithreaded async/await event loop so the
tests should Go Fast
* `stage2/bin/zig build-obj test.zig` is able to spit out an error if 2 exported
functions collide
* ability for `zig test` to accept `--object` and `--assembly`
arguments
* std.build: TestStep supports addLibPath and addObjectFile

self-hosted: first passing test

---

doc/langref.html.in
src/ir.cpp

Fix builtin alignment type

---

src/ir.cpp
test/cases/cast.zig

I left a couple of comments in the commit regarding the pointer length and the alignment, let me know and I'll fix it up for the merge.

Cast to c void

---

src/translate_c.cpp

Translate-c: Check for error before working on while loop body

---

std/array_list.zig

I found this useful. I'm not sure if the appendAssumeCapacity name is the right one, so I'm open for suggestions there.

Add capacity and appendAssumeCapacity to ArrayList

---

std/os/index.zig

Fix typo in argsAlloc comment

---

CMakeLists.txt
std/dynamic_library.zig
std/os/index.zig
std/os/windows/index.zig
std/os/windows/kernel32.zig
std/os/windows/util.zig

now you can load symbols from a dll on windows.

added dynamic library loading for windows

---

std/os/windows/ole32.zig
std/os/windows/shell32.zig

just cleaning up the windows apis before starting work on adding windows support for `event/net`.

removed unneeded dll extension

---

CMakeLists.txt

Add std.meta to deployment

---

doc/docgen.zig

adds links to headers in docs.

fixes #1667

---

src/windows_sdk.cpp

build flags were preventing the code for `windows_sdk.cpp` from compiling.

fixed mingw compilation

---

std/math/powi.zig

special cases in comments didn't match code.

fixed comments

---

std/crypto/hmac.zig
std/crypto/index.zig

os.crypto: support for Blake2s256 Hmac variety

---

src/analyze.cpp

this fixes .h file locating on macos 10.14

macos: use the same code as linux to determine libc include path

---

std/rand/index.zig

Closes #1721.
Very little thought put into documentation here. I don't want to claim that anything is "faster" than anything else without some kind of benchmark evidence, but the main purpose here is to have faster implementations.

Use better rand range implementations

---

std/math/index.zig

I've often found myself looking for a function that will return the integer type to use given a min/max value
@andrewrk pointed me to https://github.com/ziglang/zig/blob/4d747d452fba0987332244c777dfd3a29d5a20bd/src/analyze.cpp#L213-L220

add std.math.IntFittingRange

---

std/linked_list.zig

Concat function similar to sys/queue.h's TAILQ_CONCAT

Add std.LinkedList.concat

---

std/fmt/index.zig

fixes https://github.com/ziglang/zig/issues/1795
This is not finished. I would like to add a few more tests, but I ran into some other problem (see below). But I welcome feedback in the meantime.
Problem: if I add this test:
```
assert((try parseUnsigned(u32, "f", 10)) == 0);
```
I get a big stack dump which looks like an error happened during the printing of another stack dump (test assertion failure):
```
Test 1/1 parseUnsigned...error: InvalidCharacter
/Users/dbandstra/zig/build/lib/zig/std/fmt/index.zig:865:25: 0x1068fa834 in _charToDigit (test.o)
if (value >= radix) return error.InvalidCharacter;
^
integer overflow
/Users/dbandstra/zig/build/lib/zig/std/mem.zig:706:16: 0x1069155ed in _join.64 (test.o)
if (buf[buf_index - 1] != sep) {
^ …
```

make parseUnsigned handle types <8 bits wide

---

src/ir.cpp
test/behavior.zig
test/cases/inttoptr.zig

Fixed intToPtr to fn type when the address is hardcoded

---

std/fmt/index.zig

#1842 have to be merged before this can work

Added formatting of function pointers

---

doc/langref.html.in
src/all_types.hpp
src/analyze.cpp
src/bigint.cpp
src/codegen.cpp
src/ir.cpp
src/ir_print.cpp
test/behavior.zig
test/cases/bitreverse.zig

I'm not sure why 39f975b is in this pull request? I think that was already pulled in.

@bitreverse intrinsic, part of #767

---

std/debug/index.zig
std/pdb.zig

Fixed source lines printing of stack traces on windows.

---

std/mutex.zig
std/os/windows/index.zig
std/os/windows/kernel32.zig

added a windows-specific mutex implementation.

added mutex for windows

---

std/os/child_process.zig

Better behaviour of ChildProcess under windows.

---

build.zig
doc/docgen.zig
src-self-hosted/compilation.zig
src-self-hosted/introspect.zig
src-self-hosted/libc_installation.zig
src-self-hosted/link.zig
src-self-hosted/main.zig
src-self-hosted/test.zig
std/build.zig
std/debug/index.zig
std/event/fs.zig
std/os/child_process.zig
std/os/get_app_data_dir.zig
std/os/path.zig
test/cli.zig
test/tests.zig

`std.os.path` was producing inline code for every unique call causing code bloat -- this is more pronounced when running a build. This patch fixes that.
for example:
```zig
export fn tester() void {
_ =  std.os.path.join(debug.global_allocator, "/a/b", "c") catch unreachable;
_ =  std.os.path.join(debug.global_allocator, "/a/b", "c", "//d", "e///") catch unreachable;
_ =  std.os.path.join(debug.global_allocator, "/", "..", "..") catch unreachable;
}
```
creates three unique join functions (`.join`, `.join.2`, `.join.3`), which call three unique posixJoin functions (`.joinPosix`, `.joinPosix.5`, `.joinPosix.6`), which calls three unique mem.join functions (`.join.7`, `.join.8`, `.join.9`). The new code only creates one function `join.4` and calls it.
```assembly
join:
push    rbp
mov …
```

std.os.path: remove code bloat from on inlined std.mem.join;

---

std/mem.zig

Like #1807 `std.mem.join` is creating code bloat due to the use of varargs. This patch fixes it but also retains the old function as `std.mem.joinInline`
edit: this is dependent on #1807

std.mem: remove varargs on join to stop excessive inlined code;

---

std/heap.zig

Make ThreadSafeFixedBufferAllocator alias FixedBufferAllocator when --single-threaded

---

src/analyze.cpp

fixed untagged unions in release modes

---

src/codegen.cpp

Add align attribute for params pointers

---

src/ir.cpp
test/stage1/behavior/type_info.zig

missed change when switching TypeInfo to use comptime_int

---

std/priority_queue.zig

This PR adds two methods for bulk insertion, either element by element (`addSlice`) or by heapifying an existing slice (`fromOwnedSlice`). These are common use-cases and they can be implemented more efficiently than repeatedly calling `add`.

PriorityQueue: add bulk insertion methods

---

CMakeLists.txt
src/target.cpp

this is currently a WIP as linking is still not working and results in a segfault with a corrupt stack.

fix zig mingw

---

src/translate_c.cpp
test/translate_c.zig

This required the following
* `__extention__`
* `({})`
* Fixing `if (0) ; else ;`
This is still missing some tests

Implemented enough of translate-c to translate assert

---

doc/langref.html.in

Fix typos around pointer usage

---

src/ir.cpp
test/compile_errors.zig

stage1: better error message when comparing against null

---

std/zig/ast.zig
std/zig/parse.zig
std/zig/parser_test.zig
std/zig/render.zig

Add doc_comments to param decl

---

src/main.cpp

The `--` double-hyphen is now used to end further `zig` processing
of command line options. All arguments after `--` will be passed
on to the executable. eg. `--help` will be passed on.
`zig run foo.zig -- --help`
closes #2148

fix zig run to accept executable args

---

src/ir.cpp
std/event/loop.zig
std/fmt.zig
std/io.zig
test/compile_errors.zig
test/stage1/behavior/align.zig

added error for implicit cast from *const T to *[1]T.

---

src/libc_installation.cpp
src/libc_installation.hpp

zig libc command now generates a libc file correctly. compiling with libc is still broken though.

fixed libc command on mingw

---

std/math/isnan.zig

We can just rely on the builtin behavior.

Simplify math.isnan

---

std/fmt.zig

Fixes #1780 
Used the test code verbatim because of #557

support comptime_int in formatInt{,Value}

---

CMakeLists.txt
std/special/compiler_rt.zig
std/special/compiler_rt/divdf3.zig
std/special/compiler_rt/divdf3_test.zig

Also adds __aeabi_ddiv for arm32 targets

Add divdf3 to compiler_rt

---

src/all_types.hpp
src/ir.cpp
src/ir_print.cpp
test/stage1/behavior/for.zig

fixed #1726

---

std/hash_map.zig

Now returns a copy of the removed kv instead of a pointer to the removed kv. The removed kv gets overwritten when shifting the hash map during the removal, so returning a pointer to it will have another kv's values in it after the return (if the hash_map was shifted during the removal).
This bug had some really nasty downstream effects in things like std.BufSet and std.BufMap where [delete would free a still in-use KV and leave the actually removed KV un-free'd](https://github.com/ziglang/zig/blob/master/std/buf_map.zig#L62-L66). EDIT: Doing some more testing to make sure this is true. EDIT#2: Confirmed, see comment below. 
Before this PR the added `testing.expect` calls would fail because `map.remove` would return a kv with `key = 1` and `value =  11`
---
Note: This is the first time …

Fix std.HashMap.remove returning incorrect KV

---

std/debug.zig
std/dwarf.zig

The stack traces are now cool enough even when intermixing Zig and C code together.

A bunch of fixes for the DWARF parser

---

README.md

I have put WASI in other. Should we have a separate WASI column?

Update wasm tiers

---

std/heap.zig

Not sure if this requires tests, and how.

Fix memory leak using DirectAllocator on Windows.

---

std/heap.zig

Fixes #2306, see that issue for a detailed explanation of the bug (especially https://github.com/ziglang/zig/issues/2306#issuecomment-485034159). This is a port of the fix that was applied to GPDA by @andrewrk : https://github.com/andrewrk/zig-general-purpose-allocator/commit/e7abd4ca7bd44f9eb134faedcfc400e7709a930c#diff-6b04986ec1c03bb0b2c30c92a206c339L255
I couldn't think of any way to write a test case for this. If anyone has any ideas, let me know.
Here's some debug printing code I was using during testing:
```zig
const aligned_addr = mem.alignForward(addr, alignment);
std.debug.warn("\nallocing n={} alignment={}\n", n, alignment);
std.debug.warn("mapped {} page(s) initially\n", std.mem.alignForward(alloc_size, os.page_size) / os.page_size);
// Unmap the extra bytes that were only …
```

fix DirectAllocator not unmapping unused pages on large alignments

---

CMakeLists.txt

fixed linking on mingw and reworked linking of libz3 on mingw.

fixed missing symbol for stack protector on mingw

---

src/parser.cpp

Allow tag expr for enum but not struct

---

src/ir.cpp
test/stage1/behavior.zig
test/stage1/behavior/bugs/2346.zig

fixes #2346
See commit for reasoning behind these changes

fixes #2346

---

src-self-hosted/stage1.zig

fix missing semicolon

---

std/os/darwin.zig

updated syntax from change introduced in fcbb742.

fixed syntax error

---

std/fmt.zig

Resolves #2361
Makes a simple self-referential struct get formatted as something like
`"S{ .a = S{ .a = S{ .a = S{ ... } } } }"`
by default.
More complex example with differing `max_depth`s (taken from the added test):
```
max_depth=0: "S{ ... }"
max_depth=1: "S{ .a = S{ ... }, .tu = TU{ ... }, .e = E.Two, .vec = (10.200,2.220) }"
max_depth=2: "S{ .a = S{ .a = S{ ... }, .tu = TU{ ... }, .e = E.Two, .vec = (10.200,2.220) }, .tu = TU{ .ptr = TU{ ... } }, .e = E.Two, .vec = (10.200,2.220) }"
max_depth=3: "S{ .a = S{ .a = S{ .a = S{ ... }, .tu = TU{ ... }, .e = E.Two, .vec = (10.200,2.220) }, .tu = TU{ .ptr = TU{ ... } }, .e = E.Two, .vec = (10.200,2.220) }, .tu = TU{ .ptr = TU{ .ptr = TU{ ... } } }, .e = E.Two, .vec = (10.200,2.220) }"
```
Some notes:
- I put the `...` cut-off before …

std.fmt: add max_depth to avoid infinite recursion from self-references

---

src/libc_installation.cpp
src/libc_installation.hpp
src/link.cpp

implement linking to libc on mingw

---

std/special/compiler_rt.zig

One more step towards a complete ARM32 port.
CC @vegecode since I see you're working on some ARM platform as well.

compiler-rt: Add __divsi3, __aeabi_idiv

---

std/os/wasi/core.zig

All the core WASI APIs are now imported.

wasi: import all core exports

---

src/main.cpp

main: change --enable-pic and --disable-pic to -fPIC and -fno-PIC
close: #2213

main: change --enable-pic and --disable-pic to -fPIC and -fno-PIC

---

src/link.cpp

This should work with:
- `export` keyword
- `@export` function
- `pub main` for WASI
Closes https://github.com/ziglang/zig/issues/2290

Switch wasm export-all to only values marked exports

---

doc/docgen.zig
doc/langref.html.in

Also, display `-target` command line arguments explicitly

docgen: support wasm and wasi

---

std/heap.zig

Currently, referencing `std.heap.wasm_allocator` on non-wasm architectures fails with `error: expected type 'u32', found 'usize'` error. That has been fixed and a better compile time error has been introduced.

WasmAllocator: compileError on non-wasm arch

---

std/os/wasi.zig

wasi: Implement read and write with err checking

---

std/crypto/chacha20.zig
std/heap.zig
std/os/linux.zig
std/os/time.zig
std/rand.zig

The stdlib is now 32-bit friendly.

std: Remove some assumptions about the host platform

---

std/io.zig
std/io/seekable_stream.zig
std/os/file.zig
std/pdb.zig

Decouple the concepts of address-space size and file size.
Closes #637

Make io offsets/sizes u64 instead of usize

---

std/io.zig
std/os/linux.zig
std/special/compiler_rt/addXf3.zig
std/special/compiler_rt/arm/aeabi_dcmp.zig
std/special/compiler_rt/arm/aeabi_fcmp.zig
std/special/compiler_rt/extendXfYf2.zig
std/zig/render.zig

The PR is best reviewed commit-by-commit.

A batch of miscellaneous fixes

---

src/ir.cpp
test/compile_errors.zig

stage1: compile error for loop expr val ignored

---

std/debug/leb128.zig

Aka, the danger of pointer arithmetic.
Closes #2485

Fix off-by-one error in LEB128 parsing

---

std/os/linux.zig

The missing `extern` means we may end up passing garbage instead of the expected parameters.

VDSO calls must use the C CC

---

src/codegen.cpp
test/stage1/behavior/struct.zig

Fix load/store of non-integer fields in packed struct

---

std/debug.zig
std/io.zig
std/os/linux/tls.zig
std/special/bootstrap.zig
std/special/c.zig
std/special/compiler_rt/extendXfYf2.zig
std/valgrind/callgrind.zig
std/valgrind/memcheck.zig

there were some some issues formatting the stdlib: #2521.

ran zig fmt on stdlib

---

doc/langref.html.in

docs: wasm

---

src/codegen.cpp

Less global state,
Cleaner code,
More comments

Move __zig_fail_unwrap locals on stack

---

std/zig/parser_test.zig
std/zig/render.zig

Correct formatting for multiline string in arrays

---

doc/langref.html.in

doc: recommend optional pointers for nullptrs instead of allowzero

---

src/link.cpp

The code assumed that the architecture-specific bits, found in the arch/
subfolder, were only overrides for the generic .c files.
Changed the logic to always include the whole architecture-specific
implementations and discard the generic ones, this way we won't exclude
files with no .c counterpart.

Stop the musl builder from skipping necessary files

---

doc/langref.html.in

docs: add comment about for else and break

---

doc/langref.html.in

docs: update for else example

---

std/hash_map.zig

* `putNoClobber()` for `put()`
* `removeAssertDiscard()` for `remove()`
As an argument for `putNoClobber()`, there were a few places in the `hash_map.zig` file itself where it better expresses intent, which I included in this PR.

Add HashMap apis that assert the common case

---

src/ir.cpp
test/stage1/behavior.zig
test/stage1/behavior/bugs/2689.zig

Fixes #2689

---

src/buffer.hpp

stage1: check for null in buf_len and buf_ptr

---

std/hash_map.zig

Added HashInt to function calls AutoHash

---

std/mem.zig

It's like `mem.join()`, but it's generic for any type, and there's no separator.
[Here's](https://github.com/thejoshwolfe/legend-of-swarkland/blob/709bc3a306a26748adc5e91d97c477807fae120a/src/gui/gui_main.zig#L94-L97) a usecase for the function.
I ran the one test that I added, and it passed.

Add mem.concat()

---

std/fmt.zig

Use inferred enum literals and split the large test case up.
The struct/enum/union case is split up as these share only the name printing but otherwise are completely separate.
No functional changes otherwise.

Small cleanup of fmt.zig

---

std/atomic/queue.zig

Fixes #2693
A queue was previously considered empty when it wasn't empty and vice versa.

Correct the isEmpty function

---

src/codegen.cpp

align (vector -> array) store to result location

---

std/zig/parse.zig
std/zig/parser_test.zig

Fix if type expr parsing

---

src/analyze.cpp

pointer to stack `Buf namespace_name` escapes to `init_tld()`

stage1: fix stack escape in add_source_file()

---

src/all_types.hpp
src/codegen.cpp
src/ir.cpp
src/ir_print.cpp
test/stage1/behavior/union.zig

Fixes #1315
This needs to be rebased, but is otherwise ready for review.

Comptime union init.

---

std/debug.zig
std/os/windows/bits.zig
std/os/windows/kernel32.zig
std/special/start.zig

added an exception handler on windows that handles stack overflow, segmentation faults, unaligned memory access faults, and illegal instructions.

added segfault handler support for windows

---

src-self-hosted/compilation.zig
src-self-hosted/llvm.zig
src/all_types.hpp
src/codegen.cpp
src/link.cpp
src/main.cpp
src/zig_llvm.cpp
src/zig_llvm.h

This PR solves #2062 
Please check if the cache stuff is correct.
Also I think that `g->function_sections` can be uninitialized, because it is only set to `false` in main.cpp, but not initialized in codegen.cpp. I'm not sure where to add the initialization of that variable. 
Edit: Close and reopened to trigger new CI build

Added function-section functionality

---

std/build.zig

forward error code in build.zig

---

src/ir.cpp
test/stage1/behavior/cast.zig

Closes #2726. Tests are pending, just wanted to get this in before I go to sleep.

Add implicit cast for *[N]T to [*c]T

---

std/os/bits/linux.zig
std/os/bits/linux/arm64.zig
std/os/bits/linux/x86_64.zig

Updates for Linux 5.2 (currently in RC).
Please only merge once the release is done.

std: add new linux 5.2 constants

---

CMakeLists.txt

fixed compilation on mingw-w64 and removed legacy dependency on libssp.

fixed compilation on mingw-w64

---

src/link.cpp

This fix closes #2064 and also fixes the building of example/hello_world/hello_libc
The issue is that Zig was always generating .def/.lib files for system libraries, even when we were linking in the crt. lld/link will search the current directory for files that match the lib names specified (even when you don't specify a relative path) which was breaking all kinds of things on Windows.
Long term we need to move .def/.lib generated files to zig-cache so it doesn't hose the lld call, but I'm not addressing that in this PR.
Edit: I also modified the msvc lib name to automatically add '.lib' as all import libraries on Windows will contain that extension. This makes the build.zig cleaner between msvc/mingw.

resolved #2064 & fixed hello_world libc build

---

std/process.zig

fixed slice length in getEnvVarOwned

---

src/ast_render.cpp
test/translate_c.zig

Fix escape sequence rendering

---

std/c/freebsd.zig
std/os.zig

Fix #2993 - use getrandom on freebsd

---

std/os/windows.zig
std/os/windows/advapi32.zig

Fix #3015 - fix RtlGenRandom function signature

---

doc/langref.html.in
src-self-hosted/ir.zig
src-self-hosted/translate_c.zig
src/parser.cpp
std/zig/ast.zig
std/zig/parse.zig
std/zig/parser_test.zig
std/zig/render.zig

Implement new async/await syntax in self-hosted compiler

---

src/ir.cpp
test/compile_errors.zig

Add compile error for incorrect atomic ordering in fence

---

doc/langref.html.in

This is intended to resolve https://github.com/ziglang/zig/issues/2834 . Let me know what you think.

added documentation for field access to C pointers

---

src/all_types.hpp
src/analyze.cpp
src/parser.cpp
std/zig/ast.zig
std/zig/parse.zig
std/zig/parser_test.zig
std/zig/render.zig

I implement parsing and rendering, @andrewrk implements the hard part of making it actually work.
I'm okay with this.

parsing and rendering of align(N) on struct fields

---

std/hash/siphash.zig

This removes the partial buffer handling from the full slice api.
`./benchmark --filter siphash --count 1024`
old
siphash(1,3)
iterative: 3388 MiB/s [67532e53a0d210bf]
small keys: 1258 MiB/s [948c91176a000000]
siphash(2,4)
iterative: 2061 MiB/s [f792d39bff42f819]
small keys:  902 MiB/s [e1ecba6614000000]
new
siphash(1,3)
iterative: 3410 MiB/s [67532e53a0d210bf]
small keys: 1639 MiB/s [948c91176a000000]
siphash(2,4)
iterative: 2053 MiB/s [f792d39bff42f819]
small keys: 1074 MiB/s [e1ecba6614000000]

Improve siphash performance for small keys by up to 30%

---

std/special/compiler_rt/comparetf2.zig
std/zig/parser_test.zig
std/zig/render.zig

I took a stab at fixing https://github.com/ziglang/zig/issues/2661.
I didn't add any extra test cases aside from the one posted in the issue. 
I ran the new `zig fmt` on std/ and committed those changes in the 2nd commit (and removed the comment linking the issue.)
Happy to make any necessary changes!
(Sorry this is a duplicate of https://github.com/ziglang/zig/pull/2836. Trying to merge upstream/master was somehow causing massive conflicts.)

zig fmt: fix nested if

---

std/fmt/parse_float.zig

Fix parsefloat exponents

---

src/analyze.cpp
test/stage1/behavior/union.zig

Fixes issue https://github.com/ziglang/zig/issues/3058
I've added a regression test as well.  If you run that test with the current zig compiler you will get a segfault.  If you run the compiler with this fix it should pass.

Fix issue 3058: zig build segfault

---

src/analyze.cpp
src/ir.cpp
test/compile_errors.zig

error message and test for alignment of variables of zero-bit types

---

doc/langref.html.in

Shorten @field documentation and add an example

---

src/ir.cpp
test/compile_errors.zig

Add compiler error when negating invalid type

---

test/stack_traces.zig

test-stack-traces: add FreeBSD

---

std/hash/cityhash.zig
std/hash/murmur.zig
std/os/bits/linux/arm-eabi.zig

The stdlib is now usable (again)

Adjust the stdlib to be 32bit compatible

---

src/ir.cpp
test/stage1/behavior/union.zig

Allow comparison between union tag and enum literal

---

src/analyze.cpp
test/compile_errors.zig

forbid opaque types in function return types

---

src/ir.cpp

Accept void argument for @cDefine value

---

src/ir.cpp

Resolve lazy arguments passed to @compileLog

---

src/analyze.cpp
test/stage1/behavior/enum.zig
test/stage1/behavior/union.zig

* Allow comptime_int as explicit enum tag type
Closes #2997

Make single-element enum default to u0

---

std/event/channel.zig
std/event/future.zig
std/event/lock.zig

Disable Channel, Future, and Lock tests for FreeBSD

---

src/analyze.cpp

I couldn't minimize the test case not to depend on the stdlib so that's a fixme for some other contributor :)
Fixes #3128

Don't forget to resolve the pointee type

---

doc/langref.html.in

Fix #3272 - update docs for boolean and example

---

src/main.cpp
std/ascii.zig
std/build.zig

* add -D CLI option for setting C macros
* add std.ascii.allocLowerString
* add std.ascii.eqlIgnoreCase
* add std.ascii.indexOfIgnoreCasePos
* add std.ascii.indexOfIgnoreCase

zig build: linkSystemLibrary integrates with pkg-config

---

src/range_set.cpp
test/compile_errors.zig
test/stage1/behavior/switch.zig

Fix computation of switch coverage

---

src/codegen.cpp
test/cli.zig

Create user-specified `output-dir`

---

src/ir.cpp
test/stage1/behavior.zig
test/stage1/behavior/fn_delegation.zig

add VarDecl support for struct-method call syntax

---

std/io/test.zig
std/os.zig

Fix llseek behavior

---

src/analyze.cpp
test/stage1/behavior/usingnamespace.zig

Closes #3316
The simple fix was enough to plug the hole :)

Don't warn about redeclaration for the same var node

---

doc/langref.html.in

Fix typo in docs

---

lib/std/special/docs/index.html
lib/std/special/docs/main.js
src/dump_analysis.cpp

Add initial support for struct fields in the docs

---

lib/std/os.zig

Found while playing with Zig and the standard library

Correct std.os.connect_async docs

---

src/ir.cpp
test/stage1/behavior/union.zig

Extern unions should not trigger active field check

---

lib/std/debug.zig
lib/std/elf.zig
src/analyze.cpp
test/stage1/behavior/align.zig

* Backtraces now work perfectly!
* Behaviour test are passing!
* The instruction selector still panics every now and then when trying to lower some fp16-related instructions :(

More RISC-V stuff

---

src/translate_c.cpp
src/zig_clang.cpp
src/zig_clang.h

Now buildable with today's [llvm](https://apt.llvm.org/) update

Periodic LLVM-10 upgrade

---

deps/lld/COFF/DriverUtils.cpp
src/link.cpp
src/zig_llvm.cpp
src/zig_llvm.h

Assemble lib files using LLVM tools instead of lld

---

lib/std/zig/parser_test.zig
lib/std/zig/render.zig

Fix struct align fmt

---

lib/std/os/uefi.zig
lib/std/os/uefi/protocols/absolute_pointer_protocol.zig
lib/std/os/uefi/protocols/edid_active_protocol.zig
lib/std/os/uefi/protocols/edid_discovered_protocol.zig
lib/std/os/uefi/protocols/edid_override_protocol.zig
lib/std/os/uefi/protocols/graphics_output_protocol.zig
lib/std/os/uefi/protocols/hii.zig
lib/std/os/uefi/protocols/hii_database_protocol.zig
lib/std/os/uefi/protocols/hii_popup_protocol.zig
lib/std/os/uefi/protocols/rng_protocol.zig
lib/std/os/uefi/protocols/simple_pointer_protocol.zig
lib/std/os/uefi/protocols/simple_text_input_ex_protocol.zig
lib/std/os/uefi/protocols/simple_text_output_protocol.zig
lib/std/os/uefi/status.zig
lib/std/os/uefi/tables/boot_services.zig
lib/std/os/uefi/tables/configuration_table.zig
lib/std/os/uefi/tables/runtime_services.zig
lib/std/os/uefi/tables/system_table.zig
lib/std/os/uefi/tables/table_header.zig

- format() method for GUIDs
- Documentation

UEFI improvements

---

lib/std/mem.zig

~~i couldn't implement the suggested alignment of 1 because that caused a compiler error.~~ nevermind, it seems to working now...

fixed #3334

---

lib/std/build.zig
lib/std/os/windows.zig

Configurable PE Subsystem

---

src/ir.cpp

I didn't manage to reduce the original test case.
Fixes #3489

Resolve lazy slice start/end values

---

src/ir.cpp
test/compile_errors.zig

Fix crash with peer type resolution & error unions

---

doc/langref.html.in
lib/std/json.zig

fix json parser crashing on empty input

---

lib/std/priority_queue.zig

More standard library documentation

Document PriorityQueue.

---

src/translate_c.cpp
test/translate_c.zig

Fix translate-c arrow deref

---

src/ast_render.cpp

part of  #3605, --verbose-ir still hits unreachable trying to print ir of https://github.com/ziglang/zig/blob/9bc4f8ea77df395b9f2407ddfa4734bb4a1c4139/lib/std/debug.zig#L1086

Fix NodeErrorSetDecl rendering

---

lib/std/special/start.zig

```zig
// $ zig run a.zig
// TODO @asyncCall of non-async function
pub const io_mode = .evented;
pub fn main() void {}
```

Make callMainAsync async

---

lib/std/event/group.zig

Simplifies using a Group.
```zig
var g = Group(Err!void).init(allocator);
g.call(someFunc, arg1);
g.wait();
```
vs
```zig
var arena = ArenaAllocator.init(allocator);
var g = Group(Err!void).init(arena);
var frame = g.allocator.alloc(@Frame(someFunc));
frame.* = async someFunc(arg1);
g.add(frame);
g.wait();
arena.deinit();
```

Allow Group to optionally manage function frames' memory

---

lib/std/target.zig

missed cast in std/target.zig

---

src/ir.cpp
src/ir_print.cpp
src/ir_print.hpp
test/stage1/behavior/union.zig

Fix initialization of union references

---

lib/std/fs.zig

Very minor fallout from: 
https://github.com/ziglang/zig/commit/5b1a492012241276a4b7539ca6664234f0629c79

Dir handling change bugfix

---

lib/std/event/future.zig
lib/std/event/rwlock.zig
lib/std/lazy_init.zig
lib/std/mutex.zig
src/ir.cpp
test/stage1/behavior/atomics.zig

Resolves some TODOs in std lib.

Support atomic operations with enums

---

lib/std/build.zig
lib/std/target.zig

Only tested on windows for now (main usecase).

build: initial support for using vcpkg libraries

---

src/codegen.cpp
test/stage1/behavior/union.zig

Update discriminant value also for zero-sized unions

---

lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
src/parser.cpp
test/stage1/behavior/array.zig

Properly parse anon literal in array

---

src/ir.cpp
test/compile_errors.zig

Catch invalid type from peer resolution

---

doc/docgen.zig
lib/std/special/docs/index.html
lib/std/special/docs/main.js
lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig
lib/std/zig/tokenizer.zig
src-self-hosted/translate_c.zig
src/all_types.hpp
src/dump_analysis.cpp
src/parser.cpp
src/tokenizer.cpp
src/tokenizer.hpp

Closes #2288
Closes #3686
```zig
//! container doc comment
/// declaration doc comment
const A = ...
```

Implement container level doc comments

---

src/range_set.cpp
test/compile_errors.zig

First this would cause the compiler to crash.
Also adds a test case.

Stage1: Add compile error for an empty switch on a integer

---

lib/std/event/fs.zig

After this there are no dependencies on event loop's allocator #3539.

Update event.fs to new event loop

---

lib/std/debug.zig

Move some functions currently under std.debug to be methods of `DwarfInfo`. This reorganisation is much needed for some upcoming PRs.
This PR is *only* moving functions around.
The only public API change is `std.debug.printSourceAtAddressDwarf` -> `std.debug.DwarfInfo.printSourceAtAddress`
Note to self: rebase #3005 if this is merged first.

refactor std/debug.zig DwarfInfo operations to be methods

---

lib/std/event/channel.zig

I found two problems with the buffer handling logic in std.event.Channel.
1. The index was being incremented past the end of the buffer, causing an out of bounds exception when placing content into the head.
2. When accessing the tail, if the index had wrapped around to 0, subtracting the length and taking the modulo only works if the buffer length is a power of 2.
The fix protects access to self.buffer_nodes by taking the index modulo self.buffer_nodes.len and an assert is added to init to detect a buffer length that is not a power of 2.
Due to not being able to run tests in evented mode, I coped the test to a standalone program to verify the failure and that the test passes with the fix.

implement correct buffer wrapping logic in std.event.Channel

---

lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
src/all_types.hpp
src/ast_render.cpp
src/codegen.cpp
src/ir.cpp
src/ir_print.cpp
src/parser.cpp

* Adiós IR nodes for global asm expressions
* The printing code has lot of duplication, feel free to address that in another PR
Let's see if it passes a CI run...

Accept comptime-known expression for asm

---

lib/std/special/docs/index.html
lib/std/special/docs/main.js

Add docs for function parameters

---

lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig

Fix zig fmt c pointer return type

---

lib/std/json.zig

fix integers parsed as floats

---

lib/std/os/uefi/protocols.zig
lib/std/os/uefi/protocols/simple_text_input_protocol.zig
lib/std/os/uefi/tables/system_table.zig

This is the patch for https://github.com/ziglang/zig/issues/3866.

fix con_in difinition and add EFI_SIMPLE_TEXT_INPUT_PROTOCOL difinition

---

lib/std/zig/ast.zig
src-self-hosted/clang.zig
src-self-hosted/translate_c.zig
test/translate_c.zig

Please feel welcome to code review, or ask for me to do additional things before merging!

Add function params, parens handling, and some infix operators to self-hosted translate-c

---

src-self-hosted/clang.zig
src-self-hosted/stage1.zig
src-self-hosted/translate_c.zig
src/codegen.cpp
src/ir.cpp
src/translate_c.cpp
src/translate_c.hpp
src/userland.cpp
src/userland.h
src/zig_clang.cpp
src/zig_clang.h
test/tests.zig
test/translate_c.zig

Translate-c self-hosted var decl and remove translate mode

---

lib/std/zig/render.zig
src-self-hosted/clang.zig
src-self-hosted/translate_c.zig
test/translate_c.zig

@kavika13 I'm going to look at translating enums next, unless you are already working on them.

Translate-c-2 structs and unions

---

doc/langref.html.in
lib/std/fmt.zig
lib/std/os/linux/tls.zig
src/codegen.cpp
src/ir.cpp
test/compile_errors.zig
test/runtime_safety.zig
test/stage1/behavior/pointers.zig

Make sure the address is aligned for intToPtr ops

---

src/analyze.cpp
src/codegen.cpp
src/zig_llvm.cpp
src/zig_llvm.h

Generate the fn pointers into the correct address space

---

lib/std/child_process.zig

Use eventfd in ChildProcess on Linux

---

src/ir.cpp
test/stage1/behavior/misc.zig

Don't assume TLS storage has a fixed address

---

lib/std/child_process.zig

We may also use the poll trick on pipes and unify the two code paths...

More eventfd stuff

---

src-self-hosted/c_tokenizer.zig
src-self-hosted/clang.zig
src-self-hosted/stage1.zig
src-self-hosted/translate_c.zig
test/translate_c.zig

Macro functions included!
```c
#define BASIC(c) (c*2)
```
```zig
pub inline fn BASIC(c: var) @TypeOf(c * 2) {
return c * 2;
}
```
Closes #3765

Translate-c-2 macros

---

doc/docgen.zig
doc/langref.html.in

langref table of contents in a separate column on large displays

---

src/analyze.cpp
src/ir.cpp
test/stage1/behavior/pointers.zig

Fixes #3497
Also fixes the mysterious crashes in #3918

Make sure the fields array is always non-null

---

src/ir.cpp
test/stage1/behavior/pointers.zig

Fix comptime evaluation of runtime array access

---

src/ir.cpp
test/stage1/behavior/type_info.zig

Fix sentinel value of opaque pointers in typeInfo

---

lib/std/c.zig
lib/std/os.zig
lib/std/os/bits/linux.zig
lib/std/os/linux.zig

Clean up linux sigprocmask, raise

---

lib/std/testing.zig

Use std.meta.eql from std.testing.expectEqual

---

src/ir.cpp
test/compile_errors.zig

Fix ptrCast of zero-sized type

---

src/analyze.cpp
src/codegen.cpp
src/ir.cpp
test/stage1/behavior/error.zig

I've also sprinkled a few `type_has_bits2` even though it's not really ergonomic :\
Closes #3994

Resolve more types as needed

---

src/zig_clang.cpp

For some reason no error message is printed/recorded even though the diagnostic object detects something went wrong, but at least now the error path is taken instead of crashing.

Don't crash when parsing invalid files

---

lib/std/build.zig

install header in separate folder

---

src/ir.cpp
test/stage1/behavior/bit_shifting.zig

Fix segfault in bit shift safety check

---

src-self-hosted/translate_c.zig
test/translate_c.zig

translate-c properly handle unused var-args

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Prefer simple ptrCast between opaque types

---

src-self-hosted/translate_c.zig
test/translate_c.zig

translate-c fix increment rendering issues

---

src-self-hosted/c_tokenizer.zig

Fix edge case in C tokenizer

---

lib/std/zig/parser_test.zig
lib/std/zig/render.zig

Let's wait for the CI to finish this time :wink:

builtin calls formatting - take II

---

src-self-hosted/c_tokenizer.zig
src-self-hosted/translate_c.zig
test/translate_c.zig

The hex literal problem was reported by @via on IRC.

Miscellaneous translate-c patches

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Closes #4054.
My only test for this was building [my game](https://github.com/thejoshwolfe/legend-of-swarkland) for windows, which worked. I didn't figure out how to run the standard test suite successfully before making this PR.

use @intCast instead of @as for shift rhs

---

src-self-hosted/clang.zig
src-self-hosted/translate_c.zig
src/zig_clang.cpp
src/zig_clang.h
test/run_translated_c.zig
test/translate_c.zig

Hopefully now all the `bool` conversions are correct.

Better _Bool translation

---

src-self-hosted/clang.zig
src-self-hosted/translate_c.zig
src/zig_clang.cpp
src/zig_clang.h
test/run_translated_c.zig
test/translate_c.zig

Preserve packed attribute in C translated struct

---

lib/std/build.zig
lib/std/special/build_runner.zig

fixed version of #3527. there may be some issues on osx or linux due to #1814.

added -- to pass args to zig build commands

---

src/ir.cpp
test/compile_errors.zig

Fix crash in struct initializer evaluation

---

src/analyze.cpp
src/ir.cpp

Nice catch @fengb ;)
Fixes #4112

Propagate more failures upwards

---

lib/std/heap.zig
lib/std/heap/logging_allocator.zig

std: fix LoggingAllocator, add simple test

---

doc/langref.html.in
lib/std/builtin.zig
lib/std/c/darwin.zig
lib/std/special/c.zig
lib/std/special/compiler_rt.zig
lib/std/start.zig
src/all_types.hpp
src/analyze.cpp
src/codegen.cpp
src/ir.cpp
src/ir_print.cpp
test/compile_errors.zig
test/stage1/behavior/misc.zig

Pros:
* We can specify default values!
* We can add more parameters without (too much) breakage!
Cons:
* You have to update your code :(
Closes #2679 as it was just a matter of a few lines of code.

New @export() handling

---

lib/std/child_process.zig

Fix windows child process creation

---

src-self-hosted/clang.zig
src-self-hosted/translate_c.zig
src/zig_clang.cpp
src/zig_clang.h
test/run_translated_c.zig

Hopefully the check is correct, it's a bit hard to formulate it in a neat way :\
Closes #4130

Handle forward-declared functions

---

src/codegen.cpp

Makes every debugger happy and closes #2685

Inform the debugger about the effective type sizes

---

src-self-hosted/clang.zig
src-self-hosted/translate_c.zig
src/zig_clang.cpp
src/zig_clang.h
test/translate_c.zig

* Handle EmptyDecls to clean up the generated code
Closes #4143

Fix unsafe cast in translate_c

---

src/errmsg.cpp

strip cwd from compile error paths

---

doc/langref.html.in

See https://github.com/ziglang/zig-spec/pull/15

docs: update grammar to remove C strings and add anon literals

---

src/ir.cpp
test/compile_errors.zig

Propagate errors in for loop bodies

---

src/ir.cpp
test/compile_errors.zig
test/stage1/behavior/call.zig

Fix @call being too eager to resolve the fn argument

---

lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig

stage2 parser: fix segfault on extern block

---

src/analyze.cpp
test/stage1/behavior/call.zig

The hashing scheme sends shivers down my spine every time I look at it (but cbf to use something nicer in stage1)
Closes #4022
Closes #3699

Fix ICE when BoundFn are passed as parameters

---

lib/std/zig/parse.zig
lib/std/zig/parser_test.zig

Fix crash on multiline library name

---

src/zig_clang.cpp

Fix garbled error messages from clang

---

lib/std/fmt.zig
src-self-hosted/translate_c.zig

Fix regression in char printing

---

lib/std/builtin.zig
src/ir.cpp
test/stage1/behavior/type_info.zig

Add struct field default value to typeinfo

---

CMakeLists.txt
CONTRIBUTING.md

This reverts commit cd062b08d01cf2c92b05ef3e96b2ff3715f29fd5.

Revert "cmake: support `make` and `make install`"

---

lib/std/hash/benchmark.zig
lib/std/hash/crc.zig

std: use non-exhaustive enums from crc module

---

src/ir.cpp
test/stage1/behavior/enum.zig

Allow @tagName on enum literals

---

src/codegen.cpp

Fixes https://github.com/ziglang/zig/issues/4272

Don't include stdbool.h for void and unreachable

---

src/codegen.cpp
src/main.cpp

- fix regression from #4186
reported in IRC by AndroidKitKat and student069

stage1: make sure to create native_libc.txt dir

---

lib/std/debug.zig

Follow the specification about what the base address is and how it can
be changed by some entries in the list itself.

Fix parsing of DW_AT_Ranges debug entry

---

src/ir.cpp
test/compile_errors.zig

More error checking for unresolved TLDs

---

lib/std/os.zig
lib/std/os/linux.zig
lib/std/os/test.zig

The base should be zero so that p_vaddr + dlpi_addr = p_vaddr

Correct dl_iterate_phdr address

---

src-self-hosted/translate_c.zig
test/translate_c.zig

translate-c: Handle fn protos wrapped in parenthesis

---

src/ir.cpp
test/stage1/behavior/async_fn.zig

_Partially fixes https://github.com/ziglang/zig/issues/4065_
This was a cargo cult from for loops:
- https://github.com/ziglang/zig/commit/ae20574d5efaa7c63d78299b761eee38515b5865
- [`229323e`](https://github.com/ziglang/zig/commit/229323e13a074e94ef8a58409c81cfd9ac807dd8#diff-476daa305f4d991c0f097fc22a1c7ad6R6523)

Add async spills to while captured variables

---

src-self-hosted/translate_c.zig
test/translate_c.zig

translate-c: Fix translation of fn pointers

---

lib/std/zig/parser_test.zig
lib/std/zig/render.zig

fmt: Fix logic to find the argument list closing )

---

lib/std/os/windows.zig
lib/std/os/windows/ws2_32.zig

Winsock errors can be an enum

---

lib/std/start.zig
src/all_types.hpp
src/analyze.cpp
src/codegen.cpp
src/link.cpp

Added the Unicode WinMain functions and attempted to leave the default behavior as-is. 
Wasn't sure if there are any tests related to this that should be updated, so looking for any feedback.

Add wWinMain and wWinMainCRTStartup to fix #4376

---

lib/std/c/tokenizer.zig
src-self-hosted/translate_c.zig
test/translate_c.zig

Translate-c float fixes

---

src/ir.cpp
test/stage1/behavior/cast.zig

Add cast between [*c]T and ?[*:0]T on fn parameter

---

lib/std/c/tokenizer.zig
test/translate_c.zig

Fix c tokenizer bug

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Translate-c improve macro cast translation

---

lib/std/json.zig
lib/std/json/write_stream.zig
lib/std/math/big/int.zig
lib/std/math/big/rational.zig
lib/std/mem.zig
lib/std/net/test.zig
lib/std/testing.zig

Migrate (more) tests from FixedBufferAllocator to testing.allocator

---

ci/srht/freebsd_script

enable passing freebsd tests

---

lib/std/c/tokenizer.zig
test/translate_c.zig

Yet another translate-c fix

---

lib/std/array_list.zig

Seemed useful to me. I'm not 100% satisfied about the name. I also tried `resizeAndFill`, but that's actually a bit different than this.

Add an appendValues method to ArrayList to append a value n times.

---

lib/std/c.zig
lib/std/os.zig
lib/std/os/test.zig
lib/std/os/windows/bits.zig
lib/std/process.zig
lib/std/start.zig
lib/std/zig/system.zig
src/os.cpp

update std lib to integrate with libc for environ

---

src/analyze.cpp
test/stage1/behavior/sizeof_and_typeof.zig

ir: Fix sizeOf comparison with ptr to zst

---

src/ir.cpp
test/stage1/behavior/slice.zig

ir: Fix array to slice conversion for zero-sized arrays

---

src/analyze.cpp
test/compile_errors.zig
test/stage1/behavior/fn.zig

ir: Allow empty inferred error sets

---

lib/std/build.zig
lib/std/crypto/benchmark.zig
lib/std/elf.zig
lib/std/hash/auto_hash.zig
lib/std/hash/benchmark.zig
lib/std/hash/cityhash.zig
lib/std/hash/murmur.zig
lib/std/hash_map.zig
lib/std/io.zig
lib/std/math/pow.zig
lib/std/math/powi.zig
lib/std/mem.zig
lib/std/special/compiler_rt/ashlti3.zig
lib/std/special/compiler_rt/ashrti3.zig
lib/std/special/compiler_rt/lshrti3.zig
lib/std/special/compiler_rt/multi3.zig
lib/std/special/compiler_rt/udivmod.zig
lib/std/testing.zig
lib/std/valgrind.zig

short std.builtin enum literals in std lib

---

src/codegen.cpp

Commit edb210905dcbe666fa5222bceacd2e5bdb16bb89 caused the docs generation
to fail, because all the type information in pass1 was already freed in
`zig_llvm_emit_output`.
Closes #4488

Fix docs generation

---

lib/std/fmt.zig
lib/std/math.zig

Fix formatting of i1 values 

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Translate-c macro comma operator

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Translate-c demote struct to opaque if unable to translate field type

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Translate-c more macro ops

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Translate-c fixes

---

lib/std/zig/system/x86.zig

Call xgetbv only if X{SAVE,RESTORE} and AVX are detected.
Closes #4670

std: Fix version detection on x86

---

lib/std/zig/system/x86.zig

Don't read from stale eax value, rework the logic a bit so that's clear
what's going on.

std: One more cpuid fix

---

src/ir.cpp
test/compile_errors.zig

Fix grammar from "C pointers cannot point opaque types"

---

lib/std/os/bits/linux.zig
lib/std/os/bits/linux/netlink.zig

We need plenty more to use netlink reasonably, feel free to wait until I have a fully-working demo, or merge piece-meal.

std: add some definitions for netlink sockets

---

lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/render.zig
src/all_types.hpp
src/analyze.cpp
src/analyze.hpp
src/ast_render.cpp
src/codegen.cpp
src/ir.cpp
src/parser.cpp
test/compile_errors.zig
test/stage1/behavior/async_fn.zig

Implement new noasync syntax

---

src/analyze.cpp
src/analyze.hpp
src/ir.cpp
test/compile_errors.zig

fix failed assert on generic fn opaque return type

---

lib/std/os/bits/linux.zig
lib/std/zig/system.zig

This should also fix the problem noticed by @Rocknest on WSL (#4689)

std: Fix detection of Linux kernel version

---

src-self-hosted/clang.zig
src-self-hosted/translate_c.zig
src/zig_clang.cpp
src/zig_clang.h
test/translate_c.zig

Closes #3756
Closes #810, the integer casting part is being done in #4688

Translate-c improvements

---

lib/std/mem.zig

implementation for proposal from: https://github.com/ziglang/zig/issues/4554

add allocSentinel function

---

lib/std/zig/ast.zig
lib/std/zig/parser_test.zig

Fix zig fmt crash on noasync block

---

lib/std/os/uefi/protocols.zig
lib/std/os/uefi/protocols/file_protocol.zig
lib/std/os/uefi/protocols/simple_file_system_protocol.zig
lib/std/os/uefi/protocols/simple_text_input_protocol.zig

add the following protocol supports:
* EFI_SIMPLE_FILE_SYSTEM_PROTOCOL
* EFI_FILE_PROTOCOL

UEFI library improvements

---

lib/std/os/uefi/protocols/file_protocol.zig

I'm sorry that I forgot 'pub' modifier in recent PR #4713

fix recent bug

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Translate-c treat C bools as ints

---

lib/std/io/serialization.zig

fix Serializer for changes made in #4710

fix Serializer to work with new OutStream API

---

lib/std/build.zig

build: Expose function-sections switch

---

lib/std/thread.zig

std: More type checks for Thread startFn return type

---

lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig
src/all_types.hpp
src/ir.cpp
src/parser.cpp
test/compile_errors.zig
test/stage1/behavior/defer.zig

ir: Allow errdefer with payload

---

lib/std/dwarf.zig

Version 3 is similar to version 2 plus more opcodes.
CC @pixelherodev

debug: Correct version check in debug_line parser

---

src/ir.cpp
test/stage1/behavior/slice.zig

ir: Prevent crash when slicing hardcoded pointer

---

lib/std/math/big/int.zig
lib/std/math/big/rational.zig

Implements Proposal https://github.com/ziglang/zig/issues/4781

Use math.Order for comparing bigints instead of i8

---

lib/std/math.zig
lib/std/special/compiler_rt.zig
lib/std/special/compiler_rt/divdf3.zig
lib/std/special/compiler_rt/divtf3.zig
lib/std/special/compiler_rt/divtf3_test.zig

Add __divtf3 to compiler-rt

---

lib/std/c.zig

* Add socketpair definition
Closes #4797

std: Fix setsockopt definition

---

lib/std/os/linux/tls.zig
lib/std/start.zig
lib/std/thread.zig
test/stack_traces.zig

For some weird-ass reason the other PR got a green check mark even though the Azure pipeline didn't start at all...

Resend of TLS touchups

---

README.md

* Homebrew has updated llvm to point to llvm@10

Fix Readme to point to llvm for brew commands

---

lib/std/fifo.zig

- Fix use of undeclared variable
- Fix documentation error for `.read([]T) usize`; it actually _does_ return the number of items read.
- Fix other doc comments that incorrectly mention 'bytes' vs 'items'.
- Normalize `writeable` to `writable`. (The more common parlance.)
- Added a test for `writeItem` since that had no test coverage.
- Add a test that ensures `read` returns the number of items rather than bytes.

Fix std.fifo.LinearFifo

---

test/compile_errors.zig

Issue fixed by an unknown commit.
closes #2687

add compile-error test for #2687

---

lib/std/hash/adler.zig

Found it while implenting PNG support in zigimg, without this fix reading basn2c16.png from [PngSuite](http://www.schaik.com/pngsuite/pngsuite.html) fails the ADLER32 checksum

Fix porting of zlib adler32 with large input

---

test/compile_errors.zig

Issue fixed by an unknown commit.
closes #3818

add compile-error test: bitcast

---

ci/azure/linux_script

- no longer install qemu via apt-get
- wget hosted tarball, extract and prepend to path

use static-qemu linux-x86_64 tarball

---

src/ir.cpp
test/compile_errors.zig
test/stage1/behavior.zig
test/stage1/behavior/slice_sentinel_comptime.zig

stage1: add compile errors for sentinel slicing

---

test/compile_errors.zig

Issue fixed by an unknown commit.
closes #4207

add compiler-error test: coerce

---

lib/std/array_list.zig
lib/std/array_list_sentineled.zig
lib/std/build.zig
lib/std/build/emit_raw.zig
lib/std/coff.zig
lib/std/debug.zig
lib/std/dwarf.zig
lib/std/fs.zig
lib/std/http/headers.zig
lib/std/io/in_stream.zig
lib/std/json.zig
lib/std/math/big/rational.zig
lib/std/net.zig
lib/std/special/build_runner.zig
lib/std/unicode.zig
src-self-hosted/libc_installation.zig
src-self-hosted/stage2.zig
src-self-hosted/translate_c.zig
test/standalone/brace_expansion/main.zig
test/tests.zig
tools/merge_anal_dumps.zig

resolves #4852
Amazingly it passed tests on my first try.

new ArrayList API

---

src/codegen.cpp

Always run detection of libc on native target
Fixes #4772

Always run detection of libc on native target

---

src-self-hosted/translate_c.zig
test/translate_c.zig

Closes #4790
Let me know if there is anything else I should do!

translate-c: RemAssign and DivAssign

---

lib/std/special/compiler_rt/atomics.zig

The v6m ISA has no way to express a CAS loop natively without turning
off the interrupts or using the kernel cmpxchg harness.
On such a platform the user has to provide a few __sync_* builtins to
satisfy the linker.

compiler-rt: Separate max size allowed for load/store and CAS

---

cmake/Findclang.cmake
cmake/Findlld.cmake
cmake/Findllvm.cmake
lib/std/os/bits/dragonfly.zig

With these changes I got zig to compile successfully from source on DragonFly (BSD). Great! I can even cross-compile Linux apps!!!! :)

Fix compile on Dragonfly

---

lib/std/json.zig
lib/std/testing.zig
src/all_types.hpp
src/ir.cpp
src/ir_print.cpp
test/compile_errors.zig
test/stage1/behavior/for.zig
test/stage1/behavior/pointers.zig
test/stage1/behavior/slice.zig

Fix missing const on address of literal

---

lib/std/debug.zig
lib/std/fs.zig
src/codegen.cpp
test/runtime_safety.zig

Please note that:
* The checks are only correct at runtime, the comptime part is such a jungle of edge cases that I got bored pretty quick with that
* ~~No tests, how the hell do you check that the boundary checks are triggered (without having to write a thousand different and separate test cases)?~~
Closes #4777
Closes #4849 by accident

Rewrite the bound checks in slice operator

---

src/ir.cpp
test/stage1/behavior.zig
test/stage1/behavior/bugs/4954.zig

fix lazy value in ir_analyze_instruction_elem_ptr

---

src/all_types.hpp
src/ir.cpp
src/ir_print.cpp
test/compile_errors.zig

Add missing error message for invalid assignment

---

lib/std/dwarf.zig

debug: Fix parsing of DWARF info for BE machines

---

lib/std/os/windows.zig
lib/std/os/windows/bits.zig
lib/std/os/windows/kernel32.zig
lib/std/os/windows/user32.zig

Some definitions created to help @JakubSzark on discord

std: add some basic windows user32 definitions

---

lib/std/os/uefi/protocols/file_protocol.zig

Fixing EFI_FILE_PROTOCOL structure difinitions in zig std library.

fix efi file protocol structure definitions

---

src/codegen.cpp
test/stage1/behavior/ptrcast.zig
test/stage1/behavior/struct.zig

* Fix packed struct alignment
* Adjust some tests

stage1: More fixes for BE targets

---

lib/std/debug.zig

* Handle FileNotFound errors when searching for .o files
* Use the STAB symbol name when everything else fails
Thanks to `hazeycode` on IRC for the report!

debug: Minor QOL improvements for osx

---

src/ir.cpp
test/compile_errors.zig

Fix missing compile errors on builtin cast functions

---

src/analyze.cpp
src/ir.cpp
test/compile_errors.zig
test/stage1/behavior/type_info.zig

Add error for non-exter variadic functions

---

lib/std/json.zig
lib/std/mem.zig
lib/std/os/bits/linux.zig
lib/std/os/bits/linux/errno-generic.zig
lib/std/os/bits/linux/netlink.zig
lib/std/os/bits/linux/riscv64.zig
lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
src/parser.cpp
test/compile_errors.zig

Disallow declarations between fields

---

src/glibc.cpp

stage1: Fix signed multiplication overflow

---

src/codegen.cpp

Thanks to @frett27 on irc for reporting the compiler would segfault when
run on ARM.

stage1: Fix wrong union access

---

src/ir.cpp
test/stage1/behavior/cast.zig

First contribution! Apologies if there's anything I'm missing.
Appears to fix #4865 . I've added a test to check for the desired behavior as well. :)

Added peer type resolution for [*]T and *[N]T.

---

lib/std/os/windows/kernel32.zig
lib/std/progress.zig
src/analyze.cpp
src/codegen.cpp

Worksforme:tm: on Wine, please test on a real Windows box before merging.

Progressbar for Windows

---

src/codegen.cpp
src/ir.cpp
test/compile_errors.zig

stage1: fix crash on accessing an array of size zero with runtime index

---

src/codegen.cpp

Pass each target feature flag separately

---

src/codegen.cpp

Add missing state to C object cache

---

lib/std/progress.zig

Progress will now use ANSI escape codes on windows for terminals that support them

---

src/all_types.hpp
src/ir.cpp

- remove unused IrInstSrcOptionalUnwrapPtr.initializing

stage1: cleanup

---

lib/std/fs.zig
lib/std/fs/test.zig

correct usages of std.fs.dir.DeleteFileError

---

ci/azure/linux_script

closes #5245
see https://github.com/ziglang/qemu-static/commit/1b41e31a5c013dea52774ba664230402eacbc75b

ci linux: bump qemu-5.0.0-z2

---

lib/std/event/loop.zig
lib/std/os.zig
lib/std/os/linux.zig

Get evented io code paths to build on macOS

---

CMakeLists.txt
deps/dbg-macro/LICENSE
deps/dbg-macro/README.md
deps/dbg-macro/dbg.h
src/all_types.hpp

I use this to debug the compiler and hope it will be useful for other developers.
Even if this PR will be rejected. ;-)

Include dbg.h to third-party libraries

---

lib/std/crypto/blake3.zig
src/ir.cpp
test/compile_errors.zig

Fix missing compile error on call assigned to const

---

doc/langref.html.in

The proposal in #1047 was implemented.

Remove reference to import type

---

src-self-hosted/translate_c.zig
test/run_translated_c.zig

Please see #5256. This is my first PR on this project and I'm new to zig so feedback is certainly welcome :)

Add scoped typedef to translate-c

---

src/ir.cpp
test/compile_errors.zig

stage1: handle all cases of invalid struct field default value

---

lib/std/build.zig
lib/std/dwarf.zig
lib/std/dynamic_library.zig
lib/std/json.zig
lib/std/net.zig
lib/std/pdb.zig
lib/std/zig/cross_target.zig
src-self-hosted/ir/text.zig
src/ir.cpp
test/compile_errors.zig

Fixes #4909.
There are probably a handful of other places where this bug has gone unnoticed and will need to be added to the last commit here. I'm running the tests again locally but they take a while and I wanted to get this pushed up for the night.
I've not touched stage1 before so if I'm violating any stylistic or DRY rules Zig tries to follow, let me know and I can make the changes.

Fix private access

---

src/bigint.cpp
test/compile_errors.zig

stage1: detect underflow in bigint_fits_in_bits

---

src/ir.cpp
test/stage1/behavior/cast.zig

Fix intToFloat on comptime_floats

---

lib/std/ascii.zig

* Add an upper case variant of `allocLowerString`
* ~~Add case-sensitive variants of `eqlIgnoreCase`, `indexOfIgnoreCase`,
and `indexOfIgnoreCasePos`~~
* Add and update docstrings on functions

Add helper functions and docstrings to ascii.zig

---

doc/langref.html.in
lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig
lib/std/zig/tokenizer.zig
src-self-hosted/translate_c.zig
src/parser.cpp

Make self-hosted parser more error tolerant

---

lib/std/crypto/aes.zig

Split AES struct into AESEncrypt and AESDecrypt

---

lib/std/io.zig
lib/std/io/multi_out_stream.zig

std: add io.MultiOutStream

---

doc/langref.html.in
lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig
lib/std/zig/render.zig
src-self-hosted/translate_c.zig
src/parser.cpp

Self-hosted parser fixes

---

lib/std/special/docs/index.html
lib/std/special/docs/main.js

www.ziglang.org docs search:
- improve search perf by batching dom mutation of list
- improve search perf by limiting the number of results shown to 200 (with possibility to show all results)
(follow up of https://github.com/ziglang/www.ziglang.org/pull/57)

docs: search perf

---

lib/std/fmt.zig

Closes #5333.
However, for many types, more work is required.

Fixes fmt padding for some types

---

lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig

Completely forgot comptime fields existed.
Closes #5357

Fix infinite loop with invalid comptime

---

lib/std/build.zig

Closes #2972
Also closes #4386

build.zig recursive dep support

---

src/analyze.cpp
src/analyze.hpp
src/ir.cpp
test/compile_errors.zig

Fixes #4934. Thank you @LemonBoy for the tip.

stage1: fix assert fail on opaque fn ptr param

---

lib/std/zig/ast.zig
lib/std/zig/parse.zig
lib/std/zig/parser_test.zig

Fix missing compile error on while/for missing block

---

src/analyze.cpp
src/analyze.hpp
src/codegen.cpp
src/ir.cpp

Add caller location tracking for asserts (ir_assert, src_assert, ir_assert_gen)

---

src-self-hosted/translate_c.zig
test/run_translated_c.zig

Translate-c use correct scope in for loop condition

---

lib/std/hash_map.zig

The reset test now permits HashMap's iterator to return key value pairs in any order, removing a reliance on a known hashing algorithm.

Remove reliance on hashing algorithm for HashMap iterator reset test.

---

src-self-hosted/codegen.zig

This extracts REX generation into its own function, allowing for simpler logic in codegen (see the diff at what was line 398 for an example).

[Stage2/Codegen] Extract REX

---

ci/azure/linux_script
ci/drone/linux_script

This should improve efficiency slightly. This likely won't result in noticable improvements, but better efficiency is a worthy goal in my opinion.

[CI] Use ninja on Azura and Drone

---

lib/std/build/translate_c.zig

Tested locally, seems to work fine :)
Closes #5098

Add include dirs to translate-c (close #5098)

---

lib/std/process.zig

This PR is a proposal for handling args iterator in WASI while preserving (most of) the common interface between platforms maintained by `process.ArgIterator` struct. I'm submitting this PR in the hope of gathering some feedback and sparking a discussion whether this approach is acceptable, and if not, where to go next, etc.
As far as actual changes are concerned, this PR pulls WASI specific implementation of args extraction from `process.argsAlloc` and `process.argsFree` into a new iterator struct `process.ArgIteratorWasi`. It also integrates the struct with platform-independent `process.ArgIterator`.
cc @andrewrk

Add ArgIteratorWasi and integrate it with ArgIterator

---

src/ir.cpp
test/stage1/behavior.zig
test/stage1/behavior/bugs/5487.zig

stage1: fix unresolved inferred error sets

---

lib/std/zig/tokenizer.zig

Fix std.zig rejecting literal tabs in comments

---

lib/std/meta/trait.zig

Added:
```zig
hasDecls(comptime T: type, comptime names: var) bool
```
Returns whether or not a struct, enum, or union has declarations matching all `names`.
```zig
hasFields(comptime T: type, comptime names: var) bool
```
Returns whether or not a struct, enum, or union has fields matching all `names`.
```zig
hasFunctions(comptime T: type, comptime names: var) bool
```
Returns whether or not a struct, enum, or union has functions matching all `names`.

Add more traits

---

lib/std/os/windows.zig

std.os.windows.OpenFile: Handle FILE_IS_A_DIRECTORY status

---

src/ir.cpp
test/compile_errors.zig

stage1: fix crash on slice byte reinterpretation

---

ci/azure/linux_script

update qemu to upstream with mremap patch

ci linux: bump qemu-5.0.0-49ee115552

---

lib/std/fs/path.zig
lib/std/math/big/int.zig
test/tests.zig

Fix a few memory errors I found while working on the new allocator interface.

fix memory errors

---

lib/std/build/emit_raw.zig
lib/std/meta.zig
tools/process_headers.zig
tools/update_clang_options.zig
tools/update_glibc.zig

Fixes #5587 and the same problem in another few places as found by trivial grepping.

Fix a few std.sort.sort invocations

---

src-self-hosted/test.zig
test/stage2/compile_errors.zig
test/stage2/zir.zig

This blocks on #5420, as currently failures are incorrectly reported as successes, causing the test case to fail.
Furthermore, I want to rewrite the rest of the old stage2 tests before marking this as ready for proper review.

[Stage2/Testing] ZIR tests for expected errors

---

src/ir.cpp

Branch handling `*[N]T` to `E![]T` is already handled in a more complete
branch handling `*[N]T` to `[]T` *and* `*[N]T` to `E![]T` so it seems
safe to remove this one.

stage1: remove obsolete branch in ir_analyze_cast

---

src/os.cpp
src/os.hpp
src/util.hpp

Use PathSpace and wide FS calls on windows in stage1

---

lib/std/array_list.zig

Deprecates `outStream` for `writer`.  Also puts u8-specific functions inside a `u8` condition.  Also adds a test for the writer interface.

ArrayList(u8) support writer interface

---

lib/std/build.zig
lib/std/build/emit_raw.zig

Hopefully this will stop it from breaking every 2 weeks.
Closes #5621

Reference emit_raw in std lib tests

---

lib/std/unicode.zig

A small but hopefully useful addition. I needed this for a tokenizer I'm writing, and it seemed general-purpose enough to include in the standard library. 
I debated returning an error when `n` is too large, but it seemed nicer to return the remainder of the string and let the caller detect if the returned slice's length is less than `n` if desired.

Add std.unicode.Utf8Iterator.peek

---

src-self-hosted/main.zig

Close source file after reading it in zig fmt

---

src/ir.cpp
test/stage1/behavior/slice.zig

Fixes #5642.
@andrewrk This fix seems too easy. Do you remember why you left the TODO?

stage1: fix concat of sliced str literals

---

src/ir.cpp
test/compile_errors.zig

Add duplicate checking for switch on types

---

src/analyze.cpp
test/stage1/behavior/type_info.zig

Copy union const values correctly

---

src/ir.cpp
test/compile_errors.zig

One-line commit covering the missing case.

Fix issue #5618

---

lib/std/debug/leb128.zig

Overhauled LEB128 functions and added writing support as requested in #5259.

LEB128 overhaul and output

---

src-self-hosted/Module.zig
src-self-hosted/test.zig
test/stage2/compare_output.zig
test/stage2/compile_errors.zig
test/stage2/test.zig
test/stage2/zir.zig

TODO:
There's still some old tests that are worth adding, but those require much larger changes to stage2 than the ones I've already done, and will be done separately.

Clean up test harness

---

lib/std/heap.zig
lib/std/mem.zig

Fixes https://github.com/ziglang/zig/issues/5741

Fix issue 5741, use after free

---

build.zig

this allows building self-hosted without having a config.h file

Don't try to find config_h if llvm is not enabled

---

lib/std/fmt.zig

Currently, the way `parseInt` works means that attempting to parse the minimum value of a signed integer will result in an overflow error, as it defers to `parseUnsigned` and negates the result. This pull request rewrites it to internally use a function that takes the sign as an argument, and uses `math.add` or `math.sub` for positive and negative integers, respectively.
Additionally, `parseInt` previously deferred parsing to `parseUnsigned` immediately, meaning that unsigned values with `+` resulted in an error. I don't see a reason to treat unsigned integer types differently from signed integer types, and if #3806 is accepted, the concept of "signedness" will no longer exist. So now all integers are treated the same; it's an overflow to parse a negative rather than a syntax error. …

Rewrite std.fmt.parseInt to fix a few issues

---

src/analyze.cpp
test/compile_errors.zig

Fix missing check on extern variables with no type

---

doc/langref.html.in

Follow-up to #5818, closes #5819

langref: Expand "if error union with optional" test case

---

src/ir.cpp
test/compile_errors.zig
test/stage1/behavior/cast.zig

Use correct cast function when doing `@floatCast` at comptime

---

lib/std/mem.zig

currently the only options are doing a second allocation and copying or
implementing this yourself.

std: add mem.joinZ

---

src/ir.cpp
test/compile_errors.zig

Check for invalid sentinel when creating pointer with `@Type`

---

doc/langref.html.in

To introduce the Zig programming language, the "Hello, world!" code sample now has
documentation to explain some of the features shown in the code sample and links to 
their relevant sections of the documentation.
Writing style goals:
* Balance writing style to keep beginner and experience programmers interested.
* Be concise: allow the rest of the documentation to clarify language features.

Explain Language Ref's Hello World

---

CONTRIBUTING.md
lib/std/mem.zig
src-self-hosted/translate_c.zig
test/stage1/behavior.zig
test/stage1/behavior/translate_c_macros.h
test/stage1/behavior/translate_c_macros.zig
test/tests.zig
test/translate_c.zig

Closes #5887
Closes #5141
Closes #4946

Translate-c support initializer lists in macros

---

src/analyze.cpp
src/analyze.hpp
src/ir.cpp
test/stage1/behavior/misc.zig

Allow non-pointer extern opaque variables

---

src/codegen.cpp

This is follow up to https://github.com/ziglang/zig/commit/8d6536b50cfd43c07c6f0264171db6ecf8e80be5

Use function attribute "frame-pointer"

---

ci/azure/windows_msvc_install

Here's the [thread](https://github.com/msys2/MSYS2-packages/issues/2050) for reference.

Add temporary fix to the CI on Win

---

lib/std/log.zig

Make the default log handler print a newline

---

ci/azure/macos_script

We don't really want to rebuild the cache in Azure...

Refactor macOS build script in Azure

---

lib/std/mem.zig

* Added `replace` for simple pre-allocated search-and-replace
* Added `replacementSize` for calculating ahead-of-time buffer sizes for
performing a safe search-and-replace
* Added `replaceOwned` for automatically allocating and performing
replacement

Add memory replacement routines

---

lib/std/math/big/int.zig
lib/std/math/big/int_test.zig

Fix bug in big.int.Mutable.toManaged() and add tests

---

lib/std/os/windows.zig

This commit adds a Zig wrapper for `kernel32.DeviceIoControl` which
applies ReactOS logic for deciding whether to use
`ntdll.NtDeviceIoControlFile` or `ntdll.NtFsControlFile` based on the
value of passed `IO_CONTROL_CODE`. The decision logic is based on the
logic found in ReactOS found in the following [link].
Thanks to @daurnimator  for finding this bit in ReactOS!
[link]: https://doxygen.reactos.org/d3/d74/deviceio_8c.html
Closes #5944

Add Zig wrapper for kernel32.DeviceIoControl

---

lib/std/os/windows.zig

As discussed in the previous PR #5945, it would be better to avoid
function pointers to syscalls and explicitly split the control
path into two function calls instead. This commit addresses that
for `std.os.windows.DeviceIoControl`.

Split DeviceIoControl path into two fn call paths

---

src/ir.cpp
test/compile_errors.zig

Add compile error for alignCasting zero sized types

---

src-self-hosted/Module.zig
src-self-hosted/codegen.zig
src-self-hosted/link.zig

This will allow for implementation of non-Elf backends without wasting
memory.

stage2: make link data in Decl into unions 

---

lib/std/dwarf.zig
lib/std/hash/auto_hash.zig
lib/std/special/c.zig
lib/std/zig/render.zig
src-self-hosted/Module.zig
src-self-hosted/translate_c.zig
src/all_types.hpp
src/ir.cpp
test/compile_errors.zig
test/run_translated_c.zig
test/translate_c.zig

Closes #665
Should this also check for variables by the same name?

Add error for unused/duplicate labels.

---

src-self-hosted/value.zig

Ran into this while working on #6056. Wasn't quite sure how best to capture this in a test case but would be happy to try given a little guidance.

stage2: fix signed <-> unsigned Value casts

---

src-self-hosted/zir_sema.zig
src/ir.cpp
test/compile_errors.zig

Hello,
This is my first PR for this project, please note that I do not know either C++ or Zig. I just wrote my first Zig program today and found this small unhandled output when passing more arguments than required or less. Do let me know if any changes is needed or can be improved.

Handle singular param count word in error messages

---

src/analyze.cpp
src/ir.cpp
test/compile_errors.zig
test/stage1/behavior/enum.zig
test/stage1/behavior/union.zig

Fixes #5314.
@andrewrk are non-exhaustive union tag types supposed to be allowed?

stage1: fix non-exhaustive enums with one field

---

src-self-hosted/codegen/wasm.zig
src-self-hosted/link/Wasm.zig
test/stage2/compare_output.zig

Details in the commit messages, see also https://github.com/ziglang/zig/issues/5985#issuecomment-675373430

stage2/wasm: do incremental compilation in-memory

---

lib/std/zig.zig

Fix some bugs and protect against more invalid cases

fixes and improvements for parseCharLiteral

---

lib/std/build.zig

This implements integer parsing for options in the builder.

builder: implement integer options

---

lib/std/build/write_file.zig

Oops, that one remained under the radar.

Fix missing init() update in std/build/write_file.zig

---

src-self-hosted/codegen.zig
src-self-hosted/codegen/arm.zig
src-self-hosted/type.zig
test/stage2/test.zig

Added `codgen/arm.zig` with some basic functionality (load/store, data processing, branching, software interrupts)
I'm creating this as a draft pull request so people can observe the progress and incrementally provide feedback.
ToDo:

Start working on stage2 ARM backend

---

src/ir.cpp
test/compile_errors.zig

Add error checks to `@Type`

---

lib/std/macho.zig
src-self-hosted/link/MachO.zig

Also, link against `libSystem` by default when targeting macOS (cc @andrewrk).

Add (empty) __TEXT segment load command

---

lib/std/mem.zig

Surprised that I couldn't find a function for this

std.mem.count

---

doc/langref.html.in

This addresses https://github.com/ziglang/zig/issues/2060
I thought it might work well as a table, but if a different format is desired I can change it.
I'm not super confident with the descriptions of the async related keywords
Also, noalias, nosuspend, and linksection I left as TODOs as they aren't documented and I'm pretty new around here haha

Add Keyword Reference section

---

lib/std/io/reader.zig

Improve io.Reader.skipBytes and add tests

---

lib/std/os/uefi/protocols/simple_text_input_protocol.zig

fix _reset in simple_text_input_protocol.zig

---

lib/std/builtin.zig
lib/std/meta/trailer_flags.zig
src/ir.cpp
test/stage1/behavior/type_info.zig

Closes https://github.com/ziglang/zig/issues/5368
Updates https://github.com/ziglang/zig/issues/6231

builtin: Add TypeInfo.StructField.is_comptime

---

lib/std/net.zig
src/ir.cpp
test/compile_errors.zig

ir: Typecheck the sentinel value in *[N:S1]T to [S2]T casts

---

lib/std/os/linux/bpf.zig

The opcodes and instructions are listed here:
https://github.com/iovisor/bpf-docs/blob/master/eBPF.md
There's one minor exception and that's because the document doesn't cover one with enough information so I'm saving that for the kernel dive I'm doing later.

BPF: Implement rest of pseudo instructions

---

lib/std/os/linux/bpf.zig

Found where the information was mapping BPF program types to the type of context that is passed the program. Also added comments for some of the map types

BPF: add some more documentation

---

lib/std/heap/arena_allocator.zig

Adds a best-effort `resize` function, that's only different from `Allocator.noResize` when the allocation is at the top of the arena.
My use case is that this makes it possible to build up strings (or other lists) using `ArrayList`s and an `ArenaAllocator` without wasting memory or needing to copy data:
```zig
$ cat example.zig
const ArenaAllocator = std.heap.ArenaAllocator;
const ArrayList = std.ArrayList;
var arena = ArenaAllocator.init(std.heap.page_allocator);
var list = ArrayList(u8).init(&arena.allocator);
for ("1234567890") |c| {
try list.append(c);
}
std.debug.print("arena uses {} bytes\n", .{arena.state.end_index});
const slice: []const u8 = list.toOwnedSlice();
std.debug.print("arena uses {} bytes\n", .{arena.state.end_index}); …
```

Add resize for arena allocator

---

lib/std/c.zig

Also:
- correct the definition of setgid
- update the existing definitions to use the uid_t/gid_t types

std: complete C definitions for uid/gid setters

---

lib/std/c.zig
lib/std/os.zig
lib/std/os/bits/linux.zig
lib/std/os/bits/linux/prctl.zig
lib/std/os/bits/linux/securebits.zig
lib/std/os/linux.zig

With this, I no longer need to link libc for a project of mine :)

std: add prctl and securebits definitions for linux/C

---

lib/std/builtin.zig
lib/std/fmt.zig
lib/std/hash/auto_hash.zig
lib/std/io/serialization.zig
lib/std/json.zig
lib/std/meta.zig
src/analyze.cpp
src/ir.cpp
test/compile_errors.zig
test/stage1/behavior/type.zig
test/stage1/behavior/type_info.zig

I hope I didn't break unions...

Implement @Type for Union

---

src/analyze.cpp
test/stage1/behavior/type.zig

Fixes https://github.com/ziglang/zig/issues/6339

stage1: fix @Type(.Union) not resolving its tag type

---

lib/std/os.zig

Introduced in 5e3fa0e94f947c632aa584b9e13bfa2fe241fae1
Whoops!

Fix compile error in os.renameatW

---

src-self-hosted/Cache.zig
src-self-hosted/DepTokenizer.zig

stage2: make DepTokenizer non-allocating

---

lib/std/os/uefi/tables/system_table.zig

uefi system_table fix

---

lib/std/fs/test.zig
lib/std/os/windows.zig

Reverts ziglang/zig#6397
I wanna see if this fixes our CI failures. An alternative fix was proposed to resolve what #6397 ventured out to achieve. See #6452 for discussion and more context.

Revert "Fix for Windows: std.os.windows.DeleteFile()"

---

lib/std/array_list.zig

Alternative PR that implements the errors mentioned in #6294.
This version fixes the bugs naively, and adds more test coverage for ArrayListUnmanaged. The reason being
for fixing the bugs is that this keeps stack traces cleaner, and it remains questionable whether the applied `defer` in
my previous PR would be optimized very well.
I haven't made the change to `std.ArrayList.deinit` in this PR, so that it is easier to merge.

Fix std.ArrayListUnmanaged + improve test coverage

---

src/stage1/ir.cpp
test/compile_errors.zig

Fixes https://github.com/ziglang/zig/issues/6459

stage1: Fix @Type(.Enum) with invalid tag_type

---

lib/std/build.zig

Fixes --linker-script unrecognized

---

src/target.zig

stage2: Build libunwind for non-msvc Windows targets

---

src/Compilation.zig

Reintroduce progress display when compiling C files

---

CMakeLists.txt

add ability to specify the build revision using cmake

---

src/codegen.zig
src/glibc.zig
src/link/Elf.zig

https://github.com/ziglang/zig/issues/5948 was marked as resolved. This PR turns `zig fmt` back on for the affected files.

Turn zig fmt back on in various src/ files

---

src/translate_c.zig
test/translate_c.zig

Closes #6554
Closes #6013
Closes #5062

Translate-c respect C operator precedence in macros

---

src/link/MachO.zig

This is no longer needed due to the way writing to the output
file is structured.
Signed-off-by: Jakub Konka <kubkon@jakubkonka.com>

stage2: Remove obsolete addPadding fn and callsites from MachO linker

---

src/stage1/analyze.cpp
src/stage1/analyze.hpp
src/stage1/ir.cpp
test/compile_errors.zig
test/stage1/c_abi/cfuncs.c
test/stage1/c_abi/main.zig

Disallow arrays in extern function parameters and return types

---

lib/std/crypto/ghash.zig

Makes GHASH about 8 times faster on ARM CPUs with AES extensions.

std/crypto/ghash: add pmull support on aarch64

---

lib/std/math/big/int.zig
lib/std/math/big/int_test.zig

* Add an optimized squaring routine under the `sqr` name.
Algorithms for squaring bigger numbers efficiently will come in a
PR later.
* Fix a bug where a multiplication was done twice if the threshold for
the use of Karatsuba algorithm was crossed. Add a test to make sure
this won't happen again.
* Streamline `pow` method, take a `Const` parameter.
* Minor tweaks to `pow`, avoid bit-reversing the exponent.

std: Add/Fix/Change parts of big.int

---

lib/std/fmt.zig

Force comptime on comptimePrint

---

src/stage1/bigfloat.cpp
test/stage1/behavior/cast.zig

The base is 2^64 and not 2^64-1.
Closes #6683

stage1: Off-by-one error in int to float conversion

---

lib/std/build.zig
lib/std/build/emit_raw.zig
lib/std/crypto.zig
lib/std/math.zig
lib/std/meta.zig
lib/std/rand.zig
lib/std/std.zig
lib/std/target.zig
lib/std/testing.zig
lib/std/zig.zig

Closes https://github.com/ziglang/zig/issues/6436.

std: move std.meta.refAllDecls to std.testing

---

src/stage1/ir.cpp
test/compile_errors.zig

stage1: Expand undefined struct/arrays when indexed

---

src/main.zig
test/cli.zig

zig fmt: write modified files to stdout not stderr

---

lib/std/special/c.zig
lib/std/special/compiler_rt.zig
lib/std/special/ssp.zig
src/Compilation.zig
src/link/Coff.zig

@MasterQ32 please check if this patch solves your problems.

Fortified libc functions

---

lib/std/build.zig

mimics the duplication of strings in `Builder` for `Pkg`. This ensures the 
lifetime of the memory backing strings in a `Pkg` struct  and the 
`Pkg.dependencies` slice is not shorter than the `Builder` that the data 
is associated with.

add Builder.dupePkg()

---

lib/std/build.zig

@jedisct1 hopefully this should fix the CI!

Disable build.zig tests on WASI since rely on cwd()

---

doc/langref.html.in

Update Documentation to use -O instead

---

doc/langref.html.in

Fix incorrect equations in langref

---

ci/azure/windows_msvc_script.bat

This seems to solve the issues we have on Azure with the MSVC pipeline.

MSVC CI: run tests individually

---

lib/std/debug.zig
lib/std/os/bits/linux.zig
lib/std/start.zig
lib/std/target.zig
test/stack_traces.zig

Check out the commit message for more info.
I didn't add the qemu tests as I'm afraid of making the CI timeout, Travis offers ppc64le hosts that may come in handy here.

Some ppc64 stuff

---

lib/std/build.zig

This will get them into std lib docs.

std: reference more declarations in std.build

---

lib/std/process.zig

Make argsAlloc/ArgIterator return zero-sentinel strings

---

src/Compilation.zig

cc: fix regression on macOS after adding libc headers

---

lib/std/crypto/blake3.zig

Gives a ~40% speedup on x86_64.
However, the generic code remains faster on aarch64.
This is still processing only one block at a time for now.
I'm pretty confident that processing more blocks per round will eventually give a substantial performance improvement on all platforms with vector units.

std/crypto: vectorize BLAKE3

---

lib/std/fmt.zig

Format null type in std.fmt

---

lib/std/crypto/blake2.zig
lib/std/crypto/gimli.zig
lib/std/crypto/hmac.zig

std/crypto: API cleanup

---

lib/std/crypto.zig
lib/std/crypto/chacha20.zig
lib/std/crypto/salsa20.zig

Also rename (salsa20|chacha20)Internal() to a better name.

PascalCase *box names, remove unneeded comptime & parenthesis

---

src/stage1/ir.cpp
test/stage1/behavior/type_info.zig

stage1: Correctly generated optional constant values

---

lib/std/crypto/salsa20.zig

20% faster on x86_64, slower on aarch64 as usual :/

std/crypto: vectorize Salsa20

---

src/stage1/ir.cpp
test/stage1/behavior.zig
test/stage1/behavior/bugs/6456.zig

stage1: Fix bug in internal string slicing

---

lib/std/event/loop.zig

This has been broken since 127fa80

std/event: fix poll error set handling 

---

lib/std/build.zig

This just adds a type to the build options.
Fixes #6797

make addBuildOption append type

---

lib/std/compress/deflate.zig
lib/std/compress/zlib.zig
lib/std/math.zig
lib/std/testing.zig

CC @leroycep, let me know if it works for you, thanks for discovering this (not-so) edge case I didn't take into account.
We lose a wee bit of speed but such is life :(

Fix zlib EOB condition

---

src/codegen.zig
src/codegen/arm.zig

In this PR, I'll try to remove some TODOs and maybe already support arithmetic instructions.
As with the last 2 PRs regarding the ARM backend, I opened this as a draft pull request so people can incrementally provide feedback.

stage2 ARM: more stuff

---

doc/langref.html.in
src/stage1/ir.cpp
test/compile_errors.zig

stage1: Error out when trying to execute `unreachable`

---

src/codegen/c.zig
src/translate_c.zig
test/gen_h.zig
test/stage2/zir.zig
test/translate_c.zig

translate-c: correctly handle pointers to opaque demoted structs

---

lib/std/os.zig
lib/std/os/bits/darwin.zig
lib/std/os/bits/dragonfly.zig
lib/std/os/bits/freebsd.zig
lib/std/os/bits/netbsd.zig
lib/std/os/bits/openbsd.zig
lib/std/os/test.zig

std: add {set,get}rlimit bits and improve test

---

lib/std/time.zig

std: Fix early overflow in time calculation

---

lib/std/fs.zig

Fix file descriptor leak in fs.openFileZ

---

lib/std/crypto/gimli.zig

(granted, this is a very lazy way to fix it)

Fix Gimli for big-endian targets

---

src/stage1/ir.cpp
test/stage1/behavior/math.zig

stage1: Fix *WithOverflow intrinsics with u0 values

---

lib/std/c.zig
lib/std/c/darwin.zig
lib/std/os.zig
lib/std/os/bits/darwin.zig
lib/std/os/bits/dragonfly.zig
lib/std/os/bits/freebsd.zig
lib/std/os/bits/linux.zig
lib/std/os/bits/linux/arm-eabi.zig
lib/std/os/bits/linux/arm64.zig
lib/std/os/bits/linux/i386.zig
lib/std/os/bits/linux/mips.zig
lib/std/os/bits/linux/powerpc64.zig
lib/std/os/bits/linux/riscv64.zig
lib/std/os/bits/linux/sparc64.zig
lib/std/os/bits/linux/x86_64.zig
lib/std/os/bits/netbsd.zig
lib/std/os/bits/openbsd.zig
lib/std/os/bits/wasi.zig
lib/std/os/linux.zig
lib/std/os/linux/sparc64.zig
lib/std/os/linux/test.zig

Check the commit messages for more info.

Decouple kernel and libc stat definitions

---

src/translate_c.zig
test/translate_c.zig

Translate-c: fix macro functions with no arguments

---

lib/std/fs/test.zig

std: Make file locking tests less fragile

---

src/codegen.zig

`armeb` (or other big-endian targets) don't work completely yet. This is a minor step in that direction.

stage2 ARM: miscellaneous improvements

---

build.zig

Bump Zig version to 0.7.0

---

lib/std/os/bits/openbsd.zig
lib/std/reset_event.zig
lib/std/thread.zig

I started to look to make the tests to pass on OpenBSD. These commits (I grouped them to avoid too many PR) should be simple enough to avoid controversal changes.

Simple sets of commits for OpenBSD support

---

doc/langref.html.in

Fix backticked code in langref

---

src/stage1/ir.cpp
test/compile_errors.zig

Ensure TypeInfo payload is not undefined

---

lib/std/hash_map.zig

std: fix HashMap.putAssumeCapacity

---

src/codegen.zig
src/codegen/aarch64.zig
src/type.zig
test/stage2/aarch64.zig
test/stage2/test.zig

The goal of this PR is getting "Hello World" working on the AArch64 (A64) backend for the stage2 zig compiler.
As always, I'll create this as a draft pull request so people can provide incremental feedback.
TODO:

Add stage2 AArch64 backend

---

lib/std/os/windows.zig

Make it behave like the read() wrapper for unix systems.
Reading the whole buffer breaks some use-cases like buffered readers
over sockets.
Closes #7121
Sadly the test suite doesn't run that well with the Wine version I have here, needs testing.
cc @Aransentin

std: Make windows.ReadFile allow short reads

---

src/codegen/aarch64.zig

stage2 aarch64: add NOP instruction

---

src/main.zig

fix issue #6798

---

src/stage1/codegen.cpp
test/stage1/behavior/async_fn.zig

Make the code used to calculate the variable slot index into the frame
match what's done during the structure layout calculation.
Prevents a few nasty LLVM errors when such types are passed around.

stage1: Fix asyncCall with non-abi-aligned arguments

---

src/codegen/aarch64.zig

stage2 aarch64: add PC relative address instructions

---

doc/langref.html.in
lib/std/meta.zig

the function signature changed
also update langref

std: make meta.IntType a compile error

---

CMakeLists.txt
lib/std/atomic.zig
lib/std/atomic/bool.zig
lib/std/atomic/int.zig

Followup to https://github.com/ziglang/zig/pull/6598

std.atomic.{Int,Bool}

---

lib/std/hash/murmur.zig

Change the seed value for Murmur2_64 from u32 to u64.

Change seed for Murmur2_64 from u32 to u64

---

lib/std/crypto/25519/edwards25519.zig

Just some trivial changes; no functional changes.
Skip useless null additions and multiplications and comptime the basepoint multiples only once.
(maybe worth getting in 0.7.1?)

edwards25519 - skip useless operations and duplicate lookup table

---

lib/std/builtin.zig
lib/std/fmt.zig
lib/std/io/serialization.zig
lib/std/json/write_stream.zig
lib/std/leb128.zig
lib/std/math.zig
lib/std/math/big.zig
lib/std/math/big/int.zig
lib/std/math/powi.zig
lib/std/meta.zig
lib/std/meta/trait.zig
lib/std/os.zig
lib/std/os/linux.zig
lib/std/packed_int_array.zig
lib/std/rand.zig
lib/std/start.zig
src/Module.zig
src/codegen.zig
src/link/Elf.zig
src/stage1/ir.cpp
src/type.zig
src/value.zig
src/zir.zig
test/compile_errors.zig
test/stage1/behavior/type.zig
test/stage1/behavior/type_info.zig

https://github.com/ziglang/zig/pull/6713#discussion_r506992541

Add builtin.Signedness, use it instead of is_signed

---

src/stage1/analyze.cpp
src/stage1/analyze.hpp
src/stage1/ir.cpp
test/stage1/behavior/type_info.zig

stage1: Resolve usingnamespace decls when calling @typeInfo

---

src/stage1/analyze.cpp

No test case because I couldn't reduce the huuuge test case.
Fixes the problem discovered by @ifreund.

stage1: Force union member types to be resolved

---

src/codegen.zig
test/stage2/arm.zig

The goal of this PR is to enable basic arithmetic calculations and comparisons.
As always, this will initially be a draft pull request.

stage2 ARM: add basic arithmetic instructions

---

src/Compilation.zig

Add packages to root module and stage1 cache hashes

---

lib/std/ascii.zig

* startsWithIgnoreCase
* endsWithIgnoreCase

std: Add a few helpers for matching ascii strings

---

src/main.zig

This PR removes the function `parseAnyBaseInt` and replaces calls to it with `std.fmt.parseUnsigned` with radix=0 which has identical logic. It also replaces calls to `std.fmt.parseInt` where the type is unsigned.

Utilize std.fmt.parseUnsigned in main.zig.

---

src/stage1/analyze.cpp
src/stage1/analyze.hpp
src/stage1/ir.cpp
test/compile_errors.zig

stage1: Validate the specified cc for lazy fn types

---

lib/std/testing.zig
src/Compilation.zig
src/link/Coff.zig
src/link/Elf.zig
src/link/MachO.zig
src/link/Wasm.zig
src/llvm.zig
src/main.zig
src/zig_llvm.cpp
src/zig_llvm.h
test/cli.zig

invoke LLD as a child process rather than a library

---

doc/langref.html.in
lib/std/math/exp2.zig
lib/std/special/compiler_rt/atomics.zig
lib/std/special/compiler_rt/clzsi2.zig
src/stage1/ir.cpp

Check out the commit message for more info.
Closes #7346

Some compiler-rt fixes

---

src/translate_c.zig
test/stage1/behavior/translate_c_macros.h
test/stage1/behavior/translate_c_macros.zig

Translate-c: support referencing C containers in macros

---

lib/std/fs/path.zig

Implements a function that returns the file extension for a given path

Implements std.fs.path.extension

---

lib/std/fmt.zig

std: Fix formatting of type values

---

lib/std/c.zig
lib/std/debug.zig
lib/std/os.zig
lib/std/os/bits/darwin.zig
lib/std/os/bits/dragonfly.zig
lib/std/os/bits/freebsd.zig
lib/std/os/bits/linux.zig
lib/std/os/bits/netbsd.zig
lib/std/os/bits/openbsd.zig
lib/std/os/linux.zig
lib/std/os/test.zig

Add a smoke test to prevent regressions.

std: Improve sigaction interface

---

src/translate_c.zig
test/run_translated_c.zig

Translate-c: detect parenthesized string literals

---

lib/std/math.zig

Fix typo in math.order

---

doc/langref.html.in

Improve documentation for string slices.

---

src/stage1/ir.cpp
test/compile_errors.zig

Add missing error check on inferred struct field ptr

---

lib/std/fs/file.zig
lib/std/os.zig

Is this the right approach...?
Fix #7474.

cast sendto to SendError inside send

---

src/Module.zig
src/astgen.zig
src/zir.zig
src/zir_sema.zig
test/stage2/test.zig

I also filled in the `nodeMayNeedMemoryLocation` for builtins, so that I can assign to comptime variables with builtins like `@TypeOf` for testing. I just used the builtins on the website, but I don't know if I got all of them right, so please tell me. I marked some with TODO that I was especially unsure on. I also added type comparison `u32 == u32` for testing purposes. Other than that, this was pretty straightforward.

stage2: @TypeOf

---

lib/std/crypto/gimli.zig

Using the test vectors from the NIST submission, I found that running hashes on messages that were _16n_ bytes weren't matching the expected test data. Also compared with the [reference C code (zip)](https://csrc.nist.gov/CSRC/media/Projects/lightweight-cryptography/documents/round-2/submissions-rnd2/gimli.zip).

Fix Gimli hash on 16n byte inputs

---

lib/std/debug.zig
lib/std/os/bits/freebsd.zig

Enable segfault handling on FreeBSD

---

src/codegen.zig
src/ir.zig
src/zir.zig
src/zir_sema.zig
test/stage2/arm.zig

A small intermezzo while I'm working on conditional branching in the stage2 ARM backend.
TODO in this PR:

stage2 ARM: implement basic binary bitwise operations

---

lib/std/base64.zig
lib/std/build/write_file.zig
lib/std/fs.zig
lib/std/testing.zig

Return encoded slice from base64 encode
